/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojcollapsible"],function(a,f){(function(){a.La("oj.ojAccordion",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{multiple:!1,expanded:null,beforeExpand:null,expand:null,beforeCollapse:null,collapse:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-accordion oj-component").attr("role","group");this.Yb()},_OpenContextMenu:function(a,b){a.open(b,{launcher:this.element.find(".oj-collapsible-header-icon").first(),initialFocus:"menu"})},
_destroy:function(){this.element.removeClass("oj-accordion oj-component").removeAttr("role");this.element.children().removeClass("oj-accordion-collapsible");this.element.children(".oj-accordion-created").removeClass("oj-accordion-created").ojCollapsible("destroy")},_setOption:function(a,b,d){"multiple"===a?!1==b&&!0==this.options.multiple&&this.element.children(".oj-expanded").first().siblings(".oj-collapsible").ojCollapsible("collapse",!1):"expanded"===a&&this.OT(b);this._super(a,b,d)},refresh:function(){this._super();
this.Yb()},Yb:function(){this.TR();this._setOption("disabled",this.options.disabled);this._setOption("expanded",this.options.expanded);this.Lj()},TR:function(){this.element.children(":oj-collapsible").each(function(){f(this).ojCollapsible("option","expandArea","header")});this.xi=this.element.children().not(":oj-ojCollapsible").ojCollapsible({expandArea:"header"}).addClass("oj-accordion-created").end().addClass("oj-accordion-collapsible")},Lj:function(){var a={keydown:this.Ej,ojbeforeexpand:this.UM,
ojexpand:this.HO,ojbeforecollapse:this.SM,ojcollapse:this.sN};this._off(this.xi);this._on(this.xi,a)},Ej:function(a){if(!a.altKey&&!a.ctrlKey&&(f(a.target).hasClass("oj-collapsible-header")||f(a.target).hasClass("oj-collapsible-header-icon"))){var b=f.ui.keyCode,d=this.xi.not(".oj-disabled"),e=d.length,g=f(a.target).closest(".oj-collapsible"),h=d.index(g),k=!1;if(0<=h)switch(a.keyCode){case b.RIGHT:case b.DOWN:k=d[(h+1)%e];break;case b.LEFT:case b.UP:k=d[(h-1+e)%e];break;case b.HOME:k=d[0];break;
case b.END:k=d[e-1]}k&&(g&&f(g).trigger("ojfocusout"),f(k).trigger("ojfocus"),a.preventDefault())}},jC:function(a){return!this.options.multiple&&(a=f(a.target).closest(".oj-collapsible"),a.parent().is(":oj-ojAccordion"))?a.siblings(".oj-collapsible.oj-expanded").map(function(){return f(this).data("oj-ojCollapsible")}):f()},UM:function(a){if(!this.fr(a))return!0;var b,d=this,e;this.jC(a).each(function(){var g=this.element;e=d.Xk(g,f(a.target));g={header:g.find(".oj-collapsible-header"),content:g.find(".oj-collapsible-content")};
return b=this._trigger("beforeCollapse",a,g)});e||(e=d.Xk(null,f(a.target)));this.options.multiple||this._trigger("beforeExpand",a,e);return b},HO:function(a,b){if(this.fr(a)){var d,e=this;this.jC(a).each(function(){this.collapse(!1,a,b);d=e.Xk(this.element,f(a.target))});d||(d=e.Xk(null,f(a.target)));this.options.multiple||this._trigger("expand",a,d);this.jx()}},SM:function(a,b){return this.fr(a)&&!this.options.multiple?this._trigger("beforeCollapse",a,this.xD(a,b)):!0},sN:function(a,b){if(this.fr(a)){var d=
this.xD(a,b);this.options.multiple||this._trigger("collapse",a,d);this.jx()}},Xk:function(a,b){return{fromCollapsible:a,toCollapsible:b}},xD:function(a,b){var d;if(b.toCollapsible)d=b;else{if(a.originalEvent&&a.originalEvent.target){var e=f(a.originalEvent.target);e.hasClass("oj-collapsible")&&(d=this.Xk(f(a.target),e))}d||(d=this.Xk(f(a.target),null))}return d},fr:function(a){return f(a.target).is(this.xi)},jx:function(){var a,b=[];this.xi.each(function(d){f(this).ojCollapsible("option","expanded")&&
(a=f(this).attr("id"),b.push(a?a:d))});this.options.expanded=b},fY:function(a,b,d){void 0===d&&(d=b.index());d=a.indexOf(d);return-1!=d?d:a.indexOf(b.attr("id"))},OT:function(a){var b={};this.xi.each(function(a){var c=f(this).attr("id");c&&(b[c]=a)});var d=[];if(Array.isArray(a))for(var e,g=0;g<a.length;g++)e=a[g],"string"===typeof e?void 0!==b[e]&&(d[b[e]]=!0):"number"===typeof e&&(d[e]=!0);for(g=0;g<d.length;g++)f(this.xi[g]).ojCollapsible("option","expanded",!!d[g]);this.jx()},getNodeBySubId:function(a){if(null==
a)return this.element?this.element[0]:null;var b=a.subId;a=this.xi[a.index];switch(b){case "oj-accordion-content":b="oj-collapsible-content";break;case "oj-accordion-header":b="oj-collapsible-header";break;case "oj-accordion-header-icon":b="oj-collapsible-header-icon";break;case "oj-accordion-collapsible":return a;default:return null}return f(a).ojCollapsible("getNodeBySubId",{ZY:b})}})})()});
//# sourceMappingURL=oj-modular.map