/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function c(a,b){var c=a.name,d=a.form;c?(c=c.replace(/'/g,"\\'"),c=":radio[name\x3d'"+c+"']:oj-button",d=b?b.filter(c):d?f(d).find(c):f(c,a.ownerDocument).filter(function(){return!this.form})):d=(b?b.filter(a):f(a)).filter(":oj-button");return d}a.La("oj.ojButton",f.oj.baseComponent,{defaultElement:"\x3cbutton\x3e",widgetEventPrefix:"oj",options:{disabled:null,display:"all",label:null,icons:{start:void 0,end:void 0},menu:null},
_create:function(){this.element.closest("form").unbind("reset"+e).bind("reset"+e,function(){var a=f(this);setTimeout(function(){a.find(":oj-button").each(function(){f(this).data("oj-ojButton").Pp(!1)}).length||a.unbind("reset"+e)},1)});"boolean"!==typeof this.options.disabled&&(this.options.disabled=!!this.element.prop("disabled"));this.Tl=this.eventNamespace+"menu";this.XQ();this.Wx=!!this.qb.attr("title");var a=this,c=this.options,h="checkbox"===this.type||"radio"===this.type,k=h?"":"oj-active";
this.qb.addClass(g);this.lc.bind("mouseenter"+this.eventNamespace,function(){a.hd()||(this===b&&a.qb.addClass("oj-active"),a.qb.addClass("oj-hover").removeClass("oj-default oj-focus-only"))}).bind("mouseleave"+this.eventNamespace,function(){a.qb.removeClass("oj-hover");a.hd()||(a.qb.removeClass(k),a.Lf())}).bind("click"+this.eventNamespace,function(b){a.hd()&&(b.preventDefault(),b.stopImmediatePropagation())});this.element.attr("role","button").bind("focus"+this.eventNamespace,function(){a.qb.addClass("oj-focus");
a.Lf()}).bind("blur"+this.eventNamespace,function(){a.qb.removeClass("oj-focus");a.Lf()});h&&(this.element.bind("change"+this.eventNamespace,function(b){a.Pp(!0);var c=f(this).closest(":oj-buttonset").data("oj-ojButtonset"),d=c&&c.Vu(c.Zc);c&&void 0!==d&&(c.FE=b,c._setOption("checked",d))}),this.lc.bind("mousedown"+this.eventNamespace,function(){a.hd()||(d=this,a.document.one("mouseup",function(){d=null}))}).bind("mouseup"+this.eventNamespace,function(){a.hd()||this!==d||a.element.focus()}));"checkbox"===
this.type?(this.lc.bind("click"+this.eventNamespace,function(){if(a.hd())return!1}),this.element.bind("keyup"+this.eventNamespace,function(b){b.keyCode===f.ui.keyCode.ENTER&&(a.hd()||a.element.click())})):"radio"===this.type?(this.lc.bind("click"+this.eventNamespace,function(){if(a.hd())return!1}),this.element.bind("keyup"+this.eventNamespace,function(b){b.keyCode!==f.ui.keyCode.ENTER||a.element[0].checked||a.hd()||(a.element[0].checked=!0,a.element.change(),a.element.click())})):(this.lc.bind("mousedown"+
this.eventNamespace,function(c){if(a.hd())return!1;1===c.which&&(f(this).addClass("oj-active").removeClass("oj-default oj-focus-only"),b=this,a.document.one("mouseup",function(){b=null}))}).bind("mouseup"+this.eventNamespace,function(){if(a.hd())return!1;f(this).removeClass("oj-active");a.Lf()}).bind("keydown"+this.eventNamespace,function(b){if(a.hd())return!1;b.keyCode!==f.ui.keyCode.SPACE&&b.keyCode!==f.ui.keyCode.ENTER||f(this).addClass("oj-active").removeClass("oj-default oj-focus-only")}).bind("keyup"+
this.eventNamespace+" blur"+this.eventNamespace,function(){f(this).removeClass("oj-active");a.Lf()}),this.lc.is("a")&&(h=this.lc.attr("tabindex"),("undefined"===h||null===h||isNaN(h))&&this.lc.attr("tabindex","0"),this.lc.bind("keyup"+this.eventNamespace,function(a){a.keyCode===f.ui.keyCode.SPACE&&f(this).click()})));this._setOption("disabled",c.disabled);this.CQ();this.YB();this.Lf();this._super()},XQ:function(){var a;if(this.element.is("input[type\x3dcheckbox]"))this.type="checkbox";else if(this.element.is("input[type\x3dradio]"))this.type=
"radio";else if(this.element.is("input[type\x3dbutton],input[type\x3dsubmit],input[type\x3dreset]"))this.type="input";else if(this.element.is("button,a"))this.type="button";else throw Error("JET Button not supported on this element type");"checkbox"===this.type||"radio"===this.type?(a="label[for\x3d'"+this.element.attr("id")+"']",this.lc=this.element.siblings().filter(a).addClass("oj-button-label"),this.element.addClass("oj-helper-hidden-accessible").add(this.lc).wrapAll("\x3cspan\x3e\x3c/span\x3e"),
this.qb=this.element.parent(),(a=this.element[0].checked)&&this.qb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),this.element.attr("aria-pressed",a)):this.qb=this.lc=this.element},widget:function(){return this.qb},_destroy:function(){this.wF();this.element.removeClass("oj-helper-hidden-accessible").removeAttr("role").removeAttr("aria-pressed");var a="checkbox"===this.type||"radio"===this.type;a||this.qb.removeClass(g+" "+h+" "+k);this.lc.html(this.lc.find(".oj-button-text").html());
if(a){this.lc.removeClass("oj-button-label");var b=this;setTimeout(function(){b.qb.parent().length&&b.element.unwrap()},0)}else this.Wx||this.qb.removeAttr("title");d===this.lc[0]&&(d=null)},Xz:function(){this.qb.removeClass("oj-active oj-hover oj-focus");this.Lf()},Fm:function(a){this._super(a);this.RG()},RG:function(){var a=this.hd();this.qb.toggleClass("oj-disabled",a);this.qb.toggleClass("oj-enabled",!a);this.element.is("a")?this.qb.attr("aria-disabled",a):(this.element.prop("disabled",a),this.qb.removeAttr("aria-disabled"));
a?(this.widget().removeClass("oj-active oj-default oj-focus-only oj-hover oj-focus"),b=null,this.Fu()):this.Lf()},_setOption:function(a,b,c){this._super(a,b,c);switch(a){case "disabled":this.RG();break;case "label":this.UT();break;case "display":"input"!==this.type&&this.Hr();break;case "icons":this.QT(!0);break;case "menu":this.YB()}},refresh:function(){this._super();this.IA&&!f(this).closest(":oj-buttonset").length&&this.Fm(!1)},Pp:function(a){"radio"===this.type?(a?c(this.element[0]):this.element).each(function(){var a=
f(this).data("oj-ojButton");this.checked?(a.qb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),a.element.attr("aria-pressed","true")):(a.qb.removeClass("oj-selected"),a.Lf(),a.element.attr("aria-pressed","false"))}):"checkbox"===this.type&&(this.element[0].checked?(this.qb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),this.element.attr("aria-pressed","true")):(this.qb.removeClass("oj-selected"),this.Lf(),this.element.attr("aria-pressed","false")))},CQ:function(){var a=
!1;null===this.options.label&&(a=!0,this.options.label="input"===this.type?this.lc.val():this.lc.html());if("input"===this.type)this.bG();else{a=this.ST(a);void 0===this.options.icons.end&&(this.options.icons.end=this.options.menu?"oj-component-icon oj-button-menu-dropdown-icon":null);var b=this.Ir(!0),c=this.Ir(!1);this.Hr(a,b,c)}},ST:function(a){var b=this.lc,c=f("\x3cspan class\x3d'oj-button-text'\x3e\x3c/span\x3e",this.document[0]);a?c.append(b.contents()):(b.empty(),c.text(this.options.label));
b.append(c);return c},UT:function(){if("input"===this.type)this.bG();else{var a=this.lc.find(".oj-button-text");a.text(this.options.label);this.Hr(a)}},bG:function(){this.options.label&&this.element.val(this.options.label)},QT:function(){if("input"!==this.type){var a=this.Ir(!0),b=this.Ir(!1);this.Hr(void 0,a,b)}},Ir:function(a){if(a){var b=".oj-button-icon.oj-start";a="oj-button-icon oj-start";var c=this.options.icons.start,d="_lastStartIcon",e="prependTo"}else b=".oj-button-icon.oj-end",a="oj-button-icon oj-end",
c=this.options.icons.end,d="_lastEndIcon",e="appendTo";b=this.lc.find(b);c?(b.length?b.removeClass(this[d]):b=f("\x3cspan\x3e\x3c/span\x3e").addClass(a)[e](this.lc),b.addClass(c)):b.remove();this[d]=c;return!!c},Hr:function(a,b,c){void 0===a&&(a=this.lc.find(".oj-button-text"));void 0===b&&(b=!!this.options.icons.start);void 0===c&&(c=!!this.options.icons.end);var d=b&&c;c=b||c;var e="icons"===this.options.display;c&&e?(a.addClass("oj-helper-hidden-accessible"),this.Wx||(a=a.text(),this.qb.attr("title",
f.trim(a)))):(a.removeClass("oj-helper-hidden-accessible"),this.Wx||this.qb.removeAttr("title"));b=c?e?d?"oj-button-icons-only":"oj-button-icon-only":d?"oj-button-text-icons":b?"oj-button-text-icon-start":"oj-button-text-icon-end":"oj-button-text-only";this.qb.removeClass(k).addClass(b)},YB:function(){if(this.options.menu&&this.element.is("input"))throw Error("Menu Button functionality is not supported on input elements.");this.wF();if(this.options.menu){var a=this;this.element.attr("aria-haspopup",
!0).on("keydown"+this.Tl,function(b){return b.which===f.ui.keyCode.DOWN?(a.oG(b,"firstItem"),!1):b.which===f.ui.keyCode.ESCAPE?(a.Fu(b),!1):!0}).on("click"+this.Tl,function(b){var c=a.MC();c.Ip||a.oG(b,"firstItem");return c.Ip=!1})}},vO:function(a){this.Ya=a;var b=this;a.widget().on("oj__dismiss"+this.Tl,function(a){b.nE(a)}).on("ojbeforeopen"+this.Tl,function(a){b.$D||b.nE(a);b.$D=!1})},wF:function(){this.element.removeAttr("aria-haspopup").off(this.Tl);this.Fu();this.Ya&&this.Ya.widget().off(this.Tl);
this.Ya=void 0},MC:function(){var b=this.Ya;b||((b=f(this.options.menu).data("oj-ojMenu"))?this.vO(b):this.options.menu&&a.C.warn('JET Button: "menu" option specified, but does not reference a valid JET Menu.'));return b},oG:function(a,b){if(!this.hd()){var c=this.MC();c&&(this.qb.addClass("oj-selected").removeClass("oj-default oj-focus-only"),this.$D=!0,c.open(a,{launcher:this.element,initialFocus:b}),this.oE=!0)}},Fu:function(a){this.oE&&(this.Ya.Jt(a,!0),this.Ya.Hp(a))},nE:function(){"button"===
this.type&&(this.qb.removeClass("oj-selected"),this.Lf());this.oE=!1},Lf:function(){var a,b;this.qb.is(".oj-hover, .oj-active, .oj-selected, .oj-disabled")?b=a=!1:(b=this.qb.is(".oj-focus"),a=!b);this.qb.toggleClass("oj-default",a);this.qb.toggleClass("oj-focus-only",b)}});a.La("oj.ojButtonset",f.oj.baseComponent,{FR:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",options:{checked:void 0,focusManagement:"oneTabstop",
optionChange:null},VF:function(a,b){var c=f.type(a);if("string"===c||"null"===c)return(c=((c=b[0].name)||1>=b.length)&&b.filter("input[type\x3dradio][name\x3d"+c+"]").length===b.length&&(null===a||b.filter("[value\x3d"+a+"]").length))&&b.each(function(){this.checked=this.value===a}),c;if("array"===c){var c=b.filter("input[type\x3dcheckbox]").length===b.length,d;(c=c&&a.concat().sort().every(function(a){var c=a!==d&&b.filter("[value\x3d"+a+"]").length;d=a;return c}))&&b.each(function(){this.checked=
-1<a.indexOf(this.value)});return c}return!1},Vu:function(a){var b=void 0,c=null,d=null;a.each(function(){if("input"!==this.tagName.toLowerCase())return b=void 0,!1;var a=this.type.toLowerCase(),e;if("radio"===a)a=!0,e=this.name.toLowerCase();else if("checkbox"===a)a=!1,e=null;else return b=void 0,!1;if(void 0!==b&&(a!==c||e!==d||c&&!d))return b=void 0,!1;void 0===b?(b=a?this.checked?this.value:null:this.checked?[this.value]:[],c=a,d=e):this.checked&&(c?b=this.value:b.push(this.value))});return b},
hN:function(a,b){return a===b?!0:"array"===f.type(a)&&"array"===f.type(b)&&!f(a).not(b).length&&!f(b).not(a).length},_create:function(){this.element.addClass("oj-buttonset oj-component");"oneTabstop"===this.options.focusManagement&&this.element.attr("role","toolbar");this.ub(!0);this._super()},_OpenContextMenu:function(a,b){a.open(b,{launcher:this.element.find(":oj-button[tabindex\x3d0]"),initialFocus:"menu"})},XE:function(a){a=!!a;this.Zc.each(function(){f(this).data("oj-ojButton").Fm(a)})},_setOption:function(a,
b){var c=!1,d=this.FE;this.FE=null;"disabled"===a&&this.XE(b);"checked"!==a||d||null===b&&void 0===this.Vu(this.Zc)||(this.VF(b,this.Zc)?this.Zc.each(function(){f(this).data("oj-ojButton").Pp(!1)}):c=!0);c||(c=this.options[a],this._superApply(arguments),"checked"===a&&this.Cc(a,c,b,this.hN,d))},Cc:function(a,b,c,d,e){d.call(this,b,c)||this._trigger("optionChange",e,{option:a,previousValue:b,value:c,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}})},refresh:function(){this._super();this.ub(!1)},
ub:function(a){var b=this;this.Eg="rtl"===this.Ic();this.Zc=this.element.find(this.FR);if(a&&!this.VF(this.options.checked,this.Zc)){var c=this.Vu(this.Zc);this.options.checked=void 0===c?null:c}this.Zc.filter(":oj-button").ojButton("refresh").each(function(){f(this).data("oj-ojButton").Pp(!1)}).end().not(":oj-button").ojButton().end().map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-corner-start oj-buttonset-corner-end").filter(":first").addClass("oj-buttonset-corner-start").end().filter(":last").addClass("oj-buttonset-corner-end").end().end();
this.XE(this.options.disabled);"oneTabstop"===this.options.focusManagement&&(this.Zc.unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.Nv(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).data("oj-ojButton").hd()||b.Kj(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Kj(f(this))}),this.Qg=this.Zc.filter(function(){return!f(this).data("oj-ojButton").hd()}),this.Wv(a))},
Wv:function(a){var b=f(this.Fj);this.Fj=void 0;this.Zc.attr("tabindex","-1");a=a||!b.is(this.Qg)?this.Qg.first():b;this.Kj(a)},iw:function(a){var b=this.Qg;return a.map(function(a,d){if("radio"!=d.type||d.checked||""==d.name)return d;var e=c(d,b).filter(":checked");return e.length?e[0]:d})},Kj:function(a){a=this.iw(a);var b=a[0],c=this.Fj;b!==c&&(f(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.Fj=b)},Nv:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();
var c=this.Qg,d=c.length;if(2>d)break;var e=c.index(b);c.eq((e+(a.which==f.ui.keyCode.RIGHT^this.Eg?1:-1)+d)%d).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-buttonset oj-component").removeAttr("role");"oneTabstop"===this.options.focusManagement&&this.Zc.attr("tabindex","0");this.Zc.map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-corner-start oj-buttonset-corner-end").end().ojButton("destroy")}});
var b,d,e=".ojButton",g="oj-button oj-component oj-enabled oj-default",h="oj-hover oj-active oj-selected",k="oj-button-icons-only oj-button-icon-only oj-button-text-icons oj-button-text-icon-start oj-button-text-icon-end oj-button-text-only"})()});
//# sourceMappingURL=oj-modular.map