/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(a,f){a.La("oj.ojCheckboxset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:null},refresh:function(){this._super();this.Wf.each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.Wf=this.tq().filter(".oj-checkbox")._ojRadioCheckbox("refresh").end().not(".oj-checkbox")._ojRadioCheckbox().end();
this.ub()},widget:function(){return this.xJ},_InitOptions:function(c,b){var d,e=[];this._super(c,b);a.ud.Ji([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0}],b,this);null==this.options.value&&(d=this.tq(),d=d.filter(":checked"),0===d.length?d=[]:(d.each(function(){e.push(f(this).val())}),d=e),this.options.value=d)},
_ComponentCreate:function(){this._super();if(this.element.is("fieldset"))throw Error("ojCheckboxset cannot be bound to a fieldset. Use a div instead.");this.Wf=this.tq()._ojRadioCheckbox();this.xJ=this.element.addClass("oj-checkboxset oj-component").attr("role","group");this._on(this.If);this.ub()},tq:function(){var c=this.element.find("input[type\x3dcheckbox]:first");0===c.length&&a.C.warn("Could not find any input type\x3dcheckbox within this element");c=c.attr("name");return void 0===c?this.element.find("input[type\x3dcheckbox]").not("[name]"):
this.element.find("input[type\x3dcheckbox][name\x3d"+c+"]")},_OpenContextMenu:function(a,b){var d=this.element.find("input[type\x3dcheckbox]:tabbable").first();a.open(b,{launcher:d,initialFocus:"menu"})},ub:function(){this.options.disabled?this.disable():!1===this.options.disabled&&this.enable()},If:{change:function(a){this.tp(a)}},tp:function(a){this._super(a)},Yg:function(){return this.sk()},hg:function(a){this.Wf._ojRadioCheckbox("option","checked",!1);if(null!=a)for(var b=0;b<a.length;b++){var d=
this.Wf.filter("[value\x3d'"+a[b]+"']");void 0!==d&&0<d.length&&(d.prop("checked")||d._ojRadioCheckbox("option","checked",!0))}},sk:function(){var a=[],b=this.Wf.filter(":checked");if(0===b.length)return[];b.each(function(){a.push(f(this).val())});return a},_GetDefaultStyleClass:function(){return"oj-checkboxset"},Cf:function(){return this.tq()},At:function(a){var b=this.xJ;(a=a?!0:!1)&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},_setOption:function(a,b,d){this._super(a,b,d);"disabled"===
a&&(this.Wf.each(function(){f(this).data("oj-_ojRadioCheckbox").Fm(b)}),this.Wf._ojRadioCheckbox("refresh"))},getNodeBySubId:function(a){var b=this._super(a);return b||(a=a.subId,"oj-checkboxset-inputs"!==a)?b||null:this.Wf},_destroy:function(){this._super();this.element.removeClass("oj-checkboxset oj-enabled oj-component").removeAttr("role");this.Wf&&this.Wf._ojRadioCheckbox("destroy")}})});
//# sourceMappingURL=oj-modular.map