/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","jqueryui","ojs/ojmessaging"],function(a,f){function c(a,b){f(a).find("."+l).each(function(a,c){var d=f(c),e=d.data(k);if(null!=e)for(var g=0;g<e.length;g++){var l=d.data("oj-"+e[g]);null!=l&&b(l)}})}function b(a){this.TV=function(){return a}}function d(a,b,c,d,g,l,f){var h=c,m=!1,k={};delete d[g];Object.defineProperty(d,g,{get:function(){if(m||null!=a.pl)return h;var c=l(f?f():g);return e([b,c,h],k)},set:function(b){h=b;null!=a.pl?k[a.pl]=!0:m=!0},enumerable:!0})}function e(a,
b){for(var c=void 0,d=0;d<a.length;d++){var e=a[d];void 0!==e&&(c=f.isPlainObject(e)?g(f.isPlainObject(c)?[c,e]:[e],d==a.length-1?null:b,null):e)}return c}function g(a,b,c){for(var d={},e=a.length,l=0;l<e;l++)for(var h=a[l],m=Object.keys(h),k=0;k<m.length;k++){var n=m[k],q=null==b?null:null==c?n:c+"."+n;if(null==b||!b[q]){var N=h[n];void 0!==N&&(d[n]=f.isPlainObject(N)?g(f.isPlainObject(d[n])?[d[n],N]:[N],b,q):N)}}return d}function h(){return!0}a.Components={};o_("Components",a.Components,a);a.Components.Ey=
function(b){a.Components.NB=f.widget.extend(a.Components.NB||{},b)};o_("Components.setDefaultOptions",a.Components.Ey,a);a.Components.SH=function(){return a.Components.NB||{}};o_("Components.getDefaultOptions",a.Components.SH,a);a.Components.Vj=function(a){return new b(a)};o_("Components.createDynamicPropertyGetter",a.Components.Vj,a);a.Components.ws=function(a,b){var c=f(a);if(null==b){var d=c.data(k);d&&(b=d[0])}return null!=b&&(d=c[b],"function"===typeof d)?d.bind(c):null};o_("Components.getWidgetConstructor",
a.Components.ws,a);a.Components.oX=function(b){a.da.GH(b);c(b,function(a){a.tL()})};o_("Components.subtreeAttached",a.Components.oX,a);a.Components.pX=function(a){c(a,function(a){a.Xz()})};o_("Components.subtreeDetached",a.Components.pX,a);a.Components.sJ=function(b){a.da.GH(b);c(b,function(){})};o_("Components.subtreeShown",a.Components.sJ,a);a.Components.rJ=function(a){c(a,function(){})};o_("Components.subtreeHidden",a.Components.rJ,a);a.Components.Cp="data-oj-container";var k="oj-component-names",
l="oj-component-initnode";f.widget("oj.baseComponent",{options:{contextMenu:null,rootAttributes:void 0},refresh:function(){this.Nn=null},_createWidget:function(a,b){this.GE=this.options||{};this.sB=a||{};this._super(a,b)},WL:function(){var a=this.options.rootAttributes;if(a){var b=this.widget();if(null!=b){var c=a["class"];c&&b.addClass(c);if(c=a.style){var d=b.attr("style");d?b.attr("style",d+";"+c):b.attr("style",c)}a=f.extend({},a);delete a["class"];delete a.style;b.attr(a);delete a.id;a=Object.keys(a);
if(a.length)throw Error("Unsupported values passed to rootAttributes option: "+a.toString());}}},_create:function(){this.mA(this.element);this._InitOptions(this.GE,this.sB);delete this.GE;delete this.sB;this._ComponentCreate();this.Rh()},_InitOptions:function(a,b){this.hU(a,b)},_ComponentCreate:function(){this.activeable=f();this.element.addClass(l);var a=this.element,b=this.widgetName,c=a.data(k);c||(c=[],a.data(k,c));0>c.indexOf(b)&&c.push(b)},Rh:function(){this.WL();this.zx=this.eventNamespace+
"contextMenu";this.iG()},mA:function(a){var b=this;this.Mw=[];f.each(a,function(a,c){var d={},e=c.attributes;b.Mw.push({element:c,attributes:d});f.each(e,function(a,b){var e=b.name;d[e]={attr:b.value,prop:f(c).prop(e)}})})},ot:function(a){var b=this.Mw;a=a[0];for(var c=0,d=b.length;c<d;c++){var e=b[c];if(e.element===a)return e.attributes}return{}},SL:function(){f.each(this.Mw,function(a,b){var c=f(b.element),d=b.attributes;if(1===c.length){for(var e=b.element.attributes,g=[],l=0,h=e.length;l<h;l++)e[l].name in
d||g.push(e[l].name);l=0;for(h=g.length;l<h;l++)c.removeAttr(g[l]);for(var m in d)c.attr(m,d[m].attr)}})},rp:function(){return this.widgetFullName},J:function(b,c){var d={},e;2<arguments.length?d=Array.prototype.slice.call(arguments,1):2==arguments.length&&(d=arguments[1],"object"===typeof d||d instanceof Array||(d=[d]));e=this.option(n+b);return null==e?b:a.ea.pb(e.toString(),d)},getNodeBySubId:function(a){return null==a||null==a.subId?this.element?this.element[0]:null:null},getSubIdByNode:function(){return null},
destroy:function(){this.NG();this._super();this.element.removeClass(l);this.widget().removeClass("oj-disabled");this.hoverable.removeClass("oj-hover");this.focusable.removeClass("oj-focus");this.activeable.removeClass("oj-active");var a=this.element,b=this.widgetName,c=a.data(k);c&&(b=c.indexOf(b),0<=b&&(c.splice(b,1),0===c.length&&a.removeData(k)))},option:function(a,b){if(0===arguments.length)return f.widget.extend({},this.options);var c=arguments[0],d=c,e=null,g={};if("string"===typeof c){var d=
{},l=c.split("."),c=l.shift();if(l.length){var e=l.join("."),h;try{1<arguments.length&&(this.pl=e),h=d[c]=f.widget.extend({},this.options[c])}finally{this.pl=null}for(c=0;c<l.length-1;c++)h[l[c]]=h[l[c]]||{},h=h[l[c]];c=l.pop();if(1===arguments.length)return void 0===h[c]?null:h[c];h[c]=b}else{if(1===arguments.length)return void 0===this.options[c]?null:this.options[c];d[c]=b}g=arguments[2]||g}else g=arguments[1]||g;null!=e&&(g=f.widget.extend({},g,{subkey:e}));this._setOptions(d,g);return this},
_setOptions:function(a,b){for(var c in a)this._setOption(c,a[c],b);return this},_setOption:function(a,b,c){if("disabled"===a)this.options[a]=b,this.widget().toggleClass("oj-disabled",!!b).attr("aria-disabled",b),b&&(this.hoverable.removeClass("oj-hover"),this.focusable.removeClass("oj-focus"),this.activeable||(this.activeable=f()),this.activeable.removeClass("oj-active"));else{try{var d=null==c?null:c.subkey;null!=d&&(this.pl=d);this._super(a,b)}finally{this.pl=null}"contextMenu"===a&&this.iG()}return this},
_trigger:function(a,b,c){var d=this.options[a];c=c||{};b=f.Event(b,q);b.type=(this.widgetEventPrefix+a).toLowerCase();b.target=this.element[0];this.element.trigger(b,c);return!(f.isFunction(d)&&!1===d.apply(this.element[0],[b].concat(c))||b.isDefaultPrevented())},iG:function(){this.NG();var a=this.options.contextMenu;a||(a=this.element.attr("contextmenu"))&&(a="#"+a);var b,c;a&&(b=f(a),c=b.data("oj-ojMenu"));if(c){var d=this;(a=this.widget())&&a.on("keydown"+this.zx+" contextmenu"+this.zx,function(a){if("contextmenu"===
a.type||121==a.which&&a.shiftKey)d._OpenContextMenu(c,a),b.is(":visible")&&a.preventDefault();return!0})}},NG:function(){var a=this.widget();a&&a.off(this.zx)},_OpenContextMenu:function(a,b){a.open(b,{launcher:this.element,initialFocus:"menu"})},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){f(a.currentTarget).removeClass("oj-hover")}})},_focusable:function(a){this.focusable=this.focusable.add(a);
this._on(a,{focusin:function(a){f(a.currentTarget).addClass("oj-focus")},focusout:function(a){f(a.currentTarget).removeClass("oj-focus")}})},Lp:function(a){this.activeable=this.activeable.add(a);this._on(a,{mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")}})},Kc:function(a){return this.option(n+a)},Ic:function(){var a=document.documentElement.getAttribute("dir");a&&(a=a.toLowerCase());return"rtl"===a?"rtl":"ltr"},tL:function(){this.Nn=
null},Xz:function(){this.Nn=null},KX:function(){},JX:function(){},hd:function(){return this.options.disabled||this.IA?!0:!1},Fm:function(a){this.IA=a},aQ:function(){var b=[],c=this,d=0;this.LG(function(e){e=0==d?c.rp():e.widgetFullName;d++;var g=a.ea.qs(e);null==g||f.isEmptyObject(g)||b.push(e)});var e=b.length;return 0<e?function(){if(1==e)return a.ea.qs(b[0]);for(var c={},d=e-1;0<=d;d--)f.widget.extend(c,a.ea.qs(b[d]));return c}:null},mP:function(){if(!this.Nn){var b={};this.Nn=b;for(var c=this.element[0],
d=[];c;){var e=c.getAttribute,e=e?e.call(c,a.Components.Cp):null;null!=e&&d.push(e);c=c.parentNode}b.containers=d}return this.Nn},hU:function(a,b){var c=this.options,e=this.aQ(),g=b[m];null==e||void 0!==g&&!f.isPlainObject(g)||d(this,void 0,b[m],c,m,e);this.LR(a,b)},LR:function(c,g){var l=this.options,h={},m=[];this.LG(function(a){m.push(a.widgetName)});var k=a.Components.SH();m.push("default");for(var n=m.length-1;0<=n;n--){var q=k[m[n]];void 0!==q&&(h=f.widget.extend(h,q))}if(!f.isEmptyObject(h)){var w=
this,k=function(){return w.mP()},B;for(B in h)if(n=g[B],void 0===n||f.isPlainObject(n))q=h[B],null!=q&&q instanceof b?(q=q.TV(),f.isFunction(q)?d(this,c[B],n,l,B,q,k):a.C.error("Dynamic getter for property %s is not a function",B)):l[B]=e([c[B],q,n])}},LG:function(a){for(var b=this.constructor.prototype;null!=b&&"oj"===b.namespace;)a(b),b=Object.getPrototypeOf(b)}});a.La=function(a,b,c){f.widget(a,b,c);if("oj.oj"===a.substring(0,5)||"oj._oj"===a.substring(0,6)){b=a.split(".");a=b[0];b=b[1];var d=
a+"-"+b;f.expr[":"][("_"===b.substring(0,1)?"_"+a+"-"+b.substring(3):a+"-"+b.substring(2)).toLowerCase()]=function(a){return!!f.data(a,d)}}};var m="translations",n=m+".",q={preventDefault:function(){this.isDefaultPrevented=h},stopPropagation:function(){this.isPropagationStopped=h},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=h}};a.da={};a.da.NK="\\x3chtml\\x3e";a.da.MK="\\x3c/html\\x3e";a.da.jL={SPAN:1,B:1,A:1,I:1,EM:1,BR:1,HR:1,LI:1,OL:1,UL:1,P:1,TT:1,BIG:1,SMALL:1,PRE:1};
a.da.iL={"class":1,style:1,href:1};a.da.cg="data-oj-surrogateid";a.da.yW=function(b){return 0===b.indexOf(a.da.NK)&&b.lastIndexOf(a.da.MK)===b.length-7?!0:!1};a.da.sV=function(b){var c=f(document.createElement("span")).get(0);(c.innerHTML=b)&&0<=b.indexOf("\\x3c")&&a.da.jB(c);return c};a.da.jB=function(b){for(var c=b.childNodes,d,e,g,l,h,m=c.length-1;0<=m;)if(d=c.item(m),1===d.nodeType){if(a.da.jL[d.nodeName])for(e=d.attributes,h=e.length-1;0<=h;h--)g=e[h],(l=void 0!==f(d).attr(g))&&(a.da.iL[g.name]||
d.removeAttribute(g.nodeName));a.da.jB(d)}else b.removeChild(d)};a.da.xW=function(b,c){a.i.ff(b);a.i.ff(c);var d,e;1===c.nodeType&&c.hasAttribute(a.da.cg)?(d=c.getAttribute(a.da.cg),d=f("#"+d),e=0<d.length?d[0]:c.parentNode):e=c.parentNode;for(;e;){if(e==b)return!0;1===e.nodeType&&e.hasAttribute(a.da.cg)?(d=e.getAttribute(a.da.cg),d=f("#"+d),e=0<d.length?d[0]:e.parentNode):e=e.parentNode}return!1};a.da.Ol=function(b,c){a.i.ff(b);a.i.ff(c);return c==b?!0:a.da.xW(b,c)};a.da.Bh=function(b,c){var d=f(b),
e=d.data(a.da.Bm);null==e&&(e=new a.da.RL(b),d.data(a.da.Bm,e),e.start());e.addListener(c)};a.da.ck=function(b,c){var d=f(b),e=d.data(a.da.Bm);null!=e&&(e.removeListener(c),e.isEmpty()&&(e.stop(),d.removeData(a.da.Bm)))};a.da.GH=function(b){f(b).find(".oj-helper-detect-expansion").parent().each(function(b,c){var d=f(c).data(a.da.Bm);null!=d&&d.nH(!1)})};a.da.Ho=function(b){void 0===a.da.SD&&(a.da.SD=navigator&&navigator.userAgent?0<=navigator.userAgent.toLowerCase().indexOf("mac os"):!1);return a.da.SD?
b.metaKey:b.ctrlKey};a.da.mR=(window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,0)}).bind(window);a.da.RL=function(b){this.gr=f.Callbacks();this.addListener=function(a){this.gr.add(a)};this.removeListener=function(a){this.gr.remove(a)};this.isEmpty=function(){return this.gr.empty()};this.start=function(){var a=b.childNodes[0],c=this.Gk=document.createElement("div");c.className="oj-helper-detect-expansion";var d=
document.createElement("div");c.appendChild(d);b.insertBefore(c,a);this.Cr=this.Ov.bind(this);c.addEventListener("scroll",this.Cr,!1);d=this.mq=document.createElement("div");d.className="oj-helper-detect-contraction";var e=document.createElement("div");e.style.width="200%";e.style.height="200%";d.appendChild(e);b.insertBefore(d,a);d.addEventListener("scroll",this.Cr,!1);null!=c.offsetParent&&this.Mt(c.offsetWidth,c.offsetHeight)};this.stop=function(){this.Gk.removeEventListener("scroll",this.Cr);
this.mq.removeEventListener("scroll",this.Cr);b.removeChild(this.Gk);b.removeChild(this.mq)};this.nH=function(b){var c=this.Gk;if(null!=c.offsetParent){var d=c.offsetWidth,e=c.offsetHeight;if(this.pS!==d||this.oS!==e){this.LF=2;this.Mt(d,e);var g=this.gr;a.da.mR(function(){g.fire(d,e)})}else b&&0<this.LF&&(0==c.scrollLeft||0==c.scrollTop)&&(this.LF--,this.Mt(d,e))}};this.Ov=function(a){a.stopPropagation();this.nH(!0)};this.Mt=function(a,b){this.pS=a;this.oS=b;var c=this.Gk.firstChild;c.style.width=
a+1+"px";c.style.height=b+1+"px";this.Gk.scrollLeft=1;this.Gk.scrollTop=1;this.mq.scrollLeft=a;this.mq.scrollTop=b}};a.da.Bm="_ojResizeTracker";a.Ua=function(a){this.Init(a)};a.b.ra(a.Ua,a.b,"oj.ComponentMessaging");a.Ua.fd={NONE:"none",lp:"notewindow",nm:"placeholder"};a.Ua.lt={};a.Ua.wy=function(b,c){b&&"function"===typeof c&&(a.Ua.lt[b]=c)};a.Ua.prototype.Init=function(b){a.Ua.t.Init.call(this);this.Sa=b;this.Gm=!1;this.kR()};a.Ua.prototype.vi=function(b,c){var d=this;a.i.oe(c);this.Nb=b;this.jr=
a.ic.hf(this.jr||{},c);this.Gm?this.TS():(f.each(this.Mj,function(a,b){b.vi(d)}),this.Gm=!0)};a.Ua.prototype.update=function(b){a.i.oe(b);a.i.gH(this.Gm);this.jr=a.ic.hf(this.jr||{},b);this.Gm&&f.each(this.Mj,function(a,b){b.update()})};a.Ua.prototype.yg=function(){f.each(this.Mj,function(a,b){b.yg()});this.Gm=!1;this.Nb=this.Sa=null;this.Mj={}};a.Ua.prototype.hq=function(b,c){return new (a.Ua.lt[b]||a.Ua.lt[a.Ua.fd.NONE])(c)};a.Ua.prototype.hP=function(){return this.Sa||null};a.Ua.prototype.zP=function(){return this.Nb||
null};a.Ua.prototype.af=function(){return this.jr||{}};a.Ua.prototype.WC=function(){var b={},c=!1,d=this.Sa.options.placeholder,e,g={},l=this;f.each(this.Sa.options.displayOptions||{},function(b,h){c=!1;e=b+"";Array.isArray(h)?f.each(h,function(a,b){c||(c=l.GF(e,b,d,g))}):"string"===typeof h&&(c||(c=l.GF(e,h,d,g)));c||(g[e]=a.Ua.fd.NONE)});f.each(a.Ua.fd,function(a,c){b[c]=[]});f.each(g,function(a,c){b[c].push(a)});return b};a.Ua.prototype.GF=function(b,c,d,e){var g=!1;switch(c){case a.Ua.fd.nm:"converterHint"!==
b||g||d||(e[b]=c,g=!0);break;default:g||(e[b]=c,g=!0)}return g};a.Ua.prototype.kR=function(){var b=this.WC(),c=b[a.Ua.fd.lp],d=b[a.Ua.fd.NONE],b=b[a.Ua.fd.nm],e={};0<c.length&&(e[a.Ua.fd.lp]=this.hq(a.Ua.fd.lp,c));0<b.length&&(e[a.Ua.fd.nm]=this.hq(a.Ua.fd.nm,b));e[a.Ua.fd.NONE]=this.hq(a.Ua.fd.NONE,d);this.Mj=e};a.Ua.prototype.TS=function(){var b=this.WC(),c,d=this;f.each(b,function(b,e){b+="";c=d.Mj[b];e&&0<e.length?c?c&&c.Wo(e):(c=d.hq(b,e),d.Mj[b]=c,c.vi(d)):c&&a.Ua.fd.NONE!==b&&(c.yg(),delete d.Mj[b])})};
a.Tb=function(a){this.Init(a)};a.b.ra(a.Tb,a.b,"oj.MessagingStrategy");a.Tb.prototype.Init=function(b){a.i.bs(b);a.Tb.t.Init.call(this);this.nq=b};a.Tb.prototype.vi=function(a){this.ij=a};a.Tb.prototype.update=function(){};a.Tb.prototype.yg=function(){};a.Tb.prototype.Wo=function(a){this.Init(a)};a.Tb.prototype.vd=function(){return this.ij.zP()};a.Tb.prototype.Ue=function(){return this.ij.hP()};a.Tb.prototype.Zy=function(){return this.Xs().Gn};a.Tb.prototype.Yy=function(){return this.Xs().Il()};a.Tb.prototype.Xy=
function(){var a=[],b=this.af().converterHint;b&&a.push(b);return a};a.Tb.prototype.RJ=function(){var a=[],b=this.af().validatorHint||[];f.each(b,function(b,c){a.push(c)});return a};a.Tb.prototype.QJ=function(){return this.af().title||""};a.Tb.prototype.Xs=function(){return this.af().validityState};a.Tb.prototype.$y=function(){var a=this.Zy();return a&&0<a.length?!0:!1};a.Tb.prototype.hK=function(){return-1!==this.nq.indexOf("messages")?!0:!1};a.Tb.prototype.dt=function(){return-1!==this.nq.indexOf("converterHint")?
!0:!1};a.Tb.prototype.jz=function(){return-1!==this.nq.indexOf("validatorHint")?!0:!1};a.Tb.prototype.iz=function(){return-1!==this.nq.indexOf("title")?!0:!1};a.Tb.prototype.SJ=function(){return this.Xs().ay()};a.Tb.prototype.af=function(){return this.ij?this.ij.af():{}};a.td=function(a){this.Init(a)};a.Ua.wy(a.Ua.fd.NONE,a.td);a.td.Ep="oj-invalid";a.td.Fp="oj-warning";a.b.ra(a.td,a.Tb,"oj.DefaultMessagingStrategy");a.td.prototype.update=function(){a.td.t.update.call(this);var b=this.vd(),c=this.Yy(),
d=[],e=[],g=!1,l=this.Ue().widget();b&&(this.SJ()?(d.push(a.td.Fp),e.push(a.td.Ep),g=!0):this.$y()&&c===a.U.Lb.WARNING?(d.push(a.td.Ep),e.push(a.td.Fp)):(d.push(a.td.Ep),d.push(a.td.Fp)),l.removeClass(d.join(" ")).addClass(e.join(" ")),b.attr({"aria-invalid":g}))};a.td.prototype.yg=function(){this.Ue().widget().removeClass(a.td.Ep).removeClass(a.td.Fp);this.vd().removeAttr("aria-invalid");a.td.t.yg.call(this)};a.We=function(a){this.Init(a)};a.Ua.wy(a.Ua.fd.nm,a.We);a.b.ra(a.We,a.Tb,"oj.PlaceholderMessagingStrategy");
a.We.prototype.Init=function(b){a.We.t.Init.call(this,b)};a.We.prototype.vi=function(b){a.We.t.vi.call(this,b);this.eF()};a.We.prototype.Wo=function(b){a.We.t.Wo.call(this,b);this.eF()};a.We.prototype.yg=function(){a.We.t.yg.call(this)};a.We.prototype.eF=function(){var a=this.vd();this.Ue().widget();if(this.iK()&&a&&(a=this.Xy(),a=a.length?a[0]:"")){var b={},c={};b.placeholder=a;c._oj_messaging_update=!0;this.Ue().option(b,c)}};a.We.prototype.iK=function(){return this.dt()};a.zf=function(a,b){this.Init(a,
b)};a.zf.ay=function(b){return a.U.Il(b)>=a.U.Lb.ERROR?!0:!1};a.b.ra(a.zf,a.b,"oj.ComponentValidity");a.zf.prototype.Init=function(b,c){a.zf.t.Init.call(this);this.FD(c)};a.zf.prototype.ay=function(){return this.Bj};a.zf.prototype.Il=function(){return this.VR};a.zf.prototype.update=function(a,b){this.FD(b)};a.zf.prototype.FD=function(b){this.tN=b;this.Gn=this.vP();this.VR=a.U.Il(this.Gn);this.Bj=a.zf.ay(this.Gn)};a.zf.prototype.vP=function(){var b=this.tN||[],c=[],d,e;for(e in b)d=b[e],d instanceof
a.Sb&&!d.mH()||c.push(d);return c};a.rm={};o_("Test",a.rm,a);a.rm.ready=!1;o_("Test.ready",a.rm.ready,a);a.rm.KV=function(b){var c=b;if(a.hb.Id(b))try{c=f.parseJSON(b)}catch(d){return null}return c&&c.element&&(b=f(c.element))?a.Components.ws(b[0],c.component)("getNodeBySubId",{subId:c.subId}):null};o_("Test.domNodeForLocator",a.rm.KV,a);f(document).ready(function(){var a=f("\x3cdiv style\x3d'border: 1px solid;border-color:red green;position: absolute;top: -999px;background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs\x3d);'\x3e\x3c/div\x3e"),
b;a.appendTo("body");b=a.css("backgroundImage");a.css("borderTopColor")!=a.css("borderRightColor")&&(null==b||"none"!=b&&"url (invalid-url:)"!=b)||f("body").addClass("oj-hicontrast");a.remove()});f(document).ready(function(){"Microsoft Internet Explorer"==navigator.appName&&f("html").addClass("oj-slow-borderradius oj-slow-cssgradients oj-slow-boxshadow")});a.he={};a.he.Jg=function(b,c){a.i.oe(b,"position");for(var d=f.extend({},b),e=0;e<a.he.qz.length;e++){var g=a.he.qz[e],l=d[g];l&&(d[g]=l.replace("start",
c?"right":"left").replace("end",c?"left":"right"))}return d};a.he.qz=["my","at"]});
//# sourceMappingURL=oj-modular.map