var o_a=this;function o_(a,f,c){a=a.split(".");c=c||o_a;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var b;a.length&&(b=a.shift());)a.length||void 0===f?c=c[b]?c[b]:c[b]={}:c[b]=f};define(["require","ojL10n!ojtranslations/nls/ojtranslations"],function(a,f){var c={};"undefined"!==typeof window?c=window:"undefined"!==typeof self&&(c=self);var b=c.oj,d=c.oj={version:"0.7",build:"142",revision:"11328",noConflict:function(){c.oj=b}};d.C={};o_("Logger",d.C,d);d.C.TJ=0;o_("Logger.LEVEL_NONE",d.C.TJ,d);d.C.Zs=1;o_("Logger.LEVEL_ERROR",d.C.Zs,d);d.C.Qh=2;o_("Logger.LEVEL_WARN",d.C.Qh,d);d.C.bz=3;o_("Logger.LEVEL_INFO",d.C.bz,d);d.C.cz=4;o_("Logger.LEVEL_LOG",
d.C.cz,d);d.C.mL="error";d.C.pL="warn";d.C.nL="info";d.C.oL="log";d.C.MB={level:d.C.Zs,writer:null};d.C.Ta=d.C.MB;d.C.error=function(a){d.C.ho(d.C.Zs,d.C.mL,arguments)};o_("Logger.error",d.C.error,d);d.C.info=function(a){d.C.ho(d.C.bz,d.C.nL,arguments)};o_("Logger.info",d.C.info,d);d.C.warn=function(a){d.C.ho(d.C.Qh,d.C.pL,arguments)};o_("Logger.warn",d.C.warn,d);d.C.log=function(a){d.C.ho(d.C.cz,d.C.oL,arguments)};o_("Logger.log",d.C.log,d);d.C.option=function(a,c){var b={},f;if(0==arguments.length){for(f in d.C.Ta)d.C.Ta.hasOwnProperty(f)&&
(b[f]=d.C.Ta[f]);return b}if("string"===typeof a&&void 0===c)return void 0===d.C.Ta[a]?null:d.C.Ta[a];if("string"===typeof a)d.C.Ta[a]=c;else for(f in a)a.hasOwnProperty(f)&&d.C.option(f,a[f])};o_("Logger.option",d.C.option,d);d.C.ho=function(a,c,b){if(!(d.C.option("level")<a)){var f=d.C.dQ();null!=f&&(1==b.length&&b[0]instanceof Function&&(b=[b[0]()]),f[c]&&f[c].apply?f[c].apply(f,b):f[c]&&(f[c]=Function.prototype.bind.call(f[c],f),d.C.ho(a,c,b)))}};d.C.dQ=function(){var a=null;d.C.option("writer")?
a=d.C.option("writer"):void 0!==window&&void 0!==window.console&&(a=window.console);return a};d.C.xY=function(a){return void 0!==d.C.MB[a]};d.b=function(){this.Init()};o_("Object",d.b,d);d.b.t=null;d.b.ex="oj.Object";d.b.JK=/function\s+([\w\$][\w\$\d]*)\s*\(/;d.b.prototype={};d.b.prototype.constructor=d.b;d.b.g=function(a,c){var b=null,f=null,l;for(l in c)if(c.hasOwnProperty(l)){b=l;f=c[l];break}var m=a.split(".");l=d[m[0]];m=m[2];if(b!=m&&null!=b){var n=l.Ew;n||(n={},l.Ew=n);n[b]=m;l.prototype[m]=
f}};d.b.ra=function(a,c,b){d.i.wi(a);d.i.hH(c);d.i.jH(b);void 0===c&&(c=d.b);d.i.assert(a!==c,"Class can't extend itself");var f=d.b.rU;f.prototype=c.prototype;a.prototype=new f;a.prototype.constructor=a;a.t=a.superclass=c.prototype;b&&(a.ex=b)};o_("Object.createSubclass",d.b.ra,d);d.b.vV=function(a,c){var b;d.i.wi(a);d.i.assert(null!=c,"source object cannot be null");for(b in c)c.hasOwnProperty(b)&&(a.prototype[b]=c[b])};o_("Object.copyPropertiesForClass",d.b.vV,d);d.b.rU=function(){};d.b.prototype.QH=
function(a){if(void 0===a)a=this;else if(null===a)return null;return a.constructor};d.b.g("Object.prototype.getClass",{QH:d.b.prototype.QH});d.b.prototype.clone=function(){var a=new this.constructor;d.ic.hf(a,this);return a};d.b.g("Object.prototype.clone",{clone:d.b.prototype.clone});d.b.prototype.toString=function(){return this.Ly()};d.b.g("Object.prototype.toString",{toString:d.b.prototype.toString});d.b.prototype.Ly=function(){return this.getTypeName()+" Object"};d.b.g("Object.prototype.toDebugString",
{Ly:d.b.prototype.Ly});d.b.getTypeName=function(a){d.i.wi(a);var c=a.ex;null==c&&(c=a.toString(),c=(c=d.b.JK.exec(c))?c[1]:"anonymous",a.ex=c);return c};o_("Object.getTypeName",d.b.getTypeName,d);d.b.prototype.getTypeName=function(){return d.b.getTypeName(this.constructor)};d.b.g("Object.prototype.getTypeName",{getTypeName:d.b.prototype.getTypeName});d.b.prototype.Init=function(){d.i.Fb&&d.i.assert(this.getTypeName,"Not an oj.Object");var a=this.constructor;a.ar||d.b.Vv(a)};d.b.g("Object.prototype.Init",
{Init:d.b.prototype.Init});d.b.MV=function(a){d.i.wi(a);a.ar||d.b.Vv(a)};o_("Object.ensureClassInitialization",d.b.MV,d);d.b.prototype.Ci=function(a){return this===a};d.b.g("Object.prototype.equals",{Ci:d.b.prototype.Ci});d.b.ks=function(a,c){d.i.wi(c);return c.bind(a)};o_("Object.createCallback",d.b.ks,d);d.b.NA=function(a,c){var b=d.i.Ws,f=d.i.Qy,l,m;for(l in a)a.hasOwnProperty(l)&&(m=a[l],"function"!==typeof m||m.hasOwnProperty(b)||(m[b]=l,m[f]=c))};d.b.Vv=function(a){d.i.Fb&&(d.i.wi(a),d.i.assert(!a.ar));
a.ar=!0;var c=a.t,b;c&&((c=c.constructor)&&!c.ar&&d.b.Vv(c),d.b.IM(a));c=d.b.getTypeName(a);try{(b=a.InitClass||null)||(b=a.InitClass),b&&b.call(a)}finally{d.i.Fb&&(d.b.NA(a.prototype,c),d.b.NA(a,"static "+c))}};d.b.Ch=function(a,c){if(a===c)return!0;if(typeof a!==typeof c||null===a||null===c)return!1;if(a.constructor===c.constructor){if(Array.isArray(a))return d.b.uN(a,c);if(a.constructor===Object)return d.b.dj(a,c);if(a.valueOf&&"function"===typeof a.valueOf)return a.valueOf()===c.valueOf()}return!1};
o_("Object.compareValues",d.b.Ch,d);d.b.uN=function(a,c){if(a.length!==c.length)return!1;for(var b=0,f=a.length;b<f;b++)if(!d.b.Ch(a[b],c[b]))return!1;return!0};d.b.dj=function(a,c){var b,f=!1;if(a===c)return!0;if(!(a instanceof Object&&c instanceof Object)||a.constructor!==c.constructor)return!1;for(b in a)if(f||(f=!0),a.hasOwnProperty(b)&&(!c.hasOwnProperty(b)||a[b]!==c[b]&&("object"!==typeof a[b]||!d.b.dj(a[b],c[b]))))return!1;for(b in c)if(f||(f=!0),c.hasOwnProperty(b)&&!a.hasOwnProperty(b))return!1;
return f?!0:JSON.stringify(a)===JSON.stringify(c)};d.b.isEmpty=function(a){var c;if(void 0===a||null===a)return!0;for(c in a)if(a.hasOwnProperty(c))return!1;return!0};d.b.IM=function(a){d.b.Ew&&d.b.OA(a,a.t)};d.b.OA=function(a,c){if(c){var b=c.constructor;d.b.OA(a,b.t);var b=b.Ew,f;if(b)for(f in b)if(b.hasOwnProperty(f)){var l=b[f];if(f!=l){var m=a.prototype;!m.hasOwnProperty(f)&&m.hasOwnProperty(l)?m[f]=m[l]:!m.hasOwnProperty(l)&&m.hasOwnProperty(f)&&(m[l]=m[f])}}}};d.b.la=function(a){Promise.prototype.done||
(Promise.prototype.done=Promise.prototype.then);return new Promise(a)};d.Em=function(){return"function"===typeof define&&define.amd};d.i={};o_("Assert",d.i,d);d.i.QV=function(){d.i.Fb=d.i.DEBUG=!0};o_("Assert.forceDebug",d.i.QV,d);d.i.Ws="_funcName";d.i.Qy="_className";d.i.lL=20;d.i.assert=function(a,c){if(d.i.Fb&&!a){var b=c||"",f;if(2<arguments.length){b+="(";for(f=2;f<arguments.length;f+=1)b+=arguments[f];b+=")"}d.i.Ec(b,1)}};o_("Assert.assert",d.i.assert,d);d.i.fa=function(){d.i.Fb&&d.i.Ec("Abstract function called",
1)};o_("Assert.failedInAbstractFunction",d.i.fa,d);d.i.mb=function(a,c,b){var f;d.i.Fb&&(null!==a?(d.i.Ie(c,"function",null,1,!1),f=c.prototype,f.isPrototypeOf(a)||d.i.Ec("object '"+a+"' doesn't match prototype "+f,1,b)):d.i.Ec("null object doesn't match prototype "+f,1,b))};o_("Assert.assertPrototype",d.i.mb,d);d.i.kV=function(a,c,b){var f;d.i.Fb&&null!==a&&(null!==a?(d.i.Ie(c,"function",null,1,!1),f=c.prototype,f.isPrototypeOf(a)||d.i.Ec("object '"+a+"' doesn't match prototype "+f,1,b)):d.i.Ec("null object doesn't match prototype "+
f,1,b))};o_("Assert.assertPrototypeOrNull",d.i.kV,d);d.i.lV=function(a,c,b,f){d.i.Fb&&(c=c.prototype,b=b.prototype,c.isPrototypeOf(a)||b.isPrototypeOf(a)||d.i.Ec("object '"+a+"' doesn't match prototype "+c+" or "+b,1,f))};o_("Assert.assertPrototypes",d.i.lV,d);d.i.eV=function(a,c){d.i.Fb&&a&&void 0===a.nodeType&&d.i.Ec(a+" is not a DOM Node",c+1)};o_("Assert.assertDomNodeOrNull",d.i.eV,d);d.i.rx=function(a,c){d.i.Fb&&(a&&void 0!==a.nodeType||d.i.Ec(a+" is not a DOM Node",c+1))};o_("Assert.assertDomNode",
d.i.rx,d);d.i.ff=function(a,c){d.i.Fb&&(d.i.rx(a,1),1!==a.nodeType?d.i.Ec(a+" is not a DOM Element",1):c&&a.nodeName!==c&&d.i.Ec(a+" is not a "+c+" Element",1))};o_("Assert.assertDomElement",d.i.ff,d);d.i.dV=function(a,c){d.i.Fb&&null!==a&&(d.i.rx(a,1),1!==a.nodeType?d.i.Ec(a+" is not a DOM Element",1):c&&a.nodeName!==c&&d.i.Ec(a+" is not a "+c+" Element",1))};o_("Assert.assertDomElementOrNull",d.i.dV,d);d.i.Ie=function(a,c,b,f,l){!d.i.Fb||null===a&&l||typeof a===c||(a=a+" is not of type "+c,b&&(a=
b+a),f||(f=0),d.i.Ec(a,f+1))};o_("Assert.assertType",d.i.Ie,d);d.i.oe=function(a,c){d.i.Fb&&d.i.Ie(a,"object",c,1,!1)};o_("Assert.assertObject",d.i.oe,d);d.i.jV=function(a,c){d.i.Fb&&d.i.Ie(a,"object",c,1,!0)};o_("Assert.assertObjectOrNull",d.i.jV,d);d.i.iH=function(a,c){d.i.Fb&&(d.i.Ie(a,"string",c,1,!1),d.i.assert(0<a.length,"empty string"))};o_("Assert.assertNonEmptyString",d.i.iH,d);d.i.cs=function(a,c){d.i.Fb&&d.i.Ie(a,"string",c,1,!1)};o_("Assert.assertString",d.i.cs,d);d.i.jH=function(a,c){d.i.Fb&&
d.i.Ie(a,"string",c,1,!0)};o_("Assert.assertStringOrNull",d.i.jH,d);d.i.wi=function(a,c){d.i.Fb&&d.i.Ie(a,"function",c,1,!1)};o_("Assert.assertFunction",d.i.wi,d);d.i.hH=function(a,c){d.i.Fb&&d.i.Ie(a,"function",c,1,!0)};o_("Assert.assertFunctionOrNull",d.i.hH,d);d.i.gH=function(a,c){d.i.Fb&&d.i.Ie(a,"boolean",c,1,!1)};o_("Assert.assertBoolean",d.i.gH,d);d.i.fc=function(a,c){d.i.Fb&&d.i.Ie(a,"number",c,1,!1)};o_("Assert.assertNumber",d.i.fc,d);d.i.hV=function(a,c){d.i.Fb&&d.i.Ie(a,"number",c,1,!0)};
o_("Assert.assertNumberOrNull",d.i.hV,d);d.i.bs=function(a,c){d.i.Fb&&!Array.isArray(a)&&(void 0===c&&(c=a+" is not an array"),d.i.Ec(c,1))};o_("Assert.assertArray",d.i.bs,d);d.i.jo=function(a,c){d.i.Fb&&null!==a&&!Array.isArray(a)&&(void 0===c&&(c=a+" is not an array"),d.i.Ec(c,1))};o_("Assert.assertArrayOrNull",d.i.jo,d);d.i.gV=function(a,c){d.i.Fb&&!isNaN(a)&&(void 0===c&&(c=a+" is convertible to a number"),d.i.Ec(c,1))};o_("Assert.assertNonNumeric",d.i.gV,d);d.i.iV=function(a,c){d.i.Fb&&isNaN(a)&&
(void 0===c&&(c=a+" is not convertible to a number"),d.i.Ec(c,1))};o_("Assert.assertNumeric",d.i.iV,d);d.i.fV=function(a,c,b){var f;if(null===a||void 0===c[a.toString()]){if(void 0===b){b=" is not in set: {";for(f in c)c.hasOwnProperty(f)&&(b+=f,b+=",");b=a+(b+"}")}d.i.Ec(b,1)}};o_("Assert.assertInSet",d.i.fV,d);d.i.Ec=function(a,c,b){c||(c=0);var f="Assertion";b&&(f+=" ("+b+")");f+=" failed: ";void 0!==a&&(f+=a);a=d.i.Cv(c+1);a=d.i.aD(a);f+="\nStackTrace:\n"+a;a=Error(f);window.alert(f);throw a;
};o_("Assert.assertionFailed",d.i.Ec,d);d.i.getFunctionName=function(a){var c=a[d.i.Ws],b,f;void 0===c&&(c=a.toString(),b=c.indexOf("("),f=c.lastIndexOf(" ",b),c=c.substring(f+1,b),c.length||(c=null),a[d.i.Ws]=c);return c};o_("Assert.getFunctionName",d.i.getFunctionName,d);d.i.gW=function(){return d.i.aD(d.i.Cv(1))};o_("Assert.getStackString",d.i.gW,d);d.i.Cv=function(a){void 0===a&&(a=0);d.i.assert(0<=a);var c=[],b;try{for(b=d.i.Cv.caller;b&&c.length<d.i.lL;)a?a-=1:c.push(b),b=b.caller}catch(f){}return c};
d.i.EC=function(a){var c=a[d.i.jA],b,f;void 0===c&&(c=a.toString(),b=c.indexOf("("),f=c.indexOf(")",b+1),c=c.substring(b,f+1),c=c.replace(/\s+/g,""),c.length||(c=null),a[d.i.jA]=c);return c};d.i.aD=function(a){if(!a)return"";var c=a.length,b=[],f,l,m,n,q,r,p,s,t;for(f=0;f<c;f+=1){l=a[f];(m=d.i.getFunctionName(l))||(m="anonymous");(n=l[d.i.Qy])&&(m=n+"."+m);n=d.i.EC(l);q=l.arguments;r=q.length;l=null;if(r)for(l=[],p=0;p<r;p+=1)s=q[p],"function"===typeof s&&((t=d.i.getFunctionName(s))||(t="anonymous"),
s=d.i.EC(s),s="function "+t+s),l[p]=s;q=[];q[0]=m;q[1]=n;l&&(q[2]="\n",q[3]="[",q[4]=d.i.ET(l),q[5]="]");b[f]=q.join("")}return b.join("\n")};d.i.ET=function(a){var c=a.length,b="",d,l;for(d=0;d<c;d+=1)l=(l=a[d])?l.toString?l.toString():"Unknown":"(empty)",b+=l,d<c-1&&(b+=",");return b};d.i.jA="_funcParams";d.ja={};o_("Config",d.ja,d);d.ja.re=function(){var a;if(d.Em())return d.i.assert(void 0!==f,"ojtranslations module must be defined"),a=f._ojLocale_,"root"==a?"en":a;a=d.ja.al;null==a&&((a=document.documentElement.lang)||
(a=void 0===navigator?"en":(navigator.language||navigator.userLanguage||"en").toLowerCase()),d.ja.al=a=a.toLowerCase());return a};o_("Config.getLocale",d.ja.re,d);d.ja.eX=function(c,b){if(d.Em()){var h=["ojL10n!ojtranslations/nls/"+c+"/ojtranslations"];d.Fa&&h.push("ojL10n!ojtranslations/nls/"+c+"/localeElements");a(h,function(a,c){f=a;c&&d.Fa.mM(c);b&&b()})}else d.ja.al=c,b&&b()};o_("Config.setLocale",d.ja.eX,d);d.ja.ib=function(c){var b=/^\/|:/;return null==c||b.test(c)?c:(b=d.ja.yT)?b+("/"==b.charAt(b.length-
1)?"":"/")+c:d.Em()?(b=a.toUrl("ojs/_foo_"),b.replace(/[^\/]*$/,"../"+c)):c};o_("Config.getResourceUrl",d.ja.ib,d);d.ja.fX=function(a){d.ja.yT=a};o_("Config.setResourceBaseUrl",d.ja.fX,d);d.ja.dX=function(a){d.ja.NM=a};o_("Config.setAutomationMode",d.ja.dX,d);d.ja.OH=function(){return d.ja.NM};o_("Config.getAutomationMode",d.ja.OH,d);d.hb={};o_("StringUtils",d.hb,d);d.hb.lM=/^\s*|\s*$/g;d.hb.isEmpty=function(a){return null===a?!0:0===d.hb.trim(a).length};o_("StringUtils.isEmpty",d.hb.isEmpty,d);d.hb.AI=
function(a){return void 0===a||d.hb.isEmpty(a)?!0:!1};o_("StringUtils.isEmptyOrUndefined",d.hb.AI,d);d.hb.Id=function(a){return null!==a&&("string"===typeof a||a instanceof String)};o_("StringUtils.isString",d.hb.Id,d);d.hb.trim=function(a){return d.hb.Id(a)?a.replace(d.hb.lM,""):a};o_("StringUtils.trim",d.hb.trim,d);d.ic={};o_("CollectionUtils",d.ic,d);d.ic.hf=function(a,c,b,f,l){return d.ic.tB(a,c,b,f,l,0)};o_("CollectionUtils.copyInto",d.ic.hf,d);d.ic.isPlainObject=function(a){if("object"===typeof a)try{if(a.constructor&&
a.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!0}catch(c){}return!1};o_("CollectionUtils.isPlainObject",d.ic.isPlainObject,d);d.ic.tB=function(a,c,b,f,l,m){var n,q,r;if(a&&c&&a!==c){r=Object.keys(c);for(var p=0;p<r.length;p++){n=r[p];q=b?b(n):n;n=c[n];var s=!1;if(f&&m<l){var t=a[q];d.ic.isPlainObject(t)&&d.ic.isPlainObject(n)&&(s=!0,d.ic.tB(t,n,b,!0,l,m+1))}s||(a[q]=n)}}return a};d.ea={};o_("Translations",d.ea,d);d.ea.Dy=function(a){d.ea.Ut=a};o_("Translations.setBundle",d.ea.Dy,d);
d.ea.Kc=function(a){return d.ea.XC(a)};o_("Translations.getResource",d.ea.Kc,d);d.ea.pb=function(a,c){return null==a?null:d.ea.WO(a,c)};o_("Translations.applyParameters",d.ea.pb,d);d.ea.J=function(a,c){var b=d.ea.XC(a);if(null==b)return a;var f={};2<arguments.length?f=Array.prototype.slice.call(arguments,1):2==arguments.length&&(f=arguments[1],"object"===typeof f||f instanceof Array||(f=[f]));return d.ea.pb(b,f)};o_("Translations.getTranslatedString",d.ea.J,d);d.ea.qs=function(a){a=d.ea.rC()[a];var c,
b;if(null==a)return{};c={};for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c};o_("Translations.getComponentTranslations",d.ea.qs,d);d.ea.XC=function(a){a=a?a.split("."):[];var c=d.ea.rC(),b=a.length,f=0,l=a[f];for(d.i.oe(c);0<--b&&c;)c=c[l],f++,l=a[f];return c?c[l]||null:null};d.ea.WO=function(a,c){var b=a.length,d=[],l=null,f=!1,n=!1,q=!1,r=!1,p,s;for(s=0;s<b;s++){var t=a.charAt(s),u=!1;if(f)u=!0,f=!1;else switch(t){case "$":f=!0;break;case "{":r||(n||(p=!1,l=[]),n=!0);break;case "}":n&&0<l.length&&
(n=c[l.join("")],d.push(void 0===n?"null":n));n=!1;break;case "[":n||(q?r=!0:q=!0);break;case "]":r?r=!1:q=!1;break;default:u=!0}u&&(n?","==t||" "==t?p=!0:p||l.push(t):r||d.push(t))}return d.join("")};d.ea.rC=function(){var a=d.ea.Ut;return a?a:d.Em()?(d.i.assert(void 0!==f,"ojtranslations module must be defined"),f):{}};return d});
//# sourceMappingURL=oj-modular.map