/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var c=0;a.La("oj.ojCollapsible",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{expanded:!1,expandOn:"click",expandArea:"disclosureIcon",beforeExpand:null,expand:null,beforeCollapse:null,collapse:null,optionChange:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-collapsible oj-component");this.SE();this.Yb()},_init:function(){this.$q=!0;this.$F(this.options.expanded);this.$q=void 0},_OpenContextMenu:function(a,
c){a.open(c,{launcher:this.element.find(".oj-collapsible-header-icon").first(),initialFocus:"menu"})},FN:function(){var a=this.options.expanded?"oj-collapsible-open-icon":"oj-collapsible-close-icon";f("\x3ca href\x3d'#'\x3e").addClass("oj-component-icon oj-clickable-icon oj-collapsible-header-icon "+a).attr("aria-labelledby",this.header.attr("id")).prependTo(this.header)},QB:function(){this.header.children(".oj-collapsible-header-icon").remove()},_destroy:function(){this.kB();this.element.removeClass("oj-collapsible oj-component oj-expanded oj-collapsed oj-disabled");
this.header.removeClass("oj-collapsible-header").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")});this.cn().removeAttr("role").removeAttr("aria-controls").removeAttr("aria-expanded").removeAttr("aria-disabled");this.QB();this.content.css("display","").removeAttr("aria-hidden").removeAttr("tabIndex").removeClass("oj-component-content oj-collapsible-content").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")})},kB:function(){this.tl();this.content&&
(this.content.unwrap(),this.Pg=null)},mY:function(){return!1},BC:function(){return"header"==this.options.expandArea?"\x3e .oj-collapsible-header":"\x3e .oj-collapsible-header \x3e .oj-collapsible-header-icon"},_setOption:function(a,c,e){"expanded"===a?c!==this.options.expanded&&this.$F(c):"expandOn"===a||"expandArea"===a?(this.tl(),this._super(a,c,e),this.Lj()):this._super(a,c,e)},Ej:function(a){if(!a.altKey&&!a.ctrlKey){var c=f.ui.keyCode;switch(a.keyCode){case c.SPACE:case c.ENTER:this.JG(a)}}},
refresh:function(){this._super();this.kB();this.SE();this.QB();this.Yb()},SE:function(){this.header=this.element.children(":first-child").addClass("oj-collapsible-header");this.content=this.header.next().addClass("oj-collapsible-content oj-component-content");this.content.wrap("\x3cdiv\x3e\x3c/div\x3e");this.Pg=this.content.parent().addClass("oj-collapsible-wrapper")},Yb:function(){var a=this.header,d=this.content,e=this.options,f="oj-collapsible-"+(this.element.attr("id")||++c),h=a.attr("id"),k=
d.attr("id");h||a.attr("id",f+"-header");k||(k=f+"-content",d.attr("id",k));this.FN();this.cn().attr("role","button").attr("aria-controls",k).attr("aria-expanded",e.expanded);e.expanded?d.attr("aria-hidden","false"):(this.Pg.css({"max-height":0,"overflow-y":"hidden",display:"none"}),this.Pg.css("max-height",0),d.attr("aria-hidden","true"));this.Lj()},$F:function(a){a?this.expand(!0):this.collapse(!0)},Lj:function(){var a={keydown:this.Ej},c=this.options.expandOn;if(c){var e=this;f.each(c.split(" "),
function(c,d){a[d]=e.JG})}c=this.element.find(this.BC());this._on(c,a);this._on(this.Pg,{transitionend:this.Oj,webkitTransitionEnd:this.Oj,otransitionend:this.Oj,oTransitionEnd:this.Oj});this._on(this.element,{ojexpand:this.Nu,ojcollapse:this.Nu,ojfocus:this.nC,ojfocusout:this.nC});this._hoverable(c);this._focusable(c);this.Lp(c)},tl:function(){this._off(this.element.find(this.BC()));this.Pg&&this._off(this.Pg);this._off(this.element.add(this.content))},JG:function(a){this.options.expanded?this.collapse(!0,
a):this.expand(!0,a);a.preventDefault();a.stopPropagation();this.header.find(".oj-collapsible-header-icon").focus()},Nu:function(a){if(a.target===this.element[0]&&(this.$q||!a.isDefaultPrevented())){var c=this.element,e=this.options,f=this.content,h=this.Pg,k="ojcollapse"===a.type;a.preventDefault();e.expanded=!k;this.$q?k?(c.removeClass("oj-expanded"),c.addClass("oj-collapsed"),h.css("max-height",0),h.hide()):(c.removeClass("oj-collapsed"),c.addClass("oj-expanded")):(h.js=h.outerHeight(),k?(h.removeClass("oj-collapsible-transition"),
h.css({"max-height":h.js,"overflow-y":"hidden"}),setTimeout(function(){h.addClass("oj-collapsible-transition").css({"max-height":0});c.removeClass("oj-expanded");c.addClass("oj-collapsed")},10)):(h.show(),setTimeout(function(){h.js+=f.outerHeight();h.addClass("oj-collapsible-transition").css({"max-height":h.js});c.removeClass("oj-collapsed");c.addClass("oj-expanded")},1)));this.header.find(".oj-collapsible-header-icon").toggleClass("oj-collapsible-open-icon",!k).toggleClass("oj-collapsible-close-icon",
k||!1).end();this.content.attr("aria-hidden",k);this.cn().attr("aria-expanded",!k)}},nC:function(a){"ojfocusout"==a.type?(this.cn().attr("tabIndex",-1),a.preventDefault(),a.stopPropagation()):"ojfocus"==a.type&&(this.cn().attr("tabIndex",0).focus(),a.preventDefault(),a.stopPropagation())},cn:function(){return this.QO(this.header).first()},QO:function(a){return a.find("a,:input")},expand:function(a,c){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeExpand",c,e)||(this._trigger("expand",
c,e),this.Cc("expanded",!1,!0,c?!0:!1))},collapse:function(a,c){if(this.$q){var e=this.element[0];this.Nu({type:"ojcollapse",target:e,currentTarget:e,preventDefault:f.noop})}else e={header:this.header,content:this.content},a&&!1===this._trigger("beforeCollapse",c,e)||(this._trigger("collapse",c,e),this.Cc("expanded",!0,!1,c?!0:!1))},Oj:function(a){"max-height"==(a.originalEvent?a.originalEvent.propertyName:null)&&(a.preventDefault(),a.stopPropagation());this.options.expanded?this.Pg.css({"max-height":9999,
"overflow-y":""}):this.Pg.hide();this.Pg.removeClass("oj-collapsible-transition")},Cc:function(a,c,e,f){this._trigger("optionChange",f,{option:a,previousValue:c,value:e,optionMetadata:{writeback:f?"shouldWrite":"shouldNotWrite"}})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-collapsible-content":return this.content;case "oj-collapsible-header":return this.header;case "oj-collapsible-header-icon":return this.header.find("."+a)[0]}return null}})})()});
//# sourceMappingURL=oj-modular.map