/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){window.adf||(window.adf={});var c=window.adf;c.R=c.R||{};c.R.T=c.R.T||{};c.R.T.V=c.R.T.V||{};c.R.T.V.W=function(a,c,e,f,h,k){this.Zh=a;this.qS=c;this.Sm=e;this.Sp=f;h&&(h.PW&&(this.ES=h.PW),h.IW&&(this.mS=h.IW),h.YI&&(this.FS=h.YI),h.QI&&(this.nS=h.QI),h.XI&&(this.DS=h.XI),h.OI&&(this.lS=h.OI));k&&(k.eJ&&(this.OF=k.eJ),k.OV&&(this.Qu=k.OV),k.mV&&(this.gj=k.mV),k.Bh&&(this.Op=k.Bh),k.ck&&(this.Br=k.ck));this.Ot=!0;this.Lk=0;a=navigator.userAgent.toLowerCase();
if(-1!==a.indexOf("gecko/"))this.OM=!0;else if(-1!==a.indexOf("opera"))this.PM=!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.QM=!0};c.R.T.V.W.prototype.iX=function(a){var d=this,e=c.R.T.V.W;if(a){this.GN();this.XN(this.ES,this.FS,this.DS);this.IN(this.mS,this.nS,this.lS);var f=this.pr,h=this.Pr;h?(this.Vp=h.offsetWidth,this.Up=f.offsetHeight):(h=this.$r,this.Vp=f.offsetWidth,this.Up=h.offsetHeight);this.Xq();this.Wq();this.Jn=function(a){d.GQ(a)};e.ah(this.Zh,"mousewheel",
this.Jn);e.ah(this.Zh,"wheel",this.Jn);this.cx=function(a){d.QQ(a)};e.ah(this.Jc,"touchstart",this.cx);this.bx=function(a){d.PQ(a)};e.ah(this.Jc,"touchmove",this.bx);this.bo=function(){d.OQ()};e.ah(this.Jc,"touchend",this.bo);e.ah(this.Jc,"touchcancel",this.bo);this.vw=0}else this.qF();this.lu();this.HA(a);this.vh(!0);a&&this.Op&&(this.Uk=function(){d.vh(!1)},this.Op.call(this.gj,this.Zh,this.Uk),this.Op.call(this.gj,this.Wh,this.Uk))};c.R.T.V.W.prototype.destroy=function(){var a=this.Zh,d=c.R.T.V.W;
d.ll(a,"mousewheel",this.Jn);d.ll(a,"wheel",this.Jn);d.ll(this.Jc,"touchstart",this.cx);d.ll(this.Jc,"touchmove",this.bx);d.ll(this.Jc,"touchend",this.bo);d.ll(this.Jc,"touchcancel",this.bo);this.bo=this.bx=this.cx=this.Jn=null;this.Br&&this.Uk&&(this.Br.call(this.gj,a,this.Uk),this.Br.call(this.gj,this.Wh,this.Uk));this.Uk=null;d.vT(this.qu,a);this.RA=null;this.Zw?a.removeChild(this.Zw):(a.removeChild(this.Jc),a.removeChild(this.$r),a.removeChild(this.nx));this.$r=this.nx=this.ow=this.zw=this.Pr=
this.Yw=this.Zw=this.qu=this.Jc=this.Wh=this.yw=this.pr=null;this.lu();this.gj=this.Br=this.Op=this.Qu=this.OF=this.Zh=null};c.R.T.V.W.wT=function(a,d,e){var f=c.R.T.V.W,h=null;e&&(h=f.wu(),d.appendChild(h));var k=null;for(a=a.childNodes;0<a.length;){k||(k=[]);var l=a[0];if(1===l.nodeType){e||(h=f.wu(),d.appendChild(h));var m=f.iq();m.appendChild(l);h.appendChild(m);k.push(l)}else e?h.appendChild(l):d.appendChild(l)}return k};c.R.T.V.W.vT=function(a,c){if(a)for(var e=a.childNodes;0<e.length;){var f=
e[0];if(1===f.nodeType){for(var h=f.childNodes;0<h.length;){var k=h[0];1===k.nodeType?(c.appendChild(k.firstChild),f.removeChild(k)):c.appendChild(k)}a.removeChild(f)}else c.appendChild(f)}};c.R.T.V.W.xC=function(a){var c=a.ownerDocument.defaultView,e=null;return e=c?c.getComputedStyle(a,null):a.currentStyle};c.R.T.V.W.pP=function(a){var d=c.R.T.V.W;a=d.xC(a);return d.sC(a.width)};c.R.T.V.W.oP=function(a){var d=c.R.T.V.W;a=d.xC(a);return d.sC(a.height)};c.R.T.V.W.sC=function(a){return 0<a.length&&
"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};c.R.T.V.W.ah=function(a,c,e){a.addEventListener?a.addEventListener(c,e,!1):a.attachEvent&&a.attachEvent("on"+c,e)};c.R.T.V.W.ll=function(a,c,e){a.removeEventListener?a.removeEventListener(c,e,!1):a.detachEvent&&a.detachEvent("on"+c,e)};c.R.T.V.W.cQ=function(a){var c=0;return c=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};c.R.T.V.W.zB=function(){var a=document.createElement("div");a.style.display="table";return a};c.R.T.V.W.wu=
function(){var a=document.createElement("div");a.style.display="table-row";return a};c.R.T.V.W.iq=function(){var a=document.createElement("div");a.style.display="table-cell";return a};c.R.T.V.W.bH=function(a,c,e,f){var h=document.createElement("div"),k=h.style;k.display="inline-block";h.appendChild(a);c.appendChild(h);e&&(k.maxWidth=h.offsetWidth+"px");f&&(k.maxHeight=h.offsetHeight+"px");return h};c.R.T.V.W.prototype.nd=function(){return"horizontal"===this.qS};c.R.T.V.W.prototype.rR=function(){return!this.yC().hasChildNodes()};
c.R.T.V.W.prototype.qF=function(){this.vw=this.Ce();this.oB();this.Pw(0);this.Xq();this.Wq()};c.R.T.V.W.prototype.lu=function(){this.Lr=this.Mf=null};c.R.T.V.W.prototype.vh=function(a){a||this.qF();this.lu();this.Mf&&this.Lr||(this.Mf=this.lE());a||this.HA();a=this.Mf;this.yM(a.Yc,a.Gh)};c.R.T.V.W.prototype.yM=function(a,c){var e=this.pr.style,f=this.yw.style;if(this.nd()){var h=.5*(c-this.Up);e.top=h+"px";f.top=h+"px"}else h=.5*(a-this.Vp),this.Sp?(e.left=-h+"px",f.left=-h+"px"):(e.left=h+"px",f.left=
h+"px")};c.R.T.V.W.prototype.HA=function(a){var d=this.Wh,e=this.nd(),f=c.R.T.V.W,f=e?f.pP(this.Zh):f.oP(this.Zh);(e?d.offsetWidth:d.offsetHeight)>f&&this.fG(f);this.In=0;this.Fn=e?d.offsetWidth-f+this.Vp:d.offsetHeight-f+this.Up;0>this.Fn&&(this.Fn=0);this.Xq();this.Wq();this.nl(a?this.In:this.vw,!0);this.vw=0};c.R.T.V.W.prototype.GN=function(){var a=this,d=this.nd(),e=document.createElement("div");this.Jc=e;var f=e.style;f.overflow="hidden";f.display=this.gn();f.position="relative";d&&(f.verticalAlign=
"top");var h=this.Zh,k=c.R.T.V.W,l=document.createElement("div");this.Wh=l;var m=l.style;m.position="relative";d&&(m.display="inline-block");e.appendChild(l);m=null;if(d){this.Zw=m=k.zB();var n=k.wu(),q=k.iq();this.Yw=q;var r=k.iq(),p=k.iq();this.Pr=p;var s=p.style;q.style.verticalAlign="top";s.verticalAlign="top";r.appendChild(e);n.appendChild(q);n.appendChild(r);n.appendChild(p);m.appendChild(n)}n=k.zB();q=k.wT(h,n,d);if(this.Sm)for(q=[],r=this.Sm.children,p=r.length,s=0;s<p;s++){var t=r[s];1===
t.nodeType&&q.push(t)}(this.RA=q)&&0<q.length&&(this.qu=n,l.appendChild(n));m?h.appendChild(m):(this.nx=m=document.createElement("div"),this.$r=n=document.createElement("div"),h.appendChild(m),h.appendChild(e),h.appendChild(n));d&&(d=e.offsetHeight,l=l.offsetHeight,d>l&&(f.marginBottom=l-d+"px"));k.ah(e,"scroll",function(c){a.Ov(c)})};c.R.T.V.W.prototype.gn=function(){return this.nd()?"inline-block":"block"};c.R.T.V.W.prototype.XN=function(a,d,e){var f=this,h=document.createElement("div");this.yw=
h;a&&h.setAttribute("id",a);h.setAttribute("class",d);h.setAttribute("aria-hidden","true");d=h.style;d.display=this.gn();d.position="relative";if(a=this.nd())d.verticalAlign="top";d=c.R.T.V.W;d.ah(h,"click",function(){f.QF()});this.Yw?this.zw=d.bH(h,this.Yw,a,!a):this.nx.appendChild(h);e&&h.appendChild(e)};c.R.T.V.W.prototype.IN=function(a,d,e){var f=this,h=document.createElement("div");this.pr=h;a&&h.setAttribute("id",a);h.setAttribute("class",d);h.setAttribute("aria-hidden","true");d=h.style;d.display=
this.gn();d.position="relative";if(a=this.nd())d.verticalAlign="top";d=c.R.T.V.W;d.ah(h,"click",function(){f.PF()});this.Pr?this.ow=d.bH(h,this.Pr,a,!a):this.$r.appendChild(h);e&&h.appendChild(e)};c.R.T.V.W.prototype.yC=function(){var a=this.Sm;a||(a=this.Wh);return a};c.R.T.V.W.prototype.lE=function(){var a=this.qu,c=this.RA,e={Yc:0,Gh:0},f=[];if(this.yC().hasChildNodes()&&a&&c&&0<c.length)for(var a=this.nd(),h=0,h=this.Wh.offsetWidth,k=0,l=null,m=0;m<c.length;m++){var n=c[m];if(1===n.nodeType){var q=
n.offsetWidth,r=n.offsetHeight,p={Yc:q,Gh:r,id:n.id};if(a){var s=n.offsetLeft;this.Sm||0!==s||(n=n.parentNode,s=n.offsetLeft);p.start=this.Sp?h-(s+q):s;0===m&&(k=p.start);p.start-=k;e.Yc=p.start+q;e.Gh=Math.max(e.Gh,r);p.end=e.Yc-1}else s=n.offsetTop,this.Sm||0!==s||(n=n.parentNode,s=n.offsetTop),p.start=s,e.Yc=Math.max(e.Yc,q),e.Gh=p.start+r,p.end=e.Gh-1;l&&l.end>=p.start&&(q=l.end-(p.start-1),l.end-=q,a?l.Yc-=q:l.Gh-=q);f.push(p);l=p}}this.Lr=f;return e};c.R.T.V.W.prototype.Rk=function(){if(!this.Lr){var a=
this.lE();this.Mf||(this.Mf=a)}return this.Lr};c.R.T.V.W.prototype.ov=function(){return this.ow?this.ow:this.pr};c.R.T.V.W.prototype.tv=function(){return this.zw?this.zw:this.yw};c.R.T.V.W.prototype.iU=function(){this.ov().style.display=this.gn()};c.R.T.V.W.prototype.kU=function(){this.tv().style.display=this.gn()};c.R.T.V.W.prototype.Wq=function(){this.ov().style.display="none"};c.R.T.V.W.prototype.Xq=function(){this.tv().style.display="none"};c.R.T.V.W.prototype.er=function(){return"none"!==this.ov().style.display};
c.R.T.V.W.prototype.Zv=function(){return"none"!==this.tv().style.display};c.R.T.V.W.prototype.Tu=function(){return this.nd()?this.Vp:this.Up};c.R.T.V.W.prototype.HU=function(a){var c=this.Tu(),e=this.Ce(),f=this.Nk(),h=this.or();a<=this.In?(this.Zv()&&(f+=c,e-=c),this.Xq()):h&&(this.Zv()||(f-=c,e+=c),this.kU());a>=this.Fn?(this.er()&&(f+=c),this.Wq()):h&&(this.er()||(f-=c),this.iU());this.Pw(e);h?this.fG(f):this.oB()};c.R.T.V.W.prototype.fG=function(a){var c=this.Jc.style;a+="px";this.nd()?c.maxWidth=
a:c.maxHeight=a};c.R.T.V.W.prototype.oB=function(){var a=this.Jc.style;this.nd()?a.maxWidth="":a.maxHeight=""};c.R.T.V.W.prototype.Pw=function(a){var c=this.Jc;this.nd()?c.scrollLeft=this.ru(a):c.scrollTop=a};c.R.T.V.W.prototype.Nk=function(){var a=this.Jc;return this.nd()?a.offsetWidth:a.offsetHeight};c.R.T.V.W.prototype.nl=function(a,c){this.Vh||(this.Ot=!1,this.YF(a,c))};c.R.T.V.W.prototype.YF=function(a,d){if(!this.rR()){this.Vh=!0;a=this.vN(a);this.HU(a);var e=this.OF;if(d||!e||a===this.Ce())this.AE(a);
else{var f=this;e.call(this.gj,this.Jc,this.ru(a),Math.abs(this.Ce()-a)/c.R.T.V.W.TL,function(){f.AE(a)})}}};c.R.T.V.W.prototype.Ce=function(){var a=this.Jc;return this.nd()?this.BN(a.scrollLeft):a.scrollTop};c.R.T.V.W.prototype.or=function(){var a=this.Wh,c=this.Jc;return this.nd()?a.offsetWidth>c.offsetWidth:a.offsetHeight>c.offsetHeight};c.R.T.V.W.prototype.vN=function(a){!this.or()||a<this.In?a=this.In:a>this.Fn&&(a=this.Fn);return a};c.R.T.V.W.prototype.GQ=function(a){var d=this.Vh;if(this.or()&&
!this.Vh){var e=c.R.T.V.W.cQ(a);0>e&&this.er()?(d=!0,this.PF()):0<e&&this.Zv()&&(d=!0,this.QF())}d&&(a.preventDefault(),a.stopPropagation())};c.R.T.V.W.prototype.QQ=function(a){a=a.touches;this.or()&&!this.Vh&&1===a.length&&(this.Tp=!0,a=a[0],this.yU=this.nd()?a.pageX:a.pageY,this.KG=this.Ce(),this.zU=this.cB(),this.AU=this.dB())};c.R.T.V.W.prototype.PQ=function(a){if(this.Tp){var d=this.nd();a=a.touches[0];a=(d?a.pageX:a.pageY)-this.yU;var e=this.Jc;Math.abs(a)<c.R.T.V.W.VL*(d?e.offsetWidth:e.offsetHeight)?
this.nl(this.KG-a,!0):(this.nl((d&&this.Sp?0<a:0>a)?this.zU:this.AU),this.Tp=!1)}};c.R.T.V.W.prototype.OQ=function(){this.Tp&&this.nl(this.KG);this.Tp=!1};c.R.T.V.W.prototype.Ov=function(){this.Ot&&!this.Vh&&this.YF(this.Ce(),!0)};c.R.T.V.W.prototype.AE=function(a){this.Pw(a);this.PT();this.Vh=!1;if(this.Qu){this.Lk=this.aB();a=this.bB();var c=this.Rk(),e=c[this.Lk];this.Lk!==a&&this.Ce()>e.start&&this.Lk<c.length-2&&(this.Lk++,e=c[this.Lk]);this.UO=e.id;this.Qu.call(this.gj,this.UO)}};c.R.T.V.W.prototype.PT=
function(){var a=this;window.setTimeout(function(){a&&(a.Ot=!0)},0)};c.R.T.V.W.prototype.PF=function(){this.Vh||this.nl(this.cB())};c.R.T.V.W.prototype.QF=function(){this.Vh||this.nl(this.dB())};c.R.T.V.W.prototype.cB=function(){var a=this.bN(),c=0;return c=a===this.aB()?this.Ce()+this.Nk():this.dN(a)};c.R.T.V.W.prototype.dB=function(){var a=this.cN(),c=0,c=a===this.bB()?this.Ce()-this.Nk():this.aN(a);this.er()||(c+=this.Tu());c<this.Tu()&&(c=this.In);return c};c.R.T.V.W.prototype.dN=function(a){return this.Rk()[a].start};
c.R.T.V.W.prototype.aN=function(a){return this.Rk()[a].end-this.Nk()+1};c.R.T.V.W.prototype.aB=function(){var a=this.Xp(this.Ce());return 0>a?0:a};c.R.T.V.W.prototype.bB=function(){var a=this.Xp(this.Ce()+this.Nk()-1),c=this.Rk();return 0>a?c.length-1:a};c.R.T.V.W.prototype.cN=function(){var a=this.Xp(this.Ce()-1);return 0>a?0:a};c.R.T.V.W.prototype.bN=function(){var a=this.Xp(this.Ce()+this.Nk()),c=this.Rk();return 0>a?c.length-1:a};c.R.T.V.W.prototype.Xp=function(a){for(var c=this.Rk(),e=0;e<c.length;e++)if(a<=
c[e].end)return e;return-1};c.R.T.V.W.prototype.ru=function(a){var c=a;if(this.Sp&&this.nd())if(this.OM)c=-a;else if(this.QM||this.PM)c=this.Wh.offsetWidth-this.Jc.offsetWidth-a;return c};c.R.T.V.W.prototype.BN=function(a){return this.ru(a)};c.R.T.V.W.TL=1.1;c.R.T.V.W.VL=.33;(function(){a.La("oj.ojConveyorBelt",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-conveyorbelt oj-component");
this.options.disabled&&a.C.warn(b)},_init:function(){this.ub(!0)},refresh:function(){this._super();var a="rtl"===this.Ic()!==this.TA;a&&this.Du();this.ub(a)},ub:function(b){this.TA="rtl"===this.Ic();var c=this.element,g=this.options;if(b&&!this.Yp){var h=g.orientation,k=null,l=null,m=null,n=null,q=null;"vertical"!==h?(k="oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",m=this.gq("oj-conveyorbelt-overflow-icon oj-start"),
n=this.gq("oj-conveyorbelt-overflow-icon oj-end"),q=this.DM):(k="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",m=this.gq("oj-conveyorbelt-overflow-icon oj-top"),n=this.gq("oj-conveyorbelt-overflow-icon oj-bottom"),q=this.FM);var r={};r.YI=k;r.QI=l;r.XI=m;r.OI=n;k={};k.Bh=a.da.Bh;k.ck=a.da.ck;"enabled"!==a.ja.OH()&&(k.eJ=q);q=null;g.contentParent&&(q=f(g.contentParent)[0]);this.Yp=new window.adf.R.T.V.W(c[0],
h,q,this.TA,r,k)}this.Yp.iX(b);if(b)for(b=c.find(".oj-conveyorbelt-overflow-indicator"),c=b.size(),g=0;g<c;g++)h=b.get(g),this.gU(h)},_destroy:function(){this.Du();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(c,e,f){var h=!1;switch(c){case "containerParent":case "orientation":h=!0;break;case "disabled":a.C.warn(b)}h&&this.Du();this._super(c,e,f);h&&this.ub(!0)},Du:function(){var a=this.Yp;a&&a.destroy();this.Yp=null},gU:function(a){this._on(a,{mousedown:function(a){f(a.currentTarget).addClass("oj-active")},
mouseup:function(a){f(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){a=a.currentTarget;f(a).addClass("oj-hover");f(a).removeClass("oj-default")},mouseleave:function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active");f(a).addClass("oj-default")}})},gq:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon oj-clickable-icon "+a);return b},DM:function(a,b,c,h){var k={};k.scrollLeft=b;f(a).animate(k,c,"swing",h)},FM:function(a,
b,c,h){var k={};k.scrollTop=b;f(a).animate(k,c,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:"oj-conveyorbelt-bottom-overflow-indicator"===
a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null}});var b="JET ConveyorBelt: 'disabled' option not supported"})()});
//# sourceMappingURL=oj-modular.map