/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a){a.yc=function(f,c,b,d,e){a.i.fc(f,null);a.i.fc(c,null);a.i.fc(b,null);a.i.fc(d,null);a.i.jo(e);this.sf=f;this.Zj=c;this.Gg=b;this.Yj=d;this.Mc=e};o_("CollectionCellSet",a.yc,a);a.yc.prototype.hJ=function(f){a.i.bs(f);null!=f&&f.length===this.Z("row")&&(this.ak=f)};a.yc.prototype.getData=function(a){var c;c=this.Xb(a);return null==c?null:c.get(this.Mc[a.column])};a.b.g("CollectionCellSet.prototype.getData",{getData:a.yc.prototype.getData});
a.yc.prototype.getMetadata=function(f){var c;c=this.Xb(f);return null==c?null:{keys:{row:a.Xi.Pk(c),column:this.Mc[f.column]}}};a.b.g("CollectionCellSet.prototype.getMetadata",{getMetadata:a.yc.prototype.getMetadata});a.yc.prototype.Xb=function(f){var c;if(null==this.ak)return null;a.i.oe(f);c=f.row;f=f.column;a.i.assert(c>=this.sf&&c<=this.Zj&&f>=this.Gg&&f<=this.Yj);return this.ak[c-this.sf]};a.yc.prototype.Z=function(a){return"row"===a?Math.max(0,this.Zj-this.sf):"column"===a?Math.max(0,this.Yj-
this.Gg):0};a.b.g("CollectionCellSet.prototype.getCount",{Z:a.yc.prototype.Z});a.yc.prototype.getStartRow=function(){return this.sf};a.b.g("CollectionCellSet.prototype.getStartRow",{getStartRow:a.yc.prototype.getStartRow});a.yc.prototype.VH=function(){return this.Zj};a.b.g("CollectionCellSet.prototype.getEndRow",{VH:a.yc.prototype.VH});a.yc.prototype.getStartColumn=function(){return this.Gg};a.b.g("CollectionCellSet.prototype.getStartColumn",{getStartColumn:a.yc.prototype.getStartColumn});a.yc.prototype.UH=
function(){return this.Yj};a.b.g("CollectionCellSet.prototype.getEndColumn",{UH:a.yc.prototype.UH});a.yc.prototype.Ei=function(){return this.Mc};a.b.g("CollectionCellSet.prototype.getColumns",{Ei:a.yc.prototype.Ei});a.Xi=function(){};a.Xi.Pk=function(a){var c;c=a.ze();null==c&&(c=a.mk());return c};a.Pc=function(f,c,b,d){a.i.fc(f,null);a.i.fc(c,null);a.i.jo(b);this.xc=f;this.Qf=c;this.Cs=b;this.rf=d};o_("CollectionHeaderSet",a.Pc,a);a.Pc.prototype.hJ=function(f){a.i.bs(f);null!=f&&f.length===this.Z()&&
(this.ak=f)};a.Pc.prototype.getData=function(f){a.i.assert(f<=this.Qf&&f>=this.xc);if(null!=this.rf){if(null==this.ak)return null;f=this.ak[f-this.xc];return f.get(this.rf)}return this.Cs[f]};a.b.g("CollectionHeaderSet.prototype.getData",{getData:a.Pc.prototype.getData});a.Pc.prototype.getMetadata=function(f){if(null!=this.rf){if(null==this.ak)return null;f=this.ak[f-this.xc];return{key:a.Xi.Pk(f)}}return{key:this.getData(f)}};a.b.g("CollectionHeaderSet.prototype.getMetadata",{getMetadata:a.Pc.prototype.getMetadata});
a.Pc.prototype.Z=function(){return Math.max(0,this.Qf-this.xc)};a.b.g("CollectionHeaderSet.prototype.getCount",{Z:a.Pc.prototype.Z});a.Pc.prototype.Ia=function(){return this.xc};a.b.g("CollectionHeaderSet.prototype.getStart",{Ia:a.Pc.prototype.Ia});a.Pc.prototype.TH=function(){return this.Qf};a.b.g("CollectionHeaderSet.prototype.getEnd",{TH:a.Pc.prototype.TH});a.Pc.prototype.$H=function(){return this.Cs};a.b.g("CollectionHeaderSet.prototype.getHeaders",{$H:a.Pc.prototype.$H});a.Pc.prototype.uo=function(){return this.rf};
a.b.g("CollectionHeaderSet.prototype.getRowHeader",{uo:a.Pc.prototype.uo});a.ia=function(f,c){this.oa=f;null!=c&&(this.Si=c.rowHeader,this.columns=c.columns);this.O=0;this.Za=-1;a.ia.t.constructor.call(this)};o_("CollectionDataGridDataSource",a.ia,a);a.b.ra(a.ia,a.Kb,"oj.CollectionDataGridDataSource");a.ia.prototype.Init=function(){a.ia.t.Init.call(this);this.Vl={};this.$v()||(null==this.columns&&0<this.oa.length?(this.columns=this.oa.first().keys(),-1!=this.columns.indexOf(this.Si)&&this.columns.splice(this.columns.indexOf(this.Si),
1)):this.columns=[]);this.cT()};a.b.g("CollectionDataGridDataSource.prototype.Init",{Init:a.ia.prototype.Init});a.ia.prototype.cT=function(){this.oa.on("add",this.DQ.bind(this));this.oa.on("remove",this.nD.bind(this));this.oa.on("change",this.EQ.bind(this));this.oa.on("refresh",this.hQ.bind(this))};a.ia.prototype.$v=function(){return null!=this.oa.url||null!=this.oa.customURL};a.ia.prototype.qR=function(){return this.$v()?null!=this.data:!0};a.ia.prototype.OD=function(a){if(this.$v()){if("column"===
a)return null!=this.columns;if("row"===a&&null!=this.Si)return null!=this.data}return!0};a.ia.prototype.Z=function(a){if(!this.OD(a))return this.precision="estimate",-1;this.precision="exact";return"row"==a?this.size():"column"==a?this.columns.length:0};a.b.g("CollectionDataGridDataSource.prototype.getCount",{Z:a.ia.prototype.Z});a.ia.prototype.lf=function(a){null==this.precision&&this.Z(a);return this.precision};a.b.g("CollectionDataGridDataSource.prototype.getCountPrecision",{lf:a.ia.prototype.lf});
a.ia.prototype.Xd=function(a,c,b){var d,e;d=a.axis;this.OD(d)?this.mD(a,c,b):null!=c&&(e={},e.mW=a,e.callbacks=c,e.tx=b,this.Vl[d]=e)};a.b.g("CollectionDataGridDataSource.prototype.fetchHeaders",{Xd:a.ia.prototype.Xd});a.ia.prototype.mD=function(f,c,b,d){var e,g,h,k;e=f.axis;g=f.start;h=f.count;a.i.assert("row"===e||"column"===e);a.i.assert(0<h);if("column"===e)null!=this.columns?(d=Math.min(this.columns.length,g+h),k=new a.Pc(g,d,this.columns)):k=new a.ye(g,g,e,null);else if("row"===e){if(null!=
this.Si){null!=d&&(h=d.count);d=Math.min(this.size(),g+h);0<this.Za&&(d=Math.min(d,this.totalSize()-this.O));k=new a.Pc(g,d,this.columns,this.Si);this.IF(g,d,k,f,c,b);return}k=new a.ye(g,g,e,null)}null!=c&&c.success&&c.success.call(b.success,k,f);this.Vl[e]=null};a.ia.prototype.TC=function(f){var c,b,d,e,g,h;for(c=0;c<f.length;c+=1)b=f[c],a.i.assert("row"===b.axis||"column"===b.axis),a.i.assert(0<b.count),"row"===b.axis?(d=b.start,e=b.count):"column"===b.axis&&(g=b.start,h=b.count);return{rowStart:d,
rowCount:e,colStart:g,colCount:h}};a.ia.prototype.kD=function(f,c,b,d){var e,g,h;e=this.TC(f);g=e.rowStart;d=null!=d?Math.min(this.size(),g+d.count):Math.min(this.size(),g+e.rowCount);h=e.colStart;e=Math.min(this.columns.length,h+e.colCount);0<this.Za&&(d=Math.min(d,this.totalSize()-this.O));e=new a.yc(g,d,h,e,this.columns);this.IF(g,d,e,f,c,b)};a.ia.prototype.IF=function(a,c,b,d,e,g){var h;for(h=[];a<c;a++)h.push(this.oa.at(a+this.O,{deferred:!0}));Promise.all(h).then(function(a){b.hJ(a);e.success.call(g.success,
b,d)})};a.ia.prototype.Vd=function(a,c,b){this.qR()?this.kD(a,c,b):(null!=c&&(this.Lg={},this.Lg.oV=a,this.Lg.callbacks=c,this.Lg.tx=b),this.JO(a))};a.b.g("CollectionDataGridDataSource.prototype.fetchCells",{Vd:a.ia.prototype.Vd});a.ia.prototype.TE=function(a){var c,b,d,e,g;c=this.Vl[a];null!=c&&(b=c.mW,d=c.callbacks,e=c.tx,"row"===a&&(g=c.qx),this.mD(b,d,e,g))};a.ia.prototype.KS=function(){this.kD(this.Lg.oV,this.Lg.callbacks,this.Lg.tx,this.Lg.qx)};a.ia.prototype.JO=function(a){var c;a=this.TC(a);
c=a.rowStart;0<this.Za&&(c+=this.O);this.oa.Os(c,a.rowCount).then(function(a){var d=this.oa.at(c,{deferred:!0});this.LT(a.start,a.count);null!=d&&void 0===this.columns?d.then(function(a){this.Sw(a);this.gC()}.bind(this)):this.gC()}.bind(this))};a.ia.prototype.gC=function(){null!=this.Vl&&(this.TE("column"),this.TE("row"));null!=this.Lg&&this.KS();0<this.Za&&a.Kb.t.handleEvent.call(this,"sync",!0)};a.ia.prototype.LT=function(a,c){var b={start:a,count:c};null!=this.Vl.row&&(this.Vl.row.qx=b);null!=
this.Lg&&(this.Lg.qx=b)};a.ia.prototype.Sw=function(a){this.columns=a.keys();-1!=this.columns.indexOf(this.Si)&&this.columns.splice(this.columns.indexOf(this.Si),1)};a.ia.prototype.keys=function(f){var c,b,d,e,g;c=f.row+this.O;b=f.column;var h=this;return a.b.la(function(f){g=h.oa.at(c,{deferred:!0});null!=g?g.then(function(c){d=a.Xi.Pk(c);null==h.columns&&h.Sw(c);e=h.columns[b];f({row:null==d?null:d,column:null==e?null:e})}.bind(h)):f({row:null,column:null})})};a.b.g("CollectionDataGridDataSource.prototype.keys",
{keys:a.ia.prototype.keys});a.ia.prototype.Zd=function(f){var c,b,d;c=f.row;b=f.column;var e=this;return a.b.la(function(a){e.oa.indexOf(c,{deferred:!0}).then(function(c){null==e.columns&&e.oa.first(1,{deferred:!0}).then(function(a){e.Sw(a)}.bind(e));d=e.columns.indexOf(b);a({row:null==c?-1:c,column:null==d?-1:d})}.bind(e))})};a.b.g("CollectionDataGridDataSource.prototype.indexes",{Zd:a.ia.prototype.Zd});a.ia.prototype.getCapability=function(a){return"sort"===a?"column":"move"===a?"row":null};a.b.g("CollectionDataGridDataSource.prototype.getCapability",
{getCapability:a.ia.prototype.getCapability});a.ia.prototype.sort=function(a,c,b){var d,e=a.direction,g=a.key;a=a.axis;null==b&&(b={});"column"===a?(-1<this.oa.Gx&&this.oa.$a()?(this.oa.comparator=g,this.oa.sortDirection="ascending"===e?1:-1):("ascending"===e&&(d=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof Date&&(b=b.toISOString(),d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===e&&(d=function(a,b){var c,
d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),this.oa.comparator=d),this.oa.sort(),null!=c&&null!=c.success&&c.success.call(b.success)):null!=c&&null!=c.error&&c.error.call(b.error,"Axis value not supported")};a.b.g("CollectionDataGridDataSource.prototype.sort",{sort:a.ia.prototype.sort});a.ia.prototype.move=function(a,c){var b;this.oa.get(a,{deferred:!0}).then(function(d){null==
c?(this.oa.remove(d),this.oa.add(d)):(a===c?(b=this.oa.indexOf(c,{deferred:!0}),this.oa.remove(d)):(this.oa.remove(d),b=this.oa.indexOf(c,{deferred:!0})),b.then(function(a){this.oa.add(d,{at:a,FY:!0})}.bind(this)))}.bind(this))};a.b.g("CollectionDataGridDataSource.prototype.move",{move:a.ia.prototype.move});a.ia.prototype.Kq=function(a,c,b,d){var e={source:this};e.operation=a;e.keys={row:c,column:null};e.indexes={row:b,column:d};return e};a.ia.prototype.DQ=function(f){var c,b;this.oa.indexOf(f,{deferred:!0}).then(function(d){b=
a.Xi.Pk(f);c=this.Kq("insert",b,0<d-this.O?d-this.O:0,-1);this.handleEvent("change",c);d<this.Za+this.O&&(d=this.oa.at(this.O+this.Za,{deferred:!0}),null!=d&&d.then(function(a){null!=f&&this.nD(a)}.bind(this)))}.bind(this))};a.ia.prototype.nD=function(f){this.handleEvent("change",this.Kq("delete",a.Xi.Pk(f)))};a.ia.prototype.EQ=function(f){var c,b;this.oa.indexOf(f,{deferred:!0}).then(function(d){b=a.Xi.Pk(f);d=0<d-this.O?d-this.O:-1;c=this.Kq("update",b,d,-1);this.handleEvent("change",c)}.bind(this))};
a.ia.prototype.hQ=function(){this.handleEvent("change",this.Kq("refresh",null))};a.ia.prototype.setPageSize=function(a){this.Za=a};a.b.g("CollectionDataGridDataSource.prototype.setPageSize",{setPageSize:a.ia.prototype.setPageSize});a.ia.prototype.size=function(){return 0===this.oa.length?-1:null!=this.Za&&0<this.Za&&this.oa.size()>this.Za?this.Za:this.oa.size()};a.b.g("CollectionDataGridDataSource.prototype.size",{size:a.ia.prototype.size});a.ia.prototype.totalSize=function(){return null!=this.oa?
this.oa.totalResults:-1};a.b.g("CollectionDataGridDataSource.prototype.totalSize",{totalSize:a.ia.prototype.totalSize});a.ia.prototype.hasMore=function(){return null!=this.oa?this.oa.hasMore:!1};a.b.g("CollectionDataGridDataSource.prototype.hasMore",{hasMore:a.ia.prototype.hasMore});a.ia.prototype.fetch=function(a){this.O=null!=a?null!=a.startIndex?a.startIndex:0:0;this.handleEvent("change",{operation:"sync",pageSize:this.Za})};a.ia.prototype.getCollection=function(){return this.oa};a.b.g("CollectionDataGridDataSource.prototype.getCollection",
{getCollection:a.ia.prototype.getCollection});a.ia.prototype.Ei=function(){return this.columns};a.b.g("CollectionDataGridDataSource.prototype.getColumns",{Ei:a.ia.prototype.Ei});a.ia.prototype.uo=function(){return this.Si};a.b.g("CollectionDataGridDataSource.prototype.getRowHeader",{uo:a.ia.prototype.uo});a.ia.prototype.eI=function(){return this.O};a.b.g("CollectionDataGridDataSource.prototype.getStartIndex",{eI:a.ia.prototype.eI});a.ia.prototype.aI=function(){return this.Za};a.b.g("CollectionDataGridDataSource.prototype.getPageSize",
{aI:a.ia.prototype.aI});a.ia.prototype.getData=function(){return this.data};a.b.g("CollectionDataGridDataSource.prototype.getData",{getData:a.ia.prototype.getData})});
//# sourceMappingURL=oj-modular.map