/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery"],function(a,f){a.Sc=function(a){this.data=a;this.Init()};o_("DataSource",a.Sc,a);a.b.ra(a.Sc,a.b,"oj.DataSource");a.Sc.prototype.Init=function(){this.Wb=[];a.Sc.t.Init.call(this)};a.b.g("DataSource.prototype.Init",{Init:a.Sc.prototype.Init});a.Sc.prototype.on=function(a,b){var d=!1,e;for(e=0;e<this.Wb.length;e++)if(this.Wb[e].eventType==a&&this.Wb[e].eventHandlerFunc==b){d=!0;break}d||this.Wb.push({eventType:a,eventHandlerFunc:b})};a.b.g("DataSource.prototype.on",{on:a.Sc.prototype.on});
a.Sc.prototype.off=function(a,b){var d;for(d=this.Wb.length-1;0<=d;d--)if(this.Wb[d].eventType==a&&this.Wb[d].eventHandlerFunc==b){this.Wb.splice(d,1);break}};a.b.g("DataSource.prototype.off",{off:a.Sc.prototype.off});a.Sc.prototype.handleEvent=function(a,b){var d;for(d=0;d<this.Wb.length;d++){var e=this.Wb[d];e.eventType==a&&e.eventHandlerFunc(b)}};a.b.g("DataSource.prototype.handleEvent",{handleEvent:a.Sc.prototype.handleEvent});a.Sc.prototype.getCapability=function(){return null};a.b.g("DataSource.prototype.getCapability",
{getCapability:a.Sc.prototype.getCapability});a.zc=function(c){a.zc.t.constructor.call(this,c)};o_("TreeDataSource",a.zc,a);a.b.ra(a.zc,a.Sc,"oj.TreeDataSource");a.zc.prototype.Le=function(){return-1};a.zc.prototype.Wd=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.fetchChildren",{Wd:a.zc.prototype.Wd});a.zc.prototype.Dh=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.fetchDescendants",{Dh:a.zc.prototype.Dh});a.zc.prototype.sort=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.sort",
{sort:a.zc.prototype.sort});a.zc.prototype.xo=function(){return{key:null,direction:"none"}};a.b.g("TreeDataSource.prototype.getSortCriteria",{xo:a.zc.prototype.xo});a.zc.prototype.move=function(){a.i.fa()};a.b.g("TreeDataSource.prototype.move",{move:a.zc.prototype.move});a.zc.prototype.Oi=function(){return"valid"};a.b.g("TreeDataSource.prototype.moveOK",{Oi:a.zc.prototype.Oi});a.zc.prototype.getCapability=function(){return null};a.b.g("TreeDataSource.prototype.getCapability",{getCapability:a.zc.prototype.getCapability});
a.ha=function(c,b){this.Ld=c;this.Qo=b;a.ha.t.constructor.call(this)};o_("FlattenedTreeDataSource",a.ha,a);a.b.ra(a.ha,a.Sc,"oj.FlattenedTreeDataSource");a.ha.prototype.Init=function(){var c;a.ha.t.Init.call(this);this.Ld.on("change",this.FQ.bind(this));this.jy=parseInt(this.Qo.fetchSize,10);isNaN(this.jy)&&(this.jy=25);this.$j=parseInt(this.Qo.maxCount,10);isNaN(this.$j)&&(this.$j=500);c=this.Qo.expanded;Array.isArray(c)?this.Hh=c:("all"===c&&(this.Pl=[]),this.Hh=[]);this.Li=[]};a.b.g("FlattenedTreeDataSource.prototype.Init",
{Init:a.ha.prototype.Init});a.ha.prototype.handleEvent=function(c,b){a.ha.t.handleEvent.call(this,c,b)};a.b.g("FlattenedTreeDataSource.prototype.handleEvent",{handleEvent:a.ha.prototype.handleEvent});a.ha.prototype.hp=function(){delete this.Li;delete this.Hh;this.Ld.off("change");this.Ld.hp&&this.Ld.hp()};a.b.g("FlattenedTreeDataSource.prototype.Destroy",{hp:a.ha.prototype.hp});a.ha.prototype.Lx=function(){return this.jy};a.ha.prototype.WH=function(){return this.Hh};a.b.g("FlattenedTreeDataSource.prototype.getExpandedKeys",
{WH:a.ha.prototype.WH});a.ha.prototype.to=function(a){return null!=this.Qo?this.Qo[a]:null};a.b.g("FlattenedTreeDataSource.prototype.getOption",{to:a.ha.prototype.to});a.ha.prototype.getWrappedDataSource=function(){return this.Ld};a.b.g("FlattenedTreeDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.ha.prototype.getWrappedDataSource});a.ha.prototype.cv=function(a){var b,d;b=this.Lx();d=this.$j;return-1===b?-1===a?d:a:-1===a?Math.min(b,a):b};a.ha.prototype.EH=function(a,b){this.cr()?
this.MO(a,b):this.LO(a,b)};a.ha.prototype.LO=function(c,b){var d,e,f,h,k,l;if(c.start>this.Tc()){d=this.lv();if(0>this.Tc()){c.count=Math.min(d,c.count);this.Ld.Wd(null,c,{success:function(a){this.Tq(a,null,0,c,0,b)}.bind(this)});return}if(0<d){e=this.JC();f=e.parent;h=this.Ld.Le(f);k=e.index;l=e.depth;-1===h||k<h-1?(e=this.cv(h),c.start=k+1,c.count=-1===h?e:Math.min(d,Math.min(e,h-c.start)),this.Ld.Wd(f,c,{success:function(a){this.Tq(a,f,l,c,h,b)}.bind(this)})):k===h-1?(d=new a.$c(null,c.start),
null!=b&&null!=b.success&&b.success.call(null,d)):(d=this.iC(f,l,b,d),d||(d=new a.$c(null,c.start),null!=b&&null!=b.success&&b.success.call(null,d)));return}}this.Ux(c,b)};a.ha.prototype.lv=function(){return this.$j-(this.Tc()+1)};a.ha.prototype.Tq=function(c,b,d,e,f,h){var k;k=[];c=new a.ed(c,this.Co.bind(this),e);this.JS(c,b,d,k);-1===f&&0===c.Z()&&null!=b&&0<d?(b=this.iC(b,d,h))||null!=h&&null!=h.success&&h.success.call(null,c):(null!=h&&null!=h.success&&h.success.call(null,c),this.IO(k))};a.ha.prototype.iC=
function(a,b,d,e){var f,h,k,l,m,n,q,r,p;void 0===e&&(e=this.lv());this.KD()&&(f={queueOnly:!0});h=p=this.cv(-1);for(k=this.Tc()-1;0<=k;k--)if(l=this.De(k),m=l.depth,m<b&&(a=l.parent,n=this.Ld.Le(a),l=l.index,(q=-1===n)||l<n-1)){r={};r.start=l+1;q?(r.count=Math.min(e,Math.max(0,h)),f=void 0):r.count=Math.min(e,Math.min(h,n-r.start));if(0==r.count)break;this.Ld.Wd(a,r,{success:function(b){this.Tq(b,a,m,r,n,d)}.bind(this)},f);b=m;h=Math.max(0,h-r.count);if(q||0===m||0===h)break}void 0!=f&&this.Ld.Wd(a,
{start:r.count,count:0},{success:function(b){this.Tq(b,a,m,r,n,d)}.bind(this)});return h!=p};a.ha.prototype.JS=function(a,b,d,e){var f,h,k,l;f=a.Ia();h=a.Z();for(k=0;k<h;k++)l=a.getMetadata(f+k),l=l.key,this.Mp(l,d,f+k,b),this.dr(l)&&e.push(l)};a.ha.prototype.Co=function(a,b){this.dr(a)&&!b.leaf?b.state="expanded":b.state=b.leaf?"leaf":"collapsed"};a.ha.prototype.MO=function(a,b){var d={maxCount:this.$j};0<=this.Tc()&&(d.start=this.De(this.Tc()).key);this.Ld.Dh(null,{success:function(d){this.pQ(d,
a,b)}.bind(this)},d)};a.ha.prototype.pQ=function(c,b,d){var e,f,h;b.start>this.Tc()?(e=this.lv(),f=Math.min(e,b.count),c=new a.ed(c,this.Co.bind(this)),0<=this.Tc()?(h=this.JC(),e={index:0,found:!1,count:0},this.Aw(c,null,0,h,f,e),f=e.index+1):(e={count:0},this.Aw(c,null,0,null,f,e),f=0),null!=d&&null!=d.success&&(c=null!=e?0===e.count?new a.$c(null,b.start):new a.ad(c,f):new a.ad(c),d.success.call(null,c))):this.Ux(b,d)};a.ha.prototype.Aw=function(a,b,d,e,f,h){var k,l,m,n,q;k=a.Ia();l=a.Z();for(m=
0;m<l&&h.count!=f;m++){n=a.getMetadata(k+m);q=n.key;h.checkDepth&&e.depth===d&&(h.found=!0,h.checkDepth=!1);if(null==e||h.found)this.Mp(q,d,k+m,b),h.count+=1,n.state=n.leaf?"leaf":"expanded";null==e||h.found||(q===e.key?n.leaf||this.dr(q)?h.found=!0:h.checkDepth=!0:h.index+=1);a.Gd&&(n=a.Gd(m),null!=n&&this.Aw(n,q,d+1,e,f,h))}};a.ha.prototype.expand=function(a){this.kd(a)};a.b.g("FlattenedTreeDataSource.prototype.expand",{expand:a.ha.prototype.expand});a.ha.prototype.kd=function(c,b){var d,e,f,h;
d=this.Ld.Le(c);e=this.cv(d);f=this.$j;if(this.Tc()+1===f&&(h=this.Gl(c),h==f-1)){this.Tx(c,new a.$c(c,0),0,b);return}0==e?this.Tx(c,new a.$c(c,0),0,b):this.Ld.Wd(c,{start:0,count:e},{success:function(a){this.Tx(c,a,d,b)}.bind(this)})};a.ha.prototype.collapse=function(a){var b,d,e,f,h;b=this.Gl(a)+1;d=this.De(b-1);e=0;d=d.depth;f=this.Tc();for(h=b;h<f+1;h++){var k=this.De(h).depth;if(k>d)e+=1;else if(k==d)break}if(0!=e){this.cr()?this.Pl.push(a):this.mT(a);f=[];for(d=0;d<e;d++)f.push({key:this.De(b+
d).key,index:b+d});this.sF(b,e);this.Ms(f);this.handleEvent("collapse",{rowKey:a})}};a.b.g("FlattenedTreeDataSource.prototype.collapse",{collapse:a.ha.prototype.collapse});a.ha.prototype.dr=function(a){return this.cr()?this.Pl&&0<this.Pl.length?-1===this.tC(a):!0:this.Hh&&0<this.Hh.length?-1<this.CC(a):!1};a.ha.prototype.tC=function(a){return this.IC(this.Pl,a)};a.ha.prototype.CC=function(a){return this.IC(this.Hh,a)};a.ha.prototype.IC=function(a,b){var d,e;e=-1;for(d=0;d<a.length;d++)a[d]===b&&(e=
d);return e};a.ha.prototype.mT=function(a){a=this.CC(a);-1<a&&this.Hh.splice(a,1)};a.ha.prototype.hT=function(a){a=this.tC(a);-1<a&&this.Pl.splice(a,1)};a.ha.prototype.Tx=function(c,b,d,e){var f,h,k,l,m,n,q,r,p,s,t;b=new a.ed(b,this.Co.bind(this));h=f=this.Gl(c)+1;k=b.Ia();l=b.Z();m=this.De(f-1);n=m.depth+1;r=[];for(p=k;p<l;p++)k=b.getMetadata(p),q=k.key,this.dr(q)&&r.push(q),this.ID(f,k,m.key,p,n),f++;this.cr()?this.hT(c):-1===this.Hh.indexOf(c)&&this.Hh.push(c);void 0!=e&&(s=e.queue,t=e.prevNodeSetInfo);
void 0!=t&&(b=new a.ge(t.nodeSet,b,c));if(0!=r.length||void 0!==s&&0!=s.length)void 0===s&&(s=[]),0<r.length&&s.push(r),void 0===t&&(t={},t.firstIndex=h,t.firstKey=c,t.keys=[]),t.nodeSet=b,t.keys.push(c),this.pU(s,t);else{void 0!=t?this.ys(t.firstIndex,t.firstKey,b):this.ys(h,c,b);b=this.$j;-1===d&&l===this.Lx()||d>l||f==b?this.Cu(f):this.Tc()>=b&&this.Cu(b);if(void 0!=t)for(d=0;d<t.keys.length;d++)this.handleEvent("expand",{rowKey:t.keys[d]});this.handleEvent("expand",{rowKey:c})}};a.ha.prototype.pU=
function(a,b){var d,e;d=a[a.length-1];e=d.shift();0===d.length&&a.pop();this.kd(e,{prevNodeSetInfo:b,queue:a})};a.ha.prototype.IO=function(a){var b,d;this.KD()&&(b={queueOnly:!0});for(d=0;d<a.length;d++)d==a.length-1?this.kd(a[d]):this.kd(a[d],b)};a.ha.prototype.ID=function(a,b,d,e,f){b=b.key;a<=this.Tc()?this.Mp(b,f,e,d,a):this.Mp(b,f,e,d)};a.ha.prototype.Cu=function(a,b){var d;void 0==b&&(b=this.Tc()+1-a);d=[];for(var e=0;e<b;e++)d.push({row:this.De(a+e).key,index:a+e});this.sF(a,b);this.Ms(d)};
a.ha.prototype.FQ=function(a){var b,d,e;b=a.operation;d=a.parent;d=Array.isArray(d)?d[d.length-1]:d;e=a.index;"insert"===b?this.sQ(d,e,a.data):"delete"===b?this.lQ(d,e):"refresh"===b&&this.IQ(d)};a.ha.prototype.sQ=function(a,b,d){var e,f;e=this.Gl(a);f=this.De(e).depth+1;e=e+b+1;d=d.getMetadata(d.Ia());this.ID(e,d,a,b,f)};a.ha.prototype.lQ=function(c,b){var d,e,f,h,k;d=this.Gl(c);e=this.De(d);d+=b;f=this.De(d);a.i.assert(f.parent===e&&f.depth===e.depth+1);e=d+1;for(h=this.Tc();e<=h;){k=this.De(e);
if(k.depth!=f.depth)break;e++}this.Cu(d,1)};a.ha.prototype.IQ=function(a){null==a&&this.refresh()};a.ha.prototype.cr=function(){var a=this.Ld.getCapability("fetchDescendants");return void 0!=this.Pl&&null!=a&&"disable"!=a};a.ha.prototype.KD=function(){return"enable"===this.Ld.getCapability("batchFetch")};a.ha.prototype.refresh=function(){this.iN()};a.ha.prototype.Gl=function(a){var b,d,e;b=this.Tc();for(d=0;d<=b;d++)if(e=this.De(d),e.key==a)return d;return-1};a.ha.prototype.getKey=function(a){return 0>
a||a>this.Tc()?null:this.De(a).key};a.ha.prototype.ZV=function(){return{start:0,end:this.Tc()+1}};a.ha.prototype.Ux=function(a,b){null!=b&&null!=b.error&&b.error.call(null)};a.ha.prototype.ys=function(){a.i.fa()};a.ha.prototype.Ms=function(){a.i.fa()};a.ha.prototype.Tc=function(){return this.Li.length-1};a.ha.prototype.JC=function(){return this.Li[this.Tc()]};a.ha.prototype.De=function(a){return this.Li[a]};a.ha.prototype.Mp=function(a,b,d,e,f){var h={};h.key=a;h.depth=b;h.index=d;h.parent=e;void 0===
f?this.Li.push(h):this.Li.splice(f,0,h)};a.ha.prototype.sF=function(a,b){this.Li.splice(a,b)};a.ha.prototype.iN=function(){this.Li.length=0};a.uk=function(){this.id=null;this.depth=0;this.parent=null;this.children=[];this.iy=this.attr=this.title=null};a.uk.prototype.JM=function(a){return function(b,d){return b.attr&&d.attr&&b.attr[a]&&d.attr[a]?b.attr[a]<d.attr[a]?0:1:b[a]<d[a]?0:1}};a.uk.prototype.kO=function(a){return function(b,d){return b.attr&&d.attr&&b.attr[a]&&d.attr[a]?b.attr[a]<d.attr[a]?
1:0:b[a]<d[a]?1:0}};a.uk.prototype.uG=function(a){var b=a.key;"ascending"===a.direction?this.children.sort(this.JM(b)):"descending"===a.direction&&this.children.sort(this.kO(b));for(var b=0,d=this.children.length;b<d;b++)this.children[b].uG(a)};a.bc=function(c){var b;b=new a.uk;c.id||(b.id="root");this.data=this.BB(0,b,c);a.bc.t.constructor.call(this,b)};o_("JsonTreeDataSource",a.bc,a);a.b.ra(a.bc,a.zc,"oj.JsonTreeDataSource");a.bc.prototype.Init=function(){a.bc.t.Init.call(this)};a.b.g("JsonTreeDataSource.prototype.Init",
{Init:a.bc.prototype.Init});a.bc.prototype.BB=function(c,b,d,e){var f,h,k,l,m,n,q;e||(e=0);for(l in d)if("children"==l||0==e&&d instanceof Array)for(f=0==e&&d instanceof Array?d:d[l],e++,q=0;q<f.length;q++){k=f[q];h=new a.uk;k.id||(c++,k.attr?k.attr.id||(k.attr.id="rid_"+c):h.id="rid_"+c);for(m in k)for(n in h)m==n&&"children"!=m&&(h[n]=k[m]),"depth"==n&&(h[n]=e);b.children.push(h);for(n in k)"children"==n&&this.BB(c,b.children[q],k,e)}return b};a.bc.prototype.Le=function(a){a||(a=this.data.id);a=
this.ni(this.data,a);return a.children?a.children.length:0};a.b.g("JsonTreeDataSource.prototype.getChildCount",{Le:a.bc.prototype.Le});a.bc.prototype.Wd=function(c,b,d){var e,f,h,k,l;h=[];c||(c=this.data.id);k=this.ni(this.data,c);b||(b=[],b.start=0,b.count=k.children.length);b.count||(b.count=k.children.length);b.start||(b.start=0);e=b.start;f=Math.min(k.children.length,e+b.count);for(b=e;b<f;b+=1)l=new a.uk,k.children[b].attr&&(l.attr=k.children[b].attr),k.children[b].id&&(l.id=k.children[b].id),
k.children[b].depth&&(l.depth=k.children[b].depth),k.children[b].title&&(l.title=k.children[b].title),k.children[b].parent&&(l.parent=k.children[b].parent),l.iy=0<k.children[b].children.length?!1:!0,h.push(l);c=new a.cd(e,f,h,c);null!=d&&null!=d.success&&d.success.call(null,c)};a.b.g("JsonTreeDataSource.prototype.fetchChildren",{Wd:a.bc.prototype.Wd});a.bc.prototype.Dh=function(c,b){var d,e,f,h;f=[];c||(c=this.data.id);h=this.ni(this.data,c);d=[];d.start=0;d.count=h.children.length;e=d.start;for(d=
Math.min(h.children.length,e+d.count);e<d;e+=1)h.children[e].iy=0<h.children[e].children.length?!1:!0,f.push(h.children[e]);f=new a.cd(0,f.length,f,c);null!=b&&null!=b.success&&b.success.call(null,f)};a.b.g("JsonTreeDataSource.prototype.fetchDescendants",{Dh:a.bc.prototype.Dh});a.bc.prototype.move=function(a,b,d,e){var f;f=b;if(!f||f==this.data.id){if("inside"!=d){console.log("Error: root can not be the reference node if position equals to "+d);return}f||(f=this.data.id)}a=this.ni(null,a);this.ni(a,
f)?console.log("Error: the node to move contains the reference node as its sub-tree."):(b=this.ni(null,f),f=this.sv(f),this.nT(a),"inside"==d?(this.zh(a,a.depth-(b.depth+1)),b.children.push(a)):"before"==d?(this.zh(a,a.depth-b.depth),d=f.children.indexOf(b),-1<d&&(0!=d?f.children.splice(d-1,0,a):f.children.unshift(a))):"after"==d?(this.zh(a,a.depth-b.depth),d=f.children.indexOf(b),-1<d&&f.children.splice(d,0,a)):"first"==d?(this.zh(a,a.depth-b.depth),f.children.unshift(a)):"last"==d&&(this.zh(a,a.depth-
b.depth),f.children.push(a)),null!=e&&null!=e.success&&e.success.call(null,this.data))};a.b.g("JsonTreeDataSource.prototype.move",{move:a.bc.prototype.move});a.bc.prototype.sort=function(a,b){var d;d=this.ni(this.data,this.data.id);d.uG(a);null!=b&&null!=b.success&&b.success.call(null,d)};a.b.g("JsonTreeDataSource.prototype.sort",{sort:a.bc.prototype.sort});a.bc.prototype.sv=function(a,b){var d,e=null;if(a==this.data.id)return null;b||(b=this.data);if(b.children&&0<b.children.length){for(d=0;d<b.children.length;d++)if(b.children[d].id&&
b.children[d].id==a||b.children[d].attr&&b.children[d].attr.id==a)return b;for(d=0;d<b.children.length&&!(e=this.sv(a,b.children[d]));d++);}return e};a.bc.prototype.ni=function(a,b){var d,e=null;a||(a=this.data);if(a.id&&a.id==b||a.attr&&a.attr.id==b)return a;if(null!=a.children)for(d=0;d<a.children.length&&!e;d++)e=a.children[d].id&&a.children[d].id==b||a.children[d].attr&&a.children[d].attr.id==b?a.children[d]:this.ni(a.children[d],b);return e};a.bc.prototype.zh=function(a,b){var d;a.depth-=b;if(a.children&&
0!=a.children.length)for(d=0;d<a.children.length;d++)this.zh(a.children[d],b)};a.bc.prototype.nT=function(a){var b;a.id?b=a.id:a.attr&&(b=a.attr.id);(b=this.sv(b))||(b=this.data);a=b.children.indexOf(a);-1<a&&b.children.splice(a,1)};a.bc.prototype.getCapability=function(a){return"fetchDescendants"===a?"enable":"sort"===a?"default":"batchFetch"===a?"disable":"move"===a?"full":null};a.b.g("JsonTreeDataSource.prototype.getCapability",{getCapability:a.bc.prototype.getCapability});a.cb=function(c,b){a.cb._init(this,
c,b,null)};o_("Row",a.cb,a);a.b.ra(a.cb,a.b,"Row.Row");a.cb.prototype.Init=function(){a.cb.t.Init.call(this)};a.cb.prototype.attributes={};a.b.g("Row.prototype.attributes",{attributes:a.cb.prototype.attributes});a.cb.prototype.context={};a.b.g("Row.prototype.context",{context:a.cb.prototype.context});a.cb.prototype.id=null;a.b.g("Row.prototype.id",{id:a.cb.prototype.id});a.cb.prototype.Oe=null;a.b.g("Row.prototype.idAttribute",{Oe:a.cb.prototype.Oe});a.cb._init=function(a,b,d,e){b=null;a.Init();a.index=
-1;d=d||{};a.attributes={};for(b in e)e.hasOwnProperty(b)&&(a[b]=e[b]);a.rowSet=d.rowSet;a.context=d.context};a.cb.prototype.clone=function(){a.i.fa();return null};a.b.g("Row.prototype.clone",{clone:a.cb.prototype.clone});a.cb.prototype.get=function(){a.i.fa();return null};a.b.g("Row.prototype.get",{get:a.cb.prototype.get});a.cb.prototype.set=function(){a.i.fa();return null};a.b.g("Row.prototype.set",{set:a.cb.prototype.set});a.cb.prototype.keys=function(){a.i.fa();return null};a.b.g("Row.prototype.keys",
{keys:a.cb.prototype.keys});a.cb.prototype.values=function(){a.i.fa();return null};a.b.g("Row.prototype.values",{values:a.cb.prototype.values});a.cb.prototype.pairs=function(){a.i.fa();return null};a.b.g("Row.prototype.pairs",{pairs:a.cb.prototype.pairs});a.Q=function(c,b){a.Q._init(this,c,b,null)};o_("RowSet",a.Q,a);a.Q.prototype.gf=null;a.b.g("RowSet.prototype.comparator",{gf:a.Q.prototype.gf});a.Q.prototype.Tf=!0;a.b.g("RowSet.prototype.sortSupported",{Tf:a.Q.prototype.Tf});a.b.ra(a.Q,a.b,"RowSet.RowSet");
a.Q.prototype.Init=function(){a.Q.t.Init.call(this)};a.Q._init=function(a,b,d,e){var f;a.Wb=[];a.Init();if(e)for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f])};a.Q.prototype.at=function(){a.i.fa();return null};a.b.g("RowSet.prototype.at",{at:a.Q.prototype.at});a.Q.prototype.fetch=function(){a.i.fa()};a.b.g("RowSet.prototype.fetch",{fetch:a.Q.prototype.fetch});a.Q.prototype.get=function(){a.i.fa();return null};a.b.g("RowSet.prototype.get",{get:a.Q.prototype.get});a.Q.prototype.hasMore=function(){a.i.fa();
return!1};a.b.g("RowSet.prototype.hasMore",{hasMore:a.Q.prototype.hasMore});a.Q.prototype.indexOf=function(){a.i.fa();return 0};a.b.g("RowSet.prototype.indexOf",{indexOf:a.Q.prototype.indexOf});a.Q.prototype.isEmpty=function(){a.i.fa();return!0};a.b.g("RowSet.prototype.isEmpty",{isEmpty:a.Q.prototype.isEmpty});a.Q.prototype.size=function(){a.i.fa();return 0};a.b.g("RowSet.prototype.size",{size:a.Q.prototype.size});a.Q.prototype.sort=function(){a.i.fa()};a.b.g("RowSet.prototype.sort",{sort:a.Q.prototype.sort});
a.Q.prototype.totalSize=function(){a.i.fa();return 0};a.b.g("RowSet.prototype.totalSize",{totalSize:a.Q.prototype.totalSize});a.Q.prototype.on=function(a,b){var d=!1,e;for(e=0;e<this.Wb.length;e++)if(this.Wb[e].eventType==a&&this.Wb[e].eventHandlerFunc==b){d=!0;break}d||this.Wb.push({eventType:a,eventHandlerFunc:b})};a.b.g("RowSet.prototype.on",{on:a.Q.prototype.on});a.Q.prototype.off=function(a,b){var d;for(d=0;d<this.Wb.length;d++)if(this.Wb[d].eventType==a&&this.Wb[d].eventHandlerFunc==b){this.Wb.remove(this.Wb[d]);
break}};a.b.g("RowSet.prototype.off",{off:a.Q.prototype.off});a.Q.prototype.Mb=function(a,b){var d;for(d=0;d<this.Wb.length;d++){var e=this.Wb[d];e.eventType==a&&e.eventHandlerFunc(b)}};a.Q.v={ADD:"add",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",CHANGE:"change",REQUEST:"request",SYNC:"sync",ERROR:"error"};o_("RowSet.EventType",a.Q.v,a);a.Q.NL={AX:"added",FX:"deleted",LX:"updated",IX:"none"};o_("RowSet._ROW_STATUSES",a.Q.NL,a);a.Qa=function(c,b){a.Qa._init(this,c,b,null)};o_("ArrayRow",
a.Qa,a);a.b.ra(a.Qa,a.cb,"ArrayRow.ArrayRow");a.Qa.prototype.Init=function(){a.Qa.t.Init.call(this)};a.Qa.prototype.attributes={};a.b.g("ArrayRow.prototype.attributes",{attributes:a.Qa.prototype.attributes});a.Qa.prototype.id=null;a.b.g("ArrayRow.prototype.id",{id:a.Qa.prototype.id});a.Qa.prototype.Oe=null;a.b.g("ArrayRow.prototype.idAttribute",{Oe:a.Qa.prototype.Oe});a.Qa._init=function(a,b,d,e){var f=null;a.Init();a.index=-1;d=d||{};a.attributes=b;for(f in e)e.hasOwnProperty(f)&&(a[f]=e[f]);a.idAttribute=
d.idAttribute;a.context=d.context;a.Tw()};a.Qa.prototype.clone=function(){var c=new this.constructor,b;for(b in this)this.hasOwnProperty(b)&&this[b]!==this.attributes&&(c[b]=this[b]);c.attributes=a.Qa.gh(this.attributes,null);c.Tw();return c};a.b.g("ArrayRow.prototype.clone",{clone:a.Qa.prototype.clone});a.Qa.prototype.get=function(a){return this.attributes[a]};a.b.g("ArrayRow.prototype.get",{get:a.Qa.prototype.get});a.Qa.prototype.set=function(c,b,d){var e={},f=!1;if(arguments&&0<arguments.length)if(1<
arguments.length&&arguments[arguments.length-1]&&(f=!0,e=arguments[arguments.length-1]||{}),a.Qa.vj(c))this.ol(c,e);else for(e=0;e<arguments.length;e+=2)(void 0!==arguments[e]||e<arguments.length-1||!f&&e===arguments.length-1)&&this.ol(arguments[e],arguments[e+1]);return this};a.b.g("ArrayRow.prototype.set",{set:a.Qa.prototype.set});a.Qa.prototype.keys=function(){var a,b=[];for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(a);return b};a.b.g("ArrayRow.prototype.keys",{keys:a.Qa.prototype.keys});
a.Qa.prototype.values=function(){var a,b=[];for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(this.get(a));return b};a.b.g("ArrayRow.prototype.values",{values:a.Qa.prototype.values});a.Qa.prototype.pairs=function(){var a,b=[],d;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(d=[],d.push(a),d.push(this.get(a)),b.push(d));return b};a.b.g("ArrayRow.prototype.pairs",{pairs:a.Qa.prototype.pairs});a.Qa.prototype.hv=function(){return this.idAttribute||"id"};a.Qa.prototype.uv=
function(a){return this[a]instanceof Function?this[a]():this[a]};a.Qa.vj=function(a){var b;if(a&&a instanceof Object)for(b in a)if(a.hasOwnProperty(b))return!0;return!1};a.Qa.prototype.Tw=function(){var a=this.hv();if("string"===f.type(a))this.id=this.attributes[a];else if(f.isArray(a)){var b;this.id=[];for(b=0;b<a.length;b++)this.id[b]=this.attributes[a[b]]}};a.Qa.prototype.Qw=function(c,b){return a.b.dj(this.attributes[c],b)?!1:(this.attributes[c]=b,this.Tw(),a.aa.t.Mb.call(this.rowSet,a.Q.v.CHANGE,
this),!0)};a.Qa.prototype.ol=function(a,b){if(null==a)return!0;var d={},e;if(1<arguments.length)d[a]=b;else for(e in a)a.hasOwnProperty(e)&&(d[e]=a[e]);for(e in d)d.hasOwnProperty(e)&&this.Qw(e,d[e]);return!0};a.Qa.gh=function(c,b){var d;b=b||{};for(d in c)c.hasOwnProperty(d)&&("object"!==typeof c[d]?b.hasOwnProperty(d)?void 0!==c[d]&&(b[d]=c[d]):b[d]=c[d]:b[d]=a.Qa.gh(c[d],null));return b};a.aa=function(c,b){a.aa._init(this,c,b,null)};o_("ArrayRowSet",a.aa,a);a.aa.prototype.gf=null;a.b.g("ArrayRowSet.prototype.comparator",
{gf:a.aa.prototype.gf});a.aa.prototype.Tf=!0;a.b.g("ArrayRowSet.prototype.sortSupported",{Tf:a.aa.prototype.Tf});a.b.ra(a.aa,a.Q,"ArrayRowSet.ArrayRowSet");a.aa.prototype.Init=function(){a.aa.t.Init.call(this)};a.aa._init=function(c,b,d,e){var f;c.Wb=[];c.O=0;c.Init();if(e)for(f in e)e.hasOwnProperty(f)&&(c[f]=e[f]);d=d||{};c.Da=[];c.Jf=[];null!=b&&void 0!==b&&(c.un="id",null!=d&&null!=d.idAttribute&&(c.un=d.idAttribute),c.f=b instanceof Array?b:b(),c.Da=a.aa.vv(c.f,c.un,c),c.Mf=c.f.length,b instanceof
Array||b.subscribe(function(d){var e,f,g=0;f=!0;for(e=0;e<d.length;e++)"deleted"!=d[e].status&&(f=!1);if(0==b().length&&f)c.reset();else{for(e=0;e<d.length;e++)"deleted"===d[e].status&&(f=new a.Qa(d[e].value,{idAttribute:c.un}),f.index=d[e].index-g,c.mi(f,d[e].index-g),g++);for(e=0;e<d.length;e++)"added"===d[e].status&&(f=new a.Qa(d[e].value,{idAttribute:c.un}),f.index=d[e].index,c.add(f,{at:d[e].index}))}},null,"arrayChange"))};a.aa.prototype.add=function(c,b){b=b||{};var d=b.deferred;this.vM(c,
b.at,b);return d?a.b.la(function(a){a()}):null};a.b.g("ArrayRowSet.prototype.add",{add:a.aa.prototype.add});a.aa.prototype.at=function(c,b){b=b||{};if(0>c||c>=this.Da.length)return null;var d=this.Da[c];return b.deferred?a.b.la(function(a){a(d)}):d};a.b.g("ArrayRowSet.prototype.at",{at:a.aa.prototype.at});a.aa.prototype.clone=function(){var a=new this.constructor,b,d;for(b=0;b<this.Da.length;b+=1)(d=this.at(b,null))&&a.add(d.clone(),{at:b});return a};a.b.g("ArrayRowSet.prototype.clone",{clone:a.aa.prototype.clone});
a.aa.prototype.fetch=function(c){c=c||{};this.Xw();try{this.Za=0<c.pageSize?c.pageSize:-1,this.O=null!=c?null!=c.startIndex?c.startIndex:0:0,this.Jf=a.aa.rv(this.Da,this.O,this.Za)}catch(b){this.Hf(c,b);return}c.pageSize=this.Za;c.startIndex=this.O;c.refresh=!0;this.Hf(c,null)};a.b.g("ArrayRowSet.prototype.fetch",{fetch:a.aa.prototype.fetch});a.aa.prototype.get=function(c,b){b=b||{};var d=b.deferred,e,g,h,k=null;for(e=0;e<this.Da.length;e+=1)if(h=this.Da[e],void 0!==h){if(f.isArray(h.id)&&f.isArray(c)){if(h.id.length==
c.length){var l=!0;for(g=0;g<c.length;g++)if(h.id[g]!=c[g]){l=!1;break}l&&(k=h)}}else h.id==c&&(k=h);if(null!=k)return d?a.b.la(function(a){a(k)}):k}return null};a.b.g("ArrayRowSet.prototype.get",{get:a.aa.prototype.get});a.aa.prototype.hasMore=function(){return!1};a.b.g("ArrayRowSet.prototype.hasMore",{hasMore:a.aa.prototype.hasMore});a.aa.prototype.indexOf=function(a,b){b=b||{};return b.deferred?this.get(a.id,null).then(function(a){return a.index}):this.get(a.id).index};a.b.g("ArrayRowSet.prototype.indexOf",
{indexOf:a.aa.prototype.indexOf});a.aa.prototype.isEmpty=function(){return 0===this.Jf.length};a.b.g("ArrayRowSet.prototype.isEmpty",{isEmpty:a.aa.prototype.isEmpty});a.aa.prototype.remove=function(a,b){b=b||{};this.mi(a,-1,b)};a.b.g("ArrayRowSet.prototype.remove",{remove:a.aa.prototype.remove});a.aa.prototype.reset=function(c,b){var d;b=b||{};b.previousRows=this.Da;var e=b.silent;if(void 0===c||null==c||c instanceof Array&&0==c.length){for(d=0;d<this.Da.length;d+=1)this.Da[d]&&(this.Da[d].rowSet=
null);this.Jf=[];this.Da=[];this.Mf=0}else if(this.Da=[],this.Jf=[],this.Mf=0,c instanceof Array)for(d=0;d<c.length;d+=1)this.add(c[d],b);else this.add(c,b);e||a.aa.t.Mb.call(this,a.Q.v.RESET,null)};a.b.g("ArrayRowSet.prototype.reset",{reset:a.aa.prototype.reset});a.aa.prototype.size=function(){return this.Jf.length};a.b.g("ArrayRowSet.prototype.size",{size:a.aa.prototype.size});a.aa.prototype.sort=function(){var c=this.comparator,b;this.Pv()&&(b=this,this.Da.sort(function(d,e){return a.aa.tG(d,e,
c,b,b)}),this.il(0,this.Da),this.Jf=a.aa.rv(this.Da,this.O,this.Za),this.vG=!0,a.aa.t.Mb.call(this,a.Q.v.SORT,null))};a.b.g("ArrayRowSet.prototype.sort",{sort:a.aa.prototype.sort});a.aa.prototype.totalSize=function(){return this.Mf};a.b.g("ArrayRowSet.prototype.totalSize",{totalSize:a.aa.prototype.totalSize});a.aa.prototype.vM=function(c,b,d){var e,f;d=d||{};var h=d.silent;c instanceof Array||(c=[c]);for(d=0;d<c.length;d++){f=c[d];f instanceof a.Qa||(f=new a.Qa(f,{idAttribute:this.un}));this.Jf&&
0!=this.Jf.length||(this.Jf=a.aa.rv(this.Da,this.O,this.Za));if(!0==this.vG&&0<this.Da.length)for(e=0;e<this.Da.length;e++)if(0>a.aa.tG(f,this.Da[e],this.comparator,this,this)){this.Da.splice(e,0,f);f.index=e;break}else{if(e==this.Da.length-1){this.Da.push(f);f.index=e+1;break}}else void 0===b?(this.Da.push(f),f.index=this.Da.length-1):(this.Da.splice(b+d,0,f),f.index=b+d);f.rowSet=this;f.index<=a.aa.av(this.Da,this.O,this.Za)&&this.Jf.splice(f.index,0,f);this.Mf++;this.il(0,this.Da);h||a.aa.t.Mb.call(this,
a.Q.v.ADD,f)}};a.aa.prototype.Av=function(a){return void 0===a?[]:a.split(",")};a.aa.prototype.Bv=function(){return-1===this.sortDirection?"dsc":"asc"};a.aa.prototype.Pv=function(){var a=this.comparator;return void 0!==a&&null!==a};a.aa.prototype.il=function(a,b){for(var d,e=a;e<b.length;e++)(d=b[e])&&(d.index=e)};a.aa.prototype.mi=function(c,b,d){var e,f;d=d||{};var h=d.silent;c instanceof Array||(c=[c]);for(e=0;e<c.length;e++)if(f=c[e],(0>b||!0==this.vG)&&null!=this.get(f.id)&&(b=this.get(f.id).index),
-1<b){void 0!==f&&f.$W===this&&(f.$W=null);var k=a.aa.av(this.Da,this.O,this.Za);this.Da.splice(b,1);b<=k&&this.Jf.splice(b,1);this.Mf--;this.il(0,this.Da);h||(d.index=b,void 0!==f&&(h||a.aa.t.Mb.call(this,a.Q.v.REMOVE,f)))}return f};a.aa.prototype.Xw=function(){a.aa.t.Mb.call(this,a.Q.v.REQUEST,null)};a.aa.prototype.Hf=function(c,b){c=c||{};var d=c.success,e=c.error;null!=b?(a.aa.t.Mb.call(this,a.Q.v.ERROR,b),e&&e.call(this,c,b)):(a.aa.t.Mb.call(this,a.Q.v.SYNC,c),d&&d.call(this,c))};a.aa.ih=function(a,
b,d){if(-1===d){if(a<b)return 1;if(b<a)return-1}else{if(a>b)return 1;if(b>a)return-1}return 0};a.aa.av=function(a,b,d){var e=a.length-1;0<d&&(e=b+d-1,e=e>a.length-1?a.length-1:e);return e};a.aa.kn=function(c,b){return c instanceof a.cb?c.get(b):f.isFunction(c[b])?c[b]():c[b]};a.aa.rv=function(c,b,d){b=a.aa.av(c,b,d);d=[];var e,f;for(e=0;e<=b;e++)f=c[e],f.index=e,d[e]=f;return d};a.aa.vv=function(c,b,d){var e=c.length-1,f=[],h,k;for(h=0;h<=e;h++){var l={},m=null,m=c[h]instanceof a.cb?c[h].pairs():
c[h];for(k in m)m.hasOwnProperty(k)&&(l[k]=m[k]);l=new a.Qa(l,{idAttribute:b});l.index=h;f[h]=l;l.rowSet=d}return f};a.aa.tG=function(c,b,d,e,g){var h;if(f.isFunction(d)){if(1===d.length){h=d.call(g,c);g=d.call(g,b);c=a.hb.Id(h)?h.split(","):[h];b=a.hb.Id(g)?g.split(","):[g];for(d=0;d<c.length;d++)if(h=a.aa.ih(c[d],b[d],e.sortDirection),0!==h)return h;return 0}return d.call(g,c,b)}if(a.hb.Id(d)){var k=d.split(",");for(d=0;d<k.length;d++)if(h=a.aa.kn(c,k[d]),g=a.aa.kn(b,k[d]),h=a.aa.ih(h,g,e.sortDirection),
0!==h)return h}return 0};a.$c=function(a,b){this.GW=a;this.xc=b};o_("EmptyNodeSet",a.$c,a);a.$c.prototype.getParent=function(){return this.GW};a.b.g("EmptyNodeSet.prototype.getParent",{getParent:a.$c.prototype.getParent});a.$c.prototype.Ia=function(){return this.xc};a.b.g("EmptyNodeSet.prototype.getStart",{Ia:a.$c.prototype.Ia});a.$c.prototype.Z=function(){return 0};a.b.g("EmptyNodeSet.prototype.getCount",{Z:a.$c.prototype.Z});a.$c.prototype.getData=function(){return null};a.b.g("EmptyNodeSet.prototype.getData",
{getData:a.$c.prototype.getData});a.$c.prototype.getMetadata=function(){return null};a.b.g("EmptyNodeSet.prototype.getMetadata",{getMetadata:a.$c.prototype.getMetadata});a.ge=function(a,b,d){this.Mi=a;this.ly=b;this.ky=this.SO(d)};o_("MergedNodeSet",a.ge,a);a.ge.prototype.SO=function(a){var b,d,e;b=this.Mi.Ia();for(d=b+this.Mi.Z();b<d;b++)if(e=this.Mi.getMetadata(b).key,a===e)return b;return d-1};a.ge.prototype.getParent=function(){return this.Mi.getParent()};a.b.g("MergedNodeSet.prototype.getParent",
{getParent:a.ge.prototype.getParent});a.ge.prototype.Ia=function(){return this.Mi.Ia()};a.b.g("MergedNodeSet.prototype.getStart",{Ia:a.ge.prototype.Ia});a.ge.prototype.Z=function(){return this.Mi.Z()+this.ly.Z()};a.b.g("MergedNodeSet.prototype.getCount",{Z:a.ge.prototype.Z});a.ge.prototype.getData=function(a){a=this.VC(a);return a.set.getData(a.index)};a.b.g("MergedNodeSet.prototype.getData",{getData:a.ge.prototype.getData});a.ge.prototype.getMetadata=function(a){a=this.VC(a);return a.set.getMetadata(a.index)};
a.b.g("MergedNodeSet.prototype.getMetadata",{getMetadata:a.ge.prototype.getMetadata});a.ge.prototype.VC=function(a){if(a<=this.ky)return{set:this.Mi,index:a};var b=this.ly.Z();return a>this.ky+b?{set:this.Mi,index:a-b}:{set:this.ly,index:a-(this.ky+1)}};a.ed=function(a,b,d){this.jb=a;this.Pf=b;this.Ql=d};o_("NodeSetWrapper",a.ed,a);a.ed.prototype.getParent=function(){return this.jb.getParent()};a.b.g("NodeSetWrapper.prototype.getParent",{getParent:a.ed.prototype.getParent});a.ed.prototype.Ia=function(){return null!=
this.Ql?this.Ql.start:this.jb.Ia()};a.b.g("NodeSetWrapper.prototype.getStart",{Ia:a.ed.prototype.Ia});a.ed.prototype.Z=function(){var a,b;a=this.jb.Ia();b=this.jb.Z();null!=this.Ql&&(this.Ql.start>a?b=Math.min(0,b-(this.Ql.start-a)):this.Ql.start<a&&(b=0));return b};a.b.g("NodeSetWrapper.prototype.getCount",{Z:a.ed.prototype.Z});a.ed.prototype.getData=function(a){return this.jb.getData(a)};a.b.g("NodeSetWrapper.prototype.getData",{getData:a.ed.prototype.getData});a.ed.prototype.getMetadata=function(a){var b;
b=this.jb.getMetadata(a);b.index=a;b.parentKey=this.getParent();this.Pf.call(null,b.key,b);return b};a.b.g("NodeSetWrapper.prototype.getMetadata",{getMetadata:a.ed.prototype.getMetadata});a.ed.prototype.Gd=function(c){return this.jb.Gd&&(c=this.jb.Gd(c),null!=c)?new a.ed(c,this.Pf):null};a.b.g("NodeSetWrapper.prototype.getChildNodeSet",{Gd:a.ed.prototype.Gd});a.cd=function(c,b,d,e){a.i.fc(c,null);a.i.fc(b,null);this.FW=e;this.Ni=c;this.Bs=b;this.Kd=d};o_("JsonNodeSet",a.cd,a);a.cd.prototype.getParent=
function(){return this.FW};a.b.g("JsonNodeSet.prototype.getParent",{getParent:a.cd.prototype.getParent});a.cd.prototype.Ia=function(){return this.Ni};a.b.g("JsonNodeSet.prototype.getStart",{Ia:a.cd.prototype.Ia});a.cd.prototype.Z=function(){return Math.max(0,this.Bs-this.Ni)};a.b.g("JsonNodeSet.prototype.getCount",{Z:a.cd.prototype.Z});a.cd.prototype.getData=function(c){a.i.assert(c<=this.Bs&&c>=this.Ni);c-=this.Ni;return this.Kd[c]?this.Kd[c].attr:null};a.b.g("JsonNodeSet.prototype.getData",{getData:a.cd.prototype.getData});
a.cd.prototype.getMetadata=function(c){var b=[];a.i.assert(c<=this.Bs&&c>=this.Ni);c-=this.Ni;b.key=this.Kd[c].id?this.Kd[c].id:this.Kd[c].attr.id;b.leaf=this.Kd[c].iy;b.depth=this.Kd[c].depth;null==b.leaf&&(b.leaf=this.Kd[c].children&&0<this.Kd[c].children.length?!1:!0);return b};a.b.g("JsonNodeSet.prototype.getMetadata",{getMetadata:a.cd.prototype.getMetadata});a.cd.prototype.zh=function(a,b){var d;b++;a.depth=b;if(a.children&&0!=a.children.length)for(d=0;d<a.children.length;d++)this.zh(a.children[d],
b)};a.cd.prototype.Gd=function(c){var b,d,e;a.i.assert(c<=this.Bs&&c>=this.Ni);c-=this.Ni;d=this.Kd[c].depth;b=this.Kd[c].children;if(0==b.length)return null;c=this.Kd[c].id?this.Kd[c].id:this.Kd[c].attr.id;for(e=0;e<b.length;e++)this.zh(b[e],d);return new a.cd(0,b.length,b,c)};a.b.g("JsonNodeSet.prototype.getChildNodeSet",{Gd:a.cd.prototype.Gd});a.ad=function(a,b){this.jb=a;this.xc=b};o_("FlattenedNodeSet",a.ad,a);a.ad.prototype.getParent=function(){return this.jb.getParent()};a.b.g("FlattenedNodeSet.prototype.getParent",
{getParent:a.ad.prototype.getParent});a.ad.prototype.Ia=function(){return void 0!=this.xc?this.xc:this.jb.Ia()};a.b.g("FlattenedNodeSet.prototype.getStart",{Ia:a.ad.prototype.Ia});a.ad.prototype.Z=function(){void 0===this.As&&(this.As=this.zC(this.jb,0),void 0!=this.xc&&(this.As-=this.xc));return this.As};a.b.g("FlattenedNodeSet.prototype.getCount",{Z:a.ad.prototype.Z});a.ad.prototype.zC=function(a,b){var d,e,f,h;d=a.Ia();e=a.Z();b+=e;if(a.Gd)for(f=0;f<e;f++)h=a.Gd(f+d),null!=h&&(b=this.zC(h,b));
return b};a.ad.prototype.getData=function(a){return this.Yu(this.jb,a,{index:this.jb.Ia()},this.sa)};a.b.g("FlattenedNodeSet.prototype.getData",{getData:a.ad.prototype.getData});a.ad.prototype.getMetadata=function(a){return this.Yu(this.jb,a,{index:this.jb.Ia()},this.DP)};a.b.g("FlattenedNodeSet.prototype.getMetadata",{getMetadata:a.ad.prototype.getMetadata});a.ad.prototype.DP=function(a,b){return a.getMetadata(b)};a.ad.prototype.sa=function(a,b){return a.getData(b)};a.ad.prototype.Yu=function(a,
b,d,e){var f,h,k,l;f=a.Ia();h=a.Z();for(k=0;k<h;k++){l=d.index;if(l===b)return e.call(this,a,k+f);d.index=l+1;if(a.Gd&&(l=a.Gd(k+f),null!=l&&(l=this.Yu(l,b,d,e),null!=l)))return l}return null};a.Kb=function(c){a.Kb.t.constructor.call(this,c)};o_("DataGridDataSource",a.Kb,a);a.b.ra(a.Kb,a.Sc,"oj.DataGridDataSource");a.Kb.prototype.Z=function(){return 0};a.b.g("DataGridDataSource.prototype.getCount",{Z:a.Kb.prototype.Z});a.Kb.prototype.lf=function(){return"exact"};a.b.g("DataGridDataSource.prototype.getCountPrecision",
{lf:a.Kb.prototype.lf});a.Kb.prototype.Xd=function(){a.i.fa()};a.b.g("DataGridDataSource.prototype.fetchHeaders",{Xd:a.Kb.prototype.Xd});a.Kb.prototype.Vd=function(){a.i.fa()};a.b.g("DataGridDataSource.prototype.fetchCells",{Vd:a.Kb.prototype.Vd});a.Kb.prototype.keys=function(){a.i.fa();return null};a.b.g("DataGridDataSource.prototype.keys",{keys:a.Kb.prototype.keys});a.Kb.prototype.Zd=function(){a.i.fa();return null};a.b.g("DataGridDataSource.prototype.indexes",{Zd:a.Kb.prototype.Zd});a.Kb.prototype.sort=
function(){a.i.fa()};a.b.g("DataGridDataSource.prototype.sort",{sort:a.Kb.prototype.sort});a.Kb.prototype.move=function(){a.i.fa()};a.b.g("DataGridDataSource.prototype.move",{move:a.Kb.prototype.move});a.Kb.prototype.Oi=function(){return"valid"};a.b.g("DataGridDataSource.prototype.moveOK",{Oi:a.Kb.prototype.Oi});a.Kb.prototype.getCapability=function(){return null};a.b.g("DataGridDataSource.prototype.getCapability",{getCapability:a.Kb.prototype.getCapability})});
//# sourceMappingURL=oj-modular.map