/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define("ojs/ojcore jquery ojs/ojeditablevalue ojs/ojinputtext ojs/ojvalidation ojs/ojpopup ojs/ojbutton".split(" "),function(a,f){function c(b,c){var d=b.translations.dateTimeRange||{},e=[{category:"hint",entries:["min","max","inRange"]},{category:"messageDetail",entries:["rangeUnderflow","rangeOverflow"]},{category:"messageSummary",entries:["rangeUnderflow","rangeOverflow"]}],g={min:b.min,max:b.max,converter:c};if(!f.isEmptyObject(d))for(var q=0,r=e.length;q<r;q++){var p=d[e[q].category];if(p){for(var s=
{},t=e[q].entries,u=0,x=t.length;u<x;u++)s[t[u]]=p[t[u]];g[e[q].category]=s}}return a.ga.ik(a.jc.VALIDATOR_TYPE_DATETIMERANGE).createValidator(g)}function b(a,b){var c=a.filter("span");b?c.addClass("oj-disabled").removeClass("oj-enabled oj-default"):c.removeClass("oj-disabled").addClass("oj-enabled oj-default")}function d(a,b){b.setHours(a.getHours());b.setMinutes(a.getMinutes());b.setSeconds(a.getSeconds());b.setMilliseconds(a.getMilliseconds());return b}function e(a){return a.delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a",
"mouseout",function(){f(this).removeClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a","mouseover",function(){f(this).addClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a",
"focus",function(){f(this).addClass("oj-focus")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon.oj-component-icon, .oj-datepicker-calendar td a","blur",function(){f(this).removeClass("oj-focus")})}var g=a.ga.yi(a.Xf.CONVERTER_TYPE_DATETIME).createConverter({year:"numeric"});a.La("oj.ojInputDate",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",
_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-only oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelp",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],Ft:"oj-inputdatetime-input-trigger",jM:"oj-inputdatetime-calendar-icon",Cz:"oj-datepicker-current-day",kt:"oj-datepicker-days-cell-over",vA:"oj-datepicker-unselectable",Ez:"oj-datepicker-desc",ht:"oj-datepicker-calendar",kL:"oj-datepicker-div",PK:"oj-datepicker-inline",SK:" oj-inputdatetime-input-container",QK:" oj-inputdatetime-inline",options:{datePicker:{footerLayout:"",
changeMonth:"select",changeYear:"select",currentMonthPos:0,daysOutsideMonth:"hidden",numberOfMonths:1,showOn:"image",stepMonths:"numberOfMonths",stepBigMonths:12,weekDisplay:"none",yearRange:"c-10:c+10"},converter:a.ga.yi(a.Xf.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit"}),max:void 0,min:void 0,dayFormatter:null},_InitOptions:function(b,c){function d(a){return this.options.converter.parse(a)}var e=[{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},
{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},{attribute:"value",defaultOptionValue:null,coerceDomValue:d},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"min",defaultOptionValue:null,coerceDomValue:d},{attribute:"max",defaultOptionValue:null,coerceDomValue:d}];this._super(b,c);a.ud.Ji(e,c,this)},vp:function(){this.ef=null;this.Tv=!1;this.En=4;this.Yh=this.lg=this.lh=this.Gf=this.kg=0;this.an={};var a=this.element[0].nodeName.toLowerCase();
this.Td="div"===a||"span"===a;this.Bc=e(f("\x3cdiv id\x3d'"+this.Sh(this.kL)+"' role\x3d'region' aria-describedby\x3d'"+this.Sh(this.Ez)+"' class\x3d'oj-datepicker-content'\x3e\x3c/div\x3e"));f("body").append(this.Bc);if(this.Td)this._WIDGET_CLASS_NAMES+=this.QK,this._CLASS_NAMES="";else{this._WIDGET_CLASS_NAMES+=this.SK;var b=this;this.tr=this.Bc.ojPopup({initialFocus:"none",rootAttributes:{"class":"datetimepicker-dropdown"},open:function(){b.Bc.find(".oj-datepicker-calendar").focus()}})}},_ComponentCreate:function(){this.vp();
var b=this._super();this.options.dayMetaData&&(this.options.dayFormatter=function(b){return function(c){return a.DayMetaDataBinding.getMetaData(b,0,[c.fullYear,c.month,c.date])}}(this.options.dayMetaData));this.Fr(this.Eq());this.Td?(this.element.append(this.Bc),this.element.addClass(this.PK),this.Bc.css("display","block")):this.Nt();return b},Rh:function(){var a=this._superApply(arguments);this.VB(this.options.disabled);return a},_setOption:function(b,c,d){var e=null;if("value"===b)return c||(c=
null),e=this._super(b,c,d),this.Fr(c),this.jh()&&this.si(),e;if("dayMetaData"===b)this._setOption("dayFormatter",function(b){return a.DayMetaDataBinding.getMetaData(c,0,[b.fullYear,b.month,b.date])},d);else return e=this._super(b,c,d),"disabled"===b?this.VB(c):"max"===b||"min"===b?(this.an[a.jc.VALIDATOR_TYPE_DATETIMERANGE]=this.Qq("min"),this.pk()):"readOnly"===b&&c?this.hide():"dayFormatter"===b&&(this.an[a.jc.VALIDATOR_TYPE_DATERESTRICTION]=this.Qq("dayFormatter"),this.pk()),"datePicker"===b&&
"currentMonthPos"===d.subkey&&this.Fr(this.options.value),d={max:!0,min:!0,dayFormatter:!0,datePicker:!0,translations:!0},this.jh()&&b in d&&this.si(),e},_destroy:function(){var a=this._super();this.element.off("focus");this.ef&&this.ef.remove();this.Td&&(this.element.removeProp("disabled"),this.element.removeProp("readonly"));this.Bc.remove();return a},jh:function(){return this.Td||this.tr.ojPopup("isOpen")},Nt:function(){var a=this.options.datePicker.showOn,b=f("\x3cspan\x3e").addClass(this.Ft);
if("focus"===a)this.element.on("focus",f.proxy(this.show,this));a=f("\x3cspan/\x3e").addClass(this.jM+" oj-clickable-icon oj-component-icon");b.append(a);var c=this;a.on("click",function(){c.jh()?c.hide():c.show();return!1}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});this.ef=b;this.element.after(b)},tO:function(a){var b;b=!1;var c=f.ui.keyCode,d=this.wp();
if(this.jh())switch(a.keyCode){case 84:a.altKey&&a.ctrlKey&&(this.Bc.find(".oj-datepicker-current").focus(),b=!0);break;case c.TAB:this.hide();break;case c.ENTER:return b=f("td."+this.kt+":not(."+this.Cz+")",this.Bc),b[0]&&this.RF(this.Gf,this.lg,b[0],a),a.preventDefault(),a.stopPropagation(),!1;case c.ESCAPE:this.hide();this.element.focus();b=!0;break;case c.PAGE_UP:a.ctrlKey&&a.altKey?this.Bd(-this.options.datePicker.stepBigMonths,"M",!0):a.altKey?this.Bd(-1,"Y",!0):this.Bd(-this.rn(),"M",!0);b=
!0;break;case c.PAGE_DOWN:a.ctrlKey&&a.altKey?this.Bd(+this.options.datePicker.stepBigMonths,"M",!0):a.altKey?this.Bd(1,"Y",!0):this.Bd(+this.rn(),"M",!0);b=!0;break;case c.END:this.kg=this.Fq(this.lg,this.Gf);this.si(!0);b=!0;break;case c.HOME:this.kg=1;this.si(!0);b=!0;break;case c.LEFT:this.Bd(d?1:-1,"D",!0);a.originalEvent.altKey&&this.Bd(a.ctrlKey?-this.options.datePicker.stepBigMonths:-this.rn(),"M",!0);b=!0;break;case c.UP:this.Bd(-7,"D",!0);b=!0;break;case c.RIGHT:this.Bd(d?-1:1,"D",!0);a.originalEvent.altKey&&
this.Bd(a.ctrlKey?+this.options.datePicker.stepBigMonths:+this.rn(),"M",!0);b=!0;break;case c.DOWN:this.Bd(7,"D",!0),b=!0}else a.keyCode===c.HOME&&a.ctrlKey&&(this.show(),b=!0);b&&(a.preventDefault(),a.stopPropagation())},si:function(a){this.En=4;var b=this.YO();this.Bc.empty().append(b.html);var c=f("button",this.Bc);0<c.length&&f.each(c,function(a,b){f(b).ojButton()});this.KM();this.Bc.find("."+this.kt+" a").mouseover();b.BH&&this.Bc.find(".oj-datepicker-calendar").attr("aria-activedescendant",
b.BH);b=this.pv();c=b[1];this.Bc.removeClass("oj-datepicker-multi-2 oj-datepicker-multi-3 oj-datepicker-multi-4").width("");1<c&&this.Bc.addClass("oj-datepicker-multi-"+c).css("width",17*c+"em");this.Bc[(1!==b[0]||1!==b[1]?"add":"remove")+"Class"]("oj-datepicker-multi");this.jh()&&this.element.is(":visible")&&!this.element.is(":disabled")&&(a||this.Td?(a=this.Bc.find(".oj-datepicker-calendar"),a[0]!==document.activeElement&&a.focus()):this.element[0]!==document.activeElement&&this.element.focus())},
Bd:function(a,b,c){this.options.disabled||(this.GA(a+("M"===b?this.options.datePicker.currentMonthPos:0),b),this.si(c))},eQ:function(){var a=new Date;this.kg=a.getDate();this.lh=this.Gf=a.getMonth();this.Yh=this.lg=a.getFullYear();this.Bd()},SF:function(b,c){var d=parseInt(b.options[b.selectedIndex].value,10);"M"===c?this.Gf=this.lh=d:this.lg=this.Yh=d;f("#"+this.Sh(this.ht)).html(this.options.monthWide[this.lh]+" "+g.format(a.Ba.dateToLocalIso(new Date(this.Yh,this.lh,1))));this.Bd()},RF:function(b,
c,e,g){f(e).hasClass(this.vA)||this.options.disabled||(this.kg=f("a",e).html(),this.Gf=b,this.lg=c,(b=this.options.value?a.Ba.isoToLocalDate(this.options.value):null)?(c=new Date(this.lg,this.Gf,this.kg),d(b,c),b=c):b=new Date(this.lg,this.Gf,this.kg),b=a.Ba.dateToLocalIso(b),c=this.kc().format(b),this.hg(c),this.Ad(b,g),this.hide())},Eu:function(b,c){return b?"string"===typeof b?a.Ba.isoToLocalDate(b):new Date(b.getTime()):c},Fr:function(a){a=this.Eu(a,this.gD());this.kg=a.getDate();this.lh=this.Gf=
a.getMonth();this.Yh=this.lg=a.getFullYear();this.GA()},rn:function(){var a=this.options.datePicker.stepMonths;return f.isNumeric(a)?a:this.options.datePicker.numberOfMonths},KM:function(){var a=this.rn(),b=this;this.Bc.find("[data-handler]").map(function(){f(this).bind(this.getAttribute("data-event"),{prev:function(c){b.Bd(-a,"M",!0);c.preventDefault()},next:function(c){b.Bd(+a,"M",!0);c.preventDefault()},today:function(a){if("keyup"===a.type&&13===a.keyCode||"click"===a.type)b.eQ(),a.preventDefault(),
a.stopPropagation()},selectDay:function(a){b.RF(+this.getAttribute("data-month"),+this.getAttribute("data-year"),this,a);return!1},selectMonth:function(){b.SF(this,"M");return!1},selectYear:function(){b.SF(this,"Y");return!1},calendarKey:function(a){b.tO(a)}}[this.getAttribute("data-handler")])})},rS:function(a,b,c){b=b?new Date(b.getFullYear(),b.getMonth(),b.getDate()):null;c=c?new Date(c.getFullYear(),c.getMonth(),c.getDate()):null;return null!==b&&a<b||null!==c&&a>c},YO:function(){var b,c,d,e,
f,g,r=this.options.dayWide,p=this.options.dayNarrow,s=this.options.monthWide,t=this.options.monthAbbreviated,u=this.options.firstDayOfWeek,x,v,A,w,B,C,N,P="",y,K,z,L,M,E,J,F,I=new Date,I=new Date(I.getFullYear(),I.getMonth(),I.getDate()),Q=this.wp();g=this.options.datePicker.footerLayout;var H=this.pv(),D=this.options.datePicker.currentMonthPos,Z=this.options.dayFormatter;F=null;var aa=1!==H[0]||1!==H[1],V=this.Jq("min"),T=this.Jq("max"),D=this.lh-D,R=this.Yh,ba=new Date(this.lg,this.Gf,this.kg),
G=new Date(this.Eq()),X=G.getDate(),ea=G.getMonth(),da=G.getFullYear(),S=this.options.disabled,ca=this.J("weekText");G.setHours(0);G.setMinutes(0);G.setSeconds(0);G.setMilliseconds(0);0>D&&(D+=12,R--);if(T)for(b=new Date(T.getFullYear(),T.getMonth()-H[0]*H[1]+1,T.getDate()),b=V&&b<V?V:b;new Date(R,D,1)>b;)D--,0>D&&(D=11,R--);this.lh=D;this.Yh=R;b=this.J("prevText");b=this.fB(-1,R,D)&&!S?"\x3ca href\x3d'#' class\x3d'oj-datepicker-prev-icon oj-enabled oj-default oj-component-icon oj-clickable-icon' data-handler\x3d'prev' data-event\x3d'click' title\x3d'"+
b+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-prev-icon oj-disabled oj-component-icon oj-clickable-icon' title\x3d'"+b+"'\x3e\x3c/a\x3e";c=this.J("nextText");c=this.fB(1,R,D)&&!S?"\x3ca href\x3d'#' class\x3d'oj-datepicker-next-icon oj-enabled oj-default oj-component-icon oj-clickable-icon' data-handler\x3d'next' data-event\x3d'click' title\x3d'"+c+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-next-icon oj-disabled oj-component-icon oj-clickable-icon' title\x3d'"+c+"'\x3e\x3c/a\x3e";d=this.J("currentText");
f="";e="\x3cbutton type\x3d'button' class\x3d'oj-datepicker-current oj-priority-secondary' data-handler\x3d'today' data-event\x3d'click keyup'\x3e"+d+"\x3c/button\x3e";if(1<g.length){d=0;g=[{index:g.indexOf("today"),content:this.QD(I)?e:""}];for(g.sort(function(a,b){return a.index-b.index});d<g.length&&0>g[d].index;)d++;for(;d<g.length;)f+=g[d++].content;0<f.length&&(f="\x3cdiv class\x3d'oj-datepicker-buttonpane'\x3e"+f+"\x3c/div\x3e")}g=this.options.datePicker.weekDisplay;d=this.options.datePicker.daysOutsideMonth;
e="";x="all";for(v=0;v<H[0];v++){A="";this.En=4;for(w=0;w<H[1];w++){x="all";y="";if(aa){y+="\x3cdiv class\x3d'oj-datepicker-group";if(1<H[1])switch(w){case 0:y+=" oj-datepicker-group-first";x=Q?"right":"left";break;case H[1]-1:y+=" oj-datepicker-group-last";x=Q?"left":"right";break;default:y+=" oj-datepicker-group-middle",x=""}y+="'\x3e"}y+="\x3cdiv class\x3d'oj-datepicker-header"+(S?" oj-disabled ":" oj-enabled oj-default ")+"'\x3e"+(/all|left/.test(x)&&0===v?Q?c:b:"")+(/all|right/.test(x)&&0===
v?Q?b:c:"")+this.ZO(D,R,V,T,0<v||0<w,s,t)+"\x3c/div\x3e\x3ctable class\x3d'oj-datepicker-calendar"+(S?" oj-disabled ":" oj-enabled oj-default ")+"' tabindex\x3d-1 data-handler\x3d'calendarKey' data-event\x3d'keydown' aria-readonly\x3d'true' role\x3d'grid' aria-labelledby\x3d'"+this.Sh(this.ht)+"'\x3e\x3cthead role\x3d'presentation'\x3e\x3ctr role\x3d'row'\x3e";K="number"===g?"\x3cth class\x3d'oj-datepicker-week-col'\x3e"+this.J("weekHeader")+"\x3c/th\x3e":"";for(x=0;7>x;x++)z=(x+parseInt(u,10))%7,
K+="\x3cth role\x3d'columnheader' aria-label\x3d'"+r[z]+"'"+(5<=(x+u+6)%7?" class\x3d'oj-datepicker-week-end'":"")+"\x3e\x3cspan title\x3d'"+r[z]+"'\x3e"+p[z]+"\x3c/span\x3e\x3c/th\x3e";y+=K+"\x3c/tr\x3e\x3c/thead\x3e\x3ctbody role\x3d'presentation'\x3e";K=this.Fq(R,D);R===da&&D===ea&&(X=Math.min(X,K));x=(this.qP(R,D)-u+7)%7;K=Math.ceil((x+K)/7);this.En=K=aa?this.En>K?this.En:K:K;z=new Date(R,D,1-x);for(L=0;L<K;L++){y+="\x3ctr role\x3d'row'\x3e";x=this.kc().ko(a.Ba.dateToLocalIso(z));M="none"===g?
"":"\x3ctd class\x3d'oj-datepicker-week-col' role\x3d'rowheader' aria-label\x3d'"+ca+" "+x+"'\x3e"+x+"\x3c/td\x3e";for(x=0;7>x;x++){J=z.getMonth()!==D;B=z.getTime()===G.getTime();C="oj-dp-"+L+"-"+x;(N=z.getTime()===ba.getTime()&&D===this.Gf)&&(P=C);E=[!0,""];F=z.getFullYear();var W=z.getMonth(),fa=z.getDate();Z&&(F=Z({fullYear:F,month:W+1,date:fa}))&&(E=[!F.disabled,F.className||""],F.tooltip&&E.push(F.tooltip));W=z.getTime()===G.getTime();F=J&&"selectable"!==d||!E[0]||this.rS(z,V,T);M+="\x3ctd role\x3d'gridcell' aria-disabled\x3d'"+
!!F+"' aria-selected\x3d'"+B+"' id\x3d'"+C+"' class\x3d'"+(5<=(x+u+6)%7?" oj-datepicker-week-end":"")+(J?" oj-datepicker-other-month":"")+(N?" "+this.kt:"")+(F||S?" "+this.vA+" oj-disabled":" oj-enabled ")+(J&&"hidden"===d?"":" "+E[1]+(B?" "+this.Cz:"")+(z.getTime()===I.getTime()?" oj-datepicker-today":""))+"'"+(J&&"hidden"===d||!E[2]?"":" title\x3d'"+E[2].replace(/'/g,"\x26#39;")+"'")+(F?"":" data-handler\x3d'selectDay' data-event\x3d'click' data-month\x3d'"+z.getMonth()+"' data-year\x3d'"+z.getFullYear()+
"'")+"\x3e"+(J&&"hidden"===d?"\x26#xa0;":F||S?"\x3cspan class\x3d'oj-disabled'\x3e"+z.getDate()+"\x3c/span\x3e":"\x3ca class\x3d'oj-enabled"+(W?" oj-selected":"")+(J?" oj-priority-secondary":"")+"' "+(W||N?"":"tabindex\x3d'-1' ")+" href\x3d'#'\x3e"+z.getDate()+"\x3c/a\x3e")+"\x3c/td\x3e";z.setDate(z.getDate()+1)}y+=M+"\x3c/tr\x3e"}D++;11<D&&(D=0,R++);y+="\x3c/tbody\x3e\x3c/table\x3e"+(aa?"\x3c/div\x3e"+(0<H[0]&&w===H[1]-1?"\x3cdiv class\x3d'oj-datepicker-row-break'\x3e\x3c/div\x3e":""):"");A+=y}e+=
A}return{html:e+f,BH:P}},ZO:function(b,c,d,e,f,q,r){var p,s,t,u,x=this.options.datePicker.changeMonth,v=this.options.datePicker.changeYear,A=a.Fa.DI()?"before":"after",w="\x3cdiv class\x3d'oj-datepicker-title' role\x3d'header'\x3e",B="",C=this.options.disabled;if(f||"none"===x)B+="\x3cspan class\x3d'oj-datepicker-month'\x3e"+q[b]+"\x3c/span\x3e";else{p=d&&d.getFullYear()===c;s=e&&e.getFullYear()===c;B+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-month "+(C?"oj-disabled' disabled":"oj-enabled'")+
" data-handler\x3d'selectMonth' data-event\x3d'change' role\x3d'listbox'\x3e";for(t=0;12>t;t++)(!p||t>=d.getMonth())&&(!s||t<=e.getMonth())&&(B+="\x3coption role\x3d'option' value\x3d'"+t+"' aria-selected\x3d'"+(t===b?"true' selected\x3d'selected'":"false'")+"\x3e"+r[t]+"\x3c/option\x3e");B+="\x3c/select\x3e"}"before"===A&&(w+=B+(f||"select"!==x||"select"!==v?"\x26#xa0;":""));if(!this.Oh)if(this.Oh="",f||"none"===v)w+="\x3cspan class\x3d'oj-datepicker-year'\x3e"+g.format(a.Ba.dateToLocalIso(new Date(c,
b,1)))+"\x3c/span\x3e";else{p=this.options.datePicker.yearRange.split(":");u=(new Date).getFullYear();s=function(a){a=a.match(/c[+\-].*/)?c+parseInt(a.substring(1),10):a.match(/[+\-].*/)?u+parseInt(a,10):parseInt(a,10);return isNaN(a)?u:a};r=s(p[0]);p=Math.max(r,s(p[1]||""));r=d?Math.max(r,d.getFullYear()):r;p=e?Math.min(p,e.getFullYear()):p;for(this.Oh+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-year "+(C?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectYear' data-event\x3d'change' role\x3d'listbox'\x3e";r<=
p;r++)this.Oh+="\x3coption role\x3d'option' value\x3d'"+r+"' aria-selected\x3d'"+(r===c?"true' selected\x3d'selected'":"false'")+"\x3e"+g.format(a.Ba.dateToLocalIso(new Date(r,b,1)))+"\x3c/option\x3e";this.Oh+="\x3c/select\x3e";w+=this.Oh;this.Oh=null}"after"===A&&(w+=(f||"select"!==x||"select"!==v?"\x26#xa0;":"")+B);w+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.Sh(this.ht)+"'\x3e"+q[b]+" "+g.format(a.Ba.dateToLocalIso(new Date(c,b,1)))+"\x3c/span\x3e";w+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+
this.Sh(this.Ez)+"'\x3e"+this.J("datePicker")+"\x3c/span\x3e";return w+"\x3c/div\x3e"},GA:function(a,b){var c=this.Yh+("Y"===b?a:0),d=this.lh+("M"===b?a:0),e=Math.min(this.kg,this.Fq(c,d))+("D"===b?a:0),c=new Date(c,d,e);this.kg=c.getDate();this.lh=this.Gf=c.getMonth();this.Yh=this.lg=c.getFullYear()},pv:function(){var a=this.options.datePicker.numberOfMonths,a="string"===typeof a?parseInt(a,10):a;return null==a?[1,1]:"number"===typeof a?[1,a]:a},Jq:function(a){return this.Eu(this.options[a],null)},
Fq:function(a,b){return 32-(new Date(a,b,32)).getDate()},qP:function(a,b){return(new Date(a,b,1)).getDay()},fB:function(a,b,c){var d=this.pv();b=new Date(b,c+(0>a?a:d[0]*d[1]),1);0>a&&b.setDate(this.Fq(b.getFullYear(),b.getMonth()));return this.QD(b)},QD:function(a){var b,c,d=this.Jq("min"),e=this.Jq("max"),f=null,g=null;if(b=this.options.datePicker.yearRange)b=b.split(":"),c=(new Date).getFullYear(),f=parseInt(b[0],10),g=parseInt(b[1],10),b[0].match(/[+\-].*/)&&(f+=c),b[1].match(/[+\-].*/)&&(g+=
c);return(!d||a.getTime()>=d.getTime())&&(!e||a.getTime()<=e.getTime())&&(!f||a.getFullYear()>=f)&&(!g||a.getFullYear()<=g)},VB:function(a){this.ef&&b(this.ef.children(),a);a&&this.hide();this.Td&&this.si()},et:function(){this.Td||this._superApply(arguments)},rw:function(a){this.Td||this._superApply(arguments)},qr:function(a){if(!this.Td){this._superApply(arguments);var b=f.ui.keyCode,c=!1;if(this.jh())switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:this.Bc.find(".oj-datepicker-calendar").focus(),
c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.show(),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},hg:function(a){this.Td||this._superApply(arguments);this.Fr(this.Eq());this.jh()&&this.si()},kc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDate.prototype.options.converter},sk:function(){return this.options.value||""},_GetDefaultStyleClass:function(){return"oj-inputdate"},ym:function(){var b=this._superApply(arguments);if(null!=this.options.min||
null!=this.options.max)this.an[a.jc.VALIDATOR_TYPE_DATETIMERANGE]=this.Qq("min");null!=this.options.dayFormatter&&(this.an[a.jc.VALIDATOR_TYPE_DATERESTRICTION]=this.Qq("dayFormatter"));return f.extend(this.an,b)},Qq:function(b){var d=null;"min"===b||"max"===b?d=c(this.options,this.kc()):"dayFormatter"===b&&(b={dayFormatter:this.options.dayFormatter,converter:this.kc()},f.extend(b,this.options.translations.dateRestriction||{}),d=a.ga.ik(a.jc.VALIDATOR_TYPE_DATERESTRICTION).createValidator(b));return d},
gD:function(){var a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},Eq:function(){return this.Eu(this.options.value,this.gD())},getNodeBySubId:function(a){var b=null,c=a.subId,d=this.Bc;if(c)switch(c){case "oj-datepicker-content":b=d;break;case "oj-inputdatetime-calendar-icon":b=f(".oj-inputdatetime-calendar-icon",this.ef);break;case "oj-datepicker-prev-icon":b=f(".oj-datepicker-prev-icon",d);break;case "oj-datepicker-next-icon":b=f(".oj-datepicker-next-icon",
d);break;case "oj-datepicker-month":b=f(".oj-datepicker-month",d);break;case "oj-datepicker-year":b=f(".oj-datepicker-year",d);break;case "oj-datepicker-current":b=f(".oj-datepicker-current",d);break;default:b=null}return b||this._superApply(arguments)},hide:function(){this.jh()&&!this.Td&&(this.tr.ojPopup("close"),"focus"===this.options.datePicker.showOn&&(this.Tv=!0),this.element.focus());return this},refresh:function(){return this._superApply(arguments)||this},show:function(){if(!(this.jh()||this.options.disabled||
this.options.readOnly))if(this.Tv)this.Tv=!1;else{var b=this.wp();this.Bc.empty();this.si();var c=this.widget(),c=c.is("[id]")?c.attr("id"):c.uniqueId().attr("id");this.tr.ojPopup("widget").attr(a.da.cg,c);this.tr.ojPopup("open",this.element,{my:b?"right top":"left top",at:b?"right bottom":"left bottom",collision:"fit"});return this}}});a.Components.Ey({ojInputDate:{firstDayOfWeek:a.Components.Vj(function(){return a.Fa.XH()}),dayWide:a.Components.Vj(function(){return a.Fa.Kx("wide")}),dayNarrow:a.Components.Vj(function(){return a.Fa.Kx("narrow")}),
monthWide:a.Components.Vj(function(){return a.Fa.ts("wide")}),monthAbbreviated:a.Components.Vj(function(){return a.Fa.ts("abbreviated")})}});a.La("oj.ojInputTime",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-time-only oj-component oj-inputdatetime oj-inputdatetime-input-container",_INPUT_HELPER_KEY:"inputHelp",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],ZL:"ojInputTime",Ft:"oj-inputdatetime-input-trigger",kM:"oj-inputdatetime-time-icon",
options:{converter:a.ga.yi(a.Xf.CONVERTER_TYPE_DATETIME).createConverter({hour:"2-digit",hour12:!0,minute:"2-digit"}),max:void 0,min:void 0,datePickerComp:null,timePicker:{timeIncrement:"00:30:00:00"}},_InitOptions:function(b,c){function d(a){return this.options.converter.parse(a)}var e=[{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"title",defaultOptionValue:""},{attribute:"placeholder",defaultOptionValue:""},{attribute:"value",defaultOptionValue:null,coerceDomValue:d},
{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"min",defaultOptionValue:null,coerceDomValue:d},{attribute:"max",defaultOptionValue:null,coerceDomValue:d}];this._super(b,c);a.ud.Ji(e,c,this)},vp:function(){this.ax={};this.mg=this.options.datePickerComp;this.me=f("\x3cdiv id\x3d'"+this.Sh(this.ZL)+"' class\x3d'oj-listbox-drop' style\x3d'display:none'\x3e\x3c/div\x3e");f("body").append(this.me);var a=this;this.ur=this.me.ojPopup({initialFocus:"none",rootAttributes:{"class":"datetimepicker-dropdown"},
open:function(){var b=f("[aria-selected]",a.me);1===b.length&&f(b);f("ul",a.me).focus()}})},ao:function(){return this.ur.ojPopup("isOpen")},_ComponentCreate:function(){this.vp();var a=this._superApply(arguments);this.pg()&&!this.LD()&&(this._CLASS_NAMES="");this.Nt();return a},Rh:function(){var a=this._superApply(arguments);b(this.ef.children(),this.options.disabled);return a},_setOption:function(d,e,f){var g=null;if("value"===d)return e||(e=null),g=this._super(d,e,f),this.yq(),g;g=this._superApply(arguments);
"disabled"===d?(e&&this.hide(),b(this.ef.children(),e)):"max"!==d&&"min"!==d||this.pg()?"readOnly"===d&&e&&this.hide():(this.ax[a.jc.VALIDATOR_TYPE_DATETIMERANGE]=c(this.options,this.kc()),this.pk());(d in{max:!0,min:!0,converter:!0}||"timePicker"===d&&"timeIncrement"in e)&&this.yq();return g},_destroy:function(){var a=this._super();this.ef&&this.ef.remove();this.me.remove();return a},et:function(){this.Cj()&&this._superApply(arguments)},qr:function(a){if(this.Cj()){this._superApply(arguments);var b=
f.ui.keyCode,c=!1;if(this.ao())switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:f("ul",this.me).focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.show(),c=!0}if(c||a.keyCode===b.ENTER)return a.preventDefault(),a.stopPropagation(),!1}},Nt:function(){var a=this.Cj(),b=a?f(f("\x3cspan\x3e").addClass(this.Ft)):f("+ span",this.element),c=f("\x3cspan/\x3e").addClass(this.kM+" oj-clickable-icon oj-component-icon");b.append(c);var d=this;
c.on("click",function(){d.ao()?d.hide():d.show()}).on("mouseenter",function(){f(this).addClass("oj-hover")}).on("mousedown",function(){f(this).addClass("oj-active")}).on("mouseleave",function(){f(this).removeClass("oj-hover oj-active")});this.ef=b;a&&this.element.after(b)},WQ:function(a,b,c){return null!==b&&a<b||null!==c&&a>c},bQ:function(){return this.pg()?this.mg.widget.mI():this.options.value},yq:function(){var b=this.bQ(),c=this.kc(),d=f("\x3cul class\x3d'oj-listbox-results' tabindex\x3d'-1' role\x3d'listbox'\x3e\x3c/ul\x3e"),
c=b?c.format(b):"",e=[],g,b=b?a.Ba.isoToLocalDate(b):new Date;b.setHours(0);b.setMinutes(0);b.setSeconds(0);b.setMilliseconds(0);e=this.$P(b);c=c||e[0].value;this.me.empty();b=0;for(g=e.length;b<g;b++){var q=e[b].value,r=e[b].minMaxRange,p=f("\x3cli class\x3d'oj-listbox-result "+(r?"oj-disabled":"")+"' role\x3d'presentation'\x3e"),s=this.uuid+"_sel"+b,r=f("\x3cdiv class\x3d'oj-listbox-result-label' "+(r?"aria-disabled ":"")+"data-value\x3d'"+q+"' role\x3d'option' id\x3d'"+s+"'\x3e"+e[b].label+"\x3c/li\x3e");
c===q&&(r.attr("aria-selected","true"),p.addClass("oj-hover"),d.attr("aria-activedescendant",s));p.append(r);d.append(p)}this.me.append(d);f(".oj-listbox-result",d).on("mousemove",function(){var a=f(this);a.hasClass("oj-disabled")||(f(".oj-hover",d).removeClass("oj-hover"),a.addClass("oj-hover"),d.attr("aria-activedescendant",a.children()[0].id))});var t=this;d.on("click",function(a){var b=f(a.target);b.hasClass("oj-disabled")||void 0!==b.attr("aria-disabled")||(t.hide(),t.VE(a))}).on("keydown",function(a){t.vU(a)})},
$P:function(b){var c=[],d=this.kc();if(b){var e=this.options.timePicker.timeIncrement.split(":"),f=this.pg()?this.mg.widget.options.min:this.options.min,g=this.pg()?this.mg.widget.options.max:this.options.max,f=f?a.Ba.isoToLocalDate(f):null,g=g?a.Ba.isoToLocalDate(g):null;if(4===e.length){var r=parseInt(e[0].substring(0),10),p=parseInt(e[1],10),s=parseInt(e[2],10),e=parseInt(e[3],10),t=new Date(b),u="";do u=d.format(a.Ba.dateToLocalIso(t)),c.push({label:u,value:u,minMaxRange:this.WQ(t,f,g)}),t.setHours(t.getHours()+
r),t.setMinutes(t.getMinutes()+p),t.setSeconds(t.getSeconds()+s),t.setMilliseconds(t.getMilliseconds()+e);while(t.getDate()===b.getDate())}else throw Error("timeIncrement value should be in the format of hh:mm:ss:SS");}return c},vU:function(a){if(this.ao()){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();this.element.focus();c=!0;break;case b.UP:this.RE(a,"prev");c=!0;break;case b.DOWN:this.RE(a,"next");c=!0;break;case b.ENTER:this.VE(a),c=!0}if(c)return a.preventDefault(),
a.stopPropagation(),!1}},RE:function(a,b){var c=f(".oj-hover",this.me),d=f("ul",this.me);if(1===c.length){var e=c[b]();1===e.length&&(c.removeClass("oj-hover"),e.addClass("oj-hover"),d.attr("aria-activedescendant",e.children()[0].id))}},VE:function(a){var b=this.me,c=f("[aria-selected]",b),d=f("ul",b),b=f(".oj-hover div",b);1===b.length&&(1===c.length&&(c.removeAttr("aria-selected"),c.parent().removeClass("oj-hover")),b.attr("aria-selected","true"),b.parent().addClass("oj-hover"),this.hg(b.attr("data-value")),
this.Ad(b.attr("data-value"),a),d.attr("aria-activedescendant",b[0].id),this.hide(),this.element.focus(),this.pg()&&this.mg.widget.hide())},rw:function(a){this.Cj()&&this._superApply(arguments)},show:function(){if(!this.options.disabled&&!this.options.readOnly){this.pg()&&this.mg.widget.hide();this.yq();this.me.width(this.element.parent().width());this.me.css({position:"relative"});var b=this.wp(),c=this.widget(),c=c.is("[id]")?c.attr("id"):c.uniqueId().attr("id");this.ur.ojPopup("widget").attr(a.da.cg,
c);this.ur.ojPopup("open",this.element,{my:b?"right top":"left top",at:b?"right bottom":"left bottom",collision:"fit"})}},hide:function(){this.ao()&&(this.ur.ojPopup("close"),this.element.focus())},refresh:function(){return this._superApply(arguments)||this},hg:function(a){this.Cj()&&this._superApply(arguments);this.ao()&&this.yq()},Ad:function(b,c,e){if(this.pg()){this._super(b,null,e);try{b=this.kc().parse(b);var f=this.mg.widget.mI(),g=f?a.Ba.isoToLocalDate(f):new Date,q=a.Ba.dateToLocalIso(d(b?
a.Ba.isoToLocalDate(b):new Date,g));this.mg.widget.uX(q,c)}catch(r){}}else this._superApply(arguments)},xm:function(){return this.Cj()},Cj:function(){return!this.pg()||this.LD()},_GetDefaultStyleClass:function(){return"oj-inputtime"},sk:function(){return this.options.value||""},ym:function(){var b=this._superApply(arguments);null==this.options.min&&null==this.options.max||this.pg()||(this.ax[a.jc.VALIDATOR_TYPE_DATETIMERANGE]=c(this.options,this.kc()));return f.extend(this.ax,b)},kc:function(){return this.options.converter?
this._superApply(arguments):f.oj.ojInputTime.prototype.options.converter},PX:function(){},pg:function(){return null!==this.mg},LD:function(){return this.mg.inline},getNodeBySubId:function(a){var b=null,c=a.subId;"oj-listbox-drop"===c?b=this.me:"oj-inputdatetime-time-icon"===c&&(b=f(".oj-inputdatetime-time-icon",this.ef));return b||this._superApply(arguments)},widget:function(){return this.Cj()?this._super():this.mg.widget.widget()}});a.La("oj.ojInputDateTime",f.oj.ojInputDate,{version:"1.0.0",widgetEventPrefix:"oj",
_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-time oj-component oj-inputdatetime",_INPUT_HELPER_KEY:"inputHelpBoth",options:{converter:a.ga.yi(a.Xf.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",hour12:!0,minute:"2-digit"}),timePicker:{timeIncrement:"00:30:00:00"}},vp:function(){this._super();this.Rr=this.element;this.vr=this.Qr=this.df=null},_ComponentCreate:function(){var b=this._super(),c=this.fD(this.kc());if(null===c)throw Error("Plase use ojInputDate if you do not have time portion");
if(this.Td){var d=f("\x3cinput type\x3d'text'\x3e");d.insertAfter(this.element);this.Rr=d}this.df=this.Rr.ojInputTime({converter:c,value:a.Ba.dateToLocalIso(this.Eq()),timePicker:this.options.timePicker,datePickerComp:{widget:this,inline:this.Td}});this.df.ojInputTime("option","disabled",this.options.disabled);return b},_setOption:function(a,b,c){var d=this._superApply(arguments);"value"===a&&(this.vr=b);this.df&&(a in{disabled:!0,readOnly:!0}?this.df.ojInputTime("option",a,b):"timePicker"===a&&"timeIncrement"===
c.subkey?this.df.ojInputTime("option","timePicker.timeIncrement",b.timeIncrement):"converter"===a&&(this.Qr=null,this.df.ojInputTime("option",a,this.fD(this.kc()))));return d},_destroy:function(){var a=this._super();this.df.ojInputTime("destroy");this.Td&&this.Rr.remove();return a},fD:function(b){if(null!==this.Qr)return this.Qr;b=b.resolvedOptions();var c={},d="hour hour12 minute second millisecond timeFormat".split(" "),e,g;e=0;for(g=d.length;e<g;e++)d[e]in b&&("timeFormat"===d[e]&&(c.formatType=
"time"),c[d[e]]=b[d[e]]);if(f.isEmptyObject(c))throw Error("Plase use ojInputDateTime's converter is lacking the time portion");return this.Qr=b=a.ga.yi(a.Xf.CONVERTER_TYPE_DATETIME).createConverter(c)},uX:function(a,b){this.hg(this.kc().format(a));this.Ad(a,b)},mI:function(){return this.isValid()?this.options.value:this.vr?this.kc().parse(this.vr):null},Ad:function(a,b,c){this._superApply(arguments);this.vr=a},qr:function(a){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.UP:case b.DOWN:a.shiftKey&&
(this.df.ojInputTime("show"),c=!0)}return c?(a.preventDefault(),a.stopPropagation(),!1):this._superApply(arguments)},show:function(){this.df.ojInputTime("hide");return this._super()},showTimePicker:function(){this.hide();return this.df.ojInputTime("show")},hideTimePicker:function(){return this.df.ojInputTime("hide")},refresh:function(){return this._superApply(arguments)||this},getNodeBySubId:function(a){var b=a.subId;return"oj-listbox-drop"===b||"oj-inputdatetime-time-icon"===b?this.df.ojInputTime("getNodeBySubId",
a):this._superApply(arguments)},kc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDateTime.prototype.options.converter},_GetMessagingLauncherElement:function(){return this.Td?this.Rr:this._super()},_GetDefaultStyleClass:function(){return"oj-inputdatetime"},rp:function(){return"oj-ojInputDate"}})});
//# sourceMappingURL=oj-modular.map