/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){var c=!1;f(document).mouseup(function(){c=!1});a.La("oj.ojResizable",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0,maxHeight:null,maxWidth:null,minHeight:10,minWidth:10,alsoResize:!1,animate:!1,animateDuration:"slow",animateEasing:"swing",containment:!1,ghost:!1,grid:!1,handles:"e,s,se",helper:!1,resize:null,start:null,stop:null},gS:function(){var a=
this;this.element.bind("mousedown."+this.widgetName,function(c){return a.fS(c)}).bind("click."+this.widgetName,function(c){if(!0===f.data(c.target,a.widgetName+".preventClickEvent"))return f.removeData(c.target,a.widgetName+".preventClickEvent"),c.stopImmediatePropagation(),!1})},eS:function(){this.element.unbind("."+this.widgetName);this.lr&&this.document.unbind("mousemove."+this.widgetName,this.lr).unbind("mouseup."+this.widgetName,this.lw)},fS:function(a){if(!c){this.ji&&this.mr(a);this.kr=a;var d=
this,e=1===a.which,g="string"===typeof this.options.cancel&&a.target.nodeName?f(a.target).closest(this.options.cancel).length:!1;if(!e||g||!this.dS(a))return!0;(this.So=!this.options.delay)||setTimeout(function(){d.So=!0},this.options.delay);if(this.sE(a)&&this.So&&(this.ji=!1!==this.uE(a),!this.ji))return a.preventDefault(),!0;!0===f.data(a.target,this.widgetName+".preventClickEvent")&&f.removeData(a.target,this.widgetName+".preventClickEvent");this.lr=function(a){return d.hS(a)};this.lw=function(a){return d.mr(a)};
this.document.bind("mousemove."+this.widgetName,this.lr).bind("mouseup."+this.widgetName,this.lw);a.preventDefault();return c=!0}},hS:function(a){if(f.ui.IY&&(!document.documentMode||9>document.documentMode)&&!a.button||!a.which)return this.mr(a);if(this.ji)return this.tE(a),a.preventDefault();this.sE(a)&&this.So&&((this.ji=!1!==this.uE(this.kr,a))?this.tE(a):this.mr(a));return!this.ji},mr:function(a){this.document.unbind("mousemove."+this.widgetName,this.lr).unbind("mouseup."+this.widgetName,this.lw);
this.ji&&(this.ji=!1,a.target===this.kr.target&&f.data(a.target,this.widgetName+".preventClickEvent",!0),this.iS(a));return c=!1},sE:function(a){return Math.max(Math.abs(this.kr.pageX-a.pageX),Math.abs(this.kr.pageY-a.pageY))>=this.options.distance},uY:function(){return this.So},pw:function(a){return parseInt(a,10)||0},uc:function(a){return!isNaN(parseInt(a,10))},rD:function(a,c){if("hidden"===f(a).css("overflow"))return!1;var e=c&&"left"===c?"scrollLeft":"scrollTop",g=!1;if(0<a[e])return!0;a[e]=
1;g=0<a[e];a[e]=0;return g},_ComponentCreate:function(){this._super();var a,c,e,g,h,k=this;a=this.options;this.element.addClass("oj-resizable");f.extend(this,{Gs:this.element,wr:[],og:null});this.handles=a.handles||(f(".oj-resizable-handle",this.element).length?{NY:".oj-resizable-n",CY:".oj-resizable-e",VY:".oj-resizable-s",Yc:".oj-resizable-w",XY:".oj-resizable-se",aZ:".oj-resizable-sw",OY:".oj-resizable-ne",RY:".oj-resizable-nw"}:"e,s,se");if(this.handles.constructor===String)for("all"===this.handles&&
(this.handles="n,e,s,w,se,sw,ne,nw"),a=this.handles.split(","),this.handles={},c=0;c<a.length;c++)e=f.trim(a[c]),h="oj-resizable-"+e,g=f("\x3cdiv class\x3d'oj-resizable-handle "+h+"'\x3e\x3c/div\x3e"),this.handles[e]=".oj-resizable-"+e,this.element.append(g);this.rT=function(){for(var a in this.handles)this.handles[a].constructor===String&&(this.handles[a]=this.element.children(this.handles[a]).first().show())};this.rT();this.SQ=f(".oj-resizable-handle",this.element);this.SQ.mouseover(function(){k.bJ||
(this.className&&(g=this.className.match(/oj-resizable-(se|sw|ne|nw|n|e|s|w)/i)),k.axis=g&&g[1]?g[1]:"se")});this.gS()},_destroy:function(){this.eS();f(this.Gs).removeClass("oj-resizable oj-resizable-disabled oj-resizable-resizing").removeData("resizable").removeData("oj-resizable").unbind(".resizable").find(".oj-resizable-handle").remove();return this},dS:function(a){var c,e,g=!1;for(c in this.handles)if(e=f(this.handles[c])[0],e===a.target||f.contains(e,a.target))g=!0;return!this.options.disabled&&
g},uE:function(a){var c,e,g;g=this.options;c=this.element.position();var h=this.element;this.bJ=!0;/absolute/.test(h.css("position"))?h.css({position:"absolute",top:h.css("top"),left:h.css("left")}):h.is(".ui-draggable")&&h.css({position:"absolute",top:c.top,left:c.left});this.sT();c=this.pw(this.helper.css("left"));e=this.pw(this.helper.css("top"));g.containment&&(c+=f(g.containment).scrollLeft()||0,e+=f(g.containment).scrollTop()||0);this.offset=this.helper.offset();this.position={left:c,top:e};
this.size={width:h.width(),height:h.height()};this.Sf={width:h.width(),height:h.height()};this.Qi={left:c,top:e};this.Ps={width:h.outerWidth()-h.width(),height:h.outerHeight()-h.height()};this.MW={left:a.pageX,top:a.pageY};this.wg=this.Sf.width/this.Sf.height||1;g=f(".oj-resizable-"+this.axis).css("cursor");f("body").css("cursor","auto"===g?this.axis+"-resize":g);h.addClass("oj-resizable-resizing");this.Cw("start",a);this.BM(a);this.yN(a);return!0},tE:function(a){var c,e=this.helper,g={},h=this.MW;
c=a.pageX-h.left||0;var h=a.pageY-h.top||0,k=this.eh[this.axis];this.Wl={top:this.position.top,left:this.position.left};this.Xl={width:this.size.width,height:this.size.height};if(!k)return!1;c=k.apply(this,[a,c,h]);this.PU(a.shiftKey);a.shiftKey&&(c=this.NU(c,a));c=this.zT(c,a);this.IU(c);this.Cw("resize",a);this.AM(a,this.ui());this.xN(a,this.ui());this.position.top!==this.Wl.top&&(g.top=this.position.top+"px");this.position.left!==this.Wl.left&&(g.left=this.position.left+"px");this.size.width!==
this.Xl.width&&(g.width=this.size.width+"px");this.size.height!==this.Xl.height&&(g.height=this.size.height+"px");e.css(g);!this.og&&this.wr.length&&this.OS();f.isEmptyObject(g)||this._trigger("resize",a,this.ui());return!1},iS:function(a){this.bJ=!1;f("body").css("cursor","auto");this.element.removeClass("oj-resizable-resizing");this.Cw("stop",a);this.CM(a);this.zN(a);return!1},PU:function(a){var c,e,f,h;h=this.options;h={minWidth:this.uc(h.minWidth)?h.minWidth:0,maxWidth:this.uc(h.maxWidth)?h.maxWidth:
Infinity,minHeight:this.uc(h.minHeight)?h.minHeight:0,maxHeight:this.uc(h.maxHeight)?h.maxHeight:Infinity};a&&(a=h.minHeight*this.wg,e=h.minWidth/this.wg,c=h.maxHeight*this.wg,f=h.maxWidth/this.wg,a>h.minWidth&&(h.minWidth=a),e>h.minHeight&&(h.minHeight=e),c<h.maxWidth&&(h.maxWidth=c),f<h.maxHeight&&(h.maxHeight=f));this.SU=h},IU:function(a){this.offset=this.helper.offset();this.uc(a.left)&&(this.position.left=a.left);this.uc(a.top)&&(this.position.top=a.top);this.uc(a.height)&&(this.size.height=
a.height);this.uc(a.width)&&(this.size.width=a.width)},NU:function(a){var c=this.position,e=this.size,f=this.axis;this.uc(a.height)?a.width=a.height*this.wg:this.uc(a.width)&&(a.height=a.width/this.wg);"sw"===f&&(a.left=c.left+(e.width-a.width),a.top=null);"nw"===f&&(a.top=c.top+(e.height-a.height),a.left=c.left+(e.width-a.width));return a},zT:function(a){var c=this.SU,e=this.axis,f=this.uc(a.width)&&c.maxWidth&&c.maxWidth<a.width,h=this.uc(a.height)&&c.maxHeight&&c.maxHeight<a.height,k=this.uc(a.width)&&
c.minWidth&&c.minWidth>a.width,l=this.uc(a.height)&&c.minHeight&&c.minHeight>a.height,m=this.Qi.left+this.Sf.width,n=this.position.top+this.size.height,q=/sw|nw|w/.test(e),e=/nw|ne|n/.test(e);k&&(a.width=c.minWidth);l&&(a.height=c.minHeight);f&&(a.width=c.maxWidth);h&&(a.height=c.maxHeight);k&&q&&(a.left=m-c.minWidth);f&&q&&(a.left=m-c.maxWidth);l&&e&&(a.top=n-c.minHeight);h&&e&&(a.top=n-c.maxHeight);a.width||a.height||a.left||!a.top?a.width||a.height||a.top||!a.left||(a.left=null):a.top=null;return a},
OS:function(){if(this.wr.length){var a,c,e,f,h,k=this.helper||this.element;for(a=0;a<this.wr.length;a++){h=this.wr[a];if(!this.yl)for(this.yl=[],e=[h.css("borderTopWidth"),h.css("borderRightWidth"),h.css("borderBottomWidth"),h.css("borderLeftWidth")],f=[h.css("paddingTop"),h.css("paddingRight"),h.css("paddingBottom"),h.css("paddingLeft")],c=0;c<e.length;c++)this.yl[c]=(parseInt(e[c],10)||0)+(parseInt(f[c],10)||0);h.css({height:k.height()-this.yl[0]-this.yl[2]||0,width:k.width()-this.yl[1]-this.yl[3]||
0})}}},sT:function(){this.element.offset();this.helper=this.element},eh:{e:function(a,c){return{width:this.Sf.width+c}},w:function(a,c){return{left:this.Qi.left+c,width:this.Sf.width-c}},n:function(a,c,e){return{top:this.Qi.top+e,height:this.Sf.height-e}},s:function(a,c,e){return{height:this.Sf.height+e}},se:function(a,c,e){return f.extend(this.eh.s.apply(this,arguments),this.eh.e.apply(this,[a,c,e]))},sw:function(a,c,e){return f.extend(this.eh.s.apply(this,arguments),this.eh.w.apply(this,[a,c,e]))},
ne:function(a,c,e){return f.extend(this.eh.n.apply(this,arguments),this.eh.e.apply(this,[a,c,e]))},nw:function(a,c,e){return f.extend(this.eh.n.apply(this,arguments),this.eh.w.apply(this,[a,c,e]))}},Cw:function(a,c){"resize"!==a&&this._trigger(a,c,this.ui())},BM:function(){function a(b){f(b).each(function(){var a=f(this);a.data("oj-resizable-alsoresize",{width:parseInt(a.width(),10),height:parseInt(a.height(),10),left:parseInt(a.css("left"),10),top:parseInt(a.css("top"),10)})})}var c=this.options;
"object"!==typeof c.alsoResize||c.alsoResize.parentNode?a(c.alsoResize):c.alsoResize.length?(c.alsoResize=c.alsoResize[0],a(c.alsoResize)):f.each(c.alsoResize,function(c){a(c)})},AM:function(a,c){function e(a,b){f(a).each(function(){var a=f(this),e=f(this).data("oj-resizable-alsoresize"),g={};f.each(b&&b.length?b:a.parents(c.Gs[0]).length?["width","height"]:["width","height","top","left"],function(a,b){var c=(e[b]||0)+(l[b]||0);c&&0<=c&&(g[b]=c||null)});a.css(g)})}var g=this.options,h=this.Sf,k=this.Qi,
l={height:this.size.height-h.height||0,width:this.size.width-h.width||0,top:this.position.top-k.top||0,left:this.position.left-k.left||0};"object"!==typeof g.alsoResize||g.alsoResize.nodeType?e(g.alsoResize,null):f.each(g.alsoResize,function(a,b){e(a,b)})},CM:function(){f(this).removeData("resizable-alsoresize")},yN:function(){var a,c,e,g,h,k=this,l=k.element;e=k.options.containment;if(l=e instanceof f?e.get(0):/parent/.test(e)?l.parent().get(0):e)k.gs=f(l),/document/.test(e)||e===document?(k.hs=
{left:0,top:0},k.qH={left:0,top:0},k.Ri={element:f(document),left:0,top:0,width:f(document).width(),height:f(document).height()||document.body.parentNode.scrollHeight}):(a=f(l),c=[],f(["Top","Right","Left","Bottom"]).each(function(e,f){c[e]=k.pw(a.css("padding"+f))}),k.hs=a.offset(),k.qH=a.position(),k.rH={height:a.innerHeight()-c[3],width:a.innerWidth()-c[1]},e=k.hs,g=k.rH.height,h=k.rH.width,h=k.rD(l,"left")?l.scrollWidth:h,g=k.rD(l)?l.scrollHeight:g,k.Ri={element:l,left:e.left,top:e.top,width:h,
height:g})},xN:function(a,c){var e,f,h,k;e=this.options;f=this.hs;k=this.position;var l=a.shiftKey;h={top:0,left:0};var m=this.gs,n=!0;m[0]!==document&&/static/.test(m.css("position"))&&(h=f);k.left<(this.og?f.left:0)&&(this.size.width+=this.og?this.position.left-f.left:this.position.left-h.left,l&&(this.size.height=this.size.width/this.wg,n=!1),this.position.left=e.helper?f.left:0);k.top<(this.og?f.top:0)&&(this.size.height+=this.og?this.position.top-f.top:this.position.top,l&&(this.size.width=this.size.height*
this.wg,n=!1),this.position.top=this.og?f.top:0);this.offset.left=this.Ri.left+this.position.left;this.offset.top=this.Ri.top+this.position.top;e=Math.abs((this.og?this.offset.left-h.left:this.offset.left-f.left)+this.Ps.width);f=Math.abs((this.og?this.offset.top-h.top:this.offset.top-f.top)+this.Ps.height);h=this.gs.get(0)===this.element.parent().get(0);k=/relative|absolute/.test(this.gs.css("position"));h&&k&&(e-=Math.abs(this.Ri.left));e+this.size.width>=this.Ri.width&&(this.size.width=this.Ri.width-
e,l&&(this.size.height=this.size.width/this.wg,n=!1));f+this.size.height>=this.Ri.height&&(this.size.height=this.Ri.height-f,l&&(this.size.width=this.size.height*this.wg,n=!1));n||(this.position.left=c.Wl.left,this.position.top=c.Wl.top,this.size.width=c.Xl.width,this.size.height=c.Xl.height)},zN:function(){var a=this.options,c=this.hs,e=this.qH,g=this.gs,h=f(this.helper),k=h.offset(),l=h.outerWidth()-this.Ps.width,h=h.outerHeight()-this.Ps.height;this.og&&!a.animate&&/relative/.test(g.css("position"))&&
f(this).css({left:k.left-e.left-c.left,width:l,height:h});this.og&&!a.animate&&/static/.test(g.css("position"))&&f(this).css({left:k.left-e.left-c.left,width:l,height:h})},ui:function(){return{Gs:this.Gs,element:this.element,helper:this.helper,position:this.position,size:this.size,Sf:this.Sf,Qi:this.Qi,Xl:this.Xl,Wl:this.Wl}}})})();(function(){a.La("oj.ojDialog",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancelBehavior:"icon",dragAffordance:"title-bar",initialVisibility:"hide",
modality:"modal",position:{my:"center",at:"center",of:window,collision:"fit",fZ:function(a){var b=f(this).css(a).offset().top;0>b&&f(this).css("top",a.top-b)}},resizeBehavior:"resizable",role:"dialog",title:null,beforeClose:null,beforeOpen:null,close:null,focus:null,open:null,resize:null,resizeStart:null,resizeStop:null},_ComponentCreate:function(){this._super();this.LW={display:this.element[0].style.display,width:this.element[0].style.width,height:this.element[0].style.height};this.Qi={parent:this.element.parent(),
index:this.element.parent().children().index(this.element)};this.qy=this.element.attr("title");this.options.title=this.options.title||this.qy;this.ZN();this.element.show().removeAttr("title").addClass("oj-dialog-content oj-dialog-default-content").appendTo(this.Wa);this.Us=!1;if(this.element.find(".oj-dialog").length){var a=this;this.element.find(".oj-dialog-header").each(function(b,d){var e=f(d);if(!e.closest(".oj-dialog-body").length)return a.eo=e,a.Us=!0,!1})}else this.eo=this.element.find(".oj-dialog-header"),
this.eo.length&&(this.Us=!0);this.Us?(this.WN(this.eo),this.eo.prependTo(this.Wa),"icon"===this.options.cancelBehavior&&this.uB(this.eo)):this.YN();this.Nh=this.element.find(".oj-dialog-footer");this.VN(this.Nh);this.Nh&&(this.Nh.addClass("oj-helper-clearfix"),this.Nh.appendTo(this.Wa));"title-bar"===this.options.dragAffordance&&f.fn.draggable&&this.hE();this._isOpen=!1;this.BU();this._super()},_init:function(){"show"===this.options.initialVisibility&&this.open()},LA:function(){return this.document.find("body").eq(0)},
_destroy:function(){this._isOpen&&this.close();this.RB();this.Nh&&(this.Nh.removeClass("oj-helper-clearfix"),f("#"+this.LE).replaceWith(this.Nh));this.dp&&(this.dp.remove(),this.dp=null);this.Ny=null;if(this.Us){var a=this.Wa.find(".oj-dialog-header");a&&f("#"+this.ME).replaceWith(a)}this.element.removeUniqueId().removeClass("oj-dialog-content oj-dialog-default-content").css(this.LW).detach();this.Wa.stop(!0,!0).remove();this.qy&&this.element.attr("title",this.qy);f("#"+this.xw).replaceWith(this.element);
this.nO()},refresh:function(){this._super();this.mE()},widget:function(){return this.Wa},disable:f.noop,enable:f.noop,close:function(a){var b=this;this._isOpen&&!1!==this._trigger("beforeClose",a)&&(this._isOpen=!1,this.pC=null,this.RB(),this.QG(),this.opener.filter(":focusable").focus().length||f(this.document[0].activeElement).blur(),this._hide(this.Wa,null,function(){b._trigger("close",a)}),f("#"+this.xw).replaceWith(f("#"+this.px)))},isOpen:function(){return this._isOpen},mw:function(a,b){var d=
!!this.Wa.nextAll(":visible").insertBefore(this.Wa).length;d&&!b&&this._trigger("focus",a);return d},open:function(a){if(!1!==this._trigger("beforeOpen",a)){var b=this;this._isOpen?this.mw()&&this.en():(this._isOpen=!0,this.opener=f(this.document[0].activeElement),this.fT(),this.KN(),this.NE(),this.mw(null,!0),this._show(this.Wa,null,function(){b.en();b._trigger("focus")}),this.iE(),this._trigger("open"))}},en:function(){var c=this.pC;c&&0<c.length&&a.da.Ol(this.Wa[0],c[0])||(c||(c=this.element.find("[autofocus]")),
c.length||(c=this.element.find(":tabbable")),c.length||this.Nh&&(c=this.Nh.find(":tabbable")),c.length||this.Ny&&(c=this.Ny.filter(":tabbable")),c.length||(c=this.Wa),c.eq(0).focus())},_keepFocus:function(a){a.preventDefault();a=this.document[0].activeElement;this.Wa[0]===a||f.contains(this.Wa[0],a)||this.en()},Rh:function(){this._super();this.mE()},mE:function(){var a=f("\x3cdiv\x3e\x3c/div\x3e");this.IB=this.Wa.css("min-width");"none"!=this.IB?(a.width(this.IB),this.Vm=a.width(),this.uc(this.Vm)&&
(this.Vm=Math.round(this.Vm))):this.Vm="none";this.GB=this.Wa.css("max-width");"none"!=this.GB?(a.width(this.GB),this.Um=a.width(),this.uc(this.Um)&&(this.Um=Math.round(this.Um))):this.Um="none";this.HB=this.Wa.css("min-height");"none"!=this.HB?(a.height(this.HB),this.mj=a.height(),this.uc(this.mj)&&(this.mj=Math.round(this.mj))):this.mj="none";this.FB=this.Wa.css("max-height");"none"!=this.FB?(a.height(this.FB),this.Tm=a.height(),this.uc(this.Tm)&&(this.Tm=Math.round(this.Tm))):this.Tm="none";this.EB=
this.Wa.css("height");"auto"!=this.EB?(a.height(this.EB),this.Xh=a.height(),this.uc(this.Xh)&&(this.Xh=Math.ceil(this.Xh))):this.Xh="auto";this.JB=this.Wa.css("width");"auto"!=this.JB?(a.height(this.JB),this.Wm=a.height(),this.uc(this.Wm)&&(this.Wm=Math.ceil(this.Wm))):this.Wm="auto";a.remove();"resizable"===this.options.resizeBehavior&&f.fn.resizable&&this.kE()},BU:function(){this._on(this.widget(),{focusin:function(a){this.iE();this.pC=f(a.target)}})},iE:function(){this.QG();this.dx().unshift(this)},
QG:function(){var a=this.dx(),b=f.inArray(this,a);-1!==b&&a.splice(b,1)},dx:function(){var a=this.document.data("oj-dialog-instances");a||(a=[],this.document.data("oj-dialog-instances",a));return a},uc:function(a){return!isNaN(parseInt(a,10))},ZN:function(){this.element.uniqueId();this.pq=this.element.attr("id");this.px="ojDialogWrapper-"+this.pq;this.Wa=f("\x3cdiv\x3e").addClass("oj-dialog oj-helper-reset-inheritable oj-component oj-dialog-front ").hide().attr({tabIndex:-1,role:this.options.role,
id:this.px});this.Wa.insertBefore(this.element);this._on(this.Wa,{keydown:function(a){if("none"!=this.options.cancelBehavior&&!a.isDefaultPrevented()&&a.keyCode&&a.keyCode===f.ui.keyCode.ESCAPE)a.preventDefault(),this.close(a);else if(a.keyCode===f.ui.keyCode.TAB){var b=this.Wa.find(":tabbable"),d=b.filter(":first"),b=b.filter(":last");a.target!==b[0]&&a.target!==this.Wa[0]||a.shiftKey?a.target!==d[0]&&a.target!==this.Wa[0]||!a.shiftKey||(b.focus(1),a.preventDefault()):(d.focus(1),a.preventDefault())}},
mousedown:function(a){this.mw(a)&&this.en()}});this.element.find("[aria-describedby]").length||this.Wa.attr({"aria-describedby":this.element.uniqueId().attr("id")})},uB:function(a){this.dp=f("\x3cdiv\x3e").addClass("oj-dialog-header-close-wrapper").attr("tabindex","1").attr("aria-label","close").attr("role","button").appendTo(a);this.Ny=f("\x3cspan\x3e").addClass("oj-component-icon oj-clickable-icon oj-dialog-close-icon").attr("alt","close icon").prependTo(this.dp);this._on(this.dp,{click:function(a){a.preventDefault();
this.close(a)},mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active")},keydown:function(a){if(a.keyCode&&a.keyCode===f.ui.keyCode.SPACE||a.keyCode===f.ui.keyCode.ENTER)a.preventDefault(),this.close(a)}})},YN:function(){var a;a="icon"===this.options.cancelBehavior?
"oj-dialog-header oj-dialog-header-with-close-icon oj-helper-clearfix":"oj-dialog-header oj-dialog-header-without-close-icon oj-helper-clearfix";this.Ss=f("\x3cdiv\x3e").addClass(a).prependTo(this.Wa);this._on(this.Ss,{mousedown:function(a){f(a.target).closest(".oj-dialog-close-icon")||this.Wa.focus()}});"icon"===this.options.cancelBehavior&&this.uB(this.Ss);a=f("\x3cspan\x3e").uniqueId().addClass("oj-dialog-title").appendTo(this.Ss);this.HG(a);this.Wa.attr({"aria-labelledby":a.attr("id")})},HG:function(a){this.options.title||
a.html("\x26#160;");a.text(this.options.title)},hE:function(){function a(b){return{position:b.position,offset:b.offset}}var b=this,d=this.options;this.Wa.draggable({cancel:".oj-dialog-content, .oj-dialog-header-close",handle:".oj-dialog-header",containment:"document",start:function(d,g){f(this).addClass("oj-dialog-dragging");b.UA();b._trigger("dragStart",d,a(g))},drag:function(d,f){b._trigger("drag",d,a(f))},stop:function(e,g){d.position=[g.position.left-b.document.scrollLeft(),g.position.top-b.document.scrollTop()];
f(this).removeClass("oj-dialog-dragging");b.OG();b._trigger("dragStop",e,a(g))}})},kE:function(){function a(b){return{originalPosition:b.Qi,originalSize:b.Sf,position:b.position,size:b.size}}var b=this,d=this.Wa.css("position");this.Tn=this.Wa.ojResizable.bind(this.Wa);this.Tn({cancel:".oj-dialog-content",containment:"document",alsoResize:this.element,minHeight:this.aS(),maxHeight:this.Tm,minWidth:this.Vm,maxWidth:this.Um,handles:"n,e,s,w,se,sw,ne,nw",start:function(d,g){f(this).addClass("oj-dialog-resizing");
b.UA();b._trigger("resizeStart",d,a(g))},resize:function(d,f){b._trigger("resize",d,a(f))},stop:function(d,g){this.Xh=f(this).height();this.Wm=f(this).width();f(this).removeClass("oj-dialog-resizing");b.OG();b._trigger("resizeStop",d,a(g))}}).css("position",d)},aS:function(){return"auto"===this.Xh?this.mj:this.mj<this.Xh?this.mj:this.Xh},NE:function(){var c=this.Wa.is(":visible");c||this.Wa.show();var b=this.options.position,d="rtl"===this.Ic();this.Wa.position(a.he.Jg(b,d));c||this.Wa.hide()},_setOptions:function(a,
b){var d=this,e={};f.each(a,function(a,c){d._setOption(a,c,b)});this.Wa.is(":data(oj-resizable)")&&this.Tn("option",e)},_setOption:function(a,b,d){var e;e=this.Wa;"disabled"!==a&&(this._super(a,b,d),"dragAffordance"===a&&((d=e.is(":data(ui-draggable)"))&&!b&&e.draggable("destroy"),!d&&b&&this.hE()),"position"===a&&this.NE(),"resizeBehavior"===a&&(e=!1,this.Tn&&(e=!0),e&&"resizable"!=b&&(this.Tn("destroy"),this.Tn=null),e||"resizable"!==b||this.kE()),"title"===a&&this.HG(this.Ss.find(".oj-dialog-title")))},
UA:function(){this.Xx=this.document.find("iframe").map(function(){var a=f(this),b=a.offset();return f("\x3cdiv\x3e").css({position:"absolute",width:a.outerWidth(),height:a.outerHeight()}).appendTo(a.parent()).offset(b)[0]})},OG:function(){this.Xx&&(this.Xx.remove(),delete this.Xx)},zM:function(a){return f(a.target).closest(".oj-dialog").length?!0:!!f(a.target).closest(".oj-datepicker").length},fT:function(){this.xw="ojDialogPlaceHolder-"+this.pq;this.KE=f("\x3cdiv\x3e").hide().attr({id:this.xw});
this.KE.insertBefore(f("#"+this.px));this.Wa.attr(a.da.cg,this.KE.attr("id"));this.Wa.appendTo(this.LA())},VN:function(a){this.LE="ojDialogPlaceHolderFooter-"+this.pq;this.xS=f("\x3cdiv\x3e").hide().attr({id:this.LE});this.xS.insertBefore(a)},WN:function(a){this.ME="ojDialogPlaceHolderHeader-"+this.pq;this.yS=f("\x3cdiv\x3e").hide().attr({id:this.ME});this.yS.insertBefore(a)},nO:function(){this.VI&&(this.VI.remove(),this.VI=null)},KN:function(){if("modeless"!==this.options.modality){var a=!0;this._delay(function(){a=
!1});f.ui.dialog.overlayInstances||this._on(this.document,{focusin:function(b){a||!f.ui.dialog.overlayInstances||this.zM(b)||(b.preventDefault(),this.dx()[0].en())}});this.Uo=f("\x3cdiv\x3e").addClass("oj-dialog-overlay oj-dialog-front");this.Uo.appendTo(this.LA());this._on(this.Uo,{mousedown:"_keepFocus"});f.ui.dialog.overlayInstances++}},RB:function(){"modeless"!==this.options.modality&&this.Uo&&(f.ui.dialog.overlayInstances--,f.ui.dialog.overlayInstances||this.document.unbind("focusin"),this.Uo.remove(),
this.Uo=null)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-dialog":case "oj-dialog-header":case "oj-dialog-body":case "oj-dialog-footer":case "oj-dialog-content":case "oj-dialog-header-close":case "oj-resizable-n":case "oj-resizable-e":case "oj-resizable-s":case "oj-resizable-w":case "oj-resizable-se":case "oj-resizable-sw":case "oj-resizable-ne":case "oj-resizable-nw":return a="."+a,this.widget().find(a)[0]}return null}});f.ui.dialog.overlayInstances=
0})()});
//# sourceMappingURL=oj-modular.map