define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation"],function(a,f){function c(a,b){this.vS=b;this.BT=a;this.iO="/"}a.fe=function(a){this.Init(a)};o_("AttributeGroupHandler",a.fe,a);a.b.ra(a.fe,a.b,"oj.AttributeGroupHandler");a.fe.prototype.Init=function(b){a.fe.t.Init.call(this);this.Dn=b?b:{};this.Lm={};this.Zr=0;this.op=this.Nl();for(var c in this.Dn)b=this.op.indexOf(this.Dn[c]),-1!==b&&this.op.splice(b,1)};a.fe.prototype.Nl=function(){return[]};a.b.g("AttributeGroupHandler.prototype.getValueRamp",
{Nl:a.fe.prototype.Nl});a.fe.prototype.Bg=function(a){if(this.Dn[a])return this.Dn[a];this.Lm[a]||(this.Lm[a]=this.op[this.Zr],this.Zr==this.op.length-1?this.Zr=0:this.Zr++);return this.Lm[a]};a.b.g("AttributeGroupHandler.prototype.getValue",{Bg:a.fe.prototype.Bg});a.fe.prototype.PH=function(){var a=[],b;for(b in this.Lm)a.push({category:b,value:this.Lm[b]});return a};a.b.g("AttributeGroupHandler.prototype.getCategoryAssignments",{PH:a.fe.prototype.PH});a.fe.prototype.dH=function(a,b){this.Dn[a]=
b};a.b.g("AttributeGroupHandler.prototype.addMatchRule",{dH:a.fe.prototype.dH});var b={CSS_TEXT_PROPERTIES:function(a,c){var f={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,"oj-ledGauge")&&(f["font-size"]=!0,f.color=!0),a.hasClass(a,"oj-chartSliceLabel")&&(f.color=!0));return b.qE(a,c,!1,f)},CSS_BACKGROUND_PROPERTIES:function(a,c){return b.qE(a,c,!0,{})},CSS_URL:function(a){return b.uS(a)},Jz:"rgb(254, 0, 254)",Kz:"Times",OK:"1px",Mz:"1",Lz:"normal",IK:4,IV:function(a,b){return a.css(b)},
uS:function(a){return(a=a.css("background-image"))&&-1!==a.indexOf("url(")?a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):a},WM:function(a){var b="";a.css("border-top-color")&&(b+="border-color: "+a.css("border-top-color")+";");a.css("border-width")&&a.css("border-style")&&"none"!=a.css("border-style")&&(b+="border-width: "+a.css("border-width")+";");a.css("background-color")&&(b+="background-color: "+a.css("background-color")+";");return b},$M:function(a,c){var f="",h=a.css("font-family");
h&&h!==b.Kz&&(f+="font-family: "+h.replace(/"/g,"'")+";");h=a.css("font-size");!h||-1<h.indexOf("px")&&parseFloat(h)<b.IK||c["font-size"]||(f+="font-size: "+h+";");(h=a.css("font-weight"))&&h!==b.Mz&&(f+="font-weight: "+h+";");(h=a.css("color"))&&h!==b.Jz&&!c.color&&(f+="color: "+h+";");(h=a.css("font-style"))&&h!==b.Lz&&(f+="font-style: "+h+";");return f},qE:function(a,b,c,f){f||(f={});if(!a)return b;var k;b&&((k=a.attr("style"))?a.attr("style",k+b):a.attr("style",b));b="";!0!==c&&(b+=this.$M(a,
f));!1!==c&&(b+=this.WM(a));k&&a.attr("style",k);return b},QW:function(a,c,g,h){var k=f(document.createElement("div"));k.attr("style","display:none;");a.append(k);a="";for(var l=0;l<g.length;l++)a=a+g[l]+" ";k.attr("class",a);g=f(document.createElement("div"));k.append(g);g.css("font-family",b.Kz);g.css("font-size",b.OK);g.css("color",b.Jz);g.css("font-weight",b.Mz);g.css("font-style",b.Lz);for(var m in h)k=f(document.createElement("div")),k.addClass(m),g.append(k),b.LS(c,k,h[m])},LS:function(a,c,
f){if(f instanceof Array)for(var h=0;h<f.length;h++)b.KF(a,c,f[h]);else b.KF(a,c,f)},KF:function(a,e,f){a=new c(a,f.path);var h;f.property&&(h=(h=b[f.property])?h(e,a.Bg()):b.IV(e,f.property));null==h||"string"==typeof h&&""==h.replace(/^\s+/g,"")||a.hX(h)}};a.La("oj.dvtBaseComponent",f.oj.baseComponent,{_ComponentCreate:function(){this._super();this.Fw=f(document.createElement("div"));this.Fw.attr("style","visibility:hidden;");this.element.append(this.Fw);this.jj=new DvtContext(this.element[0],null,
this.Fw[0]);this.jj.setReadingDirection(this.Ic());this.jj.setTooltipStyleClass("oj-dvt-tooltip");this.jj.setDatatipStyleClass("oj-dvt-datatip");f(document.body).hasClass("oj-hicontrast")&&DvtAgent.setHighContrast(!0);this.element.attr("tabIndex",0);this.Sa=this.Af(this.jj,this.aj,this);this.jj.getStage().addChild(this.Sa);this.options._isoConverter=function(b){return b instanceof Date?a.Ba.dateToLocalIso(b):b};this.kA();this.WE();this.rt();this.gg();a.da.Bh(this.element[0],f.proxy(this.vh,this))},
refresh:function(){this._super();this.jj.setReadingDirection(this.Ic());this.WE();this.gg()},getNodeBySubId:function(a){var b;this.Sa&&this.Sa.getAutomation&&(b=this.Sa.getAutomation());return b?b.getDomElementForSubId(a.subId):null},getSubIdByNode:function(a){var b;this.Sa&&this.Sa.getAutomation&&(b=this.Sa.getAutomation());return b?b.getSubIdForDomElement(a):null},kA:function(){for(var a=this.$e(),c=0;c<a.length;c++)this.element.addClass(a[c]);b.QW(this.element,this.options,this.$e(),this.Zi())},
$e:function(){return["oj-dvtbase"]},Zi:function(){return{}},$i:function(){return[]},zm:function(){var b={"DvtUtilBundle.CLEAR_SELECTION":this.Kc("labelClearSelection"),"DvtUtilBundle.STATE_SELECTED":this.Kc("stateSelected"),"DvtUtilBundle.STATE_UNSELECTED":this.Kc("stateUnselected"),"DvtUtilBundle.STATE_MAXIMIZED":this.Kc("stateMaximized"),"DvtUtilBundle.STATE_MINIMIZED":this.Kc("stateMinimized"),"DvtUtilBundle.STATE_EXPANDED":this.Kc("stateExpanded"),"DvtUtilBundle.STATE_COLLAPSED":this.Kc("stateCollapsed"),
"DvtUtilBundle.STATE_ISOLATED":this.Kc("stateIsolated"),"DvtUtilBundle.STATE_HIDDEN":this.Kc("stateHidden"),"DvtUtilBundle.STATE_VISIBLE":this.Kc("stateVisible"),"DvtUtilBundle.SCALING_SUFFIX_THOUSAND":this.Kc("labelScalingSuffixThousand"),"DvtUtilBundle.SCALING_SUFFIX_MILLION":this.Kc("labelScalingSuffixMillion"),"DvtUtilBundle.SCALING_SUFFIX_BILLION":this.Kc("labelScalingSuffixBillion"),"DvtUtilBundle.SCALING_SUFFIX_TRILLION":this.Kc("labelScalingSuffixTrillion"),"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION":this.Kc("labelScalingSuffixQuadrillion")},
c=a.Fa.ts("abbreviated");b["DvtUtilBundle.MONTH_SHORT_JANUARY"]=c[0];b["DvtUtilBundle.MONTH_SHORT_FEBRUARY"]=c[1];b["DvtUtilBundle.MONTH_SHORT_MARCH"]=c[2];b["DvtUtilBundle.MONTH_SHORT_APRIL"]=c[3];b["DvtUtilBundle.MONTH_SHORT_MAY"]=c[4];b["DvtUtilBundle.MONTH_SHORT_JUNE"]=c[5];b["DvtUtilBundle.MONTH_SHORT_JULY"]=c[6];b["DvtUtilBundle.MONTH_SHORT_AUGUST"]=c[7];b["DvtUtilBundle.MONTH_SHORT_SEPTEMBER"]=c[8];b["DvtUtilBundle.MONTH_SHORT_OCTOBER"]=c[9];b["DvtUtilBundle.MONTH_SHORT_NOVEMBER"]=c[10];b["DvtUtilBundle.MONTH_SHORT_DECEMBER"]=
c[11];return b},qc:function(b,c){var f=this.Kc(b);if(c){for(var h={},k=0;k<c.length;k++)h[c[k]]="{"+k+"}";f=a.ea.pb(f,h)}return f},WE:function(){var a=this.zm();DvtBundle.addLocalizedStrings(a)},_destroy:function(){this.Sa.destroy&&this.Sa.destroy();a.da.ck(this.element[0],f.proxy(this.vh,this));this.element.children().remove();this.element.removeAttr("role").removeAttr("tabIndex");for(var b=this.$e(),c=0;c<b.length;c++)this.element.removeClass(b[c]);this._super()},_setOptions:function(a){this._superApply(arguments);
if(!this.Pt){var b=!1,c=this.$i();f.each(a,function(a){if(0>c.indexOf(a))return b=!0,!1});b&&this.gg()}},_setOption:function(b,c){var f=this.bj(b),h=this.options[b],k=this._superApply(arguments);if(f&&(f=this.options[b],!a.b.dj(h,f))){var l=this.tw?this.tw:{};l.writeback=this.Pt?"shouldWrite":"shouldNotWrite";this._trigger("optionChange",null,{option:b,previousValue:h,value:f,optionMetadata:l})}return k},Af:function(){return null},aj:function(){},vh:function(){var a=this.element.width(),b=this.element.height();
5<=Math.abs(a-this.ox)+Math.abs(b-this.Qv)&&(this.Sa.render(null,a,b),this.ox=a,this.Qv=b)},rt:function(){},gg:function(){this.jj.isReadyToRender()?(this.ox=this.element.width(),this.Qv=this.element.height(),this.Sa.render(this.options,this.ox,this.Qv)):a.C.error(this.Kc("notReadyToRender").summary)},bj:function(){return!1},ig:function(a,b,c){this.Pt=!0;this.tw=c;this.option(a,b);this.tw=null;this.Pt=!1}});a.qm=function(a){this.Init(a)};o_("ShapeAttributeGroupHandler",a.qm,a);a.b.ra(a.qm,a.fe,"oj.ShapeAttributeGroupHandler");
a.qm.Mm="square circle diamond plus triangleDown triangleUp human".split(" ");a.qm.prototype.Nl=function(){return a.qm.Mm.slice()};a.Rg=function(b){this.Mm=[];if(f(document.body).hasClass("oj-hicontrast"))this.Mm=a.Rg.gO.slice();else{var c=f(document.createElement("div"));c.attr("style","display:none;");c.attr("id","attrGps");f(document.body).append(c);for(var g=0;g<a.Rg.AG.length;g++){var h=f(document.createElement("div"));h.addClass(a.Rg.AG[g]);c.append(h);this.Mm.push(h.css("color"))}c.remove()}this.Init(b)};
o_("ColorAttributeGroupHandler",a.Rg,a);a.b.ra(a.Rg,a.fe,"oj.ColorAttributeGroupHandler");a.Rg.AG="oj-dvt-category1 oj-dvt-category2 oj-dvt-category3 oj-dvt-category4 oj-dvt-category5 oj-dvt-category6 oj-dvt-category7 oj-dvt-category8 oj-dvt-category9 oj-dvt-category10 oj-dvt-category11 oj-dvt-category12".split(" ");a.Rg.gO="#267db3 #68c182 #fad55c #ed6647 #8561c8 #6ddbdb #ffb54d #e371b2 #47bdef #a2bf39 #a75dba #f7f37b".split(" ");a.Rg.prototype.Nl=function(){return this.Mm.slice()};c.prototype.xT=
function(a,b,c,f){for(var k={};a&&-1<b.indexOf(c);){var l=b.substring(0,b.indexOf(c));f&&void 0===a[l]&&(a[l]={});a=a[l];b=b.substring(b.indexOf(c)+1,b.length)}a&&(k.object=a,k.parameter=b);return k};c.prototype.JF=function(a){void 0===this.Cn&&(a=this.xT(this.BT,this.vS,this.iO,a),this.Cn=a.object,this.ww=a.parameter)};c.prototype.Bg=function(){this.JF(!1);return void 0===this.Cn?void 0:this.Cn[this.ww]};c.prototype.hX=function(a){this.JF(!0);this.Cn[this.ww]!==a&&(this.Cn[this.ww]=a)}});
//# sourceMappingURL=oj-modular.map