/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtGauge"],function(a,f){a.La("oj.dvtBaseGauge",f.oj.dvtBaseComponent,{Zi:function(){var a=this._super();a["oj-gauge-metric-label"]={path:"metricLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-gauge-tick-label"]={path:"tickLabel/style",property:"CSS_TEXT_PROPERTIES"};return a},$i:function(){return["input","optionChange"]},zm:function(){var a=this._super();a["DvtGaugeBundle.EMPTY_TEXT"]=this.qc("msgNoData");
return a},aj:function(a){var b=a&&a.getType?a.getType():null;b===DvtValueChangeEvent.TYPE?this.ig("value",a.getNewValue()):b===DvtValueChangeEvent.TYPE_INPUT?this._trigger("input",null,{value:a.getNewValue()}):this._super(a)},bj:function(a){return"value"==a}});a.La("oj.ojStatusMeterGauge",f.oj.dvtBaseGauge,{version:"1.0.0",widgetEventPrefix:"oj",options:{input:null,optionChange:null},Af:function(a,b,d){return DvtStatusMeterGauge.newInstance(a,b,d)},$e:function(){var a=this._super();a.push("oj-statusmetergauge");
return a},gg:function(){this.element.attr("title")?(this.options.shortDesc=this.element.attr("title"),this.element.data(this.element,"title",this.element.attr("title")),this.element.removeAttr("title")):this.element.data("title")&&(this.options.shortDesc=this.element.data("title"));this._super()},getMetricLabel:function(){return this.Sa.getAutomation().getMetricLabel()}});a.La("oj.ojLedGauge",f.oj.dvtBaseGauge,{version:"1.0.0",widgetEventPrefix:"oj",options:{},Af:function(a,b,d){return DvtLedGauge.newInstance(a,
b,d)},$e:function(){var a=this._super();a.push("oj-ledgauge");return a},gg:function(){this.element.attr("title")?(this.options.shortDesc=this.element.attr("title"),this.element.data(this.element,"title",this.element.attr("title")),this.element.removeAttr("title")):this.element.data("title")&&(this.options.shortDesc=this.element.data("title"));this._super()},getMetricLabel:function(){return this.Sa.getAutomation().getMetricLabel()}});a.La("oj.ojRatingGauge",f.oj.dvtBaseGauge,{version:"1.0.0",widgetEventPrefix:"oj",
options:{input:null,optionChange:null},Af:function(a,b,d){return DvtRatingGauge.newInstance(a,b,d)},$e:function(){var a=this._super();a.push("oj-ratinggauge");return a},gg:function(){this.element.attr("title")?(this.options.shortDesc=this.element.attr("title"),this.element.data(this.element,"title",this.element.attr("title")),this.element.removeAttr("title")):this.element.data("title")&&(this.options.shortDesc=this.element.data("title"));this._super()},bj:function(a){return"value"==a||"changed"==
a},ig:function(a,b){this._superApply(arguments);"value"==a&&this.ig("changed",!0)}});a.La("oj.ojDialGauge",f.oj.dvtBaseGauge,{version:"1.0.0",widgetEventPrefix:"oj",options:{input:null,optionChange:null},Af:function(a,b,d){return DvtDialGauge.newInstance(a,b,d)},$e:function(){var a=this._super();a.push("oj-dialgauge");return a},gg:function(){this.element.attr("title")?(this.options.shortDesc=this.element.attr("title"),this.element.data(this.element,"title",this.element.attr("title")),this.element.removeAttr("title")):
this.element.data("title")&&(this.options.shortDesc=this.element.data("title"));this.RT();this._super()},RT:function(){var c=this.options.background,b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-circle-200x200.png"),width:200,height:200},{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-circle-400x400.png"),width:400,height:400}],d=this.options.indicator,e=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-needle-1600x1600.png"),width:374,height:575}];"string"===typeof c&&("rectangleAlta"===
c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-rectangle-200x200.png"),width:200,height:154},{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-rectangle-400x400.png"),width:400,height:309}]:"domeAlta"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-dome-200x200.png"),width:200,height:154},{src:a.ja.ib("resources/internal-deps/dvt/gauge/alta-dome-400x400.png"),width:400,height:309}]:"circleAntique"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-circle-200x200.png"),
width:200,height:200},{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-circle-400x400.png"),width:400,height:400}]:"rectangleAntique"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-rectangle-200x200.png"),width:200,height:168},{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-rectangle-400x400.png"),width:400,height:335}]:"domeAntique"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-dome-200x200.png"),width:200,height:176},{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-dome-400x400.png"),
width:400,height:352}]:"circleLight"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/light-circle-200x200.png"),width:200,height:200},{src:a.ja.ib("resources/internal-deps/dvt/gauge/light-circle-400x400.png"),width:400,height:400}]:"rectangleLight"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/light-rectangle-200x200.png"),width:200,height:154},{src:a.ja.ib("resourcesinternal-deps/dvt/gauge/light-rectangle-400x400.png"),width:400,height:307}]:"domeLight"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/light-dome-200x200.png"),
width:200,height:138},{src:a.ja.ib("resources/internal-deps/dvt/gauge/light-dome-400x400.png"),width:400,height:276}]:"circleDark"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/dark-circle-200x200.png"),width:200,height:200},{src:a.ja.ib("resources/internal-deps/dvt/gauge/dark-circle-400x400.png"),width:400,height:400}]:"rectangleDark"===c?b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/dark-rectangle-200x200.png"),width:200,height:154},{src:a.ja.ib("resourcesinternal-deps/dvt/gauge/dark-rectangle-400x400.png"),
width:400,height:307}]:"domeDark"===c&&(b=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/dark-dome-200x200.png"),width:200,height:138},{src:a.ja.ib("resources/internal-deps/dvt/gauge/dark-dome-400x400.png"),width:400,height:276}]),this.options._backgroundImages=b);"string"===typeof d&&("needleAntique"===d?e=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/antique-needle-1600x1600.png"),width:81,height:734}]:"needleDark"===d?e=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/dark-needle-1600x1600.png"),
width:454,height:652}]:"needleLight"===d&&(e=[{src:a.ja.ib("resources/internal-deps/dvt/gauge/light-needle-1600x1600.png"),width:454,height:652}]),this.options._indicatorImages=e)},getMetricLabel:function(){return this.Sa.getAutomation().getMetricLabel()}})});
//# sourceMappingURL=oj-modular.map