/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","knockout"],function(a,f,c){function b(b,c,d,e){"dayMetaData"===b&&e({dayFormatter:c?function(b){return a.DayMetaDataBinding.getMetaData(c,0,[b.fullYear,b.month,b.date])}:null})}function d(a,b){var c={};c.value=b.value;return c}function e(a,b){var c={},d=b.optionMetadata;d&&"shouldWrite"===d.writeback&&(c[b.option]=b.value);return c}function g(){this.Init()}function h(a,b,c){this.Init(a,b,c)}function k(a,b){return function(d){var e,f;e=d.parentElement;f=a.createChildContext(d.data,
null,function(a){a.$key=d.key;a.$metadata=d.metadata;a.$headerContext=d});c.renderTemplate(b,f,null,e);return null}}function l(a,b){return function(d){var e,f;e=d.parentElement;f=a.createChildContext(d.data,null,function(a){a.$keys=d.keys;a.$metadata=d.metadata;a.$cellContext=d});c.renderTemplate(b,f,null,e);return null}}function m(a,b,d){var e={};(function(b,d){e=function(e){var f=null,g=null;"header"==d?(f=a.extend({$column:e.column,$headerContext:e.headerContext}),g=e.headerContext.parentElement):
"cell"==d&&(f=a.createChildContext(e.row,null,function(a){a.$column=e.column;a.$cellContext=e.cellContext}),g=e.cellContext.parentElement);"footer"==d&&(f=a.extend({$column:e.column,$footerContext:e.footerContext}),g=e.footerContext.parentElement);c.renderTemplate(b,f,null,g,"replaceNode")}})(d,b);return e}function n(a,b){return function(d){var e=a.createChildContext(d.row,null,function(a){a.$rowContext=d.rowContext});c.renderTemplate(b,e,null,d.rowContext.parentElement,"replaceNode")}}a.ka=function(a,
b){this.Init(a,b)};o_("ComponentBinding",a.ka,a);a.b.ra(a.ka,a.b,"oj.ComponentBinding");a.ka.create=function(b,d){if(null==b)throw"Binding name is required!";var e=new a.ka(b,d),f=c.bindingHandlers,g,h=Array.isArray(b)?b:[b];for(g=0;g<h.length;g++)f[h[g]]=e;return e};o_("ComponentBinding.create",a.ka.create,a);a.ka.Eh=function(){return a.ka.TK};o_("ComponentBinding.getDefaultInstance",a.ka.Eh,a);a.ka.prototype.Mh=function(a){var b=a["for"],b=null==b?"@global":b,c=this.hr[b]||[];c.push(a);this.hr[b]=
c};a.b.g("ComponentBinding.prototype.setupManagedAttributes",{Mh:a.ka.prototype.Mh});a.ka.Dx=function(){a.ka.gB.Dx()};o_("ComponentBinding.deliverChanges",a.ka.Dx,a);a.ka.prototype.Init=function(b,c){a.ka.t.Init.call(this);"string"===typeof c&&(c={componentName:c});this.Qt=c||{};this.VM=Array.isArray(b)?b:[b];this.init=a.b.ks(this,this._init);this.update=a.b.ks(this,this.co);this.hr={}};a.ka.st="_ojNeedsJUIBInit";a.ka.prototype._init=function(b,d,e,g,h){c.applyBindingsToDescendants(h,b);f(b).data(a.ka.st,
!0);return{controlsDescendantBindings:!0}};a.ka.prototype.co=function(b,c,d,e,g){e=f(b);e.data(a.ka.st)&&(e.data(a.ka.st,null),this.yD(b,e,c,d,g))};a.ka.prototype.yD=function(b,f,g,l,k){var m=g(),n=null,v=!1,A=[],w=null,B=null,C=a.ka.aP(this.VM,b,k),N=0,P={},y=this.Qt.componentName;if(null==y){n="component";if(!C[n]&&(n="role",!C[n])){a.C.error("component attribute is required for the ojComponent binding");return}var K=m[n];if(null==K){a.C.error("non-null component attribute is required for the ojComponent binding");
return}c.computed(function(){a.ka.qq(C[n],n,P,k,!1);if(0==N)y=c.utils.unwrapObservable(K);else{v=!0;C=null;a.ka.GU(f);if(B){w.CH();w=null;var d=this.Qt.beforeDestroy;d&&d(b,B,g,l,k);B("destroy");B=null;for(d=0;d<A.length;d++)A[d].CH();A=null}this.yD(b,f,g,l,k)}return null},this,{disposeWhenNodeIsRemoved:b})}if(null!=y)if(B=f[y],"function"===typeof B){var B=B.bind(f),z=a.ka.HF(this.hr,C,y),L={},M=a.ka.Eh();this!==M&&(M=M.AP(C,y),a.ic.hf(M,z),z=M);for(var E={},w=new h(B,b,a.ka.gB),M={"^slider$":[{event:"slidechange",
getter:d}],"^oj*":[{event:"ojoptionchange",getter:e}]},J=function(){var c=this.NS,d=C[c];if(!d)throw"Binding expression for property "+c+" is not found";d=a.ka.qq(d,c,P,k,0!==N&&!v);if(0===N){var d=a.ka.IG(m[c]),e=z[c];null!=e?(L[c]=e,e=e.pW,null!=e&&(c=e(c,d,b,B,g,l,k)||{},a.ic.hf(E,c))):E[c]=d}else if(!v)if(d=a.ka.IG(d),null!=z[c]){if(e=z[c].update,null!=e)for(c=e(c,d,b,B,g,l,k)||{},d=Object.keys(c),e=0;e<d.length;e++){var f=d[e];w.cH(f,c[f])}}else w.cH(c,d);return null},F,I=Object.keys(m),Q=0;Q<
I.length;Q++)F=I[Q],F!==n&&A.push(c.computed(J,{NS:F},{disposeWhenNodeIsRemoved:b}));a.ka.eT(f,y,M,C,w,k,P);M=a.ka.dC(E);B(E);for(var H in M)B("option",H,M[H]);(H=this.Qt.afterCreate)&&H(b,B,g,l,k);a.ka.jO(L,b,B,g,l,k);E=null}else a.C.error("Component %s is not found",y);N=1};a.ka.aP=function(a,b,d){var e={},f=null,f=c.bindingProvider.instance,g;g=null;var h,f=f.SV?f.SV(b,d):b.getAttribute("data-bind");if(!f)return e;b=c.jsonExpressionRewriting.parseObjectLiteral(f);d=/^(\s|\u00A0)+|(\s|\u00A0)+$/g;
for(f=0;f<b.length;f+=1){h=b[f];var l=h.key.replace(d,"");if(0<=a.indexOf(l)){g=h.value;break}}if(!g)return e;b=c.jsonExpressionRewriting.parseObjectLiteral(g);for(a=0;a<b.length;a+=1)g=b[a],e[g.key.replace(d,"")]=g.value.replace(d,"");return e};a.ka.qq=function(a,b,c,d,e){var f=c[b],g=void 0===f;if(g||null===f.Fx&&f.jJ&&e){"string"!==typeof a&&(a=a());var f=null,h=!1;if(null!==a){if(g){if(g=a.charAt(0),"'"===g||'"'===g||0>=a.indexOf("("))h=!0}else h=!0;if(!h||e)f=new Function("$context","with($context){with($data||{}){return "+
a+";}}")}f={Fx:f,jJ:h};c[b]=f}return!f.Fx||!e&&f.jJ?null:f.Fx(d)};a.ka.prototype.AP=function(b,c){return a.ka.HF(this.hr,b,c)};a.ka.HF=function(a,b,c){function d(b,c){var e=a[b];if(null!=e)for(var f=e.length-1;0<=f;f--){var p=e[f];null!=p.attributes&&g.push(p);if(c&&(p=p.use,null!=p))for(var p=Array.isArray(p)?p:[p],h=0;h<p.length;h++)d(p[h],!0)}}var e={},g=[];d(c,!0);c=f.oj[c];if(null!=c)for(c=Object.getPrototypeOf(c.prototype);null!=c&&"oj"===c.namespace;)d(c.widgetName,!0),c=Object.getPrototypeOf(c);
d("@global",!1);if(0<g.length)for(b=Object.keys(b),c=0;c<b.length;c++)for(var h=b[c],l=0;l<g.length;l++){var k=g[l];if(0<=k.attributes.indexOf(h)){e[h]={pW:k.init,update:k.update,aV:k.afterCreate};break}}return e};a.ka.Hz=".ojWriteback";a.ka.GU=function(b){b&&b.off(a.ka.Hz)};a.ka.eT=function(b,c,d,e,f,g,h){var l={},k;for(k in d)if(c.match(k)){c=d[k];for(d=0;d<c.length;d++)k=c[d],b.on(k.event+a.ka.Hz,{lW:k.getter},function(b,c){b.stopPropagation();var d=b.data.lW(b,c);f.qX();try{for(var p in d)if(e[p]){var k=
a.ka.qq(e[p],p,h,g,!0);a.ka.WU(p,k,d[p],e[p],g,l)}}finally{f.YW()}});break}};a.ka.NP=function(a){var b=["true","false","null","undefined"];if(null==a||0<=b.indexOf(a))return null;b=a.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);return null===b?null:"function(v){"+(b[1]?"Object("+b[1]+")"+b[2]:a)+"\x3dv;}"};a.ka.WU=function(b,d,e,f,g,h){null!=d&&c.isObservable(d)?c.isWriteableObservable(d)&&d(e):(b=a.ka.qq(function(){return a.ka.NP(f)},b,h,g,!0))&&b(e)};a.ka.IG=function(b){b=c.utils.unwrapObservable(b);
(Array.isArray(b)||a.ic.isPlainObject(b))&&b.ojConvertToJS&&(b=c.toJS(b));return b};a.ka.dC=function(a){var b={},c;for(c in a)0<=c.indexOf(".")&&(b[c]=a[c]);for(var d in b)delete a[d];return b};a.ka.jO=function(a,b,c,d,e,f){for(var g=Object.keys(a),h=0;h<g.length;h++){var l=g[h],k=a[l].aV;k&&k(l,b,c,d,e,f)}};a.b.ra(g,a.b,"ComponentBinding.GlobalChangeQueue");g.prototype.Init=function(){g.t.Init.call(this);this.vl=[];this.gl=[]};g.prototype.UW=function(b){-1===this.vl.indexOf(b)&&(this.vl.push(b),
this.kq||(this.kq=setTimeout(a.b.ks(this,this.PB),1)))};g.prototype.VW=function(a){a=this.vl.indexOf(a);0<=a&&this.vl.splice(a,1)};g.prototype.Dx=function(){this.kq&&clearTimeout(this.kq);this.PB()};g.prototype.PB=function(){var a;this.kq=null;var b=this.vl;this.vl=[];for(a=0;a<b.length;a++){var c=b[a];this.gl.push({My:c,lo:c.PV()})}for(;0<this.gl.length;)a=this.gl.shift(),a.My.cV(a.lo)};a.b.ra(h,a.b,"ComponentBinding.ComponentChangeTracker");h.prototype.Init=function(a,b,c){h.t.Init.call(this);this.Sa=
a;this.BO=b;this.gl=c;this.gu={};this.rl=0};h.prototype.cH=function(a,b){this.xR()||this.qO||(this.gu[a]=b,this.gl.UW(this))};h.prototype.CH=function(){this.gl.VW(this);this.qO=!0};h.prototype.YW=function(){a.i.assert(0<this.rl,"ComponentChangeTracker._suspendCount underflow");this.rl-=1};h.prototype.qX=function(){this.rl+=1};h.prototype.cV=function(b){if(null!=a.Components.ws(this.BO)){var c=a.ka.dC(b),d={changed:!0};this.Sa("option",b,d);for(var e in c)this.Sa("option",e,c[e],d)}};h.prototype.PV=
function(){var a=this.gu;this.gu={};return a};h.prototype.xR=function(){return 1<=this.rl};a.ka.gB=new g;a.ka.TK=a.ka.create(["ojComponent","jqueryUI"]);a.fy={};o_("koStringTemplateEngine",a.fy,a);a.fy.uW=function(){function a(c){this.ul=c;this.text=function(a){if(!a)return b[this.ul];b[this.ul]=a};this.data=function(a,b){d[this.ul]||(d[this.ul]={});if(1===arguments.length)return d[this.ul][a];d[this.ul][a]=b}}var b={},d={},e=new c.nativeTemplateEngine;e.makeTemplateSource=function(b,d){if("string"==
typeof b){d=d||document;var e=d.getElementById(b);return e?new c.templateSources.domElement(e):new a(b)}if(b&&1==b.nodeType||8==b.nodeType)return new c.templateSources.anonymousTemplate(b)};c.templates=b;c.setTemplateEngine(e)};o_("koStringTemplateEngine.install",a.fy.uW,a);a.ka.Eh().Mh({attributes:["header","cell"],init:function(a,b,c,d,e,f,g){"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=k(g,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=k(g,c))),d({header:b})):
"cell"===a&&(a=b.template,null!=a&&(b.renderer=l(g,a)),d({cell:b}))},update:function(a,b,c,d,e,f,g){return"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=k(g,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=k(g,c))),{header:b}):"cell"===a?(a=b.template,null!=a&&(b.renderer=l(g,a)),{cell:b}):null},"for":"ojDataGrid"});c.bindingHandlers.ojContextMenu={update:function(a,b){f(a).off(".ojContextMenu");var d=c.utils.unwrapObservable(b());"string"!==f.type(d)&&(d=a.getAttribute("contextmenu"))&&
(d="#"+d);var e,g;d&&(e=f(d),g=e.data("oj-ojMenu"));if(g){var h=f(a);h.on("keydown.ojContextMenu contextmenu.ojContextMenu",function(a){if("contextmenu"===a.type||121==a.which&&a.shiftKey)g.open(a,{launcher:h,initialFocus:"menu"}),e.is(":visible")&&a.preventDefault();return!0})}}};a.ka.Eh().Mh({attributes:["columns","columnsDefault","rowTemplate"],init:function(a,b,c,d,e,f,g){if("columns"==a||"columnsDefault"==a){var h;for(c=0;c<b.length;c++){var l=b[c];e=l.template;f=l.footerTemplate;h=l.headerTemplate;
null!=e&&(l.renderer=m(g,"cell",e));null!=f&&(l.footerRenderer=m(g,"footer",f));null!=h&&(l.headerRenderer=m(g,"header",h))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else"rowTemplate"==a&&d({rowRenderer:n(g,b)})},update:function(a,b,c,d,e,f,g){if("columns"==a||"columnsDefault"==a){var h;for(c=0;c<b.length;c++){var l=b[c];e=l.template;f=l.footerTemplate;h=l.headerTemplate;null!=e&&(l.renderer=m(g,"cell",e));null!=f&&(l.footerRenderer=m(g,"footer",f));null!=h&&(l.headerRenderer=m(g,"header",
h))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else if("rowTemplate"==a)return{rowRenderer:n(g,b)};return null},"for":"ojTable"});a.DayMetaDataBinding={getMetaData:function r(a,b,c){if(!a||b===c.length)return a;var d=b+1;return r(a[c[b]],d,c)||r(a["*"],d,c)}};a.ka.Eh().Mh({"for":"ojDayMetaData",attributes:["dayMetaData"],init:b,update:b});a.ka.Eh().Mh({"for":"ojInputDateTime",use:"ojDayMetaData"});a.ka.Eh().Mh({"for":"ojInputDate",use:"ojDayMetaData"});a.ka.Eh().Mh({"for":"ojInputTime",use:"ojDayMetaData"})});
//# sourceMappingURL=oj-modular.map