/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery"],function(a,f){a.U=function(a,b,d){this.Init(a,b,d)};o_("Message",a.U,a);a.U.bg={CONFIRMATION:"confirmation",INFO:"info",WARNING:"warning",ERROR:"error",FATAL:"fatal"};o_("Message.SEVERITY_TYPE",a.U.bg,a);a.U.Lb={FATAL:5,ERROR:4,WARNING:3,INFO:2,CONFIRMATION:1};o_("Message.SEVERITY_LEVEL",a.U.Lb,a);a.b.ra(a.U,a.b,"oj.Message");a.U.prototype.Init=function(c,b,d){a.U.t.Init.call(this);this.summary=c;this.detail=b;this.severity=d||a.U.bg.ERROR};a.b.g("Message.prototype.Init",
{Init:a.U.prototype.Init});a.U.prototype.mH=function(){return!0};a.U.prototype.Ci=function(c){return c&&a.U.Kl(this.severity)===a.U.Kl(c.severity)&&this.summary===c.summary&&this.detail===c.detail?!0:!1};a.b.g("Message.prototype.equals",{Ci:a.U.prototype.Ci});a.U.prototype.clone=function(){return new a.U(this.summary,this.detail,this.severity)};a.b.g("Message.prototype.clone",{clone:a.U.prototype.clone});a.U.Kl=function(c){c&&("string"===typeof c?(c=a.U.pt.indexOf(c,1),c=-1===c?a.U.Lb.ERROR:c):"number"===
typeof c&&c<a.U.Lb.CONFIRMATION&&c>a.U.Lb.FATAL&&(c=a.U.Lb.ERROR));return c?c:a.U.Lb.ERROR};o_("Message.getSeverityLevel",a.U.Kl,a);a.U.fW=function(c){var b;c&&("string"===typeof c?(b=a.U.pt.indexOf(c,1),-1===b&&(c=a.U.bg.ERROR)):"number"===typeof c&&(c=c<a.U.Lb.CONFIRMATION&&c>a.U.Lb.FATAL?a.U.bg.ERROR:a.U.pt[c]));return c||a.U.bg.ERROR};o_("Message.getSeverityType",a.U.fW,a);a.U.Il=function(c){var b=-1,d;c&&0<c.length&&f.each(c,function(c,g){g&&(d=a.U.Kl(g.severity));b=b<d?d:b});return b};o_("Message.getMaxSeverity",
a.U.Il,a);a.U.isValid=function(c){return a.U.Il(c)>=a.U.Lb.ERROR?!1:!0};o_("Message.isValid",a.U.isValid,a);a.U.pt=["none",a.U.bg.CONFIRMATION,a.U.bg.INFO,a.U.bg.WARNING,a.U.bg.ERROR,a.U.bg.FATAL];a.Sb=function(a,b,d,e){this.Init(a,b,d,e)};a.b.ra(a.Sb,a.U,"oj.ComponentMessage");a.Sb.lk={$s:"shown",Ys:"hidden"};a.Sb.wK={display:a.Sb.lk.$s,context:""};a.Sb.prototype.Init=function(c,b,d,e){a.Sb.t.Init.call(this,c,b,d);this.Ta=f.extend({},a.Sb.wK,e)};a.Sb.prototype.Ci=function(c){return a.Sb.t.Ci.call(this,
c)&&this.Ta.display===c.Ta.display};a.Sb.prototype.clone=function(){return new a.Sb(this.summary,this.detail,this.severity,this.Ta)};a.Sb.prototype.mH=function(){return!(this.Ta&&this.Ta.display&&this.Ta.display===a.Sb.lk.Ys)};a.Sb.prototype.VO=function(){this.Ta&&a.Sb.lk.Ys===this.Ta.display&&(this.Ta.display=a.Sb.lk.$s)};a.Sb.prototype.TD=function(){return this.Ta&&this.Ta.context?!0:!1}});
//# sourceMappingURL=oj-modular.map