/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","knockout","ojs/ojpagingcontrol","ojs/ojknockout-model"],function(a,f,c){a.wb=function(a){this.oa=a;this.current=0;this.Init();this.kf=[];this.setPageSize(10)};o_("CollectionPagingDataSource",a.wb,a);a.b.ra(a.wb,a.kb,"oj.CollectionPagingDataSource");a.wb.prototype.Init=function(){a.wb.t.Init.call(this)};a.b.g("CollectionPagingDataSource.prototype.Init",{Init:a.wb.prototype.Init});a.wb.prototype.zv=function(){return this.hasMore()?this.pageSize:this.totalSize()-this.startIndex()};
a.wb.prototype.xh=function(){this.kf=Array(this.zv());var a=this;return this.oa.jm(this.startIndex(),this.startIndex()+this.kf.length).then(function(c){for(var e=0;e<c.length;e++)a.kf[e]=c[e];a.On()})};a.wb.prototype.On=function(){if(void 0!==this.Rf){this.Rf.removeAll();for(var b=0;b<this.kf.length;b++)this.Rf.push(a.Ka.map(this.kf[b]))}};a.wb.prototype.Xj=function(){return this.kf};a.b.g("CollectionPagingDataSource.prototype.getWindow",{Xj:a.wb.prototype.Xj});a.wb.prototype.Ao=function(){void 0===
this.Rf&&(this.Rf=c.observableArray(),this.On());return this.Rf};a.b.g("CollectionPagingDataSource.prototype.getWindowObservable",{Ao:a.wb.prototype.Ao});a.wb.prototype.fetch=function(a){var c=a||{};void 0!==c.startIndex&&(this.current=c.startIndex);void 0!==c.pageSize&&(this.pageSize=c.pageSize);var e=this;try{this.oa.fetch({success:function(){e.xh().then(function(){e.Mn(c)})}})}catch(f){e.xh().then(function(){e.Mn(c)})}};a.b.g("CollectionPagingDataSource.prototype.fetch",{fetch:a.wb.prototype.fetch});
a.wb.prototype.Mn=function(a){a=a||{};this.handleEvent("sync",null);a.success&&a.success()};a.wb.prototype.handleEvent=function(b,c){a.wb.t.handleEvent.call(this,b,c)};a.wb.prototype.hasMore=function(){return this.startIndex()+this.pageSize<this.totalSize()};a.b.g("CollectionPagingDataSource.prototype.hasMore",{hasMore:a.wb.prototype.hasMore});a.wb.prototype.next=function(){if(this.hasMore()){this.current+=this.pageSize;var a=this;return this.xh().then(function(){a.Mn(null)})}this.Mn(null)};a.b.g("CollectionPagingDataSource.prototype.next",
{next:a.wb.prototype.next});a.wb.prototype.previous=function(){0>this.startIndex()-this.pageSize?this.current=0:this.current-=this.pageSize;var a=this;return this.xh().then(function(){a.Mn(null)})};a.b.g("CollectionPagingDataSource.prototype.previous",{previous:a.wb.prototype.previous});a.wb.prototype.setPageSize=function(a){this.pageSize=a};a.wb.prototype.startIndex=function(){return this.current};a.b.g("CollectionPagingDataSource.prototype.startIndex",{startIndex:a.wb.prototype.startIndex});a.wb.prototype.size=
function(){var a=this.Xj();return a?a.length:0};a.b.g("CollectionPagingDataSource.prototype.size",{size:a.wb.prototype.size});a.wb.prototype.totalSize=function(){return this.oa.length};a.b.g("CollectionPagingDataSource.prototype.totalSize",{totalSize:a.wb.prototype.totalSize});a.Bb=function(a){this.data=a;this.current=0;this.Init();this.setPageSize(10)};o_("ArrayPagingDataSource",a.Bb,a);a.b.ra(a.Bb,a.kb,"oj.ArrayPagingDataSource");a.Bb.prototype.Init=function(){a.Bb.t.Init.call(this)};a.b.g("ArrayPagingDataSource.prototype.Init",
{Init:a.Bb.prototype.Init});a.Bb.prototype.zv=function(){return this.hasMore()?this.pageSize:this.totalSize()-this.startIndex()};a.Bb.prototype.xh=function(){this.kf=Array(this.zv());for(var a=0;a<this.kf.length;a++)this.kf[a]=this.data[this.startIndex()+a];this.On();this.handleEvent("sync",null)};a.Bb.prototype.On=function(){if(void 0!==this.Rf){this.Rf.removeAll();for(var a=0;a<this.kf.length;a++)this.Rf.push(this.kf[a])}};a.Bb.prototype.handleEvent=function(b,c){a.Bb.t.handleEvent.call(this,b,
c)};a.Bb.prototype.Xj=function(){return this.kf};a.b.g("ArrayPagingDataSource.prototype.getWindow",{Xj:a.Bb.prototype.Xj});a.Bb.prototype.Ao=function(){void 0===this.Rf&&(this.Rf=c.observableArray(),this.On());return this.Rf};a.b.g("ArrayPagingDataSource.prototype.getWindowObservable",{Ao:a.Bb.prototype.Ao});a.Bb.prototype.fetch=function(a){a=a||{};void 0!==a.startIndex&&(this.current=a.startIndex);void 0!==a.pageSize&&(this.pageSize=a.pageSize);this.xh()};a.b.g("ArrayPagingDataSource.prototype.fetch",
{fetch:a.Bb.prototype.fetch});a.Bb.prototype.hasMore=function(){return this.startIndex()+this.pageSize<this.totalSize()};a.b.g("ArrayPagingDataSource.prototype.hasMore",{hasMore:a.Bb.prototype.hasMore});a.Bb.prototype.next=function(){this.hasMore()&&(this.current+=this.pageSize,this.xh())};a.b.g("ArrayPagingDataSource.prototype.next",{next:a.Bb.prototype.next});a.Bb.prototype.previous=function(){0>this.startIndex()-this.pageSize?this.current=0:this.current-=this.pageSize;this.xh()};a.b.g("ArrayPagingDataSource.prototype.previous",
{previous:a.Bb.prototype.previous});a.Bb.prototype.setPageSize=function(a){this.pageSize=a;this.xh()};a.Bb.prototype.startIndex=function(){return this.current};a.b.g("ArrayPagingDataSource.prototype.startIndex",{startIndex:a.Bb.prototype.startIndex});a.Bb.prototype.size=function(){return this.Xj().length};a.b.g("ArrayPagingDataSource.prototype.size",{size:a.Bb.prototype.size});a.Bb.prototype.totalSize=function(){return this.data.length};a.b.g("ArrayPagingDataSource.prototype.totalSize",{totalSize:a.Bb.prototype.totalSize})});
//# sourceMappingURL=oj-modular.map