/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdatacollection-common","ojs/ojinputtext"],function(a,f){a.kb=function(a){this.Oa=a;this.Init()};o_("PagingDataSource",a.kb,a);a.b.ra(a.kb,a.Sc,"oj.PagingDataSource");a.kb.prototype.Init=function(){a.kb.t.Init.call(this)};a.b.g("PagingDataSource.prototype.Init",{Init:a.kb.prototype.Init});a.kb.prototype.fetch=function(){a.i.fa();return a.b.la(function(a,b){b()})};a.b.g("PagingDataSource.prototype.fetch",{fetch:a.kb.prototype.fetch});a.kb.prototype.hasMore=
function(){a.i.fa();return!1};a.b.g("PagingDataSource.prototype.hasMore",{hasMore:a.kb.prototype.hasMore});a.kb.prototype.next=function(){a.i.fa();return a.b.la(function(a,b){b()})};a.b.g("PagingDataSource.prototype.next",{next:a.kb.prototype.next});a.kb.prototype.previous=function(){a.i.fa();return a.b.la(function(a,b){b()})};a.b.g("PagingDataSource.prototype.previous",{previous:a.kb.prototype.previous});a.kb.prototype.setPageSize=function(){a.i.fa()};a.kb.prototype.startIndex=function(){a.i.fa();
return 0};a.b.g("PagingDataSource.prototype.startIndex",{startIndex:a.kb.prototype.startIndex});a.kb.prototype.size=function(){a.i.fa();return 0};a.b.g("PagingDataSource.prototype.size",{size:a.kb.prototype.size});a.kb.prototype.totalSize=function(){a.i.fa();return 0};a.b.g("PagingDataSource.prototype.totalSize",{totalSize:a.kb.prototype.totalSize});a.kb.v={ADD:"add",REMOVE:"remove",RESET:"reset",SYNC:"sync",REFRESH:"refresh",SORT:"sort"};o_("PagingDataSource.EventType",a.kb.v,a);(function(){a.La("oj.ojPagingControl",
f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,overflow:"fit",pageSize:25,pageOptions:{layout:["auto"],maxPageLinks:6},loadMoreOptions:{maxCount:500},mode:"page",translations:{}},eb:{cL:"labelAccPaging",YK:"labelAccNavFirstPage",ZK:"labelAccNavLastPage",$K:"labelAccNavNextPage",bL:"labelAccNavPreviousPage",aL:"labelAccNavPage",dL:"labelLoadMore",eL:"labelNavInputPage",fL:"labelNavInputPageMax",gL:"labelNavInputPageSummary",Vz:"msgItemRange",
rL:"msgItemRangeUnknown",aM:"tipNavInputPage",dM:"tipNavPageLink",cM:"tipNavNextPage",eM:"tipNavPreviousPage",$L:"tipNavFirstPage",bM:"tipNavLastPage",DK:"pageInvalid.summary",CK:"pageInvalid.detail",nt:"dataInvalidType.summary",mt:"dataInvalidType.detail",BK:"maxPageLinksInvalid.summary",AK:"maxPageLinksInvalid.detail"},Ca:{It:"oj-component",Pd:"oj-active",Yi:"oj-clickable-icon",lb:"oj-disabled",yd:"oj-enabled",Bf:"oj-focus",sp:"oj-hover",rc:"oj-selected"},pa:{yL:"oj-pagingcontrol",Zz:"oj-pagingcontrol-acc-label",
$z:"oj-pagingcontrol-content",aA:"oj-pagingcontrol-loadmore",bA:"oj-pagingcontrol-loadmore-link",cA:"oj-pagingcontrol-loadmore-range",eA:"oj-pagingcontrol-nav",Dp:"oj-pagingcontrol-nav-arrow",dA:"oj-pagingcontrol-nav-arrow-section",IL:"oj-pagingcontrol-nav-page",HL:"oj-pagingcontrol-nav-page-acc-label",BL:"oj-pagingcontrol-nav-label",hA:"oj-pagingcontrol-nav-input-section",fA:"oj-pagingcontrol-nav-input",gA:"oj-pagingcontrol-nav-input-max",wt:"oj-pagingcontrol-nav-input-summary",GL:"oj-pagingcontrol-nav-pages-section",
iA:"oj-pagingcontrol-nav-pages-links",vt:"oj-pagingcontrol-nav-first",zL:"oj-pagingcontrol-nav-first-acc-label",zt:"oj-pagingcontrol-nav-previous",JL:"oj-pagingcontrol-nav-previous-acc-label",yt:"oj-pagingcontrol-nav-next",EL:"oj-pagingcontrol-nav-next-acc-label",xt:"oj-pagingcontrol-nav-last",CL:"oj-pagingcontrol-nav-last-acc-label",AL:"oj-pagingcontrol-nav-first-icon",KL:"oj-pagingcontrol-nav-previous-icon",FL:"oj-pagingcontrol-nav-next-icon",DL:"oj-pagingcontrol-nav-last-icon",cj:"oj-component-icon",
Df:"oj-helper-hidden-accessible"},uK:"data-oj-pagenum",Qd:"enabled",Yz:"disabled",Ap:{qt:"loadMore",wL:"page"},zd:{ok:"auto",sm:"all",RK:"input",ML:"rangeText",xL:"pages",Wz:"nav"},firstPage:function(){var c=this.sa();return null!=c?(this.O=0,c.fetch({startIndex:0})):a.b.la(function(a,c){c()})},previousPage:function(){var c=this.sa();return null!=c?(this.O=this.Sk(this.ke()-1),0>this.O&&(this.O=0),c.fetch({startIndex:this.O})):a.b.la(function(a,c){c()})},nextPage:function(){var c=this.sa();if(null!=
c&&0<this.Dc()){var b=this.ke();b+1>this.Dc()&&(b=this.Dc()-1);this.O=this.Sk(b+1);return c.fetch({startIndex:this.O})}return a.b.la(function(a,b){b()})},lastPage:function(){var c=this.sa();return null!=c&&0<this.Dc()?(this.O=this.Sk(this.Dc()),c.fetch({startIndex:this.O})):a.b.la(function(a,c){c()})},page:function(c){var b=this.sa();return null!=b&&(c<=this.Dc()||0>this.Dc())?(this.O=this.Sk(c),b.fetch({startIndex:this.O})):a.b.la(function(a,b){b()})},loadNext:function(){var c=this.sa();return null!=
c?c.next():a.b.la(function(a,c){c()})},refresh:function(){this._super();if(null!=this.bi){this.bi=null;var a=this.sa();null!=a&&(a.setPageSize(this.options.pageSize),a.fetch({startIndex:this.O}))}this.Yb(!0)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId;return"oj-pagingcontrol-nav-input"===b?this.HP():"oj-pagingcontrol-nav-input-max"===b?this.bf().find("."+this.pa.gA):"oj-pagingcontrol-nav-input-summary"===b?this.bf().find("."+this.pa.wt):"oj-pagingcontrol-nav-first"===
b?this.bf().find("."+this.pa.vt):"oj-pagingcontrol-nav-next"===b?this.bf().find("."+this.pa.yt):"oj-pagingcontrol-nav-previous"===b?this.bf().find("."+this.pa.zt):"oj-pagingcontrol-nav-last"===b?this.bf().find("."+this.pa.xt):"oj-pagingcontrol-nav-page"===b?(a=a.index,this.bf().find("["+this.uK+"\x3d"+a+"]")):null},_ComponentCreate:function(){this._super();this.Qn();this.bn();this.kl(this.bf());this._on(this.If);var a=this;setInterval(function(){null!=a.nF&&(a.dF(),a.nF=null)},50);setInterval(function(){if(null!=
a.bi){var b=a.sa();null!=b&&(b.setPageSize(a.options.pageSize),b.fetch({startIndex:a.O}),a.bi=null)}},100)},_destroy:function(){this.Pj()},bn:function(){var a=this.options;this.element.addClass(this.pa.yL);this.element.addClass(this.Ca.It);this.O=0;this.LN();this.RN();a.mode==this.Ap.qt?(this.SN(),this.TN(),this.vB()):this.wB();var b=this;setTimeout(function(){null!=b.sa()&&b.sa().size()<a.pageSize&&(0>b.sa().totalSize()||b.sa().totalSize()>=b.sa().size())&&(b.sa().setPageSize(a.pageSize),b.sa().fetch({startIndex:b.O,
fetchType:"init"}))},0)},If:{"click .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var b=f(a.target).attr("data-oj-pagenum");this.page(b);a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){f(a.currentTarget).hasClass(this.Ca.lb)||this.firstPage();a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){f(a.currentTarget).hasClass(this.Ca.lb)||this.previousPage();a.preventDefault()},"click .oj-pagingcontrol-nav-next":function(a){f(a.currentTarget).hasClass(this.Ca.lb)||
this.nextPage();a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){f(a.currentTarget).hasClass(this.Ca.lb)||this.lastPage();a.preventDefault()},"keypress .oj-pagingcontrol-nav-input":function(a){13==a.which&&a.preventDefault()},"mousedown .oj-pagingcontrol-nav-first":function(a){f(a.target).addClass(this.Ca.Pd);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-previous":function(a){f(a.target).addClass(this.Ca.Pd);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-next":function(a){f(a.target).addClass(this.Ca.Pd);
a.preventDefault()},"mousedown .oj-pagingcontrol-nav-last":function(a){f(a.target).addClass(this.Ca.Pd);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Ca.Pd);
a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Ca.Pd);a.preventDefault()}},Yb:function(a){a?this.dF():this.nF=!0},dF:function(){this.f!=
this.options.data&&(this.ku(),this.bi=!0);if(this.options.mode==this.Ap.qt){var a=this.sa(),b=this.mn();null!=a&&a.size()==a.totalSize()?b.css("display","none"):(b.css("display",""),this.US())}else this.VS()},_setOption:function(a,b){this._superApply(arguments);this.bi=!0;this.Yb(!0)},ku:function(){null!=this.f&&this.Pj();this.f=null;this.O=0},jN:function(){this.Vt=null},kN:function(){this.Yt=this.Xt=this.Wt=null},ke:function(){return 0==this.O?1:Math.ceil((this.O+1)/this.options.pageSize)},sa:function(){if(!this.f&&
null!=this.options.data){var c=this.options.data;if(c instanceof a.kb)this.f=c;else{var c=this.J(this.eb.nt),b=this.J(this.eb.mt);throw Error(c+"\n"+b);}this.f.setPageSize(this.options.pageSize);this.Qn()}return this.f},HC:function(){var a=this.sa(),b=this.J(this.eb.Vz,{pageFrom:this.O,pageTo:0,pageTotal:0});null!=a&&(b=parseInt(this.O,10)+parseInt(a.size(),10),-1!=a.totalSize()?(b=b>a.totalSize()?a.totalSize():b,b=this.J(this.eb.Vz,{pageFrom:this.O+1,pageTo:b,pageTotal:a.totalSize()})):b=this.J(this.eb.rL,
{pageFrom:this.O+1,pageTo:b}));return b},BP:function(){return this.options.pageOptions.maxPageLinks},Sk:function(c){var b=(c-1)*this.options.pageSize,d=this.Dc();0>b?a.C.error("Value must be greater than 0"):0<d&&c>d&&a.C.error("Value cannot be greater than the total number of pages");return b},Dc:function(){var a=this.sa(),b=0;null!=a&&(b=a.totalSize());return-1==b?-1:Math.ceil(b/this.options.pageSize)},Jv:function(){this.Yb()},Rq:function(){this.O=0;this.sa().setPageSize(this.options.pageSize);
this.Yb(!0);this.sa().fetch({startIndex:this.O,reset:!0})},lD:function(){this.Yb();this.sa().fetch({startIndex:this.O})},Sq:function(a){this.options.mode==this.Ap.qt?this.Rq(a):this.lD(a)},Kv:function(a){if(this.options.mode==this.Ap.wL){var b=this.sa(),d=0;null!=b&&(d=b.totalSize());b=this.options.pageSize;a=a.index;var e=this.Sk(this.ke());if(e!=this.O||a>=e&&a<e+b&&d>b)this.O=e,this.bi=!0}this.Yb()},Lv:function(){0>=this.Dc()?this.O=0:this.ke()>this.Dc()&&(this.O=this.Sk(this.Dc()),this.bi=!0);
1<this.Dc()&&(this.bi=!0);this.Yb()},HQ:function(c,b){try{b.value!=this.ke()&&!isNaN(b.value)&&0<b.value&&this.page(b.value)}catch(d){var e=this.J(this.eb.DK),f=this.J(this.eb.CK);a.C.error(e+"\n"+f)}},US:function(){var a=this.GP();a[0].parentNode.removeChild(a[0]);this.vB();this.jN()},VS:function(){var a=this.options.overflow;this.ln().empty();this.kN();this.wB();this.WS();if("fit"==a){var a=this.element.width(),b=this.QC(),d=this.IP(),e=this.KP(),f=this.JP(),h=null!=b?b[0].offsetWidth:0,k=null!=
d?d[0].offsetWidth:0,d=null!=e?e.width():0,l=null!=f?f.width():0,h=h+k;h>a?h-d<=a?e.css("display","none"):h-d-l<=a?(null!=e&&e.css("display","none"),null!=f&&f.css("display","none")):(null!=e&&e.css("display","none"),null!=f&&f.css("display","none"),null!=b&&b.css("display","none")):0<h&&(null!=e&&e.css("display",""),null!=f&&f.css("display",""),null!=b&&b.css("display",""))}},WS:function(){var a=this.QC(),b=a.children("."+this.pa.vt);b&&0<b.length&&(b=f(b[0]),1==this.ke()?(b.addClass(this.Ca.lb),
b.removeClass(this.Ca.yd),b.attr("tabindex","-1")):(b.addClass(this.Ca.yd),b.removeClass(this.Ca.lb),b.attr("tabindex","0")));(b=a.children("."+this.pa.zt))&&0<b.length&&(b=f(b[0]),1==this.ke()?(b.addClass(this.Ca.lb),b.removeClass(this.Ca.yd),b.attr("tabindex","-1")):(b.addClass(this.Ca.yd),b.removeClass(this.Ca.lb),b.attr("tabindex","0")));(b=a.children("."+this.pa.xt))&&0<b.length&&(b=f(b[0]),this.ke()==this.Dc()||0>=this.Dc()?(b.addClass(this.Ca.lb),b.removeClass(this.Ca.yd),b.attr("tabindex",
"-1")):(b.addClass(this.Ca.yd),b.removeClass(this.Ca.lb),b.attr("tabindex","0")));(a=a.children("."+this.pa.yt))&&0<a.length&&(a=f(a[0]),this.ke()==this.Dc()||0===this.Dc()||0>this.Dc()&&null!=this.sa()&&0===this.sa().size()?(a.addClass(this.Ca.lb),a.removeClass(this.Ca.yd),a.attr("tabindex","-1")):(a.addClass(this.Ca.yd),a.removeClass(this.Ca.lb),a.attr("tabindex","0")))},Qn:function(){var c=this.sa();if(null!=c){this.Pj();this.sb=[];this.sb.push({eventType:a.kb.v.ADD,eventHandler:this.Kv.bind(this)});
this.sb.push({eventType:a.kb.v.REMOVE,eventHandler:this.Lv.bind(this)});this.sb.push({eventType:a.kb.v.RESET,eventHandler:this.Rq.bind(this)});this.sb.push({eventType:a.kb.v.REFRESH,eventHandler:this.lD.bind(this)});this.sb.push({eventType:a.kb.v.SYNC,eventHandler:this.Jv.bind(this)});this.sb.push({eventType:a.kb.v.SORT,eventHandler:this.Sq.bind(this)});var b,d;for(b=0;b<this.sb.length;b++)(d=c.on(this.sb[b].eventType,this.sb[b].eventHandler))&&(this.sb[b].eventHandler=d)}},kl:function(c){if(!this.aw){var b=
this;a.da.Bh(c[0],function(){b.Yb()});this.aw=!0}},Pj:function(){var a=this.sa();if(null!=this.sb&&null!=a){var b;for(b=0;b<this.sb.length;b++)a.off(this.sb[b].eventType,this.sb[b].eventHandler)}},Fk:function(a,b){var d=f(document.createElement("span"));d.addClass(b);d.addClass(this.pa.Df);d.append(a);return d},LN:function(){var a=this.bf(),b=this.J(this.eb.cL),b=this.Fk(b,this.pa.Zz),d=this.element.attr("id")+"_oj_pgCtrl_acc_label";b.attr("id",d);a.append(b);return b},PN:function(){var a=this.J(this.eb.aL);
return this.Fk(a,this.pa.HL)},MN:function(){var a=this.J(this.eb.YK);return this.Fk(a,this.pa.zL)},NN:function(){var a=this.J(this.eb.ZK);return this.Fk(a,this.pa.CL)},ON:function(){var a=this.J(this.eb.$K);return this.Fk(a,this.pa.EL)},QN:function(){var a=this.J(this.eb.bL);return this.Fk(a,this.pa.JL)},RN:function(){var a=this.bf(),b=f(document.createElement("div"));b.addClass(this.pa.$z);var d=this.FP().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",d);a.append(b);return b},SN:function(){var a=
this.ln(),b=f(document.createElement("div"));b.addClass(this.pa.aA);a.append(b);return b},TN:function(){var a=this.mn(),b=f(document.createElement("a"));b.addClass(this.pa.bA);var d=this.J(this.eb.dL);b.append(d);b.attr("tabindex","0");b.attr("href","#");a.append(b);return b},vB:function(){this.sa();var a=this.mn(),b=f(document.createElement("span"));b.addClass(this.pa.cA);var d=this.HC();b.append(d);a.append(b);return b},wB:function(){var a=this.options.pageOptions.layout;null==a&&(a=[this.zd.ok]);
var b=this.ln(),d=f(document.createElement("div"));d.addClass(this.pa.eA);b.append(d);if(-1!=f.inArray(this.zd.ok,a)||-1!=f.inArray(this.zd.sm,a)||-1!=f.inArray(this.zd.RK,a)){b=f(document.createElement("div"));b.addClass(this.pa.hA);d.append(b);var e=f(document.createElement("label"));e.addClass(this.pa.BL);var g=this.J(this.eb.eL);e.append(g);b.append(e);g=f(document.createElement("input"));g.addClass(this.pa.fA);var h=this.J(this.eb.aM);this._focusable(this.element);g.attr("title",h);g.attr("tabindex",
"0");g.val(this.ke());e.append(g);e=0;if(0<this.Dc()){e=this.Dc();h=f(document.createElement("span"));h.addClass(this.pa.gA);var k=this.J(this.eb.fL,{pageMax:e});h.append(k);b.append(h)}else e=null!=this.sa()&&0<this.sa().size()?this.ke()+1:this.ke();g.ojInputText({rootAttributes:{style:"width: auto; min-width: 0;"},optionChange:this.HQ.bind(this),validators:[{type:"numberRange",options:{min:1,max:e}}]});if(-1!=f.inArray(this.zd.ok,a)||-1!=f.inArray(this.zd.sm,a)||-1!=f.inArray(this.zd.ML,a))g=f(document.createElement("span")),
g.addClass(this.pa.wt),e=this.HC(),e=this.J(this.eb.gL,{pageSummary:e}),g.append(e),b.append(g)}b=f(document.createElement("div"));b.addClass(this.pa.dA);d.append(b);if(-1!=f.inArray(this.zd.ok,a)||-1!=f.inArray(this.zd.sm,a)||-1!=f.inArray(this.zd.Wz,a))g=f(document.createElement("a")),g.addClass(this.pa.Dp),g.addClass(this.pa.vt),g.addClass(this.pa.AL),g.addClass(this.pa.cj),g.addClass(this.Ca.Yi),g.addClass(this.Ca.lb),e=this.J(this.eb.$L),this._hoverable(g),this._focusable(g),g.attr("title",e),
g.attr("tabindex","0"),g.attr("href","#"),e=this.MN(),g.append(e),b.append(g),g=f(document.createElement("a")),g.addClass(this.pa.Dp),g.addClass(this.pa.zt),g.addClass(this.pa.KL),g.addClass(this.pa.cj),g.addClass(this.Ca.Yi),g.addClass(this.Ca.lb),e=this.J(this.eb.eM),this._hoverable(g),this._focusable(g),g.attr("title",e),g.attr("tabindex","0"),g.attr("href","#"),e=this.QN(),g.append(e),b.append(g);if(-1!=f.inArray(this.zd.ok,a)||-1!=f.inArray(this.zd.sm,a)||-1!=f.inArray(this.zd.xL,a))g=f(document.createElement("div")),
g.addClass(this.pa.GL),b.append(g),this.UN(g,this.BP());if(-1!=f.inArray(this.zd.ok,a)||-1!=f.inArray(this.zd.sm,a)||-1!=f.inArray(this.zd.Wz,a))a=f(document.createElement("a")),a.addClass(this.pa.Dp),a.addClass(this.pa.yt),a.addClass(this.pa.FL),a.addClass(this.pa.cj),a.addClass(this.Ca.Yi),a.addClass(this.Ca.lb),g=this.J(this.eb.cM),this._hoverable(a),this._focusable(a),a.attr("title",g),a.attr("tabindex","0"),a.attr("href","#"),g=this.ON(),a.append(g),b.append(a),a=f(document.createElement("a")),
a.addClass(this.pa.Dp),a.addClass(this.pa.xt),a.addClass(this.pa.DL),a.addClass(this.pa.cj),a.addClass(this.Ca.Yi),a.addClass(this.Ca.lb),g=this.J(this.eb.bM),this._hoverable(a),this._focusable(a),a.attr("title",g),a.attr("tabindex","0"),a.attr("href","#"),g=this.NN(),a.append(g),b.append(a);return d},UN:function(a,b){if(5>b){var d=this.J(this.eb.BK),e=this.J(this.eb.AK);throw Error(d+"\n"+e);}d=f(document.createElement("div"));d.addClass(this.pa.iA);a.append(d);var e=this.Dc(),g=this.ke(),h=b,k=
[];if(1<=g){if(-1!=e&&e<=h)for(h=k[0]=1;h<e;h++)k[h]=h+1;else{k.push(1);1!=g&&k.push(g);g!=e&&-1!=e&&k.push(e);var h=h-k.length,l=g-1,m=1;if(g==e||g==e-1)m=0;for(;h>m&&1<l;)k.push(l),l--,h--;g+=1;for(-1==e&&(h=null!=this.sa()&&0<this.sa().size()?1:0);0<h&&(g<=e||-1==e);)k.push(g),g++,h--}k.sort(function(a,b){return a-b});for(h=0;h<k.length;h++)g=k[h],this.vu(d,g),h!=k.length-1&&g!=k[h+1]-1&&this.vu(d,-1);-1==e&&this.vu(d,-1)}return d},vu:function(a,b){var d=this.ke(),e=null;-1==b?(e=f(document.createElement("span")),
e.append("...")):(d==b?(e=f(document.createElement("div")),e.addClass(this.Ca.rc),e.addClass(this.Ca.Pd),e.addClass(this.Ca.lb),e.removeClass(this.Ca.yd)):(e=f(document.createElement("a")),e.removeClass(this.Ca.rc),e.removeClass(this.Ca.Pd),e.removeClass(this.Ca.lb),e.addClass(this.Ca.yd)),e.attr("data-oj-pagenum",b),e.addClass(this.pa.IL),d=this.J(this.eb.dM,{pageNum:b.toString()}),this._hoverable(e),this._focusable(e),e.attr("title",d),e.attr("tabindex","0"),e.attr("href","#"),d=this.PN(),e.append(d),
e.append(b.toString()),this._hoverable(e));a.append(e);return e},FP:function(){var a=this.bf(),b=null;a&&(b=a.find("."+this.pa.Zz))&&0<b.length&&(b=f(b.get(0)));return b},bf:function(){return f(this.element)},ln:function(){if(!this.XA){var a=this.bf(),b=null;a&&(b=a.find("."+this.pa.$z))&&0<b.length&&(this.XA=f(b.get(0)))}return this.XA},mn:function(){if(!this.YA){var a=this.ln(),b=null;a&&(b=a.children("."+this.pa.aA))&&0<b.length&&(this.YA=f(b.get(0)))}return this.YA},aY:function(){if(!this.ZA){var a=
this.mn(),b=null;a&&(b=a.children("."+this.pa.bA))&&0<b.length&&(this.ZA=f(b.get(0)))}return this.ZA},GP:function(){if(!this.Vt){var a=this.mn(),b=null;a&&(b=a.children("."+this.pa.cA))&&0<b.length&&(this.Vt=f(b.get(0)))}return this.Vt},nn:function(){if(!this.Wt){var a=this.ln(),b=null;a&&(b=a.children("."+this.pa.eA))&&0<b.length&&(this.Wt=f(b.get(0)))}return this.Wt},HP:function(){if(!this.Xt){var a=this.nn(),b=null;a&&(b=a.find("."+this.pa.fA))&&0<b.length&&(this.Xt=f(b.get(0)))}return this.Xt},
JP:function(){if(!this.Yt){var a=this.nn(),b=null;a&&(b=a.find("."+this.pa.wt))&&0<b.length&&(this.Yt=f(b.get(0)))}return this.Yt},KP:function(){var a=this.nn(),b=null;a&&(b=a.find("."+this.pa.iA))&&0<b.length&&(b=f(b.get(0)));return b},QC:function(){var a=this.nn(),b=null;if(a)if((b=a.find("."+this.pa.dA))&&0<b.length)b=f(b.get(0));else return null;return b},IP:function(){var a=this.nn(),b=null;if(a)if((b=a.find("."+this.pa.hA))&&0<b.length)b=f(b.get(0));else return null;return b}})})()});
//# sourceMappingURL=oj-modular.map