/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(a,f){a.La("oj.ojRadioset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:null},refresh:function(){this._super();this.yf.each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.yf=this.uq().filter(".oj-radio")._ojRadioCheckbox("refresh").end().not(".oj-radio")._ojRadioCheckbox().end();
this.ub()},widget:function(){return this.zJ},_InitOptions:function(c,b){var d;this._super(c,b);a.ud.Ji([{attribute:"disabled",defaultOptionValue:!1,validateOption:!0},{attribute:"placeholder",defaultOptionValue:""},{attribute:"required",defaultOptionValue:!1,coerceDomValue:!0,validateOption:!0},{attribute:"title",defaultOptionValue:""}],b,this);null==this.options.value&&(d=this.uq(),d=d.filter(":checked"),d=0===d.length?null:d.val(),this.options.value=d)},_ComponentCreate:function(){this._super();
if(this.element.is("fieldset"))throw Error("ojRadioset cannot be bound to a fieldset. Use a div instead.");this.yf=this.uq()._ojRadioCheckbox();this.zJ=this.element.addClass("oj-radioset oj-component").attr("role","radiogroup");this._on(this.If);this.ub()},uq:function(){var c=this.element.find("input[type\x3dradio]:first");0===c.length&&a.C.warn("Could not find any input type\x3dradio within this element");c=c.attr("name");return void 0===c?this.element.find("input[type\x3dradio]").not("[name]"):
this.element.find("input[type\x3dradio][name\x3d"+c+"]")},_OpenContextMenu:function(a,b){var d=this.element.find("input[type\x3dradio]"),e=d.filter(":checked"),d=e.length?e:d.filter(":enabled").first();a.open(b,{launcher:d,initialFocus:"menu"})},ub:function(){!0===this.options.disabled?this.disable():!1===this.options.disabled&&this.enable()},If:{change:function(a){this.tp(a)}},tp:function(a){this._super(a)},Yg:function(){return this.sk()},hg:function(a){null!=a&&(a="[value\x3d'"+a+"']",void 0!==
a&&void 0!==this.yf&&(a=this.yf.filter(a),void 0!==a&&0<a.length?a.prop("checked")||a._ojRadioCheckbox("option","checked",!0):this.yf._ojRadioCheckbox("option","checked",!1)))},sk:function(){var a=this.yf.filter(":checked");return 0===a.length?null:a.val()},_GetDefaultStyleClass:function(){return"oj-radioset"},Cf:function(){return this.uq()},At:function(a){var b=this.zJ;a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},_setOption:function(a,b){this._superApply(arguments);"disabled"===
a&&(this.yf.each(function(){f(this).data("oj-_ojRadioCheckbox").Fm(b)}),this.yf._ojRadioCheckbox("refresh"))},getNodeBySubId:function(a){var b=this._super(a);b||(a=a.subId,"oj-radioset-inputs"===a&&(b=this.yf));return b||null},_destroy:function(){this._super();this.element.removeClass("oj-radioset oj-enabled oj-component").removeAttr("role");this.yf&&this.yf._ojRadioCheckbox("destroy")}})});
//# sourceMappingURL=oj-modular.map