/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,f){a.La("oj._ojRadioCheckbox",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:null,checked:null,type:null},label:function(){void 0===this.Rb&&(this.Rb=this.jv());return this.Rb},refresh:function(){this._super();this.ub()},widget:function(){return this.yJ},_InitOptions:function(a,b){this._super(a,b);if(null===this.options.checked)this.options.checked=void 0!==this.element.attr("checked")?
!!this.element.prop("checked"):!1;else if("boolean"!==typeof this.options.checked)throw Error("checked option must be a boolean");if(null===this.options.disabled)this.options.disabled=void 0!==this.element.attr("disabled")?!!this.element.prop("disabled"):!1;else if("boolean"!==typeof this.options.disabled)throw Error("disabled option must be a boolean");this.options.type=this.element.prop("type")},_ComponentCreate:function(){this._super();var a=this.options.type;"checkbox"==a?(this.yJ=this.element.addClass("oj-checkbox oj-component"),
this.Rb=this.jv(),this.Rb.addClass("oj-checkbox-label")):"radio"==a&&(this.yJ=this.element.addClass("oj-radio oj-component"),this.Rb=this.jv(),this.Rb.addClass("oj-radio-label"));var b=this;this._hoverable(this.element);this._focusable(this.element);this.Lp(this.element);f.each(b.Rb,function(){b._hoverable(this);b._focusable(this);b.Lp(this)});this._on(this.If)},Rh:function(){this._super();this.ub()},ub:function(){this.CF();this.options.checked?this._setOption("checked",!0):this._setOption("checked",
!1)},CF:function(){this.hd()?(this.element.prop("disabled",!0).removeAttr("aria-disabled").removeClass("oj-enabled").addClass("oj-disabled"),this.Rb.removeClass("oj-enabled").addClass("oj-disabled")):(this.element.prop("disabled",!1).removeAttr("aria-disabled").removeClass("oj-disabled").addClass("oj-enabled"),this.Rb.addClass("oj-enabled").removeClass("oj-disabled"))},If:{},_setOption:function(a,b){this._superApply(arguments);"disabled"===a&&(b=!!b,this.CF(b));"checked"===a&&(b?this.element.prop("checked",
!0):this.element.prop("checked",!1),this.element.toggleClass("oj-selected",b))},jv:function(){var a=this.element.closest("label"),b="label[for\x3d'"+this.element.prop("id")+"']";return a.add(f(b))},getNodeBySubId:function(a){var b=this._super(a);b||(a=a.subId,"oj-radiocheckbox-input"===a&&(b=this.element[0]),"oj-radiocheckbox-label"===a&&(b=this.label()[0]));return b||null},_destroy:function(){this._super();var a=this.options.type;"checkbox"==a?(this.element.removeClass("oj-checkbox oj-selected oj-disabled oj-enabled oj-component"),
this.Rb.removeClass("oj-enabled oj-disabled oj-checkbox-label")):"radio"==a&&(this.element.removeClass("oj-radio oj-selected oj-disabled oj-enabled oj-component"),this.Rb.removeClass("oj-enabled oj-disabled oj-radio-label"))}})});
//# sourceMappingURL=oj-modular.map