/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojmodel","ojs/ojdatacollection-common"],function(a,f){a.La("oj.ojRowExpander",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{context:null,expand:null,collapse:null},pe:{root:"oj-rowexpander",icon:"oj-component-icon",clickable:"oj-clickable-icon-nocontext",expand:"oj-rowexpander-expand-icon",collapse:"oj-rowexpander-collapse-icon",leaf:"oj-rowexpander-leaf-icon",lazyload:"oj-rowexpander-lazyload-icon",toucharea:"oj-rowexpander-touch-area",
indent:"oj-rowexpander-indent",iconspacer:"oj-rowexpander-icon-spacer",depth0:"oj-rowexpander-depth-0",depth1:"oj-rowexpander-depth-1",depth2:"oj-rowexpander-depth-2",depth3:"oj-rowexpander-depth-3",depth4:"oj-rowexpander-depth-4",depth5:"oj-rowexpander-depth-5",depth6:"oj-rowexpander-depth-6",depth7:"oj-rowexpander-depth-7"},Bl:{lm:7,$J:53},_create:function(){this._super();this.element.addClass(this.pe.root)},_init:function(){var a=this,b;this._super();b=this.options.context;this.va=b.component;
this.dc=b.datasource;this.depth=b.depth;this.Cg=b.state;this.Ti=b.key;this.index=b.index;this.Is=b.parentKey;this.tM();this.sM();this.Jr();if("expanded"===this.Cg||"collapsed"===this.Cg)f(this.wJ).on("click",function(b){b.preventDefault();a.kC()}),f(this.element).on("keypress",function(b){if((b.keyCode||b.which)===f.ui.keyCode.ENTER||f.ui.keyCode.SPACE)a.kC(),b.preventDefault(),b.target.focus()}),null!=this.va&&(this.uI=this.tQ.bind(this),f(this.va.element).on("ojkeydown",this.uI)),null!=this.dc&&
(this.tI=this.oQ.bind(this),this.sI=this.gQ.bind(this),this.dc.on("expand",this.tI,this),this.dc.on("collapse",this.sI,this));null!=this.va&&(this.rI=this.fQ.bind(this),f(this.va.element).on("ojactive",this.rI))},refresh:function(){this.element.empty();this._init()},_destroy:function(){null!=this.va&&(f(this.va.element).off("ojkeydown",this.uI),f(this.va.element).off("ojactive",this.rI));null!=this.dc&&(this.dc.off("expand",this.tI,this),this.dc.off("collapse",this.sI,this));this.removeClass(this.pe.root);
this.element.empty()},tM:function(){var a,b,d;d=this.depth-1;if(d<this.Bl.lm)a=f(document.createElement("span")).addClass(this.pe.indent).addClass(this.pe["depth"+d]),this.element.append(a);else{for(b=1;b<=d/this.Bl.lm;b++)a=f(document.createElement("span")).addClass(this.pe.indent).addClass(this.pe["depth"+this.Bl.lm]),this.element.append(a);a=d%this.Bl.lm;a<this.Bl.lm&&(a=f(document.createElement("span")).addClass(this.pe.indent).addClass(this.pe["depth"+a]),this.element.append(a))}},sM:function(){var a=
f(document.createElement("div")).addClass(this.pe.iconspacer);this.wJ=f(document.createElement("div")).addClass(this.pe.toucharea);this.icon=f(document.createElement("a")).attr("href","#").addClass(this.pe.icon).addClass(this.pe.clickable);this.element.append(a.append(this.wJ.append(this.icon)))},fj:function(a){this.icon.addClass(this.pe[a])},Ij:function(a){this.icon.removeClass(this.pe[a])},Jr:function(){switch(this.Cg){case "leaf":this.Ij("icon");this.Ij("clickable");this.fj("leaf");break;case "collapsed":this.fj("expand");
this.Qp(!1);break;case "expanded":this.fj("collapse");this.Qp(!0);break;case "loading":this.Ij("clickable"),this.fj("lazyload")}},Kw:function(){switch(this.Cg){case "leaf":this.Ij("leaf");this.fj("icon");this.fj("clickable");break;case "collapsed":this.Ij("expand");break;case "expanded":this.Ij("collapse");break;case "loading":this.Ij("lazyload"),this.fj("clickable")}},fQ:function(a,b){var d,e;null!=b.activeKey&&(d=b.activeKey.rowKey,this.Ti!==d||null!=b.previousActiveKey&&b.previousActiveKey.row==
b.activeKey.row||!this.va.Er||(d=this.J("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.dc.getWrappedDataSource().Le(this.Is)}),e="collapsed"===this.Cg?this.J("accessibleStateCollapsed"):"expanded"===this.Cg?this.J("accessibleStateExpanded"):"",this.va.Er({context:d,state:e})))},tQ:function(c,b){var d;this.Ti===b.rowKey&&(c=c.originalEvent,d=c.keyCode||c.which,a.da.Ho(c)&&(d==f.ui.keyCode.RIGHT?(this.fw(),this.dc.expand(this.Ti)):d==f.ui.keyCode.LEFT?(this.fw(),this.dc.collapse(this.Ti)):
c.altKey&&d==this.Bl.$J&&this.va.Er&&(d=this.J("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.dc.getWrappedDataSource().Le(this.Is)}),this.va.Er({context:d,state:""}))))},fw:function(){this.Kw();this.Cg="loading";this.Jr()},oQ:function(a){a=a.rowKey;a===this.Ti&&(this.Kw(),this.Cg="expanded",this.Jr(),this.Qp(!0),this._trigger("expand",null,{rowKey:a}))},gQ:function(a){a=a.rowKey;a===this.Ti&&(this.Kw(),this.Cg="collapsed",this.Jr(),this.Qp(!1),this._trigger("collapse",null,
{rowKey:a}))},kC:function(){var a=this.Cg;this.fw();"collapsed"===a?this.dc.expand(this.Ti):"expanded"===a&&this.dc.collapse(this.Ti)},Qp:function(a){this.icon.attr("aria-expanded",a)},getNodeBySubId:function(a){return null==a?this.element?this.element[0]:null:"oj-rowexpander-icon"===a.subId?this.icon:null}})});
//# sourceMappingURL=oj-modular.map