/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtSunburst"],function(a,f){a.Ye=function(a){this.f=a};o_("SunburstNode",a.Ye,a);a.Ye.prototype.qd=function(){return this.f?this.f.color:null};a.b.g("SunburstNode.prototype.getColor",{qd:a.Ye.prototype.qd});a.Ye.prototype.qe=function(){return this.f?this.f.label:null};a.b.g("SunburstNode.prototype.getLabel",{qe:a.Ye.prototype.qe});a.Ye.prototype.wo=function(){return this.f?this.f.size:null};a.b.g("SunburstNode.prototype.getSize",
{wo:a.Ye.prototype.wo});a.Ye.prototype.ue=function(){return this.f?this.f.tooltip:null};a.b.g("SunburstNode.prototype.getTooltip",{ue:a.Ye.prototype.ue});a.Ye.prototype.isSelected=function(){return this.f?this.f.selected:!1};a.b.g("SunburstNode.prototype.isSelected",{isSelected:a.Ye.prototype.isSelected});a.La("oj.ojSunburst",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{optionChange:null,rotateInput:null},Af:function(a,b,d){return DvtSunburst.newInstance(a,b,d)},$e:function(){var a=
this._super();a.push("oj-sunburst");return a},Zi:function(){var a=this._super();a["oj-sunburst-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-attribute-value-text"]={path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-sunburst-node oj-hover"]={path:"nodeDefaults/hoverColor",property:"border-top-color"};a["oj-sunburst-node oj-selected"]=
[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];return a},$i:function(){return["optionChange","rotateInput"]},zm:function(){var a=this._super();a["DvtSunburstBundle.COLOR"]=this.qc("labelColor");a["DvtSunburstBundle.SIZE"]=this.qc("labelSize");return a},aj:function(a){var b=a&&a.getType?a.getType():null;b===DvtSelectionEvent.TYPE?this.ig("selection",a.getSelection()):b===DvtSunburstRotationEvent.TYPE?this.ig("startAngle",
a.getStartAngle()):b===DvtSunburstRotationEvent.TYPE_INPUT?this._trigger("rotateInput",null,{value:a.getStartAngle()}):this._super(a)},rt:function(){null==this.options._resources&&(this.options._resources={});this.options._resources.rotateCursor=a.ja.ib("resources/internal-deps/dvt/sunburst/rotate.cur")},bj:function(a){return"selection"==a||"startAngle"==a},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getNode:function(c){var b=this.Sa.getAutomation();
return new a.Ye(b.getNode(c))}})});
//# sourceMappingURL=oj-modular.map