define(["ojs/ojcore","jquery","ojs/ojdatacollection-common","ojs/ojmodel"],function(a){a.ya=function(f){f=f||{};this.Xo=f.root;this.rV=f.childCollectionCallback;this.Ul=f.parseMetadata;this.fk=null;this.cm="none";this.Fc={};a.ya.t.constructor.call(this)};o_("CollectionTreeDataSource",a.ya,a);a.ya.prototype.Ul=function(a){return{key:a.idAttribute+"\x3d"+a.id}};a.b.ra(a.ya,a.zc,"oj.CollectionTreeDataSource");a.ya.prototype.Init=function(){a.ya.t.Init.call(this)};a.b.g("CollectionTreeDataSource.prototype.Init",
{Init:a.ya.prototype.Init});a.ya.prototype.Le=function(a){var c=this.Fc[a];if(c&&0<c.length)return c.length;this.Jx(a,{success:function(a){return a.length}});return-1};a.b.g("CollectionTreeDataSource.prototype.getChildCount",{Le:a.ya.prototype.Le});a.ya.prototype.Jx=function(a,c){this.Wd(a,null,{success:function(a){c.success(a.oa)},error:c.error})};a.b.g("CollectionTreeDataSource.prototype.getChildCollection",{Jx:a.ya.prototype.Jx});a.ya.prototype.Wd=function(a,c,b){c=c||{};var d=c.start?c.start:
0,e=c.count?c.count:-1;if(null===a)this.hm(null,d,e,b,null);else{var g=this;this.nv(this.Xo,a,0).then(function(c){c?(c=g.ip(c.Ro),g.hm(c,d,e,b,a)):b&&b.error&&b.error(a)})}};a.b.g("CollectionTreeDataSource.prototype.fetchChildren",{Wd:a.ya.prototype.Wd});a.ya.prototype.WJ=function(a,c,b){var d=0;b&&b.at&&(d=b.at);a=this.fq(this,"insert",d,this.Mq(c),this.YE(a));this.handleEvent("insert",a)};a.ya.prototype.XJ=function(a,c,b){var d=0;b&&b.index&&(d=b.index);this.iT(a);a=this.fq(this,"delete",d,this.Mq(c),
null);this.handleEvent("delete",a)};a.ya.prototype.YJ=function(a){var c=this.dP(a),b=null,d=null;c&&(b=c.index,d=this.Mq(c.oa));a=this.fq(this,"update",b,d,this.YE(a));this.handleEvent("update",a)};a.ya.prototype.JJ=function(a){a=this.fq(this,"refresh",null,this.Mq(a),null);this.handleEvent("refresh",a)};a.ya.prototype.YE=function(f){var c=[];c.push(f.attributes);var b={};b.idAttribute=f.idAttribute;f=new a.aa(c,b);f.fetch();return f};a.ya.prototype.Mq=function(f){var c=[],b=null;do b=this.LP(f),
null!==b&&(b!==a.ya.hz&&c.unshift(b),f=this.eP(b));while(null!=b);return c};a.ya.hz="%!@ROOT%#@!";a.ya.prototype.Aq=function(f){var c=f instanceof a.q?this.Ul(f).key:f;return f?c:a.ya.hz};a.ya.prototype.yA=function(a){return this.Fc[this.Aq(a)]};a.ya.prototype.XF=function(f,c){c.on(a.X.v.ADD,this.WJ,this);c.on(a.X.v.REMOVE,this.XJ,this);c.on(a.X.v.CHANGE,this.YJ,this);c.on(a.X.v.SYNC,this.JJ,this);this.Fc[this.Aq(f)]=c};a.ya.prototype.iT=function(a){a=this.Aq(a);for(var c in this.Fc)if(this.Fc.hasOwnProperty(c)&&
c===a){this.Fc[a].off(null,null,this);delete this.Fc[a];break}};a.ya.prototype.IR=function(a,c){for(var b=c.length,d=0;d<b;d++){var e=this.Aq(c.at(d));if(a===e)return!0}return!1};a.ya.prototype.dP=function(a){for(var c in this.Fc)if(this.Fc.hasOwnProperty(c))for(var b=this.Fc[c],d=0;d<b.length;d++)if(b.at(d)===a)return{index:d,oa:b};return null};a.ya.prototype.eP=function(a){for(var c in this.Fc)if(this.Fc.hasOwnProperty(c)){var b=this.Fc[c];if(this.IR(a,b))return b}return null};a.ya.prototype.LP=
function(a){for(var c in this.Fc)if(this.Fc.hasOwnProperty(c)&&this.Fc[c]===a)return c;return null};a.ya.prototype.ip=function(a){var c=!0,b=this.yA(a);b||(c=!1,b=this.rV(this.Xo,a),null!=b&&(this.PA(b),this.XF(a,b)));return{oa:b,sx:c}};a.ya.prototype.fq=function(a,c,b,d,e){return{source:a,operation:c,index:b,parent:d,data:e}};a.ya.prototype.hm=function(a,c,b,d,e){var g=this;null===a&&((a=this.yA(null))?a={oa:a,sx:!0}:(a={oa:g.Xo,sx:!1},g.XF(null,this.Xo)));a&&g.eC(a,function(a){d.success&&d.success(g.EP(a,
e,c,b))},d.error)};a.ya.prototype.EP=function(f,c,b,d){return new a.Qc(c,f,this,b,d)};a.ya.prototype.IT=function(f,c){var b=this;return a.b.la(function(a){function e(c,f,k){c<f.length?f.at(c,{deferred:!0}).then(function(l){if(l){var m=b.Ul(l);if(k===m.key){a(l);return}}c++;e(c,f,k)}):a(null)}e(0,f,c)})};a.ya.prototype.nv=function(f,c,b){var d=this;return a.b.la(function(a){d.IT(f,c).then(function(g){function h(d,g){if(d<k){var n=g.ip(f.at(d));n.oa?g.eC(n,function(f){g.nv(f,c,b+1).then(function(b){b?
a(b):(d++,h(d,g))})},null):(d++,h(d,g))}else a(null)}if(g)a({Ro:g,depth:b});else{var k=f.length;h(0,d)}})})};a.ya.prototype.eC=function(a,c,b){a.sx?c(a.oa):(this.fk&&"none"!==this.fk&&(a.oa.gf=this.fk,a.oa.bm=this.cm),0<a.oa.length?c(a.oa):a.oa.fetch({success:function(a){c(a)},error:b}))};a.ya.prototype.Dh=function(a,c){var b=this;null===a?this.hm(null,0,-1,{success:function(a){a.Wy({success:function(){c.success&&c.success(a)}})}},null):this.nv(this.Xo,a,0).then(function(d){d&&(d=b.ip(d.Ro),b.hm(d,
0,-1,{success:function(a){a.Wy({success:function(){c.success&&c.success(a)}})}},a))})};a.b.g("CollectionTreeDataSource.prototype.fetchDescendants",{Dh:a.ya.prototype.Dh});a.ya.prototype.sort=function(a,c){var b=a.key,d=a.direction,e=!1;b!==this.fk&&(this.fk=b,e=!0);d!==this.cm&&(this.cm=d,e=!0);if(e){"none"===this.cm&&(this.Fc={});for(var g in this.Fc)this.Fc.hasOwnProperty(g)&&this.PA(this.Fc[g])}c&&c.success&&c.success()};a.b.g("CollectionTreeDataSource.prototype.sort",{sort:a.ya.prototype.sort});
a.ya.prototype.PA=function(a){a.comparator=this.fk;a.sortDirection="ascending"===this.cm?1:-1;a.sort()};a.ya.prototype.xo=function(){return{key:this.fk,direction:this.cm}};a.b.g("CollectionTreeDataSource.prototype.getSortCriteria",{xo:a.ya.prototype.xo});a.ya.prototype.move=function(){a.i.fa()};a.b.g("CollectionTreeDataSource.prototype.move",{move:a.ya.prototype.move});a.ya.prototype.Oi=function(){return"invalid"};a.b.g("CollectionTreeDataSource.prototype.moveOK",{Oi:a.ya.prototype.Oi});a.ya.prototype.getCapability=
function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};a.b.g("CollectionTreeDataSource.prototype.getCapability",{getCapability:a.ya.prototype.getCapability});a.Qc=function(a,c,b,d,e){this.Is=a;this.oa=c;this.wx=[];this.cp=b;this.start=d<c.length?d:c.length-1;this.count=-1===e?c.length:Math.min(c.length,e)};o_("CollectionNodeSet",a.Qc,a);a.Qc.prototype.Wy=function(a){this.hC(this).then(function(){a.success&&a.success()})};a.Qc.prototype.hC=
function(f){return a.b.la(function(a){function b(e){e<d?f.OJ(e,{success:function(a){null!==a?f.hC(a).then(function(){b(e+1)}):b(e+1)}}):a()}var d=f.Z();b(0)})};a.Qc.prototype.OJ=function(a,c){var b=this.oa.at(a);if(this.cp.Ul(b).leaf)this.wx[a]=null,c.success(null);else{var d=this.cp.ip(b),b=this.cp.Ul(b).key,e=this;this.cp.hm(d,0,-1,{success:function(b){e.wx[a]=b;c.success(b)}},b)}};a.Qc.prototype.getParent=function(){return this.Is};a.b.g("CollectionNodeSet.prototype.getParent",{getParent:a.Qc.prototype.getParent});
a.Qc.prototype.Ia=function(){return this.start};a.b.g("CollectionNodeSet.prototype.getStart",{Ia:a.Qc.prototype.Ia});a.Qc.prototype.Z=function(){return this.count};a.b.g("CollectionNodeSet.prototype.getCount",{Z:a.Qc.prototype.Z});a.Qc.prototype.getData=function(a){this.iu(a);return this.oa.at(a).attributes};a.b.g("CollectionNodeSet.prototype.getData",{getData:a.Qc.prototype.getData});a.Qc.prototype.iu=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};a.Qc.prototype.getMetadata=
function(a){this.iu(a);var c={};a=this.oa.at(a);a=this.cp.Ul(a);c.key=a.key;c.leaf=a.leaf;c.depth=a.depth;return c};a.b.g("CollectionNodeSet.prototype.getMetadata",{getMetadata:a.Qc.prototype.getMetadata});a.Qc.prototype.Gd=function(a){this.iu(a);return this.wx[a]};a.b.g("CollectionNodeSet.prototype.getChildNodeSet",{Gd:a.Qc.prototype.Gd})});
//# sourceMappingURL=oj-modular.map