define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){a.La("oj.ojTrain",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selected:"",optionChange:null,beforeDeselect:null,deselect:null,beforeSelect:null,select:null},Ge:0,zb:null,_ComponentCreate:function(){this._super();var a=this.options,b=a.steps;this.Ge=b.length;this.xl=f("\x3cdiv class\x3d'oj-train-wrapper'\x3e\x3c/div\x3e");this.xl.appendTo(this.element);this.Rm=
f("\x3cdiv class\x3d'oj-train-connector-wrapper'\x3e\x3c/div\x3e");this.Rm.appendTo(this.xl);(this.zG=0<=this.element.attr("class").indexOf("oj-train-stretch")?!0:!1)&&this.Rm.css("padding","0 "+100/(2*this.Ge)+"%");this.pu=f("\x3cdiv class\x3d'oj-train-connector'\x3e\x3c/div\x3e");this.pu.appendTo(this.Rm);this.Ed=f("\x3cul\x3e");this.Ed.addClass("oj-train-step-list");this.bq=f("\x3cdiv class\x3d'oj-train-connector-fill'\x3e\x3c/div\x3e");this.bq.appendTo(this.Rm);this.fU();this.cf=this.Dv(a.selected);
-1===this.cf&&(this.cf=0,a.selected=b[0].id);for(a=0;a<this.Ge;a++)b=f("\x3cli\x3e").addClass("oj-train-step-list-item").attr({id:this.zb[a][1]}),b.appendTo(this.Ed),this.xO(a),this.AO(a),this.wO(a),this.yO(a),this.zG&&b.css("width",100/this.Ge+"%");this.bq.css({width:(this.Ge-1===this.cf?100:100/(2*(this.Ge-1))+this.cf/(this.Ge-1)*100)+"%"});this.Ed.appendTo(this.xl);this.element.addClass("oj-train")},fU:function(){var a=this.options;this.zb=[];for(var b=0;b<this.Ge;b++){var d=a.steps[b];this.zb[b]=
Array(5);this.zb[b][0]=d.label?d.label:null;this.zb[b][1]=d.id?d.id:null;this.zb[b][2]=d.disabled?!0:!1;this.zb[b][3]=d.visited?!0:!1;this.zb[b][4]=d.messageType?d.messageType:null}},wO:function(a){var b=f("\x3cdiv/\x3e").addClass("oj-train-button"),d=f("\x3cspan/\x3e"),e=this,g="";if(this.zb[a]){var h=this.zb[a][3],k=this.zb[a][2];this.cf===a?(b.addClass("oj-selected"),g=" current "):h&&!k?(b.addClass("oj-visited"),g=" visited "):h||k?b.addClass("oj-disabled"):(b.addClass("oj-default"),g=" not visited ");
this.zb[a][2]||this.cf===a||(this._hoverable(b),b.on("click"+this.eventNamespace,function(){e.Cc("selected",e.options.selected,this.parentNode.parentNode.id,!0);e.refresh()}));h=this.Ed.children().eq(a).find(".oj-train-button-connector");1<=h.length&&h.children().remove();h.append(b);d.text(g);d.addClass("oj-helper-hidden-accessible");this.Ed.children().eq(a).find("a").append(d)}},yO:function(a){var b=f("\x3cdiv/\x3e").addClass("oj-train-icon"),d=f("\x3cspan/\x3e"),e="",g=this;if(this.zb[a]){var h=
this.zb[a][4];"confirmation"===h?(b.addClass("oj-confirmation"),e=" Confirmation "):"info"===h?(b.addClass("oj-info"),e=" Info "):"error"===h?(b.addClass("oj-error"),e=" Error "):"fatal"===h?(b.addClass("oj-error"),e=" Error "):"warning"===h&&(b.addClass("oj-warning"),e=" Warning ");var k=this.Ed.children().eq(a).find(".oj-train-button");1<=k.children().length&&k.children().remove();this.zb[a][2]||this.cf===a||(this._hoverable(b),b.on("click"+this.eventNamespace,function(){g.Cc("selected",g.options.selected,
this.parentNode.parentNode.parentNode.id,!0);g.refresh()}));null!=h&&(d.text(e),d.addClass("oj-helper-hidden-accessible"),this.Ed.children().eq(a).find("a").append(d),k.append(b))}},Cc:function(a,b,d,e){var f={option:a,previousValue:b,value:d,optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};a={option:a,fromStep:this.getStep(b),toStep:this.getStep(d),optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};!1!==this._trigger("beforeDeselect",null,a)&&!1!==this._trigger("beforeSelect",
null,a)&&(b=this.Dv(b),-1!==b&&(this.options.steps[b].visited=!0),this._trigger("deselect",null,a),this.options.selected=d,this._trigger("select",null,a),this._trigger("optionChange",e,f))},AO:function(a){var b=f("\x3cdiv/\x3e");b.addClass("oj-train-button-connector");this.zb[a]&&(a<=this.cf&&b.addClass("oj-train-fill"),a=this.Ed.children().eq(a).children(),b.insertBefore(a))},xO:function(a){var b=this;if(this.zb[a]){var d=f("\x3cdiv/\x3e").addClass("oj-train-label-wrapper"),e=f("\x3ca\x3e"+this.zb[a][0]+
"\x3c/a\x3e"),g=this.zb[a][2];d.append(e);e.addClass("oj-train-label");a===this.cf?e.addClass("oj-selected"):this.zb[a][3]&&!g?e.addClass("oj-visited"):g&&e.addClass("oj-disabled");g||this.cf===a||(e.attr("href","#"),this._hoverable(e),e.on("click keydown"+this.eventNamespace,function(a){if(a.keyCode===f.ui.keyCode.ENTER||"click"===a.type)a.preventDefault(),b.Cc("selected",b.options.selected,this.parentNode.parentNode.id,!0),b.refresh()}));e=this.Ed.children().eq(a).children();1<=e.length&&e[0].remove();
this.Ed.children().eq(a).append(d)}},Dv:function(a){for(var b=0;b<this.Ge;b++)if(this.zb[b]&&this.zb[b][1]===a)return b;return-1},getStep:function(a){for(var b=0;b<this.Ge;b++)if(this.zb[b]&&this.zb[b][1]===a)return jQuery.extend({},this.options.steps[b]);return null},nextSelectableStep:function(){for(var a=this.cf;a<this.Ge;a++)if(a+1<this.Ge&&this.zb[a+1]&&!this.zb[a+1][2])return this.zb[a+1][1];return null},previousSelectableStep:function(){for(var a=this.cf;0<=a;a--)if(this.zb[a-1]&&!this.zb[a-
1][2])return this.zb[a-1][1];return null},setStep:function(a){if(a.id){var b=this.getStep(a.id),d=this.Dv(a.id);-1!==d&&(d=this.options.steps[d],a.label&&(b[0]=a.label,d.label=a.label),"boolean"===typeof a.disabled&&(b[2]=a.disabled,d.disabled=a.disabled),"boolean"===typeof a.visited&&(b[3]=a.visited,d.visited=a.visited),a.messageType&&(b[4]=a.messageType,d.messageType=a.messageType))}},_setOption:function(a,b,d){if("selected"===a){var e=this.options.selected;this.options.selected=b;e&&this.Cc("selected",
e,b,!0)}this._super(a,b,d)},_setOptions:function(a){this._super(a);this.refresh()},refresh:function(){this._super();this._destroy();this._ComponentCreate()},_destroy:function(){this.element.removeClass("oj-train oj-train-bar oj-train-wrapper oj-train-connector-wrapper oj-train-connector oj-train-connector-fill oj-train-fill oj-component-initnode");this.xl.remove();this.Rm.remove();this.pu.remove();this.bq.remove();this.Ed.remove();this.Ed.children().each(function(){f(this).remove()});this._super()},
getNodeBySubId:function(a){if(null===a)return this.element?this.element[0]:null;var b=a.index;if("number"!==typeof b||0>b||b>=this.Ge)return null;switch(a.subId){case "oj-train-button":return this.Ed.children().eq(b).find(".oj-train-button");case "oj-train-button-connector":return this.Ed.children().eq(b).find(".oj-train-button-connector");case "oj-train-connector":return this.pu;case "oj-train-connector-fill":return this.bq;case "oj-train-icon":return this.Ed.children().eq(b).find(".oj-train-icon");
case "oj-train-label":return this.Ed.children().eq(b).find(".oj-train-button")}return null}})})()});
//# sourceMappingURL=oj-modular.map