/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,f){(function(){function c(a){var b=!1,c=!0;a.Qs&&(a.title&&(b=f("style[id\x3d'"+a.title+"-stylesheet']")[0]),b?c=!1:(b=document.createElement("style"),b.setAttribute("type","text/css"),a.title&&b.setAttribute("id",a.title+"-stylesheet")),b.styleSheet?c?(document.getElementsByTagName("head")[0].appendChild(b),b.styleSheet.cssText=a.Qs):b.styleSheet.cssText=b.styleSheet.cssText+" "+a.Qs:(b.appendChild(document.createTextNode(a.Qs)),document.getElementsByTagName("head")[0].appendChild(b)))}
function b(a){n.push(a);f(a.UF).keydown(d)}function d(b){var c="";a.da.Ho(b)?c+="ctrl+":b.shiftKey&&(c+="shift+");var d=b.which;switch(d){case 32:c+="space";break;case 37:c+="left";break;case 38:c+="up";break;case 39:c+="right";break;case 40:c+="down";break;case 46:c+="del";break;case 33:c+="pgup";break;case 34:c+="pgdn";break;case 35:c+="end";break;case 36:c+="home";break;case 56:c="*";break;case 113:c+="f"+(1-(112-d))}if(0!==c.length){var e=void 0;f.each(n,function(a,d){if(d.FG.f.ui.Ke&&d.pD[c])return b.preventDefault(),
e=d.pD[c].call(d.FG,b),!1});return e}}function e(a){f.each(n,function(b){if(n[b].UF===a)return f(a).off("keydown"),n[b]=null,n.splice(b,1),!1})}var g={cut:"ojtreecut",copy:"ojtreecopy",paste:"ojtreepaste",remove:"ojtreeremove",rename:"ojtreerename"},h="optionChange hover dehover expand collapse loaded move remove rename refresh expandAll collapseAll destroy create before remove cut copy paste".split(" "),k,l,m;f(function(){/msie/.test(navigator.userAgent.toLowerCase())?(l=f('\x3ctextarea cols\x3d"10" rows\x3d"2"\x3e\x3c/textarea\x3e').css({position:"absolute",
top:-1E3,left:0}).appendTo("body"),m=f('\x3ctextarea cols\x3d"10" rows\x3d"2" style\x3d"overflow: hidden;"\x3e\x3c/textarea\x3e').css({position:"absolute",top:-1E3,left:0}).appendTo("body"),k=l.width()-m.width(),l.add(m).remove()):(l=f("\x3cdiv /\x3e").css({width:100,height:100,overflow:"auto",position:"absolute",top:-1E3,left:0}).prependTo("body").append("\x3cdiv /\x3e").find("div").css({width:"100%",height:200}),k=100-l.width(),l.parent().remove())});var n=[],q=-1,r=[];a.La("oj.ojTree",f.oj.baseComponent,
{widgetEventPrefix:"oj",defaultElement:"\x3cdiv\x3e",options:{dnd:{Zl:"disable"},expandParents:!1,initExpanded:null,qW:[],selection:[],selectionMode:"single",selectedParentCollapse:!1,selectedParentExpand:!0,selectPrevOnDelete:!1,data:null,emptyText:null,icons:!0,types:null,before:null,collapse:null,create:null,collapseAll:null,cut:null,dehover:null,remove:null,destroy:null,expand:null,expandAll:null,hover:null,loaded:null,move:null,optionChange:null,paste:null,refresh:null,rename:null},collapse:function(a,
b){var c=b?0:this.JA;a=this.qa(a);if(!a.length||-1===a||!a.hasClass("oj-expanded")||this.f.N.locked||a.hasClass("oj-disabled"))return!1;var d=this.Ma({obj:a,func:"collapse"},"before");if("boolean"!=typeof d||d)(b||c)&&a.children("ul").attr("style","display:block !important"),a.removeClass("oj-expanded").addClass("oj-collapsed").attr("aria-expanded","false"),f(a.children()[0]).removeClass("oj-selected").addClass("oj-default"),!b&&c?this.rG(a,!0):(a.children("ul")[0].style.display="none",this.Ma({obj:a},
"collapse"),this.after_close(a))},rG:function(a,b){var c,d,e;a.on("transitionend",f.proxy(this.Oj,this));c=f(a.children("ul"));b?(d=c[0].offsetHeight,e=0):(d=0,e=this.nP(c[0]));c.css("max-height",d+"px");c.css("overflow","hidden");b||(c[0].style.display="block");setTimeout(function(){c.addClass("oj-tree-transition");c.css("max-height",e+"px")},10)},nP:function(a){var b,c,d,e,g=f("\x3cdiv style\x3d'position: absolute'\x3e");b=a.parentNode;c=a.nextSibling;b.removeChild(a);e=a.style.display;a.style.display=
"block";g.append(a);this.$[0].appendChild(g[0]);d=a.offsetHeight||a.scrollHeight;a.style.display=e;this.$[0].removeChild(g[0]);g[0].removeChild(a);c?b.insertBefore(a,c):b.appendChild(a);return d},Oj:function(a){a=f(a.target);var b=a.closest("li");b.off("transitionend",this.Oj);b.hasClass("oj-collapsed")?(a[0].style.display="none",this.Ma({obj:b},"collapse"),this.after_close(b)):(a[0].style.display="block",a.css("max-height",""),this.Ma({obj:b},"expand"),this.after_open(b))},collapseAll:function(a,
b){var c=a?a:-1,d=this;if(!this.f.N.locked&&((a=a?this.qa(a):this.$)&&-1!==c&&(c=a),a&&-1!==c||(a=this.Y),!a.hasClass("oj-disabled"))){var e;-1!==c&&this.isExpanded(a)&&(e=a[0]);var f=a.find("li.oj-expanded");f.length&&f.each(function(){d.collapse(this,!b)});e&&(this.collapse(e,!b),f.splice(0,0,e));f.length&&this.Ma({obj:f,targ:c},"collapseAll")}},expand:function(a,b){this.kd(a,!1,b)},expanded:function(a,b){var c,d,e=this;if(a&&"array"===f.type(a)){if(this.f.N.locked)return null;d=a.length;f.each(a,
function(a,c){e.kd(c,!1,b)});return null}a=this.Y.find("li.oj-expanded");d=a.length;c=[];for(var g=0;g<d;g++)c.push(a[g]);return f(c)},expandAll:function(a,b){this.Mu(a,b)},toggleExpand:function(a,b){a=this.qa(a);if(-1!==a&&!a.hasClass("oj-disabled")&&!this.f.N.locked){if(a.hasClass("oj-collapsed"))return this.expand(a,b);if(a.hasClass("oj-expanded"))return this.collapse(a,b)}},deselect:function(a){var b=this.options.selection.slice(0);this.pj(a);this.Kk("selection",b,this.options.selection,null)},
deselectAll:function(a){if(!this.f.N.locked){var b=this.options.selection.slice(0);this.lq(a,!1);this.Kk("selection",b,this.options.selection,null)}},select:function(a){this.sg(a,!0)},toggleSelect:function(a){a=this.qa(a);if(!a.length)return!1;a.hasClass("oj-disabled")||this.f.N.locked||(this.isSelected(a)?this.pj(a):this.sg(a,!0))},isCollapsed:function(a){return(a=this.qa(a))&&-1!==a&&a.hasClass("oj-collapsed")},isExpanded:function(a){return(a=this.qa(a))&&-1!==a&&a.hasClass("oj-expanded")},isLeaf:function(a){return this.RD(a)},
isSelected:function(a){return 0<=this.f.ui.selected.index(this.qa(a))},create:function(a,b,c){return this.xu(a,b,c)},remove:function(a){a=this.qa(a);if(!a.length||a.hasClass("oj-disabled")||this.f.N.locked)return!1;var b=this.Ma({obj:a,func:"remove"},"before");if("boolean"==typeof b&&!b)return!1;this.ej();var b=this.ei(a),c=f([]),d=this,e=this.rh(a);a.each(function(){c=c.add(d.rh(this))});a=a.detach();-1!==b&&0===b.find("\x3e ul \x3e li").length&&b.removeClass("oj-expanded oj-collapsed").addClass("oj-tree-leaf").removeAttr("aria-expanded");
this.je(b);this.Ma({obj:a,prev:e,parent:b},"remove");return a},getText:function(a){a=this.qa(a);if(!a.length)return!1;var b=this.f.N.Bo;a=a.children("a:eq(0)");if(b)return a=a.clone(),a.children("INS").remove(),a.html();a=a.find("span:eq(0)");return a[0].textContent},rename:function(a,b){this.BF(a,b)},hover:function(a){a=this.qa(a);if(!a.length)return!1;if(!a.hasClass("oj-disabled")&&!this.f.N.locked){var b=this.Ma({obj:a,func:"hover"},"before");if("boolean"!=typeof b||b)this.f.N.xs=!0,a.hasClass("oj-hover")||
this.dehover(),this.f.ui.nb=a.children("a").addClass("oj-hover").parent(),this.Y.attr("aria-activedescendant",this.f.ui.nb.attr("id")),this.mC(a),this.Ma({obj:a},"hover")}},dehover:function(){var a=this.f.ui.nb,b;if(!a||!a.length)return!1;a.hasClass("oj-disabled")||this.f.N.locked||(b=a.children("a").removeClass("oj-hover").parent(),this.Y.removeAttr("aria-activedescendant"),this.f.ui.nb[0]===b[0]&&(this.f.ui.nb=null),this.Ma({obj:a},"dehover"))},getPath:function(a,b){var c=[],d=this;a=this.qa(a);
if(-1===a||!a||!a.length)return!1;a.parentsUntil(".oj-tree","li").each(function(){c.push(b?this.id:d.getText(this))});c.reverse();c.push(b?a.attr("id"):this.getText(a));return c},getRoot:function(){return this.$.children("ul:eq(0)")},refresh:function(a){this._super();this.f.N.locked||this.Yb(a)},move:function(a,b,c,d){this.bl(a,b,c,d)},getType:function(a){return this.Hv(a)},setType:function(a,b){return this.dU(a,b)},getNodeBySubId:function(a){return a?this.MS(a):this.element?this.element[0]:null},
getParent:function(a){return(a=this.ei(a))&&0<a.length?a:null},getPrevSibling:function(a){return(a=this.rh(a,!0))&&0<a.length?a:null},getNextSibling:function(a){return(a=this.tj(a,!0))&&0<a.length?a:null},getChildren:function(a){return(a=this.cP(a?a:-1))&&0<a.length?a:null},destroy:function(){this.Ma({obj:-1},"destroy");this._super()},_ComponentCreate:function(){this._super();this.md=this.kS();r.push(this);this.$h=this.element.attr("id");void 0===this.$h&&(this.$h="oj-tree-"+this.md,this.element.attr("id",
this.$h));this.$h="#"+this.$h;var a;a=(a=this.$h)?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$\x26"):"";this.$=f(a);this.Y=null;this.f={};this.EG=null;this.fi="rtl"===this.Ic();this.fR();this.JA=this.$O();this.ql()},_destroy:function(){this.qN();this.f.html.Rl&&(this.$.append(this.f.html.Rl),this.f.html.Ds.remove(),this.f.html.Ds=!1,this.f.html.Ts=!1);this.f.Aa.type=0;this._super()},_setOption:function(a,b,c){var d;if("selection"===a)d=this.options[a].slice(0),this._super(a,b,c),this.LQ(),
this.Kk(a,d,this.options.selection,null);else{if("selectionMode"===a)"none"===b?d=0:"single"===b?d=1:"multiple"===b?d=-1:(d=0,b="none"),d!=this.f.N.be&&(this.f.N.be=d);else if("icons"===a)"boolean"==f.type(b)&&b!=this.f.Pa.icons&&((this.f.Pa.icons=b)?this.Uw():this.Rv());else if("contextMenu"===a)this.aq(),b&&this.xn(b);else if("disabled"===a)this.mQ(b);else{if("data"===a){this._super(a,b,c);this.AD();this.BD();this.DD();this.dE();return}if("dnd"===a){this._super(a,b,c);this.CD();return}}this._super(a,
b,c)}},qN:function(){var a=this.md;this.$.unbind(".oj-tree").undelegate(".oj-tree").removeData("oj-tree-instance-id").find("[class^\x3d'oj-tree']").addBack().attr("class",function(){return this.className.replace(/oj-tree[^ ]*|$/ig,"")});var b=this.$.attr("class"),b=b.trim();0===b.length&&this.$.removeAttr("class");e(this.Y);f(document).unbind(".oj-tree-"+a).undelegate(".oj-tree-"+a);this.Y.remove();this.Y=null},qa:function(a,b){if("undefined"===typeof a||null===a)return b?this.f.ui.selected:this.f.ui.Hb;
var c=f(a,this.$);if(c.is(".oj-tree")||-1===a)return-1;c=c.closest("li",this.$);return c.length?c:!1},rh:function(a,b){a=this.qa(a);if(-1===a)return this.$.find("\x3e ul \x3e li:last-child");if(!a.length)return!1;if(b)return 0<a.prevAll("li").length?a.prevAll("li:eq(0)"):!1;if(a.prev("li").length){for(a=a.prev("li").eq(0);a.hasClass("oj-expanded");)a=a.children("ul:eq(0)").children("li:last");return a}var c=a.parentsUntil(".oj-tree","li:eq(0)");return c.length?c:!1},tj:function(a,b){a=this.qa(a);
return-1===a?this.$.find("\x3e ul \x3e li:first-child"):a.length?b?0<a.nextAll("li").size()?a.nextAll("li:eq(0)"):!1:a.hasClass("oj-expanded")?a.find("li:eq(0)"):0<a.nextAll("li").size()?a.nextAll("li:eq(0)"):a.parentsUntil(".oj-tree","li").next("li").eq(0):!1},ei:function(a){a=this.qa(a);if(-1==a||!a.length)return!1;a=a.parentsUntil(".oj-tree","li:eq(0)");return a.length?a:-1},cP:function(a){a=this.qa(a);return-1===a?this.$.children("ul:eq(0)").children("li"):a.length?a.children("ul:eq(0)").children("li"):
!1},RD:function(a){return(a=this.qa(a))&&-1!==a&&a.hasClass("oj-tree-leaf")},PC:function(a){a=this.Y.find(a);var b=!1;a&&a.length&&0<a.length&&f(a).is("li")&&(b=a);return b},bF:function(a){a.parents("div").eq(0);return this},MA:function(a,b){void 0!=a&&void 0!=b&&f.each(b,function(b,c){void 0==a[b]&&(a[b]=c)})},mQ:function(a){var b=this.Y.hasClass("oj-disabled");b||(b=!1);"undefined"!==typeof a&&b!=a&&(a?(this.Y.addClass("oj-disabled"),this.Y.prop("disabled","disabled")):(this.Y.removeClass("oj-disabled"),
this.Y.removeAttr("disabled")),this.CU(a))},CU:function(a){a?(this.f.N.locked=!0,this.f.ui.opacity=this.$.children("ul").css("opacity"),this.Y.addClass("oj-disabled").css("opacity","0.9")):(this.f.N.locked=!1,this.Y.removeClass("oj-disabled").css("opacity",this.f.ui.opacity))},LQ:function(){var a=this.options.selection.slice(0),b=[],c,d=this,e,g,h,k;c=f.grep(a,function(c,f){if(e=d.PC(c))b.push(e),a[f]=e[0];else return!1;return!0});this.options.selection=c;c=this.SP();f.each(c,function(a,c){k=b.length;
g=f(c).attr("id");h=!1;for(a=0;a<k;a++)if(g==b[a].attr("id")){h=!0;break}h||d.pj(c)});this.bU(b,null)},fl:function(a,b,c,d,e){var f={bk:this};f.wa=f.bk.qa(a);f.ua=-1===b?-1:this.qa(b);f.Lh="undefined"===typeof c||!1===c?"last":c;if(!e&&this.f.N.rd.wa&&this.f.N.rd.wa[0]===f.wa[0]&&this.f.N.rd.ua[0]===f.ua[0]&&this.f.N.rd.Lh===f.Lh)this.Ma(this.f.N.rd),d&&d.call(this,this.f.N.rd);else{f.bk=this;f.$l=this;if(-1!==f.ua&&f.ua){if(!/^(before|after)$/.test(f.Lh)&&!this.wh(f.ua))return this.rg(f.ua,function(){this.fl(a,
b,c,d,!0)});switch(f.Lh){case "before":f.Nf=f.ua.index();f.Uj=f.$l.ei(f.ua);break;case "after":f.Nf=f.ua.index()+1;f.Uj=f.$l.ei(f.ua);break;case "inside":case "first":f.Nf=0;f.Uj=f.ua;break;case "last":f.Nf=f.ua.find(" \x3e ul \x3e li").length;f.Uj=f.ua;break;default:f.Nf=f.Lh,f.Uj=f.ua}}else switch(f.Uj=-1,f.Lh){case "first":case "before":case "inside":f.Nf=0;break;case "after":case "last":f.Nf=f.$l.$.find(" \x3e ul \x3e li").length;break;default:f.Nf=f.Lh}f.Ih=-1==f.Uj?f.$l.$:f.Uj;f.Kh=f.bk.ei(f.wa);
f.AY=f.wa.index();-1===f.Kh&&(f.Kh=f.bk?f.bk.$:this.$);!/^(before|after)$/.test(f.Lh)&&f.Kh&&f.Ih&&f.Kh[0]===f.Ih[0]&&f.wa.index()<f.Nf&&f.Nf++;f.py=f.Ih.find(" \x3e ul \x3e li:nth-child("+(f.Nf+1)+")");this.f.N.rd=f;this.Ma(this.f.N.rd,"prepare_move");d&&d.call(this,this.f.N.rd,"prepare_move")}},check_move:function(){var a=this.f.N.rd,b=!0,c;c=-1===a.ua?this.$:a.ua;if(!a||!a.wa||a.py[0]===a.wa[0]||!a.ua)return!1;if(!a.AH){if(a.Kh&&a.Ih&&a.Kh[0]===a.Ih[0]&&a.Nf-1===a.wa.index())return!1;a.wa.each(function(){if(-1!==
c.parentsUntil(".oj-tree","li").addBack().index(this))return b=!1})}return b},BF:function(a,b){var c;a=this.qa(a);this.ej();c=this.getText(a);if(a&&a.length){var d=this.Ma({obj:a,func:"rename",title:b,prevTitle:c},"before");if("boolean"==typeof d&&!d)return}a&&a.length&&this.Rw.apply(this,Array.prototype.slice.call(arguments))&&this.Ma({obj:a,title:b,prevTitle:c},"rename")},bl:function(a,b,c,d,e,g){if(!(a.hasClass&&a.hasClass("oj-disabled")||this.f.N.locked)){if(!e)return this.fl(a,b,c,function(a){this.bl(a,
!1,!1,d,!0,g)});d&&(this.f.N.rd.AH=!0);if(!g&&!this.check_move())return!1;this.ej();b=!1;d?(b=a.wa.clone(!0),b.find("*[id]").addBack().each(function(){this.id&&(this.id="copy_"+this.id)})):b=a.wa;a.py.length?a.py.before(b):(a.Ih.children("ul").length||f("\x3cul /\x3e").appendTo(a.Ih),a.Ih.children("ul:eq(0)").append(b));try{a.bk.je(a.Kh),a.$l.je(a.Ih),a.Kh.find("\x3e ul \x3e li").length||a.Kh.removeClass("oj-expanded oj-collapsed").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove()}catch(h){}d&&
(this.f.N.rd.AH=!0,this.f.N.rd.SY=b);b=f.extend(!0,{},this.f.N.rd);b.obj=a.wa;this.Ma(b,"move");return this.f.N.rd}},$X:function(){return this.f.Pb.rd},Hv:function(a){var b=null;this.options.types&&(b=this.qa(a));return b&&b.length?b.attr(this.options.types.attr)||"default":!1},dU:function(a,b){var c=this.options.types,d,e=!1;a=this.qa(a);c&&a&&-1!=a&&a.length&&b&&(d=c.attr)&&c[b]&&(a.attr(d,b),a.addClass("oj-tree-type"),e=!0);return e},hB:function(a,b,c){b=this.qa(b);var d=!1,e=this.Hv(b),g=0,h=
this,k=this.qh().types,l=!1;if(-1===b)if(k[a])d=k[a];else return;else{if(!1===e)return;(l=this.f.types.wc.useData?b.data("oj-tree"):!1)&&l.types&&"undefined"!==typeof l.types[a]?d=l.types[a]:k.types[e]&&"undefined"!==typeof k.types[e][a]?d=k.types[e][a]:k.types["default"]&&"undefined"!==typeof k.types["default"][a]&&(d=k.types["default"][a])}f.isFunction(d)&&(d=d.call(this,b));var m=this.f.types.wc.maxDepth;"maxDepth"===a&&-1!==b&&!1!==c&&-2!==this.f.types.wc.maxDepth&&0!==d&&b.children("a:eq(0)").parentsUntil(".oj-tree",
"li").each(function(b){if(-1!==m&&0>=m-(b+1))return d=0,!1;g=0===b?d:h.hB(a,this,!1);if(-1!==g&&0>=g-(b+1))return d=0,!1;0<=g&&(g-(b+1)<d||0>d)&&(d=g-(b+1));0<=m&&(m-(b+1)<d||0>d)&&(d=m-(b+1))});return d},je:function(a){a=a&&-1!=a?f(a):this.Y;a=a.is("li")?a.find("li").addBack():a.find("li");a.removeClass("oj-tree-last").addClass("oj-tree-node").addClass("oj-draggable").filter("li:last-child").addClass("oj-tree-last").end().filter(":has(li)").not(".oj-expanded").removeClass("oj-tree-leaf").addClass("oj-collapsed").attr("aria-expanded",
"false");a.not(".oj-expanded, .oj-collapsed").addClass("oj-tree-leaf").children("ul").remove();var b=this.options.types?this.options.types.attr:!1;a.find("li");var c,d;f.each(a,function(){d=f(this);c=d.find("\x3e ins");1<c.length&&(c=f(c[0]));d.hasClass("oj-tree-leaf")?(c.removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default"),c.addClass("oj-tree-icon")):(c.addClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default"),c.removeClass("oj-tree-node-icon"));
b&&d.attr(b)&&d.addClass("oj-tree-type")})},xu:function(a,b,c,d,e){a=this.qa(a);if(-1!==a&&!a.length)return!1;var g=this.f.N.Bo;b="undefined"===typeof b?"last":b;var h=f("\x3cli /\x3e"),k;if(!e&&!this.wh(a))return this.rg(a,function(){this.xu(a,b,c,d,!0)}),!1;this.ej();"string"===typeof c&&(c={data:c});c||(c={});c.attr&&h.attr(c.attr);c.metadata&&h.data(c.metadata);c.state&&h.addClass("expanded"===c.state?"oj-expanded":"oj-collapsed");c.data||(c.data=void 0!==c.title?c.title:this.J("m_newnode"));
f.isArray(c.data)||(k=c.data,c.data=[],c.data.push(k));var l;f.each(c.data,function(a,b){k=f("\x3ca tabindex\x3d'-1' /\x3e");f.isFunction(b)&&(b=b.call(this,c));l=f("\x3cspan class\x3d'oj-tree-title'\x3e");"string"==typeof b?(l[g?"html":"text"](b),k.attr("href","#")):(b.attr||(b.attr={}),b.attr.href||(b.attr.href="#"),l[g?"html":"text"](b.title),b.language&&k.addClass(b.language));k.append(l);k.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-node-icon oj-component-icon'\x3e\x26#160;\x3c/ins\x3e");
!b.icon&&c.icon&&(b.icon=c.icon);b.icon&&(-1===b.icon.indexOf("/")?k.children("ins").addClass(b.icon):k.children("ins").css("background","url('"+b.icon+"') center center no-repeat"));h.append(k)});h.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default'\x3e\x26#160;\x3c/ins\x3e");-1===a&&(a=this.$,"before"===b&&(b="first"),"after"===b&&(b="last"));switch(b){case "before":a.before(h);k=this.ei(a);break;case "after":a.after(h);k=this.ei(a);break;
case "inside":case "first":a.children("ul").length||a.append("\x3cul /\x3e");a.children("ul").prepend(h);k=a;break;case "last":a.children("ul").length||a.append("\x3cul /\x3e");a.children("ul").append(h);k=a;break;default:a.children("ul").length||a.append("\x3cul /\x3e"),b||(b=0),k=a.children("ul").children("li").eq(b),k.length?k.before(h):a.children("ul").append(h),k=a}if(-1===k||k.get(0)===this.$.get(0))k=-1;this.je(k);this.Ma({obj:h,parent:k},"create_node");d&&d.call(this,h);return h},kd:function(a,
b,c){a=this.qa(a);if(!a.length)return!1;if(!a.hasClass("oj-disabled")&&!this.f.N.locked){if(!a.hasClass("oj-collapsed"))return b&&b.call(),!1;var d=this.Ma({obj:a,func:"expand"},"before");if("boolean"!=typeof d||d){var d=c?0:this.JA,e=this;this.wh(a)?(this.options.expandParents&&a.parentsUntil(".oj-tree",".oj-collapsed").each(function(){e.kd(this,!1,!0)}),(c||d)&&a.children("ul").css("display","none"),a.removeClass("oj-collapsed").addClass("oj-expanded").attr("aria-expanded","true").children("a").removeClass("oj-tree-loading"),
f(a.children()[0]).removeClass("oj-selected").addClass("oj-default"),!c&&d?this.rG(a,!1):(d=a.children("ul"),d.length&&(d.css("max-height",""),d.css("overflow","hidden"),d[0].style.display="block"),this.Ma({obj:a},"expand"),this.after_open(a)),b&&b.call()):(a.children("a").addClass("oj-tree-loading"),this.rg(a,function(){e.kd(a,b,c)},b))}}},Mu:function(a,b,c){var d=a?a:-1;(a=a?this.qa(a):-1)&&-1!==a?d=a:a=this.Y;c?a=a.find("li.oj-collapsed"):(c=a,a=a.is(".oj-collapsed")?a.find("li.oj-collapsed").addBack():
a.find("li.oj-collapsed"));var e=this;a.each(function(){var a=this;e.wh(this)?e.kd(this,!1,!b):e.expand(this,function(){e.Mu(a,b,c)},!b)});0===c.find("li.oj-collapsed").length&&this.Ma({obj:a,targ:d},"expandAll")},sg:function(b,c,d){if(0==this.f.N.be)return!1;b=this.qa(b);if(-1==b||!b||!b.length)return!1;if(!b.hasClass("oj-disabled")&&!this.f.N.locked){this.f.N.xs=!0;var e=this.isSelected(b);if(!e){var f=this.Ma({obj:b,func:"select"},"before");if("boolean"==typeof f&&!f)return}var f=this.options.selection.slice(0),
g=this.options,h=this.f.ui.wc.selectMultipleModifier,k=this.f.ui.wc.selectRangeModifier,l=this.f.ui.wc.disableSelectingChildren,h="on"==h||!1!==h&&d&&a.da.Ho(d),k=!1!==k&&d&&d[k+"Key"]&&this.f.ui.Hb&&this.f.ui.Hb[0]!==b[0]&&this.f.ui.Hb.parent()[0]===b.parent()[0],m=!0,n=this;if(c){if(l&&h&&(b.parentsUntil(".oj-tree","li").children("a.oj-selected").length||b.children("ul").find("a.oj-selected:eq(0)").length))return!1;m=!1;switch(!0){case k:this.f.ui.Hb.addClass("oj-tree-last-selected");b=b[b.index()<
this.f.ui.Hb.index()?"nextUntil":"prevUntil"](".oj-tree-last-selected").addBack();-1==this.f.N.be||b.length<this.f.N.be?(this.f.ui.Hb.removeClass("oj-tree-last-selected"),this.f.ui.selected.each(function(){this!==n.f.ui.Hb[0]&&n.pj(this)}),e=!1,m=!0):m=!1;break;case e&&!h:if(!d)break;this.lq();this.f.ui.Hy||(e=!1);m=!0;break;case !e&&!h:d?this.f.ui.selected&&1==this.f.ui.selected.length?this.pj(this.f.ui.selected):this.lq(this.f.ui.selected):1===this.f.N.be?this.pj(this.f.ui.selected):1<this.f.N.be&&
this.lq();m=!0;break;case e&&h:this.deselect(b);break;case !e&&h:if(-1==this.f.N.be||this.f.ui.selected.length+1<=this.f.N.be)m=!0}}m&&!e&&(k||(this.f.ui.Hb=b),b.children("a").addClass("oj-selected"),b.attr("aria-selected","true"),g.selectedParentExpand&&b.parents(".oj-collapsed").each(function(){n.kd(this,!1,!0)}),this.f.ui.selected=this.f.ui.selected.add(b),this.mC(b.eq(0)),this.gw(b,!0),this.f.N.$o||this.Kk("selection",f,this.options.selection,d))}},pj:function(a){a=this.qa(a);if(!a.length)return!1;
a.hasClass("oj-disabled")||this.f.N.locked||(this.isSelected(a)&&(a.children("a").removeClass("oj-selected"),a.removeAttr("aria-selected"),this.f.ui.selected=this.f.ui.selected.not(a),this.f.ui.Hb.get(0)===a.get(0)&&(this.f.ui.Hb=this.f.ui.selected.eq(0))),this.gw(a,!1))},lq:function(a,b){if(!this.f.N.locked)if(b)c=a?a:-1,d=a?f(a).find("a.oj-selected").parent():this.$.find("a.oj-selected").parent(),d.not(".oj-disabled"),0!==d.length&&(e=this,f.each(d,function(){e.pj(this)}));else{var c=a?a:-1,d=a?
f(a).find("a.oj-selected").parent():this.$.find("a.oj-selected").parent();d.not(".oj-disabled");if(0===d.length){if(-1===c)for(c=this.options.selection;c.length;)c.pop()}else{d.children("a.oj-selected").removeClass("oj-selected");d.removeAttr("aria-selected");var e=this;f.each(d,function(a,b){e.gw(f(b),!1)});this.f.ui.selected=f([]);this.f.ui.Hb=!1}}},bU:function(a,b){if(this.f.N.locked)return null;if(a&&0<a.length){var c=this;f.each(a,function(a,d){d&&c.sg(d,!0,b)})}},gw:function(a,b){var c,d,e,
g,h,k,l,m,n,q=this,r=!1;a&&(c=this.options.selection.slice(0),d=this.options.selection,l=d.length,f.each(a,function(a,p){n=!1;if(h=q.PC(p)){k=h.attr("id");for(e=0;e<l;e++)if(k==f(d[e]).attr("id")){n=!0;break}if(b)n||(c.push(p),r=!0);else if(n)for(m=c.length,g=0;g<m;g++)if(k==f(c[g]).attr("id")){c.splice(g,1);r=!0;break}}}),r&&(this.options.selection=c))},WB:function(a,b){a=f(a);if(!a.hasClass("oj-disabled")&&!this.f.N.locked){var c=a.parent(),d=c.hasClass("oj-collapsed");if(c.hasClass("oj-expanded")||
d)b?(a.addClass("oj-hover"),a.removeClass("oj-default"),a.removeClass("oj-selected")):(a.removeClass("oj-hover"),a.addClass("oj-default"))}},Yb:function(a){this.pF(a)},pF:function(a){var b=a?a:-1,c=this;this.HT();a||(a=-1);(a=this.qa(a))?b=a:a=-1;-1!==a?a.children("UL").remove():(this.Y.empty(),this.QE());this.rg(a,function(){c.Ma({obj:b},"refresh");c.Ar()})},Iw:function(a){this.saveSelected();this.pF(a)},after_open:function(a){this.Ma({obj:a},"after_open")},after_close:function(a){this.Ma({obj:a},
"after_close")},uT:function(){var a=this;this.f.N.ce.length&&f.each(this.f.N.ce,function(b,c){a.kd(c,!1,!0)});this.Ma({},"reopen")},SP:function(a){return a?f(a).find("a.oj-selected").parent():this.f.ui.selected},Rw:function(a,b){a=this.qa(a);if(!a.length)return!1;a=a.children("a:eq(0)");if(this.f.N.Bo){var c=a.children("INS").clone();a.html(b).prepend(c);this.Ma({obj:a,name:b},"set_text");return!0}a=a.find("span:eq(0)");this.Ma({obj:a,name:b},"set_text");return a[0].textContent=b},dE:function(){0!==
this.f.Aa.type&&-1!==this.f.Aa.type?this.rg(-1,function(){this.fE();this.Ar()}):(this.HM(),this.fE())},rg:function(a){this.Ma({obj:a},"load_node")},wh:function(){return!0},MR:function(a,b,c){var d=this;this.RR(a,function(){d.Ma({obj:d.qa(a)},"load_node");b.call(this)},c)},CR:function(a){a=this.qa(a);return-1===a||!a||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},YS:function(a){(a=this.qa(a))&&-1!==a&&a.removeData("oj-tree-children");return this.Iw(a)},OR:function(a,
b,c){var d=this;this.QR(a,function(){d.Ma({obj:d.qa(a)},"load_node");b.call(this)},c)},ER:function(a){var b=this.options.data;a=this.qa(a);return-1==a||!a||!b.ajax&&!this.f.Aa.uy&&!f.isFunction(b.data)||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},NR:function(a,b,c){var d=this;this.PR(a,function(){d.Ma({obj:d.qa(a)},"load_node");b.call(this)},c)},DR:function(a){var b=this.options.data,c=null,d=null;b&&(c=b.data||null,d=b.ajax||null);a=this.qa(a);return-1==a||!a||
!d&&!f.isFunction(c)||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").size()},reselect:function(){var a=this,b=this.f.ui.bp,b=f.map(f.makeArray(b),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});f.each(b,function(b,c){c&&"#"!==c&&a.select(c)});this.f.ui.selected=this.f.ui.selected.filter(function(){return this.parentNode});this.Ma(null,"reselect")},saveSelected:function(){var a=
this;this.f.ui.bp=[];this.f.ui.selected.each(function(){this.id&&a.f.ui.bp.push("#"+this.id.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:"))});this.Ma(this.f.ui.bp,"savedselected")},rollback:function(a){a&&(f.isArray(a)||(a=[a]),f.each(a,function(){}))},get_rollback:function(){this.Ma(null,"get_rollback");return{HY:this.md,Gh:this.$.children("ul").clone(!0),BY:this.data}},set_rollback:function(a,b){this.$&&this.Y&&
this.Y.empty().append(a);this.data=b;this.Ma(null,"set_rollback")},RR:function(a,b){var c=this.Oz(a);if(c.success&&c.No){var d=!a||-1===a,e=this.options.data;if(e.data&&!e.ajax||e.data&&e.ajax&&d)d&&((c=this.ki(c.No,a))?(this.Y.empty().append(c.children()),this.je()):this.f.Aa.Ud&&this.Y.empty()),b&&b.call(this);else if(!e.data&&e.ajax||e.data&&e.ajax&&!d)(c=this.ki(c.No,a))?(d?(d=this.Y,d.empty().append(c.children()),d.attr("role","tree").attr("tabindex","0").css("outline","none"),-1===this.f.N.be&&
d.attr("aria-multiselectable",!0)):(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")),this.je(a),b&&b.call(this)):d?this.f.Aa.Ud&&(this.Y.empty(),b&&b.call(this)):(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),e.correct_state&&(this.lj(a),b&&b.call(this)))}},Oz:function(a,b){var c=[],d=this.EG,e,g={},h={success:!1,No:null};-1==a&&(a=null,g.start=0);e=d.Le(a);0<e&&(g.count=e,d.Wd(a,g,{success:f.proxy(function(a){for(var e=
a.Z(),f,g=0;g<e;g++){b={};(f=a.getData(g))&&(b.attr=f);b.title=a.Kd[g].title;f.LY&&(b.metadata=a.Kd[g].metadata);var p=b.attr.id;f=d.Le(p);0<f&&(f=this.Oz(p,b),b.children=f.No);c.push(b)}h.success=!0;h.No=c},this),error:function(){h.success=!1}}));return h},ZS:function(a){a=this.qa(a);if(!this.f.N.locked){var b=!a||-1!==a||!a.length;if(b||!a.hasClass("oj-disabled")){var c=this.options.data.json;!b&&this.f.Aa.Yl&&(f.isFunction(c.data)||c.ajax)&&a.removeData("oj-tree-children");return this.Iw(a)}}},
QR:function(a,b,c){function d(){}function e(){}var g=this.qh().data,h=g&&g.data||null,k=g&&g.ajax||null;!g||h||k||(h=g);if((a=this.qa(a))&&-1!==a&&(this.f.Aa.uy||this.f.Aa.Yl)&&!a.is(".oj-expanded, .oj-tree-leaf")&&0===a.children("ul").children("li").length&&a.data("oj-tree-children")){if(g=this.ki(a.data("oj-tree-children"),a))a.append(g),this.f.Aa.Yl||a.removeData("oj-tree-children");this.je(a);b&&b.call(this)}else{if(a&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",
!0)}switch(!0){case !h&&!k:throw"ojTree - neither data nor ajax settings supplied.";case f.isFunction(h):h.call(this,a,f.proxy(function(d){(d=this.ki(d,a))?(-1!==a&&a?(a.append(d).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):this.Y.empty().append(d.children()),this.je(a),b&&b.call(this)):(-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.f.Aa.Ud&&this.lj(a)):this.f.Aa.Ud&&this.Y.empty(),
c&&c.call(this))},this));break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||((g=this.ki(h,a))?(this.Y.empty().append(g.children()),this.je()):this.f.Aa.Ud&&this.Y.empty());b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:e=function(b,d,e){var f=this.qh().data.ajax.error;f&&f.call(this,d,e,b);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.f.Aa.Ud&&this.lj(a)):"success"===d&&this.f.Aa.Ud&&this.Y.empty();
c&&c.call(this)},d=function(c,d,g){var h=this.qh().data.ajax.success;h&&(c=h.call(this,c,d,g)||c);if("string"==typeof c){d=c.replace(/^[\s\n]+$/,"");try{d=f.parseJSON(d)}catch(k){d=null}if(!d)return e.call(this,g,"Bad JSON","")}(c=this.ki(c,a))?(-1!==a&&a?(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):(g=this.Y,g.empty().append(c.children()),g.attr("role","tree").attr("tabindex","0").css("outline","none"),-1===this.f.N.be&&g.attr("aria-multiselectable",
!0)),this.je(a),b&&b.call(this)):-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.f.Aa.Ud&&(this.lj(a),b&&b.call(this))):this.f.Aa.Ud&&(this.Y.empty(),b&&b.call(this))},g.ajax.context=this,g.ajax.error=e,g.ajax.success=d,g.dataType||(g.ajax.dataType="json"),f.isFunction(g.ajax.url)&&(g.ajax.url=g.ajax.url.call(this,a)),f.isFunction(g.ajax.data)&&(g.ajax.data=g.ajax.data.call(this,a)),f.ajax(g.ajax)}}},ki:function(a,b,c){var d=!1,e,g,
h,k;if(!a)return d;this.f.Aa.Yl&&b&&-1!==b&&b.data("oj-tree-children",d);if("string"==typeof a)try{a=f.parseJSON(a)}catch(l){a=[]}if(f.isArray(a)){d=f("\x3cul\x3e");if(!a.length)return!1;g=0;for(h=a.length;g<h;g++)e=this.ki(a[g],b,!0),e.length&&(d=d.append(e));d=d.children()}else{"string"==typeof a&&(a={data:a});k="string"==typeof a.title?a.title:" ";d=f("\x3cli role\x3d'treeitem' /\x3e");a.attr&&(this.f.types.Cl&&!a.attr.type&&(a.attr.type="oj-tree-deftype",d.addClass("oj-tree-type")),d.attr(a.attr));
a.metadata&&d.data(a.metadata);(a.state||a.children&&0===a.children.length)&&d.addClass("expanded"===a.state?"oj-expanded":"oj-collapsed");a.data||(a.data={dummy:0});var m=this.f.N.Bo,n=!1,q;e=f("\x3ca tabindex\x3d'-1' /\x3e");f.each(a.data,function(b,c){f.isFunction(c)&&(c=c.call(this,a));"string"!=typeof c&&("attr"==b?e.attr(c):"style"==b&&e.css(c),"language"==b&&e.addClass(c));n||(q=f("\x3cspan class\x3d'oj-tree-title'\x3e"),q[m?"html":"text"](k),e.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-node-icon oj-component-icon'\x3e\x26#160;\x3c/ins\x3e",
q),n=!0);!c.icon&&a.icon&&(c.icon=a.icon);c.icon&&(-1===c.icon.indexOf("/")?e.children("ins").addClass(c.icon):e.children("ins").css("background","url('"+c.icon+"') center center no-repeat"))});d.append(e);d.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default'\x3e\x26#160;\x3c/ins\x3e");a.children&&(this.f.Aa.uy&&"expanded"!==a.state?d.addClass("oj-collapsed").attr("aria-expanded","false").data("oj-tree-children",a.children):(this.f.Aa.Yl&&
d.data("oj-tree-children",a.children),f.isArray(a.children)&&a.children.length&&(e=this.ki(a.children,b,!0),e.length&&(b=f("\x3cul role\x3d'group' /\x3e"),b.append(e),d.append(b)))))}c||(c=f("\x3cul /\x3e"),c.append(d),d=c);return d},lj:function(a){a=this.qa(a);if(!a||-1===a)return!1;a.removeClass("oj-collapsed oj-expanded").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove();a.find("ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").addClass("oj-tree-icon");
this.Ma({obj:a},"correct_state")},fE:function(){this.Ma(null,"loaded")},PR:function(a,b,c){function d(){}function e(){}var g=this.qh().data,h=g&&g.data||null,k=g&&g.ajax||null;if((a=this.qa(a))&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&!k&&g&&"string"===typeof g:this.cE(g,a,b,c);break;case f.isFunction(h):h.call(this,a,f.proxy(function(d){this.cE(d,a,b,c)},this));break;case !h&&!k:a&&-1!=a||(this.Y.empty().append(this.f.html.fs).find("li, a").filter(function(){return!this.firstChild||
!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon' \x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.Y.find("li").children("ins:first-child").addClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default"),this.br(this.Y),this.f.types.Cl&&this.Hm(this.Y),this.je(),this.Y.find("ul").attr("role","group"),this.Y.find("li").attr("role",
"treeitem"),this.Y.find("a").attr("tabindex",-1));b&&b.call(this);break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||(g=f(h),g.is("ul")||(g=f("\x3cul /\x3e").append(g)),this.Y.empty().append(g.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
this.Y.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.br(this.Y),this.f.types.Cl&&this.Hm(this.Y),this.je(),this.Y.find("ul").attr("role","group"),this.Y.find("li").attr("role","treeitem"),this.Y.find("a").attr("tabindex","-1"));b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:a=this.qa(a),e=function(b,d,e){var f=this.qh().data.ajax.error;
f&&f.call(this,b,d,e);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.f.Aa.Ud&&this.lj(a)):"success"===d&&this.f.Aa.Ud&&this.Y.empty();c&&c.call(this)},d=function(c,d,g){var h=this.qh().data.ajax.success;h&&(c=h.call(this,c,d,g)||c);if(""===c||c&&c.toString&&""===c.toString().replace(/^[\s\n]+$/,""))return e.call(this,g,d,"");c?(c=f(c),c.is("ul")||(c=f("\x3cul /\x3e").append(c)),-1!=a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
this.lT(a),a.append(c).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),a.removeData("oj-tree-is-loading"),a.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),
c=a):(this.Y.empty().append(c.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.Y.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),
c=this.Y),this.rQ(c),this.br(c),this.f.types.Cl&&c&&this.Hm(this.Y),this.je(a),b&&b.call(this)):(a&&-1!==a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.f.Aa.Ud&&(this.lj(a),b&&b.call(this))):this.f.Aa.Ud&&(this.Y.empty(),b&&b.call(this)),this.Y.find("ul").attr("role","group"),this.Y.find("li").attr("role","treeitem"))},g.ajax.context=this,g.ajax.error=e,g.ajax.success=d,g.ajax.dataType||(g.ajax.dataType="html"),f.isFunction(g.ajax.url)&&(g.ajax.url=
g.ajax.url.call(this,a)),f.isFunction(g.ajax.data)&&(g.ajax.data=g.ajax.data.call(this,a)),f.ajax(g.ajax)}},rQ:function(a){a=a.find(a.is("ul")?"li ul":"ul").filter(function(){return!this.firstChild||0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});f.each(a,function(){f(this).closest("li").addClass("oj-collapsed")})},lT:function(a){a=a.find("ul").filter(function(){return!this.firstChild||0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});
0<a.length&&a.remove()},cE:function(a,b,c){a&&""!==a&&a.toString&&""!==a.toString().replace(/^[\s\n]+$/,"")?(a=f(a),a.is("ul")||(a=f("\x3cul /\x3e").append(a)),-1!=b&&b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),b.append(a).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
b.removeData("oj-tree-is-loading"),a=b,this.Hm(this.Pi)):(this.Y.empty().append(a.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.Y.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),
a=this.Y,this.Hm(this.Y)),a&&this.br(a),this.je(b),c&&c.call(this)):b&&-1!==b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),b.removeData("oj-tree-is-loading"),this.f.Aa.Ud&&(this.lj(b),c&&c.call(this))):this.f.Aa.Ud&&(this.Y.empty(),c&&c.call(this))},br:function(a){f.each(a.find("li a"),function(a,b){var c=b.innerHTML,c=c.replace("ins\x3e","ins\x3e\x3cspan class\x3d'oj-tree-title'\x3e");b.innerHTML=c+"\x3c/span\x3e"})},Hm:function(a){var b,c;this.f.types.Cl&&(c=(b=this.options.types)?
b.attr:this.f.types.wc.attr,f.each(a.find("li"),function(a,b){b=f(b);b.attr(c)||b.attr(c,"oj-tree-deftype").addClass("oj-tree-type")}))},oq:function(){var a=this.f.dnd.gb;if(a.ua&&a.ua.length){this.f.dnd.off=a.ua.offset();this.fi&&(this.f.dnd.off.right=this.f.dnd.off.left+a.ua.width()-a.ua.find("\x3ea").width()-14);this.f.dnd.tJ=a.ua.find("a").width();if(this.f.dnd.os)return a=this.options.dnd.drag_check.call(this,{o:a.wa,r:a.ua}),this.f.dnd.after=a.after,this.f.dnd.before=a.before,this.f.dnd.inside=
a.inside,this.f.dnd.Vo=!0,this.Hu();this.fl(a.wa,a.ua,"before");this.f.dnd.before=this.check_move();this.fl(a.wa,a.ua,"after");this.f.dnd.after=this.check_move();this.wh(a.ua)?(this.fl(a.wa,a.ua,"inside"),this.f.dnd.inside=this.check_move()):this.f.dnd.inside=!1;this.f.dnd.Vo=!0;return this.Hu()}},Hu:function(){var a=this.f.dnd,b=!1,c;if(a.Vo){var b=["before","inside","after"],d=!1,e=a.Db,g=a.gb,b=a.Yc<this.f.N.pf/3?["before","inside","after"]:a.Yc<=2*this.f.N.pf/3?a.Yc<this.f.N.pf/2?["inside","before",
"after"]:["inside","after","before"]:["after","inside","before"];f.each(b,f.proxy(function(a,b){if(this.f.dnd[b])return e.helper.children("ins").removeClass("oj-tree-drop-invalid").addClass("oj-tree-drop-ok"),this.$.removeClass("oj-invalid-drop"),d=b,!1},this));!1===d?(e.helper.children("ins").removeClass("oj-tree-drop-ok").addClass("oj-tree-drop-invalid"),g.ua.addClass("oj-invalid-drop")):g.ua.removeClass("oj-invalid-drop").addClass("oj-valid-drop");c=this.fi?this.f.dnd.off.right-18:this.f.dnd.off.left+
5;b=!this.isLeaf(g.ua);a=this.fi?c+this.f.dnd.tJ+18:c;c=this.fi?a-this.f.dnd.KI:c+8;switch(d){case "before":b=this.f.dnd.off.top-3;g.mc.css({left:a+"px",top:b-7+"px"}).show();g.Ab&&g.Ab.css({left:c+"px",top:b+"px"}).show();break;case "after":b=this.f.dnd.off.top+this.f.N.pf-3;g.mc.css({left:a+"px",top:b-2+"px"}).show();g.Ab&&g.Ab.css({left:c+"px",top:b+6+"px"}).show();break;case "inside":g.mc.css({left:a+(this.fi?b?-4:0:4)+"px",top:this.f.dnd.off.top+this.f.N.pf/2-8+"px"}).show();g.Ab&&g.Ab.hide();
break;default:g.mc.hide(),g.Ab&&g.Ab.hide()}return g.hy=d}},Gu:function(a){var b=this.f.dnd,c=b.gb;b.Es&&(clearTimeout(b.Es),b.Es=!1);b.Vo=!1;c.ua=this.qa(a);a=this.options.dnd;var d=a.check_timeout;d?(b.Vf&&clearTimeout(b.Vf),b.Vf=setTimeout(f.proxy(this.oq,this),d)):this.oq();(a=a.open_timeout)?(b.wf&&clearTimeout(b.wf),c.ua&&c.ua.length&&c.ua.hasClass("oj-collapsed")&&(b.wf=setTimeout(f.proxy(this.XB,this),a))):c.ua&&c.ua.length&&c.ua.hasClass("oj-collapsed")&&this.XB()},sO:function(a){var b=this.f.dnd,
c=this.f.dnd.gb;b.after=!1;b.before=!1;b.inside=!1;this.f.dnd.Db.helper.children("ins").removeClass("oj-tree-drop-ok").addClass("oj-tree-drop-invalid");this.$.addClass("oj-invalid-drop");c.wa&&c.wa.removeClass("oj-valid-drop").removeClass("oj-invalid-drop");c.ua&&c.ua.removeClass("oj-valid-drop").removeClass("oj-invalid-drop");c.mc.hide();c.Ab&&c.Ab.hide();c.ua&&c.ua[0]===a.target.parentNode&&(b.Vf&&(clearTimeout(b.Vf),b.Vf=!1),b.wf&&(clearTimeout(b.wf),b.wf=!1))},XB:function(){var a=this.f.dnd.gb;
this.f.dnd.wf=!1;this.expand(a.ua,f.proxy(this.oq,this),!0)},rO:function(a){var b=this.f.dnd,c=this.f.dnd.gb;b.os?(b.after||b.before||b.inside)&&this.options.dnd.drag_finish.call(this,{o:c.wa,r:c.ua,p:c.hy}):(this.oq(),this.bl(c.wa,c.ua,c.hy,a[this.options.dnd.copy_modifier+"Key"]));c.wa&&c.wa.removeClass("oj-drag").removeClass("oj-invalid-drop").removeClass("oj-valid-drop");c.wa=!1;c.ua=!1;c.mc.hide();c.Ab&&c.Ab.hide()},nU:function(a,b){var c=this.f.dnd,d=this.f.dnd.gb;d.wa=this.qa(a);if(!d.wa.hasClass("oj-disabled")&&
!this.f.N.locked){this.f.ui&&this.isSelected(d.wa)&&(d.wa=this.qa(null,!0));var e=1<d.wa.length?this.J("m_multisel"):this.getText(d.wa),f=this.$;this.f.N.Bo||(e=e.replace(/</ig,"\x26lt;").replace(/>/ig,"\x26gt;"));d.wa.addClass("oj-drag");this.bC(b,{Qe:!0,Pi:d.wa},"\x3cspan\x3e"+e+"\x3c/span\x3e");this.f.Pa&&(d.mc&&d.mc.addClass("oj-tree-"+this.f.Pa.uf),c.Db.helper.addClass("oj-tree-dnd-helper oj-tree-"+this.f.Pa.uf));c.zl=f.offset();c.Cx=parseInt(f.width(),10);c.ch=parseInt(f.height(),10);c.ma=!0}},
bC:function(a,b,c){var d=this.f.dnd.Db;d.Pe&&this.Ku();try{a.currentTarget.unselectable="on",a.currentTarget.onselectstart=function(){return!1},a.currentTarget.style&&(a.currentTarget.style.MozUserSelect="none")}catch(e){}d.Yx=a.pageX;d.Zx=a.pageY;d.Hc=b;d.dy=!0;d.helper=f("\x3cdiv class\x3d'oj-tree-title oj-drag' style\x3d'top:-2000px' /\x3e").html(c);f(document).bind("mousemove",this.aC.bind(this));f(document).bind("mouseup",this.Ku.bind(this));return!1},aC:function(a){var b=this.f.dnd.Db,c=this.f.dnd.gb;
if(b.dy){if(!b.Pe)if(5<Math.abs(a.pageX-b.Yx)||5<Math.abs(a.pageY-b.Zx))b.helper.appendTo("body"),b.Pe=!0,f(document).triggerHandler("drag_start.ojtreeu",[{event:a,data:b.Hc}]);else return;if("mousemove"===a.type){var d=f(document),e=d.scrollTop(),d=d.scrollLeft();20>a.pageY-e?(c.Xc&&"down"===c.Dl&&(clearInterval(c.Xc),c.Xc=void 0),c.Xc||(c.Dl="up",c.Xc=setInterval(function(){f(document).scrollTop(f(document).scrollTop()-b.Ui)},150))):c.Xc&&"up"===c.Dl&&(clearInterval(c.Xc),c.Xc=void 0);20>f(window).height()-
(a.pageY-e)?(c.Xc&&"up"===c.Dl&&(clearInterval(c.Xc),c.Xc=void 0),c.Xc||(c.Dl="down",c.Xc=setInterval(function(){f(document).scrollTop(Number(f(document).scrollTop())+b.Ui)},150))):c.Xc&&"down"===c.Dl&&(clearInterval(c.Xc),c.Xc=void 0);20>a.pageX-d?(c.Wc&&"right"===c.El&&(clearInterval(c.Wc),c.Wc=void 0),c.Wc||(c.El="left",c.Wc=setInterval(function(){f(document).scrollLeft(f(document).scrollLeft()-b.Ui)},150))):c.Wc&&"left"===c.El&&(clearInterval(c.Wc),c.Wc=void 0);20>f(window).width()-(a.pageX-d)?
(c.Wc&&"left"===c.El&&(clearInterval(c.Wc),c.Wc=void 0),c.Wc||(c.El="right",c.Wc=setInterval(function(){f(document).scrollLeft(Number(f(document).scrollLeft())+b.Ui)},150))):c.Wc&&"right"===c.El&&(clearInterval(c.Wc),c.Wc=void 0)}e=b.nW;this.fi&&c.wa&&(c=c.wa.find("span.oj-tree-title:first"))&&0<c.length&&(e=-e-c[0].offsetWidth);b.helper.css({left:a.pageX+e+"px",top:a.pageY+b.oW+"px"});f(document).triggerHandler("drag.ojtreeu",[{event:a,data:b.Hc}])}},Ku:function(a){var b=this.f.dnd.gb,c=this.f.dnd.Db;
b.Wc&&clearInterval(b.Wc);b.Xc&&clearInterval(b.Xc);b.wa&&b.wa.removeClass("oj-drag").removeClass("oj-invalid-drop").removeClass("oj-valid-drop");f(document).unbind("mousemove",this.aC.bind(this));f(document).unbind("mouseup",this.Ku.bind(this));f(document).triggerHandler("drag_stop.ojtreeu",[{event:a?a:{},data:c.Hc}]);c.helper.remove();c.Yx=0;c.Zx=0;c.Hc={};c.dy=!1;c.Pe=!1;this.$.removeClass("oj-invalid-drop")},HT:function(){var a=this;this.f.N.ce=[];this.Y.find("li.oj-expanded").each(function(){this.id&&
a.f.N.ce.push("#"+this.id.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:"))})},Ar:function(a){var b=this,c=!0,d=[],e=[];if(!a){this.f.N.Ay=!1;this.f.N.RW=!0;if(a=this.vR())this.f.N.ce=[];a&&this.Y.find("li.oj-collapsed").each(function(){f(this).attr("id");b.f.N.ce.push("#"+f(this).attr("id"))});this.f.N.ce=f.map(f.makeArray(this.f.N.ce),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,
"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});this.f.N.Wi=f.map(f.makeArray(this.f.N.Wi),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});this.f.N.ce.length&&(this.f.N.Wi=this.f.N.Wi.concat(this.f.N.ce))}this.f.N.Wi.length&&(f.each(this.f.N.Wi,function(a,b){if("#"==b)return!0;f(b).length?d.push(b):e.push(b)}),d.length&&(this.f.N.Wi=e,f.each(d,function(a,d){b.wh(d)||
(b.rg(d,function(){b.Ar(!0)},function(){b.Ar(!0)}),c=!1)})));this.f.N.ce.length&&f.each(this.f.N.ce,function(a,c){b.kd(c,!1,!0)});c&&(this.f.N.Ay&&clearTimeout(this.f.N.Ay),this.f.N.Ay=setTimeout(function(){b.Ma({},"reload_nodes")},50),this.f.N.RW=!1,this.uT())},setTheme:function(a,b){if(!a)return!1;b||(b=this.f.Pa.$n+a+"/style.css");-1==f.inArray(b,this.f.Pa.uJ)&&(c({url:b}),this.f.Pa.uJ.push(b));this.f.Pa.uf!=a&&(this.$.removeClass("oj-tree-"+this.f.Pa.uf),this.f.Pa.uf=a);this.$.addClass("oj-tree-"+
a);this.f.Pa.qo?this.nG():this.sD();this.f.Pa.icons?this.Uw():this.Rv()},isIcons:function(){return this.f.Pa.icons},Uw:function(){this.f.Pa.icons=!0;this.$.children("ul").removeClass("oj-tree-no-icons")},Rv:function(){this.f.Pa.icons=!1;this.$.children("ul").addClass("oj-tree-no-icons")},toggleIcons:function(){},CO:function(){this.f.keys.LV=!0},fR:function(){this.$Q();this.ZQ();this.AD(!0);this.hR();this.CD();this.YQ();this.jR();this.eR();this.BD();this.iR();this.aR();this.xn()},Ma:function(a,b){if(b&&
"string"===f.type(b)){var c,d;c=Array.prototype.slice.call(arguments);var e=b;d=this.$;var g="before"===b,k=!1,l;if(!0!==this.f.N.locked||"unlock"===b||"isLocked"===b||"lock"===b){e=b;"rename_node"===e?e="rename":"set_focus"===e?e="focus":"unset_focus"===e?e="unfocus":"delete_node"===e?e="remove":"move_node"===e?e="move":"create_node"===e&&(e="create");(k=0<=f.inArray(e,h))||"create_node"!=e||(k=!0);k||(e="tree"+e);l=a?a.obj:void 0;if("loaded"===e||"optionChange"==e)l=-1;var m={};m.item=l;m.inst=
d;g?(d=a.func,m.func=d,m.args=c,"rename"===d&&(m.title=a.title,m.prevTitle=a.prevTitle)):k&&("move"==e?(m.position=a.Lh,m.reference=a.ua,m.data=a):"rename"==e?(m.title=a.title,m.prevTitle=a.prevTitle):"remove"==e?(m.parent=a.parent,m.prev=a.prev):"delete"==e?(m.prev=a.prev,m.parent=a.parent):"expandAll"===e||"collapseAll"===e||"deselectAll"===e?m.targ=a.targ:"optionChange"==e&&(m.option=a.option,m.previousValue=a.previousValue,m.value=a.value,m.optionMetadata=a.optionMetadata));if(k){if(c=this._trigger(e,
new f.Event("oj"+e),m),g)return"undefined"!=typeof c&&(c=c?!0:!1),c}else this.$.trigger(e,m)}}},Kk:function(a,b,c,d){var e,g,h,k,l,m=b.length!=c.length;if(!m)for(k=b.length,e=0;e<k;e++){h=f(b[e]).attr("id");l=!1;for(g=0;g<k;g++)if(h==f(c[g]).attr("id")){l=!0;break}if(!l){m=!0;break}}m&&this.Ma({option:a,previousValue:b,value:c,optionMetadata:{writeback:d?"shouldWrite":"shouldNotWrite"}},"optionChange")},ej:function(){return this.get_rollback()},MX:function(){},ql:function(){this.fi&&this.$.addClass("oj-tree-rtl").css("direction",
"rtl");this.$.html("\x3cul role\x3d'tree' tabindex\x3d'0' class\x3d'oj-tree-list' style\x3d'outline:none'"+(-1===this.f.N.be?" aria-multiselectable\x3d'true'":"")+"\x3e\x3cli class\x3d'oj-tree-last oj-tree-leaf'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e\x3ca class\x3d'oj-tree-loading' href\x3d'#'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e"+this.J("m_loading")+"\x3c/a\x3e\x3c/li\x3e\x3c/ul\x3e");this.Y=this.$.children("ul:eq(0)");this.$.data("oj-tree-instance-id",
this.md);this.f.N.pf=this.Y.find("li.oj-collapsed, li.oj-tree-leaf").eq(0).height()||18;this.$.delegate(".oj-tree-list ins.oj-tree-disclosure-icon","click.ojtree",f.proxy(function(a){a=f(a.target);this.toggleExpand(a)},this)).delegate(".oj-tree-list ins.oj-tree-disclosure-icon","mousedown",f.proxy(function(a){f(a.target).removeClass("oj-default").removeClass("oj-hover").addClass("oj-selected")},this)).delegate(".oj-tree-list ins.oj-tree-disclosure-icon","mouseup",f.proxy(function(a){f(a.target).removeClass("oj-selected").addClass("oj-default")},
this)).bind("mousedown.ojtree",f.proxy(function(){},this)).bind("dblclick.ojtree",function(){var a;if(document.selection&&document.selection.empty)document.selection.empty();else if(window.getSelection){a=window.getSelection();try{a.removeAllRanges(),a.collapse(document.getElementsByTagName("body")[0],0)}catch(b){}}});this.Y.focus(f.proxy(function(){this.f.ui.Ke=!0;if(this.f.N.xs)this.f.ui.Oo&&(this.f.ui.nb=this.f.ui.Oo,this.hover(this.f.ui.nb),this.f.ui.Oo=null),this.Y.find("a.oj-selected").removeClass("oj-tree-inactive");
else{this.f.N.xs=!0;var a=this.Y.find("li:first");this.hover(a)}},this)).blur(f.proxy(function(){this.f.ui.Ke=!1;this.f.ui.Oo=this.f.ui.nb;this.f.ui.Oo&&this.dehover(this.f.ui.nb);this.Y.find("a.oj-selected").addClass("oj-tree-inactive")},this));this.f.N.DW&&this.$.bind("treeload_node",f.proxy(function(a,b){var c=this.qa(b.item);-1===c&&(c=this.Y);c.length&&c.find("li.oj-expanded:not(:has(ul))").each(function(){this.rg(this,f.noop,f.noop)})},this));this.Ma({},"init");this.dE();this.f.menu.we&&this.Km();
b({pD:this.GR,UF:this.Y,FG:this});this.CO();this.Y.focus()},YQ:function(){this.f.N.locked=!1;this.$.addClass("oj-tree oj-tree-"+this.md);this.$.css("outline","none");this.$.css("MozUserSelect","none");this.$.css("WebkitTouchCallout","none");this.$.css("WebkitUserSelect","none");this.$.css("WebkitTapHighlightColor","rgba(0,0,0,0)")},jR:function(){this.f.ui.selected=f();this.f.ui.Hb=!1;this.f.ui.nb=null;var a=this.options.selection;a&&"array"===f.type(a)&&0<a.length&&(this.f.ui.bp=a,this.options.selection=
[]);this.$.delegate(".oj-tree-list a","click.ojtree",f.proxy(function(a){a.preventDefault();a.currentTarget.blur();f(a.currentTarget).hasClass("oj-tree-loading")||(this.sg(a.currentTarget,!0,a),this.Y.focus())},this)).delegate(".oj-tree-list a","mouseenter.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.hover(a.target)},this)).delegate(".oj-tree-list a","mouseleave.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.dehover(a.target)},
this)).delegate(".oj-tree-list .oj-tree-disclosure-icon","mouseenter.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.WB(a.target,!0)},this)).delegate(".oj-tree-list .oj-tree-disclosure-icon","mouseleave.ojtree",f.proxy(function(a){f(a.currentTarget).hasClass("oj-tree-loading")||this.WB(a.target,!1)},this)).bind("treereopen",f.proxy(function(){this.reselect()},this)).bind("treeget_rollback",f.proxy(function(){this.dehover();this.saveSelected()},this)).bind("treeset_rollback",
f.proxy(function(){this.reselect()},this)).bind("ojcollapse",f.proxy(function(a,b){var c=this.qa(b.item),d=c&&c.length?c.children("ul").find("a.oj-selected"):f();!1!==this.options.selectedParentCollapse&&d.length&&d.each(function(){this.deselect(this);"selectParent"===this.options.selectedParentCollapse&&this.select(c)})},this)).bind("ojremove",f.proxy(function(a,b){var c=this.options.selectPrevOnDelete,d=this.qa(b.item),d=d&&d.length?d.find("a.oj-selected"):[],e=this;d.each(function(){e.deselect(this)});
c&&d.length&&b.prev.each(function(){if(this.parentNode)return e.select(this),!1})},this)).bind("ojmove",f.proxy(function(a,b){var c=b.data;c.cy&&(c.oc.find("a.oj-selected").removeClass("oj-selected"),c.oc.removeAttr("aria-selected"))},this))},BD:function(){this.gR();this.dR();this.cR()},gR:function(){1===this.f.Aa.type&&(this.EG=this.options.data||null,this.rg=this.MR,this.wh=this.CR,this.Yb=this.YS)},dR:function(){3===this.f.Aa.type&&(this.f.Aa.Yl&&this.$.bind("treeafter_close",function(a,b){b.item.children("ul").remove()}),
this.rg=this.OR,this.wh=this.ER,this.Yb=this.ZS)},cR:function(){4===this.f.Aa.type&&(this.QE(),this.rg=this.NR,this.wh=this.DR,this.Yb=this.Iw)},QE:function(){this.f.html.Ts&&(this.f.html.Rl||(this.f.html.Rl=this.$.find(" \x3e ul"),this.f.html.Ds=f("\x3cdiv id\x3d'oj-tree-existing-markup-"+this.md+"' style\x3d'display:none'\x3e").append(this.f.html.Rl),this.$.after(this.f.html.Ds)),this.f.html.JI=this.f.html.Rl.find(" \x3e li"),this.f.html.fs=this.f.html.JI.clone(!0),this.f.html.fs.find("li").addBack().contents().filter(function(){return 3==
this.nodeType}).remove())},eR:function(){!1===this.f.Pa.$n&&f("script").each(function(){if(this.src.toString().match(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/))return this.f.Pa.$n=this.src.toString().replace(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/,"")+"themes/",!1});!1===this.f.Pa.$n&&(this.f.Pa.$n="themes/");this.$.bind("treeinit",f.proxy(function(){var a=this.options;this.f.Pa.qo=a.dots;this.f.Pa.icons=a.icons;this.setTheme(this.f.Pa.uf,this.f.Pa.url)},this)).bind("ojloaded",f.proxy(function(){this.f.Pa.qo?
this.nG():this.sD();this.f.Pa.icons?this.Uw():this.Rv()},this))},iR:function(){var a=this.options.types;a&&this.$.bind("treeinit",f.proxy(function(){var b=f.extend(!0,{},a.types),d=a.attr||this.f.types.wc.attr,e="",g=this;f.each(b,function(a,b){f.each(b,function(a){/^(maxDepth|maxChildren|icon|validChildren)$/.test(a)||g.f.types.kH.push(a)});var c=typeof b.icon;if("undefined"===c){c=typeof b.image;if("boolean"===c&&!b.image)b.image="ojt$none";else if(!b.image&&!b.position)return!0;b.icon={};b.image&&
(b.icon.image=b.image,delete b.image);void 0!==b.position&&(b.icon.position=b.position,delete b.position)}if(b.icon.image||b.icon.position)"default"==a?(g.f.types.Cl=!0,e+=".oj-tree-"+g.md+" .oj-tree-list li.oj-tree-type a \x3e .oj-tree-node-icon { ",e+=g.FA(b,e),e+="} ",e+=".oj-tree-"+g.md+" .oj-tree-list li["+d+'\x3d"oj-tree-deftype"].oj-tree-type \x3e a ins.oj-tree-node-icon { '):b.icon.image&&(e+=".oj-tree-"+g.md+" .oj-tree-list li["+d+'\x3d"'+a+'"].oj-tree-type \x3e a \x3e ins.oj-tree-node-icon { '),
e+=g.FA(b,e),e+="} "});""!==e&&c({Qs:e,title:"oj-tree-types"})},this)).bind("ojbefore",f.proxy(function(a,b){var c,d,e=b.func,g=b.item;if((c=(c=this.f.types.wc.useData?this.qa(g):!1)&&-1!==c&&c.length?c.data("oj-tree"):!1)&&c.types&&!1===c[e]||-1!==f.inArray(e,this.f.types.kH)&&b.item&&(b.item.tagName||b.item.jquery)&&(c=this.options.types.types,d=this.Hv(g),(c[d]&&"undefined"!==typeof c[d][e]||c["default"]&&"undefined"!==typeof c["default"][e])&&!1===this.hB(e,g)))return a.stopImmediatePropagation(),
!1},this))},FA:function(a){var b="",b="ojt$none"!==a.icon.image?b+(" background-image:url("+a.icon.image+"); "):b+" background-image:none; ";return b=a.icon.position?b+(" background-position:"+a.icon.position+"; "):b+" background-position:0 0; "},aR:function(){if(this.f.dnd.Zl){var a=this.f.dnd.gb;a.mc=f("\x3cdiv class\x3d'oj-tree-drop-marker'\x3e\x3cspan class\x3d'oj-tree-drop-ptr oj-component-icon'\x3e\x26#160;\x3c/span\x3e\x3c/div\x3e").hide().bind("mouseleave mouseenter",f.proxy(function(a){var b=
this.f.dnd.gb;b.mc.hide();b.Ab.hide();a.preventDefault();a.stopImmediatePropagation();return!1},this)).appendTo("body");a.Ab=f("\x3cdiv /\x3e").addClass("oj-tree-drop-marker-line").hide().bind("mouseup",function(a){var b=this.f.dnd.gb;if(b.ua&&b.ua.length)return b.ua.children("a").trigger(a),a.preventDefault(),a.stopImmediatePropagation(),!1}).bind("mouseleave",f.proxy(function(a){var b=this.f.dnd.gb,c=f(a.relatedTarget);if((c.is(".oj-tree")||0===c.closest(".oj-tree").length)&&b.ua&&b.ua.length)return b.ua.children("a").trigger(a),
b.mc.hide(),b.Ab.hide(),a.preventDefault(),a.stopImmediatePropagation(),!1},this)).appendTo("body");this.f.dnd.KI=a.Ab.width();f(document).bind("drag_start.ojtreeu",f.proxy(function(a,b){var c=this.f.dnd.gb;b.data.Qe&&(c.mc.show(),c.Ab&&c.Ab.show())},this));f(document).bind("drag_stop.ojtreeu",f.proxy(function(a,b){var c=this.f.dnd.gb;b.data.Qe&&(c.mc.hide(),c.Ab&&c.Ab.hide())},this));this.$.bind("mouseenter.ojtree",f.proxy(function(a){var b=this.f.dnd.Db,c=this.f.dnd.gb;if(b.Pe&&b.Hc.Qe&&(this.options.themes&&
(c.mc.addClass("oj-tree-"+this.f.Pa.uf),c.Ab&&c.Ab.addClass("oj-tree-"+this.f.Pa.uf),b.helper.addClass("oj-tree-dnd-helper oj-tree-"+this.f.Pa.uf)),a.currentTarget===a.target&&b.Hc.Pi&&f(b.Hc.Pi).length&&f(b.Hc.Pi).parents(".oj-tree:eq(0)")[0]!==a.target))if(a=this.bF(a.target),a.data.dnd.os){if(a=a.options.dnd.drag_check.call(this,{o:c.wa,r:a.$,is_root:!0}),!0===a||!0===a.inside||!0===a.before||!0===a.after)b.helper.children("ins").removeClass("oj-tree-drop-invalid").addClass("oj-tree-drop-ok"),
this.$.removeClass("oj-invalid-drop"),c.wa&&c.wa.removeClass("oj-invalid-drop").addClass("oj-valid-drop")}else a.fl(c.wa,a.$,"last"),a.check_move()&&(b.helper.children("ins").removeClass("oj-tree-drop-invalid").addClass("oj-tree-drop-ok"),this.$.removeClass("oj-invalid-drop"),c.wa&&c.wa.removeClass("oj-invalid-drop").addClass("oj-valid-drop"))},this)).bind("mouseup.ojtree",f.proxy(function(a){var b=this.f.dnd.gb,c=this.f.dnd.Db;c.Pe&&c.Hc.Qe&&a.currentTarget===a.target&&c.Hc.Pi&&f(c.Hc.Pi).length&&
f(c.Hc.Pi).parents(".oj-tree:eq(0)")[0]!==a.target&&(c=this.bF(a.currentTarget),c.data.dnd.foreign?(a=c.qh().dnd.drag_check.call(this,{o:b.wa,r:c.$,is_root:!0}),!0!==a&&!0!==a.inside&&!0!==a.before&&!0!==a.after||c.qh().dnd.drag_finish.call(this,{o:b.wa,r:c.$,is_root:!0})):c.bl(b.wa,c.$,"last",a[c.options.dnd.copy_modifier+"Key"]))},this)).bind("mouseleave.ojtree",f.proxy(function(a){var b=this.f.dnd.Db;if(a.relatedTarget&&f(a.relatedTarget).hasClass("oj-tree-drop-marker-line"))return!1;b.Pe&&b.Hc.Qe&&
(this.f.dnd.Me&&clearInterval(this.f.dnd.Me),this.f.dnd.Ne&&clearInterval(this.f.dnd.Ne),this.f.dnd.Vf&&clearTimeout(this.f.dnd.Vf),this.f.dnd.wf&&clearTimeout(this.f.dnd.wf),b.helper.children("ins").hasClass("oj-tree-drop-ok")&&(b.helper.children("ins").removeClass("oj-tree-drop-ok").addClass("oj-tree-drop-invalid"),this.$.addClass("oj-invalid-drop"),this.f.dnd.gb.wa&&this.f.dnd.gb.wa.removeClass("oj-valid-drop").removeClass("oj-invalid-drop")))},this)).bind("mousemove.ojtree",f.proxy(function(a){var b=
this.f.dnd.Db;if(b.Pe&&b.Hc.Qe){var c=this.$[0];a.pageX+24>this.f.dnd.zl.left+this.f.dnd.Cx?(this.f.dnd.Me&&clearInterval(this.f.dnd.Me),this.f.dnd.Me=setInterval(f.proxy(function(){this.scrollLeft+=b.Ui},c),100)):a.pageX-24<this.f.dnd.zl.left?(this.f.dnd.Me&&clearInterval(this.f.dnd.Me),this.f.dnd.Me=setInterval(f.proxy(function(){this.scrollLeft-=b.Ui},c),100)):this.f.dnd.Me&&clearInterval(this.f.dnd.Me);a.pageY+24>this.f.dnd.zl.top+this.f.dnd.ch?(this.f.dnd.Ne&&clearInterval(this.f.dnd.Ne),this.f.dnd.Ne=
setInterval(f.proxy(function(){this.scrollTop+=b.Ui},c),100)):a.pageY-24<this.f.dnd.zl.top?(this.f.dnd.Ne&&clearInterval(this.f.dnd.Ne),this.f.dnd.Ne=setInterval(f.proxy(function(){this.scrollTop-=b.Ui},c),100)):this.f.dnd.Ne&&clearInterval(this.f.dnd.Ne)}},this)).bind("scroll.ojtree",f.proxy(function(){var a=this.f.dnd.Db,b=this.f.dnd.gb;a.Pe&&a.Hc.Qe&&b.mc&&b.Ab&&(b.mc.hide(),b.Ab.hide())},this)).delegate(".oj-tree-list a","mousedown.ojtree",f.proxy(function(a){if(1===a.which)return this.nU(a.currentTarget,
a),!1},this)).delegate(".oj-tree-list a","mouseenter.ojtree",f.proxy(function(a){var b=this.f.dnd.Db;b.Pe&&b.Hc.Qe&&this.Gu(a.currentTarget)},this)).delegate(".oj-tree-list a","mousemove.ojtree",f.proxy(function(a){var b=this.f.dnd.Db,c=this.f.dnd.gb;b.Pe&&b.Hc.Qe&&(c.ua&&c.ua.length&&c.ua.children("a")[0]===a.currentTarget||this.Gu(a.currentTarget),"undefined"===typeof this.f.dnd.off.top&&(this.f.dnd.off=f(a.target).offset()),"undefined"===typeof this.f.dnd.off.top&&(this.f.dnd.off=f(a.target).offset()),
this.f.dnd.Yc=(a.pageY-(this.f.dnd.off.top||0))%this.f.N.pf,0>this.f.dnd.Yc&&(this.f.dnd.Yc+=this.f.N.pf),this.Hu())},this)).delegate(".oj-tree-list a","mouseleave.ojtree",f.proxy(function(a){var b=this.f.dnd.Db,c=this.f.dnd.gb;if(b.Pe&&b.Hc.Qe){if(a.relatedTarget&&f(a.relatedTarget).hasClass("oj-tree-drop-marker-line"))return!1;c.mc&&c.mc.hide();c.Ab&&c.Ab.hide();this.f.dnd.Es=setTimeout(function(b){return function(){b.sO(a)}}(this),0)}},this)).delegate(".oj-tree-list a","mouseup.ojtree",f.proxy(function(a){var b=
this.f.dnd.Db;b.Pe&&b.Hc.Qe&&this.rO(a)},this));f(document).bind("drag_stop.ojtreeu",f.proxy(function(){var a=this.f.dnd,b=this.f.dnd.gb;a.Vf&&clearTimeout(a.Vf);a.wf&&clearTimeout(a.wf);a.Me&&clearInterval(a.Me);a.Ne&&clearInterval(a.Ne);a.after=!1;a.before=!1;a.inside=!1;a.off=!1;a.Vo=!1;a.Yc=!1;a.Vf=!1;a.wf=!1;a.Me=!1;a.Ne=!1;a.ma=!1;a.os=!1;b.mc&&b.mc.css({top:"-2000px"});b.Ab&&b.Ab.css({top:"-2000px"})},this)).bind("drag_start.ojtreeu",f.proxy(function(a,b){if(b.data.Qe){var c=f(b.event.target);
c.closest(".jstree").hasClass("oj-tree-"+this.md)&&this.Gu(c)}},this));a=this.options.dnd;a.drag_target&&f(document).delegate(a.drag_target,"mousedown.ojtree-"+this.md,f.proxy(function(a){var b=this.f.dnd.Db,c=this.f.dnd,d=this.f.dnd.gb;d.wa=a.target;this.bC(a,{Qe:!0,Pi:a.target},"\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e"+f(a.target).text());this.f.Pa&&(d.mc&&d.mc.addClass("oj-tree-"+this.f.Pa.uf),d.Ab&&d.Ab.addClass("oj-tree-"+this.f.Pa.uf),b.helper.addClass("oj-tree-dnd-helper oj-tree-"+
this.f.Pa.uf));b.helper.children("ins").removeClass("oj-tree-drop-ok").addClass("oj-tree-drop-invalid");this.$.addClass("oj-invalid-drop");d.wa&&d.wa.removeClass("oj-valid-drop").addClass("oj-invalid-drop");b=this.$;c.zl=b.offset();c.Cx=parseInt(b.width(),10);c.ch=parseInt(b.height(),10);c.os=!0;a.preventDefault()},this));a.drop_target&&f(document).delegate(a.drop_target,"mouseenter.ojtreex-"+this.md,f.proxy(function(a){var b=this.f.dnd,c=this.f.dnd.gb;b.ma&&this.options.dnd.drop_check.call(this,
{o:c.wa,r:f(a.target),e:a})&&(b.Db.helper.children("ins").removeClass("oj-tree-drop-invalid").addClass("oj-tree-drop-ok"),this.$.removeClass("oj-invalid-drop"),c.wa&&c.wa.removeClass("oj-invalid-drop").addClass("oj-valid-drop"))},this)).delegate(a.drop_target,"mouseleave.ojtree-"+this.md,f.proxy(function(){this.f.dnd.ma&&(this.f.dnd.Db.helper.children("ins").removeClass("oj-tree-drop-ok").addClass("oj-tree-drop-invalid"),this.$.addClass("oj-invalid-drop"))},this)).delegate(a.drop_target,"mouseup.ojtreex-"+
this.md,f.proxy(function(a){var b=this.f.dnd.gb;this.f.dnd.ma&&this.f.dnd.Db.helper.children("ins").hasClass("oj-tree-drop-ok")&&this.options.dnd.drop_finish.call(this,{o:b.wa,r:f(a.target),e:a})},this))}},CD:function(){this.f.dnd.Zl=!1;var a=this.options.dnd,b=!0;"object"===typeof a&&(a=a.reorder,"string"===typeof a&&("enable"===a?(this.f.dnd.Zl=!0,b=!1):"disable"==a&&(b=!1)));this.f.dnd.Zl?(this.options.dnd={},this.MA(this.options.dnd,this.f.dnd.wc),this.options.dnd.reorder="enable"):b&&(this.options.dnd=
{reorder:"disable"})},iY:function(){},xn:function(a){var b,c;a||this.options.contextMenu||(b=this.$.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||this.options.contextMenu){b=a||this.options.contextMenu;c=f.type(b);if("function"==c){try{b=b()}catch(d){b=null}c=f.type(b)}if("string"===c){if(b=f(b))b.css("display","none"),c=this.f.menu,c.xe=b,c.we=!0;this.f.menu.we&&a&&this.Km()}}},th:function(a,b){this.f.menu.Ig="keydown"===a.originalEvent.originalEvent.type?this.f.ui.nb:f(a.originalEvent.target.parentNode);
this.f.menu.wX=this.f.menu.Ig.closest("div").attr("id");b.openOptions.position={my:"start top",at:"start bottom",of:this.f.menu.Ig[0]};if(this.f.menu.we&&this.f.menu.em){var c=this.f.menu.em.hasClass("oj-disabled"),d=!this.f.Pb.jf&&!this.f.Pb.Tj;c||(c=!1);c!=d&&(d?this.f.menu.em.addClass("oj-disabled"):this.f.menu.em.removeClass("oj-disabled"),this.f.menu.xe.ojMenu("refresh"))}},uh:function(a,b){if(!b.inst&&this.f.menu.wX==this.$h.substr(1)){var c=b?b.item.attr("id"):void 0;"ojtreecopy"===c?this.$N(this.f.menu.Ig):
"ojtreecut"===c?this.bO(this.f.menu.Ig):"ojtreepaste"===c?this.cO(this.f.menu.Ig):"ojtreeremove"===c?this.isSelected(this.f.menu.Ig)?this.CB():this.CB(this.f.menu.Ig):"ojtreerename"===c?this.dO(this.f.menu.Ig):"ojtreecreate"===c&&this.aO(this.f.menu.Ig)}},_OpenContextMenu:function(a,b){a.open(b,{launcher:this.Y,initialFocus:"menu"})},ZQ:function(){var a=this.options.selectionMode,a=void 0==a?"single":a;"none"===a?a=0:"single"===a?a=1:"multiple"===a&&(a=-1);this.f.N.be=a;this.f.Pa.icons=this.options.icons;
this.DD();this.f.N.Wi=this.options.initLoaded},lY:function(){},AD:function(b){var c=this.options.data,d;this.f.Aa.type=0;this.f.html.Ts=!1;this.f.html.fs=!1;if(c)if(d=f.type(c),"string"===d)this.tR(c)?this.f.Aa.type=4:this.f.Aa.type=3;else if("array"===d)this.f.Aa.type=3;else if("object"===d){try{c instanceof a.bc&&(this.f.Aa.type=1)}catch(e){this.f.Aa.type=-1}if(1!==this.f.Aa.type)try{c instanceof a.ya&&(this.f.Aa.type=2)}catch(g){this.f.Aa.type=-1}1!==this.f.Aa.type&&2!==this.f.Aa.type&&(c.data||
c.ajax)&&((d=c.dataType)?"json"===d?this.f.Aa.type=3:"html"===d&&(this.f.Aa.type=4):(c.dataType="json",this.f.Aa.type=3))}b&&0==this.f.Aa.type&&0<this.$.find("ul").length&&(this.f.Aa.type=4,this.f.html.Ts=!0)},kY:function(){},hY:function(){},gY:function(){},jY:function(){},hR:function(){var a=this.options.types;"object"===typeof a&&this.MA(a,{attr:this.f.types.wc.attr})},DD:function(){this.f.N.ce=this.UU(this.options,"initExpanded");null==this.f.N.ce&&(this.f.N.ce=[])},$Q:function(){var a=this.f;
a.N={Bo:!1,qW:[],be:1,DW:!1,pf:0,QY:!1,ce:!1,Wi:!1,rd:{},xs:!1,$o:!1};a.ui={selected:f(),Hb:!1,nb:null,Oo:null,bp:null,opacity:1,Hy:!1,Ke:!1,eH:null};a.ui.wc={selectMultipleModifier:"ctrl",selectRangeModifier:"shift",disableSelectingChildren:!1};a.Pb={};a.Pb.Tj=!1;a.Pb.jf=!1;a.Pb.wc={inputWidthLimit:200,move:{alwaysCopy:!1,openOnMove:!0,defaultPosition:"last",checkMove:function(){return!0}}};a.Pb.rd={};a.Aa={};a.Aa.uy=!1;a.Aa.Yl=!1;a.Aa.Ud=!0;a.Aa.type=0;a.zW={};a.zW.wc={data:!1,ajax:!1};a.html={};
a.html.wc={data:!1,ajax:!1};a.html.Ts=!1;a.html.Rl=!1;a.html.Ds=!1;a.html.JI=!1;a.html.fs=!1;a.Pa={};a.Pa.icons=!0;a.Pa.qo=!1;a.Pa.uf="default";a.Pa.url=!1;a.Pa.uJ=[];a.Pa.$n=!1;a.types={};a.types.kH=[];a.types.Cl=!1;a.types.wc={maxChildren:-1,maxDepth:-1,validChildren:"all",useData:!1,attr:"type",types:{"default":{maxChildren:-1,maxDepth:-1,validChildren:"all"}}};a.menu={};a.menu.we=!1;a.menu.xe=!1;a.menu.em=!1;a.menu.Ig=!1;a.keys={};a.keys.LV=!0;a.keys.bound=[];a.dnd={};a.dnd.Zl=!1;a.dnd.ma=!1;
a.dnd.after=!1;a.dnd.inside=!1;a.dnd.before=!1;a.dnd.off=!1;a.dnd.Vo=!1;a.dnd.Yc=0;a.dnd.Vf=!1;a.dnd.wf=!1;a.dnd.zl=!1;a.dnd.Cx=!1;a.dnd.ch=!1;a.dnd.Me=!1;a.dnd.Ne=!1;a.dnd.Es=!1;a.dnd.KI=100;a.dnd.tJ=100;a.dnd.wc={copy_modifier:"ctrl",check_timeout:100,open_timeout:500,drop_target:".oj-tree-drop",drop_check:function(){return!0},drop_finish:f.noop,drag_target:".oj-tree-draggable",drag_finish:f.noop,drag_check:function(){return{after:!1,before:!1,inside:!0}}};a.dnd.gb={};a.dnd.gb.wa=!1;a.dnd.gb.ua=
!1;a.dnd.gb.mc=!1;a.dnd.gb.Ab=!1;a.dnd.gb.Wc=void 0;a.dnd.gb.Xc=void 0;a.dnd.gb.Dl=!1;a.dnd.gb.El=!1;a.dnd.gb.hy=!1;a.dnd.Db={};a.dnd.Db.dy=!1;a.dnd.Db.Pe=!1;a.dnd.Db.helper=!1;a.dnd.Db.Ui=10;a.dnd.Db.Yx=0;a.dnd.Db.Zx=0;a.dnd.Db.dZ=5;a.dnd.Db.nW=15;a.dnd.Db.oW=5;a.dnd.Db.Hc={}},mC:function(a){var b=this.$[0];b.scrollHeight>b.offsetHeight&&(a=this.qa(a))&&-1!==a&&a.length&&a.is(":visible")&&(a=a.offset().top-this.$.offset().top,0>a&&(b.scrollTop=b.scrollTop+a-1),a+this.f.N.pf+(b.scrollWidth>b.offsetWidth?
k:0)>b.offsetHeight&&(b.scrollTop+=a-b.offsetHeight+this.f.N.pf+1+(b.scrollWidth>b.offsetWidth?k:0)))},YY:function(){},ND:function(){return this.f.ui.Ke},eZ:function(){},RX:function(){var a=null;f.each(r,function(b,c){if(c.f.ui.Ke)return a=c,!1});return a},kS:function(){return++q},WX:function(){return this.md},qh:function(){return f.extend(!0,{},this.options)},SX:function(){return this.$},GR:{up:function(){this.hover(this.rh(this.f.ui.nb||this.f.ui.Hb||-1));return!1},"ctrl+up":function(){this.hover(this.rh(this.f.ui.nb||
this.f.ui.Hb||-1));return!1},"shift+up":function(){this.select(this.rh(this.f.ui.nb||this.f.ui.Hb||-1),-1!==this.f.ui.be);return!1},down:function(){this.hover(this.tj(this.f.ui.nb||this.f.ui.Hb||-1));return!1},"ctrl+down":function(){this.hover(this.tj(this.f.ui.nb||this.f.ui.Hb||-1));return!1},"shift+down":function(){this.select(this.tj(this.f.ui.nb||this.f.ui.Hb||-1),-1!==this.f.ui.be);return!1},left:function(){var a=this.f.ui.nb||this.f.ui.Hb;a&&(a.hasClass("oj-expanded")?this.collapse(a):this.hover(this.rh(a)));
return!1},"ctrl+left":function(){var a=this.f.ui.nb||this.f.ui.Hb;a&&(a.hasClass("oj-expanded")?this.collapse(a):this.hover(this.rh(a)));return!1},"shift+left":function(){var a=this.f.ui.nb||this.f.ui.Hb;a&&(a.hasClass("oj-expanded")?this.collapse(a):this.hover(this.rh(a)));return!1},right:function(){var a=this.f.ui.nb||this.f.ui.Hb;a&&a.length&&(a.hasClass("oj-collapsed")?this.expand(a):this.hover(this.tj(a)));return!1},"ctrl+right":function(){var a=this.f.ui.nb||this.f.ui.Hb;a&&a.length&&(a.hasClass("oj-collapsed")?
this.expand(a):this.hover(this.tj(a)));return!1},"shift+right":function(){var a=this.f.ui.nb||this.f.ui.Hb;a&&a.length&&(a.hasClass("oj-collapsed")?this.expand(a):this.hover(this.tj(a)));return!1},space:function(){this.f.ui.nb&&(this.f.ui.Hy=!0,this.f.ui.nb.children("a:eq(0)").click(),this.f.ui.Hy=!1);return!1},home:function(){this.hover(this.Y.find("li:first"));return!1},end:function(){var a=this.Y.find("li.oj-tree-last:visible");a&&a.length&&this.hover(a[a.length-1]);return!1},"*":function(){this.Y.find("a");
this.Mu(-1,!1);return!1},"ctrl+space":function(){if(this.f.ui.nb){var a=f.Event("click");a.ctrlKey=!0;this.f.ui.nb.children("a:eq(0)").trigger(a)}return!1},"shift+space":function(){if(this.f.ui.nb){var a=f.Event("click");a.shiftKey=!0;this.f.ui.nb.children("a:eq(0)").trigger(a)}return!1},"shift+home":function(a){var b,c=this.f.ui.nb;if(c){var d=!0,e=this,g=this.Y.find("li:visible");this.f.N.$o=!0;b=this.options.selection.slice(0);c=c[0];f.each(g,function(a,b){b==c&&(d=!1);e.sg(b,!0);return d});this.f.N.$o=
!1;this.Kk("selection",b,this.options.selection,a)}return!1},"shift+pgdn":function(a){var b,c=this.f.ui.Hb||this.f.ui.nb;if(c){var d=!1,e=this,g=this.Y.find("li:visible");this.f.N.$o=!0;b=this.options.selection.slice(0);c=c[0];f.each(g,function(a,b){d||(d=b==c);d&&!e.isSelected(b)&&e.sg(b,!0);return!0});this.f.N.$o=!1;this.Kk("selection",b,this.options.selection,a)}return!1},f2:function(){this.rename(this.f.ui.nb||this.f.ui.Hb);return!1},del:function(){this.remove(this.f.ui.nb||this.qa(null));return!1}},
Km:function(){if(this.f.menu.we){var a=this.f.menu.xe,b=this;a.on("ojselect",f.proxy(this.uh,this));a.on("ojbeforeopen",f.proxy(this.th,this));var c=!1;a.find("[data-oj-command]").each(function(){var a;0===f(this).children("a").length&&(a=f(this).attr("data-oj-command").split("-"),f(this).replaceWith(b.dh(a[a.length-1])),f(this).hasClass("oj-menu-divider")&&f(this).removeClass("oj-menu-divider").addClass("oj-menu-item"),c=!0)});c&&a.ojMenu("refresh");this.f.menu.em=a.find("#ojtreepaste")}},aq:function(){var a=
this.f.menu;a.we&&(a.we=!1,a.xe.off("ojselect"),a.xe.off("ojbeforeopen"),a.xe=null)},dh:function(a){return f(this.ie(a))},ie:function(a){return"\x3cli id\x3d"+g[a]+"\x3e"+this.St(a)+"\x3c/li\x3e"},St:function(a){return'\x3ca href\x3d"#"\x3e'+this.J("m_"+a)+"\x3c/a\x3e"},bO:function(a){a=this.qa(a,!0);if(!a||!a.length)return!1;this.f.Pb.Tj=!1;this.f.Pb.jf=a;this.Ma({obj:a},"cut")},$N:function(a){a=this.qa(a,!0);if(!a||!a.length)return!1;this.f.Pb.jf=!1;this.f.Pb.Tj=a;this.Ma({obj:a},"copy")},cO:function(a){a=
this.qa(a);if(!a||!a.length)return!1;var b=this.f.Pb.jf?this.f.Pb.jf:this.f.Pb.Tj;if(!this.f.Pb.jf&&!this.f.Pb.Tj)return!1;this.f.Pb.jf&&(this.yu(this.f.Pb.jf,a),this.f.Pb.jf=!1);this.f.Pb.jf&&(this.yu(this.f.Pb.jf,a),this.f.Pb.jf=!1);this.f.Pb.Tj&&this.yu(this.f.Pb.Tj,a,!1,!0);this.Ma({obj:a,nodes:b},"paste")},yu:function(a,b,c,d,e,f){var g=this.f.Pb.wc.move;if(!e)return"undefined"===typeof c&&(c=g.defaultPosition),"inside"!==c||g.defaultPosition.match(/^(before|after)$/)||(c=g.defaultPosition),
this.bl(a,b,c,d,!1,f);if(!0===g.alwaysCopy||"multitree"===g.alwaysCopy&&a.$l.md!==a.bk.md)d=!0;this.bl(a,b,c,d,!0,f)},CB:function(a){a=this.qa(a,!0);this.ej();this.remove(a)},dO:function(a){a=this.qa(a);this.ej();this.DB(a,function(){})},DB:function(a,b){a=this.qa(a);var c=this.fi,d=this.f.Pb.wc.inputWidthLimit,e=a.children("ins").width(),g=a.find("\x3e a:visible \x3e ins").width()*a.find("\x3e a:visible \x3e ins").length,h=this.getText(a),k=this,l=f("\x3cdiv /\x3e",{css:{position:"absolute",top:"-200px",
left:c?"0px":"-1000px",visibility:"hidden"}}).appendTo("body"),m=a.css("position","relative").append(f("\x3cinput /\x3e",{value:h,"class":"oj-tree-rename-input",css:{padding:"0",border:"1px solid silver",position:"absolute",left:c?"auto":e+g+4+"px",right:c?e+g+4+"px":"auto",top:"0px",height:this.f.N.pf-2+"px",lineHeight:this.f.N.pf-2+"px",width:"150px"},blur:f.proxy(function(){var c=a.children(".oj-tree-rename-input"),d=c.val();""===d&&(d=h);l.remove();c.remove();this.Rw(a,h);this.BF(a,d);b.call(this,
a,d,h);a.css("position","")},this),keyup:function(a){a=a.keyCode||a.which;if(!k.Ju)return k.Ju=!0,!1;27==a?(k.Ju=!1,this.value=h,this.blur()):13==a?(k.Ju=!1,this.blur()):m.width(Math.min(l.text("pW"+this.value).width(),d))},keypress:function(a){if(13==(a.keyCode||a.which))return!1}})).children(".oj-tree-rename-input");this.Rw(a,"");l.css({fontFamily:m.css("fontFamily")||"",fontSize:m.css("fontSize")||"",fontWeight:m.css("fontWeight")||"",fontStyle:m.css("fontStyle")||"",fontStretch:m.css("fontStretch")||
"",fontVariant:m.css("fontVariant")||"",letterSpacing:m.css("letterSpacing")||"",wordSpacing:m.css("wordSpacing")||""});m.width(Math.min(l.text("pW"+m[0].value).width(),d))[0].select()},aO:function(a,b,c,d,e){var g=this;(a=this.qa(a))||(a=-1);this.ej();return this.xu(a,b,c,function(a){var b=this.ei(a),c=f(a).index();d&&d.call(this,a);b.length&&b.hasClass("oj-collapsed")&&this.expand(b,!1,!0);e?g.Ma({obj:a,name:this.getText(a),parent:b,position:c}):this.DB(a,function(a,d){g.Ma({obj:a,name:d,parent:b,
position:c})})})},QX:function(){return!1},tR:function(a){if(!a||3>a.length)return!1;a=a.trim();return"\x3c"===a.charAt(0)},HM:function(){var a=this.option.emptyText;"string"!==typeof a&&(a=this.J("m_emptyText"));a&&0<a.length&&(a="\x3cli class\x3d'oj-tree-empty'\x3e"+a+"\x3c/li\x3e",this.Y.empty().append(a))},MS:function(a){var b,c,d;d=null;var e;a&&(b=a.subId);if(!b)return null;d=b.split("[");if(3===d.length&&(d[0]=d[0].trim(),"oj-tree-node"===d[0]&&(d[1]=d[1].trim(),b=d[1].charAt(0),b=d[1].indexOf(b,
1),0<=b&&(a=d[1].substring(1,b).trim(),d[2]=d[2].trim(),b=d[2].charAt(0),b=d[2].indexOf(b,1),0<=b)))){d=d[2].substring(1,b).trim();try{c=this.qa(a)}catch(f){c=null}if(d&&c&&-1!==c)switch(d){case "icon":this.f.Pa.icons&&(e=c.find(" \x3e a \x3e ins:eq(0)"));break;case "link":e=c.find(" \x3e a:eq(0)");break;case "disclosure":this.RD(c)||(e=c.find(" \x3e ins:eq(0)"));break;case "title":e=c.find(" \x3e a \x3e span")}}return e?e.length?e[0]:null:null},sD:function(){this.f.Pa.qo=!1;this.$.children("ul").addClass("oj-tree-no-dots")},
nG:function(){this.f.Pa.qo=!0;this.$.children("ul").removeClass("oj-tree-no-dots")},vR:function(){var a=this.options.initExpanded;return a&&"all"==a||f.isArray(a)&&a.length&&"all"==a[0]},$O:function(){var a=0,b,c;window.getComputedStyle&&(c=this.f.ui.eH,c||(c=f("\x3cdiv id\x3d'ojtree-comp-animduration'\x3e\x3cspan class\x3d'oj-tree-transition'\x3edummy\x3c/span\x3e\x3c/div\x3e"),this.f.ui.eH=c,f(this.$h).append(c)),b=c[0].childNodes[0],b=window.getComputedStyle(b),b=b.transitionDuration,c.detach(),
"string"==typeof b&&1<b.length&&(c=b.charAt(b.length-1).toLowerCase(),"s"==c?(b=b.substring(0,b.length-1),b=parseFloat(b),isNaN(b)||(a=1E3*b)):2<b.length&&(c=b.substring(b.length-2).toLowerCase(),"ms"==c&&(b=parseFloat(b),isNaN(b)||(a=b)))));return a},UU:function(a,b){var c={};c[b]=a[b];return f.extend(!0,{},c)[b]}})})()});
//# sourceMappingURL=oj-modular.map