/*
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtTreemap"],function(a,f){a.La("oj.ojTreemap",f.oj.dvtBaseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{optionChange:null},Af:function(a,b,d){return DvtTreemap.newInstance(a,b,d)},$e:function(){var a=this._super();a.push("oj-treemap");return a},Zi:function(){var a=this._super();a["oj-treemap-isolate-icon"]={path:"_resources/isolate",property:"CSS_URL"};a["oj-treemap-isolate-icon oj-hover"]={path:"_resources/isolateOver",
property:"CSS_URL"};a["oj-treemap-isolate-icon oj-active"]={path:"_resources/isolateDown",property:"CSS_URL"};a["oj-treemap-restore-icon"]={path:"_resources/restore",property:"CSS_URL"};a["oj-treemap-restore-icon oj-hover"]={path:"_resources/restoreOver",property:"CSS_URL"};a["oj-treemap-restore-icon oj-active"]={path:"_resources/restoreDown",property:"CSS_URL"};a["oj-treemap-attribute-type-text"]={path:"styleDefaults/_attributeTypeTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-attribute-value-text"]=
{path:"styleDefaults/_attributeValueTextStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node"]={path:"nodeDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-treemap-node oj-hover"]={path:"nodeDefaults/hoverColor",property:"border-top-color"};a["oj-treemap-node oj-selected"]=[{path:"nodeDefaults/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/selectedInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header"]=[{path:"nodeDefaults/header/backgroundColor",
property:"background-color"},{path:"nodeDefaults/header/borderColor",property:"border-top-color"},{path:"nodeDefaults/header/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-treemap-node-header oj-hover"]=[{path:"nodeDefaults/header/hoverBackgroundColor",property:"background-color"},{path:"nodeDefaults/header/hoverOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/hoverInnerColor",property:"border-bottom-color"}];a["oj-treemap-node-header oj-selected"]=[{path:"nodeDefaults/header/selectedBackgroundColor",
property:"background-color"},{path:"nodeDefaults/header/selectedOuterColor",property:"border-top-color"},{path:"nodeDefaults/header/selectedInnerColor",property:"border-bottom-color"}];return a},$i:function(){return["optionChange"]},zm:function(){var a=this._super();a["DvtTreemapBundle.COLOR"]=this.qc("labelColor");a["DvtTreemapBundle.SIZE"]=this.qc("labelSize");return a},aj:function(a){var b=a&&a.getType?a.getType():null;b===DvtSelectionEvent.TYPE?this.ig("selection",a.getSelection()):b===DvtTreemapIsolateEvent.TYPE?
(b=this.options.YD,b||(this.options.YD=[],b=this.options.YD),(a=a.getId())?(b.push(a),this.ig("isolatedNode",a)):(b.pop(),this.ig("isolatedNode",0<b.length?b[b.length]:null))):this._super(a)},bj:function(a){return"isolatedNode"==a||"selection"==a},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)},getNode:function(c){var b=this.Sa.getAutomation();return new a.Ze(b.getNode(c))}});a.Ze=function(a){this.f=a};o_("TreemapNode",a.Ze,a);a.Ze.prototype.qd=
function(){return this.f?this.f.color:null};a.b.g("TreemapNode.prototype.getColor",{qd:a.Ze.prototype.qd});a.Ze.prototype.qe=function(){return this.f?this.f.label:null};a.b.g("TreemapNode.prototype.getLabel",{qe:a.Ze.prototype.qe});a.Ze.prototype.wo=function(){return this.f?this.f.size:null};a.b.g("TreemapNode.prototype.getSize",{wo:a.Ze.prototype.wo});a.Ze.prototype.ue=function(){return this.f?this.f.tooltip:null};a.b.g("TreemapNode.prototype.getTooltip",{ue:a.Ze.prototype.ue});a.Ze.prototype.isSelected=
function(){return this.f?this.f.selected:!1};a.b.g("TreemapNode.prototype.isSelected",{isSelected:a.Ze.prototype.isSelected})});
//# sourceMappingURL=oj-modular.map