/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtPanZoomCanvas'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.rp=function(a){this.Init(a)};(0,D.da)("DvtDiagramLayoutContext",D.rp);D.z.l(D.rp,D.z,"DvtDiagramLayoutContext");
D.rp.prototype.Init=function(a){this.nf=a?a.nf:D.o;this.ln=a?a.ln:D.o;this.Yr=a?a.Yr:0;this.UP=a?a.UP:0;this.zr=a?a.zr:D.p;this.k5=a?a.k5:D.o;this.Be=a?a.Be:D.o;this.Yu=a?a.Yu:D.o;this.ug=a?a.ug:D.o;this.hb={};this.tc={};this.az=[];this.jO=[];if(a){for(var b=0;b<this.Yr;b++){var c=new D.up(a.az[b]);this.az.push(c);this.hb[c.getId()]=c}for(var d in a.hb)this.hb[d]||(this.hb[d]=new D.up(a.hb[d]));for(b=0;b<this.UP;b++)c=new D.xp(a.jO[b]),this.jO.push(c),this.tc[c.getId()]=c;for(var e in a.tc)this.tc[e]||
(this.tc[e]=new D.xp(a.tc[e]))}};D.rp.prototype.ml=(0,D.ba)("nf");D.rp.prototype.$d=(0,D.v)("nf");D.rp.prototype.getLayout=D.rp.prototype.$d;D.rp.prototype.Ln=(0,D.ba)("ln");D.rp.prototype.Xi=(0,D.v)("ln");D.rp.prototype.getLayoutAttributes=D.rp.prototype.Xi;D.rp.prototype.VG=function(a){this.K(a.getId())||(this.Yr++,this.az.push(a));this.hb[a.getId()]=a};D.rp.prototype.K=function(a){return this.hb[a]};D.rp.prototype.getNodeById=D.rp.prototype.K;D.rp.prototype.GA=function(a){return this.az[a]};
D.rp.prototype.getNodeByIndex=D.rp.prototype.GA;D.rp.prototype.Oe=(0,D.v)("Yr");D.rp.prototype.getNodeCount=D.rp.prototype.Oe;D.oq=function(a,b){a.Mb(b.getId())||(a.UP++,a.jO.push(b));a.tc[b.getId()]=b};D.rp.prototype.Mb=function(a){return this.tc[a]};D.rp.prototype.getLinkById=D.rp.prototype.Mb;D.rp.prototype.xD=function(a){return this.jO[a]};D.rp.prototype.getLinkByIndex=D.rp.prototype.xD;D.rp.prototype.Ap=(0,D.v)("UP");D.rp.prototype.getLinkCount=D.rp.prototype.Ap;
D.rp.prototype.OMa=function(a,b){for(var c=b,d=new D.zq(0,0);c;)if(d.x+=c.s1.x+c.bg().x,d.y+=c.s1.y+c.bg().y,c=c.Yu){if((c=this.K(c))&&c.Qa()){var e=c.up();e&&(d.x+=e.left,d.y+=e.top)}}else c=D.o;return new D.zq(a.x+d.x,a.y+d.y)};D.rp.prototype.localToGlobal=D.rp.prototype.OMa;D.rp.prototype.pMa=(0,D.v)("zr");D.rp.prototype.isLocaleR2L=D.rp.prototype.pMa;D.rp.prototype.RIa=(0,D.v)("k5");D.rp.prototype.getComponentSize=D.rp.prototype.RIa;D.rp.prototype.VNa=(0,D.ba)("Be");
D.rp.prototype.setViewport=D.rp.prototype.VNa;D.rp.prototype.FD=(0,D.v)("Be");D.rp.prototype.getViewport=D.rp.prototype.FD;D.rp.prototype.U0=(0,D.ba)("Yu");D.rp.prototype.Naa=(0,D.v)("Yu");D.rp.prototype.getContainerId=D.rp.prototype.Naa;D.rp.prototype.fB=function(a,b,c,d){this.Yu&&(this.ug={},"number"===typeof a||"string"===typeof a||(d=a.left,b=a.right,c=a.bottom,a=a.top),this.ug.top=a,this.ug.right=b,this.ug.bottom=c,this.ug.left=d)};D.rp.prototype.setContainerPadding=D.rp.prototype.fB;
D.rp.prototype.up=(0,D.v)("ug");D.rp.prototype.getContainerPadding=D.rp.prototype.up;D.rp.prototype.TIa=(0,D.v)("FJ");D.rp.prototype.getCurrentViewport=D.rp.prototype.TIa;
D.xp=function(a){this.Init(a)};(0,D.da)("DvtDiagramLayoutContextLink",D.xp);D.z.l(D.xp,D.z,"DvtDiagramLayoutContextLink");D.xp.prototype.Init=function(a){this.Xa=a?a.Xa:D.o;this.sL=a?a.sL:D.o;this.RJ=a?a.RJ:D.o;this.Xh=a?a.Xh:D.o;this.LF=a?a.LF:D.o;this.KF=a?a.KF:D.o;this.ln=a?a.ln:D.o;this.n$=a?a.n$:0;this.j6=a?a.j6:0;this.TF=a?a.TF:1;this.Ne=a?a.Ne:D.p;this.mj=a?a.mj:D.o;this.ni=a?a.ni:D.o;this.Ws=a?a.Ws:D.p};D.xp.prototype.setId=(0,D.ba)("Xa");D.xp.prototype.getId=(0,D.v)("Xa");
D.xp.prototype.getId=D.xp.prototype.getId;D.xp.prototype.bN=(0,D.ba)("sL");D.xp.prototype.Zc=(0,D.v)("sL");D.xp.prototype.getStartId=D.xp.prototype.Zc;D.xp.prototype.TM=(0,D.ba)("RJ");D.xp.prototype.hc=(0,D.v)("RJ");D.xp.prototype.getEndId=D.xp.prototype.hc;D.xp.prototype.wc=function(a){this.Xh="string"==typeof a?D.K.CR(a):a};D.xp.prototype.setPoints=D.xp.prototype.wc;D.xp.prototype.vb=(0,D.v)("Xh");D.xp.prototype.getPoints=D.xp.prototype.vb;D.xp.prototype.Rd=(0,D.ba)("LF");
D.xp.prototype.setLabelPosition=D.xp.prototype.Rd;D.xp.prototype.qd=(0,D.v)("LF");D.xp.prototype.getLabelPosition=D.xp.prototype.qd;D.xp.prototype.Kn=(0,D.ba)("KF");D.xp.prototype.Md=(0,D.v)("KF");D.xp.prototype.getLabelBounds=D.xp.prototype.Md;D.xp.prototype.qS=(0,D.v)("n$");D.xp.prototype.getStartConnectorOffset=D.xp.prototype.qS;D.xp.prototype.XR=(0,D.v)("j6");D.xp.prototype.getEndConnectorOffset=D.xp.prototype.XR;D.xp.prototype.cE=(0,D.ba)("TF");D.xp.prototype.Sv=(0,D.v)("TF");
D.xp.prototype.getLinkWidth=D.xp.prototype.Sv;D.xp.prototype.Ln=(0,D.ba)("ln");D.xp.prototype.Xi=(0,D.v)("ln");D.xp.prototype.getLayoutAttributes=D.xp.prototype.Xi;D.xp.prototype.jb=(0,D.ba)("Ne");D.xp.prototype.tba=(0,D.v)("Ne");D.xp.prototype.getSelected=D.xp.prototype.tba;D.xp.prototype.pw=(0,D.ba)("mj");D.xp.prototype.setLabelRotationAngle=D.xp.prototype.pw;D.xp.prototype.Qv=(0,D.v)("mj");D.xp.prototype.getLabelRotationAngle=D.xp.prototype.Qv;D.xp.prototype.xs=(0,D.ba)("ni");
D.xp.prototype.setLabelRotationPoint=D.xp.prototype.xs;D.xp.prototype.Rv=(0,D.v)("ni");D.xp.prototype.getLabelRotationPoint=D.xp.prototype.Rv;D.xp.prototype.gE=(0,D.ba)("Ws");D.xp.prototype.py=(0,D.v)("Ws");
D.up=function(a){this.Init(a)};(0,D.da)("DvtDiagramLayoutContextNode",D.up);D.z.l(D.up,D.z,"DvtDiagramLayoutContextNode");
D.up.prototype.Init=function(a){this.Xa=a?a.Xa:D.o;this.Ic=a?a.Ic:D.o;this.RO=a?a.RO:D.o;this.YC=a?a.YC:D.o;this.LF=a?a.LF:D.o;this.KF=a?a.KF:D.o;this.ln=a?a.ln:D.o;this.E4=a?a.E4:D.p;this.Yu=a?a.Yu:D.o;this.Ne=a?a.Ne:D.p;this.mj=a?a.mj:D.o;this.ni=a?a.ni:D.o;this.ug=a?a.ug:D.o;this.Zr=a?a.Zr:D.o;this.Aq=a?a.Aq:D.o;this.gj=a?a.gj:D.p;this.jN=a?a.ga():D.o;this.Ly=D.k;this.s1=new D.zq(0,0)};D.up.prototype.setId=(0,D.ba)("Xa");D.up.prototype.getId=(0,D.v)("Xa");D.up.prototype.getId=D.up.prototype.getId;
D.up.prototype.Q0=function(a){this.Zr=this.Ic=a};D.up.prototype.zd=function(){!this.Ly&&this.jN&&this.jN.PM(this);return this.Ic};D.up.prototype.getBounds=D.up.prototype.zd;D.up.prototype.Hf=function(){!this.Ly&&this.jN&&this.jN.PM(this);return this.RO};D.up.prototype.getContentBounds=D.up.prototype.Hf;D.up.prototype.Ej=function(a){this.YC=a;(0,D.Aq)(this,this)};D.up.prototype.setPosition=D.up.prototype.Ej;D.up.prototype.bg=(0,D.v)("YC");D.up.prototype.getPosition=D.up.prototype.bg;
D.up.prototype.Rd=(0,D.ba)("LF");D.up.prototype.setLabelPosition=D.up.prototype.Rd;D.up.prototype.qd=(0,D.v)("LF");D.up.prototype.getLabelPosition=D.up.prototype.qd;D.up.prototype.Kn=(0,D.ba)("KF");D.up.prototype.Md=(0,D.v)("KF");D.up.prototype.getLabelBounds=D.up.prototype.Md;D.up.prototype.Ln=(0,D.ba)("ln");D.up.prototype.Xi=(0,D.v)("ln");D.up.prototype.getLayoutAttributes=D.up.prototype.Xi;D.up.prototype.Cy=(0,D.ba)("E4");D.up.prototype.IH=(0,D.v)("E4");D.up.prototype.isReadOnly=D.up.prototype.IH;
D.up.prototype.U0=(0,D.ba)("Yu");D.up.prototype.Naa=(0,D.v)("Yu");D.up.prototype.getContainerId=D.up.prototype.Naa;D.up.prototype.jb=(0,D.ba)("Ne");D.up.prototype.tba=(0,D.v)("Ne");D.up.prototype.getSelected=D.up.prototype.tba;D.up.prototype.pw=(0,D.ba)("mj");D.up.prototype.setLabelRotationAngle=D.up.prototype.pw;D.up.prototype.Qv=(0,D.v)("mj");D.up.prototype.getLabelRotationAngle=D.up.prototype.Qv;D.up.prototype.xs=(0,D.ba)("ni");D.up.prototype.setLabelRotationPoint=D.up.prototype.xs;
D.up.prototype.Rv=(0,D.v)("ni");D.up.prototype.getLabelRotationPoint=D.up.prototype.Rv;D.up.prototype.fB=function(a,b,c,d){this.Qa()&&(this.ug={},"number"===typeof a||"string"===typeof a||(d=a.left,b=a.right,c=a.bottom,a=a.top),this.ug.top=a,this.ug.right=b,this.ug.bottom=c,this.ug.left=d,this.Zr&&(this.Ic=new D.sp(this.Zr.x,this.Zr.y,this.Zr.w+d+b,this.Zr.h+a+c)),this.Aq&&(this.RO=new D.sp(this.Aq.x,this.Aq.y,this.Aq.w+d+b,this.Aq.h+a+c)))};D.up.prototype.setContainerPadding=D.up.prototype.fB;
D.up.prototype.up=(0,D.v)("ug");D.up.prototype.getContainerPadding=D.up.prototype.up;D.up.prototype.yf=(0,D.ba)("gj");D.up.prototype.Qa=(0,D.v)("gj");D.up.prototype.isDisclosed=D.up.prototype.Qa;D.up.prototype.S0=(0,D.ba)("JAa");D.up.prototype.zc=(0,D.v)("JAa");D.up.prototype.getChildNodes=D.up.prototype.zc;D.up.prototype.$M=(0,D.ba)("Kx");D.up.prototype.Rl=(0,D.v)("Kx");D.up.prototype.getParentNode=D.up.prototype.Rl;D.Aq=function(a,b){var c=b.Rl();c&&c.Ly&&(c.Ly=D.p,(0,D.Aq)(a,c))};
D.zq=function(a,b){this.Init(a,b)};(0,D.da)("DvtDiagramPoint",D.zq);D.z.l(D.zq,D.z,"DvtDiagramPoint");D.zq.prototype.Init=function(a,b){this.x=a===D.o||(0,window.isNaN)(a)?0:a;this.y=b===D.o||(0,window.isNaN)(b)?0:b};
D.sp=function(a,b,c,d){this.Init(a,b,c,d)};(0,D.da)("DvtDiagramRectangle",D.sp);D.z.l(D.sp,D.z,"DvtDiagramRectangle");D.sp.prototype.Init=function(a,b,c,d){this.x=a===D.o||(0,window.isNaN)(a)?0:a;this.y=b===D.o||(0,window.isNaN)(b)?0:b;this.w=c===D.o||(0,window.isNaN)(c)?0:c;this.h=d===D.o||(0,window.isNaN)(d)?0:d};
D.op=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtBaseDiagram",D.op);D.z.l(D.op,D.pp,"DvtBaseDiagram");D.x=D.op.prototype;D.x.Init=function(a,b,c){D.op.o.Init.call(this,a,b,c);this.j().Kc.sa().setAttributeNS(D.o,"text-rendering","geometricPrecision");this.O7;this.wK=this.io=D.o;this.aX;this.A4=D.k;this.Dl=new D.D(a);this.Vh=new D.D(a);this.Ot=new D.D(a);this.Zy=0.5;this.Kfa()};D.x.HN=function(){var a=this.da;a.qw(this.zD());a.xu(this.fy());a.ow(this.xa());a.ba.k(this.Dl);a.ba.k(this.Vh);a.ba.k(this.Ot)};
D.x.ow=function(a){this.Zy=a;this.da&&this.da.ow(a)};D.x.xa=(0,D.v)("Zy");D.x.xu=function(a){this.ov=a;this.da&&this.da.xu(a)};D.x.fy=(0,D.v)("ov");D.x.qw=function(a){this.zt=a;this.da&&this.da.qw(a)};D.x.zD=(0,D.v)("zt");D.x.Kfa=function(){this.xu(2);this.qw(0)};D.x.Ij=function(){this.eK||(D.op.o.Ij.call(this),this.HN(),this.dq());this.eK=D.p};D.x.dq=(0,D.t)();D.x.K=(0,D.ca)(D.o);D.x.Mb=(0,D.ca)(D.o);D.x.xI=function(){return[]};D.x.rB=function(){return[]};D.x.Oe=function(){return this.rB().length};
D.op.prototype.getNodeCount=D.op.prototype.Oe;D.op.prototype.Ap=function(){return this.xI().length};D.op.prototype.getLinkCount=D.op.prototype.Ap;D.qp=function(a,b){if(b&&a.uD())a.oC?(a.oC.ca(a.Ga/2),a.oC.va(a.Ta/2),D.$e.Qb(a.oC,a.getWidth()-2*D.$e.Q1,window.Infinity,a)):a.oC=a.dea(a.uD());else if(a.oC){var c=a.oC.getParent();c&&c.removeChild(a.oC);a.oC=D.o}};D.x=D.op.prototype;D.x.dea=function(a){var b=this.q();return D.$e.Om(this,a,new D.A(0,0,this.getWidth(),this.getHeight()),this.ka(),b._statusMessageStyle)};
D.x.uD=(0,D.v)("jn");D.x.bS=(0,D.v)("aX");D.x.mh=(0,D.v)("Hb");D.x.rw=function(a){this.Hb="single"==a?new D.$k("s"):"multiple"==a?new D.$k("m"):D.o;this.ka().yu(this.Hb)};D.x.Sl=function(){return this.Hb?this.Hb.Pa():D.o};D.x.br=function(){return this.Hb?D.k:D.p};D.x.ka=(0,D.v)("eb");D.tp=function(a){var b=new D.rp,c=(0,D.E)(a.j());b.zr=c;a=new D.sp(0,0,a.getWidth(),a.getHeight());b.k5=a;return b};
D.op.prototype.Es=function(a,b,c){var d=new D.up;d.setId(a.getId?a.getId():a.getData().getId());d.Q0(D.vp.YG(a.ae()));var e=D.vp.YG(a.Hf());d.RO=e;d.Aq=e;d.Ln(a.Xi(b));d.Kn(D.vp.YG(a.Md()));d.Rd(D.vp.dqa(a.qd()));d.jb(D.k==a.Da());if(a.Qa()&&(d.yf(D.k),b=(0,D.wp)(a.up()),d.Qa()&&(d.ug=b)))d.Zr&&(d.Zr=new D.sp(d.Zr.x,d.Zr.y,d.Zr.w-(b.left+b.right),d.Zr.h-(b.top+b.bottom))),d.Aq&&(d.Aq=new D.sp(d.Aq.x,d.Aq.y,d.Aq.w-(b.left+b.right),d.Aq.h-(b.top+b.bottom)));d.U0(a.getData().$R?a.getData().gd:D.o);d.jN=
this;d.Ly=!c;return d};D.op.prototype.oB=function(a,b,c,d){var e=new D.xp;e.setId(a.getId?a.getId():a.getData().getId());e.bN(b?b:a.getData().Zc());e.TM(c?c:a.getData().hc());e.Ln(a.Xi(d));e.Kn(D.vp.YG(a.Md()));e.Rd(D.vp.dqa(a.qd()));b=a.qS();e.n$=b;b=a.XR();e.j6=b;e.cE(a.Sv());e.jb(D.k==a.Da());e.gE(D.k==a.py());return e};
D.op.prototype.mB=function(a,b,c){var d=a.up();if(d){var e=a.Yu;e&&(e=this.K(e))&&e.fB((0,D.yp)(d),b)}for(var e=d=window.Number.MAX_VALUE,f=0;f<a.Oe();f++){var g=a.GA(f),h=this.K(g.getId()),j=g.bg();j&&(d=window.Math.min(d,j.x),e=window.Math.min(e,j.y));h=g.Md();j=g.qd();h&&j&&(d=window.Math.min(d,j.x+h.x),e=window.Math.min(e,j.y+h.y))}for(f=0;f<a.Ap();f++){var g=a.xD(f),l=this.Mb(g.getId());if(j=g.vb()){j=D.zp.Z1(j);for(h=0;h<j.length;h++)var m=j[h],d=window.Math.min(d,m.x),e=window.Math.min(e,m.y)}h=
g.Md();j=g.qd();h&&j&&(d=window.Math.min(d,j.x+h.x),e=window.Math.min(e,j.y+h.y))}e=this.$da(-d,-e);d=e.x;e=e.y;for(f=0;f<a.Oe();f++){g=a.GA(f);h=this.K(g.getId());(j=g.bg())&&h.Iw(j.x+d,j.y+e,b);var n=g.Md(),m=g.qd();if(n&&m){var j=new D.F(m.x-j.x,m.y-j.y),m=g.mj,q=D.vp.cqa(g.ni);b?((0,D.T)(b,"typeRectangle",h,h.Md,h.Kn,n),h.qd()?(0,D.T)(b,"typePoint",h,h.qd,h.Rd,j):h.Rd(j),m!=D.o&&(0,D.T)(b,"typeNumber",h,h.Qv,h.pw,m),q&&(h.ni?(0,D.T)(b,"typePoint",h,h.Rv,h.xs,q):h.xs(q))):(h.Kn(n),h.Rd(j),m!=D.o&&
h.pw(m),q&&h.xs(q))}h.Qa()&&(g=g.up())&&h.fB((0,D.yp)(g),b)}if(!this.hz)for(f=0;f<a.Ap();f++){g=a.xD(f);l=this.Mb(g.getId());if(j=g.vb()){0<j.length&&!(0,window.isNaN)(j[0])&&(j=D.zp.OT(j));for(var r=[],h=0;h<j.length;)(0,window.isNaN)(j[h])?(r.push(j[h]),h++):(r.push(j[h]+d),r.push(j[h+1]+e),h+=2);b&&l.vb()?0<r.length&&(0,window.isNaN)(r[0])?(h=D.Ap.Iqa(l.vb(),r),l.wc(h.Ada),(0,D.T)(b,"typePath",l,l.vb,l.wc,h.zda),(0,D.hl)(b,function(){l.wc(r)})):(0,D.T)(b,"typePolyline",l,l.vb,l.wc,r):l.wc(r)}h=
D.vp.uHa(g.Md());j=g.qd();m=g.mj;q=D.vp.cqa(g.ni);h&&j&&(g=new D.F(j.x+d,j.y+e),b?((0,D.T)(b,"typeRectangle",l,l.Md,l.Kn,h),l.qd()?(0,D.T)(b,"typePoint",l,l.qd,l.Rd,g):l.Rd(g),m!=D.o&&(0,D.T)(b,"typeNumber",l,l.Qv,l.pw,m),q&&(l.ni?(0,D.T)(b,"typePoint",l,l.Rv,l.xs,q):l.xs(q))):(l.Kn(h),l.Rd(g),m!=D.o&&l.pw(m),q&&l.xs(q)))}if(b=a.FD())this.io=new D.A(b.x+d,b.y+e,b.w,b.h),this.wK=a.Yu;c&&(this.O7=new D.F(d,e))};
D.Cp=function(a,b){var c;if(a.io&&(c=new D.A(a.io.x,a.io.y,a.io.e,a.io.g),a.wK))for(var d=a.K(a.wK);d;){var e=d.N(),f=d.M();if(b){var g=(0,D.Bp)(b,d,d.N),h=(0,D.Bp)(b,d,d.M);if(g||0==g)e=g;if(h||0==h)f=h}c.x+=e;c.y+=f;d=(d=d.getData().$R?d.getData().gd:D.o)?a.K(d):D.o}return c};D.op.prototype.$da=function(a,b){return new D.F(a,b)};D.op.prototype.vw=function(a,b){if(0==this.zt){var c=this.da,d=b?b:(0,D.Dp)(this,a,D.i,D.i),e=(0,D.Ep)(this,d);c.qw(0.5*window.Math.min(e,c.fy()));return d}return D.o};
D.Ep=function(a,b){if(!b)return 0;var c=a.da;return window.Math.min((a.Ga-2*c.Jq)/b.e,(a.Ta-2*c.Jq)/b.g)};
D.Dp=function(a,b,c,d){var e=D.o,f,g,h,j,l=a.da.ba;c||(c=a.rB());for(var m=0;m<c.length;m++)if(f=c[m],(j=a.K(f))&&j.bb&&!j.ce){var n=j,q=b;f=n.ae();g=new D.A(f.x,f.y,f.e,f.g);h=D.o;q&&(h=(0,D.Bp)(q,n,n.qd));h||(h=n.qd());var r=D.o,s=D.o;q&&(r=(0,D.Bp)(q,n,n.Qv),s=(0,D.Bp)(q,n,n.Rv));r==D.o&&(r=n.mj);s||(s=n.ni);n=n.Md();h&&n&&(r!=D.o&&(n=(0,D.Fp)(n,r,s)),g.x=window.Math.min(f.x,n.x+h.x),g.y=window.Math.min(f.y,n.y+h.y),g.e=window.Math.max(f.x+f.e,n.x+h.x+n.e)-g.x,g.g=window.Math.max(f.y+f.g,n.y+h.y+
n.g)-g.y);f=g;h=g=D.o;b&&(g=(0,D.Bp)(b,j,j.N),h=(0,D.Bp)(b,j,j.M));g==D.o&&(g=j.N());h==D.o&&(h=j.M());f.x+=g;f.y+=h;if(g=j.getData().$R?j.getData().gd:D.o)g=j.getParent(),j=(0,D.Gp)(new D.F(f.x,f.y),g,b),j=(0,D.Hp)(j,l,b),g=(0,D.Gp)(new D.F(f.x+f.e,f.y+f.g),g,b),g=(0,D.Hp)(g,l,b),f.x=j.x,f.y=j.y,f.e=g.x-j.x,f.g=g.y-j.y;e?(j=e.x,g=e.y,e.x=window.Math.min(e.x,f.x),e.y=window.Math.min(e.y,f.y),e.e=window.Math.max(j+e.e,f.x+f.e)-e.x,e.g=window.Math.max(g+e.g,f.y+f.g)-e.y):e=f}d||(d=a.xI());for(m=0;m<
d.length;m++)if(c=d[m],(c=a.Mb(c))&&c.bb){j=c;g=b;f=new D.A(window.Number.MAX_VALUE,window.Number.MAX_VALUE,-window.Number.MAX_VALUE,-window.Number.MAX_VALUE);h=D.o;g&&(h=(0,D.Bp)(g,j,j.vb));h||(h=j.vb());if(h){h=D.zp.Z1(h);for(var u=D.i,u=n=s=r=D.i,q=0;q<h.length;q++)u=h[q],r=window.Math.max(f.x+f.e,u.x),s=window.Math.max(f.y+f.g,u.y),n=window.Math.min(f.x,u.x),u=window.Math.min(f.y,u.y),f.x=n,f.y=u,f.e=r-n,f.g=s-u}h=new D.A(f.x,f.y,f.e,f.g);r=D.o;g&&(r=(0,D.Bp)(g,j,j.qd));r==D.o&&(r=j.qd());n=s=
D.o;g&&(s=(0,D.Bp)(g,j,j.Qv),n=(0,D.Bp)(g,j,j.Rv));s==D.o&&(s=j.mj);n||(n=j.ni);j=j.Md();r&&j&&(s!=D.o&&(j=(0,D.Fp)(j,s,n)),h.x=window.Math.min(f.x,j.x+r.x),h.y=window.Math.min(f.y,j.y+r.y),h.e=window.Math.max(f.x+f.e,j.x+r.x+j.e)-h.x,h.g=window.Math.max(f.y+f.g,j.y+r.y+j.g)-h.y);f=h;if(g=c.getData().$R?c.getData().gd:D.o)c=c.getParent(),j=(0,D.Gp)(new D.F(f.x,f.y),c,b),j=(0,D.Hp)(j,l,b),g=(0,D.Gp)(new D.F(f.x+f.e,f.y+f.g),c,b),g=(0,D.Hp)(g,l,b),f.x=j.x,f.y=j.y,f.e=g.x-j.x,f.g=g.y-j.y;e?(j=e.x,g=
e.y,e.x=window.Math.min(e.x,f.x),e.y=window.Math.min(e.y,f.y),e.e=window.Math.max(j+e.e,f.x+f.e)-e.x,e.g=window.Math.max(g+e.g,f.y+f.g)-e.y):e=f}return e};
D.Fp=function(a,b,c){if(b==D.o&&!c)return a;var d=new D.F(a.x,a.y),e=new D.F(a.x+a.e,a.y),f=new D.F(a.x,a.y+a.g);a=new D.F(a.x+a.e,a.y+a.g);var g=new D.hj;b!=D.o&&(c&&g.translate(-c.x,-c.y),g.rotate(b),c&&g.translate(c.x,c.y));b=(0,D.Ip)(g,d);e=(0,D.Ip)(g,e);f=(0,D.Ip)(g,f);d=(0,D.Ip)(g,a);a=window.Math.min(window.Math.min(b.x,e.x),window.Math.min(f.x,d.x));g=window.Math.max(window.Math.max(b.x,e.x),window.Math.max(f.x,d.x));c=window.Math.min(window.Math.min(b.y,e.y),window.Math.min(f.y,d.y));b=window.Math.max(window.Math.max(b.y,
e.y),window.Math.max(f.y,d.y));return new D.A(a,c,g-a,b-c)};D.Hp=function(a,b,c){for(var d=(0,D.Jp)(b),e=a,f=d.length-1;0<=f;f--){b=d[f];a=b.ta().Y();var g=D.o,h=D.o;c&&(g=(0,D.Bp)(c,b,b.N),h=(0,D.Bp)(c,b,b.M));g!=D.o&&(a.qc=g);h!=D.o&&(a.oc=h);a.ky();e=(0,D.Ip)(a,e)}return e};D.Gp=function(a,b,c){for(var d=(0,D.Jp)(b),e=a,f=0;f<d.length;f++){b=d[f];a=b.ta().Y();var g=D.o,h=D.o;c&&(g=(0,D.Bp)(c,b,b.N),h=(0,D.Bp)(c,b,b.M));g!=D.o&&(a.qc=g);h!=D.o&&(a.oc=h);e=(0,D.Ip)(a,e)}return e};
D.op.prototype.kN=function(a,b,c,d,e){var f=this.da,g=f.Tc().e/2,h=f.Tc().g/2;c=g-(c+a)*e;d=h-(d+b)*e;a=g-a*e;b=h-b*e;this.io&&(h=(0,D.Cp)(this),-h.x*e<c?(g=c+h.x*e,c-=g,a+=g):-h.x*e>a&&(g=-h.x*e-a,c-=g,a+=g),-h.y*e<d?(e=d+h.y*e,d-=e,b+=e):-h.y*e>b&&(e=-h.y*e-b,d-=e,b+=e));f.xt=c;f.yt=d;f.vt=a;f.wt=b};D.yp=function(a){var b={};b.top=a.top;b.right=a.right;b.bottom=a.bottom;b.left=a.left;return b};D.wp=function(a){var b={};b.top=a.top;b.right=a.right;b.bottom=a.bottom;b.left=a.left;return b};
D.op.prototype.PM=(0,D.t)();D.Kp=function(a,b){a.Q0(D.vp.YG(b.ae()));var c=D.vp.YG(b.Hf());a.RO=c;a.Aq=c;a.Kn(D.vp.YG(b.Md()));a.Ly=D.k};
D.Lp=function(a,b){this.Init(a,b)};D.z.l(D.Lp,D.Mp,"DvtBaseDiagramKeyboardHandler");D.x=D.Lp.prototype;D.x.Init=function(a,b){D.Lp.o.Init.call(this,a,b);this.u=a};D.x.ga=(0,D.v)("u");D.x.qy=function(a){return 9==a.keyCode?D.p:this.tg(a)&&!a.ctrlKey};D.x.ar=function(a){return 32==a.keyCode&&a.ctrlKey};D.x.d_=function(a,b,c){b=b.keyCode;if(!c||1>c.length||!a)return D.o;var d=c[0];a=a.Ee();a=a.x+a.e/2;for(var e=0;e<c.length;e++){var f=c[e],g=f.Ee(),g=g.x+g.e/2;if(188==b&&g<=a||190==b&&g>=a){d=f;break}}return d};
D.x.r_=function(a,b,c,d){if(!d)return D.o;if(!b)return d[0];if(!a)return b;for(var e=0;e<d.length;e++){var f=d[e],g=f,h=a,j=f,l=this.rE(j.Zc?j.Zc():j.getData().Zc()),j=this.rE(j.hc?j.hc():j.getData().hc()),l=h==l?j:l,h=(0,D.Np)(h),l=(0,D.Np)(l),h=window.Math.atan2(l.y-h.y,l.x-h.x),h=0>h?h+2*window.Math.PI:h;g.R3=h;l=g=f;h=this.rE(l.Zc?l.Zc():l.getData().Zc());l=this.rE(l.hc?l.hc():l.getData().hc());h=(0,D.Np)(h);l=(0,D.Np)(l);g.KE=window.Math.sqrt(window.Math.pow(l.x-h.x,2)+window.Math.pow(l.y-h.y,
2));f.eO=a==this.rE(f.hc?f.hc():f.getData().hc())?1:0}d.sort(function(a,b){var c=a.R3,d=b.R3,e=-1;!(0,D.Op)(c,d)&&c>d?e=1:(0,D.Op)(c,d)&&(a.KE>b.KE?e=1:b.KE==a.KE&&a.eO>b.eO?e=1:b.KE==a.KE&&a.eO==b.eO&&(e=0));return e});for(a=0;a<d.length;a++)e=d[a],e.R3=D.i,e.KE=D.i,e.eO=D.i;c=40==c.keyCode?D.k:D.p;for(e=a=0;e<d.length;e++)if(d[e]===b){a=c?e==d.length-1?0:e+1:0==e?d.length-1:e-1;break}return d[a]};D.x.rE=(0,D.ca)(D.o);D.Np=function(a){a=a.Ee();return new D.F(a.x+a.e/2,a.y+a.g/2)};
D.Op=function(a,b){var c=1E-7>=window.Math.abs(a-b);c||(c=1E-7>=window.Math.abs(2*window.Math.PI+window.Math.min(a,b)-window.Math.max(a,b)));return c};
D.Pp=function(a,b,c){this.Init(a,b,c)};D.z.l(D.Pp,D.D,"DvtBaseDiagramLink");D.x=D.Pp.prototype;D.x.Init=function(a,b,c){D.Pp.o.Init.call(this,a,D.o,b);this.u=c;this.bz;this.Xh;this.Lx;this.Oa;this.NP;this.mj;this.ni;this.Ne=D.p;this.EG=D.k;this.G;this.wg;this.Cg};D.x.ga=(0,D.v)("u");D.x.mT=(0,D.t)();D.x.yp=(0,D.ca)(D.o);D.x.vT=(0,D.t)();D.x.OKa=(0,D.v)("Cg");(0,D.da)("DvtBaseDiagramLink.prototype.getStartConnector",D.Pp.prototype.OKa);D.Pp.prototype.nJa=(0,D.v)("wg");
(0,D.da)("DvtBaseDiagramLink.prototype.getEndConnector",D.Pp.prototype.nJa);D.x=D.Pp.prototype;D.x.sw=(0,D.ba)("G");D.x.rb=(0,D.v)("G");D.x.pw=function(a){this.mj=a;var b=this.Oa,c=this.qd();this.Md();b&&(a=(0,D.Qp)(c,a,this.ni),b.za(a))};D.x.Qv=(0,D.v)("mj");D.x.xs=function(a){this.ni=a;var b=this.Oa,c=this.qd();this.Md();b&&(a=(0,D.Qp)(c,this.mj,a),b.za(a))};D.x.Rv=(0,D.v)("ni");D.x.qd=(0,D.v)("NP");D.x.Rd=function(a){if(a){this.NP=a;var b=this.Oa;this.Md();b&&(a=(0,D.Qp)(a,this.mj,this.ni),b.za(a))}};
D.x.Md=(0,D.ca)(D.o);D.x.Kn=(0,D.t)();D.x.qS=(0,D.ca)(0);D.x.XR=(0,D.ca)(0);D.x.Lf=(0,D.ba)("EG");D.x.Aa=function(){return this.ga().br()&&this.EG};D.x.Da=(0,D.v)("Ne");(0,D.da)("DvtBaseDiagramLink.prototype.isSelected",D.Pp.prototype.Da);D.x=D.Pp.prototype;D.x.jb=(0,D.ba)("Ne");D.x.gE=(0,D.t)();D.x.py=(0,D.ca)(D.p);D.x.cE=(0,D.t)();D.x.Sv=(0,D.ca)(1);(0,D.da)("DvtBaseDiagramLink.prototype.getLinkWidth",D.Pp.prototype.Sv);D.x=D.Pp.prototype;D.x.XM=(0,D.t)();D.x.qH=(0,D.ca)("solid");D.x.WM=(0,D.t)();
D.x.FA=(0,D.ca)(D.o);D.x.tp=(0,D.ca)(D.o);D.x.Lea=function(){return this.qH()};D.x.oE=function(){return this.Sv()};D.x.Kea=function(){return this.FA()};D.Sp=function(a,b,c,d,e){if(c||e){var f;e||(f=a.G.Yb().Y(),f.Gk(0),f.Gc=D.p);if(c=D.Rp.cea(a.j(),c,e,f,a))a.G.k(c),D.Rp.UI(c,0,e,b,d);return c}};
D.Pp.prototype.wc=function(a){this.bz=a;D.zp.mU(a)?(this.Lx=a,this.Xh=D.zp.bea(a)):(this.Xh=a,this.Lx=D.zp.OT(a));this.G&&this.G instanceof D.Jh&&(this.G.Go(this.Lx),this.wg?D.Rp.UI(this.wg,this.yp(),this.tp(D.Rp.vI),this.Xh,1):this.wg=(0,D.Sp)(this,this.Xh,this.yp(),1,this.tp(D.Rp.vI)),this.Cg?D.Rp.UI(this.Cg,this.Wq(),this.tp(D.Rp.QI),this.Xh,0):this.Cg=(0,D.Sp)(this,this.Xh,this.Wq(),0,this.tp(D.Rp.QI)));var b=a=D.o;this.le&&this.le.jD instanceof D.Jh&&this.le.jD.Go(this.Lx);this.le&&(a=this.le.Qt)&&
D.Rp.UI(a,this.Wq(),this.tp(D.Rp.QI),this.Xh,0);this.le&&(b=this.le.Pt)&&D.Rp.UI(b,this.yp(),this.tp(D.Rp.vI),this.Xh,1);this.Pr&&this.Pr.jD instanceof D.Jh&&this.Pr.jD.Go(this.Lx);this.rL&&this.rL.Ej((0,D.Tp)(this));this.QJ&&this.QJ.Ej((0,D.Up)(this))};D.Pp.prototype.vb=(0,D.v)("bz");D.Tp=function(a){return!a.Xh?D.o:new D.F(a.Xh[0],a.Xh[1])};D.Up=function(a){if(!a.Xh)return D.o;var b=a.Xh.length;return new D.F(a.Xh[b-2],a.Xh[b-1])};
D.Qp=function(a,b,c){var d=new D.hj;b!=D.o&&(c&&d.translate(-c.x,-c.y),d.rotate(b),c&&d.translate(c.x,c.y));a&&d.translate(a.x,a.y);return d};D.Pp.prototype.sN=function(a,b,c){!b&&0!=b&&(b=1);!c&&0!=c&&(c=0);c=this.oE()+c;a=new D.hg(a,b,c);return new D.Vp(this.j(),this.Lx,a)};
D.Xp=function(a,b,c,d){b=a.sN(b,c,d);a.Cg&&a.Wq()&&(c=a.Wq(),d=(0,D.Wp)(b,a.Xh,c,a.tp(D.Rp.QI),a,0),b.Qt&&b.removeChild(b.Qt),b.Qt=d,b.H$=c,b.k(b.Qt));a.wg&&a.yp()&&(c=a.yp(),a=(0,D.Wp)(b,a.Xh,c,a.tp(D.Rp.vI),a,1),b.Pt&&b.removeChild(b.Pt),b.Pt=a,b.G$=c,b.k(b.Pt));return b};D.Yp=function(a,b,c){a=a.Lea();a=D.zp.aea(a);b.Gk(a,D.zp.Yea(a,c),D.zp.Zea(a,c))};
D.Zp=function(a,b){if(a){var c=D.o;b.qb&&(c=b.qb());if(c){var d=a.Yb()?a.Yb().Y():D.o,e=a.Rb()?a.Rb().Y():D.o;d&&d.jr&&(d.jr(c),a.V(d));e&&e.jr&&(e.jr(c),a.L(e))}}};D.x=D.Pp.prototype;D.x.Ad=(0,D.ca)(D.o);D.x.Ee=function(a){return this.F(a)};D.x.yj=function(){return this.sa()};D.x.Vd=(0,D.t)();D.x.jc=(0,D.t)();D.x.pc=(0,D.t)();D.x.Mc=(0,D.ca)(D.o);
D.$p=function(a,b,c){this.Init(a,b,c)};D.z.l(D.$p,D.D,"DvtBaseDiagramNode");D.x=D.$p.prototype;D.x.Init=function(a,b,c){D.$p.o.Init.call(this,a,D.o,b);this.u=c;this.Ne=this.gj=D.p;this.EG=D.k;this.Oa;this.NP;this.mj;this.ni;this.rn;this.Rj};D.x.ga=(0,D.v)("u");D.x.getData=(0,D.ca)(D.o);D.x.ae=function(){return this.Hf()};D.x.Hf=function(){return new D.A(0,0,this.getWidth(),this.getHeight())};D.x.Xi=function(){return{}};
D.x.Rd=function(a){if(a){this.NP=a;var b=this.Oa;this.Md();b&&(a=(0,D.aq)(a,this.mj,this.ni),b.za(a))}};D.x.qd=(0,D.v)("NP");D.x.Md=(0,D.ca)(D.o);D.x.Kn=(0,D.t)();D.x.up=(0,D.ca)(D.o);D.x.fB=(0,D.t)();D.x.Qa=(0,D.v)("gj");D.x.yf=(0,D.ba)("gj");D.x.Da=(0,D.v)("Ne");(0,D.da)("DvtBaseDiagramNode.prototype.isSelected",D.$p.prototype.Da);D.x=D.$p.prototype;D.x.jb=(0,D.ba)("Ne");D.x.Lf=(0,D.ba)("EG");D.x.Aa=function(){return this.ga().br()&&this.EG};D.x.oT=(0,D.ba)("ce");D.x.jMa=(0,D.v)("ce");
D.x.pw=function(a){this.mj=a;var b=this.Oa,c=this.qd();this.Md();b&&(a=(0,D.aq)(c,a,this.ni),b.za(a))};D.x.Qv=(0,D.v)("mj");D.x.xs=function(a){this.ni=a;var b=this.Oa,c=this.qd();this.Md();b&&(a=(0,D.aq)(c,this.mj,a),b.za(a))};D.x.Rv=(0,D.v)("ni");D.aq=function(a,b,c){var d=new D.hj;b!=D.o&&(c&&d.translate(-c.x,-c.y),d.rotate(b),c&&d.translate(c.x,c.y));a&&d.translate(a.x,a.y);return d};D.x=D.$p.prototype;
D.x.Iw=function(a,b,c){c?((0,D.T)(c,"typeNumber",this,this.N,this.I,a),(0,D.T)(c,"typeNumber",this,this.M,this.O,b)):(0,D.pk)(this,a,b)};D.x.Ad=(0,D.ca)(D.o);D.x.Ee=function(a){var b=this.Hf(a);a=(0,D.df)(this,new D.F(b.x,b.y));b=(0,D.df)(this,new D.F(b.x+b.e,b.y+b.g));return new D.A(a.x,a.y,b.x-a.x,b.y-a.y)};D.x.yj=function(){return this.sa()};D.x.Vd=(0,D.t)();D.x.jc=(0,D.t)();D.x.pc=(0,D.t)();D.x.Mc=(0,D.ca)(D.o);D.bq=function(a,b){a.rn||(a.rn=[]);a.rn.push(b)};
D.cq=function(a,b){a.Rj||(a.Rj=[]);a.Rj.push(b)};
D.dq=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtDiagram",D.dq);D.z.l(D.dq,D.op,"DvtDiagram");D.dq.prototype.Init=function(a,b,c){D.dq.o.Init.call(this,a,b,c);this.rf=new D.eq;this.eb=new D.fq(a,this.Pd,this);this.eb.me(this);(0,D.Jf)()||(0,D.xj)(this.eb,new D.gq(this,this.eb));this.hb={};this.rl=[];this.tc={};this.Lu=[];this.ym=0};D.dq.newInstance=function(a,b,c){return new D.dq(a,b,c)};D.x=D.dq.prototype;
D.x.MI=function(){!this.uq&&this.ye&&("none"!=this.GJ&&(this.qn={id:this.getId(),getId:(0,D.v)("id"),options:this.q(),getOptions:(0,D.v)("options"),panZoomMatrix:this.da.ba.ta(),getPanZoomMatrix:(0,D.v)("panZoomMatrix"),nodes:this.hb?(0,D.hq)(this):[],links:this.tc?(0,D.iq)(this):[],getNodes:(0,D.v)("nodes"),getLinks:(0,D.v)("links")},this.qn.q=this.qn.getOptions,this.qn.lKa=this.qn.getPanZoomMatrix,this.qn.getId=this.qn.getId,this.qn.Jra=this.qn.getNodes,this.qn.xra=this.qn.getLinks),this.ye=D.p,
this.LK=this.da);this.uq||this.n3()};D.x.n3=function(){this.Dl=new D.D(this.j());this.Vh=new D.D(this.j());this.Ot=new D.D(this.j());this.hb={};this.rl=[];this.tc={};this.Lu=[];this.qx=D.o};D.x.zq=function(){this.mf&&(this.removeChild(this.mf),this.mf.Q());this.mf=D.o;this.Ua&&(this.Ua=D.o,this.ka().me(this))};
D.x.gf=function(a,b){var c=new D.qn(this.j(),D.o,a.xa()),d=b.lKa(),e=this.da.ba.ta();d.Xc(e)||(this.da.ba.za(d),(0,D.T)(c.J,"typeMatrix",this.da.ba,this.da.ba.ta,this.da.ba.za,e));(0,D.Tm)(a,b.Jra(),this.hb?(0,D.hq)(this):[]);(0,D.Tm)(a,b.xra(),this.tc?(0,D.iq)(this):[]);a.add(c,1)};
D.x.dq=function(a){var b=D.p;if(!this.ye&&!this.uq){var c=this.q().nodes;if(c)for(var d=0;d<c.length;d++){var e=c[d],e=D.pl.bd(e,this.q().styleDefaults.nodeDefaults),e=new D.jq(this.j(),this,e),f=e.getId();e.Yba()?this.rl.push(f):(e.P(this.Vh),this.rl.push(f),this.hb[f]=e)}if(c=this.q().links)for(d=0;d<c.length;d++){var e=c[d],e=D.pl.bd(e,this.q().styleDefaults.linkDefaults),g=new D.kq(this.j(),this,e),e=g.getId();g.Yba()?this.Lu.push(e):(g.P(this.Dl),this.Lu.push(e),this.tc[e]=g,f=this.K(g.Zc()),
g=this.K(g.hc()),(0,D.bq)(f,e),(0,D.cq)(g,e))}var c=[],h;for(h in this.hb)c.push(h);b=0===c.length;(0,D.Vl)(this.j(),[this]);this.ym++}if(b)this.ym=this.ye?this.ym:this.ym-1,0===this.ym&&(0,D.lq)(this,a,b);else{this.contains(this.LK)||this.k(this.LK);var j=this;this.cr(a).then(function(){j.ym=j.ye?j.ym:j.ym-1;0===j.ym&&(0,D.lq)(j,a,b)},function(){j.ym=j.ye?j.ym:j.ym-1;0===j.ym&&(j.removeChild(j.LK),j.LK=D.o,j.ye=D.k)})}};
D.lq=function(a,b,c){var d;if(!c){a.removeChild(a.LK);a.bA();a.cA();if(d=a.Hi==D.o)a.Hi=(0,D.Dp)(a,b,D.i,D.i);var e=a.da;if(a.ye){if(a.uq){var f=a.vw(b,a.Hi),f=g?(0,D.Cp)(a):f?f:a.Hi;e.CO=D.k;e.Io(D.o,f);e.CO=a.uA}}else{a.vw(b,a.Hi);if(!a.uq){var g=a.io?D.k:D.p,f=g?(0,D.Cp)(a):a.Hi;g&&(e.Jq=0);e.Io(D.o,f)}e.ji=a.Dt;e.Wn=a.uA;e.CO=a.uA}}a.LK=D.o;a.ye||(a.Ua&&a.Ua.stop(D.k),(0,D.Zk)()&&a.bS()&&!a.qn?a.Ua=D.dl.by(a.j(),a.bS(),a,D.o,a.xa()):"none"!=a.GJ&&a.qn&&(a.mf=new D.D(a.j(),"Delete Container"),
a.k(a.mf),e=new D.mq(a.j(),a.mf,a.qn,a),(0,D.Tm)(e,[a.qn],[a]),a.Ua=e.Oq()),a.Ua?(a.ka().Cc(),a.ka().gi(a),a.Ua.ie(a.zq,a),a.Ua.play()):a.zq());a.ye=D.k;(0,D.qp)(a,c);a.Dt&&(c=a.Hi,c!=D.o&&(b=a.da.Cd(b),a.kN(c.x,c.y,c.e,c.g,b)));a.io=D.o;a.wK=D.o;d&&(a.Hi=D.o)};D.x=D.dq.prototype;
D.x.vd=function(a){D.dq.o.vd.call(this,a);(0,D.nq)(this,this.D);this.Dt="none"!=this.D.panning;this.uA="none"!=this.D.zooming;this.TO="hidden";this.GJ=this.D.animationOnDataChange;this.aX="auto"==this.D.animationOnDisplay?D.dl.uw:D.o;this.rw(this.D.selectionMode);this.jn=this.D.emptyText?this.D.emptyText:(0,D.nk)(this.D,"labelNoData","DvtUtilBundle","NO_DATA")};D.x.fy=function(){var a=this.q().maxZoom,a=(0,window.parseFloat)(a);return 0<a?a:1};
D.x.zD=function(){var a=this.q().minZoom;if(a){var b=(0,window.parseFloat)(a);0<b&&(a=window.Math.min(b,this.fy()));return a}return D.o};D.x.xa=function(){return(0,D.hp)(this.q().styleDefaults.animationDuration)/1E3};D.x.Pd=function(a){var b=a.Pa();("categoryRollOver"==b||"categoryRollOut"==b)&&this.bA();a&&this.dispatchEvent(a)};
D.x.cr=function(a){for(var b=this.q().layout,c=(0,D.tp)(this),d={},e=0;e<this.rl.length;e++){var f=this.rl[e];this.K(f)&&(d[f]=D.k,c.VG(this.Es(this.K(f))))}for(var g in this.tc)if(e=this.Mb(g)){var f=e.getData().startNode,h=e.getData().endNode;d[f]&&d[h]&&(0,D.oq)(c,this.oB(e,f,h))}if(b&&"function"==typeof b){var j=this;(b=b(c))||(b={then:function(a){a()}});this.P0(0);b.then(function(){1===j.ym&&(j.P0(1),j.mB(c,a,D.k))},(0,D.t)());return b}this.xE("DvtDiagram: Layout function is not defined",1)};
D.x.P0=function(a){this.ye||(this.Dl.B(a),this.Vh.B(a))};D.x.K=function(a){return this.hb[a]};D.x.Mb=function(a){return this.tc[a]};D.x.xI=(0,D.v)("Lu");D.iq=function(a){var b=[],c;for(c in a.tc)b.push(a.tc[c]);return b};D.dq.prototype.rB=(0,D.v)("rl");D.hq=function(a){var b=[],c;for(c in a.hb)b.push(a.hb[c]);return b};D.x=D.dq.prototype;
D.x.ph=function(a){D.dq.o.ph.call(this,a);switch(a.xj()){case "adjustPanConstraints":if(this.Dt){var b=a.qv,c=this.Hi?this.Hi:(0,D.Dp)(this,a.J,D.i,D.i);this.kN(c.x,c.y,c.e,c.g,b)}break;case "zoomToFitCalcBounds":this.io||(c=this.Hi?this.Hi:(0,D.Dp)(this,a.J,D.i,D.i),a.TG=c);break;case "zoomed":if(this.q().zoomRenderer&&a.RC!==a.qv)for(b in this.hb){var c=this.K(b),d=a;if(c.u.q().zoomRenderer){var e=c.Ki(d.RC),d=c.Ki(d.qv);(0,D.pq)(c,c.u.q().zoomRenderer,d,e)}}}};D.x.Ata=(0,D.t)();
D.x.kM=function(a){var b=[],c;for(c in this.tc){var d=this.Mb(c),e=d.Zc(),f=d.hc();(e==a||f==a)&&d.bb&&b.push(d)}return b};D.x.Hj=function(){return(0,D.L)("DvtUtilBundle","DIAGRAM")};D.x.cA=function(){if(this.D.selection&&this.br()){var a=[],b;for(b in this.hb)a.push(this.K(b));for(var c in this.tc)a.push(this.Mb(c));(0,D.Il)(this.mh(),this.D.selection,a)}};
D.x.bA=function(){this.qx&&(this.uR(D.p,this.qx),this.qx=D.o);var a=this.D.highlightedCategories;if(a){var b="any"==this.D.highlightMatch;this.qx={};var c=[],d;for(d in this.hb){var e=this.K(d),f=b?D.H.hu(e.Mc(),a):D.H.yS(e.Mc(),a);f&&(this.qx[e.getId()]=e,c.push(e))}d=this.D.nodeHighlightMode;if("node"!=d){f="nodeAndIncomingLinks"==d||"nodeAndLinks"==d;d="nodeAndOutgoingLinks"==d||"nodeAndLinks"==d;for(var e=[],g=0;g<c.length;g++)for(var h=c[g],j=f&&h.Rj?h.Rj:[],j=d&&h.rn?j.concat(h.rn):j,h=0;h<
j.length;h++){var l=j[h];this.qx[l]=this.Mb(l);e.push(this.Mb(l))}(0,D.qq)(this,e)}var c=[],m;for(m in this.tc)if(d=this.Mb(m),f=b?D.H.hu(d.Mc(),a):D.H.yS(d.Mc(),a))this.qx[d.getId()]=d,c.push(d);"linkAndNodes"==this.D.linkHighlightMode&&(0,D.qq)(this,c);this.uR(D.k,this.qx)}};D.qq=function(a,b){for(var c=0;c<b.length;c++){var d=b[c],e=d.Zc(),d=d.hc();a.qx[e]=a.K(e);a.qx[d]=a.K(d)}};
D.dq.prototype.uR=function(a,b){var c=a?this.D.styleDefaults._highlightAlpha:1;this.Dl.B(c);this.Vh.B(c);for(var d in b)a?this.Ot.k(b[d]):b[d]instanceof D.kq?this.Dl.k(b[d]):b[d]instanceof D.jq&&this.Vh.k(b[d])};D.dq.prototype.Ge=function(a){this.D.highlightedCategories=D.pl.Y(a);this.bA()};D.dq.prototype.highlight=D.dq.prototype.Ge;D.dq.prototype.select=function(a){this.D.selection=D.pl.Y(a);this.cA()};D.dq.prototype.select=D.dq.prototype.select;
D.dq.prototype.Gf=function(){this.Kk||(this.Kk=new D.rq(this));return this.Kk};D.dq.prototype.getAutomation=D.dq.prototype.Gf;D.dq.prototype.xE=function(a,b){var c=this.q()._logger;if(c)switch(b){case 1:c.error&&c.error(a);break;case 2:c.warn&&c.warn(a);break;case 3:c.info&&c.info(a);break;default:c.log&&c.log(a)}};D.dq.prototype.ss=function(a,b){var c=this.K(a);c&&c.ss(b)};D.dq.prototype.processDefaultHoverEffect=D.dq.prototype.ss;D.dq.prototype.bB=function(a,b){var c=this.K(a);c&&c.bB(b)};
D.dq.prototype.processDefaultSelectionEffect=D.dq.prototype.bB;D.dq.prototype.kw=function(a,b){var c=this.K(a);c&&c.kw(b)};D.dq.prototype.processDefaultFocusEffect=D.dq.prototype.kw;D.dq.prototype.PM=function(a){var b=this.K(a.getId());b.Ly()||(b.P(this.Vh),(0,D.Kp)(a,b))};
D.tq=function(a,b){D.tq.o.constructor.call(this,a,b);this.W6=100;this.u=b};D.z.l(D.tq,D.uq,"DvtDiagramCategoryRolloverHandler");D.tq.prototype.g2=function(a){return D.z.xf(this,function(){this.oJ=D.k;this.u.Pd(a)})};D.tq.prototype.f2=function(a){return D.z.xf(this,function(){(0,D.vq)(this);this.u.Pd(a)})};
D.eq=function(){this.Init({skyros:D.wq,alta:D.xq})};D.z.l(D.eq,D.Nj,"DvtDiagramDefaults");
D.wq={skin:"alta",emptyText:D.o,selectionMode:"none",animationOnDataChange:"none",animationOnDisplay:"none",maxZoom:1,highlightMatch:"all",nodeHighlightMode:"node",linkHighlightMode:"link",panning:"none",touchResponse:"auto",zooming:"none",_statusMessageStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),styleDefaults:{animationDuration:500,hoverBehaviorDelay:200,_highlightAlpha:0.1,nodeDefaults:{labelStyle:'font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:bold;font-size:12px;color:#383A47',
hoverInnerColor:"rgb(255,255,255)",hoverOuterColor:"rgba(0,0,0, .3)",selectionColor:"rgb(0,0,0)",icon:{width:10,height:10,fillPattern:"none",shape:"circle"}},linkDefaults:{startConnectorType:"none",endConnectorType:"none",width:1,style:"solid",hoverInnerColor:"rgb(255,255,255)",hoverOuterColor:"rgba(0,0,0, .3)",selectionColor:"rgb(0,0,0)",labelStyle:'font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:bold;font-size:12px;color:#383A47',_hitDetectionOffset:4}}};D.xq={};
D.mq=function(a,b,c,d){this.Init(a,b,c,d)};D.z.l(D.mq,D.Sm,"DvtDiagramDataAnimationHandler");D.mq.prototype.Init=function(a,b,c,d){D.mq.o.Init.call(this,a,b);this.aEa=c;this.PPa=d};D.mq.prototype.xa=function(){return(0,D.hp)(this.aEa.q().styleDefaults.animationDuration)/1E3};
D.fq=function(a,b,c){this.Init(a,b,c);this.u=c};D.z.l(D.fq,D.Pj,"DvtDiagramEventManager");D.x=D.fq.prototype;D.x.fm=function(a,b,c){a=this.u.q();"dim"==a.hoverBehavior&&(b=b.Mc?b.Mc():[],a.highlightedCategories=c?b.slice():D.o,c=new D.zm(c?"categoryRollOver":"categoryRollOut",a.highlightedCategories),b=(0,D.hp)(a.styleDefaults.hoverBehaviorDelay),this.GB.Pd(c,(0,D.hq)(this.u),b,"any"==a.highlightMatch))};D.x.w1=function(a,b){return new D.tq(a,b)};
D.x.Kh=function(a){var b=D.k,c=a.keyCode,d=this.dd(),e=d instanceof D.jq?d.$u:D.o;9!=c&&this.Ww?(e.VL(a),a.preventDefault()):9==c&&e instanceof D.sj?!a.shiftKey&&d.pc()?(d.jc(),e.VL(a),a.preventDefault(),this.Ww=D.k):(a.shiftKey&&this.Ww?(this.SI(a,d),a.preventDefault()):(this.Ww&&d.Vd(),b=D.fq.o.Kh.call(this,a)),this.Ww=D.p):b=D.fq.o.Kh.call(this,a);return b};D.x.Bu=function(){var a=this.u.q();return"none"!==a.panning||"none"!==a.zooming?"touchHold":"touchStart"===a.touchResponse?"touchStart":"auto"};
D.x.qr=function(a){return(0,D.yq)(this,a,"panned")};D.x.Jw=function(a){return"panned"==a?D.p:D.fq.o.Jw.call(this,a)};
D.gq=function(a,b){this.Init(a,b)};D.z.l(D.gq,D.Lp,"DvtDiagramKeyboardHandler");D.gq.prototype.tg=function(a){var b=D.p;switch(a.keyCode){case 188:case 190:b=a.altKey?D.k:D.p;break;default:b=D.gq.o.tg.call(this,a)}return b};D.gq.prototype.Fh=function(a){if(9==a.keyCode){var b=this.ea.dd();if(b)return(0,D.hi)(a),b;b=(0,D.hq)(this.ga());if(0<b.length)return(0,D.hi)(a),this.tD(b)}return D.gq.o.Fh.call(this,a)};D.gq.prototype.rE=function(a){return this.ga().K(a)};
D.vp={};D.z.l(D.vp,D.z,"DvtDiagramLayoutUtils");D.vp.oLa=function(a){for(var b=D.vp.QJa(a),c=window.Math.max(b.w,b.h),b=a.Oe(),d=a.Ap(),e=window.Math.floor(window.Math.sqrt(b)),f=0,f=(f=a.Xi())&&f.padding?f.padding:0<d?c:0.25*c,c=c+f,d=-(window.Math.ceil(b/e)-1)*c/2,f=-(e-1)*c/2,g=0;g<b;g++)D.vp.pHa(a.GA(g),d+c*window.Math.floor(g/e),f+c*(g%e))};
D.vp.QJa=function(a){for(var b=a.Oe(),c=0,d=0,e=0;e<b;e++){var f=a.GA(e),g=f.zd(),c=window.Math.max(g.w,c),d=window.Math.max(g.h,d);if(f=f.Md())c=window.Math.max(f.w,c),d=window.Math.max(g.h+f.h,d)}return new D.sp(0,0,c,d)};D.vp.pHa=function(a,b,c){var d=a.Hf();a.Ej(new D.zq(b-d.x-0.5*d.w,c-d.y-0.5*d.h));D.vp.iNa(a)};D.vp.iNa=function(a){var b=a.zd(),c=a.bg(),d=a.Md();d&&a.Rd(new D.zq(b.x+c.x+0.5*(b.w-d.w),b.y+c.y+b.h))};D.vp.YG=function(a){return a===D.i||a==D.o?D.o:new D.sp(a.x,a.y,a.e,a.g)};
D.vp.dqa=function(a){return a===D.i||a==D.o?D.o:new D.zq(a.x,a.y)};D.vp.uHa=function(a){return a?new D.A(a.x,a.y,a.w,a.h):D.o};D.vp.cqa=function(a){return a?new D.F(a.x,a.y):D.o};
D.kq=function(a,b,c){this.Init(a,b,c)};D.z.l(D.kq,D.Pp,"DvtDiagramLink");D.x=D.kq.prototype;D.x.Init=function(a,b,c){D.kq.o.Init.call(this,a,c.id,b);this.oa=c;this.u.br()&&this.setCursor("pointer")};D.x.getData=(0,D.v)("oa");D.x.getId=function(){return this.getData().id};D.x.Zc=function(){return this.getData().startNode};D.x.hc=function(){return this.getData().endNode};D.x.Md=function(){var a=D.o;this.Oa&&(a=this.Oa.F());return a};D.x.qH=function(){return this.getData().style};D.x.Sv=function(){return this.getData().width};
D.x.FA=function(){return this.getData().color};D.x.Wq=function(){return this.getData().startConnectorType};D.x.yp=function(){return this.getData().endConnectorType};D.x.qS=function(){if(this.Wq()){var a=this.rb().Yb().Y();a.Gk(0);return D.Rp.UT(D.o,this.Wq(),D.o,a,this)}return 0};D.x.XR=function(){if(this.yp()){var a=this.rb().Yb().Y();a.Gk(0);return D.Rp.UT(D.o,this.yp(),D.o,a,this)}return 0};
D.x.P=function(a){var b=this.getData(),c=this.Lx;c||(c=["M",0,0,"L",0,0]);var d=b.id,e=b.color,f=b.width,g=b.style;this.Pr=this.sN("#000000",0,b._hitDetectionOffset);this.k(this.Pr);b=new D.hg(e,1,f);(0,D.Jf)()&&((0,D.Bq)()&&1==(0,D.On)())&&(b.Gc=D.k);g=D.zp.aea(g);b.Gk(g,D.zp.Yea(g),D.zp.Zea(g));c=new D.Jh(this.j(),c,d);c.L(D.o);c.V(b);this.sw(c);this.k(c);b=this.u;c=this.getData();d=(0,D.E)(b.j())?"right":"left";c.label&&(g=c.labelStyle,b=new D.Kf(b.j(),c.label,0,0),b.Ha(new D.G(g)),b.uu(d),b.Ey("top"),
c=(0,D.Cq)((new D.G(c.labelStyle)).getWidth()),0<c&&D.$e.Qb(b,c,window.Infinity,this)||this.k(b),this.Oa=b);a.k(this);this.Ud("img");this.$m();this.u.ka().Ca(this,this)};D.x.jb=function(a){D.kq.o.jb.call(this,a);a?this.Ev(this.Al,D.k):this.Jz();this.$m()};D.x.Aa=function(){return this.ga().br()&&"off"!=this.getData().selectable};
D.x.Ev=function(a,b){if(a){this.Zh||(this.Zh=this.rb().Yb());var c=this.rb().Yb().Y();c.jr&&c.jr(this.getData().hoverInnerColor);this.rb().V(c);(0,D.Zp)(this.Cg,c);(0,D.Zp)(this.wg,c)}else this.Zh&&(this.rb().V(this.Zh),(0,D.Zp)(this.Cg,this.Zh),(0,D.Zp)(this.wg,this.Zh),this.Zh=D.o);this.le||(this.le=(0,D.Xp)(this,"#000000",1,0),this.Ma(this.le,0));var c=b?this.getData().selectionColor:this.getData().hoverOuterColor,d=this.le.Yb().Y();d.jr(c);d.ma(2+this.oE());(0,D.Yp)(this,d,D.k);this.le.V(d,2)};
D.x.Jz=function(){this.Zh&&(this.rb().V(this.Zh),(0,D.Zp)(this.Cg,this.Zh),(0,D.Zp)(this.wg,this.Zh),this.Zh=D.o);this.le&&(this.removeChild(this.le),this.le.Q&&this.le.Q(),this.le=D.o)};D.x.Ob=function(){this.Al||(this.Al=D.k,this.Ev(D.k,this.Da()))};D.x.Db=function(){this.Da()?this.Ev(D.p,D.k):this.Jz();this.Al=D.p};D.x.De=function(){var a=this.ga().q().tooltip;return a?(0,D.ip)(this.ga().j().ge(),a,this.vp()):this.Bc()};D.x.Bc=function(){return this.getData().shortDesc};
D.x.vp=function(){return{id:this.getId(),type:"link",label:this.getData().label}};D.x.fc=function(){var a=[];this.Aa()&&a.push((0,D.L)("DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.ok)(this.Bc(),a)};D.x.$m=function(){if(!(0,D.cf)()){var a=this.fc();a&&this.$b("label",a)}};
D.x.Ad=function(a){if(32==a.keyCode&&a.ctrlKey)return this;if(38==a.keyCode||40==a.keyCode){var b=this.rK;b||(b=this.ga().K((0,D.Dq)(this.ga(),this)));var c=this,d=this.ga().kM(b.getId()),e;(e=this.ga().ka().Sf)&&e.r_&&(c=e.r_(b,this,a,d));c.rK=b;return c}return 39==a.keyCode||37==a.keyCode?(a=this.LX(a.keyCode)?this.Zc():this.hc(),this.ga().K(a)):a.type==D.kk?this:D.o};D.x.LX=function(a){var b=(0,D.Tp)(this),c=(0,D.Up)(this),b=b.x<c.x?D.k:D.p;return 39==a&&b||37==a&&!b?D.p:D.k};
D.x.Vd=function(){this.Ib=D.k;this.Ob()};D.x.jc=function(){this.Ib=D.p;this.Db()};D.x.pc=(0,D.v)("Ib");D.x.Mc=function(){return this.getData().categories?this.getData().categories:[this.getId()]};D.x.Yba=function(){var a=this.ga().q().hiddenCategories;return a&&D.H.hu(a,this.Mc())||!this.ga().K(this.Zc())||!this.ga().K(this.hc())?D.k:D.p};
D.x.gf=function(a,b){var c=b.vb(),d=this.vb(),e=new D.qn(this.j(),D.o,a.xa());D.H.Xc(c,d)||(this.wc(c),c="typePolyline",0<d.length&&(0,window.isNaN)(d[0])&&(c="typePath"),(0,D.T)(e.J,c,this,this.vb,this.wc,d));b.Oa&&this.Oa&&(d=b.Oa.ta(),c=this.Oa.ta(),d.Xc(c)||(this.Oa.za(d),(0,D.T)(e.J,"typeMatrix",this.Oa,this.Oa.ta,this.Oa.za,c)));if(b.rb()&&this.rb()&&(d=b.rb().Yb(),c=this.rb().Yb(),d&&c&&d instanceof D.hg&&c instanceof D.hg&&(d.qb()!=c.qb()||d.getWidth()!=c.getWidth())))this.rb().V(d),(0,D.T)(e.J,
"typeStroke",this.rb(),this.rb().Yb,this.rb().V,c);a.add(e,1)};D.x.kh=function(a){this.ga().Dl.k(this);var b=this,c=new D.sn(this.j(),this,a.xa());(0,D.hl)(c,function(){b.getParent().removeChild(b);b.Q()});a.add(c,0)};D.x.qg=function(a){this.B(0);a.add(new D.Vm(this.j(),this,a.xa()),2)};D.x.Xi=function(){return this.getData()};
D.Rp={};D.z.l(D.Rp,D.z,"DvtDiagramLinkConnectorUtils");D.Rp.vI="endConnector";D.Rp.QI="startConnector";D.Rp.Uda="arrowOpen";D.Rp.KT="arrow";D.Rp.LT="arrowConcave";D.Rp.Wda="rectangle";D.Rp.Xda="rectangleRounded";D.Rp.Vda="circle";
D.Rp.cea=function(a,b,c,d,e){if(c)return D.Rp.yua(c,e);c=e.oE();switch(b){case D.Rp.KT:return D.Rp.zua(a,c,e.FA());case D.Rp.LT:return D.Rp.Aua(a,c,e.FA());case D.Rp.Uda:return D.Rp.Cua(a,c,d);case D.Rp.Vda:return D.Rp.xua(a,c,d);case D.Rp.Wda:return D.Rp.hea(a,c,d);case D.Rp.Xda:return D.Rp.Gua(a,c,d)}return D.o};D.Rp.UI=function(a,b,c,d,e){b=D.Rp.qua(a,c,d,e);a.za(b)};
D.Rp.qua=function(a,b,c,d){var e=-1,f=0,g=0,h=0;c&&(f=c.length,1===d?(2<=f&&(g=c[f-2],h=c[f-1]),4<=f?(e=c[f-4],f=c[f-3]):(e=g-1E-4,f=h)):(2<=f&&(g=c[0],h=c[1]),4<=f?(e=c[2],f=c[3]):(e=g+1E-4,f=h)));c=g;d=h;e=D.Rp.pua(e,f,g,h);g=a.QAa;g||(g=a.ta().Y(),a.QAa=g);h=new D.hj;b&&(b=D.Rp.wka(a),f=a.vc(),a=a.Ac(),h.translate(-0.5*b.e*f,-0.5*b.g*a));h.rotate(e);h.translate(c,d);h.concat(g);return h};D.Rp.wka=function(a){var b=a.EAa;b||(b=a.F(),a.EAa=b);return b};
D.Rp.pua=function(a,b,c,d){return window.Math.atan2(d-b,c-a)};D.Rp.Aua=function(a,b,c){b=6*D.Rp.LW(b);var d=0.8*b;a=new D.Un(a,[-0.22*b,-0.5*d,0.78*b,0,-0.22*b,0.5*d,0,0]);a.pa(c);return a};D.Rp.zua=function(a,b,c){b=5*D.Rp.LW(b);var d=0.8*b;a=new D.Un(a,[0,-0.5*d,b,0,0,0.5*d]);a.pa(c);return a};D.Rp.LW=function(a){if(1>=a)return a;a=0.5*(a-1);return 1+a};
D.Rp.Cua=function(a,b,c){b*=3;var d=c.getWidth();a=new D.po(a,[-b+d*window.Math.sqrt(2)/2,-b,d*window.Math.sqrt(2)/2,0,-b+d*window.Math.sqrt(2)/2,b]);a.V(c);a.L(D.o);return a};D.Rp.Vqa=function(a){return 2*a};D.Rp.Rra=function(a){return 3*a};D.Rp.xua=function(a,b,c){b=D.Rp.Vqa(b);a=new D.Vn(a,b,0,b);a.V(c);a.L(D.o);return a};D.Rp.hea=function(a,b,c){b=D.Rp.Rra(b);a=new D.Te(a,0,-b/2,b,b);a.V(c);a.L(D.o);return a};D.Rp.Gua=function(a,b,c){a=D.Rp.hea(a,b,c);(0,D.Eq)(a,b);return a};
D.Rp.yua=function(a,b){var c=(0,D.ji)(b.ga()),d=b.getData().xl;c.Ir=d;c.gB(b,b.IR);d=b.xH();c.Lt=d;return D.ze.XH(c,a,b)};D.Rp.UT=function(a,b,c,d,e){if(c)return b=D.Rp.wka(a),a=a.vc(),0.5*b.e*a;a=e.oE();d=d.getWidth();switch(b){case D.Rp.Uda:return d*window.Math.sqrt(2);case D.Rp.KT:return b=D.Rp.LW(a),5*b;case D.Rp.LT:return b=D.Rp.LW(a),0.78*6*b;case D.Rp.Vda:return 2*D.Rp.Vqa(d)+d/2;case D.Rp.Wda:case D.Rp.Xda:return D.Rp.Rra(d)+d/2;default:return 0}};
D.Vp=function(a,b,c){D.Vp.o.Init.call(this,a);this.Init(a,b,c)};D.z.l(D.Vp,D.D,"DvtDiagramLinkUnderlay");D.Vp.prototype.Init=function(a,b,c){b||(b=["M",0,0,"L",1,0]);this.oo=c;this.oo||(this.oo=new D.hg("#ffffff",1,1));this.jD=new D.Jh(a,b);this.jD.V(c);this.jD.L(D.o);this.k(this.jD);this.G$=this.Pt=this.H$=this.Qt=D.o};D.Wp=function(a,b,c,d,e,f){a=D.Rp.cea(a.j(),c,d,a.oo,e);D.Rp.UI(a,0,d,b,f);return a};
D.Vp.prototype.V=function(a,b){this.oo=a;(0,D.Jf)()&&((0,D.Bq)()&&1==(0,D.On)())&&(a.Gc=D.k);this.jD.V(a);if(this.Qt){var c=a.Y();c.Gk(0);c.Gc=D.p;if(this.H$==D.Rp.KT||this.H$==D.Rp.LT)c.ma(b),this.Qt.pa(a.qb());this.Qt.V(c)}if(this.Pt){c=a.Y();c.Gk(0);c.Gc=D.p;if(this.G$==D.Rp.KT||this.G$==D.Rp.LT)c.ma(b),this.Pt.pa(a.qb());this.Pt.V(c)}};D.Vp.prototype.Yb=(0,D.v)("oo");
D.zp={};D.z.l(D.zp,D.z,"DvtDiagramLinkUtils");D.zp.aea=function(a){var b=0;switch(a){case "dash":b=1;break;case "dot":b=2;break;case "dashDot":b=3}return b};D.zp.Yea=function(a,b){if(0==a)return D.o;if(1==a)return b?"8,2":"6,4";if(2==a)return b?"4,1":"2,3";if(3==a)return b?"10,1,4,1":"8,3,2,3"};D.zp.Zea=function(a,b){return b&&0!=a?1:D.o};D.zp.OT=function(a){var b=[];if(a)for(var c=0;c<a.length;c+=2)0==c?b.push("M"):b.push("L"),b.push(a[c]),b.push(a[c+1]);return b};
D.zp.bea=function(a){var b=[];if(a)for(var c=0;c<a.length;c++)(0,window.isNaN)(a[c])||b.push(a[c]);return b};D.zp.mU=function(a){return a&&0<a.length?(0,window.isNaN)(a[0]):D.p};D.zp.Z1=function(a){var b=[];a=D.zp.mU(a)?D.zp.bea(a):a;for(var c=0;c<a.length;c+=2)b.push(new D.F(a[c],a[c+1]));return b};
D.jq=function(a,b,c){this.Init(a,b,c)};D.z.l(D.jq,D.$p,"DvtDiagramNode");D.x=D.jq.prototype;D.x.Init=function(a,b,c){D.jq.o.Init.call(this,a,c.id,b);this.oa=c;this.u.br()&&this.setCursor("pointer")};D.x.getData=(0,D.v)("oa");D.x.getId=function(){return this.oa.id};D.x.Hf=(0,D.v)("AJ");D.x.Md=function(){var a=D.o;this.Oa&&(a=this.ux?this.ux:this.Oa.F());return a};
D.x.jb=function(a){var b=this.Ki();D.jq.o.jb.call(this,a);this.u.q().selectionRenderer?(0,D.pq)(this,this.u.q().selectionRenderer,this.Ki(),b):this.bB(a);this.$m()};D.x.bB=function(a){this.zo()&&this.zo().jb(a)};D.x.Aa=function(){return this.ga().br()&&"off"!=this.getData().selectable};D.x.zN=(0,D.v)("G");
D.x.P=function(a){if(this.u.q().renderer)(0,D.pq)(this,this.u.q().renderer,this.Ki(),D.o);else{var b=this.getData(),c=this.u,d=new D.G(b.backgroundStyle);if(!(0,D.Wf)(d)){var e=(0,D.Cq)(d.A("width")),f=(0,D.Cq)(d.A("height")),g=d.A("background-color"),h=d.A("border-color"),j=(0,D.Cq)(d.A("border-width")),d=(0,D.Cq)(d.A("border-radius")),c=new D.Te(c.j(),0,0,e,f);c.pa(g);d&&(c.zf(d),c.Kf(d));h&&c.V(new D.hg(h,1,j));this.k(c);this.fI(c);this.Na=c}g=this.u;if(h=b.icon){c=h.width;e=h.height;j=h.color;
g=h.source?new D.ch(g.j(),c/2,e/2,c,e,h.source,h.sourceSelected,h.sourceHover,h.sourceHoverSelected):new D.dh(g.j(),h.shape,"alta",c/2,e/2,c,e);"none"!=h.fillPattern?g.L(new D.eh(h.fillPattern,j,j)):g.pa(j);h.borderColor&&g.V(new D.hg(h.borderColor,h.borderWidth));this.k(g);this.G=g;if(this.Na){var h=b.icon,j=this.Na.getWidth(),c=this.Na.getHeight(),e=h.width,f=h.height,d=0.5*(j-e),l=0.5*(c-f);if(h.positionX!==D.i)d=(0,window.parseFloat)(h.positionX),(0,D.E)(this.j())&&(d=j-d-e);else{var m=h.halign;
"start"==m?m=(0,D.E)(this.j())?"right":"left":"end"==m&&(m=(0,D.E)(this.j())?"left":"right");d="left"==m?0:"right"==m?j-e:d}h.positionY!==D.i?l=(0,window.parseFloat)(h.positionY):"top"==h.valign?l=0:"bottom"==h.valign&&(l=c-f);(0,D.pk)(this.G,d,l)}this.Na||this.fI(g)}j=this.u;g=(0,D.E)(j.j())?"right":"left";b.label&&(h=b.labelStyle,j=new D.Kf(j.j(),b.label,0,0),j.Ha(new D.G(h)),j.uu(g),j.Ey("top"),g=(0,D.Cq)((new D.G(b.labelStyle)).getWidth()),0<g&&D.$e.Qb(j,g,window.Infinity,this)||this.k(j),this.Oa=
j);(0,D.Fq)(this.zo(),b)}a.k(this);a=D.o;this.$u?(b=this.F())&&(a=new D.A(b.x,b.y,b.e-b.x,b.g-b.y)):(a=this.Na?this.Na.pE(this):D.o)&&this.G?a=(0,D.Bo)(a,this.G.pE(this)):!a&&this.G&&(a=this.G.pE(this));this.AJ=a;this.Ud("img");this.$m();this.u.ka().Ca(this,this)};
D.pq=function(a,b,c,d){var e=a.u.q()._contextHandler;if(e){var f=a.getData();c=e(a.sa(),a.$u,f,c,d);b=b(c);a.$u&&b!=a.$u&&(a.$u.namespaceURI===D.B.WN?(0,D.Gq)(a).removeChild(a.$u):a.removeChild(b),a.$u=D.o);b&&b.namespaceURI===D.B.WN?a.$u||(D.B.yd((0,D.Gq)(a),b),a.$u=b):b instanceof D.sj?a.$u||(a.k(b),a.$u=b):b&&a.u.xE("DvtDiagram: could not add custom node content for the node "+a.getId()+b,1)}else a.u.xE("DvtDiagram: could not add custom node content - context handler is undefined",1)};
D.Fq=function(a,b){var c=b.hoverInnerColor,d=b.hoverOuterColor,e=b.selectionColor,f=new D.hg(c,1,4);f.Gc=D.k;d=new D.hg(d,1,8);d.Gc=D.k;var g=new D.hg(e,1,2);g.Gc=D.k;var h=new D.hg(e,1,4);h.Gc=D.k;c=new D.hg(c,1,4);c.Gc=D.k;e=new D.hg(e,1,8);e.Gc=D.k;a.Pp(f,d).Rp(g,h).kr(c,e)};D.x=D.jq.prototype;D.x.fI=(0,D.ba)("FG");D.x.zo=function(){if(!this.FG&&this.AJ){var a=new D.Te(this.u.j(),this.AJ.x,this.AJ.y,this.AJ.e,this.AJ.g);(0,D.wi)(a);this.fI(a);this.Ma(a,0);(0,D.Fq)(a,this.getData());this.FG=a}return this.FG};
D.x.Ob=function(){var a=this.Ki();this.Al=D.k;this.u.q().hoverRenderer?(0,D.pq)(this,this.u.q().hoverRenderer,this.Ki(),a):this.ss(D.k)};D.x.Db=function(){var a=this.Ki();this.Al=D.p;this.u.q().hoverRenderer?(0,D.pq)(this,this.u.q().hoverRenderer,this.Ki(),a):this.ss(D.p)};D.x.ss=function(a){this.zo()&&(a?this.zo().Ob():this.zo().Db())};D.x.De=function(){var a=this.ga().q().tooltip;return a?(0,D.ip)(this.ga().j().ge(),a,this.vp()):this.Bc()};D.x.Bc=function(){return this.getData().shortDesc};
D.x.vp=function(){return{id:this.getId(),type:"node",label:this.getData().label}};D.x.fc=function(){var a=[];this.Aa()&&a.push((0,D.L)("DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.ok)(this.Bc(),a)};D.x.$m=function(){if(!(0,D.cf)()){var a=this.fc();a&&this.$b("label",a)}};
D.x.Ad=function(a){var b=D.o;if(32==a.keyCode&&a.ctrlKey)b=this;else if(a.altKey){var c=this.ga().kM(this.getId()),d;(d=this.ga().ka().Sf)&&d.d_&&(b=d.d_(this,a,c));b?b.rK=this:b=this}else a.type==D.kk?b=this:(b=(0,D.hq)(this.ga()),b=(0,D.Jm)(this,a,b));return b};D.x.Vd=function(){var a=this.Ki();this.Ib=D.k;this.u.q().focusRenderer?(0,D.pq)(this,this.u.q().focusRenderer,this.Ki(),a):this.kw(D.k)};
D.x.jc=function(){this.pc()&&(this.Ki(),this.Ib=D.p,this.u.q().focusRenderer?(0,D.pq)(this,this.u.q().focusRenderer,this.getData(),this.Ki()):this.kw(D.p))};D.x.kw=function(a){this.ss(a)};D.x.pc=(0,D.v)("Ib");D.x.Mc=function(){return this.getData().categories?this.getData().categories:[this.getId()]};D.x.Yba=function(){var a=this.ga().q().hiddenCategories;return a&&D.H.hu(a,this.Mc())?D.k:D.p};
D.x.gf=function(a,b){var c=new D.qn(this.j(),D.o,a.xa()),d=b.N(),e=b.M(),f=this.N(),g=this.M();d!=f&&(this.I(d),(0,D.T)(c.J,"typeNumber",this,this.N,this.I,f));e!=g&&(this.O(e),(0,D.T)(c.J,"typeNumber",this,this.M,this.O,g));b.G&&this.G&&((0,D.T)(c.J,"typeRectangle",this.G,this.G.Yt,this.G.eB,this.G.Yt()),this.G.eB(b.G.Yt()));b.Oa&&this.Oa&&(d=b.Oa.ta(),e=this.Oa.ta(),d.Xc(e)||(this.Oa.za(d),(0,D.T)(c.J,"typeMatrix",this.Oa,this.Oa.ta,this.Oa.za,e)));(0,D.Hq)(c,b.Na,this.Na);(0,D.Hq)(c,b.G,this.G);
a.add(c,1)};D.Hq=function(a,b,c){b&&c&&((0,D.T)(a.J,"typeFill",c,c.Rb,c.L,c.Rb()),c.L(b.Rb()))};D.jq.prototype.kh=function(a){this.ga().Vh.k(this);var b=this,c=new D.sn(this.j(),this,a.xa());(0,D.hl)(c,function(){b.getParent().removeChild(b);b.Q()});a.add(c,0)};D.jq.prototype.qg=function(a){this.B(0);a.add(new D.Vm(this.j(),this,a.xa()),2)};D.jq.prototype.Xi=function(){return this.getData()};D.jq.prototype.Ki=function(a){return{hovered:this.Al,selected:this.Da(),focused:this.Ib,zoom:a?a:this.ga().da.Cd()}};
D.rq=function(a){this.Init(a)};(0,D.da)("DvtDiagramAutomation",D.rq);D.z.l(D.rq,D.Dj,"DvtDiagramAutomation");D.rq.prototype.Init=(0,D.ba)("u");D.rq.prototype.ql=function(a){return(a=(0,D.Ej)(this.u.ka(),a))&&a instanceof D.jq?"node["+this.u.rB().indexOf(a.getId())+"]":a&&a instanceof D.kq?"link["+this.u.xI().indexOf(a.getId())+"]":D.o};
D.rq.prototype.If=function(a){if("tooltip"==a)return(0,D.bm)(this.u);var b=this.tG(a);a=b.component;var b=b.index,c=D.o;"node"==a?c=this.vh(b):"link"==a&&(c=(0,D.sq)(this,b));return c?c.sa():D.o};D.rq.prototype.getDomElementForSubId=D.rq.prototype.If;D.rq.prototype.tG=function(a){var b=a,c=-1,d=a.substring(0,a.indexOf("["));d&&(b="node"==d||"link"==d?d:D.o,c=(0,window.parseInt)(a.substring(a.indexOf("[")+1,a.indexOf("]"))));return{component:b,index:c}};D.rq.prototype.Oe=function(){return this.u.Oe()};
D.rq.prototype.getNodeCount=D.rq.prototype.Oe;D.rq.prototype.Ap=function(){return this.u.Ap()};D.rq.prototype.getLinkCount=D.rq.prototype.Ap;D.rq.prototype.Nb=function(a){if(a=this.vh(a)){var b={};b.id=a.getId();b.selected=a.Da();b.tooltip=a.Bc();b.label=a.getData().label;b.background=a.getData().backgroundStyle;b.icon=this.xP(a.zN());return b}return D.o};D.rq.prototype.getNode=D.rq.prototype.Nb;
D.rq.prototype.dM=function(a){if(a=(0,D.sq)(this,a)){var b={};b.id=a.getId();b.selected=a.Da();b.tooltip=a.Bc();b.label=a.getData().label;b.color=a.FA();b.width=a.Sv();b.style=a.qH();b.startNode=a.Zc();b.endNode=a.hc();b.startConnectorType=a.Wq();b.endConnectorType=a.yp();return b}return D.o};D.rq.prototype.getLink=D.rq.prototype.dM;D.rq.prototype.xP=function(a){if(a){var b={};b.shape=a instanceof D.dh?a.Pa():"none";a.Rb()&&(b.color=a.Rb().qb());return b}return D.o};
D.rq.prototype.vh=function(a){var b=this.u.rB();return 0<=a&&a<b.length?this.u.K(b[a]):D.o};D.sq=function(a,b){var c=a.u.xI();return 0<=b&&b<c.length?a.u.Mb(c[b]):D.o};

  return D;
});