/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.sO=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtNBox",D.sO);D.z.l(D.sO,D.sj,"DvtNBox");D.sO.newInstance=function(a,b,c){return new D.sO(a,b,c)};D.sO.getDefaults=function(a){return(0,D.tj)(new D.tO,a)};
D.sO.prototype.Init=function(a,b,c){D.sO.o.Init.call(this,a,b,c);this.rf=new D.tO;this.Ia=new D.uO(this);this.Ia.me(this);this.Hd=new D.ou(a);this.wl=new D.vO(this);(0,D.Oq)(this.Ia,this.Hd);(0,D.Jf)()||(0,D.xj)(this.Ia,this.xw(this.Ia));this.setId("nbox1000"+window.Math.floor(1E9*window.Math.random()));this.Gg=this.Ua=D.o;this.Cq=[];this.$U=D.k};
D.sO.prototype.vd=function(a){a||(a=(0,D.wO)(this));a?(this.D=this.rf.Vj(a),D.W.Mca(this),(0,D.Zk)()||(this.D[D.X.Qda]="none",this.D[D.X.Pda]="none")):this.D||(this.D=(0,D.zj)(this));this.ke=[];a=this.D[D.X.CU];this.Hb="single"==a?new D.$k("s"):"multiple"==a?new D.$k("m"):D.o;this.Ia.yu(this.Hb)};
D.sO.prototype.P=function(a,b,c){var d=D.xO.vaa(this),e=D.o;this.D&&"none"!==d&&(e={options:this.D,getOptions:(0,D.v)("options"),displayables:this.ke,getDisplayables:(0,D.v)("displayables"),id:this.getId(),getId:(0,D.v)("id")},e.q=e.getOptions,e.Yc=e.getDisplayables,e.getId=e.getId);this.dO();this.vd(a);!(0,window.isNaN)(b)&&!(0,window.isNaN)(c)&&(this.Ga=b,this.Ta=c);b=new D.D(this.j());this.k(b);D.yO.P(this,b,new D.A(0,0,this.Ga,this.Ta));c=[this];var f=D.W.eS(this);if(f&&f.sections){var g=D.W.ia(this,
f,"panelDrawer");g&&(c.push(g),g.Qa()&&(f=D.W.ia(this,f,"legend"),c.push(f)))}(0,D.Vl)(this.j(),c);a&&(D.W.Dm(this)&&D.W.au(this))&&(c=D.W.ia(this,D.W.Dm(this)),this.Ia.ws(c),this.Ia.Op(D.p));this.pA();this.Ua&&(this.eJ=D.k,this.Ua.stop());var f=D.xO.waa(this),g=D.xO.xa(this),h=new D.A(0,0,this.Ga,this.Ta);c=D.p;this.X?"none"!=d&&a&&((this.Ua=D.dl.qD(this.j(),d,this.X,b,h,g))?c=D.k:(this.mf=new D.D(this.j(),"DeleteContainer"),this.k(this.mf),d=new D.zO(this.j(),this.mf,e,this),(0,D.Tm)(d,[e],[this]),
this.Ua=d.Oq())):"none"!==f&&(this.Ua=D.dl.by(this.j(),f,b,h,g));this.Ua&&(this.qa(D.p),(0,D.hl)(this.Ua,this.zq,this),(0,D.Pi)()&&12<=(0,D.kj)()&&(0,D.hl)(this.Ua,function(){this.$U=D.p;this.P(a);this.$U=D.k},this),this.Ua.play());c?this.Og=this.X:this.X&&(this.removeChild(this.X),this.X.Q());this.X=b;this.Sn()};D.sO.prototype.render=D.sO.prototype.P;D.x=D.sO.prototype;D.x.dO=function(){this.Ia.Cc();this.Cq.length=0};
D.x.zq=function(){this.Og&&(this.removeChild(this.Og),this.Og.Q(),this.Og=D.o);this.mf&&(this.removeChild(this.mf),this.mf.Q());this.mf=D.o;this.eJ=D.p;this.Ua=D.o;this.qa(D.k)};D.x.xw=function(a){return new D.AO(a,this)};D.x.Wj=(0,D.v)("X");D.x.Yc=(0,D.v)("ke");D.x.pA=function(){var a=this.Ia.dd(),b=D.p;if(a){var c,b=a.pc();a.wD&&(c=a.wD());c&&b&&c.Vd();this.Ia.ws(c)}};D.x.ka=(0,D.v)("Ia");
D.x.Pd=function(a){var b=a.Pa(),c=(0,D.wO)(this);b==D.wl.Kw||b==D.wl.Sy?a=this.g9(a):"categoryRollOver"==b||"categoryRollOut"==b?a=this.h9(a):"selection"==b?a=this.i9(a):c._legend&&"dvtPanelDrawerEvent"==b&&(b="hide"==a.xj()?"undisclosed":"disclosed",a=new D.hr,(0,D.El)(a,D.X.oU,b),c[D.X.oU]=b,this.P(c));a&&this.dispatchEvent(a)};
D.x.g9=function(a){var b=(0,D.wO)(this),c=b[D.X.tE];c||(c=[]);var d=D.H.wa(c,a.Pk);a.Pa()==D.wl.Kw&&-1==d&&c.push(a.Pk);a.Pa()==D.wl.Sy&&-1!=d&&c.splice(d,1);0==c.length&&(c=D.o);a=new D.hr;(0,D.El)(a,D.X.tE,c);b[D.X.tE]=c;this.P(b);return a};D.x.h9=function(a){this.bA(a.categories);return a};
D.x.i9=function(a){var b=a.getSelection(),c=D.o;if(b){a={};for(c=0;c<b.length;c++)a[b[c]]=D.k;var b=this.Uq(),d=D.o;if(D.W.au(this))for(c=0;c<b.length;c++)if(b[c]instanceof D.BO){if(a[b[c].getId()]){a[b[c].getId()]=D.p;for(var e=b[c].getData().nodeIndices,f=0;f<e.length;f++){var g=D.W.Nb(this,e[f]);a[g[D.X.ID]]=D.k}}}else b[c]instanceof D.CO&&(d=b[c]);var b=[],c=[],h;for(h in a)a[h]&&(b.push(h),c.push(h));a=new D.Km(b)}D.W.SNa(this,c);d&&d.Ty();return a};D.x.ZD=function(a){this.Cq.push(a)};
D.x.Uq=(0,D.v)("Cq");D.x.getWidth=(0,D.v)("Ga");D.x.getHeight=(0,D.v)("Ta");D.x.mh=(0,D.v)("Hb");D.x.br=function(){return this.Hb?D.k:D.p};D.x.rd=function(a){return this.vG?this.vG[a]:D.o};D.x.gf=function(a,b){D.yO.gf(a,b,this)};D.wO=function(a){return D.pl.Y(a.q(),function(a){return 0!=a.indexOf("__")})};D.sO.prototype.ls=function(){return{}};D.sO.prototype.YI=function(a){return this.Hb?a[0]:D.o};
D.sO.prototype.RB=function(a){a.Da()||(this.Hb.Nm(a,D.p),this.Ia.Nv());a=[];for(var b={},c=this.Hb.getSelection(),d=0;d<c.length;d++){var e=c[d];if(e instanceof D.DO)e=e.getData()[D.X.ID],a.push(e),b[e]=D.k;else if(e instanceof D.BO){for(var f=e.getData().nodeIndices,g=0;g<f.length;g++){var h=D.W.Nb(this,f[g])[D.X.ID];a.push(h);b[h]=D.k}b[e.getData()[D.X.ID]]=D.k}}c=(0,D.Cl)(this.Hb);for(d=0;d<c.length;d++)if(e=c[d],!b[e])if((0,window.isNaN)(D.W.sH(this,e))){if(D.W.au(this)&&D.W.Qq(this,e)){f=D.W.Qq(this,
e).nodeIndices;for(g=0;g<f.length;g++)h=D.W.Nb(this,f[g])[D.X.ID],b[h]||(a.push(h),b[h]=D.k);b[e]=D.k}}else a.push(e),b[e]=D.k;return a};D.sO.prototype.QB=function(){return this.Hb.getSelection().slice(0)};D.EO=function(a,b,c){for(var d=D.W.Xj(a)*D.W.lh(a),e=0;e<d;e++){var f=D.W.ia(a,D.W.Zd(a,e));if(f.contains(b,c))return f}return D.o};D.sO.prototype.Hu=function(a){this.Cf&&(this.Cf.getParent().removeChild(this.Cf),this.Cf=D.o);a&&(this.Cf=a.Xca());return this.Cf};
D.sO.prototype.Gf=function(){this.Kk||(this.Kk=new D.FO(this));return this.Kk};D.sO.prototype.getAutomation=D.sO.prototype.Gf;D.sO.prototype.Hj=function(){return(0,D.L)("DvtUtilBundle","NBOX",D.W.lh(this)*D.W.Xj(this))};D.sO.prototype.Ge=function(a){this.D.highlightedCategories=D.pl.Y(a);this.bA(a)};D.sO.prototype.highlight=D.sO.prototype.Ge;
D.sO.prototype.bA=function(a){var b=(0,D.GO)(this),c=D.W.Xj(this)*D.W.lh(this);this.q().__highlightedMap=D.o;for(var d=D.yO.R4(this),e=0;e<c;e++){var f=D.W.Zd(this,e),g=D.W.ia(this,f);D.HO.M0(this,f,g,d,D.p)}d=D.W.aM(this);c={};if(d)for(var e=0;e<d.length;e++)c[d[e][D.X.ID]]=D.k;for(e=0;e<b.length;e++){if(d=a)if(d=0<a.length){a:{d=b[e];if(d instanceof D.DO){if(d.Mc()){d="all"==this.q()[D.X.l2]?D.H.yS(a,d.Mc()):D.H.hu(a,d.Mc());break a}}else if(d instanceof D.BO){d=d.getData();f=d.nodeIndices.length;
for(g=0;g<f;g++){var h=D.W.Nb(this,d.nodeIndices[g]);if(h[D.X.Au]&&("all"==this.q()[D.X.l2]?D.H.yS(a,h[D.X.Au]):D.H.hu(a,h[D.X.Au]))){d=D.k;break a}}}d=D.p}d=!d}d?b[e].B(D.xO.c_(this)):b[e].B(1);if(b[e]instanceof D.BO){f=0;d=b[e].getData();for(g=0;g<d.nodeIndices.length;g++)c[d.nodeIndices[g]]&&(f+=1);d.highlightedCount=f;f=D.xO.Bba(this,d)!=D.o||D.xO.QR(this,d)!=D.o;D.IO.roa(this,b[e].getData(),b[e],d.__scale,f,d.__gap)}}};
D.GO=function(a){for(var b=[],c=D.W.Oe(a),d=0;d<c;d++)b.push(D.W.Nb(a,d));d=D.W.uj(a);if(c=a.q().__groups)if(d==D.X.Zp)for(var e=D.W.Xj(a)*D.W.lh(a),d=0;d<e;d++){var f=c[d+""],g;for(g in f)b.push(f[g])}else for(g in c)b.push(c[g]);g=[];for(d=0;d<b.length;d++)(c=D.W.ia(a,b[d]))&&g.push(c);return g};
D.x=D.sO.prototype;D.x.zj=function(a,b,c){return this.Hd.zj(c)};D.x.yk=function(a,b){return this.Hd.yk(a,b)};D.x.$t=function(a,b){return this.Hd.$t(a,b)};D.x.xp=function(a,b){return this.Hd.xp(a,b)};D.x.Ov=function(a,b){return this.Hd.Ov(a,b)};D.x.Vv=function(a,b){return this.Hd.Vv(a,b)};D.x.$v=function(){this.Hd.$v()};D.x.es=function(){this.Hd.es()};
D.sO.prototype.ro=function(a,b,c){return this.wl.ro(a,b,c)};D.sO.prototype.ks=function(a,b){return this.wl.ks(a,b)};
D.X={};D.z.l(D.X,D.z,"DvtNBoxConstants");D.X.cj="column";D.X.nE="columns";D.X.m1="columnsTitle";D.X.nua="columnsTitleStyle";D.X.oua="columnLabelStyle";D.X.Ns="maximizedColumn";(0,D.da)("DvtNBoxConstants.MAXIMIZED_COLUMN",D.X.Ns);D.X.dj="row";D.X.e3="rows";D.X.f3="rowsTitle";D.X.cwa="rowsTitleStyle";D.X.dwa="rowLabelStyle";D.X.Os="maximizedRow";(0,D.da)("DvtNBoxConstants.MAXIMIZED_ROW",D.X.Os);D.X.JT="cell";D.X.l1="cells";D.X.mE="cellDefaults";D.X.rU="nodes";D.X.bk="nodeDefaults";D.X.Au="categories";
D.X.lU="icon";D.X.Eva="iconDefaults";D.X.Gfa="indicator";D.X.Ky="indicatorIcon";D.X.GN="indicatorIconDefaults";D.X.vE="indicatorColor";D.X.Sga="xPercentage";D.X.Xga="yPercentage";D.X.uga="selection";D.X.CU="selectionMode";D.X.kwa="selectionInfo";(0,D.da)("DvtNBoxConstants.SELECTION_INFO",D.X.kwa);D.X.BOa="hasSelectionListener";D.X.k2="highlightedCategories";D.X.l2="highlightMatch";D.X.tE="hiddenCategories";(0,D.da)("DvtNBoxConstants.HIDDEN_CATEGORIES",D.X.tE);D.X.COa="hoverBehavior";D.X.xN="groupCategory";
D.X.fva="groupAttributes";D.X.Jea="groupBehavior";D.X.Zp="withinCell";D.X.wI="acrossCells";D.X.Lva="otherColor";D.X.Mva="otherThreshold";D.X.Pda="animationOnDataChange";D.X.Qda="animationOnDisplay";D.X.mua="animationDuration";D.X.Aw="_drawer";(0,D.da)("DvtNBoxConstants.DRAWER",D.X.Aw);D.X.nU="_legend";D.X.oU="legendDisclosure";(0,D.da)("DvtNBoxConstants.LEGEND_DISCLOSURE",D.X.oU);D.X.ID="id";D.X.je="label";D.X.My="labelStyle";D.X.C2="labelHalign";D.X.Hw="secondaryLabel";D.X.jwa="secondaryLabelStyle";
D.X.mwa="shortDesc";D.X.o3="showCount";D.X.qwa="style";D.X.be="styleDefaults";D.X.Fy="borderColor";D.X.Sda="borderRadius";D.X.k1="borderWidth";D.X.bj="color";D.X.cq="pattern";D.X.FOa="opacity";D.X.HB="shape";D.X.Ry="source";D.X.Cu="height";D.X.Ss="width";
(0,D.Dg)("DvtNBoxBundle",{HIGHLIGHTED_COUNT:"{0}/{1}",COMMA_SEP_LIST:"{0}, {1}",OTHER:"Other",LEGEND:"Legend",GROUP_NODE:"Group",ADDITIONAL_DATA:"Additional Data",SIZE:"Size"});
D.tO=function(){this.Init({skyros:D.VO,alta:D.WO})};D.z.l(D.tO,D.Nj,"DvtNBoxDefaults");
D.VO={skin:"alta",selectionMode:"multiple",animationOnDataChange:"none",animationOnDisplay:"none",cellMaximize:"on",cellContent:"auto",legendDisplay:"auto",legendDisclosure:"disclosed",groupBehavior:"withinCell",otherColor:"#636363",otherThreshold:0,hoverBehavior:"none",highlightMatch:"all",highlightedCategories:[],touchResponse:"auto",styleDefaults:{animationDuration:500,hoverBehaviorDelay:200,columnLabelStyle:new D.G('font-size: 12px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),rowLabelStyle:new D.G('font-size: 12px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),
columnsTitleStyle:new D.G('font-size: 14px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),rowsTitleStyle:new D.G('font-size: 14px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),cellDefaults:{style:new D.G("background-color:#e9e9e9"),maximizedStyle:new D.G("background-color:#dddddd"),minimizedStyle:new D.G("background-color:#e9e9e9"),labelStyle:new D.G('font-size: 14px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:bold'),
countLabelStyle:new D.G('font-size: 14px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),bodyCountLabelStyle:new D.G('color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),dropTargetStyle:new D.G("background-color:rgba(217, 244, 250, .75);border-color:#ccf6ff"),showCount:"auto",showMaximize:"on"},__scrollbar:{scrollbarBackground:"linear-gradient(bottom, #dce2e7 0%, #f8f8f8 8%)",scrollbarBorderColor:"#dce2e7",scrollbarHandleColor:"#abb0b4",scrollbarHandleHoverColor:"#333333",
scrollbarHandleActiveColor:"#333333"},__drawerDefaults:{background:"#e9e9e9",borderColor:"#bcc7d2",borderRadius:1,headerBackground:"linear-gradient(to bottom, #f5f5f5 0%, #f0f0f0 100%)",labelStyle:new D.G('font-size: 14px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:bold'),countLabelStyle:new D.G('font-size: 14px; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif;font-weight:bold'),countBorderRadius:1},nodeDefaults:{color:"#FFFFFF",labelStyle:new D.G('font-size: 12px; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),
secondaryLabelStyle:new D.G('font-size: 11px; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif'),alphaFade:0.2,borderRadius:1,hoverColor:"#FFFFFF",selectionColor:"#000000",iconDefaults:{preferredSize:19,preferredSizeTouch:34,shapePaddingRatio:0.15,sourcePaddingRatio:0,opacity:1,pattern:"none",borderWidth:1,borderRadius:0,shape:"circle"},indicatorIconDefaults:{width:10,height:10,opacity:1,pattern:"none",borderWidth:1,borderRadius:0,shape:"circle"}},__legendDefaults:{sectionStyle:'font-size: 12px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif; font-weight:bold',
itemStyle:'font-size: 12px; color: #252525; font-family:"Helvetica Neue", Helvetica, Arial, sans-serif',markerColor:"#808080"},__categoryNodeDefaults:{labelStyle:new D.G('font-family:"Helvetica Neue", Helvetica, Arial, sans-serif')}},__layout:{componentGap:8,titleGap:4,titleComponentGap:4,nodeLabelOnlyStartLabelGap:5,nodeStartLabelGap:3,nodeEndLabelGap:5,nodeSingleLabelGap:2,nodeDualLabelGap:2,nodeInterLabelGap:0,nodeIndicatorGap:3,nodeSwatchSize:10,categoryNodeLabelGap:5,minimumCellSize:34,cellGap:3,
gridGap:6,cellStartGap:6,cellEndGap:6,cellTopGap:6,cellBottomGap:6,cellLabelGap:6,cellCloseGap:6,countLabelGap:10,markerGap:3,minimumLabelWidth:55,maximumLabelWidth:148,drawerButtonGap:6,drawerCountHorizontalGap:5,drawerCountVerticalGap:3,drawerStartGap:6,drawerLabelGap:6,drawerHeaderHeight:31,legendBottomGap:10}};D.WO={};
D.LO=(0,D.t)();D.z.l(D.LO,D.D,"DvtNBoxCell");D.LO.newInstance=function(a,b){var c=new D.LO;c.Init(a,b);return c};D.x=D.LO.prototype;D.x.Init=function(a,b){var c=D.W.cg(a,b[D.X.dj]),d=D.W.vo(a,b[D.X.cj]);D.LO.o.Init.call(this,a.j(),D.o,"c:"+c+","+d);this.$=a;this.oa=b;this.aQa=D.p};D.x.getData=(0,D.v)("oa");D.x.P=function(a,b,c,d){this.b5=c;a.k(this);D.W.Qe(this.$,this.oa,this);D.HO.P(this.$,this.oa,this,b,c,d);this.$.Ia.Ca(this,this)};D.x.Wj=(0,D.v)("d5");D.x.jda=(0,D.ba)("d5");
D.x.gf=function(a,b){D.HO.gf(a,b,this)};D.x.kh=function(a){D.HO.kh(a,this)};D.x.qg=function(a){D.HO.qg(a,this)};D.x.Eh=function(){return D.W.Fsa(this.$)};
D.x.os=function(){if(this.Eh()){var a=D.W.Cp(this.$),b=D.W.Bp(this.$),c=(0,D.wO)(this.$),d=new D.hr;c[D.X.Aw]=D.o;(0,D.El)(d,D.X.Aw,D.o);a==this.oa[D.X.dj]&&b==this.oa[D.X.cj]?(c[D.X.Os]=D.o,(0,D.El)(d,D.X.Os,D.o),c[D.X.Ns]=D.o,(0,D.El)(d,D.X.Ns,D.o)):(c[D.X.Os]=this.oa[D.X.dj],(0,D.El)(d,D.X.Os,this.oa[D.X.dj]),c[D.X.Ns]=this.oa[D.X.cj],(0,D.El)(d,D.X.Ns,this.oa[D.X.cj]));var e;(a=this.$.Ia.dd())?a instanceof D.DO?e=this.$f()!=D.W.$f(this.$,a.getData()):a instanceof D.OO?e=this!=a.OV:a instanceof
D.LO?e=this.$f()!=a.$f():a instanceof D.BO&&(e=this.$f()!=a.getData().cell):(0,D.Bj)(this.$.Ia,this);e&&((0,D.Bj)(this.$.Ia,this),this.$.Ia.Op(D.p));this.$.Pd(d);this.$.P(c)}};D.x.contains=function(a,b){var c=D.W.ia(this.$,this.oa,"background"),d=this.N()+c.ja(),e=this.M()+c.na(),f=d+c.getWidth(),c=e+c.getHeight();return d<=a&&a<=f&&e<=b&&b<=c};D.x.Xca=function(){return D.HO.Xca(this.$,this)};
D.x.ak=function(a){var b=D.W.Cp(this.$),c=D.W.Bp(this.$),b=b==this.oa[D.X.dj]&&c==this.oa[D.X.cj]?D.k:D.p;(!b&&13==a.keyCode||b&&27==a.keyCode)&&this.os()};D.x.fc=function(){var a=this.$f(),b=[];D.W.BM(this.$,a)?b.push((0,D.L)("DvtUtilBundle","STATE_MAXIMIZED")):D.W.NA(this.$,a)&&b.push((0,D.L)("DvtUtilBundle","STATE_MINIMIZED"));b.push([(0,D.L)("DvtNBoxBundle","SIZE"),this.Oe()]);return(0,D.ok)(this.getData().shortDesc,b)};D.x.Ee=function(){return(0,D.SO)(this)};D.x.yj=function(){return this.sa()};
D.x.Vd=function(){this.Ib=D.k;D.W.ia(this.$,this.getData(),"focusEffect").show()};D.x.jc=function(){this.Ib=D.p;D.W.ia(this.$,this.getData(),"focusEffect").Co()};D.x.pc=(0,D.v)("Ib");
D.x.Ad=function(a){var b=D.o;if(this.$.Ia.Sf.tg(a)){if(219==a.keyCode){var b=D.o,b=D.W.Cp(this.$),c=D.W.Bp(this.$),d=D.W.Dm(this.$);if(d&&b==this.getData()[D.X.dj]&&c==this.getData()[D.X.cj])b=D.W.ia(this.$,d);else if(b=this.Wj(),b.sba&&(b=b.X),0<b.Ja()&&(b.ha(0)instanceof D.DO||b.ha(0)instanceof D.OO))b=D.W.e_(this.$,b);else{c=[];for(d=0;d<b.Ja();d++){var e=b.ha(d);e instanceof D.BO&&c.push(e)}b=(0,D.TO)(D.o,a,c)}a=b}else{b=[];c=D.W.Xj(this.$)*D.W.lh(this.$);for(d=0;d<c;d++)b.push(D.W.ia(this.$,
D.W.Zd(this.$,d)));a=(0,D.lk)(this,a,b)}b=a}return b};D.x.$f=function(){return D.W.Rqa(this.$,this.getData()[D.X.dj],this.getData()[D.X.cj])};D.x.Nc=function(){var a=this.getData()[D.X.je];return a?a:D.o};D.x.Oe=function(){this.b5||(this.b5=D.yO.R4(this.$));var a=this.$f();return this.b5.total[a]};D.x.Nb=function(a){var b=this.$.q()[D.X.rU];if(b)for(var c=0,d=0;d<b.length;d++)if(this.getData()[D.X.dj]==b[d][D.X.dj]&&this.getData()[D.X.cj]==b[d][D.X.cj]&&!D.W.HH(this.$,b[d])){if(a==c)return b[d];c++}return D.o};
D.x.ia=function(){return this};D.x.wD=function(){return D.W.uj(this.$)!=D.X.wI||!this.$.q().__groups?D.W.ia(this.$,D.W.Zd(this.$,D.W.$f(this.$,this.getData()))):D.o};
D.DO=(0,D.t)();D.z.l(D.DO,D.D,"DvtNBoxNode");D.DO.newInstance=function(a,b){var c=new D.DO;c.Init(a,b);return c};D.x=D.DO.prototype;D.x.Init=function(a,b){D.DO.o.Init.call(this,a.j(),D.o,b[D.X.ID]);this.$=a;this.oa=b;this.$.ZD(this);var c=this.$.q()[D.X.CU];("single"==c||"multiple"==c||this.Ce())&&this.setCursor("pointer");this.Vr=1};D.x.getData=(0,D.v)("oa");D.x.Ce=function(){return this.oa.action};
D.x.P=function(a,b){D.ZO.P(this.$,this.oa,this,b);a.k(this);D.W.Qe(this.$,this.oa,this);this.$.Ia.Ca(this,this)};D.x.Aa=(0,D.ca)(D.k);D.x.Da=function(){return this.zo().Da()};D.x.jb=function(a){this.zo().jb(a);this.Ty()};D.x.Ob=function(){this.zo().Ob()};D.x.Db=function(){this.zo().Db()};D.x.fI=(0,D.ba)("FG");D.x.zo=(0,D.v)("FG");
D.x.De=function(){var a=this.$.q().tooltip;if(a){var b={id:this.oa.id,label:this.oa.label,secondaryLabel:this.oa.secondaryLabel,row:this.oa.row,column:this.oa.column,color:D.xO.rH(this.$,this.oa),indicatorColor:D.xO.tH(this.$,this.oa)};return(0,D.ip)(this.$.j().ge(),a,b)}return this.Bc()};D.x.Bc=function(){return this.oa[D.X.mwa]};D.x.vi=function(){return D.xO.rH(this.$,this.oa)};D.x.Ota=function(a){this.Vr=a;this.B(this.fa())};D.x.B=function(a){D.DO.o.B.call(this,window.Math.min(a,this.Vr))};
D.x.gf=function(a,b){D.ZO.gf(a,b,this)};D.x.kh=function(a){D.ZO.kh(a,this)};D.x.qg=function(a){D.ZO.qg(a,this)};D.x.Eh=(0,D.ca)(D.k);D.x.os=function(){(0,D.$O)(this).os()};D.x.rd=function(){if(!this.pd){this.pd=[];var a=this.oa.showPopupBehaviors;if(a)for(var b=0;b<a.length;b++)this.pd.push(new D.Gi(a[b].popupId,a[b].triggerType,a[b].alignId,a[b].align))}return this.pd};
D.x.uH=function(a){if(a&&a.XL()){a=D.yO.wi(this);var b=D.W.ia(this.$,this.oa,"background");return new D.A(a.qc+b.ja(),a.oc+b.na(),b.getWidth(),b.getHeight())}return D.o};D.x.zj=function(a){return this.$.YI(a)};D.x.yk=function(){return this.$.RB(this)};D.x.Zt=function(){return this.$.QB()};D.$O=function(a){var b=D.W.Dm(a.$);b||(b=D.W.$f(a.$,a.oa),b=D.W.Zd(a.$,b));return a=D.W.ia(a.$,b)};D.x=D.DO.prototype;D.x.Ty=function(){if(!(0,D.cf)()){var a=this.fc();a&&this.$b(D.X.je,a)}};
D.x.fc=function(){return D.W.Z$(this.$,this,this.Bc(),this.Da())};D.x.Mc=function(){return this.getData()[D.X.Au]?this.getData()[D.X.Au]:[]};D.x.Ee=function(){return(0,D.SO)(this)};D.x.yj=function(){return this.sa()};D.x.Vd=function(){this.Ib=D.k;this.Ob();var a=D.W.t_(this.$,this);a&&a.scrollIntoView(this)};D.x.jc=function(){this.Ib=D.p;this.Db()};D.x.pc=(0,D.v)("Ib");
D.x.Ad=function(a){var b=D.o;if(32==a.keyCode&&a.ctrlKey)return this;this.$.Ia.Sf.tg(a)?b=221==a.keyCode?(0,D.$O)(this):219==a.keyCode?this:D.W.Era(this.$,this,a):a.type==D.kk&&(b=this);return b};D.x.ak=function(a){if(D.W.Dm(this.$)&&27==a.keyCode)this.os();else{var b=D.W.Cp(this.$),c=D.W.Bp(this.$),b=b==this.oa[D.X.dj]&&c==this.oa[D.X.cj]?D.k:D.p;(!b&&13==a.keyCode||b&&27==a.keyCode)&&this.os()}};D.x.ia=function(){return this};
D.x.wD=function(){var a=D.W.Nb(this.$,D.W.sH(this.$,this.getData()[D.X.ID]));if(a){var b=D.W.ia(this.$,a);if(b)return b;a=D.W.Zd(this.$,D.W.$f(this.$,a));a=D.W.ia(this.$,a);b=D.W.sra(this.$,a.Wj());if(b instanceof D.OO)return b;a:{for(b=this;b&&b.getParent;)if(b=b.getParent(),b instanceof D.CO)break a;b=D.o}return b?b.wD():a.wD()}return D.o};
D.OO=(0,D.t)();D.z.l(D.OO,D.D,"DvtNBoxNodeOverflow");D.OO.newInstance=function(a,b){var c=new D.OO;c.Init(a,b);return c};D.x=D.OO.prototype;D.x.Init=function(a,b){D.OO.o.Init.call(this,a.j());this.$=a;this.OV=b;this.Td};
D.x.P=function(a,b,c){var d=this.$.q(),e=d._resources.overflow_ena.width,f=d._resources.overflow_ena.height,g=1;if(b<e||c<f)g=window.Math.min(b/e,c/f);var e=g*e,f=g*f,g=(b-e)/2,h=(c-f)/2,j=this.$.j(),l=new D.Te(j,0,0,b,c),m=new D.Te(j,0,0,b,c),n=new D.Te(j,0,0,b,c),q=new D.Te(j,0,0,b,c);(0,D.wi)(l);(0,D.wi)(m);(0,D.wi)(n);(0,D.wi)(q);var r=new D.D(j),s=new D.D(j),u=new D.D(j),w=new D.D(j);r.k(l);s.k(m);u.k(n);w.k(q);r.k(new D.Ue(j,d._resources.overflow_ena.src,g,h,e,f));s.k(new D.Ue(j,d._resources.overflow_ovr.src,
g,h,e,f));u.k(new D.Ue(j,d._resources.overflow_dwn.src,g,h,e,f));w.k(new D.Ue(j,d._resources.overflow_dis.src,g,h,e,f));this.Td=new D.Oe(j,r,s,u,w,D.o,this.Je,this);D.W.Fsa(this.$)||((0,D.Qe)(this.Td,D.p),(0,D.Ne)(this.Td));this.k(this.Td);b=new D.Bg(this.$.j(),this,new D.A(-1,-1,b+2,c+2));D.W.Qe(this.$,this,b,"focusEffect");a.k(this);this.Yy();this.$.Ia.Ca(this,this)};D.x.Je=function(a){(0,D.hi)(a);this.OV.os(D.k)};D.x.ak=function(a){13==a.keyCode&&this.OV.os()};
D.x.Yy=function(){this.Ud("button");if(!(0,D.cf)()){var a=this.fc();a&&this.$b(D.X.je,a)}};D.x.De=function(){return(0,D.L)("DvtNBoxBundle","ADDITIONAL_DATA")};D.x.fc=function(){return this.De()};D.x.Ee=function(){return(0,D.SO)(this)};D.x.yj=function(){return this.sa()};D.x.Vd=function(){this.Ib=D.k;D.W.ia(this.$,this,"focusEffect").show()};D.x.jc=function(){this.Ib=D.p;D.W.ia(this.$,this,"focusEffect").Co()};D.x.pc=(0,D.v)("Ib");
D.x.Ad=function(a){var b=D.o;this.$.Ia.Sf.tg(a)&&(b=221==a.keyCode?this.OV:D.W.Era(this.$,this,a));return b};D.x.ia=function(){return this};D.x.wD=function(){var a=D.W.Nb(this.$,D.W.sH(this.$,this.__prev[D.X.ID])).__next;return D.W.ia(this.$,a)};
D.BO=(0,D.t)();D.z.l(D.BO,D.D,"DvtNBoxCategoryNode");D.BO.newInstance=function(a,b){var c=new D.BO;c.Init(a,b);return c};D.x=D.BO.prototype;D.x.Init=function(a,b){D.BO.o.Init.call(this,a.j(),D.o,(0,window.isNaN)(b[D.X.JT])?b[D.X.ID]:b[D.X.JT]+":"+b[D.X.ID]);this.$=a;this.oa=b;this.$.ZD(this);"multiple"==this.$.q()[D.X.CU]&&this.setCursor("pointer");this.Vr=1};D.x.getData=(0,D.v)("oa");D.x.P=function(a,b,c){D.IO.P(this.$,this.oa,this,b,c);a.k(this);D.W.Qe(this.$,this.oa,this);this.$.Ia.Ca(this,this)};
D.x.Aa=function(){return"multiple"==this.$.q()[D.X.CU]};D.x.Da=function(){return this.zo().Da()};D.x.jb=function(a){this.zo().jb(a);this.Ty()};D.x.Ob=function(){this.zo().Ob()};D.x.Db=function(){this.zo().Db()};D.x.fI=(0,D.ba)("FG");D.x.zo=(0,D.v)("FG");D.x.Nc=function(){for(var a=D.W.Pqa(this.$,this.oa);1<a.length;){var b=(0,D.L)("DvtNBoxBundle","COMMA_SEP_LIST",[a[0],a[1]]);a.splice(0,2,b)}return a[0]};
D.x.De=function(){var a=this.$.q().tooltip;if(a){var b={id:this.oa.id,color:D.xO.dH(this.$,this.oa),indicatorColor:D.xO.QR(this.$,this.oa),size:this.oa.nodeIndices.length};"withinCell"==D.W.uj(this.$)&&(b.row=D.W.Zd(this.$,this.oa.cell).row,b.column=D.W.Zd(this.$,this.oa.cell).column);return(0,D.ip)(this.$.j().ge(),a,b)}return this.Bc()+"\n"+(0,D.L)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.L)("DvtNBoxBundle","SIZE"),this.oa.nodeIndices.length])};D.x.Bc=function(){return D.W.Pqa(this.$,this.oa).join("\n")};
D.x.vi=function(){return D.xO.dH(this.$,this.oa)};D.x.Ota=function(a){this.Vr=a;this.B(this.fa())};D.x.B=function(a){D.BO.o.B.call(this,window.Math.min(a,this.Vr))};D.x.Eh=(0,D.ca)(D.k);D.x.os=function(){var a=(0,D.wO)(this.$);a[D.X.Aw]={id:this.getId()};var b=new D.hr;(0,D.El)(b,D.X.Aw,this.getId());this.$.Pd(b);this.$.P(a)};D.x.gf=function(a,b){D.IO.gf(a,b,this)};D.x.kh=function(a){D.IO.kh(a,this)};D.x.qg=function(a){D.IO.qg(a,this)};D.x.zj=function(a){return this.$.YI(a)};D.x.yk=function(){return this.$.RB(this)};
D.x.Zt=function(){return this.$.QB()};D.x.ak=function(a){if(13==a.keyCode)this.os();else if(27==a.keyCode&&D.W.uj(this.$)==D.X.Zp){var b=D.W.Zd(this.$,this.oa.tQa);D.W.ia(this.$,b).ak(a)}};D.x.Ty=function(){if(!(0,D.cf)()){var a=this.fc();a&&this.$b(D.X.je,a)}};D.x.fc=function(){return D.W.Z$(this.$,this,this.Bc(),this.Da())};
D.x.Mc=function(){var a=this.getData()[D.X.Au];if(!a){for(var b=function(a,b){return a.filter(function(a){return-1<b.indexOf(a)})},c=this.getData().nodeIndices,a=D.o,d=0;d<c.length;d++){var e=D.W.Nb(this.$,c[d])[D.X.Au];if(!e){a=[];break}a=a==D.o?e:b(a,e)}this.getData()[D.X.Au]=a}return a};D.BO.baa=function(a,b){var c=a.nodeIndices.length,d=b.nodeIndices.length;return c==d?0:c<d?1:-1};D.x=D.BO.prototype;D.x.Ee=function(){return(0,D.SO)(this)};D.x.yj=function(){return this.sa()};
D.x.Vd=function(){this.Ib=D.k;this.Ob()};D.x.jc=function(){this.Ib=D.p;this.Db()};D.x.pc=(0,D.v)("Ib");
D.x.Ad=function(a){var b=D.o;if(32==a.keyCode&&a.ctrlKey)return this;if(221==a.keyCode&&D.W.uj(this.$)==D.X.Zp)a=D.W.Zd(this.$,this.getData()[D.X.JT]),b=D.W.ia(this.$,a);else if(221==a.keyCode||219==a.keyCode)b=this;else if(this.$.Ia.Sf.tg(a))if(D.W.uj(this.$)==D.X.wI){var b=this.$.q().__groups,c=[],d;for(d in b){var e=D.W.ia(this.$,b[d]);e&&c.push(e)}b=(0,D.TO)(this,a,c)}else{d=this.getParent();b=[];for(c=0;c<d.Ja();c++)d.ha(c)instanceof D.BO&&b.push(d.ha(c));b=(0,D.TO)(this,a,b)}else a.type==D.kk&&
(b=this);return b};D.x.ia=function(){return this};D.x.wD=function(){var a=D.W.Dm(this.$);return a||D.W.au(this.$)&&(a=D.W.Qq(this.$,this.getId()))?D.W.ia(this.$,a):D.o};
D.UO=function(a,b){D.UO.o.constructor.call(this,a,b);this.$=b};D.z.l(D.UO,D.uq,"DvtNBoxCategoryRolloverHandler");D.UO.prototype.g2=function(a){return D.z.xf(this,function(){this.oJ=D.k;this.$.Pd(a);this.lb&&this.lb.call(this.ra,a,this.qL)})};D.UO.prototype.f2=function(a){return D.z.xf(this,function(){(0,D.vq)(this);this.$.Pd(a);this.lb&&this.lb.call(this.ra,a,this.qL)})};
D.CO=(0,D.t)();D.z.l(D.CO,D.D,"DvtNBoxDrawer");D.CO.newInstance=function(a,b){var c=new D.CO;c.Init(a,b);return c};D.x=D.CO.prototype;D.x.Init=function(a,b){D.CO.o.Init.call(this,a.j(),D.o,b.id+"_d");this.$=a;this.oa=b;this.$.ZD(this)};D.x.getData=(0,D.v)("oa");D.x.P=function(a,b){a.k(this);D.W.Qe(this.$,this.oa,this);D.XO.P(this.$,this.oa,this,b);this.$.Ia.Ca(this,this)};D.x.Wj=(0,D.v)("d5");D.x.jda=(0,D.ba)("d5");D.x.Eh=(0,D.ca)(D.k);D.x.os=function(){this.$$()};
D.x.$$=function(){var a=(0,D.wO)(this.$);a[D.X.Aw]=D.o;var b=new D.hr;(0,D.El)(b,D.X.Aw,D.o);this.$.Pd(b);this.$.P(a)};D.x.gf=function(a,b){D.XO.gf(a,b,this)};D.x.kh=function(a){D.XO.kh(a,this)};D.x.qg=function(a){D.XO.qg(a,this)};D.x.ak=function(a){27==a.keyCode&&this.$$()};D.x.Ty=function(){if(!(0,D.cf)()){var a=this.fc();a&&((0,D.Jf)()?D.W.ia(this.$,this.getData(),"background"):this).$b("label",a)}};
D.x.fc=function(){var a=D.W.ia(this.$,D.W.Qq(this.$,this.getData().id)),b=D.W.gMa(this.$,a);return D.W.Z$(this.$,this,a.Bc(),b)};D.x.Ee=function(){return(0,D.SO)(this)};D.x.yj=function(){return this.sa()};D.x.Vd=function(){this.Ib=D.k;D.W.ia(this.$,this.getData(),"focusEffect").show()};D.x.jc=function(){this.Ib=D.p;D.W.ia(this.$,this.getData(),"focusEffect").Co()};D.x.pc=(0,D.v)("Ib");
D.x.Ad=function(a){var b=D.o;this.$.Ia.Sf.tg(a)&&(219==a.keyCode?(a=this.Wj(),a.sba&&(a=a.X),b=D.W.e_(this.$,a)):221==a.keyCode&&(a=D.W.gM(this.$),b=D.W.ia(this.$,D.W.Zd(this.$,a))));return b};D.x.ia=function(){return this};D.x.wD=function(){if(this.$.q()._drawer)return this;var a=D.W.Qq(this.$,this.getData()[D.X.ID]);return a?D.W.ia(this.$,a):D.o};
D.zO=function(a,b,c,d){this.Init(a,b,c,d)};D.z.l(D.zO,D.Sm,"DvtNBoxDataAnimationHandler");D.zO.prototype.Init=function(a,b,c,d){D.zO.o.Init.call(this,a,b);this.PC=c;this.yq=d};D.zO.prototype.xa=function(){return D.xO.xa(this.PC)};
D.vO=(0,D.ba)("H");D.z.l(D.vO,D.qu,"DvtNBoxDropTarget");D.vO.prototype.ro=function(a,b,c){if(a=(0,D.EO)(this.H,a,b))a!=this.uF&&(this.H.Hu(a),this.uF=a);else return this.H.Hu(D.o),D.o;return c[0]};D.vO.prototype.ks=function(a,b){var c=(0,D.EO)(this.H,a,b);return c?(c=c.getData(),{fT:c[D.X.dj],vQa:c[D.X.cj]}):D.o};
D.uO=function(a){this.Init(a.j(),a.Pd,a);this.$=a};D.z.l(D.uO,D.Pj,"DvtNBoxEventManager");D.x=D.uO.prototype;D.x.II=function(a){a=(0,D.Ej)(this,a.target);this.wG(a)};D.x.Ny=function(a){(0,D.YO)(this,(0,D.sm)(this,a))};D.x.wB=function(a){(0,D.YO)(this,(0,D.sm)(this,a))};D.x.EN=function(a){a=(0,D.Ej)(this,a.target);this.wG(a)};D.x.qr=function(a){a=(0,D.Ej)(this,a.target);this.wG(a)};D.YO=function(a,b){var c=(0,D.Ej)(a,b);c&&(c.Eh&&c.Eh()&&c.os)&&c.os()};D.x=D.uO.prototype;
D.x.Kh=function(a){var b=D.p,c=a.keyCode,d=this.dd();if(13==c||27==c)d&&d.ak&&d.ak(a);else if(32==a.keyCode&&a.ctrlKey){if(d instanceof D.BO||d instanceof D.DO)b=D.uO.o.Kh.call(this,a)}else b=D.uO.o.Kh.call(this,a);return b};
D.x.fm=function(a,b,c){a=this.$.q();"dim"==a.hoverBehavior&&(b=b.Mc?b.Mc():[],a.highlightedCategories=c?b.slice():D.o,c=new D.zm(c?"categoryRollOver":"categoryRollOut",a.highlightedCategories),b=(0,D.hp)(a.styleDefaults.hoverBehaviorDelay),this.GB.Pd(c,(0,D.GO)(this.$),b,"any"==a.highlightMatch))};D.x.w1=function(a,b){return new D.UO(a,b)};D.x.wG=function(a){a&&(a.Ce&&a.Ce())&&this.Xg(new D.Sj("action",a.Ce(),a.getId()))};
D.x.Bu=function(){var a=this.$.q(),b=D.W.Dm(this.$),c=D.W.Zd(this.$,D.W.gM(this.$));return b&&(0,D.fE)(D.W.ia(this.$,b).Wj())||c&&(0,D.fE)(D.W.ia(this.$,c).Wj())?"touchHold":"touchStart"===a.touchResponse?"touchStart":"auto"};
D.AO=function(a,b){this.Init(a,b)};D.z.l(D.AO,D.jk,"DvtNBoxKeyboardHandler");D.AO.prototype.Init=function(a,b){D.AO.o.Init.call(this,a);this.$=b};
D.AO.prototype.Fh=function(a){if(9==a.keyCode){var b=this.ea.dd(),c=D.o;(0,D.hi)(a);if(b)c=b;else{if(b=D.W.Dm(this.$))c=D.W.ia(this.$,b);else if(D.W.uj(this.$)==D.X.wI&&(b=this.$.q().__groups)){var c=[],d;for(d in b){var e=D.W.ia(this.$,b[d]);e&&c.push(e)}c=(0,D.TO)(D.o,a,c)}c||(a=D.W.lh(this.$)*(D.W.Xj(this.$)-1),c=D.W.ia(this.$,D.W.Zd(this.$,a)))}return c}return D.AO.o.Fh.call(this,a)};D.AO.prototype.qy=function(a){return 9==a.keyCode?D.p:this.tg(a)&&!a.ctrlKey};
D.AO.prototype.ar=function(a){return 32==a.keyCode&&a.ctrlKey};D.SO=function(a){var b=a.F(),c=(0,D.df)(a,new D.F(b.x,b.y));a=(0,D.df)(a,new D.F(b.x+b.e,b.y+b.g));return new D.A(c.x,c.y,a.x-c.x,a.y-c.y)};D.AO.prototype.tg=function(a){var b=D.p;switch(a.keyCode){case 219:case 221:b=D.k;break;default:b=D.AO.o.tg.call(this,a)}return b};
D.TO=function(a,b,c){if(!c||0>=c.length)return D.o;c[0]instanceof D.BO&&c.sort(function(a,b){return D.BO.baa(a.getData(),b.getData())});if(a==D.o)return c[0];var d=a;b=39==b.keyCode||40==b.keyCode?D.k:D.p;for(var e=c.length,f=0;f<e;f++)if(c[f]===a){d=c[b?f+1<e?f+1:f:0<=f-1?f-1:f];break}return d};
D.FO=function(a){this.Init(a)};(0,D.da)("DvtNBoxAutomation",D.FO);D.z.l(D.FO,D.Dj,"DvtNBoxAutomation");D.FO.prototype.Init=(0,D.ba)("Ae");
D.FO.prototype.ql=function(a){for(var b=(0,D.JO)(a,"DvtNBoxCell"),c=(0,D.JO)(a,"DvtNBoxDrawer");a&&!(a instanceof D.sO);){var d=this.ci(),e,f;if(a instanceof D.DO)return a=D.W.sH(d,a.getData().id),e=(0,D.KO)([a]),e="node"+e,this.eh(e,f);if(b){e=b.getData().row;var g=b.getData().column;e=(0,D.KO)([e,g]);e="cell"+e;if(a instanceof D.LO)return this.eh(e,f);if(a instanceof D.Oe){if((0,D.JO)(a,"DvtNBoxNodeOverflow"))return f="overflow",this.eh(e,f);if(a==D.W.ia(d,b.getData(),"closeButton"))return f="closeButton",
this.eh(e,f)}if(a instanceof D.BO)return b=a.getData().id,f="groupNode",f=D.W.Nb(d,a.getData().nodeIndices[0]).groupCategory?f+(0,D.KO)([b]):f+(0,D.MO)(b.split(";")),this.eh(e,f)}if(c){e="dialog";if(a instanceof D.CO)return this.eh(e,f);if(a instanceof D.Oe)return f="closeButton",this.eh(e,f)}if(a instanceof D.BO)return b=a.getData().id,e="groupNode",e=D.W.Nb(d,a.getData().nodeIndices[0]).groupCategory?e+(0,D.KO)([b]):e+(0,D.MO)(b.split(";")),this.eh(e,f);a=a.getParent()}return D.o};
D.FO.prototype.eh=function(a,b){var c=a;b&&(c+="#"+b);return c};
D.FO.prototype.If=function(a){var b=this.ci();if("tooltip"==a)return(0,D.bm)(b);a=this.tG(a);var c=a.component,d=a.action,e=D.o,f=D.o;a=D.o;0===c.lastIndexOf("node",0)&&(e=(0,D.NO)(c,D.k),f=D.W.Nb(b,e[0]),a=D.W.ia(b,f));if(0===c.lastIndexOf("cell",0)){var g=e=(0,D.NO)(c),h=this.ci(),f=D.W.lh(h),c=D.W.cg(h,g[0]),g=D.W.vo(h,g[1]),f=D.W.Zd(b,g!=D.o&&c!=D.o?g+f*c:D.o);if(!f)return D.o;c=D.W.ia(b,f);if(d){f=c.Wj();f.sba&&(f=f.X);if("overflow"==d)for(g=f.Ja();0<g;g--)if(f.ha(g-1)instanceof D.OO){a=f.ha(g-
1).Td;break}"closeButton"==d&&(a=D.W.ia(b,c.getData(),"closeButton"));if(0===d.lastIndexOf("node",0)){e=(0,D.NO)(d,D.k);g=e[0];if(0>g)return D.o;c=D.W.e_(b,f);for(h=0;c&&"DvtNBoxNode"==c.Xq();){if(h==g){a=c;break}c=D.W.ia(b,c.getData().__next);h++}}if(0===d.lastIndexOf("groupNode",0)){var j;-1<d.indexOf("{")?e=(0,D.PO)(d):j=d.substring(d.indexOf("[")+1,d.indexOf("]"));for(g=0;g<f.Ja();g++)if(c=f.ha(g),c instanceof D.BO)if(b=c.getData().id,e&&(0,D.QO)(e,b.split(";"))){a=c;break}else if(j&&j==b){a=
c;break}}}else a=c}else if(0===c.lastIndexOf("groupNode",0)){f=b.Wj();-1<c.indexOf("{")?e=(0,D.PO)(c):j=c.substring(c.indexOf("[")+1,c.indexOf("]"));for(g=0;g<f.Ja();g++)if(c=f.ha(g),c instanceof D.BO)if(b=c.getData().id,e&&(0,D.QO)(e,b.split(";"))){a=c;break}else if(j&&j==b){a=c;break}}else if("dialog"===c&&(f=b.Wj()))for(g=0;g<f.Ja();g++)if(f.ha(g)instanceof D.CO){j=f.ha(g);if(d){if("closeButton"==d)for(e=0;e<j.Ja();e++)j.ha(e)instanceof D.Oe&&(a=j.ha(e));if(0===d.lastIndexOf("node",0)){j=j.Wj().X;
e=(0,D.NO)(d,D.k);g=e[0];if(0>g)return D.o;c=D.W.e_(b,j);for(h=0;c&&"DvtNBoxNode"==c.Xq();){if(h==g){a=c;break}c=D.W.ia(b,c.getData().__next);h++}}}else a=j;break}return a?a.sa():D.o};D.FO.prototype.getDomElementForSubId=D.FO.prototype.If;D.FO.prototype.tG=function(a){var b=D.o,c=D.o,d=a.indexOf("#");-1!==d?(b=a.substring(0,d),c=a.substring(d+1)):b=a;return{component:b,action:c}};D.FO.prototype.ci=(0,D.v)("Ae");
D.NO=function(a,b){var c=a.substring(a.indexOf("[")+1,a.indexOf("]")).split(",");if(b)for(var d=0;d<c.length;d++)c[d]=(0,window.parseInt)(c[d]);return 0<c.length?c:D.o};D.KO=function(a){return 0<a.length?"["+a.join(",")+"]":""};D.PO=function(a){return a.substring(a.indexOf("{")+1,a.lastIndexOf("}")).split(",")};D.MO=function(a){for(var b="{",c=0;c<a.length;c++)b+=a[c].trim()+",";return b.substring(0,b.length-1)+"}"};
D.QO=function(a,b){if(a.length!=b.length)return D.p;a.sort();b.sort();for(var c=0;c<a.length;c++)if(a[c].trim()!=b[c].trim())return D.p;return D.k};D.JO=function(a,b){for(var c=a;c;){if(c.Xq()==b)return c;c=c.getParent()}return D.o};
D.FO.prototype.getData=function(a,b){if(this.Ae)if("rowsTitle"==a){if(this.Ae.q().rowsTitle)return this.Ae.q().rowsTitle}else if("rowCount"==a){var c=this.Ae.q().rows;if(c)return c.length}else if("row"==a){if(0<=D.W.cg(this.Ae,b))return c={},c.label=D.W.vKa(this.Ae,b),c}else if("columnsTitle"==a){if(this.Ae.q().columnsTitle)return this.Ae.q().columnsTitle}else if("columnCount"==a){if(c=this.Ae.q().columns)return c.length}else if("column"==a){if(0<=D.W.vo(this.Ae,b))return c={},c.label=D.W.PIa(this.Ae,
b),c}else if("groupBehavior"==a)return D.W.uj(this.Ae);return D.o};D.FO.prototype.getData=D.FO.prototype.getData;D.FO.prototype.qJa=function(a){if(a&&D.W.au(this.Ae)&&D.W.uj(this.Ae)==D.X.wI){if("string"===typeof a)return(0,D.RO)(this,a);var b="",c;for(c in a)b=a[c]?b+(c+":"+a[c]+";"):b+(c+";");return(0,D.RO)(this,b.substring(0,b.length-1))}return D.o};D.FO.prototype.getGroupNode=D.FO.prototype.qJa;
D.RO=function(a,b){var c=D.W.Qq(a.Ae,b);if(c){var d=D.W.ia(a.Ae,c);if(d){var e={};e.selected=d.Da();e.color=D.xO.dH(a.Ae,c);e.indicatorColor=D.xO.QR(a.Ae,c);e.tooltip=d.Bc();e.size=c.nodeIndices?c.nodeIndices.length:-1;c=D.W.ia(a.Ae,c,"indicatorIcon");e.indicatorIcon=a.xP(c);return e}}return D.o};
D.FO.prototype.Zd=function(a,b){var c=D.W.Haa(this.Ae,a,b);if(c){var d=c.$f(),e={};e.label=c.Nc();var f=D.xO.Tqa(c.$,c.$f()),g=f.A("background"),f=f.A("background-color");e.background=g?g:f;e.getNodeCount=function(){return c.Oe()};e.rowValue=a;e.columnValue=b;e.cellIndex=d;return e}return D.o};D.FO.prototype.getCell=D.FO.prototype.Zd;D.FO.prototype.HIa=function(a,b){if(this.Ae&&!D.W.au(this.Ae)){var c=D.W.Haa(this.Ae,a.rowValue,a.columnValue).Nb(b);return this.vh(c)}return D.o};
D.FO.prototype.getCellNode=D.FO.prototype.HIa;D.FO.prototype.Nb=function(a){a=D.W.Nb(this.Ae,a);return this.vh(a)};D.FO.prototype.getNode=D.FO.prototype.Nb;
D.FO.prototype.vh=function(a){if(a){var b=D.W.ia(this.Ae,a);if(b){var c={};c.selected=b.Da();c.tooltip=b.Bc();c.color=D.xO.rH(this.Ae,a);c.indicatorColor=D.xO.tH(this.Ae,a);a.label&&(c.label=a.label);a.secondaryLabel&&(c.secondaryLabel=a.secondaryLabel);b=D.W.ia(this.Ae,a,"icon");c.icon=this.xP(b);a=D.W.ia(this.Ae,a,"indicatorIcon");c.indicatorIcon=this.xP(a);return c}}return D.o};
D.FO.prototype.GIa=function(a,b){if(b&&D.W.au(this.Ae)&&D.W.uj(this.Ae)==D.X.Zp){if("string"===typeof b)return(0,D.RO)(this,a.cellIndex+":"+b);var c=a.cellIndex+":",d;for(d in b)c=b[d]?c+(d+":"+b[d]+";"):c+(d+";");return(0,D.RO)(this,c.substring(0,c.length-1))}return D.o};D.FO.prototype.getCellGroupNode=D.FO.prototype.GIa;D.FO.prototype.xP=function(a){if(a){var b={};b.shape=a instanceof D.dh?a.Pa():"none";a.Rb()&&(b.color=a.Rb().qb());return b}return D.o};
D.FO.prototype.cJa=function(){var a=D.W.Dm(this.Ae);if(a){var b=D.W.Qq(this.Ae,a.id);if(b){var c=D.W.ia(this.Ae,b),a={};a.label=c.Nc();a.getNodeCount=function(){return b.nodeIndices?b.nodeIndices.length:-1};for(var c={},d=b.id.split(";"),e=0;e<d.length;e++){var f=d[e].split(":");f&&2==f.length&&(c[f[0]]=f[1])}a.groupInfo=c;return a}}return D.o};D.FO.prototype.getDialog=D.FO.prototype.cJa;
D.FO.prototype.dJa=function(a){var b=D.W.Dm(this.Ae);return b&&(b=D.W.Qq(this.Ae,b.id))&&b.nodeIndices&&b.nodeIndices[a]!=D.o?(a=D.W.Nb(this.Ae,b.nodeIndices[a]),this.vh(a)):D.o};D.FO.prototype.getDialogNode=D.FO.prototype.dJa;D.FO.prototype.YJa=function(a){return D.W.Nb(this.Ae,a).id};D.FO.prototype.getNodeIdFromIndex=D.FO.prototype.YJa;D.FO.prototype.ZJa=function(a){return D.W.sH(this.Ae,a)};D.FO.prototype.getNodeIndexFromId=D.FO.prototype.ZJa;
D.yO={};D.z.l(D.yO,D.z,"DvtNBoxRenderer");D.yO.P=function(a,b,c){D.yO.Gt(a,b,c);D.yO.aD(a,b,c);D.yO.Sw(c);var d=D.yO.R4(a),e=D.HO.Wpa(a,d);D.yO.y9(a,b,e,c);D.yO.Sw(c);D.yO.hFa(a,b,d,e,c);D.yO.DFa(a,b,d,c);D.yO.wFa(a);D.yO.NBa(a)};D.yO.Gt=function(a,b,c){a=new D.Te(a.j(),c.x,c.y,c.e,c.g);(0,D.wi)(a);b.k(a);a=new D.ug;(0,D.wg)(a,c.x,c.y,c.e,c.g);(0,D.xg)(b,a)};
D.yO.aD=function(a,b,c){var d=D.W.eS(a);if(d&&d.sections){var e=a.q(),f=(0,D.E)(a.j()),g=new D.ur(a.j(),a.Pd,a,"pd1");g.la("dvtPanelDrawerEvent",a.Pd,D.p,a);g.mC="top";g.rT(c.g-e.__layout.legendBottomGap);g.wu(c.e/3);b.k(g);var h=(0,D.Cn)(a.j(),a.Pd,a);b.k(h);var j=h.Dp(d,g.gS(),g.fM());h.P(d,j.e,j.g);b.removeChild(h);var j=e._resources.legend_ena,l=e._resources.legend_ovr;b=e._resources.legend_dwn;j=new D.Ue(a.j(),j.src,0,0,j.width,j.height);l=new D.Ue(a.j(),l.src,0,0,l.width,l.height);b=new D.Ue(a.j(),
b.src,0,0,b.width,b.height);(0,D.yr)(g,h,j,l,b,(0,D.L)("DvtUtilBundle","LEGEND"),"legend");f&&(g.av="right");g.ir();"disclosed"==e[D.X.oU]&&((0,D.Gr)(g,"legend"),g.yf(D.k,D.k));e=g.F();(0,D.pk)(g,f?0:c.e,0);f&&(c.x+=e.e);c.e-=e.e;D.W.Qe(a,d,h,"legend");D.W.Qe(a,d,g,"panelDrawer")}};
D.yO.y9=function(a,b,c,d){var e=a.q(),f=D.W.lh(a),g=D.W.Xj(a),h=e.__layout.componentGap,j=e.__layout.titleGap,l=e.__layout.titleComponentGap,m=(0,D.E)(a.j());d.x+=h;d.y+=h;d.e-=2*h;d.g-=2*h;var n=D.W.Bp(a),h=n?D.W.vo(a,n):-1,q=D.W.Cp(a),r=q?D.W.cg(a,q):-1,s=D.o,u=D.o,w=[],y=[],C=0,O=0,M=0,J=0,R=0,N=0,Y=0,ha=0;e[D.X.m1]&&(s=D.yO.$k(a.j(),e[D.X.m1],e[D.X.be][D.X.nua],"center","middle"),b.k(s),C=D.$e.Dh(s).g);e[D.X.f3]&&(u=D.yO.$k(a.j(),e[D.X.f3],e[D.X.be][D.X.cwa],"center","middle"),b.k(u),O=D.$e.Dh(u).g);
for(e=0;e<f;e++){var ta=D.W.pD(a,e);if(ta[D.X.je]){var xa=D.yO.$k(a.j(),ta[D.X.je],D.xO.QIa(a,e),"center","middle"),R=window.Math.max(R,D.$e.Dh(xa).g);if(!n||n==ta[D.X.ID])w[e]=xa,b.k(w[e])}}for(e=0;e<g;e++)if(n=D.W.DD(a,e),n[D.X.je]&&(ta=D.yO.$k(a.j(),n[D.X.je],D.xO.wKa(a,e),"center","middle"),N=window.Math.max(N,D.$e.Dh(ta).g),!q||q==n[D.X.ID]))y[e]=ta,b.k(y[e]);if(O||N)Y=l,O&&N&&(M=j);if(C||R)ha=l,C&&R&&(J=j);j=O+M+N+Y;l=C+J+R+ha;d.x+=m?0:j;d.e-=j;d.g-=l;s&&D.$e.Qb(s,d.e,C,b)&&(D.yO.Jn(s,d.x+d.e/
2,d.y+d.g+l-C/2),D.W.Qe(a,a.q(),s,D.X.m1));u&&D.$e.Qb(u,d.g,O,b)&&(D.yO.Jn(u,d.x+(m?d.e:0)+(m?1:-1)*(j-O/2),d.y+d.g/2,m?window.Math.PI/2:-window.Math.PI/2),D.W.Qe(a,a.q(),u,D.X.f3));for(e=0;e<f;e++)w[e]&&(s=D.HO.$Z(a,-1==r?0:r,e,c,d),D.$e.Qb(w[e],s.e,R,b)&&(D.yO.Jn(w[e],s.x+s.e/2,d.y+d.g+ha+R/2),D.W.Qe(a,D.W.pD(a,e),w[e],D.X.je)));for(e=0;e<g;e++)y[e]&&(s=D.HO.$Z(a,e,-1==h?0:h,c,d),D.$e.Qb(y[e],s.g,N,b)&&(D.yO.Jn(y[e],d.x+(m?d.e:0)+(m?1:-1)*(Y+N/2),s.y+s.g/2,m?window.Math.PI/2:-window.Math.PI/2),
D.W.Qe(a,D.W.DD(a,e),y[e],D.X.je)))};D.yO.$k=function(a,b,c,d,e){a=new D.Kf(a,b,0,0);a.Ha(c);a.uu(d);a.Ey(e);return a};D.yO.hFa=function(a,b,c,d,e){for(var f=D.W.Xj(a),g=D.W.lh(a),h=0;h<f;h++)for(var j=0;j<g;j++){var l=D.W.Zd(a,h*g+j);D.LO.newInstance(a,l).P(b,d,c,e)}};
D.yO.R4=function(a){var b=D.W.Xj(a),c=D.W.lh(a),d=b*c,b=[],c=D.o,e=D.W.aM(a),f={};if(e)for(var c=[],g=0;g<e.length;g++)f[e[g][D.X.ID]]=D.k;for(g=0;g<d;g++)b[g]=0,c&&(c[g]=0);d=D.W.Oe(a);for(g=0;g<d;g++)if(e=D.W.Nb(a,g),!D.W.HH(a,e)){var h=D.W.$f(a,e);b[h]++;c&&f[e[D.X.ID]]&&c[h]++}a={};a.total=b;c&&(a.highlighted=c);return a};
D.yO.DFa=function(a,b,c,d){if(0<D.W.Oe(a))if("counts"==D.W.EIa(a)){b=D.W.Xj(a);d=D.W.lh(a);for(var e=[],f=0;f<b;f++)for(var g=0;g<d;g++)e.push(f*d+g);D.HO.Fta(a,c,e)}else D.W.au(a)?(D.yO.gFa(a,b,d),D.yO.mFa(a,b,d)):D.yO.vFa(a,c)};
D.yO.vFa=function(a,b){var c=a.q().__layout.gridGap,d=(0,D.E)(a.j()),e=["normal"],f=D.xO.c_(a),g=D.W.aM(a),h={};if(g)for(var j=0;j<g.length;j++)h[g[j][D.X.ID]]=D.k;var l=D.W.A_(a),m={};if(l)for(j=0;j<l.length;j++)m[l[j]]=D.k;g?e=l?["highlighted-selected","highlighted-unselected","unhighlighted-selected","unhighlighted-unselected"]:["highlighted-unselected","unhighlighted-unselected"]:l&&(e=["unhighlighted-selected","unhighlighted-unselected"]);for(var j={},l=D.W.Oe(a),n=0;n<e.length;n++)for(var q=
0;q<l;q++){var r=D.W.Nb(a,q);if(!D.W.HH(a,r)&&("normal"==e[n]||"highlighted-selected"==e[n]&&h[r[D.X.ID]]&&m[r[D.X.ID]]||"highlighted-unselected"==e[n]&&h[r[D.X.ID]]&&!m[r[D.X.ID]]||"unhighlighted-selected"==e[n]&&!h[r[D.X.ID]]&&m[r[D.X.ID]]||"unhighlighted-unselected"==e[n]&&!h[r[D.X.ID]]&&!m[r[D.X.ID]])){var s=D.W.$f(a,r);D.W.NA(a,s)||(j[s]||(j[s]=[]),j[s].push(r))}}for(var e=D.ZO.nHa(a,j),m=e.indicatorSectionWidth+e.iconSectionWidth+e.labelSectionWidth+c,l=e.nodeHeight+c,n=D.W.Xj(a),u=D.W.lh(a),
w=0;w<n;w++)for(var y=0;y<u;y++){var s=w*u+y,C=j[s];if(C&&C.length){var O=D.W.Zd(a,s),s=e.cellLayouts[s],q=s.cellRows,M=s.cellColumns;if(!(0==q||0==M||1==q&&1==M&&s.overflow))for(var J=q*M-(s.overflow?1:0),q=0;q<C.length;q++)if(r=C[q],0>J||q<J){var R=D.W.ia(a,O).Wj(),N=R instanceof D.MA,Y=D.DO.newInstance(a,r),ha=O.__childArea.x+(O.__childArea.e-s.cellColumns*m+c)/2,ta=N?c:O.__childArea.y,xa=q%M;d&&(xa=M-xa-1);var Ea=window.Math.floor(q/M);(0,D.pk)(Y,ha+m*xa,ta+l*Ea);Y.P(N?R.X:R,e);g&&!h[r[D.X.ID]]&&
Y.B(f);if(ha=0<q?C[q-1]:D.o)r.__prev=ha,ha.__next=r}}}n=D.W.Xj(a);u=D.W.lh(a);f=[];for(w=0;w<n;w++)for(y=0;y<u;y++){g=w*u+y;if(!D.W.NA(a,g)&&(j=D.W.Zd(a,g),O=D.W.ia(a,j),s=e.cellLayouts[g],s.overflow))if(q=s.cellRows,M=s.cellColumns,0==q||0==M||1==q&&1==M&&s.overflow)f.push(g);else{h=D.OO.newInstance(a,O);if((ha=D.W.sra(a,O.Wj()))&&ha instanceof D.DO)h.__prev=ha.getData(),ha.getData().__next=h;D.W.Qe(a,h,h);D.W.Qe(a,j,h,"overflow");ha=j.__childArea.x+(j.__childArea.e-s.cellColumns*m+c)/2;ta=j.__childArea.y;
xa=s.cellColumns-1;d&&(xa=0);Ea=s.cellRows-1;(0,D.pk)(h,ha+m*xa,ta+l*Ea);h.P(O.Wj(),m-c,l-c)}D.W.BM(a,g)&&(R=D.W.ia(a,D.W.Zd(a,g)).Wj(),(0,D.NA)(R))}0<f.length&&D.HO.Fta(a,b,f)};
D.yO.gFa=function(a,b,c){var d={},e=D.W.Oe(a),f=D.W.uj(a),g=(0,D.E)(a.j()),h=D.W.aM(a),j={};if(h)for(var l=0;l<h.length;l++)j[h[l][D.X.ID]]=D.k;for(l=0;l<e;l++)if(h=D.W.Nb(a,l),!D.W.HH(a,h)){var m=d;if(f==D.X.Zp){var n=D.W.$f(a,h)+"",m=d[n];m||(m={},d[n]=m)}var n=D.W.iS(h),q=m[n];q||(q={},q[D.X.ID]=n,f==D.X.Zp&&(q[D.X.JT]=D.W.$f(a,h)),q.nodeIndices=[],q.highlightedCount=0,m[n]=q);q.nodeIndices.push(l);j[D.W.Nb(a,l)[D.X.ID]]&&q.highlightedCount++}if(f==D.X.Zp){var l={},r;for(r in d)l[r]=D.yO.coa(a,
d[r])}else l=D.yO.coa(a,d);d=l;a.q().__groups=d;if(f==D.X.wI){r=[];for(q in d)r.push(q);r.sort(function(a,b){return D.BO.baa(d[a],d[b])});f=window.Math.sqrt(0.15*c.e*c.g/e);for(l=0;l<r.length;l++){q=r[l];m=j=0;e=d[q].nodeIndices.length;for(n=0;n<e;n++)h=D.W.Nb(a,d[q].nodeIndices[n]),j+=D.W.gLa(a,h),m+=D.W.lLa(a,h);j/=e;m/=e;e=D.BO.newInstance(a,d[q]);(0,D.pk)(e,c.x+(g?1-j:j)*c.e,c.y+(1-m)*c.g);e.P(b,f,0);e.Ota(0.8)}}else if(f==D.X.Zp){l=D.W.Xj(a);b=D.W.lh(a);b*=l;c=[];for(l=0;l<b;l++)d[l]&&!D.W.NA(a,
l)&&(g=D.W.Zd(a,l),c[l]=D.yO.OBa(d[l],g.__childArea.e,g.__childArea.g));f=40;for(l=0;l<b;l++)d[l]&&!D.W.NA(a,l)&&(f=window.Math.min(f,c[l].scale));for(l=0;l<b;l++)if(d[l]&&!D.W.NA(a,l))for(q in h=c[l].positions,r=c[l].center,g=D.W.Zd(a,l),j=D.W.ia(a,g).Wj(),m=j instanceof D.MA,h)e=D.BO.newInstance(a,d[l][q]),(0,D.pk)(e,g.__childArea.x+g.__childArea.e/2+f*(h[q].x-r.x),(m?0:g.__childArea.y)+g.__childArea.g/2+f*(h[q].y-r.y)),e.P(m?j.X:j,f,3)}};
D.yO.uKa=function(a,b,c){a=D.W.Xj(a);var d=c.g/a;return new D.A(c.x,c.y+(a-b-1)*d,c.e,d)};D.yO.OIa=function(a,b,c){var d=D.W.lh(a),d=c.e/d;a=(0,D.E)(a.j());return new D.A(c.x+(a?c.e-d:0)+(a?-1:1)*b*d,c.y,d,c.g)};D.yO.Sw=function(a){a.x=window.Math.round(a.x);a.y=window.Math.round(a.y);a.e=window.Math.round(a.e);a.g=window.Math.round(a.g)};D.yO.Jn=function(a,b,c,d){a.ca(b);a.va(c);if(d){var e=a.ta();e.translate(-b,-c);e.rotate(d);e.translate(b,c);a.za(e)}};
D.yO.wFa=function(a){if(a.br()){var b={},c=[],d=D.W.A_(a);if(d){for(var e=0;e<d.length;e++)c.push(d[e]),b[d[e]]=D.k;var f=a.Uq();if(D.W.au(a))for(e=0;e<f.length;e++)if(f[e]instanceof D.BO){for(var d=f[e].getData().nodeIndices,g=D.k,h=0;h<d.length;h++){var j=D.W.Nb(a,d[h]);if(!b[j[D.X.ID]]){g=D.p;break}}g&&c.push(f[e].getId())}}(0,D.Il)(a.mh(),c,f)}};
D.yO.OBa=function(a,b,c){var d=[],e;for(e in a)d.push(e);d.sort(function(b,c){return D.BO.baa(a[b],a[c])});for(var f={},g=2*window.Math.PI/d.length,h=0;h<d.length;h++)f[d[h]]=D.DF.DR(h*window.Math.cos(g*h),h*window.Math.sin(g*h));for(var g=1,j=-0.25*c/window.Math.max(b,c),l=-0.25*b/window.Math.max(b,c);0.005<g;){for(var m={},h=0;h<d.length;h++){var n=d[h];e=f[n];var q=a[n].nodeIndices.length;m[n]=D.DF.DR(g*j*e.x,g*l*e.y);for(var r=0;r<d.length;r++)if(h!=r){for(var s=d[r],u=a[s].nodeIndices.length,
s=D.DF.bOa(e,f[s]),w=D.DF.PJa(s),y=window.Math.atan2(s.y,s.x);0>y;)y+=window.Math.PI/2;for(;y>=window.Math.PI/2;)y-=window.Math.PI/2;y=y<window.Math.PI/4?0.5*(window.Math.sqrt(q)+window.Math.sqrt(u))/window.Math.cos(y):0.5*(window.Math.sqrt(q)+window.Math.sqrt(u))/window.Math.sin(y);w<y&&(m[n]=D.DF.Mpa(m[n],D.DF.ENa(s,(1-g)*u/(q+u)*((y-w)/w))))}}for(h=0;h<d.length;h++)n=d[h],f[n]=D.DF.Mpa(f[n],m[n]);g*=0.98}g=window.Number.MAX_VALUE;j=-window.Number.MAX_VALUE;l=window.Number.MAX_VALUE;m=-window.Number.MAX_VALUE;
for(h=0;h<d.length;h++)e=d[h],n=window.Math.sqrt(a[e].nodeIndices.length),e=f[e],g=window.Math.min(g,e.x-n/2),j=window.Math.max(j,e.x+n/2),l=window.Math.min(l,e.y-n/2),m=window.Math.max(m,e.y+n/2);return{scale:window.Math.min(b/(j-g),c/(m-l)),center:new D.F((g+j)/2,(l+m)/2),positions:f}};
D.yO.coa=function(a,b){var c=D.W.Oe(a),c=D.W.eKa(a)*c;if(1>=c)return b;var d={},e={};if(D.W.uj(a)==D.X.Zp)for(var f in b){var g=b[f];e.cell=g.cell;break}e.id="other";e.nodeIndices=[];e.otherNode=D.k;for(f in b)if(g=b[f],g.nodeIndices.length<c)for(var h=0;h<g.nodeIndices.length;h++)e.nodeIndices.push(g.nodeIndices[h]);else d[f]=g;0<e.nodeIndices.length&&(d.other=e);return d};
D.yO.mFa=function(a,b,c){var d=D.W.Dm(a);d&&(D.W.Qq(a,d.id)?D.CO.newInstance(a,d).P(b,c):(a.q()[D.X.Aw]=D.o,b=new D.hr,(0,D.El)(b,D.X.Aw,D.o),a.Pd(b)))};D.yO.wi=function(a){var b=a.ta().Y();for(a=a.getParent();a;){var c=a.ta();b.translate(c.qc,c.oc);a=a.getParent()}return b};D.yO.gf=function(a,b,c){D.yO.Iza(a,b,c);D.yO.Lza(a,b,c);var d=D.W.Dm(b),d=d?d.id:D.o,e=D.W.Dm(c),e=e?e.id:D.o;d!=e&&D.yO.Jza(a,b,c)};
D.yO.Iza=function(a,b,c){for(var d=D.W.Xj(b),e=D.W.Xj(c),f=D.W.lh(b),g=D.W.lh(c),h=d*f,j=e*g,l=[],m=[],n=0;n<h;n++)l.push(D.W.ia(b,D.W.Zd(b,n)));for(n=0;n<j;n++)m.push(D.W.ia(c,D.W.Zd(c,n)));if(d==e&&f==g){d=D.k;for(n=0;n<e;n++)if(f=D.W.DD(b,n)[D.X.ID],h=D.W.DD(c,n)[D.X.ID],f!=h){d=D.p;break}if(d)for(n=0;n<g;n++)if(e=D.W.pD(b,n)[D.X.ID],f=D.W.pD(c,n)[D.X.ID],e!=f){d=D.p;break}if(d){(0,D.Tm)(a,l,m);return}}(0,D.Tm)(a,l,[]);(0,D.Tm)(a,[],m)};
D.yO.Lza=function(a,b,c){for(var d=D.W.Oe(b),e=D.W.Oe(c),f=[],g=[],h=0;h<d;h++)f.push(D.W.ia(b,D.W.Nb(b,h)));for(h=0;h<e;h++)g.push(D.W.ia(c,D.W.Nb(c,h)));(0,D.Tm)(a,f,g);d=D.W.Dm(b);D.W.Dm(c)||(e=D.yO.Rka(b),f=D.yO.Rka(c),d&&(D.W.gM(b)!=D.W.gM(c)?(e=e.filter(function(a){return a.getData().cell!=D.W.gM(b)}),f=f.filter(function(a){return a.getData().cell!=D.W.gM(b)})):f=e=D.o),(0,D.Tm)(a,e,f))};
D.yO.Rka=function(a){var b=D.W.uj(a),c=a.q().__groups,d=[];if(c)if(b==D.X.Zp)for(var b=D.W.Xj(a),e=D.W.lh(a),b=b*e,e=0;e<b;e++)for(var f=D.yO.Ska(a,c[e+""]),g=0;g<f.length;g++)d.push(f[g]);else d=D.yO.Ska(a,c);return d};D.yO.Ska=function(a,b){var c=[],d;for(d in b){var e=D.W.ia(a,b[d]);e&&c.push(e)}c.sort(function(a,b){var c=a.getId(),d=b.getId();return c==d?0:c<d?-1:1});return c};D.yO.Jza=function(a,b,c){var d=D.W.Dm(b),d=d?[D.W.ia(b,d)]:D.o;b=(b=D.W.Dm(c))?[D.W.ia(c,b)]:[];(0,D.Tm)(a,d,b)};
D.yO.L=function(a,b){if(0==b.indexOf("linear-gradient")){var c=(0,D.ZB)(b);c&&a.L(new D.fg(c.Ol(),c.km,c.jm,c.cz))}else a.pa(b)};D.yO.NBa=function(a){var b=D.W.eS(a);b&&b.sections&&(a=D.W.ia(a,b,"panelDrawer"))&&a.getParent().k(a)};
D.HO={};D.z.l(D.HO,D.z,"DvtNBoxCellRenderer");
D.HO.P=function(a,b,c,d,e,f){var g=a.q(),h=g.__layout.cellGap,j=g.__layout.cellStartGap,l=g.__layout.cellEndGap,m=g.__layout.cellTopGap,g=g.__layout.cellBottomGap,n=D.W.cg(a,b[D.X.dj]),q=D.W.vo(a,b[D.X.cj]),r=D.HO.$Z(a,n,q,d,f);(0,D.pk)(c,r.x+h/2,r.y+h/2);f=n*D.W.lh(a)+q;h=new D.Te(a.j(),0,0,window.Math.max(r.e-h,0),window.Math.max(r.g-h,0));(0,D.Ei)(h);n=D.xO.Tqa(a,f);D.HO.eia(h,n);c.k(h);D.W.Qe(a,b,h,"background");n=new D.Bg(a.j(),c,new D.A(-1,-1,h.getWidth()+2,h.getHeight()+2));D.W.Qe(a,b,n,"focusEffect");
e=D.HO.M0(a,b,c,e,D.p);f=D.W.BM(a,f)?new D.MA(a.j(),h.getWidth(),h.getHeight()-(e?d.headerSize:0)):new D.D(a.j());c.k(f);c.jda(f);c=D.o;e?(c=D.HO.KP(a,b)?new D.A(d.headerSize,m,h.getWidth()-d.headerSize-l,h.getHeight()-m-g):new D.A(j,d.headerSize,h.getWidth()-j-l,h.getHeight()-d.headerSize-g),f instanceof D.MA&&(0,D.pk)(f,0,d.headerSize)):c=new D.A(j,m,h.getWidth()-j-l,h.getHeight()-m-g);c.e=window.Math.max(c.e,0);c.g=window.Math.max(c.g,0);b.__childArea=c};
D.HO.M0=function(a,b,c,d,e){var f=D.W.ia(a,b,D.X.je);f&&(f.getParent().removeChild(f),D.W.Qe(a,b,D.o,D.X.je));if(f=D.W.ia(a,b,"countLabel"))f.getParent().removeChild(f),D.W.Qe(a,b,D.o,"countLabel");if(f=D.W.ia(a,b,"closeButton"))f.getParent().removeChild(f),D.W.Qe(a,b,D.o,"closeButton");var g=D.p;if(b){var h=a.q(),f=h.__layout.countLabelGap,j=h.__layout.cellCloseGap,l=h.__layout.cellStartGap,m=h.__layout.cellEndGap,n=h.__layout.cellTopGap,q=h.__layout.__cellLayout,r=D.W.ia(a,b,"background"),s=D.W.cg(a,
b[D.X.dj]),u=D.W.vo(a,b[D.X.cj]),u=s*D.W.lh(a)+u,s=(0,D.E)(a.j()),w=0;if(D.W.BM(a,u)){var y=h._resources.close_ena,C=y.width;r.getWidth()-l-m>C&&(g=h._resources.close_ovr,w=h._resources.close_dwn,h=new D.Ue(a.j(),y.src,0,0,y.width,y.height),g=new D.Ue(a.j(),g.src,0,0,g.width,g.height),w=new D.Ue(a.j(),w.src,0,0,w.width,w.height),g=new D.Oe(a.j(),h,g,w,D.o,D.o,c.os,c),w=s?window.Math.min((r.getWidth()-C)/2,m):window.Math.max((r.getWidth()-C)/2,r.getWidth()-m-C),(0,D.pk)(g,w,n),c.k(g),w=C+j,D.W.Qe(a,
b,g,"closeButton"),g=D.k)}if(b[D.X.je]){var j=q.labelHeight,O=D.p,C=D.xO.FJa(a,b),M=h=0,q=D.o,y=h=0,J=D.o,R=D.xO.Sqa(a,b),N=b.countLabel;e||(N&&"off"!=R?J=N:"on"==R&&(J=""+d.total[u],d.highlighted&&(J=(0,D.L)("DvtNBoxBundle","HIGHLIGHTED_COUNT",[d.highlighted[u],J]))));D.HO.KP(a,b)?(J&&(q=D.yO.$k(a.j(),J,D.xO.Iaa(a),"center","middle"),D.$e.Qb(q,r.getHeight()-l-m,r.getWidth()-2*n,c)?(D.W.Qe(a,b,q,"countLabel"),g=D.k,h=q.F().e,M=h+f,y=r.getHeight()/2,h=n+j/2):O=D.k),d=0,O||(e=D.yO.$k(a.j(),b[D.X.je],
D.xO.Jaa(a,u),"center","middle"),D.$e.Qb(e,r.getHeight()-l-m-M,r.getWidth()-2*n,c)&&(D.W.Qe(a,b,e,D.X.je),d=e.F().e,g=D.k,D.yO.Jn(e,n+j/2,(r.getHeight()+M)/2,s?window.Math.PI/2:-window.Math.PI/2),d=(d+f)/2)),q&&D.yO.Jn(q,h,y-d,s?window.Math.PI/2:-window.Math.PI/2)):(J&&(q=D.yO.$k(a.j(),J,D.xO.Iaa(a),C,"middle"),D.$e.Qb(q,r.getWidth()-l-m-w,r.getHeight()-2*n,c)?(D.W.Qe(a,b,q,"countLabel"),g=D.k,h=q.F().e,M=h+f,h="center"==C?r.getWidth()/2:"right"==C?r.getWidth()-m:l,y=n+j/2,D.yO.Jn(q,h,y)):O=D.k),
d=0,O||(e=D.yO.$k(a.j(),b[D.X.je],D.xO.Jaa(a,u),C,"middle"),D.$e.Qb(e,r.getWidth()-l-m-w-M,r.getHeight()-2*n,c)&&(D.W.Qe(a,b,e,D.X.je),d=e.F().e,g=D.k,"center"==C?(l=(r.getWidth()-(s?-1:1)*M)/2,d=(s?-1:1)*(d+f)/2):"right"==C?(l=r.getWidth()-m-(s?0:1)*M,d=(s?-1:0)*(d+f)):(l+=(s?1:0)*M,d=(s?0:1)*(d+f)),D.yO.Jn(e,l,n+j/2))),q&&d&&D.yO.Jn(q,h+d,y))}}D.HO.Yy(a,b,c);return g};
D.HO.Fta=function(a,b,c){var d=D.HO.Wpa(a,b),e=a.q().__layout.cellTopGap,f=a.q().__layout.cellStartGap,g=window.Number.MAX_VALUE,h=D.p,j=D.W.Zd(a,c[0]),l=D.W.ia(a,j,D.X.je),m=D.W.ia(a,j,"countLabel"),n=l&&l.gc()?l.gc().BA():D.o,q=m&&m.gc()?m.gc().BA():D.o,n=(0,window.isNaN)(n)?(0,window.parseFloat)(n):n,q=(0,window.isNaN)(q)?(0,window.parseFloat)(q):q;if(!(0,window.isNaN)(n)||!(0,window.isNaN)(q))g=(0,window.isNaN)(n)?q:(0,window.isNaN)(q)?n:window.Math.max(n,q);for(var n=[],q=[],r=0;r<c.length;r++)j=
c[r],D.W.NA(a,j)?q.push(j):n.push(j);for(var s=[],u=[],r=0;r<n.length;r++)j=n[r],j=b.total[j],s[r]=D.yO.$k(a.j(),""+j,D.xO.Qqa(a),"center","middle");for(r=0;r<q.length;r++)j=q[r],j=b.total[j],u[r]=D.yO.$k(a.j(),""+j,D.xO.Qqa(a),"center","middle");var w=D.HO.WZ(a,n,s);if(w<=g||m&&!l)h=D.k;var y=D.HO.WZ(a,q,u);if(y<=g||m&&!l)h=D.k;if(h){for(r=0;r<c.length;r++)j=D.W.Zd(a,c[r]),l=D.W.ia(a,j,D.X.je),m=D.W.ia(a,j,"countLabel"),g=j.__childArea,w=D.p,l&&(l.getParent().removeChild(l),D.W.Qe(a,j,D.o,D.X.je),
w=D.k),m&&(m.getParent().removeChild(m),D.W.Qe(a,j,D.o,"countLabel"),w=D.k),w&&(D.HO.KP(a,j)?(g.x-=d.headerSize-f,g.e+=d.headerSize-f):(g.y-=d.headerSize-e,g.g+=d.headerSize-e),j.__childArea=g);w=D.HO.WZ(a,n,s);y=D.HO.WZ(a,q,u)}for(r=0;r<n.length;r++)j=n[r],j=D.W.Zd(a,j),c=D.W.ia(a,j),g=j.__childArea,s[r].Ie(w),D.$e.Qb(s[r],g.e,g.g,c)&&(h||D.HO.M0(a,j,c,b,D.k),D.yO.Jn(s[r],g.x+g.e/2,g.y+g.g/2));for(r=0;r<q.length;r++)j=q[r],j=D.W.Zd(a,j),c=D.W.ia(a,j),g=j.__childArea,u[r].Ie(y),D.$e.Qb(u[r],g.e,g.g,
c)&&(h||D.HO.M0(a,j,c,b,D.k),D.yO.Jn(u[r],g.x+g.e/2,g.y+g.g/2))};D.HO.WZ=function(a,b,c){for(var d=window.Number.MAX_VALUE,e=0;e<b.length;e++)var f=D.W.Zd(a,b[e]).__childArea,d=window.Math.min(d,c[e].Tv(f));return d};D.HO.KP=function(a,b){var c=D.W.Bp(a),d=D.W.Cp(a);return c&&c!=b[D.X.cj]&&(!d||d==b[D.X.dj])?D.k:D.p};
D.HO.$Z=function(a,b,c,d,e){var f=a.q().__layout.cellGap,g=(0,D.E)(a.j()),f=f+d.minimumCellSize,h=D.W.Xj(a);d=D.W.lh(a);var j=D.yO.uKa(a,b,e),l=D.yO.OIa(a,c,e),m=D.W.Cp(a),n=D.W.Bp(a),q=l.x,r=j.y,l=l.e,j=j.g,s=D.k;m&&(r=D.W.cg(a,m),m=window.Math.min(e.g/(3*(h-1)),f),b<r?(r=e.y+e.g-(b+1)*m,j=m,s=D.p):b==r?(r=e.y+(h-b-1)*m,j=e.g-(h-1)*m):(r=e.y+(h-b-1)*m,j=m,s=D.p));n&&s&&(a=D.W.vo(a,n),b=window.Math.min(e.e/(3*(d-1)),f),c<a?(l=b,q=e.x+(g?e.e-b:0)+(g?-1:1)*c*b):c==a?(l=e.e-(d-1)*b,q=e.x+(g?e.e-l:0)+
(g?-1:1)*c*b):(l=b,q=e.x+(g?-b:e.e)+(g?1:-1)*(d-c)*b));return new D.A(q,r,l,j)};
D.HO.Wpa=function(a,b){var c=a.q(),d=c.__layout.cellTopGap,e=c.__layout.cellBottomGap,f=c.__layout.cellLabelGap,g=c.__layout.minimumCellSize,h=0,j=D.W.Zd(a,0);if(j&&j[D.X.je]){var l=j[D.X.C2],h=D.yO.$k(a.j(),j[D.X.je],D.xO.Jaa(a,0),l,"middle"),h=D.$e.Dh(h).g;"on"==D.xO.Sqa(a,j)&&(j=D.yO.$k(a.j(),b.total[0],D.xO.Iaa(a),l,"middle"),j=D.$e.Dh(j).g,h=window.Math.max(h,j))}D.W.Cp(a)&&D.W.Bp(a)&&(h=window.Math.max(h,c._resources.close_ena.height));e=h+d+e;d=h+d+f;g=window.Math.max(e,g);g={labelHeight:h,
headerSize:d,minimizedHeaderSize:e,minimumCellSize:g};return c.__layout.__cellLayout=g};
D.HO.gf=function(a,b,c){var d=a.PC,e=a.yq,f=new D.qn(e.j(),c,a.xa()),g=c.Wj(),h=g.ta();g.za(D.yO.wi(g));var j=c.getParent();j.Ma(g,j.Qf(c)+1);var j=c.N(),l=c.M();(0,D.T)(f.J,"typeMatrix",c,c.ta,c.za,c.ta());c.za(b.ta());var m=D.W.ia(d,b.getData(),"background"),n=D.W.ia(e,c.getData(),"background"),q=(0,D.E)(e.j())?0:n.getWidth()-m.getWidth();(0,D.T)(f.J,"typeFill",n,n.Rb,n.L,n.Rb());n.L(m.Rb());(0,D.T)(f.J,"typeNumber",n,n.getWidth,n.ma,n.getWidth());n.ma(m.getWidth());(0,D.T)(f.J,"typeNumber",n,n.getHeight,
n.Ea,n.getHeight());n.Ea(m.getHeight());if(c.pc()&&(n=D.W.ia(e,c.getData(),"focusEffect").Saa()))(0,D.T)(f.J,"typeNumber",n,n.getWidth,n.ma,n.getWidth()),n.ma(m.getWidth()+2),(0,D.T)(f.J,"typeNumber",n,n.getHeight,n.Ea,n.getHeight()),n.Ea(m.getHeight()+2);D.HO.cia(a,b,c,"countLabel");D.HO.cia(a,b,c,D.X.je);b=D.W.ia(d,b.getData(),"closeButton");d=D.W.ia(e,c.getData(),"closeButton");b?d?((0,D.T)(f.J,"typeMatrix",d,d.ta,d.za,d.ta()),d.za(b.ta())):(d=D.yO.wi(b),(0,D.pk)(b,b.N()+q+j,b.M()+l),a.add(new D.sn(e.j(),
b,a.xa()),1),(0,D.T)(f.J,"typeMatrix",b,b.ta,b.za,b.ta()),b.za(d),e.mf.k(b)):d&&(a.add(new D.Vm(e.j(),d,a.xa()),1),(0,D.T)(f.J,"typeMatrix",d,d.ta,d.za,d.ta()),(0,D.pk)(d,d.N()-q,d.M()),d.B(0));(0,D.hl)(f,function(){c.k(g);g.za(h)});a.add(f,1)};
D.HO.cia=function(a,b,c,d){var e=a.PC,f=a.yq,g=D.W.ia(e,b.getData(),d),h=D.W.ia(f,c.getData(),d);b=D.HO.KP(e,b.getData());e=D.HO.KP(f,c.getData());if(g||h)if(g&&h&&b==e){b=new D.qn(f.j(),h,a.xa());var e=g.zn(),j=h.zn(),e=(("left"==j?-1:"center"==j?0:1)-("left"==e?-1:"center"==e?0:1))*h.Eb().e/2;(0,D.T)(b.J,"typeNumber",h,h.ja,h.ca,h.ja());h.ca(g.ja()+e);(0,D.T)(b.J,"typeNumber",h,h.na,h.va,h.na());h.va(g.na());(0,D.T)(b.J,"typeMatrix",h,h.ta,h.za,h.ta());h.za(g.ta());a.add(b,1);"countLabel"==d&&g.Bd()!=
h.Bd()&&(h.B(0),c.k(g),c=new D.sn(f.j(),g,a.xa()),h=new D.Vm(f.j(),h,a.xa()),a.add(c,1),a.add(h,2),(0,D.hl)(c,function(){f.mf.k(g)}))}else g&&(g.za(D.yO.wi(g)),f.mf.k(g),a.add(new D.sn(f.j(),g,a.xa()),1)),h&&(h.B(0),a.add(new D.Vm(f.j(),h,a.xa()),1))};D.HO.kh=function(a,b){var c=a.yq,d=b.Wj();if(d){var e=D.yO.wi(d),f=b.getParent();f.Ma(d,f.Qf(b)+1);d.za(e)}c.mf.k(b);a.add(new D.sn(c.j(),b,a.xa()),1)};
D.HO.qg=function(a,b){var c=a.yq,d=b.Wj(),e=D.o;if(d){var e=d.ta(),f=D.yO.wi(b),g=b.getParent();g.Ma(d,g.Qf(b)+1);d.za(f)}b.B(0);c=new D.Vm(c.j(),b,a.xa());d&&(0,D.hl)(c,function(){b.k(d);d.za(e)});a.add(c,1)};D.HO.Xca=function(a,b){var c=D.W.ia(a,b.getData(),"background"),d=new D.Te(a.j(),c.ja(),c.na(),c.getWidth(),c.getHeight());(0,D.Ei)(d);var e=D.xO.FIa(a);D.HO.eia(d,e);b.Ma(d,b.Qf(c)+1);return d};
D.HO.eia=function(a,b){var c=b.A("background"),d=b.A("background-color");(c=c?c:d)&&D.yO.L(a,c);"solid"==b.A("border-style")&&(c=(c=b.A("border-color"))?c:"#000000",d=b.A("border-width"),d=d==D.o?1:(0,window.parseFloat)(d),a.Ra(c,D.o,d))};D.HO.Yy=function(a,b,c){a=(0,D.Jf)()?D.W.ia(a,b,"background"):c;a.Ud("img");(0,D.cf)()||(c=c.fc())&&a.$b(D.X.je,c)};
D.ZO={};D.z.l(D.ZO,D.z,"DvtNBoxNodeRenderer");D.ZO.P=function(a,b,c,d){D.ZO.s9(a,b,c,d);D.ZO.t9(a,b,c,d);D.ZO.BFa(a,b,c,d);D.ZO.CFa(a,b,c,d);D.ZO.Yy(a,c)};
D.ZO.nHa=function(a,b){for(var c=a.q(),d=c.__layout.gridGap,e=c.__layout.nodeStartLabelGap,f=c.__layout.nodeLabelOnlyStartLabelGap,g=c.__layout.nodeEndLabelGap,h=c.__layout.nodeSwatchSize,j=c.__layout.maximumLabelWidth,l=D.ZO.Ria(a),m=l.nodeHeight,n=l.indicatorSectionWidth,q=l.iconSectionWidth,f=n||q?e:f,r=D.W.Nb(a,0),s=D.W.j_(a,r),u=D.W.An(a,r),w=0,e=[],y=0,C=0,C=D.W.Cp(a),O=D.W.Bp(a),w=D.W.Xj(a),M=D.W.lh(a),J=0;J<w;J++)for(var R=0;R<M;R++)e.push({cellRows:0,cellColumns:0,overflow:D.p});for(var N=
[],J=D.W.Oe(a),y=0;y<J;y++){var Y=D.W.Nb(a,y);D.W.HH(a,Y)||(R=D.W.$f(a,Y),(0,window.isNaN)(N[R])&&(N[R]=0),N[R]++)}if(C&&O){N=D.W.vo(a,O)+M*D.W.cg(a,C);O=D.W.Zd(a,N).__childArea;w=l.labelSectionWidth;w==D.o&&("ifRequired"!=c.labelTruncation?w=j+f+g:(l=b[N],w=window.Math.max(j,D.ZO.F6(a,l))+f+g),w=window.Math.min(w,O.e-n-q));C=window.Math.floor((O.e+d)/(n+q+w+d));if(r[D.X.je]&&(d=new D.D,j=D.p,M=D.W.jS(a,r),y=D.$e.Dh(M).g,D.$e.Qb(M,w-f-g,y,d)&&(j=D.k),r[D.X.Hw]&&(M=D.W.kS(a,r),y=D.$e.Dh(M).g,D.$e.Qb(M,
w-f-g,y,d)&&(j=D.k)),!j&&(w=0,r[D.X.bj]&&(!s||D.xO.tH(a,r))&&(!u||u[D.X.Ry]))))w=window.Math.max(0,window.Math.min(h,O.e-n-q));if(0>O.e-n-q)var ha=q,q=window.Math.max(0,O.e-n);0>O.e-n&&(n=O.e);e[N]={cellRows:-1,cellColumns:C,overflow:D.p}}else{h=[];if(C){C=D.W.cg(a,C);for(R=0;R<M;R++)h.push(R+C*M)}else if(O){C=D.W.vo(a,O);for(J=0;J<w;J++)h.push(C+J*M)}else for(y=0;y<e.length;y++)h.push(y);if(l.labelSectionWidth!=D.o)w=l.labelSectionWidth,C=D.W.Zd(a,h[0]),O=C.__childArea,y=window.Math.floor((O.g+d)/
(m+d)),C=window.Math.floor((O.e+d)/(n+q+w+d));else{for(O=r=0;O<h.length;O++)!(0,window.isNaN)(N[h[O]])&&N[h[O]]>N[r]&&(r=h[O]);if("ifRequired"!=c.labelTruncation)if(C=D.W.Zd(a,r),O=C.__childArea,C=window.Math.floor((O.g+d)/(m+d)),s=window.Math.floor((O.e+d)/(n+q+c.__layout.minimumLabelWidth+f+g+d)),C*s<N[r])w=window.Math.floor(window.Math.min(c.__layout.maximumLabelWidth+f+g,(O.e+d)/s-(n+q+d))),y=C,C=s;else{j=s;for(w=window.Math.floor(window.Math.min(c.__layout.maximumLabelWidth+f+g,(O.e+d)/j-(n+
q+d)));w<c.__layout.maximumLabelWidth+f+g;)if((j-1)*C>=N[r])j--,w=window.Math.floor(window.Math.min(c.__layout.maximumLabelWidth+f+g,(O.e+d)/j-(n+q+d)));else break;y=C;C=j}else{for(var C=D.W.Zd(a,h[0]),O=C.__childArea,C=window.Math.floor((O.g+d)/(m+d)),s=window.Math.floor((O.e+d)/(n+q+c.__layout.minimumLabelWidth+f+g+d)),y=C,ta=u=C=0;C<=s;){C++;var xa=window.Math.floor((O.e+d)/C-(n+q+d));if(u>xa){C=window.Math.max(C-1,1);break}for(var Ea=C*y,ob=[],J=0;J<w;J++)for(R=0;R<M;R++)if(Y=D.W.vo(a,R)+M*D.W.cg(a,
J),(l=b[Y])&&l.length){var La=window.Math.min(l.length,Ea);l.length>Ea&&La--;for(Y=ta;Y<La;Y++)ob.push(l[Y])}u=window.Math.max(u,window.Math.ceil(D.ZO.F6(a,ob)+f+g));if(u>xa){C=window.Math.max(C-1,1);break}if(Ea>=N[r])break;ta=Ea}xa=window.Math.floor((O.e+d)/C-(n+q+d));w=u>xa?xa:window.Math.max(u,window.Math.min(xa,j+f+g));w<c.__layout.minimumLabelWidth&&(C=0)}}for(O=0;O<h.length;O++)Y=h[O],g=D.p,N[Y]>y*C&&(g=D.k),e[Y]={cellRows:y,cellColumns:C,overflow:g}}m={nodeHeight:m,indicatorSectionWidth:n,
iconSectionWidth:q,iconWidth:ha,labelSectionWidth:w,cellLayouts:e};return c.__layout.__nodeLayout=m};
D.ZO.mHa=function(a,b,c){var d=a.q(),e=d.__layout.gridGap,f=d.__layout.nodeStartLabelGap,g=d.__layout.nodeLabelOnlyStartLabelGap,h=d.__layout.nodeEndLabelGap,j=d.__layout.nodeSwatchSize,l=d.__layout.maximumLabelWidth,m=D.W.Nb(a,0),n=D.W.j_(a,m),q=D.W.An(a,m),r=D.ZO.Ria(a),s=r.nodeHeight,u=r.indicatorSectionWidth,w=r.iconSectionWidth,f=u||w?f:g;b=b.__childArea;r=r.labelSectionWidth;r==D.o&&(r="ifRequired"!=d.labelTruncation?l+f+h:window.Math.max(l,D.ZO.F6(a,c))+f+h,r=window.Math.min(r,b.e-u-w));c=
window.Math.floor((b.e+e)/(u+w+r+e));if(m[D.X.je]){var e=new D.D,l=D.p,g=D.W.jS(a,m),y=D.$e.Dh(g).g;D.$e.Qb(g,r-f-h,y,e)&&(l=D.k);m[D.X.Hw]&&(g=D.W.kS(a,m),y=D.$e.Dh(g).g,D.$e.Qb(g,r-f-h,y,e)&&(l=D.k));if(!l&&(r=0,m[D.X.bj]&&(!n||D.xO.tH(a,m))&&(!q||q[D.X.Ry])))r=window.Math.max(0,window.Math.min(j,b.e-u-w))}if(0>b.e-u-w)var C=w,w=window.Math.max(0,b.e-u);0>b.e-u&&(u=b.e);a={nodeHeight:s,indicatorSectionWidth:u,iconSectionWidth:w,iconWidth:C,labelSectionWidth:r,drawerLayout:{rows:-1,columns:c}};return d.__layout.__nodeDrawerLayout=
a};
D.ZO.Ria=function(a){var b=a.q(),c=b.__layout.nodeIndicatorGap,d=b.__layout.nodeSingleLabelGap,e=b.__layout.nodeDualLabelGap,f=b.__layout.nodeInterLabelGap,g=b.__layout.nodeSwatchSize,h=D.W.Nb(a,0),j=b=0,l=0,m=D.o,n=D.W.j_(a,h),q=D.xO.tH(a,h),r=D.W.An(a,h);n?(q=n[D.X.Cu],j=n[D.X.Ss]+2*c,b=window.Math.max(b,q+2*c)):q&&(j=g);if(h[D.X.je])c=D.W.jS(a,h),c=D.$e.Dh(c).g,b=window.Math.max(b,c+2*d),h[D.X.Hw]&&(a=D.W.kS(a,h),a=D.$e.Dh(a).g,b=window.Math.max(b,c+a+2*e+f));else if(m=0,h[D.X.bj]&&(!n||D.xO.tH(a,h))&&
(!r||r[D.X.Ry]))m=j?j:g;r&&(l=window.Math.max(b,(0,D.Jf)()?r.preferredSizeTouch:r.preferredSize),e=(r[D.X.Ry]?r.sourcePaddingRatio:r.shapePaddingRatio)*l,f=r[D.X.Cu]?r[D.X.Cu]:l-2*e,l=(r[D.X.Ss]?r[D.X.Ss]:l-2*e)+2*e,b=window.Math.max(b,f+2*e));return{nodeHeight:b,indicatorSectionWidth:j,iconSectionWidth:l,labelSectionWidth:m}};
D.ZO.s9=function(a,b,c,d){var e=d.indicatorSectionWidth+d.iconSectionWidth+d.labelSectionWidth,f=d.nodeHeight;d=D.xO.iba(a);var g=D.xO.Hra(a),h=D.xO.Ira(a),j=new D.Te(a.j(),0,0,e,f);j.L(D.o);d&&(j.zf(d),j.Kf(d));j.Pp(new D.hg(g,D.o,2),new D.hg(h,D.o,4));j.Rp(new D.hg(h,D.o,4),D.o);j.kr(new D.hg(g,D.o,2),new D.hg(h,D.o,6));c.k(j);c.fI(j);e=new D.Te(a.j(),0,0,e,f);d&&(e.zf(d),e.Kf(d));d=D.xO.rH(a,b);e.pa(d);D.xO.Fra(a,b)&&D.xO.Gra(a,b)&&e.Ra(D.xO.Fra(a,b),D.o,D.xO.Gra(a,b));c.k(e);D.W.Qe(a,b,e,"background")};
D.ZO.t9=function(a,b,c,d){var e=D.xO.rH(a,b),f=D.I.tj(e),g=(0,D.E)(a.j())?d.labelSectionWidth+d.iconSectionWidth:0,h=D.xO.tH(a,b);if(h){var f=D.I.tj(h),j=new D.Te(a.j(),g,0,d.indicatorSectionWidth,d.nodeHeight);j.pa(h);D.ZO.i5(a,j,d);c.k(j);D.W.Qe(a,b,j,D.X.Gfa)}if(h=D.W.j_(a,b))f=h[D.X.bj]?h[D.X.bj]:f,g=h[D.X.Ry]?new D.ch(a.j(),g+d.indicatorSectionWidth/2,d.nodeHeight/2,h[D.X.Ss],h[D.X.Cu],h[D.X.Ry]):new D.dh(a.j(),h[D.X.HB],"alta",g+d.indicatorSectionWidth/2,d.nodeHeight/2,h[D.X.Ss],h[D.X.Cu]),
"none"!=h[D.X.cq]?g.L(new D.eh(h[D.X.cq],f,e)):g.pa(f),h[D.X.Ss]>d.indicatorSectionWidth&&D.ZO.i5(a,g,d),c.k(g),D.W.Qe(a,b,g,D.X.Ky)};
D.ZO.BFa=function(a,b,c,d){var e=D.xO.rH(a,b),f=D.I.tj(e),g=(0,D.E)(a.j()),h=D.W.An(a,b);if(h){var j=(h[D.X.Ry]?h.sourcePaddingRatio:h.shapePaddingRatio)*d.nodeHeight,l=h[D.X.Ss]?h[D.X.Ss]:d.iconWidth?d.iconWidth:d.iconSectionWidth-2*j,j=h[D.X.Cu]?h[D.X.Cu]:d.nodeHeight-2*j,g=d[g?"labelSectionWidth":"indicatorSectionWidth"]+window.Math.max(d.iconSectionWidth/2,d.iconWidth?d.iconWidth/2:0),m=d.nodeHeight/2,f=h[D.X.bj]?h[D.X.bj]:f,l=h[D.X.Ry]?new D.ch(a.j(),g,m,l,j,h[D.X.Ry]):new D.dh(a.j(),h[D.X.HB],
"alta",g,m,l,j);"none"!=h[D.X.cq]?l.L(new D.eh(h[D.X.cq],f,e)):l.pa(f);(0==d.indicatorSectionWidth||0==d.labelSectionWidth)&&D.ZO.i5(a,l,d);c.k(l)}D.W.Qe(a,b,l,D.X.lU)};
D.ZO.CFa=function(a,b,c,d){var e=a.q(),f=e.__layout.nodeInterLabelGap,g=e.__layout.nodeLabelOnlyStartLabelGap,h=e.__layout.nodeStartLabelGap,e=e.__layout.nodeEndLabelGap,g=d.indicatorSectionWidth||d.iconSectionWidth?h:g,h=D.xO.rH(a,b),h=D.I.tj(h),j=(0,D.E)(a.j())?d.labelSectionWidth-g:d.indicatorSectionWidth+d.iconSectionWidth+g;if(b[D.X.je]){var l=D.W.jS(a,b),m=D.$e.Dh(l).g;D.$e.Qb(l,d.labelSectionWidth-g-e,m,c)&&(D.yO.Jn(l,j,d.nodeHeight/2),l.gc()&&l.gc().A("color")?l.pa(l.gc().A("color")):l.pa(h),
D.W.Qe(a,b,l,D.X.je));if(b[D.X.Hw]){var n=D.W.kS(a,b),q=D.$e.Dh(n).g;D.$e.Qb(n,d.labelSectionWidth-g-e,q,c)&&(c=(d.nodeHeight-m-q-f)/2,D.yO.Jn(l,j,c+m/2),D.yO.Jn(n,j,c+m+f+q/2),n.gc()&&n.gc().A("color")?n.pa(n.gc().A("color")):n.pa(h),D.W.Qe(a,b,n,D.X.Hw))}}};D.ZO.F6=function(a,b){for(var c=new D.D,d=0;d<b.length;d++){var e=b[d];c.k(D.W.jS(a,e));c.k(D.W.kS(a,e))}a.k(c);for(d=c.F().e;0<c.Ja();)c.removeChild(c.ha(0));a.removeChild(c);return d};
D.ZO.i5=function(a,b,c){if(a=D.xO.iba(a)){var d=c.indicatorSectionWidth+c.iconSectionWidth+c.labelSectionWidth;c=c.nodeHeight;var e=new D.ug;(0,D.wg)(e,0,0,d,c,a,a);(0,D.xg)(b,e)}};
D.ZO.gf=function(a,b,c){var d=a.PC,e=a.yq,f=D.yO.wi(b),g=D.yO.wi(c),h=c.ta(),j=c.getParent();b.B(0);a.yq.k(c);c.za(f);var l=D.W.t_(d,b),m=D.W.t_(e,c);if(l||m){var f=new D.ug,n;if(l){n=D.yO.wi(l);n=new D.A(n.qc,n.oc,l.getWidth(),l.getHeight());var l=D.W.$f(d,b.getData()),l=D.W.Zd(d,l),l=D.W.ia(d,l,"background"),q=D.yO.wi(l),l=new D.A(q.qc,q.oc,l.getWidth(),l.getHeight());n=(0,D.Bo)(n,l)}m&&(l=D.yO.wi(m),m=new D.A(l.qc,l.oc,m.getWidth(),m.getHeight()),l=D.W.$f(e,c.getData()),l=D.W.Zd(e,l),l=D.W.ia(e,
l,"background"),q=D.yO.wi(l),l=new D.A(q.qc,q.oc,l.getWidth(),l.getHeight()),m=(0,D.Bo)(m,l),n=n?(0,D.Bo)(n,m):m);n&&((0,D.wg)(f,n.x,n.y,n.e,n.g),(0,D.xg)(c,f))}g=new D.fv(c.j(),c,new D.F(g.qc,g.oc),a.xa());(0,D.hl)(g,function(){j.k(c);c.za(h);(0,D.xg)(c,D.o)});a.add(g,1);g=new D.qn(e.j(),c,a.xa());D.ZO.dJ(g,d,e,b,c,"background");D.ZO.dJ(g,d,e,b,c,D.X.je);D.ZO.dJ(g,d,e,b,c,D.X.Hw);D.ZO.dJ(g,d,e,b,c,D.X.Gfa);D.ZO.dJ(g,d,e,b,c,D.X.Ky);D.ZO.dJ(g,d,e,b,c,D.X.lU);a.add(g,1)};
D.ZO.dJ=function(a,b,c,d,e,f){b=D.W.ia(b,d.getData(),f);c=D.W.ia(c,e.getData(),f);b&&c&&((0,D.T)(a.J,"typeFill",c,c.Rb,c.L,c.Rb()),c.L(b.Rb()))};
D.ZO.kh=function(a,b){var c=0,d=a.PC,e=a.yq,f=d.q().__layout.__nodeLayout;if(f){var g=b.getData(),h=D.W.sH(e,g[D.X.ID]);if(!(0,window.isNaN)(h)&&(h=D.W.Nb(e,h),!D.W.HH(e,h)))if(c=1,D.W.au(e)){if(g=e.q().__groups,D.W.uj(e)==D.X.Zp&&(g=g[D.W.$f(e,h)]),h=g[D.W.iS(h)])if(h=D.W.ia(e,h))h=D.yO.wi(h),f=new D.F((f.indicatorSectionWidth+f.iconSectionWidth+f.labelSectionWidth)/2,f.nodeHeight/2),a.add(new D.fv(e.j(),b,new D.F(h.qc-f.x,h.oc-f.y),a.xa()),c)}else if(g[D.X.dj]!=h[D.X.dj]||g[D.X.cj]!=h[D.X.cj]){d=
D.yO.wi(b);c=b.F();a.yq.k(b);b.za(d);g=D.W.Haa(e,h[D.X.dj],h[D.X.cj]);(d=D.W.ia(e,g.getData(),"overflow"))?(f=D.yO.wi(d),a.add(new D.fv(e.j(),b,new D.F(f.qc,f.oc),a.xa()),1)):(d=D.yO.wi(g),g=g.F(),f=new D.F((f.indicatorSectionWidth+f.iconSectionWidth+f.labelSectionWidth)/2,f.nodeHeight/2),a.add(new D.fv(e.j(),b,new D.F(d.qc+g.e/2-f.x,d.oc+g.g/2-f.y),a.xa()),1));f=new D.qn(e.j(),h,a.xa());(0,D.T)(f.J,"typeNumber",b,b.vc,b.qf,0.01);(0,D.T)(f.J,"typeNumber",b,b.Ac,b.Re,0.01);(0,D.hl)(f,function(){e.mf.k(b)});
a.add(f,2);a.add(new D.gD(e.j(),b,new D.F(c.e/2,c.g/2),a.xa()),2);a.add(new D.sn(e.j(),b,a.xa()),2);return}b.za(D.yO.wi(b));if(h=D.W.t_(d,b))f=new D.ug,d=D.yO.wi(h),h=new D.A(d.qc,d.oc,h.Ba,h.Fa),(0,D.wg)(f,h.x,h.y,h.e,h.g),(0,D.xg)(b,f);a.add(new D.sn(e.j(),b,a.xa()),c);e.mf.k(b)}};
D.ZO.qg=function(a,b){var c=2,d=a.PC,e=a.yq,f=e.q().__layout.__nodeLayout;if(f){var g=b.getData()[D.X.ID],g=D.W.sH(d,g);if(!(0,window.isNaN)(g)&&(g=D.W.Nb(d,g),!D.W.HH(d,g)&&(c=1,D.W.au(d)))){var h=d.q().__groups;D.W.uj(d)==D.X.Zp&&(h=h[D.W.$f(d,g)]);if(g=h[D.W.iS(g)])if(g=D.W.ia(d,g)){var j=b.ta(),l=b.getParent(),d=D.yO.wi(b),g=D.yO.wi(g),f=new D.F((f.indicatorSectionWidth+f.iconSectionWidth+f.labelSectionWidth)/2,f.nodeHeight/2);g.translate(-f.x,-f.y);e.k(b);b.za(g);f=new D.fv(e.j(),b,new D.F(d.qc,
d.oc),a.xa());(0,D.hl)(f,function(){b.za(j);l.k(b)});a.add(f,c)}}e=new D.qn(e.j(),b,a.xa());(0,D.T)(e.J,"typeNumber",b,b.fa,b.B,b.fa());a.add(e,c);b.B(0)}};D.ZO.Yy=function(a,b){b.Ud("img");if(!(0,D.cf)()){var c=b.fc();c&&b.$b(D.X.je,c)}};
D.IO={};D.z.l(D.IO,D.z,"DvtNBoxCategoryNodeRenderer");D.IO.P=function(a,b,c,d,e){D.IO.s9(a,b,c,d,e);var f=D.IO.t9(a,b,c,d,e);D.IO.roa(a,b,c,d,f,e);D.IO.Yy(a,c)};
D.IO.s9=function(a,b,c,d,e){b.__scale=d;b.__gap=e;e=window.Math.max(0,D.IO.vba(b));d=D.xO.iba(a);var f=D.xO.Hra(a),g=D.xO.Ira(a),h=new D.Te(a.j(),-e/2,-e/2,e,e);h.L(D.o);d&&(h.zf(d),h.Kf(d));h.Pp(new D.hg(f,D.o,2),new D.hg(g,D.o,4));h.Rp(new D.hg(g,D.o,4),D.o);h.kr(new D.hg(f,D.o,2),new D.hg(g,D.o,6));c.k(h);c.fI(h);e=new D.Te(a.j(),-e/2,-e/2,e,e);d&&(e.zf(d),e.Kf(d));a=D.xO.dH(a,b);e.pa(a);c.k(e)};D.IO.vba=function(a){return a.__scale*window.Math.sqrt(a.nodeIndices.length)-a.__gap};
D.IO.t9=function(a,b,c,d,e){var f=D.p,g=a.q().__layout.markerGap,h=(0,D.E)(a.j()),j=d*window.Math.sqrt(b.nodeIndices.length)-e;d=D.xO.dH(a,b);var l=D.I.tj(d),m=j/4,n=1,q=h?j/2-m:-j/2;(e=D.xO.Bba(a,b))&&(n=window.Math.min(m/(e[D.X.Ss]+2*g),j/(e[D.X.Cu]+2*g)));if(g=D.xO.QR(a,b))l=D.I.tj(g),f=new D.Te(a.j(),q,-j/2,m,j),f.pa(g),c.k(f),f=D.k;e&&(f=e[D.X.bj]?e[D.X.bj]:l,h=new D.dh(a.j(),e[D.X.HB],"alta",(h?1:-1)*(j-m)/2,0,e[D.X.Ss]*n,e[D.X.Cu]*n),e[D.X.cq]&&"none"!=e[D.X.cq]?h.L(new D.eh(e[D.X.cq],f,d)):
h.pa(f),c.k(h),D.W.Qe(a,b,h,D.X.Ky),f=D.k);return f};
D.IO.roa=function(a,b,c,d,e,f){var g=a.q().__layout.categoryNodeLabelGap,h=(0,D.E)(a.j()),j=D.xO.c_(a),l=D.W.aM(a),m=D.W.ia(a,b,"label");if(l){if(l=b.highlightedCount,0==l){m&&m.we("");c.B(j);return}}else l=b.nodeIndices.length;d=d*window.Math.sqrt(b.nodeIndices.length)-f;e=e?0.75*d:d;h=(h?-1:1)*(d-e)/2;f=D.xO.dH(a,b);f=D.I.tj(f);j=new D.A(0,0,e-2*g,d-2*g);m?m.we(""+l):(m=D.yO.$k(a.j(),""+l,D.xO.DIa(a),"center","middle"),D.W.Qe(a,b,m,"label"));a=m.Tv(j);m.Ie(a);D.$e.Qb(m,e-2*g,d-2*g,c)&&(D.yO.Jn(m,
h,0),m.pa(f))};D.IO.gf=function(a,b,c){var d=D.yO.wi(b),e=D.yO.wi(c),f=c.ta(),g=c.getParent();b.B(0);a.yq.k(c);c.za(d);b=new D.fv(c.j(),c,new D.F(e.qc,e.oc),a.xa());(0,D.hl)(b,function(){g.k(c);c.za(f)});a.add(b,1)};D.IO.kh=function(a,b){var c=1,d=a.PC,e=a.yq;D.IO.Gsa(d,e)&&D.IO.Dsa(d,e)&&(c=0);d=new D.LD(e.j(),b,new D.F(0.01,0.01),a.xa());a.add(d,c);d=new D.sn(e.j(),b,a.xa());a.add(d,c);b.za(D.yO.wi(b));e.mf.k(b)};
D.IO.qg=function(a,b){var c=1,d=a.PC,e=a.yq;D.IO.Gsa(d,e)&&D.IO.Dsa(d,e)&&(c=2);b.qf(0.01);b.Re(0.01);d=new D.LD(e.j(),b,new D.F(1,1),a.xa());a.add(d,c);e=new D.qn(e.j(),b,a.xa());(0,D.T)(e.J,"typeNumber",b,b.fa,b.B,b.fa());a.add(e,c);b.B(0)};D.IO.Dsa=function(a,b){var c=D.W.uj(a),d=D.W.uj(b),e=D.W.Oe(a),f=D.W.Oe(b),g=D.p;if(c==d&&e==f){g=D.k;for(c=0;c<e;c++)if(d=D.W.iS(D.W.Nb(a,c)),f=D.W.iS(D.W.Nb(b,c)),d!=f){g=D.p;break}}return g};
D.IO.Gsa=function(a,b){var c=D.W.Cp(a),d=D.W.Bp(a),e=D.W.Cp(b),f=D.W.Bp(b);return c==e&&d==f};D.IO.Yy=function(a,b){b.Ud("img");if(!(0,D.cf)()){var c=b.fc();c&&b.$b(D.X.je,c)}};
D.XO={};D.z.l(D.XO,D.z,"DvtNBoxDrawerRenderer");D.XO.P=function(a,b,c,d){d=D.XO.hJa(a,b,d);b.__drawerBounds=d;(0,D.pk)(c,d.x,d.y);d=new D.Bg(a.j(),c,new D.A(-1,-1,d.e+2,d.g+2));D.W.Qe(a,b,d,"focusEffect");D.XO.dFa(a,b,c);D.XO.uFa(a,b,c);D.XO.Yy(a,b,c)};
D.XO.uFa=function(a,b,c){var d=a.q(),e=d.__layout.drawerButtonGap,f=d.__layout.drawerStartGap,g=d.__layout.drawerLabelGap,h=d.__layout.drawerCountHorizontalGap,j=d.__layout.drawerCountVerticalGap,l=d.__layout.drawerHeaderHeight,m=d.__layout.nodeIndicatorGap,n=d.__layout.nodeSwatchSize,q=(0,D.E)(a.j()),r=D.W.Qq(a,b[D.X.ID]),s=r.nodeIndices.length;b=b.__drawerBounds;var u=d._resources.close_ena,w=u.width;if(b.e>w){var y=d._resources.close_ovr,C=d._resources.close_dwn,d=u.height,u=new D.Ue(a.j(),u.src,
0,0,u.width,u.height),y=new D.Ue(a.j(),y.src,0,0,y.width,y.height),C=new D.Ue(a.j(),C.src,0,0,C.width,C.height),y=new D.Oe(a.j(),u,y,C,D.o,D.o,c.$$,c),C=q?window.Math.min((b.e-w)/2,e):window.Math.max((b.e-w)/2,b.e-e-w);(0,D.pk)(y,C,l/2-d/2);c.k(y)}var d=D.xO.dH(a,r),y=D.I.tj(d),u=(C=D.xO.QR(a,r))?D.I.tj(C):y,O=D.xO.Bba(a,r),M=n,J=1;if(O)var R=O[D.X.Ss],J=n/O[D.X.Cu],M=J*R,u=O[D.X.bj]?O[D.X.bj]:u;var N=D.xO.iJa(a),R=q?"right":"left",s=D.yO.$k(a.j(),""+s,D.xO.jJa(a),R,"middle"),Y=s.Eb(),j=Y.g+2*j,n=
O?M+2*m:C?n:0,M=Y.e+2*h,m=n+M,ha;b.e-w-2*e-f>m&&(ha=D.K.ZH(0,0,m,j,N,N,N,N),ha=new D.Jh(a.j(),ha),ha.pa(d),c.k(ha),Y=q?M:0,0<n&&(C&&(N=D.K.ZH(Y,0,n,j,q?0:N,q?N:0,q?N:0,q?0:N),N=new D.Jh(a.j(),N),N.pa(C),ha.k(N)),O&&(J=new D.dh(a.j(),O[D.X.HB],"alta",Y+n/2,j/2,O[D.X.Ss]*J,O[D.X.Cu]*J),O[D.X.cq]&&"none"!=O[D.X.cq]?J.L(new D.eh(O[D.X.cq],u,C?C:d)):J.pa(u),ha.k(J))),ha.k(s),s.pa(y),D.yO.Jn(s,q?M-h:n+h,j/2));h=D.W.ia(a,r).Nc();a=D.yO.$k(a.j(),h,D.xO.kJa(a),R,"middle");h=0;D.$e.Qb(a,b.e-f-g-m-2*e-w,l,c)&&
(D.yO.Jn(a,q?b.e-f:f,l/2),h=a.Eb().e+g);ha&&(0,D.pk)(ha,q?b.e-f-m-h:f+h,(l-j)/2)};
D.XO.dFa=function(a,b,c){var d=a.q(),e=d.__layout.gridGap,f=d.__layout.drawerHeaderHeight,g=b.__drawerBounds,d=(0,D.E)(a.j()),h=D.xO.gJa(a),j=D.xO.fJa(a),h=D.K.ZH(0,0,g.e,g.g,h,h,h,h),h=new D.Jh(a.j(),h);D.yO.L(h,D.xO.eJa(a));h.Ra(j);(0,D.Ei)(h);c.k(h);D.W.Qe(a,b,h,"background");b.__childArea=new D.A(e,f+e,window.Math.max(g.e-2*e,0),window.Math.max(g.g-f-2*e,0));g=new D.MA(a.j(),g.e,g.g-f);(0,D.pk)(g,0,f);c.k(g);c.jda(g);var l=["normal"];c=D.xO.c_(a);f=D.W.aM(a);g={};if(f)for(j=0;j<f.length;j++)g[f[j][D.X.ID]]=
D.k;var h=D.W.A_(a),m={};if(h)for(j=0;j<h.length;j++)m[h[j]]=D.k;f?l=h?["highlighted-selected","highlighted-unselected","unhighlighted-selected","unhighlighted-unselected"]:["highlighted-unselected","unhighlighted-unselected"]:h&&(l=["unhighlighted-selected","unhighlighted-unselected"]);for(var j=[],n=D.W.Qq(a,b[D.X.ID]),q=n.nodeIndices.length,r=0;r<l.length;r++)for(h=0;h<q;h++){var s=D.W.Nb(a,n.nodeIndices[h]);("normal"==l[r]||"highlighted-selected"==l[r]&&g[s[D.X.ID]]&&m[s[D.X.ID]]||"highlighted-unselected"==
l[r]&&g[s[D.X.ID]]&&!m[s[D.X.ID]]||"unhighlighted-selected"==l[r]&&!g[s[D.X.ID]]&&m[s[D.X.ID]]||"unhighlighted-unselected"==l[r]&&!g[s[D.X.ID]]&&!m[s[D.X.ID]])&&j.push(s)}l=D.ZO.mHa(a,b,j);m=l.indicatorSectionWidth+l.iconSectionWidth+l.labelSectionWidth+e;n=l.nodeHeight+e;q=D.W.ia(a,b).Wj();for(h=0;h<j.length;h++)if(s=j[h],0!=l.drawerLayout[D.X.nE]&&0!=l.drawerLayout[D.X.e3]){var r=D.DO.newInstance(a,s),u=b.__childArea.x+(b.__childArea.e-l.drawerLayout[D.X.nE]*m+e)/2,w=e,y=h%l.drawerLayout[D.X.nE];
d&&(y=l.drawerLayout[D.X.nE]-y-1);(0,D.pk)(r,u+m*y,w+n*window.Math.floor(h/l.drawerLayout[D.X.nE]));r.P(q.X,l);f&&!g[s[D.X.ID]]&&r.B(c);if(r=0<h?j[h-1]:D.o)s.__prev=r,r.__next=s}(0,D.NA)(q)};
D.XO.hJa=function(a,b,c){var d=a.q(),e=d.__layout.gridGap,d=d.__layout.__cellLayout,f=new D.A(c.x+e,c.y+e,window.Math.max(c.e-2*e,0),window.Math.max(c.g-2*e,0));D.W.uj(a)==D.X.Zp&&(b=(0,window.parseInt)(b.id.substring(0,b[D.X.ID].indexOf(":"))),D.W.BM(a,b)&&(f=D.W.Zd(a,b),b=D.W.cg(a,f[D.X.dj]),f=D.W.vo(a,f[D.X.cj]),a=D.HO.$Z(a,b,f,d,c),f=new D.A(a.x+e,a.y+e+d.headerSize,window.Math.max(a.e-2*e,0),window.Math.max(a.g-d.headerSize-2*e,0))));return f};D.XO.gf=function(){window.console.log("********************* DvtNBoxDrawerRenderer.animateUpdate *********************")};
D.XO.kh=function(a,b){var c=a.yq,d=b.getData().__drawerBounds,e=b.getData()[D.X.ID],f=D.W.Qq(c,e);if(f){var e=D.IO.vba(f),g=e/d.e,d=e/d.g;if(f=D.W.ia(c,f))f=D.yO.wi(f),e=new D.hj(g,0,0,d,f.qc-e/2,f.oc-e/2),g=new D.qn(c.j(),b,a.xa()),(0,D.T)(g.J,"typeMatrix",b,b.ta,b.za,e),a.add(g,1)}c.mf.k(b);c=new D.sn(c.j(),b,a.xa());a.add(c,1)};
D.XO.qg=function(a,b){var c=a.yq,d=b.getData().__drawerBounds,e=b.getData()[D.X.ID],f=D.W.Qq(c,e);if(f){var e=D.IO.vba(f),g=e/d.e,d=e/d.g;if(f=D.W.ia(c,f)){f=D.yO.wi(f);e=new D.hj(g,0,0,d,f.qc-e/2,f.oc-e/2);g=new D.qn(c.j(),b,a.xa());(0,D.T)(g.J,"typeMatrix",b,b.ta,b.za,b.ta());var h=b.getParent();c.k(b);(0,D.hl)(g,function(){h.k(b)});b.za(e);a.add(g,1)}}b.B(0);c=new D.Vm(c.j(),b,a.xa());a.add(c,1)};
D.XO.Yy=function(a,b,c){a=(0,D.Jf)()?D.W.ia(a,b,"background"):c;a.Ud("img");(0,D.cf)()||(c=c.fc())&&a.$b(D.X.je,c)};
D.W={};D.z.l(D.W,D.z,"DvtNBoxDataUtils");
D.W.Mca=function(a){var b=a.q(),c=b[D.X.l1],d={};if(c)for(var e=0;e<c.length;e++){var f=c[e],g=f[D.X.dj];d[g]||(d[g]={});var h=f[D.X.cj];d[g][h]=f}for(var f=[],e={},c={},j=0;j<D.W.Xj(a);j++)g=D.W.DD(a,j),e[g[D.X.ID]]=j;b.__rowMap=e;for(var l=0;l<D.W.lh(a);l++)h=D.W.pD(a,l),c[h[D.X.ID]]=l;b.__columnMap=c;for(j=0;j<D.W.Xj(a);j++){g=D.W.DD(a,j);g=g[D.X.ID];for(l=0;l<D.W.lh(a);l++)h=D.W.pD(a,l),h=h[D.X.ID],d[g]&&d[g][h]?f.push(d[g][h]):f.push({row:g,column:h})}b[D.X.l1]=f;d={};g=D.p;for(h=0;h<D.W.Oe(a);h++)if(f=
D.W.Nb(a,h),d[f[D.X.ID]]=h,!g&&(f[D.X.xN]||f._groupCategories||f._groupLabels))g=D.k;b.__nodeMap=d;b.__grouping="none"!=b[D.X.Jea]?g:D.p;D.W.au(a)&&D.W.uj(a)==D.X.wI&&(b[D.X.Os]=D.o,D.W.RZ(a,D.X.Os),b[D.X.Ns]=D.o,D.W.RZ(a,D.X.Ns));if(b[D.X.Os]&&(0,window.isNaN)(e[b[D.X.Os]])||b[D.X.Ns]&&(0,window.isNaN)(c[b[D.X.Ns]]))b[D.X.Os]=D.o,D.W.RZ(a,D.X.Os),b[D.X.Ns]=D.o,D.W.RZ(a,D.X.Ns);if((a=b[D.X.nU])&&a.sections){var m="color iconFill iconShape iconPattern indicatorColor indicatorIconColor indicatorIconShape indicatorIconPattern".split(" ");
a.sections=a.sections.slice(0);a.sections.sort(function(a,b){return D.H.wa(m,a.type)-D.H.wa(m,b.type)});c=b[D.X.tE];a.hideAndShowBehavior="on";a.textStyle=b.styleDefaults.__legendDefaults.itemStyle;a.layout={rowGap:2};a.symbolWidth=16;a.symbolHeight=16;for(e=0;e<a.sections.length;e++){d=a.sections[e];d.titleStyle=b.styleDefaults.__legendDefaults.sectionStyle;for(g=0;g<d.items.length;g++)h=d.items[g],h.categoryVisibility=-1!=D.H.wa(c,h.categories&&0<h.categories.length?h.categories[0]:h.id)?"hidden":
D.o,h.indicatorColor&&(h.color=h.indicatorColor),h.color||(h.color=b.styleDefaults.__legendDefaults.markerColor),h.shape&&(h.markerShape=h.shape)}}};D.W.lh=function(a){return a.q()[D.X.nE].length};D.W.Xj=function(a){return a.q()[D.X.e3].length};D.W.PIa=function(a,b){var c=D.W.pD(a,D.W.vo(a,b));return c&&c[D.X.je]?c[D.X.je]:D.o};D.W.vKa=function(a,b){var c=D.W.DD(a,D.W.cg(a,b));return c&&c[D.X.je]?c[D.X.je]:D.o};D.W.Haa=function(a,b,c){return(b=D.W.Zd(a,D.W.Rqa(a,b,c)))?D.W.ia(a,b):D.o};
D.W.Rqa=function(a,b,c){return D.W.vo(a,c)+D.W.cg(a,b)*D.W.lh(a)};D.W.pD=function(a,b){return a.q()[D.X.nE][b]};D.W.DD=function(a,b){return a.q()[D.X.e3][b]};D.W.Cp=function(a){return a.q()[D.X.Os]};D.W.Bp=function(a){return a.q()[D.X.Ns]};D.W.cg=function(a,b){return a.q().__rowMap[b]};D.W.vo=function(a,b){return a.q().__columnMap[b]};D.W.Zd=function(a,b){return a.q()[D.X.l1][b]};D.W.Oe=function(a){return a.q()[D.X.rU]?a.q()[D.X.rU].length:0};D.W.Nb=function(a,b){return a.q()[D.X.rU][b]};
D.W.sH=function(a,b){return a.q().__nodeMap[b]};D.W.$f=function(a,b){var c=D.W.cg(a,b[D.X.dj]),d=D.W.vo(a,b[D.X.cj]),e=D.W.lh(a);return d+c*e};D.W.An=function(a,b){return b[D.X.lU]?D.xO.UKa(a,b[D.X.lU]):D.o};D.W.j_=function(a,b){return b[D.X.Ky]?D.xO.VKa(a,b[D.X.Ky]):D.o};D.W.A_=function(a){return a.q()[D.X.uga]};D.W.SNa=function(a,b){a.q()[D.X.uga]=b};D.W.aM=function(a){var b,c=a.q()[D.X.k2];if(c&&0<c.length){b=[];for(c=0;c<D.W.Oe(a);c++){var d=D.W.Nb(a,c);D.W.rMa(a,d)&&b.push(d)}}return b};
D.W.au=function(a){return a.q().__grouping};D.W.Tq=function(a){return a.q()[D.X.fva]};D.W.uj=function(a){return a.q()[D.X.Jea]};D.W.iS=function(a){return a[D.X.xN]?a[D.X.xN]:(a=a._groupCategories)&&0<a.length?a.join(";"):D.o};D.W.gLa=function(a,b){if(!(0,window.isNaN)(b[D.X.Sga]))return b[D.X.Sga];var c=D.W.lh(a);return(D.W.vo(a,b[D.X.cj])+0.5)/c};D.W.lLa=function(a,b){if(!(0,window.isNaN)(b[D.X.Xga]))return b[D.X.Xga];var c=D.W.Xj(a);return(D.W.cg(a,b[D.X.dj])+0.5)/c};D.W.eKa=function(a){return a.q()[D.X.Mva]};
D.W.cKa=function(a){return a.q()[D.X.Lva]};D.W.Dm=function(a){return a.q()[D.X.Aw]};D.W.Qq=function(a,b){var c=D.W.uj(a),d=a.q().__groups,e=b;c==D.X.Zp&&(c=b.substring(0,b.indexOf(":")),e=b.substring(b.indexOf(":")+1),d=d[c]);return d?d[e]:D.o};
D.W.Pqa=function(a,b){if(b.__labels)return b.__labels;var c=D.W.Nb(a,b.nodeIndices[0]);if(c[D.X.xN])return b.__labels=[c[D.X.xN]];b.__labels=[];if(c._groupCategories)for(var d=a.q()._groupLabels,e=0;e<c._groupCategories.length;e++)b.__labels[e]=d&&d[c._groupCategories[e]]?d[c._groupCategories[e]]:c._groupCategories[e];return b.__labels};D.W.Qe=function(a,b,c,d){a=a.Yc();d=d?"__displayable:"+d:"__displayable";b[d]?a[b[d]]=c:(b[d]=a.length,a.push(c))};
D.W.ia=function(a,b,c){if(!b)return D.o;b=b[c?"__displayable:"+c:"__displayable"];a=a.Yc();return b==D.o?D.o:a[b]};D.W.Fsa=function(a){return"off"!=a.q().cellMaximize};D.W.EIa=function(a){return"counts"==a.q().cellContent?"counts":"auto"};D.W.NA=function(a,b){var c=D.W.Cp(a),d=D.W.Bp(a);if(!c&&!d)return D.p;var e=D.W.Zd(a,b),f=e[D.X.dj],e=e[D.X.cj];return c&&d?c!=f||d!=e:c!=f&&d!=e};D.W.BM=function(a,b){var c=D.W.Cp(a),d=D.W.Bp(a),e=D.W.Zd(a,b),f=e[D.X.cj];return c==e[D.X.dj]&&d==f};D.W.eS=function(a){return a.q()._legend};
D.W.HH=function(a,b){var c=a.q();c[D.X.tE]&&!c.__hiddenMap&&(c.__hiddenMap=D.H.ZG(c[D.X.tE]));return D.H.yM(c.__hiddenMap,b[D.X.Au])};D.W.rMa=function(a,b){var c=a.q();c[D.X.k2]&&!c.__highlightedMap&&(c.__highlightedMap=D.H.ZG(c[D.X.k2]));return"all"==c[D.X.l2]?D.H.qsa(c.__highlightedMap,b[D.X.Au]):D.H.yM(c.__highlightedMap,b[D.X.Au])};
D.W.t_=function(a,b){if(!b)return D.o;var c=D.W.Dm(a);if(c&&(c=D.W.ia(a,c)))return c.Wj();c=D.W.$f(a,b.getData());return D.W.BM(a,c)?(c=D.W.Zd(a,c),D.W.ia(a,c).Wj()):D.o};D.W.jS=function(a,b){if(!b[D.X.je])return D.o;var c=D.W.ia(a,b,D.X.je);if(c)return c;c=(0,D.E)(a.j())?"right":"left";c=D.yO.$k(a.j(),b[D.X.je],D.xO.$Ja(a),c,"middle");D.W.Qe(a,b,c,D.X.je);return c};
D.W.kS=function(a,b){if(!b[D.X.Hw])return D.o;var c=D.W.ia(a,b,D.X.Hw);if(c)return c;c=(0,D.E)(a.j())?"right":"left";c=D.yO.$k(a.j(),b[D.X.Hw],D.xO.aKa(a),c,"middle");D.W.Qe(a,b,c,D.X.Hw);return c};D.W.RZ=function(a,b){var c=new D.hr;(0,D.El)(c,b,D.o);a.Pd(c)};D.W.gM=function(a){var b=D.o,c=D.W.Cp(a),d=D.W.Bp(a);c&&d&&(b=D.W.lh(a),b=D.W.vo(a,d)+b*D.W.cg(a,c));return b};
D.W.gMa=function(a,b){var c=D.p,d=D.W.A_(a);if(d){for(var e={},c=0;c<d.length;c++)e[d[c]]=D.k;for(var d=b.getData().nodeIndices,c=D.k,f=0;f<d.length;f++){var g=D.W.Nb(a,d[f]);if(!e[g[D.X.ID]]){c=D.p;break}}}return c};
D.W.Z$=function(a,b,c,d){c=b instanceof D.BO||b instanceof D.CO?(0,D.L)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.L)("DvtNBoxBundle","GROUP_NODE"),c]):c;var e=[];d?e.push((0,D.L)("DvtUtilBundle","STATE_SELECTED")):e.push((0,D.L)("DvtUtilBundle","STATE_UNSELECTED"));b instanceof D.BO?(a=b.getData().nodeIndices.length,e.push((0,D.L)("DvtUtilBundle","STATE_COLLAPSED")),e.push((0,D.L)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.L)("DvtNBoxBundle","SIZE"),a]))):b instanceof D.CO&&(a=D.W.Qq(a,b.getData()[D.X.ID]).nodeIndices.length,
e.push((0,D.L)("DvtUtilBundle","STATE_EXPANDED")),e.push((0,D.L)("DvtUtilBundle","COLON_SEP_LIST",[(0,D.L)("DvtNBoxBundle","SIZE"),a])));return(0,D.ok)(c,e)};D.W.e_=function(a,b){var c=D.o;if(0<b.Ja()){var c=b.ha(0),d;do c instanceof D.DO?d=c.getData().__prev:c instanceof D.OO&&(d=c.__prev),c=d?D.W.ia(a,d):c;while(d)}return c};D.W.sra=function(a,b){var c=D.o,d=b.Ja();if(0<d){c=b.ha(d-1);do c=(d=c instanceof D.DO?c.getData().__next:D.o)?D.W.ia(a,d):c;while(d)}return c};
D.W.Era=function(a,b,c){c=39==c.keyCode||40==c.keyCode?D.k:D.p;var d;b instanceof D.DO?d=c?b.getData().__next:b.getData().__prev:b instanceof D.OO&&(d=c?D.o:b.__prev);return d?D.W.ia(a,d):b};
D.xO={};D.z.l(D.xO,D.z,"DvtNBoxStyleUtils");D.xO.waa=function(a){if(!a.$U)return"none";a=a.q()[D.X.Qda];"auto"==a&&(a=D.dl.uw);return a};D.xO.vaa=function(a){return!a.$U?"none":a.q()[D.X.Pda]};D.xO.xa=function(a){return(0,D.hp)(a.q()[D.X.be][D.X.mua])/1E3};D.xO.QIa=function(a,b){var c=a.q()[D.X.be][D.X.oua],d=D.W.pD(a,b);return d[D.X.My]?D.pl.bd(new D.G(d[D.X.My]),c):c};D.xO.wKa=function(a,b){var c=a.q()[D.X.be][D.X.dwa],d=D.W.DD(a,b);return d[D.X.My]?D.pl.bd(new D.G(d[D.X.My]),c):c};
D.xO.Tqa=function(a,b){var c=a.q(),d=D.X.qwa,e=D.W.Cp(a),f=D.W.Bp(a);if(D.W.NA(a,b))d="minimizedStyle";else if((e||f)&&!D.W.NA(a,b))d="maximizedStyle";c=c[D.X.be][D.X.mE][d];e=D.W.Zd(a,b);return e[d]?D.pl.bd(new D.G(e[d]),c):c};D.xO.Jaa=function(a,b){var c=a.q()[D.X.be][D.X.mE][D.X.My],d=D.W.Zd(a,b);return d[D.X.My]?D.pl.bd(new D.G(d[D.X.My]),c):c};D.xO.Sqa=function(a,b){return b[D.X.o3]?b[D.X.o3]:a.q()[D.X.be][D.X.mE][D.X.o3]};D.xO.Iaa=function(a){return a.q()[D.X.be][D.X.mE].countLabelStyle};
D.xO.Qqa=function(a){return a.q()[D.X.be][D.X.mE].bodyCountLabelStyle};D.xO.FIa=function(a){return a.q()[D.X.be][D.X.mE].dropTargetStyle};D.xO.$Ja=function(a){return a.q()[D.X.be][D.X.bk][D.X.My]};D.xO.aKa=function(a){return a.q()[D.X.be][D.X.bk][D.X.jwa]};D.xO.rH=function(a,b){return b[D.X.bj]?b[D.X.bj]:a.q()[D.X.be][D.X.bk][D.X.bj]};D.xO.Fra=function(a,b){var c=b[D.X.Fy]?b[D.X.Fy]:a.q()[D.X.be][D.X.bk][D.X.Fy];return c?c:D.o};
D.xO.Gra=function(a,b){var c=b[D.X.k1]?b[D.X.k1]:a.q()[D.X.be][D.X.bk][D.X.k1];return c?c:D.o};D.xO.tH=function(a,b){return b[D.X.vE]?b[D.X.vE]:a.q()[D.X.be][D.X.bk][D.X.vE]};D.xO.UKa=function(a,b){return D.pl.bd(b,a.q()[D.X.be][D.X.bk][D.X.Eva])};D.xO.VKa=function(a,b){return D.pl.bd(b,a.q()[D.X.be][D.X.bk][D.X.GN])};D.xO.c_=function(a){return a.q()[D.X.be][D.X.bk].alphaFade};D.xO.QQa=function(a){return a.q()[D.X.be].__scrollbar};
D.xO.dH=function(a,b){if("none"==D.W.uj(a)||D.W.Tq(a)&&-1==D.W.Tq(a).indexOf("color"))return a.q()[D.X.be][D.X.bk][D.X.bj];if(b.otherNode)return D.W.cKa(a);var c=b.nodeIndices,d=D.W.Nb(a,c[0])[D.X.bj];if(!d)return a.q()[D.X.be][D.X.bk][D.X.bj];for(var e=1;e<c.length;e++){var f=D.W.Nb(a,c[e]);if(d!=f[D.X.bj])return a.q()[D.X.be][D.X.bk][D.X.bj]}return d};
D.xO.QR=function(a,b){if("none"==D.W.uj(a)||D.W.Tq(a)&&-1==D.W.Tq(a).indexOf("indicatorColor"))return D.o;var c=b.nodeIndices,d=D.W.Nb(a,c[0])[D.X.vE];if(!d)return a.q()[D.X.be][D.X.bk][D.X.vE];for(var e=1;e<c.length;e++){var f=D.W.Nb(a,c[e]);if(d!=f[D.X.vE])return a.q()[D.X.be][D.X.bk][D.X.vE]}return d};
D.xO.Bba=function(a,b){if("none"==D.W.uj(a)||D.W.Tq(a)&&-1==D.W.Tq(a).indexOf("indicatorIconShape")&&-1==D.W.Tq(a).indexOf("indicatorIconColor")&&-1==D.W.Tq(a).indexOf("indicatorIconPattern"))return D.o;var c={},d=b.nodeIndices,e=D.W.Nb(a,d[0])[D.X.Ky];if(!e)return D.o;var f=D.k;if(!D.W.Tq(a)||-1!=D.W.Tq(a).indexOf("indicatorIconShape")){for(var g=e[D.X.HB],h=1;h<d.length;h++){var j=D.W.Nb(a,d[h])[D.X.Ky];j&&g!=j[D.X.HB]&&(f=D.p)}c[D.X.HB]=f?g:a.q()[D.X.be][D.X.bk][D.X.GN][D.X.HB]}f=D.k;if(!D.W.Tq(a)||
-1!=D.W.Tq(a).indexOf("indicatorIconColor")){g=e[D.X.bj];for(h=1;h<d.length;h++)(j=D.W.Nb(a,d[h])[D.X.Ky])&&g!=j[D.X.bj]&&(f=D.p);c[D.X.bj]=f?g:a.q()[D.X.be][D.X.bk][D.X.GN][D.X.bj]}f=D.k;if(!D.W.Tq(a)||-1!=D.W.Tq(a).indexOf("indicatorIconPattern")){e=e[D.X.cq];for(g=1;g<d.length;g++)(j=D.W.Nb(a,d[g])[D.X.Ky])&&e!=j[D.X.cq]&&(f=D.p);c[D.X.cq]=f?e:a.q()[D.X.be][D.X.bk][D.X.GN][D.X.cq]}return D.pl.bd(c,a.q()[D.X.be][D.X.bk][D.X.GN])};D.xO.eJa=function(a){return a.q()[D.X.be].__drawerDefaults.background};
D.xO.KQa=function(a){return a.q()[D.X.be].__drawerDefaults.headerBackground};D.xO.fJa=function(a){return a.q()[D.X.be].__drawerDefaults[D.X.Fy]};D.xO.gJa=function(a){return a.q()[D.X.be].__drawerDefaults[D.X.Sda]};D.xO.kJa=function(a){return a.q()[D.X.be].__drawerDefaults[D.X.My]};D.xO.jJa=function(a){return a.q()[D.X.be].__drawerDefaults.countLabelStyle};D.xO.iJa=function(a){return a.q()[D.X.be].__drawerDefaults.countBorderRadius};D.xO.DIa=function(a){return a.q()[D.X.be].__categoryNodeDefaults.labelStyle};
D.xO.iba=function(a){return a.q()[D.X.be][D.X.bk][D.X.Sda]};D.xO.Hra=function(a){return a.q()[D.X.be][D.X.bk].hoverColor};D.xO.Ira=function(a){return a.q()[D.X.be][D.X.bk].selectionColor};D.xO.FJa=function(a,b){var c=b[D.X.C2];c||(c=a.q()[D.X.be][D.X.mE][D.X.C2]);var d=(0,D.E)(a.j());return"end"==c?d?"left":"right":"center"==c?"center":d?"right":"left"};

  return D;
});