/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.wQ=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtPictoChart",D.wQ);D.z.l(D.wQ,D.sj,"DvtPictoChart");D.wQ.newInstance=function(a,b,c){return new D.wQ(a,b,c)};D.wQ.prototype.Init=function(a,b,c){D.wQ.o.Init.call(this,a,b,c);this.Ia=new D.xQ(this);this.Ia.me(this);(0,D.Jf)()||(0,D.xj)(this.Ia,new D.yQ(this.Ia));this.rf=new D.zQ;this.Za=[]};D.wQ.prototype.vC=function(a,b){if(!a||!b){var c=D.AQ.bl(this,a,b);this.f7=c;a||(a=c.Ul?c.aqa*c.EZ:0);b||(b=c.Ul?c.Kta*c.O0:0)}return new D.Cg(a,b)};
D.wQ.prototype.P=function(a,b,c){this.Og=this.X;var d=this.nn,e=this.Ga?this.Ga:0,f=this.Ta?this.Ta:0;this.Ia.Cc();this.Za=[];this.nn=[];this.f7=D.o;this.jn&&(this.X.removeChild(this.jn),this.jn=D.o);this.Ua&&this.Ua.stop();this.vd(a);var g=this.j();if(!b&&!c){if(g.Ka.style.display="block",b=this.vC(),D.B.xT(g,b.e,b.g),c=D.B.lba(g),b.e==c.e&&b.g!=c.g?(this.Ta=c.g,b=this.vC(D.o,this.Ta),D.B.xT(g,b.e,this.Ta),this.Ga=D.B.lba(g).e):b.e!=c.e&&b.g==c.g?(this.Ga=c.e,b=this.vC(this.Ga,D.o),D.B.xT(g,this.Ga,
b.g),this.Ta=D.B.lba(g).g):(this.Ga=c.e,this.Ta=c.g),this.Ga!=b.e||this.Ta!=b.g)this.f7=D.o}else this.Ga=b,this.Ta=c;this.X=new D.D(g);this.k(this.X);D.AQ.P(this,this.X,new D.A(0,0,this.Ga,this.Ta),this.f7);if(this.Og)"none"!=this.D.animationOnDataChange&&a&&(a=new D.Sm(g,D.o),(0,D.Tm)(a,d,this.nn),this.Ua=a.Oq());else{var h=this.D.animationOnDisplay,d=this.xa();a=this.j();b=new D.A(0,0,this.Ga,this.Ta);if(D.dl.isSupported(h))d=D.dl.by(a,h,this.X,b,d);else{c=[];if("popIn"==h)for(h=0;h<this.nn.length;h++){var j=
this.nn[h];c.push(new D.pn(a,j,D.k,d))}else if("none"!=h){for(h=0;h<this.nn.length;h++){var j=this.nn[h],l=new D.qn(a,j,d),m,n;D.AQ.Sa(this)?(m=D.AQ.cca(this)?this.Ga:0,n=j.Eg(),j.ru(m),(0,D.T)(l.J,"typeNumber",j,j.Eg,j.ru,n)):(m=D.AQ.bca(this)?this.Ta:0,n=j.Fg(),j.su(m),(0,D.T)(l.J,"typeNumber",j,j.Fg,j.su,n));c.push(l)}c.push(D.dl.by(a,D.dl.uw,this.X,b,d))}d=0<c.length?new D.on(a,c):D.o}this.Ua=d}this.Ua?(D.B.xT(g,window.Math.max(e,this.Ga),window.Math.max(f,this.Ta)),this.Ia.gi(this),this.jn&&
this.X.removeChild(this.jn),this.Ua.ie(this.una,this),this.Ua.play()):this.una();this.Sn()};D.wQ.prototype.render=D.wQ.prototype.P;D.x=D.wQ.prototype;D.x.vd=function(a){a?this.D=this.rf.Vj(a):this.D||(this.D=(0,D.zj)(this));(0,D.Zk)()||(this.D.animationOnDisplay="none",this.D.animationOnDataChange="none");a=this.D.selectionMode;this.Hb="single"==a?new D.$k("s"):"multiple"==a?new D.$k("m"):D.o;this.Ia.yu(this.Hb)};
D.x.una=function(){this.Og&&(this.removeChild(this.Og),this.Og.Q(),this.Og=D.o);this.Ua&&(this.Ua=D.o,this.Ia.me(this),this.jn&&this.X.k(this.jn));D.B.xT(this.j(),this.Ga,this.Ta);(0,D.Bj)(this.Ia,this.Za[0]);this.Hb&&(0,D.Il)(this.Hb,this.D.selection,this.Za);(0,D.ql)(this.D.highlightedCategories,this.Za,"any"==this.D.highlightMatch)};D.x.ka=(0,D.v)("Ia");D.x.Uca=(0,D.ba)("Za");D.x.Bh=(0,D.v)("Za");D.x.xa=function(){return(0,D.hp)(this.D.animationDuration)/1E3};
D.x.Q=function(){this.Ia&&(this.Ia.gi(this),this.Ia.Q(),this.Ia=D.o);D.wQ.o.Q.call(this)};D.wQ.prototype.destroy=D.wQ.prototype.Q;D.wQ.prototype.Ge=function(a){var b=this.q();b.highlightedCategories=D.pl.Y(a);(0,D.ql)(a,this.Bh(),"any"==b.highlightMatch)};D.wQ.prototype.highlight=D.wQ.prototype.Ge;D.wQ.prototype.select=function(a){this.q().selection=D.pl.Y(a);this.Hb&&(0,D.Il)(this.Hb,a,this.Bh())};D.wQ.prototype.select=D.wQ.prototype.select;
D.wQ.prototype.Hj=function(){return(0,D.nk)(this.q(),"componentName","DvtUtilBundle","PICTOCHART")};D.wQ.prototype.Gf=function(){this.lia||(this.lia=new D.BQ(this));return this.lia};D.wQ.prototype.getAutomation=D.wQ.prototype.Gf;
D.BQ=(0,D.ba)("mg");(0,D.da)("DvtPictoChartAutomation",D.BQ);D.z.l(D.BQ,D.Dj,"DvtPictoChartAutomation");D.BQ.prototype.ql=function(a){return(a=(0,D.Ej)(this.mg.ka(),a))&&a instanceof D.CQ?"item["+this.mg.Bh().indexOf(a)+"]":D.o};D.BQ.prototype.If=function(a){if("tooltip"==a)return(0,D.bm)(this.mg);var b=a.indexOf("[");return 0<b&&"item"===a.substring(0,b)&&(a=(0,window.parseInt)(a.substring(b+1,a.length-1)),a=this.mg.Bh()[a])?a.sa():D.o};D.BQ.prototype.getDomElementForSubId=D.BQ.prototype.If;
D.BQ.prototype.getItem=function(a){if(a=this.mg.Bh()[a]){var b={};b.color=a.vi();b.tooltip=a.Bc();b.id=a.getId();b.name=a.getName();b.count=a.getCount();b.selected=a.Da();return b}return D.o};D.BQ.prototype.getItem=D.BQ.prototype.getItem;D.BQ.prototype.bM=function(){return this.mg.Bh().length};D.BQ.prototype.getItemCount=D.BQ.prototype.bM;
D.xQ=function(a){this.Init(a.j(),a.dispatchEvent,a);this.mg=a};D.z.l(D.xQ,D.Pj,"DvtPictoChartEventManager");D.x=D.xQ.prototype;D.x.fm=function(a,b,c){a=this.mg.q();"none"!=a.hoverBehavior&&(b=b.Mc?b.Mc():[],a.highlightedCategories=c?b.slice():D.o,c=new D.zm(c?"categoryRollOver":"categoryRollOut",a.highlightedCategories),b=(0,D.hp)(a.hoverBehaviorDelay),this.GB.Pd(c,this.mg.Bh(),b,"any"==a.highlightMatch))};D.x.II=function(a){(a=(0,D.Ej)(this,a.target))&&(!a.Aa||!a.Aa())&&this.ts(a)};
D.x.Ny=function(a){(a=(0,D.Ej)(this,a.target))&&a.Aa&&a.Aa()&&this.ts(a)};D.x.EN=function(a){(a=(0,D.Ej)(this,a.target))&&(!a.Aa||!a.Aa())&&this.ts(a)};D.x.qr=function(a){(a=(0,D.Ej)(this,a.target))&&(!a.Aa||!a.Aa())&&this.ts(a)};D.x.wB=function(a){var b=(0,D.Ej)(this,a.target);b&&(b.Aa&&b.Aa())&&(a.preventDefault(),a.stopPropagation(),this.ts(b))};D.x.ts=function(a){a instanceof D.CQ&&a.Ug()&&this.Xg(new D.Uj(a.getId()))};
D.zQ=function(){this.Init({alta:D.DQ})};D.z.l(D.zQ,D.Nj,"DvtPictoChartDefaults");
D.DQ={animationOnDisplay:"none",animationOnDataChange:"none",animationDuration:750,drilling:"off",hiddenCategories:[],highlightedCategories:[],highlightMatch:"all",hoverBehavior:"none",hoverBehaviorDelay:200,layout:"horizontal",layoutOrigin:"topStart",selection:[],selectionMode:"none",_defaultColor:"#a6acb1",_defaultSize:32,_defaultShape:"rectangle",_gapRatio:0.25,_textStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; color: #252525;"),_statusMessageStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; color: #252525;"),
_tooltipStyle:new D.G("border-collapse: separate; border-spacing: 1px"),_tooltipLabelStyle:new D.G("color: #737373; padding: 0px 2px"),_tooltipValueStyle:new D.G("color: #333333; padding: 0px 2px")};
D.EQ=function(a,b,c,d,e,f,g,h,j,l){D.EQ.o.Init.call(this,a.j(),b,c,d,e,f,g,h,j,l);this.mg=a};D.z.l(D.EQ,D.ch,"DvtPictoChartImageMarker");D.x=D.EQ.prototype;D.x.gf=function(a,b){var c=new D.qn(this.j(),this,0.75*this.mg.xa()),d=c.J,e=this.Sk();this.zm(b.Sk());(0,D.T)(d,"typeNumberArray",this,this.Sk,this.zm,e);b.B(0);a.add(c,1)};D.x.kh=function(a){a.add(new D.sn(this.j(),this,0.5*this.mg.xa()),0)};D.x.qg=function(a){this.B(0);a.add(new D.Vm(this.j(),this,0.5*this.mg.xa()),2)};
D.x.Sk=function(){return[this.Eg(),this.Fg(),this.getWidth(),this.getHeight()]};D.x.zm=function(a){this.ru(a[0]);this.su(a[1]);this.ma(a[2]);this.Ea(a[3])};
D.CQ=function(a,b){this.Init(a,b)};D.z.l(D.CQ,D.D,"DvtPictoChartItem");D.FQ=0;D.CQ.prototype.Init=function(a,b){D.CQ.o.Init.call(this,a.j(),D.o,b.id);this.mg=a;this.Tk=b;this.Xa=b.id!=D.o?b.id:b.name!=D.o?b.name:"_defaultId"+D.FQ;D.FQ++;this.Ib=this.Th=D.p;this.Kla=new D.F(0,0);(this.Aa()||this.Ug())&&this.setCursor("pointer");a.ka().Ca(this,this)};D.GQ=function(a){a=a.Tk.columnSpan;return a!=D.o&&0<=a?a:1};D.HQ=function(a){a=a.Tk.rowSpan;return a!=D.o&&0<=a?a:1};D.x=D.CQ.prototype;
D.x.getCount=function(){var a=this.Tk.count;return a!=D.o?window.Math.max(a,0):1};D.x.rb=function(){return this.Tk.shape||this.mg.q()._defaultShape};D.x.qb=function(){return this.Tk.color||this.mg.q()._defaultColor};D.x.xk=function(){return this.Tk.borderColor};D.x.Sg=function(){return this.Tk.borderWidth};D.x.pS=function(){return this.Tk.source};D.x.yba=function(){return this.Tk.sourceSelected};D.x.wba=function(){return this.Tk.sourceHover};D.x.xba=function(){return this.Tk.sourceHoverSelected};
D.x.getName=function(){return this.Tk.name};D.x.getId=(0,D.v)("Xa");D.x.Bc=function(){return this.Tk.shortDesc};D.x.Ug=function(){var a=this.Tk.drilling;return a&&"inherit"!=a?"on"==a:"on"==this.mg.q().drilling};D.x.Eh=function(){return this.Aa()&&this.Ug()};
D.x.De=function(){var a=this.mg.q(),b=this.mg.q().tooltip;if(b){var a=this.mg.j().ge(),c={id:this.getId(),name:this.getName(),count:this.getCount(),color:this.qb()};return(0,D.ip)(a,b,c)}if(this.Bc()!=D.o)return this.Bc();b="";(c=this.getName())&&(b=(0,D.jp)("td",a._tooltipLabelStyle)+c+"\x3c/td\x3e");c=(0,D.E)(this.mg.j());a._tooltipLabelStyle.W("text-align",c?"left":"right");a._tooltipValueStyle.W("text-align",c?"right":"left");return(0,D.jp)("table",a._tooltipStyle)+"\x3ctr\x3e"+b+(0,D.jp)("td",
a._tooltipValueStyle)+(0,D.IQ)(this)+"\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e"};D.x.vi=function(){return this.qb()};D.IQ=function(a){var b=a.mg.q(),c=a.getCount();a=a.mg;for(var d=0,e=0;e<a.Za.length;e++)d+=a.Za[e].getCount();return(0,D.nk)(b,"labelCountWithTotal","DvtUtilBundle","COUNT_WITH_TOTAL",[c,d])};D.x=D.CQ.prototype;D.x.Aa=function(){return"none"!=this.mg.q().selectionMode};D.x.Da=(0,D.v)("Th");
D.x.jb=function(a){this.Th=a;this.Iq();for(var b=0;b<this.Ja();b++){var c=this.ha(b);(c instanceof D.JQ||c instanceof D.EQ)&&c.jb(a)}};D.x.Ob=function(){for(var a=0;a<this.Ja();a++){var b=this.ha(a);(b instanceof D.JQ||b instanceof D.EQ)&&b.Ob()}};D.x.Db=function(){for(var a=0;a<this.Ja();a++){var b=this.ha(a);(b instanceof D.JQ||b instanceof D.EQ)&&b.Db()}};D.x.Yc=function(){return[this]};
D.x.fc=function(){var a=[],b=this.mg.q();this.Aa()&&a.push((0,D.nk)(b,this.Da()?"stateSelected":"stateUnselected","DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));this.Ug()&&a.push((0,D.nk)(b,"stateDrillable","DvtUtilBundle","STATE_DRILLABLE"));b=this.getName();b=this.Bc()!=D.o?this.Bc():b==D.o?(0,D.IQ)(this):(0,D.L)("DvtUtilBundle","COLON_SEP_LIST",[b,(0,D.IQ)(this)]);return(0,D.ok)(b,a)};D.x.Iq=function(){(0,D.cf)()||this.$b("label",this.fc())};
D.x.Mc=function(){return this.Tk.categories||[this.getId()]};D.x.Ad=function(a){var b=this.mg.ka().Sf;if(a.type==D.kk||b.ar(a))a=this;else if(b.tg(a)){var b=this.mg,c=D.AQ.cca(b),d=D.AQ.bca(b);a=37==a.keyCode&&c||39==a.keyCode&&!c||38==a.keyCode&&d||40==a.keyCode&&!d;b=b.Bh();a=D.H.wa(b,this)+(a?1:-1);a=a<b.length&&0<=a?b[a]:this}else a=D.o;return a};D.x.Ee=function(a){return this.F(a)};D.x.yj=function(){return this.sa()};D.x.Vd=function(){this.Ib=D.k;this.Ob()};D.x.jc=function(){this.Ib=D.p;this.Db()};
D.x.pc=(0,D.v)("Ib");D.x.cba=(0,D.v)("Kla");
D.yQ=function(a){this.Init(a)};D.z.l(D.yQ,D.jk,"DvtPictoChartKeyboardHandler");D.yQ.prototype.qy=function(a){return this.tg(a)&&!a.ctrlKey};D.yQ.prototype.ar=function(a){return 32==a.keyCode&&a.ctrlKey};D.yQ.prototype.Fh=function(a){var b=this.ea.dd();return b&&13==a.keyCode?(this.ea.ts(b),(0,D.hi)(a),b):D.yQ.o.Fh.call(this,a)};
D.JQ=function(a,b,c,d,e,f,g){D.JQ.o.Init.call(this,a.j(),b,"alta",c,d,e,f,D.k,g);this.mg=a};D.z.l(D.JQ,D.dh,"DvtPictoChartShapeMarker");D.x=D.JQ.prototype;D.x.gf=function(a,b){var c=new D.qn(this.j(),this,0.75*this.mg.xa()),d=c.J,e=this.Rb();this.L(b.Rb().Y());(0,D.T)(d,"typeFill",this,this.Rb,this.L,e);e=this.Sk();this.zm(b.Sk());(0,D.T)(d,"typeNumberArray",this,this.Sk,this.zm,e);b.B(0);a.add(c,1)};D.x.kh=function(a){a.add(new D.sn(this.j(),this,0.5*this.mg.xa()),0)};
D.x.qg=function(a){this.B(0);a.add(new D.Vm(this.j(),this,0.5*this.mg.xa()),2)};D.x.Sk=function(){return[this.Eg(),this.Fg(),this.getWidth(),this.getHeight()]};D.x.zm=function(a){this.ru(a[0]);this.su(a[1]);this.ma(a[2]);this.Ea(a[3])};
D.AQ={};D.z.l(D.AQ,D.z,"DvtPictoChartRenderer");
D.AQ.P=function(a,b,c,d){var e=a.j(),f=new D.Te(e,c.x,c.y,c.e,c.g);(0,D.wi)(f);b.k(f);d||(d=D.AQ.bl(a,c.e,c.g));if(d.Ul){a.Uca(d.Ul);for(var f=a.q()._gapRatio,g=D.AQ.Sa(a),h=D.AQ.bca(a),j=D.AQ.cca(a),l=new D.tl,m=0,n=0,q=0,r=0;r<d.Ul.length;r++){for(var s=d.Ul[r],u=(0,D.GQ)(s),w=(0,D.HQ)(s),y=u*d.EZ,C=w*d.O0,O=s.getCount(),M=0,J=D.k,R;0<O;){if(u!=m||w!=n)q=0;0==q&&(R=D.AQ.hka(l,u,w,d.aqa,d.Kta,g));if(R==D.o)break;var N=R.aaa*d.EZ+y/2,Y=R.fT*d.O0+C/2,N=c.x+(j?c.e-N:N),ha=c.y+(h?c.g-Y:Y),Y=window.Math.min(1-
q,O),ta,xa,Ea,ob;g?(ta=N-y/2,xa=h?ha+C*(0.5-Y-q):ha+C*(q-0.5),Ea=y,ob=C*Y):(ta=j?N+y*(0.5-Y-q):N+y*(q-0.5),xa=ha-C/2,Ea=y*Y,ob=C);var La;1==Y?(La=s.getId()+"_"+M,M++):La=window.Math.random();if(s.pS())La=new D.EQ(a,N,ha,y,C,s.pS(),s.yba(),s.wba(),s.xba(),La+"_I");else{var kb=new D.Te(e,ta,xa,Ea,ob);(0,D.wi)(kb);s.k(kb);La=new D.JQ(a,s.rb(),N,ha,y-d.EZ*f,C-d.O0*f,La+"_S");La.pa(s.qb());La.Ra(s.xk(),D.o,s.Sg());La.dI(s.qb())}1>Y&&(kb=new D.ug,(0,D.wg)(kb,ta,xa,Ea,ob),(0,D.xg)(La,kb));J&&(J=new D.F(N,
ha),s.Kla=J,J=D.p);s.k(La);a.nn.push(La);O-=Y;q=(q+Y)%1}b.k(s);m=s;m.Ud("img");m.Iq();m=u;n=w}}else D.AQ.Om(a,b,c)};
D.AQ.bl=function(a,b,c){var d=a.q(),e=d.items;if(!e)return{};for(var f=D.H.ZG(d.hiddenCategories),g=[],h=0,j=1,l=1,m=0;m<e.length;m++)if(e[m]!=D.o){var n=new D.CQ(a,e[m]);if(!f||!D.H.yM(f,n.Mc())){var q=(0,D.GQ)(n),r=(0,D.HQ)(n);q>j&&(j=q);r>l&&(l=r);h+=q*r*n.getCount();g.push(n)}}if(0==h)return{};e=d.columnWidth;f=d.rowHeight;if(!b||!c)e||(e=f?f:d._defaultSize),f||(f=e);a=D.AQ.Sa(a);m=d.columnCount;d=d.rowCount;!m&&!d&&(b&&c?a?d=D.AQ.uJ(window.Math.sqrt(h*c/b),l):m=D.AQ.uJ(window.Math.sqrt(h*b/c),
j):b?m=window.Math.max(window.Math.floor(b/e),1):c?d=window.Math.max(window.Math.floor(c/f),1):a?d=D.AQ.uJ(window.Math.sqrt(h),l):m=D.AQ.uJ(window.Math.sqrt(h),j));m?d||(d=D.AQ.uJ(h/m,l)):m=D.AQ.uJ(h/d,j);b&&c&&(e||(e=f?f:window.Math.min(b/m,c/d)),f||(f=e));return 0>=m||0>=d||0>=e||0>=f?{}:{Ul:g,aqa:m,Kta:d,EZ:e,O0:f}};D.AQ.uJ=function(a,b){return window.Math.ceil(a/b)*b};
D.AQ.hka=function(a,b,c,d,e,f){if(f)return(a=D.AQ.hka(a,c,b,e,d,D.p))?{aaa:a.fT,fT:a.aaa}:D.o;for(f=0;f<e-c+1;f++)for(var g=0;g<d-b+1;g++)if(D.AQ.Xza(a,g,f,b,c))return D.AQ.ZDa(a,g,f,b,c),{aaa:g,fT:f};return D.o};D.AQ.Xza=function(a,b,c,d,e){for(var f=0;f<e;f++)for(var g=0;g<d;g++)if(a.get(b+g,c+f))return D.p;return D.k};D.AQ.ZDa=function(a,b,c,d,e){for(var f=0;f<e;f++)for(var g=0;g<d;g++)a.put(b+g,c+f,D.k)};
D.AQ.Om=function(a,b,c){var d=a.q(),e=(0,D.nk)(d,"labelNoData","DvtUtilBundle","NO_DATA");b=D.$e.Om(b,e,c.Y(),a.ka(),d._statusMessageStyle);a.jn=b};D.AQ.Sa=function(a){return"vertical"==a.q().layout};D.AQ.bca=function(a){a=a.q().layoutOrigin;return"bottomStart"==a||"bottomEnd"==a};D.AQ.cca=function(a){var b=a.q().layoutOrigin,b="topEnd"==b||"bottomEnd"==b;return(0,D.E)(a.j())?!b:b};

  return D;
});