/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtTimelineOverview'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.bP={am:function(){return(0,D.Jf)()}};D.z.l(D.bP,D.z,"DvtTimeUtils");D.bP.fe=function(a,b,c,d){c=(c-a)*d;a=b-a;return 0==c||0==a?0:c/a};D.bP.rg=function(a,b,c,d){b=c*(b-a);return 0==b||0==d?a:b/d+a};
D.VT=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtTimeComponent",D.VT);D.z.l(D.VT,D.sj,"DvtTimeComponent");D.VT.prototype.Init=function(a,b,c){D.VT.o.Init.call(this,a);this.lb=b;this.ra=c;this.LGa=D.p};D.VT.prototype.P=function(a,b,c){c&&this.vd(c);this.Ga=a;this.Ta=b;this.D&&(a=this.AE(this.D),this.Ku(a))};D.VT.prototype.render=D.VT.prototype.P;D.VT.prototype.vd=function(a){this.D=D.pl.Y(a)};D.VT.prototype.NL=function(a,b,c,d,e,f,g){b=new D.Di(this.j(),b,d,c,e,g);b.V(f);(0,D.Ei)(b);a.k(b);return b};
D.WT=function(a,b,c,d,e){b.ca(c);b.va(d);b.il()&&b.we(b.Ao());D.$e.Qb(b,e,window.Infinity,a);b.Ye()};D.VT.prototype.kD=function(a,b,c,d,e,f,g,h,j,l,m){c=new D.Kf(this.j(),c,b,0,g);f!=D.o&&c.Ha(f);a.k(c);var n=c.F();a.removeChild(c);e-=n.g;c.va(e);m&&c.ca(b-n.e);h&&(h=window.Math.min(n.e+2*j,d),b=new D.Te(this.j(),(m?b-h+2*j:b)-j,e-j,h,n.g+2*j,"ob_"+g),b.Ha(f),(0,D.Eq)(b,3),a.k(b),l&&l.push(b));D.$e.Qb(c,d,window.Infinity,a);l&&l.push(c);return c};
D.VT.prototype.Ku=function(a){this.VPa=a.pta;this.UPa=a.ota;this.ob=a.start;this.Xb=a.end;this.dX=a.Asa;this.Yd=a.scale;this.vl=a.vHa;this.QL()};D.VT.prototype.QL=function(){(0,D.Uf)(this.gp,this.dX)};D.XT=function(a,b){a.Hc=a.Jg<b?b:a.Jg;a.LGa||(a.Mr=0,a.Vo=a.Hc)};D.VT.prototype.nh=function(){return(0,D.E)(this.j())};D.VT.prototype.Sa=(0,D.v)("Tb");
D.YT=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.z.l(D.YT,D.D,"DvtTimeComponentAxis");D.YT.mea=50;D.YT.kea=21;D.YT.lea=2;D.YT.Kua=1;D.YT.Mua=1;D.YT.Lha="seconds minutes hours days weeks months quarters years".split(" ");D.x=D.YT.prototype;D.x.Init=function(a,b,c,d,e,f){D.YT.o.Init.call(this,a);this.Sia=new D.ZT;this.mka=new D.$T(D.$T.SHORT,f);this.ao=d?D.YT.mea:D.YT.kea;this.bF=D.YT.Kua;this.Lv=e;this.yz=a.o_().dateToIsoConverter};D.x.Qp=(0,D.ba)("Yd");
D.x.zH=function(){this.kR==D.o&&(this.kR=30);return this.kR};D.x.Lta=(0,D.ba)("bF");D.x.Sg=(0,D.v)("bF");D.x.Tc=function(){return this.ao+2*this.bF};D.x.Gk=function(a,b){this.mka=new D.$T(a,b)};D.x.OL=function(a){return this.Sia.OL(new window.Date(a),this.Yd)};D.x.lM=function(a){return this.Sia.lM(a,this.Yd)};
D.aU=function(a,b){if(a.vl){var c;c=a.vl[a.Yd]?a.vl[a.Yd]:a.vl["default"]?a.vl["default"]:a.vl;if(c.format)return c.format(a.yz?a.yz(b):b);if(c.getAsString)return c.getAsString(b)}if(a.HJ&&a.HJ[a.Yd]){c=a.HJ[a.Yd];if(c.format)return c.format(a.yz?a.yz(b):b);if(c.getAsString)return c.getAsString(b)}return a.mka.Ut(b,a.Yd)};
D.$T=function(a,b){this.Init(a,b)};D.z.l(D.$T,D.z,"DvtTimeComponentAxisFormatter");D.$T.Iva=0;D.$T.SHORT=1;
D.$T.prototype.Init=function(a,b){this.pg=a;this.lF=b;this.lj=[];this.lj[0]={};this.lj[0].seconds="HH:MM:ss";this.lj[0].minutes="HH:MM";this.lj[0].hours="HH:MM";this.lj[0].days="dddd";this.lj[0].weeks="m/dd";this.lj[0].months="mmmm";this.lj[0].quarters="mmmm";this.lj[0].halfyears="yyyy";this.lj[0].years="yyyy";this.lj[0].twoyears="yyyy";this.lj[1]={};this.lj[1].seconds="HH:MM:ss";this.lj[1].minutes="HH:MM";this.lj[1].hours="HH:MM";this.lj[1].days="m/dd";this.lj[1].weeks="m/dd";this.lj[1].months="mmm";
this.lj[1].quarters="mmm";this.lj[1].halfyears="yy";this.lj[1].years="yy";this.lj[1].twoyears="yy"};D.$T.prototype.Ut=function(a,b){var c=this.lj[this.pg][b];if(c!=D.o){if(-1!=c.indexOf(":"))var d=":";else-1!=c.indexOf("/")&&(d="/");if(d){for(var c=c.split(d),e=(0,D.bU)(this,a,c[0]),f=1;f<c.length;f++)e+=d+(0,D.bU)(this,a,c[f]);return e}return(0,D.bU)(this,a,c)}return a.toLocaleString()};
D.bU=function(a,b,c){switch(c){case "ss":return a=b.getSeconds(),10>a?"0"+a:a;case "HH":return a=b.getHours(),10>a?"0"+a:a;case "MM":return a=b.getMinutes(),10>a?"0"+a:a;case "dd":return a=b.getDate(),10>a?"0"+a:a;case "dddd":return a.lF.THa[b.getDay()+7];case "m":return b.getMonth()+1;case "mmm":return a.lF.mta[b.getMonth()];case "mmmm":return a.lF.mta[b.getMonth()+12];case "yy":return b.getFullYear().toString().substring(2,4);default:return b.getFullYear()}};
D.ZT=function(a){this.Init(a)};D.z.l(D.ZT,D.z,"DvtTimeComponentCalendar");D.ZT.prototype.Init=function(){this.oBa=864E5};
D.ZT.prototype.OL=function(a,b){var c=new window.Date(a.getTime());if("weeks"==b){c.setHours(0,0,0);var d=(a.getDay()-0+7)%7;0<d&&c.setTime(c.getTime()-d*this.oBa)}else"months"==b?c.setDate(1):"days"==b?c.setHours(0,0,0):"hours"==b?c.setMinutes(0,0,0):"minutes"==b?c.setSeconds(0,0):"seconds"==b?c.setMilliseconds(0):"quarters"==b?(c.setDate(1),d=2-(a.getMonth()+11)%3,0<d&&c.setMonth(c.getMonth()+d)):"halfyears"==b?(c.setDate(1),d=5-(a.getMonth()+11)%6,0<d&&c.setMonth(c.getMonth()+d)):"years"==b?(c.setMonth(0),
c.setDate(1)):"twoyears"==b&&(c.setMonth(0),c.setDate(1));return c};
D.ZT.prototype.lM=function(a,b){if("seconds"==b)return new window.Date(a+1E3);if("minutes"==b)return new window.Date(a+6E4);if("hours"==b)return new window.Date(a+36E5);var c=new window.Date(a);"days"==b?c.setDate(c.getDate()+1):"weeks"==b?c.setDate(c.getDate()+7):"months"==b?c.setMonth(c.getMonth()+1):"quarters"==b?c.setMonth(c.getMonth()+3):"halfyears"==b?c.setMonth(c.getMonth()+6):"years"==b?c.setFullYear(c.getFullYear()+1):"twoyears"==b?c.setFullYear(c.getFullYear()+2):c.setYear(c.getYear()+1);
return c};
D.gU=function(a){this.Init(a)};D.z.l(D.gU,D.jk,"DvtTimelineKeyboardHandler");D.gU.prototype.Init=function(a){D.gU.o.Init.call(this,a)};D.gU.prototype.qy=function(a){return this.tg(a)&&!a.ctrlKey};D.gU.prototype.ar=function(a){return 32==a.keyCode&&a.ctrlKey};
D.gU.prototype.Fh=function(a){var b=a.keyCode;(0,D.Dm)(a)||(0,D.Em)(a)?this.ea.lr(1/1.5):(0,D.Fm)(a)||(0,D.Gm)(a)?this.ea.lr(1.5):33==b?(a.shiftKey?this.ea.ei(-0.25,0):this.ea.ei(0,-0.25),(0,D.hi)(a)):34==b&&(a.shiftKey?this.ea.ei(0.25,0):this.ea.ei(0,0.25),(0,D.hi)(a));return D.gU.o.Fh.call(this,a)};
D.KU=function(a,b,c){var d=a.Fe(),e=a.sg(),f=(0,D.E)(d.j()),d=d.Sa(),g=1<c.length;if(!f&&39==b.keyCode||f&&37==b.keyCode)if(d){if(g&&1!=e)return(0,D.IU)(a,c[1])}else return(0,D.JU)(a,c[e],D.k);else if(!f&&37==b.keyCode||f&&39==b.keyCode)if(d){if(g&&0!=e)return(0,D.IU)(a,c[0])}else return(0,D.JU)(a,c[e],D.p);else if(40==b.keyCode){if(d)return(0,D.JU)(a,c[e],D.k);if(g&&1!=e)return(0,D.IU)(a,c[1])}else if(38==b.keyCode){if(d)return(0,D.JU)(a,c[e],D.p);if(g&&0!=e)return(0,D.IU)(a,c[0])}return D.o};
D.JU=function(a,b,c){a=D.H.wa(b,a)+(c?1:-1);return 0<=a&&a<b.length?b[a]:D.o};D.IU=function(a,b){if(0<b.length){for(var c=b[0],d=a.Zo,e=window.Math.abs(d-c.Zo),f=1;f<b.length;f++){var g=window.Math.abs(d-b[f].Zo);g<e&&(e=g,c=b[f])}return c}return D.o};
D.eU=function(a){this.Init(a.j(),a.Pd,a);this.Lc=a;this.y7=this.t7=D.p};D.z.l(D.eU,D.Pj,"DvtTimelineEventManager");D.x=D.eU.prototype;D.x.me=function(a){D.eU.o.me.call(this,a);D.nm.xR(this.Lc,this.lG,this.kG,this.jG,this);(0,D.Jf)()||((0,D.jj)()?a.la("wheel",this.Gw,D.p,this):a.la(D.om,this.Gw,D.p,this),(0,D.Pi)()&&(a=this.j().Kc,a.la("mouseenter",this.bga,D.p,this),a.la("mouseleave",this.cga,D.p,this)))};
D.x.gi=function(a){D.eU.o.gi.call(this,a);(0,D.Jf)()||((0,D.jj)()?a.Ya("wheel",this.Gw,D.p,this):a.Ya(D.om,this.Gw,D.p,this),(0,D.Pi)()&&(a=this.j().Kc,a.Ya("mouseenter",this.bga,D.p,this),a.Ya("mouseleave",this.cga,D.p,this)))};D.x.NN=function(a){D.eU.o.NN.call(this,a);this.Lc.DN(a)};D.x.Jh=function(a){this.t7||(D.eU.o.Jh.call(this,a),(0,D.BU)(this.Lc,a))};D.x.AU=function(a){this.Vk&&this.Vk.xi()&&this.Vk.stop();D.eU.o.AU.call(this,a);!(0,D.Pi)()&&!this.d0&&(this.d0=D.k,(0,D.pU)(this.Lc)||(0,D.qU)(this.Lc))};
D.x.bga=function(){this.Vk&&this.Vk.xi()&&this.Vk.stop();this.d0||(this.d0=D.k,(0,D.pU)(this.Lc)||(0,D.qU)(this.Lc))};D.x.cga=function(){this.Vk||(this.Vk=new D.Yq(this.j(),10,this.UX,this,1));this.Vk.reset();this.Vk.start()};D.x.zU=function(a){D.eU.o.zU.call(this,a);(0,D.Pi)()||(this.Vk||(this.Vk=new D.Yq(this.j(),10,this.UX,this,1)),this.Vk.reset(),this.Vk.start())};D.x.UX=function(){this.d0=D.p};D.x.yU=function(a){this.t7=D.p;D.eU.o.yU.call(this,a);this.Lc.vB(a)};
D.x.Gw=function(a){var b=this.Lc;(0,D.hi)(a);var c=a.wheelDelta;if((0,D.oU)(b)&&c){var d=(0,D.pm)(b.j());a=b.Tb?a.pageY-d.y:a.pageX-d.x;d=(b.Xb-b.ob)/b.Hc*a+b.zb;(0,D.wU)(b,b.Hc*(0.02*c+1),d,a,D.k)}};D.x.JI=function(a){D.eU.o.JI.call(this,a);this.Lc.kU(a);this.Lc.j().Kc.Vy.parentNode.focus()};D.x.wU=function(a){D.eU.o.wU.call(this,a);this.Lc.jU(a)};D.x.lG=function(a){if((0,D.oU)(this.Lc))return(0,D.Jf)()?this.yQ(a):this.vQ(a)};D.x.kG=function(a){return(0,D.Jf)()?this.xQ(a):this.uQ(a)};
D.x.jG=function(a){return(0,D.Jf)()?this.wQ(a):this.tQ(a)};D.x.xg=function(a,b){this.qi||(this.qi=(0,D.pm)(this.U));return new D.F(a-this.qi.x,b-this.qi.y)};D.x.vQ=function(a){return 2!=a.button?(a=this.xg(a.pageX,a.pageY),this.Lc.zR(a.x,a.y),D.k):D.p};D.x.uQ=function(a){a=this.xg(a.pageX,a.pageY);this.Lc.BR(a.x,a.y)&&(this.t7=D.k)};D.x.tQ=function(){this.Lc.UL();this.qi=D.o};
D.x.yQ=function(a){var b=a.touches;if(1==b.length)return a=this.xg(b[0].pageX,b[0].pageY),this.Lc.zR(a.x,a.y),D.k;if(2==b.length){this.Lc.UL();this.y7=D.k;var c=this.xg(b[0].pageX,b[0].pageY),d=this.xg(b[1].pageX,b[1].pageY),b=this.Lc,e=c.x,c=c.y,f=d.x,d=d.y;b.j7=b.Tb?window.Math.sqrt((c-d)*(c-d))+(c<d?c:d):window.Math.sqrt((e-f)*(e-f))+(e<f?e:f);b.wla=(b.Xb-b.ob)/b.Hc*b.j7+b.zb;b.i7=window.Math.sqrt((e-f)*(e-f)+(c-d)*(c-d));b.vla=b.Hc;(0,D.hi)(a);return D.k}return D.p};
D.x.xQ=function(a){var b=a.touches;if(1==b.length)b=this.xg(b[0].pageX,b[0].pageY),this.Lc.BR(b.x,b.y),a.preventDefault();else if(2==b.length){var c=this.xg(b[0].pageX,b[0].pageY),d=this.xg(b[1].pageX,b[1].pageY),b=this.Lc,e=c.x,c=c.y,f=d.x,d=d.y,e=window.Math.sqrt((e-f)*(e-f)+(c-d)*(c-d));e!=b.i7&&(b.FL=D.k);(0,D.wU)(b,e/b.i7*b.vla,b.wla,b.j7,D.p);a.preventDefault()}};
D.x.wQ=function(a){if(this.y7){this.y7=D.p;var b=this.Lc;b.i7=D.o;b.j7=D.o;b.vla=D.o;b.wla=D.o;b.FL&&(b.FL=D.p,b.dispatchEvent(new D.vU("viewportChange",b.zb,b.Sc,b.Yd)))}else this.Lc.UL();a.preventDefault();this.qi=D.o};D.x.lr=function(a){this.Lc.lr(a)};D.x.ei=function(a,b){var c=a*this.Lc.Jg*((0,D.E)(this.U)?-1:1),d=b*this.Lc.Ff;0!=c&&(this.Lc.FL=D.k);var e=this.dd();e&&(this.Lc.sh=e.sb);this.Lc.ei(c,d);(0,D.CU)(this.Lc)};D.x.w2=function(){this.Lc.lr(1/1.5)};D.x.z2=function(){this.Lc.lr(1.5)};
D.x.Bu=(0,D.ca)("touchHold");
D.cU=(0,D.t)();(0,D.da)("DvtTimeline",D.cU);D.z.l(D.cU,D.VT,"DvtTimeline");D.cU.newInstance=function(a,b,c){var d=new D.cU;d.Init(a,b,c);return d};D.cU.prototype.Init=function(a,b,c){D.cU.o.Init.call(this,a,b,c);this.rf=new D.dU;this.Ia=new D.eU(this);this.Ia.me(this);(0,D.Jf)()?this.GC=D.o:(this.GC=new D.gU(this.Ia),(0,D.xj)(this.Ia,this.GC))};D.cU.prototype.vd=function(a){this.D=this.rf.Vj(a);(0,D.Zk)()||(this.D.animationOnDisplay="none",this.D.animationOnDataChange="none")};
D.cU.prototype.AE=function(a){this.vv=new D.hU;return this.vv.parse(a)};
D.cU.prototype.Ku=function(a){var b=a.orientation;this.Tb=b&&"vertical"==b?D.k:D.p;this.Or=a.TLa;this.zb=a.jOa;this.Sc=a.iOa;this.Gq=a.gT;this.Ym="single"==this.Gq?new D.$k("s"):"multiple"==this.Gq?new D.$k("m"):D.o;this.Ia.yu(this.Ym);this.jAa=a.fHa;this.Kt=a.XNa;this.Xa=a.id;this.yG=a.oNa;this.Lv=a.kOa;this.ZQ=a.INa;this.lF={THa:[(0,D.L)("DvtUtilBundle","DAY_SHORT_SUNDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SHORT_MONDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SHORT_TUESDAY",D.o),(0,D.L)("DvtUtilBundle",
"DAY_SHORT_WEDNESDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SHORT_THURSDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SHORT_FRIDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SHORT_SATURDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SUNDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_MONDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_TUESDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_WEDNESDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_THURSDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_FRIDAY",D.o),(0,D.L)("DvtUtilBundle","DAY_SATURDAY",D.o)],mta:[(0,D.L)("DvtUtilBundle",
"MONTH_SHORT_JANUARY",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_FEBRUARY",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_MARCH",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_APRIL",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_MAY",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_JUNE",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_JULY",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_AUGUST",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_SEPTEMBER",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_OCTOBER",D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_NOVEMBER",
D.o),(0,D.L)("DvtUtilBundle","MONTH_SHORT_DECEMBER",D.o),(0,D.L)("DvtUtilBundle","MONTH_JANUARY",D.o),(0,D.L)("DvtUtilBundle","MONTH_FEBRUARY",D.o),(0,D.L)("DvtUtilBundle","MONTH_MARCH",D.o),(0,D.L)("DvtUtilBundle","MONTH_APRIL",D.o),(0,D.L)("DvtUtilBundle","MONTH_MAY",D.o),(0,D.L)("DvtUtilBundle","MONTH_JUNE",D.o),(0,D.L)("DvtUtilBundle","MONTH_JULY",D.o),(0,D.L)("DvtUtilBundle","MONTH_AUGUST",D.o),(0,D.L)("DvtUtilBundle","MONTH_SEPTEMBER",D.o),(0,D.L)("DvtUtilBundle","MONTH_OCTOBER",D.o),(0,D.L)("DvtUtilBundle",
"MONTH_NOVEMBER",D.o),(0,D.L)("DvtUtilBundle","MONTH_DECEMBER",D.o)]};this.ZQ?(this.hGa=a.GNa,this.dp=new D.YT(this.j(),D.o,D.o,this.Tb),this.dp.Qp(this.ZQ),this.dp.vl=this.hGa,this.Tb?(this.dp.Gk(D.$T.SHORT,this.lF),this.dp.HJ=this.Ti.converterVert):(this.dp.Gk(D.$T.Iva,this.lF),this.dp.HJ=this.Ti.converter)):this.dp=D.o;this.tBa=[D.p,D.k];D.cU.o.Ku.call(this,a)};D.iU=function(a,b){return!a.Or&&1==b?a.Yf.Tc()-a.Yf.Sg():a.Yf.Tc()};
D.cU.prototype.select=function(a){this.D.selection=D.pl.Y(a);this.Ym&&(0,D.jU)(this)};D.cU.prototype.select=D.cU.prototype.select;
D.cU.prototype.P=function(a,b,c){if(a){this.vd(a);this.D&&(this.Ti=this.D._resources,this.Ti==D.o&&(this.Ti=[]));this.Ga=b;this.Ta=c;a=this.AE(this.D);this.Ku(a);this.Mr=0;this.Vo=this.Tb?c:b;this.D.styleDefaults&&(this.fz=this.D.styleDefaults.minorAxis,this.HDa=this.D.styleDefaults.majorAxis,this.GG=this.D.styleDefaults.series);(0,D.kU)(this);if(this.Yd){b=this.ob;c=this.Xb;a=this.j();var d=D.$.xIa(this.D);this.Yf=new D.YT(a,D.o,D.o,this.Tb,this.Lv);this.Yf.vl=this.vl;this.Yf.Gk(D.$T.SHORT,this.lF);
this.Hja=[];this.Cl=[];this.Kv=[];if(this.Tb){var e=D.YT.kea;this.Yf.HJ=this.Ti.converterVert}else e=D.YT.mea,this.Yf.HJ=this.Ti.converter;for(var f=0;f<this.Yf.Lv.length;f++){var g=this.Yf.Lv[f];this.Yf.Qp(g);var h=new D.Te(a,0,0,0,0,"tempAxis"),j=window.Infinity,l=0,m=[],n=[],q=this.Yf.OL(b).getTime();for(m.push(q);q<c;){var r=(0,D.aU)(this.Yf,new window.Date(q)),s=new D.Kf(a,r,0,0,"s_label"+q);s.Ha(d);s.time=q;n.push(s);r=this.Yf.lM(q).getTime();h.k(s);var u=s.F();h.removeChild(s);this.Tb?(s=u.g,
u=u.e):(s=u.e,u=u.g);s=window.Math.max(e,s+2*D.YT.lea);q=(r-q)/s;q<j&&(j=q);u>l&&(l=u);q=r;m.push(q)}h=this.Yf;l+=2*D.YT.lea;l>h.ao&&(h.ao=l);this.Hja.push(m);this.Cl.push(n);j=(c-b)/j;this.Kv.push(j);g==this.Yd&&(this.tA=f,this.c$&&((0,D.XT)(this,j),this.c$=D.p,this.zb==D.o?this.Sc!=D.o?(this.zb=this.Sc-this.Jg/j*(c-b),this.zb<this.ob&&(this.zb=this.ob),g=this.Sc-this.zb,g=this.Jg/g,(0,D.XT)(this,g*(this.Xb-this.ob)),this.uc=g*(this.ob-this.zb),this.nh()&&!this.Tb&&(this.uc=this.Mj-this.Hc-this.uc)):
(this.zb=this.ob,this.uc=0,this.nh()&&!this.Tb&&(this.uc=this.Mj-this.Hc-this.uc),this.Sc=this.Jg/j*(c-b)+this.zb,this.Sc>this.Xb&&(this.Sc=this.Xb)):(this.Sc=this.Jg/j*(c-b)+this.zb,this.Sc>this.Xb&&(this.Sc=this.Xb),g=this.Sc-this.zb,g=this.Jg/g,(0,D.XT)(this,g*(this.Xb-this.ob)),this.uc=g*(this.ob-this.zb),this.nh()&&!this.Tb&&(this.uc=this.Mj-this.Hc-this.uc))));0==f&&(this.i8=n.length*this.Jg)}this.Yf.Qp(this.Yd);(0,D.lU)(this)}if(b=this.D.series){c=window.Math.min(b.length,2);this.IY=[];if(this.sb){if(c!=
this.sb.length){for(a=0;a<this.sb.length;a++)this.Mg.removeChild(this.sb[a]);this.sb=[]}}else this.sb=[];for(a=0;a<c;a++){d=b[a];d.start=this.ob;d.end=this.Xb;d.inverted=this.tBa[a];d.orientation=this.D.orientation;d.referenceObjects=this.yG;d.timeline=this;d.index=a;d.animationOnDisplay=this.D.animationOnDisplay;d.animationOnDataChange=this.D.animationOnDataChange;this.D.majorAxis&&(d.scale=this.D.majorAxis.scale,d.timeAxis=this.dp);if(d.styleDefaults=this.D.styleDefaults)d.seriesStyleDefaults=this.GG,
d.axisStyleDefaults=this.HDa;this.IY.push(d);this.sb[a]==D.o&&(d=new D.mU(this.j(),this.ffa,this),this.sb.push(d))}}else this.sb=[];D.nU.xNa(this);this.Sn();(0,D.Vl)(this.j(),[this])}else this.Q6(b,c)};D.cU.prototype.render=D.cU.prototype.P;
D.oU=function(a){var b=a.Yd&&-1!=D.H.wa(D.YT.Lha,a.Yd),c=a.ob&&a.Xb&&a.Xb>a.ob,d=a.sb&&0<a.sb.length,e;if(d)a:{for(e=0;e<a.IY.length;e++){var f=a.IY[e];if(f.Ul)for(var g=0;g<f.Ul.length;g++){var h=f.Ul[g],j=(new window.Date(h.start)).getTime();if(!j){e=D.p;break a}if(h.hasOwnProperty("end")&&(h=(new window.Date(h.end)).getTime(),!(h&&h>j))){e=D.p;break a}}}e=D.k}else e=D.p;f=a.ZQ?-1!=D.H.wa(D.YT.Lha,a.ZQ):D.k;g=a.zb&&a.Sc?a.Sc>a.zb:D.k;j=a.zb?a.zb>=a.ob&&a.zb<a.Xb:D.k;a=a.Sc?a.Sc>a.ob&&a.Sc<=a.Xb:
D.k;return b&&c&&d&&e&&f&&g&&j&&a};D.cU.prototype.Hj=function(){return this.Kt?this.Kt:(0,D.L)("DvtUtilBundle","TIMELINE")};D.pU=function(a){for(var b=0;b<a.sb.length;b++)if(a.sb[b].hX)return D.k;return D.p};
D.qU=function(a,b){if((0,D.oU)(a)){for(var c=new D.lr(a.j(),D.$.fra(),0,D.MD),d=0;d<a.cD.length;d++){var e=a.cD[d],f=e.getId(),g=D.k;if(a.Hc<=a.Jg&&("lhs"==f||"rhs"==f))g=D.p;var h=e.getParent().getId();if(h&&(h=h.substring(h.length-1),b!=D.o&&b!=h&&(g=D.p),a.sb[h].Oi<=a.Ff&&("ths"==f||"bhs"==f)))g=D.p;g&&(0,D.T)(c,"typeNumber",e,e.fa,e.B,D.$.xJa())}(0,D.hl)(c,a.WLa,a);c.play()}};
D.cU.prototype.WLa=function(){var a=this.cD.length;if(0!=a){for(var b=new D.lr(this.j(),D.$.fra(),0,D.MD),c=0;c<a;c++){var d=this.cD[c];(0,D.T)(b,"typeNumber",d,d.fa,d.B,0)}b.play()}};
D.cU.prototype.QL=function(){this.gp=new D.G(D.$.ZKa());if(this.D.styleDefaults){var a=this.D.styleDefaults.borderColor;a&&(0,D.Uf)(this.gp,"border-color:"+a+";")}if(this.Or&&(this.UC=this.Tb?D.$.hKa():D.$.mba(),a=this.D.overview.style))for(var a=a.split(";"),b=0;b<a.length;b++){var c=a[b];if(c&&0<c.length){var d=c.indexOf(":");if(-1<d){var e=D.jg.trim(c.substring(0,d));if(this.Tb&&"width"==e||!this.Tb&&"height"==e){this.UC=(0,window.parseInt)(D.jg.trim(c.substring(d+1)),10);break}}}}D.cU.o.QL.call(this);
a=this.gp.Sg();b=2*a;(0,D.Uf)(this.gp,"border:"+b+"px;");this.oj=this.ai=a;this.Mj=this.Ga;this.DO=this.Ta;this.Tb?(this.Jg=this.DO-b,this.Or?(this.Br=this.Mj-this.UC-b,this.nh()&&(this.ai+=this.UC)):this.Br=this.Mj-b):(this.Jg=this.Mj-b,this.Br=this.Or?this.Ta-this.UC-b:this.Ta-b)};
D.lU=function(a){a.lO=new D.G(D.$.zIa());if(a.fz){var b="",c=a.fz.backgroundColor;c&&(b=b+"background-color:"+c+";");(c=a.fz.borderColor)&&(b=b+"border-color:"+c+";");(c=a.fz.borderWidth)&&(b=b+"border-width:"+c+";");(0,D.Uf)(a.lO,b)}(0,D.Uf)(a.lO,a.jAa);a.TE=a.lO.Sg();(0,D.Uf)(a.lO,"border:"+2*a.TE+"px;");a.Yf.Lta(a.TE);a.hV=a.Hc+2*a.TE-D.YT.Mua;if(a.GG&&a.GG.backgroundColor){var d=a.GG.backgroundColor,b=D.I.te(d),c=D.I.pe(d),d=D.I.oe(d);a.gQa="background-color:rgba("+b+","+c+","+d+",0.8);"}};
D.kU=function(a){a.c$=D.k;a.uc=0;a.nh()&&!a.Tb&&(a.uc=a.Mj-a.Hc-a.uc);if(a.zb&&a.Sc){var b=a.Sc-a.zb;0<b&&(a.c$=D.p,b=a.Jg/b,(0,D.XT)(a,b*(a.Xb-a.ob)),a.uc=b*(a.ob-a.zb),a.nh()&&!a.Tb&&(a.uc=a.Mj-a.Hc-a.uc))}};D.cU.prototype.kU=function(a){if(1==a.touches.length){if(this.sh=(0,D.rU)(this,a.target))var b=this.sb[0]==this.sh?0:1;(0,D.qU)(this,b)}};
D.wU=function(a,b,c,d,e){b>a.i8?(b=a.i8,(0,D.sU)(a,D.k)):(0,D.tU)(a,D.k);a.Jg>b?(b=a.Jg,(0,D.sU)(a,D.p)):(0,D.tU)(a,D.p);var f=a.Hc<=b,g=(a.Sc-a.zb)/(a.Xb-a.ob)*a.Hc;(0,D.XT)(a,b);b=g/a.Hc*(a.Xb-a.ob);c?(g=(a.Xb-a.ob)/a.Hc,a.zb=c-d*g,a.zb<a.ob&&(a.zb=a.ob),a.Sc=a.zb+b,a.Sc>a.Xb&&(a.Sc=a.Xb,a.zb=a.Sc-b,a.zb<a.ob&&(a.zb=a.ob)),a.uc=1/g*(a.ob-a.zb)):(a.zb=a.ob,a.Sc=a.zb+b,a.zb<a.ob&&(a.zb=a.ob),a.uc=0);a.nh()&&!a.Tb&&(a.uc=a.Mj-a.Hc-a.uc);a.Or&&a.lc.Yl(a.zb,a.Sc,a.Tb?a.lc.Ta:a.lc.Ga);if(f)for(;0<a.tA;)if(c=
a.Kv[a.tA-1],a.Hc>=c){a.tA--;a:{c=a.Yf;for(d=1;d<c.Lv.length;d++)if(c.Lv[d]==c.Yd){c.Yd=c.Lv[d-1];break a}}a.Yd=a.Yf.Yd}else break;else for(;a.tA<a.Kv.length-1;)if(c=a.Kv[a.tA],a.Hc<c){a.tA++;a:{c=a.Yf;for(d=0;d<c.Lv.length-1;d++)if(c.Lv[d]==c.Yd){c.Yd=c.Lv[d+1];break a}}a.Yd=a.Yf.Yd}else break;(0,D.lU)(a);D.nU.qY(a,a.Mg);(0,D.uU)(a);a.Tb?a.Mg.O(a.oj+a.uc):a.Mg.I(a.ai+a.uc);e&&a.dispatchEvent(new D.vU("viewportChange",a.zb,a.Sc,a.Yd))};
D.cU.prototype.lr=function(a){var b=this.Tb?this.Ta/2:this.Ga/2;(0,D.wU)(this,this.Hc*((1/a-1)/2+1),(this.Xb-this.ob)/this.Hc*b+this.zb,b,D.k)};
D.uU=function(a){if(a.sb){var b=a.sb.length,c=(0,D.iU)(a,b);a.Ff=(a.Br-c)/b;for(var d=0;d<b;d++){var e=a.sb[d];(0,D.xg)(e,D.o);var f=new D.ug;if(a.Tb){var g=a.nh()?window.Math.abs(d-1):d;if(a.nh()&&1==a.sb.length){(0,D.wg)(f,c,0,a.Ff,a.Hc);var h=new D.hj(1,0,0,1,c,0)}else(0,D.wg)(f,g*(a.Ff+c),0,a.Ff,a.Hc),h=new D.hj(1,0,0,1,g*(a.Ff+c),0);var j=a.Ff,g=a.Hc}else(0,D.wg)(f,0,d*(a.Ff+c),a.Hc,a.Ff),h=new D.hj(1,0,0,1,0,d*(a.Ff+c)),j=a.Hc,g=a.Ff;(0,D.xg)(e,f);e.za(h);f=j;e.qh.O(0);e.qh.I(0);e.Ga=f;e.Ta=
g;e.Mr=0;e.Tb?(e.Vo=g,e.Oi=f,e.Ng=g,e.no=f):(e.Vo=f,e.Oi=g,e.Ng=f,e.no=g);e.Na.ma(f);e.Na.Ea(g);D.xU.hOa(e)}}};D.x=D.cU.prototype;
D.x.Q6=function(a,b){this.Ga=a;this.Ta=b;this.QL();this.Mr=0;this.Vo=this.Tb?b:a;(0,D.kU)(this);D.nU.Gt(this);if((0,D.oU)(this)){if(D.nU.qoa(this,this.qh),(0,D.lU)(this),(0,D.uU)(this),D.nU.qY(this,this.Mg),D.nU.yoa(this),D.nU.woa(this),D.nU.Boa(this),this.Or&&(D.nU.toa(this),this.Ym)){var c=(0,D.Cl)(this.Ym);if(c&&0!=c.length)for(var d=0;d<c.length;d++){var e=this.lc,f=(0,D.yU)(e,c[d]);f!=D.o&&(0,D.zU)(e,f)}}}else D.nU.QQ(this)};
D.x.DN=function(a){(39==a.keyCode||37==a.keyCode||40==a.keyCode||38==a.keyCode)&&(0,D.AU)(this,this.Ia.dd())};D.x.vB=function(a){this.sh=(0,D.rU)(this,a.target)};D.x.zR=function(a,b){this.G5=a;this.H5=b};D.x.jU=function(a){"none"!=this.Gq&&(0,D.BU)(this,a)};D.x.UL=function(){this.sh=D.o;(0,D.CU)(this)};D.CU=function(a){a.FL&&(a.FL=D.p,a.dispatchEvent(new D.vU("viewportChange",a.zb,a.Sc,a.Yd)))};
D.cU.prototype.BR=function(a,b){if(this.G5&&this.H5){var c=this.G5-a,d=this.H5-b;if(0==c&&0==d)return D.p;this.FL=D.k;this.G5=a;this.H5=b;this.ei(c,d);return D.k}return D.p};
D.cU.prototype.ei=function(a,b){var c=(0,D.iU)(this,this.sb.length);if(this.Tb){var d,e;if(this.sh){var f=this.sh.N()-a;1<this.sb.length&&(!this.nh()&&this.sh.ok||this.nh()&&!this.sh.ok)?(d=c+2*this.sh.Ga-this.sh.Oi,e=this.sh.Ga+c):this.nh()&&!this.sh.ok?(d=this.sh.Ga-this.sh.Oi+c,e=c):(d=0,e=this.sh.Oi-this.sh.Ga);f<d?f=d:f>e&&(f=e);this.sh.I(f)}d=this.Mg.M()-b;e=-(this.Hc-this.Jg-this.oj);c=this.oj;d<e?d=e:d>c&&(d=c);this.Mg.O(d);this.uc=d-this.oj;d=this.Hc/(this.Xb-this.ob);e=this.Sc-this.zb;this.zb=
this.ob-this.uc/d;this.Sc=this.zb+e;this.Or&&(d=this.lc.Ta,this.lc.Yl(this.zb,this.Sc,d))}else f=this.Mg.N()-a,d=-(this.Hc-this.Jg-this.ai),e=this.ai,f<d?f=d:f>e&&(f=e),this.Mg.I(f),this.uc=f-this.ai,this.nh()&&(this.uc=this.Mj-this.Hc-this.uc),d=this.Hc/(this.Xb-this.ob),e=this.Sc-this.zb,this.zb=this.ob-this.uc/d,this.Sc=this.zb+e,this.nh()&&(this.uc=this.Mj-this.Hc-this.uc),this.Or&&(d=this.lc.Ga,this.lc.Yl(this.zb,this.Sc,d)),this.sh&&(d=this.sh.M()-b,this.sh.ok?(e=c+2*this.sh.Ta-this.sh.Oi,c=
this.sh.Ta+c):(e=0,c=this.sh.Oi-this.sh.Ta),d<e?d=e:d>c&&(d=c),this.sh.O(d))};
D.cU.prototype.ffa=function(a){var b=a.Pa();if("selection"==b||"dvtAct"==b)D.QC.dispatchEvent(this.lb,this.ra,this,a);else if("overview"==b){b=a.xj();if("rangeChanging"==b||"rangeChange"==b){var c=this.Sc-this.zb;this.zb=a.Yi("newStartTime");this.Sc=a.Yi("newEndTime");var d=this.Sc-this.zb;if(0<d){var e=this.Jg/d;(0,D.XT)(this,e*(this.Xb-this.ob));this.uc=e*(this.ob-this.zb);this.nh()&&!this.Tb&&(this.uc=this.Mj-this.Hc-this.uc);if(c>d){c=this.Kv.length;for(d=this.Kv[c-1];this.Hc>=d&&0<c;)c--,d=this.Kv[c-
1];c==this.Kv.length&&c--}else{c=0;for(d=this.Kv[c];this.Hc<d&&c<this.Kv.length-1;)c++,d=this.Kv[c]}this.tA=c;this.Yf.Qp(this.Yf.Lv[c]);this.Yd=this.Yf.Yd;(0,D.lU)(this);D.nU.qY(this,this.Mg);(0,D.uU)(this);this.Tb?this.Mg.O(this.oj+this.uc):this.Mg.I(this.ai+this.uc)}"rangeChange"==b&&this.dispatchEvent(new D.vU("viewportChange",this.zb,this.Sc,this.Yd))}if("scrollPos"==b||"scrollTime"==b)this.zb=a.Yi("newStartTime"),this.Sc=a.Yi("newEndTime"),e=this.Hc/(this.Xb-this.ob),this.uc=e*(this.ob-this.zb),
this.nh()&&!this.Tb&&(this.uc=this.Mj-this.Hc-this.uc),this.Tb?this.Mg.O(this.oj+this.uc):this.Mg.I(this.ai+this.uc),this.dispatchEvent(new D.vU("viewportChange",this.zb,this.Sc,this.Yd))}else if(b=a.xj(),"selection"==b){b=a.mH();a=a.Yi("multiSelect");d=(a!=D.o?a:D.p)&&"multiple"==this.Gq;for(a=0;a<this.sb.length;a++)for(var e=this.sb[a],f=0;f<e.Za.length;f++)if(c=e.Za[f],c.getId()==b){(0,D.Kl)(this.Ym,c,d);(0,D.Bj)(this.Ia,c);e=this.Sc-this.zb;this.zb=c.Xf-e/2;this.zb<this.ob?this.zb=this.ob:this.zb+
e>this.Xb&&(this.zb=this.Xb-e);this.Sc=this.zb+e;this.uc=this.Hc/(this.Xb-this.ob)*(this.ob-this.zb);this.nh()&&!this.Tb&&(this.uc=this.Mj-this.Hc-this.uc);this.Tb?this.Mg.O(this.oj+this.uc):this.Mg.I(this.ai+this.uc);this.dispatchEvent(new D.vU("viewportChange",this.zb,this.Sc,this.Yd));break}}else if("highlight"==b){b=a.mH();for(a=0;a<this.sb.length;a++){e=this.sb[a];for(f=0;f<e.Za.length;f++)if(c=e.Za[f],c.getId()==b){c.Ob(D.k);break}}}else if("unhighlight"==b){b=a.mH();for(a=0;a<this.sb.length;a++){e=
this.sb[a];for(f=0;f<e.Za.length;f++)if(c=e.Za[f],c.getId()==b){c.Db(D.k);break}}}};D.tU=function(a,b){b?((0,D.Qe)(a.Ik,D.k),(0,D.Me)(a.Ik)):((0,D.Qe)(a.Jk,D.k),(0,D.Me)(a.Jk))};D.sU=function(a,b){b?((0,D.Qe)(a.Ik,D.p),(0,D.Ne)(a.Ik),a.Ik.setCursor(D.o)):((0,D.Qe)(a.Jk,D.p),(0,D.Ne)(a.Jk),a.Jk.setCursor(D.o))};
D.AU=function(a,b){var c=a.Tb?b.getHeight():b.getWidth(),d=D.$.jra(),e=b.Zo-(a.Tb?c/2+d:D.$.PR()+d);a.nh()&&!a.Tb&&(e-=d,a.uc=a.Mj-a.Hc-a.uc);c=e+c+2*d;d=a.uc-a.Jg;-e>a.uc?a.uc=-e:-c<d&&(a.uc=-c+a.Jg);e=a.Hc/(a.Xb-a.ob);c=a.Sc-a.zb;a.zb=a.ob-a.uc/e;a.zb<a.ob&&(a.zb=a.ob,a.uc=(a.ob-a.zb)*e);a.Sc=a.zb+c;a.Sc>a.Xb&&(a.Sc=a.Xb,a.zb=a.Sc-c,a.uc=(a.ob-a.zb)*e);a.nh()&&!a.Tb&&(a.uc=a.Mj-a.Hc-a.uc);a.Tb?a.Mg.O(a.oj+a.uc):a.Mg.I(a.ai+a.uc);a.Or&&a.lc.Yl(a.zb,a.Sc,a.Tb?a.lc.Ta:a.lc.Ga);a.dispatchEvent(new D.vU("viewportChange",
a.zb,a.Sc,a.Yd))};D.BU=function(a,b){if(b){var c=a.XJ(b.target);if(c){var d=(0,D.rU)(a,c);if(c.Pb){var d=(0,D.rU)(a,c),c=c.Pb,e=c.Ce();e&&(c=new D.DU(e,c.getId()),D.QC.dispatchEvent(d.lb,d.ra,d,c))}}}};D.jU=function(a){if(a.D.selection)for(var b=[],c=0;c<a.sb.length;c++)for(var d=a.sb[c],e=0;e<d.Za.length;e++)b.push(d.Za[e]);(0,D.Il)(a.Ym,a.D.selection,b)};D.cU.prototype.Pd=function(a){a&&this.dispatchEvent(a)};
D.rU=function(a,b){if((0,D.oU)(a)&&b&&b!=a){var c=b.getId();return b==a.sb[0]||1<a.sb.length&&b==a.sb[1]?b:c&&"_s0"==c.substring(c.length-3,c.length)?a.sb[0]:c&&"_s1"==c.substring(c.length-3,c.length)?a.sb[1]:(0,D.rU)(a,b.getParent())}return D.o};
D.cU.prototype.XJ=function(a){if(a){var b=a.getId();if(b&&"_duration_"==b.substring(0,10)&&a.Pb)return a;var c=a.getParent();if(c){if(b&&"zoom"==b.substring(0,4))return a;if(b&&"_bubble_"==b.substring(0,8)&&c.Pb)return c;if(a=c.getParent()){if(b&&"_bubble_"==b.substring(0,8)&&a.Pb)return a;if((b=a.getId())&&"_bubble_"==b.substring(0,8)&&a.getParent())return a.getParent()}}}return D.o};D.cU.prototype.Gf=function(){this.Kk||(this.Kk=new D.EU(this));return this.Kk};D.cU.prototype.getAutomation=D.cU.prototype.Gf;
D.cU.prototype.ka=(0,D.v)("Ia");D.FU=function(a){a.Ct&&(a.removeChild(a.Ct),a.Ct=D.o)};
D.EU=(0,D.ba)("Lc");(0,D.da)("DvtTimelineAutomation",D.EU);D.z.l(D.EU,D.Dj,"DvtTimelineAutomation");D.EU.prototype.ql=function(a){if((a=(0,D.Ej)(this.Lc.Ia,a))&&a instanceof D.GU)for(var b=0;b<this.Lc.sb.length;b++){var c=D.H.wa(this.Lc.sb[b].Za,a);if(-1!=c)return"timelineItem["+b+"]["+c+"]"}return D.o};
D.EU.prototype.If=function(a){if(a){var b=a.indexOf("[");if(0<b&&"timelineItem"===a.substring(0,b)){var c=a.indexOf("]");if(0<c){var d=(0,window.parseInt)(a.substring(c+2,a.length-1));if(a=this.Lc.sb[(0,window.parseInt)(a.substring(b+1,c))])if(d=a.Za[d])return d.Yc()[0].sa()}}}return D.o};D.EU.prototype.getDomElementForSubId=D.EU.prototype.If;
D.dU=function(){this.Init({alta:D.HU})};D.z.l(D.dU,D.Nj,"DvtTimelineDefaults");
D.HU={animationOnDataChange:"none",animationOnDisplay:"none",orientation:"horizontal",overview:{rendered:"off"},selectionMode:"none",styleDefaults:{animationDuration:500,borderColor:"#d9dfe3",item:{backgroundColor:"#ffffff",borderColor:"#648baf",descriptionStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; color: #084B8A; white-space: nowrap;"),hoverBorderColor:"#85bbe7",selectedBorderColor:"#000000",titleStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: bold; color: #000000; white-space: nowrap;")},
majorAxis:{labelStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; color: #4f4f4f; background-color: rgba(249,249,249,0.8); white-space: nowrap;"),separatorColor:"#bcc7d2"},minorAxis:{backgroundColor:"#f9f9f9",borderColor:"#d9dfe3",labelStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; color: #333333;"),separatorColor:"#bcc7d2"},overview:{backgroundColor:"#e6ecf3",labelStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: bold; color: #4f4f4f;"),
window:{backgroundColor:"#ffffff",borderColor:"#4f4f4f"}},referenceObject:{color:"#ff591f"},series:{backgroundColor:"#f9f9f9",colors:D.km,emptyTextStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal; color: #333333; white-space: nowrap;"),labelStyle:new D.G("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 13px; font-weight: bold; color: #252525; background-color: rgba(249,249,249,0.8); white-space: nowrap;")}}};
D.hU=(0,D.t)();D.z.l(D.hU,D.z,"DvtTimelineParser");
D.hU.prototype.parse=function(a){this.Jla=a.selectionMode;a.viewportStart&&(this.zb=new window.Date(a.viewportStart));a.viewportEnd&&(this.Sc=new window.Date(a.viewportEnd));this.Xf=new window.Date(a.start);this.Sh=new window.Date(a.end);var b=this.DE();b.Asa=a.style;var c=a.minorAxis;if(c){var d=c.scale;b.scale=d;var e=c.zoomOrder;e==D.o?e=[d]:e.reverse();b.kOa=e;b.vHa=c.converter;b.fHa=c.style}if(c=a.majorAxis)b.INa=c.scale,b.GNa=c.converter;b.XNa=a.shortDesc;b.id=a.id;b.orientation=a.orientation;
if((c=a.referenceObjects)&&0<c.length){d=[];for(e=0;e<c.length;e++)d.push(new window.Date(c[e].value));b.oNa=d}a=a.overview;b.TLa=a!=D.o&&"on"==a.rendered?D.k:D.p;return b};D.hU.prototype.DE=function(){var a={};a.pta=this.Xf;a.ota=this.Sh;a.orientation="horizontal";a.start=this.Xf.getTime();a.end=this.Sh.getTime();this.zb&&(a.jOa=this.zb.getTime());this.Sc&&(a.iOa=this.Sc.getTime());a.gT="none";this.Jla!=D.o&&(a.gT=this.Jla);return a};
D.nU={};D.z.l(D.nU,D.z,"DvtTimelineRenderer");
D.nU.xNa=function(a){D.nU.Gt(a);D.nU.v9(a);if((0,D.oU)(a)){D.nU.qoa(a,a.qh);D.nU.NFa(a,a.Mg);D.nU.yoa(a);D.nU.qY(a,a.Mg);a.Or?D.nU.toa(a):(0,D.FU)(a);if(a.GC)for(var b=0;b<a.sb.length;b++){var c=a.sb[b];if(c.Za&&0<c.Za.length){(0,D.Bj)(a.Ia,c.Za[0]);break}}D.nU.woa(a);D.nU.Boa(a);a.Ym&&(0,D.jU)(a);D.bP.am()&&(0,D.HE)(a,"flowto",a.sb[0].getId());for(b=0;b<a.sb.length;b++){var c=a.sb[b],d=c.j();c.bD&&0!=c.bD.length?(c.hX=D.k,d=new D.on(d,new D.sn(d,c.bD,D.$.xa(c.D))),d.play(),(0,D.hl)(d,c.oEa,c)):c.Wz?
(c.hX=D.k,c.Wz.play(),(0,D.hl)(c.Wz,c.H8,c)):c.Fz&&0!=c.Fz.length&&(c.hX=D.k,d=new D.on(d,new D.Vm(d,c.Fz,D.$.xa(c.D),0)),d.play(),(0,D.hl)(d,c.zq,c))}(0,D.Zk)()&&!(0,D.pU)(a)&&(0,D.qU)(a)}else D.nU.QQ(a)};D.nU.Gt=function(a){a.Na?((0,D.xg)(a.Na,D.o),a.Na.ma(a.Mj),a.Na.Ea(a.DO)):a.Na=new D.Te(a.j(),0,0,a.Mj,a.DO,"bg");a.Na.Ha(a.gp);(0,D.Ei)(a.Na);var b=new D.ug;(0,D.wg)(b,0,0,a.Mj,a.DO);(0,D.xg)(a.Na,b);a.Na.getParent()!=a&&a.k(a.Na)};D.nU.v9=function(a){a.qh||(a.qh=new D.D(a.j(),"canvas"),a.k(a.qh))};
D.nU.qoa=function(a,b){a.Mg?(0,D.xg)(a.Mg,D.o):a.Mg=new D.D(a.j(),"iCanvas");var c=new D.ug;a.Sa()?((0,D.wg)(c,a.ai,a.oj,a.Br,a.Jg),a.Mg.I(a.ai),a.Mg.O(a.oj+a.uc)):((0,D.wg)(c,a.ai,a.oj,a.Jg,a.Br),a.Mg.I(a.ai+a.uc),a.Mg.O(a.oj));(0,D.xg)(b,c);a.Mg.getParent()!=b&&b.k(a.Mg)};
D.nU.NFa=function(a,b){if(a.sb){var c=(0,D.E)(a.j()),d=a.sb.length,e=(0,D.iU)(a,d);if(!a.Sa()&&1<d&&a.Br%2!=e%2){var e=a.Yf,f=a.Yf.ao+1;f>e.ao&&(e.ao=f);e=(0,D.iU)(a,d)}a.Ff=(a.Br-e)/d;for(f=0;f<d;f++){var g=a.sb[f];(0,D.xg)(g,D.o);var h=new D.ug;if(a.Sa()){var j=c?window.Math.abs(f-1):f;c&&1==a.sb.length?((0,D.wg)(h,e,0,a.Ff,a.Hc),j=new D.hj(1,0,0,1,e,0)):((0,D.wg)(h,j*(a.Ff+e),0,a.Ff,a.Hc),j=new D.hj(1,0,0,1,j*(a.Ff+e),0));var l=a.Ff,m=a.Hc}else(0,D.wg)(h,0,f*(a.Ff+e),a.Hc,a.Ff),j=new D.hj(1,0,
0,1,0,f*(a.Ff+e)),l=a.Hc,m=a.Ff;(0,D.xg)(g,h);g.za(j);g.getParent()!=b&&b.k(g);g.P(a.IY[f],l,m)}}};
D.nU.yoa=function(a){if(a.sb){var b=a.j(),c=(0,D.E)(b);if(a.lL)for(var d=0;d<a.lL.length;d++)a.removeChild(a.lL[d]);a.lL=[];for(var e=a.sb.length,f=D.$.EKa(),g=2*f,d=0;d<e;d++){var h=a.sb[d],j=h.Nc();if(j!=D.o){var l=D.$.FKa(a.D),j=new D.Kf(b,j,0,0,"sl_s"+d);j.Ha(l);a.k(j);var m=j.F();a.removeChild(j);var n=a.Sa()?a.Ff:a.Jg,n=window.Math.min(m.e,n- -38*(d-1)-g),q=D.$.DKa(),r=new D.Te(b,0,0,n+2*q,m.g+2*q,"slb_s"+d);r.Ha(l);(0,D.Eq)(r,3);if(a.Sa())l=c?window.Math.abs(d-1)*(a.Br-n-g)+f+a.ai+38*(d-1):
d*(a.Br-n-g)+f+a.ai+-38*(d-1),s=a.oj+f;else var l=c?a.Jg-n-f- -38*(d-1):a.ai+f+-38*(d-1),s=d*(a.Br-m.g-g)+f+a.oj;m=new D.hj(1,0,0,1,l,s);j.za(m);m=new D.hj(1,0,0,1,l-q,s-q);r.za(m);a.k(r);D.$e.Qb(j,n,window.Infinity,a);a.lL.push(r);a.lL.push(j)}h.jDa&&(h=h.uD(),h!=D.o&&(h=new D.Kf(b,h,0,0,"et_s"+d),h.Ha(D.$.ara(a.D)),a.k(h),m=h.F(),a.removeChild(h),m=new D.hj(1,0,0,1,(a.Jg-m.e)/2+a.ai,d*(a.Ff+(0,D.iU)(a,e))+(a.Ff-m.g)/2+a.oj),h.za(m),a.k(h),a.lL.push(h)))}}};
D.nU.qY=function(a,b){var c=a.j(),d=(0,D.E)(c),e=a.sb.length,f=a.Yf.Tc(),g=(0,D.iU)(a,e),e=1==e?a.Br-g:a.Br/e-g/2;d&&(a.Sa()&&1==a.sb.length)&&(e=0);a.xe==D.o?(d=new D.ug,a.Sa()?(a.xe=new D.Te(c,e,-a.TE,f,a.hV,"axis"),(0,D.wg)(d,e,0,f,a.Hc)):(a.xe=new D.Te(c,-a.TE,e,a.hV,f,"axis"),(0,D.wg)(d,0,e,a.Hc,f)),a.xe.Ha(a.lO),(0,D.Ei)(a.xe),(0,D.xg)(a.xe,d),b.k(a.xe)):((0,D.xg)(a.xe,D.o),d=new D.ug,a.Sa()?(a.xe.ca(e),a.xe.va(-a.TE),a.xe.ma(f),a.xe.Ea(a.hV),(0,D.wg)(d,e,0,f,a.Hc)):(a.xe.ca(-a.TE),a.xe.va(e),
a.xe.ma(a.hV),a.xe.Ea(f),(0,D.wg)(d,0,e,a.Hc,f)),(0,D.xg)(a.xe,d));D.nU.w9(a,e)};D.nU.w9=function(a,b){a.xe.Cj();var c=new D.G(D.$.yIa());if(a.fz){var d=a.fz.separatorColor;d&&(0,D.Uf)(c,"color:"+d+";")}a.kL=new D.hg(c.A("color"));c=b+a.Yf.bF;D.nU.RFa(a,a.Mr,a.Vo,a.xe,a.Hc,c+a.Yf.ao,c,c);D.nU.x9(a,a.Mr,a.Vo,a.Mg,a.Hc)};
D.nU.RFa=function(a,b,c,d,e,f,g,h){var j=a.j(),l=(0,D.E)(j),j=new D.D(j,"block_"+b+"_"+c);j.Tta=b;j.yqa=c;d.k(j);b=a.Hja[a.tA];c=a.Cl[a.tA];for(d=0;d<b.length-1;d++){var m=b[d],n=b[d+1],q=D.bP.fe(a.ob,a.Xb,m,e),n=D.bP.fe(a.ob,a.Xb,n,e),r=n-q;0!=q&&((a.Sa()?a.NL(j,f,g,q,q,a.kL,"s_tick"+m):l?a.NL(j,e-q,e-q,f,g,a.kL,"s_tick"+m):a.NL(j,q,q,f,g,a.kL,"s_tick"+m)).time=m);a.Sa()?(0,D.WT)(j,c[d],h+(f-h)/2,q+(n-q)/2-7,f-h):l?(0,D.WT)(j,c[d],e-(q+(n-q)/2),h+2,r):(0,D.WT)(j,c[d],q+(n-q)/2,h+2,r)}};
D.nU.x9=function(a,b,c,d,e){var f=(0,D.E)(a.j());if(a.WF)for(var g=0;g<a.WF.length;g++)d.removeChild(a.WF[g]);a.WF=[];if(a.ZQ){var g=a.ob,h=a.Xb;b=D.bP.rg(g,h,b,e);b=a.dp.OL(b);for(var j=D.bP.fe(g,h,b,e);j<c;){var l=(0,D.aU)(a.dp,b),m=a.dp.lM(b.getTime()),n=D.bP.fe(g,h,m,e),q=n-j,r=j;(f?a.Sa()?a.kD(d,a.Br-5,l,q,r+18,D.$.C_(a.D),"o_label"+j+"_s0",D.k,D.$.B_(),a.WF,f):a.kD(d,e-(r+5),l,q,a.Ff-2,D.$.C_(a.D),"o_label"+j+"_s0",D.k,D.$.B_(),a.WF,f):a.Sa()?a.kD(d,5,l,q,r+18,D.$.C_(a.D),"o_label"+j+"_s0",
D.k,D.$.B_(),a.WF,f):a.kD(d,r+5,l,q,a.Ff-2,D.$.C_(a.D),"o_label"+j+"_s0",D.k,D.$.B_(),a.WF,f)).time=b.getTime();b=m;j=n}}};
D.nU.toa=function(a){var b=a.j(),c=(0,D.E)(b);if(a.Ct==D.o){var d=D.k;a.Ct=new D.D(b,"oCanvas")}else a.Ct.Cj();var e=a.gp.Sg(),f=e/2;if(a.Sa()){var g=a.UC,e=a.Ta-e;c?a.Ct.I(f):a.Ct.I(a.Ga-a.UC-f);a.Ct.O(f)}else g=a.Ga-e,e=a.UC,a.Ct.O(a.Ta-a.UC-f),a.Ct.I(f);d&&a.k(a.Ct);a.lc=new D.LU(b,a.ffa,a);a.Ct.k(a.lc);var b=a.Tb?"":'_ds\x3d"square" _dsx\x3d"1.3d" _dsy\x3d"0.9d" ',c=D.$.fKa(a.D),d=D.$.gKa(a.D),f=D.$.iKa(a.D),h=D.$.jKa(a.D),j=D.$.Sra(a.D),b='\x3ctimelineOverview renstart\x3d"'+a.zb+'" start\x3d"'+
a.ob+'" end\x3d"'+a.Xb+'" width\x3d"'+a.Hc+'" orn\x3d"'+(a.Tb?"vertical":"horizontal")+(a.yG&&0<a.yG.length&&a.yG[0]?'" ocd\x3d"'+a.yG[0].getTime():"")+'" _hbi\x3d"'+(a.Tb?a.Ti.overviewHandleVert+'" _hw\x3d"15" _hh\x3d"3"':a.Ti.overviewHandleHor+'" _hw\x3d"3" _hh\x3d"15"')+' ovp\x3d"below" selmode\x3d"'+a.Gq+'" rtl\x3d"'+a.nh()+'" sid\x3d"ts1" _bts\x3d"none" _btc\x3d"#4f4f4f" _fc\x3d"#aadd77" '+b+'_do\x3d"0" _wbc\x3d"'+f+'" _wbts\x3d"solid" _wbrs\x3d"solid" _wbbs\x3d"solid" _wbls\x3d"solid" _wbtc\x3d"'+
h+'" _wbrc\x3d"'+h+'" _wbbc\x3d"'+h+'" _wblc\x3d"'+h+'" _hfc\x3d"'+f+'" _obc\x3d"'+c+'" _ctic\x3d"'+j+'" _ls\x3d"'+d+'" _tic\x3d"#BCC7D2" _tabc\x3d"#D9DFE3" _tabo\x3d"0" _bs\x3d"solid" _bc\x3d"#648BAF" _bw\x3d"1px" _bof\x3d"0px" _dbs\x3d"solid" _dbc\x3d"#648BAF" _dbw\x3d"1px" _hbs\x3d"solid" _hbc\x3d"#85bbe7" _hbw\x3d"2px" _hbof\x3d"0px" _hgc\x3d"#ebeced" _hgo\x3d"1" _hdbs\x3d"solid" _hdbc\x3d"#85bbe7" _hdbw\x3d"2px" _sbs\x3d"solid" _sbc\x3d"#000000" _sbw\x3d"2px" _sbof\x3d"0px" _sbo\x3d"1" _sdbs\x3d"solid" _sdbc\x3d"#000000" _sdbw\x3d"2px" _asbs\x3d"solid" _asbc\x3d"#000000" _asbw\x3d"2px" _asbof\x3d"0px" _asbo\x3d"1" _asgc\x3d"#e4f0fa" _asgo\x3d"1" _asdbs\x3d"solid" _asdbc\x3d"#000000" _asdbw\x3d"2px" _aoc\x3d"off"\x3e',
c="\x3cticks\x3e";if(a.dp)for(var d=a.ob,f=a.Xb,h=a.Tb?a.Ta:a.Ga,j=D.bP.rg(d,f,a.Mr,h),j=a.dp.OL(j),l=D.bP.fe(d,f,j,h);l<a.Vo;)var l=(0,D.aU)(a.dp,j),m=a.dp.lM(j.getTime()),n=D.bP.fe(d,f,m,h),c=c+('\x3ctick time\x3d"'+j.getTime()+'" label\x3d"'+l+'"/\x3e'),j=m,l=n;b+=c+"\x3c/ticks\x3e";if(a.sb){c="\x3cmarkers\x3e";d=a.sb.length;for(f=0;f<d;f++){h=a.sb[f].Za;for(j=0;j<h.length;j++){l=h[j];c+='\x3cti rk\x3d"'+j;c+='" tid\x3d"'+l.getId();c+='" t\x3d"'+l.Xf;if(m=l.Sh)c+='" et\x3d"'+m,(l=l.Cz)&&(c+='" dfc\x3d"'+
l);c+='" _sd\x3d"true"/\x3e'}}c+="\x3c/markers\x3e"}else c=D.i;a.lc.P(b+c+"\x3c/timelineOverview\x3e",g,e)};
D.nU.woa=function(a){if(a.sb){var b=a.j(),c=(0,D.E)(b),d=a.sb.length,e=(0,D.iU)(a,d);if(a.YQ)for(var f=0;f<a.YQ.length;f++)a.YQ[f].Cj();else{var g=D.k;a.YQ=[]}a.cD=[];for(var h=D.$.yJa(),j=D.$.zJa(),l=D.$.wJa(),m=D.$.tJa(),n=D.$.sJa(),q=D.$.uJa(),r=D.$.vJa(),f=0;f<d;f++){if(g){var s=new D.D(b,"hotspots_s"+f);a.k(s);a.YQ.push(s)}else s=a.YQ[f];if(a.Sa())var u=c?window.Math.abs(f-1):f,w=N=a.ai+u*(a.Ff+e)+(a.Ff-j)/2,y=a.oj+h,C=a.oj+a.Jg-l-h,u=Y=N+m/2,O=y+n/2,M=C+n/2,J=a.Ti.scrollUp,R=a.Ti.scrollDown;
else var N=a.ai+h,w=a.ai+a.Jg-j-h,y=a.oj+f*(a.Ff+e)+(a.Ff-l)/2,C=y,Y=N+m/2,u=w+m/2,O=y+n/2,M=O,J=a.Ti.scrollLeft,R=a.Ti.scrollRight;N=new D.Te(b,N,y,j,l,"lhs");N.pa(q,1);(0,D.Eq)(N,r);N.DH="left";N.B(0);N.qa(D.p);Y=new D.Ue(b,J,Y,O,m,n,"lhs_arr");Y.DH="left";N.k(Y);w=new D.Te(b,w,C,j,l,"rhs");w.pa(q,1);(0,D.Eq)(w,r);w.DH="right";w.B(0);w.qa(D.p);u=new D.Ue(b,R,u,M,m,n,"rhs_arr");u.DH="right";w.k(u);s.k(N);a.cD.push(N);s.k(w);a.cD.push(w);a.Sa()?(u=c?window.Math.abs(f-1):f,N=a.ai+u*(a.Ff+e)+h,w=a.ai+
(u+1)*a.Ff+u*e-j-h,C=y=a.oj+(a.Jg-l)/2,Y=N+m/2,u=w+m/2,M=O=y+n/2,J=a.Ti.scrollLeft,R=a.Ti.scrollRight):(w=N=a.ai+(a.Jg-j)/2,y=a.oj+f*(a.Ff+e)+h,C=a.oj+(f+1)*a.Ff+f*e-l-h,u=Y=N+m/2,O=y+n/2,M=C+n/2,J=a.Ti.scrollUp,R=a.Ti.scrollDown);N=new D.Te(b,N,y,j,l,"ths");N.pa(q,1);(0,D.Eq)(N,r);N.DH="top";N.B(0);N.qa(D.p);Y=new D.Ue(b,J,Y,O,m,n,"ths_arr");Y.DH="top";N.k(Y);w=new D.Te(b,w,C,j,l,"bhs");w.pa(q,1);(0,D.Eq)(w,r);w.DH="bottom";w.B(0);w.qa(D.p);u=new D.Ue(b,R,u,M,m,n,"bhs_arr");u.DH="bottom";w.k(u);
s.k(N);a.cD.push(N);s.k(w);a.cD.push(w)}}};
D.nU.Boa=function(a){var b=a.j(),c=(0,D.E)(b),d=(0,D.LF)(b,a.Ti.zoomIn),e=(0,D.LF)(b,a.Ti.zoomIn_h),f=(0,D.LF)(b,a.Ti.zoomIn_a),g=(0,D.LF)(b,a.Ti.zoomIn_d);a.Ik==D.o?(a.Ik=new D.KF(b,d,e,f,g,a.Ia,a.Ia.w2),a.Ia.Ca(a.Ik,a.Ik)):((0,D.$t)(a.Ik,d),(0,D.bu)(a.Ik,e),(0,D.au)(a.Ik,f),(0,D.EF)(a.Ik,g));d=(0,D.LF)(b,a.Ti.zoomOut);e=(0,D.LF)(b,a.Ti.zoomOut_h);f=(0,D.LF)(b,a.Ti.zoomOut_a);g=(0,D.LF)(b,a.Ti.zoomOut_d);a.Jk==D.o?(a.Jk=new D.KF(b,d,e,f,g,a.Ia,a.Ia.z2),a.Ia.Ca(a.Jk,a.Jk)):((0,D.$t)(a.Jk,d),(0,D.bu)(a.Jk,
e),(0,D.au)(a.Jk,f),(0,D.EF)(a.Jk,g));a.Ik.Fj((0,D.L)("DvtUtilBundle","ZOOM_IN",D.o));a.Jk.Fj((0,D.L)("DvtUtilBundle","ZOOM_OUT",D.o));a.Ik.Co();a.Jk.Co();D.bP.am()&&(D.B.C(a.Ik.sa(),"role","button"),D.B.C(a.Ik.sa(),"aria-label",(0,D.L)("DvtUtilBundle","ZOOM_IN",D.o)),D.B.C(a.Jk.sa(),"role","button"),D.B.C(a.Jk.sa(),"aria-label",(0,D.L)("DvtUtilBundle","ZOOM_OUT",D.o)));c?(a.Ik.I(a.Mj-44),a.Jk.I(a.Mj-44)):(a.Ik.I(a.ai+11),a.Jk.I(a.ai+11));a.Ik.O(a.oj+11);a.Jk.O(a.oj+48);a.Ik.getParent()!=a.qh&&a.qh.k(a.Ik);
a.Jk.getParent()!=a.qh&&a.qh.k(a.Jk);b=a.Hc;b>=a.i8&&(0,D.sU)(a,D.k);a.Jg>=b&&(0,D.sU)(a,D.p)};D.nU.QQ=function(a){var b=a.D.series?(0,D.L)("DvtUtilBundle","INVALID_DATA",D.o):(0,D.L)("DvtUtilBundle","NO_DATA",D.o);a.qh&&a.qh.Cj();(0,D.FU)(a);D.$e.Om(a.qh,b,new D.A(0,0,a.Mj,a.DO),a.Ia,D.$.ara(a.D))};
D.$={};D.z.l(D.$,D.z,"DvtTimelineStyleUtils");D.$.Pxa="border:1px #d9dfe3;background-color:#f9f9f9;";D.$.kxa="background-color:#f9f9f9;border:1px #d9dfe3;";D.$.jxa="color:#bcc7d2;";D.$.Mxa="background-color:#f9f9f9;";D.$.Lxa=20;D.$.Kxa=2;D.$.Jxa="color:#bcc7d2";D.$.Ixa=1;D.$.Gxa=60;D.$.Fxa=100;D.$.rxa="#000000";D.$.sxa=2;D.$.uxa=0.6;D.$.wxa=28;D.$.txa=28;D.$.vxa=3;D.$.qxa=14;D.$.pxa=14;D.$.oxa=0.3;D.$.zxa=1;D.$.Axa=2;D.$.Dxa=2;D.$.Bxa="rgba(249,249,249,0)";D.$.xxa="#e4f0fa";D.$.yxa="rgba(249,249,249,0)";
D.$.Cxa=2;D.$.lxa=20;D.$.mxa=15;D.$.nxa=10;D.$.Oxa=32;D.$.Nxa=32;D.$.ira=function(a){var b=a.sb.q().styleDefaults.item.descriptionStyle;if(a=a.A())a=new D.G(a),(0,D.Uf)(b,a);return b};D.$.pra=function(a){var b=a.sb.q().styleDefaults.item.titleStyle;if(a=a.A())a=new D.G(a),(0,D.Uf)(b,a);return b};D.$.Sra=function(a){return a.styleDefaults.referenceObject.color};D.$.FKa=function(a){return a.styleDefaults.series.labelStyle};D.$.DKa=function(){return D.$.Kxa};D.$.EKa=function(){return D.$.Lxa};
D.$.ara=function(a){return a.styleDefaults.series.emptyTextStyle};D.$.PR=function(){return D.$.lxa};D.$.ZL=function(){return D.$.mxa};D.$.aba=function(a){var b=a.A();return b&&(b=(new D.G(b)).A("background-color"))?b:a.sb.q().styleDefaults.item.backgroundColor};D.$.dS=function(a){var b=a.A();return b&&(b=(new D.G(b)).A("border-color"))?b:a.sb.q().styleDefaults.item.borderColor};D.$.bba=function(){return D.$.zxa};
D.$.BJa=function(a){var b=a.sb.q().styleDefaults.item.hoverBackgroundColor;return b?b:D.$.aba(a)};D.$.CJa=function(a){var b=a.sb.q().styleDefaults.item.hoverBorderColor;return b?b:D.$.dS(a)};D.$.jra=function(){return D.$.Axa};D.$.mra=function(a){var b=a.sb.q().styleDefaults.item.selectedBackgroundColor;return b?b:D.$.aba(a)};D.$.nra=function(a){var b=a.sb.q().styleDefaults.item.selectedBorderColor;return b?b:D.$.dS(a)};D.$.ora=function(){return D.$.Dxa};D.$.GKa=function(){return D.$.Mxa};
D.$.NIa=function(a){return a.styleDefaults.series.colors};D.$.$qa=function(){return D.$.nxa};D.$.Dba=function(){return D.$.Oxa};D.$.Xra=function(){return D.$.Nxa};D.$.CKa=function(){return D.$.Jxa};D.$.kra=function(){return D.$.xxa};D.$.DJa=function(){return D.$.Bxa};D.$.lra=function(){return D.$.yxa};D.$.EJa=function(){return D.$.Cxa};D.$.fra=function(){return D.$.oxa};D.$.xJa=function(){return D.$.uxa};D.$.ZKa=function(){return D.$.Pxa};D.$.hKa=function(){return D.$.Gxa};D.$.mba=function(){return D.$.Fxa};
D.$.zIa=function(){return D.$.kxa};D.$.xIa=function(a){return a.styleDefaults.minorAxis.labelStyle};D.$.iKa=function(a){return a.styleDefaults.overview.window.backgroundColor};D.$.jKa=function(a){return a.styleDefaults.overview.window.borderColor};D.$.fKa=function(a){return a.styleDefaults.overview.backgroundColor};D.$.gKa=function(a){return a.styleDefaults.overview.labelStyle};D.$.C_=function(a){return a.styleDefaults.majorAxis.labelStyle};D.$.yIa=function(){return D.$.jxa};D.$.B_=function(){return D.$.Ixa};
D.$.yJa=function(){return D.$.vxa};D.$.zJa=function(){return D.$.wxa};D.$.wJa=function(){return D.$.txa};D.$.tJa=function(){return D.$.qxa};D.$.sJa=function(){return D.$.pxa};D.$.uJa=function(){return D.$.rxa};D.$.vJa=function(){return D.$.sxa};D.$.xa=function(a){return(0,D.hp)(a.styleDefaults.animationDuration)/1E3};
D.mU=function(a,b,c){this.Init(a,b,c)};D.z.l(D.mU,D.VT,"DvtTimelineSeries");D.x=D.mU.prototype;D.x.Init=function(a,b,c){D.mU.o.Init.call(this,a,b,c);this.aF=[];this.TQ=[];this.KY=[];this.LPa=[]};D.x.oEa=function(){for(var a=0;a<this.bD.length;a++){var b=this.bD[a];b.getParent().removeChild(b)}this.Wz&&this.fla?(this.Wz.play(),(0,D.hl)(this.Wz,this.H8,this)):this.H8()};
D.x.H8=function(){if(this.Fz&&0!=this.Fz.length){var a=new D.on(this.j(),new D.Vm(this.j(),this.Fz,D.$.xa(this.D),0));a.play();(0,D.hl)(a,this.zq,this)}else this.zq()};D.x.zq=function(){this.hX=D.p;(0,D.Zk)()&&(0,D.qU)(this.ra)};
D.x.P=function(a,b,c){a&&this.vd(a);this.lDa=this.Ga?D.p:D.k;this.Ga=b;this.Ta=c;(a=this.D.orientation)&&"vertical"==a?(this.gO=this.Tb==D.p?D.p:D.k,this.Tb=D.k):(this.gO=this.Tb?D.p:D.k,this.Tb=D.p);this.D&&(a=this.AE(this.D),this.Ku(a));this.Mr=0;this.Tb?(this.Vo=c,this.Oi=b,this.Ng=c,this.no=b):(this.Vo=b,this.Oi=c,this.Ng=b,this.no=c);this.ok=this.D.inverted;this.Rz=this.fx=0;D.xU.wNa(this,b,c);D.bP.am()&&0<this.Za.length&&(0,D.HE)(this,"flowto","_bt_"+this.Za[0].getId());if(b=this.Hj())D.B.C(this.sa(),
"role","group"),D.B.C(this.sa(),"aria-label",D.jg.aB(b))};D.x.Hj=function(){var a=[(0,D.L)("DvtUtilBundle","TIMELINE_SERIES")];this.Cb?a.push(this.Cb):a.push(this.D.index+1);return(0,D.L)("DvtUtilBundle","COLON_SEP_LIST",a)};D.x.QL=function(){this.gp=new D.G(D.$.GKa());this.GG=this.D.seriesStyleDefaults;this.fz=this.D.axisStyleDefaults;this.dja=D.$.NIa(this.D);this.yG=this.D.referenceObjects;if(this.GG){var a=this.GG.backgroundColor;a&&(0,D.Uf)(this.gp,"background-color:"+a+";")}D.cU.o.QL.call(this)};
D.x.vd=(0,D.ba)("D");D.x.AE=function(a){this.vv=new D.UU;return this.vv.parse(a,this.Za)};D.x.Ku=function(a){this.Za&&(this.nQ=this.Za);this.jDa=(this.Za=a.Ul)&&0<this.Za.length?D.p:D.k;this.kDa=a.mMa;this.iDa=a.eMa;this.Cb=a.label;this.Yf=a.dOa;this.jn=a.hIa;this.jn==D.o&&(this.jn=(0,D.L)("DvtUtilBundle","NO_DATA",D.o));D.mU.o.Ku.call(this,a)};
D.VU=function(a,b,c){if(!(a.Yo==D.o||0==a.Yo.length)){var d=b.Zo,e=b.Hq;e==D.o&&(e=a.IP);var f=a.Oi;if(a.Tb)for(h=0;h<c;h++)j=a.Yo[h],l=j.getWidth()+10,f<e+l&&(f=e+l);else for(var g=D.$.ZL(),h=0;h<c;h++){var j=a.Yo[h],l=j.getWidth()+10,m=j.getHeight();if(j.Zo!=D.o&&j!=b){var n=j.Zo;n==D.o&&(n=0);j=j.Hq;j==D.o&&(j=a.IP);d>=n&&(d<=n+l&&e>=j&&e<=j+m)&&(e=j+m+g,b.Hq=e,e=(0,D.VU)(a,b,c))}f<e+m&&(f=e+m)}f>a.Oi&&(a.Oi=f+D.$.ZL());return e}};
D.WU=function(a,b,c){if(!(a.Za==D.o||0==a.Za.length)){var d=b.Xf,e=b.Sh;if(e&&e!=d){e=b.nq;e==D.o&&(e=1);for(var f=0;f<c;f++){var g=a.Za[f];if(g!=b){var h=g.Xf,j=g.Sh;j&&j!=h&&(g=g.nq,g==D.o&&(g=1),d>=h&&(d<=j&&e==g)&&(e=g+1,b.nq=e,e=(0,D.WU)(a,b,c)))}}e>a.Rz&&(a.Rz=e);return e}}};
D.mU.prototype.F0=function(){for(var a=0;a<this.Za.length;a++){var b=this.Za[a],c=b.Xf,d=b.Sh;d&&d!=c&&(c=(0,D.WU)(this,b,this.Za.length),b.nq=c,b.nP=22+10*b.nq-5,b.Cz==D.o&&(b.Cz=this.dja[this.fx],this.fx++,this.fx==this.dja.length&&(this.fx=0)))}};D.mU.prototype.Nc=(0,D.v)("Cb");D.mU.prototype.uD=(0,D.v)("jn");D.DU=function(a,b){D.DU.o.constructor.call(this,"action",a,b)};(0,D.da)("DvtTimelineSeriesActionEvent",D.DU);D.z.l(D.DU,D.Sj,"DvtTimelineSeriesActionEvent");
D.XU=function(a,b){this.Init(a,b)};D.z.l(D.XU,D.D,"DvtTimelineSeriesItem");D.x=D.XU.prototype;D.x.Init=function(a,b){D.XU.o.Init.call(this,a,"g",b)};D.x.jb=function(a){this.Th!=a&&((this.Th=a)?this.Al?this.vn("asel"):this.vn("sel"):this.vn("en"))};D.x.Ob=function(a){this.Al||(this.Al=D.k,this.Th&&a?this.vn("asel"):this.Th?this.vn("sel"):this.vn("hl"))};D.x.Db=function(a){this.Th&&a?this.vn("asel"):this.Th?this.vn("sel"):this.vn("en");this.Al=D.p};
D.x.vn=function(a){var b=this.Pb,c=b.vg;if(c!=D.o){var d=c.ha(0),e=d.ha(0),c=b.NJ;if("asel"==a){a=D.$.mra(b);var f=D.$.nra(b),g=D.$.ora(),h=D.$.kra()}else"sel"==a?(a=D.$.mra(b),f=D.$.nra(b),g=D.$.ora(),h=D.$.lra()):"hl"==a?(a=D.$.BJa(b),f=D.$.CJa(b),g=D.$.jra(),h=D.$.kra()):(a=D.$.aba(b),f=D.$.dS(b),g=D.$.bba(),h=D.$.lra());var j=D.$.EJa(),f=new D.hg(f,1,g),h=new D.hg(h,1,j);d.pa(a);d.V(f);e.V(h);(b=b.VJ)&&b.V(f);c&&c.V(f)}};
D.YU={};D.z.l(D.YU,D.z,"DvtTimelineSeriesItemRenderer");D.YU.vNa=function(a,b,c,d,e,f){a.Ii?(D.YU.eFa(a,b,c,e),D.YU.Q5(a,b,d,D.o)):(b.fla=D.k,D.YU.Q5(a,b,d,f));b.Sa()||(a.VJ&&b.gO?D.YU.Cpa(a,b,d,f):D.YU.pFa(a,b,c.qaa,d,e))};D.YU.aMa=function(a,b){a.vg&&b.gO?D.YU.zpa(a,b):D.YU.YAa(a,b)};D.YU.YAa=function(a,b){var c=(0,D.VU)(b,a,b.Za.length);a.Hq=c;c=D.YU.VBa(a,b);b.k(c);var d=c.F();b.removeChild(c);a.ma(d.e+10);a.Ea(d.g+10);a.Ii=c};
D.YU.eFa=function(a,b,c,d){var e=b.j(),f=(0,D.E)(e),g=a.getId(),h=a.Ii;a.Ii=D.o;var j=a.getWidth(),l=a.getHeight(),m="_bubble_"+g;if(b.Sa()){var n=l/2,q=n-6,r=n+6;!f&&b.ok||f&&!b.ok?(f=[0,0,0,q,-6,n,0,r,0,l,j,l,j,0,0,0],l=[2,2,2,q,-4,n,2,r,2,l-2,j-2,l-2,j-2,2,2,2]):(f=[0,0,0,l,j,l,j,r,j+6,n,j,q,j,0,0,0],l=[2,2,2,l-2,j-2,l-2,j-2,r,j+4,n,j-2,q,j-2,2,2,2])}else n=f?j-D.$.PR():D.$.PR(),q=n-6,r=n+6,b.ok?(f=[0,0,q,0,n,-6,r,0,j,0,j,l,0,l,0,0],l=[2,2,q,2,n,-4,r,2,j-2,2,j-2,l-2,2,l-2,2,2]):(f=[0,0,0,l,q,l,
n,l+6,r,l,j,l,j,0,0,0],l=[2,2,2,l-2,q,l-2,n,l+4,r,l-2,j-2,l-2,j-2,2,2,2]);j=new D.Un(e,f,m);m=new D.Un(e,l,m+"_i");m.pa(D.$.DJa());(0,D.pk)(h,5,5);j.k(m);j.k(h);e=new D.XU(e,"_bt_"+g);d&&(e.B(0),d.push(e));e.k(j);D.bP.am()&&D.B.C(e.ya,"id",e.Xa);e.Pb=a;a.vg=e;e.vn("en");0<=a.Zo&&c.k(e);e.Ud("group");a.Iq();b.ra.Ia.Ca(e,a)};
D.YU.Q5=function(a,b,c,d){var e=(0,D.E)(b.j()),f=a.Zo,g=a.getWidth(),h=a.getHeight(),j=a.Hq;a=a.vg;b.Sa()?(h=f-h/2,e&&b.ok||!e&&!b.ok?e=b.no-(g+b.IP)+c:(e=b.IP,c=0)):(e=e?b.Ng-f-g+D.$.PR():f-D.$.PR(),b.ok?(c=0,h=j):h=b.Ta-j-h+c);d?(b.Sa()?a.I(a.N()+b.MV+c):a.O(a.M()+b.dF+c),(0,D.T)(d,"typeNumber",a,a.N,a.I,e),(0,D.T)(d,"typeNumber",a,a.M,a.O,h)):(0,D.pk)(a,e,h)};
D.YU.VBa=function(a,b){var c=b.j(),d=(0,D.E)(c),e=a.Yv(),f=a.JJ,g=a.hpa,h=new D.D(c),j=0,l=0;if(d)e&&(m=new D.Kf(c,e,0,l),m.Ha(D.$.pra(a)),j=m.Eb().e+2,l=15,h.k(m)),f&&(f=new D.Kf(c,f,0,l),f.Ha(D.$.ira(a)),e=f.Eb().e+2,0!=j&&e!=j?e>j?(m.ca(e-j),j=e):f.ca(j-e):j=e,h.k(f)),g&&(g=new D.Ue(c,g,j,0,D.$.Dba(),D.$.Xra(),"_tn"),g.qa(D.p),h.k(g));else{g&&(g=new D.Ue(c,g,0,0,D.$.Dba(),D.$.Xra(),"_tn"),g.qa(D.p),h.k(g),j=D.$.Dba()+2);if(e){var m=new D.Kf(c,e,j,l);m.Ha(D.$.pra(a));l=15;h.k(m)}f&&(f=new D.Kf(c,
f,j,l),f.Ha(D.$.ira(a)),h.k(f))}return h};D.YU.zpa=function(a,b){var c=(0,D.VU)(b,a,b.Za.length);a.Hq=c};D.YU.pFa=function(a,b,c,d,e){var f=b.j(),g=(0,D.E)(f),h=a.getId(),j=a.Zo,l=a.Hq;if(b.ok)m=a.nP,d=l;else{var m=b.Ta+d-a.nP;d=b.Ta-l+d}b=g?b.Ng-j:j;f=new D.Di(f,b,m,b,d,"_feeler_"+h);e&&(f.B(0),e.push(f));c.k(f);c=D.$.bba();e=D.$.dS(a);c=new D.hg(e,1,c);f.V(c);f.Pb=a;a.VJ=f};
D.YU.Cpa=function(a,b,c,d){if(b.Sa())a.VJ=D.o;else{var e=(0,D.E)(b.j()),f=a.VJ;if(b.ok)c=0,g=a.nP,h=a.Hq;else var g=b.Ta+c-a.nP,h=b.Ta-a.Hq+c;a=e?b.Ng-a.Zo:a.Zo;d?(f.ol(f.Fp()+b.dF+c),f.$l(f.ns()+b.dF+c),(0,D.T)(d,"typeNumber",f,f.Bo,f.nl,a),(0,D.T)(d,"typeNumber",f,f.Fp,f.ol,g),(0,D.T)(d,"typeNumber",f,f.Zq,f.Zl,a),(0,D.T)(d,"typeNumber",f,f.ns,f.$l,h)):(f.nl(a),f.ol(g),f.Zl(a),f.$l(h))}};D.YU.rNa=function(a,b,c,d,e,f){a.NJ?D.YU.Wx(a,b,d,f):D.YU.nFa(a,b,c,d,e)};
D.YU.nFa=function(a,b,c,d,e){var f=b.j(),g=(0,D.E)(f),h=a.Sh,j=D.bP.fe(b.ob,b.Xb,a.Xf,b.Ng),l="_duration_"+a.getId(),m=22+10*a.nq,h=D.bP.fe(b.ob,b.Xb,h,b.Ng);b.Sa()?(!g&&!b.ok||g&&b.ok?f=new D.Te(f,b.no-m+5,j,m,h-j,l):(f=new D.Te(f,-5,j,m,h-j,l),d=0),f.I(d),f.va(j),f.ma(m),f.Ea(h-j)):(h-=j,j=g?b.Ng-j-h:j,b.ok?(f=new D.Te(f,j,-5,h,m,l),f.O(0)):(f=new D.Te(f,j,b.no-m+5,h,m,l),f.O(d)));e&&(f.B(0),e.push(f));(0,D.Eq)(f,5);f.pa(a.Cz);d=D.$.bba();e=D.$.dS(a);d=new D.hg(e,1,d);f.V(d);f.Pb=a;b.ra.Ia.Ca(f,
a);c.k(f);a.NJ=f};
D.YU.Wx=function(a,b,c,d){var e=(0,D.E)(b.j()),f=a.NJ;if(f!=D.o){var g=D.bP.fe(b.ob,b.Xb,a.Xf,b.Ng),h=22+10*a.nq,j=D.bP.fe(b.ob,b.Xb,a.Sh,b.Ng);if(b.Sa()){a=0;!e&&!b.ok||e&&b.ok?e=b.no-h+5:(e=-5,c=0);var l=c,m=g,n=h,g=j-g}else l=0,j-=g,e=e?b.Ng-g-j:g,b.ok?(a=c=0,m=-5):(a=c,m=b.no-h+5),n=j,g=h;d?(b.Sa()?f.I(f.N()+b.MV+c):f.O(f.M()+b.dF+c),(0,D.T)(d,"typeNumber",f,f.N,f.I,l),(0,D.T)(d,"typeNumber",f,f.M,f.O,a),(0,D.T)(d,"typeNumber",f,f.ja,f.ca,e),(0,D.T)(d,"typeNumber",f,f.na,f.va,m),(0,D.T)(d,"typeNumber",
f,f.getWidth,f.ma,n),(0,D.T)(d,"typeNumber",f,f.getHeight,f.Ea,g)):(f.I(l),f.O(a),f.ca(e),f.va(m),f.ma(n),f.Ea(g))}};
D.GU=function(a,b,c){this.Init(a,b,c)};D.z.l(D.GU,D.z,"DvtTimelineSeriesNode");D.x=D.GU.prototype;D.x.Init=function(a,b,c){this.Lc=a;this.Ag=b;this.sb=a.sb[b];this.Xa=c.id;this.XQ=c.bda;this.Xf=(0,window.parseInt)(c.startTime);c.nD&&(this.Sh=(0,window.parseInt)(c.nD));this.qj=c.title;this.JJ=c.KZ;this.hpa=c.Wta;this.gp=c.style;this.oa=c.data;this.an=c.action;this.Cz=c.OZ;this.nP=0};D.x.getId=(0,D.v)("Xa");D.x.Fe=(0,D.v)("sb");D.x.sg=(0,D.v)("Ag");D.x.rba=(0,D.v)("XQ");D.x.Yv=(0,D.v)("qj");D.x.A=(0,D.v)("gp");
D.x.getData=(0,D.v)("oa");D.x.Nc=function(){return this.Sh!=D.o?"Start Time: "+(new window.Date(this.Xf)).toLocaleString()+"; End Time: "+(new window.Date(this.Sh)).toLocaleString()+"; Title: "+this.Yv()+"; Description: "+this.JJ:"Time: "+(new window.Date(this.Xf)).toLocaleString()+"; Title: "+this.Yv()+"; Description: "+this.JJ};D.x.getWidth=(0,D.v)("Iv");D.x.ma=(0,D.ba)("Iv");D.x.getHeight=(0,D.v)("$ka");D.x.Ea=(0,D.ba)("$ka");D.x.Ce=(0,D.v)("an");
D.x.Ad=function(a){var b=this.Lc.Ia.Sf;if(a.type==D.kk||b.ar(a))return this;if(b.tg(a)){for(var b=[],c=0;c<this.Lc.sb.length;c++)b.push(this.Lc.sb[c].Za);return(0,D.KU)(this,a,b)}return D.o};D.x.yj=function(){return this.vg.sa()};D.x.Ee=function(a){return this.vg.F(a)};D.x.Vd=function(){this.Ib=D.k;this.Ob();(0,D.AU)(this.Lc,this)};D.x.jc=function(){this.Ib=D.p;this.Db()};D.x.pc=(0,D.v)("Ib");D.x.Yc=function(){return[this.vg]};
D.x.fc=function(){var a=[];this.Aa()&&a.push((0,D.L)("DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.ok)(this.Nc(),a)};D.x.Lf=(0,D.ba)("qDa");D.x.Aa=(0,D.v)("qDa");D.x.Da=(0,D.v)("Th");
D.x.jb=function(a){this.Th=a;this.vg.jb(a);this.Iq();if(this.Lc.Or&&this.Lc.lc)if(a){a=this.Lc.lc;var b=this.getId(),b=(0,D.yU)(a,b);b!=D.o&&(0,D.zU)(a,b)}else if(a=this.Lc.lc,b=this.getId(),b=(0,D.yU)(a,b),b!=D.o&&a.sk!=D.o){for(var c=-1,d=0;d<a.sk.length;d++)if(b==a.sk[d]){c=d;break}-1!=c&&(a.vn(b,"_"),a.sk.splice(c,1))}};
D.x.Ob=function(a){this.vg.Ob(this.Lc.Ia.dd()==this);if(!a&&this.Lc.Or){a=this.Lc.lc;var b=this.getId(),b=(0,D.yU)(a,b);b!=D.o&&(0,D.QU)(a,b)}this.Lc.Tb&&(this.zl||(this.zl=this.sb.aF[0].Qf(this.vg)),this.sb.aF[0].k(this.vg))};D.x.Db=function(a){this.vg.Db(this.Lc.Ia.dd()==this);if(!a&&this.Lc.Or){a=this.Lc.lc;var b=this.getId(),b=(0,D.yU)(a,b);b!=D.o&&(0,D.RU)(a,b)}this.Lc.Tb&&(this.zl&&!this.Th)&&this.sb.aF[0].Ma(this.vg,this.zl)};D.x.Iq=function(){(0,D.cf)()||this.vg.$b("label",this.fc())};
D.UU=(0,D.t)();D.z.l(D.UU,D.z,"DvtTimelineSeriesParser");D.x=D.UU.prototype;D.x.parse=function(a,b){var c=[],d=a.items;if(d)for(var e=0;e<d.length;e++)c.push(d[e]);this.Xf=new window.Date(a.start);this.Sh=new window.Date(a.end);d=this.DE();d.Asa=a.style;d.scale=a.scale;d.dOa=a.timeAxis;d.label=a.label;d.hIa=a.emptyText;d.mMa="auto"==a.animationOnDisplay;d.eMa="auto"==a.animationOnDataChange;d.Ul=this.X8(a.timeline,a.index,c,b);d.vRa="false";return d};
D.x.DE=function(){var a={};a.pta=this.Xf;a.ota=this.Sh;a.orientation="horizontal";a.start=this.Xf.getTime();a.end=this.Sh.getTime();return a};
D.x.X8=function(a,b,c,d){var e=[],f=a.sb[b];if(c)for(var g=0;g<c.length;g++){var h=this.W2(c[g]);if(h){if(f.gO){var j;a:{j=h;var l=d;if(l)for(var m=0;m<l.length;m++){var n=l[m];if(j.id==n.getId()&&j.title==n.Yv()&&j.KZ==n.JJ&&j.Wta==n.hpa){j=n;break a}}j=D.i}j?(l=D.H.wa(d,j),d.splice(l,1),j.Hq=D.o,j.nq=D.o,j.Zo=D.o,j.jb(D.p),j.Xf=h.startTime,j.Sh=h.nD):(j=new D.GU(a,b,h),j.Lf(D.k))}else j=new D.GU(a,b,h),j.Lf(D.k);h=j.Xf;l=D.k;for(m=0;m<e.length;m++)if(h<e[m].Xf){e.splice(m,0,j);l=D.p;break}l&&e.push(j)}}return e};
D.x.getDate=function(a){return a==D.o?D.o:a.getTime?a.getTime():(0,window.isNaN)(a)?(new window.Date(a)).getTime()+0:a};D.x.W2=function(a){var b={};b.id=a.id;b.bda=b.id;b.startTime=this.getDate(a.start);b.nD=this.getDate(a.end);if((b.nD?b.nD:b.startTime)<this.Xf.getTime()||b.startTime>this.Sh.getTime())return D.o;b.title=a.title;b.KZ=a.description;b.Wta=a.thumbnail;b.data=a;b.style=a.style;b.action=a.action;b.OZ=a.durationFillColor;return b};
D.xU={};D.z.l(D.xU,D.z,"DvtTimelineSeriesRenderer");
D.xU.wNa=function(a,b,c){D.xU.Gt(a,b,c);D.xU.v9(a);D.xU.KFa(a,a.qh);D.xU.w9(a);if(!(a.Za==D.o||0==a.Za.length)){if(0==a.aF.length){c=a.j();b=new D.D(c,"itemBlock_"+a.Mr+"_"+a.Vo);b.Tta=a.Mr;b.yqa=a.Vo;var d=new D.D(c,"feelers");b.k(d);b.qaa=d;c=new D.D(c,"durations");b.k(c);b.xqa=c;a.qh.k(b);a.aF.push(b)}else b=a.aF[0];a.F0(a.Za);c=a.Za;a.IP=a.Sa()?20*(0<a.Rz?1:0)+D.$.ZL()+10*a.Rz:20+D.$.ZL()+10*a.Rz;a.Yo=[];for(d=0;d<c.length;d++){var e=c[d],f=D.bP.fe(a.ob,a.Xb,e.Xf,a.Ng),g=e.Sh;g&&g!=e.Xf&&(g=D.bP.fe(a.ob,
a.Xb,g,a.Ng)-f,f+=window.Math.min(D.$.$qa(),g/2));e.Zo=f;for(var g=D.k,h=0;h<a.Yo.length;h++)if(f<a.Yo[h].Zo){a.Yo.splice(h,0,e);g=D.p;break}g&&a.Yo.push(e)}for(d=0;d<a.Yo.length;d++)e=a.Yo[d],f=D.bP.fe(a.ob,a.Xb,e.Xf,a.Ng),f<a.Mr||f>a.Vo||D.YU.aMa(e,a);a.lDa?(a.Fz=a.kDa?[]:D.o,a.Wz=D.o,a.bD=D.o):a.gO&&a.iDa?(a.Fz=[],a.Wz=new D.lr(a.j(),D.$.xa(a.D),0,D.nD),a.bD=[]):(a.Fz=D.o,a.Wz=D.o,a.bD=D.o);a.fla=D.p;c=window.Math.max(0,a.Oi-a.no);a.EQ=c;D.xU.Xha(a,c);a.nQ&&D.xU.ZEa(a.nQ,a,b,a.bD);a.nQ=D.o;a.Sa()&&
b.qaa.Cj();D.xU.n9(a.Za,a,b,a.Mr,a.Vo,c,a.Fz,a.Wz);D.xU.Dpa(a);D.xU.Epa(a)}};D.xU.hOa=function(a){D.xU.GGa(a.Za,a);D.xU.Dpa(a);D.xU.Epa(a)};D.xU.Gt=function(a,b,c){if(a.Na){var d=D.p;a.Na.ma(b);a.Na.Ea(c)}else d=D.k,a.Na=new D.Te(a.j(),0,0,b,c,"bg");a.Na.Ha(a.gp);(0,D.Ei)(a.Na);a.Na.setCursor("move");d&&a.k(a.Na)};
D.xU.Xha=function(a,b){var c=(0,D.E)(a.j());0<b&&(a.Sa()?a.Na.ma(a.Oi):a.Na.Ea(a.Oi));if(a.Sa()){if(!a.ok&&!c||a.ok&&c)a.Na.I(-b),a.qh!=D.o&&a.qh.I(0-b)}else a.ok||(a.Na.O(-b),a.qh!=D.o&&a.qh.O(0-b))};D.xU.v9=function(a){a.qh?(a.MV=a.qh.N(),a.dF=a.qh.M(),a.qh.I(0),a.qh.O(0)):(a.qh=new D.D(a.j(),"canvas"),a.k(a.qh))};
D.xU.n9=function(a,b,c,d,e,f,g,h){for(var j=0;j<b.Yo.length;j++){var l=b.Yo[j],m=D.bP.fe(b.ob,b.Xb,l.Xf,b.Ng);m<d||m>e||D.YU.vNa(l,b,c,f,g,h)}if(D.bP.am())for(j=0;j<b.Yo.length-1;j++)l=b.Yo[j],(0,D.HE)(l.vg,"flowto","_bt_"+b.Yo[j+1].getId());D.xU.oFa(a,b,c,f,g,h)};
D.xU.GGa=function(a,b){if(!(a==D.o||0==a.length)){var c=b.Vo,d=b.aF[0];d.Tta=b.Mr;d.yqa=c;b.F0(a);b.IP=b.Sa()?20*(0<b.Rz?1:0)+D.$.ZL()+10*b.Rz:20+D.$.ZL()+10*b.Rz;for(c=0;c<a.length;c++){var d=a[c],e=d.Xf,f=D.bP.fe(b.ob,b.Xb,e,b.Ng),g=d.Sh;g&&g!=e&&(e=D.bP.fe(b.ob,b.Xb,g,b.Ng)-f,f+=window.Math.min(D.$.$qa(),e/2));d.Zo=f;d.Hq=D.o}for(c=0;c<a.length;c++)d=a[c],f=d.Xf,f<b.ob||f>b.Xb||D.YU.zpa(d,b);f=window.Math.max(0,b.Oi-b.no);D.xU.Xha(b,f);for(c=0;c<a.length;c++)d=a[c],D.YU.Q5(d,b,f,D.o),D.YU.Cpa(d,
b,f,D.o),D.YU.Wx(d,b,f,D.o)}};D.xU.oFa=function(a,b,c,d,e,f){c=c.xqa;for(var g=b.Rz;0<g;g--)for(var h=0;h<a.length;h++){var j=a[h],l=j.Xf,m=j.Sh;m&&(m!=l&&g==j.nq)&&D.YU.rNa(j,b,c,d,e,f)}};D.xU.w9=function(a){a.JY==D.o?(a.JY=new D.D(a.j()),a.qh.k(a.JY)):(a.JY.Cj(),a.KY=[]);if(a.Yd&&a.Yf){var b=new D.G(D.$.CKa());if(a.fz){var c=a.fz.separatorColor;c&&(0,D.Uf)(b,"color:"+c+";")}a.kL=new D.hg(b.A("color"));a.kL.W(1,3);D.xU.x9(a,a.Mr,a.Vo,a.JY)}};
D.xU.Epa=function(a){for(var b=(0,D.E)(a.j()),c=0;c<a.KY.length;c++){var d=a.KY[c],e=!a.Sa()&&b?a.Ng-D.bP.fe(a.ob,a.Xb,d.time,a.Ng):D.bP.fe(a.ob,a.Xb,d.time,a.Ng);a.Sa()?(d.nl(0),d.ol(e),d.Zl(a.Oi),d.$l(e)):(d.nl(e),d.ol(0),d.Zl(e),d.$l(a.Oi))}};
D.xU.x9=function(a,b,c,d){var e=(0,D.E)(a.j()),f=a.ob,g=a.Xb;b=D.bP.rg(f,g,b,a.Ng);b=a.Yf.OL(b);for(var h=D.bP.fe(f,g,b,a.Ng);h<c;){var j=a.Yf.lM(b.getTime()),l=D.bP.fe(f,g,j,a.Ng),m=!a.Sa()&&e?a.Ng-h:h;if(a.Sa())var n=0,q=m,r=a.Oi;else n=m,q=0,r=m,m=a.Oi;h=a.NL(d,n,r,q,m,a.kL,"o_tick"+h);h.time=b.getTime();a.KY.push(h);b=j;h=l}};
D.xU.KFa=function(a,b){var c=a.j(),d=(0,D.E)(c);a.lY==D.o&&(a.lY=new D.D(c),b.k(a.lY));var e=a.yG;if(e)for(var f=window.Math.min(1,e.length),g=0;g<f;g++){var h=e[g];if(h){var j=D.bP.fe(a.ob,a.Xb,h,a.Ng);if(0==a.TQ.length){a.Sa()?j=new D.Di(c,0,j,a.Oi,j,"zoomOrder[i]"):(d&&(j=a.Ng-j),j=new D.Di(c,j,0,j,a.Oi,"zoomOrder[i]"));var l=new D.hg(D.$.Sra(a.D));j.V(l);(0,D.Ei)(j);j.SHa=h;a.lY.k(j);a.TQ[g]=j}}}else a.lY.Cj(),a.TQ=[]};
D.xU.Dpa=function(a){for(var b=(0,D.E)(a.j()),c=0;c<a.TQ.length;c++){var d=a.TQ[c],e=D.bP.fe(a.ob,a.Xb,d.SHa,a.Ng);a.Sa()?(d.nl(0),d.ol(e),d.Zl(a.Oi),d.$l(e)):(b&&(e=a.Ng-e),d.nl(e),d.ol(0),d.Zl(e),d.$l(a.Oi))}};D.xU.ZEa=function(a,b,c,d){if(d)D.xU.Kza(a,b,d);else for(d=0;d<a.length;d++){var e=a[d];c.removeChild(e.vg);b.Sa()||c.qaa.removeChild(e.VJ);var f=e.Xf,g=e.Sh;g&&g!=f&&c.xqa.removeChild(e.NJ)}};
D.xU.Kza=function(a,b,c){for(var d=0;d<a.length;d++){var e=a[d],f=e.vg;b.Sa()?f.I(f.N()+b.MV+b.EQ):f.O(f.M()+b.dF+b.EQ);c.push(f);b.Sa()||(f=e.VJ,f.O(f.M()+b.dF+b.EQ),c.push(f));var f=e.Xf,g=e.Sh;g&&g!=f&&(e=e.NJ,b.Sa()?e.I(e.N()+b.MV+b.EQ):e.O(e.M()+b.dF+b.EQ),c.push(e))}};
D.vU=function(a,b,c,d){D.vU.o.Init.call(this,a);this.KGa=b;this.JGa=c;this.RDa=d};(0,D.da)("DvtTimelineViewportChangeEvent",D.vU);D.z.l(D.vU,D.Li,"DvtTimelineViewportChangeEvent");D.vU.TYPE="viewportChange";D.vU.prototype.dLa=(0,D.v)("KGa");D.vU.prototype.getViewportStart=D.vU.prototype.dLa;D.vU.prototype.bLa=(0,D.v)("JGa");D.vU.prototype.getViewportEnd=D.vU.prototype.bLa;D.vU.prototype.VJa=(0,D.v)("RDa");D.vU.prototype.getMinorAxisScale=D.vU.prototype.VJa;

  return D;
});