/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.nS=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtTagCloud",D.nS);D.z.l(D.nS,D.sj,"DvtTagCloud");D.nS.newInstance=function(a,b,c){return new D.nS(a,b,c)};D.nS.prototype.Init=function(a,b,c){D.nS.o.Init.call(this,a,b,c);this.j().Kc.sa().setAttributeNS(D.o,"text-rendering","geometricPrecision");this.Ia=new D.oS(this,a,this.Pd,this);this.Ia.me(this);(0,D.Jf)()||(0,D.xj)(this.Ia,new D.pS(this.Ia));this.rf=new D.qS;this.Za=[];this.Cq=[];this.Gg=D.o;this.Hd=new D.ou(this.j());(0,D.Oq)(this.Ia,this.Hd)};
D.nS.prototype.P=function(a,b,c){!(0,window.isNaN)(b)&&!(0,window.isNaN)(c)&&(this.Ga=b,this.Ta=c);this.dO();this.vd(a);this.Ua&&this.Ua.stop();this.Og=this.X;this.nQ=this.Za;this.Za=[];this.Ila=[];this.X=new D.D(this.j());this.k(this.X);D.rS.P(this,this.X,new D.A(0,0,this.Ga,this.Ta));this.Ym&&(0,D.Il)(this.Ym,this.D.selection,this.Uq());b=this.D.animationDuration;c=new D.A(0,0,this.Ga,this.Ta);this.Og?"none"!==this.D.animationOnDataChange&&a&&(this.mf=new D.D(this.j()),this.k(this.mf),a=new D.Sm(this.j(),
this.mf),(0,D.Tm)(a,this.nQ,this.Za),this.Ua=a.Oq()):"none"!==this.D.animationOnDisplay&&(this.Ua=D.dl.by(this.j(),D.dl.uw,this.X,c,b));this.Ua?(this.Ia.Cc(),this.Ia.gi(this),this.Ua.ie(this.dga,this),this.Ua.play()):this.dga();this.Sn()};D.nS.prototype.render=D.nS.prototype.P;D.nS.prototype.Uca=(0,D.ba)("Za");D.nS.prototype.Gf=function(){this.Kk||(this.Kk=new D.sS(this));return this.Kk};D.nS.prototype.getAutomation=D.nS.prototype.Gf;D.nS.prototype.ZD=function(a,b){this.Cq.push(a);this.Ila[b]=a};
D.nS.prototype.Uq=(0,D.v)("Cq");D.nS.prototype.Bh=(0,D.v)("Ila");D.nS.prototype.Ge=function(a){this.D.highlightedCategories=D.pl.Y(a);(0,D.ql)(a,this.Uq(),"any"===this.D.highlightMatch);this.Gg&&this.Gg.Ge(a)};D.nS.prototype.highlight=D.nS.prototype.Ge;D.nS.prototype.select=function(a){this.D.selection=D.pl.Y(a);this.Ym&&(0,D.Il)(this.Ym,this.D.selection,this.Uq())};D.nS.prototype.select=D.nS.prototype.select;D.x=D.nS.prototype;
D.x.vd=function(a){a?this.D=this.rf.Vj(a):this.D||(this.D=(0,D.zj)(this));a=this.D.selectionMode;this.Ym="single"===a?new D.$k("s"):"multiple"===a?new D.$k("m"):D.o;this.Ia.yu(this.Ym);(0,D.Zk)()||(this.D.animationOnDisplay="none",this.D.animationOnDataChange="none")};D.x.Hj=function(){return(0,D.nk)(this.q(),"componentName","DvtUtilBundle","TAG_CLOUD")};
D.x.dga=function(){this.Og&&(this.removeChild(this.Og),this.Og.Q(),this.Og=D.o);this.mf&&(this.removeChild(this.mf),this.mf.Q(),this.mf=D.o);this.Ua&&(this.Ua=D.o,this.Ia.me(this));this.D.highlightedCategories&&0<this.D.highlightedCategories.length&&this.Ge(this.D.highlightedCategories)};D.x.dO=function(){this.Ia.Cc();this.Cq.length=0};D.x.ka=(0,D.v)("Ia");
D.x.Pd=function(a,b){var c=a.Pa();if(c==D.wl.Kw||c==D.wl.Sy){var d=a.Pk,e=D.H.wa(this.D.hiddenCategories,d);c==D.wl.Kw&&0>e&&this.D.hiddenCategories.push(d);c==D.wl.Sy&&0<=e&&this.D.hiddenCategories.splice(e,1);this.P(this.D,this.Ga,this.Ta)}else if("categoryRollOver"==c||"categoryRollOut"==c)this!=b?this.Ge(a.categories):this.Gg&&this.Gg!=b&&this.Gg.Pd(a,b);a&&this.dispatchEvent(a)};D.x.Zt=function(){for(var a=[],b=this.Ym.getSelection(),c=0;c<b.length;c++)a=a.concat(b[c].Yc());return a};
D.nS.prototype.zj=function(a,b,c){return this.Hd.zj(c)};D.nS.prototype.isDragAvailable=D.nS.prototype.zj;D.nS.prototype.yk=function(a,b){return this.Hd.yk(a,b)};D.nS.prototype.getDragTransferable=D.nS.prototype.yk;D.nS.prototype.$t=function(a,b){return this.Hd.$t(a,b)};D.nS.prototype.getDragOverFeedback=D.nS.prototype.$t;D.nS.prototype.xp=function(a,b){return this.Hd.xp(a,b)};D.nS.prototype.getDragContext=D.nS.prototype.xp;D.nS.prototype.Ov=function(a,b){return this.Hd.Ov(a,b)};
D.nS.prototype.getDragOffset=D.nS.prototype.Ov;D.nS.prototype.Vv=function(a,b){return this.Hd.Vv(a,b)};D.nS.prototype.getPointerOffset=D.nS.prototype.Vv;D.nS.prototype.$v=function(){this.Hd.$v()};D.nS.prototype.initiateDrag=D.nS.prototype.$v;D.nS.prototype.es=function(){this.Hd.es()};D.nS.prototype.dragDropEnd=D.nS.prototype.es;
D.nS.prototype.ro=function(a,b,c){this.wl||(this.wl=new D.vS);return this.wl.ro(a,b,c)};D.nS.prototype.acceptDrag=D.nS.prototype.ro;
D.sS=(0,D.ba)("Rx");(0,D.da)("DvtTagCloudAutomation",D.sS);D.z.l(D.sS,D.Dj,"DvtTagCloudAutomation");D.sS.prototype.ql=function(a){return(a=(0,D.Ej)(this.Rx.Ia,a))&&a instanceof D.tS?"item["+this.Rx.Bh().indexOf(a)+"]":D.o};D.sS.prototype.If=function(a){if("tooltip"==a)return(0,D.bm)(this.Rx);var b=a.indexOf("[");return 0<b&&"item"===a.substring(0,b)&&(a=(0,window.parseInt)(a.substring(b+1,a.length-1)),a=this.Rx.Bh()[a])?a.Yc()[0].sa():D.o};D.sS.prototype.getDomElementForSubId=D.sS.prototype.If;
D.sS.prototype.getItem=function(a){if(a=this.Rx.Bh()[a]){var b={};b.color=a.vi();b.tooltip=a.Bc();b.label=a.Nc();b.value=a.getValue();b.selected=a.Da();return b}return D.o};D.sS.prototype.getItem=D.sS.prototype.getItem;D.sS.prototype.bM=function(){return this.Rx.Uq().length};D.sS.prototype.getItemCount=D.sS.prototype.bM;
D.xS=function(a,b,c,d,e,f,g){this.Init(a,b,c,d,e,f,g)};D.z.l(D.xS,D.Zj,"DvtTagCloudItem");D.x=D.xS.prototype;D.x.Init=function(a,b,c,d,e,f,g){D.xS.o.Init.call(this,b,c,d,e,f,g);this.Rx=a;this.xZ();f&&(0,D.yS)(this,f)};D.x.jb=function(a){this.Th!=a&&((this.Th=a)?this.Al?this.Ha(this.YW):this.Ha(this.GY):this.Ha(this.cG))};D.x.Ob=function(){this.Al||(this.Al=D.k,this.Th?this.Ha(this.YW):this.Ha(this.Z6))};D.x.Db=function(){this.Th?this.Ha(this.GY):this.Ha(this.cG);this.Al=D.p};
D.x.gf=function(a,b){var c=new D.qn(this.j(),this,D.zS.xa(this.Rx)),d=this.gc(),e=b.gc(),f=D.p,g=e.A("color"),h=d.A("color");if(g!=h){var j=this;this.Ha(d.W("color",g));(0,D.T)(c.J,"typeColor",this,function(){return j.gc().A("color")},function(a){j.Ha(j.gc().W("color",a))},h)}e=(0,window.parseFloat)(e.A("font-size"));d=(0,window.parseFloat)(d.A("font-size"));e!=d&&(f=D.k,j=this,this.Ie(e),(0,D.T)(c.J,"typeNumber",this,function(){return(0,window.parseFloat)(j.gc().A("font-size"))},this.Ie,d));g=b.ja();
d=this.ja();e=b.zn();h=this.zn();if(d!=g||f&&h!=e)h!=e&&(f=g,g=b.Xd.F(D.i),g="left"==e?f+g.e:"right"==e?f-g.e:f),this.ca(g),(0,D.T)(c.J,"typeNumber",this,this.ja,this.ca,d);f=b.na();d=this.na();d!=f&&(this.va(f),(0,D.T)(c.J,"typeNumber",this,this.na,this.va,d));b.B(0);a.add(c,1)};D.x.kh=function(a){a.add(new D.sn(this.j(),this,D.zS.xa(this.Rx)),0)};D.x.qg=function(a){this.B(0);a.add(new D.Vm(this.j(),this,D.zS.xa(this.Rx)),2)};D.x.Ie=function(a){D.xS.o.Ie.call(this,a);(0,D.yS)(this,this.gc())};
D.yS=function(a,b){a.cG=b.Y();var c=a.cG.A("color");a.cG.W("background-color",D.o);a.Z6=a.cG.Y();var d=(0,D.AS)(c,0.3);a.Z6.W("background-color",d);a.Z6.W("color",D.I.tj(d));a.GY=a.cG.Y();a.GY.W("background-color",c);a.GY.W("color",D.I.tj(c));a.YW=a.cG.Y();c=(0,D.AS)(c,0.6);a.YW.W("background-color",c);a.YW.W("color",D.I.tj(c))};D.AS=function(a,b){var c=D.I.te(a),d=D.I.pe(a),e=D.I.oe(a);return D.I.$A(window.Math.floor(255*(1-b)+b*c),window.Math.floor(255*(1-b)+b*d),window.Math.floor(255*(1-b)+b*e))};
D.tS=function(a,b,c){this.Init(a,b,c)};D.z.l(D.tS,D.z,"DvtTagCloudObjPeer");D.x=D.tS.prototype;D.x.Init=function(a,b,c){this.H=a;this.vg=b;this.oa=c;this.YE=this.Th=D.p;c.url?(b.Ud("link"),this.U7=D.B.yD("_blank",c.url)):b.Ud("img");this.Iq()};D.x.getId=function(){return this.oa.id};D.x.Nc=function(){return this.oa.label};D.x.getValue=function(){return this.oa.value};D.x.Bc=function(){return this.oa.shortDesc};D.x.Ce=function(){return this.oa.action};
D.x.De=function(){var a=this.H.q().tooltip;return a?(0,D.ip)(this.H.j().ge(),a,this.vp()):this.Bc()};D.x.vp=function(){return{id:this.getId(),label:this.Nc(),color:this.vi(),value:this.getValue()}};D.x.yD=(0,D.v)("U7");D.x.vi=function(){this.bo||(this.bo=(new D.G(this.oa.style)).A("color"));return this.bo};D.x.Lf=(0,D.ba)("YE");D.x.Aa=(0,D.v)("YE");D.x.Da=(0,D.v)("Th");D.x.jb=function(a){this.Th=a;this.vg.jb(a);this.Iq()};D.x.Ob=function(){this.vg.Ob()};D.x.Db=function(){this.vg.Db()};
D.x.Ad=function(a){var b=this.H.Ia.Sf;a.type==D.kk||b.ar(a)?b=this:b.tg(a)?(b=this.H.Uq(),a=39==a.keyCode||40==a.keyCode?D.k:D.p,a=D.H.wa(b,this)+(a?1:-1),b=a<b.length&&0<=a?b[a]:D.o):b=D.o;return b};D.x.Ee=function(a){return this.vg.F(a)};D.x.yj=function(){return this.vg.sa()};D.x.Vd=function(){this.Ib=D.k;this.Ob()};D.x.jc=function(){this.Ib&&(this.Ib=D.p,this.Db())};D.x.pc=(0,D.v)("Ib");D.x.Yc=function(){return[this.vg]};
D.x.fc=function(){var a=[];this.Aa()&&a.push((0,D.L)("DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.ok)(this.Bc(),a)};D.x.Mc=function(){return this.oa.categories};D.x.Iq=function(){(0,D.cf)()||this.vg.$b("label",this.fc())};D.x.rd=function(){if(!this.pd&&(this.pd=[],this.oa.showPopupBehaviors))for(var a=this.oa.showPopupBehaviors,b=0;b<a.length;b++)this.pd.push(new D.Gi(a[b].popupId,a[b].triggerType,a[b].alignId,a[b].align));return this.pd};
D.x.zj=function(a){return this.H.Ym?a[0]:D.o};D.x.yk=function(){var a=this.H;this.Da()||(a.Ym.Nm(this,D.p),a.Ia.Nv());for(var b=[],a=a.Ym.getSelection(),c=0;c<a.length;c++){var d=a[c];d instanceof D.tS&&b.push(d.getId())}return b};D.x.Zt=function(){return this.H.Zt()};
D.qS=function(){this.Init({alta:D.uS})};D.z.l(D.qS,D.Nj,"DvtTagCloudDefaults");
D.uS={animationOnDisplay:"none",animationOnDataChange:"none",emptyText:D.o,hiddenCategories:[],hideAndShowBehavior:"none",highlightedCategories:[],highlightMatch:"all",hoverBehavior:"none",layout:"rectangular",selectionMode:"none",_statusMessageStyle:new D.G('font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #333333;'),styleDefaults:{animationDuration:500,hoverBehaviorDelay:200,style:new D.G('font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; color: #333333;')},touchResponse:"auto"};
D.rS={};D.z.l(D.rS,D.z,"DvtTagCloudRenderer");D.rS.P=function(a,b,c){D.rS.Gt(a,b,c);D.rS.aD(a,b,c);D.rS.Sw(c);var d=a.q();d.items&&0<d.items.length?(d=D.rS.n9(a,b,c),0<d.length?(a.Uca(d),(0,D.Bj)(a.Ia,a.Uq()[0])):D.rS.QQ(a,b,c)):D.rS.QQ(a,b,c)};D.rS.QQ=function(a,b,c){var d=a.q(),e=d.emptyText;e||(e=(0,D.nk)(d,"labelNoData","DvtUtilBundle","NO_DATA",D.o));D.$e.Om(b,e,new D.A(c.x,c.y,c.e,c.g),a.Ia,d._statusMessageStyle)};D.rS.Gt=function(a,b,c){a=new D.Te(a.j(),c.x,c.y,c.e,c.g);(0,D.wi)(a);b.k(a)};
D.rS.n9=function(a,b,c){for(var d=a.q(),e=[],f=d.items,g=window.Number.MAX_VALUE,h=-window.Number.MAX_VALUE,j=0;j<f.length;j++)g=window.Math.min(g,f[j].value),h=window.Math.max(h,f[j].value);g=D.BS.pJa(g,h);h=D.H.ZG(d.hiddenCategories);for(j=0;j<f.length;j++){var l=f[j];l.categories||(l.categories=[l.label]);if(!h||!D.H.yM(h,l.categories)){var m=d.styleDefaults.style.Y();(0,D.Uf)(m,l.style);m.W("font-size",g.call(D.o,l.value).toString());var m=new D.xS(a,a.j(),l.label,0,0,m,l.id),n=new D.tS(a,m,l);
a.Ia.Ca(m,n);a.ZD(n,j);"none"!==d.selectionMode&&n.Lf(D.k);(n.Aa()||l.url||n.Ce())&&m.setCursor("pointer");e.push(m);b.k(m)}}0<e.length&&("cloud"===d.layout?D.BS.tHa(c,e):D.BS.nNa(c,e,(0,D.E)(a.j())));return e};
D.rS.aD=function(a,b,c){var d=a.q(),e=d.legend;if(e&&e.sections){e=D.pl.Y(e);e.orientation="horizontal";e.halign="center";e.hoverBehavior=d.hoverBehavior;e.hideAndShowBehavior=d.hideAndShowBehavior;e.hiddenCategories=d.hiddenCategories;d=(0,D.Cn)(a.j(),a.Pd,a);b.k(d);var f=d.Dp(e,c.e,c.g/3);d.P(e,f.e,f.g);(0,D.An)(c,"bottom",d,f.e,f.g,0);a.Gg&&(a.Gg.Q(),b.removeChild(a.Gg));a.Gg=d}};D.rS.Sw=function(a){a.x=window.Math.round(a.x);a.y=window.Math.round(a.y);a.e=window.Math.round(a.e);a.g=window.Math.round(a.g)};
D.BS=(0,D.t)();D.z.l(D.BS,D.z,"DvtTagCloudLayoutUtils");D.BS.pJa=function(a,b){return function(c){return 12+window.Math.ceil(12*(2*(c-a)/(b-a)))}};
D.BS.tHa=function(a,b){var c=[],d=10/180,e=10/180;a.e>a.g?d*=a.e/a.g:e*=a.g/a.e;for(var f=2*window.Math.PI/180,g=D.o,h=0,j=[],l=[],m=0;m<b.length;m++)for(var n=D.p,q=0,r=4,s=b[m],u=s.F(),h=window.Math.max(h,(0,window.parseFloat)(s.gc().A("font-size"))),w=-1;!n;){var y=q%180;j[y]===D.i&&(j[y]=window.Math.cos(q*f));l[y]===D.i&&(l[y]=window.Math.sin(q*f));var C=d*q*j[y],O=e*q*l[y],M=new D.A(C,O,u.e,u.g),n=D.k;-1!=w&&c[w].V_(M)&&(n=D.p);if(n)for(y=0;y<m;y++)if(c[y].V_(M)){w=y;n=D.p;break}n&&(g=g?(0,D.Bo)(g,
M):M,w=-1,c[m]=M,s.ca(C),s.va(-u.y+O));3600===q?r=3:5400===q?r=2:10800===q&&(r=1);q+=r}c=window.Math.max(g.e/a.e,g.g/a.g);d=g.x+g.e/2;g=g.y+g.g/2;for(y=0;y<b.length;y++)s=b[y],s.ca(a.x+s.ja()/c+(a.e/2-d/c)),s.va(a.y+s.na()/c+(a.g/2-g/c)),e=(0,window.parseFloat)(s.gc().A("font-size")),s.Ie(e/c)};
D.BS.nNa=function(a,b,c){for(var d=[],e=0,f=0,g=0,h=0;h<b.length;h++){var j=b[h],l=j.F(),e=window.Math.max(e,l.e),f=window.Math.max(f,l.g),g=window.Math.max(g,(0,window.parseFloat)(j.gc().A("font-size")));d.push(new D.Cg(l.e,l.g))}h=0;for(j=(a.e-10)/e;0.001<j-h;)e=(h+j)/2,g=D.BS.Pia(d,(a.e-10)/e),g.length*(e*f+2)-2>a.g-10?j=e:h=e;e=h;g=D.BS.Pia(d,(a.e-10)/e);g.push(b.length);for(h=0;h<g.length-1;h++){var l=g[h],m=g[h+1],n=0,q=0,r=D.k;if(1<m-l){for(var j=0,s=l;s<m;s++)j+=d[s].e*e,q=window.Math.max(q,
d[s].g*e);n=(a.e-10-j)/(m-l-1);h==g.length-2&&(s=0.5*q,s<n&&j+(m-l)*s<0.9*(a.e-10)&&(n=s,r=D.p))}for(var q=5+(h+1)*(f*e+2)-2,u=c?a.e-5:5,s=l;s<m;s++){var j=b[s],w=(0,window.parseFloat)(j.gc().A("font-size"));j.Ie(w*e);j.va(a.y+q);r&&s==m-1&&s!=l?c?(j.yh(),j.ca(a.x+5)):(j.zh(),j.ca(a.x+a.e-5)):(j.ca(a.x+u),c?(j.zh(),u-=d[s].e*e+n):(j.yh(),u+=d[s].e*e+n))}}};D.BS.Pia=function(a,b){var c=[0],d=a[0].e+2;if(1<a.length)for(var e=1;e<a.length;e++)d+a[e].e>b&&(c.push(e),d=0),d+=a[e].e+2;return c};
D.zS={};D.z.l(D.zS,D.z,"DvtTagCloudStyleUtils");D.zS.xa=function(a){return a.q().styleDefaults.animationDuration/1E3};
D.oS=function(a,b,c,d){this.Init(b,c,d);this.H=a};D.z.l(D.oS,D.Pj,"DvtTagCloudEventManager");D.oS.prototype.II=function(a){a=(0,D.Ej)(this,a.target);(0,D.wS)(a);this.wG(a)};D.oS.prototype.EN=function(a){a=(0,D.Ej)(this,a.target);this.wG(a)};D.oS.prototype.qr=function(a){a=(0,D.Ej)(this,a.target);(0,D.wS)(a);this.wG(a)};D.wS=function(a){a instanceof D.tS&&(a=a.yD())&&a.call()};D.oS.prototype.Kh=function(a){var b=D.k,c=this.dd();13==a.keyCode?(0,D.wS)(c):b=D.oS.o.Kh.call(this,a);return b};
D.oS.prototype.fm=function(a,b,c){a=this.H.q();"dim"==a.hoverBehavior&&(b=b.Mc?b.Mc():[],a.highlightedCategories=c?b.slice():D.o,c=new D.zm(c?"categoryRollOver":"categoryRollOut",a.highlightedCategories),b=(0,D.hp)(a.styleDefaults.hoverBehaviorDelay),this.GB.Pd(c,this.H.Uq(),b,"any"==a.highlightMatch))};D.oS.prototype.wG=function(a){a&&(a.Ce&&a.Ce())&&this.Xg(new D.Sj("action",a.Ce(),a.getId()))};D.oS.prototype.Bu=function(){return this.H.q().touchResponse};
D.pS=function(a){this.Init(a)};D.z.l(D.pS,D.jk,"DvtTagCloudKeyboardHandler");D.pS.prototype.Init=function(a){D.pS.o.Init.call(this,a)};D.pS.prototype.qy=function(a){return this.tg(a)&&!a.ctrlKey};D.pS.prototype.ar=function(a){return 32==a.keyCode&&a.ctrlKey};
D.vS=(0,D.t)();D.z.l(D.vS,D.qu,"DvtTagCloudDropTarget");D.vS.prototype.ro=function(a,b,c){return c[0]};

  return D;
});