/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtPanZoomCanvas'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.CS=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtAmxThematicMap",D.CS);D.z.l(D.CS,D.D,"DvtAmxThematicMap");D.CS.NB=10;D.CS.prototype.Init=function(a,b,c){D.CS.o.Init.call(this,a);this.aa=new D.DS(a,b,c);this.fZ=new D.D(a);this.fZ.k(this.aa);this.k(this.fZ);this.rf=new D.ES};D.CS.newInstance=function(a,b,c){return new D.CS(a,b,c)};D.CS.newInstance=D.CS.newInstance;D.CS.prototype.P=function(a,b,c){this.D=this.rf.Vj(a);this.Ba=b;this.Fa=c;b=new D.A(0,0,b,c);this.aD(this,b);this.aa.P(a,b.e,b.g)};
D.CS.prototype.render=D.CS.prototype.P;
D.CS.prototype.aD=function(a,b){this.wb&&(a.removeChild(this.wb),this.wb=D.o);var c=new D.A(D.CS.NB,D.CS.NB,b.e-2*D.CS.NB,b.g-2*D.CS.NB),d=this.D,e=d.legend.rendered,f=d.legend.scrolling,g=D.pl.Y(d.legend);this.c4(this.D,g);if(e&&!(g.FNa&&0==g.FNa.length)){e=d.legend.position;delete g.position;g.layout.gapRatio=(0,D.FS)(this);g.hideAndShowBehavior="none";g.rolloverBehavior="none";g.scrolling=d.legend.scrolling;var h=(0,D.Cn)(this.aa.j());a.k(h);"auto"==e&&"asNeeded"!==f?e="bottom":"auto"==e&&"asNeeded"==
f&&(e="end");f=(0,D.E)(a.j());"start"==e?e=f?"right":"left":"end"==e&&(e=f?"left":"right");g.orientation="left"==e||"right"==e?"vertical":"horizontal";f="top"==e||"bottom"==e;f=h.Dp(g,f?c.e:d.layout.legendMaxSize*c.e,f?d.layout.legendMaxSize*c.g:c.g);if(0<f.e&&0<f.g)switch(h.P(g,f.e,f.g),this.wb=h,d=window.Math.ceil(d.layout.legendGap*(0,D.FS)(this)),(0,D.An)(c,e,h,f.e,f.g,d),e){case "top":this.fZ.O(f.g+D.CS.NB);case "bottom":b.g-=f.g+D.CS.NB;break;case "left":this.fZ.I(f.e+D.CS.NB);case "right":b.e-=
f.e+D.CS.NB}}};D.FS=function(a){if(a.D.layout.gapRatio!==D.o&&!(0,window.isNaN)(a.D.layout.gapRatio))return a.D.layout.gapRatio;var b=window.Math.min(a.Ba/400,1);a=window.Math.min(a.Fa/300,1);return window.Math.min(b,a)};D.CS.prototype.c4=function(a,b){b.title=a.legend?a.legend.title:D.o;b.sections=[];if(a&&a.legend&&a.legend.sections)for(var c=0;c<a.legend.sections.length;c++){var d=a.legend.sections[c];d&&b.sections.push({title:d.title,items:d.items,sections:d.sections})}return b};
D.DS=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtThematicMap",D.DS);D.z.l(D.DS,D.pp,"DvtThematicMap");
D.DS.prototype.Init=function(a,b,c){D.DS.o.Init.call(this,a,b,c);(0,D.nT)(this);this.Df=[];this.Az=[];this.BDa=this.xx=this.Vc=this.wb=D.o;this.s4=D.p;this.lP=[];this.HP={};this.jY=D.p;this.yW={};this.f5={};this.Uo=[];this.o4=new D.D(this.j());this.YO=new D.D(this.j());this.xz=new D.D(this.j());this.vx=new D.D(this.j());this.UK=this.UG=this.n7=D.p;this.EX=6;this.Nz=D.k;this.iL={};this.wV=D.p;this.pd=D.o;this.eo=16777215;this.rf=new D.ES;this.eb.Ca(this,this);this.ye=D.p};
D.DS.newInstance=function(a,b,c){return new D.DS(a,b,c)};D.DS.prototype.vd=function(a){D.DS.o.vd.call(this,a);(0,D.Zk)()||(this.D.animationOnDisplay="none",this.D.animationOnMapChange="none",this.D.animationOnDrill="none");(new D.oT(this)).parse(this.D)};D.DS.prototype.ka=(0,D.v)("eb");D.pT=function(a,b){for(var c=0;c<a.Df.length;c++)if(a.Df[c].Ih==b)return a.Df[c]};D.x=D.DS.prototype;D.x.ow=function(a){this.Zy=(0,window.parseFloat)(a)};D.x.xa=(0,D.v)("Zy");
D.x.Y0=function(a){a=(0,window.parseInt)(a);var b=this.eo;if(1==a||3==a||5==a||7==a)b&=-17,this.UK=D.p;if(2==a||3==a||6==a||7==a)b&=-4098,this.UG=D.p;if(4==a||5==a||6==a||7==a)b&=-257;this.eo=b};D.x.nda=function(a){this.hn=a;this.eb.nda(a)};
D.x.MI=function(){D.DS.o.MI.call(this);!this.uq&&this.TEa&&(this.Df=[],this.lP=[],this.HP={},this.yW={},this.f5={},this.Uo=[],this.removeChild(this.Vc),this.BDa=this.xx=this.wb=this.Vc=D.o,this.eo=16777215,this.UK=this.UG=D.k,this.MK=this.Jb,this.o4=new D.D(this.j()),this.YO=new D.D(this.j()),this.xz=new D.D(this.j()),this.vx=new D.D(this.j()),this.pd=D.o,this.eb.gi(this),(0,D.nT)(this),this.wV=D.p,this.eb.Cc(),this.eb.Ca(this,this))};
D.nT=function(a){a.eb=new D.qT(a.j(),a.dispatchEvent,a);a.eb.me(a);(0,D.Jf)()?a.GC=D.o:(a.GC=new D.rT(a,a.eb),(0,D.xj)(a.eb,a.GC))};D.x=D.DS.prototype;D.x.mva=function(a){(0,D.E)(this.j())||(a=this.getWidth()-5-a.getWidth(),this.Vc.I(a))};
D.x.aD=function(){if(this.xx){this.Vc&&(this.Vc.Q(),this.removeChild(this.Vc));var a="true"==this.xx.disclosed,b="fixed"==this.xx.display||(0,D.Fe)();if(!b||a){var c=this.xx.maxWidth,d=c.indexOf("%"),c=-1!=d?(0,window.parseFloat)(c.substring(0,d))/100*this.getWidth():(0,window.parseFloat)(c),d=this.getHeight()-10;"alta"==this.nc?(this.Vc=new D.ur(this.j(),D.o,this,"pd"),this.Vc.la("dvtPanelDrawerEvent",this.gfa,D.p,this),this.Vc.wu(c),this.Vc.rT(d),this.Vc.Mz=b,(0,D.E)(this.j())?(this.Vc.av="right",
this.Vc.I(0)):this.Vc.I(this.getWidth())):(this.Vc=new D.Ku(this.j(),c,d,"col_northeast",(0,D.xr)(this),this.ls(),a,b),this.Vc.la("dvtCollapsiblePanelEvent",this.gfa,D.p,this),this.Vc.la("dvtResizeEvent",this.mva,D.p,this),c=this.Vc,d=this.xx.collapseTooltip,c.rP=this.xx.expandTooltip,c.LO=d);c=this.xx;this.wb=(0,D.Cn)(this.j(),this.Oca,this);this.k(this.Vc);this.k(this.wb);d=this.wb.Dp(c,this.Vc.gS(),this.Vc.fM());this.wb.P(c,d.e,d.g);var e;if("alta"==this.nc){(0,D.wr)(this.Vc,this.wb.hs().g);this.removeChild(this.wb);
var c=new D.Ue(this.j(),(0,D.xr)(this).legendEna,0,0,24,24),d=new D.Ue(this.j(),(0,D.xr)(this).legendOvr,0,0,24,24),f=new D.Ue(this.j(),(0,D.xr)(this).legendDwn,0,0,24,24),g=(0,D.L)("DvtUtilBundle","LEGEND");(0,D.yr)(this.Vc,this.wb,c,d,f,g,"legend");this.Vc.ir();a&&this.Vc.yf(D.k,D.k)}else e=this.Vc,a=this.wb,e.zJ.k(a),a.la("dvtResizeEvent",e.t2,D.p,e),a=e.zJ.F(),e.Ba=window.Math.min(e.Uh,a.e+10),e.Fa=window.Math.min(e.Ni,a.g+10),e.Na?(e.Na.Dj((0,D.cQ)(e,e.Ba,e.Fa)),a="col_northwest"==e.Pj||"col_southwest"==
e.Pj,e.hj&&a&&e.hj.I(e.Ba)):(a=new D.Jh(e.j(),(0,D.cQ)(e,e.Ba,e.Fa)),c=e.Z.borderAlpha,a.pa(e.oz,e.mm),a.Ra(e.Ys,c),e.Na=a,e.Ma(e.Na,0),e.Mz||(e.hj=D.zC.eaa(e.j(),25,e.Z,D.p),e.hj.B(e.Z.borderAlpha),e.k(e.hj),a="col_northwest"==e.Pj||"col_southwest"==e.Pj,e.om=e.isCollapsed()?D.U.IZ(e.j(),e.Zn,25,e.Z,a?D.U.pB:D.U.zw):D.U.GZ(e.j(),e.Zn,25,e.Z,a?D.U.pB:D.U.zw),e.hj.k(e.om),e.hj.I(a?e.Ba:-10),(0,D.Jf)()?e.om.la(D.kh,e.HI,D.p,e):(e.om.la(D.kk,e.HI,D.p,e),e.om.la(D.Yz,e.M2,D.p,e),e.om.la(D.Zz,e.L2,D.p,
e)))),e.SV&&(0,D.dQ)(e,D.p),e=this.Vc.F(),a=(0,D.E)(this.j())?5:this.getWidth()-5-e.e-e.x,(0,D.pk)(this.Vc,a,5),e.e+=5;if(this.Cla=b)e||(e=this.Vc.F()),this.Q7=e.e,this.Jb.Fk(this.getWidth()-this.Q7,this.getHeight(),D.k)}}};
D.x.Ij=function(){D.DS.o.Ij.call(this);var a=new D.D(this.j()),b=new D.D(this.j());this.Jb=this.da;this.Jb.k(a);this.Jb.ba.k(b);this.Uj(a,b);if(this.Xk){(this.Rc=this.Jb.Rc)&&this.Jb.k(this.Rc);(0,D.sT)(this);b=new D.A(0,0,this.getWidth(),this.getHeight());if(!this.ye&&!this.MK)D.dl.isSupported(this.dia)&&(this.Ua=D.dl.by(this.j(),this.dia,this.Jb,b,this.Zy));else{var c=D.o;this.s4&&!this.uq?c=this.Rza:this.Xk&&this.Xk.Ih!=this.gEa&&(c=this.Xk.Oq());D.dl.isSupported(c)&&(this.Ua=D.dl.qD(this.j(),
c,this.MK,this.Jb,b,this.Zy))&&this.k(this.MK)}this.Ua?(this.Rc&&this.k(this.Rc),this.eb.Cc(),this.eb.gi(this),this.wV=D.k,this.Ua.ie(this.sr,this),this.Ua.play()):this.sr();this.TEa=a;this.Xk&&(this.gEa=this.Xk.Ih);(0,D.Vl)(this.j(),[this]);this.ye=D.k}};
D.x.Uj=function(a,b){this.aD();b.k(this.o4);b.k(this.YO);this.Nz?a.k(this.xz):b.k(this.xz);a.k(this.vx);var c=this.Jb.ba.ta();this.E$=D.p;for(var d=0;d<this.Df.length;d++){var e=this.Df[d];if(!this.E$&&e instanceof D.OS||!(e instanceof D.OS))e.P(c),!this.E$&&e instanceof D.OS&&(this.E$=D.k,this.Xk=e)}this.Xk&&(c=this.Xk.pK,this.pK!=c&&(this.pK=c,this.m7=this.tla=this.sla=D.o),this.GC&&(c=(0,D.$S)(this),0==c.length&&(c=(0,D.mT)(this)),(c=c[0])&&D.qT.o.ws.call(this.eb,c)),this.Jb.qw(D.o),this.Jb.xu(D.o),
this.Jb.Wn=D.k,this.Jb.ji=D.k,!this.s4&&!this.uq&&this.m7!=D.o?((0,D.Sr)(this.Jb,this.m7),(0,D.Vr)(this.Jb,this.sla,this.tla)):this.Jb.Io(D.o,this.Xk.pH()),(0,D.tT)(this),(0,D.uT)(this),this.Jb.Wn=this.UG,this.Jb.ji=this.UK)};D.x.fOa=function(a,b,c){this.ye=D.p;(0,D.sT)(this);(0,D.vT)(new D.oT(this),[a],(0,D.pT)(this,b),this.Xk.Ih,c);this.aD();this.ye=D.k;this.GC&&(a=(0,D.$S)(this),0==a.length&&(a=(0,D.mT)(this)),(a=a[0])&&D.qT.o.ws.call(this.eb,a));(0,D.Vl)(this.j(),[this]);(0,D.uT)(this)};
D.DS.prototype.updateLayer=D.DS.prototype.fOa;D.uT=function(a){var b;b=a.Jb.Jq;var c=a.Xk.pH(),d=a.Jb.Tc();b=window.Math.min((d.e-2*b)/c.e,(d.g-2*b)/c.g);a.Jb.qw(b);a.Jb.xu(b*(a.UG?a.EX:1))};D.kT=function(a){a.Xk.pK&&a.Jb.Io(D.o,a.Xk.pH());(0,D.tT)(a);a.n7&&(0,D.wT)(a)};D.DS.prototype.tda=(0,D.ba)("H9");D.xT=function(a,b){var c=new D.hj;c.translate(b.qc,b.oc);a.Nz&&a.xz.za(c);a.vx.za(c)};D.DS.prototype.gfa=function(a){var b=new D.hr;(0,D.El)(b,"isLegendDisclosed","show"==a.xj());this.dispatchEvent(b)};
D.yT=function(a,b,c){if(b=b.J){var d=a.Jb.ba,e=(0,D.Bp)(b,d,d.ta);c&&(a.xja=d.ta(),(0,D.T)(b,"typeMatrix",a,a.WBa,a.iGa,e));c=new D.hj(1,0,0,1,e.qc,e.oc);a.Nz&&(0,D.T)(b,"typeMatrix",a.xz,a.xz.ta,a.xz.za,c);(0,D.T)(b,"typeMatrix",a.vx,a.vx.ta,a.vx.za,c)}};
D.DS.prototype.ph=function(a){switch(a.xj()){case "adjustPanConstraints":if(this.UK){var b=a.qv;a=this.Jb.Jq;var c=this.Jb.Tc();a=new D.A(a,a,c.e-2*a,c.g-2*a);var d=this.Xk.pH(),e=d.x*b,c=d.y*b,f=d.e*b,b=d.g*b,d=0;f>a.e?(this.Cla&&(0,D.E)(this.j())&&(d=this.Q7),this.Jb.xt=a.x+a.e+d-(e+f),this.Jb.vt=a.x-e+d):(this.Cla&&(0,D.E)(this.j())&&(d=2*this.Q7),e=(a.x+a.e+d)/2-(e+f/2),this.Jb.xt=e,this.Jb.vt=e);b>a.g?(this.Jb.yt=a.y+a.g-(c+b),this.Jb.wt=a.y-c):(a=(a.y+a.g)/2-(c+b/2),this.Jb.yt=a,this.Jb.wt=
a)}break;case "zooming":case "elasticAnimBegin":(0,D.yT)(this,a,D.k);break;case "zoomed":if(a.qv!=D.o){c=this.Jb.ba.ta();(0,D.El)(a,"panX",c.qc);(0,D.El)(a,"panY",c.oc);a.J=D.o;this.dispatchEvent(a);(0,D.xT)(this,c);for(b=0;b<this.Df.length;b++)this.Df[b].ph(a,c)}break;case "zoomAndCenter":(0,D.zT)(this);break;case "zoomToFitEnd":this.dispatchEvent(new D.WC)}};
D.DS.prototype.Ew=function(a){var b=a.xj();if("elasticAnimBegin"==b)(0,D.yT)(this,a,D.p);else if("panned"==b&&a.Rma!=D.o){var c=this.Jb.ba.ta();(0,D.El)(a,"zoom",this.Jb.Cd());(0,D.El)(a,"panX",c.qc);(0,D.El)(a,"panY",c.oc);a.J=D.o;this.dispatchEvent(a);(0,D.xT)(this,c);for(a=0;a<this.Df.length;a++)this.Df[a].Ew(c)}this.Vc&&("alta"==this.nc?"dragPanBegin"===b?this.Vc.qa(D.p):"dragPanEnd"===b&&this.Vc.qa(D.k):(c=this.ls(),a=this.Vc.Na.Yb().Y(),"dragPanBegin"===b?(this.wb.B(c.backgroundDragAlpha),a.B(c.borderDragAlpha),
this.Vc.Na.V(a),this.Vc.hj&&this.Vc.hj.B(c.borderDragAlpha),this.Vc.qa(D.p)):"dragPanEnd"===b&&(this.wb.B(1),a.B(c.borderAlpha),this.Vc.Na.V(a),this.Vc.hj&&this.Vc.hj.B(c.borderAlpha),this.Vc.qa(D.k))))};D.DS.prototype.tB=function(){return"none"==this.hn&&!this.UG&&(!this.UK||"alta"==this.nc)?"hidden":D.DS.o.tB.call(this)};D.DS.prototype.VT=function(){var a=this.tB();return"hidden"!=a?new D.AT(this.j(),this,"initCollapsed"==a?1:2):D.o};
D.tT=function(a){a.jY=D.k;for(var b=0;b<a.Df.length;b++){var c=a.Df[b].Ih;c in a.HP&&(a.iL[c]=a.HP[c][1],a.nm=c,a.bx=a.HP[c][0],a.NZ())}a.jY=D.p};
D.DS.prototype.ada=function(){(0,D.sT)(this);for(var a=[],b=[],c=this.Df.length-1;-1<c;c--)this.Df[c].Ih==this.Xk.Ih?this.Df[c].reset(b):this.Df[c].reset(a);for(c=0;c<a.length;c++)if(a[c]){var d=a[c].getParent();d&&d.removeChild(a[c])}for(c=0;c<b.length;c++)b[c]&&b[c].B(1);this.lP=[];a=new D.lr(this.j(),0.3);this.Jb.Io(a);a.play();this.Uo=[];this.Rc&&"none"!=this.hn&&((0,D.BT)(this.Rc,D.p),(0,D.CT)(this.Rc,D.p))};
D.wT=function(a){var b=a.YO.F(),c=a.xz.F();if(a.Nz){var d=a.Jb.ba.ta();c.e/=d.Ed;c.g/=d.ig;c.x/=d.Ed;c.y/=d.ig}b=(0,D.Bo)(b,c);(0,D.sT)(a);var e;a.Jb.Wn||(e=a.Jb.fy(),a.Jb.xu(e*a.EX));var f;(0,D.Zk)()&&(f=new D.lr(a.j(),0.3));0<b.e&&0<b.g?a.Jb.Io(f,b):a.Jb.Io(f,a.Xk.pH());f&&f.play();e&&a.Jb.xu(e)};D.DS.prototype.TG=function(a){var b=new D.lr(this.j(),0.3);this.Jb.Io(b,a);b.play()};
D.zT=function(a){if(a.bx){var b=(0,D.pT)(a,a.nm).ti(a.bx);if(b&&(b=b.Hb)){for(var b=b.getSelection(),c=0;c<b.length;c++)b[c]=b[c].ia();if(0<b.length){for(var d=b[0].F(),c=1;c<b.length;c++)d=(0,D.Bo)(d,b[c].F());a.TG(d)}}}};D.DT=function(a,b){var c=D.GS.nKa(a.pk,b);return(0,D.pT)(a,c)};D.WS=function(a,b){var c=D.GS.Uqa(a.pk,b);return(0,D.pT)(a,c)};D.$S=function(a){var b=[];if(a.Xk)for(var c=0;c<a.Df.length;c++){var d=a.Df[c].Gj,e;for(e in d)b=a.Xk.Ih==a.Df[c].Ih?b.concat((0,D.eT)(d[e])):b.concat((0,D.fT)(d[e]))}return b};
D.mT=function(a){var b=[];if(a.Xk)for(var c=0;c<a.Df.length;c++){var d=a.Df[c].Gj;if(a.Xk.Ih==a.Df[c].Ih||!(a.Df[c]instanceof D.OS))for(var e in d)b=b.concat(d[e].jk)}return b};D.DS.prototype.iGa=function(a){this.xja=a;if(this.Nz){for(var b=(0,D.mT)(this),c=0;c<b.length;c++)b[c].ph(a);b=this.vx.Ja();for(c=0;c<b;c++)for(var d=this.vx.ha(c),e=d.Ja(),f=0;f<e;f++){var g=d.ha(f);g instanceof D.TS&&g.update(a)}}};D.DS.prototype.WBa=(0,D.v)("xja");
D.DS.prototype.NZ=function(){(0,D.sT)(this);var a=(0,D.WS)(this,this.nm),b=(0,D.pT)(this,this.nm),c=[];if(a){this.yW[this.nm]=this.bx;for(var d=this.iL[this.nm],e=[],f=0;f<d.length;f++){var g;a:{g=b.ti(this.bx).Oc;for(var h=0;h<g.length;h++)if(g[h].zk()===d[f]){g=g[h];break a}g=D.o}g.aw()||e.push(d[f])}!this.jY&&"single"==this.hn&&(this.Uo.pop(),b.reset(c,d),a.reset(this.Az));d=[];for(f=0;f<e.length;f++){g=e[f];h=(0,D.SS)(b,g);d.push(h[0]);for(var j=0;j<h.length;j++)this.f5[h[j]]=g;a.maa(h,c);if(h=
b.ti(this.bx)){for(var j=g,l=this.Az,m=0;m<h.Oc.length;m++)if(h.Oc[m].zk()==j){h.Oc[m].SM(D.k);h.Uo.push(j);l.push(h.Oc[m].ia());if(m=h.Oc[m].Nc())l.push(m),(m=m.wm)&&l.push(m);break}for(m=0;m<h.jk.length;m++)if(h.jk[m].zk()==j){l.push(h.jk[m].ia());break}}this.Uo.push(g)}(0,D.ET)(this,this.Az,c,D.p);(0,D.FT)(this,a.Ih,D.k);this.nm=a.Ih;this.iL[this.nm]=d}};
D.DS.prototype.naa=function(){(0,D.sT)(this);for(var a=(0,D.pT)(this,this.nm),b=(0,D.DT)(this,this.nm),c=[],d=[],e=this.iL[this.nm],f=0;f<e.length;f++){var g=this.f5[e[f]];d.push(g);if(-1!=D.H.wa(this.Uo,g)){a.CT((0,D.SS)(b,g),this.Az);for(var h=b.ti(this.yW[b.Ih]),j=g,l=c,m=0;m<h.Oc.length;m++)if(h.Oc[m].zk()==j){var n=D.H.wa(h.Uo,j);h.Uo.splice(n,1);h.Oc[m].SM(D.p);n=h.Oc[m].ia();h.en.k(n);l.push(n);if(m=h.Oc[m].Nc())m.update(h.ZK),l.push(m),l.push(m.wm);break}for(m=0;m<h.jk.length;m++)if(h.jk[m].zk()==
j){n=h.jk[m].ia();h.ix.k(n);l.push(n);break}g=D.H.wa(this.Uo,g);-1!=g&&this.Uo.splice(g,1)}}(0,D.ET)(this,this.Az,c,D.k);this.nm=b.Ih;this.bx=this.yW[this.nm];this.iL[this.nm]=d;(0,D.FT)(this,this.nm)};D.sT=function(a){a.Ua&&(a.Ua.stop(D.k),a.Ua=D.o)};
D.ET=function(a,b,c,d){a.Jb.ba.ta();if("zoomToFit"==a.l4&&!a.jY){var e=new D.lr(a.j(),0.3);(0,D.Zk)()||(e=D.o);d?a.Jb.Io(e):(0,D.zT)(a);e&&e.play()}(0,D.sT)(a);if((0,D.Zk)()&&("alphaFade"==a.l4||"auto"==a.l4))a.Ua=D.dl.qD(a.j(),"alphaFade",b,c,D.o,0.5);a.Ua?(a.eb.Cc(),a.eb.gi(a),a.Ua.ie(a.Vva,a),a.Ua.play()):(0,D.GT)(a)};
D.DS.prototype.dispatchEvent=function(a){var b=a.Pa();if("selection"==b)if(this.bx){this.X9=a.getSelection();for(var b=this.iL,c=this.nm,d=this.X9,e=[],f=(0,D.pT)(this,this.nm).ti(this.bx).Oc,g=0;g<d.length;g++)for(var h=0;h<f.length;h++)if(f[h].getId()==d[g]){e.push(f[h].zk());break}b[c]=e;(0,D.FT)(this,this.nm);(0,D.El)(a,"clientId",this.bx);this.RV&&!(this.RV instanceof D.JH)&&(this.Kpa=this.RV)}else(0,D.FT)(this,D.o),this.Kpa=D.o;else b==D.jT.Jga?((0,D.El)(a,"clientId",this.SJ),this.lP="multiple"==
this.hn?this.lP.concat(this.X9):this.X9,b=a.BBa,b==D.jT.Rua&&this.naa(),b==D.jT.L1?this.NZ():b==D.jT.bwa&&this.ada(),a.yf(this.lP)):("showPopup"==b||"hidePopup"==b)&&(0,D.El)(a,"clientId",this.SJ);D.DS.o.dispatchEvent.call(this,a)};D.FT=function(a,b,c){if(a.Rc&&a.hn&&"none"!=a.hn){var d=(0,D.WS)(a,b);b=(0,D.DT)(a,b);d&&!c?(0,D.BT)(a.Rc,D.k):(0,D.BT)(a.Rc,D.p);b?(0,D.CT)(a.Rc,D.k):(0,D.CT)(a.Rc,D.p)}};D.DS.prototype.Q=function(){D.DS.o.Q.call(this);this.eb&&(this.eb.Q(),this.eb=D.o)};
D.DS.prototype.destroy=D.DS.prototype.Q;D.DS.prototype.sr=function(){this.Rc&&this.Jb.k(this.Rc);this.MK&&(this.removeChild(this.MK),this.MK=D.o);this.Ua=D.o;this.n7&&(0,D.wT)(this);this.D.highlightedCategories&&0<this.D.highlightedCategories.length&&this.Ge(this.D.highlightedCategories);this.wV&&(this.eb.me(this),this.wV=D.p)};D.DS.prototype.Vva=function(){(0,D.GT)(this);this.Ua=D.o;this.eb.me(this)};
D.GT=function(a){if(0<a.Az.length){for(var b=0;b<a.Az.length;b++){var c=a.Az[b];if(c)if(c instanceof D.TS)c.reset();else if(c.aw&&c.aw())c.B(0);else{var d=c.getParent();d&&d.removeChild(c)}}a.Az=[]}};D.DS.prototype.p6=function(a,b){var c=new D.zm(a,b),d=[],e;for(e in this.fj)for(var f in this.fj[e])d.push(this.fj[e][f]);for(e in this.nn)for(f in this.nn[e])d.push(this.nn[e][f]);e=this.wb.GPa;for(var g in e)f=new D.HT(e[g].ag(),g),d.push(f);(0,D.ql)(c.Pk,d,D.k)};D.DS.prototype.rd=(0,D.v)("pd");
D.DS.prototype.aN=(0,D.ba)("pd");D.DS.prototype.Gf=function(){this.Kk||(this.Kk=new D.IT(this));return this.Kk};D.DS.prototype.getAutomation=D.DS.prototype.Gf;D.DS.prototype.Hj=function(){return(0,D.L)("DvtUtilBundle","THEMATIC_MAP")};D.DS.prototype.Oca=function(a){"dvtResizeEvent"==a.Pa()&&this.wb&&this.wb.yc(a)};D.DS.prototype.Ge=function(a){this.D.highlightedCategories=D.pl.Y(a);(0,D.ql)(a,(0,D.$S)(this).concat((0,D.mT)(this)),"any"==this.D.highlightMatch)};D.DS.prototype.highlight=D.DS.prototype.Ge;
D.DS.prototype.ss=function(a,b){var c=(0,D.JT)(this,a);c&&c.ss(b)};D.DS.prototype.processDefaultHoverEffect=D.DS.prototype.ss;D.DS.prototype.bB=function(a,b){var c=(0,D.JT)(this,a);c&&c.bB(b)};D.DS.prototype.processDefaultSelectionEffect=D.DS.prototype.bB;D.DS.prototype.kw=function(a,b){var c=(0,D.JT)(this,a);c&&c.kw(b)};D.DS.prototype.processDefaultFocusEffect=D.DS.prototype.kw;
D.JT=function(a,b){for(var c=0;c<a.Df.length;c++){var d=a.Df[c].Gj,e;for(e in d)for(var f=d[e].jk,g=0;g<f.length;g++)if(f[g].getId()===b)return f[g]}return D.o};
D.ES=function(){this.Init({fusion:D.MT,alta:D.NT})};D.z.l(D.ES,D.Nj,"DvtThematicMapDefaults");
D.MT={animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"none",highlightMatch:"all",hoverBehavior:"none",initialZooming:"none",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",touchResponse:"auto",visualEffects:"none",zooming:"none",styleDefaults:{skin:"alta",areaStyle:"background-color:#B8CDEC;border-color:#FFFFFF;",hoverBehaviorDelay:200,dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",
drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",borderWidth:0.5,color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:0.4,scaleX:1,scaleY:1,shape:"circle",width:8},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:D.k,layout:{gapRatio:1}},layout:{gapRatio:D.o,legendMaxSize:0.3,legendGap:10},resources:{images:{},
translations:{}}};D.NT={styleDefaults:{areaStyle:"background-color:#DDDDDD;border-color:#FFFFFF;",dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;color:#333333',opacity:1},labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;'}};D.OT={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};D.PT={animationOnDataChange:"none",selectionMode:"none"};
D.UT=function(a){for(var b=0;b<a.Df.length;b++){var c=a.Df[b].Gj,d;for(d in c){var e=c[d].Hd;if(e&&e.nC)return e}}return D.o};D.x=D.DS.prototype;D.x.zj=function(a,b,c){this.vBa=D.p;return(a=(0,D.UT)(this))?a.zj(c):D.p};D.x.yk=function(a,b){var c=(0,D.UT)(this);return c?c.yk(a,b):D.o};D.x.$t=function(a,b){var c=(0,D.UT)(this);return c?c.$t(a,b):D.o};D.x.xp=function(a,b){var c=(0,D.UT)(this);return c?c.xp(a,b):D.o};D.x.Ov=function(a,b){var c=(0,D.UT)(this);return c?c.Ov(a,b):D.o};
D.x.Vv=function(a,b){var c=(0,D.UT)(this);return c?c.Vv(a,b):D.o};D.x.$v=function(){var a=(0,D.UT)(this);a&&a.$v()};D.x.es=function(){var a=(0,D.UT)(this);a&&a.es();(0,D.pu)(this.da)};
D.DS.prototype.ro=function(a,b,c){var d=this.Jb.Cd();a=(a-(0,D.Tr)(this.Jb))/d;b=(b-(0,D.Ur)(this.Jb))/d;a:{for(var d=a,e=b,f=0;f<this.Df.length;f++)if(this.Df[f].lJa){var g=this.Df[f].wl;if(g&&g.ks(d,e)){d=g;break a}}d=D.o}return(this.wl=d)?this.wl.ro(a,b,c):D.o};D.DS.prototype.ks=function(a,b){var c=this.Jb.Cd();a=(a-(0,D.Tr)(this.Jb))/c;b=(b-(0,D.Ur)(this.Jb))/c;return this.wl?this.wl.ks(a,b):D.o};
D.QS=function(a,b){this.cV=a;this.xAa=b};D.z.l(D.QS,D.qu,"DvtThematicMapDropTarget");D.QS.prototype.ro=function(a,b,c){if(a=(0,D.XS)(this.cV,a,b))a!=this.uF&&(this.cV.Hu(a),this.uF=a);else return this.cV.Hu(D.o),D.o;return c[0]};D.QS.prototype.ks=function(a,b){var c=(0,D.XS)(this.cV,a,b);if(c){var d=D.Z.bMa(a,b,this.xAa);return{sRa:c.aAa,cRa:d.x,dRa:d.y}}return D.o};
D.IT=(0,D.ba)("aa");(0,D.da)("DvtThematicMapAutomation",D.IT);D.z.l(D.IT,D.Dj,"DvtThematicMapAutomation");
D.IT.prototype.ql=function(a){var b=(0,D.Ej)(this.aa.ka(),a);if(b&&(b instanceof D.YS||b instanceof D.ZS)){var c;a:{a=b.ia();for(var d=this.aa.Df,e=0;e<d.length;e++){var f=d[e].Gj;for(c in f)if(a instanceof D.Jh)for(var g=f[c].Oc,h=0;h<g.length;h++){if(g[h]===b){c=(0,D.KT)(c)+":area["+h+"]";break a}}else if(a instanceof D.dh||a instanceof D.ch){g=f[c].jk;for(h=0;h<g.length;h++)if(g[h]===b){c=(0,D.KT)(c)+":marker["+h+"]";break a}}}c=D.o}return c}if(c=this.aa.da.Rc)if((b=(0,D.Ej)(c.ka(),a))&&b instanceof
D.Oe){a="disclosure zoomIn zoomOut zoomToFit drillDown drillUp reset".split(" ");for(d=0;d<a.length;d++)if(c.Nq(a[d])===b)return"controlPanel#"+a[d]}return D.o};
D.IT.prototype.If=function(a){if("tooltip"==a)return(0,D.bm)(this.aa);var b=a.indexOf(":"),c=a.indexOf("[");return 0<b&&0<c?(a=(0,D.LT)(this,a.substring(0,b),a.substring(b+1,c),(0,window.parseInt)(a.substring(c+1,a.length-1))))?a.ia().sa():D.o:0===a.lastIndexOf("controlPanel")&&(b=a.indexOf("#"),0<b&&(a=a.substring(b+1),(b=this.aa.da.Rc)&&a))?(a=b.Nq(a))?a.sa():D.o:D.o};D.IT.prototype.getDomElementForSubId=D.IT.prototype.If;
D.IT.prototype.getData=function(a,b,c){return(a=(0,D.LT)(this,a,b,c))?(b={},b.color=a.vi(),b.tooltip=a.Bc(),c=a.Nc(),b.label=c?c.Bd():D.o,b.selected=a.Da(),b):D.o};D.IT.prototype.getData=D.IT.prototype.getData;D.LT=function(a,b,c,d){a=a.aa.Df;for(var e=0;e<a.length;e++){var f=a[e].Gj,g;for(g in f)if((0,D.KT)(g)==b){if("area"==c)return f[g].Cja[d];if("marker"==c)return f[g].Eja[d]}}return D.o};D.KT=function(a){var b=a.lastIndexOf(":");return 0<b?a.substring(b+1):a};
D.IS=function(a,b){this.Init(a,b)};D.z.l(D.IS,D.Jh,"DvtDrillablePath");D.x=D.IS.prototype;D.x.Init=function(a,b){D.IS.o.Init.call(this,a);this.lC=this.kC=this.qW=this.pW=D.o;this.u7=D.p;this.Zoom=1;this.Tf=b};D.x.aw=(0,D.v)("u7");
D.x.SM=function(a){this.u7!=a&&(this.u7=a,this.aw()?(this.kC=this.Vi(),this.kC.L(D.o),this.kC.qa(D.p),this.lC=this.Vi(),this.lC.L(D.o),this.lC.qa(D.p),a=this.getParent(),a.k(this.lC),a.k(this.kC),this.kC.V((0,D.JS)(this,this.pW,2)),this.lC.V((0,D.JS)(this,this.qW,4)),this.qa(D.p),this.cf=D.p):(this.cf&&(this.Lh(),this.Ci.V((0,D.JS)(this,this.Ls,1),2)),this.lC.getParent().removeChild(this.lC),this.kC.getParent().removeChild(this.kC),this.qa(D.k),this.B(1)))};
D.x.jb=function(a){this.Mk!=a&&(a&&(this.cf?(this.qN(),this.Xm=(0,D.JS)(this,this.Xm,2),this.gm=(0,D.JS)(this,this.gm,6)):(this.Qs=(0,D.JS)(this,this.Qs,1),this.eq=(0,D.JS)(this,this.eq,4))),D.IS.o.jb.call(this,a))};D.x.Ob=function(){this.Da()?(this.qN(),this.Xm=(0,D.JS)(this,this.Xm,2),this.gm=(0,D.JS)(this,this.gm,6)):this.Ls=(0,D.JS)(this,this.Ls,2);D.IS.o.Ob.call(this)};
D.x.qN=function(){this.Xm||(this.Xm=this.Ls.Y(),this.Xm.ma(2),this.Tf&&(this.Xm.Gc=D.k));this.gm||(this.gm=this.eq.Y(),this.gm.ma(6),this.Tf&&(this.gm.Gc=D.k))};D.x.Db=function(){this.Da()&&(this.Qs=(0,D.JS)(this,this.Qs,1),this.eq=(0,D.JS)(this,this.eq,4));D.IS.o.Db.call(this)};D.x.Pp=function(a,b){D.IS.o.Pp.call(this,a,b);this.Tf&&(this.Ls&&(this.Ls.Gc=D.k),this.FN&&(this.FN.Gc=D.k));return this};
D.x.Rp=function(a,b){D.IS.o.Rp.call(this,a,b);this.Tf&&(this.Qs&&(this.Qs.Gc=D.k),this.eq&&(this.eq.Gc=D.k));return this};D.x.kr=function(a,b){D.IS.o.kr.call(this,a,b);this.Tf&&(this.Xm&&(this.Xm.Gc=D.k),this.gm&&(this.gm.Gc=D.k));return this};D.KS=function(a,b,c){if(!a.Tf){var d=b.Yb();d&&(d=d.Y(),d.ma(c/a.Zoom),b.V(d))}};D.JS=function(a,b,c){a.Tf||(b=b.Y(),b.ma(c/a.Zoom));return b};
D.LS=function(a,b){a.Zoom=b.Ed;a.aw()?((0,D.KS)(a,a.kC,2),(0,D.KS)(a,a.lC,4)):a.Da()?a.cf?((0,D.KS)(a,a.Ci,2),(0,D.KS)(a,a,6)):((0,D.KS)(a,a.Ci,1),(0,D.KS)(a,a,4)):a.cf?(0,D.KS)(a,a.Ci,2):(0,D.KS)(a,a,1)};
D.HS=function(a,b,c){this.Init(a,b,c)};D.z.l(D.HS,D.D,"DvtCustomDataItem");D.x=D.HS.prototype;
D.x.Init=function(a,b,c){D.HS.o.Init.call(this,a);this.wz=b;b instanceof D.sj?(this.Ba=b.getWidth(),this.Fa=b.getHeight(),this.k(b)):(this.sa().appendChild(b),b=(0,D.rg)(a,this),this.Ba=b.e,this.Fa=b.g);this.Vu=new D.Te(a,-5,-5,this.Ba+10,this.Fa+10);(0,D.wi)(this.Vu);a=new D.hg(c.selectedInnerColor,1,2);b=new D.hg("rgb(235, 236, 237)",1,4);var d=new D.hg(c.selectedInnerColor,1,2),e=new D.hg(c.selectedOuterColor,1,4),f=new D.hg(c.selectedInnerColor,1,2);c=new D.hg(c.selectedOuterColor,1,6);this.Vu.Pp(a,
b).Rp(d,e).kr(f,c);this.Ma(this.Vu,0)};D.x.$b=function(a,b){(0,D.Jf)()?this.Vu.$b(a,b):D.HS.o.$b.call(this,a,b)};D.x.Ud=function(a){(0,D.Jf)()?this.Vu.Ud(a):D.HS.o.Ud.call(this,a)};D.x.getWidth=(0,D.v)("Ba");D.x.getHeight=(0,D.v)("Fa");D.x.Lf=function(a){this.Vu.Lf(a)};D.x.Aa=function(){return this.Vu.Aa()};D.x.Da=function(){return this.Vu.Da()};D.x.jb=function(a){this.Vu.jb(a)};D.x.Ob=function(){this.Vu.Ob()};D.x.Db=function(){this.Vu.Db()};D.x.CD=(0,D.v)("wz");
D.x.VL=function(a){this.wz instanceof D.sj&&this.wz.VL(a)};
this?this.DvtBaseMapManager?D.GS=this.DvtBaseMapManager:(this.DvtBaseMapManager=D.GS={},D.GS._UNPROCESSED_MAPS=[[],[],[]],D.GS._UNPROCESSED_PARENT_UPDATES=[[]]):window.DvtBaseMapManager?D.GS=window.DvtBaseMapManager:(D.GS={},window.DvtBaseMapManager=D.GS,D.GS._UNPROCESSED_MAPS=[[],[],[]],D.GS._UNPROCESSED_PARENT_UPDATES=[[]]);D.z.l(D.GS,D.z,"DvtBaseMapManager");D.GS.HE=0;D.GS.ZN=1;D.GS.z3=2;D.GS.y3=3;D.GS.LU=4;D.GS.Mw="__index";D.GS.Di={};
D.GS.Mqa=function(a,b){D.GS.Dq();var c=D.GS.Di[a][b];return c&&(c=c[D.GS.LU])?new D.A(c[0],c[1],c[2],c[3]):D.o};D.GS.vIa=function(a,b){D.GS.Dq();var c=D.GS.Di[a][b];return c?c[D.GS.y3]:D.o};D.GS.wIa=function(a,b){D.GS.Dq();var c=D.GS.Di[a][b];return c?c[D.GS.HE]:D.o};D.GS.OJa=function(a,b,c){D.GS.Dq();a=D.GS.Di[a][b];var d;a&&(d=a[D.GS.HE]);return d&&d[c]?d[c][1]:D.o};D.GS.KIa=function(a,b){D.GS.Dq();var c=D.GS.Di[a];if(c&&(c=c.cities))if(c=c[D.GS.ZN][b])return new D.F(c[0],c[1]);return D.o};
D.GS.LIa=function(a,b){D.GS.Dq();var c=D.GS.Di[a];if(c&&(c=c.cities))if(c=c[D.GS.HE][b])return c[1];return D.o};D.GS.tIa=function(a,b,c){D.GS.Dq();var d=D.GS.Di[a];if(d&&(d=d[b])){if((d=d[D.GS.y3])&&d[c])return(0,D.CF)(d[c][0]).Kd();a=D.GS.Di[a][b][D.GS.ZN][c];if(!a)return D.o;a=D.K.CR(a);return D.K.F(a).Kd()}return D.o};D.GS.Uqa=function(a,b){D.GS.Dq();var c=D.GS.Di[a][b];return c?D.GS.Di[a][D.GS.Mw][c.__index+1]:D.o};
D.GS.nKa=function(a,b){D.GS.Dq();return D.GS.Di[a][b]?D.GS.Di[a][D.GS.Mw][D.GS.Di[a][b].__index-1]:D.o};D.GS.Hqa=function(a,b){D.GS.Dq();return D.GS.Di[a][b][D.GS.ZN]};D.GS.oKa=function(a,b,c){D.GS.Dq();return D.GS.Di[a][b][D.GS.ZN][c]};D.GS.JIa=function(a,b){D.GS.Dq();var c=D.GS.Uqa(a,b);return c&&(c=D.GS.Di[a][c][D.GS.z3])?c:[]};D.GS.NQa=function(a,b){D.GS.Dq();return D.GS.Di[a][D.GS.Mw][b]};
D.GS.Tca=function(a,b,c,d,e,f,g,h){var j=D.GS.Di[a];j||(j={},j[D.GS.Mw]=[],D.GS.Di[a]=j);a=j[b];a||(a={},j[b]=a,g!=D.o&&(j[D.GS.Mw][g]=b));a[D.GS.HE]=c;a[D.GS.ZN]=d;a[D.GS.z3]=e;a[D.GS.y3]=f;a[D.GS.LU]=h;a[D.GS.Mw]=g};(0,D.da)("DvtBaseMapManager.registerBaseMapLayer",D.GS.Tca);D.GS.Dta=function(a,b,c){var d=D.GS.Di[a];d||(d={},D.GS.Di[a]=d);a=d[b];a||(a={},d[b]=a);(a=d[b])&&(a[D.GS.HE]=c)};(0,D.da)("DvtBaseMapManager.registerResourceBundle",D.GS.Dta);
D.GS.bua=function(a,b,c){if(a=D.GS.Di[a])if(b=a[b])for(var d in c)b[D.GS.HE][d]=c[d]};(0,D.da)("DvtBaseMapManager.updateResourceBundle",D.GS.bua);
D.GS.Dq=function(){var a,b,c=D.GS._UNPROCESSED_MAPS;if(c){for(a=0;a<c[0].length;a++)b=c[0][a],D.GS.Tca(b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7]);for(a=0;a<c[1].length;a++)b=c[1][a],D.GS.Dta(b[0],b[1],b[2]);for(a=0;a<c[2].length;a++)b=c[2][a],D.GS.bua(b[0],b[1],b[2]);D.GS._UNPROCESSED_MAPS=[[],[],[]]}if(c=D.GS._UNPROCESSED_PARENT_UPDATES){for(a=0;a<c[0].length;a++){b=c[0][a];var d=b[1],e=b[2],f=D.GS.Di[b[0]],g;if(f){if(d=f[d]){d[D.GS.z3]=b[3];g=d[D.GS.LU];a=d[D.GS.Mw];d=f[D.GS.Mw];d.splice(a,0,e);f[e][D.GS.Mw]=
a;for(a+=1;a<d.length;a++)(e=f[d[a]])&&e[D.GS.Mw]++}(d=f[b[2]])&&(d[D.GS.LU]=g)}}D.GS._UNPROCESSED_PARENT_UPDATES=[[]]}};D.GS.YNa=function(a,b,c,d,e,f){if(0<f){b=1/(window.Math.min(d/b,e/c)*f);if(1>=b)return a;c=[];if(a)for(var g in a)d=a[g],(0,window.isNaN)(d)&&(d=D.K.CR(a[g])),c[g]=D.K.ZNa(d,b);return c}return a};D.GS.JJa=function(a,b){D.GS.Dq();var c=D.GS.Di[a][b],d={};if(c){var c=c[D.GS.HE],e;for(e in c)d[e]=c[e][1]}return d};(0,D.da)("DvtBaseMapManager.getLayerIds",D.GS.JJa);
D.HT=function(a,b){this.Init(a,b)};D.z.l(D.HT,D.z,"DvtThematicMapCategoryWrapper");D.HT.prototype.Init=function(a,b){this.vg=a;this.Pk=b};D.HT.prototype.Mc=(0,D.v)("Pk");D.HT.prototype.Yc=function(){return[this.vg]};
D.jT=function(a){this.Init(D.jT.Jga);this.BBa=a};D.z.l(D.jT,D.Li,"DvtMapDrillEvent");D.jT.Jga="drill";D.jT.Rua=0;D.jT.L1=1;D.jT.bwa=2;D.jT.prototype.yf=(0,D.ba)("gn");
D.MS=function(a,b,c){this.Init("action");this.cC=a;this.XQ=b;this.an=c};(0,D.da)("DvtMapActionEvent",D.MS);D.z.l(D.MS,D.Li,"DvtMapActionEvent");D.MS.TYPE="action";D.MS.prototype.al=(0,D.v)("cC");D.MS.prototype.getClientId=D.MS.prototype.al;D.MS.prototype.rba=(0,D.v)("XQ");D.MS.prototype.getRowKey=D.MS.prototype.rba;D.MS.prototype.Ce=(0,D.v)("an");D.MS.prototype.getAction=D.MS.prototype.Ce;
D.TS=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};D.z.l(D.TS,D.Kf,"DvtMapLabel");D.x=D.TS.prototype;D.x.Init=function(a,b,c,d,e,f){D.TS.o.Init.call(this,a,b,0,0);this.Tf=f;this.Zw=[];this.qa(D.p);this.Ye();this.wf();this.li=D.o;this.Sr=d;this.rG=e;if(c&&(this.Zw.push((0,D.CF)(c[0])),1<c.length)){this.P7=[];for(b=1;b<c.length;b++)d=c[b],this.Zw.push((0,D.CF)(d[0])),d=new D.po(a,d[1]),(0,D.Ei)(d),e=new D.hg("#000000"),this.Tf&&(e.Gc=D.k),d.V(e),this.P7.push(d)}};
D.x.update=function(a){a=a.Ed;for(var b=-1,c=D.$e.Dh(this),d=D.p,e=0;e<this.Zw.length;e++){var f=this.Zw[e].e*a;if(c.g<=this.Zw[e].g*a)if(c.e<=f){b=e;break}else if(this.getParent()||(d=D.k,this.rG.k(this)),this.F().e<=f){b=e;break}}-1==b&&"on"==this.Sr&&(b=this.Zw.length-1);this.E5!=b?(-1==b?this.reset():(this.getParent()||this.rG.k(this),c=this.Zw[b].Kd(),this.Np(c),this.P7&&(this.rG.removeChild(this.wm),this.wm=D.o,0<b?(this.wm=this.P7[b-1],this.rG.k(this.wm),d=this.gc(),d.W("color","#000000"),
this.Ha(d),d=this.Zw[b],e=this.wm.vb(),f=e.length,d.x>e[f-2]?(this.yh(),this.wf(),this.Np(new D.F(d.x,c.y))):d.y>e[f-1]?(this.Ll(),this.Ye(),this.Np(new D.F(c.x,d.y))):d.x+d.e<e[f-2]?(this.zh(),this.wf(),this.Np(new D.F(d.x+d.e,c.y))):d.y+d.g<e[f-1]&&(this.so(),this.Ye(),this.Np(new D.F(c.x,d.y+d.g)))):(this.Ye(),this.wf(),d=this.gc(),d.W("color",this.Mla),this.Ha(d)))),this.E5=b):-1==b&&d&&this.rG.removeChild(this);-1!=this.E5&&(b=new D.hj,b.translate(a*this.li.x-this.li.x,a*this.li.y-this.li.y),
this.za(b),this.wm&&(this.wm.za(new D.hj(a,0,0,a)),this.Tf||(b=this.wm.Yb().Y(),b.ma(1/a),this.wm.V(b))))};D.x.Np=function(a){this.li=a;this.ca(a.x);this.va(a.y)};D.x.Kd=(0,D.v)("li");D.x.Ha=function(a){D.TS.o.Ha.call(this,a);this.Mla||(this.Mla=a.A("color"))};D.x.reset=function(){this.rG.removeChild(this);this.E5=-1;this.wm&&(this.rG.removeChild(this.wm),this.wm=D.o)};
D.ZS=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.z.l(D.ZS,D.z,"DvtMapObjPeer");D.x=D.ZS.prototype;
D.x.Init=function(a,b,c,d,e){this.oa=a;this.kq=b;this.Bb=c;this.Ib=this.Al=this.Th=D.p;this.Bb.dI&&this.Bb.dI(a.color);this.Cb=d;this.li=e;this.wk=1;this.H=b.aa;this.oa.categories||this.Cb&&(this.oa.categories=[this.Cb.Bd()]);c=a.location;"auto"==this.H.Nja&&c&&(b=b.IQ,(b=!(b instanceof D.OS)||b instanceof D.aT?D.GS.LIa(this.H.pk,c):D.GS.OJa(this.H.pk,b.Ih,c))&&(this.oa.shortDesc=a.shortDesc?b+": "+a.shortDesc:b));this.Bb&&(a.destination?(this.Bb.Ud("link"),this.U7=D.B.yD("_blank",a.destination)):
this.Bb.Ud("img"));this.$m()};D.x.getId=function(){return this.oa.id};D.x.al=function(){return this.oa.clientId};D.x.zk=function(){return this.oa.location};D.x.Kd=(0,D.v)("li");D.x.Np=function(a){this.li=a;this.VU()};D.x.ia=(0,D.v)("Bb");D.x.Nc=(0,D.v)("Cb");D.x.ti=(0,D.v)("kq");D.x.Ce=function(){return this.oa.action};D.x.kb=function(a){this.Bb.kb(a);this.Cb&&this.Cb.kb(a)};D.x.Bc=function(){return this.oa.shortDesc};
D.x.Tc=function(){return this.Bb.getWidth?this.Bb.getWidth()*this.Bb.getHeight():0};D.x.Mc=function(){return this.oa.categories};D.x.De=function(){if("none"!=this.H.Nja){var a=this.H.q().tooltip;return a?(0,D.ip)(this.H.j().ge(),a,this.vp()):this.Bc()}return D.o};D.x.vp=function(){return{id:this.getId(),label:this.Cb?this.Cb.Bd():D.o,color:this.vi(),location:this.zk(),x:this.oa.x,y:this.oa.y}};D.x.yD=(0,D.v)("U7");D.x.vi=function(){return this.oa.color?this.oa.color:"#000000"};
D.x.fc=function(){var a=[];this.Aa()&&a.push((0,D.L)("DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.ok)(this.Bc(),a)};D.x.Yc=function(){return[this.ia()]};D.x.$m=function(){if(!(0,D.cf)()){var a=this.fc();a&&this.Bb.$b("label",a)}};D.x.Lf=function(a){var b=this.Nc();this.Bb.Lf&&(this.Bb.Lf(a),b&&a&&b.setCursor("pointer"));this.oa.destination&&(this.Bb.setCursor("pointer"),b&&b.setCursor("pointer"))};D.x.Aa=function(){return this.Bb.Aa?this.Bb.Aa():D.p};D.x.Da=(0,D.v)("Th");
D.x.jb=function(a){if(this.Aa()){var b=this.Ki();this.Th=a;this.kq.q().selectionRenderer?(0,D.lT)(this,this.kq.q().selectionRenderer,this.Ki(),b):this.bB(a);this.$m()}};D.x.Ob=function(){var a=this.Ki();this.Al=D.k;this.kq.q().hoverRenderer?(0,D.lT)(this,this.kq.q().hoverRenderer,this.Ki(),a):this.ss(D.k)};D.x.Db=function(){var a=this.Ki();this.Al=D.p;this.kq.q().hoverRenderer?(0,D.lT)(this,this.kq.q().hoverRenderer,this.Ki(),a):this.ss(D.p)};D.x.aN=(0,D.ba)("pd");D.x.rd=(0,D.v)("pd");
D.x.zj=function(a){for(var b=this.kq.al(),c=0;c<a.length&&a[c]!=b;c++);return b};D.x.yk=function(){return this.kq.RB(this)};D.x.Zt=function(){return this.kq.QB()};D.x.Ad=function(a){return a.type==D.kk?this:32==a.keyCode&&a.ctrlKey?this:(0,D.Jm)(this,a,this.Uea())};D.x.Uea=function(){return(0,D.mT)(this.ti().aa)};D.x.Ee=function(a){return this.Bb.getParent()?this.Bb instanceof D.HS?this.Bb.F(a?a:this.Bb.j().Kc):this.Bb.F(a):new D.A(0,0,0,0)};D.x.yj=function(){return this.Bb.sa()};
D.x.Vd=function(){var a=this.Ki();this.Ib=D.k;this.kq.q().focusRenderer?(0,D.lT)(this,this.kq.q().focusRenderer,this.Ki(),a):this.kw(D.k)};D.x.jc=function(){if(this.pc()){var a=this.Ki();this.Ib=D.p;this.kq.q().focusRenderer?(0,D.lT)(this,this.kq.q().focusRenderer,this.Ki(),a):this.kw(D.p)}};D.x.pc=(0,D.v)("Ib");D.x.ph=function(a){this.Bb.getParent()&&(this.wk=a.Ed,this.VU())};
D.x.D0=function(){if(this.Cb){this.Cb.Ye();var a=this.Bb.Eg()*this.wk,b=this.Bb.Fg()*this.wk,c=this.Bb.getHeight(),d=this.Bb instanceof D.dh?this.Bb.Pa():"image",e=this.oa.labelPosition;"top"==e?(b=b-c/2-4,this.Cb.so()):"bottom"==e?(b+=c/2,this.Cb.Ll()):(b="triangleUp"==d?b+c/6:"triangleDown"==d?b-c/6:b,this.Cb.wf());this.Cb.ca(a).va(b)}};
D.x.VU=function(){var a=this.Bb.getWidth(),b=this.Bb.getHeight();if(a!=D.o&&b!=D.o&&this.Bb.getParent()){var c=0,d=this.li.x,c=this.li.y;this.Bb.Wv&&(c=this.Bb.Wv(),d=this.li.x*window.Math.cos(c)-this.li.y*window.Math.sin(c),c=this.li.x*window.Math.sin(c)+this.li.y*window.Math.cos(c));d=this.li.x*this.wk-d;c=this.li.y*this.wk-c;this.Bb instanceof D.HS&&(d+=this.li.x-a/2,c+=this.li.y-b/2);(0,D.pk)(this.Bb,d,c);(0,D.Eo)(this.Bb);this.D0()}};
D.x.gf=function(a,b){var c=new D.qn(this.H.j(),this.Bb,this.ti().xa()),d=b.ia();if(this.Bb.Rb){var e=d.Rb(),f=this.Bb.Rb();f instanceof D.En&&!(f.qb()==e.qb()&&f.fa()==e.fa())&&(this.Bb.L(e),b.Nc()&&this.Cb&&(e=this.Cb.Rb(),this.Cb.L(b.Nc().Rb().Y()),(0,D.T)(c.J,"typeFill",this.Cb,this.Cb.Rb,this.Cb.L,e)),(0,D.T)(c.J,"typeFill",this.Bb,this.Bb.Rb,this.Bb.L,f))}if(this.Bb.Yt&&(f=b.ia().Yt(),e=this.Bb.Yt(),f.x!=e.x||f.y!=e.y||f.e!=e.e||f.g!=e.g))this.Bb.eB(f),(0,D.T)(c.J,"typeRectangle",this.Bb,this.Bb.Yt,
this.Bb.eB,e);f=d.Wv();e=this.Bb.Wv();if(f!=e){var g=f-e;g>window.Math.PI?f-=2*window.Math.PI:g<-window.Math.PI&&(f+=2*window.Math.PI);this.Bb.$j(f);(0,D.T)(c.J,"typeNumber",this.Bb,this.Bb.Wv,this.Bb.$j,e)}var g=b.Kd(),h=this.Kd();if(g&&h&&(g.x!=h.x||g.y!=h.y||f!=e))this.Np(new D.F(g.x,g.y)),(0,D.T)(c.J,"typePoint",this,this.Kd,this.Np,new D.F(h.x,h.y));this.Cb&&b.Nc()?(f=b.Nc().ja(),e=this.Cb.ja(),f!=e&&(this.Cb.ca(f),(0,D.T)(c.J,"typeNumber",this.Cb,this.Cb.ja,this.Cb.ca,e)),f=b.Nc().na(),e=this.Cb.na(),
f!=e&&(this.Cb.va(f),(0,D.T)(c.J,"typeNumber",this.Cb,this.Cb.na,this.Cb.va,e)),b.Nc().B(0)):b.Nc()&&b.Nc().B(0);d.B(0);a.add(c,1)};D.x.kh=function(a){var b=[this.Bb],c=this.Nc();c&&b.push(c);b=new D.sn(this.H.j(),b,this.ti().xa());a.add(b,0)};D.x.qg=function(a){var b=[this.Bb];this.Bb.B(0);var c=this.Nc();c&&(c.B(0),b.push(c));b=new D.Vm(this.H.j(),b,this.ti().xa());a.add(b,2)};D.x.bB=function(a){this.Bb.jb&&this.Bb.jb(a)};D.x.kw=function(a){this.ss(a)};
D.x.ss=function(a){a?this.Bb.Ob&&this.Bb.Ob():this.Bb.Db&&!this.pc()&&this.Bb.Db()};D.lT=function(a,b,c,d){if(a.Bb instanceof D.HS){var e=a.H.q()._contextHandler;e&&(c=e(a.Bb.sa(),a.Bb.CD(),a.oa,c,d),b=b(c),a=a.Bb,a.wz!==b&&(a.wz&&(a.wz instanceof D.sj?a.removeChild(a.wz):a.sa().removeChild(a.wz)),b instanceof D.sj?a.k(b):a.sa().appendChild(b),a.wz=b))}};D.ZS.prototype.Ki=function(){return{hovered:this.Al,selected:this.Da(),focused:this.pc()}};
D.YS=function(a,b,c,d){this.Init(a,b,c,d)};D.z.l(D.YS,D.ZS,"DvtMapAreaPeer");D.x=D.YS.prototype;D.x.Init=function(a,b,c,d){D.YS.o.Init.call(this,a,b,c,d)};D.x.jb=function(a){this.Aa()&&(a&&!this.Al&&this.en.k(this.Bb),D.YS.o.jb.call(this,a))};D.x.Ob=function(){this.en.k(this.Bb);D.YS.o.Ob.call(this)};D.x.Db=function(){this.Da()?this.en.k(this.Bb):this.en.Ma(this.Bb,0);D.YS.o.Db.call(this)};D.x.aw=function(){return this.Bb.aw()};D.x.SM=function(a){a?this.en.k(this.Bb):this.en.Ma(this.Bb,0);this.Bb.SM(a)};
D.x.ph=function(a){D.YS.o.ph.call(this,a);this.Bb.getParent()&&((0,D.LS)(this.Bb,a),this.aw()||this.D0(a))};D.x.D0=function(a){this.Nc()&&this.Nc().update(a)};D.x.Uea=function(){return(0,D.$S)(this.ti().aa)};D.x.gf=function(a,b){D.YS.o.gf.call(this,a,b);this.ti().IQ.Ft[this.zk()]=D.p};D.x.VU=(0,D.t)();
D.NS=function(a,b,c,d){this.Init(a,b,c,d)};D.z.l(D.NS,D.D,"DvtMapArea");D.x=D.NS.prototype;D.x.Init=function(a,b,c,d){D.NS.o.Init.call(this,a);this.Th=this.YE=D.p;this.aAa=c;this.G=b;this.k(this.G);this.Tf=d;if(a=b.Yb())this.hia=a.getWidth()};D.x.Jf=(0,D.v)("Ui");D.x.Fj=(0,D.ba)("Ui");D.x.Yb=function(){return this.G instanceof D.Oi?this.G.Yb():D.o};D.x.V=function(a){this.G instanceof D.Oi&&this.G.V(a)};D.x.L=function(a){this.G instanceof D.Oi&&this.G.L(a)};
D.x.Rb=function(){return this.G instanceof D.Oi?this.G.Rb():D.o};D.x.zA=function(){return this.G instanceof D.Jh?this.G.zA():D.o};D.x.Dj=function(a){this.G instanceof D.Jh&&this.G.Dj(a)};D.x.hI=function(a){this.G instanceof D.Ue&&this.G.hI(a)};D.x.iH=function(){return this.G.Vi()};D.x.contains=function(a,b){var c=this.F();return a>=c.x&&a<=c.x+c.e&&b>=c.y&&b<=c.y+c.g};D.x.ph=function(a){if(!this.Tf&&this.G&&this.hia){var b=this.G.Yb().Y();b.ma(this.hia/a.Ed);this.G.V(b)}};
D.PS=function(a,b,c){this.Init(a,b,c)};D.z.l(D.PS,D.z,"DvtMapLayer");D.x=D.PS.prototype;D.x.Init=function(a,b,c){this.aa=a;this.Ih=b;this.T1=c;this.Gj={};this.Mo=new D.hj};D.x.iga=(0,D.t)();D.x.b3=(0,D.t)();
D.x.yda=function(a,b){this.Ua&&this.Ua.stop(D.k);this.Mo=b;this.At=this.ti(a.al());this.Gj[a.al()]=a;a.P(this.Mo);a.ph(new D.WC("zoomed"),this.Mo);if(this.At){var c=a.Oq(),d=a.xa();if("auto"==c){var e=new D.Sm(this.aa.j());(0,D.Tm)(e,this.At.jk.concat(this.At.Oc),a.jk.concat(a.Oc));this.Ua=e.Oq()}else if(D.dl.isSupported(c)){this.joa=D.k;for(var f=new D.A(0,0,this.aa.getWidth(),this.aa.getHeight()),g=(0,D.dT)(this.At),e=0;e<g.length;e++){var h=new D.Te(this.aa.j(),0,0,this.aa.getWidth(),this.aa.getHeight());
h.L(D.o);g[e].k(h)}for(var j=(0,D.dT)(a),e=0;e<j.length;e++)h=new D.Te(this.aa.j(),0,0,this.aa.getWidth(),this.aa.getHeight()),h.L(D.o),j[e].k(h);f=D.dl.qD(this.aa.j(),c,g,j,f,d);g=new D.A(0,0,this.aa.getWidth()/this.Mo.Ed,this.aa.getHeight()/this.Mo.Ed);j=[this.At.en];for(e=0;e<j.length;e++)h=new D.Te(this.aa.j(),0,0,this.aa.getWidth()/this.Mo.Ed,this.aa.getHeight()/this.Mo.Ed),h.L(D.o),j[e].k(h);for(var l=[a.en],e=0;e<l.length;e++)h=new D.Te(this.aa.j(),0,0,this.aa.getWidth()/this.Mo.Ed,this.aa.getHeight()/
this.Mo.Ed),h.L(D.o),l[e].k(h);e=D.dl.qD(this.aa.j(),c,j,l,g,d);this.Ua=new D.on(this.aa.j(),[f,e])}else{c=[this.At.en,this.At.ix,this.At.$O];for(e=0;e<c.length;e++)c[e].getParent().removeChild(c[e])}this.iga();if(this.Ua){this.T1.gi(this.ra);var m=this;this.Ua.ie(function(){m.sr(a)},this);this.Ua.play()}}else this.b3(),(0,D.kT)(this.aa)};D.x.ti=function(a){return this.Gj?this.Gj[a]:D.o};D.x.P=function(a){this.Mo=a;for(var b in this.Gj)this.Gj[b].P(a)};
D.x.reset=function(a,b){for(var c in this.Gj)this.Gj[c].reset(a,b)};D.x.ph=function(a,b){this.Mo=b;for(var c in this.Gj)this.Gj[c].ph(a,b)};D.x.Ew=function(a){this.Mo=a;for(var b in this.Gj)this.Gj[b].Ew(a)};
D.x.sr=function(a){if(this.At)for(var b=[this.At.en,this.At.ix,this.At.$O],c=0;c<b.length;c++){var d=b[c].getParent();d&&d.removeChild(b[c])}if(this.joa){this.joa=D.p;b=(0,D.dT)(a);for(c=0;c<b.length;c++)b[c].us(b[c].Ja()-1);a=[a.en];for(c=0;c<a.length;c++)a[c].us(a[c].Ja()-1)}this.b3();(0,D.kT)(this.aa);this.Ua=D.o;this.T1.me(this.ra)};
D.OS=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.z.l(D.OS,D.PS,"DvtMapAreaLayer");D.x=D.OS.prototype;D.x.Init=function(a,b,c,d,e){D.OS.o.Init.call(this,a,b,e);this.Sr=c;this.Ola=d;this.kO={};this.Jo={};this.Cs={};this.tK=this.zu=D.o;this.gn=[];this.Ft={};this.Ht={};this.uY={};this.oI=new D.D(this.aa.j());this.MN=new D.D(this.aa.j());this.aa.o4.Ma(this.oI,0);this.aa.vx.Ma(this.MN,0);this.wl=new D.QS(this,this.aa.pk)};D.x.hda=(0,D.ba)("j4");D.x.Oq=(0,D.v)("j4");D.x.ow=(0,D.ba)("i4");D.x.xa=(0,D.v)("i4");
D.x.lJa=(0,D.v)("wl");D.RS=function(a,b){a.zu=b;for(var c in a.zu)a.Ft[c]=D.k,a.Ht[c]=D.k};D.OS.prototype.rra=function(a){return!this.tK?D.o:this.tK[a]};D.SS=function(a,b){return a.ul[b]?a.ul[b].split(","):[]};D.OS.prototype.m_=(0,D.v)("Sr");
D.OS.prototype.pH=function(){if(!this.vK)if(this.pK)this.vK=D.K.F(D.K.CR(D.GS.oKa(this.aa.pk,this.Ih,this.pK)));else if("world"!=this.aa.pk&&"worldRegions"!=this.aa.pk&&(this.vK=D.GS.Mqa(this.aa.pk,this.Ih)),!this.vK){var a=(0,D.Bo)(this.oI.F(),this.aa.YO.F());0<a.e&&0<a.g&&(this.vK=a)}return this.vK};
D.US=function(a,b,c){var d=a.Cs[b];if(d&&((c||!a.Jo[b])&&a.aua(b),a.Jo[b]||(c=new D.NS(a.aa.j(),d,b,a.aa.Tf),a.Jo[b]=c,a.T1.Ca(d,c),c.Fj(a.zu&&a.zu[b]?a.zu[b][1]:D.o)),a.Ht[b]&&(c=a.kO[b],!c&&("off"!=a.Sr&&a.zu)&&(c="short"==a.Ola?a.zu[b][0]:a.zu[b][1]))))a.tK&&a.tK[b]?c=new D.TS(a.aa.j(),c,a.tK[b],a.Sr,a.MN,a.aa.Tf):(d=(0,D.rg)(a.aa.j(),d),c=new D.TS(a.aa.j(),c,[[d.x,d.y,d.e,d.g]],a.Sr,a.MN,a.aa.Tf)),a.kO[b]=c,a.M7&&c.Ha(a.M7)};
D.VS=function(a,b,c){if(a.Cs[b]){a.oI.k(a.Jo[b]);var d=a.kO[b];d&&(a.Ht[b]?d.update(a.Mo):d.reset(),a.uY[b]=a.Ht[b]);c&&(c.push(a.Jo[b]),d&&(c.push(d),c.push(d.wm)))}};D.x=D.OS.prototype;
D.x.aua=function(a){if(!this.Pna||this.Aia){this.Aia=D.p;var b;this.Pna=(b="world"==this.aa.pk||"worldRegions"==this.aa.pk?D.GS.Mqa(this.aa.pk,this.Ih):this.pH())?D.GS.YNa(D.GS.Hqa(this.aa.pk,this.Ih),b.e,b.g,this.aa.getWidth(),this.aa.getHeight(),this.aa.UG?this.aa.EX:1):D.GS.Hqa(this.aa.pk,this.Ih)}b=this.Pna[a];this.Cs[a]&&b?this.Cs[a].Dj(b):delete this.Cs[a]};D.x.yda=function(a,b,c){D.OS.o.yda.call(this,a,b,c);if(c==this.Ih)for(var d in this.Cs)(0,D.US)(this,d,D.k),this.Ft[d]&&(0,D.VS)(this,d)};
D.x.P=function(a){this.Aia=D.k;for(var b in this.Cs)(0,D.US)(this,b,D.k),this.Ft[b]&&(0,D.VS)(this,b);D.OS.o.P.call(this,a)};D.x.iga=function(){for(var a in this.Ft)this.Ft[a]||((0,D.US)(this,a,D.p),(0,D.VS)(this,a))};D.x.b3=function(){for(var a in this.Ft)if(!this.Ft[a]){this.oI.removeChild(this.Jo[a]);var b=this.kO[a];b&&(this.uY[a]=D.p,this.MN.removeChild(b),(b=b.wm)&&this.MN.removeChild(b))}};
D.x.maa=function(a,b){for(var c=0;c<a.length;c++)(0,D.US)(this,a[c],D.p),this.Ft[a[c]]&&(0,D.VS)(this,a[c],b);for(var d in this.Gj)this.Gj[d].maa(a,b,this.Mo);this.gn=this.gn.concat(a)};D.x.CT=function(a,b){for(var c in this.Gj)this.Gj[c].CT(a,b);c=(0,D.WS)(this.aa,this.Ih);for(var d=0;d<a.length;d++){var e=a[d];if(this.Jo[e]){var f=D.H.wa(this.gn,e);-1!==f&&(this.gn.splice(f,1),b.push(this.Jo[e]))}c&&c.CT((0,D.SS)(this,e),b)}};
D.x.reset=function(a,b){D.OS.o.reset.call(this,a,b);"none"!=this.aa.hn&&(this.CT(this.gn,a),this.gn=[])};D.XS=function(a,b,c){for(var d in a.Jo)if(a.Jo[d].contains(b,c))return a.Jo[d];return D.o};
D.OS.prototype.Hu=function(a){this.Cf&&(this.oI.removeChild(this.Cf),this.Cf=D.o);if(a&&(this.Cf=a.iH()))this.Cf.L(new D.En(this.mP.A("background-color"))),a=this.mP.A("border-width")?this.mP.A("border-width").substring(0,this.mP.A("border-width").indexOf("px")):1,this.aa.Tf||(a/=this.Mo.Ed),a=new D.hg(this.mP.A("border-color"),1,a),this.aa.Tf&&(a.Gc=D.k),this.Cf.V(a),this.oI.k(this.Cf);return this.Cf};
D.OS.prototype.ph=function(a,b){D.OS.o.ph.call(this,a,b);if(!this.aa.Tf)for(var c in this.Jo)this.Jo[c].ph(b);for(c in this.uY)if(this.uY[c]){var d=this.kO[c];d&&d.update(b)}};
D.aT=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.z.l(D.aT,D.OS,"DvtMapCustomAreaLayer");D.aT.prototype.Init=function(a,b,c,d,e){D.aT.o.Init.call(this,a,b,c,d,e)};D.aT.prototype.aua=(0,D.t)();D.aT.prototype.pH=function(){return new D.A(0,0,this.wDa,this.vDa)};D.bT=function(a){var b=a.aa.getWidth(),c=a.aa.getHeight();a=a.$za;for(var d=0;d<a.length;d++){var e=a[d],f=e.source,g=e.width,e=e.height;if(f&&-1<f.search(".svg")||g>=b&&e>=c||d==a.length-1)return f}};
D.aT.prototype.ph=function(a,b){D.aT.o.ph.call(this,a,b);if(this.Jo.image){var c=(0,D.bT)(this);c!=this.ZW&&(this.ZW=c,this.Jo.image.hI(this.ZW))}};
D.cT=function(a,b,c,d,e){this.Init(a,b,c,d,e)};D.z.l(D.cT,D.z,"DvtMapDataLayer");D.cT.prototype.Init=function(a,b,c,d,e){this.aa=a;this.cC=c;this.ee=e;this.Oc=[];this.jk=[];this.Cja=[];this.Eja=[];this.eb=d;this.Hd=new D.ou(a.j());(0,D.Oq)(this.eb,this.Hd);this.en=new D.D(this.aa.j());this.ix=new D.D(this.aa.j());this.$O=new D.D(this.aa.j());this.aa.YO.Ma(this.en,0);this.aa.xz.Ma(this.ix,0);this.aa.vx.Ma(this.$O,0);this.IQ=b;this.gn=[];this.Uo=[]};D.cT.prototype.q=(0,D.v)("ee");
D.dT=function(a){var b=[a.$O];a.aa.Nz&&b.push(a.ix);return b};D.eT=function(a){for(var b=[],c=0;c<a.Oc.length;c++)a.Oc[c].aw()||b.push(a.Oc[c]);return b};D.fT=function(a){for(var b=[],c=0;c<a.Oc.length;c++)for(var d=0;d<a.gn.length;d++)a.Oc[c].zk()==a.gn[d]&&(a.Oc[c].aw()||b.push(a.Oc[c]));return b};D.gT=function(a,b){a.Eja.push(b);if(b){a.jk.push(b);a.eb.Ca(b.ia(),b);var c=b.Nc();c&&a.eb.Ca(c,b)}};D.hT=function(a,b){a.Cja.push(b);b&&(a.Oc.push(b),a.eb.Ca(b.ia(),b),b.en=a.en)};D.x=D.cT.prototype;
D.x.al=(0,D.v)("cC");D.x.hda=(0,D.ba)("j4");D.x.Oq=(0,D.v)("j4");D.x.ow=(0,D.ba)("i4");D.x.xa=(0,D.v)("i4");D.x.rw=function(a){if(this.Gq=a)this.Hb=new D.$k(this.Gq),this.eb.yu(this.cC,this.Hb)};D.x.Aa=function(){return this.Gq!=D.o};D.iT=function(a,b){var c;c=a.Oc[b];var d=c.ia(),e=a.IQ.Cs[c.zk()];e?(d.Dj(e.zA()),c=D.k):(c=a.Oc.indexOf(c),-1!==c&&a.Oc.splice(c,1),c=D.p);if(c){d=a.Oc[b].ia();a.en.k(d);if(c=a.Oc[b].Nc())0<c.Zw.length||(d=d.F(),c.Zw.push(d)),c.update(a.ZK);return D.k}return D.p};
D.x=D.cT.prototype;D.x.P=function(a){this.pia=D.k;this.ZK=a;a={};var b=this.jk.slice();b.sort(function(a,b){return a.Tc()<b.Tc()?1:a.Tc()>b.Tc()?-1:0});for(var c=0;c<b.length;c++){var d=b[c],e=d.ia(),f=d.Nc();if(f){var g=new D.D(e.j());this.ix.k(g);g.k(e);g.k(f);d.D0()}else this.ix.k(e);(d=d.zk())&&(a[d]=D.k)}for(c=0;c<this.Oc.length;c++)a[this.Oc[c].zk()]&&(this.Oc[c].Cb=D.o),(0,D.iT)(this,c)||c--;this.h7&&this.cA()};
D.x.maa=function(a,b,c){this.ZK=c;for(var d=[],e=0;e<a.length;e++)for(var f=0;f<this.Oc.length;f++)if(this.Oc[f].zk()==a[e]){d.push(this.Oc[f].zk());(0,D.iT)(this,f);var g=this.Oc[f].ia();b.push(g);(0,D.LS)(g,c);if(f=this.Oc[f].Nc())b.push(f),(f=f.wm)&&b.push(f);break}for(f=0;f<this.jk.length;f++)for(e=0;e<a.length;e++)c=this.jk[f].zk(),g=this.jk[f].ia(),c!=D.o?c==a[e]&&(this.ix.k(g),b.push(g)):(this.ix.k(g),b.push(g));this.gn=this.gn.concat(d)};
D.x.CT=function(a,b){for(var c=0;c<a.length;c++)for(var d=0;d<this.Oc.length;d++)if(this.Oc[d].zk()==a[c]){this.Oc[d].aw()&&this.Oc[d].SM(D.p);this.Oc[d].Da()&&this.Hb.eT(this.Oc[d]);var e=D.H.wa(this.gn,a[c]);if(-1<e&&(this.gn.splice(e,1),b.push(this.Oc[d].ia()),d=this.Oc[d].Nc()))b.push(d),b.push(d.wm);break}};
D.x.reset=function(a,b){if(this.Hb)for(var c=this.Hb.getSelection(),d=0;d<c.length;d++)(!b||b&&-1==D.H.wa(b,c[d].zk()))&&this.Hb.eT(c[d]);if("none"!=this.aa.hn)for(c=0;c<this.Uo.length;c++){for(d=0;d<this.Oc.length;d++)if(this.Oc[d].zk()==this.Uo[c]){this.Oc[d].SM(D.p);var e=this.Oc[d].ia();this.en.k(e);a.push(e);if(d=this.Oc[d].Nc())d.update(this.ZK),a.push(d),a.push(d.wm);break}for(d=0;d<this.jk.length;d++)if(this.jk[d].zk()==this.Uo[c]){e=this.jk[d].ia();this.ix.k(e);a.push(e);break}}this.Uo=[]};
D.x.ph=function(a,b){this.ZK=b;var c=b.Ed,d=a.xj();if(this.pia&&"zoomed"==d){this.pia=D.p;for(d=0;d<this.Oc.length;d++){var e=this.Oc[d].ia(),f=e.SEa;if(f){var g=new D.eh;f.He(g);g.za(new D.hj(1/c,D.o,D.o,1/c));e.L(g)}}}d=this.Oc;for(c=0;c<d.length;c++)d[c].ph(b);if(this.aa.Nz){d=this.jk;for(c=0;c<d.length;c++)d[c].ph(b)}};D.x.Ew=(0,D.ba)("ZK");D.x.cA=function(){this.Hb&&((0,D.Il)(this.Hb,this.h7,this.jk.concat(this.Oc)),this.h7=D.o)};
D.x.RB=function(a){if(this.Hb){a.Da()||(this.Hb.Nm(a,D.p),this.eb.Nv(a));a=[];for(var b=this.Hb.getSelection(),c=0;c<b.length;c++)a.push(b[c].getId());return a}return D.o};D.x.QB=function(){for(var a=[],b=this.Hb.getSelection(),c=0;c<b.length;c++)a.push(b[c].ia());return a};
D.rT=function(a,b){this.Init(a,b)};D.z.l(D.rT,D.Mp,"DvtThematicMapKeyboardHandler");D.x=D.rT.prototype;D.x.Init=function(a,b){D.rT.o.Init.call(this,a,b);this.aa=a};D.x.qy=function(a){return this.tg(a)&&!a.ctrlKey};
D.x.Fh=function(a){var b=a.keyCode;if(221==b){var b=this.ea.dd(),c=(0,D.mT)(this.aa);b instanceof D.YS&&0<c.length&&(b=(0,D.Jm)(b,a,c));(0,D.QT)(this.ea,b)}else 219==b?(b=this.ea.dd(),c=(0,D.$S)(this.aa),!(b instanceof D.YS)&&0<c.length&&(b=(0,D.Jm)(b,a,c)),(0,D.QT)(this.ea,b)):(b=D.rT.o.Fh.call(this,a),this.tg(a)&&!a.ctrlKey&&(0,D.QT)(this.ea,b));return b};D.x.ar=function(a){return 32==a.keyCode&&a.ctrlKey};
D.x.tg=function(a){var b=D.rT.o.tg.call(this,a);if(!b&&(a=a.keyCode,219==a||221==a))b=D.k;return b};
D.qT=function(a,b,c){this.Init(a,b,c)};D.z.l(D.qT,D.Pj,"DvtThematicMapEventManager");D.x=D.qT.prototype;D.x.Init=function(a,b,c){D.qT.o.Init.call(this,a,b,c);this.jA={};this.aa=c;this.Ww=D.p};D.x.mh=function(a){if(a&&a.ti)return this.jA[a.ti().al()]};D.x.yu=function(a,b){this.jA[a]=b};D.x.nda=(0,D.ba)("hn");D.x.eT=function(a,b){var c=this.jA[a];c&&c.eT(b)};D.x.SL=function(a){(a=this.jA[a])&&a.SL()};
D.x.Oy=function(a){var b=(0,D.Ej)(this,a.target);b&&(b.rd&&b.ti)&&(this.aa.SJ=b.ti().al());D.qT.o.Oy.call(this,a)};D.x.Sm=function(a){this.aa.SJ=D.o;D.qT.o.Sm.call(this,a)};D.x.Jh=function(a){var b=(0,D.Ej)(this,a.target);(0,D.QT)(this,b);if(!b||!b.Aa||!b.Aa())for(var c in this.jA)if(this.jA[c].Nm(D.o,a.ctrlKey)){var d=new D.Km([]);(0,D.El)(d,"clientId",c);this.lb.call(this.ra,d)}D.qT.o.Jh.call(this,a);this.QW(b,a.pageX,a.pageY)};
D.x.QW=function(a,b,c){if(a instanceof D.ZS){var d=a.yD();d?d.call():a.Ce()!=D.o?(0,D.RT)(this,a,b,c):a.rd()&&(this.aa.SJ=a.ti().al())}};D.RT=function(a,b,c,d){var e=new D.MS(b.al(),b.getId(),b.Ce());(0,D.El)(e,"clientId",b.ti().al());c!=D.o&&d!=D.o&&(b=(0,D.Pu)(a.aa.j(),c,d),(0,D.El)(e,"pointXY",{x:b.x,y:b.y}));a.Cc();a.lb.call(a.ra,e)};
D.QT=function(a,b){var c=D.o,d=D.o,e=D.o;b&&(b instanceof D.ZS?e=b.ia():b instanceof D.NS&&(e=b),b.ti&&(d=b.ti(),c=d.al(),d=d.IQ.Ih));var f=a.aa;f.nm=d;f.bx=c;f.RV=e};D.x=D.qT.prototype;D.x.Ny=function(a){a=(0,D.Ej)(this,a.target);this.mh(a)&&(this.hn&&"none"!=this.hn)&&(a=new D.jT(D.jT.L1),this.lb.call(this.ra,a))};
D.x.Kh=function(a){var b=D.k,c=a.keyCode,d=this.dd(),e=d.ia();9!=c&&this.Ww?(e.VL(a),a.preventDefault()):(48==c||96==c)&&a.ctrlKey&&a.shiftKey?(this.aa.ada(),a.preventDefault()):220==c?((d=this.aa.Vc)&&(d instanceof D.Ku?(0,D.Lu)(d,!d.isCollapsed()):d instanceof D.ur&&d.yf(!d.Qa())),a.preventDefault()):13==c?d instanceof D.ZS&&((e=d.yD())?e.call():d.Ce()!=D.o?(0,D.RT)(this,d):a.shiftKey?this.aa.naa():this.aa.NZ(),a.preventDefault()):32==c&&a.ctrlKey?((0,D.QT)(this,d),(0,D.dz)(this,d,D.k),a.preventDefault()):
(48==c||96==c)&&a.ctrlKey?(a.altKey?(d=this.aa,e||(e=d.Kpa),e||(e=d.RV),d.TG(e.F())):(0,D.zT)(this.aa),a.preventDefault()):9==c&&e instanceof D.HS?!a.shiftKey&&d.pc()?(d.jc(),e.VL(a),a.preventDefault(),this.Ww=D.k):(a.shiftKey&&this.Ww?(this.SI(a,d),a.preventDefault()):(this.Ww&&d.Vd(),b=D.qT.o.Kh.call(this,a)),this.Ww=D.p):b=D.qT.o.Kh.call(this,a);return b};
D.x.AB=function(a){if(!(0,D.yq)(this,a,"panned")){var b=(0,D.Ej)(this,a.target);(0,D.QT)(this,b);if(b instanceof D.DS)for(var c in this.jA)if(this.jA[c].Nm(D.o,a.ctrlKey)){for(var d=this.jA[c].getSelection(),e=[],f=0;f<d.length;f++)e.push(d[f].getId());d=new D.Km(e);this.lb.call(this.ra,d)}D.qT.o.AB.call(this,a);this.QW(b,a.Ho.pageX,a.Ho.pageY)}};D.x.v2=function(a){a=(0,D.Ej)(this,a.target);this.aa.SJ=a&&a.rd&&a.ti?a.ti().al():D.o};
D.x.zfa=function(a){a=(0,D.Ej)(this,a.target);this.aa.SJ=a&&a.rd&&a.ti?a.ti().al():D.o};D.x.wB=function(a){var b=(0,D.Ej)(this,a.target);b&&(this.mh(b)&&this.hn&&"none"!=this.hn)&&((0,D.dz)(this,b,a.ctrlKey),a=new D.jT(D.jT.L1),this.lb.call(this.ra,a))};D.x.iU=function(a,b){var c=(0,D.Ej)(this,a.target);(0,D.QT)(this,c);D.qT.o.iU.call(this,a,b)};
D.x.fm=function(a,b,c){a=this.aa.q();"dim"==a.hoverBehavior&&(b=b.Mc?b.Mc():[],a.highlightedCategories=c?b.slice():D.o,c=new D.zm(c?"categoryRollOver":"categoryRollOut",a.highlightedCategories),b=(0,D.hp)(a.styleDefaults.hoverBehaviorDelay),this.GB.Pd(c,(0,D.$S)(this.aa).concat((0,D.mT)(this.aa)),b,"any"==a.highlightMatch))};D.x.Bu=function(){var a=this.aa.q();return"none"!==a.panning||"none"!==a.zooming?"touchHold":"touchStart"===a.touchResponse?"touchStart":"auto"};
D.x.Jw=function(a){return"panned"==a?D.p:D.qT.o.Jw.call(this,a)};
D.oT=function(a){this.Init(a)};D.z.l(D.oT,D.z,"DvtThematicMapJsonParser");D.oT.prototype.Init=function(a){this.aa=a;this.iX=D.p;this.SE=D.o;this.nDa=(0,D.Jf)();this.zja={};this.Aja={}};
D.oT.prototype.parse=function(a){var b=a.animationDuration;"string"==typeof b?"ms"==b.slice(-2)?b=(0,window.parseInt)(b.slice(0,-2))/1E3:"s"==b.slice(-1)&&(b=(0,window.parseFloat)(b.slice(0,-1))):b/=1E3;this.aa.ow(b);this.aa.dia="auto"==a.animationOnDisplay?"alphaFade":a.animationOnDisplay;this.aa.Rza="auto"==a.animationOnMapChange?"alphaFade":a.animationOnMapChange;this.iX=a.source!=D.o;var b=this.aa,c=this.iX?"$"+a.basemap:a.basemap;b.s4=b.pk&&b.pk!=c;b.pk=c;this.aa.Y0(a.featuresOff);this.aa.TO=
a.controlPanelBehavior;b=a.tooltipDisplay;"shortDesc"==b?b="shortDescOnly":"labelAndShortDesc"==b&&(b="auto");this.aa.Nja=b;(b=a.popups)&&this.aa.aN(this.tm(b));this.aa.nda(a.drilling);this.aa.l4=a.animationOnDrill;this.aa.n7="auto"==a.initialZooming;this.aa.Nz="fixed"==a.markerZoomBehavior;this.aa.UK="auto"==a.panning;this.aa.UG="auto"==a.zooming;this.aa.sla=a.panX;this.aa.tla=a.panY;this.aa.m7=a.zoom;(0,window.isNaN)(a.maxZoom)||(b=window.Math.max(a.maxZoom,1),this.aa.EX=b);a._legend&&(this.aa.xx=
a._legend);b=a.styleDefaults;(0,D.nq)(this.aa,b);this.SE=new D.G(b.areaStyle);(0,D.Uf)(this.SE,b.labelStyle);this.Zza=new D.G(b.dropTargetStyle);this.aa.aZ=b;if(this.iX&&a.sourceXml)for(var b=(new D.lj).parse(a.sourceXml).zc(),d,e,c=0;c<b.length;c++)if(d=b[c],e=d.getName(),"layer"==e){e=d;d=e.zc();e=e.v("id");for(var f=D.i,g=D.i,h=[],j=0;j<d.length;j++)if(f=d[j],g=f.getName(),"image"==g){g={};g.source=f.v("source");g.width=f.v("width");g.height=f.v("height");var l=f.v("bidi"),f=f.v("dir");g.dir="true"==
l||"rtl"==f?"rtl":"ltr";h.push(g)}this.zja[e]=h}else if("points"==e){d=d.zc();h=e=D.i;j={};f={};for(g=0;g<d.length;g++)e=d[g],h=e.getName(),"point"==h&&(j[e.v("name")]=[e.v("x"),e.v("y")],f[e.v("name")]=[D.o,e.v("longLabel")]);D.GS.Tca(this.aa.pk,"cities",f,j,D.o,D.o,1)}b=a.areaLayers;c=this.aa.pk;for(d=0;d<b.length;d++)if(e=D.pl.bd(b[d],D.OT),j=e.layer){e.areaStyle&&(0,D.Uf)(this.SE,e.areaStyle);e.labelStyle&&(0,D.Uf)(this.SE,e.labelStyle);if(this.iX){f=h=new D.aT(this.aa,j,e.labelDisplay,e.labelType,
this.aa.ka());j=this.zja[j];l=D.o;g=(0,D.E)(f.aa.j());if(j&&0<j.length){var l=j[0].width,m=j[0].height;f.wDa=l;f.vDa=m;for(var n=[],q=0;q<j.length;q++)g&&"rtl"==j[q].dir?n.push(j[q]):!g&&"ltr"==j[q].dir&&n.push(j[q]);f.$za=0<n.length?n:j;f.ZW=(0,D.bT)(f);l=new D.Ue(f.aa.j(),f.ZW,0,0,l,m)}l&&((0,D.RS)(f,{image:[D.o,D.o]}),f.Cs={image:l})}else{h=new D.OS(this.aa,j,e.labelDisplay,e.labelType,this.aa.ka());f=D.GS.wIa(c,j);g=h;q=f;l={};m=this.aa.j();n=D.i;for(n in q){l[n]=new D.Jh(m);if((q=this.SE.A("border-color"))&&
"transparent"!=q)q=new D.hg(q),this.aa.Tf&&(q.Gc=D.k),l[n].V(q);q=this.SE.A("background-color");"transparent"!=q?l[n].pa(q):l[n].L(D.o)}g.Cs=l;(0,D.RS)(h,f);f=D.GS.vIa(c,j);h.tK=f;j=D.GS.JIa(this.aa.pk,j);h.ul=j}h.M7=this.SE;h.mP=this.Zza;h.hda("auto"==e.animationOnLayerChange?"alphaFade":e.animationOnLayerChange);h.ow(this.aa.xa());this.aa.Df.push(h);e.areaDataLayer&&(0,D.vT)(this,[e.areaDataLayer],h,D.o,D.k);e.pointDataLayers&&(0,D.vT)(this,e.pointDataLayers,h,D.o,D.p)}(0,D.vT)(this,a.pointDataLayers,
D.o,D.o,D.p)};
D.vT=function(a,b,c,d,e){if(b)for(var f=0;f<b.length;f++){var g=D.pl.bd(b[f],D.PT);if(g.markerDefs){var h=g.markerDefs,j;for(j in h)if(!a.Aja[j]){var l=(new D.lj).parse(h[j]);a.Aja[j]=D.EE.CHa(a.aa.j(),l)}}g.legend&&(a.aa.xx=g.legend);if(c){if(c instanceof D.OS&&e)for(h in e=c,h=D.i,e.zu)e.Ft[h]=D.k,e.Ht[h]=D.k}else c=new D.PS(a.aa,g.id,a.aa.ka()),a.aa.Df.push(c);h=new D.cT(a.aa,c,g.id,a.aa.ka(),g);e=g.selectionMode;"single"==e?h.rw("s"):"multiple"==e&&h.rw("m");h.hda(g.animationOnDataChange);h.ow(a.aa.xa());
var m=D.o;c instanceof D.OS&&(m=g.isolatedItem);var n=g.disclosedItems,l=[],q;e=c instanceof D.OS;var r;g.popups&&(r=a.tm(g.popups));var s=a.aa.q().hiddenCategories,u=g.areas;if(u)for(var w=0;w<u.length;w++)if(s&&D.H.hu(s,u[w].categories))(0,D.hT)(h,D.o);else{var y=u[w].location;if(m)if(m!=u[w].id)continue;else q=y;n&&-1!=D.H.wa(n,u[w].id)&&l.push(y);var C=a,O=c,M=h,y=u[w],J=y.location;if(O.Cs[J]&&y.color){O.Ft[J]=D.p;J=new D.IS(C.aa.j(),C.aa.Tf);y=D.pl.bd(y,C.aa.aZ.dataAreaDefaults);y.labelStyle||
(y.labelStyle=C.aa.aZ.labelStyle);var R=new D.hg(y.hoverColor,1,2),N=new D.hg(y.selectedInnerColor,1,1),Y=new D.hg(y.selectedOuterColor,1,4);J.Pp(R,D.o).Rp(N,Y);R=new D.hg(y.drilledInnerColor,1,2);Y=new D.hg(y.drilledOuterColor,1,4);N=J;N.pW=R;N.pW&&N.Tf&&(N.pW.Gc=D.k);N.qW=Y;N.qW&&N.Tf&&(N.qW.Gc=D.k);O.Ht[y.location]=D.p;(0,D.ST)(C,y,J);C=C.hF(O,M,y,J,D.k);y=new D.YS(y,M,J,C)}else y=D.o;r&&y.aN(r);y&&(y.Lf(h.Aa()),(0,D.hT)(h,y))}u=g.renderer;if((M=g.markers)&&!u)for(w=0;w<M.length;w++)if(s&&D.H.hu(s,
M[w].categories))(0,D.gT)(h,D.o);else{y=M[w].location;if(m)if(m!=M[w].id)continue;else q=y;y=a.gW(c,h,M[w],e);r&&y.aN(r);y&&(y.Lf(h.Aa()),(0,D.gT)(h,y))}if(s=g.images)for(w=0;w<s.length;w++){y=s[w].location;if(m)if(m!=s[w].id)continue;else q=y;y=a.w5(c,h,s[w],e);r&&y.aN(r);y&&(0,D.gT)(h,y)}if(u)for(w=0;w<M.length;w++){y=M[w].location;if(m)if(m!=M[w].id)continue;else q=y;n&&-1!=D.H.wa(n,M[w].id)&&l.push(y);s=a.aa.q()._contextHandler(a.aa.sa(),D.o,M[w],{hovered:D.p,selected:D.p,focused:D.p},D.o);J=
u(s);C=a;O=c;s=h;y=M[w];R=J;N=e;(J=(0,D.TT)(s,y))?(N&&(O.Ht[y.location]=D.p),C=new D.HS(C.aa.j(),R,C.aa.aZ.dataAreaDefaults),y=new D.ZS(y,s,C,D.o,J)):y=D.o;r&&y.aN(r);y&&(y.Lf(h.Aa()),(0,D.gT)(h,y))}if(q)for(w in h.KPa=m,m=c,n=q,m.pK=n,m.vK=D.o,w=D.i,m.Cs)w!=n&&(m.Ft[w]=D.p);if((g=g.selection)&&0<g.length)h.h7=g;l&&0<l.length&&(a.aa.HP[c.Ih]=[h.al(),l]);d?c.yda(h,a.aa.da.ba.ta(),d):c.Gj[h.al()]=h}};
D.oT.prototype.gW=function(a,b,c,d){var e=(0,D.TT)(b,c);if(!e)return D.o;var f=this.aa.aZ.dataMarkerDefaults,g=new D.G(f.labelStyle);(0,D.Uf)(g,c.labelStyle);c=D.pl.bd(c,f);c.labelStyle=g.toString();f=1;(0,window.isNaN)(c.scaleX)||(f=c.scaleX);g=1;(0,window.isNaN)(c.scaleY)||(g=c.scaleY);var h=c.width,j=c.height;if(!h||(0,window.isNaN)(h))h=this.aa.q().styleDefaults.dataMarkerDefaults.width;if(!j||(0,window.isNaN)(j))j=this.aa.q().styleDefaults.dataMarkerDefaults.height;if(c.source)f=new D.ch(this.aa.j(),
e.x,e.y,h*f,j*g,c.source,c.sourceSelected,c.sourceHover,c.sourceHoverSelected);else var l=c.shape?c.shape:this.aa.q().styleDefaults.dataMarkerDefaults.shape,f=new D.dh(this.aa.j(),l,this.aa.nc,e.x,e.y,h*f,j*g);(g=c.rotation)&&f.$j(g*window.Math.PI/180);d&&(a.Ht[c.location]=D.p);(0,D.ST)(this,c,f);a=this.hF(a,b,c,f,d);return new D.ZS(c,b,f,a,e)};
D.oT.prototype.w5=function(a,b,c,d){var e=(0,D.TT)(b,c);if(!e)return D.o;var f=new D.Ue(this.aa.j(),c.url),g=c.width,h=c.height;g!=D.o&&h!=D.o&&(f.ca(e.x-g/2),f.va(e.y-h/2),f.ma(g),f.Ea(h));d&&(a.Ht[c.location]=D.p);var j=new D.ZS(c,b,f,D.o,e);(!g||!h)&&D.Ge.Gn(this.aa.j(),c.url,function(a){a&&(a.width&&a.height)&&(f.ma(a.width),f.Ea(a.height),f.ca(e.x-a.width/2),f.va(e.y-a.height/2),j.VU())});return j};
D.oT.prototype.hF=function(a,b,c,d,e){var f=c.location,g=c.label,h=g?"on":"off";e&&(h=a.m_());d=d instanceof D.Jh;if(!g&&e&&(d&&"off"!=h||!d&&"on"==h))g="long"==a.Ola?a.zu[f][1]:a.zu[f][0];if(g){var j=this.aa.j(),j=d?new D.TS(j,g,a.rra?a.rra(f):D.o,h,b.$O,this.aa.Tf):new D.Kf(j,g,0,0);b=new D.G;d&&b.bd(new D.G(a.M7));c.labelStyle&&(0,D.Uf)(b,c.labelStyle);a=b.A("color");b.W("color",D.o);j.Ha(b);if(j instanceof D.TS&&(D.Io===D.k||!a))a=D.I.tj(c.color);a&&j.pa(a)}return j};
D.ST=function(a,b,c){var d=b.pattern,e=b.color,f=a.nDa||"alta"==a.aa.nc?"none":b.visualEffects;if(c instanceof D.dh){if("none"!=b.borderStyle){var g=b.borderWidth;"string"==typeof g&&(g="px"==g.slice(-2)?(0,window.parseFloat)(b.borderWidth.slice(0,-2)):(0,window.parseFloat)(b.borderWidth));var h=new D.hg(b.borderColor,1,g);a.aa.Nz||(h.Gc=D.k);h.Gk((0,D.ig)(b.borderStyle));c.V(h)}g=b.opacity;"none"!=f?c.L(new D.fh.mqa(e,c,g)):d?c.L(new D.eh(d,e,"#FFFFFF")):e&&c.pa(e,g)}else if(c instanceof D.Jh){if(b=
b.borderColor)h=new D.hg(b),a.aa.Tf&&(h.Gc=D.k),c.V(h);d?(a=new D.eh(d,e,"#FFFFFF"),c.SEa=a):c.pa(e,g)}};D.TT=function(a,b){var c=a.aa,d=c.pk,e=b.location;return e?((c=D.GS.tIa(d,a.IQ.Ih,e))||(c=D.GS.KIa(d,e)),c):D.Z.mNa(b.x,b.y,c.pk)};D.oT.prototype.tm=function(a){for(var b=[],c=0;c<a.length;c++)b.push(new D.Gi(a[c].popupId,a[c].triggerType,D.o,a[c].align));return b};
D.Z={};D.z.l(D.Z,D.z,"DvtThematicMapProjections");D.Z.Qw=new D.A(0,0,800,500);D.Z.RU=6378206.4;D.Z.M3=new D.A(500,200,200,200);D.Z.L3=new D.A(163,-49,17,17);D.Z.Yga=new D.A(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);D.Z.aha=new D.A(-0.8436866097568272,-0.7626456732012923,1.8336308036296942,1.5748427214611724);D.Z.bha=new D.A(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);
D.Z.nha=new D.A(-0.47944476148667076,-0.0014669405958800579,0.7364925893845453,0.6293972741802124);D.Z.Cha=new D.A(-0.6154469465354344,-0.24589767758847714,1.2448236795108683,1.2631535127174947);D.Z.Iha=new D.A(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);D.Z.$ga=new D.A(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);D.Z.mha=new D.A(-24.543831069368586,-37.202500659225905,204.54283106936856,164.9634493690208);
D.Z.Aha=new D.A(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);D.Z.Kha=new D.A(-0.6154656300926513,0.0507209798775865,1.0153104799231851,0.966537441082997);D.Z.Mha=new D.A(-171.9,-62.6,349.8,150.8);D.Z.Mwa=new D.A(172,51,8,3);D.Z.Nwa=new D.A(-180,51,51,21);D.Z.Xxa=new D.A(-178.5,18.9,35,11);D.Z.Vya=new D.A(-124.8,24.4,58,25.5);D.Z.Zga=new D.A(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);
D.Z.uha=new D.A(-160.23606872558594,18.91549301147461,5.4374847412109375,3.3189010620117188);D.Z.Jha=new D.A(-2386803.25,-1183550.5,4514111,2908402);D.Z.K3=new D.A(165,400,100,100);D.Z.H3=new D.A(-75,350,240,150);D.Z.Tn=[[1,0],[0.9986,0.0314],[0.9954,0.0629],[0.99,0.0943],[0.9822,0.1258],[0.973,0.1572],[0.96,0.1887],[0.9427,0.2201],[0.9216,0.2515],[0.8962,0.2826],[0.8679,0.3132],[0.835,0.3433],[0.7986,0.3726],[0.7597,0.4008],[0.6732,0.4532],[0.6213,0.4765],[0.5722,0.4951],[0.5322,0.5072]];
D.Z.mNa=function(a,b,c){var d;switch(c){case "africa":d=D.Z.Gz(D.Z.Yga,D.Z.yP(a,b));break;case "asia":d=D.Z.Gz(D.Z.aha,D.Z.FW(40,95,20,60,a,b),D.Z.aj(5));break;case "australia":d=D.Z.UBa(a,b);break;case "europe":d=D.Z.Gz(D.Z.nha,D.Z.FW(35,25,40,65,a,b),D.Z.aj(10));break;case "northAmerica":d=D.Z.Gz(D.Z.Cha,D.Z.FW(23,-96,20,60,a,b));break;case "southAmerica":d=D.Z.Gz(D.Z.Iha,new D.F(a,b),D.Z.aj(5));break;case "apac":d=D.Z.Gz(D.Z.$ga,D.Z.yP(a,b));break;case "emea":d=D.Z.Gz(D.Z.mha,D.Z.yP(a,b));break;
case "latinAmerica":d=D.Z.Gz(D.Z.Aha,new D.F(a,b));break;case "usaAndCanada":d=D.Z.Gz(D.Z.Kha,D.Z.FW(23,-96,20,60,a,b));break;case "worldRegions":d=D.Z.Zka(a,b);break;case "usa":d=D.Z.ACa(a,b);break;case "world":d=D.Z.Zka(a,b)}return d?new D.F(10*d.x,10*d.y):D.o};
D.Z.ACa=function(a,b){var c;(0,D.vm)(D.Z.Mwa,a,b)||(0,D.vm)(D.Z.Nwa,a,b)?(c=D.Z.rq(D.Z.Zga,D.Z.H3),c=D.Z.hO(c,D.Z.yP(a,b))):(0,D.vm)(D.Z.Xxa,a,b)?(c=D.Z.rq(D.Z.uha,D.Z.K3),c=D.Z.hO(c,new D.F(a,b))):(0,D.vm)(D.Z.Vya,a,b)&&(c=D.Z.rq(D.Z.Jha,D.Z.Qw),c=D.Z.hO(c,D.Z.rCa(new D.F(-95,36),a,b)));return D.Z.GW(c)};D.Z.Zka=function(a,b){var c=D.Z.rq(D.Z.Mha,D.Z.Qw),c=D.Z.hO(c,D.Z.vCa(a,b));return D.Z.GW(c)};
D.Z.UBa=function(a,b){var c;c=(0,D.vm)(D.Z.L3,a,b)?D.Z.rq(D.Z.L3,D.Z.M3):D.Z.rq(D.Z.bha,D.Z.Qw);c=D.Z.hO(c,D.Z.yP(a,b));return D.Z.GW(c)};D.Z.Gz=function(a,b,c){a=D.Z.rq(a,D.Z.Qw);if(c){var d=new D.hj;d.rotate(c);a=D.Z.fja(a,d)}b=(0,D.Ip)(a,b);return D.Z.GW(b)};D.Z.GW=function(a){var b=D.Z.Qw;return!a||!(0,D.vm)(b,a.x,a.y)?D.o:a};
D.Z.FW=function(a,b,c,d,e,f){b=D.Z.aj(b);a=D.Z.aj(a);c=D.Z.aj(c);d=D.Z.aj(d);d=0.5*(window.Math.sin(c)+window.Math.sin(d));c=window.Math.pow(window.Math.cos(c),2)+2*d*window.Math.sin(c);a=c-2*d*window.Math.sin(a);a=window.Math.sqrt(a)/d;e=d*(D.Z.aj(e)-b);f=c-2*d*window.Math.sin(D.Z.aj(f));f=window.Math.sqrt(f)/d;return new D.F(f*window.Math.sin(e),a-f*window.Math.cos(e))};D.Z.yP=function(a,b){var c=window.Math.log(window.Math.tan(0.25*window.Math.PI+0.5*D.Z.aj(b)));return new D.F(a,D.Z.fN(c))};
D.Z.rCa=function(a,b,c){b=D.Z.aj(b);c=D.Z.aj(c);var d=D.Z.aj(a.x);a=D.Z.aj(a.y);return new D.F(window.Math.cos(c)*window.Math.sin(b-d)*D.Z.RU,(window.Math.cos(a)*window.Math.sin(c)-window.Math.sin(a)*window.Math.cos(c)*window.Math.cos(b-d))*D.Z.RU)};
D.Z.vCa=function(a,b){var c=window.Math.floor(window.Math.abs(b)/5);c>=D.Z.Tn.length-1&&(c=D.Z.Tn.length-2);var d=(window.Math.abs(b)-5*c)/5,e=a*(D.Z.Tn[c][0]+d*(D.Z.Tn[c+1][0]-D.Z.Tn[c][0])),c=D.Z.Tn[c][1]+d*(D.Z.Tn[c+1][1]-D.Z.Tn[c][1]);0>b&&(c*=-1);return new D.F(e,180*c)};D.Z.hO=function(a,b){return new D.F(b.x*a.Ed+a.qc,b.y*a.ig+a.oc)};D.Z.fja=function(a,b){var c=a.Ed,d=a.ig;return new D.hj(b.Ed*c,b.Oh*c,b.ah*d,b.ig*d,a.qc+b.qc*c,a.oc+b.oc*d)};
D.Z.rq=function(a,b){var c=b.x,d=b.y,e=a.e,f=a.g,g=0,g=b.e/e,h=b.g/f,g=g<=h?g:h,c=c-a.x*g,d=d+a.y*g,c=c+(b.e-e*g)/2,d=d+(b.g-(b.g-f*g)/2);return new D.hj(g,0,0,-g,c,d)};D.Z.aj=function(a){return a*(window.Math.PI/180)};D.Z.fN=function(a){return a*(180/window.Math.PI)};
D.Z.bMa=function(a,b,c){var d;a/=10;b/=10;switch(c){case "africa":d=D.Z.Hz(D.Z.Yga,new D.F(a,b));d=D.Z.wP(d.x,d.y);break;case "asia":d=D.Z.Hz(D.Z.aha,new D.F(a,b),D.Z.aj(5));d=D.Z.KW(40,95,20,60,d.x,d.y);break;case "australia":d=D.Z.gCa(a,b);break;case "europe":d=D.Z.Hz(D.Z.nha,new D.F(a,b),D.Z.aj(10));d=D.Z.KW(35,25,40,65,d.x,d.y);break;case "northAmerica":d=D.Z.Hz(D.Z.Cha,new D.F(a,b));d=D.Z.KW(23,-96,20,60,d.x,d.y);break;case "southAmerica":d=D.Z.Hz(D.Z.Iha,new D.F(a,b),D.Z.aj(5));break;case "apac":d=
D.Z.Hz(D.Z.$ga,new D.F(a,b));d=D.Z.wP(d.x,d.y);break;case "emea":d=D.Z.Hz(D.Z.mha,new D.F(a,b));d=D.Z.wP(d.x,d.y);break;case "latinAmerica":d=D.Z.Hz(D.Z.Aha,new D.F(a,b));break;case "usaAndCanada":d=D.Z.Hz(D.Z.Kha,new D.F(a,b));d=D.Z.KW(23,-96,20,60,d.x,d.y);break;case "worldRegions":d=D.Z.Eka(a,b);break;case "usa":d=D.Z.jCa(a,b);break;case "world":d=D.Z.Eka(a,b)}return d?d:new D.F(a,b)};
D.Z.jCa=function(a,b){var c;return(0,D.vm)(D.Z.H3,a,b)?(c=D.Z.rq(D.Z.Zga,D.Z.H3),c.ky(),c=(0,D.Ip)(c,new D.F(a,b)),D.Z.wP(c.x,c.y)):(0,D.vm)(D.Z.K3,a,b)?(c=D.Z.rq(D.Z.uha,D.Z.K3),c.ky(),(0,D.Ip)(c,new D.F(a,b))):(0,D.vm)(D.Z.Qw,a,b)?(c=D.Z.rq(D.Z.Jha,D.Z.Qw),c.ky(),c=(0,D.Ip)(c,new D.F(a,b)),D.Z.hCa(new D.F(-95,36),c.x,c.y)):new D.F(a,b)};D.Z.Eka=function(a,b){var c=D.Z.rq(D.Z.Mha,D.Z.Qw);c.ky();c=(0,D.Ip)(c,new D.F(a,b));return D.Z.iCa(c.x,c.y)};
D.Z.gCa=function(a,b){var c;c=(0,D.vm)(D.Z.M3,a,b)?D.Z.rq(D.Z.L3,D.Z.M3):D.Z.rq(D.Z.bha,D.Z.Qw);c.ky();c=(0,D.Ip)(c,new D.F(a,b));return D.Z.wP(c.x,c.y)};D.Z.Hz=function(a,b,c){a=D.Z.rq(a,D.Z.Qw);if(c){var d=new D.hj;d.rotate(c);a=D.Z.fja(a,d)}a.ky();return(0,D.Ip)(a,b)};
D.Z.KW=function(a,b,c,d,e,f){b=D.Z.aj(b);a=D.Z.aj(a);c=D.Z.aj(c);d=D.Z.aj(d);d=0.5*(window.Math.sin(c)+window.Math.sin(d));c=window.Math.pow(window.Math.cos(c),2)+2*d*window.Math.sin(c);a=c-2*d*window.Math.sin(a);a=window.Math.sqrt(a)/d;var g=window.Math.sqrt(e*e+(a-f)*(a-f));return new D.F(D.Z.fN(b+window.Math.atan(e/(a-f))/d),D.Z.fN(window.Math.asin((c-g*g*d*d)/(2*d))))};D.Z.wP=function(a,b){return new D.F(a,D.Z.fN(2*window.Math.atan(window.Math.exp(D.Z.aj(b)))-0.5*window.Math.PI))};
D.Z.hCa=function(a,b,c){b/=D.Z.RU;c/=D.Z.RU;var d=D.Z.aj(a.y),e=window.Math.sqrt(b*b+c*c),f=window.Math.asin(e);return new D.F(D.Z.fN(D.Z.aj(a.x)+window.Math.atan(b*window.Math.sin(f)/(e*window.Math.cos(d)*window.Math.cos(f)-c*window.Math.sin(d)*window.Math.sin(f)))),D.Z.fN(window.Math.asin(window.Math.cos(f)*window.Math.sin(d)+c*window.Math.sin(f)*window.Math.cos(d)/e)))};
D.Z.iCa=function(a,b){var c=window.Math.floor(window.Math.abs(b)/5);c>=D.Z.Tn.length-1&&(c=D.Z.Tn.length-2);var d=(window.Math.abs(b/180)-D.Z.Tn[c][1])/(D.Z.Tn[c+1][1]-D.Z.Tn[c][1]),e=5*d+5*c,c=a/(D.Z.Tn[c][0]+d*(D.Z.Tn[c+1][0]-D.Z.Tn[c][0]));0>b&&(e*=-1);return new D.F(c,e)};
D.AT=function(a,b,c){this.Init(a,b,c)};D.z.l(D.AT,D.Xt,"DvtThematicMapControlPanel");D.AT.prototype.Init=function(a,b,c){D.AT.o.Init.call(this,a,b,c);this.hn=b.hn;this.Zn=(0,D.xr)(b);this.CBa=D.z.xf(b,b.naa);this.ABa=D.z.xf(b,b.NZ);this.TFa=D.z.xf(b,b.ada);this.Er=this.Fr=this.dA=D.o;this.Uja=this.Tja=D.p;this.Z=b.ls()};D.BT=function(a,b){a.Tja=b;a.Er&&(0,D.Qe)(a.Er,b)};D.CT=function(a,b){a.Uja=b;a.Fr&&(0,D.Qe)(a.Fr,b)};
D.AT.prototype.UN=function(a){if(this.hn&&"none"!=this.hn){var b=(0,D.fu)(this.Z,"buttonWidth",0);this.dA=D.U.KHa(this.j(),this.Zn,this.Z);(0,D.Gh)(this.dA,this.TFa,this);this.dA.Fj((0,D.L)("DvtSubcomponentBundle","CONTROL_PANEL_RESET"));this.ea.Ca(this.dA,this.dA);a.k(this.dA);this.Er=D.U.yHa(this.j(),this.Zn,this.Z);(0,D.Gh)(this.Er,this.ABa,this);this.Er.Fj((0,D.L)("DvtSubcomponentBundle","CONTROL_PANEL_DRILLDOWN"));this.ea.Ca(this.Er,this.Er);this.Er.I(b);(0,D.Qe)(this.Er,this.Tja);a.k(this.Er);
this.Fr=D.U.zHa(this.j(),this.Zn,this.Z);(0,D.Gh)(this.Fr,this.CBa,this);this.Fr.Fj((0,D.L)("DvtSubcomponentBundle","CONTROL_PANEL_DRILLUP"));this.ea.Ca(this.Fr,this.Fr);this.Fr.I(2*b);(0,D.Qe)(this.Fr,this.Uja);a.k(this.Fr)}};D.AT.prototype.Nq=function(a,b){var c=D.AT.o.Nq.call(this,a,b);!c&&this.Qa()&&("drillDown"==a&&this.Er&&this.Er.isEnabled()?c=this.Er:"drillUp"==a&&this.Fr&&this.Fr.isEnabled()?c=this.Fr:"reset"==a&&(this.dA&&this.dA.isEnabled())&&(c=this.dA));return c};

  return D;
});