/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(b){b.Ra=function(f,a){if(!(f instanceof Array)&&"function"!=typeof f&&"function"!=typeof f.iqa)throw Error("_ERR_DATA_INVALID_TYPE_SUMMARY\n_ERR_DATA_INVALID_TYPE_DETAIL");this.Er=this.rea(a);null!=a&&(this.columns=a.columns,this.Di=a.initialSort);b.Ra.q.constructor.call(this,f)};o_("ArrayDataGridDataSource",b.Ra,b);b.b.ga(b.Ra,b.Ym,"oj.ArrayDataGridDataSource");b.Ra.prototype.Init=function(){null==this.columns&&(this.columns=this.mda(this.Kj()));
this.Jga();"function"==typeof this.data&&this.data.subscribe(this.Cla.bind(this),null,"arrayChange");b.Ra.q.Init.call(this)};b.b.g("ArrayDataGridDataSource.prototype.Init",{Init:b.Ra.prototype.Init});b.Ra.prototype.rea=function(b){if(null!=b&&null!=b.rowHeader)if(b=b.rowHeader,"object"===typeof b){if(null!=b["default"]&&"none"==b["default"])return}else if(null!=b)return b;return"m_defaultIndex"};b.Ra.prototype.Jga=function(){var b;b=this.Kj();for(this.or=0;this.or<b.length;this.or+=1)b[this.or].ojKey=
this.or.toString()};b.Ra.prototype.mda=function(b){var a,d;if("number"!==typeof b.length||0===b.length)return[];d=[];for(a in b[0])b[0].hasOwnProperty(a)&&(void 0!=this.Er&&a==this.Er||d.push(a));return d};b.Ra.prototype.R=function(b){return"row"===b?this.uo():"column"===b?this.columns.length:0};b.b.g("ArrayDataGridDataSource.prototype.getCount",{R:b.Ra.prototype.R});b.Ra.prototype.xg=function(){return"exact"};b.b.g("ArrayDataGridDataSource.prototype.getCountPrecision",{xg:b.Ra.prototype.xg});b.Ra.prototype.eJ=
function(b,a){var d;if("row"===b){if(void 0==this.Er)return null;if("m_defaultIndex"==this.Er)return this.$B(a);d=this.Kj();return d[a][this.Er]}if("column"===b)return this.columns[a]};b.Ra.prototype.Ida=function(b,a){var d;if("row"===b)return{key:this.$B(a)};if("column"===b)return d=this.eJ(b,a),null!=this.Di&&this.Di.key===d?{key:this.eJ(b,a),sortDirection:this.Di.direction}:{key:d}};b.Ra.prototype.Kf=function(f,a,d){var c,e,g,h;c=f.axis;e=f.start;g=f.count;e=Math.max(0,e);"column"===c?g=Math.min(this.columns.length,
e+g):(h=this.Kj(),g=void 0===this.Er?e:Math.min(h.length,e+g));c=new b.Gd(e,g,c,this);null!=a&&null!=a.success&&(null==d&&(d={}),a.success.call(d.success,c,f))};b.b.g("ArrayDataGridDataSource.prototype.fetchHeaders",{Kf:b.Ra.prototype.Kf});b.Ra.prototype.eda=function(b,a){var d=this.columns[a];return this.Kj()[b][d]};b.Ra.prototype.fda=function(b,a){return{keys:{row:this.$B(b),column:this.columns[a]}}};b.Ra.prototype.wg=function(f,a,d){var c,e,g,h,k,l;for(c=0;c<f.length;c+=1)e=f[c],"row"===e.axis?
(g=e.start,h=Math.min(this.uo(),g+e.count)):"column"===e.axis&&(k=e.start,l=Math.min(this.columns.length,k+e.count));void 0===h||void 0===l?null!=a&&null!=a.error&&(null==d&&(d={}),a.error.call(d.error)):(c=new b.Vf(g,h,k,l,this),null!=a&&null!=a.success&&(null==d&&(d={}),a.success.call(d.success,c,f)))};b.b.g("ArrayDataGridDataSource.prototype.fetchCells",{wg:b.Ra.prototype.wg});b.Ra.prototype.keys=function(b){var a=b.row,d=b.column;return new Promise(function(b){b({row:this.$B(a),column:this.columns[d]})}.bind(this))};
b.b.g("ArrayDataGridDataSource.prototype.keys",{keys:b.Ra.prototype.keys});b.Ra.prototype.Cg=function(b){var a=b.row,d=b.column;return new Promise(function(b){b({row:this.ZB(a),column:this.columns.indexOf(d)})}.bind(this))};b.b.g("ArrayDataGridDataSource.prototype.indexes",{Cg:b.Ra.prototype.Cg});b.Ra.prototype.sort=function(b,a,d){var c=[],e=[],g,h;null!=a&&null==d&&(d={});if(null==b)this.GL(a,d);else if(g=b.axis,h=b.key,b=b.direction,"column"===g)void 0==this.zr&&(this.ria=this.Di,this.zr=this.data.slice()),
this.Di={key:h,direction:b},this.Kj().sort(this.jZ(b,h)),null!=a&&null!=a.success&&a.success.call(d.success);else if("row"===g){h=this.ZB(h);for(g=0;g<this.columns.length;g+=1)c[g]=this.Kj()[h][this.columns[g]];c.sort(this.jZ(b));for(g=0;g<this.columns.length;g+=1)e[g]=this.columns[c.indexOf(this.Kj()[h][this.columns[g]])];this.I4=this.columns;this.columns=e;null!=a&&null!=a.success&&a.success.call(d.success)}else null!==a&&null!=a.error&&a.error.call(d.error,"Invalid axis value")};b.b.g("ArrayDataGridDataSource.prototype.sort",
{sort:b.Ra.prototype.sort});b.Ra.prototype.GL=function(b,a){null!=this.zr&&(this.data=this.zr,this.Di=this.ria);null!=this.I4&&(this.columns=this.I4);null!=b&&null!=b.success&&b.success.call(a.success)};b.Ra.prototype.getCapability=function(b){return"sort"===b?"column":"move"===b?"row":null};b.b.g("ArrayDataGridDataSource.prototype.getCapability",{getCapability:b.Ra.prototype.getCapability});b.Ra.prototype.jZ=function(b,a){if("ascending"===b)return function(b,c){var e,f;void 0!=a&&(b instanceof Array?
(b=b[parseInt(a,10)],c=c[parseInt(a,10)]):(b=b[a],c=c[a]));e=isNaN(b);f=isNaN(c);b instanceof Date&&(b=b.toISOString(),e=!0);c instanceof Date&&(c=c.toISOString(),f=!0);return e&&f?b<c?-1:b===c?0:1:e?1:f?-1:b-c};if("descending"===b)return function(b,c){var e,f;void 0!=a&&(b instanceof Array?(b=b[parseInt(a,10)],c=c[parseInt(a,10)]):(b=b[a],c=c[a]));e=isNaN(b);f=isNaN(c);b instanceof Date&&(b=b.toISOString(),e=!0);c instanceof Date&&(c=c.toISOString(),f=!0);return e&&f?b>c?-1:b===c?0:1:e?-1:f?1:c-
b}};b.Ra.prototype.move=function(b,a){var d,c;d=this.ZB(b);c=this.data.splice(d,1)[0];this.data instanceof Array&&(d=this.wk("delete",b,null,d,-1,!0),this.handleEvent("change",d));null===a?(this.data.push(c),d=this.data.length):(d=this.ZB(a),this.data.splice(d,0,c));this.data instanceof Array&&(d=this.wk("insert",b,null,d,-1),this.handleEvent("change",d));null!=this.zr&&(this.zr=this.data.slice())};b.b.g("ArrayDataGridDataSource.prototype.move",{move:b.Ra.prototype.move});b.Ra.prototype.qd=function(){return"valid"};
b.b.g("ArrayDataGridDataSource.prototype.moveOK",{qd:b.Ra.prototype.qd});b.Ra.prototype.Kj=function(){return"function"===typeof this.data?this.data():this.data};b.Ra.prototype.ZB=function(b){var a,d=this.Kj();for(a=0;a<d.length;a++)if(d[a].ojKey===b)return a;return-1};b.Ra.prototype.$B=function(b){var a=this.Kj();return a[b]?a[b].ojKey:null};b.Ra.prototype.wk=function(b,a,d,c,e,g){var h={source:this};h.operation=b;h.keys={row:a,column:d};h.indexes={row:c,column:e};h.silent=g;return h};b.Ra.prototype.Cla=
function(b){var a,d,c,e=!1;d=!1;var g=[],h=[];for(a=0;a<b.length;a++){c=b[a];if(void 0!==c.moved){d=!0;c=this.wk("refresh",null,null);this.handleEvent("change",c);break}"added"===c.status&&(e=!0)}if(!d){for(a=0;a<b.length;a++)c=b[a],"deleted"===c.status&&(d=c.value,c=c.index,d=d.ojKey,g.push({row:d,column:-1}),h.push({row:c,column:-1}));0<g.length&&(c={source:this,operation:"delete",keys:g,indexes:h,silent:e},this.handleEvent("change",c));for(a=0;a<b.length;a++)c=b[a],"added"===c.status&&(d=c.value,
c=c.index,null==d.ojKey&&(d.ojKey=this.or.toString(),this.or++),d=d.ojKey,c=this.wk("insert",d,null,c,-1),this.handleEvent("change",c))}null!=this.zr&&(this.zr=this.data.slice())};b.Ra.prototype.uo=function(){return this.Kj().length};b.Ra.prototype.j3=function(){return this.Er};b.b.g("ArrayDataGridDataSource.prototype.getRowHeaderKey",{j3:b.Ra.prototype.j3});b.Ra.prototype.Lo=function(){return this.columns};b.b.g("ArrayDataGridDataSource.prototype.getColumns",{Lo:b.Ra.prototype.Lo});b.Ra.prototype.getData=
function(){return this.data};b.b.g("ArrayDataGridDataSource.prototype.getData",{getData:b.Ra.prototype.getData});b.Gd=function(b,a,d,c){this.ac=b;this.re=a;this.i4=d;this.Nj=c};o_("ArrayHeaderSet",b.Gd,b);b.Gd.prototype.getData=function(f,a){if(null==this.Nj)return null;b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return this.Nj.eJ(this.i4,f)};b.b.g("ArrayHeaderSet.prototype.getData",{getData:b.Gd.prototype.getData});b.Gd.prototype.getMetadata=
function(f,a){if(null==this.Nj)return null;b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return this.Nj.Ida(this.i4,f)};b.b.g("ArrayHeaderSet.prototype.getMetadata",{getMetadata:b.Gd.prototype.getMetadata});b.Gd.prototype.zg=function(){return 0<this.R()?1:0};b.b.g("ArrayHeaderSet.prototype.getLevelCount",{zg:b.Gd.prototype.zg});b.Gd.prototype.Vb=function(f,a){b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==
a,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};b.b.g("ArrayHeaderSet.prototype.getExtent",{Vb:b.Gd.prototype.Vb});b.Gd.prototype.le=function(f,a){b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return 1};b.b.g("ArrayHeaderSet.prototype.getDepth",{le:b.Gd.prototype.le});b.Gd.prototype.R=function(){return null==this.Nj?0:Math.max(0,this.re-this.ac)};b.b.g("ArrayHeaderSet.prototype.getCount",{R:b.Gd.prototype.R});b.Gd.prototype.ta=
function(){return this.ac};b.b.g("ArrayHeaderSet.prototype.getStart",{ta:b.Gd.prototype.ta});b.Vf=function(b,a,d,c,e){this.Mi=b;this.rr=a;this.hl=d;this.qr=c;this.Nj=e};o_("ArrayCellSet",b.Vf,b);b.Vf.prototype.getData=function(b){return this.Nj.eda(b.row,b.column)};b.b.g("ArrayCellSet.prototype.getData",{getData:b.Vf.prototype.getData});b.Vf.prototype.getMetadata=function(b){return this.Nj.fda(b.row,b.column)};b.b.g("ArrayCellSet.prototype.getMetadata",{getMetadata:b.Vf.prototype.getMetadata});b.Vf.prototype.ta=
function(b){return"row"==b?this.Mi:"column"==b?this.hl:-1};b.b.g("ArrayCellSet.prototype.getStart",{ta:b.Vf.prototype.ta});b.Vf.prototype.R=function(b){return"row"===b?Math.max(0,this.rr-this.Mi):"column"===b?Math.max(0,this.qr-this.hl):0};b.b.g("ArrayCellSet.prototype.getCount",{R:b.Vf.prototype.R});b.Vf.prototype.getStartRow=function(){return this.Mi};b.b.g("ArrayCellSet.prototype.getStartRow",{getStartRow:b.Vf.prototype.getStartRow});b.Vf.prototype.getStartColumn=function(){return this.hl};b.b.g("ArrayCellSet.prototype.getStartColumn",
{getStartColumn:b.Vf.prototype.getStartColumn})});