/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","knockout","ojs/ojdatasource-common"],function(b,f,a){b.Bb=function(a){this.data=a;this.current=0;this.Init();this.VL(10)};o_("ArrayPagingDataSource",b.Bb,b);b.b.ga(b.Bb,b.Ti,"oj.ArrayPagingDataSource");b.Bb.prototype.Init=function(){b.Bb.q.Init.call(this)};b.b.g("ArrayPagingDataSource.prototype.Init",{Init:b.Bb.prototype.Init});b.Bb.prototype.BJ=function(){return this.Zw()?this.om:this.totalSize()-this.current};b.Bb.prototype.Kq=function(a){a=a||{};this.If=Array(this.BJ());
for(var b=0;b<this.If.length;b++)this.If[b]=this.data[this.current+b];this.Qx();this.kj=this.$+this.If.length-1;a.silent||this.handleEvent("sync",{data:this.If,startIndex:this.current})};b.Bb.prototype.Qx=function(){if(void 0!==this.Qj){this.Qj.removeAll();for(var a=0;a<this.If.length;a++)this.Qj.push(this.If[a])}};b.Bb.prototype.handleEvent=function(a,c){return b.Bb.q.handleEvent.call(this,a,c)};b.Bb.prototype.ym=function(){return this.If};b.b.g("ArrayPagingDataSource.prototype.getWindow",{ym:b.Bb.prototype.ym});
b.Bb.prototype.Qy=function(){void 0===this.Qj&&(this.Qj=a.observableArray(),this.Qx());return this.Qj};b.b.g("ArrayPagingDataSource.prototype.getWindowObservable",{Qy:b.Bb.prototype.Qy});b.Bb.prototype.getPage=function(){return this.Nc};b.b.g("ArrayPagingDataSource.prototype.getPage",{getPage:b.Bb.prototype.getPage});b.Bb.prototype.setPage=function(a,c){c=c||{};a=parseInt(a,10);try{b.Bb.q.handleEvent.call(this,b.dc.D.BEFOREPAGE,{page:a,previousPage:this.Nc})}catch(e){return Promise.reject(null)}this.pageSize=
null!=c.pageSize?c.pageSize:this.pageSize;c.startIndex=a*this.pageSize;var f=this.Nc;this.Nc=a;this.$=c.startIndex;var h=this;return new Promise(function(a,d){h.De(c).then(function(){b.Bb.q.handleEvent.call(h,b.dc.D.PAGE,{page:h.Nc,previousPage:f});a(null)},function(){h.Nc=f;h.$=h.Nc*h.pageSize;d(null)})})};b.b.g("ArrayPagingDataSource.prototype.setPage",{setPage:b.Bb.prototype.setPage});b.Bb.prototype.getStartItemIndex=function(){return this.$};b.b.g("ArrayPagingDataSource.prototype.getStartItemIndex",
{getStartItemIndex:b.Bb.prototype.getStartItemIndex});b.Bb.prototype.getEndItemIndex=function(){return this.kj};b.b.g("ArrayPagingDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.Bb.prototype.getEndItemIndex});b.Bb.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.pageSize)};b.b.g("ArrayPagingDataSource.prototype.getPageCount",{getPageCount:b.Bb.prototype.getPageCount});b.Bb.prototype.fetch=function(a){a=a||{};if(void 0!==a.pageSize&&void 0!==a.startIndex){if(!this.Zw())return Promise.resolve();
this.om=a.startIndex+a.pageSize}this.Kq(null);return Promise.resolve()};b.b.g("ArrayPagingDataSource.prototype.fetch",{fetch:b.Bb.prototype.fetch});b.Bb.prototype.De=function(a){var b=a||{};void 0!==b.startIndex&&(this.current=b.startIndex);void 0!==b.pageSize&&(this.om=this.pageSize=b.pageSize);this.Kq(a);return Promise.resolve({data:this.If,startIndex:this.current})};b.Bb.prototype.Zw=function(){return this.current+this.om<this.totalSize()};b.Bb.prototype.VL=function(a){this.om=this.pageSize=a;
this.Kq(null)};b.Bb.prototype.totalSize=function(){return this.data.length};b.Bb.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("ArrayPagingDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.Bb.prototype.totalSizeConfidence});b.Bb.prototype.getCapability=function(){return null};b.b.g("ArrayPagingDataSource.prototype.getCapability",{getCapability:b.Bb.prototype.getCapability})});