/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(b,f){b.Ea=function(a,d){this.data={};if(!(a instanceof Array)&&"function"!=typeof a&&"function"!=typeof a.iqa)throw Error(b.T.gc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+b.T.gc._ERR_DATA_INVALID_TYPE_DETAIL);null!=d&&null!=d.idAttribute||b.r.info(b.Ea.gc._INFO_ARRAY_TABLE_DATASOURCE_IDATTR);b.Ea.q.constructor.call(this,a,d);this.jd=[];this.qa={};if(null!=a&&void 0!==a&&(this.mK=null,null!=d&&null!=d.idAttribute&&(this.mK=d.idAttribute),
this.i=a instanceof Array?a:a(),this.ke=this.i.length,!(a instanceof Array))){var c=this;a.subscribe(function(a){if(c.lY()){var b,d=[],f=[];for(b=0;b<a.length;b++)"deleted"===a[b].status&&d.push(a[b].value);c.remove(d,null);d=[];f=[];for(b=0;b<a.length;b++)"added"===a[b].status&&(d.push(a[b].value),f.push(a[b].index));c.add(d,{at:f})}},null,"arrayChange")}if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d)this.cy=!0};o_("ArrayTableDataSource",b.Ea,b);b.b.ga(b.Ea,b.T,"oj.ArrayTableDataSource");
b.Ea.prototype.Init=function(){b.Ea.q.Init.call(this)};b.b.g("ArrayTableDataSource.prototype.Init",{Init:b.Ea.prototype.Init});b.Ea.prototype.add=function(a,b){b=b||{};this.Up();return this.m$(a,b.at,b)};b.b.g("ArrayTableDataSource.prototype.add",{add:b.Ea.prototype.add});b.Ea.prototype.at=function(a){this.Up();var b;b=0>a||a>=this.qa.data.length?null:{data:this.qa.data[a],index:a,key:this.mt(this.qa.data[a])};return new Promise(function(a){a(b)})};b.b.g("ArrayTableDataSource.prototype.at",{at:b.Ea.prototype.at});
b.Ea.prototype.change=function(a,d){d=d||{};this.Up();var c=d.silent,e,f,h,k,l={data:[],keys:[],indexes:[]};a instanceof Array||(a=[a]);for(e=0;e<a.length;e++)f=a[e],null!=f&&(h=this.mt(f),k=this.Gh(h,null),l.data.push(f),l.keys.push(h),l.indexes.push(k.index),this.qa.data[k.index]=f);!c&&0<l.data.length&&b.T.q.handleEvent.call(this,b.T.D.CHANGE,l);return Promise.resolve(l)};b.b.g("ArrayTableDataSource.prototype.change",{change:b.Ea.prototype.change});b.Ea.prototype.fetch=function(a){a=a||{};return"init"!=
a.fetchType||this.cy?this.De(a):Promise.resolve()};b.b.g("ArrayTableDataSource.prototype.fetch",{fetch:b.Ea.prototype.fetch});b.Ea.prototype.get=function(a,b){b=b||{};this.Up();return Promise.resolve(this.Gh(a,b))};b.b.g("ArrayTableDataSource.prototype.get",{get:b.Ea.prototype.get});b.Ea.prototype.getCapability=function(){return"full"};b.b.g("ArrayTableDataSource.prototype.getCapability",{getCapability:b.Ea.prototype.getCapability});b.Ea.prototype.remove=function(a,b){b=b||{};this.Up();return this.Nq(a,
b)};b.b.g("ArrayTableDataSource.prototype.remove",{remove:b.Ea.prototype.remove});b.Ea.prototype.reset=function(a,d){d=d||{};d.previousRows=this.qa;var c=d.silent;null!=a&&(this.i=a);this.qa={};this.ke=0;c||b.T.q.handleEvent.call(this,b.T.D.RESET,null);return Promise.resolve()};b.b.g("ArrayTableDataSource.prototype.reset",{reset:b.Ea.prototype.reset});b.Ea.prototype.sort=function(a){if(null==a)return this.comparator=null,Promise.resolve();this.Up();var d=a.key,c=a.direction,e=null;"ascending"==c?
e=function(a){return f.isFunction(a[d])?a[d]():a[d]}:"descending"==c&&(e=function(a,b){var c,e;f.isFunction(a[d])?(c=a[d](),e=b[d]()):(c=a[d],e=b[d]);return c===e?0:c>e?-1:1});this.comparator=e;this.direction=c;var g=this;return new Promise(function(c){a=a||{};if(g.hC()){var d=g.comparator;g.qa.data.sort(function(a,c){return b.Ea.I0(a,c,d,g)});g.xla=!0;var e={header:a.key,direction:a.direction};b.T.q.handleEvent.call(g,b.T.D.SORT,e);c(e)}})};b.b.g("ArrayTableDataSource.prototype.sort",{sort:b.Ea.prototype.sort});
b.Ea.prototype.totalSize=function(){return this.ke};b.b.g("ArrayTableDataSource.prototype.totalSize",{totalSize:b.Ea.prototype.totalSize});b.Ea.prototype.m$=function(a,d,c){var e,f;c=c||{};var h=c.silent,k={data:[],keys:[],indexes:[]};a instanceof Array||(a=[a]);null==d||d instanceof Array||(d=[d]);for(c=0;c<a.length;c++)if(f=a[c],null!=f){e=this.mt(f);k.data.push(f);k.keys.push(e);if(!0==this.xla&&0<this.qa.data.length)for(e=0;e<this.qa.data.length;e++)if(0>b.Ea.I0(f,this.qa.data[e],this.comparator,
this)){this.qa.data.splice(e,0,f);k.indexes.push(e);break}else{if(e==this.qa.data.length-1){this.qa.data.push(f);k.indexes.push(e+1);break}}else null==d?(this.qa.data.push(f),k.indexes.push(this.qa.data.length-1)):(this.qa.data.splice(d[c],0,f),k.indexes.push(d[c]));this.ke++;this.Mx()}!h&&0<k.data.length&&b.T.q.handleEvent.call(this,b.T.D.ADD,k);return Promise.resolve(k)};b.Ea.prototype.Up=function(){this.lY()||(this.qa=this.oq(this.i),this.ke=this.i.length)};b.Ea.prototype.lY=function(){return null==
this.qa||null==this.qa.data?!1:!0};b.Ea.prototype.De=function(a){a=a||{};this.by(a);this.Up();var d;try{d=0<a.pageSize?a.pageSize:-1;this.$||(this.$=0);this.$=null==a.startIndex?this.$:a.startIndex;var c=b.Ea.MB(this.qa,this.$,d),e=[],f=[],h;for(h=this.$;h<=c;h++)e[h-this.$]=this.qa.data[h],f[h-this.$]=this.mt(this.qa.data[h])}catch(k){return this.Zg(a,null,k),Promise.reject(k)}c<this.$&&(this.$=c+1);a.pageSize=d;a.startIndex=this.$;a.refresh=!0;d={data:e,keys:f,startIndex:this.$};this.Zg(a,d,null);
return Promise.resolve(d)};b.Ea.prototype.Gh=function(a){var b,c,e,g,h=null;for(b=0;b<this.qa.data.length;b++)if(e=this.qa.data[b],void 0!==e)if(g=this.mt(e),f.isArray(g)&&f.isArray(a)){if(g.length==a.length){var k=!0;for(c=0;c<a.length;c++)if(g[c]!=a[c]){k=!1;break}k&&(h={data:e,key:g,index:this.qa.indexes[b]})}}else g==a&&(h={data:e,key:g,index:this.qa.indexes[b]});return h};b.Ea.prototype.hC=function(){var a=this.comparator;return void 0!==a&&null!==a};b.Ea.prototype.Mx=function(){for(var a=0;a<
this.qa.data.length;a++)this.qa.indexes[a]=a};b.Ea.prototype.Nq=function(a,d){var c,e;d=d||{};var f=d.silent,h={data:[],keys:[],indexes:[]};a instanceof Array||(a=[a]);var k=[];for(c=0;c<a.length;c++)e=a[c],null!=e&&(e=this.mt(e),e=this.Gh(e,null),null!=e&&k.push({data:e.data,key:e.key,index:e.index}));k.sort(function(a,b){return a.index-b.index});for(c=0;c<k.length;c++)h.data.push(k[c].data),h.keys.push(k[c].key),h.indexes.push(k[c].index);for(c=h.indexes.length-1;0<=c;c--)this.qa.data.splice(h.indexes[c],
1),this.qa.indexes.splice(h.indexes[c],1),this.ke--,this.Mx();!f&&0<h.data.length&&b.T.q.handleEvent.call(this,b.T.D.REMOVE,h);return Promise.resolve(h)};b.Ea.prototype.by=function(a){a.silent||b.T.q.handleEvent.call(this,b.T.D.REQUEST,{startIndex:a.startIndex})};b.Ea.prototype.Zg=function(a,d,c){null!=c?b.T.q.handleEvent.call(this,b.T.D.ERROR,c):a.silent||b.T.q.handleEvent.call(this,b.T.D.SYNC,d)};b.Ea.Gl=function(a,b,c){if("descending"==c){if(a<b)return 1;if(b<a)return-1}else{if(a>b)return 1;if(b>
a)return-1}return 0};b.Ea.MB=function(a,b,c){var e=a.data.length-1;0<c&&(e=b+c-1,e=e>a.data.length-1?a.data.length-1:e);return e};b.Ea.Tn=function(a,b){return f.isFunction(a[b])?a[b]():a[b]};b.Ea.prototype.oq=function(a){var b=a.length-1,c={},e,f;c.data=[];c.indexes=[];this.Dn=null;for(e=0;e<=b;e++){var h={},k=a[e];for(f in k)k.hasOwnProperty(f)&&(h[f]=k[f],0==e&&(null==this.Dn&&(this.Dn=[]),this.Dn.push(f)));c.data[e]=h;c.indexes[e]=e}return c};b.Ea.prototype.mt=function(a){var d,c=this.gJ(a);if(f.isArray(c)){var e;
d=[];for(e=0;e<c.length;e++)if(c[e]in a)d[e]=a[c[e]];else throw a=b.ha.Mb(b.Ea.gc._ERR_ARRAY_TABLE_DATASOURCE_IDATTR_NOT_IN_ROW,[c[e]]),Error(a);}else if(c in a)d=a[c];else throw a=b.ha.Mb(b.Ea.gc._ERR_ARRAY_TABLE_DATASOURCE_IDATTR_NOT_IN_ROW,[c]),Error(a);return d};b.Ea.prototype.gJ=function(a){if(null!=this.mK)return this.mK;if(null==this.Dn){this.Dn=[];for(var b in a)a.hasOwnProperty(b)&&this.Dn.push(b)}return this.Dn.hasOwnProperty("id")?"id":this.Dn};b.Ea.I0=function(a,d,c,e){var g,h;if(f.isFunction(c)){if(1===
c.length){g=c.call(e,a);h=c.call(e,d);a=b.Fa.od(g)?g.split(","):[g];d=b.Fa.od(h)?h.split(","):[h];for(c=0;c<a.length;c++)if(g=b.Ea.Gl(a[c],d[c],e.direction),0!==g)return g;return 0}return c.call(e,a,d)}if(b.Fa.od(c)){var k=c.split(",");for(c=0;c<k.length;c++)if(g=b.Ea.Tn(a,k[c]),h=b.Ea.Tn(d,k[c]),g=b.Ea.Gl(g,h,e.direction),0!==g)return g}return 0};b.Ea.gc={_INFO_ARRAY_TABLE_DATASOURCE_IDATTR:"idAttribute option has not been specified. Will default to using 'id' if the field exists. If not, will use all the fields.",
_ERR_ARRAY_TABLE_DATASOURCE_IDATTR_NOT_IN_ROW:"Specified idAttribute {0} not in row data. Please ensure all specified idAttribute fields are in the row data or do not specify idAttribute and all fields will be used as id."}});