/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,f){(function(){function a(a,c,d){a:{for(var e=r[a],f=0;f<e.length;++f){var g=e[f];if(0<=d.indexOf(g))for(;;c=c.parentNode){var h=b.Components.Of(c,g);if(h){d=h;break a}}}d=null}return d?d("option","chroming"):b.ze.Yk(a).chroming}function d(a,b){var c=a.name,d=a.form;c?(c=c.replace(/'/g,"\\'"),c=":radio[name\x3d'"+c+"']:oj-button",d=b?b.filter(c):d?f(d).find(c):f(c,a.ownerDocument).filter(function(){return!this.form})):d=(b?b.filter(a):
f(a)).filter(":oj-button");return d}function c(a,b){a.removeClass(n).addClass(p[b])}b.ya("oj.ojButton",f.oj.baseComponent,{defaultElement:"\x3cbutton\x3e",widgetEventPrefix:"oj",options:{chroming:"full",disabled:!1,display:"all",label:null,icons:{start:null,end:null},menu:null},Yd:function(a,b){this._super(a,b);this.lga();"disabled"in b||this.option("disabled",!!this.element.prop("disabled"),{_context:{Va:!0}});"label"in b||(this.epa=!0,this.option("label","inputPush"===this.type?this.Cd.val():this.Cd.html(),
{_context:{Va:!0}}));!this.options.menu||b.icons&&void 0!==b.icons.end||this.option("icons.end","oj-component-icon oj-button-menu-dropdown-icon",{_context:{Ic:!0,Va:!0}})},_ComponentCreate:function(){function a(){b.IK=Date.now();b.ub.removeClass(l);b.ub.removeClass("oj-hover");b.Lh()}this._super();this.element.closest("form").unbind("reset"+h).bind("reset"+h,function(){var a=f(this);setTimeout(function(){a.find(":oj-button").each(function(){f(this).data("oj-ojButton").IA(!1)}).length||a.unbind("reset"+
h)},1)});this.Ru=this.eventNamespace+"menu";this.mga();this.ZN=!!this.ub.attr("title");var b=this,d=this.jx,l=d?"":"oj-active";this.ub.addClass(k);c(this.ub,this.options.chroming);this.document.bind("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,a);this.Cd.bind("touchstart"+this.eventNamespace,function(){b.Zd()||(f(this).addClass(l),b.Lh())}).bind("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,a).bind("mouseenter"+this.eventNamespace,function(){b.Zd()||b.Nx()||
(this===e&&b.ub.addClass("oj-active"),b.ub.addClass("oj-hover").removeClass("oj-default oj-focus-only"))}).bind("mouseleave"+this.eventNamespace,function(){b.ub.removeClass("oj-hover");b.Zd()||(b.ub.removeClass(l),b.Lh())}).bind("click"+this.eventNamespace,function(a){b.Zd()&&(a.preventDefault(),a.stopImmediatePropagation())});this.element.bind("focus"+this.eventNamespace,function(){b.ub.addClass("oj-focus");b.Lh()}).bind("blur"+this.eventNamespace,function(){b.ub.removeClass("oj-focus");b.Lh()});
d&&(this.element.bind("change"+this.eventNamespace,function(a){b.IA(!0);var c=f(this).closest(":oj-buttonset").data("oj-ojButtonset"),d=c&&c.RV(c.Fd);c&&void 0!==d&&c.option("checked",d,{_context:{Ic:!0,originalEvent:a,Va:!0}})}),this.Cd.bind("mousedown"+this.eventNamespace,function(){b.Zd()||(g=this,b.document.one("mouseup",function(){g=null}))}).bind("mouseup"+this.eventNamespace,function(){b.Zd()||this!==g||b.element.focus()}));"checkbox"===this.type?(this.Cd.bind("click"+this.eventNamespace,function(){if(b.Zd())return!1}),
this.element.bind("keyup"+this.eventNamespace,function(a){a.keyCode===f.ui.keyCode.ENTER&&(b.Zd()||b.element.click())})):"radio"===this.type?(this.Cd.bind("click"+this.eventNamespace,function(){if(b.Zd())return!1}),this.element.bind("keyup"+this.eventNamespace,function(a){a.keyCode!==f.ui.keyCode.ENTER||b.element[0].checked||b.Zd()||(b.element[0].checked=!0,b.element.change(),b.element.click())})):(this.Cd.bind("mousedown"+this.eventNamespace,function(a){if(b.Zd())return!1;1!==a.which||b.Nx()||(f(this).addClass("oj-active").removeClass("oj-default oj-focus-only"),
e=this,b.document.one("mouseup",function(){e=null}))}).bind("mouseup"+this.eventNamespace,function(){if(b.Zd())return!1;f(this).removeClass("oj-active");b.Lh()}).bind("keydown"+this.eventNamespace,function(a){if(b.Zd())return!1;var c=a.keyCode===f.ui.keyCode.SPACE,d="anchor"===b.type;d&&c&&a.preventDefault();(c&&!d||a.keyCode===f.ui.keyCode.ENTER)&&f(this).addClass("oj-active").removeClass("oj-default oj-focus-only")}).bind("keyup"+this.eventNamespace+" blur"+this.eventNamespace,function(){f(this).removeClass("oj-active");
b.Lh()}),"anchor"===this.type&&(d=this.Cd.attr("tabindex"),("undefined"===d||null===d||isNaN(d))&&this.Cd.attr("tabindex","0")));this.OM();this.Afa();this.s0();this.Lh()},Nx:function(){return 500>Date.now()-this.IK},qf:function(a,b,c){this.sf(b,c,{position:{of:"keyboard"===c?this.ub:b}})},lga:function(){if(this.element.is("input[type\x3dcheckbox]"))this.type="checkbox",this.jx=!0;else if(this.element.is("input[type\x3dradio]"))this.type="radio",this.jx=!0;else if(this.element.is("input[type\x3dbutton],input[type\x3dsubmit],input[type\x3dreset]"))this.type=
"inputPush";else if(this.element.is("button"))this.type="button";else if(this.element.is("a"))this.type="anchor";else throw Error("JET Button not supported on this element type");if(this.jx){var a="label[for\x3d'"+this.element.attr("id")+"']";this.Cd=this.element.siblings().filter(a)}else this.Cd=this.element},mga:function(){this.jx?(this.Cd.addClass("oj-button-label"),this.element.addClass("oj-button-input oj-helper-hidden-accessible").add(this.Cd).wrapAll("\x3cspan\x3e\x3c/span\x3e"),this.ub=this.element.parent(),
this.ub.addClass("oj-button-toggle"),this.element[0].checked&&this.ub.addClass("oj-selected").removeClass("oj-default oj-focus-only")):this.ub=this.element},widget:function(){return this.ub},_destroy:function(){this.q_();this.document.off(this.eventNamespace);this.element.removeClass("oj-helper-hidden-accessible").removeAttr("aria-labelledby").removeUniqueId();var a=this.jx;a||this.ub.removeClass(k+" "+l+" "+m+" "+n);this.Cd.html(this.Cd.find(".oj-button-text").html());a?(this.Cd.removeClass("oj-button-label"),
b.v.unwrap(this.element)):this.ZN||this.ub.removeAttr("title");g===this.Cd[0]&&(g=null)},li:function(){this._super();this.Lh()},Zv:function(a){this._super(a);this.OM()},OM:function(){var a=this.Zd();this.ub.toggleClass("oj-disabled",a);this.ub.toggleClass("oj-enabled",!a);"anchor"!==this.type?(this.element.prop("disabled",a),this.ub.removeAttr("aria-disabled")):this.ub.attr("aria-disabled",a);a?(this.widget().removeClass("oj-active oj-default oj-focus-only oj-hover oj-focus"),e=null,this.rI()):this.Lh()},
_setOption:function(a,b,d){this._super(a,b,d);switch(a){case "chroming":c(this.ub,b);break;case "disabled":this.OM();break;case "label":this.Pka();break;case "display":"inputPush"!==this.type&&this.eD();break;case "icons":this.Mka(!0);break;case "menu":this.s0()}},refresh:function(){this._super();this.gT&&!f(this).closest(":oj-buttonset").length&&this.Zv(!1);c(this.ub,this.options.chroming)},IA:function(a){"radio"===this.type?(a?d(this.element[0]):this.element).each(function(){var a=f(this).data("oj-ojButton");
this.checked?a.ub.addClass("oj-selected").removeClass("oj-default oj-focus-only"):(a.ub.removeClass("oj-selected"),a.Lh())}):"checkbox"===this.type&&(this.element[0].checked?this.ub.addClass("oj-selected").removeClass("oj-default oj-focus-only"):(this.ub.removeClass("oj-selected"),this.Lh()))},Afa:function(){if("inputPush"===this.type)this.d0();else{var a=this.Oka(),b=this.fD(!0),c=this.fD(!1);this.eD(a,b,c)}},Oka:function(){var a=this.Cd,b=f("\x3cspan class\x3d'oj-button-text'\x3e\x3c/span\x3e",
this.document[0]);this.epa?b.append(a.contents()):(a.empty(),b.text(this.options.label));a.append(b);if("button"===this.type||"anchor"===this.type)b.uniqueId(),this.element.attr("aria-labelledby",b.attr("id"));return b},Pka:function(){if("inputPush"===this.type)this.d0();else{var a=this.Cd.find(".oj-button-text");a.text(this.options.label);this.eD(a)}},d0:function(){this.options.label&&this.element.val(this.options.label)},Mka:function(){if("inputPush"!==this.type){var a=this.fD(!0),b=this.fD(!1);
this.eD(void 0,a,b)}},fD:function(a){if(a){var b=".oj-button-icon.oj-start";a="oj-button-icon oj-start";var c=this.options.icons.start,d="_lastStartIcon",e="prependTo"}else b=".oj-button-icon.oj-end",a="oj-button-icon oj-end",c=this.options.icons.end,d="_lastEndIcon",e="appendTo";b=this.Cd.find(b);c?(b.length?b.removeClass(this[d]):b=f("\x3cspan\x3e\x3c/span\x3e").addClass(a)[e](this.Cd),b.addClass(c)):b.remove();this[d]=c;return!!c},eD:function(a,b,c){void 0===a&&(a=this.Cd.find(".oj-button-text"));
void 0===b&&(b=!!this.options.icons.start);void 0===c&&(c=!!this.options.icons.end);var d=b&&c;c=b||c;var e="icons"===this.options.display;c&&e?(a.addClass("oj-helper-hidden-accessible"),this.ZN||(a=a.text(),this.ub.attr("title",f.trim(a)))):(a.removeClass("oj-helper-hidden-accessible"),this.ZN||this.ub.removeAttr("title"));b=c?e?d?"oj-button-icons-only":"oj-button-icon-only":d?"oj-button-text-icons":b?"oj-button-text-icon-start":"oj-button-text-icon-end":"oj-button-text-only";this.ub.removeClass(m).addClass(b)},
s0:function(){if(this.options.menu&&this.element.is("input"))throw Error("Menu Button functionality is not supported on input elements.");this.q_();if(this.options.menu){var a=this;this.element.attr("aria-haspopup",!0).on("keydown"+this.Ru,function(b){if(b.which===f.ui.keyCode.DOWN)a.x0(b,"firstItem"),b.preventDefault();else if(b.which===f.ui.keyCode.ESCAPE){var c=a.qaa(a.ub);a.rI(b);return c}return!0}).on("click"+this.Ru,function(b){var c=a.nJ();c.AA||a.x0(b,"firstItem");c.AA=!1;b.preventDefault();
return!0})}},qaa:function(a){return!a.hasClass("oj-selected")},q_:function(){this.element.removeAttr("aria-haspopup").off(this.Ru);this.rI();this.oa&&this.oa.widget().off(this.Ru);this.oa=void 0},nJ:function(){if(!this.oa){this.oa=f(this.options.menu).data("oj-ojMenu");if(!this.oa)throw Error('JET Button: "menu" option specified, but does not reference a valid JET Menu.');var a=this;this.oa.widget().on("oj__dismiss"+this.Ru,function(b){a.bZ(b)}).on("ojbeforeopen"+this.Ru,function(b){a.OY||a.bZ(b);
a.OY=!1})}return this.oa},x0:function(a,b){if(!this.Zd()){this.OY=!0;var c=this.nJ(),d=c.widget();c.open(a,{launcher:this.element,initialFocus:b});this.dZ=!0;d.attr("aria-label")||d.attr("aria-labelledby")||(this.element.uniqueId(),this.V_=!0,d.attr("aria-labelledby",this.element.attr("id")));this.ub.addClass("oj-selected").removeClass("oj-default oj-focus-only")}},rI:function(a){this.dZ&&(this.oa.WG(a,!0),this.oa.Pp(a))},bZ:function(){this.V_&&(this.nJ().widget().removeAttr("aria-labelledby"),this.V_=
!1);this.ub.removeClass("oj-selected");this.Lh();this.dZ=!1},Lh:function(){var a,b;this.ub.is(".oj-hover, .oj-active, .oj-selected, .oj-disabled")?b=a=!1:(b=this.ub.is(".oj-focus"),a=!b);this.ub.toggleClass("oj-default",a);this.ub.toggleClass("oj-focus-only",b)}});b.ya("oj.ojButtonset",f.oj.baseComponent,{KY:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",options:{checked:null,chroming:"full",focusManagement:"oneTabstop"},
Zx:function(a,b){var c=f.type(a),d;if("null"===c||"array"===c)d=b.filter("input[type\x3dcheckbox]").length===b.length;if(d&&"null"===c)throw Error("Invalid 'checked' value set on JET Buttonset: "+a);if("string"===c||"null"===c)(c=((c=b[0].name)||1>=b.length)&&b.filter("input[type\x3dradio][name\x3d"+c+"]").length===b.length&&(null===a||b.filter("[value\x3d"+a+"]").length))&&b.each(function(){this.checked=this.value===a}),c=c||null===a;else if("array"===c){var e;(c=d&&a.concat().sort().every(function(a){var c=
a!==e&&b.filter("[value\x3d"+a+"]").length;e=a;return c}))&&b.each(function(){this.checked=-1<a.indexOf(this.value)})}else c=!1;if(!c)throw Error("Invalid 'checked' value set on JET Buttonset: "+a);},RV:function(a){var b=void 0,c=null,d=null;a.each(function(){if("input"!==this.tagName.toLowerCase())return b=void 0,!1;var a=this.type.toLowerCase(),e;if("radio"===a)a=!0,e=this.name.toLowerCase();else if("checkbox"===a)a=!1,e=null;else return b=void 0,!1;if(void 0!==b&&(a!==c||e!==d||c&&!d))return b=
void 0,!1;void 0===b?(b=a?this.checked?this.value:null:this.checked?[this.value]:[],c=a,d=e):this.checked&&(c?b=this.value:b.push(this.value))});return b},Iv:function(a,b,c){return"checked"===a?b===c?!0:"array"===f.type(b)&&"array"===f.type(c)&&!f(b).not(c).length&&!f(c).not(b).length:this._superApply(arguments)},Yd:function(a,b){this._super(a,b);this.Fd=this.element.find(this.KY);if(!("checked"in b)){this.aO=!0;var c=this.RV(this.Fd);"array"===f.type(c)&&(this.options.checked=[]);void 0!==c&&this.option("checked",
c,{_context:{Va:!0}})}},_ComponentCreate:function(){this._super();this.element.attr(b.Components.tn,this.widgetName).addClass("oj-buttonset oj-component");this.o0(this.options.focusManagement);this.Aa(!0)},qf:function(a,b,c){a=this.element.find(":oj-button[tabindex\x3d0]");this.sf(b,c,{launcher:a,position:{of:"keyboard"===c?a.ojButton("widget"):b}})},po:function(a){a=!!a;this.Fd.each(function(){f(this).data("oj-ojButton").Zv(a)})},o0:function(a){"oneTabstop"===a?this.element.attr("role","toolbar"):
this.element.removeAttr("role")},_setOption:function(a,b,d){this._superApply(arguments);"disabled"===a?this.po(b):"checked"===a?(this.Zx(b,this.Fd),this.Fd.each(function(){f(this).data("oj-ojButton").IA(!1)})):"focusManagement"===a?this.o0(b):"chroming"===a&&(c(this.element,b),this.Fd.ojButton("refresh"))},refresh:function(){this._super();this.Aa(!1)},Aa:function(a){var b=this;this.Qf="rtl"===this.ec();c(this.element,this.options.chroming);a?this.aO||this.Zx(this.options.checked,this.Fd):this.Fd=
this.element.find(this.KY);this.element.toggleClass("oj-buttonset-multi",1<this.Fd.length);this.Fd.filter(":oj-button").ojButton("refresh").each(function(){f(this).data("oj-ojButton").IA(!1)}).end().not(":oj-button").ojButton().end().map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").filter(":first").addClass("oj-buttonset-first").end().filter(":last").addClass("oj-buttonset-last").end().end();this.po(this.options.disabled);"oneTabstop"===this.options.focusManagement&&
(this.Fd.unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.tq(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).data("oj-ojButton").Zd()||b.Pq(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Pq(f(this))}),this.rl=this.Fd.filter(function(){return!f(this).data("oj-ojButton").Zd()}),this.sK(a))},sK:function(a){var b=f(this.Eq);this.Eq=void 0;this.Fd.attr("tabindex","-1");
a=a||!b.is(this.rl)?this.rl.first():b;this.Pq(a)},NK:function(a){var b=this.rl;return a.map(function(a,c){if("radio"!=c.type||c.checked||""==c.name)return c;var e=d(c,b).filter(":checked");return e.length?e[0]:c})},Pq:function(a){a=this.NK(a);var b=a[0],c=this.Eq;b!==c&&(f(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.Eq=b)},tq:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();var c=this.rl,d=c.length;if(2>d)break;var e=c.index(b);c.eq((e+(a.which==
f.ui.keyCode.RIGHT^this.Qf?1:-1)+d)%d).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-buttonset oj-component "+n).removeAttr(b.Components.tn).removeAttr("role");"oneTabstop"===this.options.focusManagement&&this.Fd.attr("tabindex","0");this.Fd.map(function(){return f(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").end().ojButton("destroy")}});var e,g,h=".ojButton",
k="oj-button oj-component oj-enabled oj-default",l="oj-hover oj-active oj-selected",m="oj-button-icons-only oj-button-icon-only oj-button-text-icons oj-button-text-icon-start oj-button-text-icon-end oj-button-text-only",n="oj-button-full-chrome oj-button-half-chrome oj-button-outlined-chrome",p={full:"oj-button-full-chrome",half:"oj-button-half-chrome",outlined:"oj-button-outlined-chrome"},r={button:["ojButtonset","ojToolbar"],buttonset:["ojToolbar"]};b.Components.Om({ojButton:{chroming:b.Components.nh(function(b){return a("button",
b.element,b.containers)})},ojButtonset:{chroming:b.Components.nh(function(b){return a("buttonset",b.element,b.containers)})}})})()});