/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtChart"],function(b,f,a,d,c){b.ya("oj.ojSparkChart",f.oj.dvtBaseComponent,{widgetEventPrefix:"oj",options:{},nf:function(a,b,d){return c.DvtSparkChart.newInstance(a,b,d)},Be:function(){var a=this._super();a.push("oj-sparkchart");return a},ii:function(){var a=this.options.translations,b=this._super();b["DvtUtilBundle.CHART"]=a.componentName;return b},ig:function(){this.element.attr("title")?(this.options.shortDesc=
this.element.attr("title"),this.element.data(this.element,"title",this.element.attr("title")),this.element.removeAttr("title")):this.element.data("title")&&(this.options.shortDesc=this.element.data("title"));this._super()},getDataItem:function(a){var c=this.ka.getAutomation();return new b.kf(c.getDataItem(a))},gi:function(){return{root:["items"]}}});b.kf=function(a){this.i=a};o_("SparkChartDataItem",b.kf,b);b.kf.prototype.I2=function(){return this.i?this.i.borderColor:null};b.b.g("SparkChartDataItem.prototype.getBorderColor",
{I2:b.kf.prototype.I2});b.kf.prototype.O2=function(){return this.i?this.i.color:null};b.b.g("SparkChartDataItem.prototype.getColor",{O2:b.kf.prototype.O2});b.kf.prototype.getDate=function(){return this.i?this.i.date:null};b.b.g("SparkChartDataItem.prototype.getDate",{getDate:b.kf.prototype.getDate});b.kf.prototype.getFloatValue=function(){return this.NN()};b.b.g("SparkChartDataItem.prototype.getFloatValue",{getFloatValue:b.kf.prototype.getFloatValue});b.kf.prototype.NN=function(){return this.i?this.i.low:
null};b.b.g("SparkChartDataItem.prototype.getLow",{NN:b.kf.prototype.NN});b.kf.prototype.b3=function(){return this.i?this.i.high:null};b.b.g("SparkChartDataItem.prototype.getHigh",{b3:b.kf.prototype.b3});b.kf.prototype.Lc=function(){return this.i?this.i.value:null};b.b.g("SparkChartDataItem.prototype.getValue",{Lc:b.kf.prototype.Lc});b.ya("oj.ojChart",f.oj.dvtBaseComponent,{widgetEventPrefix:"oj",options:{categoryFilter:null,categoryHighlight:null,optionChange:null,selectInput:null,viewportChange:null,
viewportChangeInput:null,drill:null},nf:function(a,b,d){return c.DvtChart.newInstance(a,b,d)},di:function(a){var b=a.subId;"oj-chart-item"==b?b="dataItem["+a.seriesIndex+"]["+a.itemIndex+"]":"oj-chart-group"==b?b="group"+this.Bp(a.indexPath):"oj-chart-series"==b?b="series["+a.index+"]":"oj-chart-axis-title"==b?b=a.axis+":title":"oj-chart-reference-object"==b?b=a.axis+":referenceObject["+a.index+"]":"oj-legend-section"==b?b="legend:section"+this.Bp(a.indexPath):"oj-legend-item"==b?(b="legend:section"+
this.Bp(a.sectionIndexPath),b+=":item["+a.itemIndex+"]"):"oj-chart-tooltip"==b&&(b="tooltip");return b},gg:function(a){var b={};if(0==a.indexOf("dataItem")){var c=this.wl(a);b.subId="oj-chart-item";b.seriesIndex=c[0];b.itemIndex=c[1]}else if(0==a.indexOf("group"))b.subId="oj-chart-group",b.indexPath=this.wl(a);else if(0==a.indexOf("series"))b.subId="oj-chart-series",b.index=this.Ug(a);else if(0<a.indexOf("Axis:title"))b.subId="oj-chart-axis-title",b.axis=a.substring(0,a.indexOf(":"));else if(0<a.indexOf("Axis:referenceObject"))b.subId=
"oj-chart-reference-object",b.axis=a.substring(0,a.indexOf(":")),b.index=this.Ug(a);else if(0==a.indexOf("legend"))if(0<a.indexOf(":item")){var d=a.indexOf(":item"),c=a.substring(0,d);a=a.substring(d);b.subId="oj-legend-item";b.sectionIndexPath=this.wl(c);b.itemIndex=this.Ug(a)}else 0==a.indexOf("section")&&(b.subId="oj-legend-section",b.indexPath=this.wl(a));else"tooltip"==a&&(b.subId="oj-chart-tooltip");return b},lA:function(){this._super();this.options.styleDefaults||(this.options.styleDefaults=
{});if(!this.options.styleDefaults.colors){var a=new b.Le;this.options.styleDefaults.colors=a.mr()}},Be:function(){var a=this._super();a.push("oj-chart");return a},ei:function(){var a=this._super();a["oj-chart-data-label"]={path:"styleDefaults/dataLabelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-stack-label"]={path:"styleDefaults/stackLabelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-footnote"]={path:"footnote/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-pie-center-label"]={path:"pieCenterLabel/style",
property:"CSS_TEXT_PROPERTIES"};a["oj-chart-slice-label"]={path:"styleDefaults/sliceLabelStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-subtitle"]={path:"subtitle/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-stock-falling"]={path:"styleDefaults/stockFallingColor",property:"background-color"};a["oj-chart-stock-range"]={path:"styleDefaults/stockRangeColor",property:"background-color"};a["oj-chart-stock-rising"]={path:"styleDefaults/stockRisingColor",property:"background-color"};a["oj-chart-title"]=
{path:"title/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-xaxis-tick-label"]={path:"xAxis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-xaxis-title"]={path:"xAxis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-yaxis-tick-label"]={path:"yAxis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-yaxis-title"]={path:"yAxis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-y2axis-tick-label"]={path:"y2Axis/tickLabel/style",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-y2axis-title"]=
{path:"y2Axis/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-chart-pan-icon"]={path:"_resources/panUp",property:"CSS_URL"};a["oj-chart-pan-icon oj-active"]={path:"_resources/panDown",property:"CSS_URL"};a["oj-chart-select-icon"]={path:"_resources/selectUp",property:"CSS_URL"};a["oj-chart-select-icon oj-active"]={path:"_resources/selectDown",property:"CSS_URL"};a["oj-chart-zoom-icon"]={path:"_resources/zoomUp",property:"CSS_URL"};a["oj-chart-zoom-icon oj-active"]={path:"_resources/zoomDown",property:"CSS_URL"};
a["oj-legend"]={path:"legend/textStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legend-title"]={path:"legend/titleStyle",property:"CSS_TEXT_PROPERTIES"};a["oj-legend-section-close-icon"]={path:"legend/_resources/closedEnabled",property:"CSS_URL"};a["oj-legend-section-close-icon oj-hover"]={path:"legend/_resources/closedOver",property:"CSS_URL"};a["oj-legend-section-close-icon oj-active"]={path:"legend/_resources/closedDown",property:"CSS_URL"};a["oj-legend-section-open-icon"]={path:"legend/_resources/openEnabled",
property:"CSS_URL"};a["oj-legend-section-open-icon oj-hover"]={path:"legend/_resources/openOver",property:"CSS_URL"};a["oj-legend-section-open-icon oj-active"]={path:"legend/_resources/openDown",property:"CSS_URL"};return a},hi:function(){return"categoryFilter categoryHighlight drill optionChange selectInput viewportChange viewportChangeInput".split(" ")},ii:function(){var a=this.options.translations,b=this._super();b["DvtChartBundle.DEFAULT_GROUP_NAME"]=a.labelDefaultGroupName;b["DvtChartBundle.LABEL_SERIES"]=
a.labelSeries;b["DvtChartBundle.LABEL_GROUP"]=a.labelGroup;b["DvtChartBundle.LABEL_VALUE"]=a.labelValue;b["DvtChartBundle.LABEL_TARGET_VALUE"]=a.labelTargetValue;b["DvtChartBundle.LABEL_X"]=a.labelX;b["DvtChartBundle.LABEL_Y"]=a.labelY;b["DvtChartBundle.LABEL_Z"]=a.labelZ;b["DvtChartBundle.LABEL_PERCENTAGE"]=a.labelPercentage;b["DvtChartBundle.LABEL_LOW"]=a.labelLow;b["DvtChartBundle.LABEL_HIGH"]=a.labelHigh;b["DvtChartBundle.LABEL_OPEN"]=a.labelOpen;b["DvtChartBundle.LABEL_CLOSE"]=a.labelClose;b["DvtChartBundle.LABEL_VOLUME"]=
a.labelVolume;b["DvtChartBundle.LABEL_MIN"]=a.labelMin;b["DvtChartBundle.LABEL_MAX"]=a.labelMax;b["DvtChartBundle.LABEL_OTHER"]=a.labelOther;b["DvtChartBundle.PAN"]=a.tooltipPan;b["DvtChartBundle.MARQUEE_SELECT"]=a.tooltipSelect;b["DvtChartBundle.MARQUEE_ZOOM"]=a.tooltipZoom;b["DvtUtilBundle.CHART"]=a.componentName;return b},ki:function(a){var b=a&&a.getType?a.getType():null;if(b===c.DvtSelectionEvent.TYPE||b===c.DvtSelectionEvent.TYPE_INPUT){var d=a.getSelection();if(d){for(var f=[],l=0;l<d.length;l++){var m=
{id:d[l].getId(),series:d[l].getSeries(),group:d[l].getGroup()};f.push(m)}a={endGroup:a.getEndGroup(),startGroup:a.getStartGroup(),xMax:a.getXMax(),xMin:a.getXMin(),yMax:a.getYMax(),yMin:a.getYMin()};b===c.DvtSelectionEvent.TYPE?this.jc("selection",f,a):(a.items=f,this._trigger("selectInput",null,a))}}else b===c.DvtCategoryHideShowEvent.TYPE_HIDE||b===c.DvtCategoryHideShowEvent.TYPE_SHOW?(b=b===c.DvtCategoryHideShowEvent.TYPE_HIDE?"out":"in",this._trigger("categoryFilter",null,{category:a.getCategory(),
type:b}),this.jc("hiddenCategories",a.hiddenCategories)):b===c.DvtCategoryRolloverEvent.TYPE_OVER||b===c.DvtCategoryRolloverEvent.TYPE_OUT?(this._trigger("categoryHighlight",null,{categories:a.categories,type:b===c.DvtCategoryRolloverEvent.TYPE_OVER?"on":"off"}),this.jc("highlightedCategories",a.categories)):b===c.DvtChartViewportChangeEvent.TYPE||b===c.DvtChartViewportChangeEvent.TYPE_INPUT?(f={endGroup:a.getEndGroup(),startGroup:a.getStartGroup(),xMax:a.getXMax(),xMin:a.getXMin(),yMax:a.getYMax(),
yMin:a.getYMin()},b===c.DvtChartViewportChangeEvent.TYPE&&(this.options.xAxis||(this.options.xAxis={}),this.options.yAxis||(this.options.yAxis={}),this.options.xAxis.viewportStartGroup=null,this.options.xAxis.viewportEndGroup=null,null!=a.getXMin()&&null!=a.getXMax()&&(this.options.xAxis.viewportMin=a.getXMin(),this.options.xAxis.viewportMax=a.getXMax()),null!=a.getYMin()&&null!=a.getYMax()&&(this.options.yAxis.viewportMin=a.getYMin(),this.options.yAxis.viewportMax=a.getYMax())),this._trigger(b===
c.DvtChartViewportChangeEvent.TYPE?"viewportChange":"viewportChangeInput",null,f)):b===c.DvtDrillEvent.TYPE?this._trigger("drill",null,{id:a.getId(),series:a.getSeries(),group:a.getGroup()}):this._super(a)},vs:function(){null==this.options._resources&&(this.options._resources={});var a=this.options._resources;a.overviewGrippy=b.ba.kb("resources/internal-deps/dvt/chart/drag_horizontal.png");a.panCursorDown=b.ba.kb("resources/internal-deps/dvt/chart/hand-closed.cur");a.panCursorUp=b.ba.kb("resources/internal-deps/dvt/chart/hand-open.cur")},
getTitle:function(){return this.ka.getAutomation().getTitle()},getGroup:function(a){return this.ka.getAutomation().getGroup(a)},getSeries:function(a){return this.ka.getAutomation().getSeries(a)},getGroupCount:function(){return this.ka.getAutomation().getGroupCount()},getSeriesCount:function(){return this.ka.getAutomation().getSeriesCount()},getDataItem:function(a,b){var c=this.ka.getAutomation().getDataItem(a,b);this.Tg(c);return c},getLegend:function(){var a=this.ka.getAutomation().getLegend();this.Tg(a);
return a},getPlotArea:function(){var a=this.ka.getAutomation().getPlotArea();this.Tg(a);return a},getXAxis:function(){var a=this.ka.getAutomation().getXAxis();this.Tg(a);return a},getYAxis:function(){var a=this.ka.getAutomation().getYAxis();this.Tg(a);return a},getY2Axis:function(){var a=this.ka.getAutomation().getY2Axis();this.Tg(a);return a},getValuesAt:function(a,b){return this.ka.getValuesAt(a,b)},getContextByNode:function(a){return(a=this.getSubIdByNode(a))&&"oj-chart-tooltip"!==a.subId?a:null},
gi:function(){return{root:["groups","series"]}},whenReady:function(){return this._super()}})});