/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(b,f){(function(){b.ya("oj.ojCheckboxset",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:!1,value:void 0},refresh:function(){this._super();this.Aa()},widget:function(){return this.uqa},Yd:function(a,c){var e=[],g;this._super(a,c);b.ve.al([{W:"disabled",yc:!0},{W:"title"},{W:"placeholder"},{W:"required",Ze:!0,yc:!0}],c,this);this.wh=this.GI();void 0===c.value&&
(g=this.wh.filter(":checked"),0<g.length&&(g.each(function(){e.push(f(this).val())}),this.option("value",e,{_context:{Ic:!0,Va:!0}})),void 0===this.options.value&&(this.options.value=[]))},_ComponentCreate:function(){this._super();if(this.element.is("fieldset"))throw Error("ojCheckboxset cannot be bound to a fieldset. Use a div instead.");this.wh._ojRadioCheckbox();this.uqa=this.element.addClass("oj-checkboxset oj-component").attr("role","group").wrapInner("\x3cdiv class\x3d'oj-checkboxset-wrapper'\x3e\x3c/div\x3e");
this._on(this.Ml);this.Aa()},CG:function(){this.wh=this.GI();this.wh.filter(".oj-checkbox").each(function(){var a=void 0!==f(this).attr("disabled")?!!f(this).prop("disabled"):!1;f(this)._ojRadioCheckbox("option","disabled",a)});this.wh.not(".oj-checkbox")._ojRadioCheckbox()},Focus:function(){this.Xd().first().focus();return!0},FG:function(){},GI:function(){var a=this.element.find("input[type\x3dcheckbox]:first");0===a.length&&b.r.warn("Could not find any input type\x3dcheckbox within this element");
a=a.attr("name");return void 0===a?(a=this.element.find("input[type\x3dcheckbox]"),a.not("[name]")):this.element.find("input[type\x3dcheckbox][name\x3d"+a+"]")},qf:function(a,b,e){a=this.element.find("input[type\x3dcheckbox]:tabbable").first();this.sf(b,e,{launcher:a})},_GetMessagingLauncherElement:function(){var a=this.Xd(),c=b.ze.Yk("radioset").renderInputAs;return c&&"html"!==c?this.widget():a},Aa:function(){this.po(this.options.disabled)},Ml:{change:function(a){this.Xz(a)}},Xz:function(b){var c=
this.hg();this.hc(c,b,a)},hg:function(){return this.qs()},oi:function(a){var b;this.wh._ojRadioCheckbox("option","checked",!1);if(null!=a)for(var e=0;e<a.length;e++)b=a[e],b="[value\x3d'"+b+"']",b=this.wh.filter(b),void 0!==b&&0<b.length&&(b.prop("checked")||b._ojRadioCheckbox("option","checked",!0))},qs:function(){var a=[],b=this.wh.filter(":checked");if(0===b.length)return[];b.each(function(){a.push(f(this).val())});return a},_GetDefaultStyleClass:function(){return"oj-checkboxset"},Xd:function(){return this.GI()},
BG:function(){},Lz:function(){return!0},po:function(a){a=!!a;this.wh.each(function(){f(this).data("oj-_ojRadioCheckbox").Zv(a)});this.wh._ojRadioCheckbox("refreshDisabled")},_setOption:function(a,b,e){this._super(a,b,e);"disabled"===a&&this.po(b)},getNodeBySubId:function(a){var b=this._super(a);return b||(a=a.subId,"oj-checkboxset-inputs"!==a)?b||null:this.wh.get()},_destroy:function(){var a=this._super(),b=this.element[0].firstChild;this.wh&&this.wh._ojRadioCheckbox("destroy");f(b).contents().unwrap();
return a}});var a={er:!1}})()});