/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
var o_a=this;function o_(b,f,a){b=b.split(".");a=a||o_a;b[0]in a||!a.execScript||a.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===f?a=a[d]?a[d]:a[d]={}:a[d]=f};/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["require","ojL10n!ojtranslations/nls/ojtranslations"],function(b,f){var a={};"undefined"!==typeof window?a=window:"undefined"!==typeof self&&(a=self);var d=a.oj,c=a.oj={version:"2.1.0",build:"2072",revision:"22646",noConflict:function(){a.oj=d}};c.r={};o_("Logger",c.r,c);c.r.F6=0;o_("Logger.LEVEL_NONE",c.r.F6,c);c.r.BF=1;o_("Logger.LEVEL_ERROR",c.r.BF,c);c.r.cn=2;o_("Logger.LEVEL_WARN",c.r.cn,c);c.r.Wr=3;o_("Logger.LEVEL_INFO",c.r.Wr,c);c.r.fQ=4;o_("Logger.LEVEL_LOG",
c.r.fQ,c);c.r.w8="error";c.r.z8="warn";c.r.x8="info";c.r.y8="log";c.r.NU={level:c.r.BF,writer:null};c.r.jb=c.r.NU;c.r.error=function(a){c.r.uy(c.r.BF,c.r.w8,arguments)};o_("Logger.error",c.r.error,c);c.r.info=function(a){c.r.uy(c.r.Wr,c.r.x8,arguments)};o_("Logger.info",c.r.info,c);c.r.warn=function(a){c.r.uy(c.r.cn,c.r.z8,arguments)};o_("Logger.warn",c.r.warn,c);c.r.log=function(a){c.r.uy(c.r.fQ,c.r.y8,arguments)};o_("Logger.log",c.r.log,c);c.r.option=function(a,b){var d={},e;if(0==arguments.length){for(e in c.r.jb)c.r.jb.hasOwnProperty(e)&&
(d[e]=c.r.jb[e]);return d}if("string"===typeof a&&void 0===b)return void 0===c.r.jb[a]?null:c.r.jb[a];if("string"===typeof a)c.r.jb[a]=b;else for(e in a)a.hasOwnProperty(e)&&c.r.option(e,a[e])};o_("Logger.option",c.r.option,c);c.r.uy=function(a,b,d){if(!(c.r.option("level")<a)){var e=c.r.Fea();null!=e&&(1==d.length&&d[0]instanceof Function&&(d=[d[0]()]),e[b]&&e[b].apply?e[b].apply(e,d):e[b]&&(e[b]=Function.prototype.bind.call(e[b],e),c.r.uy(a,b,d)))}};c.r.Fea=function(){var a=null;c.r.option("writer")?
a=c.r.option("writer"):void 0!==window&&void 0!==window.console&&(a=window.console);return a};c.r.Lra=function(a){return void 0!==c.r.NU[a]};var e=a.__ojCheckpointManager;c.Uh={};o_("CHECKPOINT_MANAGER",c.Uh,c);c.Uh.dqa=function(a,b){e&&e.startCheckpoint(a,b)};o_("CHECKPOINT_MANAGER.startCheckpoint",c.Uh.dqa,c);c.Uh.Ona=function(a){e&&e.endCheckpoint(a)};o_("CHECKPOINT_MANAGER.endCheckpoint",c.Uh.Ona,c);c.Uh.RN=function(a){return e?e.getRecord(a):void 0};o_("CHECKPOINT_MANAGER.getRecord",c.Uh.RN,
c);c.Uh.t4=function(a){return e?e.matchRecords(a):[]};o_("CHECKPOINT_MANAGER.matchRecords",c.Uh.t4,c);c.Uh.Lna=function(a){c.r.info(function(){for(var b="Checkpoint Records:",d=c.Uh.t4(a),e=0;e<d.length;e++){var g=d[e],b=b+"\n"+g.name,f=g.description;null!=f&&(b=b+" ("+f+")");b+=":\n";b=b+"start: "+g.start+"\tduration: "+g.duration}return b})};o_("CHECKPOINT_MANAGER.dump",c.Uh.Lna,c);c.b=function(){this.Init()};o_("Object",c.b,c);c.b.q=null;c.b.GM="oj.Object";c.b.V7=/function\s+([\w\$][\w\$\d]*)\s*\(/;
c.b.prototype={};c.b.prototype.constructor=c.b;c.b.g=function(a,b){var d=null,e=null,g;for(g in b)if(b.hasOwnProperty(g)){d=g;e=b[g];break}var f=a.split(".");g=c[f[0]];f=f[2];if(d!=f&&null!=d){var r=g.nL;r||(r={},g.nL=r);r[d]=f;g.prototype[f]=e}};c.b.ga=function(a,b,d){c.l.Eo(a);c.l.tu(b);c.l.$M(d);void 0===b&&(b=c.b);c.l.assert(a!==b,"Class can't extend itself");var e=c.b.Lla;e.prototype=b.prototype;a.prototype=new e;a.prototype.constructor=a;a.q=a.superclass=b.prototype;d&&(a.GM=d)};o_("Object.createSubclass",
c.b.ga,c);c.b.gna=function(a,b){var d;c.l.Eo(a);c.l.assert(null!=b,"source object cannot be null");for(d in b)b.hasOwnProperty(d)&&(a.prototype[d]=b[d])};o_("Object.copyPropertiesForClass",c.b.gna,c);c.b.Lla=function(){};c.b.prototype.M2=function(a){if(void 0===a)a=this;else if(null===a)return null;return a.constructor};c.b.g("Object.prototype.getClass",{M2:c.b.prototype.M2});c.b.prototype.clone=function(){var a=new this.constructor;c.oc.$e(a,this);return a};c.b.g("Object.prototype.clone",{clone:c.b.prototype.clone});
c.b.prototype.toString=function(){return this.pP()};c.b.g("Object.prototype.toString",{toString:c.b.prototype.toString});c.b.prototype.pP=function(){return this.getTypeName()+" Object"};c.b.g("Object.prototype.toDebugString",{pP:c.b.prototype.pP});c.b.getTypeName=function(a){c.l.Eo(a);var b=a.GM;null==b&&(b=a.toString(),b=(b=c.b.V7.exec(b))?b[1]:"anonymous",a.GM=b);return b};o_("Object.getTypeName",c.b.getTypeName,c);c.b.prototype.getTypeName=function(){return c.b.getTypeName(this.constructor)};c.b.g("Object.prototype.getTypeName",
{getTypeName:c.b.prototype.getTypeName});c.b.prototype.Init=function(){c.l.fO()&&c.l.assert(this.getTypeName,"Not an oj.Object");var a=this.constructor;a.Wl||c.b.rK(a)};c.b.g("Object.prototype.Init",{Init:c.b.prototype.Init});c.b.Pna=function(a){c.l.Eo(a);a.Wl||c.b.rK(a)};o_("Object.ensureClassInitialization",c.b.Pna,c);c.b.prototype.Ko=function(a){return this===a};c.b.g("Object.prototype.equals",{Ko:c.b.prototype.Ko});c.b.e2=function(a,b){c.l.Eo(b);return b.bind(a)};o_("Object.createCallback",c.b.e2,
c);c.b.rK=function(a){c.l.fO()&&(c.l.Eo(a),c.l.assert(!a.Wl));a.Wl=!0;var b=a.q;b&&((b=b.constructor)&&!b.Wl&&c.b.rK(b),c.b.D$(a));(b=a.InitClass||null)||(b=a.InitClass);b&&b.call(a)};c.b.mh=function(a,b){if(a===b)return!0;if(typeof a!==typeof b||null===a||null===b)return!1;if(a.constructor===b.constructor){if(Array.isArray(a))return c.b.Laa(a,b);if(a.constructor===Object)return c.b.Yv(a,b);if(a.valueOf&&"function"===typeof a.valueOf)return a.valueOf()===b.valueOf()}return!1};o_("Object.compareValues",
c.b.mh,c);c.b.Laa=function(a,b){if(a.length!==b.length)return!1;for(var d=0,e=a.length;d<e;d++)if(!c.b.mh(a[d],b[d]))return!1;return!0};c.b.hU=function(a,b){if(!a)return!b||0==b.length;if(!b)return!a||0==a.length;if(a.length!=b.length)return!1;for(var d=0;d<a.length;d++)if(a[d]!=b[d]&&(-1==a.indexOf(b[d])||-1==b.indexOf(a[d])))return!1;return!0};c.b.Yv=function(a,b){var d,e=!1;if(a===b)return!0;if(!(a instanceof Object&&b instanceof Object)||a.constructor!==b.constructor)return!1;for(d in a)if(e||
(e=!0),a.hasOwnProperty(d)&&(!b.hasOwnProperty(d)||a[d]!==b[d]&&("object"!==typeof a[d]||!c.b.Yv(a[d],b[d]))))return!1;for(d in b)if(e||(e=!0),b.hasOwnProperty(d)&&!a.hasOwnProperty(d))return!1;return e?!0:JSON.stringify(a)===JSON.stringify(b)};c.b.Pf=function(a){var b;if(void 0===a||null===a)return!0;for(b in a)if(a.hasOwnProperty(b))return!1;return!0};c.b.D$=function(a){c.b.nL&&c.b.jT(a,a.q)};c.b.jT=function(a,b){if(b){var d=b.constructor;c.b.jT(a,d.q);var d=d.nL,e;if(d)for(e in d)if(d.hasOwnProperty(e)){var g=
d[e];if(e!=g){var f=a.prototype;!f.hasOwnProperty(e)&&f.hasOwnProperty(g)?f[e]=f[g]:!f.hasOwnProperty(g)&&f.hasOwnProperty(e)&&(f[g]=f[e])}}}};c.Js=function(){return"function"===typeof define&&define.amd};c.l={};o_("Assert",c.l,c);c.l.Una=function(){c.l.DEBUG=!0};o_("Assert.forceDebug",c.l.Una,c);c.l.bna=function(){c.l.DEBUG=!1};o_("Assert.clearDebug",c.l.bna,c);c.l.fO=function(){return!0==c.l.DEBUG};o_("Assert.isDebug",c.l.fO,c);c.l.assert=function(a,b){if(c.l.DEBUG&&!a){var d=b||"",e;if(2<arguments.length){d+=
"(";for(e=2;e<arguments.length;e+=1)d+=arguments[e];d+=")"}c.l.Qd(d)}};o_("Assert.assert",c.l.assert,c);c.l.Zb=function(){c.l.DEBUG&&c.l.Qd("Abstract function called")};o_("Assert.failedInAbstractFunction",c.l.Zb,c);c.l.Bd=function(a,b,d){var e;c.l.DEBUG&&(null!=a?(c.l.Oh(b,"function",null,0,!1),e=b.prototype,e.isPrototypeOf(a)||c.l.Qd("object '"+a+"' doesn't match prototype "+e,0,d)):c.l.Qd("null object doesn't match prototype "+e,0,d))};o_("Assert.assertPrototype",c.l.Bd,c);c.l.Sma=function(a,b,
d){var e;c.l.DEBUG&&null!=a&&(null!=a?(c.l.Oh(b,"function",null,0,!1),e=b.prototype,e.isPrototypeOf(a)||c.l.Qd("object '"+a+"' doesn't match prototype "+e,0,d)):c.l.Qd("null object doesn't match prototype "+e,0,d))};o_("Assert.assertPrototypeOrNull",c.l.Sma,c);c.l.Tma=function(a,b,d,e){c.l.DEBUG&&(b=b.prototype,d=d.prototype,b.isPrototypeOf(a)||d.isPrototypeOf(a)||c.l.Qd("object '"+a+"' doesn't match prototype "+b+" or "+d,0,e))};o_("Assert.assertPrototypes",c.l.Tma,c);c.l.Mma=function(a){c.l.DEBUG&&
a&&void 0===a.nodeType&&c.l.Qd(a+" is not a DOM Node")};o_("Assert.assertDomNodeOrNull",c.l.Mma,c);c.l.ZM=function(a){c.l.DEBUG&&(a&&void 0!==a.nodeType||c.l.Qd(a+" is not a DOM Node"))};o_("Assert.assertDomNode",c.l.ZM,c);c.l.YM=function(a,b){c.l.DEBUG&&(c.l.ZM(a),1!==a.nodeType?c.l.Qd(a+" is not a DOM Element"):b&&a.nodeName!==b&&c.l.Qd(a+" is not a "+b+" Element"))};o_("Assert.assertDomElement",c.l.YM,c);c.l.Lma=function(a,b){c.l.DEBUG&&null!=a&&(c.l.ZM(a),1!==a.nodeType?c.l.Qd(a+" is not a DOM Element"):
b&&a.nodeName!==b&&c.l.Qd(a+" is not a "+b+" Element"))};o_("Assert.assertDomElementOrNull",c.l.Lma,c);c.l.Oh=function(a,b,d,e,g){!c.l.DEBUG||null==a&&g||typeof a===b||(a=a+" is not of type "+b,d&&(a=d+a),c.l.Qd(a))};o_("Assert.assertType",c.l.Oh,c);c.l.Hf=function(a,b){c.l.DEBUG&&c.l.Oh(a,"object",b,0,!1)};o_("Assert.assertObject",c.l.Hf,c);c.l.K1=function(a,b){c.l.DEBUG&&c.l.Oh(a,"object",b,0,!0)};o_("Assert.assertObjectOrNull",c.l.K1,c);c.l.Oma=function(a,b){c.l.DEBUG&&(c.l.Oh(a,"string",b,0,!1),
c.l.assert(0<a.length,"empty string"))};o_("Assert.assertNonEmptyString",c.l.Oma,c);c.l.Fo=function(a,b){c.l.DEBUG&&c.l.Oh(a,"string",b,0,!1)};o_("Assert.assertString",c.l.Fo,c);c.l.$M=function(a,b){c.l.DEBUG&&c.l.Oh(a,"string",b,0,!0)};o_("Assert.assertStringOrNull",c.l.$M,c);c.l.Eo=function(a,b){c.l.DEBUG&&c.l.Oh(a,"function",b,0,!1)};o_("Assert.assertFunction",c.l.Eo,c);c.l.tu=function(a,b){c.l.DEBUG&&c.l.Oh(a,"function",b,0,!0)};o_("Assert.assertFunctionOrNull",c.l.tu,c);c.l.J1=function(a,b){c.l.DEBUG&&
c.l.Oh(a,"boolean",b,0,!1)};o_("Assert.assertBoolean",c.l.J1,c);c.l.jm=function(a,b){c.l.DEBUG&&c.l.Oh(a,"number",b,0,!1)};o_("Assert.assertNumber",c.l.jm,c);c.l.Qma=function(a,b){c.l.DEBUG&&c.l.Oh(a,"number",b,0,!0)};o_("Assert.assertNumberOrNull",c.l.Qma,c);c.l.UD=function(a,b){c.l.DEBUG&&!Array.isArray(a)&&(void 0===b&&(b=a+" is not an array"),c.l.Qd(b))};o_("Assert.assertArray",c.l.UD,c);c.l.wy=function(a,b){c.l.DEBUG&&null!=a&&!Array.isArray(a)&&(void 0===b&&(b=a+" is not an array"),c.l.Qd(b))};
o_("Assert.assertArrayOrNull",c.l.wy,c);c.l.Pma=function(a,b){c.l.DEBUG&&!isNaN(a)&&(void 0===b&&(b=a+" is convertible to a number"),c.l.Qd(b))};o_("Assert.assertNonNumeric",c.l.Pma,c);c.l.Rma=function(a,b){c.l.DEBUG&&isNaN(a)&&(void 0===b&&(b=a+" is not convertible to a number"),c.l.Qd(b))};o_("Assert.assertNumeric",c.l.Rma,c);c.l.Nma=function(a,b,d){var e;if(null==a||void 0===b[a.toString()]){if(void 0===d){d=" is not in set: {";for(e in b)b.hasOwnProperty(e)&&(d+=e,d+=",");d=a+(d+"}")}c.l.Qd(d)}};
o_("Assert.assertInSet",c.l.Nma,c);c.l.Qd=function(a,b,d){b="Assertion";d&&(b+=" ("+d+")");b+=" failed: ";void 0!==a&&(b+=a);throw Error(b);};o_("Assert.assertionFailed",c.l.Qd,c);var g=a.__oj_Assert_DEBUG;void 0!==g&&(c.l.DEBUG=g);c.Pg=function(){this.Init()};o_("EventSource",c.Pg,c);c.b.ga(c.Pg,c.b,"oj.EventSource");c.Pg.prototype.Init=function(){this.jd=[];c.Pg.q.Init.call(this)};c.b.g("EventSource.prototype.Init",{Init:c.Pg.prototype.Init});c.Pg.prototype.on=function(a,b){var d=!1,c;for(c=0;c<
this.jd.length;c++)if(this.jd[c].eventType==a&&this.jd[c].eventHandlerFunc==b){d=!0;break}d||this.jd.push({eventType:a,eventHandlerFunc:b})};c.b.g("EventSource.prototype.on",{on:c.Pg.prototype.on});c.Pg.prototype.off=function(a,b){var d;for(d=this.jd.length-1;0<=d;d--)if(this.jd[d].eventType==a&&this.jd[d].eventHandlerFunc==b){this.jd.splice(d,1);break}};c.b.g("EventSource.prototype.off",{off:c.Pg.prototype.off});c.Pg.prototype.handleEvent=function(a,b){var d,c;for(d=0;d<this.jd.length;d++)if(c=this.jd[d],
c.eventType==a&&(c=c.eventHandlerFunc.apply(this,Array.prototype.slice.call(arguments).slice(1)),!1===c))return!1;return!0};c.b.g("EventSource.prototype.handleEvent",{handleEvent:c.Pg.prototype.handleEvent});c.ba={};o_("Config",c.ba,c);c.ba.Ag=function(){var a;if(c.Js())return c.l.assert(void 0!==f,"ojtranslations module must be defined"),a=f._ojLocale_,"root"==a?"en":a;a=c.ba.Mt;null==a&&((a=document.documentElement.lang)||(a=void 0===navigator?"en":(navigator.language||navigator.userLanguage||"en").toLowerCase()),
c.ba.Mt=a=a.toLowerCase());return a};o_("Config.getLocale",c.ba.Ag,c);c.ba.Wpa=function(a,d){if(c.Js()){var e=["ojL10n!ojtranslations/nls/"+a+"/ojtranslations"];c.Ja&&e.push("ojL10n!ojtranslations/nls/"+a+"/localeElements");b(e,function(a,b){f=a;b&&c.Ja.S9(b);d&&d()})}else c.ba.Mt=a,d&&d()};o_("Config.setLocale",c.ba.Wpa,c);c.ba.kb=function(a){var d=/^\/|:/;return null==a||d.test(a)?a:(d=c.ba.jka)?d+("/"==d.charAt(d.length-1)?"":"/")+a:c.Js()?(d=b.toUrl("ojs/_foo_"),d.replace(/[^\/]*$/,"../"+a)):
a};o_("Config.getResourceUrl",c.ba.kb,c);c.ba.Xpa=function(a){c.ba.jka=a};o_("Config.setResourceBaseUrl",c.ba.Xpa,c);c.ba.Vpa=function(a){c.ba.K$=a};o_("Config.setAutomationMode",c.ba.Vpa,c);c.ba.EN=function(){return c.ba.K$};o_("Config.getAutomationMode",c.ba.EN,c);c.ba.B3=function(){var a="Oracle JET Version: "+c.version+"\n",a=a+("Oracle JET Revision: "+c.revision+"\n");window.navigator&&(a+="Browser: "+window.navigator.userAgent+"\n",a+="Browser Platform: "+window.navigator.platform+"\n");$&&
($.fn&&(a+="jQuery Version: "+$.fn.jquery+"\n"),$.ui&&$.ui.version&&(a+="jQuery UI Version: "+$.ui.version+"\n"));c.ia&&(a+="Knockout Version: "+c.ia.R9()+"\n");window.Mpa&&(a+="Require Version: "+window.Mpa.version+"\n");return a};o_("Config.getVersionInfo",c.ba.B3,c);c.ba.ipa=function(){console.log(c.ba.B3())};o_("Config.logVersionInfo",c.ba.ipa,c);c.Ma=function(){};c.Ma.sl={zF:"ie",NP:"firefox",tQ:"safari",g6:"chrome",Cv:"unknown"};c.Ma.Zm={EQ:"trident",QF:"webkit",QP:"gecko",Cv:"unknown"};c.Ma.Xi=
{h7:"Windows",Z6:"Solaris",hQ:"Mac",Cv:"Unknown",BP:"Android",AF:"IOS",G6:"Linux"};c.Ma.Gy=function(){var a;c.Fa.Ji(a)&&(a=navigator.userAgent);a=a.toLowerCase();var b=c.Fa.nr(a),d=c.Ma.Nba;if(d&&d.hashCode===b)return{os:d.os,browser:d.browser,browserVersion:d.browserVersion,engine:d.engine,engineVersion:d.engineVersion,hashCode:d.hashCode};var d=c.Ma.Xi.Cv,e=c.Ma.sl.Cv,g=0,f=c.Ma.Zm.Cv,r=0;-1<a.indexOf("iphone")||-1<a.indexOf("ipad")?d=c.Ma.Xi.AF:-1<a.indexOf("mac")?d=c.Ma.Xi.hQ:-1<a.indexOf("sunos")?
d=c.Ma.Xi.Z6:-1<a.indexOf("android")?d=c.Ma.Xi.BP:-1<a.indexOf("linux")?d=c.Ma.Xi.G6:-1<a.indexOf("win")&&(d=c.Ma.Xi.h7);-1<a.indexOf("msie")?(e=c.Ma.sl.zF,g=c.Ma.zi(a,/msie (\d+[.]\d+)/),a.indexOf("trident")&&(f=c.Ma.Zm.EQ,r=c.Ma.zi(a,/trident\/(\d+[.]\d+)/))):-1<a.indexOf("trident")?(e=c.Ma.sl.zF,g=c.Ma.zi(a,/rv:(\d+[.]\d+)/),a.indexOf("trident")&&(f=c.Ma.Zm.EQ,r=c.Ma.zi(a,/trident\/(\d+[.]\d+)/))):-1<a.indexOf("chrome")?(e=c.Ma.sl.g6,g=c.Ma.zi(a,/chrome\/(\d+[.]\d+)/),f=c.Ma.Zm.QF,r=c.Ma.zi(a,
/applewebkit\/(\d+[.]\d+)/)):-1<a.indexOf("safari")?(e=c.Ma.sl.tQ,g=c.Ma.zi(a,/version\/(\d+[.]\d+)/),f=c.Ma.Zm.QF,r=c.Ma.zi(a,/applewebkit\/(\d+[.]\d+)/)):-1<a.indexOf("firefox")&&(e=c.Ma.sl.NP,g=c.Ma.zi(a,/rv:(\d+[.]\d+)/),f=c.Ma.Zm.QP,r=c.Ma.zi(a,/gecko\/(\d+)/));d=c.Ma.Nba={hashCode:b,os:d,browser:e,browserVersion:g,engine:f,engineVersion:r};return{os:d.os,browser:d.browser,browserVersion:d.browserVersion,engine:d.engine,engineVersion:d.engineVersion,hashCode:d.hashCode}};c.Ma.zi=function(a,b){var d=
a.match(b);return d&&(d=d[1])?parseFloat(d):0};c.ze={};c.ze.K4=function(a){var b=document.getElementsByClassName(a).item(0);null===b&&(b=document.createElement("meta"),b.className=a,document.head.appendChild(b));if((b=window.getComputedStyle(b))&&(b=b.getPropertyValue("font-family"))&&"none"!=b&&(b=b.replace(/^['"]+|\s+|\\|(;\s?})+|['"]$/g,""))){try{b=JSON.parse(b)}catch(d){return c.r.error("Error parsing json for selector "+a+".\nString being parsed is "+b+"\n"+d),null}return b}c.r.info("No json found for selector "+
a);return null};c.ze.Yk=function(a){a=a.toLowerCase();null==c.ze.MO&&(c.ze.MO={});var b=c.ze.MO[a];null==b&&(b=c.ze.K4("oj-"+a+"-option-defaults"),null==b&&(b={}),c.ze.MO[a]=b);return b};c.qb=function(){};o_("ResponsiveUtils",c.qb,c);c.qb.Yi={SM:"sm",MD:"md",LG:"lg",XL:"xl",XXL:"xxl"};o_("ResponsiveUtils.SCREEN_RANGE",c.qb.Yi,c);c.qb.Sr={SM_UP:"sm-up",MD_UP:"md-up",LG_UP:"lg-up",XL_UP:"xl-up",XXL_UP:"xxl-up",SM_ONLY:"sm-only",MD_ONLY:"md-only",LG_ONLY:"lg-only",XL_ONLY:"xl-only",MD_DOWN:"md-down",
LG_DOWN:"lg-down",XL_DOWN:"xl-down",HIGH_RESOLUTION:"high-resolution"};o_("ResponsiveUtils.FRAMEWORK_QUERY_KEY",c.qb.Sr,c);c.qb.Jp={};c.qb.Jp[c.qb.Yi.SM]=0;c.qb.Jp[c.qb.Yi.MD]=1;c.qb.Jp[c.qb.Yi.LG]=2;c.qb.Jp[c.qb.Yi.XL]=3;c.qb.Jp[c.qb.Yi.XXL]=4;c.qb.Wda=function(a){var b=document.getElementsByClassName(a).item(0);null===b&&(b=document.createElement("meta"),b.className=a,document.head.appendChild(b));return window.getComputedStyle(b).getPropertyValue("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,
"")};c.qb.Du=function(a){a=c.qb.Wda("oj-mq-"+a);return"null"==a?null:a};o_("ResponsiveUtils.getFrameworkQuery",c.qb.Du,c);c.qb.compare=function(a,b){var d=c.qb.Jp[a],e=c.qb.Jp[b];if(void 0==d)throw"size1 param "+a+" illegal, please use one of the screen size constants like oj.ResponsiveUtils.SCREEN_RANGE.MD";if(void 0==e)throw"size2 param "+b+" illegal, please use one of the screen size constants like oj.ResponsiveUtils.SCREEN_RANGE.MD";return d-e};o_("ResponsiveUtils.compare",c.qb.compare,c);c.Fa=
{};o_("StringUtils",c.Fa,c);c.Fa.N9=/^\s*|\s*$/g;c.Fa.Pf=function(a){return null===a?!0:0===c.Fa.trim(a).length};o_("StringUtils.isEmpty",c.Fa.Pf,c);c.Fa.Ji=function(a){return void 0===a||c.Fa.Pf(a)?!0:!1};o_("StringUtils.isEmptyOrUndefined",c.Fa.Ji,c);c.Fa.od=function(a){return null!==a&&("string"===typeof a||a instanceof String)};o_("StringUtils.isString",c.Fa.od,c);c.Fa.trim=function(a){return c.Fa.od(a)?a.replace(c.Fa.N9,""):a};o_("StringUtils.trim",c.Fa.trim,c);c.Fa.nr=function(a){var b=0;if(0===
a.length)return b;for(var d=0;d<a.length;d++)b=(b<<5)-b+a.charCodeAt(d),b&=b;return b};c.oc={};o_("CollectionUtils",c.oc,c);c.oc.$e=function(a,b,d,e,g){return c.oc.oU(a,b,d,e,g,0)};o_("CollectionUtils.copyInto",c.oc.$e,c);c.oc.isPlainObject=function(a){if("object"===typeof a)try{if(a.constructor&&a.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!0}catch(b){}return!1};o_("CollectionUtils.isPlainObject",c.oc.isPlainObject,c);c.oc.oU=function(a,b,d,e,g,f){var r,s,q;if(a&&b&&a!==b){q=Object.keys(b);
for(var t=0;t<q.length;t++){r=q[t];s=d?d(r):r;r=b[r];var v=!1;if(e&&f<g){var w=a[s];c.oc.isPlainObject(w)&&c.oc.isPlainObject(r)&&(v=!0,c.oc.oU(w,r,d,!0,g,f+1))}v||(a[s]=r)}}return a};c.ha={};o_("Translations",c.ha,c);c.ha.bP=function(a){c.ha.pH=a};o_("Translations.setBundle",c.ha.bP,c);c.ha.i3=function(a){return c.ha.PW(a)};o_("Translations.getResource",c.ha.i3,c);c.ha.Mb=function(a,b){return null==a?null:c.ha.Wca(a,b)};o_("Translations.applyParameters",c.ha.Mb,c);c.ha.A=function(a,b){var d=c.ha.PW(a);
if(null==d)return a;var e={};2<arguments.length?e=Array.prototype.slice.call(arguments,1):2==arguments.length&&(e=arguments[1],"object"===typeof e||e instanceof Array||(e=[e]));return c.ha.Mb(d,e)};o_("Translations.getTranslatedString",c.ha.A,c);c.ha.lE=function(a){a=c.ha.QV()[a];var b,d;if(null==a)return{};b={};for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b};o_("Translations.getComponentTranslations",c.ha.lE,c);c.ha.PW=function(a){a=a?a.split("."):[];var b=c.ha.QV(),d=a.length,e=0,g=a[e];for(c.l.Hf(b);0<
--d&&b;)b=b[g],e++,g=a[e];return b?b[g]||null:null};c.ha.Wca=function(a,b){var d=a.length,c=[],e=null,g=!1,f=!1,s=!1,q=!1,t,v;for(v=0;v<d;v++){var w=a.charAt(v),u=!1;if(g)u=!0,g=!1;else switch(w){case "$":g=!0;break;case "{":q||(f||(t=!1,e=[]),f=!0);break;case "}":f&&0<e.length&&(f=b[e.join("")],c.push(void 0===f?"null":f));f=!1;break;case "[":f||(s?q=!0:s=!0);break;case "]":q?q=!1:s=!1;break;default:u=!0}u&&(f?","==w||" "==w?t=!0:t||e.push(w):q||c.push(w))}return c.join("")};c.ha.QV=function(){var a=
c.ha.pH;return a?a:c.Js()?(c.l.assert(void 0!==f,"ojtranslations module must be defined"),f):{}};return c});