/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","jqueryui-amd/core","jqueryui-amd/widget","ojs/ojmessaging"],function(b,f){function a(a,b){function c(){var a=f(this),d=a.data(k);if(null!=d)for(var e=0;e<d.length;e++){var g=a.data("oj-"+d[e]);null!=g&&b(g)}}var d=f(a);d.hasClass(l)&&c.call(a);d.find("."+l).each(c)}function d(a){this.GN=function(){return a}}function c(a,b,c,d,g,f,h){var k=c,m=!1,p={};delete d[g];Object.defineProperty(d,g,{get:function(){if(m||null!=a.cu)return k;var c=f(h?h():g);return e([b,c,k],p)},
set:function(b){k=b;null!=a.cu?p[a.cu]=!0:m=!0},enumerable:!0})}function e(a,b){for(var c=void 0,d=0;d<a.length;d++){var e=a[d];void 0!==e&&(c=f.isPlainObject(e)?g(f.isPlainObject(c)?[c,e]:[e],d==a.length-1?null:b,null):e)}return c}function g(a,b,c){for(var d={},e=a.length,h=0;h<e;h++)for(var k=a[h],m=Object.keys(k),p=0;p<m.length;p++){var n=m[p],l=null==b?null:null==c?n:c+"."+n;if(null==b||!b[l]){var J=k[n];void 0!==J&&(d[n]=f.isPlainObject(J)?g(f.isPlainObject(d[n])?[d[n],J]:[J],b,l):J)}}return d}
function h(){return!0}b.Components={};o_("Components",b.Components,b);b.Components.Om=function(a){b.Components.PU=f.widget.extend(b.Components.PU||{},a)};o_("Components.setDefaultOptions",b.Components.Om,b);b.Components.R2=function(){return b.Components.PU||{}};o_("Components.getDefaultOptions",b.Components.R2,b);b.Components.nh=function(a){return new d(a)};o_("Components.createDynamicPropertyGetter",b.Components.nh,b);b.Components.Of=function(a,b){var c=f(a),d=c.data(k);return d&&(null==b?b=d[0]:
0>d.indexOf(b)&&(b=void 0),null!=b&&(d=c[b],"function"===typeof d))?d.bind(c):null};o_("Components.getWidgetConstructor",b.Components.Of,b);b.Components.Sf=function(c){b.v.A2(c);a(c,function(a){a.sn()})};o_("Components.subtreeAttached",b.Components.Sf,b);b.Components.Kg=function(b){a(b,function(a){a.li()})};o_("Components.subtreeDetached",b.Components.Kg,b);b.Components.Rm=function(c){b.v.A2(c);a(c,function(a){a.yl()})};o_("Components.subtreeShown",b.Components.Rm,b);b.Components.gp=function(b){a(b,
function(a){a.xl()})};o_("Components.subtreeHidden",b.Components.gp,b);b.Components.dO=function(a){var b=a.data(k);return f.isArray(b)&&-1<b.indexOf("ojPopup")&&a.is("."+l)?!0:!1};b.Components.tn="data-oj-container";var k="oj-component-names",l="oj-component-initnode";f.widget("oj.baseComponent",{options:{contextMenu:null,rootAttributes:null,optionChange:void 0,destroy:void 0},refresh:function(){this.Wt=null},_createWidget:function(a,b){this.wZ=this.options||{};this.lU=a||{};this._super(a,b);this.KQ()},
rA:function(){var a=this.options.rootAttributes;if(a){var b=this.widget();if(null!=b){var c=a["class"];c&&b.addClass(c);if(c=a.style){var d=b.attr("style");d?b.attr("style",d+";"+c):b.attr("style",c)}a=f.extend({},a);delete a["class"];delete a.style;b.attr(a);delete a.id;a=Object.keys(a);if(a.length)throw Error("Unsupported values passed to rootAttributes option: "+a.toString());}}},_create:function(){this.Tv(this.element);this.Yd(this.wZ,this.lU);delete this.wZ;delete this.lU;this._ComponentCreate();
this.mf();this.element.addClass(l)},Yd:function(a,b){this.kla(a,b);this.oga(b)},_ComponentCreate:function(){var a=this.element,b=this.widgetName,c=a.data(k);c||(c=[],a.data(k,c));0>c.indexOf(b)&&c.push(b)},mf:function(){this.rA();this.Fi=this.eventNamespace+"contextMenu";this.r0(!0)},KQ:f.noop,Tv:function(){},E9:function(a){var b=this;this.JL=[];f.each(a,function(a,c){var d={},e=c.attributes;b.JL.push({element:c,attributes:d});f.each(e,function(a,b){var e=b.name;d[e]={attr:b.value,prop:f(c).prop(e)}})})},
sR:function(a){var b=this.JL;if(void 0===b)return null;a=a[0];for(var c=0,d=b.length;c<d;c++){var e=b[c];if(e.element===a)return e.attributes}return{}},Cs:function(){},k9:function(){f.each(this.JL,function(a,b){var c=f(b.element),d=b.attributes;if(1===c.length){for(var e=b.element.attributes,g=[],h=0,k=e.length;h<k;h++)e[h].name in d||g.push(e[h].name);h=0;for(k=g.length;h<k;h++)c.removeAttr(g[h]);for(var m in d)c.attr(m,d[m].attr)}})},Wz:function(){return this.widgetFullName},Iv:function(a,b,c){return b==
c},A:function(a,c){var d={},e;2<arguments.length?d=Array.prototype.slice.call(arguments,1):2==arguments.length&&(d=arguments[1],"object"===typeof d||d instanceof Array||(d=[d]));e=this.option(n+a);return null==e?a:b.ha.Mb(e.toString(),d)},getNodeBySubId:function(a){return null==a||null==a.subId?this.element?this.element[0]:null:null},getSubIdByNode:function(){return null},destroy:function(){this._trigger("destroy");this._super();this.j_();this.element.removeClass(l);this.widget().removeClass("oj-disabled");
this.zL(this.element);var a=this.element,b=this.widgetName,c=a.data(k);c&&(b=c.indexOf(b),0<=b&&(c.splice(b,1),0===c.length&&a.removeData(k)));this.Cs();this.bY?this.element.attr("contextmenu",this.bY):this.element.removeAttr("contextmenu");this.Wt=null},option:function(a,b){if(0===arguments.length)return f.widget.extend({},this.options);var c=arguments[0],d=c,e=null,g={};if("string"===typeof c){var d={},h=c.split("."),c=h.shift();if(h.length){var e=h.join("."),k;try{1<arguments.length&&(this.cu=
e),k=d[c]=f.widget.extend({},this.options[c])}finally{this.cu=null}for(c=0;c<h.length-1;c++)k[h[c]]=k[h[c]]||{},k=k[h[c]];c=h.pop();if(1===arguments.length)return void 0===k[c]?null:k[c];k[c]=b}else{if(1===arguments.length)return void 0===this.options[c]?null:this.options[c];d[c]=b}g=arguments[2]||g}else g=arguments[1]||g;null!=e&&(g=f.widget.extend({},g,{subkey:e}));(e=g?g._context:null)&&e.Va?this.Mga(d,g):this._setOptions(d,g);return this},Mga:function(a,b){for(var c in a){var d=a[c],e=this.options[c];
this.options[c]=d;this.uZ(c,d,e,b)}},_setOptions:function(a,b){for(var c in a)this._setOption(c,a[c],b);return this},_setOption:function(a,b,c){var d=this.options[a];if("disabled"===a)this.options[a]=b,this.widget().toggleClass("oj-disabled",!!b).attr("aria-disabled",b),b&&this.zL(this.widget());else{try{var e=null==c?null:c.subkey;null!=e&&(this.cu=e);this._super(a,b)}finally{this.cu=null}"contextMenu"===a&&this.r0(!1)}this.uZ(a,b,d,c);return this},uZ:function(a,b,c,d){var e=!1,g=null,h=!1,k=null,
m=null,p;d&&(e=d.changed,g=d._context)&&(k=g.originalEvent,h=void 0===g.Ic?null!=k:g.Ic,m=g.yr,p=g.Hj);if(e||!this.Iv(a,c,b))m=m||{},m.writeback=h?"shouldWrite":"shouldNotWrite",a={option:a,previousValue:c,value:b,optionMetadata:m},null!=p&&(a=f.extend({},p,a)),this._trigger("optionChange",k,a)},_trigger:function(a,b,c){var d=this.options[a];c=c||{};b=f.Event(b,p);b.type=(this.widgetEventPrefix+a).toLowerCase();b.target=this.element[0];this.element.trigger(b,c);return!(f.isFunction(d)&&!1===d.apply(this.element[0],
[b].concat(c))||b.isDefaultPrevented())},oga:function(a){var b=this.element.attr("contextmenu");this.bY=b;!b||"contextMenu"in a||this.option("contextMenu","#"+b,{_context:{Va:!0}})},r0:function(a){this.j_();if(this.options.contextMenu){var c=this.widget(),d=this.element;a&&!d.is(c)&&d.removeAttr("contextmenu");(a=f(this.options.contextMenu).attr("id"))&&c.attr("contextmenu",a);var e=this;this.BZ=function(a){121==a.which&&a.shiftKey&&e.ZV().is(":visible")&&a.preventDefault()};var g=!1,h=!1,k,m,p,n=
null,l=function(a,b,d){g=d;var f=e.XI();if(g)c.one("touchend"+e.Fi,function(){f.Hs(!0);setTimeout(function(){f.Hs(!1)},50)});"touchstart"===n&&"contextmenu"===a.type||"contextmenu"===n&&"touchstart"===a.type?(n=null,clearTimeout(p)):a.isDefaultPrevented()||a.originalEvent&&a.originalEvent.defaultPrevented||e.Zd()||(e.qf(f,a,b),!e.ZV().is(":visible")||(a.preventDefault(),document.addEventListener("keyup",e.BZ),"touchstart"!==a.type&&"contextmenu"!==a.type))||(n=a.type,p=setTimeout(function(){n=null},
300))};this.aU=function(a){g&&(a.preventDefault(),a.stopPropagation(),g=!1)};c[0].addEventListener("click",this.aU,!0);c.on("touchstart"+this.Fi+" mousedown"+this.Fi+" keydown"+this.Fi+" ",function(a){if("mousedown"!==a.type||!e.XI().Hs()){g=!1;if("touchstart"===a.type&&1===a.originalEvent.touches.length){var b=a.originalEvent.touches[0];k=b.pageX;m=b.pageY;h=!0;this.WH=setTimeout(l.bind(void 0,a,"touch",!0),750)}return!0}}).on("touchmove"+this.Fi,function(a){a=a.originalEvent.touches[0];if(5<Math.abs(k-
a.pageX)||5<Math.abs(m-a.pageY))h=!1,clearTimeout(this.WH);return!0}).on("touchend"+this.Fi+" touchcancel"+this.Fi,function(){h=!1;clearTimeout(this.WH);return!0}).on("keydown"+this.Fi+" contextmenu"+this.Fi,function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&l(a,h?"touch":"keydown"===a.type?"keyboard":"mouse",!1);return!0}).addClass(b.v.Sd()?"oj-menu-context-menu-launcher":void 0)}},Z_:function(){this.Zp=f(this.options.contextMenu).first();this.ZA=this.Zp.data("oj-ojMenu");if(!this.ZA)throw Error('"contextMenu" option set to "'+
this.options.contextMenu+'", which does not reference a valid JET Menu.');var a=this;this.Zp.on("oj__dismiss"+this.Fi,function(){document.removeEventListener("keyup",a.BZ)})},XI:function(){this.ZA||this.Z_();return this.ZA},ZV:function(){this.Zp||this.Z_();return this.Zp},j_:function(){this.widget().removeAttr("contextmenu").off(this.Fi).removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",this.aU,!0);this.Zp&&this.Zp.off(this.Fi);clearTimeout(this.WH);this.Zp=this.ZA=void 0},
qf:function(a,b,c){this.sf(b,c)},sf:function(a,b,c,d,e){b={launcher:this.element,position:{mouse:{my:"start top",at:"start bottom",of:a,collision:"flipfit"},touch:{my:"start\x3e40 center",at:"start bottom",of:a,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher",collision:"flipfit"}}[b]};var g={initialFocus:"menu"};c=e?f.extend(b,c,g):f.extend(!0,b,c,g);e=this.XI();e.zA=!0;e.open(a,c,d);e.zA=!1},zL:function(a){a.removeClass("oj-hover oj-focus oj-active");a.find(".oj-hover").removeClass("oj-hover");
a.find(".oj-focus").removeClass("oj-focus");a.find(".oj-active").removeClass("oj-active")},_hoverable:function(a){this._on(a,{mouseenter:function(a){f(a.currentTarget).hasClass("oj-disabled")||f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){f(a.currentTarget).removeClass("oj-hover")}})},_focusable:function(a){this._on(a,{focusin:function(a){f(a.currentTarget).addClass("oj-focus")},focusout:function(a){f(a.currentTarget).removeClass("oj-focus")}})},Bn:function(a){this._on(a,{mousedown:function(a){f(a.currentTarget).addClass("oj-active")},
mouseup:function(a){f(a.currentTarget).removeClass("oj-active")}})},Np:function(a){if(a){f(a).off(this.eventNamespace);var b=this.bindings;b&&(this.bindings=f(b.not(a)))}},i3:function(a){return this.option(n+a)},ec:function(){return b.v.um()},sn:function(){this.Wt=null},li:function(){this.Wt=null;this.zL(this.widget())},yl:function(){},xl:function(){},Zd:function(){return this.options.disabled||this.gT?!0:!1},Zv:function(a){this.gT=a},Aea:function(){var a=[],c=this,d=0;this.k1(function(e){e=0==d?
c.Wz():e.widgetFullName;d++;var g=b.ha.lE(e);null==g||f.isEmptyObject(g)||a.push(e)});var e=a.length;return 0<e?function(){if(1==e)return b.ha.lE(a[0]);for(var c={},d=e-1;0<=d;d--)f.widget.extend(c,b.ha.lE(a[d]));return c}:null},vda:function(){if(!this.Wt){var a={};this.Wt=a;for(var c=this.element[0],d=c,e=[];d;){var g=d.getAttribute,g=g?g.call(d,b.Components.tn):null;null!=g&&e.push(g);d=d.parentNode}a.containers=e;a.element=c}return this.Wt},kla:function(a,b){var d=this.options,e=this.Aea(),g=b[m];
null==e||void 0!==g&&!f.isPlainObject(g)||c(this,void 0,b[m],d,m,e);this.Aha(a,b)},Aha:function(a,g){var h=this.options,k={},m=[];this.k1(function(a){m.push(a.widgetName)});var p=b.Components.R2();m.push("default");for(var n=m.length-1;0<=n;n--){var l=p[m[n]];void 0!==l&&(k=f.widget.extend(k,l))}if(!f.isEmptyObject(k)){var x=this,p=function(){return x.vda()},B;for(B in k)if(n=g[B],void 0===n||f.isPlainObject(n))l=k[B],null!=l&&l instanceof d?(l=l.GN(),f.isFunction(l)?c(this,a[B],n,h,B,l,p):b.r.error("Dynamic getter for property %s is not a function",
B)):h[B]=e([a[B],l,n])}},k1:function(a){for(var b=this.constructor.prototype;null!=b&&"oj"===b.namespace;)a(b),b=Object.getPrototypeOf(b)}});delete f.fn.baseComponent;b.ya=function(a,b,c,d){f.widget(a,b,c);d&&delete f.fn[a.split(".")[1]];if("oj.oj"===a.substring(0,5)||"oj._oj"===a.substring(0,6)){b=a.split(".");a=b[0];b=b[1];var e=a+"-"+b;f.expr[":"][("_"===b.substring(0,1)?"_"+a+"-"+b.substring(3):a+"-"+b.substring(2)).toLowerCase()]=function(a){return!!f.data(a,e)}}};var m="translations",n=m+".",
p={preventDefault:function(){this.isDefaultPrevented=h},stopPropagation:function(){this.isPropagationStopped=h},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=h}};f(document).ready(function(){var a=f("\x3cdiv style\x3d'border: 1px solid;border-color:red green;position: absolute;top: -999px;background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs\x3d);'\x3e\x3c/div\x3e"),b;a.appendTo("body");b=a.css("backgroundImage");a.css("borderTopColor")!=
a.css("borderRightColor")&&(null==b||"none"!=b&&"url (invalid-url:)"!=b)||f("body").addClass("oj-hicontrast");a.remove()});b.v={};b.v.a8="\x3chtml\x3e";b.v.Z7="\x3c/html\x3e";b.v.t8={SPAN:1,B:1,I:1,EM:1,BR:1,HR:1,LI:1,OL:1,UL:1,P:1,TT:1,BIG:1,SMALL:1,PRE:1};b.v.s8={"class":1,style:1};b.v.apa=function(a){return 0===a.indexOf(b.v.a8)&&a.lastIndexOf(b.v.Z7)===a.length-7?!0:!1};b.v.$ma=function(a){var c=f(document.createElement("span")).get(0);(c.innerHTML=a)&&0<=a.indexOf("\x3c")&&b.v.QT(c);return c};
b.v.QT=function(a){for(var c=a.childNodes,d,e,g,h,k,m=c.length-1;0<=m;){if((d=c.item(m))&&1===d.nodeType)if(b.v.t8[d.nodeName]){e=d.attributes;for(k=e.length-1;0<=k;k--)g=e[k],(h=void 0!==f(d).attr(g.name))&&(b.v.s8[g.name]||d.removeAttribute(g.nodeName));b.v.QT(d)}else d&&a.removeChild(d);m--}};b.v.bl=function(a,b){for(var c=b.parentNode;c;){if(c==a)return!0;c=c.parentNode}return!1};b.v.Qo=function(a,c){return c==a?!0:b.v.bl(a,c)};b.v.Nh=function(a,c,d){var e=f(a),g=e.data(b.v.Rv);null==g&&(g=new b.v.j9(a),
e.data(b.v.Rv,g),g.start());g.addListener(c,d)};b.v.Oi=function(a,c){var d=f(a),e=d.data(b.v.Rv);null!=e&&(e.removeListener(c),e.Pf()&&(e.stop(),d.removeData(b.v.Rv)))};b.v.A2=function(a){f(a).find(".oj-helper-detect-expansion").parent().each(function(a,c){var d=f(c).data(b.v.Rv);null!=d&&d.zm(!0)})};b.v.Am=function(a){var c=b.Ma.Gy();return b.Ma.Xi.hQ===c.os?a.metaKey:a.ctrlKey};b.v.Nga=(window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,
0)}).bind(window);b.v.LT=(window.cancelAnimationFrame||window.mozCancelAnimationFrame||window.webkitCancelAnimationFrame||function(a){return window.clearTimeout(a)}).bind(window);b.v.j9=function(a){function c(a){var b=!1;if(null!=z.offsetParent){var e=z.offsetWidth,g=z.offsetHeight;if(F!==e||D!==g)l=n,h(e,g),b=!0,a&&d(!0)}return b}function d(c){var e=a.offsetWidth,g=a.offsetHeight;k.has()&&(c?(null!==J&&b.v.LT(J),J=b.v.Nga(function(){J=null;k.fire(e,g)})):k.fire(e,g));for(c=0;c<m.length;c++)m[c].GN()(e,
g)}function e(a){a.stopPropagation();!c(!0)&&0<l&&null!=z.offsetParent&&(0==z.scrollLeft||0==z.scrollTop)&&(l--,h(F,D))}function g(){d(!1)}function h(a,b){F=a;D=b;var c=z.firstChild.style,d=1;do c.width=a+d+"px",c.height=b+d+"px",z.scrollLeft=z.scrollTop=d,d++;while((0==z.scrollTop||0==z.scrollLeft)&&5>=d);A.scrollLeft=a;A.scrollTop=b}var k=f.Callbacks(),m=[],p=[],n=2,l=0,J=null,F=null,D=null,z=null,A=null,E=null,L=null;this.addListener=function(a,c){void 0===c||0===c?k.add(a):(m.push(new b.v.Jaa(a,
c)),p.push(a))};this.removeListener=function(a){var b=p.indexOf(a);0<=b?(p.splice(b,1),m.splice(b,1)[0].stop()):k.remove(a)};this.Pf=function(){return!k.has()&&0==p.length};this.start=function(){L=e.bind(this);if(a.attachEvent)E=g.bind(this),a.attachEvent("onresize",E);else{var b=a.childNodes[0];z=document.createElement("div");z.className="oj-helper-detect-expansion";var c=document.createElement("div");z.appendChild(c);null!=b?a.insertBefore(z,b):a.appendChild(z);z.addEventListener("scroll",L,!1);
A=document.createElement("div");A.className="oj-helper-detect-contraction";b=document.createElement("div");b.style.width="200%";b.style.height="200%";A.appendChild(b);a.insertBefore(A,z);A.addEventListener("scroll",L,!1);this.zm(!1)}};this.stop=function(){null!=J&&(b.v.LT(J),J=null);null!=z?(z.removeEventListener("scroll",L),A.removeEventListener("scroll",L),a.removeChild(z),a.removeChild(A)):a.detachEvent("onresize",E)};this.zm=function(a){var b=c(a);a&&!b&&null!=z.offsetParent&&h(F,D)}};b.v.Rv=
"_ojResizeTracker";b.v.yE=function(a){return/^[A-Za-z][0-9A-Z_a-z-]*$/.test(a)};b.v.Jaa=function(a,b){function c(){e=Array.prototype.slice.call(arguments);null==g&&(g=window.setTimeout(d,b))}function d(){a.apply(null,e);g=null}var e=null,g=null;this.GN=function(){return c};this.stop=function(){null!=g&&(window.clearTimeout(g),g=null)}};b.v.Sd=function(){return"ontouchstart"in window||0<navigator.msMaxTouchPoints||0<navigator.maxTouchPoints};b.v.k5=function(a){b.v.rha=a};b.v.unwrap=function(a,c){var d=
b.v.rha;d&&d==a.parent().get(0)||(1<arguments.length?c.replaceWith(a):a.unwrap())};b.v.T3=function(a){function c(a){var d=a.target,e=f(d),g=d.getBoundingClientRect(),h=b.v.qE(),q="ltr"===b.v.um();return q&&("HTML"===d.nodeName||"visible"!==e.css("overflow-x"))&&a.clientX>g.right-h?!0:!q&&"HTML"===d.nodeName&&a.clientX>g.left-h?!0:!q&&"visible"!==e.css("overflow-x")&&a.clientX<g.left+h?!0:("HTML"===d.nodeName||"visible"!==e.css("overflow-y"))&&a.clientY>g.bottom-h?!0:!1}if(!("clientX"in a&&"clientY"in
a))return!1;var d=b.Ma.Gy();if(b.Ma.Xi.BP===d.os||b.Ma.Xi.AF===d.os)a=!1;else{var e;if(b.Ma.Zm.QP===d.engine)try{e=a.originalTarget.localName?!1:!0}catch(g){e=!0}else e=b.Ma.Zm.QF===d.engine?c(a):b.Ma.sl.zF===d.browser?c(a):!1;a=e}return a};b.v.qE=function(){var a=b.v.uka;if(f.isNumeric(a))return a;a=f("\x3cdiv /\x3e");f(document.body).append(a);a.width(50).height(50).css({overflow:"scroll",visibility:"hidden",position:"absolute"});var c=f("\x3cdiv /\x3e");c.height(1);a.append(c);var c=c.width(),
d=a.width();a.remove();return a=b.v.uka=d-c};b.v.um=function(){var a=document.documentElement.getAttribute("dir");a&&(a=a.toLowerCase());return"rtl"===a?"rtl":"ltr"};b.v.Hy=function(a){return isNaN(a)?a&&0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0:a};b.v.Xna=function(a){return isNaN(a)?a&&0<a.length?(a=parseFloat(a),isNaN(a)&&(a=0),a):0:a};b.v.cpa=function(a){function c(a,d){if(-1>a.bottom-d.top)return!1;var e="auto"===d.overflowY||"scroll"===d.overflowY?b.v.qE():0;if(1>d.bottom-
e-a.top)return!1;e="auto"!==d.overflowX&&"scroll"!==d.overflowX||"rtl"!==b.v.um()?0:b.v.qE();if(-1>a.right-(d.left+e))return!1;e="auto"!==d.overflowX&&"scroll"!==d.overflowX||"ltr"!==b.v.um()?0:b.v.qE();return-1<a.left-(d.right-e)?!1:!0}function d(a){return"visible"!==a.css("overflow-x")||"visible"!==a.css("overflow-y")}function e(a){var b=a[0];return 1===b.nodeType?(b=b.getBoundingClientRect(),b.overflowX=a.css("overflow-x"),b.overflowY=a.css("overflow-y"),b):f.isWindow(b)?b={width:b.innerWidth,
height:b.innerHeight,top:0,bottom:b.innerHeight,left:0,right:b.innerWidth}:{height:0,width:0}}if(!a)return!1;var g=e(a),h=!0;for(a=a.parent();h&&a&&0<a.length&&1===a[0].nodeType;){if(d(a)){var k=e(a);0<k.height&&0<k.width&&(h=c(g,k))}a=a.parent()}return h};b.v.mG="oj-logical-parent";b.v.aoa=function(a){if(a)return a.data(b.v.mG)};b.v.l5=function(a,c){a&&(null===c?a.removeData(b.v.mG):a.data(b.v.mG,c))};b.v.bpa=function(a,c){b.l.YM(a);b.l.YM(c);for(var d=c;d;){if(d==a)return!0;var e=b.v.aoa(f(d)),
d=e?e[0]:d.parentNode}return!1};b.v.zqa=function(a){var b=document.createElement("a");b.href=a;a=b.protocol;null!=a&&(a=a.toLowerCase());if(0>["http:","https:"].indexOf(a))throw a+" is not a valid URL protocol";};b.v.Dla=function(){f(document.body).hasClass("oj-hybrid")&&document.body.addEventListener("contextmenu",function(a){a.preventDefault()},!0)};b.v.Dla();b.Sa=function(a){this.Init(a)};b.b.ga(b.Sa,b.b,"oj.ComponentMessaging");b.Sa.fd={NONE:"none",Dz:"notewindow",rv:"placeholder",nv:"inline"};
b.Sa.dG={};b.Sa.QE=function(a,c){a&&"function"===typeof c&&(b.Sa.dG[a]=c)};b.Sa.prototype.Init=function(a){b.Sa.q.Init.call(this);this.ka=a;this.aw=!1;this.Iga()};b.Sa.prototype.Do=function(a,c){var d=this;b.l.Hf(c);this.lc=a;this.HC=b.oc.$e(this.HC||{},c);this.aw?this.dja():(f.each(this.Sq,function(a,b){b.Do(d)}),this.aw=!0)};b.Sa.prototype.update=function(a){b.l.Hf(a);b.l.J1(this.aw);this.HC=b.oc.$e(this.HC||{},a);this.aw&&f.each(this.Sq,function(b,c){c.gP(a)&&c.update()})};b.Sa.prototype.Uk=function(){f.each(this.Sq,
function(a,b){b.Uk()});this.aw=!1;this.lc=this.ka=null;this.Sq={}};b.Sa.prototype.ww=function(a,c){return new (b.Sa.dG[a]||b.Sa.dG[b.Sa.fd.NONE])(c)};b.Sa.prototype.nda=function(){return this.ka||null};b.Sa.prototype.Qda=function(){return this.lc||null};b.Sa.prototype.si=function(){return this.HC||{}};b.Sa.prototype.OW=function(){var a={},c=!1,d,e,g=this.ka.options.placeholder,h,k,m,p,n=this.ka.options.displayOptions||{},l={};k=Object.keys(n);for(m=0;m<k.length;m++){e=k[m];d=n[e];c=!1;h=e+"";if(Array.isArray(d))for(p=
0;p<d.length;p++)e=d[p],c||(c=this.E_(h,e,g,l));else"string"===typeof d&&(c||(c=this.E_(h,d,g,l)));c||(l[h]=b.Sa.fd.NONE)}f.each(b.Sa.fd,function(b,c){a[c]=[]});f.each(l,function(b,c){a[c].push(b)});return a};b.Sa.prototype.E_=function(a,c,d,e){var g=!1;switch(c){case b.Sa.fd.rv:"converterHint"!==a||g||d||(e[a]=c,g=!0);break;case b.Sa.fd.nv:"messages"!==a||g||(e[a]=c,g=!0);break;default:g||(e[a]=c,g=!0)}return g};b.Sa.prototype.Iga=function(){var a=this.OW(),c=a[b.Sa.fd.Dz],d=a[b.Sa.fd.NONE],e=a[b.Sa.fd.rv],
a=a[b.Sa.fd.nv],g={};0<c.length&&(g[b.Sa.fd.Dz]=this.ww(b.Sa.fd.Dz,c));0<e.length&&(g[b.Sa.fd.rv]=this.ww(b.Sa.fd.rv,e));0<a.length&&(g[b.Sa.fd.nv]=this.ww(b.Sa.fd.nv,a));g[b.Sa.fd.NONE]=this.ww(b.Sa.fd.NONE,d);this.Sq=g};b.Sa.prototype.dja=function(){var a=this.OW(),c,d=this;f.each(a,function(a,e){a+="";c=d.Sq[a];e&&0<e.length?c?c&&c.Br(e):(c=d.ww(a,e),d.Sq[a]=c,c.Do(d)):c&&b.Sa.fd.NONE!==a&&(c.Uk(),delete d.Sq[a])})};b.pc=function(a){this.Init(a)};b.b.ga(b.pc,b.b,"oj.MessagingStrategy");b.pc.prototype.Init=
function(a){b.l.UD(a);b.pc.q.Init.call(this);this.kB=a};b.pc.prototype.Do=function(a){this.Yp=a};b.pc.prototype.Uk=function(){};b.pc.prototype.Br=function(a){this.Init(a)};b.pc.prototype.gP=function(){return!0};b.pc.prototype.update=function(){};b.pc.prototype.Xh=function(){return this.Yp.Qda()};b.pc.prototype.Vi=function(){return this.Yp.nda()};b.pc.prototype.rF=function(){return this.tF().qx};b.pc.prototype.qF=function(){return this.tF().Gu()};b.pc.prototype.VP=function(){var a=[],b=this.si();(b=
b&&b.d2)&&a.push(b);return a};b.pc.prototype.A6=function(){var a=[],b=this.si();f.each(b&&b.Cqa||[],function(b,c){a.push(c)});return a};b.pc.prototype.z6=function(){var a=this.si();return a&&a.title||""};b.pc.prototype.tF=function(){var a=this.si();return a&&a.Y5||null};b.pc.prototype.yF=function(){var a=this.rF();return a&&0<a.length?!0:!1};b.pc.prototype.zQ=function(){return-1!==this.kB.indexOf("messages")?!0:!1};b.pc.prototype.KF=function(){return-1!==this.kB.indexOf("converterHint")?!0:!1};b.pc.prototype.BQ=
function(){return-1!==this.kB.indexOf("validatorHint")?!0:!1};b.pc.prototype.AQ=function(){return-1!==this.kB.indexOf("title")?!0:!1};b.pc.prototype.D6=function(){return this.tF().iO()};b.pc.prototype.si=function(){return this.Yp?this.Yp.si():{}};b.df=function(a){this.Init(a)};b.Sa.QE(b.Sa.fd.NONE,b.df);b.df.oA="oj-invalid";b.df.pA="oj-warning";b.b.ga(b.df,b.pc,"oj.DefaultMessagingStrategy");b.df.prototype.update=function(){b.df.q.update.call(this);var a=this.Xh(),c=this.qF(),d=[],e=[],g=!1,f=this.Vi().widget();
a&&(this.D6()?(d.push(b.df.pA),e.push(b.df.oA),g=!0):this.yF()&&c===b.X.Tb.WARNING?(d.push(b.df.oA),e.push(b.df.pA)):(d.push(b.df.oA),d.push(b.df.pA)),f.removeClass(d.join(" ")).addClass(e.join(" ")),a.attr({"aria-invalid":g}))};b.df.prototype.Uk=function(){this.Vi().widget().removeClass(b.df.oA).removeClass(b.df.pA);this.Xh().removeAttr("aria-invalid");b.df.q.Uk.call(this)};b.yh=function(a){this.Init(a)};b.Sa.QE(b.Sa.fd.rv,b.yh);b.b.ga(b.yh,b.pc,"oj.PlaceholderMessagingStrategy");b.yh.prototype.Init=
function(a){b.yh.q.Init.call(this,a)};b.yh.prototype.Do=function(a){b.yh.q.Do.call(this,a);this.rL()};b.yh.prototype.Br=function(a){b.yh.q.Br.call(this,a);this.rL()};b.yh.prototype.gP=function(a){return a&&void 0!==a.d2?!0:!1};b.yh.prototype.update=function(){b.yh.q.update.call(this);this.rL()};b.yh.prototype.rL=function(){var a=this.Xh();this.b7()&&a&&(a=this.VP(),a=a.length?a[0]:"",this.Vi().option({placeholder:a},{_context:{Zoa:!0}}))};b.yh.prototype.b7=function(){return this.KF()};b.Qi=function(a,
b){this.Init(a,b)};b.Qi.iO=function(a){return b.X.Gu(a)>=b.X.Tb.ERROR?!0:!1};b.b.ga(b.Qi,b.b,"oj.ComponentValidity");b.Qi.prototype.Init=function(a,c){b.Qi.q.Init.call(this);this.cY(c)};b.Qi.prototype.iO=function(){return this.ao};b.Qi.prototype.Gu=function(){return this.Lha};b.Qi.prototype.update=function(a,b){this.cY(b)};b.Qi.prototype.cY=function(a){this.Kaa=a;this.qx=this.Kda();this.Lha=b.X.Gu(this.qx);this.ao=b.Qi.iO(this.qx)};b.Qi.prototype.Kda=function(){for(var a=this.Kaa||[],c=[],d,e=0;e<
a.length;e++)d=a[e],d instanceof b.Jc&&!d.Q1()||c.push(d);return c};b.td={};b.td.sS=":tabbable";b.td.YD=function(a){var c=document.activeElement;return a&&c?b.v.Qo(a,c):!1};b.td.Fy=function(a){a.focus()};b.td.BN=function(a){(a=b.td.X2(a))&&b.td.Fy(a)};b.td.X2=function(a){var c=f(a);return c.is(b.td.sS)?a:(a=c.find(b.td.sS))&&0<a.length?a[0]:null};b.aj={};o_("Test",b.aj,b);b.aj.ready=!1;o_("Test.ready",b.aj.ready,b);b.aj.Ina=function(a){var c=a;if(b.Fa.od(a))try{c=f.parseJSON(a)}catch(d){return null}return c&&
c.element&&(a=f(c.element))?(a=b.Components.Of(a[0],c.component),delete c.element,a("getNodeBySubId",c)):null};o_("Test.domNodeForLocator",b.aj.Ina,b);b.aj.QN=function(){return b.J.QN()};o_("Test.getOpenPopupCount",b.aj.QN,b);b.aj.tN=function(){return b.J.tN()};o_("Test.findOpenPopups",b.aj.tN,b);b.aj.jN=function(a,c){return b.J.jN(a,c)};o_("Test.compareStackingContexts",b.aj.jN,b)});