/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(b){b.Mc=function(f,a,d,c,e){b.l.wy(d);this.ac=f;this.re=a;this.CE=d;this.Fg=c;this.r4=e};o_("CollectionHeaderSet",b.Mc,b);b.Mc.prototype.m5=function(f){b.l.UD(f);null!=f&&f.length===this.R()&&(this.vr=f)};b.Mc.prototype.getData=function(f,a){var d;b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");if(null!=this.Fg){if(null==this.vr)return null;d=this.vr[f-this.ac];
return d.get(this.Fg)}return this.CE[f]};b.b.g("CollectionHeaderSet.prototype.getData",{getData:b.Mc.prototype.getData});b.Mc.prototype.getMetadata=function(f,a){var d;b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");if(null!=this.Fg){if(null==this.vr)return null;d=this.vr[f-this.ac];return{key:b.mp.nt(d)}}d=this.getData(f,a);return this.r4.key===d?{key:d,sortDirection:this.r4.direction}:{key:d}};b.b.g("CollectionHeaderSet.prototype.getMetadata",
{getMetadata:b.Mc.prototype.getMetadata});b.Mc.prototype.zg=function(){return 0<this.R()?1:0};b.b.g("CollectionHeaderSet.prototype.getLevelCount",{zg:b.Mc.prototype.zg});b.Mc.prototype.Vb=function(f,a){b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");b.l.assert(null==a||0==a,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};b.b.g("CollectionHeaderSet.prototype.getExtent",{Vb:b.Mc.prototype.Vb});b.Mc.prototype.le=function(f,a){b.l.assert(f<=this.re&&f>=this.ac,"index out of bounds");
b.l.assert(null==a||0==a,"level out of bounds");return 1};b.b.g("CollectionHeaderSet.prototype.getDepth",{le:b.Mc.prototype.le});b.Mc.prototype.R=function(){return Math.max(0,this.re-this.ac)};b.b.g("CollectionHeaderSet.prototype.getCount",{R:b.Mc.prototype.R});b.Mc.prototype.ta=function(){return this.ac};b.b.g("CollectionHeaderSet.prototype.getStart",{ta:b.Mc.prototype.ta});b.Mc.prototype.S2=function(){return this.re};b.b.g("CollectionHeaderSet.prototype.getEnd",{S2:b.Mc.prototype.S2});b.Mc.prototype.a3=
function(){return this.CE};b.b.g("CollectionHeaderSet.prototype.getHeaders",{a3:b.Mc.prototype.a3});b.Mc.prototype.My=function(){return this.Fg};b.b.g("CollectionHeaderSet.prototype.getRowHeader",{My:b.Mc.prototype.My});b.Hd=function(f,a,d,c,e){b.l.wy(e);this.Mi=f;this.rr=a;this.hl=d;this.qr=c;this.Td=e};o_("CollectionCellSet",b.Hd,b);b.Hd.prototype.m5=function(f){b.l.UD(f);null!=f&&f.length===this.R("row")&&(this.vr=f)};b.Hd.prototype.getData=function(b){var a;a=this.Pb(b);return null==a?null:a.get(this.Td[b.column])};
b.b.g("CollectionCellSet.prototype.getData",{getData:b.Hd.prototype.getData});b.Hd.prototype.getMetadata=function(f){var a;a=this.Pb(f);return null==a?null:{keys:{row:b.mp.nt(a),column:this.Td[f.column]}}};b.b.g("CollectionCellSet.prototype.getMetadata",{getMetadata:b.Hd.prototype.getMetadata});b.Hd.prototype.Pb=function(f){var a;if(null==this.vr)return null;b.l.Hf(f);a=f.row;f=f.column;b.l.assert(a>=this.Mi&&a<=this.rr&&f>=this.hl&&f<=this.qr);return this.vr[a-this.Mi]};b.Hd.prototype.R=function(b){return"row"===
b?Math.max(0,this.rr-this.Mi):"column"===b?Math.max(0,this.qr-this.hl):0};b.b.g("CollectionCellSet.prototype.getCount",{R:b.Hd.prototype.R});b.Hd.prototype.getStartRow=function(){return this.Mi};b.b.g("CollectionCellSet.prototype.getStartRow",{getStartRow:b.Hd.prototype.getStartRow});b.Hd.prototype.U2=function(){return this.rr};b.b.g("CollectionCellSet.prototype.getEndRow",{U2:b.Hd.prototype.U2});b.Hd.prototype.getStartColumn=function(){return this.hl};b.b.g("CollectionCellSet.prototype.getStartColumn",
{getStartColumn:b.Hd.prototype.getStartColumn});b.Hd.prototype.T2=function(){return this.qr};b.b.g("CollectionCellSet.prototype.getEndColumn",{T2:b.Hd.prototype.T2});b.Hd.prototype.Lo=function(){return this.Td};b.b.g("CollectionCellSet.prototype.getColumns",{Lo:b.Hd.prototype.Lo});b.mp=function(){};b.mp.nt=function(b){var a;a=b.ag();null==a&&(a=b.qp());return a};b.wa=function(f,a){this.Ba=f;null!=a&&(this.nz=a.rowHeader,this.columns=a.columns);this.p0();b.wa.q.constructor.call(this)};o_("CollectionDataGridDataSource",
b.wa,b);b.b.ga(b.wa,b.Ym,"oj.CollectionDataGridDataSource");b.wa.prototype.Init=function(){b.wa.q.Init.call(this);this.Km={};this.Sx()};b.b.g("CollectionDataGridDataSource.prototype.Init",{Init:b.wa.prototype.Init});b.wa.prototype.Sx=function(){this.Ba.on("add",this.Bfa.bind(this));this.Ba.on("remove",this.Dfa.bind(this));this.Ba.on("change",this.Cfa.bind(this));this.Ba.on("refresh",this.Uea.bind(this));this.Ba.on("reset",this.Vea.bind(this))};b.wa.prototype.Uga=function(){return null!=this.data};
b.wa.prototype.R=function(b){var a;void 0==this.precision&&(this.precision={});if("row"==b){a=this.ke();if(-1===a||0===a&&(!this.Uga()||0<this.uo()))return this.precision[b]="estimate",-1;this.precision[b]="exact";return this.uo()}if("column"==b){if(null!=this.columns)return this.precision[b]="exact",this.columns.length;this.precision[b]="estimate";return-1}return 0};b.b.g("CollectionDataGridDataSource.prototype.getCount",{R:b.wa.prototype.R});b.wa.prototype.xg=function(b){null!=this.precision&&null!=
this.precision[b]||this.R(b);return this.precision[b]};b.b.g("CollectionDataGridDataSource.prototype.getCountPrecision",{xg:b.wa.prototype.xg});b.wa.prototype.Kf=function(b,a,d){var c,e;null!=a&&(c=b.axis,e={},e.J3=b,e.callbacks=a,e.xy=d,this.Km[c]=e)};b.b.g("CollectionDataGridDataSource.prototype.fetchHeaders",{Kf:b.wa.prototype.Kf});b.wa.prototype.pfa=function(f,a,d,c){var e,g,h,k;e=f.axis;g=f.start;h=f.count;if("column"===e)null!=this.columns?(c=Math.min(this.columns.length,g+h),k=new b.Mc(g,c,
this.columns,void 0,this.Di)):k=new b.Gd(g,g,e,null);else if("row"===e){if(null!=this.nz){null!=c&&(h=c.count);c=Math.min(this.uo(),g+h);k=new b.Mc(g,c,this.columns,this.nz);this.G_(g,c,k,f,a,d);return}k=new b.Gd(g,g,e,null)}null!=a&&a.success&&a.success.call(d.success,k,f)};b.wa.prototype.LW=function(b){var a,d,c,e,g,h;for(a=0;a<b.length;a+=1)d=b[a],"row"===d.axis?(c=d.start,e=d.count):"column"===d.axis&&(g=d.start,h=d.count);return{rowStart:c,rowCount:e,colStart:g,colCount:h}};b.wa.prototype.Nea=
function(f,a,d,c){var e,g,h;e=this.LW(f);g=e.rowStart;c=null!=c?Math.min(this.uo(),g+c.count):Math.min(this.uo(),g+e.rowCount);h=e.colStart;e=Math.min(null==this.columns?0:this.columns.length,h+e.colCount);e=new b.Hd(g,c,h,e,this.columns);this.G_(g,c,e,f,a,d)};b.wa.prototype.G_=function(b,a,d,c,e,g){var h;for(h=[];b<a;b++)h.push(this.Ba.at(b,{deferred:!0}));Promise.all(h).then(function(a){d.m5(a);e.success.call(g.success,d,c)})};b.wa.prototype.wg=function(b,a,d){null!=a&&(this.Hg={},this.Hg.R1=b,
this.Hg.callbacks=a,this.Hg.xy=d);this.Hca(b)};b.b.g("CollectionDataGridDataSource.prototype.fetchCells",{wg:b.wa.prototype.wg});b.wa.prototype.GZ=function(b){var a,d,c,e,g;a=this.Km[b];null!=a&&(d=a.J3,c=a.callbacks,e=a.xy,"row"===b&&(g=a.WM),this.pfa(d,c,e,g),this.Km[b]=null)};b.wa.prototype.Sia=function(){this.Nea(this.Hg.R1,this.Hg.callbacks,this.Hg.xy,this.Hg.WM)};b.wa.prototype.Hca=function(b){var a;b=this.LW(b);a=b.rowStart;this.Ba.oz(a,b.rowCount).then(function(b){this.data=!0;this.wka(b.start,
b.count);void 0===this.columns?this.Ba.at(a,{deferred:!0}).then(function(a){null!=a&&this.$L(a);this.vV()}.bind(this)):this.vV()}.bind(this),function(a){this.Ica(a)}.bind(this))};b.wa.prototype.Ica=function(f){b.r.error(f);null!=this.Km&&(this.HZ("column",f),this.HZ("row",f));null!=this.Hg&&this.Tia(f)};b.wa.prototype.HZ=function(b,a){var d,c,e;d=this.Km[b];null!=d&&(c=d.callbacks,e=d.xy,d=d.J3,c.error&&c.error.call(e.error,a,d),this.Km[b]=null)};b.wa.prototype.Tia=function(b){var a,d,c;a=this.Hg.callbacks;
d=this.Hg.xy;c=this.Hg.R1;a.error&&a.error.call(d.error,b,c);this.Hg=null};b.wa.prototype.vV=function(){null!=this.Km&&(this.GZ("column"),this.GZ("row"));null!=this.Hg&&this.Sia()};b.wa.prototype.wka=function(b,a){var d={start:b,count:a};null!=this.Km.row&&(this.Km.row.WM=d);null!=this.Hg&&(this.Hg.WM=d)};b.wa.prototype.$L=function(b){this.columns=b.keys();-1!=this.columns.indexOf(this.nz)&&this.columns.splice(this.columns.indexOf(this.nz),1)};b.wa.prototype.keys=function(f){var a,d,c,e,g;a=f.row;
d=f.column;g=this;return new Promise(function(f){g.Ba.at(a,{deferred:!0}).then(function(a){null==a?f({row:null,column:null}):(c=b.mp.nt(a),null==g.columns&&g.$L(a),e=g.columns[d],f({row:c,column:e}))}.bind(g))})};b.b.g("CollectionDataGridDataSource.prototype.keys",{keys:b.wa.prototype.keys});b.wa.prototype.Cg=function(b){var a,d,c,e;a=b.row;d=b.column;e=this;return new Promise(function(b){e.Ba.indexOf(a,{deferred:!0}).then(function(a){-1===a?b({row:-1,column:-1}):null==e.columns?e.Ba.at(a,{deferred:!0}).then(function(f){e.$L(f);
c=e.columns.indexOf(d);-1===c&&(a=-1);b({row:a,column:c})}.bind(e)):(c=e.columns.indexOf(d),-1===c&&(a=-1),b({row:a,column:c}))}.bind(e))})};b.b.g("CollectionDataGridDataSource.prototype.indexes",{Cg:b.wa.prototype.Cg});b.wa.prototype.getCapability=function(b){return"sort"===b?"column":"move"===b?"row":null};b.b.g("CollectionDataGridDataSource.prototype.getCapability",{getCapability:b.wa.prototype.getCapability});b.wa.prototype.sort=function(b,a,d){var c,e,g;null==d&&(d={});null==b?this.GL(a,d):(e=
b.direction,g=b.key,b=b.axis,"column"===b?(this.Ba.Xa()?(this.Ba.comparator=g,this.Ba.sortDirection="ascending"===e?1:-1):("ascending"===e&&(c=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof Date&&(b=b.toISOString(),d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===e&&(c=function(a,b){var c,d;a=a.get(g);b=b.get(g);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());
return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),this.Ba.comparator=c),this.Ba.sort(),this.p0(g),null!=a&&null!=a.success&&a.success.call(d.success)):null!=a&&null!=a.error&&a.error.call(d.error,"Axis value not supported"))};b.b.g("CollectionDataGridDataSource.prototype.sort",{sort:b.wa.prototype.sort});b.wa.prototype.GL=function(b,a){this.Ba.comparator=null;this.Ba.reset();null!=b&&null!=b.success&&b.success.call(a.success)};b.wa.prototype.p0=function(b){var a,d;a=this.Ba.comparator;d=-1===this.Ba.sortDirection?
"descending":"ascending";null==b&&"function"===typeof a?this.Di={}:(this.Di={},this.Di.axis="column",this.Di.direction=d,this.Di.key=null==b?a:null)};b.wa.prototype.move=function(b,a,d,c,e){var g;this.Ba.get(b,{deferred:!0}).then(function(d){null==a?(this.Ba.remove(d),this.Ba.add(d),null!=c&&null!=c.success&&c.success.call(e.success)):(b===a?(g=this.Ba.indexOf(a,{deferred:!0}),this.Ba.remove(d)):(this.Ba.remove(d),g=this.Ba.indexOf(a,{deferred:!0})),g.then(function(a){this.Ba.add(d,{at:a,Xra:!0});
null!=c&&null!=c.success&&c.success.call(e.success)}.bind(this)))}.bind(this))};b.b.g("CollectionDataGridDataSource.prototype.move",{move:b.wa.prototype.move});b.wa.prototype.qd=function(){return"valid"};b.b.g("CollectionDataGridDataSource.prototype.moveOK",{qd:b.wa.prototype.qd});b.wa.prototype.wk=function(b,a,d,c,e){var g={source:this};g.operation=b;g.keys={row:a,column:d};g.indexes={row:c,column:e};return g};b.wa.prototype.Bfa=function(f){var a,d;this.Ba.indexOf(f,{deferred:!0}).then(function(c){d=
b.mp.nt(f);a=this.wk("insert",d,null,c,-1);this.handleEvent("change",a)}.bind(this))};b.wa.prototype.Dfa=function(f,a,d){this.handleEvent("change",this.wk("delete",b.mp.nt(f),null,d.index,-1))};b.wa.prototype.Cfa=function(f){var a,d;this.Ba.indexOf(f,{deferred:!0}).then(function(c){d=b.mp.nt(f);a=this.wk("update",d,null,c,-1);this.handleEvent("change",a)}.bind(this))};b.wa.prototype.Uea=function(){this.data=null;this.handleEvent("change",this.wk("refresh",null,null))};b.wa.prototype.Vea=function(){this.data=
null;this.handleEvent("change",this.wk("reset",null,null))};b.wa.prototype.uo=function(){return this.Ba.size()};b.wa.prototype.ke=function(){return void 0===this.Ba.totalResults?-1:this.Ba.totalResults};b.wa.prototype.N2=function(){return this.Ba};b.b.g("CollectionDataGridDataSource.prototype.getCollection",{N2:b.wa.prototype.N2});b.wa.prototype.Lo=function(){return this.columns};b.b.g("CollectionDataGridDataSource.prototype.getColumns",{Lo:b.wa.prototype.Lo});b.wa.prototype.My=function(){return this.nz};
b.b.g("CollectionDataGridDataSource.prototype.getRowHeader",{My:b.wa.prototype.My});b.wa.prototype.getData=function(){return this.data};b.b.g("CollectionDataGridDataSource.prototype.getData",{getData:b.wa.prototype.getData})});