/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,f){function a(a,b,e,f,h,k){this.sc=a;this.qia=b;this.Qs=e;this.NA=f;h&&(h.zpa&&(this.Kia=h.zpa),h.ppa&&(this.iia=h.ppa),h.Q4&&(this.Lia=h.Q4),h.D4&&(this.jia=h.D4),h.P4&&(this.Jia=h.P4),h.C4&&(this.hia=h.C4));k&&(k.f5&&(this.M_=k.f5),k.Sna&&(this.QI=k.Sna),k.Xma&&(this.Sp=k.Xma),k.Nh&&(this.GA=k.Nh),k.Oi&&(this.YC=k.Oi));this.LA=!0;this.gt=0;a=navigator.userAgent.toLowerCase();if(-1!==a.indexOf("gecko/"))this.L$=!0;else if(-1!==a.indexOf("opera"))this.M$=
!0;else if(-1!==a.indexOf("applewebkit")||-1!==a.indexOf("safari"))this.N$=!0}a.prototype.Pm=function(b){var c=this;if(b){this.gba();this.xba(this.Kia,this.Lia,this.Jia);this.jba(this.iia,this.jia,this.hia);var e=this.vj,f=this.sD;f?(this.QA=f.offsetWidth,this.PA=e.offsetHeight):(f=this.OD,this.QA=e.offsetWidth,this.PA=f.offsetHeight);this.nC();this.mC();this.tx=function(a){c.Jfa(a)};a.uf(this.sc,"mousewheel",this.tx);a.uf(this.sc,"wheel",this.tx);this.rM=function(a){c.hK(a)};a.uf(this.fe,"touchstart",
this.rM);this.pM=function(a){c.gK(a)};a.uf(this.fe,"touchmove",this.pM);this.jy=function(a){c.eK(a)};a.uf(this.fe,"touchend",this.jy);a.uf(this.fe,"touchcancel",this.jy);this.XK=0}else this.h_();this.PH();this.dT(b);this.Ve(!0);b&&this.GA&&(this.eh=function(){c.Ve(!1)},this.GA.call(this.Sp,this.sc,this.eh),this.GA.call(this.Sp,this.Ln,this.eh))};a.prototype.destroy=function(){var b=this.sc;a.ie(b,"mousewheel",this.tx);a.ie(b,"wheel",this.tx);a.ie(this.fe,"touchstart",this.rM);a.ie(this.fe,"touchmove",
this.pM);a.ie(this.fe,"touchend",this.jy);a.ie(this.fe,"touchcancel",this.jy);this.jy=this.pM=this.rM=this.tx=null;this.YC&&this.eh&&(this.YC.call(this.Sp,b,this.eh),this.YC.call(this.Sp,this.Ln,this.eh));this.eh=null;a.aka(this.UH,b);this.mT=null;this.jM?b.removeChild(this.jM):(b.removeChild(this.fe),b.removeChild(this.OD),b.removeChild(this.UM));this.OD=this.UM=this.RK=this.fL=this.sD=this.iM=this.jM=this.UH=this.fe=this.Ln=this.Gk=this.vj=null;this.PH();this.Qs=this.Sp=this.YC=this.GA=this.QI=
this.M_=this.sc=null};a.bka=function(b,c,e){var f=null;e&&(f=a.dI(),c.appendChild(f));var h=null;for(b=b.childNodes;0<b.length;){h||(h=[]);var k=b[0];if(1===k.nodeType){e||(f=a.dI(),c.appendChild(f));var l=a.eB();l.appendChild(k);f.appendChild(l);h.push(k)}else e?f.appendChild(k):c.appendChild(k)}return h};a.aka=function(a,b){if(a)for(var e=a.childNodes;0<e.length;){var f=e[0];if(1===f.nodeType){for(var h=f.childNodes;0<h.length;){var k=h[0];1===k.nodeType?(b.appendChild(k.firstChild),f.removeChild(k)):
b.appendChild(k)}a.removeChild(f)}else b.appendChild(f)}};a.Iw=function(a){var b=a.ownerDocument.defaultView,e=null;return e=b?b.getComputedStyle(a,null):a.currentStyle};a.yda=function(b){b=a.Iw(b);return a.ng(b.width)};a.xda=function(b){b=a.Iw(b);return a.ng(b.height)};a.ng=function(a){return 0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};a.uf=function(a,b,e){a.addEventListener?a.addEventListener(b,e,!1):a.attachEvent&&a.attachEvent("on"+b,e)};a.ie=function(a,b,e){a.removeEventListener?
a.removeEventListener(b,e,!1):a.detachEvent&&a.detachEvent("on"+b,e)};a.Eea=function(a){var b=0;return b=null!=a.wheelDelta?a.wheelDelta:null!=a.deltaY?-a.deltaY:-a.detail};a.AU=function(){var a=document.createElement("div");a.style.display="table";return a};a.dI=function(){var a=document.createElement("div");a.style.display="table-row";return a};a.eB=function(){var a=document.createElement("div");a.style.display="table-cell";return a};a.z1=function(a,b,e,f){var h=document.createElement("div"),k=
h.style;k.display="inline-block";h.appendChild(a);b.appendChild(h);e&&(k.maxWidth=h.offsetWidth+"px");f&&(k.maxHeight=h.offsetHeight+"px");return h};a.prototype.Lb=function(){return"horizontal"===this.qia};a.prototype.Xga=function(){return!this.XV().hasChildNodes()};a.prototype.h_=function(){this.XK=this.$g();this.ZT();this.TL(0);this.nC();this.mC()};a.prototype.PH=function(){this.nD=this.ke=null};a.prototype.Ve=function(a){a||this.h_();this.PH();this.ke&&this.nD||(this.ke=this.$Y());a||this.dT(!1);
a=this.ke;this.s$(a.Tf,a.ph)};a.prototype.s$=function(a,b){var e=this.vj.style,f=this.Gk.style;if(this.Lb()){var h=.5*(b-this.PA);e.top=h+"px";f.top=h+"px"}else h=.5*(a-this.QA),this.NA?(e.left=-h+"px",f.left=-h+"px"):(e.left=h+"px",f.left=h+"px")};a.prototype.dT=function(b){var c=this.Ln,e=this.Lb(),f=e?a.yda(this.sc):a.xda(this.sc);(e?c.offsetWidth:c.offsetHeight)>f&&this.h0(f);this.rx=0;this.px=e?c.offsetWidth-f+this.QA:c.offsetHeight-f+this.PA;0>this.px&&(this.px=0);this.nC();this.mC();this.au(b?
this.rx:this.XK,!0);this.XK=0};a.prototype.gba=function(){var b=this,c=this.Lb(),e=document.createElement("div");this.fe=e;var f=e.style;f.overflow="hidden";f.display=this.Jw();f.position="relative";c&&(f.verticalAlign="top");var h=this.sc,k=document.createElement("div");this.Ln=k;var l=k.style;l.position="relative";c&&(l.display="inline-block");e.appendChild(k);l=null;if(c){this.jM=l=a.AU();var m=a.dI(),n=a.eB();this.iM=n;var p=a.eB(),r=a.eB();this.sD=r;var s=r.style;n.style.verticalAlign="top";
s.verticalAlign="top";p.appendChild(e);m.appendChild(n);m.appendChild(p);m.appendChild(r);l.appendChild(m)}m=a.AU();n=a.bka(h,m,c);if(this.Qs)for(n=[],p=this.Qs.children,r=p.length,s=0;s<r;s++){var q=p[s];1===q.nodeType&&n.push(q)}(this.mT=n)&&0<n.length&&(this.UH=m,k.appendChild(m));l?h.appendChild(l):(this.UM=l=document.createElement("div"),this.OD=m=document.createElement("div"),h.appendChild(l),h.appendChild(e),h.appendChild(m));c&&(c=e.offsetHeight,k=k.offsetHeight,c>k&&(f.marginBottom=k-c+"px"));
a.uf(e,"scroll",function(){b.Rfa()})};a.prototype.Jw=function(){return this.Lb()?"inline-block":"block"};a.prototype.xba=function(b,c,e){var f=this,h=document.createElement("div");this.Gk=h;b&&h.setAttribute("id",b);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");b=h.style;b.display=this.Jw();b.position="relative";if(c=this.Lb())b.verticalAlign="top";a.uf(h,"click",function(){f.O_()});this.iM?this.fL=a.z1(h,this.iM,c,!c):this.UM.appendChild(h);e&&h.appendChild(e)};a.prototype.jba=function(b,
c,e){var f=this,h=document.createElement("div");this.vj=h;b&&h.setAttribute("id",b);h.setAttribute("class",c);h.setAttribute("aria-hidden","true");b=h.style;b.display=this.Jw();b.position="relative";if(c=this.Lb())b.verticalAlign="top";a.uf(h,"click",function(){f.N_()});this.sD?this.RK=a.z1(h,this.sD,c,!c):this.OD.appendChild(h);e&&h.appendChild(e)};a.prototype.XV=function(){var a=this.Qs;a||(a=this.Ln);return a};a.prototype.$Y=function(){var a=this.UH,b=this.mT,e={Tf:0,ph:0},f=[];if(this.XV().hasChildNodes()&&
a&&b&&0<b.length)for(var a=this.Lb(),h=0,h=this.Ln.offsetWidth,k=0,l=null,m=0;m<b.length;m++){var n=b[m];if(1===n.nodeType){var p=n.offsetWidth,r=n.offsetHeight,s={Tf:p,ph:r,id:n.id};if(a){var q=n.offsetLeft;this.Qs||0!==q||(n=n.parentNode,q=n.offsetLeft);s.start=this.NA?h-(q+p):q;0===m&&(k=s.start);s.start-=k;e.Tf=s.start+p;e.ph=Math.max(e.ph,r);s.end=e.Tf-1}else q=n.offsetTop,this.Qs||0!==q||(n=n.parentNode,q=n.offsetTop),s.start=q,e.Tf=Math.max(e.Tf,p),e.ph=s.start+r,s.end=e.ph-1;l&&l.end>=s.start&&
(p=l.end-(s.start-1),l.end-=p,a?l.Tf-=p:l.ph-=p);f.push(s);l=s}}this.nD=f;return e};a.prototype.wt=function(){if(!this.nD){var a=this.$Y();this.ke||(this.ke=a)}return this.nD};a.prototype.rJ=function(){return this.RK?this.RK:this.vj};a.prototype.yJ=function(){return this.fL?this.fL:this.Gk};a.prototype.ula=function(){this.rJ().style.display=this.Jw()};a.prototype.vla=function(){this.yJ().style.display=this.Jw()};a.prototype.mC=function(){this.rJ().style.display="none"};a.prototype.nC=function(){this.yJ().style.display=
"none"};a.prototype.Ht=function(){return"none"!==this.rJ().style.display};a.prototype.ix=function(){return"none"!==this.yJ().style.display};a.prototype.SI=function(){return this.Lb()?this.QA:this.PA};a.prototype.jma=function(a){var b=this.SI(),e=this.$g(),f=this.lt(),h=this.KC();a<=this.rx?(this.ix()&&(f+=b,e-=b),this.nC()):h&&(this.ix()||(f-=b,e+=b),this.vla());a>=this.px?(this.Ht()&&(f+=b),this.mC()):h&&(this.Ht()||(f-=b),this.ula());this.TL(e);h?this.h0(f):this.ZT()};a.prototype.h0=function(a){var b=
this.fe.style;a+="px";this.Lb()?b.maxWidth=a:b.maxHeight=a};a.prototype.ZT=function(){var a=this.fe.style;this.Lb()?a.maxWidth="":a.maxHeight=""};a.prototype.TL=function(a){var b=this.fe;this.Lb()?b.scrollLeft=this.XH(a):b.scrollTop=a};a.prototype.lt=function(){var a=this.fe;return this.Lb()?a.offsetWidth:a.offsetHeight};a.prototype.au=function(a,b){this.En||(this.LA=!1,this.$_(a,b))};a.prototype.$_=function(b,c){if(!this.Xga()){this.En=!0;b=this.Naa(b);this.jma(b);var e=this.M_;if(c||!e||b===this.$g())this.pZ(this.LA?
this.$g():b);else{var f=this;e.call(this.Sp,this.fe,this.XH(b),Math.abs(this.$g()-b)/a.l9,function(){f.pZ(b)})}}};a.prototype.$g=function(){var a=this.fe;return this.Lb()?this.Taa(a.scrollLeft):a.scrollTop};a.prototype.KC=function(){var a=this.Ln,b=this.fe;return this.Lb()?a.offsetWidth>b.offsetWidth:a.offsetHeight>b.offsetHeight};a.prototype.Naa=function(a){!this.KC()||a<this.rx?a=this.rx:a>this.px&&(a=this.px);return a};a.prototype.Jfa=function(b){var c=this.En;if(this.KC()&&!this.En){var e=a.Eea(b);
0>e&&this.Ht()?(c=!0,this.N_()):0<e&&this.ix()&&(c=!0,this.O_())}c&&(b.preventDefault(),b.stopPropagation())};a.prototype.hK=function(a){a=a.touches;this.KC()&&!this.En&&1===a.length&&(this.gj=!0,a=a[0],this.yD=this.Lb()?a.pageX:a.pageY,this.sM=this.$g(),this.Yla=this.ET(),this.Zla=this.FT(),this.h1=this.Ht(),this.i1=this.ix())};a.prototype.gK=function(b){var c=this.Lb(),e=b.touches[0],e=(c?e.pageX:e.pageY)-this.yD,f=c&&this.NA?0<e:0>e,h=f&&this.h1||!f&&this.i1;if(this.gj&&h){h=this.fe;if(Math.abs(e)<
a.B9*(c?h.offsetWidth:h.offsetHeight)){if(this.au(this.sM-e,!0),this.h1&&!this.Ht()||this.i1&&!this.ix())this.gj=!1}else this.au(f?this.Yla:this.Zla,!1),this.gj=!1;this.Zt=!0}this.Zt&&(b.preventDefault(),b.stopPropagation())};a.prototype.eK=function(){this.gj&&this.au(this.sM,!1);this.Zt=this.gj=!1};a.prototype.Rfa=function(){this.LA&&!this.En&&this.$_(this.$g(),!0)};a.prototype.pZ=function(a){this.TL(a);this.Gka();this.En=!1;if(this.QI){this.gt=this.CT();a=this.DT();var b=this.wt(),e=b[this.gt];
this.gt!==a&&this.$g()>e.start&&this.gt<b.length-2&&(this.gt++,e=b[this.gt]);this.Sca=e.id;this.QI.call(this.Sp,this.Sca)}};a.prototype.Gka=function(){var a=this;window.setTimeout(function(){a&&(a.LA=!0)},0)};a.prototype.N_=function(){this.En||this.au(this.ET(),!1)};a.prototype.O_=function(){this.En||this.au(this.FT(),!1)};a.prototype.ET=function(){var a=this.gaa(),b=0;return b=a===this.CT()?this.$g()+this.lt():this.iaa(a)};a.prototype.FT=function(){var a=this.haa(),b=0,b=a===this.DT()?this.$g()-
this.lt():this.faa(a);this.Ht()||(b+=this.SI());b<this.SI()&&(b=this.rx);return b};a.prototype.iaa=function(a){return this.wt()[a].start};a.prototype.faa=function(a){return this.wt()[a].end-this.lt()+1};a.prototype.CT=function(){var a=this.SA(this.$g());return 0>a?0:a};a.prototype.DT=function(){var a=this.SA(this.$g()+this.lt()-1),b=this.wt();return 0>a?b.length-1:a};a.prototype.haa=function(){var a=this.SA(this.$g()-1);return 0>a?0:a};a.prototype.gaa=function(){var a=this.SA(this.$g()+this.lt()),
b=this.wt();return 0>a?b.length-1:a};a.prototype.SA=function(a){for(var b=this.wt(),e=0;e<b.length;e++)if(a<=b[e].end)return e;return-1};a.prototype.XH=function(a){var b=a;if(this.NA&&this.Lb())if(this.L$)b=-a;else if(this.N$||this.M$)b=this.Ln.offsetWidth-this.fe.offsetWidth-a;return b};a.prototype.Taa=function(a){return this.XH(a)};a.l9=1.1;a.B9=.33;(function(){b.ya("oj.ojConveyorBelt",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{orientation:"horizontal",contentParent:null},
_ComponentCreate:function(){this._super();this.element.addClass("oj-conveyorbelt oj-component");this.options.disabled&&b.r.warn(d);this.Aa(!0)},refresh:function(){this._super();var a="rtl"===this.ec()!==this.xf;a&&this.nI();this.Aa(a)},yl:function(){this._super();this.Zc&&this.Aa(this.Zc[0])},sn:function(){this._super();this.Zc&&this.Aa(this.Zc[0])},Aa:function(c){if(this.kw()){this.Zc=null;this.xf="rtl"===this.ec();var d=this.element,g=this.options;if(c&&!this.TA){var h=g.orientation,k=null,l=null,
m=null,n=null,p=null;"vertical"!==h?(k="oj-enabled oj-conveyorbelt-overflow-indicator oj-start oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-end oj-default",m=this.bB("oj-conveyorbelt-overflow-icon oj-start"),n=this.bB("oj-conveyorbelt-overflow-icon oj-end"),p=this.w$):(k="oj-enabled oj-conveyorbelt-overflow-indicator oj-top oj-default",l="oj-enabled oj-conveyorbelt-overflow-indicator oj-bottom oj-default",m=this.bB("oj-conveyorbelt-overflow-icon oj-top"),n=this.bB("oj-conveyorbelt-overflow-icon oj-bottom"),
p=this.x$);var r={};r.Q4=k;r.D4=l;r.P4=m;r.C4=n;k={};k.Nh=b.v.Nh;k.Oi=b.v.Oi;"enabled"!==b.ba.EN()&&(k.f5=p);p=null;g.contentParent&&(p=f(g.contentParent)[0]);this.TA=new a(d[0],h,p,this.xf,r,k)}this.TA.Pm(c);c&&(c=d.find(".oj-conveyorbelt-overflow-indicator"),this.jla(c))}else d=!1,this.Zc&&(d=this.Zc[0]),this.Zc=[c||d]},_destroy:function(){this.nI();this.element.removeClass("oj-conveyorbelt oj-component");this._super()},_setOption:function(a,e,f){var h=!1;switch(a){case "containerParent":case "orientation":h=
!0;break;case "disabled":b.r.warn(d)}h&&this.nI();this._super(a,e,f);h&&this.Aa(!0)},nI:function(){var a=this.TA;a&&(this.element.find(".oj-conveyorbelt-overflow-indicator").off(this.eventNamespace),a.destroy());this.TA=null},kw:function(){var a=document.createElement("div"),b=a.style;b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var d=!1;try{d=0<a.offsetWidth&&0<a.offsetHeight}catch(f){}b.removeChild(a);return d},jla:function(a){a.on("mousedown"+this.eventNamespace,function(a){f(a.currentTarget).addClass("oj-active")}).on("mouseup"+
this.eventNamespace,function(a){f(a.currentTarget).removeClass("oj-active")}).on("mouseenter"+this.eventNamespace,function(a){a=a.currentTarget;f(a).addClass("oj-hover");f(a).removeClass("oj-default")}).on("mouseleave"+this.eventNamespace,function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active");f(a).addClass("oj-default")})},bB:function(a){var b=document.createElement("span");b.setAttribute("class","oj-component-icon "+a);return b},w$:function(a,b,d,h){var k={};k.scrollLeft=
b;f(a).animate(k,d,"swing",h)},x$:function(a,b,d,h){var k={};k.scrollTop=b;f(a).animate(k,d,"swing",h)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-conveyorbelt-start-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-start")[0]:"oj-conveyorbelt-end-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-end")[0]:"oj-conveyorbelt-top-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-top")[0]:
"oj-conveyorbelt-bottom-overflow-indicator"===a?this.widget().find(".oj-conveyorbelt-overflow-indicator.oj-bottom")[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-conveyorbelt-start-overflow-indicator"}),d=this.getNodeBySubId({subId:"oj-conveyorbelt-end-overflow-indicator"}),f=this.getNodeBySubId({subId:"oj-conveyorbelt-top-overflow-indicator"}),k=this.getNodeBySubId({subId:"oj-conveyorbelt-bottom-overflow-indicator"}),l=this.element[0];a&&a!=l;){if(a===b)return{subId:"oj-conveyorbelt-start-overflow-indicator"};
if(a===d)return{subId:"oj-conveyorbelt-end-overflow-indicator"};if(a===f)return{subId:"oj-conveyorbelt-top-overflow-indicator"};if(a===k)return{subId:"oj-conveyorbelt-bottom-overflow-indicator"};a=a.parentElement}return null}});var d="JET ConveyorBelt: 'disabled' option not supported"})()});