/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(b,f){b.zc=function(a,d){this.data={};if(!(a instanceof b.j))throw Error(b.T.gc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+b.T.gc._ERR_DATA_INVALID_TYPE_DETAIL);b.zc.q.constructor.call(this,a,d);this.Xb=a;this.U9();this.Init();if(null!=d&&("enabled"==d.startFetch||null==d.startFetch)||null==d)this.cy=!0};o_("CollectionTableDataSource",b.zc,b);b.b.ga(b.zc,b.T,"oj.CollectionTableDataSource");b.zc.prototype.Init=function(){b.zc.q.Init.call(this)};
b.b.g("CollectionTableDataSource.prototype.Init",{Init:b.zc.prototype.Init});b.zc.prototype.at=function(a,d){d=d||{};d.deferred=!0;var c=this.Xb.at(a,d),e=this;e.hx=!0;var f;return new Promise(function(d,k){null!=c?c.then(function(b){e.hx=!1;f={data:b.attributes,index:a,key:b.id};d(f)},function(a){e.hx=!1;b.T.q.handleEvent.call(e,b.T.D.ERROR,a);k(a)}):d(null)})};b.b.g("CollectionTableDataSource.prototype.at",{at:b.zc.prototype.at});b.zc.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||
this.cy?this.De(a):Promise.resolve()};b.b.g("CollectionTableDataSource.prototype.fetch",{fetch:b.zc.prototype.fetch});b.zc.prototype.get=function(a,d){d=d||{};d.deferred=!0;var c=this.Xb.get(a,d),e=this,f;return new Promise(function(a,d){null!=c?c.then(function(b){f={data:b.attributes,index:b.index,key:b.id};a(f)},function(a){b.T.q.handleEvent.call(e,b.T.D.ERROR,a);d(a)}):a(null)})};b.b.g("CollectionTableDataSource.prototype.get",{get:b.zc.prototype.get});b.zc.prototype.sort=function(a){if(null==
a)return Promise.resolve();var b=this;return new Promise(function(c){b.zka(a);b.Xb.sort(null);c({header:a.key,direction:a.direction})})};b.b.g("CollectionTableDataSource.prototype.sort",{sort:b.zc.prototype.sort});b.zc.prototype.totalSize=function(){var a=0<=this.Xb.totalResults?this.Xb.totalResults:-1;if(-1<a){var b=this.Xb.size();return b>a?b:a}if(0<this.FI)a=this.FI;else if("atLeast"==this.totalSizeConfidence())return this.Xb.size();return a};b.b.g("CollectionTableDataSource.prototype.totalSize",
{totalSize:b.zc.prototype.totalSize});b.zc.prototype.totalSizeConfidence=function(){return 0<=this.Xb.totalResults?"actual":this.Xb.hasMore?"atLeast":"unknown"};b.b.g("CollectionTableDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.zc.prototype.totalSizeConfidence});b.zc.prototype.U9=function(){var a=this;this.Xb.on(b.Y.D.SYNC,function(d){if(d instanceof b.j&&!a.hx&&!a.oY){var c=d.offset,e=d.lastFetchCount;0<e?(a.$=c,a.La=e,a.hx=!0,d.Vr(c,c+e).then(function(b){a.hx=!1;var d=[],e=[],
f;for(f=0;f<b.length;f++)null!=b[f]&&(d.push(b[f].attributes),e.push(b[f].id));a.Zg.call(a,{silent:!1},{data:d,keys:e,startIndex:c},null)})):(d=a.oq(),a.Zg.call(a,{silent:!1},d,null))}});this.Xb.on(b.Y.D.ALLADDED,function(d,c){var e=[],f=[],h=[],k;for(k=0;k<c.length;k++)e.push(c[k].attributes),f.push(c[k].id),h.push(c[k].index);b.T.q.handleEvent.call(a,b.T.D.ADD,{data:e,keys:f,indexes:h})});this.Xb.on(b.Y.D.ALLREMOVED,function(d,c){var e=[],f=[],h=[],k;for(k=0;k<c.length;k++)e.push(c[k].attributes),
f.push(c[k].id),h.push(c[k].index);b.T.q.handleEvent.call(a,b.T.D.REMOVE,{data:e,keys:f,indexes:h})});this.Xb.on(b.Y.D.RESET,function(d){b.T.q.handleEvent.call(a,b.T.D.RESET,d)});this.Xb.on(b.Y.D.SORT,function(d,c){null!=c&&c.add||b.T.q.handleEvent.call(a,b.T.D.SORT,d)});this.Xb.on(b.Y.D.CHANGE,function(d){b.T.q.handleEvent.call(a,b.T.D.CHANGE,{data:[d.attributes],keys:[d.id],indexes:[d.index]})});this.Xb.on(b.Y.D.DESTROY,function(d){b.T.q.handleEvent.call(a,b.T.D.DESTROY,d)});this.Xb.on(b.Y.D.REFRESH,
function(d){b.T.q.handleEvent.call(a,b.T.D.REFRESH,d)});this.Xb.on(b.Y.D.ERROR,function(d,c,e){b.T.q.handleEvent.call(a,b.T.D.ERROR,d,c,e)})};b.zc.prototype.De=function(a){this.by(a);a=a||{};var b=this;this.fha=0<a.pageSize?!0:!1;this.$=null==a.startIndex?this.$:a.startIndex;this.sC=!0;this.La=0<a.pageSize?a.pageSize:-1;a.pageSize=this.La;a.startIndex=this.$;a.refresh=!0;return new Promise(function(c,e){if(b.fha)b.Xb.oz(b.$,b.La).then(function(e){var f=[],g=[],m;for(m=0;m<e.models.length;m++)f[m]=
e.models[m].attributes,g[m]=e.models[m].id;f={data:f,keys:g,startIndex:b.$};e.models.length<b.La?0>b.totalSize()&&(b.FI=b.$+e.models.length):b.FI=null;b.Zg.call(b,a,f,null);c(f)},function(c){b.Zg.call(b,a,null,c);e(c)});else if(0<b.Xb.size()){var f=b.oq();b.Zg.call(b,a,f,null);c(f)}else b.Xb.fetch({success:function(e){b.Xb=e;e=b.oq();b.Zg.call(b,a,e,null);c(e)},error:function(c,f){b.Xb=c;b.Zg.call(b,a,null,f);e(f)}})})};b.zc.prototype.by=function(a){this.oY=!0;a.silent||b.T.q.handleEvent.call(this,
b.T.D.REQUEST,{startIndex:a.startIndex})};b.zc.prototype.Zg=function(a,d,c){this.oY=!1;null!=c?b.T.q.handleEvent.call(this,b.T.D.ERROR,c):a.silent||b.T.q.handleEvent.call(this,b.T.D.SYNC,d)};b.zc.prototype.zka=function(a){if(null==a)this.Xb.comparator=null;else{var b=a.key;a=a.direction;var c=null;this.Xb.Xa()?(this.Xb.comparator=b,this.Xb.sortDirection="ascending"===a?1:-1):("ascending"==a?c=function(a){return f.isFunction(a.get)?a.get(b):a[b]()}:"descending"==a&&(c=function(a,c){var h,k;f.isFunction(a.get)?
(h=a.get(b),k=c.get(b)):(h=a[b](),k=c[b]());return h===k?0:h>k?-1:1}),this.Xb.comparator=c)}};b.zc.prototype.oq=function(){var a=this.Xb.size()-1,b=[],c=[],e;for(e=0;e<=a;e++)b[e]=this.Xb.at(e).attributes,c[e]=this.Xb.at(e).id;return{data:b,keys:c,startIndex:this.$}};b.zc.prototype.getCapability=function(){return null};b.b.g("CollectionTableDataSource.prototype.getCapability",{getCapability:b.zc.prototype.getCapability})});