/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(b){b.te=function(b,a,d,c,e){this.KE=b;this.Ba=a;this.fN=[];this.tz=d;this.start=c<a.length?c:a.length-1;this.count=-1===e?a.length:Math.min(a.length,e)};o_("CollectionNodeSet",b.te,b);b.te.prototype.PP=function(b){this.wV(this).then(function(){b.success&&b.success()})};b.te.prototype.wV=function(b){return new Promise(function(a){function d(e){e<c?b.s6(e,{success:function(a){null!==a?b.wV(a).then(function(){d(e+1)}):d(e+
1)}}):a(void 0)}var c=b.R();d(0)})};b.te.prototype.s6=function(b,a){var d=this.Ba.at(b);if(this.tz.Tu(d).leaf)this.fN[b]=null,a.success(null);else{var c=this.tz.yz(d),d=this.tz.Tu(d).key,e=this;this.tz.hv(c,0,-1,{success:function(c){e.fN[b]=c;a.success(c)}},d)}};b.te.prototype.getParent=function(){return this.KE};b.b.g("CollectionNodeSet.prototype.getParent",{getParent:b.te.prototype.getParent});b.te.prototype.ta=function(){return this.start};b.b.g("CollectionNodeSet.prototype.getStart",{ta:b.te.prototype.ta});
b.te.prototype.R=function(){return this.count};b.b.g("CollectionNodeSet.prototype.getCount",{R:b.te.prototype.R});b.te.prototype.getData=function(b){this.KH(b);return this.Ba.at(b).attributes};b.b.g("CollectionNodeSet.prototype.getData",{getData:b.te.prototype.getData});b.te.prototype.KH=function(b){if(b<this.start||b>this.start+this.count)throw"Out of range";};b.te.prototype.getMetadata=function(b){this.KH(b);var a={};b=this.Ba.at(b);b=this.tz.Tu(b);a.key=b.key;a.leaf=b.leaf;a.depth=b.depth;return a};
b.b.g("CollectionNodeSet.prototype.getMetadata",{getMetadata:b.te.prototype.getMetadata});b.te.prototype.Mf=function(b){this.KH(b);return this.fN[b]};b.b.g("CollectionNodeSet.prototype.getChildNodeSet",{Mf:b.te.prototype.Mf});b.Ia=function(f){f=f||{};this.lz=f.root;this.Zma=f.childCollectionCallback;this.Tu=f.parseMetadata;this.Gr=null;this.Xu="none";this.Rd={};b.Ia.q.constructor.call(this)};o_("CollectionTreeDataSource",b.Ia,b);b.Ia.prototype.Tu=function(b){return{key:b.idAttribute+"\x3d"+b.id}};
b.b.ga(b.Ia,b.wp,"oj.CollectionTreeDataSource");b.Ia.prototype.Init=function(){b.Ia.q.Init.call(this)};b.b.g("CollectionTreeDataSource.prototype.Init",{Init:b.Ia.prototype.Init});b.Ia.prototype.af=function(b){var a=this.Rd[b];if(a&&0<a.length)return a.length;this.HN(b,{success:function(a){return a.length}});return-1};b.b.g("CollectionTreeDataSource.prototype.getChildCount",{af:b.Ia.prototype.af});b.Ia.prototype.HN=function(b,a){this.Jf(b,null,{success:function(b){a.success(b.Ba)},error:a.error})};
b.b.g("CollectionTreeDataSource.prototype.getChildCollection",{HN:b.Ia.prototype.HN});b.Ia.prototype.Jf=function(b,a,d){a=a||{};var c=a.start?a.start:0,e=a.count?a.count:-1;if(null===b)this.hv(null,c,e,d,null);else{var g=this;this.pJ(this.lz,b,0).then(function(a){if(a){a=g.yz(a.Xo);try{g.hv(a,c,e,d,b)}catch(k){d&&d.error&&d.error({status:k.message})}}else d&&d.error&&d.error(b)})}};b.b.g("CollectionTreeDataSource.prototype.fetchChildren",{Jf:b.Ia.prototype.Jf});b.Ia.prototype.M6=function(b,a,d){var c=
0;d&&d.at&&(c=d.at);a=this.WB(a);b=this.aB(this,"insert",c,a,this.LZ(null!=a&&0<a.length?a[a.length-1]:null,b));this.handleEvent("change",b)};b.Ia.prototype.N6=function(b,a,d){var c=0;d&&d.index&&(c=d.index);this.Aja(b);b=this.aB(this,"delete",c,this.WB(a),null);this.handleEvent("change",b)};b.Ia.prototype.O6=function(b){var a=this.jda(b),d=null,c=null;a&&(d=a.index,c=this.WB(a.Ba));b=this.aB(this,"update",d,c,this.LZ(null!=c&&0<c.length?c[c.length-1]:null,b));this.handleEvent("change",b)};b.Ia.prototype.j6=
function(b){b=this.aB(this,"refresh",null,this.WB(b),null);this.handleEvent("refresh",b)};b.Ia.prototype.LZ=function(f,a){var d=new b.j;d.add(a);return this.DW(d,f,0,1)};b.Ia.prototype.WB=function(f){var a=[],d=null;do d=this.jea(f),null!==d&&(d!==b.Ia.rQ&&a.unshift(d),f=this.kda(d));while(null!=d);return a};b.Ia.rQ="%!@ROOT%#@!";b.Ia.prototype.FB=function(f){var a=f instanceof b.t?this.Tu(f).key:f;return f?a:b.Ia.rQ};b.Ia.prototype.RS=function(b){return this.Rd[this.FB(b)]};b.Ia.prototype.Y_=function(f,
a){a.on(b.Y.D.ADD,this.M6,this);a.on(b.Y.D.REMOVE,this.N6,this);a.on(b.Y.D.CHANGE,this.O6,this);a.on(b.Y.D.SYNC,this.j6,this);this.Rd[this.FB(f)]=a};b.Ia.prototype.Aja=function(b){b=this.FB(b);for(var a in this.Rd)if(this.Rd.hasOwnProperty(a)&&a===b){this.Rd[b].off(null,null,this);delete this.Rd[b];break}};b.Ia.prototype.qha=function(b,a){for(var d=a.length,c=0;c<d;c++){var e=this.FB(a.at(c));if(b===e)return!0}return!1};b.Ia.prototype.jda=function(b){for(var a in this.Rd)if(this.Rd.hasOwnProperty(a))for(var d=
this.Rd[a],c=0;c<d.length;c++)if(d.at(c)===b)return{index:c,Ba:d};return null};b.Ia.prototype.kda=function(b){for(var a in this.Rd)if(this.Rd.hasOwnProperty(a)){var d=this.Rd[a];if(this.qha(b,d))return d}return null};b.Ia.prototype.jea=function(b){for(var a in this.Rd)if(this.Rd.hasOwnProperty(a)&&this.Rd[a]===b)return a;return null};b.Ia.prototype.yz=function(b){var a=!0,d=this.RS(b);d||(a=!1,d=this.Zma(this.lz,b),null!=d&&(this.kT(d),this.Y_(b,d)));return{Ba:d,cN:a}};b.Ia.prototype.aB=function(b,
a,d,c,e){return{source:b,operation:a,index:d,parent:c,data:e}};b.Ia.prototype.hv=function(b,a,d,c,e){var g=this;null===b&&((b=this.RS(null))?b={Ba:b,cN:!0}:(b={Ba:g.lz,cN:!1},g.Y_(null,this.lz)));b&&g.tV(b,function(b){c.success&&c.success(g.DW(b,e,a,d))},c.error)};b.Ia.prototype.DW=function(f,a,d,c){return new b.te(a,f,this,d,c)};b.Ia.prototype.tka=function(b,a){var d=this;return new Promise(function(c){function e(a,b,f){a<b.length?b.at(a,{deferred:!0}).then(function(l){if(l){var m=d.Tu(l);if(f===
m.key){c(l);return}}a++;e(a,b,f)}):c(null)}e(0,b,a)})};b.Ia.prototype.pJ=function(b,a,d){var c=this;return new Promise(function(e){c.tka(b,a).then(function(g){function h(c,g){if(c<k){var n=g.yz(b.at(c));n.Ba?g.tV(n,function(b){g.pJ(b,a,d+1).then(function(a){a?e(a):(c++,h(c,g))})},null):(c++,h(c,g))}else e(null)}if(g)e({Xo:g,depth:d});else{var k=b.length;h(0,c)}})})};b.Ia.prototype.tV=function(b,a,d){b.cN?a(b.Ba):(this.Gr&&"none"!==this.Gr&&(b.Ba.iN=this.Gr,b.Ba.iP=this.Xu),0<b.Ba.length||!b.Ba.E6()?
a(b.Ba):b.Ba.fetch({success:function(b){a(b)},error:d}))};b.Ia.prototype.Cu=function(b,a){var d=this;null===b?this.hv(null,0,-1,{success:function(b){b.PP({success:function(){a.success&&a.success(b)}})}},null):this.pJ(this.lz,b,0).then(function(c){c&&(c=d.yz(c.Xo),d.hv(c,0,-1,{success:function(b){b.PP({success:function(){a.success&&a.success(b)}})}},b))})};b.b.g("CollectionTreeDataSource.prototype.fetchDescendants",{Cu:b.Ia.prototype.Cu});b.Ia.prototype.sort=function(b,a){var d=b.key,c=b.direction,
e=!1;d!==this.Gr&&(this.Gr=d,e=!0);c!==this.Xu&&(this.Xu=c,e=!0);if(e){"none"===this.Xu&&(this.Rd={});for(var g in this.Rd)this.Rd.hasOwnProperty(g)&&this.kT(this.Rd[g])}a&&a.success&&a.success()};b.b.g("CollectionTreeDataSource.prototype.sort",{sort:b.Ia.prototype.sort});b.Ia.prototype.kT=function(b){b.comparator=this.Gr;b.sortDirection="ascending"===this.Xu?1:-1;b.sort()};b.Ia.prototype.vm=function(){return{key:this.Gr,direction:this.Xu}};b.b.g("CollectionTreeDataSource.prototype.getSortCriteria",
{vm:b.Ia.prototype.vm});b.Ia.prototype.move=function(){b.l.Zb()};b.b.g("CollectionTreeDataSource.prototype.move",{move:b.Ia.prototype.move});b.Ia.prototype.qd=function(){return"invalid"};b.b.g("CollectionTreeDataSource.prototype.moveOK",{qd:b.Ia.prototype.qd});b.Ia.prototype.getCapability=function(b){return"sort"===b?"default":"move"===b?"none":"batchFetch"===b||"fetchDescendants"===b?"disable":null};b.b.g("CollectionTreeDataSource.prototype.getCapability",{getCapability:b.Ia.prototype.getCapability})});