/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojinputtext","ojs/ojvalidation","ojs/ojpopup","ojs/ojbutton"],function(b,f){function a(a){return this.options.converter.parse(a)}function d(a,c){var d=a.translations.dateTimeRange||{},e=[{category:"hint",entries:["min","max","inRange"]},{category:"messageDetail",entries:["rangeUnderflow","rangeOverflow"]},{category:"messageSummary",entries:["rangeUnderflow","rangeOverflow"]}],g={min:a.min,max:a.max,converter:c};if(!f.isEmptyObject(d))for(var h=
0,k=e.length;h<k;h++){var l=d[e[h].category];if(l){for(var w={},u=e[h].entries,y=0,x=u.length;y<x;y++)w[u[y]]=l[u[y]];g[e[h].category]=w}}return b.pa.Lr(b.ed.VALIDATOR_TYPE_DATETIMERANGE).createValidator(g)}function c(a,b){var c=a.filter("span");b?c.addClass("oj-disabled").removeClass("oj-enabled oj-default"):c.removeClass("oj-disabled").addClass("oj-enabled oj-default")}function e(a,b,c){if(!a||b===c.length)return a;var d=b+1;return e(a[c[b]],d,c)||e(a["*"],d,c)}function g(a,b){b.setHours(a.getHours());
b.setMinutes(a.getMinutes());b.setSeconds(a.getSeconds());b.setMilliseconds(a.getMilliseconds());return b}function h(a){return a.delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a","mouseout",function(){f(this).removeClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a",
"mouseover",function(){f(this).addClass("oj-hover")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a","focus",function(){f(this).addClass("oj-focus")}).delegate(".oj-datepicker-prev-icon, .oj-datepicker-prev-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-next-icon, .oj-datepicker-next-icon .oj-clickable-icon-nocontext.oj-component-icon, .oj-datepicker-calendar td a",
"blur",function(){f(this).removeClass("oj-focus")})}function k(a){var b=f(a.element[0]).parent().parent();a.Bn(b)}var l=b.pa.lm(b.Uj.CONVERTER_TYPE_DATETIME).createConverter({year:"numeric"});b.ya("oj.ojInputDate",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-only oj-component oj-inputdatetime",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_INPUT_HELPER_KEY:"inputHelp",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],
_GET_INIT_OPTIONS_PROPS:[{W:"disabled",yc:!0},{W:"pattern"},{W:"title"},{W:"placeholder"},{W:"value",Ze:a},{W:"required",Ze:!0,yc:!0},{W:"readonly",option:"readOnly",yc:!0},{W:"min",Ze:a},{W:"max",Ze:a}],TG:"oj-inputdatetime-input-trigger",SG:"oj-inputdatetime-calendar-icon",XQ:"oj-datepicker-current-day",cR:"oj-datepicker-days-cell-over",OS:"oj-datepicker-unselectable",bR:"oj-datepicker-desc",ZF:"oj-datepicker-calendar",v8:"oj-datepicker-div",d8:"oj-datepicker-inline",iG:" oj-inputdatetime-input-container",
e8:" oj-inputdatetime-inline",options:{datePicker:{footerLayout:"",changeMonth:"select",changeYear:"select",currentMonthPos:0,daysOutsideMonth:"hidden",numberOfMonths:1,showOn:"image",stepMonths:"numberOfMonths",stepBigMonths:12,weekDisplay:"none",yearRange:"c-10:c+10"},converter:b.pa.lm(b.Uj.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit"}),max:void 0,min:void 0,dayFormatter:null},$z:function(){this.md=null;this.pK=!1;this.ox=4;this.On=this.tk=this.Kl=this.ij=
this.rk=0;this.Cw={};var a=this.element[0].nodeName.toLowerCase();this.ce="div"===a||"span"===a;this.Md=h(f("\x3cdiv id\x3d'"+this.nn(this.v8)+"' role\x3d'region' aria-describedby\x3d'"+this.nn(this.bR)+"' class\x3d'oj-datepicker-content'\x3e\x3c/div\x3e"));f("body").append(this.Md);if(this.ce)this._WIDGET_CLASS_NAMES+=this.e8,this._CLASS_NAMES="";else{this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES+=this.iG;var b=this;this.aL=this.Md.ojPopup({initialFocus:"none",modality:"modeless",open:function(){b.Md.find(".oj-datepicker-calendar").focus()},
rootAttributes:{"class":"oj-datepicker-popup"}})}},_ComponentCreate:function(){this.$z();var a=this._super();this.options.dayMetaData&&(this.options.dayFormatter=function(a){return function(b){return e(a,0,[b.fullYear,b.month,b.date])}}(this.options.dayMetaData));this.dD(this.KB());this.ce?(this.element.append(this.Md),this.element.addClass(this.d8),this.Md.css("display","block")):this.fH();k(this);return a},mf:function(){var a=this._superApply(arguments);this.$U(this.options.disabled);return a},
_setOption:function(a,c,d){var g=null;if("value"===a)return c||(c=null),g=this._super(a,c,d),this.dD(c),this.Il()&&this.yo(!0),g;if("dayMetaData"===a)this._setOption("dayFormatter",function(a){return e(c,0,[a.fullYear,a.month,a.date])},d);else return g=this._super(a,c,d),"disabled"===a?this.$U(c):"max"===a||"min"===a?(this.Cw[b.ed.VALIDATOR_TYPE_DATETIMERANGE]=this.fC("min"),this.fs()):"readOnly"===a&&c?this.hide():"dayFormatter"===a&&(this.Cw[b.ed.VALIDATOR_TYPE_DATERESTRICTION]=this.fC("dayFormatter"),
this.fs()),"datePicker"===a&&"currentMonthPos"===d.subkey&&this.dD(this.options.value),d={max:!0,min:!0,dayFormatter:!0,datePicker:!0,translations:!0},this.Il()&&a in d&&this.yo(),g},VF:function(){return this.md},_destroy:function(){var a=this._super();this.element.off("focus");this.md&&this.md.remove();this.ce&&(this.element.removeProp("disabled"),this.element.removeProp("readonly"));this.Md.remove();return a},Il:function(){return this.ce||this.aL.ojPopup("isOpen")},fH:function(){var a=this.options.datePicker.showOn,
b=f("\x3cspan\x3e").addClass(this.TG);if("focus"===a)this.element.on("focus",f.proxy(this.show,this));a=f("\x3cspan title\x3d'"+this.UI()+"'/\x3e").addClass(this.SG+" oj-clickable-icon-nocontext oj-component-icon");b.append(a);var c=this;a.on("click",function(){c.Il()?c.hide():c.show();return!1});this.Bn(a);this._hoverable(a);this.FM=a;this.md=b;this.element.after(b)},eca:function(a){var b;b=!1;var c=f.ui.keyCode,d=this.zj;if(this.Il())switch(a.keyCode){case 84:a.altKey&&a.ctrlKey&&(this.Md.find(".oj-datepicker-current").focus(),
b=!0);break;case c.TAB:this.hide();break;case c.ENTER:return b=f("td."+this.cR+":not(."+this.XQ+")",this.Md),b[0]&&this.R_(this.ij,this.tk,b[0],a),a.preventDefault(),a.stopPropagation(),!1;case c.ESCAPE:this.hide();this.element.focus();b=!0;break;case c.PAGE_UP:a.ctrlKey&&a.altKey?this.vf(-this.options.datePicker.stepBigMonths,"M",!0):a.altKey?this.vf(-1,"Y",!0):this.vf(-this.Vw(),"M",!0);b=!0;break;case c.PAGE_DOWN:a.ctrlKey&&a.altKey?this.vf(+this.options.datePicker.stepBigMonths,"M",!0):a.altKey?
this.vf(1,"Y",!0):this.vf(+this.Vw(),"M",!0);b=!0;break;case c.END:this.rk=this.Lw(this.tk,this.ij);this.yo(!0);b=!0;break;case c.HOME:this.rk=1;this.yo(!0);b=!0;break;case c.LEFT:this.vf(d?1:-1,"D",!0);a.originalEvent.altKey&&this.vf(a.ctrlKey?-this.options.datePicker.stepBigMonths:-this.Vw(),"M",!0);b=!0;break;case c.UP:this.vf(-7,"D",!0);b=!0;break;case c.RIGHT:this.vf(d?-1:1,"D",!0);a.originalEvent.altKey&&this.vf(a.ctrlKey?+this.options.datePicker.stepBigMonths:+this.Vw(),"M",!0);b=!0;break;
case c.DOWN:this.vf(7,"D",!0),b=!0}else a.keyCode===c.HOME&&a.ctrlKey&&(this.show(),b=!0);b&&(a.preventDefault(),a.stopPropagation())},yo:function(a){this.ox=4;var b=this.Xca();this.Md.empty().append(b.html);var c=f("button",this.Md);0<c.length&&(1===c.length&&f(c[0]).addClass("oj-datepicker-single-button"),f.each(c,function(a,b){f(b).ojButton()}));this.F$();b.r2&&this.Md.find(".oj-datepicker-calendar").attr("aria-activedescendant",b.r2);b=this.tJ();c=b[1];this.Md.removeClass("oj-datepicker-multi-2 oj-datepicker-multi-3 oj-datepicker-multi-4").width("");
1<c&&this.Md.addClass("oj-datepicker-multi-"+c).css("width",17*c+"em");this.Md[(1!==b[0]||1!==b[1]?"add":"remove")+"Class"]("oj-datepicker-multi");this.Il()&&this.element.is(":visible")&&!this.element.is(":disabled")&&(a?(a=this.Md.find(".oj-datepicker-calendar"),a[0]!==document.activeElement&&a.focus()):this.ce||this.element[0]===document.activeElement||this.element.focus())},vf:function(a,b,c){this.options.disabled||(this.cT(a+("M"===b?this.options.datePicker.currentMonthPos:0),b),this.yo(c))},
Hea:function(){var a=new Date;this.rk=a.getDate();this.Kl=this.ij=a.getMonth();this.On=this.tk=a.getFullYear();this.vf()},S_:function(a,c){var d=parseInt(a.options[a.selectedIndex].value,10);"M"===c?this.ij=this.Kl=d:this.tk=this.On=d;f("#"+this.nn(this.ZF)).html(this.ck(this.options.monthWide[this.Kl])+" "+l.format(b.sb.dateToLocalIso(new Date(this.On,this.Kl,1))));this.vf(0,0,!0)},R_:function(a,c,d,e){f(d).hasClass(this.OS)||this.options.disabled||(this.rk=f("a",d).html(),this.ij=a,this.tk=c,a=
b.sb,(c=this.options.value?a.isoToLocalDate(this.options.value):null)?(d=new Date(this.tk,this.ij,this.rk),g(c,d),c=d):c=new Date(this.tk,this.ij,this.rk),a=a.dateToLocalIso(c),c=this.Uc().format(a),this.oi(c),this.hc(a,e),this.hide())},oI:function(a,c){return a?"string"===typeof a?b.sb.isoToLocalDate(a):new Date(a.getTime()):c},dD:function(a){a=this.oI(a,this.fX());this.rk=a.getDate();this.Kl=this.ij=a.getMonth();this.On=this.tk=a.getFullYear();this.cT()},Vw:function(){var a=this.options.datePicker.stepMonths;
return f.isNumeric(a)?a:this.options.datePicker.numberOfMonths},F$:function(){var a=this.Vw(),b=this;this.Md.find("[data-handler]").map(function(){f(this).bind(this.getAttribute("data-event"),{prev:function(c){b.vf(-a,"M",!0);c.preventDefault()},next:function(c){b.vf(+a,"M",!0);c.preventDefault()},today:function(a){if("keyup"===a.type&&13===a.keyCode||"click"===a.type)b.Hea(),a.preventDefault(),a.stopPropagation()},selectDay:function(a){b.R_(+this.getAttribute("data-month"),+this.getAttribute("data-year"),
this,a);return!1},selectMonth:function(){b.S_(this,"M");return!1},selectYear:function(){b.S_(this,"Y");return!1},calendarKey:function(a){b.eca(a)}}[this.getAttribute("data-handler")])})},sia:function(a,b,c){b=b?new Date(b.getFullYear(),b.getMonth(),b.getDate()):null;c=c?new Date(c.getFullYear(),c.getMonth(),c.getDate()):null;return null!==b&&a<b||null!==c&&a>c},Xca:function(){var a,c,d,e,g,f,h=this.options.dayWide,k=this.options.dayNarrow,l=this.options.monthWide,u=this.options.monthAbbreviated,y=
this.options.firstDayOfWeek,x,B,O,J,F,D,z,A="",E,L,C,M,G,I,N,H,P=new Date,P=new Date(P.getFullYear(),P.getMonth(),P.getDate()),Q=this.zj;f=this.options.datePicker.footerLayout;var W=this.tJ(),K=this.options.datePicker.currentMonthPos,V=this.options.dayFormatter;H=null;var Z=1!==W[0]||1!==W[1],X=this.TB("min"),R=this.TB("max"),K=this.Kl-K,U=this.On,ha=new Date(this.tk,this.ij,this.rk),Y=new Date(this.KB()),T=Y.getDate(),aa=Y.getMonth(),fa=Y.getFullYear(),ba=this.options.disabled,S=this.ck(this.A("weekText")),
ca=b.sb;Y.setHours(0);Y.setMinutes(0);Y.setSeconds(0);Y.setMilliseconds(0);0>K&&(K+=12,U--);if(X)for(a=new Date(X.getFullYear(),X.getMonth(),X.getDate()),a=R&&R<a?R:a;new Date(U,K,this.Lw(U,K))<a;)K++,11<K&&(K=0,U++);if(R)for(a=new Date(R.getFullYear(),R.getMonth()-W[0]*W[1]+1,R.getDate()),a=X&&a<X?X:a;new Date(U,K,1)>a;)K--,0>K&&(K=11,U--);this.Kl=K;this.On=U;a=this.ck(this.A("prevText"));a=this.KT(-1,U,K)&&!ba?"\x3ca href\x3d'#' class\x3d'oj-datepicker-prev-icon oj-enabled oj-default oj-component-icon oj-clickable-icon-nocontext' data-handler\x3d'prev' data-event\x3d'click' title\x3d'"+
a+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-prev-icon oj-disabled oj-component-icon oj-clickable-icon-nocontext' title\x3d'"+a+"'\x3e\x3c/a\x3e";c=this.ck(this.A("nextText"));c=this.KT(1,U,K)&&!ba?"\x3ca href\x3d'#' class\x3d'oj-datepicker-next-icon oj-enabled oj-default oj-component-icon oj-clickable-icon-nocontext' data-handler\x3d'next' data-event\x3d'click' title\x3d'"+c+"'\x3e\x3c/a\x3e":"\x3ca class\x3d'oj-datepicker-next-icon oj-disabled oj-component-icon oj-clickable-icon-nocontext' title\x3d'"+
c+"'\x3e\x3c/a\x3e";d=this.ck(this.A("currentText"));g="";e="\x3cbutton type\x3d'button' class\x3d'oj-datepicker-current oj-priority-secondary' data-handler\x3d'today' data-event\x3d'click keyup'\x3e"+d+"\x3c/button\x3e";if(1<f.length){d=0;f=[{index:f.indexOf("today"),content:this.sY(P)?e:""}];for(f.sort(function(a,b){return a.index-b.index});d<f.length&&0>f[d].index;)d++;for(;d<f.length;)g+=f[d++].content;0<g.length&&(g="\x3cdiv class\x3d'oj-datepicker-buttonpane'\x3e"+g+"\x3c/div\x3e")}f=this.options.datePicker.weekDisplay;
d=this.options.datePicker.daysOutsideMonth;e="";x="all";for(B=0;B<W[0];B++){O="";this.ox=4;for(J=0;J<W[1];J++){x="all";E="";if(Z){E+="\x3cdiv class\x3d'oj-datepicker-group";if(1<W[1])switch(J){case 0:E+=" oj-datepicker-group-first";x=Q?"right":"left";break;case W[1]-1:E+=" oj-datepicker-group-last";x=Q?"left":"right";break;default:E+=" oj-datepicker-group-middle",x=""}E+="'\x3e"}E+="\x3cdiv class\x3d'oj-datepicker-header"+(ba?" oj-disabled ":" oj-enabled oj-default ")+"'\x3e"+(/all|left/.test(x)&&
0===B?Q?c:a:"")+(/all|right/.test(x)&&0===B?Q?a:c:"")+this.Yca(K,U,X,R,0<B||0<J,l,u,Z)+"\x3c/div\x3e\x3ctable class\x3d'oj-datepicker-calendar"+(ba?" oj-disabled ":" oj-enabled oj-default ")+"' tabindex\x3d-1 data-handler\x3d'calendarKey' data-event\x3d'keydown' aria-readonly\x3d'true' role\x3d'grid' aria-labelledby\x3d'"+this.nn(this.ZF)+"'\x3e\x3cthead role\x3d'presentation'\x3e\x3ctr role\x3d'row'\x3e";L="number"===f?"\x3cth class\x3d'oj-datepicker-week-col'\x3e"+this.ck(this.A("weekHeader"))+
"\x3c/th\x3e":"";for(x=0;7>x;x++)C=(x+parseInt(y,10))%7,L+="\x3cth role\x3d'columnheader' aria-label\x3d'"+h[C]+"'"+(5<=(x+y+6)%7?" class\x3d'oj-datepicker-week-end'":"")+"\x3e\x3cspan title\x3d'"+h[C]+"'\x3e"+k[C]+"\x3c/span\x3e\x3c/th\x3e";E+=L+"\x3c/tr\x3e\x3c/thead\x3e\x3ctbody role\x3d'presentation'\x3e";L=this.Lw(U,K);U===fa&&K===aa&&(T=Math.min(T,L));x=(this.Cda(U,K)-y+7)%7;L=Math.ceil((x+L)/7);this.ox=L=Z?this.ox>L?this.ox:L:L;C=new Date(U,K,1-x);for(M=0;M<L;M++){E+="\x3ctr role\x3d'row'\x3e";
x=this.Uc().Go(ca.dateToLocalIso(C));G="none"===f?"":"\x3ctd class\x3d'oj-datepicker-week-col' role\x3d'rowheader' aria-label\x3d'"+S+" "+x+"'\x3e"+x+"\x3c/td\x3e";for(x=0;7>x;x++){N=C.getMonth()!==K;F=C.getTime()===Y.getTime();D="oj-dp-"+this.uuid+"-"+M+"-"+x+"-"+B+"-"+J;(z=C.getTime()===ha.getTime()&&K===this.ij)&&(A=D);I=[!0,""];H=C.getFullYear();var da=C.getMonth(),ga=C.getDate();V&&(H=V({fullYear:H,month:da+1,date:ga}))&&(I=[!H.disabled,H.className||""],H.tooltip&&I.push(H.tooltip));da=C.getTime()===
Y.getTime();H=N&&"selectable"!==d||!I[0]||this.sia(C,X,R);G+="\x3ctd role\x3d'gridcell' aria-disabled\x3d'"+!!H+"' aria-selected\x3d'"+F+"' id\x3d'"+D+"' class\x3d'"+(5<=(x+y+6)%7?" oj-datepicker-week-end":"")+(N?" oj-datepicker-other-month":"")+(z?" "+this.cR:"")+(H||ba?" "+this.OS+" oj-disabled":" oj-enabled ")+(N&&"hidden"===d?"":" "+I[1]+(F?" "+this.XQ:"")+(C.getTime()===P.getTime()?" oj-datepicker-today":""))+"'"+(N&&"hidden"===d||!I[2]?"":" title\x3d'"+I[2].replace(/'/g,"\x26#39;")+"'")+(H?
"":" data-handler\x3d'selectDay' data-event\x3d'click' data-month\x3d'"+C.getMonth()+"' data-year\x3d'"+C.getFullYear()+"'")+"\x3e"+(N&&"hidden"===d?"\x26#xa0;":H||ba?"\x3cspan class\x3d'oj-disabled'\x3e"+C.getDate()+"\x3c/span\x3e":"\x3ca class\x3d'oj-enabled"+(da?" oj-selected":"")+(N?" oj-priority-secondary":"")+"' "+(da||z?"":"tabindex\x3d'-1' ")+" href\x3d'#'\x3e"+C.getDate()+"\x3c/a\x3e")+"\x3c/td\x3e";C.setDate(C.getDate()+1)}E+=G+"\x3c/tr\x3e"}K++;11<K&&(K=0,U++);E+="\x3c/tbody\x3e\x3c/table\x3e"+
(Z?"\x3c/div\x3e"+(0<W[0]&&J===W[1]-1?"\x3cdiv class\x3d'oj-datepicker-row-break'\x3e\x3c/div\x3e":""):"");O+=E}e+=O}return{html:e+g,r2:A}},Yca:function(a,c,d,e,g,f,h,k){var w,u,y,x,B=this.options.datePicker.changeMonth,O=this.options.datePicker.changeYear,J=b.Ja.X3()?"before":"after",F="\x3cdiv class\x3d'oj-datepicker-title' role\x3d'header'\x3e",D="",z=this.options.disabled,A=b.sb;if(g||"none"===B)D+="\x3cspan class\x3d'oj-datepicker-month'\x3e"+f[a]+"\x3c/span\x3e";else{w=d&&d.getFullYear()===
c;u=e&&e.getFullYear()===c;D+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-month "+(z?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectMonth' data-event\x3d'change' role\x3d'listbox'\x3e";for(y=0;12>y;y++)(!w||y>=d.getMonth())&&(!u||y<=e.getMonth())&&(D+="\x3coption role\x3d'option' value\x3d'"+y+"' aria-selected\x3d'"+(y===a?"true' selected\x3d'selected'":"false'")+"\x3e"+h[y]+"\x3c/option\x3e");D+="\x3c/select\x3e"}"before"===J&&(F+=D+(g||"select"!==B||"select"!==O?"\x26#xa0;":
""));if(!this.Um)if(this.Um="",g||"none"===O)F+="\x3cspan class\x3d'oj-datepicker-year'\x3e"+l.format(A.dateToLocalIso(new Date(c,a,1)))+"\x3c/span\x3e";else{w=this.options.datePicker.yearRange.split(":");x=(new Date).getFullYear();u=function(a){a=a.match(/c[+\-].*/)?c+parseInt(a.substring(1),10):a.match(/[+\-].*/)?x+parseInt(a,10):parseInt(a,10);return isNaN(a)?x:a};h=u(w[0]);w=Math.max(h,u(w[1]||""));h=d?Math.max(h,d.getFullYear()):h;w=e?Math.min(w,e.getFullYear()):w;for(this.Um+="\x3cselect tabindex\x3d'-1' class\x3d'oj-datepicker-year "+
(z?"oj-disabled' disabled":"oj-enabled'")+" data-handler\x3d'selectYear' data-event\x3d'change' role\x3d'listbox'\x3e";h<=w;h++)this.Um+="\x3coption role\x3d'option' value\x3d'"+h+"' aria-selected\x3d'"+(h===c?"true' selected\x3d'selected'":"false'")+"\x3e"+l.format(A.dateToLocalIso(new Date(h,a,1)))+"\x3c/option\x3e";this.Um+="\x3c/select\x3e";F+=this.Um;this.Um=null}"after"===J&&(F+=(g||"select"!==B||"select"!==O?"\x26#xa0;":"")+D);k&&g||(F+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+
this.nn(this.ZF)+"'\x3e"+f[a]+" "+l.format(A.dateToLocalIso(new Date(c,a,1)))+"\x3c/span\x3e",F+="\x3cspan class\x3d'oj-helper-hidden-accessible' id\x3d'"+this.nn(this.bR)+"'\x3e"+this.ck(this.A("datePicker"))+"\x3c/span\x3e");return F+"\x3c/div\x3e"},cT:function(a,b){var c=this.On+("Y"===b?a:0),d=this.Kl+("M"===b?a:0),e=Math.min(this.rk,this.Lw(c,d))+("D"===b?a:0),c=new Date(c,d,e);this.rk=c.getDate();this.Kl=this.ij=c.getMonth();this.On=this.tk=c.getFullYear()},tJ:function(){var a=this.options.datePicker.numberOfMonths,
a="string"===typeof a?parseInt(a,10):a;return null==a?[1,1]:"number"===typeof a?[1,a]:a},TB:function(a){return this.oI(this.options[a],null)},Lw:function(a,b){return 32-(new Date(a,b,32)).getDate()},Cda:function(a,b){return(new Date(a,b,1)).getDay()},KT:function(a,b,c){var d=this.tJ();b=new Date(b,c+(0>a?a:d[0]*d[1]),1);0>a&&b.setDate(this.Lw(b.getFullYear(),b.getMonth()));return this.sY(b)},sY:function(a){var b,c,d=this.TB("min"),e=this.TB("max"),g=null,f=null;if(b=this.options.datePicker.yearRange)b=
b.split(":"),c=(new Date).getFullYear(),g=parseInt(b[0],10),f=parseInt(b[1],10),b[0].match(/[+\-].*/)&&(g+=c),b[1].match(/[+\-].*/)&&(f+=c);return(!d||a.getTime()>=d.getTime())&&(!e||a.getTime()<=e.getTime())&&(!g||a.getFullYear()>=g)&&(!f||a.getFullYear()<=f)},UI:function(){return this.ck(this.A("tooltipCalendar"+(this.options.disabled?"Disabled":"")))},$U:function(a){this.md&&(c(this.md.children(),a),this.md.find("."+this.SG).attr("title",this.UI()));a&&this.hide();this.ce&&this.yo()},UF:function(){this.ce||
this._superApply(arguments)},WK:function(a){this.ce||this._superApply(arguments)},MC:function(a){if(!this.ce){this._superApply(arguments);var b=f.ui.keyCode,c=!1;if(this.Il())switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:this.Md.find(".oj-datepicker-calendar").focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.hc(this.hg(),a),this.show(),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},oi:function(a){this.ce||this._superApply(arguments);
this.dD(this.KB());this.Il()&&this.yo(!0)},Uc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDate.prototype.options.converter},qs:function(){return this.options.value||""},_GetDefaultStyleClass:function(){return"oj-inputdate"},Lv:function(){var a=this._superApply(arguments);if(null!=this.options.min||null!=this.options.max)this.Cw[b.ed.VALIDATOR_TYPE_DATETIMERANGE]=this.fC("min");null!=this.options.dayFormatter&&(this.Cw[b.ed.VALIDATOR_TYPE_DATERESTRICTION]=this.fC("dayFormatter"));
return f.extend(this.Cw,a)},li:function(){this.hide()},xl:function(){this.hide()},fC:function(a){var c=null;"min"===a||"max"===a?c=d(this.options,this.Uc()):"dayFormatter"===a&&(a={dayFormatter:this.options.dayFormatter,converter:this.Uc()},f.extend(a,this.options.translations.dateRestriction||{}),c=b.pa.Lr(b.ed.VALIDATOR_TYPE_DATERESTRICTION).createValidator(a));return c},fX:function(){var a=new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a},KB:function(){return this.oI(this.options.value,
this.fX())},getNodeBySubId:function(a){var b=null,c=a&&a.subId,d=this.Md;if(c)switch(c){case "oj-datepicker-content":b=d[0];break;case "oj-inputdatetime-calendar-icon":b=f(".oj-inputdatetime-calendar-icon",this.md)[0];break;case "oj-datepicker-prev-icon":b=f(".oj-datepicker-prev-icon",d)[0];break;case "oj-datepicker-next-icon":b=f(".oj-datepicker-next-icon",d)[0];break;case "oj-datepicker-month":b=f(".oj-datepicker-month",d)[0];break;case "oj-datepicker-year":b=f(".oj-datepicker-year",d)[0];break;
case "oj-datepicker-current":b=f(".oj-datepicker-current",d)[0];break;case "oj-inputdatetime-date-input":b=this.ce?null:this.element[0];break;default:b=null}return b||this._superApply(arguments)},getSubIdByNode:function(a){var b=this.Md,c=null,d=[{selector:".oj-inputdatetime-calendar-icon",ele:this.md},{selector:".oj-datepicker-prev-icon",ele:b},{selector:".oj-datepicker-next-icon",ele:b},{selector:".oj-datepicker-month",ele:b},{selector:".oj-datepicker-year",ele:b},{selector:".oj-datepicker-current",
ele:b}];if(a===b[0])return"oj-datepicker-content";if(!this.ce&&a===this.element[0])return"oj-inputdatetime-date-input";for(var b=0,e=d.length;b<e;b++){var g=d[b],h=f(g.selector,g.ele);if(1===h.length&&h[0]===a){c=g.selector.substr(1);break}}return c||this._superApply(arguments)},hide:function(){this.Il()&&!this.ce&&(this.aL.ojPopup("close"),"focus"===this.options.datePicker.showOn&&(this.pK=!0),this.element.focus());return this},refresh:function(){this.md&&this.md.find("."+this.SG).attr("title",this.UI());
return this._superApply(arguments)||this},show:function(){if(!(this.Il()||this.options.disabled||this.options.readOnly))if(this.pK)this.pK=!1;else{var a=this.zj;this.Md.empty();this.yo();a=b.qc.Gg({my:"start top",at:"start bottom",of:this.element,collision:"flipfit flipfit"},a);this.aL.ojPopup("open",this.FM,a);return this}}});b.Components.Om({ojInputDate:{firstDayOfWeek:b.Components.nh(function(){return b.Ja.W2()}),dayWide:b.Components.nh(function(){return b.Ja.Iy("wide")}),dayNarrow:b.Components.nh(function(){return b.Ja.Iy("narrow")}),
monthWide:b.Components.nh(function(){return b.Ja.Ky("wide")}),monthAbbreviated:b.Components.nh(function(){return b.Ja.Ky("abbreviated")}),datePicker:b.Components.nh(function(){return b.ze.Yk("inputDate").datePicker})}});b.ya("oj.ojInputTime",f.oj.inputBase,{version:"1.0.0",widgetEventPrefix:"oj",_CLASS_NAMES:"oj-inputdatetime-input",_WIDGET_CLASS_NAMES:"oj-inputdatetime-time-only oj-component oj-inputdatetime",iG:"oj-inputdatetime-input-container",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_INPUT_HELPER_KEY:"inputHelp",
_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_GET_INIT_OPTIONS_PROPS:[{W:"disabled",yc:!0},{W:"pattern"},{W:"title"},{W:"placeholder"},{W:"value",Ze:a},{W:"required",Ze:!0,yc:!0},{W:"readonly",option:"readOnly",yc:!0},{W:"min",Ze:a},{W:"max",Ze:a}],J9:"ojInputTime",TG:"oj-inputdatetime-input-trigger",UG:"oj-inputdatetime-time-icon",options:{converter:b.pa.lm(b.Uj.CONVERTER_TYPE_DATETIME).createConverter({hour:"2-digit",hour12:!0,minute:"2-digit"}),max:void 0,min:void 0,datePickerComp:null,timePicker:{timeIncrement:"00:30:00:00"}},
Yd:function(a,c){this._super(a,c);null===this.options.datePickerComp&&b.ve.al(this._GET_INIT_OPTIONS_PROPS,c,this)},$z:function(){this.nM={};this.Hl=this.options.datePickerComp;this.tg=f("\x3cdiv id\x3d'"+this.nn(this.J9)+"' class\x3d'oj-listbox-drop' style\x3d'display:none'\x3e\x3c/div\x3e");f("body").append(this.tg);var a=this;this.bL=this.tg.ojPopup({initialFocus:"none",rootAttributes:{"class":"datetimepicker-dropdown"},chrome:"none",modality:"modeless",open:function(){var b=f("[aria-selected]",
a.tg);1===b.length&&a.OT(b.parent(),!0);f("ul",a.tg).focus()},beforeClose:function(){a.e1=f("ul",a.tg).scrollTop()}});this.bo()&&(this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES+=this.iG)},hy:function(){return this.bL.ojPopup("isOpen")},_ComponentCreate:function(){this.$z();var a=this._superApply(arguments);this.Xl()&&!this.mY()?this._CLASS_NAMES="":k(this);this.fH();return a},mf:function(){var a=this._superApply(arguments);c(this.md.children(),this.options.disabled);return a},_setOption:function(a,e,g){var f=
null;if("value"===a)return e||(e=null),f=this._super(a,e,g),this.CB(),f;f=this._superApply(arguments);"disabled"===a?(e&&this.hide(),this.md.find("."+this.UG).attr("title",this.JJ()),c(this.md.children(),e)):"max"!==a&&"min"!==a||this.Xl()?"readOnly"===a&&e&&this.hide():(this.nM[b.ed.VALIDATOR_TYPE_DATETIMERANGE]=d(this.options,this.Uc()),this.fs());a in{max:!0,min:!0,converter:!0,timePicker:!0}&&this.CB();return f},_destroy:function(){var a=this._super();this.md&&this.md.remove();this.tg.remove();
return a},UF:function(){this.bo()&&this._superApply(arguments)},VF:function(){return this.md},MC:function(a){if(this.bo()){this._superApply(arguments);var b=f.ui.keyCode,c=!1;if(this.hy())switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();c=!0;break;case b.UP:case b.DOWN:f("ul",this.tg).focus(),c=!0}else switch(a.keyCode){case b.UP:case b.DOWN:this.hc(this.hg(),a),this.show(),c=!0}if(c||a.keyCode===b.ENTER)return a.preventDefault(),a.stopPropagation(),!1}},JJ:function(){return this.ck(this.A("tooltipTime"+
(this.options.disabled?"Disabled":"")))},fH:function(){var a=this.bo(),b=a?f("\x3cspan\x3e").addClass(this.TG):f("+ span",this.element),c=f("\x3cspan title\x3d'"+this.JJ()+"'/\x3e").addClass(this.UG+" oj-clickable-icon-nocontext oj-component-icon");b.append(c);var d=this;c.on("click",function(){d.hy()?d.hide():d.show()});this.Bn(c);this._hoverable(c);this.FM=c;this.md=b;a&&this.element.after(b)},jga:function(a,b,c){return null!==b&&a<b||null!==c&&a>c},rq:function(){return this.Xl()?this.Hl.widget.A3():
this.options.value},CB:function(){var a=this.rq(),c=this.Uc(),d=f("\x3cul class\x3d'oj-listbox-results' tabindex\x3d'-1' role\x3d'listbox'\x3e\x3c/ul\x3e"),c=a?c.format(a):"",e=[],g,a=a?b.sb.isoToLocalDate(a):new Date;a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);e=this.zea(a);c=c||e[0].value;this.tg.empty();a=0;for(g=e.length;a<g;a++){var h=e[a].value,k=e[a].minMaxRange,l=f("\x3cli class\x3d'oj-listbox-result "+(k?"oj-disabled":"")+"' role\x3d'presentation'\x3e"),w=this.uuid+
"_sel"+a,k=f("\x3cdiv class\x3d'oj-listbox-result-label' "+(k?"aria-disabled ":"")+"data-value\x3d'"+h+"' role\x3d'option' id\x3d'"+w+"'\x3e"+e[a].label+"\x3c/li\x3e");c===h&&(k.attr("aria-selected","true"),l.addClass("oj-hover"),d.attr("aria-activedescendant",w));l.append(k);d.append(l)}this.tg.append(d);f(".oj-listbox-result",d).on("mousemove",function(){var a=f(this);a.hasClass("oj-disabled")||(f(".oj-hover",d).removeClass("oj-hover"),a.addClass("oj-hover"),d.attr("aria-activedescendant",a.children()[0].id))});
var u=this;d.on("click",function(a){var b=f(a.target);b.hasClass("oj-disabled")||void 0!==b.attr("aria-disabled")||(u.JZ(a),u.hide())}).on("keydown",function(a){u.Rla(a)})},zea:function(a){var c=[],d=this.Uc();if(a){var e=this.options.timePicker.timeIncrement.split(":"),g=b.sb,f=this.Xl(),h=g.dateToLocalIso(a),k=f?this.Hl.widget.options.min:this.options.min,f=f?this.Hl.widget.options.max:this.options.max,k=k?g.isoToLocalDate(g._minMaxIsoString(k,h)):null,f=f?g.isoToLocalDate(g._minMaxIsoString(f,
h)):null;if(4===e.length){var h=parseInt(e[0].substring(0),10),l=parseInt(e[1],10),u=parseInt(e[2],10),e=parseInt(e[3],10),y=new Date(a),x="";do x=d.format(g.dateToLocalIso(y)),c.push({label:x,value:x,minMaxRange:this.jga(y,k,f)}),y.setHours(y.getHours()+h),y.setMinutes(y.getMinutes()+l),y.setSeconds(y.getSeconds()+u),y.setMilliseconds(y.getMilliseconds()+e);while(y.getDate()===a.getDate())}else throw Error("timeIncrement value should be in the format of hh:mm:ss:SS");}return c},Rla:function(a){if(this.hy()){var b=
f.ui.keyCode,c=!1;switch(a.keyCode){case b.TAB:this.hide();break;case b.ESCAPE:this.hide();this.element.focus();c=!0;break;case b.UP:this.EZ(a,"prev");c=!0;break;case b.DOWN:this.EZ(a,"next");c=!0;break;case b.ENTER:this.JZ(a),c=!0}if(c)return a.preventDefault(),a.stopPropagation(),!1}},EZ:function(a,b){var c=f(".oj-hover",this.tg),d=f("ul",this.tg),e=null;1===c.length?(e=c[b](),1===e.length&&c.removeClass("oj-hover")):e=f(d.children()[0]);e&&1===e.length&&(e.addClass("oj-hover"),d.attr("aria-activedescendant",
e.children()[0].id),this.OT(e))},JZ:function(a){var b=this.tg,c=f("[aria-selected]",b),d=f("ul",b),b=f(".oj-hover div",b);1===b.length&&(1===c.length&&(c.removeAttr("aria-selected"),c.parent().removeClass("oj-hover")),b.attr("aria-selected","true"),b.parent().addClass("oj-hover"),this.hide(),this.oi(b.attr("data-value")),this.hc(b.attr("data-value"),a),d.attr("aria-activedescendant",b[0].id),this.element.focus(),this.Xl()&&this.Hl.widget.hide())},WK:function(a){this.bo()&&this._superApply(arguments)},
show:function(){if(!this.options.disabled&&!this.options.readOnly){this.Xl()&&this.Hl.widget.hide();this.CB();var a=this.tg,c=this.bL;a.width(this.element.parent().width());a.css({position:"relative"});var d=b.qc.Gg({my:"start top",at:"start bottom",of:this.element,collision:"flipfit flipfit"},this.zj);c.ojPopup("open",this.FM,d);a.find("[aria-selected]").parent().addClass("oj-hover")}},hide:function(){this.hy()&&(this.bL.ojPopup("close"),this.element.focus())},refresh:function(){this.md&&this.md.find("."+
this.UG).attr("title",this.JJ());return this._superApply(arguments)||this},oi:function(a){this.bo()&&this._superApply(arguments);this.hy()&&this.CB()},hc:function(a,c,d){if(this.Xl()){this._super(a,null,d);try{var e=this.Uc().parse(a),f=b.sb,h=this.Hl.widget,k=h.A3(),l=k?f.isoToLocalDate(k):new Date,w=g(e?f.isoToLocalDate(e):new Date,new Date(l)),u=f.dateToLocalIso(w);l.getTime()!=w.getTime()&&h.rqa(u,c)}catch(y){}}else this._superApply(arguments)},Jv:function(){return this.bo()},bo:function(){return!this.Xl()||
this.mY()},_GetDefaultStyleClass:function(){return"oj-inputtime"},qs:function(){return this.options.value||""},Lv:function(){var a=this._superApply(arguments);null==this.options.min&&null==this.options.max||this.Xl()||(this.nM[b.ed.VALIDATOR_TYPE_DATETIMERANGE]=d(this.options,this.Uc()));return f.extend(this.nM,a)},Uc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputTime.prototype.options.converter},OT:function(a,b){var c=a.parent();b&&this.e1&&f(c).scrollTop(this.e1);
var d=f(c).scrollTop(),e=d+f(c).height(),g=a[0].offsetTop,h=g+f(a).height();g<d?f(c).scrollTop(g):h>e&&f(c).scrollTop(h-f(c).height())},Xl:function(){return null!==this.Hl},mY:function(){return this.Hl.inline},li:function(){this.hide()},xl:function(){this.hide()},getNodeBySubId:function(a){var b=null,c=a&&a.subId;if(c)switch(c){case "oj-listbox-drop":b=this.tg[0];break;case "oj-inputdatetime-time-icon":b=f(".oj-inputdatetime-time-icon",this.md)[0];break;case "oj-inputdatetime-time-input":b=this.element[0];
break;default:b=null}return b||this._superApply(arguments)},getSubIdByNode:function(a){var b=f(".oj-inputdatetime-time-icon",this.md),c=null;a===this.tg[0]?c="oj-listbox-drop":a===b[0]?c="oj-inputdatetime-time-icon":a===this.element[0]&&(c="oj-inputdatetime-time-input");return c||this._superApply(arguments)},widget:function(){return this.bo()?this._super():this.Hl.widget.widget()}});b.ya("oj.ojInputDateTime",f.oj.ojInputDate,{version:"1.0.0",widgetEventPrefix:"oj",_WIDGET_CLASS_NAMES:"oj-inputdatetime-date-time oj-component oj-inputdatetime",
_INPUT_HELPER_KEY:"inputHelpBoth",options:{converter:b.pa.lm(b.Uj.CONVERTER_TYPE_DATETIME).createConverter({day:"2-digit",month:"2-digit",year:"2-digit",hour:"2-digit",hour12:!0,minute:"2-digit"}),timePicker:{timeIncrement:"00:30:00:00"}},$z:function(){this._super();this.ju=this.element;this.QC=this.tD=this.sg=null},_ComponentCreate:function(){var a=this._super(),c=this.eX(this.Uc());if(null===c)throw Error("Please use ojInputDate if you do not have time portion");if(this.ce){var d=f("\x3cinput type\x3d'text'\x3e");
d.insertAfter(this.element);this.ju=d}for(var d=["title","placeholder","disabled","required","readOnly"],e={},g=0,h=d.length;g<h;g++)e[d[g]]=this.options[d[g]];this.sg=this.ju.ojInputTime(f.extend(e,{converter:c,displayOptions:{converterHint:"none",title:"none",messages:this.options.displayOptions.messages},value:b.sb.dateToLocalIso(this.KB()),timePicker:this.options.timePicker,datePickerComp:{widget:this,inline:this.ce}}));return a},_setOption:function(a,b,c){var d=this._superApply(arguments);"value"===
a&&(this.QC=b);this.sg&&(a in{disabled:!0,readOnly:!0}?this.sg.ojInputTime("option",a,b):"timePicker"===a?this.sg.ojInputTime("option","timePicker.timeIncrement",b.timeIncrement):"converter"===a&&(this.tD=null,this.sg.ojInputTime("option",a,this.eX(this.Uc()))));return d},_destroy:function(){var a=this._super();this.sg.ojInputTime("destroy");this.ce&&this.ju.remove();return a},eX:function(a){if(null!==this.tD)return this.tD;a=a.resolvedOptions();var c={},d="hour hour12 minute second millisecond timeFormat".split(" "),
e,g;e=0;for(g=d.length;e<g;e++)d[e]in a&&("timeFormat"===d[e]&&(c.formatType="time"),c[d[e]]=a[d[e]]);if(f.isEmptyObject(c))throw Error("Plase use ojInputDateTime's converter is lacking the time portion");return this.tD=a=b.pa.lm(b.Uj.CONVERTER_TYPE_DATETIME).createConverter(c)},rqa:function(a,b){this.oi(this.Uc().format(a));this.hc(a,b)},A3:function(){if(this.isValid())return this.options.value;if(this.QC)try{return this.Uc().parse(this.QC)}catch(a){return this.options.value}else return null},hc:function(a,
b,c){this._superApply(arguments);this.QC=a},MC:function(a){var b=f.ui.keyCode,c=!1;switch(a.keyCode){case b.UP:case b.DOWN:a.shiftKey&&(this.hc(this.hg(),a),this.sg.ojInputTime("show"),c=!0)}return c?(a.preventDefault(),a.stopPropagation(),!1):this._superApply(arguments)},show:function(){this.sg.ojInputTime("hide");return this._super()},showTimePicker:function(){this.hide();return this.sg.ojInputTime("show")},hideTimePicker:function(){return this.sg.ojInputTime("hide")},refresh:function(){var a=this._superApply(arguments)||
this;this.sg.ojInputTime("refresh");return a},getNodeBySubId:function(a){var b=a&&a.subId,c=null;b&&("oj-listbox-drop"===b||"oj-inputdatetime-time-icon"===b?c=this.sg.ojInputTime("getNodeBySubId",a):"oj-inputdatetime-date-input"===b&&(c=this.ce?this.ju[0]:this.element[0]));return c||this._superApply(arguments)},getSubIdByNode:function(a){var b=null;this.ce?a===this.ju[0]&&(b="oj-inputdatetime-date-input"):a===this.element[0]&&(b="oj-inputdatetime-date-input");return b||this.sg.ojInputTime("getSubIdByNode",
a)||this._superApply(arguments)},Uc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputDateTime.prototype.options.converter},li:function(){this._superApply(arguments);this.sg&&this.hideTimePicker()},xl:function(){this._superApply(arguments);this.sg&&this.hideTimePicker()},_GetMessagingLauncherElement:function(){return this.ce?this.ju:this._super()},_GetDefaultStyleClass:function(){return"oj-inputdatetime"},Wz:function(){return"oj-ojInputDate"}})});