/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/internal-deps/datagrid/DvtDataGrid","ojs/ojcomponentcore","ojs/ojdatasource-common","ojs/ojarraydatagriddatasource","ojs/ojflattenedtreedatagriddatasource","ojs/ojpagingdatagriddatasource","ojs/ojinputnumber","ojs/ojmenu","ojs/ojdialog","ojs/ojpagingcontrol"],function(b,f,a){b.Vh=function(a,c){this.Spa=a;this.sqa=c;this.Pa={};this.Pa.datagrid="oj-datagrid";this.Pa.cell="oj-datagrid-cell";this.Pa.cellcontent="oj-datagrid-cell-content";this.Pa.celltext="oj-datagrid-cell-text";
this.Pa.banded="oj-datagrid-banded";this.Pa.row="oj-datagrid-row";this.Pa.databody="oj-datagrid-databody";this.Pa.topcorner="oj-datagrid-top-corner";this.Pa.bottomcorner="oj-datagrid-bottom-corner";this.Pa.rowheaderspacer="oj-datagrid-row-header-spacer";this.Pa.colheaderspacer="oj-datagrid-column-header-spacer";this.Pa.status="oj-datagrid-status";this.Pa.emptytext="oj-datagrid-empty-text";this.Pa.header="oj-datagrid-header";this.Pa.groupingcontainer="oj-datagrid-header-grouping";this.Pa.headercell=
"oj-datagrid-header-cell";this.Pa.headercelltext="oj-datagrid-header-cell-text";this.Pa.headercellcontent="oj-datagrid-header-cell-content";this.Pa.rowheader="oj-datagrid-row-header";this.Pa.colheader="oj-datagrid-column-header";this.Pa.colheadercell="oj-datagrid-column-header-cell";this.Pa.rowheadercell="oj-datagrid-row-header-cell";this.Pa["scroller-mobile"]="oj-datagrid-scroller-touch";this.Pa.scroller="oj-datagrid-scroller";this.Pa.scrollers="oj-datagrid-scrollers";this.Pa.focus="oj-focus";this.Pa.hover=
"oj-hover";this.Pa.active="oj-active";this.Pa.selected="oj-selected";this.Pa.disabled="oj-disabled";this.Pa.enabled="oj-enabled";this.Pa["default"]="oj-default";this.Pa.sortcontainer="oj-datagrid-sort-icon-container";this.Pa.sortascending="oj-datagrid-sort-ascending-icon";this.Pa.sortdescending="oj-datagrid-sort-descending-icon";this.Pa.icon="oj-component-icon";this.Pa.clickableicon="oj-clickable-icon-nocontext";this.Pa.info="oj-helper-hidden-accessible";this.Pa.rowexpander="oj-rowexpander";this.Pa.cut=
"oj-datagrid-cut";this.Pa.selectaffordancetop="oj-datagrid-touch-selection-affordance-top";this.Pa.selectaffordancebottom="oj-datagrid-touch-selection-affordance-bottom";this.Pa.toucharea="oj-datagrid-touch-area";this.Pa.draggable="oj-draggable";this.Pa.drag="oj-drag";this.Pa.drop="oj-drop";this.Pa.activedrop="oj-active-drop";this.Pa.validdrop="oj-valid-drop";this.Pa.invaliddrop="oj-invalid-drop";this.lh={};this.lh.sortCol="oj-datagrid-sortCol";this.lh.sortColAsc="oj-datagrid-sortColAsc";this.lh.sortColDsc=
"oj-datagrid-sortColDsc";this.lh.sortRow="oj-datagrid-sortRow";this.lh.sortRowAsc="oj-datagrid-sortRowAsc";this.lh.sortRowDsc="oj-datagrid-sortRowDsc";this.lh.resize="oj-datagrid-resize";this.lh.resizeWidth="oj-datagrid-resizeWidth";this.lh.resizeHeight="oj-datagrid-resizeHeight";this.lh.cut="oj-datagrid-cut";this.lh.paste="oj-datagrid-paste";this.lh.discontiguousSelection="oj-datagrid-discontiguousSelection";this.attributes={};this.attributes.key="data-oj-key";this.attributes.context="data-oj-context";
this.attributes.resizable="data-oj-resizable";this.attributes.sortable="data-oj-sortable";this.attributes.sortDir="data-oj-sortdir";this.attributes.expander="data-oj-expander";this.attributes.expanderIndex="data-oj-expander-index";this.attributes.container=b.Components.tn;this.attributes.extent="data-oj-extent";this.attributes.start="data-oj-start";this.attributes.depth="data-oj-depth";this.attributes.level="data-oj-level";this.attributes.tabMod="data-oj-tabmod"};o_("DataGridResources",b.Vh,b);b.Vh.prototype.Y3=
function(){return"rtl"===this.Spa?!0:!1};b.b.g("DataGridResources.prototype.isRTLMode",{Y3:b.Vh.prototype.Y3});b.Vh.prototype.z3=function(a,b){return this.sqa(a,b)};b.b.g("DataGridResources.prototype.getTranslatedText",{z3:b.Vh.prototype.z3});b.Vh.prototype.PN=function(a){return null!=a?this.Pa[a]:null};b.b.g("DataGridResources.prototype.getMappedStyle",{PN:b.Vh.prototype.PN});b.Vh.prototype.nE=function(a){return null!=a?this.lh[a]:null};b.b.g("DataGridResources.prototype.getMappedCommand",{nE:b.Vh.prototype.nE});
b.Vh.prototype.ON=function(a){return null!=a?this.attributes[a]:null};b.b.g("DataGridResources.prototype.getMappedAttribute",{ON:b.Vh.prototype.ON});b.ya("oj.ojDataGrid",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{bandingInterval:{row:0,column:0},data:null,gridlines:{horizontal:"visible",vertical:"visible"},scrollPosition:null,selectionMode:null,dnd:{reorder:{row:"disable"}},scrollPolicy:"auto",selection:[],currentCell:null,header:{row:{className:null,renderer:null,resizable:{width:"disable",
height:"disable"},sortable:"auto",style:null},column:{className:null,renderer:null,resizable:{width:"disable",height:"disable"},sortable:"auto",style:null}},cell:{className:null,renderer:null,style:null},resize:null,sort:null,optionChange:null,ready:null,scroll:null,beforeCurrentCell:null},_ComponentCreate:function(){this._super();this.root=this.element[0];this.rh=this.root.getAttribute("id");this.grid=new a;this.grid.setVisibility(a.VISIBILITY_STATE_RENDER);f(this.root).addClass("oj-datagrid oj-component");
this.WO={data:"all",header:["className","renderer","style","template"]}},mf:function(){this.Nk(this.root);f(this.root).empty();this._super();this.Dr=new b.Vh(this.ec(),this.dC.bind(this));this.a0();this.bu();null!=this.mc&&(this.BA(),this.grid.SetDataSource(this.mc));this.grid.SetOptions(this.options);this.grid.SetResources(this.Dr);this.grid.SetCreateContextCallback(this.Uha.bind(this));this.grid.SetRemoveCallback(this.tL.bind(this));this.Sx();this.Dx();null!=this.mc&&this.yj(this.root)},Sx:function(){var a=
this;this.grid.addListener("resize",function(b){a._trigger("resize",b.event,b.ui)});this.grid.addListener("select",function(b){a.option("selection",b.ui.selection,{_context:{originalEvent:b.event,Va:!0},changed:!0})});this.grid.addListener("currentCell",function(b){a.option("currentCell",b.ui,{_context:{originalEvent:b.event,Va:!0},changed:!0})});this.grid.addListener("beforeCurrentCell",function(b){return a._trigger("beforeCurrentCell",b.event,b.ui)});this.grid.addListener("sort",function(b){a._trigger("sort",
b.event,b.ui)});this.grid.addListener("keydown",function(b){a._trigger("keydown",b.event,b.ui)});this.grid.addListener("ready",function(){a._trigger("ready",null,{})});this.grid.addListener("scroll",function(b){a._trigger("scroll",b.event,b.ui)})},refresh:function(){this._super();this.Nk(this.root);f(this.root).empty();!0===this.uma&&(this.options.contextMenu=null);this.a0();null!=this.mc&&(this.mc instanceof b.$a&&(this.mc.Oe(),this.mc.Init()),this.BA(),this.grid.SetDataSource(this.mc));this.grid.SetOptions(this.options);
this.grid.SetResources(this.Dr);this.grid.getVisibility()!=a.VISIBILITY_STATE_RENDER&&this.grid.setVisibility(a.VISIBILITY_STATE_REFRESH);this.Dx();null!=this.mc&&this.yj(this.root)},_destroy:function(){null!=this.mc&&this.mc.Oe&&this.mc.Oe();this.grid.destroy();this.Nk(this.root);f(this.root).empty()},_setOptions:function(a,b){var e;this.mc?(e=this.rla(a),this._super(a,b),e?this.refresh():this.grid.UpdateOptions(a)):(this._super(a,b),null!=a.data&&this.refresh())},yl:function(){this._super();this.Dx()},
xl:function(){this._super();this.grid.getVisibility()===a.VISIBILITY_STATE_VISIBLE&&this.grid.setVisibility(a.VISIBILITY_STATE_HIDDEN)},sn:function(){this._super();this.Dx()},li:function(){this._super();this.grid.getVisibility()===a.VISIBILITY_STATE_VISIBLE&&this.grid.setVisibility(a.VISIBILITY_STATE_HIDDEN)},rla:function(a){var c,e,g,f,k,l;g=!1;for(e in a)if(e in this.WO)if("data"===e){g=!0;break}else if("header"==e)for(f in a.header){if("column"==f||"row"==f||"cell"==f)for(k in a.header[f]){for(c=
0;c<this.WO.header.length;c++)if(k==this.WO.header[c])for(l in this.options.header[f])if(l==k&&a.header[f][k]!=this.options.header[f][k]){g=!0;break}if(g)break}if(g)break}else for(l in this.options)if(l==e&&!b.b.mh(a[e],this.options[l])){g=!0;break}return g},yC:function(a,b){return this.options.header[a]&&this.options.header[a].resizable?"disable"!==this.options.header[a].resizable[b]:!1},FY:function(a){return this.options.header[a]?"disable"!==this.options.header[a].sortable:!1},BA:function(){var a,
c,e=null,g=null,h=null,k=null,l,m;a=this;if(null==this.options.contextMenu){if(null!=this.mc){c=f("\x3cul\x3e");c.css("display","none").attr("id",this.rh+"contextmenu");f(this.root).append(c);if(this.yC("column","width")||this.yC("column","height")||this.yC("row","width")||this.yC("row","height"))e=this.qi("resize");l=this.mc.getCapability("sort");!this.FY("column")||"column"!==l&&"full"!==l||(g=this.qi("sortCol"));!this.FY("row")||"row"!==l&&"full"!==l||(g=null!=g?g.add(this.qi("sortRow")):this.qi("sortRow"));
if("enable"===this.options.dnd.reorder.row)switch(this.mc.getCapability("move")){case "none":break;default:k=this.jg("cut").add(this.jg("paste"))}this.tj()&&b.v.Sd()&&(this.jB=!1,h=this.jg("discontiguousSelection"));if(null!=e||null!=g||null!=k||null!=h)c.append(e).append(g).append(k).append(h),c.ojMenu(),this.uma=!0,this._setOption("contextMenu","#"+c.attr("id")),c.on("ojselect",this.rj.bind(this))}}else null==this.OK&&(this.OK=[]),c=f(this.options.contextMenu),e=c.find("[data-oj-command]"),m=[],
e.each(function(){var b;b=f(this).children("a");if(0===b.length||-1!=a.OK.indexOf(b.get(0)))b=f(this).attr("data-oj-command").split("-"),b=a.qi(b[b.length-1]),f(this).replaceWith(b),m.push(b.children("a").get(0))}),this.OK=m,c.data("oj-ojMenu")&&c.ojMenu("refresh"),c.on("ojselect",this.rj.bind(this))},qi:function(a){if("resize"===a)return this.jg("resize").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.jg("resizeWidth")).append(this.jg("resizeHeight")));if("sortCol"===a)return this.jg("sortCol").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.jg("sortColAsc")).append(this.jg("sortColDsc")));
if("sortRow"===a)return this.jg("sortRow").append(f("\x3cul\x3e\x3c/ul\x3e").append(this.jg("sortRowAsc")).append(this.jg("sortRowDsc")));if(-1!=Object.keys(this.Dr.lh).indexOf(a))return f(this.jg(a))},jg:function(a){var b=f("\x3cli\x3e\x3c/li\x3e");b.attr("data-oj-command",this.Ql(a));b.append(this.nH(a));return b},nH:function(a){var b="label"+a.charAt(0).toUpperCase()+a.slice(1);"discontiguousSelection"===a&&(b="labelEnableNonContiguous");return f('\x3ca href\x3d"#"\x3e\x3c/a\x3e').text(this.dC(b))},
bW:function(){return f(this.options.contextMenu).get(0)},dC:function(a,b){return this.A(a,b)},Ofa:function(){var a=f("#"+this.rh+"spinner").ojInputNumber("option","value");f("#"+this.rh+"dialog").ojDialog("close");this.grid.handleContextMenuReturn(this.yu,this.Oj,a);this.yu.target.focus()},Y$:function(a,b){var e,g,h,k,l;e=f("#"+this.rh+"dialog");h=f("#"+this.rh+"spinner");0===e.length||0===h.length?(e=f("\x3cdiv\x3e"),e.attr("id",this.rh+"dialog"),e.attr("title",a),g=f('\x3cdiv class\x3d"oj-dialog-body"\x3e\x3c/div\x3e'),
k=f('\x3cdiv class\x3d"oj-dialog-footer"\x3e\x3c/div\x3e'),e.append(g).append(k),h=f('\x3cinput id\x3d"'+this.rh+'spinner"/\x3e'),l=f('\x3cbutton id\x3d"'+this.rh+'dialogsubmit"/\x3e'),g.append(h),k.append(l),f(this.root).append(e),l.ojButton({Q:"ojButton",label:this.dC("labelResizeDialogSubmit")}),l.on("click",this.Ofa.bind(this)),h.ojInputNumber({Q:"ojInputNumber",max:1E3,min:20,step:1,value:b}),e.ojDialog({initialVisibility:"show",position:{my:"center center",at:"center center",collision:"none",
of:f(this.root)}})):(h.ojInputNumber("option","value",b),f("#"+this.rh+"dialog").ojDialog("open"))},rj:function(a,b){var e;this.Oj=b.item.attr("data-oj-command");this.Oj===this.Ql("sortColAsc")||this.Oj===this.Ql("sortColDsc")||this.Oj===this.Ql("cut")||this.Oj===this.Ql("paste")?this.grid.handleContextMenuReturn(this.yu,this.Oj,null):this.Oj===this.Ql("resizeWidth")||this.Oj===this.Ql("resizeHeight")?(e=f(this.yu.target).closest("."+this.Nd("cell")),0==e.length&&(e=f(this.yu.target).closest("."+
this.Nd("headercell"))),0<e.length&&(e=this.Oj===this.Ql("resizeWidth")?e.outerWidth():e.outerHeight(),this.Y$(b.item.text(),e))):this.Oj===this.Ql("discontiguousSelection")&&(this.jB=!this.jB,this.grid.handleContextMenuReturn(this.yu,this.Oj,this.jB),e=this.jB?"labelDisableNonContiguous":"labelEnableNonContiguous",b.item.children().first().text(this.dC(e)))},qf:function(a,b,e){this.grid.handleContextMenuGesture(b,e,this.Saa.bind(this))},Saa:function(a,b,e){var g;null!=a&&(this.yu=b.originalEvent,
g=a.launcher,a=a.capabilities,this.Jha(a),g="keyboard"===e?{position:{of:g},launcher:f(g)}:{launcher:f(g)},this.sf(b,e,g))},V9:function(a){var b;b=f(this.bW());b.find("[data-oj-command\x3d"+a+"]").hasClass("oj-disabled")||b.find("[data-oj-command\x3d"+a+"]").addClass("oj-disabled")},Bja:function(a){f(this.bW()).find("[data-oj-command\x3d"+a+"]").removeClass("oj-disabled")},Jha:function(a){var b,e;for(b in a)a.hasOwnProperty(b)&&(e=this.Dr.nE(b),"disable"===a[b]?this.V9(e):this.Bja(e))},BV:function(a){var b;
b=a.parent();a=a.index();return{rowIndex:b.index(),columnIndex:a}},hra:function(a){var b;b=this.qea().children().eq(0).children().eq(a.rowIndex+1);a=this.lda().children().eq(0).children().eq(a.columnIndex);return{rowHeader:b,columnHeader:a}},jW:function(){return f(this.root)},lda:function(){return f("#"+this.rh+"\\:columnHeader")},qea:function(){return f("#"+this.rh+"\\:rowHeader")},rda:function(){return f("#"+this.rh+"\\:databody ."+this.Nd("row"))},a0:function(){this.mc=null!=this.options.data?
this.options.data:null},bu:function(){var a=this.options.selection;null!=a&&this.grid.SetSelection(a)},Uha:function(a){a.component=b.Components.Of(this.element,"ojDataGrid")},cD:function(a){this.grid.SetAccessibleContext(a)},Nk:function(a){a&&this.Ge&&b.v.Oi(a,this.Ge)},yj:function(a){a&&(null==this.Ge&&(this.Ge=this.Ve.bind(this)),b.v.Nh(a,this.Ge))},Ve:function(a,b){0<a&&0<b&&(this.Dx(),this.grid.HandleResize(a,b))},getNodeBySubId:function(a){var b,e,g,h;if(null==a)return this.element?this.element[0]:
null;b=a.subId;if("oj-datagrid-cell"===b)b=a.rowIndex-this.grid.getStartRow(),a=a.columnIndex-this.grid.getStartColumn(),g=this.rda().eq(b).children().eq(a);else if("oj-datagrid-sort-icon"===b||"oj-datagrid-sort-ascending"===b||"oj-datagrid-sort-descending"===b||"oj-datagrid-header"===b){h=a.axis;g=a.index;a=null==a.level?0:a.level;"column"===h?e=this.lW(g,a,f("#"+this.rh+"\\:columnHeader"),this.grid.getStartColumnHeader()):"row"===h&&(e=this.lW(g,a,f("#"+this.rh+"\\:rowHeader"),this.grid.getStartRowHeader()));
if(null==e)return null;if("oj-datagrid-sort-icon"===b)return e.children("."+this.Nd("sortcontainer")).children().get(0);g="oj-datagrid-sort-ascending"===b?e.find("."+this.Nd("sortascending")):"oj-datagrid-sort-descending"===b?e.find("."+this.Nd("sortdescending")):e}return null!=g&&0<g.length?g[0]:null},getSubIdByNode:function(a){var b,e;b=f(a).closest("."+this.Nd("cell"));if(0<b.length)return a=this.BV(b),{subId:"oj-datagrid-cell",rowIndex:a.rowIndex+this.grid.getStartRow(),columnIndex:a.columnIndex+
this.grid.getStartColumn()};e=f(a).closest("."+this.Nd("headercell"));return 0<e.length?(b=e[0][this.pj("context")],a=f(a).hasClass(this.Nd("sortascending"))?"oj-datagrid-sort-ascending":f(a).hasClass(this.Nd("sortdescending"))?"oj-datagrid-sort-descending":"oj-datagrid-header",{subId:a,axis:b.axis,index:this.mW(e),level:b.level}):null},getContextByNode:function(a){var b;b=f(a).closest("."+this.Nd("cell"));if(0<b.length)return a=b[0][this.pj("context")],b=this.BV(b),{subId:"oj-datagrid-cell",component:a.component,
data:a.data,datasource:a.datasource,indexes:{row:b.rowIndex+this.grid.getStartRow(),column:b.columnIndex+this.grid.getStartColumn()},keys:{row:a.keys.row,column:a.keys.column}};b=f(a).closest("."+this.Nd("headercell"));return 0<b.length?(a=b[0][this.pj("context")],{subId:"oj-datagrid-header",axis:a.axis,component:a.component,data:a.data,datasource:a.datasource,depth:a.depth,extent:a.extent,index:this.mW(b),key:a.key,level:a.level}):null},Nd:function(a){return this.Dr.PN(a)},pj:function(a){return this.Dr.ON(a)},
Ql:function(a){return this.Dr.nE(a)},Vga:function(){return null!=this.root.offsetParent?!0:!1},Dx:function(){var b=this.grid.getVisibility();this.Vga()?(b===a.VISIBILITY_STATE_RENDER?this.grid.render(this.root):b===a.VISIBILITY_STATE_REFRESH&&this.grid.refresh(this.root),this.grid.setVisibility(a.VISIBILITY_STATE_VISIBLE)):b===a.VISIBILITY_STATE_VISIBLE&&this.grid.setVisibility(a.VISIBILITY_STATE_HIDDEN)},lW:function(a,b,e,g){if(0>b)return null;if(e.children().first().children().last().hasClass(this.Nd("headercell")))return e.children().first().children("."+
this.Nd("headercell")).eq(a-g);e=this.kW(a,b,0,e.children().first().children());if(null==e)return null;if(b<=parseInt(e.attr(this.pj("level")),10)+parseInt(e.children().eq(0).attr(this.pj("depth")),10)-1)return e.children().eq(0);g=parseInt(e.attr(this.pj("start")),10);a=a-g+1;return e.children().eq(a)},kW:function(a,b,e,g){var f,k,l,m;if(null==g.eq(1)||g.eq(1).hasClass(this.Nd("headercell")))return b===e?g.eq(0).parent():null;f=g.parent().parent();for(l=f.hasClass(this.Nd("colheader"))||f.hasClass(this.Nd("rowheader"))?
0:1;l<g.length;l++)if(f=parseInt(g.eq(l).attr(this.pj("start")),10),k=parseInt(g.eq(l).attr(this.pj("extent")),10),m=parseInt(g.eq(l).children().eq(0).attr(this.pj("depth")),10),a>=f&&a<f+k)return b<e+m?g.eq(l):this.kW(a,b,e+m,g.eq(l).children());return null},mW:function(a){var b;if(a.parent().hasClass(this.Nd("groupingcontainer"))){b=parseInt(a.parent().attr(this.pj("start")),10);if(a.get(0)===a.parent().children(":first").get(0))return b;b--}else b=a.hasClass(this.Nd("rowheadercell"))?this.grid.getStartRowHeader():
this.grid.getStartColumnHeader();return b+=a.index()},mra:function(a){var b;return a.parent().hasClass(this.Nd("groupingcontainer"))?(b=parseInt(a.parent().attr(this.pj("level")),10),a.get(0)===a.parent().children(":first").get(0)?b:b+1):0},tj:function(){return null==this.options.selectionMode||"multiple"!==this.options.selectionMode.row&&"multiple"!==this.options.selectionMode.cell?!1:!0},tL:function(a){f(a).remove()},scrollTo:function(a){this.grid.scroll(a)}})});