/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore","jqueryui-amd/draggable","jqueryui-amd/mouse"],function(b,f){(function(){b.ya("oj.ojResizable",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0,maxHeight:null,maxWidth:null,minHeight:10,minWidth:10,alsoResize:!1,animate:!1,animateDuration:"slow",animateEasing:"swing",containment:!1,ghost:!1,grid:!1,handles:"e,s,se",helper:!1,resize:null,start:null,
stop:null},SK:function(a){return parseInt(a,10)||0},Fe:function(a){return!isNaN(parseInt(a,10))},JX:function(a,b){if("hidden"===f(a).css("overflow"))return!1;var c=b&&"left"===b?"scrollLeft":"scrollTop",e=!1;if(0<a[c])return!0;a[c]=1;e=0<a[c];a[c]=0;return e},_ComponentCreate:function(){this._super();var a,b,c,e,g,h=this;a=this.options;b=this.element.mouse.bind(this.element);b();this.Em=b("instance");this.Em._mouseCapture=function(a){return h.Wha(a)};this.Em._mouseStart=function(a){return h.Zha(a)};
this.Em._mouseDrag=function(a){return h.Xha(a)};this.Em._mouseStop=function(a){return h.sx(a)};this.element.addClass("oj-resizable");f.extend(this,{JE:this.element,SC:[],Ak:null});this.handles=a.handles||(f(".oj-resizable-handle",this.element).length?{fsa:".oj-resizable-n",Tra:".oj-resizable-e",osa:".oj-resizable-s",Tf:".oj-resizable-w",qsa:".oj-resizable-se",ssa:".oj-resizable-sw",gsa:".oj-resizable-ne",isa:".oj-resizable-nw"}:"e,s,se");if(this.handles.constructor===String)for("all"===this.handles&&
(this.handles="n,e,s,w,se,sw,ne,nw"),a=this.handles.split(","),this.handles={},b=0;b<a.length;b++)c=f.trim(a[b]),g="oj-resizable-"+c,e=f("\x3cdiv class\x3d'oj-resizable-handle "+g+"'\x3e\x3c/div\x3e"),this.handles[c]=".oj-resizable-"+c,this.element.append(e);this.Xja=function(){for(var a in this.handles)this.handles[a].constructor===String&&(this.handles[a]=this.element.children(this.handles[a]).first().show())};this.Xja();this.Yfa=f(".oj-resizable-handle",this.element);this.Yfa.mouseover(function(){h.a5||
(this.className&&(e=this.className.match(/oj-resizable-(se|sw|ne|nw|n|e|s|w)/i)),h.axis=e&&e[1]?e[1]:"se")});this.Em._mouseInit()},_destroy:function(){this.Em&&this.Em._mouseDestroy();try{this.Em.destroy(),this.Em=null}catch(a){}f(this.JE).removeClass("oj-resizable oj-resizable-disabled oj-resizable-resizing").removeData("resizable").removeData("oj-resizable").unbind(".resizable").find(".oj-resizable-handle").remove();return this},Wha:function(a){var b,c,e=!1;for(b in this.handles)if(c=f(this.handles[b])[0],
c===a.target||f.contains(c,a.target))e=!0;return!this.options.disabled&&e},Zha:function(a){var b,c,e;e=this.options;b=this.element.position();var g=this.element;this.a5=!0;/absolute/.test(g.css("position"))?g.css({position:"absolute",top:g.css("top"),left:g.css("left")}):g.is(".oj-draggable")&&g.css({position:"absolute",top:b.top,left:b.left});this.Yja();b=this.SK(this.helper.css("left"));c=this.SK(this.helper.css("top"));e.containment&&(b+=f(e.containment).scrollLeft()||0,c+=f(e.containment).scrollTop()||
0);this.offset=this.helper.offset();this.position={left:b,top:c};this.size={width:g.width(),height:g.height()};this.Rj={width:g.width(),height:g.height()};this.$o={left:b,top:c};this.UE={width:g.outerWidth()-g.width(),height:g.outerHeight()-g.height()};this.vpa={left:a.pageX,top:a.pageY};this.Pk=this.Rj.width/this.Rj.height||1;e=f(".oj-resizable-"+this.axis).css("cursor");f("body").css("cursor","auto"===e?this.axis+"-resize":e);g.addClass("oj-resizable-resizing");this.lL("start",a);this.u$(a);this.Qaa(a);
return!0},Xha:function(a){var b,c=this.helper,e={},g=this.vpa;b=a.pageX-g.left||0;var g=a.pageY-g.top||0,h=this.Dh[this.axis];this.Uu={top:this.position.top,left:this.position.left};this.Vu={width:this.size.width,height:this.size.height};if(!h)return!1;b=h.apply(this,[a,b,g]);this.sma(a.shiftKey);a.shiftKey&&(b=this.rma(b,a));b=this.kka(b,a);this.kma(b);this.lL("resize",a);this.t$(a,this.ui());this.Paa(a,this.ui());this.position.top!==this.Uu.top&&(e.top=this.position.top+"px");this.position.left!==
this.Uu.left&&(e.left=this.position.left+"px");this.size.width!==this.Vu.width&&(e.width=this.size.width+"px");this.size.height!==this.Vu.height&&(e.height=this.size.height+"px");c.css(e);!this.Ak&&this.SC.length&&this.Xia();f.isEmptyObject(e)||this._trigger("resize",a,this.ui());return!1},sx:function(a){this.a5=!1;f("body").css("cursor","auto");this.element.removeClass("oj-resizable-resizing");this.lL("stop",a);this.v$(a);this.Raa(a);return!1},sma:function(a){var b,c,e,f;f=this.options;f={minWidth:this.Fe(f.minWidth)?
f.minWidth:0,maxWidth:this.Fe(f.maxWidth)?f.maxWidth:Infinity,minHeight:this.Fe(f.minHeight)?f.minHeight:0,maxHeight:this.Fe(f.maxHeight)?f.maxHeight:Infinity};a&&(a=f.minHeight*this.Pk,c=f.minWidth/this.Pk,b=f.maxHeight*this.Pk,e=f.maxWidth/this.Pk,a>f.minWidth&&(f.minWidth=a),c>f.minHeight&&(f.minHeight=c),b<f.maxWidth&&(f.maxWidth=b),e<f.maxHeight&&(f.maxHeight=e));this.vma=f},kma:function(a){this.offset=this.helper.offset();this.Fe(a.left)&&(this.position.left=a.left);this.Fe(a.top)&&(this.position.top=
a.top);this.Fe(a.height)&&(this.size.height=a.height);this.Fe(a.width)&&(this.size.width=a.width)},rma:function(a){var b=this.position,c=this.size,e=this.axis;this.Fe(a.height)?a.width=a.height*this.Pk:this.Fe(a.width)&&(a.height=a.width/this.Pk);"sw"===e&&(a.left=b.left+(c.width-a.width),a.top=null);"nw"===e&&(a.top=b.top+(c.height-a.height),a.left=b.left+(c.width-a.width));return a},kka:function(a){var b=this.vma,c=this.axis,e=this.Fe(a.width)&&b.maxWidth&&b.maxWidth<a.width,f=this.Fe(a.height)&&
b.maxHeight&&b.maxHeight<a.height,h=this.Fe(a.width)&&b.minWidth&&b.minWidth>a.width,k=this.Fe(a.height)&&b.minHeight&&b.minHeight>a.height,l=this.$o.left+this.Rj.width,m=this.position.top+this.size.height,n=/sw|nw|w/.test(c),c=/nw|ne|n/.test(c);h&&(a.width=b.minWidth);k&&(a.height=b.minHeight);e&&(a.width=b.maxWidth);f&&(a.height=b.maxHeight);h&&n&&(a.left=l-b.minWidth);e&&n&&(a.left=l-b.maxWidth);k&&c&&(a.top=m-b.minHeight);f&&c&&(a.top=m-b.maxHeight);a.width||a.height||a.left||!a.top?a.width||
a.height||a.top||!a.left||(a.left=null):a.top=null;return a},Xia:function(){if(this.SC.length){var a,b,c,e,f,h=this.helper||this.element;for(a=0;a<this.SC.length;a++){f=this.SC[a];if(!this.uu)for(this.uu=[],c=[f.css("borderTopWidth"),f.css("borderRightWidth"),f.css("borderBottomWidth"),f.css("borderLeftWidth")],e=[f.css("paddingTop"),f.css("paddingRight"),f.css("paddingBottom"),f.css("paddingLeft")],b=0;b<c.length;b++)this.uu[b]=(parseInt(c[b],10)||0)+(parseInt(e[b],10)||0);f.css({height:h.height()-
this.uu[0]-this.uu[2]||0,width:h.width()-this.uu[1]-this.uu[3]||0})}}},Yja:function(){this.element.offset();this.helper=this.element},Dh:{e:function(a,b){return{width:this.Rj.width+b}},w:function(a,b){return{left:this.$o.left+b,width:this.Rj.width-b}},n:function(a,b,c){return{top:this.$o.top+c,height:this.Rj.height-c}},s:function(a,b,c){return{height:this.Rj.height+c}},se:function(a,b,c){return f.extend(this.Dh.s.apply(this,arguments),this.Dh.e.apply(this,[a,b,c]))},sw:function(a,b,c){return f.extend(this.Dh.s.apply(this,
arguments),this.Dh.w.apply(this,[a,b,c]))},ne:function(a,b,c){return f.extend(this.Dh.n.apply(this,arguments),this.Dh.e.apply(this,[a,b,c]))},nw:function(a,b,c){return f.extend(this.Dh.n.apply(this,arguments),this.Dh.w.apply(this,[a,b,c]))}},lL:function(a,b){"resize"!==a&&this._trigger(a,b,this.ui())},u$:function(){function a(a){f(a).each(function(){var a=f(this);a.data("oj-resizable-alsoresize",{width:parseInt(a.width(),10),height:parseInt(a.height(),10),left:parseInt(a.css("left"),10),top:parseInt(a.css("top"),
10)})})}var b=this.options;"object"!==typeof b.alsoResize||b.alsoResize.parentNode?a(b.alsoResize):b.alsoResize.length?(b.alsoResize=b.alsoResize[0],a(b.alsoResize)):f.each(b.alsoResize,function(b){a(b)})},t$:function(a,b){function c(a,c){f(a).each(function(){var a=f(this),e=f(this).data("oj-resizable-alsoresize"),g={};f.each(c&&c.length?c:a.parents(b.JE[0]).length?["width","height"]:["width","height","top","left"],function(a,b){var c=(e[b]||0)+(k[b]||0);c&&0<=c&&(g[b]=c||null)});a.css(g)})}var e=
this.options,g=this.Rj,h=this.$o,k={height:this.size.height-g.height||0,width:this.size.width-g.width||0,top:this.position.top-h.top||0,left:this.position.left-h.left||0};"object"!==typeof e.alsoResize||e.alsoResize.nodeType?c(e.alsoResize,null):f.each(e.alsoResize,function(a,b){c(a,b)})},v$:function(){f(this).removeData("oj-resizable-alsoresize")},Qaa:function(){var a,b,c,e,g,h=this,k=h.element;c=h.options.containment;if(k=c instanceof f?c.get(0):/parent/.test(c)?k.parent().get(0):c)h.WD=f(k),/document/.test(c)||
c===document?(h.XD={left:0,top:0},h.b2={left:0,top:0},h.ap={element:f(document),left:0,top:0,width:f(document).width(),height:f(document).height()||document.body.parentNode.scrollHeight}):(a=f(k),b=[],f(["Top","Right","Left","Bottom"]).each(function(c,e){b[c]=h.SK(a.css("padding"+e))}),h.XD=a.offset(),h.b2=a.position(),h.c2={height:a.innerHeight()-b[3],width:a.innerWidth()-b[1]},c=h.XD,e=h.c2.height,g=h.c2.width,g=h.JX(k,"left")?k.scrollWidth:g,e=h.JX(k)?k.scrollHeight:e,h.ap={element:k,left:c.left,
top:c.top,width:g,height:e})},Paa:function(a,b){var c,e,f,h;c=this.options;e=this.XD;h=this.position;var k=a.shiftKey;f={top:0,left:0};var l=this.WD,m=!0;l[0]!==document&&/static/.test(l.css("position"))&&(f=e);h.left<(this.Ak?e.left:0)&&(this.size.width+=this.Ak?this.position.left-e.left:this.position.left-f.left,k&&(this.size.height=this.size.width/this.Pk,m=!1),this.position.left=c.helper?e.left:0);h.top<(this.Ak?e.top:0)&&(this.size.height+=this.Ak?this.position.top-e.top:this.position.top,k&&
(this.size.width=this.size.height*this.Pk,m=!1),this.position.top=this.Ak?e.top:0);this.offset.left=this.ap.left+this.position.left;this.offset.top=this.ap.top+this.position.top;c=Math.abs((this.Ak?this.offset.left-f.left:this.offset.left-e.left)+this.UE.width);e=Math.abs((this.Ak?this.offset.top-f.top:this.offset.top-e.top)+this.UE.height);f=this.WD.get(0)===this.element.parent().get(0);h=/relative|absolute/.test(this.WD.css("position"));f&&h&&(c-=Math.abs(this.ap.left));c+this.size.width>=this.ap.width&&
(this.size.width=this.ap.width-c,k&&(this.size.height=this.size.width/this.Pk,m=!1));e+this.size.height>=this.ap.height&&(this.size.height=this.ap.height-e,k&&(this.size.width=this.size.height*this.Pk,m=!1));m||(this.position.left=b.Uu.left,this.position.top=b.Uu.top,this.size.width=b.Vu.width,this.size.height=b.Vu.height)},Raa:function(){var a=this.options,b=this.XD,c=this.b2,e=this.WD,g=f(this.helper),h=g.offset(),k=g.outerWidth()-this.UE.width,g=g.outerHeight()-this.UE.height;this.Ak&&!a.animate&&
/relative/.test(e.css("position"))&&f(this).css({left:h.left-c.left-b.left,width:k,height:g});this.Ak&&!a.animate&&/static/.test(e.css("position"))&&f(this).css({left:h.left-c.left-b.left,width:k,height:g})},ui:function(){return{JE:this.JE,element:this.element,helper:this.helper,position:this.position,size:this.size,Rj:this.Rj,$o:this.$o,Vu:this.Vu,Uu:this.Uu}}})})();(function(){b.ya("oj.ojDialog",f.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancelBehavior:"icon",dragAffordance:"title-bar",
initialVisibility:"hide",modality:"modal",position:{my:"center",at:"center",of:window,collision:"fit",vsa:function(a){var b=f(this).css(a).offset().top;0>b&&f(this).css("top",a.top-b)}},resizeBehavior:"resizable",role:"dialog",title:null,beforeClose:null,beforeOpen:null,close:null,focus:null,open:null,resize:null,resizeStart:null,resizeStop:null},_ComponentCreate:function(){this._super();this.upa={display:this.element[0].style.display,width:this.element[0].style.width,height:this.element[0].style.height};
this.$o={parent:this.element.parent(),index:this.element.parent().children().index(this.element)};this.OO=this.element.attr("title");this.options.title=this.options.title||this.OO;this.Hba();this.element.show().removeAttr("title").addClass("oj-dialog-content oj-dialog-default-content").appendTo(this.Qb);this.vz=!1;if(this.element.find(".oj-dialog").length){var a=this;this.element.find(".oj-dialog-header").each(function(b,c){var e=f(c);if(!e.closest(".oj-dialog-body").length)return a.Ao=e,a.vz=!0,
!1})}else this.Ao=this.element.find(".oj-dialog-header"),this.Ao.length&&(this.vz=!0);this.vz?(this.wba(this.Ao),this.Ao.prependTo(this.Qb),"icon"===this.options.cancelBehavior&&(this.$A(this.Ao),this.py=this.Ao.find(".oj-dialog-title"),this.py.length&&this.py.insertAfter(this.ip))):this.Gba();this.Sm=this.element.children(".oj-dialog-footer");this.vba(this.Sm);this.Sm.length&&(this.Sm.addClass("oj-helper-clearfix"),this.Sm.appendTo(this.Qb));"title-bar"===this.options.dragAffordance&&f.fn.draggable&&
this.Nt();this.co=!1},KQ:function(){"show"===this.options.initialVisibility&&this.open()},_destroy:function(){this.Rba&&window.clearTimeout(this.Rba);this.isOpen()&&this.Xp();this.fm&&(this.fm("instance")&&this.fm("destroy"),this.fm=null);this.Sm.length&&(this.Sm.removeClass("oj-helper-clearfix"),f("#"+this.xZ).replaceWith(this.Sm));this.iB();if(this.vz){var a=this.Qb.find(".oj-dialog-header");a&&f("#"+this.yZ).replaceWith(a)}this.T5&&(this.T5.remove(),this.T5=null);this.element.removeUniqueId().removeClass("oj-dialog-content oj-dialog-default-content").css(this.upa);
this.Qb&&this.Qb.stop(!0,!0);this.element.unwrap();this.OO&&this.element.attr("title",this.OO);this.Tm&&(this.Tm.remove(),this.Tm=null);delete this.xj;delete this.co;this._super()},widget:function(){return this.Qb},disable:f.noop,enable:f.noop,close:function(a){if(this.isOpen()&&(!1!==this._trigger("beforeClose",a)||this.cx)){this.co=!1;this.Uca=null;this.opener.filter(":focusable").focus().length||f(this.document[0].activeElement).blur();var d={};d[b.N.Qa.gf]=this.Qb;b.N.pe().close(d);this._trigger("close",
a)}},isOpen:function(){return this.co},open:function(a){if(!1!==this._trigger("beforeOpen",a)){if(!this.isOpen()){this.co=!0;this.opener=f(this.document[0].activeElement);"resizable"===this.options.resizeBehavior&&this.ZY();a="rtl"===this.ec();a=b.qc.Gg(this.options.position,a);var d={};d[b.N.Qa.gf]=this.Qb;d[b.N.Qa.ov]=this.opener;d[b.N.Qa.tv]=a;d[b.N.Qa.Yh]=this.options.modality;d[b.N.Qa.np]=this.rt();d[b.N.Qa.bn]="oj-dialog-layer";d[b.N.Qa.an]=b.N.an.LF;b.N.pe().open(d);this._trigger("open")}this.MV()}},
refresh:function(){this._super()},MV:function(){var a=this.Uca;a&&0<a.length&&b.v.Qo(this.Qb[0],a[0])||(a||(a=this.element.find("[autofocus]")),a.length||(a=this.element.find(":tabbable")),a.length||this.Sm.length&&(a=this.Sm.find(":tabbable")),a.length||this.tP&&(a=this.tP.filter(":tabbable")),a.length||(a=this.Qb),a.eq(0).focus(),this._trigger("focus"))},_keepFocus:function(a){a.preventDefault();a=this.document[0].activeElement;this.Qb[0]===a||f.contains(this.Qb[0],a)||this.MV()},Fe:function(a){return!isNaN(parseInt(a,
10))},Hba:function(){this.CY=!1;this.element.uniqueId();this.BI=this.element.attr("id");this.Bma="ojDialogWrapper-"+this.BI;this.Qb=f("\x3cdiv\x3e");this.Qb.addClass("oj-dialog oj-component").hide().attr({tabIndex:-1,role:this.options.role,id:this.Bma});this.Qb.insertBefore(this.element);this._on(this.Qb,{keyup:function(){},keydown:function(a){if("none"!=this.options.cancelBehavior&&!a.isDefaultPrevented()&&a.keyCode&&a.keyCode===f.ui.keyCode.ESCAPE)a.preventDefault(),a.stopImmediatePropagation(),
this.close(a);else if(a.keyCode===f.ui.keyCode.TAB){var b=this.Qb.find(":tabbable"),c=b.filter(":first"),e=b.filter(":last");a.shiftKey?a.shiftKey&&(a.target===c[0]||a.target===this.Qb[0]?(e.focus(),a.preventDefault()):(c=b.index(document.activeElement),1==c&&b[0]&&(b[0].focus(),a.preventDefault()))):a.target===e[0]||a.target===this.Qb[0]?(c.focus(),a.preventDefault()):(c=b.index(document.activeElement),0==c&&b[1]&&(b[1].focus(),a.preventDefault()))}}});this.element.find("[aria-describedby]").length||
this.Qb.attr({"aria-describedby":this.element.uniqueId().attr("id")})},iB:function(){this.ip&&(this.ip.remove(),this.tP=this.ip=null)},$A:function(a){this.ip=f("\x3cdiv\x3e").addClass("oj-dialog-header-close-wrapper").attr("tabindex","1").attr("aria-label","close").attr("role","button").appendTo(a);this.tP=f("\x3cspan\x3e").addClass("oj-component-icon oj-clickable-icon oj-dialog-close-icon").attr("alt","close icon").prependTo(this.ip);this._on(this.ip,{click:function(a){a.preventDefault();a.stopImmediatePropagation();
this.close(a)},mousedown:function(a){f(a.currentTarget).addClass("oj-active")},mouseup:function(a){f(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){f(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){a=a.currentTarget;f(a).removeClass("oj-hover");f(a).removeClass("oj-active")},keyup:function(a){if(a.keyCode&&a.keyCode===f.ui.keyCode.SPACE||a.keyCode===f.ui.keyCode.ENTER)a.preventDefault(),a.stopImmediatePropagation(),this.close(a)}})},Gba:function(){var a;this.Tm=f("\x3cdiv\x3e").addClass("oj-dialog-header oj-helper-clearfix").prependTo(this.Qb);
this._on(this.Tm,{mousedown:function(a){f(a.target).closest(".oj-dialog-close-icon")||this.Qb.focus()}});"icon"===this.options.cancelBehavior&&this.$A(this.Tm);a=f("\x3cspan\x3e").uniqueId().addClass("oj-dialog-title").appendTo(this.Tm);this.f1(a);this.Qb.attr({"aria-labelledby":a.attr("id")})},f1:function(a){this.options.title||a.html("\x26#160;");a.text(this.options.title)},Nt:function(){function a(a){return{position:a.position,offset:a.offset}}var b=this,c=this.options;this.Qb.draggable({Nra:!1,
cancel:".oj-dialog-content, .oj-dialog-header-close",handle:".oj-dialog-header",containment:"document",start:function(c,g){f(this).addClass("oj-dialog-dragging");b.vT();b.Cx();b._trigger("dragStart",c,a(g))},drag:function(c,f){b.Cx();b._trigger("drag",c,a(f))},stop:function(e,g){c.position=[g.position.left-b.document.scrollLeft(),g.position.top-b.document.scrollTop()];f(this).removeClass("oj-dialog-dragging");b.m1();b.Cx();b._trigger("dragStop",e,a(g))}});this.Qb.addClass("oj-draggable")},ZY:function(){function a(a){return{originalPosition:a.$o,
originalSize:a.Rj,position:a.position,size:a.size}}var b=this;this.Qb.css("position");this.fm=this.Qb.ojResizable.bind(this.Qb);this.fm({cancel:".oj-dialog-content",containment:"document",handles:"n,e,s,w,se,sw,ne,nw",start:function(c,e){b.CY=!0;f(this).addClass("oj-dialog-resizing");b.vT();b._trigger("resizeStart",c,a(e))},resize:function(c,e){b._trigger("resize",c,a(e))},stop:function(c,e){b.CY=!1;f(this).removeClass("oj-dialog-resizing");b.m1();b._trigger("resizeStop",c,a(e))}})},dL:function(){var a=
"rtl"===this.ec(),a=b.qc.Gg(this.options.position,a);this.Qb.position(a);this.Cx()},Cx:function(){b.N.pe().sP(this.Qb,b.N.Bc.dn)},_setOption:function(a,d,c){var e;e=this.Qb;if("disabled"!==a)switch(this._super(a,d,c),a){case "dragAffordance":(a=e.hasClass("oj-draggable"))&&"none"===d&&(e.draggable("destroy"),this.Qb.removeClass("oj-draggable"));a||"title-bar"!==d||this.Nt();break;case "position":this.dL();break;case "resizeBehavior":e=!1;this.fm&&(e=!0);e&&"resizable"!=d&&(this.fm("instance")&&this.fm("destroy"),
this.fm=null);e||"resizable"!==d||this.ZY();break;case "title":this.f1(this.Tm.find(".oj-dialog-title"));break;case "role":e.attr("role",d);break;case "modality":this.isOpen()&&(e={},e[b.N.Qa.gf]=this.Qb,e[b.N.Qa.Yh]=d,b.N.pe().vu(e));break;case "cancelBehavior":"none"===d||"escape"===d?this.iB():"icon"===d&&(this.vz?(this.iB(),this.$A(this.Ao),this.py=this.Ao.find(".oj-dialog-title"),this.py.length&&this.py.insertAfter(this.ip)):(this.iB(),this.$A(this.Tm),this.z5=this.Tm.find(".oj-dialog-title"),
this.z5.length&&this.z5.insertAfter(this.ip)))}},vT:function(){this.$N=this.document.find("iframe").map(function(){var a=f(this),b=a.offset();return f("\x3cdiv\x3e").css({width:a.outerWidth(),height:a.outerHeight()}).appendTo(a.parent()).offset(b)[0]})},m1:function(){this.$N&&(this.$N.remove(),delete this.$N)},vba:function(a){this.xZ="ojDialogPlaceHolderFooter-"+this.BI;this.Aia=f("\x3cdiv\x3e").hide().attr({id:this.xZ});this.Aia.insertBefore(a)},wba:function(a){this.yZ="ojDialogPlaceHolderHeader-"+
this.BI;this.Bia=f("\x3cdiv\x3e").hide().attr({id:this.yZ});this.Bia.insertBefore(a)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-dialog-header":case "oj-dialog-body":case "oj-dialog-footer":case "oj-dialog-content":case "oj-dialog-header-close-wrapper":case "oj-resizable-n":case "oj-resizable-e":case "oj-resizable-s":case "oj-resizable-w":case "oj-resizable-se":case "oj-resizable-sw":case "oj-resizable-ne":case "oj-resizable-nw":a="."+
a;if(!this.widget().find(a))break;return this.widget().find(a)[0];case "oj-dialog-close-icon":case "oj-dialog-close":if(!this.widget().find(".oj-dialog-close-icon"))break;return this.widget().find(".oj-dialog-close-icon")[0]}return null},getSubIdByNode:function(a){if(null!=a){a=f(a);if(a.hasClass("oj-dialog-header"))return{subId:"oj-dialog-header"};if(a.hasClass("oj-dialog-footer"))return{subId:"oj-dialog-footer"};if(a.hasClass("oj-dialog-content"))return{subId:"oj-dialog-content"};if(a.hasClass("oj-dialog-header-close-wrapper"))return{subId:"oj-dialog-header-close-wrapper"};
if(a.hasClass("oj-dialog-close-icon"))return{subId:"oj-dialog-close"};if(a.hasClass("oj-resizable-n"))return{subId:"oj-resizable-n"};if(a.hasClass("oj-resizable-e"))return{subId:"oj-resizable-e"};if(a.hasClass("oj-resizable-s"))return{subId:"oj-resizable-s"};if(a.hasClass("oj-resizable-w"))return{subId:"oj-resizable-w"};if(a.hasClass("oj-resizable-se"))return{subId:"oj-resizable-se"};if(a.hasClass("oj-resizable-sw"))return{subId:"oj-resizable-sw"};if(a.hasClass("oj-resizable-ne"))return{subId:"oj-resizable-ne"};
if(a.hasClass("oj-resizable-nw"))return{subId:"oj-resizable-nw"}}return null},Tq:function(){this.element.remove()},rt:function(){if(!this.xj){var a=this.xj={};a[b.N.Bc.Zr]=f.proxy(this.Xp,this);a[b.N.Bc.$r]=f.proxy(this.Tq,this);a[b.N.Bc.dn]=f.proxy(this.Cx,this)}return this.xj},Xp:function(){this.cx=!0;this.close();delete this.cx}})})()});