/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery"],function(b,f){b.$f=function(a,b,c){c=c||{};this.i=b;this.pB=a;this.dt=c.fetchSize;this.dt=0<this.dt?this.dt:25;this.Ot=c.maxCount;this.Ot=0<this.Ot?this.Ot:500;this.bD=0;this.R0=c.success;this.zca=c.error;this.Lq();f(this.pB).on("scroll.domscroller",function(a){var b=f(a.target).scrollTop();a=f(a.target)[0].scrollHeight-f(a.target)[0].clientHeight;0<a&&this.cK(b,a)}.bind(this))};b.$f.prototype.destroy=function(){this.Mk();f(this.pB).off("scroll.domscroller")};b.b.g("DomScroller.prototype.destroy",
{destroy:b.$f.prototype.destroy});b.$f.prototype.checkViewport=function(){return 0<this.pB[0].clientHeight&&!this.raa()?this.yV():Promise.resolve(null)};b.b.g("DomScroller.prototype.checkViewport",{checkViewport:b.$f.prototype.checkViewport});b.$f.prototype.cK=function(a,b){if(1>=b-a){var c=this;this.yV().then(function(a){null!=c.R0&&c.R0(a)},this.zca)}};b.$f.prototype.raa=function(){var a=this.pB;return a[0].scrollHeight>a[0].clientHeight+1?!0:!1};b.$f.prototype.yV=function(){if(this.sB)return this.sB;
var a=this.Ot-this.bD;if(0<a){var b=this.dt,c=this;a<this.dt&&(b=a);var e=this.Jca({pageSize:b});return this.sB=new Promise(function(b){e.then(function(d){c.sB=null;null!=d&&(c.bD=d.data.length+d.startIndex,a<c.dt&&(d.maxCount=c.Ot,d.maxCountLimit=!0));b(d)})})}return Promise.resolve({maxCount:this.Ot,maxCountLimit:!0})};b.$f.prototype.Jca=function(a){a=a||{};var b=a.pageSize;this.Eh=this.Eh?this.Eh+b:b;if(-1==this.i.totalSize()||this.i.totalSize()>this.Eh){var c=this;return new Promise(function(a,
f){c.i.fetch({startIndex:c.Eh,pageSize:b}).then(function(b){a(b)},function(){f(null)})})}return Promise.resolve()};b.$f.prototype.Xn=function(){this.Eh=null;this.bD=0};b.$f.prototype.$ea=function(a){this.Eh=a.startIndex;this.bD=a.data.length+this.Eh};b.$f.prototype.Lq=function(){var a=this.i;if(null!=a){this.Mk();this.Ua=[];this.Ua.push({eventType:b.T.D.SORT,eventHandler:this.Xn.bind(this)});this.Ua.push({eventType:b.T.D.REFRESH,eventHandler:this.Xn.bind(this)});this.Ua.push({eventType:b.T.D.RESET,
eventHandler:this.Xn.bind(this)});this.Ua.push({eventType:b.T.D.SYNC,eventHandler:this.$ea.bind(this)});var d,c;for(d=0;d<this.Ua.length;d++)(c=a.on(this.Ua[d].eventType,this.Ua[d].eventHandler))&&(this.Ua[d].eventHandler=c)}};b.$f.prototype.Mk=function(){var a=this.i;if(null!=this.Ua&&null!=a){var b;for(b=0;b<this.Ua.length;b++)a.off(this.Ua[b].eventType,this.Ua[b].eventHandler)}}});