/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation","ojs/internal-deps/dvt/DvtToolkit","promise"],function(b,f,a,d,c){function e(a,b){this.xia=b;this.oka=a;this.Sba="/"}b.Ng=function(a){this.Init(a)};o_("AttributeGroupHandler",b.Ng,b);b.b.ga(b.Ng,b.b,"oj.AttributeGroupHandler");b.Ng.prototype.Init=function(a){b.Ng.q.Init.call(this);this.nx=a?a:{};this.gw={};this.ND=0;this.Kz=this.mr();for(var c in this.nx)a=this.Kz.indexOf(this.nx[c]),-1!==a&&this.Kz.splice(a,1)};b.Ng.prototype.mr=
function(){return[]};b.b.g("AttributeGroupHandler.prototype.getValueRamp",{mr:b.Ng.prototype.mr});b.Ng.prototype.Lc=function(a){if(this.nx[a])return this.nx[a];this.gw[a]||(this.gw[a]=this.Kz[this.ND],this.ND==this.Kz.length-1?this.ND=0:this.ND++);return this.gw[a]};b.b.g("AttributeGroupHandler.prototype.getValue",{Lc:b.Ng.prototype.Lc});b.Ng.prototype.J2=function(){var a=[],b;for(b in this.gw)a.push({category:b,value:this.gw[b]});return a};b.b.g("AttributeGroupHandler.prototype.getCategoryAssignments",
{J2:b.Ng.prototype.J2});b.Ng.prototype.B1=function(a,b){this.nx[a]=b};b.b.g("AttributeGroupHandler.prototype.addMatchRule",{B1:b.Ng.prototype.B1});b.Av=function(a){this.Init(a)};o_("ShapeAttributeGroupHandler",b.Av,b);b.b.ga(b.Av,b.Ng,"oj.ShapeAttributeGroupHandler");b.Av.hw="square circle diamond plus triangleDown triangleUp human".split(" ");b.Av.prototype.mr=function(){return b.Av.hw.slice()};e.prototype.hka=function(a,b,c,d){for(var e={};a&&-1<b.indexOf(c);){var g=b.substring(0,b.indexOf(c));
d&&void 0===a[g]&&(a[g]={});a=a[g];b=b.substring(b.indexOf(c)+1,b.length)}a&&(e.object=a,e.parameter=b);return e};e.prototype.H_=function(a){void 0===this.mx&&(a=this.hka(this.oka,this.xia,this.Sba,a),this.mx=a.object,this.ZK=a.parameter)};e.prototype.Lc=function(){this.H_(!1);return void 0===this.mx?void 0:this.mx[this.ZK]};e.prototype.r5=function(a,b){this.H_(!0);if(b||!this.mx[this.ZK])this.mx[this.ZK]=a};var g={CSS_TEXT_PROPERTIES:function(a){var b={};a&&(a.hasClass("oj-gaugeMetricLabel")&&a.hasClass(a.parentNode,
"oj-ledGauge")?(b["font-size"]=!0,b.color=!0):a.hasClass(a,"oj-chartSliceLabel")?b.color=!0:a.hasClass("oj-treemap-node-header")&&(b["font-weight"]=!0));return g.aaa(a,b)},CSS_BACKGROUND_PROPERTIES:function(a){return g.S$(a)},CSS_URL:function(a){return g.wia(a)},uR:"rgb(254, 0, 254)",b8:"Times",c8:"1px",wR:"1",vR:"normal",U7:4,pD:{},Cna:function(a,b){return a.css(b)},wia:function(a){return(a=a.css("background-image"))&&-1!==a.indexOf("url(")?a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):
a},S$:function(a){var b={};a.css("border-top-color")&&(b["border-color"]=a.css("border-top-color"));a.css("border-width")&&a.css("border-style")&&"none"!=a.css("border-style")&&(b["border-width"]=a.css("border-width"));a.css("background-color")&&(b["background-color"]=a.css("background-color"));return b},aaa:function(a,b){var c={},d=a.css("font-family");d&&d!==g.b8&&(c["font-family"]=d.replace(/"/g,"'"));d=a.css("font-size");!d||-1<d.indexOf("px")&&parseFloat(d)<g.U7||b["font-size"]||(c["font-size"]=
d);(d=a.css("font-weight"))&&d!==g.wR&&!b["font-weight"]&&(c["font-weight"]=d);(d=a.css("color"))&&d!==g.uR&&!b.color&&(c.color=d);(d=a.css("font-style"))&&d!==g.vR&&(c["font-style"]=d);return c},Apa:function(a,b,c,d){var e=f(document.createElement("div"));e.attr("style","display:none;");a.append(e);a="";for(var p=0;p<c.length;p++)a=a+c[p]+" ";e.attr("class",a);f(document.body).append(e);c=f(document.createElement("div"));c.css("font-size",g.c8);c.css("color",g.uR);c.css("font-weight",g.wR);c.css("font-style",
g.vR);e.append(c);for(var r in d)a=d[r],a instanceof Array||(a=[a]),g.Uia(c,b,r,a);e.remove()},Uia:function(a,b,c,d){g.pD[c]||(g.pD[c]={});for(var n=null,p=0;p<d.length;p++){var r=d[p],s=r.property;if(s){var q=g.pD[c][s];"undefined"==typeof q&&(n||(n=f(document.createElement("div")),n.addClass(c),a.append(n)),q=g.ika(n,s),g.pD[c][s]=q);if(null!=q){var r=new e(b,r.path),t=g[s];if(null!=t){var v=r.Lc();if("CSS_URL"!==s){s="";if(null!=v){for(var w in q)-1===v.indexOf(w)&&(s+=w+":"+q[w]+";");s+=v}else for(w in q)s+=
w+":"+q[w]+";";q=s}}r.r5(q,null!=t)}}}},ika:function(a,b){var c=g[b],c=c?c(a):g.Cna(a,b);return null==c||"string"==typeof c&&""==c.replace(/^\s+/g,"")?null:c}};b.ya("oj.dvtBaseComponent",f.oj.baseComponent,{_ComponentCreate:function(){this._super();this.yx=this.CL=0;this.Ek=null;this.oL=f(document.createElement("div"));this.oL.attr("style","visibility:hidden;");this.element.append(this.oL);var a=this.element[0].parentElement;this.lg=a&&a.zI?a.zI:new c.DvtContext(this.element[0],null,this.oL[0]);this.lg.setReadingDirection(this.ec());
this.lg.setTooltipAttachedCallback(b.Components.Sf);this.lg.setTooltipStyleClass("oj-dvt-tooltip");this.lg.setDatatipStyleClass("oj-dvt-datatip");f(document.body).hasClass("oj-hicontrast")&&c.DvtAgent.setHighContrast(!0);this.ka=this.nf(this.lg,this.ki,this);this.lg.getStage().addChild(this.ka);!1!==c.requireJS&&(this.Uka(),this.KZ());this.vs();this.options._environment="jet";this.options._widgetConstructor=b.Components.Of(this.element)},mf:function(){this._super();this.element.attr("tabIndex",0);
this.ig();"off"!=this.options.trackResize&&this.ZG()},refresh:function(){this._super();this.lg.setReadingDirection(this.ec());this.KZ();this.ig()},getNodeBySubId:function(a){var b=this.ka&&this.ka.getAutomation?this.ka.getAutomation():null;if(b)return a=this.di(a),b.getDomElementForSubId(a)},getSubIdByNode:function(a){var b=this.ka&&this.ka.getAutomation?this.ka.getAutomation():null;if(b)return(a=b.getSubIdForDomElement(a))?this.gg(a):null},di:function(){return null},gg:function(){return null},lA:function(){for(var a=
this.Be(),b=0;b<a.length;b++)this.element.addClass(a[b]);g.Apa(this.element,this.options,this.Be(),this.ei())},Be:function(){return["oj-dvtbase"]},ei:function(){return{"oj-dvt-no-data-message":{path:"_statusMessageStyle",property:"CSS_TEXT_PROPERTIES"}}},hi:function(){return[]},ii:function(){var a=this.options.translations,a={"DvtUtilBundle.CLEAR_SELECTION":a.labelClearSelection,"DvtUtilBundle.COLON_SEP_LIST":a.labelAndValue,"DvtUtilBundle.INVALID_DATA":a.labelInvalidData,"DvtUtilBundle.NO_DATA":a.labelNoData,
"DvtUtilBundle.DATA_VISUALIZATION":a.labelDataVisualization,"DvtUtilBundle.STATE_SELECTED":a.stateSelected,"DvtUtilBundle.STATE_UNSELECTED":a.stateUnselected,"DvtUtilBundle.STATE_MAXIMIZED":a.stateMaximized,"DvtUtilBundle.STATE_MINIMIZED":a.stateMinimized,"DvtUtilBundle.STATE_EXPANDED":a.stateExpanded,"DvtUtilBundle.STATE_COLLAPSED":a.stateCollapsed,"DvtUtilBundle.STATE_ISOLATED":a.stateIsolated,"DvtUtilBundle.STATE_HIDDEN":a.stateHidden,"DvtUtilBundle.STATE_VISIBLE":a.stateVisible,"DvtUtilBundle.SCALING_SUFFIX_THOUSAND":a.labelScalingSuffixThousand,
"DvtUtilBundle.SCALING_SUFFIX_MILLION":a.labelScalingSuffixMillion,"DvtUtilBundle.SCALING_SUFFIX_BILLION":a.labelScalingSuffixBillion,"DvtUtilBundle.SCALING_SUFFIX_TRILLION":a.labelScalingSuffixTrillion,"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION":a.labelScalingSuffixQuadrillion},c=b.Ja.Ky("abbreviated");a["DvtUtilBundle.MONTH_SHORT_JANUARY"]=c[0];a["DvtUtilBundle.MONTH_SHORT_FEBRUARY"]=c[1];a["DvtUtilBundle.MONTH_SHORT_MARCH"]=c[2];a["DvtUtilBundle.MONTH_SHORT_APRIL"]=c[3];a["DvtUtilBundle.MONTH_SHORT_MAY"]=
c[4];a["DvtUtilBundle.MONTH_SHORT_JUNE"]=c[5];a["DvtUtilBundle.MONTH_SHORT_JULY"]=c[6];a["DvtUtilBundle.MONTH_SHORT_AUGUST"]=c[7];a["DvtUtilBundle.MONTH_SHORT_SEPTEMBER"]=c[8];a["DvtUtilBundle.MONTH_SHORT_OCTOBER"]=c[9];a["DvtUtilBundle.MONTH_SHORT_NOVEMBER"]=c[10];a["DvtUtilBundle.MONTH_SHORT_DECEMBER"]=c[11];return a},KZ:function(){var a=this.ii();c.DvtBundle.addLocalizedStrings(a)},Uka:function(){var a={};a.numberConverterFactory=b.pa.Q2("number");a.dateToIsoConverter=function(a){return a instanceof
Date?b.sb.dateToLocalIso(a):a};a.isoToDateConverter=function(a){return"string"==typeof a?b.sb.isoToLocalDate(a):a};this.lg.setLocaleHelpers(a)},_destroy:function(){this.lg.hideTooltips();this.ka.destroy&&this.ka.destroy();this.yL();this.element.children().remove();this.element.removeAttr("role").removeAttr("tabIndex");for(var a=this.Be(),b=0;b<a.length;b++)this.element.removeClass(a[b]);this._super()},_setOptions:function(a,b){this._superApply(arguments);var c=this.options.trackResize;"off"==c&&this.Bi?
this.yL():"off"==c||this.Bi||this.ZG();if(!this.tT){var d=!1,e=this.hi(),g=["highlightedCategories","selection","dataCursorPosition"];f.each(a,function(a){if(0>e.indexOf(a)&&0>g.indexOf(a))return d=!0,!1});d?this.ig():(void 0!==a.highlightedCategories&&this.ka.highlight(a.highlightedCategories),void 0!==a.selection&&this.ka.select(a.selection),void 0!==a.dataCursorPosition&&this.ka.positionDataCursor&&this.ka.positionDataCursor(a.dataCursorPosition))}},nf:function(){return null},ki:function(a){var b=
a&&a.getType?a.getType():null;b===c.DvtCategoryHideShowEvent.TYPE_HIDE||b===c.DvtCategoryHideShowEvent.TYPE_SHOW?this.jc("hiddenCategories",a.hiddenCategories):b===c.DvtCategoryRolloverEvent.TYPE_OVER||b===c.DvtCategoryRolloverEvent.TYPE_OUT?this.jc("highlightedCategories",a.categories):b===c.DvtOptionChangeEvent.TYPE?this.jc(a.key,a.value,a.optionMetadata):this.options.contextMenu&&b===c.DvtComponentTouchEvent.TOUCH_HOVER_END_TYPE?this.sf(f.Event(a.getNativeEvent()),"touch"):"ready"===b&&0===this.yx&&
(this.kL&&this.kL(!0),this.NZ=!0,this.jL=this.kL=null)},ZG:function(){this.Bi||(this.Bi=this.Ve.bind(this),b.v.Nh(this.element[0],this.Bi,250))},yL:function(){this.Bi&&(b.v.Oi(this.element[0],this.Bi),this.Bi=null)},Ve:function(){var a=this.element.width(),b=this.element.height();(null==this.PD||null==this.kC||5<=Math.abs(a-this.PD)+Math.abs(b-this.kC))&&this.ig(!0)},vs:function(){},ig:function(a){this.NZ=!1;this.lg.isReadyToRender()?(this.PD=this.aA()?null:this.element.width(),this.kC=this.aA()?
null:this.element.height(),this.options._width=this.PD,this.options._height=this.kC,this.options._locale=b.ba.Ag(),this.lA(),this.CL++,a?this.Ek||this.BL(null):0===this.gka().length&&this.BL(this.options),this.EL=!1):this.EL=!0},yl:function(){this._super();this.EL&&this.ig()},sn:function(){this._super();this.EL&&this.ig()},li:function(){this._super();this.lg.hideTooltips()},xl:function(){this._super();this.lg.hideTooltips()},jc:function(a,b,c){this.tT=!0;this.option(a,b,{_context:{Ic:!0,yr:c,Va:!0}});
this.tT=!1},qf:function(a,b,c){"touch"!==c&&("keyboard"===c?this.sf(b,c,{position:{of:this.ka.getKeyboardFocus()}}):this._super(a,b,c))},Kv:function(a){return(a=b.Components.Of(a)("instance"))?a.ka:null},Tg:function(a){if(a){var b={},c;for(c in a)this.a$(a,c,b);Object.defineProperties(a,b)}},a$:function(a,b,c){var d=("selected"==b?"is":"get")+b.charAt(0).toUpperCase()+b.slice(1);c[d]={value:function(){return a[b]}}},Bp:function(a){for(var b="",c=0;c<a.length;c++)b+="["+a[c]+"]";return b},wl:function(a){for(var b=
[],c=0;0<a.indexOf("[",c);){var d=a.indexOf("[",c)+1,c=a.indexOf("]",c);b.push(Number(a.substring(d,c)));c+=1}return b},Ug:function(a){return Number(this.Vz(a))},Vz:function(a){var b=a.indexOf("[")+1,c=a.indexOf("]");return a.substring(b,c)},gi:function(){return{}},gka:function(){this.Ek=null;var a=this.gi(),b;for(b in a)for(var c=a[b],d=0;d<c.length;d++)if("root"===b){if(this.$p(this.options,c[d]))break}else{var e=this.options[b];if(e)for(var g=0;g<e.length&&!this.$p(e[g],c[d]);g++);}var f=[];this.yx=
0;if(this.Ek){var s=this;for(b in a)c=a[b],c.forEach(function(a){var c;if("root"===b)(c=s.KW(s.Ek,a))&&f.push(c);else{var d=s.Ek[b];if(d)for(var e=0;e<d.length;e++)(c=s.KW(d[e],a))&&f.push(c)}})}return f},$p:function(a,b){if(!this.Ek){var d=(new e(a,b)).Lc();d&&(d instanceof Function||d instanceof Promise)&&(this.Ek=c.DvtJSONUtils.clone(this.options))}return null!==this.Ek},KW:function(a,b){var c=new e(a,b),d=c.Lc();d instanceof Function&&(d=Promise.resolve(d(this.rR(a))));if(d&&d instanceof Promise){this.yx++;
var g=this.CL,f=this;d.then(function(a){f.v_(g,c,a)},function(){f.v_(g,c,[])});return d}return null},v_:function(a,b,c){a===this.CL&&(this.yx--,b.r5(c,!0),0===this.yx&&(this.BL(this.Ek),this.Ek=null))},BL:function(a){var b=this.aA()&&this.Bi;b&&this.yL();this.ka.render(a,this.PD,this.kC);b&&this.ZG()},rR:function(){return{}},aA:function(){return!1},whenReady:function(){if(this.NZ)return Promise.resolve(!0);if(!this.jL){var a=this;this.jL=new Promise(function(b){a.kL=b})}return this.jL}},!0);b.Le=
function(a){this.hw=[];if(f(document.body).hasClass("oj-hicontrast"))this.hw=b.Le.dR.slice();else{if(!b.Le.tw){b.Le.tw=[];var c=f(document.createElement("div"));c.attr("style","display:none;");c.attr("id","attrGps");f(document.body).append(c);for(var d=0;d<b.Le.qS.length;d++){var e=f(document.createElement("div"));e.addClass(b.Le.qS[d]);c.append(e);(e=e.css("color"))&&b.Le.tw.push(e)}c.remove()}this.hw=0<b.Le.tw.length?b.Le.tw.slice():b.Le.dR.slice()}this.Init(a)};o_("ColorAttributeGroupHandler",
b.Le,b);b.b.ga(b.Le,b.Ng,"oj.ColorAttributeGroupHandler");b.Le.dR="#267db3 #68c182 #fad55c #ed6647 #8561c8 #6ddbdb #ffb54d #e371b2 #47bdef #a2bf39 #a75dba #f7f37b".split(" ");b.Le.qS="oj-dvt-category1 oj-dvt-category2 oj-dvt-category3 oj-dvt-category4 oj-dvt-category5 oj-dvt-category6 oj-dvt-category7 oj-dvt-category8 oj-dvt-category9 oj-dvt-category10 oj-dvt-category11 oj-dvt-category12".split(" ");b.Le.tw=null;b.Le.prototype.mr=function(){return this.hw.slice()}});