/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","ojs/ojjquery-hammer","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(b,f,a){b.ve={};o_("EditableValueUtils",b.ve,b);b.ve.Wna=function(a,b){var c,d,e={};if(a&&b)switch(b){case "disabled":c=void 0!==a.attr("disabled")?!!a.prop("disabled"):void 0;break;case "pattern":c=a.prop("pattern")||void 0;break;case "placeholder":c=a.prop("placeholder")||void 0;break;case "readonly":c=void 0!==a.attr("readonly")?!!a.prop("readonly"):void 0;break;case "required":c=
a.attr("required");d=a.prop("required");c=void 0!==c?void 0!==d?!!d:!!c:void 0;break;case "title":c=void 0!==a.attr("title")?a.prop("title"):void 0;break;case "value":c=a.val()||void 0;break;default:c=a.attr(b)||void 0}void 0!==c?(e.E2=!0,e.value=c):e.E2=!1;return e};b.ve.al=function(a,c,d,e){for(var g={},f=0;f<a.length;f++){var h,k;h=a[f];k=h.W;var l=h.option||k,u=h.Ze,y=h.yc,x=d.element,B=d.options[l];void 0===c[l]&&(B=d.options[l],k=b.ve.Wna(x,k),k.E2?(h=k.value,u&&("boolean"===typeof u?h=b.ve.cna(l,
h):"function"===typeof u&&(h=u.call(d,h))),g[l]=h):void 0===B&&(g[l]=h.cE));u=l in g?g[l]:B;y&&"boolean"===typeof y&&b.ve.Aqa(l,u)}null!=e&&e(g);d.option(g,{_context:{Ic:!0,Va:!0}})};b.ve.Aqa=function(a,b){var c=!1;switch(a){case "required":null!==b&&"boolean"!==typeof b&&(c=!0);break;case "readOnly":case "disabled":null!==b&&"boolean"!==typeof b&&(c=!0)}if(c)throw"Option '"+a+"' has invalid value set: "+b;};b.ve.cna=function(a,b){var c=b;switch(a){case "required":c=b?!0:!1}return c};b.gb=function(a){this.Init(a)};
b.Sa.QE(b.Sa.fd.Dz,b.gb);b.b.ga(b.gb,b.pc,"oj.PopupMessagingStrategy");b.gb.ls={ojRadioset:{position:"launcher",Gj:{open:"focus focusin mouseover",close:"mouseout"}},ojCheckboxset:{position:"launcher",Gj:{open:"focusin mouseover",close:"mouseout"}},ojInputText:{position:"launcher",Gj:{open:"focusin"}},ojTextArea:{position:"launcher",Gj:{open:"focusin"}},ojInputPassword:{position:"launcher",Gj:{open:"focusin"}},ojSwitch:{position:"launcher",Gj:{open:"focusin mouseover",close:"mouseout"}},ojSlider:{position:"launcher",
Gj:{open:"focusin mouseover",close:"mouseout"}},"default":{position:"launcher-wrapper",Gj:{open:"focusin"}}};b.gb.DG="oj-form-control-hint";b.gb.m9="oj-form-control-hint-converter";b.gb.o9="oj-form-control-hint-validator";b.gb.n9="oj-form-control-hint-title";b.gb.prototype.Do=function(a){b.gb.q.Do.call(this,a);this.wga()};b.gb.prototype.Br=function(a){b.gb.q.Br.call(this,a);this.r1()};b.gb.prototype.update=function(){b.gb.q.update.call(this);this.r1()};b.gb.prototype.Uk=function(){this.dma();this.Wba();
b.gb.q.Uk.call(this)};b.gb.prototype.dU=function(){this.AY()&&this.Ke.ojPopup("close")};b.gb.prototype.wga=function(){this.NC||this.uja()};b.gb.prototype.tZ=function(){var a,c;if(this.laa()&&(c=this.yT(),!b.Fa.Ji(c))){var d=this.IW();a=d.ojPopup("isOpen");a?a&&(a=d[0],a.innerHTML="",a.innerHTML=c,d.ojPopup("refresh")):(a=d[0],a.innerHTML="",a.innerHTML=c,d.ojPopup("open",this.Xh()))}};b.gb.prototype.laa=function(){var a=this.Vi().options,b=a.readOnly||!1;return!(a.disabled||b)};b.gb.prototype.r1=
function(){var a;a=!1;var b,c;if(this.AY()){var d=this.IW();a=d.ojPopup("isOpen");b=this.yT();c=document.activeElement===this.Xh()[0]?!0:!1;a?b?(a=d[0],a.innerHTML="",a.innerHTML=b,d.ojPopup("refresh")):d.ojPopup("close"):c&&b&&this.tZ()}};b.gb.prototype.dma=function(){var a=b.gb.ls[this.Vi().widgetName],a=a?a.Gj:b.gb.ls["default"].Gj;if(a.open){var c=this.NC;delete this.NC;c&&this.Xh().off(a.open,c)}a.close&&(c=this.eU)&&this.Xh().off(a.close,c)};b.gb.prototype.uja=function(){var a=this.Xh(),c=b.gb.ls[this.Vi().widgetName],
c=c?c.Gj:b.gb.ls["default"].Gj;if(c.open){var d=this.NC;d||(d=this.NC=f.proxy(this.tZ,this));a.on(c.open,d)}c.close&&(d=this.eU,d||(d=this.eU=f.proxy(this.dU,this)),a.on(c.close,d))};b.gb.prototype.lea=function(){var a,c=b.gb.ls[this.Vi().widgetName];(c=c?c.position:b.gb.ls["default"].position)&&("launcher"===c?a=this.Xh():"launcher-wrapper"===c&&(a=this.Xh().parent()));a||(a=this.Vi().widget());return{my:"start bottom",at:"end top",collision:"flipcenter",of:a}};b.gb.prototype.IW=function(){if(this.Ke)return this.Ke;
var a=b.vd.f3(),c=this.lea();a.ojPopup("option","position",c);a.ojPopup("option","close",f.proxy(this.Dia,this));a.ojPopup("option","open",f.proxy(this.Eia,this));return this.Ke=a};b.gb.prototype.Eia=function(a){var c=f(a.target),d=this;window.setTimeout(function(){b.Components.dO(c)?c.ojPopup("option","autoDismiss","focusLoss"):delete d.Ke},10)};b.gb.prototype.Dia=function(a){a=f(a.target);b.Components.dO(a)&&(a.ojPopup("option","autoDismiss","none"),a.ojPopup("option","open",null),a.ojPopup("option",
"close",null));delete this.Ke;a.children().remove()};b.gb.prototype.Wba=function(){this.dU();b.vd.Gna()};b.gb.prototype.yT=function(){var a="",c=this.Vi().document[0],d=[],e=!1;this.zQ()&&d.push(this.oH(c));(this.KF()||this.BQ()||this.AQ())&&d.push(this.U$(c));f.each(d,function(d,g){g&&(e?a=a.concat(b.Na.foa(c)):e=!0,a=a.concat(g))});return a};b.gb.prototype.oH=function(a){var c;c="";var d=this.qF();this.yF()&&(c=this.rF(),c=b.Na.O1(a,c,d,!1));return c};b.gb.prototype.U$=function(a){var c=[],d,e=
"";this.KF()&&(c=this.VP(),c=c.length?c[0]:"",e+=b.Na.bN(a,b.gb.m9,c,!1,b.gb.DG));if(this.BQ())for(c=this.A6(),d=0;d<c.length;d++)e+=b.Na.bN(a,b.gb.o9,c[d],!1,b.gb.DG);this.AQ()&&(e+=b.Na.bN(a,b.gb.n9,this.z6(),!0,b.gb.DG));return e?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+e+"\x3c/div\x3e":""};b.gb.prototype.AY=function(){return this.Ke?b.Components.dO(this.Ke):!1};b.Na={};b.Na.bN=function(a,c,d,e,g){var h;d&&(h=f(a.createElement("div")),h.addClass(g+(" "+c)),h.append(b.Na.cX(a,d,e)));return h?
h.get(0).outerHTML:""};b.Na.n3=function(a){var c;switch(a){case b.X.Tb.FATAL:c=b.ha.A("oj-message.fatal");break;case b.X.Tb.ERROR:c=b.ha.A("oj-message.error");break;case b.X.Tb.WARNING:c=b.ha.A("oj-message.warning");break;case b.X.Tb.INFO:c=b.ha.A("oj-message.info");break;case b.X.Tb.CONFIRMATION:c=b.ha.A("oj-message.confirmation")}return c};b.Na.foa=function(a){return(a=f(a.createElement("hr")))?a.get(0).outerHTML:""};b.Na.O1=function(a,c,d,e){var g="",f,h,k,l,u={};l=[];for(f=0;f<c.length;f++)k=
c[f],l=k instanceof b.X?k:new b.X(k.summary,k.detail,k.severity),h=b.X.Iu(l.severity),u[h]||(u[h]=[]),u[h].push(l);for(f=d;f>=b.X.Tb.CONFIRMATION;f--)for(l=u[f]||[],c=0;c<l.length;c++)k=l[c],b.l.Bd(k,b.X),h=b.X.Iu(k.severity),d=b.Na.n3(h),d=k.summary||d,k=k.detail||"",g=g.concat(b.Na.N1(a,d,k,h,e));return g};b.Na.N1=function(a,c,d,e,g){var h,k;k=b.Na.n3(e);h=f(a.createElement("div"));h.addClass(b.Na.p9);g&&h.addClass(b.Na.uea(e));g=f(a.createElement("span"));g.addClass(b.Na.tea(e)).attr("title",k).attr("role",
"img");h.append(g);e=f(a.createElement("span"));e.addClass(b.Na.s9);k=f(a.createElement("div"));k.addClass(b.Na.w9).text(c);e.append(k);d&&(c=b.Na.cX(a,d,!0),a=f(a.createElement("div")),a.addClass(b.Na.t9).append(c),e.append(a));h.append(e);return h?h.get(0).outerHTML:""};b.Na.tea=function(a){var c;switch(a){case b.X.Tb.FATAL:c=b.Na.pS;break;case b.X.Tb.ERROR:c=b.Na.pS;break;case b.X.Tb.WARNING:c=b.Na.y9;break;case b.X.Tb.INFO:c=b.Na.v9;break;case b.X.Tb.CONFIRMATION:c=b.Na.r9}return b.Na.w7+c};b.Na.uea=
function(a){switch(a){case b.X.Tb.FATAL:a=b.Na.oS;break;case b.X.Tb.ERROR:a=b.Na.oS;break;case b.X.Tb.WARNING:a=b.Na.x9;break;case b.X.Tb.INFO:a=b.Na.u9;break;default:a=b.Na.q9}return a};b.Na.cX=function(a,c,d){var e=null;b.Fa.od(c)&&(d&&b.v.apa(c)?e=b.v.$ma(c.substring(6,c.length-7)):(e=a.createElement("span"),e.textContent=c));return e};b.Na.w7="oj-component-icon oj-message-status-icon ";b.Na.p9="oj-message";b.Na.w9="oj-message-summary";b.Na.t9="oj-message-detail";b.Na.s9="oj-message-content";b.Na.pS=
"oj-message-error-icon";b.Na.y9="oj-message-warning-icon";b.Na.v9="oj-message-info-icon";b.Na.r9="oj-message-confirmation-icon";b.Na.oS="oj-message-error";b.Na.x9="oj-message-warning";b.Na.u9="oj-message-info";b.Na.q9="oj-message-confirmation";b.vd={};b.vd.f3=function(){var a=b.vd.HW(),c=a.find("."+b.vd.EG);0===c.length?(c=f(b.vd.kea()).hide(),c.appendTo(a),c.ojPopup({rootAttributes:{"class":b.vd.z9},initialFocus:"none",tail:"simple",autoDismiss:"none",modality:"modeless"})):c=f(c[0]);return c};b.vd.Gna=
function(){if(0<b.vd.Eda()){var a=b.vd.f3();a.ojPopup("destroy");a.remove()}};b.vd.HW=function(){var a=f("#"+b.vd.MR);if(0<a.length)return a;a=f("\x3cdiv\x3e");a.attr("id",b.vd.MR);a.attr("role","presentation");a.appendTo(f(document.body));return a};b.vd.Eda=function(){return b.vd.HW().find("."+b.vd.EG).length};b.vd.kea=function(){return"\x3cdiv class\x3d'"+b.vd.EG+"'\x3e\x3c/div\x3e"};b.vd.EG="oj-messaging-popup-container";b.vd.z9="oj-messaging-popup";b.vd.MR="__oj_messaging_popup_pool";(function(){b.ya("oj._ojLabel",
f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{ariaRequiredUnsupported:!1,describedById:null,help:{definition:null,source:null},required:!1,rootAttributes:null},xa:{MS:"tooltipHelp",NS:"tooltipRequired"},widget:function(){return this.Kr},refresh:function(){this._super();this.WZ();this.SZ()},Yd:function(a,b){this._super(a,b);this.saa();this.IH()},_ComponentCreate:function(){this._super();this.wD=this.eventNamespace+"TouchEatClick";this.lC=this.eventNamespace+
"HelpDefPopup";this.Fn=b.v.Sd();this.sca()},Tv:function(a){this.Yx=a.attr("class")},Cs:function(){this.Yx?this.element.attr("class",this.Yx):this.element.removeAttr("class")},sca:function(){var a=this.options,b=a.required,a=a.ariaRequiredUnsupported,c=this.kZ(),d=null;this.Kr=this.element.wrap(this.Aba()).closest(".oj-component");this.$ha();c&&(d=this.ZH());this.qU(d);b&&(a?d.appendChild(this.dB()):this.element.before(this.dB()))},qU:function(a){var b=this.options,c=b.help.definition;if(b.help.source||
c)this.Kga(a),this.c$(),this.G$()},saa:function(){var a=this.options.required;if(null!==a&&"boolean"!==typeof a)throw Error("Option 'required' has invalid value set: "+a);},IH:function(){var a=this.options;if(this.kZ()&&null==a.describedById)throw Error("ojLabel's describedById option must be set if help source is set\n\r\n      or (ariaRequiredUnsupported and required is set).");},$ha:function(){var a=this.element.attr("class"),b;if(a&&(a=a.split(/\s+/),null!=a)){b=a.length;for(var c=0;c<b;c++){var d=
a[c];0<d.indexOf("-label")&&(this.Kr.addClass(d),this.element.removeClass(d))}}},ZH:function(){var a=this.Kr.find(".oj-label-group"),b=document.createElement("span");b.setAttribute("id",this.options.describedById);a.prepend(b);return b},Aba:function(){var a=this.options.rootAttributes,b,c;c="oj-label oj-component";a&&(b=a["class"]);null!==b&&(c=c+" "+b);a=document.createElement("div");a.className=c;c=document.createElement("div");c.className="oj-label-group";a.appendChild(c);return a},dB:function(){var a=
this.A(this.xa.NS),b=document.createElement("span");b.className="oj-label-required-icon oj-component-icon";b.setAttribute("role","img");b.setAttribute("title",a);return b},dba:function(a,c){var d;if(this.JC()){d=document.createElement("a");d.setAttribute("tabindex","0");d.setAttribute("target","_blank");d.className="oj-label-help-icon-anchor oj-label-help-icon oj-component-icon oj-clickable-icon-nocontext";if(c)try{b.v.zqa(c),d.setAttribute("href",c)}catch(e){throw Error(e+". The source option ("+
c+") is invalid.");}a?d.setAttribute("title",a):d.setAttribute("title",this.A(this.xa.MS))}return d},G$:function(){var b;b=this.options.help.definition;var c,d,e;d=this.widget().find(".oj-label-help-icon-anchor");if(0!=d.length){c=b?b:this.A(this.xa.MS);this.ax?(e=f(document.getElementById(this.ax)))&&e.text(c):(b=document.createElement("div"),b.style.display="none",e=f(b),e.uniqueId(),this.ax=e.prop("id"),e.text(c),c=document.getElementsByTagName("body")[0],c.appendChild(b));this.Fn&&(this.oB&&this.widget().off(this.wD),
this.oB=function(){return!1});var g=this;this.OC||(this.OC=function(a){g.Kfa(a,e,d,!1)});if(this.Fn)d.jl({recognizers:[[a.Press,{time:750}]]}).on("press",this.OC);else d.on("focusin"+this.lC+" mousedown"+this.lC,this.OC);b={my:"start bottom",at:"end top",collision:"flipcenter",of:d};e.ojPopup({position:b,modality:"modeless"})}},Kfa:function(a,b,c,d){if("mousedown"===a.type)d=!0;else if("focusin"===a.type&&d)d=!1;else{if(this.Fn)if("press"===a.type){var e=this.widget();e.on("click"+this.wD,this.oB);
var g=this;b.on("ojclose",function(){e.off(g.wD);g.oB=null})}else b.off("ojclose");b.ojPopup("isOpen")||b.ojPopup("open",c)}},c$:function(){var a=this.element,b=this.options.help.definition,c;b&&(a.addClass("oj-label-help-def"),(c=a.attr("title"))?a.attr("title",c+" "+b):a.attr("title",b))},o_:function(a){this.Fn&&(this.widget().off(this.wD),this.oB=null,a.jl().off(this.lC));a.off(this.lC);this.OC=null},p_:function(){var a;if(null!=this.ax){if(a=f(document.getElementById(this.ax)))a.ojPopup("destroy"),
a.remove();this.ax=null}},Ija:function(){this.element.removeClass("oj-label-help-def");this.element.attr("title","")},Kga:function(a){var b=this.options.help.source,c=this.options.help.definition;this.JC()&&f(a).prepend(this.dba(c,b))},kZ:function(){var a=this.options;return this.JC()||a.ariaRequiredUnsupported&&a.required},JC:function(){var a=this.options;return a.help.source||a.help.definition},SZ:function(){var a,b;this.IH();this.Ija();a=this.Kr.find(".oj-label-help-icon");1===a.length&&(this.o_(a),
this.p_(),a.remove());a=this.JC();b=document.getElementById(this.options.describedById);null!=a&&null==b?b=this.ZH():null==a&&null!==b&&0===b.children.length&&b.remove();this.qU(b)},WZ:function(){var a,b;b=this.Kr.find(".oj-label-required-icon");a=this.options.describedById;this.options.required?(this.IH(),0===b.length?this.options.ariaRequiredUnsupported?(b=document.getElementById(a),null==b&&(b=this.ZH()),b.appendChild(this.dB())):this.element.before(this.dB()):(a=this.A(this.xa.NS),b.attr("title",
a))):(b.remove(),b=document.getElementById(a),null!==b&&0===b.children.length&&b.remove())},_setOption:function(a,b){this._superApply(arguments);"required"===a&&this.WZ();"help"===a&&this.SZ()},getNodeBySubId:function(a){var b;b=this._super(a);b||(a=a.subId,"oj-label-help-icon"===a&&(b=this.widget().find(".oj-label-help-icon")[0]),"oj-label-required-icon"===a&&(b=this.widget().find(".oj-label-required-icon")[0]));return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a===this.widget().find(".oj-label-help-icon")[0]?
b={subId:"oj-label-help-icon"}:a===this.widget().find(".oj-label-required-icon")[0]&&(b={subId:"oj-label-required-icon"}));return b||this._superApply(arguments)},_destroy:function(){var a=this.Kr.find(".oj-label-help-icon");this.o_(a);this.p_();b.v.unwrap(this.element,this.Kr);return this._super()}})})();var d={h6:1,FP:2,IP:3,nQ:4,oQ:5,pQ:6,V6:7,d7:8,FQ:9,GQ:10,g7:11},c={Jo:!0,Pi:d.FP},e={Jo:!0,Pi:d.IP},g={Jo:!0,Pi:d.pQ},h={Jo:!0,Pi:d.nQ},k={Jo:!0,Pi:d.oQ},l={Jo:!0,Pi:d.GQ};b.ya("oj.editableValue",
f.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:!1,displayOptions:void 0,help:{definition:null,source:null},messagesCustom:void 0,messagesHidden:void 0,messagesShown:void 0,required:!1,title:"",validators:void 0,value:void 0},getNodeBySubId:function(a){return this._super(a)},isValid:function(){void 0===this.RM&&(this.RM=this.Bea());return this.RM},refresh:function(){this._super();this.fV(!0)},reset:function(){this.VA();this.Xx(this.ej.V6);this.qL(this.options.value,!0)},showMessages:function(){var a=
this.options.messagesHidden,c,d=!1,e,g=[];for(e=0;e<a.length;e++)d=!0,c=a[e],c instanceof b.Jc&&c.Vca(),g.push(c.clone());d&&(this.qw("messagesHidden"),this.GD("messagesShown",g))},validate:function(){return this.hc(this.hg(),null,this.wA)},Xv:{OP:1,f7:2,qQ:3},ej:d,wA:{er:!1,Pi:d.FQ},Yd:function(a,b){this._super(a,b)},_ComponentCreate:function(){var a=this.element,b=this.sR(a);this._super();this.options.messagesCustom=this.options.messagesCustom||[];this.options.messagesHidden=[];this.options.messagesShown=
0<this.options.messagesCustom.length?this.Daa(this.options.messagesCustom):[];this.FG(a);this.Dp()&&(this.yn(this.options.placeholder),this.iI=!0);f.each(["required","title"],function(c,d){d in b&&a.removeAttr(d)})},mf:function(){this._super();this.mba();this.fV(!1);this.qC();this.Xx(this.ej.h6);0<this.options.messagesShown.length&&this.$x("messagesShown",this.options.messagesShown,null,!0);this.widget().addClass("oj-form-control")},Tv:function(a){this.E9(a)},Cs:function(a){this.k9(a)},LQ:function(a,
b){switch(a){case "disabled":this.MQ(a,e);break;case "converter":this.i7(a);break;case "displayOptions":this.qC();break;case "help":this.Wg(a,this.options[a]);break;case "messagesCustom":this.Rha(b);break;case "placeholder":this.Cia(b);break;case "readOnly":this.MQ(a,h);break;case "required":this.j7(a);break;case "title":this.Sla();break;case "translations":this.refresh();break;case "value":this.k7(a,b);break;case "validators":this.fs(a)}},i7:function(a){var b=!1;this.i9();this.iC()&&(b=!0);b?(this.WA(),
this.ID(c)):this.Wg(a,this.options[a],!0)},MQ:function(a,b){var c=!this.options[a];this.Wg(a,this.options[a]);c&&this.J_(b)},j7:function(a){this.Wg(a,this.options[a]);this.J_(g)},k7:function(a,b){var c=!1,d,e=b?b._context:null;e&&(c=e.originalEvent?!0:!1,d=e.Jo||!1);c||(d||this.VA(null),this.Xx(this.ej.g7));this.Wg(a,this.options[a],!0)},fs:function(){var a=!1;this.nS();this.iC()&&(a=!0);a&&(this.WA(),this.ID(l))},Hv:function(){var a=this.options.readOnly||!1;return this.options.disabled||a?!1:!0},
_destroy:function(){this.widget();var a=this._super();this.VA(null,!0);this.kt().Uk();this.Rb&&null!=b.Components.Of(this.Rb[0])&&this.Rb._ojLabel("destroy");return a},Focus:function(){this.Xd().focus();return!0},_setOption:function(a,c,d){var e;e=!1;if("string"===typeof a&&void 0!==c)switch(a){case "messagesHidden":e=!0;break;case "messagesShown":e=!0;break;case "rawValue":e=!0}if(e)return b.r.error(a+" option cannot be set"),this;e=this._superApply(arguments);this.LQ(a,d);return e},Xd:function(){return this.element},
W7:function(){var a=this.NV(this.element);if(null!==a&&0!==a.length)return a;a=this.element.prop("id");if(void 0!==a&&(a=f("label[for\x3d'"+a+"']"),0!==a.length))return a;a=this.element.closest("[aria-labelledby]");return 0!==a.length&&(a=this.NV(a),null!==a&&0!==a.length)?a:null},qs:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.Xd()},Uc:function(){this.Kc||(this.Kc=b.sb.getConverterInstance(this.options.converter));return this.Kc||null},Lv:function(){this.RX||
(this.RX={});return this.RX},hg:function(){return this.Xd().val()},qR:function(){if(!this.cw){var a=[],c=this.options.validators,d,e=!0,g=this.Lv(),f=[],h,k;k=Object.keys(g);h=k.length;if(0<h){for(var l=0;l<h;l++)d=k[l],f.push(g[d]);a=a.concat(f)}if(c){f=[];for(k=0;k<c.length;k++)d=c[k],"object"===typeof d?(d.validate&&"function"===typeof d.validate||(e=!1),e||(h=d.type)&&"string"===typeof h&&((g=b.pa.Lr(h))?(d=b.oc.$e({},d.options)||{},d.converter=d.converter||this.Uc(),d.label=d.label||this.jJ(),
d=g.createValidator(d)):b.r.error("Unable to locate a validatorFactory for the requested type: "+h)),f.push(d)):b.r.error("Unable to parse the validator provided:"+d);a=a.concat(f)}this.cw=a}return this.cw||[]},nS:function(){this.cw&&(this.cw.length=0);this.cw=null;this.kt().update(this.si(this.Ch.HQ))},i9:function(){this.Kc=null;this.kt().update(this.si(this.Ch.EP))},fk:function(){return this.options.required},Xz:function(a){var b=this.hg();this.hc(b,a)},zn:function(a,b){var c={};c._context={originalEvent:b,
Ic:!0,Va:!0};this.options.rawValue!==a&&this.option("rawValue",a,c)},Wg:function(a,b,c){switch(a){case "converter":b=this.options.value;this.qL(b,c);break;case "disabled":this.a_("disabled",this.options.disabled);break;case "help":b=this.options.help.definition;c=this.options.help.source;a=this.RI();this.Rb&&(this.Rb._ojLabel("option","describedById",a),this.Rb._ojLabel("option","help",{definition:b,source:c}));break;case "required":this.a_("required",this.fk());this.BG(b);this.Rb&&(a=this.RI(),this.Rb._ojLabel("option",
{describedById:a,ariaRequiredUnsupported:this.Lz()}),this.Rb._ojLabel("option","required",b));break;case "value":this.qL(b,c)}},BG:function(a){var b=this.Xd();a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},Lz:function(){return!1},CG:function(){this.Rb&&this.Rb._ojLabel("refresh");this.Kc=this.qK=null;this.nS()},oi:function(a){var b=this.Xd();b.val()!==a&&b.val(a)},FG:function(a){"boolean"===typeof this.options.disabled&&a.prop("disabled",this.options.disabled)},yn:function(a){this.Xd().attr("placeholder",
a)},rS:function(a){this.options.placeholder=a},Dp:function(){return this.options.placeholder},ZQ:function(){this.rS("");this.yn("")},hc:function(a,c,d){var e=d&&"boolean"===typeof d.er?d.er:!0;if(void 0===a)return b.r.warn("Attempt to set a value of undefined"),!1;if(e&&a===this.Nda())b.r.dz>b.r.cn&&b.r.info("Validation skipped and value option not updated as submitted value '"+a.toString?a.toString():a+" same as previous.");else if(a=this.PS(a,c,d),void 0!==a&&this.isValid()){var g;d&&d._context&&
(g=d._context);this.t1(a,c,d&&d.Pi,g);return!0}return!1},PS:function(a,c,d){var e=d&&d.Bqa?d.Bqa:this.Xv.OP,g=d&&d.Pi?d.Pi:this.ej.d7;d=d&&d.Jo||!1;if(void 0===a)b.r.warn("Attempt to set a value of undefined");else if(this.Hv()){d||this.VA(c);this.e0(a);try{return this.pka(a,e,g,c)}catch(f){}}else b.r.dz>b.r.cn&&b.r.info("Validation skipped and value option not set as component state does not  allow setting value. For example if the component is readonly or disabled.")},Iv:function(a,c,d){return"value"===
a?b.b.mh(c,d):0===a.indexOf("messages")?this.Sha(c,d):this._superApply(arguments)},_GetDefaultStyleClass:function(){b.l.Zb();return""},Ch:{bv:1,IQ:2,EP:3,HQ:4,DQ:5},xn:{disabled:"oj-disabled",required:"oj-required"},VA:function(a,b){b?(this.options.messagesHidden=[],this.options.messagesShown=[],this.options.messagesCustom=[]):(this.qw("messagesHidden",a),this.qw("messagesShown",a),this.qw("messagesCustom",a))},WA:function(){var a=this.options.messagesShown,c=a.length,d;this.qw("messagesHidden");
for(var e=c-1;0<=e;e--)d=a[e],d instanceof b.Jc&&a.splice(e,1);a.length!==c&&this.$x("messagesShown",a,null,!0)},$x:function(a,b,c,d){var e={},g=0===b.length&&0===this.options[a].length;if(d||!g)e._context={originalEvent:c,Ic:!0,Va:!0},e.changed=d||!g,this.eka(),this.option(a,b,e),this.pma()},qw:function(a,b){this.$x(a,[],b)},Daa:function(a){var c,d=[],e;if(a&&0<a.length)for(e=0;e<a.length;e++)c=a[e],c instanceof b.X?d.push(c.clone()):(c=new b.X(c.summary,c.detail,c.severity),c=Object.freeze?Object.freeze(c):
c,d.push(c));return d},mba:function(){if(this.Rb=this.W7()){var a=this.options.help.definition,b=this.options.help.source,c=this.Lz(),d=this.T9(b,a,this.options.required,c);this.Rb._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:d,required:this.options.required,ariaRequiredUnsupported:c,help:{definition:a,source:b}})}},fV:function(a){var b=!1;a?(this.CG(),this.qC(),this.iC()&&(b=!0),this.WA(),b?this.ID(k):(this.fk()&&this.Xx(k.Pi),this.Wg("value",this.options.value,
!0))):(this.Wg("value",this.options.value),this.Wg("required",this.options.required));this.Wg("disabled",this.options.disabled)},nra:function(){return this.oZ},Nda:function(){void 0===this.VK&&(this.VK="");return this.VK},NV:function(a){a=a.attr("aria-labelledby");return void 0!==a?f("label[id\x3d'"+a+"']"):null},RI:function(){this.element.uniqueId();return this.element.prop("id")+"Icons"},T9:function(a,b,c,d){var e=this.RI();(a||b||c&&d)&&this.XG(e);return e},XG:function(a){this.Xd().each(function(){var b=
f(this).attr("aria-describedby");b?f(this).attr("aria-describedby",b+" "+a):f(this).attr("aria-describedby",a)})},SB:function(){return this.options.messagesShown.concat(this.options.messagesHidden)},jJ:function(){if(this.Rb)return this.Rb.text()},iX:function(){this.w1||(this.w1=new b.Qi(this.isValid(),this.SB()));return this.w1},iK:function(){return!b.X.isValid(this.SB())},iC:function(){return!this.isValid()&&0<this.options.messagesShown.length},$fa:function(){for(var a=this.options.messagesShown,
c,d,e=0;e<a.length;e++)c=a[e],c instanceof b.Jc&&c.tY()&&(d=d||[],d.push(c));return void 0===d?!1:!b.X.isValid(d)},qC:function(){var a=this.kt(),b=this._GetMessagingLauncherElement(),c=this.si(this.Ch.bv);this.iI||this.ZQ();a.Do(b,c)},Rha:function(a){var c=this.options.messagesCustom,d=[],e,g,f=this.options.messagesShown,h=a?a._context:null;for(g=0;g<f.length;g++)e=f[g],e instanceof b.Jc&&e.tY()&&d.push(e);for(g=0;g<c.length;g++)d.push(c[g]);this.$x("messagesShown",d,h?h.originalEvent:null,a&&a.changed)},
Cia:function(a){a=(a&&a._context||{}).Zoa?!1:!0;this.yn(this.options.placeholder);a?(this.iI=!0,this.Uc()&&this.qC()):this.iI=!1},Rka:function(a){this.oZ=a},e0:function(a){this.VK=a},Sla:function(){this.kt().update(this.si(this.Ch.DQ))},GD:function(a,b,c){var d,e,g;if("object"===typeof b&&Array.isArray(b))for(g=this.options[a],d=b.length,e=0;e<d;e++)g.push(b[e]);this.$x(a,g,c,!0)},pma:function(){this.kt().update(this.si())},t1:function(a,b,c,d){d=d||{};b&&(d.originalEvent=b);switch(c){case this.ej.FP:case this.ej.IP:case this.ej.nQ:case this.ej.oQ:case this.ej.pQ:case this.ej.FQ:case this.ej.GQ:d.Ic=
!0,d.Jo=!0}this.option({value:a},{_context:d})},eka:function(){this.RM=void 0},Bea:function(){var a=this.SB(),b=!0;a&&0!==a.length&&(b=!this.iK());return b},dq:function(a){var c=a,d=this.Uc();d&&"object"===typeof d&&(d.format&&"function"===typeof d.format?c=d.format(a):b.r.dz>b.r.cn&&b.r.info("converter does not support the format method."));return c},kt:function(){this.Yp||(this.Yp=new b.Sa(this));return this.Yp},Jda:function(a){var b,c=[];b="";var d;this.fk()&&(b=this.oW(),b.getHint&&"function"===
typeof b.getHint&&(b=b.getHint())&&c.push(b));for(d=0;d<a.length;d++)b=a[d],"object"===typeof b&&b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b);return c},oW:function(){var a;a={};var c;null==this.qK&&(a=this.options.translations?this.options.translations.required||{}:{},c={hint:a.hint||null,label:this.jJ(),messageSummary:a.messageSummary||null,messageDetail:a.messageDetail||null},this.qK=(a=b.pa.Lr(b.ed.VALIDATOR_TYPE_REQUIRED))?a.createValidator(c):null);return this.qK},si:function(a){var b=
{},c=this.Uc(),d="",e=[];a=a||this.Ch.IQ;if(a===this.Ch.bv||a===this.Ch.IQ)e=this.SB(),this.iX().update(this.isValid(),e),b.Y5=this.iX();if(a===this.Ch.bv||a===this.Ch.EP)c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(d=c.getHint()||""),b.d2=d;if(a===this.Ch.bv||a===this.Ch.HQ)c=this.qR(),e=this.Jda(c)||[],b.Cqa=e;if(a===this.Ch.bv||a===this.Ch.DQ)b.title=this.options.title||"";return b},Sha:function(a,c){var d=-1,e,g=!0,h=f.extend([],a),k=f.extend([],c);if(h.length!==k.length)return!1;
f.each(h,function(a,c){c instanceof b.X?e=c:(e=new b.X(c.summary,c.detail,c.severity),e=Object.freeze?Object.freeze(e):e);d=-1;f.each(k,function(a,b){e.Ko(b)&&(d=a)});-1<d?k.splice(d,1):g=!1});return g},PC:function(a){var c=this.Uc(),d=a;c&&"object"===typeof c&&(c.parse&&"function"===typeof c.parse?d=c.parse(a):b.r.dz>b.r.cn&&b.r.info("converter does not support the parse method."));return d},$G:function(a,c){var d,e,g;a instanceof b.Me||a instanceof b.Ah?(d=a.Hu(),b.l.Bd(d,b.X),g=d.severity,e=d.summary,
d=d.detail):(g=b.X.Tb.ERROR,e=b.ha.A("oj-message.error"),d=a.message||b.ha.A("oj-converter.detail"));c.push({summary:e,detail:d,severity:g})},iL:function(a,c,d){var e={},g=[],f=a.qx||[];e.context=c||0;e.display=d||b.Jc.Pr.HF;0===f.length&&this.$G(a,f);for(c=0;c<f.length;c++)a=f[c],g.push(this.$aa(a.summary,a.detail,a.severity,e));return g||null},$aa:function(a,c,d,e){a=new b.Jc(a,c,d,e);return a=Object.seal?Object.seal(a):a},qL:function(a,b){var c=a||this.options.value,d;d=this.oZ;(b||c!==d)&&this.nma(c)},
a_:function(a,b){-1!==Object.keys(this.xn).indexOf(a)&&this.widget().toggleClass(this.xn[a],!!b)},Xx:function(a){if(this.Hv())try{this.v1(this.options.value,this.Xv.qQ)}catch(c){(a=this.iL(c,a,b.Jc.Pr.uF))&&this.GD("messagesHidden",a)}else b.r.dz>b.r.cn&&b.r.info("Deferred validation skipped as component is readonly or disabled.")},pka:function(a,b,c,d){var e=a;try{b===this.Xv.OP&&(e=this.PC(a)),this.v1(e,b===this.Xv.qQ)}catch(g){throw a=this.iL(g,c),this.GD("messagesShown",a,d),g;}return e},J_:function(a){var b=
!0;this.iC()&&(b=!1);this.WA();b?this.fk()&&this.Xx(a.Pi):this.ID(a)},nma:function(a,b){var c,d;this.Rka(a);c=a;try{c=this.dq(a)}catch(e){d=this.iL(e),this.GD("messagesShown",d,b)}this.oi(c);c=this.hg();this.e0(c);this.zn(c,null)},ID:function(a){var b;b=this.PS(this.hg(),null,a);void 0===b||!this.isValid()&&this.$fa()||this.t1(b,null,a.Pi)},v1:function(a,c){var d=this.qR(),e,g,f=[];if(this.fk()){e=this.oW();try{e.validate(b.Fa.trim(a))}catch(h){this.$G(h,f)}}if(!c)for(g=0;g<d.length;g++)if(e=d[g],
"object"===typeof e)if(e.validate&&"function"===typeof e.validate)try{e.validate(a)}catch(k){this.$G(k,f)}else b.r.dz>b.r.cn&&b.r.info("validator does not support the validate method.");if(0<f.length)throw d=Error(),d.qx=f,d;}},!0);b.Components.Om({editableValue:{displayOptions:{messages:["inline"],converterHint:["placeholder","notewindow"],validatorHint:["notewindow"],title:["notewindow"]}}});b.ff=function(a){this.Init(a)};b.Sa.QE(b.Sa.fd.nv,b.ff);b.b.ga(b.ff,b.pc,"oj.InlineMessagingStrategy");b.ff.prototype.Br=
function(a){b.ff.q.Br.call(this,a);this.TZ()};b.ff.prototype.gP=function(a){return a&&void 0!==a.Y5?!0:!1};b.ff.prototype.update=function(){b.ff.q.update.call(this);this.TZ()};b.ff.prototype.Uk=function(){this.r_();b.ff.q.Uk.call(this)};b.ff.prototype.TZ=function(){var a,b;a=this.Vi().widget();this.hV()||(this.Ke=f("\x3cdiv class\x3d'oj-messaging-inline-container'\x3e\x3c/div\x3e"),this.XG(this.Ke),a.append(this.Ke));(b=this.V$())?(a=this.Ke[0],a.innerHTML="",a.innerHTML=b):this.r_()};b.ff.prototype.r_=
function(){this.hV()&&this.Ke&&(this.yja(this.Ke),this.Ke.remove(),this.Ke=null)};b.ff.prototype.XG=function(a){var c=this.Xh();b.l.Bd(c,jQuery);b.l.Bd(a,jQuery);a=a.uniqueId().attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];d.push(a);d=f.trim(d.join(" "));c.attr("aria-describedby",d)};b.ff.prototype.yja=function(a){var c=this.Xh();b.l.Bd(c,jQuery);b.l.Bd(a,jQuery);a=a.attr("id");var d=c.attr("aria-describedby"),d=d?d.split(/\s+/):[];a=f.inArray(a,d);-1!==a&&d.splice(a,1);(d=f.trim(d.join(" ")))?
c.attr("aria-describedby",d):c.removeAttr("aria-describedby")};b.ff.prototype.V$=function(){var a=this.Vi().document[0];return this.zQ()?this.oH(a):""};b.ff.prototype.oH=function(a){var c;c="";var d=this.qF();this.yF()&&(c=this.rF(),c=b.Na.O1(a,c,d,!0));return c};b.ff.prototype.hV=function(){return null!=this.Ke}});