/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise"],function(b,f){b.Id=function(){this.Init()};b.b.ga(b.Id,b.Pg,"oj.FilmStripPagingModel");b.Id.prototype.Init=function(){b.Id.q.Init.call(this);this.Nc=-1;this.ke=0;this.La=-1};b.b.g("FilmStripPagingModel.prototype.Init",{Init:b.Id.prototype.Init});b.Id.prototype.Zpa=function(a){this.ke=a};b.Id.prototype.getPage=function(){return this.Nc};b.b.g("FilmStripPagingModel.prototype.getPage",{getPage:b.Id.prototype.getPage});b.Id.prototype.setPage=
function(a,b){a=parseInt(a,10);try{var c=this.getPageCount(),e=this.Nc,f=this.La,h=f;b&&b.pageSize&&(h=b.pageSize);var k=Math.ceil(this.ke/h);if(0>a||a>k-1)throw Error("JET FilmStrip: Invalid 'page' set: "+a);var l=!1;if(a!=e||h!=f){if(!1===this.handleEvent("beforePage",{page:a,previousPage:e}))return Promise.reject();l=!0}this.Nc=a;this.La=h;var m=this.getPageCount(),n=this;return new Promise(function(b){c!=m&&n.handleEvent("pageCount",{pageCount:m,previousPageCount:c});l&&n.handleEvent("page",{page:a,
previousPage:e});b(null)})}catch(p){return Promise.reject(p)}};b.b.g("FilmStripPagingModel.prototype.setPage",{setPage:b.Id.prototype.setPage});b.Id.prototype.getStartItemIndex=function(){return this.Nc*this.La};b.b.g("FilmStripPagingModel.prototype.getStartItemIndex",{getStartItemIndex:b.Id.prototype.getStartItemIndex});b.Id.prototype.getEndItemIndex=function(){return Math.min(this.getStartItemIndex()+this.La,this.ke)-1};b.b.g("FilmStripPagingModel.prototype.getEndItemIndex",{getEndItemIndex:b.Id.prototype.getEndItemIndex});
b.Id.prototype.getPageCount=function(){return Math.ceil(this.ke/this.La)};b.b.g("FilmStripPagingModel.prototype.getPageCount",{getPageCount:b.Id.prototype.getPageCount});b.Id.prototype.totalSize=function(){return this.ke};b.b.g("FilmStripPagingModel.prototype.totalSize",{totalSize:b.Id.prototype.totalSize});b.Id.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("FilmStripPagingModel.prototype.totalSizeConfidence",{totalSizeConfidence:b.Id.prototype.totalSizeConfidence});(function(){function a(a){var b=
f("\x3cdiv\x3e\x3c/div\x3e");b.text(a);return b[0].innerHTML}function d(a){a.css("-webkit-transform",p).css("-ms-transform",p).css("transform",p)}function c(a,b){a.css("-webkit-transform",b).css("-ms-transform",b).css("transform",b)}b.ya("oj.ojFilmStrip",f.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{maxItemsPerPage:0,orientation:"horizontal",currentItem:0,arrowPlacement:"adjacent",arrowVisibility:"auto"},_ComponentCreate:function(){this._super();var a=this.element;
a.addClass("oj-filmstrip oj-component").attr("tabindex",0).attr("role","region");a.uniqueId();a=this.options;a.disabled&&b.r.warn(da);if(a.orientation!==y&&a.orientation!==fa)throw Error(s+a.orientation);if(a.arrowPlacement!==e&&a.arrowPlacement!==Y)throw Error(q+a.arrowPlacement);if(a.arrowVisibility!==ba&&a.arrowVisibility!==w&&a.arrowVisibility!==x&&a.arrowVisibility!==h)throw Error(t+a.arrowVisibility);this.sz=this.eventNamespace+"Touch";this.HE=this.eventNamespace+"Mouse";this.c4=this.eventNamespace+
"Key";this.JO=this.eventNamespace+"NavArrowHoverable";this.Aa(!0)},refresh:function(){this._super();this.Aa(!1)},getItemsPerPage:function(){return this.Cq},getPagingModel:function(){return this.ge},yl:function(){this._super();this.Zc&&this.Aa(this.Zc[0])},sn:function(){this._super();this.Zc&&this.Aa(this.Zc[0])},Aa:function(a){if(this.kw()){this.Zc=null;this.xf="rtl"===this.ec();this.Fn=b.v.Sd();var c=this.element,d=this;a?(this.Cq=0,this.$J=function(a){d.ZJ(a)},this.ge=new b.Id,this.Kn=0,this.kx=
-1,this.zk=function(){d.vq()},this.eh=function(){d.Ve()},this.Fn&&(this.FX=function(a){d.hK(a)},this.EX=function(a){d.gK(a)},this.fK=function(a){d.eK(a)},this.n$()),this.uX=function(a){d.Ffa(a)},this.vX=function(a){d.Gfa(a)},this.xX=function(a){d.Ifa(a)},this.j$(),this.tX=function(a){d.tq(a)},this.h$()):this.UU();for(var e=c.children(),f=0;f<e.length;f++)b.Components.Kg(e[f]);a&&(a=this.ge,a.Zpa(e.length),a.on("page",this.$J));this.yma();this.eT();for(f=0;f<e.length;f++)b.Components.Sf(e[f]);b.v.Nh(c[0],
this.eh)}else c=!1,this.Zc&&(c=this.Zc[0]),this.Zc=[a||c]},_destroy:function(){this.Fn&&(this.Vja(),this.fK=this.EX=this.FX=null);this.Oja();this.xX=this.vX=this.uX=null;this.Mja();this.tX=null;this.UU();this.ge.off("page",this.$J);this.zk=this.eh=this.ge=this.$J=null;var a=this.element;a.removeClass("oj-filmstrip oj-component "+L).removeAttr("tabindex role");a.removeUniqueId();this._super()},UU:function(){b.v.Oi(this.element[0],this.eh);this.kx=-1;this.Kx&&(clearTimeout(this.Kx),this.Kx=null);for(var a=
this.QB(),c=0;c<a.length;c++)b.Components.Kg(a[c]);this.ST();this.hJ().unwrap();this.gma();for(c=0;c<a.length;c++)b.Components.Sf(a[c])},_setOption:function(a,c,d){var f=this.options,g=!1,k=-1,l=this.ge,m=l.getPage();switch(a){case "disabled":b.r.warn(da);break;case "orientation":if(c!==y&&c!==fa)throw Error(s+c);g=f.orientation!=c;break;case "maxItemsPerPage":g=f.maxItemsPerPage!=c;break;case "arrowPlacement":if(c!==e&&c!==Y)throw Error(q+c);g=f.arrowPlacement!=c;break;case "arrowVisibility":if(c!==
ba&&c!==w&&c!==x&&c!==h)throw Error(t+c);g=f.arrowVisibility!=c;break;case B:if(f.currentItem!=c&&(k=this.JI(c),0>k||k>=l.getPageCount()))throw Error(r+c);}this._super(a,c,d);switch(a){case B:-1<k&&k!=m&&l.setPage(k)}g&&this.Aa(!1)},Ve:function(){if(!this.rT)this.rT=!0,this.eT(!0),this.rT=!1;else if(!this.Kx){var a=this;this.Kx=setTimeout(function(){a.Kx=null;a.Ve()},0)}},Lb:function(){return this.options.orientation!==fa},Kw:function(){return this.Lb()?this.xf?"right":"left":"top"},gq:function(){return this.Lb()?
"width":"height"},kw:function(){var a=document.createElement("div"),b=a.style;b.position="absolute";b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},yma:function(){var a=this.element,b=this.Lb();a.children().addClass(C).wrap("\x3cdiv class\x3d'"+E+" "+M+"'\x3e\x3c/div\x3e");var c=this.Kw();this.wj=c=a.children().wrapAll("\x3cdiv class\x3d'"+E+" "+I+"' style\x3d'"+c+": 0px;'\x3e\x3c/div\x3e").parent();
var d=this.options;d.arrowVisibility!==w&&d.arrowPlacement===e&&(this.VH=c.wrap("\x3cdiv class\x3d'"+E+" oj-filmstrip-content-container'\x3e\x3c/div\x3e").parent());a.addClass(E);b||a.addClass(R);d.arrowVisibility!==w&&(this.Gk=this.yba(),this.vj=this.kba(),this.PK()&&this.lla())},gma:function(){var a=this.element,b=this.QB();this.Jla();this.Gk&&(this.Np(this.Gk),this.Gk=null);this.vj&&(this.Np(this.vj),this.vj=null);var c=a.children(T+z);c&&c.remove();b.removeClass(C).unwrap().unwrap();this.wj=null;
this.VH&&(b.unwrap(),this.VH=null);a.removeClass(E+" "+R)},lla:function(){this.element.on("mouseenter"+this.JO,function(a){f(a.currentTarget).hasClass("oj-disabled")||f(a.currentTarget).addClass(L)}).on("mouseleave"+this.JO,function(a){f(a.currentTarget).removeClass(L)})},Jla:function(){this.element.off(this.JO)},PK:function(){var a=this.options,b=a.arrowVisibility;return b===x||b===h&&a.arrowPlacement===Y},bga:function(){return 0<this.ge.getPage()},aga:function(){var a=this.ge;return a.getPage()<
a.getPageCount()-1},Mia:function(){if(this.bga()){var a=this.ge;a.setPage(a.getPage()-1)}},kia:function(){if(this.aga()){var a=this.ge;a.setPage(a.getPage()+1)}},bV:function(a,b){this.options.arrowPlacement===e?b.css("visibility",a?"":w):b.parent().css("display",a?"":O)},qma:function(){if(this.options.arrowVisibility!==w){var a=this.ge,b=a.getPage(),a=a.getPageCount();this.bV(0!==b,this.Gk);this.bV(b!==a-1,this.vj)}},yba:function(){var b=this.element,c=this.Lb()?U:ha,d=this.tU(c);this.options.arrowPlacement===
Y?b.append(d):b.prepend(d);var b=a(this.A("labelAccArrowPreviousPage")),e=a(this.A("tipArrowPreviousPage")),c=this.sU(d,c,b,e),f=this;c.on("click",function(){f.Mia()});return c},kba:function(){var b=this.element,c=this.Lb()?F:J,d=this.tU(c);b.append(d);var b=a(this.A("labelAccArrowNextPage")),e=a(this.A("tipArrowNextPage")),c=this.sU(d,c,b,e),f=this;c.on("click",function(){f.kia()});return c},tU:function(a){var b=f(document.createElement("div"));b.addClass(z+" "+a);this.options.arrowPlacement===Y&&
(b.addClass("oj-filmstrip-arrow-container-overlay"),this.PK()&&b.addClass(A));return b},sU:function(a,b,c,d){var f="\x3cdiv class\x3d'"+D+" oj-default oj-enabled "+b+"' role\x3d'button' tabindex\x3d'-1'";a.append(f+("\x3e\x3cspan class\x3d'oj-filmstrip-arrow-icon "+b+" oj-component-icon'\x3e\x3c/span\x3e\x3c/div\x3e"));b=this.element.attr("id");a=a.children(T+D).eq(0);a.uniqueId();f=a.attr("id");c&&a.attr("aria-label",c);d&&a.attr("title",d);a.attr("aria-labelledby",f+" "+b);this._hoverable(a);this.Bn(a);
this.options.arrowPlacement===e&&this.PK()&&a.addClass(A);return a},hJ:function(){return this.wj.find(T+M)},QB:function(){return this.wj.find(T+C)},Un:function(){return this.wj.children(T+G)},ST:function(){var a=this.wj;this.Un().css(v,p).css(ca,p);this.hJ().css(v,p).css(ca,p);a.css(this.gq(),p)},eT:function(a){this.ST();var c=this.options,d=this.Lb(),h=c.maxItemsPerPage,l=1>h,m=this.element,n=this.hJ();if(0>this.kx){var q=this.qW(c.currentItem),q=f(n[q]),r=q.children(T+C);r.css(k,p);b.Components.Rm(r[0]);
this.kx=d?q.width():q.height()}q=d?m.width():m.height();c.arrowVisibility!==w&&c.arrowPlacement===e&&(m=m.children(T+z).eq(0),d=d?m.width():m.height(),q-=2*d);this.Kn=q;l||(d=Math.max(Math.floor(q/this.kx),1),d<h&&(h=d));h=l?Math.max(Math.floor(q/this.kx),1):h;l=q/h;n.css(v,l+aa).css(ca,l+aa);l=Math.ceil(n.length/h);r=this.Un();d=!1;m=this.ge;if(m.getPageCount()!=l||this.Cq!=h||!r||1>r.length){d=!0;if(a)for(var s=0;s<n.length;s++)b.Components.Kg(n[s]);r&&0<r.length&&n.unwrap();for(s=0;s<n.length;s+=
h)n.slice(s,s+h).wrapAll("\x3cdiv class\x3d'"+E+" "+G+"' style\x3d'"+k+": "+O+";' "+g+"\x3d'true'\x3e\x3c/div\x3e");if(a)for(s=0;s<n.length;s++)b.Components.Sf(n[s])}r=this.Un();r.css(v,q+aa).css(ca,q+aa);a=this.VH;this.wj.css(this.gq(),q);a&&a.css(this.gq(),q);a=0;if(c.currentItem||0===c.currentItem)a=this.JI(c.currentItem,h);m.getPageCount()!=l||this.Cq!=h||m.getPage()!=a?m.setPage(a,{pageSize:h}):d&&(c=m.getPage(),this.ZJ({previousPage:c,page:c}))},ZJ:function(a){var b=a.page,c=a.previousPage;
a=this.wj;var d=this.Un(),e=this.ge.La,g=0>c||c==b||this.Cq!=e;this.Cq=e;e=null;g||(e=f(d[c]));var h=this.Kw(),k=f(d[b]),l=k.is(u);l&&this.HM(k);var m=this.Ms;-1<c&&!g&&(m=!0,a.css(this.gq(),2*this.Kn),b<c&&l&&a.css(h,-this.Kn+aa),b>c?(e.addClass(P),k.addClass(H)):(e.addClass(W),k.addClass(Q)));if(m){var n=this,p=this.Ms;p&&0>c&&d.filter(S).addClass(N);setTimeout(function(){n.DV(b,c,g,p)},25)}else this.DV(b,c,g)},DV:function(a,b,e,g){var h=this.wj;e||(this.sT=!0,h.on("transitionend"+this.eventNamespace+
" webkitTransitionEnd"+this.eventNamespace,this.zk));e?this.vq():(e=this.Un(),g&&d(e),-1<b?(g=a>b,b=f(e[b]),a=f(e[a]),b.addClass(N),a.addClass(N),g?(b.removeClass(P),a.removeClass(H),b.addClass(V),a.addClass(K)):(b.removeClass(W),a.removeClass(Q),b.addClass(X),a.addClass(Z))):g&&(a=e.filter(S),c(a,"translate3d(0, 0, 0)")))},vq:function(){this.sT=!1;var a=this.wj,c=this.Kw();a.off(this.eventNamespace).css(this.gq(),this.Kn).css(c,"0px");c=null;if(b.td.YD(a[0])||this.vj&&b.td.YD(this.vj[0])||this.Gk&&
b.td.YD(this.Gk[0]))c=document.activeElement;for(var a=this.ge.getPage(),e=this.Un(),g=0;g<e.length;g++)g!=a&&this.LX(f(e[g]));e.removeClass(N+" "+V+" "+K+" "+X+" "+Z);d(e);this.qma();c&&f(c).is(u)&&(c=this.element,(e=b.td.X2(e[a]))?b.td.Fy(e):b.td.Fy(c[0]));this.JI(this.options.currentItem)!=a&&(a=this.gW(a),this.option(B,a,{_context:{Ic:!0}}))},qW:function(a){var c=-1,d=this.QB();if("number"===typeof a)0<=a&&a<d.length&&(c=a);else if("string"===typeof a&&b.v.yE(a))for(var e=0;e<d.length;e++){var f=
d[e].id;if(f&&0<f.length&&f===a){c=e;break}}return c},JI:function(a,b){var c=this.qW(a),d=-1;-1<c&&(void 0===b&&(b=this.Cq),d=Math.floor(c/b));return d},gW:function(a,b,c){var d=this.ge;void 0===b&&(b=d.getPageCount());return 0<=a&&a<b&&(b=this.QB(),void 0===c&&(c=this.Cq),a*=c,a<b.length)?(c=b[a].id)&&0<c.length?c:a:-1},LX:function(a){b.Components.gp(a[0]);a.css(k,O).attr(g,"true");a.find(T+C).css(k,O)},HM:function(a){a.css(k,p).removeAttr(g);a.find(T+C).css(k,p);b.Components.Rm(a[0])},h$:function(){this.element.on("keydown"+
this.c4,this.tX)},Mja:function(){this.element.off(this.c4)},j$:function(){this.element.on("mousedown"+this.HE,this.uX).on("mousemove"+this.HE,this.vX).on("mouseup"+this.HE,this.xX)},Oja:function(){this.element.off(this.HE)},n$:function(){this.element.on("touchstart"+this.sz,this.FX).on("touchmove"+this.sz,this.EX).on("touchend"+this.sz,this.fK).on("touchcancel"+this.sz,this.fK)},Vja:function(){this.element.off(this.sz)},tq:function(a){var b=this.ge,c=b.getPage(),d=-1;switch(a.keyCode){case f.ui.keyCode.RIGHT:d=
this.xf?c-1:c+1;break;case f.ui.keyCode.LEFT:d=this.xf?c+1:c-1;break;case f.ui.keyCode.DOWN:d=c+1;break;case f.ui.keyCode.UP:d=c-1;break;case f.ui.keyCode.HOME:d=0;break;case f.ui.keyCode.END:d=b.getPageCount()-1;break;default:return}-1<d&&d<b.getPageCount()&&b.setPage(d);a.preventDefault()},Ffa:function(a){this.nV(a.originalEvent)},Gfa:function(a){this.mV(a,a.originalEvent)},Ifa:function(){this.lV()},hK:function(a){a=a.originalEvent.touches;1===a.length&&this.nV(a[0])},gK:function(a){this.mV(a,a.originalEvent.touches[0]);
(this.gj||this.Zt)&&a.preventDefault()},eK:function(){this.lV()},nV:function(a){1<this.ge.getPageCount()&&!this.sT&&(this.gj=!0,this.Ms=!1,this.yD=this.Lb()?a.pageX:a.pageY)},sga:function(a){this.yD=this.Lb()?a.pageX:a.pageY;a=this.Kw();var b=this.wj,c=this.ge,d=this.Un(),e=1;0<c.getPage()&&(this.HM(f(d[c.getPage()-1])),b.css(a,-this.Kn+aa),e++);c.getPage()<c.getPageCount()-1&&(this.HM(f(d[c.getPage()+1])),e++);1<e&&b.css(this.gq(),e*this.Kn);this.sM=parseInt(b.css(a),10)},mV:function(a,b){if(this.gj){var d=
this.Lb(),e=(d?b.pageX:b.pageY)-this.yD;if(this.Ms){var g=d&&this.xf?0<e:0>e,h=this.ge,k=h.getPage();if(g&&k<h.getPageCount()-1||!g&&0<k){var p=this.element[0],q=Math.min(m*(d?p.offsetWidth:p.offsetHeight),n),r=this.Kw(),s=this.wj,p=this.Un();Math.abs(e)>=q?(d=g?k+1:k-1,this.gW(d),k=g?k-1:k+1,-1<k&&k<h.getPageCount()&&this.LX(f(p[k])),g&&-1<k&&(p=parseInt(s.css(r),10),s.css(r,p+this.Kn+aa)),s.css(this.gq(),2*this.Kn),this.gj=!1,h.setPage(d)):(h=d&&this.xf?-e:e,h=d?"translate3d("+h+"px, 0, 0)":"translate3d(0, "+
h+"px, 0)",c(p.filter(S),h));this.Zt=!0}this.Zt&&(a.preventDefault(),a.stopPropagation())}else Math.abs(e)>l&&(this.sga(b),this.Ms=!0)}},lV:function(){if(this.gj&&this.Ms){var a=this.ge.getPage();this.ZJ({previousPage:a,page:a})}this.Zt=this.Ms=this.gj=!1},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-filmstrip-start-arrow"===a?this.widget().find(T+D+T+U)[0]:"oj-filmstrip-end-arrow"===a?this.widget().find(T+D+T+F)[0]:"oj-filmstrip-top-arrow"===
a?this.widget().find(T+D+T+ha)[0]:"oj-filmstrip-bottom-arrow"===a?this.widget().find(T+D+T+J)[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-filmstrip-start-arrow"}),c=this.getNodeBySubId({subId:"oj-filmstrip-end-arrow"}),d=this.getNodeBySubId({subId:"oj-filmstrip-top-arrow"}),e=this.getNodeBySubId({subId:"oj-filmstrip-bottom-arrow"}),f=this.element[0];a&&a!=f;){if(a===b)return{subId:"oj-filmstrip-start-arrow"};if(a===c)return{subId:"oj-filmstrip-end-arrow"};if(a===d)return{subId:"oj-filmstrip-top-arrow"};
if(a===e)return{subId:"oj-filmstrip-bottom-arrow"};a=a.parentElement}return null}});var e="adjacent",g="aria-hidden",h="auto",k="display",l=3,m=.33,n=100,p="",r="JET FilmStrip: Value of 'currentItem' option not found: ",s="JET FilmStrip: Unsupported value set as 'orientation' option: ",q="Unsupported value set as 'arrowPlacement' option: ",t="Unsupported value set as 'arrowVisibility' option: ",v="flex-basis",w="hidden",u=":hidden",y="horizontal",x="hover",B="currentItem",O="none",J="oj-bottom",F=
"oj-end",D="oj-filmstrip-arrow",z="oj-filmstrip-arrow-container",A="oj-filmstrip-arrow-transition",E="oj-filmstrip-container",L="oj-filmstrip-hover",C="oj-filmstrip-item",M="oj-filmstrip-item-container",G="oj-filmstrip-page",I="oj-filmstrip-pages-container",N="oj-filmstrip-transition",H="oj-filmstrip-transition-next-newpage-from",P="oj-filmstrip-transition-next-oldpage-from",Q="oj-filmstrip-transition-prev-newpage-from",W="oj-filmstrip-transition-prev-oldpage-from",K="oj-filmstrip-transition-next-newpage-to",
V="oj-filmstrip-transition-next-oldpage-to",Z="oj-filmstrip-transition-prev-newpage-to",X="oj-filmstrip-transition-prev-oldpage-to",R="oj-filmstrip-vertical",U="oj-start",ha="oj-top",Y="overlay",T=".",aa="px",fa="vertical",ba="visible",S=":visible",ca="-webkit-flex-basis",da="JET FilmStrip: 'disabled' option not supported"})()});