/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojbutton"],function(b,f){b.ya("oj.ojInputNumber",f.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:b.pa.lm(b.Uj.CONVERTER_TYPE_NUMBER).createConverter(),max:null,min:null,placeholder:void 0,rawValue:void 0,readOnly:!1,step:1,value:null},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputnumber-up"===c&&(b=this.widget().find(".oj-inputnumber-up")[0]),
"oj-inputnumber-down"===c&&(b=this.widget().find(".oj-inputnumber-down")[0]),"oj-inputnumber-input"===c&&(b=this.widget().find(".oj-inputnumber-input")[0]));return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a===this.widget().find(".oj-inputnumber-up")[0]?b={subId:"oj-inputnumber-up"}:a===this.widget().find(".oj-inputnumber-down")[0]?b={subId:"oj-inputnumber-down"}:a===this.widget().find(".oj-inputnumber-input")[0]&&(b={subId:"oj-inputnumber-input"}));return b||this._superApply(arguments)},
refresh:function(){this._super();this.Aa()},stepDown:function(a){this.M0(a,!1)},stepUp:function(a){this.M0(a,!0)},widget:function(){return this.Jr},Yd:function(a,d){var c=this.options,e=this;this._superApply(arguments);b.ve.al([{W:"disabled",yc:!0},{W:"placeholder"},{W:"value"},{W:"readonly",option:"readOnly",yc:!0},{W:"required",Ze:!0,yc:!0},{W:"title"},{W:"min"},{W:"max"},{W:"step"}],d,this,function(a){for(var b=["value","step","min","max"],d=0;d<b.length;d++){var f=b[d],m=f in a?a[f]:c[f];null!=
m&&(a[f]="step"===f?e.Ax(m):e.Fk(f,m))}});if(void 0===c.value)throw Error("ojInputNumber has no value");if(null!=c.min&&null!=c.max&&c.max<c.min)throw Error("ojInputNumber's max must not be less than min");},_ComponentCreate:function(){var a=this.element;this._super();this.Dw();a.removeAttr("pattern");this.fY={};this.Aa();this._on(this.Ml);this._focusable(this.Jr);this.Bn(this.Jr)},LQ:function(a,b,c){this._superApply(arguments);switch(a){case "min":case "max":this.Wg(a,this.options[a])}},_setOption:function(a,
b,c){var e;e="value"===a||"max"===a||"min"===a?this.Fk(a,b):"step"===a?this.Ax(b):b;this._super(a,e,c);if("max"===a||"min"===a)this.zU(),this.fs();"disabled"===a&&this.element.prop("disabled",!!b);"readOnly"===a&&(this.element.prop("readonly",!!b),this.UC("readOnly",this.options.readOnly),this.XZ("readOnly",this.options.readOnly))},_destroy:function(){var a=this._super();this.uz.ojButton("destroy");this.Cy.ojButton("destroy");this.uz.remove();this.Cy.remove();this.Cy=this.uz=null;b.v.unwrap(this.element,
this.Jr);clearTimeout(this.bd);return a},Wg:function(a,b,c){this._superApply(arguments);var e="value"===a||"max"===a||"min"===a,f=e||"disabled"===a,h;f&&(h=this.IB());e&&this.pL(h);"converter"===a&&this.RZ(h);f&&this.LM(h)},Uc:function(){return this.options.converter?this._superApply(arguments):f.oj.ojInputNumber.prototype.options.converter},Lv:function(){var a=this._superApply(arguments);null==this.options.min&&null==this.options.max||this.zU();return f.extend(this.fY,a)},_GetDefaultStyleClass:function(){return"oj-inputnumber"},
Ml:{input:function(a){this.zn(this.element.val(),a)},keydown:function(a){a.keyCode===f.ui.keyCode.ENTER?(this.wT(a),a.preventDefault()):this.Kh()&&this.Dq(a)&&a.preventDefault()},keyup:function(a){this.dy(a)},focus:function(){this.Lm=this.element.val()},blur:function(a){this.dN?delete this.dN:this.wT(a)},"mousedown .oj-inputnumber-button":function(a){function b(){this.element[0]!==this.document[0].activeElement&&(this.element.focus(),this.Lm=c,this._delay(function(){this.Lm=c}))}var c;c=this.element[0]===
this.document[0].activeElement?this.Lm:this.element.val();a.preventDefault();b.call(this);this.dN=!0;this._delay(function(){delete this.dN;b.call(this)});this.Kh();this.Ux(null,f(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a)},"mouseup .oj-inputnumber-button":function(a){this.dy(a)},"mouseenter .oj-inputnumber-button":function(a){f(a.currentTarget).hasClass("oj-active")&&(this.Kh(),this.Ux(null,f(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseleave .oj-inputnumber-button":function(a){this.dy(a)}},
xa:{L9:"tooltipDecrement",M9:"tooltipIncrement"},xn:{readOnly:"oj-read-only"},Aa:function(){var a=this.A(this.xa.M9),b=this.A(this.xa.L9),c=this.IB();this.uz.ojButton({label:a});this.Cy.ojButton({label:b});this.pL(c);this.LM(c);"boolean"===typeof this.options.readOnly&&this.element.prop("readonly",this.options.readOnly);this.UC("readOnly",this.options.readOnly);this.XZ("readOnly",this.options.readOnly)},lba:function(){this.uz=this.Jr.find(".oj-inputnumber-up").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-up-icon"}});
this.Cy=this.Jr.find(".oj-inputnumber-down").ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-down-icon"}})},Dw:function(){var a=this.element,b=this.Jr=a.addClass("oj-inputnumber-input").wrap("\x3cspan class\x3d'oj-inputnumber-wrapper'\x3e\x3c/span\x3e").parent().append("\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/button\x3e").wrap("\x3cdiv class\x3d'oj-inputnumber oj-component'\x3e\x3c/div\x3e").parent();
this.saveType=a.prop("type");a.attr("type","text");b.find(".oj-inputnumber-button").attr("tabIndex","-1").attr("aria-hidden",!0);this.lba()},Dq:function(a){var b=f.ui.keyCode;switch(a.keyCode){case b.UP:return this.Ux(null,1,a),!0;case b.DOWN:return this.Ux(null,-1,a),!0}return!1},Jra:function(){return"\x3cspan class\x3d'oj-inputnumber-wrapper'\x3e\x3c/span\x3e"},fra:function(){return"\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/button\x3e"},
Kh:function(){return this.y5=!0},Ux:function(a,b,c){a=a||500;clearTimeout(this.bd);this.bd=this._delay(function(){this.Ux(40,b,c)},a);this.gM(b*this.options.step,c)},gM:function(a,b){var c=this.IB(),c=this.p$(c,a);this.hc(c,b,this.Xv.f7)},Gia:function(){var a=this.options,b=a.min,a=this.zZ(a.step);null!=b&&(a=Math.max(a,this.zZ(b)));return a},zZ:function(a){a=a.toString();var b=a.indexOf(".");return-1===b?0:a.length-b-1},p$:function(a,b){var c,e,f=this.options,h=f.min,k=f.step,l=f.max,f=this.Gia();
e=null!=h?h:0;c=a-e;var m=Math.round(c/k)*k,m=parseFloat(m.toFixed(f));m!==c?(c=0>b?Math.ceil(c/k)*k:Math.floor(c/k)*k,c=e+c+b):c=a+b;c=parseFloat(c.toFixed(f));return null!=h&&c<h?h:null!=l&&c>l?(h=Math.floor((l-e)/k)*k+e,h=parseFloat(h.toFixed(f))):c},dy:function(){this.y5&&(clearTimeout(this.bd),this.y5=!1)},LM:function(a){var b=this.options,c=b.min,e=b.max;if(this.Jr){var f=this.Cy,h=this.uz;b.disabled||void 0===a?(f.ojButton("disable"),h.ojButton("disable")):null!=e&&a>=e?(f.ojButton("enable"),
h.ojButton("disable")):(null!=c&&a<=c?f.ojButton("disable"):f.ojButton("enable"),h.ojButton("enable"))}},IB:function(){var a,b;try{b=this.hg()||0,a=this.PC(b)}catch(c){a=void 0}return a},wT:function(a){var b=this.element.val();this.dy();var c=this.IB();this.pL(c);this.LM(c);this.hc(b,a)},zU:function(){var a=this.options,d=a.min,c=a.max,e=(a=a.translations)?a.numberRange||{}:{},f,h,k,l,m,n,p,a=e.hint||{},r=e.messageDetail||{},e=e.messageSummary||{};null!==a&&(f=a.min||null,h=a.max||null,k=a.inRange||
null);null!==r&&(l=r.rangeOverflow||null,m=r.rangeUnderflow||null);null!==e&&(n=e.rangeOverflow||null,p=e.rangeUnderflow||null);d={min:null!=d?d:void 0,max:null!=c?c:void 0,hint:{min:f||null,max:h||null,inRange:k||null},messageDetail:{rangeOverflow:l||null,rangeUnderflow:m||null},messageSummary:{rangeOverflow:n||null,rangeUnderflow:p||null},converter:this.Uc()};this.fY[b.ed.VALIDATOR_TYPE_NUMBERRANGE]=b.pa.Lr(b.ed.VALIDATOR_TYPE_NUMBERRANGE).createValidator(d)},Fk:function(a,b){var c;c=null!==b?+b:
b;if(isNaN(c))throw Error("ojInputNumber's "+a+" option is not a number");return c},Ax:function(a){if(null===a)return 1;a=this.Fk("step",a);if(0>=a)throw Error("Invalid step for ojInputNumber; step must be \x3e 0");if(null===a||0>=a)a=1;return a},UC:function(a,b){-1!=Object.keys(this.xn).indexOf(a)&&this.widget().toggleClass(this.xn[a],!!b)},XZ:function(a,b){b?this.element.removeAttr("role"):this.element.attr("role","spinbutton")},pL:function(a){this.element.attr({"aria-valuemin":this.options.min,
"aria-valuemax":this.options.max,"aria-valuenow":a});this.RZ(a)},RZ:function(a){var b=this.element,c=b.val();this.Iv("value",""+a,c)||b.attr({"aria-valuetext":c})},M0:function(a,b){this.Kh();b?this.gM((a||1)*this.options.step):this.gM((a||1)*-this.options.step);this.dy()}})});