/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(b,f){b.ya("oj.inputBase",f.oj.editableValue,{version:"1.0.0",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"",_WIDGET_CLASS_NAMES:"",_ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES:"",_GET_INIT_OPTIONS_PROPS:[{W:"disabled",yc:!0},{W:"pattern"},{W:"placeholder"},{W:"value"},{W:"readonly",option:"readOnly",yc:!0},{W:"required",Ze:!0,yc:!0},{W:"title"}],_INPUT_HELPER_KEY:"",NQ:"blur",JR:"keydown",yR:"input",iR:"drop",options:{converter:void 0,placeholder:void 0,
rawValue:void 0,readOnly:!1},Tv:function(a){var b=this._superApply(arguments);this.Pia();return b},Yd:function(a,d){this._super(a,d);b.ve.al(this._GET_INIT_OPTIONS_PROPS,d,this)},_ComponentCreate:function(){var a=this.element,b=this._superApply(arguments),c=this.sR(a),e=this.options.readOnly;this.zj="rtl"===this.ec();"boolean"===typeof e&&this.element.prop("readonly",e);this.Jv()&&(this.Ama(),this.jR()&&this.zma());"pattern"in c&&a.removeAttr("pattern");this.jI={};this.jd=null;return b},mf:function(){var a=
this._superApply(arguments),b=this;this._CLASS_NAMES&&this.element.addClass(this._CLASS_NAMES);this.pT();this.UF();f.each(["disabled","readOnly"],function(a,e){b.options[e]&&b.CZ(e,b.options[e])});return a},CZ:function(a,b){"disabled"===a&&this.element.prop("disabled",b);"readOnly"===a&&(this.element.prop("readonly",b),this.UC("readOnly",b));"disabled"!==a&&"readOnly"!==a||this.pT()},_setOption:function(a,d){var c=this._superApply(arguments);"disabled"!==a&&"readOnly"!==a||this.CZ(a,d);"pattern"===
a&&(this.jI[b.ed.VALIDATOR_TYPE_REGEXP]=this.nW(),this.fs());return c},_destroy:function(){var a=this._superApply(arguments);this.element.off("blur drop keydown input");this.uK&&this.uK.remove();this.Jv()&&(this.jR()?b.v.unwrap(this.element,this.ou):b.v.unwrap(this.element));return a},pT:function(){if(!this.options.readOnly&&!this.options.disabled){this.jd={};var a=f.proxy(this.WK,this),b=f.proxy(this.MC,this),c=f.proxy(this.nia,this),e=function(){this.focus()};this.element.on("blur",a);this.element.on("keydown",
b);this.element.on("input",c);this.element.on("drop",e);this.jd[this.NQ]=a;this.jd[this.JR]=b;this.jd[this.yR]=c;this.jd[this.iR]=e}else if(this.jd)for(a=[this.NQ,this.JR,this.yR,this.iR],b=0,c=a.length;b<c;b++)this.jd[a[b]]&&(this.element.off(a[b],this.jd[a[b]]),delete this.jd[a[b]])},xn:{readOnly:"oj-read-only"},Pia:function(){for(var a=this._ATTR_CHECK,b=0,c=a.length;b<c;b++){var e=a[b].attr;"setMandatory"in a[b]&&this.element.attr(e,a[b].setMandatory)}},WK:function(a){this.hc(this.hg(),a)},MC:function(a){a.keyCode===
f.ui.keyCode.ENTER&&this.hc(this.hg(),a)},nia:function(a){this.zn(this.Xd().val(),a)},Jv:function(){return this._WIDGET_CLASS_NAMES},jR:function(){return this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES},Ama:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._WIDGET_CLASS_NAMES));this.ou=this.element.parent()},zma:function(){f(this.element).wrap(f("\x3cdiv\x3e").addClass(this._ELEMENT_TRIGGER_WRAPPER_CLASS_NAMES))},UF:function(){if(this._INPUT_HELPER_KEY&&this.Jv()){var a=this.element.attr("aria-describedby")||
"",b=this.nn(this._INPUT_HELPER_KEY);this.element.attr("aria-describedby",a+(" "+b));this.uK=f("\x3cdiv class\x3d'oj-helper-hidden-accessible' id\x3d'"+b+"'\x3e"+this.ck(this.A(this._INPUT_HELPER_KEY))+"\x3c/div\x3e");this.VF().append(this.uK)}},ck:function(a){return f("\x3cspan\x3e"+a+"\x3c/span\x3e").text()},VF:function(){return this.widget()},Lv:function(){var a=this._superApply(arguments);this.options.pattern&&(this.jI[b.ed.VALIDATOR_TYPE_REGEXP]=this.nW());return f.extend(this.jI,a)},UC:function(a,
b){-1!=Object.keys(this.xn).indexOf(a)&&this.widget().toggleClass(this.xn[a],!!b)},nW:function(){if(!this.options.pattern)return null;var a={pattern:this.options.pattern,label:this.jJ()};f.extend(a,this.options.translations.regexp||{});return b.pa.Lr(b.ed.VALIDATOR_TYPE_REGEXP).createValidator(a)},nn:function(a){return this.uuid+"_"+a},Uqa:function(){return this.zj},refresh:function(){var a=this._superApply(arguments);this.zj="rtl"===this.ec();return a},getNodeBySubId:function(a){return this._super(a)},
widget:function(){return this.Jv()?this.ou:this.element}},!0);b.ya("oj.ojInputPassword",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"password"}],_CLASS_NAMES:"oj-inputpassword-input",_WIDGET_CLASS_NAMES:"oj-inputpassword oj-form-control oj-component",options:{pattern:""},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputpassword-input"===c&&(b=this.element?this.element[0]:null));return b||
null},_GetDefaultStyleClass:function(){return"oj-inputpassword"}});b.ya("oj.ojTextArea",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3ctextarea\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[],_CLASS_NAMES:"oj-textarea-input",_WIDGET_CLASS_NAMES:"oj-textarea oj-form-control oj-component",options:{pattern:""},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-textarea-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-textarea"},
Wz:function(){return"oj-inputBase"}});b.ya("oj.ojInputText",f.oj.inputBase,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",_ATTR_CHECK:[{attr:"type",setMandatory:"text"}],_CLASS_NAMES:"oj-inputtext-input",_WIDGET_CLASS_NAMES:"oj-inputtext oj-form-control oj-component",options:{pattern:""},getNodeBySubId:function(a){var b=this._superApply(arguments),c;b||(c=a.subId,"oj-inputtext-input"===c&&(b=this.element?this.element[0]:null));return b||null},_GetDefaultStyleClass:function(){return"oj-inputtext"},
Wz:function(){return"oj-inputBase"}})});