/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","knockout"],function(b,f,a){function d(){this.Init()}function c(a,b){var c={};c.value=b.value;return c}function e(a,b){var c={},d=b.optionMetadata;d&&"shouldWrite"===d.writeback&&(c[b.option]=b.value);return c}function g(b,c){return function(d){var e,g;e=d.parentElement;g=b.createChildContext(d.data,null,function(a){a.$optionContext=d});a.renderTemplate(c,g,null,e);return null}}function h(a,b,c){return"optionTemplate"===a&&null!==b?{optionRenderer:g(c,String(b))}:null}
function k(b,c){return function(d){var e=b.createChildContext(d.data);a.renderTemplate(c,e,null,d.parentElement);return null}}function l(a,b,c){if("areaLayers"===a){for(a=0;a<b.length;a++){var d=b[a].areaDataLayer;if(d){var e=d.template;null!=e&&(d._templateRenderer=k(c,e))}}return{areaLayers:b}}if("pointDataLayers"===a){for(a=0;a<b.length;a++)e=b[a].template,null!=e&&(b[a]._templateRenderer=k(c,e));return{pointDataLayers:b}}return null}function m(a,b){this.Init(a,b)}function n(b,c){return function(d){var e=
b.createChildContext(d.data);a.renderTemplate(c,e,null,d.parentElement);return null}}function p(a,b,c,d){if(null==c)return null;var e=r(c);null!=e&&(c=s(a,e,d,b,c));return c}function r(a){a=Object.keys(a);for(var c=-0;c<a.length;c++){var d=a[c];if(b.ia.bha(d))return d}return null}function s(a,c,d,e,g){a=v(a,c,d,e);d=a.Uma;if(null==d)return g;var f={};w(d,function(a,b){f[a]=b});g=b.oc.$e({},g);g[c]=q(e,f,a.Wma);return g}function q(a,c,d){function e(){var d={};Object.keys(c).forEach(function(e){var g=
b.ia.pU(c[e]).bind(null,a);Object.defineProperty(d,e,{get:g,enumerable:!0})});Object.defineProperty(d,b.ia.YR,{value:c});return d}e.toString=function(){return d};return e}function t(a,b,c){var d=b.getBindingsString;if(d)return d.call(b,a,c);switch(a.nodeType){case 1:return a.getAttribute("data-bind");case 8:return(a=a.nodeValue.match(/^\s*ko(?:\s+([\s\S]+))?\s*$/))?a[1]:null}return null}function v(b,c,d,e){var g=null;b=t(b,d,e);b=a.jsonExpressionRewriting.parseObjectLiteral(b);var f=null;w(b,function(a,
b){return a===c?(f=b,!0):!1});null!=f&&0===f.indexOf("{")&&(g=a.jsonExpressionRewriting.parseObjectLiteral(f));return{Uma:g,Wma:f}}function w(a,b){for(var c=0;c<a.length;c++){var d=a[c],e=d.key,d=d.value;if(null!=e&&null!=d&&b(e.trim(),d.trim()))break}}function u(a,b,c,d){var e=a[c];null!=e&&(b[c]=function(){var b=e.apply(a,arguments);if(null!=d){var c=Array.prototype.slice.call(arguments);c.push(b,a);b=d.apply(null,c)}return b})}function y(b,c){return function(d){var e,g;e=d.parentElement;g=b.createChildContext(d.data,
null,function(a){a.$key=d.key;a.$metadata=d.metadata;a.$headerContext=d});a.renderTemplate(c,g,null,e);return null}}function x(b,c){return function(d){var e,g;e=d.parentElement;g=b.createChildContext(d.data,null,function(a){a.$keys=d.keys;a.$metadata=d.metadata;a.$cellContext=d});a.renderTemplate(c,g,null,e);return null}}function B(b,c,d){var e={};(function(c,d){e=function(e){var g=null,f=null;"header"==d?(g=b.extend({$columnIndex:e.columnIndex,$headerContext:e.headerContext,$data:e.data}),f=e.headerContext.parentElement):
"cell"==d&&(g=b.createChildContext(e.row,null,function(a){a.$columnIndex=e.columnIndex;a.$cellContext=e.cellContext}),f=e.cellContext.parentElement);"footer"==d&&(g=b.extend({$columnIndex:e.columnIndex,$footerContext:e.footerContext}),f=e.footerContext.parentElement);a.renderTemplate(c,g,null,f,"replaceNode")}})(d,c);return e}function O(b,c){return function(d){var e=b.createChildContext(d.row,null,function(a){a.$rowContext=d.rowContext});a.renderTemplate(c,e,null,d.rowContext.parentElement,"replaceNode")}}
function J(b,c){return function(d){var e,g;e=d.parentElement;g=b.createChildContext(d.data,null,function(a){a.$itemContext=d});a.renderTemplate(c,g,null,e,"replaceNode");return null}}function F(a,b,c){return"item"==a?(a=b.template,null!=a&&(b.renderer=J(c,a)),{item:b}):null}b.b.ga(d,b.b,"ComponentBinding.GlobalChangeQueue");d.prototype.Init=function(){d.q.Init.call(this);this.AD=[];this.Ix=[]};d.prototype.Gpa=function(a){-1===this.AD.indexOf(a)&&(this.AD.push(a),this.gB||(this.gB=setTimeout(b.b.e2(this,
this.RU),1)))};d.prototype.oN=function(){this.gB&&clearTimeout(this.gB);this.RU()};d.prototype.RU=function(){var a;this.gB=null;var b=this.AD;this.AD=[];for(a=0;a<b.length;a++){var c=b[a];this.Ix.push({rP:c,Ho:c.Tna()})}for(;0<this.Ix.length;)a=this.Ix.shift(),a.rP.Kma(a.Ho)};b.ia=function(a,b){this.Init(a,b)};o_("ComponentBinding",b.ia,b);b.b.ga(b.ia,b.b,"oj.ComponentBinding");b.ia.create=function(c,d){if(null==c)throw"Binding name is required!";var e=new b.ia(c,d),g=a.bindingHandlers,f,h=Array.isArray(c)?
c:[c];for(f=0;f<h.length;f++){var q=h[f];b.ia.mS.push(q);g[q]=e}return e};o_("ComponentBinding.create",b.ia.create,b);b.ia.oh=function(){return b.ia.f8};o_("ComponentBinding.getDefaultInstance",b.ia.oh,b);b.ia.prototype.sh=function(a){var b=a["for"],b=null==b?"@global":b,c=this.GC[b]||[];c.push(a);this.GC[b]=c};b.b.g("ComponentBinding.prototype.setupManagedAttributes",{sh:b.ia.prototype.sh});b.ia.oN=function(){b.ia.MT.oN()};o_("ComponentBinding.deliverChanges",b.ia.oN,b);b.ia.prototype.Init=function(a,
c){b.ia.q.Init.call(this);"string"===typeof c&&(c={componentName:c});this.kH=c||{};Array.isArray(a);this.init=this._init.bind(this);this.update=this.xo.bind(this);this.GC={}};b.ia.prototype._init=function(b,c,d,e,g){a.applyBindingsToDescendants(g,b);return{controlsDescendantBindings:!0}};b.ia.prototype.xo=function(c,d,e,g,h){function q(a){p.forEach(function(a){a.dispose()});p=[];a&&t&&(t("destroy"),t=null);r&&(r.Bu(),r=null);n.off(b.ia.gG)}function k(a,d,g){if(null!=a){var f=n[a];if("function"!==
typeof f)b.r.error("Component %s is not found",a);else{f=f.bind(n);r=new m(f,b.ia.MT);var q=Object.keys(g).filter(function(a){return!(null==a||a===d)});t=this.nga(c,{Q:f,zy:r,Z1:a,pz:q,fna:p,jp:function(){return g},su:e,$q:h,Fna:function(){t=null}})}}}var p=[],l=0,t,r,n=f(c);a.ignoreDependencies(function(){a.computed(function(){var c=a.utils.unwrapObservable(d());"object"!==typeof c&&b.r.error("ojComponent binding should evaluate to an object");var e=this.kH.componentName,g,f=!1;if(null==e&null!=
c){for(var h=[b.ia.s7,"role"],p=0;!f&&p<h.length;p++)g=h[p],g in c&&(f=!0,e=c[g]);f||b.r.error("component attribute is required for the ojComponent binding");e=a.utils.unwrapObservable(e)}0==l?l=1:a.ignoreDependencies(q,this,[!0]);a.ignoreDependencies(k,this,[e,g,c])},this,{disposeWhenNodeIsRemoved:c})},this);a.utils.domNodeDisposal.addDisposeCallback(c,q.bind(this,[!1]))};b.ia.prototype.nga=function(c,d){function e(){var a=this.Wia,f=b.ia.Tla(d.jp()[a]);if(0===h){var k=t[a];null!=k?(q[a]=k,k=k.zm,
null!=k&&(a=k(a,f,c,p,d.jp,d.su,d.$q)||{},b.oc.$e(n,a))):n[a]=f}else if(!g)if(null!=t[a]){if(k=t[a].update,null!=k)for(a=k(a,f,c,p,d.jp,d.su,d.$q)||{},f=Object.keys(a),k=0;k<f.length;k++){var m=f[k];d.zy.A1(m,a[m])}}else d.zy.A1(a,f)}var g=!1,h=0,q={},k=f(c),p=d.Q,m=d.Z1,l=this;k.on("ojdestroy"+b.ia.gG,function(a){a.target&&a.target==c&&(d.Fna(),(a=l.kH.beforeDestroy)&&a(c,p,d.jp,d.su,d.$q),b.ia.SU(!1,q,c,p,d.jp,d.su,d.$q),g=!0,d.zy.Bu())});var t=b.ia.F_(this.GC,d.pz,m),r=b.ia.oh();this!==r&&(m=r.Tda(d.pz,
m),b.oc.$e(m,t),t=m);for(var n={},m=0;m<d.pz.length;m++)d.fna.push(a.computed(e,{Wia:d.pz[m]}));h=1;b.ia.wja(k,d);k=b.ia.sV(n);m=Object.keys(k);m.forEach(function(a){delete n[a]});p(n);for(r=0;r<m.length;r++){var s=m[r];p("option",s,k[s])}(k=this.kH.afterCreate)&&k(c,p,d.jp,d.su,d.$q);b.ia.SU(!0,q,c,p,d.jp,d.su,d.$q);n=null;return p};b.ia.pU=function(a){return new Function("$context","with($context){with($data||{}){return "+a+";}}")};b.ia.prototype.Tda=function(a,c){return b.ia.F_(this.GC,a,c)};b.ia.F_=
function(a,b,c){function d(b,c){var e=a[b];if(null!=e)for(var f=e.length-1;0<=f;f--){var h=e[f];null!=h.attributes&&g.push(h);if(c&&(h=h.use,null!=h))for(var h=Array.isArray(h)?h:[h],q=0;q<h.length;q++)d(h[q],!0)}}var e={},g=[];d(c,!0);c=f.oj[c];if(null!=c)for(c=Object.getPrototypeOf(c.prototype);null!=c&&"oj"===c.namespace;)d(c.widgetName,!0),c=Object.getPrototypeOf(c);d("@global",!1);if(0<g.length)for(c=0;c<b.length;c++)for(var h=b[c],q=0;q<g.length;q++){var k=g[q];if(0<=k.attributes.indexOf(h)){e[h]=
{zm:k.init,update:k.update,pu:k.afterCreate,Vma:k.beforeDestroy};break}}return e};b.ia.gG=".oj_ko";b.ia.wja=function(a,d){for(var g={"^slider$":[{event:"slidechange",getter:c}],"^oj*":[{event:"ojoptionchange",getter:e}]},f={},h=Object.keys(g),q=0;q<h.length;q++){var k=h[q];if(d.Z1.match(k)){g=g[k];for(h=0;h<g.length;h++)q=g[h],a.on(q.event+b.ia.gG,{noa:q.getter},function(c,e){if(c.target===a[0]){var g=c.data.noa(c,e),h=d.jp(),q;for(q in g){d.zy.jqa(q);try{if(0<=d.pz.indexOf(q)){var k=h[b.ia.YR];b.ia.Cma(q,
h[q],g[q],null==k?null:k[q],d.$q,f)}}finally{d.zy.Ppa(q)}}}});break}}};b.ia.nea=function(a){var b=["true","false","null","undefined"];if(null==a||0<=b.indexOf(a))return null;b=a.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);return null===b?null:"function(v){"+(b[1]?"Object("+b[1]+")"+b[2]:a)+"\x3dv;}"};b.ia.Cma=function(c,d,e,g,f,h){null!=d&&a.isObservable(d)?a.isWriteableObservable(d)&&d(e):(c in h||(d=null,g=b.ia.nea(g),null!=g&&(d=b.ia.pU(g)),h[c]=d),(c=h[c])&&c(f)(e))};b.ia.Tla=
function(c){c=a.utils.unwrapObservable(c);(Array.isArray(c)||b.oc.isPlainObject(c))&&c.ojConvertToJS&&(c=a.toJS(c));return c};b.ia.sV=function(a){for(var b={},c=Object.keys(a),d=0;d<c.length;d++){var e=c[d];0<=e.indexOf(".")&&(b[e]=a[e])}return b};b.ia.SU=function(a,b,c,d,e,g,f){for(var h=Object.keys(b),q=0;q<h.length;q++){var k=h[q],p=b[k];(p=a?p.pu:p.Vma)&&p(k,c,d,e,g,f)}};b.ia.MT=new d;b.ia.R9=function(){return b.Js()&&a?a.version:""};b.ia.bha=function(a){return 0<=b.ia.mS.indexOf(a)};b.ia.mS=
[];b.ia.s7="component";b.ia.YR="_ojOptions";(function(){var c=a.removeNode;a.removeNode=function(a){var d=b.Components;d&&b.v.k5(a);try{c(a)}finally{d&&b.v.k5(null)}}})();b.ia.f8=b.ia.create(["ojComponent","jqueryUI"]);b.ia.oh().sh({attributes:["optionTemplate"],init:function(a,b,c,d,e,g,f){a=h(a,b,f);if(null!==a)return a},update:function(a,b,c,d,e,g,f){return h(a,b,f)},"for":"ComboboxOptionRenderer"});b.ia.oh().sh({"for":"ojCombobox",use:"ComboboxOptionRenderer"});b.ia.oh().sh({"for":"ojSelect",
use:"ComboboxOptionRenderer"});b.ia.oh().sh({"for":"ojInputSearch",use:"ComboboxOptionRenderer"});b.Zj={};o_("ResponsiveKnockoutUtils",b.Zj,b);b.Zj.zu=function(b){if(null==b)throw Error("oj.ResponsiveKnockoutUtils.createMediaQueryObservable: aborting, queryString is null");b=window.matchMedia(b);var c=a.observable(b.matches);b.addListener(function(a){c(a.matches)});-1!=navigator.userAgent.indexOf("WebKit")&&-1==navigator.userAgent.indexOf("Chrome")&&f(window).resize(function(){0===f("body").has(".oj-webkit-bug-123293").length&&
f("body").append('\x3cdiv aria-hidden\x3d"true" class\x3d"oj-helper-hidden-accessible oj-webkit-bug-123293"\x3e');f(".oj-webkit-bug-123293").text((new Date).getMilliseconds().toString())});return c};o_("ResponsiveKnockoutUtils.createMediaQueryObservable",b.Zj.zu,b);b.Zj.lna=function(){var c=b.qb.Du(b.qb.Sr.XXL_UP),d=b.qb.Du(b.qb.Sr.XL_UP),e=b.qb.Du(b.qb.Sr.LG_UP),g=b.qb.Du(b.qb.Sr.MD_UP),f=b.qb.Du(b.qb.Sr.SM_UP),h=null==c?null:b.Zj.zu(c),q=null==d?null:b.Zj.zu(d),k=null==e?null:b.Zj.zu(e),p=null==
g?null:b.Zj.zu(g),m=null==f?null:b.Zj.zu(f);return a.computed(function(){if(h&&h())return b.qb.Yi.XXL;if(q&&q())return b.qb.Yi.XL;if(k&&k())return b.qb.Yi.LG;if(p&&p())return b.qb.Yi.MD;if(m&&m())return b.qb.Yi.SM;throw Error(" NO MATCH in oj.ResponsiveKnockoutUtils.createScreenRangeObservable");})};o_("ResponsiveKnockoutUtils.createScreenRangeObservable",b.Zj.lna,b);b.ia.oh().sh({attributes:["areaLayers","pointDataLayers"],init:function(a,b,c,d,e,g,f){return l(a,b,f)},update:function(a,b,c,d,e,g,
f){return l(a,b,f)},"for":"ojThematicMap"});a.bindingHandlers.ojContextMenu={update:function(c,d){function e(a,b,c){r=c;var d=q();if(r)p.one("touchend.ojContextMenu",function(){d.Hs(!0);setTimeout(function(){d.Hs(!1)},50)});"touchstart"===v&&"contextmenu"===a.type||"contextmenu"===v&&"touchstart"===a.type?(v=null,clearTimeout(s)):!a.isDefaultPrevented()&&(b={launcher:p,initialFocus:"menu",position:{mouse:{my:"start top",at:"start bottom",of:a},touch:{my:"start\x3e40 center",at:"start bottom",of:a,
collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher"}}[b]},d.zA=!0,d.open(a,b),d.zA=!1,h().is(":visible")&&(a.preventDefault(),document.addEventListener("keyup",g),"touchstart"===a.type||"contextmenu"===a.type))&&(v=a.type,s=setTimeout(function(){v=null},300))}function g(a){121==a.which&&a.shiftKey&&h().is(":visible")&&a.preventDefault()}function h(){m||k();return m}function q(){l||k();return l}function k(){m=f(u).first();l=m.data("oj-ojMenu");if(!l)throw Error('"contextMenu" set to "'+
u+'", which does not reference a valid JET Menu.');m.on("oj__dismiss.ojContextMenu",function(){document.removeEventListener("keyup",g)})}var p=f(c),m,l,t,r=!1,n=!1,s,v=null,w;p.off(".ojContextMenu").removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",w,!0);m&&m.off(".ojContextMenu");clearTimeout(t);m=l=void 0;var u=a.utils.unwrapObservable(d());"string"!==f.type(u)&&(u=c.getAttribute("contextmenu"))&&(u="#"+u);w=function(a){if(r)return a.preventDefault(),a.stopPropagation(),
r=!1};c.addEventListener("click",w,!0);p.on("touchstart.ojContextMenu mousedown.ojContextMenu keydown.ojContextMenu ",function(a){if("mousedown"!==a.type||!q().Hs())return r=!1,"touchstart"===a.type&&(n=!0,t=setTimeout(e.bind(void 0,a,"touch",!0),750)),!0}).on("touchend.ojContextMenu touchcancel.ojContextMenu",function(){n=!1;clearTimeout(t);return!0}).on("keydown.ojContextMenu contextmenu.ojContextMenu",function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&e(a,n?"touch":"keydown"===a.type?
"keyboard":"mouse",!1);return!0}).addClass(b.v.Sd()?"oj-menu-context-menu-launcher":"")}};b.b.ga(m,b.b,"ComponentBinding.ComponentChangeTracker");m.prototype.Init=function(a,b){m.q.Init.call(this);this.ka=a;this.Ix=b;this.GH={};this.eu={}};m.prototype.A1=function(a,b){this.gha(a)||this.cV||(this.GH[a]=b,this.Ix.Gpa(this))};m.prototype.Bu=function(){this.cV=!0};m.prototype.Ppa=function(a){var c=this.eu[a]||0;b.l.assert(0<c,"ComponentChangeTracker suspendCount underflow");c--;0==c?delete this.eu[a]:
this.eu[a]=c};m.prototype.jqa=function(a){this.eu[a]=(this.eu[a]||0)+1};m.prototype.Kma=function(a){if(!this.cV){var c=b.ia.sV(a),d={changed:!0};this.ka("option",a,d);for(var e in c)this.ka("option",e,c[e],d)}};m.prototype.Tna=function(){var a=this.GH;this.GH={};return a};m.prototype.gha=function(a){return 1<=(this.eu[a]||0)};b.ia.oh().sh({attributes:["template"],init:function(a,b,c,d,e,g,f){return"template"===a?{_templateFunction:n(f,b)}:null},update:function(a,b,c,d,e,g,f){return"template"===a?
{_templateFunction:n(f,b)}:null},"for":"ojDiagram"});b.lO={};o_("koStringTemplateEngine",b.lO,b);b.lO.Woa=function(){if(!a.templates){var b={},c={},d=new a.nativeTemplateEngine,e=function(a){this.iu=a;this.text=function(a){if(!a)return b[this.iu];b[this.iu]=a};this.data=function(a,b){c[this.iu]||(c[this.iu]={});if(1===arguments.length)return c[this.iu][a];c[this.iu][a]=b}};d.makeTemplateSource=function(b,c){if("string"==typeof b){c=c||document;var d=c.getElementById(b);return d?new a.templateSources.domElement(d):
new e(b)}if(b&&1==b.nodeType||8==b.nodeType)return new a.templateSources.anonymousTemplate(b)};a.templates=b;a.setTemplateEngine(d)}};o_("koStringTemplateEngine.install",b.lO.Woa,b);(function(){var c=a.bindingProvider,d=c.instance,c=c.instance={};u(d,c,"nodeHasBindings");u(d,c,"getBindings",function(a,c,d){a=d;c=r(d);null!=c&&(b.r.error("%s binding is not compatible with bidding providers not implementing getBindingAccessors()",c),a=b.oc.$e({},d),delete a[c]);return a});u(d,c,"getBindingAccessors",
p)})();b.ia.oh().sh({attributes:["header","cell"],init:function(a,b,c,d,e,g,f){if("header"===a)return a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=y(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=y(f,c))),{header:b};if("cell"===a)return a=b.template,null!=a&&(b.renderer=x(f,a)),{cell:b}},update:function(a,b,c,d,e,g,f){return"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=y(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=y(f,c))),{header:b}):"cell"===
a?(a=b.template,null!=a&&(b.renderer=x(f,a)),{cell:b}):null},"for":"ojDataGrid"});b.ia.oh().sh({attributes:["columns","columnsDefault","rowTemplate"],init:function(a,b,c,d,e,g,f){if("columns"==a||"columnsDefault"==a){for(c=0;c<b.length;c++){var h=b[c];d=h.template;e=h.footerTemplate;g=h.headerTemplate;null!=d&&(h.renderer=B(f,"cell",d));null!=e&&(h.footerRenderer=B(f,"footer",e));null!=g&&(h.headerRenderer=B(f,"header",g))}return"columns"==a?{columns:b}:{columnsDefault:b}}if("rowTemplate"==a)return{rowRenderer:O(f,
b)}},update:function(a,b,c,d,e,g,f){if("columns"==a||"columnsDefault"==a){var h;for(c=0;c<b.length;c++){var q=b[c];e=q.template;g=q.footerTemplate;h=q.headerTemplate;null!=e&&(q.renderer=B(f,"cell",e));null!=g&&(q.footerRenderer=B(f,"footer",g));null!=h&&(q.headerRenderer=B(f,"header",h))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else if("rowTemplate"==a)return{rowRenderer:O(f,b)};return null},"for":"ojTable"});b.ia.oh().sh({attributes:["item"],init:function(a,b,c,d,e,g,f){a=F(a,b,f);if(null!=
a)return a},update:function(a,b,c,d,e,g,f){return F(a,b,f)},"for":"ojListViewRenderer"});b.ia.oh().sh({"for":"ojListView",use:"ojListViewRenderer"});b.ia.oh().sh({"for":"ojNavigationList",use:"ojListViewRenderer"})});