/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore"],function(b,f){(function(){b.ya("oj.ojMenu",f.oj.baseComponent,{defaultElement:"\x3cul\x3e",delay:300,role:"menu",widgetEventPrefix:"oj",options:{menuSelector:"ul",openOptions:{initialFocus:"menu",launcher:null,position:{my:"start top",at:"start bottom",collision:"flipfit"}},submenuOpenOptions:{position:{my:"start top",at:"end top",collision:"flipfit"}},beforeOpen:null,select:null},_ComponentCreate:function(){this._super();this._focusForTesting=
this.mg;this._nextForTesting=this.mZ;this._selectForTesting=this.Aj;this.Yq=this.element;this.IO=!1;this.element.uniqueId().addClass("oj-menu oj-component").hide().attr({role:this.role,tabIndex:"0"});this._on(!0,{"mousedown .oj-menu-item":function(a){this.options.disabled&&a.preventDefault()},click:function(a){this.options.disabled&&a.preventDefault()},keydown:function(a){!this.options.disabled||a.keyCode!==f.ui.keyCode.ESCAPE&&a.keyCode!==f.ui.keyCode.TAB||(a.keyCode===f.ui.keyCode.TAB&&a.preventDefault(),
this.lc&&this.zB(a))}});this.options.disabled&&this.element.addClass("oj-disabled").attr("aria-disabled","true");var a=function(a){if(!this.CN){this.CN=!0;var b=f(a.currentTarget);b.siblings().removeClass("oj-focus-ancestor");this.mg(a,b)}}.bind(this);this._on({"mousedown .oj-menu-item \x3e a":function(a){a.preventDefault()},"click .oj-disabled \x3e a":function(a){a.preventDefault()},click:function(){this.IO=!1},touchstart:function(){this.CN=!1},mouseover:function(){this.CN=!1},"click .oj-menu-item:has(a)":function(a){var b=
f(a.target).closest(".oj-menu-item");!this.IO&&b.not(".oj-disabled").length&&(this.IO=!0,a.preventDefault(),this.Da&&this.Da.closest(b).length&&this.Da.get(0)!=b.get(0)||(b.has(".oj-menu").length?this.ae(a):(this.Aj(a),this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.Da&&1===this.Da.parents(".oj-menu").length&&clearTimeout(this.bd)))))},"mouseenter .oj-menu-item":a,"touchstart .oj-menu-item":a,mouseleave:function(a){this.pk(a,"eventSubtree")},"mouseleave .oj-menu":function(a){this.pk(a,
"eventSubtree")},focus:function(a,b){if(!b){var c=this.Da||this.element.children(".oj-menu-item").eq(0);this.mg(a,c)}},keydown:this.Dq,keyup:function(a){if(a.keyCode==f.ui.keyCode.ENTER||a.keyCode==f.ui.keyCode.SPACE)this.AA=!1}});this.qy=f.proxy(this.ry,this);this.Aa()},Hs:function(a){if(arguments.length)d=a;else return d},QH:function(b){if(("focus"===b.type||"mousedown"===b.type||"touchstart"===b.type||93==b.which||121==b.which&&b.shiftKey||93==b.keyCode)&&("mousedown"!==b.type||!d)){var e=a.slice(0,
a.length);f.each(e,function(a,d){!f(b.target).closest(d.element).length&&("keydown"===b.type||"mousedown"===b.type&&3===b.which||!f(b.target).closest(d.lc).length||d.uha&&("mousedown"===b.type&&3!==b.which||"touchstart"===b.type))&&(d.pk(b,"eventSubtree"),d.lc&&d.Pp(b))})}},_setOption:function(a,d){this._superApply(arguments);this.lc||("submenuOpenOptions"===a?this.qD=b.qc.Gg(d.position,this.Qf):"submenuOpenOptions.position"===a&&(this.qD=b.qc.Gg(d,this.Qf)))},_destroy:function(){this.element.is(":visible")&&
this.Pp();clearTimeout(this.bd);delete this.bd;this.element.removeAttr("aria-activedescendant").removeClass("oj-component").find(".oj-menu").addBack().removeClass("oj-menu oj-menu-submenu oj-menu-icons oj-menu-text-only").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();this.element.find(".oj-menu-item").removeClass("oj-menu-item").removeAttr("role").children("a").removeAttr("aria-disabled").removeUniqueId().removeClass("oj-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=
f(this);a.data("oj-ojMenu-submenu-icon")&&a.remove()});this.element.find("a").removeAttr("aria-expanded");this.element.find(".oj-menu-divider").removeClass("oj-menu-divider").removeAttr("role");0<=a.indexOf(this)&&a.splice(a.indexOf(this),1);delete this.xj;delete this.qy;var b=this.Hn;isNaN(b)||(delete this.Hn,window.clearTimeout(b));this._super()},Dq:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")}var d,h,k,l,m=!0;switch(a.keyCode){case f.ui.keyCode.HOME:this.IC("first",
"first",a);break;case f.ui.keyCode.END:this.IC("last","last",a);break;case f.ui.keyCode.UP:this.Nia(a);break;case f.ui.keyCode.DOWN:this.mZ(a);break;case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.keyCode===f.ui.keyCode.RIGHT^this.Qf?this.Da&&!this.Da.is(".oj-disabled")&&this.ae(a):this.pk(a,"active");break;case f.ui.keyCode.ENTER:case f.ui.keyCode.SPACE:this.jfa(a);this.AA=!0;var n=this;setTimeout(function(){n.AA=!1},100);break;case f.ui.keyCode.TAB:a.preventDefault();this.lc&&this.zB(a);break;
case f.ui.keyCode.ESCAPE:this.lc?(h=this.element.attr("aria-activedescendant"),k="#"+this.element.attr("id")+"\x3e*\x3ea",h&&!f("#"+h).is(k)?this.pk(a,"active"):this.zB(a)):this.pk(a,"active");break;default:m=!1,d=this.NE||"",h=String.fromCharCode(a.keyCode),k=!1,clearTimeout(this.Rna),h===d?k=!0:h=d+h,l=new RegExp("^"+b(h),"i"),d=this.Yq.children(".oj-menu-item").filter(function(){return l.test(f(this).children("a").text())}),d=k&&-1!==d.index(this.Da.next())?this.Da.nextAll(".oj-menu-item"):d,d.length||
(h=String.fromCharCode(a.keyCode),l=new RegExp("^"+b(h),"i"),d=this.Yq.children(".oj-menu-item").filter(function(){return l.test(f(this).children("a").text())})),d.length?(this.mg(a,d),1<d.length?(this.NE=h,this.Rna=this._delay(function(){delete this.NE},1E3)):delete this.NE):delete this.NE}m&&a.preventDefault()},jfa:function(a){this.Da&&!this.Da.is(".oj-disabled")&&(this.Da.children("a[aria-haspopup\x3d'true']").length?this.ae(a):this.Aj(a))},refresh:function(){this._super();this.Aa();var a=this.element;
if(a.is(":visible")){var b=a.data("oj-menu-position");b&&a.position(b);a.find(".oj-menu").each(function(){var a=f(this);a.is(":visible")&&(b=a.data("oj-menu-position"))&&a.position(b)})}},Aa:function(){this.Qf="rtl"===this.ec();this.qD=b.qc.Gg(this.options.submenuOpenOptions.position,this.Qf);var a=this,d=this.element.find(this.options.menuSelector),g=d.add(this.element),h=g.children();h.filter(".oj-menu-divider").has("a").removeClass("oj-menu-divider oj-menu-item").removeAttr("role");h.filter(":not(.oj-menu-item):has(a)").addClass("oj-menu-item").attr("role",
"presentation").children("a").uniqueId().attr({tabIndex:"-1",role:"menuitem"});h.filter(":not(.oj-menu-item)").each(function(){var a=f(this);/[^\-\u2014\u2013\s]/.test(a.text())||a.addClass("oj-menu-divider").attr("role","separator")});h.filter(".oj-disabled").children("a").attr("aria-disabled","true");h.filter(":not(.oj-disabled)").children("a").removeAttr("aria-disabled");d.filter(":not(.oj-menu)").addClass("oj-menu oj-menu-submenu").hide().attr({role:this.role,"aria-hidden":"true"}).each(function(){var b=
f(this),d=a.DJ(b),e=f("\x3cspan\x3e");e.addClass("oj-menu-submenu-icon oj-component-icon").data("oj-ojMenu-submenu-icon",!0);d.attr("aria-haspopup","true").attr("aria-expanded","false").append(e);d=d.attr("id");b.attr("aria-labelledby",d)});g.each(function(){var a=f(this),b=a.children().children().children(".oj-menu-item-icon").length;a.toggleClass("oj-menu-icons",!!b).toggleClass("oj-menu-text-only",!b)});this.Da&&!f.contains(this.element[0],this.Da[0])&&this.lH()},DJ:function(a){return a.prev("a")},
Fra:function(){return"menuitem"},CA:function(a){return a.add(a.prev(".oj-menu-divider")).add(a.next(".oj-menu-divider"))},mg:function(a,b){a&&"focus"===a.type||clearTimeout(this.bd);b=b.first();this.XY(b,a);var d=b.parent().closest(".oj-menu-item");this.CA(d).addClass("oj-focus-ancestor");a&&"keydown"===a.type?this.Fl():this.bd=this._delay(function(){delete this.bd;this.Fl()},this.delay);d=b.children(".oj-menu");d.length&&a&&/^mouse/.test(a.type)&&!this.Da.hasClass("oj-disabled")&&this.yla(d);this.Yq=
b.parent()},XY:function(a,b){if(!a.is(this.Da)){var d=this.Da?this.Da:f(),h=a.children("a");this.Da=a;this.element.attr("aria-activedescendant",h.attr("id"));this.CA(d).removeClass("oj-focus");this.CA(a).addClass("oj-focus");this._trigger("_activeItem",b,{previousItem:d,item:a,privateNotice:"The _activeItem event is private.  Do not use."})}},xja:function(a){if(this.Da){var b=this.Da;this.Da=null;this.element.removeAttr("aria-activedescendant");this.CA(b).removeClass("oj-focus");this._trigger("_activeItem",
a,{previousItem:b,item:f(),privateNotice:"The _activeItem event is private.  Do not use."})}},lH:function(a){clearTimeout(this.bd);this.xja(a)},zB:function(a){this.lc.focus();this.Pp(a)},Pp:function(c){var d={};d[b.N.Qa.gf]=this.element;b.N.pe().close(d);this.element.removeData("oj-menu-position");this.lc=void 0;this._trigger("__dismiss",c,{});0<=a.indexOf(this)&&a.splice(a.indexOf(this),1)},open:function(c,d,g){this.element.is(":visible")&&this.Pp();d=f.extend({},this.options.openOptions,d);d.position=
f.extend({},d.position);g=f.extend({},this.options.submenuOpenOptions,g);b.qc.lia(c);this.uha=this.zA;if(this._trigger("beforeOpen",c,{openOptions:d})){var h=d.launcher;if((h="string"===f.type(h)?f(h):h)&&h.length){var k=b.qc.Gg(d.position,this.Qf);k.of=b.qc.spa(k.of,h,c);if(null==k.of)b.r.warn("position.of passed to Menu.open() is 'event', but the event is null.  Ignoring the call.");else{var l=this.element[0],m=a.slice(0,a.length);f.each(m,function(a,b){b.element[0]!==l&&(b.pk(c,"eventSubtree"),
b.lc&&b.Pp(c))});this.qD=b.qc.Gg(g.position,this.Qf);g=this.qy;f.isFunction(k.using)&&k.using!==g&&(k.origUsing=k.using);k.using=g;g={};g[b.N.Qa.gf]=this.element;g[b.N.Qa.ov]=h;g[b.N.Qa.tv]=k;g[b.N.Qa.np]=this.rt();g[b.N.Qa.bn]="oj-menu-layer";b.N.pe().open(g);this.element.data("oj-menu-position",k);d=d.initialFocus;((k="firstItem"===d)||"menu"===d)&&this.element.focus();k?this.mg(c,this.element.children().first()):this.lH(c);this.lc=h;a.push(this)}}else b.r.warn("When calling Menu.open(), must specify openOptions.launcher via the component option, method param, or beforeOpen listener.  Ignoring the call.")}},
yla:function(a){clearTimeout(this.bd);"true"===a.attr("aria-hidden")&&(this.bd&&clearTimeout(this.bd),this.bd=this._delay(function(){delete this.bd;this.Fl();this.sZ(a)},this.delay))},sZ:function(b){var d=f.extend({of:this.Da},this.qD);clearTimeout(this.bd);this.element.find(".oj-menu").not(b.parents(".oj-menu")).hide().attr("aria-hidden","true").removeData("oj-menu-position");b.show().removeAttr("aria-hidden").position(d).data("oj-menu-position",d);this.DJ(b).attr("aria-expanded","true");!this.lc&&
0>a.indexOf(this)&&a.push(this)},WG:function(a,b,d){function h(){delete k.bd;var d=b?k.element:f(a&&a.target).closest(k.element.find(".oj-menu"));d.length||(d=k.element);k.Fl(d);k.lH(a);k.Yq=d}clearTimeout(this.bd);var k=this;d?this.bd=this._delay(h,d):h()},Fl:function(b){b||(b=this.Da?this.Da.parent():this.element);var d=b.find(".oj-menu");d.hide().attr("aria-hidden","true").removeData("oj-menu-position");this.DJ(d).attr("aria-expanded","false");b.find("oj-focus-ancestor").removeClass("oj-focus-ancestor");
this.lc||0<=a.indexOf(this)&&b===this.element&&a.splice(a.indexOf(this),1)},pk:function(a,d){if(null==d||"active"===d){var f=this.Yq&&this.Yq.closest(".oj-menu-item",this.element);f&&f.length&&(this.Fl(),this.mg(a,f))}else"all"===d||"eventSubtree"===d?this.WG(a,"all"===d,this.delay):b.r.warn("Invalid param "+d+" passed to Menu._collapse().  Ignoring the call.")},ae:function(a){var b=this.Da&&this.Da.children(".oj-menu ").children(".oj-menu-item").first();b&&b.length&&(this.sZ(b.parent()),this.bd&&
clearTimeout(this.bd),this.bd=this._delay(function(){delete this.bd;this.mg(a,b)}))},mZ:function(a){this.IC("next","first",a)},Nia:function(a){this.IC("prev","last",a)},Bra:function(){return this.Da&&!this.Da.prevAll(".oj-menu-item").length},Cra:function(){return this.Da&&!this.Da.nextAll(".oj-menu-item").length},IC:function(a,b,d){var f;this.Da&&(f="first"===a||"last"===a?this.Da["first"===a?"prevAll":"nextAll"](".oj-menu-item").eq(-1):this.Da[a+"All"](".oj-menu-item").eq(0));f&&f.length&&this.Da||
(f=this.Yq.children(".oj-menu-item")[b]());this.mg(d,f)},Aj:function(a){if(!this.Da&&a&&a.target){var d=f(a.target).closest(".oj-menu-item");d.closest(this.element).length&&this.XY(d,a)}this.Da?this.Da.has(".oj-menu").length||this.Da.is(".oj-disabled")?b.r.warn("Selecting a disabled menu item or parent menu item is not allowed."):(d={item:this.Da},this.WG(a,!0),this.lc&&this.zB(a),this._trigger("select",a,d)):b.r.warn("Menu._select() called when no menu item is focused and no menu item can be inferred from event param.")},
Tq:function(){this.element.remove()},rt:function(){if(!this.xj){var a=this.xj={};a[b.N.Bc.Zr]=f.proxy(this.cU,this);a[b.N.Bc.$r]=f.proxy(this.Tq,this);a[b.N.Bc.dn]=f.proxy(this.refresh,this);a[b.N.Bc.Yr]=f.proxy(this.QH,this)}return this.xj},cU:function(){this.Fl(this.element);this.Pp(null)},ry:function(a,d){var g=d.element.element;g.css(a);(g=g.data("oj-menu-position"))&&(g=g.origUsing)&&g(a,d);b.qc.cO(d)&&(this.Hn=this._delay(f.proxy(this.cU,this),1))}});var a=[],d=!1})()});