/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery"],function(b,f){b.X=function(a,b,c){this.Init(a,b,c)};o_("Message",b.X,b);b.X.$j={CONFIRMATION:"confirmation",INFO:"info",WARNING:"warning",ERROR:"error",FATAL:"fatal"};o_("Message.SEVERITY_TYPE",b.X.$j,b);b.X.Tb={FATAL:5,ERROR:4,WARNING:3,INFO:2,CONFIRMATION:1};o_("Message.SEVERITY_LEVEL",b.X.Tb,b);b.b.ga(b.X,b.b,"oj.Message");b.X.prototype.Init=function(a,d,c){b.X.q.Init.call(this);this.summary=a;this.detail=d;this.severity=c||b.X.$j.ERROR};b.b.g("Message.prototype.Init",
{Init:b.X.prototype.Init});b.X.prototype.Q1=function(){return!0};b.X.prototype.Ko=function(a){return a&&b.X.Iu(this.severity)===b.X.Iu(a.severity)&&this.summary===a.summary&&this.detail===a.detail?!0:!1};b.b.g("Message.prototype.equals",{Ko:b.X.prototype.Ko});b.X.prototype.clone=function(){return new b.X(this.summary,this.detail,this.severity)};b.b.g("Message.prototype.clone",{clone:b.X.prototype.clone});b.X.Iu=function(a){a&&("string"===typeof a?(a=b.X.lG.indexOf(a,1),a=-1===a?b.X.Tb.ERROR:a):"number"===
typeof a&&a<b.X.Tb.CONFIRMATION&&a>b.X.Tb.FATAL&&(a=b.X.Tb.ERROR));return a?a:b.X.Tb.ERROR};o_("Message.getSeverityLevel",b.X.Iu,b);b.X.goa=function(a){var d;a&&("string"===typeof a?(d=b.X.lG.indexOf(a,1),-1===d&&(a=b.X.$j.ERROR)):"number"===typeof a&&(a=a<b.X.Tb.CONFIRMATION&&a>b.X.Tb.FATAL?b.X.$j.ERROR:b.X.lG[a]));return a||b.X.$j.ERROR};o_("Message.getSeverityType",b.X.goa,b);b.X.Gu=function(a){var d=-1,c;a&&0<a.length&&f.each(a,function(a,g){g&&(c=b.X.Iu(g.severity));d=d<c?c:d});return d};o_("Message.getMaxSeverity",
b.X.Gu,b);b.X.isValid=function(a){return b.X.Gu(a)>=b.X.Tb.ERROR?!1:!0};o_("Message.isValid",b.X.isValid,b);b.X.lG=["none",b.X.$j.CONFIRMATION,b.X.$j.INFO,b.X.$j.WARNING,b.X.$j.ERROR,b.X.$j.FATAL];b.Jc=function(a,b,c,e){this.Init(a,b,c,e)};b.b.ga(b.Jc,b.X,"oj.ComponentMessage");b.Jc.Pr={HF:"shown",uF:"hidden"};b.Jc.v7={display:b.Jc.Pr.HF,context:""};b.Jc.prototype.Init=function(a,d,c,e){b.Jc.q.Init.call(this,a,d,c);this.jb=f.extend({},b.Jc.v7,e)};b.Jc.prototype.Ko=function(a){return b.Jc.q.Ko.call(this,
a)&&this.jb.display===a.jb.display};b.Jc.prototype.clone=function(){return new b.Jc(this.summary,this.detail,this.severity,this.jb)};b.Jc.prototype.Q1=function(){return!(this.jb&&this.jb.display&&this.jb.display===b.Jc.Pr.uF)};b.Jc.prototype.Vca=function(){this.jb&&b.Jc.Pr.uF===this.jb.display&&(this.jb.display=b.Jc.Pr.HF)};b.Jc.prototype.tY=function(){return this.jb&&this.jb.context?!0:!1}});