/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","promise"],function(b,f){b.Y=window.oj.Events={on:function(a,b,c){return this.vl(a,b,c,!1,!1)},off:function(a,b,c){return this.TK(a,b,c,!1)},trigger:function(a){var d=Array.prototype.slice.call(arguments);d.unshift(!1);return b.Y.Kb.apply(this,d)},once:function(a,b,c){return this.rZ(a,b,c,!1,null)},listenTo:function(a,d,c){var e,g,f,k,l={};d.constructor===String?l[d]=c:l=d;for(k in l)if(l.hasOwnProperty(k))for(d=b.Y.jq(k),c=0;c<d.length;c+=1)e=d[c].event,g=d[c].W,f={event:e,
W:g,object:a,Db:l[k]},this.JH(this._listeningTo,f,b.Y.RY),e=g?e+":"+g:e,void 0===this._listeningTo&&(this._listeningTo=[]),this._listeningTo.push(f),a.vl(e,l[k],null,!0,!1);return this},listenToOnce:function(a,d,c){var e,g,f,k,l={};d.constructor===String?l[d]=c:l=d;for(k in l)if(l.hasOwnProperty(k))for(d=b.Y.jq(k),c=0;c<d.length;c+=1)e=d[c].event,g=d[c].W,f={event:e,W:g,object:a,Db:l[k]},this.JH(this._listeningTo,f,b.Y.RY),e=g?e+":"+g:e,void 0===this._listeningTo&&(this._listeningTo=[]),this._listeningTo.push(f),
a.rZ(e,l[k],null,!0,this);return this},stopListening:function(a,d,c){var e,g={},f,k,l,m,n,p,r,s,q;if(null==arguments||1>=arguments.length){p=this._listeningTo?this._listeningTo.length:0;for(s=0;s<p;s++)if(m=this._listeningTo[s],n=a?a===m.object:!0)n=m.object.TK,n.apply(m.object,[m.event,m.Db,m.context,!0]);this._listeningTo=[];return this}e=d;a&&a.constructor===String&&(e=a);e.constructor===String?g[e]=c:g=e;for(q in g)if(g.hasOwnProperty(q))for(e=b.Y.jq(q),f=0;f<e.length;f+=1)for(k=e[f].event,l=
e[f].W,p=this._listeningTo?this._listeningTo.length:0,s=p-1;0<=s;s-=1)m=this._listeningTo[s],n=a?a===m.object:!0,p=k?k===m.event:!0,r=c?g[q]===m.Db:!0,m=l?l===m.W:!0,n&&p&&r&&m&&(n=this._listeningTo[s].object.TK,n.apply(this._listeningTo[s].object,[this._listeningTo[s].event,this._listeningTo[s].Db,this._listeningTo[s].context,!0]),this._listeningTo.splice(s,1));return this}};b.Y.bind=b.Y.on;b.Y.unbind=b.Y.off;b.Y.D={ADD:"add",ALLADDED:"alladded",REMOVE:"remove",RESET:"reset",REFRESH:"refresh",SORT:"sort",
CHANGE:"change",DESTROY:"destroy",ALLREMOVED:"allremoved",REQUEST:"request",SYNC:"sync",ERROR:"error",INVALID:"invalid",READY:"ready",ALL:"all"};o_("Events.EventType",b.Y.D,b);b.Y.DF=function(a,b){var c,e=b||this;for(c in e)"function"===typeof e[c]&&(a[c]=e[c]);a.ad={};a._listeningTo=[]};b.Y.rZ=function(a,b,c,e,g){var f,k,l,m;l=this.aJ(a,b);for(m in l)if(l.hasOwnProperty(m))for(a=this.jq(m),b=0;b<a.length;b+=1)f=a[b].event,k=a[b].W,void 0===this.ad&&(this.ad=[]),void 0===this.ad[f]&&(this.ad[f]=[]),
this.ad[f].push({Db:l[m],context:c,W:k,Gm:!0,fired:!1,So:e,jz:g});return this};b.Y.v0=function(a){return a.Gm?a.fired?!1:a.fired=!0:!0};b.Y.YV=function(a,b){return b.context||b.jz||a};b.Y.Kb=function(a,d){var c=this.jq(d),e,g,f,k,l,m;k=[];for(e=0;e<c.length;e+=1)g=c[e].event,f=c[e].W,k.push({event:g,W:f});for(e=0;e<k.length;e+=1){l=this.OB(this.ad,b.Y.D.ALL);c=b.Y.OB(this.ad,k[e].event,!1);for(g=0;g<(c?c.length:0);g+=1)c[g].W===k[e].W&&c[g].Db&&(f=Array.prototype.slice.call(arguments),c&&c[g]&&c[g].Gm&&
(this.n_(b.Y.OB(this.ad,k[e].event,!0),c[g]),c[g].jz&&c[g].jz.stopListening(this,d,c[g].Db)),c&&c[g]&&this.v0(c[g])&&(m=c[g].Db,a&&!c[g].M3||m.apply(b.Y.YV(this,c[g]),f.slice(2))));for(g=0;g<(l?l.length:0);g+=1)f=Array.prototype.slice.call(arguments),0<f.length&&(f[1]=k[e].W?k[e].event+":"+k[e].W:k[e].event),l&&l[g]&&l[g].Db&&this.v0(l[g])&&(m=l[g].Db,a&&!l[g].M3||m.apply(b.Y.YV(this,l[g]),f.slice(1))),l&&l[g]&&l[g].Gm&&(this.n_(this.OB(this.ad,b.Y.D.ALL,!0),l[g]),l[g].jz&&l[g].jz.stopListening(this,
b.Y.D.ALL,l[g].Db))}return this};b.Y.vl=function(a,d,c,e,g){var f,k,l,m;a=this.aJ(a,d);for(f in a)if(a.hasOwnProperty(f))for(d=this.jq(f),k=0;k<d.length;k+=1)l=d[k].event,m=d[k].W,void 0===this.ad&&(this.ad=[]),void 0===this.ad[l]&&(this.ad[l]=[]),m={Db:a[f],context:c,W:m,So:e,M3:g},-1===this.JH(this.ad[l],m,b.Y.Xfa)&&this.ad[l].push(m);return this};b.Y.TK=function(a,b,c,e){var g,f;if(null==arguments||0==arguments.length)return this.ad={},this;if(null==a)return this.m_(a,b,c,e),this;g=this.aJ(a,b);
for(f in g)g.hasOwnProperty(f)&&this.m_(f,g[f],c,e);return this};b.Y.aJ=function(a,b){var c={};a.constructor===String?c[a]=b:c=a;return c};b.Y.m_=function(a,d,c,e){var g=[],f,k,l,m,n,p,r,s;if(a)g=b.Y.jq(a);else if(void 0!==this.ad)for(k in this.ad)this.ad.hasOwnProperty(k)&&g.push({event:k});for(a=0;a<g.length;a+=1)if(k=g[a].event,l=g[a].W,void 0!==this.ad&&this.ad[k]instanceof Array){m=this.ad[k];for(f=m.length-1;0<=f;f-=1)n=void 0===d||null===d||m[f].Db==d,p=void 0===c||null===c||m[f].context==
c,r=void 0===l||null===l||m[f].W==l,s=void 0===e||null===e||m[f].So==e,n&&p&&r&&s&&m.splice(f,1);0===m.length&&delete this.ad[k]}};b.Y.n_=function(a,b){var c,e,g,f,k,l;if(a)for(c=a.length-1;0<=c;c-=1)e=void 0===b.Db||null===b.Db||a[c].Db==b.Db,g=void 0===b.context||null===b.context||a[c].context==b.context,f=void 0===b.W||null===b.W||a[c].W==b.W,k=void 0===b.So||null===b.So||a[c].So==b.So,l=void 0===b.Gm||null===b.Gm||a[c].Gm==b.Gm,e&&g&&f&&k&&l&&a.splice(c,1)};b.Y.jq=function(a){a=a?a.split(" "):
[];var b=[],c,e,g;for(c=0;c<a.length;c+=1)e=a[c].split(":"),g=e[0],e=1<e.length?e[1]:null,b.push({event:g,W:e});return b};b.Y.Xfa=function(a,b){return a.Db===b.Db&&a.W===b.W&&a.context===b.context&&a.So===b.So&&a.Gm===b.Gm};b.Y.RY=function(a,b){return a.event===b.event&&a.W===b.W&&a.context===b.context&&a.object===b.object};b.Y.JH=function(a,b,c){var e;if(void 0===a)return-1;for(e=0;e<a.length;e+=1)if(c(a[e],b))return e;return-1};b.Y.OB=function(a,b,c){if(a&&a[b]instanceof Array){if(c)return a[b];
c=[];var e;for(e=0;e<a[b].length;e++)c.push(a[b][e]);return c}return null};b.t=function(a,d){b.t._init(this,a,d,null)};o_("Model",b.t,b);b.b.ga(b.t,b.b,"oj.Model");b.t.prototype.Init=function(){b.t.q.Init.call(this)};b.t.prototype.attributes={};b.b.g("Model.prototype.attributes",{attributes:b.t.prototype.attributes});b.t.prototype.Gc={};b.b.g("Model.prototype.defaults",{Gc:b.t.prototype.Gc});b.t.prototype.id=null;b.b.g("Model.prototype.id",{id:b.t.prototype.id});b.t.prototype.L3="id";b.b.g("Model.prototype.idAttribute",
{L3:b.t.prototype.L3});b.t.prototype.X5=null;b.b.g("Model.prototype.urlRoot",{X5:b.t.prototype.X5});b.t.prototype.Ej=null;b.b.g("Model.prototype.customURL",{Ej:b.t.prototype.Ej});b.t.nK=0;b.t._init=function(a,d,c,e){var g=null,h;if(!b.t.lx){a.Init();b.Y.DF(a);a.Ns();a.SO={};a.IE=!1;a.index=-1;c=c||{};a.attributes={};a.defaults&&!c.Poa&&(a.attributes=b.t.XA(f.isFunction(a.defaults)?a.defaults():a.defaults,null));for(g in e)e.hasOwnProperty(g)&&(a[g]=e[g]);if(d)if(e=c.parse,f.isFunction(e)&&(a.parse=
e),h=b.t.XA(d,a.attributes),h=e?a.parse(h):h,null==h||void 0===h)a.attributes={};else for(g in h)h.hasOwnProperty(g)&&a.WL(g,h[g],!1,!1,c);a.Gz();a.yv(c.collection);c.customURL&&(a.customURL=c.customURL);c.url&&(a.url=c.url);c.urlRoot&&(a.urlRoot=c.urlRoot);a.initialize&&a.initialize(d,c);a.ak()}};b.t.extend=function(a,d){b.t.lx=!0;var c,e;c=new b.t;b.t.lx=!1;f.extend(c,this.prototype);a=a||{};for(e in a)a.hasOwnProperty(e)&&(c[e]=a[e]);var g;g=a&&a.constructor&&a.hasOwnProperty("constructor")?a.constructor:
function(d,c){b.t._init(this,d,c,a)};f.extend(g,this);g.prototype=c;g.extend=b.t.extend;g.prototype.constructor=g;b.Y.DF(g,this);if(d)for(e in d)d.hasOwnProperty(e)&&(g[e]=d[e]);return g};o_("Model.extend",b.t.extend,b);b.t.prototype.Kb=function(){};b.t.prototype.Gz=function(){this.qp()||(this.cid="id"+b.t.nK,b.t.nK+=1)};b.t.prototype.qp=function(){return this.cid};b.t.prototype.zv=function(a){this.index=a};b.t.prototype.y6=function(){return this.index};b.t.prototype.JF=function(a){this.qpa=a};b.t.prototype.Hz=
function(a){var b=this.TO;this.TO=a;return b};b.t.prototype.L6=function(a,d,c){var e,g=!1,f=b.Fa.od(d),k,l=!1;for(e in a.attributes)a.attributes.hasOwnProperty(e)&&(k=this.attributes[e]!=a.attributes[e],f?e===d&&k&&(g=!0):k&&(g=!0),k&&(l=!0,this.attributes[e]=a.attributes[e],this.YG(e,a.attributes[e]),this.uB(e,this.attributes[e],null,c)));this.ak();l&&this.vB(null,c);return g};b.t.jC=function(a){var b;if(a&&a instanceof Object)for(b in a)if(a.hasOwnProperty(b))return!0;return!1};b.t.prototype.yv=
function(a){null==a?delete this.collection:(this.collection=a,this.ak())};b.t.prototype.jv=function(){return this.collection};b.t.prototype.uB=function(a,d,c,e){null!=a&&this.Kb(e,b.Y.D.CHANGE+":"+a,this,d,c)};b.t.prototype.vB=function(a,d){this.Kb(d,b.Y.D.CHANGE,this,a,null)};b.t.prototype.ak=function(){var a=null;this.collection&&this.collection.modelId&&(a=this.collection.modelId,a=f.isFunction(a)?a.call(this.collection,this.attributes):a);a||(a=this.gJ(),a=null!=this.attributes?this.attributes[a]:
null);this.id=a};b.t.prototype.Zka=function(a,d,c){var e=b.b.Yv(this.attributes[a],d);return c||!e?(this.attributes[a]=d,this.ak(),!e):!1};b.t.prototype.Ns=function(){this.changed={}};b.t.prototype.YG=function(a,b){this.changed[a]=b};b.t.prototype.WL=function(a,d,c,e,g){if(null==a)return!0;var f={},k,l=this.IE;if(e)for(k in a)a.hasOwnProperty(k)&&(f[k]=a[k]);else f[a]=d;a=g||{};if(!this.ow(f,{validate:a.validate},!1))return!1;l||(this.Ns(),this.Ho=[]);this.IE||(this.SO=b.t.XA(this.attributes,null));
this.IE=!0;for(k in f)f.hasOwnProperty(k)&&(this.Zka(k,f[k],c)?(this.YG(k,f[k]),this.Ho.push(k)):delete f[k]);c=a.silent;for(k in f)f.hasOwnProperty(k)&&(!c&&(0<this.Ho.length||l&&-1===this.Ho.indexOf(k))&&(this.L4=!0,this.xpa=a),this.uB(k,f[k],a,c));if(l)return!0;if(!c&&!l)for(;this.L4;)this.L4=!1,this.vB(this.xpa,c);this.IE=!1;return!0};b.t.prototype.clear=function(a){var d,c={silent:!0},e;a=a||{};e=a.silent;c.validate=a.validate;this.Ns();for(d in this.attributes)if(this.attributes.hasOwnProperty(d)){if(!this.DD(d,
c,!0))return!1;this.Kb(e,b.Y.D.CHANGE+":"+d,this,void 0,null)}this.attributes={};this.ak();this.uB(null,null,null,e);this.vB(null,e);return this};b.b.g("Model.prototype.clear",{clear:b.t.prototype.clear});b.t.XA=function(a,d){d=d||{};for(var c in a)d.hasOwnProperty(c)&&a.hasOwnProperty(c)&&void 0===a[c]&&delete a[c];b.oc.$e(d,a,void 0,!0,1E4);return d};b.t.prototype.clone=function(){var a=new this.constructor,d;for(d in this)this.hasOwnProperty(d)&&this[d]!==this.attributes&&(a[d]=this[d]);a.attributes=
b.t.XA(this.attributes,null);delete a.cid;a.Gz();a.ak();return a};b.b.g("Model.prototype.clone",{clone:b.t.prototype.clone});b.t.prototype.tp=function(a,b){var c=this.ag();if(void 0!==c&&c==a)return!0;c=this.cid;return void 0!==c&&c==b?!0:!1};b.t.prototype.set=function(a,d,c){var e=c||{},g,f=!0;if(arguments&&0<arguments.length)if(b.Fa.od(a))e.unset?this.DD(a,null,!1):this.WL(a,d,!1,!1,e)||(f=!1);else if(e=d||{},e.unset)for(g in a)a.hasOwnProperty(g)&&this.DD(g,null,!1);else this.WL(a,null,!0,!0,e)||
(f=!1);return f?this:!1};b.b.g("Model.prototype.set",{set:b.t.prototype.set});b.t.prototype.V5=function(a,b){return this.DD(a,b,!1)};b.b.g("Model.prototype.unset",{V5:b.t.prototype.V5});b.t.prototype.DD=function(a,b,c){b=b||{};var e=b.silent,g={};if(this.has(a)){if(!this.ow(g,b,!1))return!1;c||this.Ns();delete this.attributes[a];this.YG(a,void 0);this.uB(a,null,null,e);this.vB(null,e)}this.ak();return!0};b.t.prototype.get=function(a){return this.attributes[a]};b.b.g("Model.prototype.get",{get:b.t.prototype.get});
b.t.prototype.has=function(a){return b.j.Jl(this.attributes[a])};b.b.g("Model.prototype.has",{has:b.t.prototype.has});b.t.prototype.fetch=function(a){a=a||{};var d=a.success,c=a.error,e=this,g;g=b.t.$p(a);g.error=function(d,g,f){b.t.ly(e,!1,a,g,f,d);c&&c.apply(e,arguments)};g.success=function(c){g.xhr&&(a.xhr=g.xhr);b.t.ft(e,c,g);f.isFunction(e.parse)&&e.set(e.parse(c),g);d&&d.call(e,this,c,a)};b.t.ex("read",this,g)};b.b.g("Model.prototype.fetch",{fetch:b.t.prototype.fetch});b.t.prototype.parse=function(a){return a};
b.t.prototype.url=function(){var a=this.hX(),d=this.ag();if(a)return d?a+"/"+encodeURIComponent(d):a;if(a=this.collection)return a=b.t.$m(a,"url"),d&&a?(d="/"==b.t.Mda(a)?"":"/",a+d+encodeURIComponent(this.ag())):a;throw new b.jn;};b.b.g("Model.prototype.url",{url:b.t.prototype.url});b.t.prototype.keys=function(){var a,b=[];for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(a);return b};b.b.g("Model.prototype.keys",{keys:b.t.prototype.keys});b.t.prototype.Z5=function(){var a,b=[];
for(a in this.attributes)this.attributes.hasOwnProperty(a)&&b.push(this.get(a));return b};b.b.g("Model.prototype.values",{Z5:b.t.prototype.Z5});b.t.prototype.J4=function(){var a,b=[],c;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(c=[],c.push(a),c.push(this.get(a)),b.push(c));return b};b.b.g("Model.prototype.pairs",{J4:b.t.prototype.J4});b.t.prototype.H4=function(a){var b=[],c,e,g={};if(a instanceof Array)b=a;else for(c=0;c<arguments.length;c++)b.push(arguments[c]);for(e in this.attributes)this.attributes.hasOwnProperty(e)&&
-1==b.indexOf(e)&&(g[e]=this.get(e));return g};b.b.g("Model.prototype.omit",{H4:b.t.prototype.H4});b.t.prototype.M4=function(a){var b=[],c,e={};if(a instanceof Array)b=a;else for(c=0;c<arguments.length;c++)b.push(arguments[c]);for(c=0;c<b.length;c++)this.attributes.hasOwnProperty(b[c])&&(e[b[c]]=this.get(b[c]));return e};b.b.g("Model.prototype.pick",{M4:b.t.prototype.M4});b.t.prototype.S3=function(){var a,b={},c;for(a in this.attributes)this.attributes.hasOwnProperty(a)&&(c=this.get(a),b[c]=a);return b};
b.b.g("Model.prototype.invert",{S3:b.t.prototype.S3});b.t.Mda=function(a){return a.charAt(a.length-1)};b.t.prototype.rka=function(){var a=this.hX();return a?a:this.jv()?this.jv().url:null};b.t.prototype.hX=function(){return b.t.$m(this,"urlRoot")};b.t.prototype.parseSave=function(a){return a};b.t.prototype.isValid=function(){var a={};a.validate=this.validate;return this.ow(this.attributes,a,!1)};b.b.g("Model.prototype.isValid",{isValid:b.t.prototype.isValid});b.t.lha=function(a,b){a=a||{};return void 0!==
a.validate&&null!==a.validate?a.validate:b};b.t.prototype.ow=function(a,d,c){d=d||{};var e=this.validate;return e&&b.t.lha(d,c)&&(this.validationError=e.call(this,a,d))?(this.Kb(!1,b.Y.D.INVALID,this,this.validationError,d),!1):!0};b.t.Oia=function(a){var d=!1,c={},e,g={};if(a&&0<a.length){1<a.length&&a[a.length-1]&&b.t.jC(a[a.length-1])&&(d=!0,c=a[a.length-1]||{});if(null==a[0])return{attributes:null,options:c};if(b.t.jC(a[0])||b.b.Pf(a[0]))for(e in a[0])a[0].hasOwnProperty(e)&&(g[e]=a[0][e]);else for(e=
0;e<a.length;e+=2)if(void 0!==a[e]||e<a.length-1||!d&&e===a.length-1)g[a[e]]=a[e+1]}return{attributes:g,options:c}};b.t.$p=function(a){var b={},c;a=a||{};for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};b.t.ly=function(a,d,c,e,g,f){c=c||{};c.textStatus=e;c.errorThrown=g;a.Kb(d,b.Y.D.ERROR,a,f,c)};b.t.prototype.save=function(a,d){var c,e,g,h,k,l;c=b.t.Oia(arguments);var m,n,p;p=void 0===a?void 0:c.attributes;d=d||{};m=b.t.$p(c.options);if(!this.ow(this.attributes,m,!0))return!1;m.wait||this.set(p);
c=void 0===m.forceNew?!1:m.forceNew;h=this;k=m.error;l=m.patch;m.error=function(a,c,e){b.t.ly(h,!1,d,c,e,a);k&&k.apply(h,arguments)};m.saveAttrs=m.wait?this.I$(p):this.attributes;n=this.attributes;this.attributes=m.saveAttrs;m.saveAttrs=this.toJSON();this.attributes=n;if(!c&&!this.wE())return e=m.success,m.success=function(a){var c;m.xhr&&(d.xhr=m.xhr);a&&!b.b.Pf(a)?(c=f.isFunction(h.parse)?h.parse(a):a,h.attributes=f.extend(!0,h.attributes,c),h.ak(),b.t.ft(h,c,m),m.wait&&h.set(c)):(b.t.ft(h,a,m),
m.wait&&h.set(p));e&&e.call(b.t.Wi(m,h),h,a,d);h.Ns()},m.attrs||(m.attrs=void 0===p?void 0:l?p:m.saveAttrs),b.t.ex(l?"patch":"update",this,m);g=b.t.ZW(m);m.success=function(a){var c;m.xhr&&(d.xhr=m.xhr);if(a&&!b.b.Pf(a)){c=f.isFunction(h.parse)?h.parse(a):a;if(!h.ow(c,m,!0))return;h.attributes=f.extend(!0,h.attributes,c);h.ak();b.t.ft(h,c,m);m.wait&&h.set(c)}else m.wait&&h.set(p),b.t.ft(h,a,m);g&&g.call(b.t.Wi(m,h),h,a,d);h.Ns()};m.attrs||(m.attrs=m.saveAttrs);m.parse=!0;l&&(m.saveAttrs=m.attrs);
return b.t.ex("create",this,m)};b.b.g("Model.prototype.save",{save:b.t.prototype.save});b.t.prototype.I$=function(a){var b={},c;for(c in this.attributes)this.attributes.hasOwnProperty(c)&&(b[c]=this.attributes[c]);for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};b.t.$m=function(a,b){return a?f.isFunction(a[b])?a[b]():a[b]:f.isFunction(b)?b():b};b.t.aQ=function(a){return a&&a.hasOwnProperty("value")&&a.hasOwnProperty("comparator")};b.t.prototype.Zfa=function(a){for(var d in a)if(a.hasOwnProperty(d)){if(!this.attributes.hasOwnProperty(d))return!1;
for(var c=Array.isArray(a[d])?a[d]:[a[d]],e=0;e<c.length;e++)if(b.t.aQ(c[e])){var g=c[e].comparator,f=c[e].value;if(b.Fa.od(g))throw Error("String comparator invalid for local where/findWhere");if(!g(this,d,f))return!1}else if(a[d]!==this.attributes[d])return!1}return!0};b.t.prototype.matches=function(a){a:{for(var b in a)if(this.get(b)!==a[b]){a=!1;break a}a=!0}return a};b.b.g("Model.prototype.matches",{matches:b.t.prototype.matches});b.t.prototype.k6=function(a){a=a.constructor===Array?a:[a];var b;
for(b=0;b<a.length;b++)if(this.Zfa(a[b]))return!0;return!1};b.t.ZW=function(a){return null!=a&&a.success?a.success:null};b.t.Wi=function(a,b){return void 0!==a&&void 0!==a.context?a.context:b};b.t.prototype.wE=function(){return void 0==this.ag()};b.b.g("Model.prototype.isNew",{wE:b.t.prototype.wE});b.t.prototype.gJ=function(){return this.idAttribute||"id"};b.t.prototype.ag=function(){return this.id};b.t.prototype.eN=function(a){if(a){var d={},c;for(c in a)a.hasOwnProperty(c)&&(b.b.Yv(a[c],this.attributes[c])||
(d[c]=a[c]));return b.b.Pf(d)?!1:d}return b.b.Pf(this.changed)?!1:this.changed};b.b.g("Model.prototype.changedAttributes",{eN:b.t.prototype.eN});b.t.prototype.YN=function(a){return void 0!==a?b.t.jC(this.changed)&&this.changed.hasOwnProperty(a):b.t.jC(this.changed)};b.b.g("Model.prototype.hasChanged",{YN:b.t.prototype.YN});b.t.prototype.destroy=function(a){a=a||{};var d=a.wait,c,e=a.error,g=this,f,k;k=b.t.$p(a);c=b.t.ZW(k);var l=this.jv();k.success=function(e){k.xhr&&(a.xhr=k.xhr);if(l){var f=b.Fa.od(e)&&
!b.Fa.Pf(e)?JSON.parse(e):e;l.i0(f,null,e,!0)}d&&g.NI();b.t.ft(g,e,k);c&&c.call(b.t.Wi(k,g),g,e,a)};k.error=function(d,c,f){g.Kb(!1,b.Y.D.ERROR,g,d,a);e&&e.apply(g,arguments)};if(!this.wE())return f=b.t.ex("delete",this,k),d||this.NI(),f;d||this.NI();c&&c.call(b.t.Wi(k,g),g,null,a);return!1};b.b.g("Model.prototype.destroy",{destroy:b.t.prototype.destroy});b.t.prototype.GV=function(a,d,c,e){this.Kb(e,b.Y.D.REQUEST,a,d,c)};b.t.prototype.NI=function(){this.Kb(!1,b.Y.D.DESTROY,this,this.collection,null)};
b.t.ft=function(a,d,c){a.Kb(!1,b.Y.D.SYNC,a,d,c)};b.t.prototype.toJSON=function(){var a={},b;for(b in this.attributes)this.attributes.hasOwnProperty(b)&&(Array.isArray(this.attributes[b])?a[b]=this.attributes[b].slice(0):a[b]=this.attributes[b]);return a};b.b.g("Model.prototype.toJSON",{toJSON:b.t.prototype.toJSON});b.t.prototype.Lm=function(a){return this.SO[a]};b.b.g("Model.prototype.previous",{Lm:b.t.prototype.Lm});b.t.prototype.R4=function(){return this.SO};b.b.g("Model.prototype.previousAttributes",
{R4:b.t.prototype.R4});b.t.prototype.sync=function(a,b,c){return window.oj.sync(a,b,c)};b.t.ex=function(a,d,c){c=c||{};d.oauth&&(c.oauthHeader=d.oauth.getHeader());!c.dataType&&d.dataType&&(c.dataType=d.dataType);!c.jsonpCallback&&d.jsonpCallback&&(c.jsonpCallback=d.jsonpCallback);if("create"===a||"patch"===a||"update"===a)c.PO=d.parseSave.call(d,"patch"===a?c.attrs:c.saveAttrs);var e=null;d instanceof b.t&&(e=d.ag());var g={};if(c)for(var f in c)g[f]=c[f];e=b.t.xQ(e,d,c);for(f in e)g[f]=e[f];c.xhr=
d.sync(a,d,g);g.xhr&&(c.xhr=g.xhr);return c.xhr};b.t.xQ=function(a,d,c){d=d instanceof b.j?d.P6(c):{};a&&(d.recordID=a);return d};b.oP=function(a,d,c){function e(a){d.GV(d,a,c,c.silent);return a}c=c||{};var g,f=c.success,k=c.error;g=d.customURL;if("create"===a.valueOf())return a=(a=d.rka())?a:b.t.$m(d,"url"),g=new b.Ta(a,g),e(g.Ema(c.PO,k,c,d));if("read"===a.valueOf()){if(d instanceof b.t)return a=c.url?c.url:b.t.$m(d,"url"),g=new b.Ta(a,g),e(g.RN(f,k,d.ag(),c,b.t.Wi(c,d)));a=d.SP(c);g=new b.Ta(a,
g);return e(g.coa(f,k,c,d))}g=new b.Ta(b.t.$m(d,"url"),g);var l=null;d instanceof b.t&&(l=d.ag());return"update"===a.valueOf()?e(g.W5(f,l,c.PO,k,c,d,!1)):"patch"===a.valueOf()?e(g.W5(f,l,c.PO,k,c,d,!0)):"delete"===a.valueOf()?e(g.Ena(l,k,c,d)):null};o_("sync",b.oP,b);b.t.tma=function(a){if(!a.url)throw Error("The url property or function must be specified");};b.ajax=function(){arguments&&0<arguments.length&&b.t.tma(arguments[0]);return f.ajax.apply(window.oj,arguments)};o_("ajax",b.ajax,b);b.jn=function(){this.name=
"URLError";this.message="No URL defined"};o_("URLError",b.jn,b);b.jn.prototype=Error();b.jn.constructor=b.jn;b.Ta=function(a,b){this.mz=a;this.Ej=b;f.support.cors=!0};b.Ta.rs="headers";b.Ta.vy=function(a,d,c){var e;a=f.extend(!0,a,c);for(e in d)d.hasOwnProperty(e)&&"oauthHeader"!==e&&(a.hasOwnProperty(e)||(a[e]=d[e]),e===b.Ta.rs&&(a[e]=f.extend(!0,a[e],d[e])));if(d.oauthHeader)for(e in a[b.Ta.rs]||(a[b.Ta.rs]={}),d.oauthHeader)d.oauthHeader.hasOwnProperty(e)&&(a[b.Ta.rs].hasOwnProperty(e)||(a[b.Ta.rs][e]=
d.oauthHeader[e]));return a};b.Ta.prototype.coa=function(a,d,c,e){c=c||{};var g="jsonp"===c.dataType,f=this.Xw("read",this.mz,this.Ej,null,e,c);a={crossDomain:c.crossDomain||!g,dataType:this.JB(c),jsonpCallback:c.jsonpCallback,context:null!==e?e:this,success:a,error:d};a=this.EA(a);a=b.Ta.vy(a,c,f);c.xhr=this.ajax(a);return c.xhr};b.Ta.prototype.EA=function(a){a[b.Ta.rs]={"Accept-Language":this.Ag()};return a};b.Ta.prototype.RN=function(a,d,c,e,g){e=e||{};var f="jsonp"===e.dataType;c=this.Xw("read",
this.mz,this.Ej,c,g,e);a={crossDomain:e.crossDomain||!f,dataType:this.JB(e),jsonpCallback:e.jsonpCallback,context:null!==g?g:this,success:a,error:d};a=this.EA(a);a=b.Ta.vy(a,e,c);e.xhr=this.ajax(a);return e.xhr};b.Ta.prototype.W5=function(a,d,c,e,g,f,k){g=g||{};var l="jsonp"===g.dataType;d=this.Xw(k?"patch":"update",this.mz,this.Ej,d,f,g);k=b.Ta.Ys(g);a={crossDomain:g.crossDomain||!l,contentType:this.oda(g),dataType:this.JB(g),jsonpCallback:g.jsonpCallback,data:this.eb(JSON.stringify(c),g,d),emulateHTTP:k,
emulateJSON:b.Ta.Zs(g),success:a,error:e,context:null!==f?f:this};a=this.EA(a);a=b.Ta.vy(a,g,d);a=b.Ta.uT(k,a);g.xhr=this.ajax(a);return g.xhr};b.Ta.uT=function(a,b){if(a){var c=b.beforeSend;b.beforeSend=function(a){a.setRequestHeader("X-HTTP-Method-Override",b.yi);if(c)return c.apply(this,arguments)}}return b};b.Ta.prototype.eb=function(a,d,c){return b.Ta.Zs(d)?(d={_method:c.yi?c.yi:c.type},a&&(d.model=a),d):a};b.Ta.prototype.Fda=function(a,d){if(d.type)return{method:d.type};var c=null;"create"===
a&&(c="POST");"delete"===a&&(c="DELETE");"patch"===a&&(c="PATCH");"update"===a&&(c="PUT");if(b.Ta.Ys(d)){var e={method:"POST"};e.yi=c;return e}null===c&&(c="GET");return{method:c}};b.Ta.Ys=function(a){return a.emulateHTTP||b.emulateHTTP};b.Ta.Zs=function(a){return a.emulateJSON||b.emulateJSON};b.Ta.prototype.Xw=function(a,d,c,e,g,h){var k=this.Fda(a,h);if(f.isFunction(c)){a=c.call(this,a,g,b.t.xQ(e,g,h));if(b.Fa.od(a))return d={url:a,type:k.method},k.yi&&(d.yi=k.yi),d;if(a)return a.url=a.hasOwnProperty("url")?
a.url:d,a.hasOwnProperty("type")||(a.type=k.method),!a.hasOwnProperty("data")&&k.yi&&(a.yi=k.yi),a}d={url:b.t.$m(null,d),type:k.method};k.yi&&(d.yi=k.yi);return d};b.Ta.prototype.Ena=function(a,d,c,e){c=c||{};var g="jsonp"===c.dataType;a=this.Xw("delete",this.mz,this.Ej,a,e,c);var f=b.Ta.Ys(c);d={crossDomain:c.crossDomain||!g,success:c.success,error:d,context:null!==e?e:this,emulateHTTP:f,emulateJSON:b.Ta.Zs(c)};(e=this.eb(null,c,a))&&(d.data=e);d=b.Ta.vy(d,c,a);d=b.Ta.uT(f,d);c.xhr=this.ajax(d);
return c.xhr};b.Ta.prototype.Ema=function(a,d,c,e){c=c||{};var g=JSON.stringify(a),f="jsonp"===c.dataType;a=this.Xw("create",this.mz,this.Ej,null,e,c);var k=b.Ta.Ys(c);d={crossDomain:c.crossDomain||!f,contentType:c.contentType||"application/json",dataType:this.JB(c),jsonpCallback:c.jsonpCallback,data:this.eb(g,c,a),success:c.success,error:d,emulateHTTP:k,emulateJSON:b.Ta.Zs(c),context:null!==e?e:this};d=this.EA(d);d=b.Ta.vy(d,c,a);c.xhr=this.ajax(d);return c.xhr};b.Ta.prototype.JB=function(a){return b.Ta.Zs(a)&&
!b.Ta.Ys(a)?"application/x-www-form-urlencoded":a.dataType||"json"};b.Ta.prototype.oda=function(a){return b.Ta.Zs(a)&&!b.Ta.Ys(a)?"application/x-www-form-urlencoded":a.contentType||"application/json"};b.Ta.prototype.Ag=function(){return b.ba.Ag()};b.Ta.prototype.ajax=function(a){if(null===a.url||void 0===a.url)throw new b.jn;return window.oj.ajax(a)};b.Fb=function(a,d){d=d||{};b.Fb._init(this,d,a||"Authorization")};o_("OAuth",b.Fb,b);b.b.ga(b.Fb,b.b,"oj.OAuth");b.Fb.prototype.Init=function(){b.Fb.q.Init.call(this)};
b.Fb.prototype.Y2=function(){var a={};this.Co.access_token||this.gN();a[this.Ok.M1]="Bearer "+this.Co.access_token;return a};b.b.g("OAuth.prototype.getHeader",{Y2:b.Fb.prototype.Y2});b.Fb.prototype.W3=function(){return this.Co.Mra?!0:!1};b.b.g("OAuth.prototype.isInitialized",{W3:b.Fb.prototype.W3});b.Fb.prototype.gN=function(){var a={},d=this;a[d.Ok.M1]="Basic "+b.Fb.O$(d.Ok.client_id+":"+d.Ok.client_secret);f.ajax({type:"POST",async:!1,url:this.Ok.bearer_url,data:"grant_type\x3dclient_credentials",
headers:a,success:function(a){b.Fb.dx(d.Co,a)},error:function(a){throw Error(a.responseText);}})};b.b.g("OAuth.prototype.clientCredentialGrant",{gN:b.Fb.prototype.gN});b.Fb.prototype.h5=function(a){b.Fb.dx(this.Co,a)};b.b.g("OAuth.prototype.setAccessTokenResponse",{h5:b.Fb.prototype.h5});b.Fb.prototype.G2=function(){return this.Co};b.b.g("OAuth.prototype.getAccessTokenResponse",{G2:b.Fb.prototype.G2});b.Fb.prototype.T1=function(){b.Fb.PT(this.Co)};b.b.g("OAuth.prototype.cleanAccessTokenResponse",
{T1:b.Fb.prototype.T1});b.Fb.prototype.g5=function(a){b.Fb.dx(this.Ok,a)};b.b.g("OAuth.prototype.setAccessTokenRequest",{g5:b.Fb.prototype.g5});b.Fb.prototype.F2=function(){return this.Ok};b.b.g("OAuth.prototype.getAccessTokenRequest",{F2:b.Fb.prototype.F2});b.Fb.prototype.S1=function(){b.Fb.PT(this.Ok)};b.b.g("OAuth.prototype.cleanAccessTokenRequest",{S1:b.Fb.prototype.S1});b.Fb._init=function(a,d,c){a.Init();a.Ok={};a.Co={};d.access_token?b.Fb.dx(a.Co,d):d.client_id&&d.client_secret&&d.bearer_url&&
b.Fb.dx(a.Ok,d);a.Ok.M1=c};b.Fb.dx=function(a,b){var c;b=b||{};for(c in b)a[c]=b[c]};b.Fb.PT=function(a){for(var b in a)a.hasOwnProperty(b)&&"auth_header"!==b&&(a[b]=null,delete a[b])};b.Fb.O$=function(a){var b,c,e,g,f=0,k=0,l=[];do b=a.charCodeAt(f++),c=a.charCodeAt(f++),e=a.charCodeAt(f++),g=b<<16|c<<8|e,b=g>>18&63,c=g>>12&63,e=g>>6&63,g&=63,l[k++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(c)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(g);while(f<a.length);l=l.join("");b=a.length%3;return(b?l.slice(0,b-3):l)+"\x3d\x3d\x3d".slice(b||3)};b.j=function(a,d){b.j.lx||b.j._init(this,a,d,null)};o_("Collection",b.j,b);b.b.ga(b.j,b.b,"oj.Collection");b.j.prototype.Xo=null;b.b.g("Collection.prototype.model",{Xo:b.j.prototype.Xo});b.j.prototype.w4=function(a){var b=this.model;return b&&
a?a[b.idAttribute||b.prototype.idAttribute||"id"]:null};b.b.g("Collection.prototype.modelId",{w4:b.j.prototype.w4});b.j.prototype.length=void 0;b.b.g("Collection.prototype.length",{length:b.j.prototype.length});b.j.prototype.y4=void 0;b.b.g("Collection.prototype.models",{y4:b.j.prototype.y4});b.j.prototype.Yb=[];b.j.prototype.url=null;b.b.g("Collection.prototype.url",{url:b.j.prototype.url});b.j.prototype.Ho=[];b.b.g("Collection.prototype.changes",{Ho:b.j.prototype.Ho});b.j.prototype.Ej=null;b.b.g("Collection.prototype.customURL",
{Ej:b.j.prototype.Ej});b.j.prototype.p2=null;b.b.g("Collection.prototype.customPagingOptions",{p2:b.j.prototype.p2});b.j.prototype.e4=void 0;b.b.g("Collection.prototype.lastFetchSize",{e4:b.j.prototype.e4});b.j.prototype.G3=!1;b.b.g("Collection.prototype.hasMore",{G3:b.j.prototype.G3});b.j.prototype.J5=void 0;b.b.g("Collection.prototype.totalResults",{J5:b.j.prototype.J5});b.j.prototype.d4=void 0;b.b.g("Collection.prototype.lastFetchCount",{d4:b.j.prototype.d4});b.j.prototype.x4=-1;b.b.g("Collection.prototype.modelLimit",
{x4:b.j.prototype.x4});b.j.prototype.offset=void 0;b.b.g("Collection.prototype.offset",{offset:b.j.prototype.offset});b.j.prototype.x2=-1;b.b.g("Collection.prototype.fetchSize",{x2:b.j.prototype.x2});b.j.prototype.iP=1;b.b.g("Collection.prototype.sortDirection",{iP:b.j.prototype.iP});b.j.prototype.iN=null;b.b.g("Collection.prototype.comparator",{iN:b.j.prototype.iN});b.j.prototype.Init=function(){b.j.q.Init.call(this)};b.j.extend=function(a,d){b.j.lx=!0;var c=new b.j;b.j.lx=!1;f.extend(c,this.prototype);
var e;e=a&&a.constructor&&a.hasOwnProperty("constructor")?a.constructor:function(d,c){b.j._init(this,d,c,a)};if(d)for(var g in d)d.hasOwnProperty(g)&&(e[g]=d[g]);if(a)for(g in a)a.hasOwnProperty(g)&&(c[g]=a[g]);f.extend(e,this);e.prototype=c;e.extend=b.j.extend;return e.prototype.constructor=e};o_("Collection.extend",b.j.extend,b);b.j._init=function(a,d,c,e){var g,f;a.Init();b.Y.DF(a);if(e)for(g in e)e.hasOwnProperty(g)&&(a[g]=e[g]);c=c||{};f=["comparator","customPagingOptions","customURL",b.j.Ld,
"model","modelLimit","sortDirection","url"];for(g=0;g<f.length;g++)c.hasOwnProperty(f[g])&&void 0!==c[f[g]]&&(a[f[g]]=c[f[g]]);void 0===a.vk(null)&&a.TE(-1);void 0===a.modelLimit&&a.cP(-1);a.hasMore=!1;a.Ki=0;a.Oq([],!0);c.parse&&(d=a.parse(d));if(null!=d)for(c.E4=!0,f=d instanceof Array?d:[d],g=0;g<f.length;g+=1)a.add(f[g],c);a.Kk();e&&e.initialize&&e.initialize.call(a,d,c)};b.j.prototype.on=function(){};b.j.prototype.vl=function(){};b.j.prototype.Kb=function(){};b.j.prototype.GV=function(a,d,c,
e){this.Kb(e,b.Y.D.REQUEST,a,d,c)};b.j.prototype.cka=function(){this.changes=[]};b.j.prototype.PL=function(a,b){for(var c=a;c<a+b;c++)-1===this.changes.indexOf(c)&&(this.changes.push(c),this.changes.sort(function(a,b){return a-b}))};b.j.prototype.Oq=function(a,b){this.models=a;if(b)this.Yb=[],this.cka();else for(var c=0;c<a.length;c++)a[c]&&this.Yb.push(c)};b.j.prototype.Ec=function(){return this.models};b.j.prototype.Yc=function(){return this.Ec().length};b.j.prototype.tia=function(a){return a<this.Yc()||
this.Xa()&&(!this.wq()||0===this.Yc())?!1:!0};b.j.prototype.wq=function(){return b.j.Jl(this.totalResults)};b.j.Jl=function(a){return null!=a};b.j.prototype.Yia=function(a){this.Ec().push(a);this.Yb.push(this.Yc()-1);this.PL(this.Yc()-1,1)};b.j.prototype.Zia=function(a){this.MK(a);this.Yia(a);this.Ki++;a.zv(this.Yc()-1)};b.j.prototype.PZ=function(a){if(a)for(var b=0;b<a.length;b++)a[b]&&this.Ki--};b.j.prototype.L0=function(a,b,c){for(var e=a;e<a+b;e++)this.s_(this.Pb(e));void 0===c?(this.PZ(this.Ec().splice(a,
b)),this.K0(a,a+b-1)):(this.PZ(this.Ec().splice(a,b,c)),this.K0(a,a+b-1),this.Lga(a),this.MK(c));this.PL(a,b);0>this.Ki&&(this.Ki=0);this.OZ(a)};b.j.prototype.Pb=function(a){return this.Ec()[a]};b.j.prototype.OZ=function(a){for(var b,c=0;c<this.Yb.length;c++)b=this.Yb[c],b>=a&&this.Pb(b)&&this.Pb(b).zv(b)};b.j.prototype.s_=function(a){if(a){var b=a.TO;a=a.qpa;b?b.JF(a):this.head=a;a?a.Hz(b):this.tail=b}};b.j.prototype.MK=function(a){a.JF(this.head);this.head?this.head.Hz(a):this.tail=a;a.Hz(null);
this.head=a};b.j.prototype.Vka=function(a){-1===this.Yb.indexOf(a)&&this.Yb.push(a)};b.j.prototype.Lga=function(a){for(var b=0;b<this.Yb.length;b++)this.Yb[b]>=a&&this.Yb[b]++;this.Yb.push(a)};b.j.prototype.K0=function(a,b){void 0===b&&(b=a);this.YT(a,b);for(var c=b-a+1,e=0;e<this.Yb.length;e++)this.Yb[e]>b&&(this.Yb[e]-=c)};b.j.prototype.YT=function(a,b){void 0===b&&(b=a);for(var c=a;c<=b;c++){var e=this.Yb.indexOf(a);-1<e&&this.Yb.splice(e,1)}};b.j.prototype.hD=function(a,b){var c=this.Pb(a);this.s_(c);
c||this.Ki++;this.PL(a,1);if(this.Ec()[a]=b)this.Vka(a),b.zv(a),this.MK(b)};b.j.prototype.Baa=function(a){var b=this.tail,c,e,g=0;for(this.tail=null;b&&g<a;)c=b.y6(),(e=this.Pb(c))&&e.YN()?(this.tail||(this.tail=b),b=b.TO):(this.Ki--,-1<c&&(this.hD(c,void 0),this.YT(c,c)),b.JF(null),b=b.Hz(null),g++);this.tail||(this.tail=b);0>this.Ki&&(this.Ki=0);0===this.Ki&&(this.tail=this.head=null)};b.j.prototype.Vx=function(){this.Ki=0;this.tail=this.head=null};b.j.prototype.Fq=function(a){if(this.Xa()){var b=
this.yW();-1<b&&this.Ki+a>b&&this.Baa(this.Ki+a-b)}};b.j.prototype.clone=function(){return this.bU(!0)};b.b.g("Collection.prototype.clone",{clone:b.j.prototype.clone});b.j.prototype.bU=function(a){var b=new this.constructor,c;this.Xa()&&(b=this.Uaa(b),b.FL());b=this.Vaa(b);if(a){var e=[];for(a=0;a<this.Yb.length;a++)e.push(this.Yb[a]);e.sort(function(a,b){return a-b});var g;for(a=0;a<e.length;a++)g=e[a],(c=this.El(g,null,!0,!1))&&b.Cl(c.clone(),{at:g},!0,!1)}return b};b.j.prototype.Vaa=function(a){var b=
["comparator","model","modelId"],c,e;for(e=0;e<b.length;e++)c=b[e],a[c]=this[c];return a};b.j.prototype.Uaa=function(a){var d=["totalResults","hasMore",b.j.Ld],c,e;for(e=0;e<d.length;e++)c=d[e],a[c]=this[c];return a};b.j.prototype.be=function(){return this.length};b.j.prototype.Kk=function(){var a=this.Yc();this.length=a;this.Xa()||(this.totalResults=a)};b.j.$H=function(a,b,c){return a.model?f.isFunction(a.model)?new a.model(b,c):new a.model.constructor(b,c):null};b.j.prototype.xx=function(a,d,c){var e=
null;d=d||{};d.Poa=c;a instanceof b.t?e=a:this.model?e=b.j.$H(this,a,d):(d.collection=this,e=new b.t(a,d));return d.validate&&e.validate&&(a=e.validate(e.attributes))?(d.validationError=a,this.Kb(!1,b.Y.D.INVALID,e,a,d),null):e};b.j.prototype.add=function(a,b){this.Fq(1);return this.Yw(this.Cl(a,b,!1,(b||{}).deferred))};b.b.g("Collection.prototype.add",{add:b.j.prototype.add});b.j.prototype.Cl=function(a,d,c,e){function g(a,e,g,f,h){var k,r=null;!p&&t&&g?(w=g.L6(e,a.comparator,n),r=g):(p||(k=a.uW(f))&&
c&&m!==k.index&&b.r.warn("Duplicate ID fetched or added without merging, the id \x3d "+k.ag()),void 0===k?(void 0===m?(a.Zia(f),s=a.Yc()-1,a.Pb(s).Gz()):(s=m,a.Xa()&&c?a.hD(s,f):a.L0(s,0,f),a.Pb(s).Gz(),m+=1),void 0===f.jv()&&f.yv(a),a.Kk(),a.yha(f),u=!0,r=f):r=k);c&&(d=d||{},d.fillIn=!0);w&&void 0===k&&!v&&void 0===m&&1<a.be()&&(-1<s&&(q=a.Pb(s).cid),e={},b.oc.$e(e,d),e.add=!0,a.sort(e),-1<s&&(s=a.Xa()?-1:a.indexOf(a.FN(q),h)));u&&(d.at&&(d.index=s),f?(f.Kb(n,b.Y.D.ADD,f,a,d),y.push(f)):(g.Kb(n,
b.Y.D.ADD,g,a,d),y.push(g)));return r}function f(a,e,h){u=!1;var q=a.xx(e,d,!1),k=null,m=null;if(null!=q){s=-1;q.ak();k=e instanceof b.t?e:q;if(h)return p?new Promise(function(b){var d=g(a,k,void 0,q,h);x.push(d);b(d)}):a.Gh(k,{silent:!0},h,!0).then(function(b){m=b.m;b=g(a,k,m,q,h);x.push(b)});!p&&t&&(m=c?a.uW(k):a.get(k));(e=g(a,k,m,q,h))&&x.push(e)}else x.push(!1)}function k(a,b){return a.parse&&d.parse&&!d.E4?a.parse(b):b}d=d||{};var l=[],m=d.at,n=d.silent,p=d.force,r,s,q,t=d.merge||!1,v=d.sort,
w=!0,u=!1,y=[],x=[];void 0!==m&&0>m&&(m+=this.be()+1);a instanceof Array?l=a:l.push(a);if(!c&&(this.Xa()||e)){var B=this;return new Promise(function(a,c){function e(a){return new Promise(function(b,d){f(B,l[a],!0).then(function(){b(a+1)},d)})}var g=Promise.resolve(0);l=k(B,l);for(r=0;r<l.length;r++)g=g.then(e);g.then(function(){0<y.length&&B.Kb(d.silent,b.Y.D.ALLADDED,B,y,d);a(b.j.HL(x))},c)})}l=k(this,l);for(r=0;r<l.length;r++)f(this,l[r],!1);0<y.length&&this.Kb(d.silent,b.Y.D.ALLADDED,this,y,d);
return b.j.HL(x)};b.j.HL=function(a){return 1===a.length?a[0]:a};b.j.prototype.hC=function(){return b.j.Jl(this.comparator)};b.j.prototype.sort=function(a){a=a||{};var d=a.silent,c=this.comparator,e;if(!this.hC())return null;if(this.Xa()){var g=this.totalResults;this.wq()?this.Oq(Array(g),!0):(this.Oq([],!0),this.Vx(),this.Kk());g=a.add?{add:!0}:null;this.Kb(d,b.Y.D.SORT,this,g,null);d=a.startIndex;return void 0!==d&&null!==d?this.oz(d,this.vk(a)):null}e=this;this.Ec().sort(function(a,d){return b.j.CQ(a,
d,c,e,e)});this.OZ(0);g=a.add?{add:!0}:null;this.Kb(d,b.Y.D.SORT,this,g,null);return null};b.b.g("Collection.prototype.sort",{sort:b.j.prototype.sort});b.j.Tn=function(a,d){return a instanceof b.t?a.get(d):b.t.$m(a,d)};b.j.CQ=function(a,d,c,e,g){var h,k,l;if(f.isFunction(c)){if(1===c.length){h=c.call(g,a);k=c.call(g,d);h=b.Fa.od(h)?h.split(","):[h];var m=b.Fa.od(k)?k.split(","):[k];for(l=0;l<h.length;l++)if(k=b.j.Gl(h[l],m[l],e.sortDirection),0!==k)return k}return c.call(g,a,d)}if(b.Fa.od(c))for(c=
c.split(","),l=0;l<c.length;l++)if(h=b.j.Tn(a,c[l]),k=b.j.Tn(d,c[l]),k=b.j.Gl(h,k,e.sortDirection),0!==k)return k;return 0};b.j.prototype.x5=function(a,d){var c=d?d:this.comparator,e;if(!c)return-1;this.Gf("sortedIndex");e=this;return b.j.Pca(this.Ec(),a,function(a,d){var k,l;if(f.isFunction(c)){if(1===c.length){k=c.call(e,a);l=c.call(e,d);k=b.Fa.od(k)?k.split(","):[k];l=b.Fa.od(l)?l.split(","):[l];var m,n;for(n=0;n<k.length;n++)if(m=b.j.Gl(k[n],l[n],e.sortDirection),0!==m)return m}return c.call(e,
a,d)}return b.Fa.od(c)?(k=a.get(c),l=d.get(c),b.j.Gl(k,l,e.sortDirection)):0})};b.b.g("Collection.prototype.sortedIndex",{x5:b.j.prototype.x5});b.j.Pca=function(a,b,c){function e(g,f){var k,l;if(g>f)return-1;k=b.qp();l=b.ag();if(a[g].tp(l,k))return g;if(a[f].tp(l,k))return f;k=Math.floor((f+g)/2);return-1===c(a[k],b)?e(g+1,k):1===c(a[k],b)?e(k,f-1):k}return e(0,a.length-1)};b.j.Gl=function(a,b,c){if(-1===c){if(a<b)return 1;if(b<a)return-1}else{if(a>b)return 1;if(b>a)return-1}return 0};b.j.prototype.unshift=
function(a,d){var c={};b.oc.$e(c,d||{});c.at||(c.at=0);this.Fq(1);return this.Yw(this.Cl(a,c,!1,c.deferred))};b.b.g("Collection.prototype.unshift",{unshift:b.j.prototype.unshift});b.j.prototype.Yw=function(a){return f.isFunction(a.then)?this.$d(function(){return a}):a};b.j.prototype.shift=function(a){a=a||{};var d=this.zf(a),c;if(this.Xa()||d){var e=this;return this.at(0,a).then(function(d){c=e.Nq(d,0,a);e.Kb(a.silent,b.Y.D.ALLREMOVED,e,[c],a);return c})}c=this.Nq(this.at(0),0,a);this.Kb(a.silent,
b.Y.D.ALLREMOVED,this,[c],a);return c};b.b.g("Collection.prototype.shift",{shift:b.j.prototype.shift});b.j.prototype.tE=function(a){void 0===a&&(a=1);this.Gf("initial");var b=[],c;for(c=0;c<this.be()-a;c+=1)b.push(this.at(c));return b};b.b.g("Collection.prototype.initial",{tE:b.j.prototype.tE});b.j.prototype.zf=function(a){return(a||{}).deferred};b.j.prototype.last=function(a,b){var c=this.zf(b);void 0===a&&(a=1);if(1===a){var e=this.Yc();0===e&&(e=a);return 0<e?this.at(e-1,c):null}var g=[],e=this.be();
if(c||this.Xa()){var f=e-a;0>f&&(f=0);0===e&&(e=a);var k=this;return this.$d(function(){return k.Vr(f,e)})}for(c=e-a;c<e;c+=1)g.push(this.at(c));return g};b.b.g("Collection.prototype.last",{last:b.j.prototype.last});b.j.prototype.Vr=function(a,b){var c=[],e,g=this;return new Promise(function(f,k){function l(a){return new Promise(function(b,d){g.kI(a,null).then(function(d){c.push(d);b(a+1)},d)})}var m=Promise.resolve(a);for(e=a;e<b;e++)m=m.then(l);m.then(function(){f(c)},k)})};b.j.prototype.cW=function(a){return void 0===
a||null===a?this[b.j.Ld]:a};b.j.prototype.jaa=function(){var a=this.lastFetchCount;if(void 0===a||null===a)a=this[b.j.Ld];return void 0===this.offset||null===this.offset?a:this.offset+a};b.j.prototype.next=function(a,d){d=d||{};d[b.j.Ld]=this.cW(a);var c=this.jaa(),e=this.be();if(0===e&&0<d[b.j.Ld])c=0;else if(c>=e)return d.success&&d.success.call(b.t.Wi(d,this),this,null,d),null;d.startIndex=c;return this.fetch(d)};b.b.g("Collection.prototype.next",{next:b.j.prototype.next});b.j.prototype.kaa=function(a){return void 0===
this.offset||null===this.offset?0:this.offset-a};b.j.prototype.Lm=function(a,d){d=d||{};if(0===this.offset)return d.success&&this.lastFetchCount&&d.success.call(b.t.Wi(d,this),this,null,d),null;d[b.j.Ld]=this.cW(a);var c=this.kaa(d[b.j.Ld]);0>c&&(d[b.j.Ld]=this.offset,c=0);d.startIndex=c;return this.fetch(d)};b.b.g("Collection.prototype.previous",{Lm:b.j.prototype.Lm});b.j.prototype.cP=function(a){this.modelLimit=a;this.Fq(0)};b.b.g("Collection.prototype.setModelLimit",{cP:b.j.prototype.cP});b.j.prototype.yW=
function(){return this.modelLimit};b.j.prototype.TE=function(a){this[b.j.Ld]=a};b.b.g("Collection.prototype.setFetchSize",{TE:b.j.prototype.TE});b.j.prototype.b5=function(a,b){var c=this.zf(b);void 0===a&&(a=1);var e=[];if(this.Xa()||c){var g=this;return this.$d(function(){return g.Vr(a,g.be())})}for(c=a;c<this.be();c+=1)e.push(this.at(c));return e};b.b.g("Collection.prototype.rest",{b5:b.j.prototype.b5});b.j.prototype.remove=function(a,d){d=d||{};var c=[],e;a instanceof Array?c=a:c.push(a);var g=
[];for(e=c.length-1;0<=e;e-=1)g.unshift(this.Nq(c[e],-1,d));this.Kb(d.silent,b.Y.D.ALLREMOVED,this,c,d);return b.j.HL(g)};b.b.g("Collection.prototype.remove",{remove:b.j.prototype.remove});b.j.prototype.Nq=function(a,d,c){c=c||{};a=-1==d?this.Gh(a):b.j.Rl(d,a);var e=c.silent;d=a.index;if(-1<d){var g=a.m;void 0!==g&&g.jv()===this&&g.yv(null);this.L0(d,1);this.Kk();var f={};b.oc.$e(f,c);f.index=d;void 0!==g&&g.Kb(e,b.Y.D.REMOVE,g,this,f);this.n1(g)}return a.m};b.j.prototype.n1=function(a){void 0!==
a&&a.off(null,null,this)};b.j.prototype.yha=function(a){a.vl(b.Y.D.ALL,this.Tha,this,!1,!0)};b.j.prototype.Tha=function(a,d,c,e){a===b.Y.D.DESTROY&&this.remove(d);void 0!==c&&c instanceof b.j&&c!==this||(Array.prototype.slice.call(arguments),this.Kb(e&&e.silent,a,d,c,e))};b.j.prototype.refresh=function(a){a=a||{};var d=this;return this.$d(function(){return new Promise(function(c,e){if(!d.Xa()){var g=void 0!==a.silent&&a.silent;try{d.reset(null,{silent:!0});var f={},k;for(k in a)a.hasOwnProperty(k)&&
(f[k]=a[k]);f.success=function(a,e,f){d.Kb(g,b.Y.D.REFRESH,d,f,null);c({collection:a,response:e,options:f})};f.error=function(c,g,f){e(b.j.yw(c,g,f,d,a))};d.fetch(f);return}catch(l){if(l instanceof b.jn){d.Kb(g,b.Y.D.REFRESH,d,a,null);c({collection:d,options:a});return}throw l;}}f=a.startIndex;d.Oq([],!0);d.Vx();d.totalResults=void 0;d.Kk();g=void 0!==a.silent&&a.silent;d.Kb(g,b.Y.D.REFRESH,d,a,null);if(void 0===f||null===f)f=0;void 0!==f&&null!==f?d.m0(f,d.vk(a)).then(function(a){c(a)},function(a){e(a)}):
c(void 0)})})};b.b.g("Collection.prototype.refresh",{refresh:b.j.prototype.refresh});b.j.prototype.reset=function(a,d){var c={};b.oc.$e(c,d||{});c.previousModels=this.Ec();for(var e,g=0;g<this.Yb.length;g++)if(e=this.Yb[g],e=this.Pb(e))this.n1(e),e.yv(null);this.Oq([],!0);this.Vx();g=void 0!==c.silent&&c.silent;if(!a)return this.totalResults=void 0,this.Kk(),this.Kb(g,b.Y.D.RESET,this,c,null),null;e=null;c.parse&&(a=this.parse(a));this.Fq(a instanceof Array?a.length:1);c.E4=!0;e=this.Cl(a,c,!0,!1);
this.Kk();this.Kb(g,b.Y.D.RESET,this,c,null);return this.Yw(e)};b.b.g("Collection.prototype.reset",{reset:b.j.prototype.reset});b.j.prototype.at=function(a,b){return this.El(a,b,!1,this.zf(b))};b.b.g("Collection.prototype.at",{at:b.j.prototype.at});b.j.prototype.El=function(a,b,c,e){0>a&&(a+=this.be());if(0>a||this.tia(a))return c||!this.Xa()&&!e?null:this.$d(function(){return Promise.resolve(null)});var g=this;return c||!this.Xa()&&!e?this.Pb(a):this.$d(function(){return g.kI(a,b)})};b.j.prototype.whenReady=
function(){return this.oo?this.oo:Promise.resolve()};b.b.g("Collection.prototype.whenReady",{whenReady:b.j.prototype.whenReady});b.j.prototype.$d=function(a){var d=this;void 0===this.oo&&(this.Hx=0,this.oo=Promise.resolve());this.Hx++;return this.oo=this.oo.then(a.bind(d)).then(function(a){d.Hx--;0===d.Hx&&(d.oo=void 0,d.Kb(!1,b.Y.D.READY,d,null,null));return a},function(a){d.Hx--;0===d.Hx&&(d.oo=void 0);return Promise.reject(a)})};b.j.prototype.kI=function(a,d){var c=this,e=c.Pb(a);return void 0===
e?new Promise(function(e,f){var k={};b.oc.$e(k,d||{});k.context=c;k.startIndex=a;k.error=function(a,e,g){f(b.j.yw(a,e,g,c,d))};k.success=function(){e(c.Pb(a))};c.De(k,-1,!1)}):new Promise(function(a){a(e)})};b.j.prototype.FN=function(a){for(var b=this.Ec(),c,e=null,g=0;g<this.Yb.length;g++)if(c=this.Yb[g],b[c]&&a===b[c].cid){e=b[c];break}if(e)return e;if(this.Xa())throw Error("Not found locally and not supported by server for virtual collections");return null};b.b.g("Collection.prototype.getByCid",
{FN:b.j.prototype.FN});b.j.prototype.get=function(a,b){var c=this.Gh(a,b,this.zf(b));if(c){if(f.isFunction(c.then))return this.$d(function(){return new Promise(function(a,b){c.then(function(b){a(b.m)},function(a){b(a)})})});if(this.Xa())return this.$d(function(){return new Promise(function(a){a(c.m)})});if(c.hasOwnProperty("m"))return c.m}return null};b.b.g("Collection.prototype.get",{get:b.j.prototype.get});b.j.prototype.uW=function(a){return(a=this.vW(a))?a.m:null};b.j.prototype.vW=function(a){var d=
a;a instanceof b.t?(d=a.qp(),a=a.ag()):b.j.Jl(a)&&void 0!==a.id&&(a=a.id);for(var c=null,e=this.Yb.length,g,f=this.Ec(),k,l=0;l<e;l++)if(k=this.Yb[l],g=f[k],void 0!==g&&g.tp(a,d)){c=b.j.Rl(k,g);break}return c?c:b.j.Rl(-1,void 0)};b.j.prototype.Gh=function(a,d,c,e){var g=a;void 0===e&&(e=!1);a instanceof b.t?(g=a.qp(),a=a.ag()):b.j.Jl(a)&&void 0!==a.id&&(a=a.id);for(var f=null,k=this.Ec(),l,m=0;m<this.Yb.length;m++)if(l=this.Yb[m],k[l]&&k[l].tp(a,g)){f=b.j.Rl(l,k[l]);break}if(f)return c?new Promise(function(a){a(f)}):
f;if(this.Xa()){if(void 0===a&&void 0!==g)return new Promise(function(a){a(b.j.Rl(-1,void 0))});var n=this;return new Promise(function(c,f){var h={};b.oc.$e(h,d||{});h.context=n;h.startID=a;h.error=function(a,c,e){f(b.j.yw(a,c,e,n,d))};h.success=function(d,e){if(null!=e){var f=n.uJ(),h=n.Pb(f);void 0!==h&&h.tp(a,g)?c(b.j.Rl(f,h)):c(b.j.Rl(-1,void 0))}else c(b.j.Rl(-1,void 0))};n.De(h,-1,e)})}var p=b.j.Rl(-1,void 0);return c?new Promise(function(a){a(p)}):p};b.j.Rl=function(a,b){return{index:a,m:b}};
b.j.prototype.parse=function(a){var b;if(a instanceof Array||!a)return a;for(b in a)if(a.hasOwnProperty(b)&&a[b]instanceof Array)return a[b];return a};b.j.prototype.oaa=function(a,b,c){return this.wq()&&0<this.totalResults&&c.start+c.count>=this.totalResults?!0:c.start===a&&c.count===b};b.j.prototype.oz=function(a,b){var c=this;return this.$d(function(){return c.m0(a,b)})};b.b.g("Collection.prototype.setRangeLocal",{oz:b.j.prototype.oz});b.j.prototype.m0=function(a,b){this.Xa()&&this.FL();var c=this.RB(a,
b),e=this;if(this.oaa(a,b,c))return new Promise(function(a){a(c)});var g=this.yW();-1<g&&g<b&&(this.modelLimit=b);return new Promise(function(c,g){e.l0(a,b,-1,{start:a,count:b},c,g,!0)})};b.j.prototype.l0=function(a,d,c,e,g,f,k){var l=this,m=a+d;this[b.j.Ld]&&this[b.j.Ld]>d&&(m=this[b.j.Ld]+a);var n=null;this.Xa()?(n=this.hW(a,m),n>a&&(a=n,m=a+d,this[b.j.Ld]&&this[b.j.Ld]>d&&(m=this[b.j.Ld]+a)),n={context:this,startIndex:a,fetchSize:m-a}):n={context:this};n.error=function(a,d,c){f(b.j.yw(a,d,c,l,
null))};n.success=function(){var b=l.RB(e.start,e.count);if(k&&l.wq()&&b.count<e.count){var c=b.start+b.count,q=a+d;q<l.totalResults?l.l0(q,d,c,e,g,f,k):g(b)}else g(b)};try{this.De(n,c,-1<c)}catch(p){p instanceof b.jn&&(c=l.RB(a,d),g(c))}};b.j.yw=function(a,d,c,e,g){var f=!1;g&&g.silent&&(f=g.silent);b.t.ly(e,f,g,d,c,a);g=Error(d);g.xhr=a;g.error=c;g.collection=e;g.status=d;return g};b.j.prototype.Uda=function(a,b){var c=this.Yc();return 0===c?a+b:a+b>c?c:a+b};b.j.prototype.Z3=function(a,b){var c=
this.RB(a,b);return 0===this.Yc()?0===b:a===c.start&&(b===c.count||a+b>this.Yc())};b.b.g("Collection.prototype.isRangeLocal",{Z3:b.j.prototype.Z3});b.j.prototype.Sw=function(a,b){for(var c=[],e=this.Ec(),g=a+b,f=a;f<g;f++)c.push(e[f]);return c};b.j.prototype.RB=function(a,b){if(!this.Xa()){if(0<this.Yc()){if(a+b>this.Yc()){var c=this.Yc()-a;return{start:a,count:c,models:this.Sw(a,c)}}return{start:a,count:b,models:this.Sw(a,b)}}return{start:a,count:0,models:[]}}c=this.Uda(a,b);if(!this.wq()&&c<a+b)return{start:a,
count:c-a,models:this.Sw(a,c-a)};if(0===c)return{start:a,count:0,models:[]};var e=this.hW(a,c);if(-1<e)return{start:a,count:e-a,models:this.Sw(a,e-a)};a>c?b=0:a+b>c&&(b=c-a);return{start:a,count:b,models:this.Sw(a,b)}};b.j.prototype.hW=function(a,b){for(var c=a;c<b;c++)if(void 0===this.Pb(c))return c;return-1};b.j.prototype.fetch=function(a){var b=this.De(a,-1,!1);this.$d(function(){return Promise.resolve(b)});return b};b.b.g("Collection.prototype.fetch",{fetch:b.j.prototype.fetch});b.j.prototype.De=
function(a,d,c){function e(a,b,d){a.Xa()?d||a.FL():b.add||b.wP||a.reset(null,{silent:!0})}var g=a||{},f=g.success,k,l=g.error;g.set&&(g.wP=g.set?!0:!1);void 0===g.parse&&(g.parse=!0);k=this;g.error=function(d,c,e){b.t.ly(k,!1,a,c,e,d);l&&l.call(b.t.Wi(a,k),d,c,e)};g.success=function(m){var n;try{n=k.parse(m,a)}catch(p){b.j.$C(k,p,g.error,a);return}k.i0(m,a,n,c);var r=null;if(g.add||k.model){e(k,g,c);try{q=!1,-1===d&&(q=!0,d=k.uJ()),r=k.Nca(n,d,q,g)}catch(l){b.j.$C(k,l,g.error,a);return}}else if(!c)if(k.Xa()){e(k,
g,c);var q=!1;-1===d&&(q=!0,d=k.uJ());r=k.$ia(n,d,q)}else g.wP?k.SL(n,!1,g,!1):k.reset(n,{silent:!0});k.Xa()&&r&&(k.lastFetchCount=r.length);k.Kb(g.silent?!0:!1,b.Y.D.SYNC,k,m,g);f&&f.call(b.t.Wi(a,k),k,m,g)};return this.uV(g)};b.j.prototype.$ia=function(a,b,c){var e;if(a){e=a instanceof Array?a:[a];a={};c&&this.Fq(e.length);c=this.Xa();for(var g=null,f=0;f<e.length;f+=1)c&&(a={at:b},g=this.El(b,null,!0,!1)),a.silent=!0,this.Cl(e[f],a,!0,!1),this.El(b,null,!0,!1)!==g&&b++}return e};b.j.prototype.Nca=
function(a,d,c,e){e=e||{};var g=e.parse,f=b.j.$H(this);if(a){var k=a instanceof Array?a:[a];a={};c&&this.Fq(k.length);c=this.Xa();if(e.wP&&!c){for(var l=0;l<k.length;l+=1)d=f&&g?f.parse(k[l]):k[l],k[l]=d;this.SL(k,!1,e,!1)}else{e=null;for(var m=d,l=0;l<k.length;l+=1)d=f&&g?f.parse(k[l]):k[l],c&&(a={at:m},e=this.El(m,a,!0,!1)),a.silent=!0,this.Cl(d,a,!0,!1),this.El(m,null,!0,!1)!==e&&m++}}return k};b.j.$C=function(a,d,c,e){b.r.error(d.toString());c&&c.call(b.t.Wi(e,a),a,d,e)};b.j.prototype.Kca=function(a){var d=
a||{},c=d.success,e,g;void 0===d.parse&&(d.parse=!0);g=this;d.success=function(f){var k,l,m=null,n=[];try{k=g.parse(f,a)}catch(p){b.j.$C(g,p,d.error,a);return}if(d.add||g.model)if(l=b.j.$H(g),k)for(m=k instanceof Array?k:[k],k=0;k<m.length;k+=1){if(l&&d.parse)try{e=l.parse(m[k])}catch(r){b.j.$C(g,r,d.error,a);return}else e=m[k];n.push(g.xx(e))}g.Kb(!1,b.Y.D.SYNC,g,f,d);c&&c.call(b.t.Wi(a,g),g,n,d)};this.uV(d)};b.j.prototype.uV=function(a){try{return b.t.ex("read",this,a)}catch(d){throw b.t.ly(this,
!1,a,null,d,null),d;}};b.j.prototype.FL=function(){var a=this.totalResults;void 0!==a&&this.Yc()!==a&&(this.Oq(Array(a),!0),this.Vx(),this.Kk())};b.j.prototype.vk=function(a){a=a||{};return a[b.j.Ld]||this[b.j.Ld]};b.j.prototype.Xa=function(){return-1<this.vk(null)};b.j.prototype.YB=function(a,d,c,e,g){a=parseInt(b.j.XB(a,d,c),10);return void 0===a||null===a||isNaN(a)?e?e:g:a};b.j.prototype.RT=function(a){return-1===a?void 0:a};b.j.prototype.i0=function(a,d,c,e){var g={};this.customPagingOptions&&
((g=this.customPagingOptions.call(this,a))||(g={}));d=d||{};this.lastFetchSize=this.YB(g,a,"limit",d.fetchSize,this.fetchSize);this.offset=this.YB(g,a,"offset",d.startIndex,0);this.lastFetchCount=this.YB(g,a,"count",this.lastFetchCount,this.lastFetchCount);this.totalResults=this.RT(this.YB(g,a,"totalResults",this.totalResults,this.totalResults));this.hasMore=this.Gda(b.j.XB(g,a,"hasMore"),this.offset,this.lastFetchSize,this.totalResults);e||(this.totalResults=this.o$(this.RT(parseInt(b.j.XB(g,a,"totalResults"),
10)),this.hasMore,this.offset,parseInt(b.j.XB(g,a,"count"),10),c&&Array.isArray(c)?c.length:0));!this.Xa()&&this.totalResults&&this.totalResults!==this.lastFetchCount&&this.lastFetchSize&&this.TE(this.lastFetchSize)};b.j.prototype.o$=function(a,b,c,e,g){return!b&&isNaN(a)?(isNaN(e)?g:e)+c:this.totalResults};b.j.prototype.Gda=function(a,d,c,e){return b.j.Jl(a)?a:void 0===e||null===e?!0:d+c>e?!1:!0};b.j.XB=function(a,b,c){return a.hasOwnProperty(c)?a[c]:b?b[c]:void 0};b.j.prototype.uJ=function(){return b.j.Jl(this.offset)?
this.offset:0};b.j.prototype.create=function(a,d){function c(d,c){d.save(a instanceof b.t?null:a,c);return d}function e(a,b){if(d.wait){if(g.Xa()||f)return g.$d(function(){return Promise.resolve(void 0)})}else return g.add(a,b)}var g=this;d=d||{};var f=this.zf(d),k=this.xx(a,d,!1),l=d.success,m=d.context;d.context=this;d.success=function(a,b,c){c.xhr&&(d.xhr=c.xhr);d.wait&&g.add(k,d);l&&l.call(null!=m?m:g,a,b,d)};if(null==k)return!1;d.forceNew=null!=k.ag();var n=b.t.$p(d);k.yv(this);if(f||this.Xa())return new Promise(function(a){n.merge=
!0;n.deferred=!0;e(k,n).then(function(){d.success=function(b,c,e){e.xhr&&(d.xhr=e.xhr);d.wait?(g.Xa()&&(n.force=!0),g.add(k,n).then(function(){l&&l.call(null!=m?m:g,b,c,d);a(b)})):(l&&l.call(null!=m?m:g,b,c,d),a(b))};var b=c(k,d);b||a(b)})});n.merge=!0;e(k,n);return c(k,d)};b.b.g("Collection.prototype.create",{create:b.j.prototype.create});b.j.prototype.O4=function(a){var b=[],c;this.Gf("pluck");for(c=0;c<this.be();c+=1)b.push(this.at(c).get(a));return b};b.b.g("Collection.prototype.pluck",{O4:b.j.prototype.O4});
b.j.prototype.a6=function(a,b){return this.Yw(this.sy(a,b))};b.b.g("Collection.prototype.where",{a6:b.j.prototype.a6});b.j.prototype.sy=function(a,d){d=d||{};var c=this.zf(d),e=this;if(this.Xa())return new Promise(function(c,g){e.Kca({query:a,all:!0,success:function(a,b){c(b)},error:function(a,c,f){g(b.j.yw(a,c,f,e,d))}})});var g=[],f,k;for(f=0;f<this.be();f+=1)k=this.at(f),k.k6(a)&&g.push(k);return c?new Promise(function(a){a(g)}):g};b.j.prototype.b6=function(a,d){d=d||{};var c=this.zf(d),e=this;
if(this.Xa()||c)return e.$d(function(){return new Promise(function(b,c){return e.sy(a,d).then(function(a){a=e.YY(a);b(a)},function(a){c(a)})})});c=this.sy(a,d);c=this.YY(c);c[b.j.Ld]=-1;c.Kk();return c};b.b.g("Collection.prototype.whereToCollection",{b6:b.j.prototype.b6});b.j.prototype.YY=function(a){var b=this.bU(!1);b.Oq(a,!1);b.Vx();b.Kk();return b};b.j.prototype.Gf=function(a){if(this.Xa())throw Error(a+" not valid on a virtual Collection");};b.j.prototype.map=function(a,b){var c=[],e;this.Gf("map");
this.Ec().forEach(function(g){e=a.call(b||this,g);c.push(e)});return c};b.b.g("Collection.prototype.map",{map:b.j.prototype.map});b.j.prototype.each=function(a,b){this.Gf("each");this.Ec().forEach(a,b)};b.b.g("Collection.prototype.each",{each:b.j.prototype.each});b.j.prototype.size=function(){return this.be()};b.b.g("Collection.prototype.size",{size:b.j.prototype.size});b.j.prototype.v5=function(a,d){var c=[],e;this.Gf("sortBy");this.Ec().forEach(function(a){c.push(a)});e=this;c.sort(function(c,h){var k,
l;if(f.isFunction(a))return k=a.call(d||e,c),l=a.call(d||e,h),b.j.Gl(k,l,e.sortDirection);k=c.get(a);l=h.get(a);return b.j.Gl(k,l,e.sortDirection)});return c};b.b.g("Collection.prototype.sortBy",{v5:b.j.prototype.v5});b.j.prototype.C3=function(a,b){var c={},e;this.Gf("groupBy");this.Ec().forEach(function(g){e=f.isFunction(a)?a.call(b||this,g):g.get(a);void 0===c[e]&&(c[e]=[]);c[e].push(g)},this);return c};b.b.g("Collection.prototype.groupBy",{C3:b.j.prototype.C3});b.j.prototype.O3=function(a,b){var c=
{},e;this.Gf("indexBy");this.Ec().forEach(function(g){e=f.isFunction(a)?a.call(b||this,g):g.get(a);c[e]=g},this);return c};b.b.g("Collection.prototype.indexBy",{O3:b.j.prototype.O3});b.j.prototype.min=function(a,b){var c={},e,g;this.Gf("min");if(0==this.Yc())return null;c=this.Pb(0);e=a.call(b||this,this.Pb(0));this.Ec().forEach(function(f,k){1<=k&&(g=a.call(b||this,f),g<e&&(c=f,e=g))},this);return c};b.b.g("Collection.prototype.min",{min:b.j.prototype.min});b.j.prototype.max=function(a,b){var c=
{},e,g;this.Gf("max");if(0==this.Yc())return null;c=this.Pb(0);e=a.call(b,this.Pb(0));this.Ec().forEach(function(f,k){1<=k&&(g=a.call(b||this,f),g>e&&(c=f,e=g))},this);return c};b.b.g("Collection.prototype.max",{max:b.j.prototype.max});b.j.prototype.filter=function(a,b){var c=[];this.Gf("filter");this.Ec().forEach(function(e){a.call(b||this,e)&&c.push(e)});return c};b.b.g("Collection.prototype.filter",{filter:b.j.prototype.filter});b.j.prototype.c6=function(a){var b=[],c,e,g,f;this.Gf("without");
for(var k,l=0;l<this.Ec().length;l++){f=!0;k=this.Pb(l);for(c=0;c<arguments.length;c+=1)if(g=arguments[c].qp(),e=arguments[c].ag(),k.tp(e,g)){f=!1;break}f&&b.push(k)}return b};b.b.g("Collection.prototype.without",{c6:b.j.prototype.c6});b.j.prototype.s2=function(a){var b=[],c,e,g,f,k;this.Gf("difference");for(var l,m=0;m<this.Ec().length;m++){k=!0;l=this.Pb(m);for(c=0;c<arguments.length;c+=1){for(e=0;e<arguments[c].length;e++)if(f=arguments[c][e].qp(),g=arguments[c][e].ag(),l.tp(g,f)){k=!1;break}if(!k)break}k&&
b.push(l)}return b};b.b.g("Collection.prototype.difference",{s2:b.j.prototype.s2});b.j.prototype.Pf=function(){return 0===this.be()};b.b.g("Collection.prototype.isEmpty",{Pf:b.j.prototype.Pf});b.j.prototype.F1=function(a,b){this.Gf("any");for(var c,e=0;e<this.Yc();e+=1)if(c=this.Pb(e),a.call(b||this,c))return!0;return!1};b.b.g("Collection.prototype.any",{F1:b.j.prototype.F1});b.j.prototype.y2=function(a,b){var c=this.zf(b),e=this;if(this.Xa()||c)return this.$d(function(){return new Promise(function(c){e.sy(a,
b).then(function(a){a&&0<a.length&&c(a[0]);c(null)})})});c=this.sy(a,b);return 0<c.length?c[0]:null};b.b.g("Collection.prototype.findWhere",{y2:b.j.prototype.y2});b.j.prototype.slice=function(a,b,c){var e=this.zf(c);c=[];if(void 0===b){if(this.Xa()&&!this.wq())throw Error("End must be set for virtual collections with no totalResults");b=this.Yc()}if(e||this.Xa()){var g=this;return this.$d(function(){return g.Vr(a,b)})}for(e=a;e<b;e+=1)c.push(this.Pb(e));return c};b.b.g("Collection.prototype.slice",
{slice:b.j.prototype.slice});b.j.prototype.set=function(a,b){return this.SL(a,!0,b,this.zf(b)||this.Xa())};b.b.g("Collection.prototype.set",{set:b.j.prototype.set});b.j.i_=function(a,b,c,e,g){if(c)for(c=b.length-1;0<=c;c-=1)-1==e.indexOf(c)&&a.Nq(b[c],c,g)};b.j.prototype.Ela=function(a,b,c,e){if(this.hC()||!c||!e)return{index:a,nP:!1};c=this.Yc();if(a>=c||b>=c)return{index:a,nP:!1};c=this.Pb(a);e=this.Pb(b);this.hD(a,e);e.zv(a);this.hD(b,c);c.zv(b);return{index:b,nP:b!==a}};b.j.prototype.SL=function(a,
d,c,e){c=c||{};var g=void 0===c.add?!0:c.add,f=void 0===c.remove?!0:c.remove,k=void 0===c.merge?!0:c.merge,l=[],m=null,n;d&&(a=this.parse(a));n=Array.isArray(a)?a:[a];if(e){var p=this;return this.$d(function(){return p.Qba(n,p.Ec(),c,f,g,k)})}d=!1;for(a=0;a<n.length;a+=1)if(m=this.q1(this.xx(n[a],c,!0),g,k,e),-1!==m){var m=this.Ela(m,a,f,g),r=m.index;m.nP&&(d=!0);-1===l.indexOf(r)&&l.push(r)}d&&this.Kb(c.silent,b.Y.D.SORT,this,c.add?{add:!0}:null,null);b.j.i_(this,this.Ec(),f,l,c)};b.j.prototype.Qba=
function(a,d,c,e,g,f){var k=[],l,m=this;return new Promise(function(n,p){function r(b){return new Promise(function(d,e){m.q1(m.xx(a[b],c,!0),g,f,!0).then(function(a){-1!==a&&k.push(a);d(b+1)},e)})}var s=Promise.resolve(0);for(l=0;l<a.length;l+=1)s=s.then(r);s.then(function(){b.j.i_(m,d,e,k,c);n(void 0)},p)})};b.j.prototype.q1=function(a,b,c,e){function g(e,g,f){var h=g?g.index:-1;if(g&&g.m){if(c){var k={merge:c};if(f)return new Promise(function(b){e.Cl(a,k,!1,!0).then(function(){b(h)})});e.add(a,
k)}}else if(b){if(f)return new Promise(function(b){e.Cl(a,k,!1,!0).then(function(){b(e.be()-1)})});e.add(a);h=e.be()-1}return h}if(e||this.Xa()){var f=this;return new Promise(function(b){f.Gh(a,{silent:!0},e).then(function(a){g(f,a,!0).then(function(a){b(a)})})})}var k=this.Gh(a);return g(this,k,!1)};b.j.prototype.toJSON=function(){var a=[];this.Gf("toJSON");this.Ec().forEach(function(b){a.push(b.toJSON())});return a};b.b.g("Collection.prototype.toJSON",{toJSON:b.j.prototype.toJSON});b.j.prototype.first=
function(a,b){var c=this.zf(b),e=this.be(),g=[];a?e=a:a=1;c=this.Xa()||c;if(1===a){if(c){var f=this;return this.$d(function(){return f.kI(0,null)})}return 0<this.Yc()?this.Pb(0):null}e>this.Yc()&&(!this.Xa()||this.wq())&&(e=this.Yc());if(c)return f=this,this.$d(function(){return f.Vr(0,e)});for(c=0;c<e;c+=1)g.push(this.Pb(c));return g};b.b.g("Collection.prototype.first",{first:b.j.prototype.first});b.j.prototype.indexOf=function(a,b){var c=this.zf(b);if(this.Xa()||c){var e=this;return this.$d(function(){return e.Gh(a,
null,!0).then(function(a){return a.index})})}return this.Gh(a).index};b.b.g("Collection.prototype.indexOf",{indexOf:b.j.prototype.indexOf});b.j.prototype.contains=function(a,b){var c=this.zf(b);if(this.Xa()||c){var e=this;return this.$d(function(){return e.Gh(a,null,!0).then(function(a){return-1<a.index})})}return-1<this.Gh(a).index};b.b.g("Collection.prototype.contains",{contains:b.j.prototype.contains});b.j.prototype.N3=b.j.prototype.contains;b.b.g("Collection.prototype.include",{N3:b.j.prototype.N3});
b.j.prototype.Hha=function(a){a=this.vW(a);return void 0!==a?a.index:-1};b.j.prototype.pop=function(a){var b=this.zf(a);if(this.Xa()||b){var c=this;return this.at(this.be()-1,{deferred:b}).then(function(b){c.remove(b,a);return b})}b=this.at(this.be()-1);this.remove(b,a);return b};b.b.g("Collection.prototype.pop",{pop:b.j.prototype.pop});b.j.prototype.push=function(a,b){var c=this.zf(b);this.Fq(1);return this.Yw(this.Cl(a,b,!1,c))};b.b.g("Collection.prototype.push",{push:b.j.prototype.push});b.j.prototype.lastIndexOf=
function(a,d){var c;this.Gf("lastIndexOf");void 0===d&&(d=0);for(c=this.be()-1;c>=d;c-=1)if(b.b.Yv(a,this.at(c)))return c;return-1};b.b.g("Collection.prototype.lastIndexOf",{lastIndexOf:b.j.prototype.lastIndexOf});b.j.prototype.XW=function(a){return void 0===a?[]:a.split(",")};b.j.oea=function(a){a=Array.isArray(a)?a:[a];var d="",c,e,g,h;for(g=0;g<a.length;g++){c=a[g];for(h in c)if(c.hasOwnProperty(h))for(var k=Array.isArray(c[h])?c[h]:[c[h]],l=0;l<k.length;l++){if(b.t.aQ(k[l])){e=k[l].value;var m=
null,m=k[l].comparator,m=f.isFunction(m)?m(null,h,e):m;e=h+m+e}else e=h+"\x3d"+c[h];d+=e+"+"}d=d.substring(0,d.length-1)+","}return","===d.substring(d.length-1)?d.substring(0,d.length-1):d};b.j.prototype.P6=function(a){var d={},c;for(c in a)a.hasOwnProperty(c)&&(d[c]=a[c]);if((a=this.comparator)&&b.Fa.od(a)){a=this.XW(a);for(c=0;c<a.length;c++)d.sort=0===c?a[c]:d.sort+(","+a[c]);d.sortDir=this.YW()}this.Xa()&&(d[b.j.Ld]=this.vk(d));return d};b.j.prototype.E6=function(){if(f.isFunction(this.customURL))return!0;
var a=this.SP(null);return b.j.Jl(a)};b.j.prototype.SP=function(a){var d=b.t.$m(this,"url");if(this.Xa()){var c=a.all,e=null;e=c?(e=this.totalResults)?e:this.vk(a):this.vk(a);d=d&&-1<d.indexOf("?")?d+"\x26":d+"?";d+="limit\x3d"+e;c||(b.j.Jl(a.startIndex)&&(d+="\x26offset\x3d"+a.startIndex),a.startID&&(d+="\x26fromID\x3d"+a.startID),a.since&&(d+="\x26since\x3d"+a.since),a.until&&(d+="\x26until\x3d"+a.until));a.query&&(a=b.j.oea(a.query))&&0<a.length&&(d+="\x26q\x3d"+a);if((a=this.comparator)&&b.Fa.od(a))for(a=
this.XW(a),c=this.YW(),e=0;e<a.length;e++)d=0===e?d+("\x26orderBy\x3d"+a[e]+":"+c):d+(","+a[e]+":"+c);d+="\x26totalResults\x3dtrue"}return d};b.j.prototype.YW=function(){return-1===this.sortDirection?"desc":"asc"};b.j.prototype.sync=function(a,b,c){return window.oj.sync(a,b,c)};b.j.Ld="fetchSize"});