/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","knockout","promise"],function(b,f){b.Xr={};b.Xr.Gc={viewPath:"text!views/",viewSuffix:".html",modelPath:"viewModels/",initializeMethod:"initialize",disposeMethod:"dispose",activatedHandler:"handleActivated",attachedHandler:"handleAttached",detachedHandler:"handleDetached",bindingsAppliedHandler:"handleBindingsApplied",deactivatedHandler:"handleDeactivated",transitionCompletedHandler:"handleTransitionCompleted"};o_("ModuleBinding.defaults",b.Xr.Gc,b);(function(){function a(a,
d,e,g,h,k,l){var n=d.canAnimate;if(null==n||n.call(d,a)){var p,s;if(n=d.prepareAnimation.call(d,a))p=n.newViewParent,s=n.oldViewParent;var F=p||e;s&&s!==e?c(g,s):F===e&&k(null);F!==e&&f.virtualElements.setDomNodeChildren(F,[]);h(F);var r=Array.prototype.slice.call(F.childNodes),z=!1,A=function(){z||(z=!0,e!==F&&m(e,r))},E=k.bind(null,s);a.newViewParent=p;a.oldViewParent=s;a.oldViewNodes=g;a.removeOldView=E;a.insertNewView=A;var L=function(){E();A();l()};return d.animate.call(d,a).then(L,function(){L();
b.r.error("ojModule animation promise was rejected")})}}function d(a,b,c){b=b||a;var d=[];c&&a===b&&(c.parentNode.removeChild(c),d.push(c));f.virtualElements.setDomNodeChildren(b,d)}function c(a,b){a.forEach(function(a){b.appendChild(a)})}function e(a,b,c){if(a&&a[b]){var d={element:c[0],valueAccessor:c[1]};2<c.length&&(d.viewModel=c[2],3<c.length&&(d["boolean"===typeof c[3]?"fromCache":"cachedNodes"]=c[3]));return f.ignoreDependencies(a[b],a,[d])}}function g(a,c,d){if(null!=a&&(c=b.Xr.Gc[c],null!=
c&&a&&(c=a[c],"function"===typeof c))){var e=void 0;d&&(e={element:d[0],valueAccessor:d[1]},2<d.length&&(e["boolean"===typeof d[2]?"fromCache":"cachedNodes"]=d[2]));return f.ignoreDependencies(c,a,[e])}}function h(a,b,c){var d=[];for(a=f.virtualElements.firstChild(a);null!=a&&a!=c;a=a.nextSibling)a!=b&&d.push(a);return d}function k(a,b){var c=[],d=f.virtualElements.firstChild(a);l(d,b,function(a){c.push(a)});return c}function l(a,b,c){for(;null!=a;){var d=f.virtualElements.nextSibling(a),e=a.nodeType;
a===b||1!==e&&8!==e||c(a);a=d}}function m(a,b){for(var c=b.length-1;0<=c;c--)f.virtualElements.prepend(a,b[c])}function n(a,c){if(null!=b.Components)for(var d=0;d<a.length;d++)c?b.Components.Rm(a[d]):b.Components.gp(a[d])}function p(a){if("string"===typeof a)a=f.utils.parseHtmlFragment(a);else if(window.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType)a=f.utils.arrayPushAll([],a.childNodes);else if(Array.isArray(a))a=f.utils.arrayPushAll([],a);else throw"The View ("+a+") has an unsupported type";
return a}function r(a){return new Promise(function(b){require([a],function(a){b(a)},function(){throw Error("ojModule failed to load "+a);})})}function s(a){return a?new Promise(function(b){a.then(b,b)}):a}f.bindingHandlers.ojModule={init:function(q,t,v,w,u){function y(a){if(a!=D)throw Error("Promise cancelled because ojModule is fetching new View and ViewModel");}function x(a){g(a,"disposeMethod",[q,t])}var B,O,J={},F,D=-1,z,A;f.utils.domNodeDisposal.addDisposeCallback(q,function(){x(B);for(var a=
Object.keys(J),b=0;b<a.length;b++)x(J[a[b]].Xo)});8===q.nodeType&&(f.virtualElements.setDomNodeChildren(q,[]),A=q.nextSibling);f.computed(function(){D++;var v=0===D,w=f.utils.unwrapObservable,C=w(t()),M,G,I,N,H,P,Q,W;"string"===typeof C?M=C:(M=w(C.name),G=w(C.viewName),I=w(C.params),N=w(C.viewModelFactory),H=w(C.createViewFunction),P=w(C.cacheKey),Q=w(C.lifecycleListener),W=w(C.animation));var w=e(Q,"activated",[q,t]),K,V,Z=null==P?null:J[P];if(null!=Z)delete J[P],K=Promise.resolve(Z.view),V=Promise.resolve(Z.Xo);
else if(null!=N&&(V=f.ignoreDependencies(N.createViewModel,N,[I,t])),null==V&&null!=M&&(V=r(b.Xr.Gc.modelPath+M)),null!=V&&(V=V.then(function(a,b){y(a);return b="function"===typeof b?new b(I):g(b,"initializeMethod",[q,t])||b}.bind(null,D)),null!=H&&(K=V.then(function(a,b){y(a);if(null==b)throw"createViewFunction option cannot be used when the ViewModel is null";var c=b[H];if(null==c)throw"function specified by the createViewFunction option was not found on the ViewModel";return c.call(b)}.bind(null,
D)))),null==K)if(G=null==G?M:G,null!=G)K=r(b.Xr.Gc.viewPath+G+b.Xr.Gc.viewSuffix);else throw Error("View name must be specified");if(null==K)throw Error("ojModule is missing a View");var X;null!=V&&(X=V.then(function(a,b){y(a);return g(b,"activatedHandler",[q,t])}.bind(null,D)));Promise.all([K,V,w,X,O]).then(function(b,w){if(b==D){var y=w[0];if(null==y)throw"The module's View was resolved to null";var r=p(y),C=w[1],L=!1,M,G=h(q,z,A),H=k(q,z);null!=F&&(L=!0,M=G,z||(z=document.createElement("div"),
z.className="oj-helper-module-cache",f.virtualElements.prepend(q,z)));var K=!1,y=function(a){K||(K=!0,L?c(G,z):H.forEach(function(a){f.cleanNode(a)}),d(q,a||q,z),v||(e(Q,"detached",[q,t,B,M]),g(B,"detachedHandler",[q,t,M]),e(Q,"deactivated",[q,t,B]),g(B,"deactivatedHandler",[q,t])),L?(n(M,!1),J[F]={Xo:B,view:M}):x(B),B=C,F=P)},N=function(a){a=a||q;m(a,r);var b=null!=Z;b&&n(r,!0);e(Q,"attached",[a,t,C,b]);g(C,"attachedHandler",[a,t,b]);if(!b){var c=u.createChildContext(C,void 0,function(a){a.$module=
C;a.$params=I});l(r[0],z,function(a){f.applyBindings(c,a)});e(Q,"bindingsApplied",[a,t,C]);g(C,"bindingsAppliedHandler",[a,t])}},ga=function(){e(Q,"transitionCompleted",[q,t,C]);g(C,"transitionCompletedHandler",[q,t])};if(null!=W){var ja=a({node:q,valueAccessor:t,isInitial:v,oldViewModel:B,newViewModel:C},W,q,G,N,y,ga);O=s(ja)}else O=void 0;O||(y(null),N(null),ga())}}.bind(null,D),function(a,c){a==D&&null!=c&&b.r.error(c)}.bind(null,D))},null,{disposeWhenNodeIsRemoved:q});return{controlsDescendantBindings:!0}}};
f.virtualElements.allowedBindings.ojModule=!0})()});