/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojbutton","ojs/ojmenu","ojs/ojlistview"],function(b,f){b.sd=function(a,b,e){this.u=a;this.Ab=b;this.uO=e};b.sd.prototype.Oe=function(){this.Ab.removeClass("oj-navigationlist-expanded oj-navigationlist-vertical")};b.sd.prototype.Rr=function(){};b.sd.prototype.Or=function(){};b.sd.prototype.YP=function(){return!1};b.sd.prototype.EF=function(){};b.sd.prototype.OF=function(a,b){a.attr("aria-selected",b?"true":"false")};b.sd.prototype.iF=function(){};
b.sd.prototype.cQ=function(){};b.sd.prototype.dQ=function(){};b.sd.prototype.sp=function(b,c,e){return a.q.sp.apply(this.u,arguments)};b.sd.prototype.Tr=function(b){return a.q.Tr.apply(this.u,arguments)};b.sd.prototype.Re=function(b){return a.q.Re.apply(this.u,arguments)};b.sd.prototype.vp=function(b,c){a.q.vp.apply(this.u,arguments)};b.sd.prototype.Init=function(){this.Ab.addClass("oj-navigationlist-expanded oj-navigationlist-vertical")};b.sd.prototype.xh=function(b){return a.q.xh.apply(this.u,arguments)};
b.sd.prototype.uv=function(){};b.sd.prototype.GP=function(){};b.sd.prototype.Fr=function(){};b.bg=function(a,c,e){b.bg.q.constructor.call(this,a,c,e)};b.b.ga(b.bg,b.sd,"oj.HorizontalNavListHandler");b.bg.prototype.Oe=function(){this.Ab.removeClass("oj-navigationlist-expanded oj-navigationlist-horizontal");this.Ab.find("."+this.u.Qr).remove()};b.bg.prototype.OF=function(a,b){a.attr("aria-pressed",b?"true":"false")};b.bg.prototype.sp=function(b,c,e){b===f.ui.keyCode.LEFT?b=this.u.Qf()?f.ui.keyCode.DOWN:
f.ui.keyCode.UP:b===f.ui.keyCode.RIGHT&&(b=this.u.Qf()?f.ui.keyCode.UP:f.ui.keyCode.DOWN);b=a.q.sp.call(this.u,b,c,e);"top"===this.u.V.options.edge&&this.u.hb.elem[0].scrollIntoView(!1);return b};b.bg.prototype.Tr=function(a){return a===this.u.MF||a===this.u.kF||a===this.u.pv||a===this.u.Fz};b.bg.prototype.EF=function(a){a=this.u.rE(a);a.attr("role","button");a[0].hasAttribute("aria-selected")&&(a.attr("aria-pressed","false"),a.removeAttr("aria-selected"))};b.bg.prototype.iF=function(){var a=this;
this.u.element.attr("role","toolbar");this.u.element.find("."+this.u.bf()+":visible").each(function(b){0<b&&a.ZS(this,b)})};b.bg.prototype.ZS=function(a,b){var e=f(a),g=e.prev();0<b&&e.is(":visible")&&g.length&&!g.is("li."+this.u.Qr)&&e.before('\x3cli role\x3d"separator" class\x3d"'+this.u.Qr+'"\x3e\x3c/li\x3e')};b.bg.prototype.cQ=function(a,b){this.ZS(a,b.index)};b.bg.prototype.dQ=function(a){a=f(a);var b=a.prev();b.length&&b.is("li."+this.u.Qr)?b.remove():(a=a.next(),a.is("li."+this.u.Qr)&&a.remove())};
b.bg.prototype.xh=function(a){return this.u.oe(f(a))[0].hasAttribute("aria-pressed")};b.bg.prototype.Init=function(){this.Ab.addClass("oj-navigationlist-expanded oj-navigationlist-horizontal")};b.bg.prototype.uv=function(){};b.Tj=function(a,c,e){b.Tj.q.constructor.call(this,a,c,e)};b.b.ga(b.Tj,b.sd,"oj.CollapsibleNavListHandler");b.Tj.prototype.Oe=function(){this.Ab.removeClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};b.Tj.prototype.Init=function(){this.Ab.addClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};
b.Tj.prototype.Rr=function(b,c){a.q.fF.apply(this.u,arguments)};b.Tj.prototype.Or=function(b,c){a.q.dF.apply(this.u,arguments)};b.Tj.prototype.YP=function(a,b,e,g){var h=0<e.children("."+this.u.Hi()).length;if(b===this.u.pv||b===this.u.Fz)return b===this.u.pv&&!this.u.Qf()||b===this.u.Fz&&this.u.Qf()?this.u.Re(e)===this.u.$i&&this.u.Xm(e,a,!0,g,!0,!0):this.u.Re(e)===this.u.Zi&&this.u.op(e,a,!0,g,!0,!0,!0),!0;if(h&&(b===f.ui.keyCode.ENTER||b===f.ui.keyCode.SPACE)){if(0>=e.length)return;this.u.Re(e)===
this.u.Zi?this.u.op(e,null,!0,g,!0,!0,!0):this.u.Re(e)===this.u.$i&&this.u.Xm(e,null,!0,g,!0,!0);return!0}return!1};b.Tj.prototype.uv=function(){};b.cd=function(a,c,e){b.cd.q.constructor.call(this,a,c,e);this.xO=[]};b.b.ga(b.cd,b.Tj,"oj.SlidingNavListHandler");b.cd.prototype.Oe=function(){this.Ab.removeClass("oj-navigationlist-slider oj-navigationlist-vertical");this.vD.remove()};b.cd.prototype.F0=function(a,b,e){var f=this,h=this.u.SN(),k=h.outerWidth()/2,l=this.u.Qf();b||(k*=-1);l?(h.css({"margin-right":k}),
h.animate({"margin-right":"0px"},400,"swing",function(){f.oD(a,b,e)})):(h.css({"margin-left":k}),h.animate({"margin-left":"0px"},400,"swing",function(){f.oD(a,b,e)}))};b.cd.prototype.oD=function(a,b,e){null!==this.u.He&&(e&&(e=this.u.ud(e[0]),this.u.bi("currentItem",e)),b?this.u.gF(a.children("."+this.u.Hi())):this.u.eF(a.children("."+this.u.Hi())))};b.cd.prototype.Rr=function(a,b){var e=f(a).parents(".oj-navigationlist-item-element:first"),g=e.children("."+this.u.Hi()),h,k=null,l=e.closest("."+this.u.en);
if(0<l.length){l.removeClass(this.u.en);e.addClass(this.u.en);var k=g.find("."+this.u.bf()+":eq(0)"),m=e.parentsUntil(l,"ul"),m=l.is(this.u.element)?m.get().concat(l.get()):m.get(),n=this,p,m=f(m.reverse());m.each(function(a,b){h=f(b).is(n.u.element)?n.u.pE():n.u.LN(f(b).parent());p=a===m.length-1?e:f(m.get(a+1)).parent();n.g$(n.u.ud(p[0]),n.u.LN(p),h);n.xO.push(p)})}b?this.F0(e,!0,k):this.oD(e,!0,k);this.u.element.focus();e.siblings().attr("aria-hidden","true");e.children("."+this.u.yg()).children("."+
this.u.Xj).attr("aria-hidden","true");g.removeAttr("aria-hidden");a.css("display","");e.addClass("oj-skipfocus")};b.cd.prototype.Or=function(a,b){var e=a.children("."+this.u.Hi()),f=a.parent();a.children("."+this.u.yg()).children("."+this.u.Xj).removeAttr("aria-hidden");e.attr("aria-hidden","true");a.siblings().removeAttr("aria-hidden");a.removeClass("oj-skipfocus");a.removeClass(this.u.en);0===a.closest("."+this.u.en).length&&(f.closest("."+this.u.bf()).addClass(this.u.en),this.u.element.is(f)&&
this.u.element.addClass(this.u.en));b?this.F0(a,!1,e.parent()):this.oD(a,!1,e.parent());this.Lja();this.u.element.focus()};b.cd.prototype.OF=function(a,b){b?a.attr("aria-describedby","selectedLabel"):a.removeAttr("aria-describedby")};b.cd.prototype.Re=function(a){a=this.u.oe(a).attr("aria-expanded");return"true"===a?this.u.$i:"false"===a?this.u.Zi:this.u.vQ};b.cd.prototype.vp=function(a,b){b===this.u.$i?(this.u.oe(a).attr("aria-expanded","true"),a.removeClass(this.u.DP).addClass(this.u.MP)):b===this.u.Zi&&
(this.u.oe(a).attr("aria-expanded","false"),a.removeClass(this.u.MP).addClass(this.u.DP))};b.cd.prototype.EF=function(a,b){var e=this.u.oe(a);e.attr("role","menuitem");b.attr("id")||b.uniqueId();var f=a.children("."+this.u.Hi());0<f.length&&(e.attr("aria-haspopup","true"),f.attr("role","menu"),f.css("display",""),a.removeAttr("aria-expanded"),e.attr("aria-expanded","false"))};b.cd.prototype.iF=function(){this.u.element.attr("role","menu")};b.cd.prototype.Init=function(a){this.Ab.addClass("oj-navigationlist-slider oj-navigationlist-vertical");
a.element.addClass("oj-navigationlist-current");this.Z$(a);this.Gga()};b.cd.prototype.Z$=function(a){var b;this.vD=f(document.createElement("div"));this.vD.addClass("oj-navigationlist-toolbar");this.dm=f(document.createElement("a"));this.Gx=f(document.createElement("span"));this.Gx.addClass("oj-navigationlist-previous-icon oj-component-icon oj-clickable-icon-nocontext").attr("role","img").attr("alt",this.uO.A("previousIcon"));this.Gx.css("visibility","hidden");this.dm.addClass("oj-navigationlist-previous-link").attr("tabindex",
"-1").append(this.Gx);this.$w=f(document.createElement("label"));this.$w.addClass("oj-navigationlist-current-header").text(this.u.pE());this.KD=f(document.createElement("span"));this.KD.attr("role","separator").attr("aria-orientation","vertical").addClass("oj-navigationlist-toolbar-separator");this.Hh=f(document.createElement("button"));this.Hh.addClass("oj-navigationlist-hierarchical-button");this.Af=f(document.createElement("ul"));this.Af.addClass("oj-navigationlist-hierarchical-menu").hide();b=
f(document.createElement("label"));b.addClass("oj-helper-hidden-accessible").attr("aria-hidden","true").attr("id","selectedLabel");b.text(this.uO.A("selectedLabel"));this.dm.append(this.$w);this.vD.append(this.dm).append(this.KD).append(this.Hh).append(this.Af).append(b);this.Ab.prepend(this.vD);this.lD(a.hierarchyMenuDisplayThresholdLevel)};b.cd.prototype.GP=function(){var a=this.xO.pop();a&&this.u.Xm(a,null,!0,null,!0,!0)};b.cd.prototype.Gga=function(){var a=this,b=this.Af.uniqueId().attr("id");
this.Af.ojMenu({openOptions:{position:{my:"end top",at:"end bottom"}},select:function(b,c){for(var h=c.item.nextAll(),k,l,m=a.xO,n=c.item.data("key");0<m.length&&(l=m.pop(),k=a.u.ud(l[0]),a.u.Xm(f(l),null,!0,k,!0,!0),n!==k););h.remove();c.item.remove();a.Af.ojMenu("refresh")}});this.Hh.ojButton({label:this.uO.A("hierMenuBtnLabel"),display:"icons",icons:{start:"oj-fwk-icon oj-hier-icon"},menu:"#"+b,disabled:!0,chroming:"half"})};b.cd.prototype.g$=function(a,b,e){if(this.Hh){var g=this.Af.find("li").length,
h=f(document.createElement("li")),k=f(document.createElement("a"));k.attr("href","#");h.append(k);if(0<g){for(var l=0;l<g;l++)0<l&&k.append(f(document.createElement("span")).addClass("oj-navigationlist-hvitem-space"));k.append(f(document.createElement("span")).addClass("oj-menu-item-icon oj-icon oj-navigationlist-level-indicator"))}g=f(document.createElement("span")).addClass("oj-navigationlist-hierarchical-menu-label");g.text(e);k.append(g);h.data("key",a);this.Af.append(h);this.Af.ojMenu("refresh");
this.lD(this.u.Ud("hierarchyMenuDisplayThresholdLevel"));this.Hh.ojButton("option","disabled",!1);this.Gx.css("visibility","visible");this.dm.attr("tabindex","0");this.$w.text(b)}};b.cd.prototype.Fr=function(a){this.u.Ud("hierarchyMenuDisplayThresholdLevel")!==a.hierarchyMenuDisplayThresholdLevel&&this.lD(a.hierarchyMenuDisplayThresholdLevel)};b.cd.prototype.lD=function(a){var b=this.Af.find("li").length;-1===a||b<a?(this.KD.css("visibility","hidden"),this.Hh.css("visibility","hidden")):b>=a&&(this.KD.css("visibility",
"visible"),this.Hh.css("visibility","visible"))};b.cd.prototype.Lja=function(){if(this.Hh){var a=this.Af.find("li").last().remove();this.Af.ojMenu("refresh");this.lD(this.u.Ud("hierarchyMenuDisplayThresholdLevel"));0===this.Af.children("li").length?(this.Hh.ojButton("option","disabled",!0),this.Gx.css("visibility","hidden"),this.dm.attr("tabindex","-1"),this.$w.text(this.u.pE())):this.$w.text(a.children("a").text())}};b.cd.prototype.uv=function(a,b){a.removeClass(this.u.en);b.removeAttr("role").removeAttr("aria-expanded").removeAttr("aria-describedby").removeAttr("aria-hidden")};
var a=function(a,c){function e(){}b.b.ga(e,a,"");f.extend(e.prototype,c);return e}(b.UK,{Xj:"oj-navigationlist-item-content",MP:"oj-expanded",DP:"oj-collapsed",en:"oj-navigationlist-current",Qr:"oj-navigationlist-divider",m7:"oj-navigationlist-category-divider",jG:"oj-navigationlist-item-label",tR:"oj-navigationlist-icon-only",AR:"oj-navigationlist-item-icon",Tqa:"oj-navigationlist-horizontal",SR:"oj-navigationlist-has-icons",TR:"oj-navigationlist-item-no-icon",H8:"oj-navigationlist-item-title",UR:"oj-navigationlist",
VR:"oj-navigationlist-touch",I8:"oj-navigationlist-listview-container",Zz:"IsTitleAttrDueToTruncation",TF:"oj-navigationlist-app-level",tG:"oj-navigationlist-page-level",oG:"navigationListItemIconHastitle",LN:function(a){a=this.mE(a);return a.is("a")?f.trim(a.text()):f.trim(a.find("."+this.H8).text())},mE:function(a){var b=a.children("."+this.Xj);0===b.length&&(b=a.children("."+this.yg()).children("."+this.Xj),0===b.length&&(b=a.children("."+this.yg()).children(":not(."+this.sm()+"):not(."+this.Jj()+
")")));return b},Qf:function(){return"rtl"===this.V.ec()},cp:function(){this.$b.iF();a.q.cp.apply(this,arguments)},b4:function(a,b){this.$b.cQ(a,b)},jO:function(b){this.$b.dQ(b);a.q.jO.apply(this,arguments)},I_:function(a){var b=a.children();a.removeAttr("style").removeClass(this.SR).removeAttr("aria-hidden");for(a=0;a<b.length;a++){var e=b[a],e=f(e);if(e.hasClass(this.Qr))e.remove();else{var g=this.mE(e);g.removeClass(this.Xj).removeClass(this.TR).removeAttr("aria-haspopup");var h=g.children("."+
this.AR);h&&0<h.length&&(h.removeAttr("role"),h.removeAttr("aria-label"),this.Uja(h));e.removeClass("oj-default").removeAttr("role").removeAttr("aria-disabled").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-pressed");h=this.oe(e);h.removeAttr("role").removeAttr("aria-hidden").removeAttr("aria-pressed");g.children("."+this.jG).contents().unwrap();h.data(this.Zz)&&h.removeAttr("title");h=e.children("ul");0<h.length?(this.$b.uv(e,g,h),this.I_(h)):this.$b.uv(e,g)}}},Cz:function(b){return b.hasClass(this.Xj)||
b.hasClass(this.sm())||b.hasClass(this.Jj())?!1:a.q.Cz.apply(this,arguments)},bQ:function(a){return a.prop("nodeName").match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)&&!a.hasClass(this.Xj)||a.hasClass("oj-component")},Iia:function(a){var b={drillMode:"none"!==a.drillMode?"collapsible":"none",selection:null!==a.selection?[a.selection]:[],item:a.item,data:a.data,selectionMode:"single"};b.element=this.io;b.item.focusable=function(a){return f(a.data).is("li")?!f(a.data).hasClass("oj-disabled"):!f(a.parentElement).hasClass("oj-disabled")};
return b=f.extend(f.extend({},a),b)},pE:function(){return this.V.options.rootLabel?this.V.options.rootLabel:this.V.A("defaultRootLabel")},xv:function(){var b=this.V.element.attr("aria-labelledby");b?(this.element.attr("aria-labelledby",b),this.V.element.removeAttr("aria-labelledby")):this.element.attr("aria-label",this.pE());a.q.xv.apply(this,arguments)},NF:function(){this.element.attr("aria-labelledby")&&(this.V.element.attr("aria-labelledby",this.element.attr("aria-labelledby")),this.element.removeAttr("aria-labelledby"));
this.element.attr("aria-label")&&this.element.removeAttr("aria-label");a.q.NF.apply(this,arguments)},zm:function(d){var c=this,e=d.V.element;e.addClass(this.UR);b.v.Sd()&&e.addClass(this.VR);this.io=e.children("ul:first");0===this.io.length&&(this.io=f(document.createElement("ul")),e.append(this.io));e=f(document.createElement("div"));e.addClass(this.I8);this.io.wrap(e);d=this.Iia(d);a.q.zm.call(this,d);this.element.removeClass("oj-component-initnode");this.V._on(this.V.element,{mouseup:function(a){c.NH(a)},
"click .oj-navigationlist-previous-link":function(){c.SH()},"keydown .oj-navigationlist-previous-link":function(a){a.keyCode===f.ui.keyCode.ENTER&&c.SH()},"keydown .oj-navigationlist-element":function(a){a.keyCode!==f.ui.keyCode.ESCAPE||a.isDefaultPrevented()||c.SH()},"mouseenter a.oj-navigationlist-item-content":function(a){a=f(a.currentTarget);var b=a.find("."+c.jG);b[0].offsetWidth<b[0].scrollWidth&&!a.attr("title")&&(a.attr("title",b.text().trim()),a.data(c.Zz,"true"))},"mouseleave a.oj-navigationlist-item-content":function(a){var b=
f(a.currentTarget);b.data(c.Zz)&&(b.removeData(c.Zz),b.removeAttr("title"));c.NH(a)}})},SH:function(){this.$b.GP()},aY:function(){var a=this.V.options.drillMode,c=this.V.options.edge;this.$b="sliding"===a?new b.cd(this,this.V.element,this.V):"collapsible"===a?new b.Tj(this,this.V.element,this.V):"none"===a&&"top"===c?new b.bg(this,this.V.element,this.V):new b.sd(this,this.V.element,this.V);this.$b.Init(this.options);this.f0(this.V.options.navigationLevel)},f0:function(a){"none"===this.V.options.drillMode&&
("application"===a?(this.V.element.addClass(this.TF),this.V.element.removeClass(this.tG)):"page"===a&&(this.V.element.addClass(this.tG),this.V.element.removeClass(this.TF)))},NH:function(a){a=this.Wj(f(a.target));null!=a&&this.mv(a,"oj-active",!1)},pu:function(){this.aY();a.q.pu.apply(this,arguments)},Bz:function(b){a.q.Bz.apply(this,arguments);var c=this.Wj(f(b.target));c&&!c.hasClass("oj-disabled")&&this.mv(c,"oj-active",!0)},kv:function(b){this.NH(b);a.q.kv.apply(this,arguments)},TP:function(){return"oj-navigationlist-listview"},
sF:function(){return"oj-navigationlist-element"},Lj:function(){return"oj-navigationlist-item"},Wk:function(){return"oj-navigationlist-focused-element"},bf:function(){return"oj-navigationlist-item-element"},Jj:function(){return"oj-navigationlist-collapse-icon"},sm:function(){return"oj-navigationlist-expand-icon"},IN:function(a){return"oj-navigationlist-depth-"+a},yg:function(){return"oj-navigationlist-group-item"},Hi:function(){return"oj-navigationlist-group"},Eu:function(){return"oj-navigationlist-collapsible-transition"},
hr:function(){return this.Eu()},fF:function(a,b){this.$b.Rr(a,b)},dF:function(a,b){this.$b.Or(a,b)},sp:function(a,b,e){return this.$b.sp(a,b,e)},Tr:function(a){return this.$b.Tr(a)},Re:function(a){return this.$b.Re(a)},vp:function(a,b){this.$b.vp(a,b)},xF:function(b){var c=this.Wj(f(b.target));null!=c&&0!==c.length&&(this.ci(c)?b.preventDefault():(this.ud(c[0]),this.Cz(f(b.target))||(c=this.mE(c).attr("href"),c&&"#"!==c&&0===b.button&&(b.shiftKey||b.ctrlKey)||(a.q.xF.apply(this,arguments),b.preventDefault()))))},
ZP:function(a){var b,e,g;if(this.hb)if(b=a.keyCode,e=this.hb.elem,g=this.hb.key,b===f.ui.keyCode.HOME||b===f.ui.keyCode.END){var h;h=b===f.ui.keyCode.HOME?this.element.find("."+this.Xj+":visible").first().closest("."+this.bf()):this.element.find("."+this.Xj+":visible").last().closest("."+this.bf());h=this.ud(h[0]);this.bi("currentItem",h);a.preventDefault()}else h=this.$P(a),b=this.$b.YP(a,b,e,g),!0!==h&&!0!==b||a.preventDefault()},Iz:function(b,c,e){var f=this.hb.elem;this.xh(f[0])&&!this.EY(f)&&
this.MI(b,f)&&(a.q.Iz.apply(this,arguments),this.tK(f))},mv:function(a,b,e){var g;a=f(a);"oj-selected"===b&&this.$b.OF(this.oe(a),e);g=a.children("."+this.yg());0<g.length&&(a=f(g[0]));e?a.addClass(b):a.removeClass(b);a.hasClass("oj-selected")||a.hasClass("oj-hover")||a.hasClass("oj-active")||a.hasClass("oj-disabled")?a.removeClass("oj-default"):a.addClass("oj-default")},xh:function(a){return!f(a).hasClass("oj-disabled")&&this.$b.xh(f(a))},hn:function(a,b,e){return"ready"!==a?this.V._trigger(a,b,
e):!0},bi:function(a,b,e){if("selection"===a){var f=e._context,h=f&&f.Hj&&f.Hj.items;h&&(f.Hj.item=h,f.Hj.items=void 0);b&&0<b.length?this.V.option(a,b[0],e):this.V.option(a,null,e)}else this.V.option(a,b,e);this.options[a]=b},yQ:function(a){return null!=a.data||null!=a.drillMode||null!=a.item||null!=a.display||null!=a.edge},Fr:function(b,c){var e={hP:[]},g;void 0!==b.hierarchyMenuDisplayThresholdLevel&&this.$b.Fr(b);void 0!==b.navigationLevel&&this.f0(b.navigationLevel);if(void 0!==b.selection)if(g=
b.selection){var h=this.Ud("selection");h&&0!==h.length&&h[0]===g?delete b.selection:(h=this.Jd(g))&&this.xh(h)?this.MI(null,f(h))?(b.selection=[g],this.tK(f(h))):(delete b.selection,e.hP.push("selection")):(delete b.selection,e.hP.push("selection"))}else b.selection=[];e.opa=a.q.Fr.call(this,b,c);void 0!==g&&(b.selection=g);return e},Ud:function(a){var b=this.V.option(a);return"selection"===a?b?[b]:[]:null===b?this.options[a]:b},Of:function(){return b.Components.Of(this.V.element)},wv:function(b,
c){!b.hasClass("oj-disabled")&&this.xh(b[0])&&(!this.EY(b)&&this.MI(c,b)?(a.q.wv.apply(this,arguments),this.tK(b)):this.XP(b,c))},MI:function(a,b){var e=this.ud(b[0]);return this.hn("beforeSelect",a,{item:b,key:e})},tK:function(a){return(a=this.mE(a).attr("href"))&&"#"!==a?(window.location.href=a,!0):!1},EY:function(a){var b;b=this.Ud("selection");a=this.ud(a[0]);return-1<b.indexOf(a)?!0:!1},fla:function(a,b){a.attr("title")||a.attr("title",b)},Uja:function(a){a.data(this.oG)?a.removeData(this.oG):
a.removeAttr("title")},bz:function(b,c){var e=f(b);if(e.hasClass(this.m7))e.removeClass(this.bf()),e.removeClass(this.Wk()),e.removeClass(this.Lj()),e.removeAttr("aria-selected"),e.children().remove(),e.attr("role","separator");else{var g=this.Jj(),h=this.sm(),k=this.AR,l=e.children("."+this.yg()),m;0<l.length?(l.addClass(this.Lj()),m=l.children(":not(."+h+"):not(."+g+")"),h=l.children("."+h),0===h.length&&(h=l.children("."+g)),h.attr("role","presentation"),h.removeAttr("aria-labelledby"),e.hasClass("oj-disabled")&&
l.addClass("oj-disabled")):m=e.children().first();m.addClass(this.Xj);g=m.wrapInner('\x3cspan class\x3d"'+this.jG+'"\x3e\x3c/span\x3e').find("."+k);0<g.length?(g.insertBefore(g.parent()),g.attr("title")&&g.data(this.oG,g.attr("title")),"icons"===this.V.options.display&&(this.V.element.addClass(this.tR),k=this.LN(e),g.attr("aria-label",k),g.attr("role","img"),this.fla(g,k)),e.closest("ul").addClass(this.SR)):m.addClass(this.TR);e.hasClass("oj-disabled")?this.oe(e).attr("aria-disabled","true"):0<l.length?
l.addClass("oj-default"):e.addClass("oj-default");this.$b.EF(e,m);a.q.bz.apply(this,arguments)}},getNodeBySubId:function(a){var b;if(null===a)return this.element?this.element[0]:null;b=a.subId;return"oj-navigationlist-item"===b?(a=a.key,a=this.Jd(a)):"oj-navigationlist-previous-link"===b?this.$b.dm?this.$b.dm[0]:null:"oj-navigationlist-hierarchical-button"===b?this.$b.Hh?this.$b.Hh[0]:null:"oj-navigationlist-hierarchical-menu"===b?this.$b.Af?this.$b.Af[0]:null:null},getSubIdByNode:function(a){if(this.$b.dm&&
this.$b.dm[0]===a)return{subId:"oj-navigationlist-previous-link"};if(this.$b.Hh&&this.$b.Hh[0]===a)return{subId:"oj-navigationlist-hierarchical-button"};if(this.$b.Af&&this.$b.Af[0]===a)return{subId:"oj-navigationlist-hierarchical-menu"};a=this.Wj(a);return null!=a&&0<a.length&&(a=this.ud(a[0]),null!=a)?{subId:"oj-navigationlist-item",key:a}:null},refresh:function(){this.C_();this.aY();a.q.refresh.apply(this,arguments)},C_:function(){this.V.element.removeClass(this.tR);this.V.element.removeClass(this.TF);
this.V.element.removeClass(this.tG);this.I_(this.element);this.$b.Oe()},destroy:function(){this.C_();a.q.destroy.apply(this,arguments);this.io.unwrap();this.io.is(":empty")&&this.io.remove();this.V.element.removeClass(this.UR+" "+this.VR);this.V._off(this.element,"click");this.V._off(this.element,"focus");this.V._off(this.element,"blur");this.V._off(this.element,"mouseover");this.V._off(this.element,"mousein");this.V._off(this.element,"mouseout");this.V._off(this.element,"keydown")}});(function(){b.ya("oj.ojNavigationList",
f.oj.baseComponent,{widgetEventPrefix:"oj",options:{currentItem:null,drillMode:"none",edge:"start",hierarchyMenuDisplayThresholdLevel:0,rootLabel:null,selection:null,expanded:"auto",data:null,display:"all",navigationLevel:"page",item:{renderer:null,selectable:!0},beforeSelect:null,beforeCollapse:null,beforeCurrentItem:null,collapse:null,beforeExpand:null,expand:null,optionChange:null},_ComponentCreate:function(){this._super();this.Aa()},mf:function(){this._super();this.qh.pu()},qf:function(a,b,e){this.qh.F4(a,
b,e)},Aa:function(){for(var b in this.options)this.u1(b,this.options[b]);this.LD(this.options.drillMode,this.options.display,this.options.edge);this.qh=new a;b={V:this};b=f.extend(this.options,b);this.qh.zm(b)},getNodeBySubId:function(a){return this.qh.getNodeBySubId(a)},getSubIdByNode:function(a){return this.qh.getSubIdByNode(a)},expand:function(a,b){this.qh.sN(a,b,!0,!0)},collapse:function(a,b){this.qh.V1(a,b,!0)},getExpanded:function(){return this.qh.getExpanded()},LD:function(a,b,e){if("none"!==
a){if("icons"===b)throw"Icon only navigation list should have drillMode set to 'none'.";if("top"===e)throw"Horizontal navigation list should have drillMode set to 'none'.";}},u1:function(a,b){var e=!0;"drillMode"===a?e="none"===b||"collapsible"===b||"sliding"===b:"display"===a?e="all"===b||"icons"===b:"edge"===a&&(e="top"===b||"start"===b);if(!e)throw"Invalid value: "+b+" for key: "+a;},_setOption:function(a,b){this.u1(a,b);switch(a){case "drillMode":this.LD(b,this.options.display,this.options.edge);
break;case "display":this.LD(this.options.drillMode,b,this.options.edge);break;case "edge":this.LD(this.options.drillMode,this.options.display,b)}return this._super(a,b)},_setOptions:function(a,b){var e=this.qh.Fr(a,b),f;for(f in a)0>e.hP.indexOf(f)&&this._setOption(f,a[f],b);e.opa&&this.qh.refresh();return this},li:function(){this.qh.G4()},yl:function(){},refresh:function(){this._super();this.qh.refresh()},_destroy:function(){this.qh.destroy();this._super();delete this.qh}});b.Components.Om({ojNavigationList:{hierarchyMenuDisplayThresholdLevel:b.Components.nh(function(){return b.ze.Yk("navigationList").hierarchyMenuDisplayThresholdLevel})}})})()});