/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","promise","ojs/ojjquery-hammer","ojs/ojcomponentcore"],function(b,f,a){b.o={};o_("OffcanvasUtils",b.o,b);b.o.aG="oj-offcanvasEdge";b.o.mn="oj-offcanvas";b.o.bG="oj-mediaQueryListener";b.o.aR="oj-offcanvasHammer";b.o.vv="selector";b.o.gv="start";b.o.fv="end";b.o.KP="top";b.o.lF="bottom";b.o.dv="displayMode";b.o.ev="push";b.o.JP="overlay";b.o.I6="modality";b.o.Iqa="none";b.o.J6="modal";b.o.wz="_dismissHandler";b.o.FF="_openPromise";b.o.cv="_closePromise";b.o.xz=
"_glassPane";b.o.wQ="_surrogate";b.o.IF="data-oj-surrogate-id";b.o.U6="oj-offcanvas-outer-wrapper";b.o.jQ="oj-offcanvas-open";b.o.gn="oj-offcanvas-transition";b.o.t6="oj-offcanvas-glasspane";b.o.RP="oj-offcanvas-glasspane-dim";b.o.Jqa="oj-offcanvas-generated";b.o.pla={start:"oj-offcanvas-shift-start",end:"oj-offcanvas-shift-end",top:"oj-offcanvas-shift-down",bottom:"oj-offcanvas-shift-up"};b.o.uca={start:"oj-offcanvas-start",end:"oj-offcanvas-end",top:"oj-offcanvas-top",bottom:"oj-offcanvas-bottom"};
b.o.tda=function(a){a=a[b.o.dv];a!==b.o.JP&&a!==b.o.ev&&(a=b.ze.Yk("offcanvas").displayMode);return a};b.o.Fh=function(a){return f(a[b.o.vv])};b.o.AK=function(a){return a[b.o.I6]===b.o.J6};b.o.co=function(a){return a.hasClass(b.o.jQ)};b.o.ot=function(a){return a.closest("."+b.o.U6)};b.o.EB=function(a){var c=b.o.Fh(a);return a[b.o.dv]===b.o.ev?c.parent():c};b.o.UW=function(a){var c=b.o.pla[a];if(!c)throw"Invalid edge: "+a;return c};b.o.ee=function(){return"rtl"===b.v.um()};b.o.YL=function(a,b){a.css({"-webkit-transform":b,
"-ms-transform":b,transform:b})};b.o.jD=function(a,c,e){c=c===b.o.fv;b.o.ee()&&(c=!c);b.o.YL(a,"translate3d("+(c?"-":"")+e+", 0, 0)")};b.o.gla=function(a,c,e){b.o.YL(a,"translate3d(0, "+(c===b.o.lF?"-":"")+e+", 0)")};b.o.K_=function(a){var c=a.edge;a=b.o.Fh(a);c&&c.length||(c=a.hasClass("oj-offcanvas-start")?b.o.gv:a.hasClass("oj-offcanvas-end")?b.o.fv:a.hasClass("oj-offcanvas-top")?b.o.KP:a.hasClass("oj-offcanvas-bottom")?b.o.lF:b.o.gv);f.data(a[0],b.o.aG,c);return c};b.o.$I=function(a){return f.data(a[0],
b.o.aG)};b.o.uD=function(a,c,e){var f=a[b.o.dv],h=b.o.Fh(a),k=b.o.jQ,f=f===b.o.JP?b.o.gn+" oj-offcanvas-overlay":b.o.gn;e?(h.addClass(k),c.addClass(f)):(a=a.tabindex,void 0===a?h.removeAttr("tabindex"):h.attr("tabindex",a),h.removeClass(k),c.removeClass(f))};b.o.Hk=function(a){var c=b.o.Fh(a),e=c.find(":focusable");0<e.length?a=e[0]:(e=c.attr("tabindex"),void 0!==e&&(a.tabindex=e),c.attr("tabindex","-1"),a=c);b.td.Fy(a)};b.o.Qga=function(a){return"none"!=a.autoDismiss};b.o.qZ=function(a,b){function e(){b();
a.off("transitionend webkitTransitionEnd otransitionend oTransitionEnd",e)}a.on("transitionend webkitTransitionEnd otransitionend oTransitionEnd",e)};b.o.e_=function(a){b.o.o1(a);if(b.o.Qga(a)){var c=b.o.Fh(a),e=a[b.o.wz]=function(e){var g=e.target;b.v.T3(e)||"focus"===e.type&&!f(g).is(":focusable")||b.v.bpa(c[0],g)||b.o.close(a)},g=document.documentElement;b.v.Sd()&&g.addEventListener("touchstart",e,!0);g.addEventListener("mousedown",e,!0);g.addEventListener("focus",e,!0)}b.o.WC(a)};b.o.o1=function(a){var c=
a[b.o.wz];if(c){var e=document.documentElement;b.v.Sd()&&e.removeEventListener("touchstart",c,!0);e.removeEventListener("mousedown",c,!0);e.removeEventListener("focus",c,!0);delete a[b.o.wz];a[b.o.wz]=null}b.o.CD(a)};b.o.WC=function(d){if(b.v.Sd()){var c=d[b.o.vv],e=f(c),g=b.o.$I(e),h,k;g===b.o.gv&&!b.o.ee()||g===b.o.fv&&b.o.ee()?(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_LEFT}]]},h="swipeleft"):g===b.o.gv&&b.o.ee()||g===b.o.fv&&!b.o.ee()?(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_RIGHT}]]},
h="swiperight"):g===b.o.KP?(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_UP}]]},h="swipeup"):g===b.o.lF&&(k={recognizers:[[a.Swipe,{direction:a.DIRECTION_DOWN}]]},h="swipedown");e=e.jl(k).on(h,function(a){a.preventDefault();b.o.close(d)});f.data(f(c)[0],b.o.aR,{event:h,hammer:e})}};b.o.CD=function(a){a=b.o.Fh(a);(a=f.data(a[0],b.o.aR))&&a.hammer.off(a.event)};b.o.fT=function(a){var c=b.o.Fh(a);if(f.data(c[0],b.o.mn)===a){b.o.$I(c);var e=b.o.EB(a);b.o.uD(a,e,!1);b.o.Nja(a);b.o.o1(a);c.trigger("ojclose",
a);f.removeData(c[0],b.o.mn)}};b.o.q0=function(a,c,e){var g=f(a);(c=!!c)&&b.o.co(g)&&b.o.Fl(a,!1);g.toggleClass(b.o.uca[e],!c)};b.o.aqa=function(a){var c=a.query;if(null!==c){var e=a[b.o.vv],c=window.matchMedia(c),g=b.o.K_(a);a=function(a){b.o.q0(e,a.matches,g)};c.addListener(a);b.o.q0(e,c.matches,g);f.data(f(e)[0],b.o.bG,{mqList:c,mqListener:a})}};o_("OffcanvasUtils.setupResponsive",b.o.aqa,b);b.o.oqa=function(a){a=b.o.Fh(a);var c=f.data(a[0],b.o.bG);c&&(c.mqList.removeListener(c.mqListener),f.removeData(a[0],
b.o.bG))};o_("OffcanvasUtils.tearDownResponsive",b.o.oqa,b);b.o.open=function(a){var c=b.o.Fh(a),e=f.data(c[0],b.o.mn);if(e){if(e[b.o.cv])return e[b.o.cv];if(e[b.o.FF])return e[b.o.FF]}var e=new Promise(function(e,g){b.l.Bd(c,jQuery);var l=b.o.K_(a),m=f.Event("ojbeforeopen");c.trigger(m,a);if(!1===m.result)g("ojbeforeopen veto");else{var n,m=b.o.tda(a),p=f.extend({},a);p[b.o.dv]=m;f.data(c[0],b.o.mn,p);var r;r=b.o.EB(p);b.l.Bd(r,jQuery);b.o.uD(p,r,!0);l===b.o.gv||l===b.o.fv?(n=void 0===n?c.outerWidth(!0)+
"px":n,m===b.o.ev&&b.o.jD(r,l,n)):(n=void 0===n?c.outerHeight(!0)+"px":n,m===b.o.ev&&b.o.gla(r,l,n));var s;window.setTimeout(function(){s=b.o.ot(c);b.l.Bd(s,jQuery);s.addClass(b.o.UW(l))},10);b.o.C$(p,c);b.o.qZ(r,function(){r.removeClass(b.o.gn);b.o.Hk(p);c.trigger("ojopen",p);b.o.e_(p);e(!0)})}}),g=f.data(c[0],b.o.mn);g&&(g[b.o.FF]=e);return e};o_("OffcanvasUtils.open",b.o.open,b);b.o.close=function(a){return b.o.Fl(a[b.o.vv],!0)};o_("OffcanvasUtils.close",b.o.close,b);b.o.Fl=function(a,c){var e=
f(a);b.l.Bd(e,jQuery);var g=f.data(e[0],b.o.mn);if(g&&g[b.o.cv])return g[b.o.cv];var h=new Promise(function(h,l){if(b.o.co(e)){a!=g[b.o.vv]&&h(!0);var m=b.o.$I(e),n=g[b.o.dv],m=b.o.UW(m),p=b.o.ot(e);b.l.Bd(p,jQuery);p.hasClass(m)||h(!0);var r=f.Event("ojbeforeclose");e.trigger(r,g);if(!1===r.result)l("beforeClose veto");else{r=b.o.EB(g);if(c){var s=0,q=function(){b.o.fT(g);0!==s&&window.cancelAnimationFrame(s);h(!0)},t=function(){null==e[0].offsetParent?q():s=window.requestAnimationFrame(t)};b.o.qZ(r,
q);s=window.requestAnimationFrame(t)}n===b.o.ev&&b.o.YL(r,"");p.removeClass(m);b.o.AK(g)&&g[b.o.xz].removeClass(b.o.RP);c?r.addClass(b.o.gn):(b.o.fT(g),h(!0))}}else h(!0)});(g=f.data(e[0],b.o.mn))&&(g[b.o.cv]=h);return h};b.o.toggle=function(a){var c=b.o.Fh(a);b.l.Bd(c,jQuery);return b.o.co(c)?b.o.close(a):b.o.open(a)};o_("OffcanvasUtils.toggle",b.o.toggle,b);b.o.b$=function(a){var c=f("\x3cdiv\x3e");c.addClass(b.o.t6);c.attr("role","presentation");c.attr("aria-hidden","true");c.appendTo(a.parent());
c.on("keydown keyup keypress mousedown mouseup mouseover mouseout click focusin focus",function(a){a.stopPropagation();a.preventDefault()});return c};b.o.cI=function(a){var c=f("\x3cscript\x3e"),e=a.attr("id");e?(e=[e,"surrogate"].join("_"),c.attr("id",e)):e=c.uniqueId();c.insertBefore(a);a.attr(b.o.IF,e);return c};b.o.Fla=function(a,c){a[b.o.wQ]=b.o.cI(c);c.appendTo(c.parent())};b.o.mka=function(a){var c=b.o.Fh(a);a=a[b.o.wQ];c&&a&&c.attr(b.o.IF)===a.attr("id")&&(c.insertAfter(a),c.removeAttr(b.o.IF),
a.remove())};b.o.C$=function(a,c){b.o.AK(a)&&(a[b.o.xz]=b.o.b$(c),b.o.Fla(a,c),window.setTimeout(function(){a[b.o.xz].addClass(b.o.RP)},0))};b.o.Nja=function(a){b.o.AK(a)&&(a[b.o.xz].remove(),b.o.mka(a))};b.o.s5=function(d){var c,e,g,h,k,l,m,n,p,r,s,q;null==f(d).attr("oj-data-pansetup")&&(f(d).attr("oj-data-pansetup","true"),d.displayMode="push",c=b.o.Fh(d),e=d.size,null==e&&(e=c.outerWidth()),g=b.o.ot(c),h=b.o.EB(d),k={recognizers:[[a.Pan,{direction:a.DIRECTION_HORIZONTAL}]]},l=!1,f(g).jl(k).on("panstart",
function(e){m=null;switch(e.gesture.direction){case a.DIRECTION_LEFT:Math.abs(e.gesture.deltaY)<Math.abs(e.gesture.deltaX)&&(m=b.o.ee()?"end":"start");break;case a.DIRECTION_RIGHT:Math.abs(e.gesture.deltaY)<Math.abs(e.gesture.deltaX)&&(m=b.o.ee()?"start":"end")}null!=m&&(n={direction:m,distance:Math.abs(e.gesture.deltaX)},p=f.Event("ojpanstart"),c.trigger(p,n),p.isDefaultPrevented()||(d._closePromise=null,b.o.uD(d,h,!0),l=!0,e.stopPropagation()))}).on("panmove",function(a){l&&(r=Math.abs(a.gesture.deltaX),
c.css("width",r),h.removeClass(b.o.gn),b.o.jD(h,"start",a.gesture.deltaX+"px"),n={direction:m,distance:r},p=f.Event("ojpanmove"),c.trigger(p,n),a.stopPropagation())}).on("panend",function(a){l&&(l=!1,r=Math.abs(a.gesture.deltaX),n={distance:r},p=f.Event("ojpanend"),c.trigger(p,n),a.stopPropagation(),p.isDefaultPrevented()?(q=function(){b.o.uD(d,h,!1);h.removeClass(b.o.gn);h.off("transitionend webkitTransitionEnd otransitionend oTransitionEnd",q)},h.on("transitionend webkitTransitionEnd otransitionend oTransitionEnd",
q),h.addClass(b.o.gn),b.o.jD(h,"start","0px")):(h.addClass(b.o.gn),c.css("width",e+"px"),s=d.edge,null==s&&(s=c.hasClass("oj-offcanvas-start")?"start":"end"),b.o.jD(h,s,e+"px"),f.data(c[0],b.o.mn,d),f.data(c[0],b.o.aG,s),b.o.e_(d)))}))};o_("OffcanvasUtils.setupPanToReveal",b.o.s5,b);b.o.G5=function(a){a=b.o.Fh(a);f(b.o.ot(a)).off("panstart panmove panend")};o_("OffcanvasUtils.tearDownPanToReveal",b.o.G5,b)});