/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","hammerjs","ojs/ojpagingtabledatasource","ojs/ojinputtext","ojs/ojjquery-hammer"],function(b,f,a,d){(function(){b.ya("oj.ojPagingControl",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,overflow:"fit",pageSize:25,pageOptions:{layout:["auto"],type:"numbers",maxPageLinks:6,orientation:"horizontal"},loadMoreOptions:{maxCount:500},mode:"page",ready:null},xa:{o8:"labelAccPaging",j8:"labelAccNavFirstPage",
k8:"labelAccNavLastPage",l8:"labelAccNavNextPage",n8:"labelAccNavPreviousPage",m8:"labelAccNavPage",p8:"labelLoadMore",q8:"labelLoadMoreMaxRows",KR:"labelNavInputPage",kG:"labelNavInputPageMax",Vqa:"labelNavInputPageSummary",OR:"msgItemRangeCurrent",PR:"msgItemRangeCurrentSingle",QR:"msgItemRangeItems",E8:"msgItemRangeOfAtLeast",D8:"msgItemRangeOfApprox",F8:"msgItemRangeOf",IS:"tipNavInputPage",K9:"tipNavPageLink",KS:"tipNavNextPage",LS:"tipNavPreviousPage",HS:"tipNavFirstPage",JS:"tipNavLastPage",
Ap:"pageInvalid.summary",Qqa:"pageInvalid.detail",lR:"dataInvalidType.summary",kR:"dataInvalidType.detail",Q7:"maxPageLinksInvalid.summary",P7:"maxPageLinksInvalid.detail"},Ca:{VG:"oj-component",lf:"oj-active",yp:"oj-clickable-icon-nocontext",vb:"oj-disabled",pf:"oj-enabled",cj:"oj-focus",dk:"oj-hover",hd:"oj-selected"},O:{O8:"oj-pagingcontrol",bS:"oj-pagingcontrol-acc-label",cS:"oj-pagingcontrol-content",dS:"oj-pagingcontrol-loadmore",hA:"oj-pagingcontrol-loadmore-link",uG:"oj-pagingcontrol-loadmore-max-rows",
iA:"oj-pagingcontrol-loadmore-range",vG:"oj-pagingcontrol-loadmore-range-current",wG:"oj-pagingcontrol-loadmore-range-max",fS:"oj-pagingcontrol-nav",jA:"oj-pagingcontrol-nav-arrow",eS:"oj-pagingcontrol-nav-arrow-section",zG:"oj-pagingcontrol-nav-page",b9:"oj-pagingcontrol-nav-page-ellipsis",Q8:"oj-pagingcontrol-nav-dot",P8:"oj-pagingcontrol-nav-dot-bullet",a9:"oj-pagingcontrol-nav-page-acc-label",hS:"oj-pagingcontrol-nav-label",gS:"oj-pagingcontrol-nav-input-section",Ip:"oj-pagingcontrol-nav-input",
Pv:"oj-pagingcontrol-nav-input-max",Qv:"oj-pagingcontrol-nav-input-summary",xG:"oj-pagingcontrol-nav-input-summary-current",yG:"oj-pagingcontrol-nav-input-summary-max",jS:"oj-pagingcontrol-nav-pages-section",iS:"oj-pagingcontrol-nav-pages-links",xs:"oj-pagingcontrol-nav-first",R8:"oj-pagingcontrol-nav-first-acc-label",As:"oj-pagingcontrol-nav-previous",c9:"oj-pagingcontrol-nav-previous-acc-label",zs:"oj-pagingcontrol-nav-next",X8:"oj-pagingcontrol-nav-next-acc-label",ys:"oj-pagingcontrol-nav-last",
U8:"oj-pagingcontrol-nav-last-acc-label",S8:"oj-pagingcontrol-nav-first-icon",d9:"oj-pagingcontrol-nav-previous-icon",Y8:"oj-pagingcontrol-nav-next-icon",V8:"oj-pagingcontrol-nav-last-icon",T8:"oj-pagingcontrol-nav-first-vertical-icon",e9:"oj-pagingcontrol-nav-previous-vertical-icon",Z8:"oj-pagingcontrol-nav-next-vertical-icon",W8:"oj-pagingcontrol-nav-last-vertical-icon",Op:"oj-component-icon",ji:"oj-helper-hidden-accessible"},$Q:"data-oj-pagenum",Vg:"enabled",vn:"disabled",Xg:"tabindex",hk:{qn:"loadMore",
aS:"page"},tf:{Sg:"auto",Dv:"all",Yz:"input",g9:"rangeText",M8:"pages",RR:"nav"},N8:6,vA:{Xqa:"numbers",I7:"dots"},firstPage:function(){return null!=this.eb()?this.vi(0,!1):this.st()},previousPage:function(){if(null!=this.eb()){var a=this.yf();if(0<a)return this.vi(a-1,!1)}return this.st()},nextPage:function(){if(null!=this.eb()){var a=this.yf();if(a+1<=this.Ad()-1||0>this.Ad())return this.vi(a+1,!1)}return this.st()},lastPage:function(){return null!=this.eb()&&0<this.Ad()?this.vi(this.Ad()-1,!1):
this.st()},page:function(a){return null!=this.eb()&&(this.og()&&a<=this.Ad()-1||0>this.Ad()||!this.og())?this.vi(a,!1):this.st()},loadNext:function(){return null!=this.eb()?this.Oga():this.st()},refresh:function(){this._super();this.Pd()},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId,d=null;"oj-pagingcontrol-nav-input"===b?d=this.Od().find("."+this.O.Ip)[0]:"oj-pagingcontrol-nav-input-max"===b?d=this.Od().find("."+this.O.Pv)[0]:"oj-pagingcontrol-nav-input-summary"===
b?d=this.Od().find("."+this.O.Qv)[0]:"oj-pagingcontrol-nav-input-summary-current"===b?d=this.Od().find("."+this.O.xG)[0]:"oj-pagingcontrol-nav-input-summary-max"===b?d=this.Od().find("."+this.O.yG)[0]:"oj-pagingcontrol-nav-first"===b?d=this.Od().find("."+this.O.xs)[0]:"oj-pagingcontrol-nav-next"===b?d=this.Od().find("."+this.O.zs)[0]:"oj-pagingcontrol-nav-previous"===b?d=this.Od().find("."+this.O.As)[0]:"oj-pagingcontrol-nav-last"===b?d=this.Od().find("."+this.O.ys)[0]:"oj-pagingcontrol-nav-page"===
b?(a=a.index,d=this.Od().find("["+this.$Q+"\x3d"+a+"]")[0]):"oj-pagingcontrol-load-more-link"===b?d=this.Od().find("."+this.O.hA)[0]:"oj-pagingcontrol-load-more-range"===b?d=this.Od().find("."+this.O.iA)[0]:"oj-pagingcontrol-load-more-range-current"===b?d=this.Od().find("."+this.O.vG)[0]:"oj-pagingcontrol-load-more-range-max"===b?d=this.Od().find("."+this.O.wG)[0]:"oj-pagingcontrol-load-more-max-rows"===b&&(d=this.Od().find("."+this.O.uG)[0]);void 0===d&&(d=null);return d},getSubIdByNode:function(a){return f(a).hasClass(this.O.Ip)?
{subId:"oj-pagingcontrol-nav-input"}:f(a).hasClass(this.O.Pv)?{subId:"oj-pagingcontrol-nav-input-max"}:f(a).hasClass(this.O.Qv)?{subId:"oj-pagingcontrol-nav-input-summary"}:f(a).hasClass(this.O.xG)?{subId:"oj-pagingcontrol-nav-input-summary-current"}:f(a).hasClass(this.O.yG)?{subId:"oj-pagingcontrol-nav-input-summary-max"}:f(a).hasClass(this.O.xs)?{subId:"oj-pagingcontrol-nav-first"}:f(a).hasClass(this.O.zs)?{subId:"oj-pagingcontrol-nav-next"}:f(a).hasClass(this.O.As)?{subId:"oj-pagingcontrol-nav-previous"}:
f(a).hasClass(this.O.ys)?{subId:"oj-pagingcontrol-nav-last"}:f(a).hasClass(this.O.zG)?{subId:"oj-pagingcontrol-nav-page",index:f(a).attr(this.$Q)}:f(a).hasClass(this.O.hA)?{subId:"oj-pagingcontrol-load-more-link"}:f(a).hasClass(this.O.iA)?{subId:"oj-pagingcontrol-load-more-range"}:f(a).hasClass(this.O.vG)?{subId:"oj-pagingcontrol-load-more-range-current"}:f(a).hasClass(this.O.wG)?{subId:"oj-pagingcontrol-load-more-range-max"}:f(a).hasClass(this.O.uG)?{subId:"oj-pagingcontrol-load-more-max-rows"}:
null},_ComponentCreate:function(){this._super();this.Lq();this.Dw();this.yj(this.Od());this._on(this.Ml)},mf:function(){this._super();this.WC();this.vi(0,!0)},_destroy:function(){this.Mk();this.CD();this.uw=!0},Dw:function(){var a=this.options;this.element.addClass(this.O.O8);this.element.addClass(this.Ca.VG);this.nba();this.tba();this.fZ=a.mode;a.mode==this.hk.qn?(this.uU(),this.vU(),this.wU()):this.xU()},Ml:{"mouseup .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();f(a.target).data("_mouseup",
!0);a.preventDefault()},"click .oj-pagingcontrol-loadmore-link":function(a){f(a.target).data("_mouseup")?f(a.target).data("_mouseup",!1):this.loadNext();a.preventDefault()},"click .oj-pagingcontrol-nav-dot":function(a){var d=f(a.currentTarget).attr("data-oj-pagenum"),g=this;this.page(d).then(function(){},function(a){var c=g.A(g.xa.Ap);b.r.error(c+"\n"+a)});a.preventDefault()},"click .oj-pagingcontrol-nav-page":function(a){var d=f(a.currentTarget).attr("data-oj-pagenum"),g=this;this.page(d).then(function(){},
function(a){var c=g.A(g.xa.Ap);b.r.error(c+"\n"+a)});a.preventDefault()},"click .oj-pagingcontrol-nav-first":function(a){if(!f(a.currentTarget).hasClass(this.Ca.vb)){var d=this;this.firstPage().then(function(){},function(a){var c=d.A(d.xa.Ap);b.r.error(c+"\n"+a)})}a.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(a){if(!f(a.currentTarget).hasClass(this.Ca.vb)){var d=this;this.previousPage().then(function(){},function(a){var c=d.A(d.xa.Ap);b.r.error(c+"\n"+a)})}a.preventDefault()},
"click .oj-pagingcontrol-nav-next":function(a){if(!f(a.currentTarget).hasClass(this.Ca.vb)){var d=this;this.nextPage().then(function(){},function(a){var c=d.A(d.xa.Ap);b.r.error(c+"\n"+a)})}a.preventDefault()},"click .oj-pagingcontrol-nav-last":function(a){if(!f(a.currentTarget).hasClass(this.Ca.vb)){var d=this;this.lastPage().then(function(){},function(a){var c=d.A(d.xa.Ap);b.r.error(c+"\n"+a)})}a.preventDefault()},"keypress .oj-pagingcontrol-nav-input":function(a){13==a.which&&a.preventDefault()},
"mousedown .oj-pagingcontrol-nav-first":function(a){f(a.currentTarget).hasClass(this.Ca.vb)||f(a.target).addClass(this.Ca.lf);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-previous":function(a){f(a.currentTarget).hasClass(this.Ca.vb)||f(a.target).addClass(this.Ca.lf);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-next":function(a){f(a.currentTarget).hasClass(this.Ca.vb)||f(a.target).addClass(this.Ca.lf);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-last":function(a){f(a.currentTarget).hasClass(this.Ca.vb)||
f(a.target).addClass(this.Ca.lf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-first":function(a){f(a.target).removeClass(this.Ca.lf);
a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-previous":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-next":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-last":function(a){f(a.target).removeClass(this.Ca.lf);a.preventDefault()}},Pd:function(){this.i!=this.options.data&&(this.OH(),this.vi(0,!0));var a=0,b=0;null!=this.i&&(b=this.i.getStartItemIndex());null!=this.i&&0!=this.i.totalSize()&&
0<=this.i.getEndItemIndex()&&(a=this.i.getEndItemIndex()-b+1);if(this.fZ!=this.options.mode)this.fZ=this.options.mode,this.options.mode==this.hk.qn?this.UZ(a,b):this.VZ(a,b);else if(this.options.mode==this.hk.qn){var d=this.eb(),f=this.qt();null!=d&&(b+a==d.totalSize()&&this.og()||0==d.totalSize())?f.css("display","none"):this.UZ(a,b)}else this.VZ(a,b)},_setOption:function(a,b){this._superApply(arguments);this.vi(0,!0);if(this.options.mode!=this.hk.qn&&"pageOptions"==a){var d=this.ti();null!=d&&(this.JM(d),
this.CD(),d.empty());this.xaa();this.xU();this.WC()}this.Pd()},OH:function(){null!=this.i&&this.Mk();this.i=null},waa:function(){this.sH=this.rH=this.qH=null},xaa:function(){this.vH=this.uH=this.tH=null},yf:function(){var a=this.eb(),b=0;null!=a&&(b=a.getPage());return b},eb:function(){this.i||null==this.options.data||(this.i=this.options.data,this.Lq());return this.i},iJ:function(a,b){var d=0<=b?b:0,h=f(document.createElement("span")),k=f(document.createElement("span"));this.options.mode==this.hk.qn?
k.addClass(this.O.vG):k.addClass(this.O.xG);h.append(k);var l=this.eb();if(null!=l&&null!=l.totalSize()&&null!=a){var m=this.A(this.xa.PR,{pageFrom:d}),m=parseInt(b,10)+parseInt(a,10),d=0<m?d+1:0;if(-1!=l.totalSize()){var m=m>l.totalSize()?l.totalSize():m,m=d==m?this.A(this.xa.PR,{pageFrom:d}):this.A(this.xa.OR,{pageFrom:d,pageTo:m}),d=this.A(this.xa.F8),n=null;"atLeast"==l.totalSizeConfidence()?n=this.A(this.xa.E8):"estimate"==l.totalSizeConfidence()&&(n=this.A(this.xa.D8));var p=f(document.createElement("span"));
null==n?p.text(" "+d+" "):p.text(" "+n+" ");h.append(p);d=f(document.createElement("span"));this.options.mode==this.hk.qn?d.addClass(this.O.wG):d.addClass(this.O.yG);d.text(l.totalSize());h.append(d)}else m=this.A(this.xa.OR,{pageFrom:d,pageTo:m});l=this.A(this.xa.QR);d=f(document.createElement("span"));d.text(" "+l);h.append(d);k.text(m)}return h},wW:function(){var a=this.options.pageOptions.maxPageLinks;this.options.pageOptions.type==this.vA.I7?a=Number.MAX_VALUE:a||(a=this.N8);return a},xW:function(a){var b=
0;0<this.Ad()&&this.og()?b=this.Ad():0<a?(a=this.eb(),b=null==a||"atLeast"!=a.totalSizeConfidence()&&"estimate"!=a.totalSizeConfidence()?this.yf()+2:this.Ad()+1):b=this.yf()+1;return b},st:function(){return Promise.reject()},Ad:function(){var a=this.eb(),b=0;null!=a&&(b=a.getPageCount());return-1<=b?b:0},RJ:function(){var a=f(document.activeElement);if(a.hasClass(this.O.zG)){var b=a.attr("data-oj-pagenum"),d=this;setTimeout(function(){0<=b&&d.ti().find("div[data-oj-pagenum\x3d"+b+"]").focus()},100)}else a.hasClass(this.O.xs)?
(d=this,setTimeout(function(){d.ti().find("."+d.O.xs).focus()},100)):a.hasClass(this.O.As)?(d=this,setTimeout(function(){d.ti().find("."+d.O.As).focus()},100)):a.hasClass(this.O.zs)?(d=this,setTimeout(function(){d.ti().find("."+d.O.zs).focus()},100)):a.hasClass(this.O.ys)?(d=this,setTimeout(function(){d.ti().find("."+d.O.ys).focus()},100)):a.hasClass(this.O.Ip)&&(d=this,setTimeout(function(){d.ti().find("."+d.O.Ip).focus()},100));this.Xt()},Yea:function(a){a.page!=a.previousPage&&this.Xt()},Xn:function(){this.vi(0,
!1)},gC:function(){this.Xt()},UJ:function(a){this.options.mode==this.hk.qn&&this.Xn(a)},SJ:function(a){this.options.mode==this.hk.aS&&this.wY(a)?this.vi(this.yf(),!0):this.Xt()},TJ:function(a){0<this.Ad()&&this.yf()>this.Ad()-1?this.vi(this.Ad()-1,!0):this.wY(a)?this.vi(this.yf(),!0):this.Xt()},Lfa:function(a,d){var g=d.value;if(g!=this.yf()+1&&!isNaN(g)&&0<g){var g=Math.round(g),f=this;this.page(g-1).then(function(){},function(a){var c=f.A(f.xa.Ap);b.r.error(c+"\n"+a)})}},vi:function(a,b){try{a=
parseInt(a,10)}catch(d){return Promise.reject(d)}this.Eh=0;if(b)return this.bja(a),Promise.resolve();var f=this.eb(),k=this;return new Promise(function(b,d){null!=f?f.setPage(a,{pageSize:k.options.pageSize}).then(function(){b(null)},function(a){d(a)}):b(null)})},Oga:function(){var a=this.eb(),b=this.options.pageSize;this.Eh=this.Eh?this.Eh+b:b;if(!this.og()||a.totalSize()>this.Eh&&this.og()){var d=this;return new Promise(function(f,k){a.fetch({startIndex:d.Eh,pageSize:b}).then(function(a){f(a)},function(){k(null)})})}return Promise.resolve()},
wY:function(a){var b=this.eb(),d=this.options.pageSize,f;for(f=0;f<a.indexes.length;f++){var k=a.indexes[f],l=b.getStartItemIndex(),m=l+d;this.options.mode==this.hk.qn&&(l=0);if(k>=l&&k<m)return!0}return!1},og:function(){var a=this.eb();return null!=a&&"actual"==a.totalSizeConfidence()?!0:!1},bja:function(a){var d=this;this.Tt||(this.Iq=0,this.Tt=Promise.resolve());this.Iq++;this.uia=a;this.Tt=this.Tt.then(function(){d.Iq--;if(0==d.Iq&&!d.uw){d.Tt=void 0;var a=d.eb();null!=a&&a.setPage(d.uia,{pageSize:d.options.pageSize}).then(function(){},
function(a){d.Iq--;0>=d.Iq&&(d.Tt=void 0,b.r.error(a))})}},function(a){d.Iq--;0>=d.Iq&&(d.Tt=void 0,b.r.error(a))})},Xt:function(){var a=this;this.Bx||(this.Px=0,this.Bx=Promise.resolve());this.Px++;this.Bx=this.Bx.then(function(){a.Px--;0!=a.Px||a.uw||(a.Bx=void 0,a.Pd(),a._trigger("ready"))},function(d){a.Px--;0==a.Px&&(a.Bx=void 0,b.r.error(d))})},UZ:function(a,b){var d=this.ti();null!=d&&d.empty();this.waa();this.uU();d=-1;null!=a&&(d=b+a);0>d||d<this.options.loadMoreOptions.maxCount?(this.vU(),
this.wU(a,b)):this.uba()},VZ:function(a,b){var d=this.options.overflow;this.jja(a,b);this.ija();this.hja();this.lja(a,b);this.kja(a,b);this.gja(a,b);if("fit"==d){var d=this.element.width(),f=this.vJ(),k=this.wJ(),l=this.iea(),m=this.hea(),n=null!=f?f[0].offsetWidth:0,p=null!=k?k[0].offsetWidth:0,k=null!=l?l.width():0,r=null!=m?m.width():0,n=n+p+r;n>d?n-k<=d?l.css("display","none"):n-k-r<=d?(null!=l&&l.css("display","none"),null!=m&&m.css("display","none")):(null!=l&&l.css("display","none"),null!=
m&&m.css("display","none"),null!=f&&f.css("display","none")):0<n&&(null!=l&&l.css("display",""),null!=m&&m.css("display",""),null!=f&&f.css("display",""))}},gja:function(a){var b=this.vJ(),d=b.children("."+this.O.xs);if(d&&0<d.length){var d=f(d[0]),h=this.A(this.xa.HS);d.attr("title",h);0==this.yf()?(d.addClass(this.Ca.vb),d.removeClass(this.Ca.pf),d.attr("tabindex","-1")):(d.addClass(this.Ca.pf),d.removeClass(this.Ca.vb),d.attr(this.Xg,"0"))}(d=b.children("."+this.O.As))&&0<d.length&&(d=f(d[0]),
h=this.A(this.xa.LS),d.attr("title",h),0==this.yf()?(d.addClass(this.Ca.vb),d.removeClass(this.Ca.pf),d.attr(this.Xg,"-1")):(d.addClass(this.Ca.pf),d.removeClass(this.Ca.vb),d.attr(this.Xg,"0")));(d=b.children("."+this.O.ys))&&0<d.length&&(d=f(d[0]),h=this.A(this.xa.JS),d.attr("title",h),this.yf()==this.Ad()-1||0>=this.Ad()||!this.og()?(d.addClass(this.Ca.vb),d.removeClass(this.Ca.pf),d.attr(this.Xg,"-1")):(d.addClass(this.Ca.pf),d.removeClass(this.Ca.vb),d.attr(this.Xg,"0")));(b=b.children("."+this.O.zs))&&
0<b.length&&(b=f(b[0]),d=this.A(this.xa.KS),b.attr("title",d),this.yf()==this.Ad()-1&&this.og()||0===this.Ad()||0>this.Ad()&&0===a?(b.addClass(this.Ca.vb),b.removeClass(this.Ca.pf),b.attr(this.Xg,"-1")):(b.addClass(this.Ca.pf),b.removeClass(this.Ca.vb),b.attr(this.Xg,"0")))},kja:function(a,b){var d=this.Sl().find("."+this.O.jS);null!=d&&0<d.length&&(d=f(d.get(0)),d.empty(),this.yU(d,this.wW(),a,b))},ija:function(){var a=this.wJ();if(null!=a&&(a=a.children("."+this.O.hS),null!=a&&0<a.length)){var a=
f(a[0]),b=this.A(this.xa.KR);a.text(b)}},hja:function(){var a=this.gea();if(null!=a){var b=this.A(this.xa.IS);a.attr("title",b);a.ojInputText("option","title",b)}},lja:function(a,b){var d=this.Sl().children("."+this.O.Qv);if(null!=d&&0<d.length){var h=this.iJ(a,b);0<h.text().length&&(d=f(d.get(0)),d.empty(),d.append("("),d.append(h),d.append(")"))}},jja:function(a){a=this.xW(a);var b=this.Sl().find("."+this.O.Pv);if(null!=b&&0<b.length)if(b=f(b.get(0)),0<this.Ad()&&this.og()){var d=this.A(this.xa.kG,
{pageMax:a});b.text(d)}else b.empty();else d=this.wJ(),null!=d&&0<this.Ad()&&this.og()&&(b=f(document.createElement("span")),b.addClass(this.O.Pv),d.append(b),d=this.A(this.xa.kG,{pageMax:a}),b.text(d));b=this.Sl().find("."+this.O.Ip);null!=b&&0<b.length&&(b=f(b.get(0)),b.val(this.yf()+1),b.ojInputText("option","validators",[{type:"numberRange",options:{min:1,max:a}}]))},Lq:function(){var a=this.eb();if(null!=a){this.Mk();this.Ua=[];this.Ua.push({eventType:b.dc.D.PAGE,eventHandler:this.Yea.bind(this)});
this.Ua.push({eventType:b.dc.D.PAGECOUNT,eventHandler:this.gC.bind(this)});this.Ua.push({eventType:b.na.D.ADD,eventHandler:this.SJ.bind(this)});this.Ua.push({eventType:b.na.D.REMOVE,eventHandler:this.TJ.bind(this)});this.Ua.push({eventType:b.na.D.RESET,eventHandler:this.Xn.bind(this)});this.Ua.push({eventType:b.na.D.REFRESH,eventHandler:this.gC.bind(this)});this.Ua.push({eventType:b.na.D.SYNC,eventHandler:this.RJ.bind(this)});this.Ua.push({eventType:b.na.D.SORT,eventHandler:this.UJ.bind(this)});var d,
g;for(d=0;d<this.Ua.length;d++)(g=a.on(this.Ua[d].eventType,this.Ua[d].eventHandler))&&(this.Ua[d].eventHandler=g)}},yj:function(a){if(!this.zC){var d=this;b.v.Nh(a[0],function(){d.Xt()},50);this.zC=!0}},WC:function(){if(b.v.Sd()&&this.options.mode==this.hk.aS){var a=this.vJ();if(null!=a){var e=this;if("vertical"==this.options.pageOptions.orientation){var g={recognizers:[[d.Swipe,{direction:d.DIRECTION_VERTICAL}]]};this.QJ=a.jl(g).on("swipeup",function(a){a.preventDefault();e.nextPage()});this.NJ=
a.jl(g).on("swipedown",function(a){a.preventDefault();e.previousPage()})}else g={recognizers:[[d.Swipe,{direction:d.DIRECTION_HORIZONTAL}]]},this.OJ=a.jl(g).on("swipeleft",function(a){a.preventDefault();e.nextPage()}),this.PJ=a.jl(g).on("swiperight",function(a){a.preventDefault();e.previousPage()})}}},Mk:function(){var a=this.eb();if(null!=this.Ua&&null!=a){var b;for(b=0;b<this.Ua.length;b++)a.off(this.Ua[b].eventType,this.Ua[b].eventHandler)}},JM:function(a){var b=this;a.find("*").each(function(){b.Np(this)})},
CD:function(){b.v.Sd()&&("vertical"==this.options.pageOptions.orientation?(null!=this.QJ&&(this.QJ.off("swipeup"),this.QJ=null),null!=this.NJ&&(this.NJ.off("swipedown"),this.NJ=null)):(null!=this.OJ&&(this.OJ.off("swipeleft"),this.OJ=null),null!=this.PJ&&(this.PJ.off("swiperight"),this.PJ=null)))},Rs:function(a,b){var d=f(document.createElement("span"));d.addClass(b);d.addClass(this.O.ji);d.text(a);return d},nba:function(){var a=this.Od(),b=this.A(this.xa.o8),b=this.Rs(b,this.O.bS),d=this.element.attr("id")+
"_oj_pgCtrl_acc_label";b.attr("id",d);a.append(b);return b},rba:function(){var a=this.A(this.xa.m8);return this.Rs(a,this.O.a9)},oba:function(){var a=this.A(this.xa.j8);return this.Rs(a,this.O.R8)},pba:function(){var a=this.A(this.xa.k8);return this.Rs(a,this.O.U8)},qba:function(){var a=this.A(this.xa.l8);return this.Rs(a,this.O.X8)},sba:function(){var a=this.A(this.xa.n8);return this.Rs(a,this.O.c9)},tba:function(){var a=this.Od(),b=f(document.createElement("div"));b.addClass(this.O.cS);var d=this.fea().attr("id");
b.attr("role","navigation");b.attr("aria-labelledby",d);a.append(b);return b},uU:function(){var a=this.ti(),b=f(document.createElement("div"));b.addClass(this.O.dS);a.append(b);return b},vU:function(){var a=this.qt(),b=f(document.createElement("a"));b.addClass(this.O.hA);var d=this.A(this.xa.p8);b.text(d);b.attr(this.Xg,"0");b.attr("href","#");a.append(b);return b},uba:function(){var a=this.qt(),b=f(document.createElement("span"));b.addClass(this.O.uG);var d=this.A(this.xa.q8,{maxRows:this.options.loadMoreOptions.maxCount});
b.text(d);a.append(b);return b},wU:function(a,b){var d=this.qt(),h=f(document.createElement("span"));h.addClass(this.O.iA);var k=this.iJ(a,b);h.append(k);d.append(h);return h},xU:function(a,b){var d="vertical"==this.options.pageOptions.orientation?!0:!1,h="dots"==this.options.pageOptions.type?!0:!1,k=this.options.pageOptions.layout;null==k&&(k=[this.tf.Sg]);var l=this.ti(),m=f(document.createElement("div"));m.addClass(this.O.fS);l.append(m);if(-1!=f.inArray(this.tf.Sg,k)&&!h||-1!=f.inArray(this.tf.Dv,
k)||-1!=f.inArray(this.tf.Yz,k)){l=f(document.createElement("div"));l.addClass(this.O.gS);m.append(l);var n=f(document.createElement("label"));n.attr("for",this.element.attr("id")+"_nav_input");n.addClass(this.O.hS);n.addClass("oj-label-inline");var p=this.A(this.xa.KR);n.text(p);l.append(n);n=f(document.createElement("input"));n.addClass(this.O.Ip);p=this.A(this.xa.IS);this._focusable(this.element);n.attr("id",this.element.attr("id")+"_nav_input");n.attr("title",p);n.attr(this.Xg,"0");n.val(this.yf()+
1);l.append(n);p=this.xW(a);if(0<this.Ad()&&this.og()){var r=f(document.createElement("span"));r.addClass(this.O.Pv);var s=this.A(this.xa.kG,{pageMax:p});r.text(s);l.append(r)}n.ojInputText({displayOptions:{messages:["notewindow"],converterHint:["notewindow"],validatorHint:["notewindow"]},rootAttributes:{style:"width: auto; min-width: 0;"},optionChange:this.Lfa.bind(this),validators:[{type:"numberRange",options:{min:1,max:p}}]})}if(-1!=f.inArray(this.tf.Sg,k)&&!h||-1!=f.inArray(this.tf.Dv,k)||-1!=
f.inArray(this.tf.g9,k))l=f(document.createElement("span")),l.addClass(this.O.Qv),n=this.iJ(a,b),0<n.text().length&&(l.append("("),l.append(n),l.append(")")),m.append(l);l=f(document.createElement("div"));l.addClass(this.O.eS);m.append(l);if(-1!=f.inArray(this.tf.Sg,k)&&!h||-1!=f.inArray(this.tf.Dv,k)||-1!=f.inArray(this.tf.RR,k))n=f(document.createElement("a")),n.addClass(this.O.jA),n.addClass(this.O.xs),d?n.addClass(this.O.T8):n.addClass(this.O.S8),n.addClass(this.O.Op),n.addClass(this.Ca.yp),n.addClass(this.Ca.vb),
p=this.A(this.xa.HS),this._hoverable(n),this._focusable(n),n.attr("title",p),n.attr(this.Xg,"0"),n.attr("href","#"),n.attr("oncontextmenu","return false;"),p=this.oba(),n.append(p),d&&n.css("display","block"),l.append(n),n=f(document.createElement("a")),n.addClass(this.O.jA),n.addClass(this.O.As),d?n.addClass(this.O.e9):n.addClass(this.O.d9),n.addClass(this.O.Op),n.addClass(this.Ca.yp),n.addClass(this.Ca.vb),p=this.A(this.xa.LS),this._hoverable(n),this._focusable(n),n.attr("title",p),n.attr(this.Xg,
"0"),n.attr("href","#"),n.attr("oncontextmenu","return false;"),p=this.sba(),n.append(p),d&&n.css("display","block"),l.append(n);if(-1!=f.inArray(this.tf.Sg,k)||-1!=f.inArray(this.tf.Dv,k)||-1!=f.inArray(this.tf.M8,k))n=f(document.createElement("div")),n.addClass(this.O.jS),l.append(n),this.yU(n,this.wW(),a,b);if(-1!=f.inArray(this.tf.Sg,k)&&!h||-1!=f.inArray(this.tf.Dv,k)||-1!=f.inArray(this.tf.RR,k))h=f(document.createElement("a")),h.addClass(this.O.jA),h.addClass(this.O.zs),d?h.addClass(this.O.Z8):
h.addClass(this.O.Y8),h.addClass(this.O.Op),h.addClass(this.Ca.yp),h.addClass(this.Ca.vb),k=this.A(this.xa.KS),this._hoverable(h),this._focusable(h),h.attr("title",k),h.attr(this.Xg,"0"),h.attr("href","#"),h.attr("oncontextmenu","return false;"),k=this.qba(),h.append(k),d&&h.css("display","block"),l.append(h),h=f(document.createElement("a")),h.addClass(this.O.jA),h.addClass(this.O.ys),d?h.addClass(this.O.W8):h.addClass(this.O.V8),h.addClass(this.O.Op),h.addClass(this.Ca.yp),h.addClass(this.Ca.vb),
k=this.A(this.xa.JS),this._hoverable(h),this._focusable(h),h.attr("title",k),h.attr(this.Xg,"0"),h.attr("href","#"),h.attr("oncontextmenu","return false;"),k=this.pba(),h.append(k),d&&h.css("display","block"),l.append(h);return m},yU:function(a,b,d){if(5>b){var h=this.A(this.xa.Q7);d=this.A(this.xa.P7);throw Error(h+"\n"+d);}h=f(document.createElement("div"));h.addClass(this.O.iS);a.append(h);a=this.Ad();var k=this.yf(),l=b;b=[];if(0<=k){if(this.og()&&a<=l)for(b[0]=0,d=1;d<a;d++)b[d]=d;else{b.push(0);
0!=k&&b.push(k);k!=a-1&&this.og()&&b.push(a-1);var l=l-b.length,m=k-1,n=1;for(!this.og()||k!=a-1&&k!=a-2||(n=0);l>n&&1<=m;)b.push(m),m--,l--;k+=1;for(-1==a&&(l=0<d?1:0);0<l&&(k<=a||-1==a);)b.push(k),k++,l--}b.sort(function(a,b){return a-b});for(d=0;d<b.length;d++)a=b[d],this.aI(h,a),d!=b.length-1&&a!=b[d+1]-1&&this.aI(h,-1);this.og()||this.aI(h,-1)}return h},aI:function(a,b){var d=this.yf(),h=null,k="rtl"===this.ec(),l="vertical"==this.options.pageOptions.orientation?!0:!1,m="dots"==this.options.pageOptions.type?
!0:!1;if(-1==b)h=f(document.createElement("span")),h.addClass(this.O.b9),h.text("...");else{d==b?(h=f(document.createElement("div")),h.addClass(this.Ca.hd),h.addClass(this.Ca.lf),h.addClass(this.Ca.vb),h.removeClass(this.Ca.pf)):(h=f(document.createElement("a")),h.removeClass(this.Ca.hd),h.removeClass(this.Ca.lf),h.removeClass(this.Ca.vb),h.addClass(this.Ca.pf),h.attr("href","#"));h.attr("data-oj-pagenum",b);m?h.addClass(this.O.Q8):h.addClass(this.O.zG);var n=this.A(this.xa.K9,{pageNum:(b+1).toString()});
this._hoverable(h);this._focusable(h);h.attr("title",n);h.attr(this.Xg,"0");h.attr("oncontextmenu","return false;");n=this.rba();h.append(n);n=f(document.createElement("span"));n.append((b+1).toString());m&&(n.addClass(this.O.P8),this._hoverable(n),d==b&&(n.addClass(this.Ca.hd),n.addClass(this.Ca.lf)));n.attr("dir",k?"rtl":"ltr");h.append(n);this._hoverable(h);l&&h.css("display","block")}a.append(h);return h},fea:function(){var a=this.Od(),b=null;a&&(b=a.find("."+this.O.bS))&&0<b.length&&(b=f(b.get(0)));
return b},Od:function(){return f(this.element)},ti:function(){if(!this.zT){var a=this.Od(),b=null;a&&(b=a.find("."+this.O.cS))&&0<b.length&&(this.zT=f(b.get(0)))}return this.zT},qt:function(){if(!this.qH){var a=this.ti(),b=null;a&&(b=a.children("."+this.O.dS))&&0<b.length&&(this.qH=f(b.get(0)))}return this.qH},qra:function(){if(!this.rH){var a=this.qt(),b=null;a&&(b=a.children("."+this.O.hA))&&0<b.length&&(this.rH=f(b.get(0)))}return this.rH},rra:function(){if(!this.sH){var a=this.qt(),b=null;a&&
(b=a.children("."+this.O.iA))&&0<b.length&&(this.sH=f(b.get(0)))}return this.sH},Sl:function(){if(!this.tH){var a=this.ti(),b=null;a&&(b=a.children("."+this.O.fS))&&0<b.length&&(this.tH=f(b.get(0)))}return this.tH},gea:function(){if(!this.uH){var a=this.Sl(),b=null;a&&(b=a.find("."+this.O.Ip))&&0<b.length&&(this.uH=f(b.get(0)))}return this.uH},hea:function(){if(!this.vH){var a=this.Sl(),b=null;a&&(b=a.find("."+this.O.Qv))&&0<b.length&&(this.vH=f(b.get(0)))}return this.vH},iea:function(){var a=this.Sl(),
b=null;a&&(b=a.find("."+this.O.iS))&&0<b.length&&(b=f(b.get(0)));return b},vJ:function(){var a=this.Sl(),b=null;if(a)if((b=a.find("."+this.O.eS))&&0<b.length)b=f(b.get(0));else return null;return b},wJ:function(){var a=this.Sl(),b=null;if(a)if((b=a.find("."+this.O.gS))&&0<b.length)b=f(b.get(0));else return null;return b}})})()});