/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojpagingtabledatasource"],function(b){b.xe=function(b,a){this.sr=b;this.Dm=a};o_("PagingHeaderSet",b.xe,b);b.xe.prototype.getData=function(b,a){return this.sr.getData(b+this.Dm,a)};b.b.g("PagingHeaderSet.prototype.getData",{getData:b.xe.prototype.getData});b.xe.prototype.getMetadata=function(b,a){return this.sr.getMetadata(b+this.Dm,a)};b.b.g("PagingHeaderSet.prototype.getMetadata",{getMetadata:b.xe.prototype.getMetadata});b.xe.prototype.R=function(){return this.sr.R()};
b.b.g("PagingHeaderSet.prototype.getCount",{R:b.xe.prototype.R});b.xe.prototype.zg=function(){return this.sr.zg()};b.b.g("PagingHeaderSet.prototype.getLevelCount",{zg:b.xe.prototype.zg});b.xe.prototype.Vb=function(b,a){return this.sr.Vb(b+this.Dm,a)};b.b.g("PagingHeaderSet.prototype.getExtent",{Vb:b.xe.prototype.Vb});b.xe.prototype.le=function(b,a){return this.sr.le(b+this.Dm,a)};b.b.g("PagingHeaderSet.prototype.getDepth",{le:b.xe.prototype.le});b.xe.prototype.Z2=function(){return this.sr};b.b.g("PagingHeaderSet.prototype.getHeaderSet",
{Z2:b.xe.prototype.Z2});b.xe.prototype.Ny=function(){return this.Dm};b.b.g("PagingHeaderSet.prototype.getStartIndex",{Ny:b.xe.prototype.Ny});b.Ka=function(f){if(!(f instanceof b.Ym))throw new b.X("Not a datagridatasource","Not a datagridatasource",b.X.Tb.ERROR);this.vc=f;this.$=0;this.Init()};o_("PagingDataGridDataSource",b.Ka,b);b.b.ga(b.Ka,b.Ym,"oj.PagingDataGridDataSource");b.Ka.prototype.Init=function(){b.Ka.q.Init.call(this);this.Sx()};b.b.g("PagingDataGridDataSource.prototype.Init",{Init:b.Ka.prototype.Init});
b.Ka.prototype.Sx=function(){this.vc.on("change",this.Qea.bind(this))};b.Ka.prototype.getPage=function(){return this.Nc};b.b.g("PagingDataGridDataSource.prototype.getPage",{getPage:b.Ka.prototype.getPage});b.Ka.prototype.setPage=function(f,a){a=a||{};f=parseInt(f,10);try{b.Ka.q.handleEvent.call(this,b.dc.D.BEFOREPAGE,{page:f,previousPage:this.Nc})}catch(d){return Promise.reject(null)}this.La=null!=a.pageSize?a.pageSize:this.La;a.startIndex=f*this.La;var c=this.Nc;this.Nc=f;this.$=a.startIndex;var e=
this;return new Promise(function(b,d){e.De(a).then(function(){b(null)},function(){e.Nc=c;e.$=e.Nc*e.La;d(null)})})};b.b.g("PagingDataGridDataSource.prototype.setPage",{setPage:b.Ka.prototype.setPage});b.Ka.prototype.De=function(b){this.Wl=!0;this.$=b.startIndex;var a=this;return new Promise(function(b){a.handleEvent("change",{operation:"sync",pageSize:a.La});b(void 0)})};b.Ka.prototype.fetch=function(b){this.La=b.pageSize+b.startIndex;b.startIndex=0;return this.De(b)};b.b.g("PagingDataGridDataSource.prototype.fetch",
{fetch:b.Ka.prototype.fetch});b.Ka.prototype.getStartItemIndex=function(){return this.$};b.b.g("PagingDataGridDataSource.prototype.getStartItemIndex",{getStartItemIndex:b.Ka.prototype.getStartItemIndex});b.Ka.prototype.getEndItemIndex=function(){return this.kj};b.b.g("PagingDataGridDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.Ka.prototype.getEndItemIndex});b.Ka.prototype.getPageCount=function(){var b=this.totalSize();return-1==b?-1:Math.ceil(b/this.La)};b.b.g("PagingDataGridDataSource.prototype.getPageCount",
{getPageCount:b.Ka.prototype.getPageCount});b.Ka.prototype.Qea=function(f){switch(f.operation){case "refresh":this.$=0;this.handleEvent("change",{operation:"sync",pageSize:this.La});this.handleEvent(b.na.D.REFRESH,null);break;case "reset":this.handleEvent(b.na.D.RESET,null);break;case "insert":this.handleEvent(b.na.D.ADD,{index:f.indexes.row});break;case "delete":this.handleEvent(b.na.D.REMOVE,null);break;case "update":f.indexes.row=0<=f.indexes.row-this.$?f.indexes.row-this.$:-1;this.handleEvent("change",
f);break;default:this.handleEvent("change",f),this.handleEvent(b.na.D.SYNC,null)}};b.Ka.prototype.R=function(b){var a=this.vc.R(b);return"row"===b&&0<=a?this.$+this.La<a?this.La:a-this.$:a};b.b.g("PagingDataGridDataSource.prototype.getCount",{R:b.Ka.prototype.R});b.Ka.prototype.xg=function(b){return this.vc.xg(b)};b.b.g("PagingDataGridDataSource.prototype.getCountPrecision",{xg:b.Ka.prototype.xg});b.Ka.prototype.Kf=function(f,a,d){var c;null==this.Wl?(c=new b.Gd(0,0,f.axis,null),null!=a&&a.success&&
a.success.call(d.success,c,f)):"row"===f.axis?(f.start+=this.$,f.start+f.count>this.$+this.La&&(f.count=this.La-f.start),this.Ut={callbacks:a,callbackObjects:d},this.vc.Kf(f,{success:this.aK.bind(this),error:this.Qfa.bind(this)},d)):this.vc.Kf(f,a,d)};b.b.g("PagingDataGridDataSource.prototype.fetchHeaders",{Kf:b.Ka.prototype.Kf});b.Ka.prototype.aK=function(f,a){var d,c,e;a.start-=this.$;a.count+=1;d=new b.xe(f,this.$);c=this.Ut.callbacks.success;e=this.Ut.callbackObjects.success;this.Ut=null;c.call(e,
d,a)};b.Ka.prototype.Qfa=function(b){var a,d;a=this.Ut.callbacks.error;d=this.Ut.callbackObjects.error;this.Ut=null;a.call(d,b)};b.Ka.prototype.wg=function(f,a,d){var c;if(null==this.Wl)c=new b.Vf(0,0,0,0,null),null!=a&&a.success&&a.success.call(d.success,c,f);else{for(c=0;c<f.length;c+=1)"row"===f[c].axis&&(f[c].start+=this.$,f[c].start+f[c].count>this.$+this.La&&(f[c].count=this.La-f[c].start));this.St={callbacks:a,callbackObjects:d};this.vc.wg(f,{success:this.Pea.bind(this),error:this.Oea.bind(this)},
d)}};b.b.g("PagingDataGridDataSource.prototype.fetchCells",{wg:b.Ka.prototype.wg});b.Ka.prototype.Pea=function(f,a){var d,c,e;for(d=0;d<a.length;d+=1)"row"===a[d].axis&&(a[d].start-=this.$,a[d].count+=1);d=new b.$h(f,this.$);c=this.St.callbacks.success;e=this.St.callbackObjects.success;this.St=null;this.kj=this.$+f.R("row")-1;this.handleEvent("sync",{data:Array(f.R("row")),startIndex:this.$});c.call(e,d,a)};b.Ka.prototype.Oea=function(b){var a,d;a=this.St.callbacks.error;d=this.St.callbackObjects.error;
this.St=null;a.call(d,b)};b.Ka.prototype.keys=function(b){return this.vc.keys({column:b.column,row:b.row+this.$})};b.b.g("PagingDataGridDataSource.prototype.keys",{keys:b.Ka.prototype.keys});b.Ka.prototype.Cg=function(b){b=this.vc.Cg(b);-1!=b.row&&(b.row-=this.$);return b};b.b.g("PagingDataGridDataSource.prototype.indexes",{Cg:b.Ka.prototype.Cg});b.Ka.prototype.getCapability=function(b){return this.vc.getCapability(b)};b.b.g("PagingDataGridDataSource.prototype.getCapability",{getCapability:b.Ka.prototype.getCapability});
b.Ka.prototype.size=function(){var b;if(null==this.Wl)return-1;b=this.vc.R("row");return this.vc.R("row")>this.La?this.La:b};b.b.g("PagingDataGridDataSource.prototype.size",{size:b.Ka.prototype.size});b.Ka.prototype.sort=function(b,a,d){this.vc.sort(b,a,d)};b.b.g("PagingDataGridDataSource.prototype.sort",{sort:b.Ka.prototype.sort});b.Ka.prototype.totalSize=function(){return null==this.Wl?-1:this.vc.R("row")};b.b.g("PagingDataGridDataSource.prototype.totalSize",{totalSize:b.Ka.prototype.totalSize});
b.Ka.prototype.totalSizeConfidence=function(){return"actual"};b.b.g("PagingDataGridDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.Ka.prototype.totalSizeConfidence});b.Ka.prototype.qd=function(b,a,d){return this.vc.qd(b,a,d)};b.b.g("PagingDataGridDataSource.prototype.moveOK",{qd:b.Ka.prototype.qd});b.Ka.prototype.move=function(b,a,d,c,e){this.vc.move(b,a,d,c,e)};b.b.g("PagingDataGridDataSource.prototype.move",{move:b.Ka.prototype.move});b.$h=function(b,a){this.zE=b;this.Dm=a};o_("PagingCellSet",
b.$h,b);b.$h.prototype.getData=function(b){return this.zE.getData({column:b.column,row:b.row+this.Dm})};b.b.g("PagingCellSet.prototype.getData",{getData:b.$h.prototype.getData});b.$h.prototype.getMetadata=function(b){return this.zE.getMetadata({column:b.column,row:b.row+this.Dm})};b.b.g("PagingCellSet.prototype.getMetadata",{getMetadata:b.$h.prototype.getMetadata});b.$h.prototype.R=function(b){return this.zE.R(b)};b.b.g("PagingCellSet.prototype.getCount",{R:b.$h.prototype.R});b.$h.prototype.K2=function(){return this.zE};
b.b.g("PagingCellSet.prototype.getCellSet",{K2:b.$h.prototype.K2});b.$h.prototype.Ny=function(){return this.Dm};b.b.g("PagingCellSet.prototype.getStartIndex",{Ny:b.$h.prototype.Ny})});