/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(b){b.na=function(f){if(!(f instanceof b.T))throw Error(b.T.gc._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+b.T.gc._ERR_DATA_INVALID_TYPE_DETAIL);this.vc=f;this.kj=this.$=0;this.Init()};o_("PagingTableDataSource",b.na,b);b.b.ga(b.na,b.T,"oj.PagingTableDataSource");b.na.prototype.Init=function(){b.na.q.Init.call(this)};b.b.g("PagingTableDataSource.prototype.Init",{Init:b.na.prototype.Init});b.na.prototype.getWrappedDataSource=function(){return this.vc};
b.b.g("PagingTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:b.na.prototype.getWrappedDataSource});b.na.prototype.getPage=function(){return"loadMore"==this.tB?0:this.VB()};b.b.g("PagingTableDataSource.prototype.getPage",{getPage:b.na.prototype.getPage});b.na.prototype.setPage=function(f,a){a=a||{};f=parseInt(f,10);try{b.na.q.handleEvent.call(this,b.dc.D.BEFOREPAGE,{page:f,previousPage:this.VB()})}catch(d){return Promise.reject(null)}var c=this.VB();this.La=null!=a.pageSize?a.pageSize:
this.La;a.pageSize=this.La;a.startIndex=f*this.La;this.$=null==a.startIndex?this.$:a.startIndex;this.tB="page";var e=this;return new Promise(function(d,f){0<e.La?e.vc.fetch(a).then(function(a){a.startIndex=0;e.FD();b.na.q.handleEvent.call(e,b.dc.D.PAGE,{page:e.VB(),previousPage:c});d(null)},function(){e.$=c*e.La;f(null)}):d(null)})};b.b.g("PagingTableDataSource.prototype.setPage",{setPage:b.na.prototype.setPage});b.na.prototype.getStartItemIndex=function(){return"loadMore"==this.tB?0:this.$};b.b.g("PagingTableDataSource.prototype.getStartItemIndex",
{getStartItemIndex:b.na.prototype.getStartItemIndex});b.na.prototype.getEndItemIndex=function(){return this.kj};b.b.g("PagingTableDataSource.prototype.getEndItemIndex",{getEndItemIndex:b.na.prototype.getEndItemIndex});b.na.prototype.getPageCount=function(){var b=this.totalSize();return-1==b?-1:Math.ceil(b/this.La)};b.b.g("PagingTableDataSource.prototype.getPageCount",{getPageCount:b.na.prototype.getPageCount});b.na.prototype.at=function(b,a){return this.vc.at(b,a)};b.b.g("PagingTableDataSource.prototype.at",
{at:b.na.prototype.at});b.na.prototype.fetch=function(b){b=b||{};if(null==b.startIndex)return this.setPage(this.getPage());this.tB="loadMore";this.$=null==b.startIndex?this.$:b.startIndex;var a=null!=b.pageSize?b.pageSize:this.La;b.pageSize=a;b.startIndex=this.$;var d=this;return new Promise(function(c,e){0<a?d.vc.fetch(b).then(function(a){d.FD();c(a)},function(a){e(a)}):c(null)})};b.b.g("PagingTableDataSource.prototype.fetch",{fetch:b.na.prototype.fetch});b.na.prototype.get=function(b,a){return this.vc.get(b,
a)};b.b.g("PagingTableDataSource.prototype.get",{get:b.na.prototype.get});b.na.prototype.getCapability=function(b){return this.vc.getCapability(b)};b.b.g("PagingTableDataSource.prototype.getCapability",{getCapability:b.na.prototype.getCapability});b.na.prototype.on=function(f,a){var d=this,c=this.vc;if(f==b.T.D.SYNC){var e=function(b){d.Vfa(b,a)};c.on(f,e);return e}if(f==b.T.D.ADD||f==b.T.D.REMOVE||f==b.T.D.CHANGE)return e=function(b){d.Pfa(b,a)},c.on(f,e),e;if(f==b.T.D.REFRESH||f==b.T.D.RESET)return e=
function(b){d.$=0;a(b)},c.on(f,e),e;if(f==b.dc.D.PAGE||f==b.dc.D.PAGECOUNT)b.na.q.on.call(this,f,a);else c.on(f,a);return a};b.b.g("PagingTableDataSource.prototype.on",{on:b.na.prototype.on});b.na.prototype.off=function(f,a){return f==b.dc.D.PAGE||f==b.dc.D.PAGECOUNT?(b.na.q.off.call(this,f,a),a):this.vc.off(f,a)};b.b.g("PagingTableDataSource.prototype.off",{off:b.na.prototype.off});b.na.prototype.sort=function(b){return this.vc.sort(b)};b.b.g("PagingTableDataSource.prototype.sort",{sort:b.na.prototype.sort});
b.na.prototype.totalSize=function(){return this.vc.totalSize()};b.b.g("PagingTableDataSource.prototype.totalSize",{totalSize:b.na.prototype.totalSize});b.na.prototype.totalSizeConfidence=function(){return this.vc.totalSizeConfidence()};b.b.g("PagingTableDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:b.na.prototype.totalSizeConfidence});b.na.prototype.VB=function(){return 0<this.La?Math.floor(this.$/this.La):0};b.na.prototype.Pfa=function(b,a){var d=[],c;for(c=0;c<b.indexes.length;c++){var e=
b.indexes[c];void 0!==e&&(e-=this.$,(0>e||e>=this.$+this.La)&&d.push(c))}if(0<d.length)for(d.sort(function(a,b){return a-b}),c=d.length-1;0<=c;c--)b.data.splice(d[c],1),b.indexes.splice(d[c],1),b.keys.splice(d[c],1);this.FD();b.startIndex=this.$;a(b)};b.na.prototype.Vfa=function(f,a){f.startIndex!=this.$&&(this.$=f.startIndex);this.FD();if("page"==this.tB){var d={};b.oc.$e(d,f);d.startIndex=0;a(d)}else a(f)};b.na.prototype.FD=function(){var b=this.totalSize();this.kj=this.$+this.La-1;0<b&&(this.kj=
this.kj>b-1?b-1:this.kj)};b.na.D={ADD:"add",REMOVE:"remove",RESET:"reset",SYNC:"sync",REFRESH:"refresh",SORT:"sort"};o_("PagingTableDataSource.EventType",b.na.D,b);b.dc=function(){};o_("PagingModel",b.dc,b);b.dc.prototype.getPage=function(){};b.b.g("PagingModel.prototype.getPage",{getPage:b.dc.prototype.getPage});b.dc.prototype.setPage=function(){};b.b.g("PagingModel.prototype.setPage",{setPage:b.dc.prototype.setPage});b.dc.prototype.getStartItemIndex=function(){};b.b.g("PagingModel.prototype.getStartItemIndex",
{getStartItemIndex:b.dc.prototype.getStartItemIndex});b.dc.prototype.getEndItemIndex=function(){};b.b.g("PagingModel.prototype.getEndItemIndex",{getEndItemIndex:b.dc.prototype.getEndItemIndex});b.dc.prototype.getPageCount=function(){};b.b.g("PagingModel.prototype.getPageCount",{getPageCount:b.dc.prototype.getPageCount});b.dc.prototype.totalSize=function(){};b.b.g("PagingModel.prototype.totalSize",{totalSize:b.dc.prototype.totalSize});b.dc.prototype.totalSizeConfidence=function(){};b.b.g("PagingModel.prototype.totalSizeConfidence",
{totalSizeConfidence:b.dc.prototype.totalSizeConfidence});b.dc.D={BEFOREPAGE:"beforePage",PAGE:"page",PAGECOUNT:"pageCount"};o_("PagingModel.EventType",b.dc.D,b)});