/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore"],function(b,f){(function(){var a="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),d={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-left oj-middle","center-bottom":"oj-center oj-bottom"};b.ya("oj.ojPopup",f.oj.baseComponent,
{widgetEventPrefix:"oj",options:{autoDismiss:"focusLoss",chrome:"default",initialFocus:"auto",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",modality:"modeless",role:"tooltip",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},_ComponentCreate:function(){this._super();var a=f("\x3cdiv\x3e");this.je=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-component");var b=f("\x3cdiv\x3e").addClass("oj-popup-content");b.attr("role","presentation");
b.appendTo(a);this.element.after(a);this.element.appendTo(b);this.element.show();this.BU();this.X_();this.qy=f.proxy(this.ry,this)},_destroy:function(){this.isOpen()&&this.Xp();this.YU();delete this.qy;delete this.xj;b.v.unwrap(this.element,this.je);this.element.hide();var a=this.Hn;isNaN(a)||(delete this.Hn,window.clearTimeout(a));this.ZU();this._super()},widget:function(){return this.je},open:function(a,d){if(this.isOpen()&&(this.close(),this.isOpen()))return;this.Tka(a);var f=this.je;a=this.lc;
b.Fa.Ji(f.attr("id"))&&f.attr("id",this.aC("wrapper"));if(!1!==this._trigger("beforeOpen")){this.j0(d);var h=this.options;this.NL(h.autoDismiss);this.X9();f.attr("role",h.role);d=h.position;var k="rtl"===this.ec();d=b.qc.Gg(d,k);var k="oj-popup-layer",l=h.tail;"none"!==l&&(k+=" "+["oj-popup-tail",l].join("-"));l={};l[b.N.Qa.gf]=f;l[b.N.Qa.ov]=a;l[b.N.Qa.tv]=d;l[b.N.Qa.np]=this.rt();l[b.N.Qa.bn]=k;l[b.N.Qa.Yh]=h.modality;b.N.pe().open(l);this._trigger("open");this.vK();this.Ega();this._on(f,{keydown:this.Kt,
keyup:this.Kt});a&&0<a.length&&this._on(a,{keydown:this.Kt,keyup:this.Kt})}},close:function(){if(this.isOpen()&&(!1!==this._trigger("beforeClose")||this.cx)){this.lka();var a=this.lc,d=this.je;this._off(d,"keydown keyup");a&&0<a.length&&this._off(a,"keydown keyup");this.ZU();a={};a[b.N.Qa.gf]=d;b.N.pe().close(a);this.Cja();this.NL();delete this.lc;d=this.options.position;d._ofo&&(delete d._ofo,delete d.of);this._trigger("close")}},isOpen:function(){return this.je.is(":visible")},refresh:function(){this._super();
this.isOpen()&&this.y_();var a=this.je;b.N.pe().sP(a,b.N.Bc.dn)},_setOption:function(a,d){var f=this.options;switch(a){case "tail":d!==f.tail&&this.ela(d);break;case "chrome":d!==f.chrome&&this.X_(d);break;case "position":this.j0(d);this.refresh();return;case "autoDismiss":this.isOpen()&&d!==f.autoDismiss&&this.NL(d);break;case "modality":this.isOpen()&&(f={},f[b.N.Qa.gf]=this.je,f[b.N.Qa.Yh]=d,b.N.pe().vu(f))}this._superApply(arguments)},sra:function(){return"oj-popup"},ela:function(a){this.YU();
this.BU(a);this.y_()},BU:function(a){a=a?a:this.options.tail;if("none"!==a){a=["oj-popup-tail",a].join("-");var d=f("\x3cdiv\x3e").hide();d.addClass("oj-popup-tail").addClass(a);d.attr("role","presentation");this.Z0=d.attr("id",this.aC("tail")).attr("id");var g=this.je;d.appendTo(g);g.addClass(a);this.isOpen()&&(d={},d[b.N.Qa.gf]=g,d[b.N.Qa.bn]="oj-popup-layer "+a,b.N.pe().vu(d))}},bX:function(){var a=this.Z0;return a?f(document.getElementById(a)):null},YU:function(){var a=this.bX();a&&a.remove();
delete this.Z0;a=this.je;a.removeClass(["oj-popup-tail",this.options.tail].join("-"));if(this.isOpen()){var d={};d[b.N.Qa.gf]=a;d[b.N.Qa.bn]="oj-popup-layer";b.N.pe().vu(d)}},X_:function(a){a=a?a:this.options.chrome;var b=this.je;"default"===a&&b.hasClass("oj-popup-no-chrome")?b.removeClass("oj-popup-no-chrome"):"none"!==a||b.hasClass("oj-popup-no-chrome")||b.addClass("oj-popup-no-chrome")},Tka:function(a){a?"string"===f.type(a)?a=f(a):1===a.nodeType&&(a=f(a)):a=f(document.activeElement);if(a instanceof
jQuery&&1<a.length)for(var d=this.je,g=0;g<a.length;g++){var h=a[0];if(!b.v.Qo(d[0],h)){a=f(h);break}}else if(!(a instanceof jQuery)||a instanceof jQuery&&0===a.length)a=f(document.activeElement);this.lc=a},j0:function(a){var b=this.options;a&&(b.position=f.extend(b[a],a));a=b.position;b=this.qy;f.isFunction(a.using)&&a.using!==b&&(a.origUsing=a.using);a.using=b;b=this.lc;a.of||(a.of=b,a._ofo=!0)},ry:function(c,e){var g=e.element.element;if(c.top!==g.css("top")||c.left!==g.css("left")){var h=this.bX();
if(h){h.hide();for(var k=0;k<a.length;k++)h.removeClass(a[k]),g.removeClass(a[k]);h.removeAttr("style");if(e.target&&0===e.target.height&&0===e.target.width&&(k="rtl"===this.ec(),k=b.qc.Gg(this.options.position,k).my,!b.Fa.Ji(k))){var k=k.split(" "),l=k[0],m="middle";1<k.length&&(m="center"===k[1]?"middle":k[1]);e.horizontal=l;e.vertical=m}k=d[[e.horizontal,e.vertical].join("-")];h.addClass(k);g.addClass(k);h.show();"left"===e.horizontal?(k=h.outerWidth(),k-=k+b.v.Hy(h.css("left")),c.left+=k-2):"right"===
e.horizontal&&(k=h.outerWidth(),k-=k+b.v.Hy(h.css("right")),c.left-=k-2);"top"===e.vertical?(k=h.outerHeight(),k-=k+b.v.Hy(h.css(e.vertical)),c.top+=k-2):"bottom"===e.vertical&&(k=h.outerHeight(),k-=k+b.v.Hy(h.css(e.vertical)),c.top-=k-2);g.css(c);"center"===e.horizontal&&"middle"!==e.vertical?(g=g.width(),g=Math.round((g/2-h.outerWidth()/2)/g*100),h.css({left:g+"%"})):"middle"===e.vertical&&(g=g.height(),g=Math.round((g/2-h.outerHeight()/2)/g*100),h.css({top:g+"%"}))}else g.css(c);h=this.options;
(g=h.position.origUsing)&&g(c,e);"focusLoss"===h.autoDismiss&&b.qc.cO(e)&&(this.oK=!0,this.Hn=this._delay(f.proxy(this.Xp,this),1))}},y_:function(){var a=this.je,d=this.options.position,f="rtl"===this.ec();a.position(b.qc.Gg(d,f))},vK:function(a){var b=this.Tba();a&&"none"===b&&(b="popup");"firstFocusable"===b&&(a=this.element.find(":focusable"),0<a.length?(f(a[0]).focus(),this._trigger("focus")):b="popup");"popup"===b&&(b=this.je,b.attr("tabindex","-1"),b.focus(),this._trigger("focus"))},Tba:function(){var a=
this.options,d=a.initialFocus;"auto"===d&&(d="modal"===a.modality?b.v.Sd()?"popup":"firstFocusable":"none");return d},wC:function(a,d){a||(a=document.activeElement);if(!a)return!1;var f=this.je;d&&(f=f.parent());return b.v.Qo(f[0],a)},pY:function(a){a||(a=document.activeElement);return b.v.Qo(this.lc[0],a)},lka:function(){this.oK?delete this.oK:this.wC(null,!0)&&this.lc.focus()},Kt:function(a){if(!a.isDefaultPrevented()){var b=a.type,d=a.target;if("keyup"===b&&a.keyCode===f.ui.keyCode.ESCAPE&&(this.wC(d)||
this.pY(d)))a.preventDefault(),this.close();else if("keydown"===b&&117===a.keyCode)this.wC(d)?(d=this.options,"modeless"===d.modality?(a.preventDefault(),a=this.lc,a.focus()):this.close()):this.pY(d)&&(a.preventDefault(),this.vK(!0));else if("keydown"===b&&a.keyCode===f.ui.keyCode.TAB&&this.wC(d)){var h=this.element.find(":tabbable");if(0<h.length){var b=h[0],h=h[h.length-1],k=this.je;b!==d&&k[0]!==d||!a.shiftKey?h!==d||a.shiftKey||(a.preventDefault(),h===b?(k.attr("tabindex","-1"),k.focus()):f(b).focus()):
(a.preventDefault(),b===h&&b===d?(k.attr("tabindex","-1"),k.focus()):f(h).focus())}else a.preventDefault(),d=this.options,"modeless"===d.modality?(a=this.lc,a.focus()):this.close()}}},NL:function(a){var d=this.KV,g=this.rt();d&&(delete g[b.N.Bc.Yr],delete this.KV);"focusLoss"===a&&(d=this.KV=f.proxy(this.Xba,this),g[b.N.Bc.Yr]=d);this.isOpen()&&(a={},a[b.N.Qa.gf]=this.je,a[b.N.Qa.np]=g,b.N.pe().vu(a))},Xba:function(a){var d=this.lc,g=this.je.parent(),h=a.target,k=this.AB;if(k&&(k=k.getLink())&&b.v.Qo(k[0],
h))return;if(!b.v.Qo(d[0],h)&&!b.v.Qo(g[0],h)){if(f(h).is(":focusable")){if("mousedown"===a.type||"touchstart"===a.type)return;this.oK=!0}this.close()}},X9:function(){var a=this.lc,b=this.je.attr("id"),d=a.attr("aria-describedby"),d=d?d.split(/\s+/):[];d.push(b);d=f.trim(d.join(" "));a.attr("aria-describedby",d)},Cja:function(){var a=this.lc,b=this.je.attr("id"),d=a.attr("aria-describedby"),d=d?d.split(/\s+/):[],b=f.inArray(b,d);-1!==b&&d.splice(b,1);(d=f.trim(d.join(" ")))?a.attr("aria-describedby",
d):a.removeAttr("aria-describedby")},Ega:function(){var a=b.Ma.Gy().os===b.Ma.Xi.AF,d=this.JK;d||(d=this.JK=new b.ye);var g;g=a?this.A("none"===this.options.initialFocus?"ariaLiveRegionInitialFocusNoneTouch":"ariaLiveRegionInitialFocusFirstFocusableTouch"):this.A("none"===this.options.initialFocus?"ariaLiveRegionInitialFocusNone":"ariaLiveRegionInitialFocusFirstFocusable");d.Jma(g);if(a){if(!this.AB){var d=this.aC("focusSkipLink"),h=this.lc,a=f.proxy(this.vK,this,!0);g=this.A("ariaFocusSkipLink");
this.AB=new b.ai(h,g,a,d)}this.RH||(d=this.aC("closeSkipLink"),h=this.element,a=f.proxy(this.Xp,this),g=this.A("ariaCloseSkipLink"),this.RH=new b.ai(h,g,a,d))}},ZU:function(){var a=this.JK;a&&(a.destroy(),delete this.JK);if(a=this.AB)a.destroy(),delete this.AB;if(a=this.RH)a.destroy(),delete this.RH},aC:function(a){var d=this.element.attr("id");b.Fa.Ji(d)&&(d=this.uuid);return[d,a].join("_")},Tq:function(){this.element.remove()},rt:function(){if(!this.xj){var a=this.xj={};a[b.N.Bc.Zr]=f.proxy(this.Xp,
this);a[b.N.Bc.$r]=f.proxy(this.Tq,this);a[b.N.Bc.dn]=f.proxy(this.refresh,this)}return this.xj},Xp:function(){this.cx=!0;this.close();delete this.cx}});b.Components.Om({ojPopup:{modality:b.Components.nh(function(){return b.ze.Yk("popup").modality})}})})()});