/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","jqueryui-amd/draggable","ojs/ojtouchproxy"],function(b,f){(function(){b.ya("oj.ojSlider",f.oj.editableValue,{defaultElement:"\x3cinput\x3e",version:"1.0.1",widgetEventPrefix:"oj",options:{distance:0,max:100,min:0,orientation:"horizontal",readOnly:!1,disabled:!1,step:1,type:"fromMin",value:0,rawValue:void 0},nZ:5,G0:null,ee:function(){return"rtl"===b.v.um()},_ComponentCreate:function(){this._super();this.element.removeAttr("pattern");this.gY=!1;
this.element.is("INPUT")?(this.gY=!0,this.element[0].style&&(this.Bla=this.element[0].style.cssText),this.eY=this.element.css("display"),this.element.css("display","none"),this.ri=f(this.element).wrap("\x3cdiv\x3e \x3c/div\x3e").parent()):this.ri=this.element;this.iU()},iU:function(){this.lZ=[];this.qg=null;var a="oj-slider ",a=this.kc()?a+"oj-slider-vertical":a+"oj-slider-horizontal",a=a+" oj-component oj-form-control";this.options.VO&&(a+=" oj-read-only");this.options.disabled&&(a+=" oj-disabled");
this.ri.removeClass();this.ri.addClass(a);this.Df="range"===this.options.type?!0:!1;this.GT();this.Cba();this.Yaa();this.baa();this.zba();this.Fba();this.oy();this.Cj()},mf:function(){this._super();this.Nt();var a=this.X7();if(a){var b=this.ri.find(".oj-slider-thumb"),c=a.attr("id");c||(c=a.attr("for"));b.attr("aria-labelledby",c);1<a.length&&1<b.length&&b[1].attr("aria-labelledby",String(c))}else if(a=this.element.attr("aria-label"))b=this.ri.find(".oj-slider-thumb"),b.attr("aria-label",a)},X7:function(){var a=
this.bda();if(null!==a&&0!==a.length)return a;a=this.ada();if(null!==a&&0!==a.length)return a},ada:function(){var a=this.element.prop("id");if(void 0!==a){var b=f("label[for\x3d'"+a+"']");if(0<b.length)return b;a="span[for\x3d'"+a+"']";if(0!==f(a).length)return f(a)}return null},bda:function(){var a=this.element.attr("aria-labelledby");if(void 0!==a){var b=f("label[id\x3d'"+a+"']");if(0<b.length)return b;a=f("span[id\x3d'"+a+"']");if(0<a.length)return a}else return null},widget:function(){return this.ri},
oi:function(a){this.G0=a},hg:function(){return this.G0},LB:function(){return this.element[0].id},GJ:function(a){return this.LB()+"-thumb"+a},PV:function(){return this.LB()+"-barValue"},dda:function(){return this.LB()+"-barBack"},vea:function(){return this.LB()+"-sliderWrapper"},Fba:function(){var a,b,c="",e="class\x3d'oj-slider-thumb ui-state-default' tabindex\x3d'0' role\x3d'slider'"+("aria-valuemin \x3d '"+this.$c()+"' ")+("aria-valuemax \x3d '"+this.Ye()+"' ")+"\x3e\x3c/span\x3e",g=[];b=this.Df?
this.options.value.length:1;for(a=0;a<b;a++)c="\x3cspan "+("id\x3d'"+this.GJ(a)+"' ")+e,g.push(c);this.rg=f(g.join("")).appendTo(this.Ci);this.wo=this.rg.eq(0);var h=this;this.rg.each(function(a){f(this).data("oj-slider-thumb-index",a);h.kc()&&f(this).attr("aria-orientation","vertical");h.options.disabled?(f(this).attr("aria-disabled","true"),f(this).removeAttr("tabindex")):f(this).removeAttr("aria-disabled");h.options.readOnly?f(this).attr("title","read only"):f(this).removeAttr("title")})},Cba:function(){var a=
this.vea(),b=this.ri.find("#"+a);b.length&&b.remove();this.Ci=f("\x3cdiv\x3e\x3c/div\x3e");f(this.Ci).attr("id",a);this.Ci.addClass("oj-slider-container");this.element.after(this.Ci);this.Ci[0].style.cssText=this.Bla;this.kc()&&""==this.Ci[0].style.height&&(this.Ci[0].style.height="150px")},Yaa:function(){var a=this.dda(),b=this.ri.find("#"+a);b.length&&b.remove();this.Vc=f("\x3cdiv\x3e\x3c/div\x3e");b="oj-slider-bar";b=this.kc()?b+" oj-slider-vertical":b+" oj-slider-horizontal";f(this.Vc).attr("id",
a);this.Vc.addClass(b);this.Ci.append(this.Vc);var c=this;this.Vc.on("mousedown"+c.eventNamespace,function(a){c.z_(a);c.sx(a);c.DB().focus()})},baa:function(){this.options.type&&(this.options.value?this.Df&&2!=this.options.value.length&&(this.options.value=[0<this.options.value.length?this.options.value[0]:this.$c(),this.Ye()],this.option("value",this.options.value,{_context:{Ic:!0,Va:!0}})):(this.options.value=this.Df?[this.$c(),this.Ye()]:this.$c(),this.option("value",this.options.value,{_context:{Ic:!0,
Va:!0}})))},zba:function(){var a=this.options,b="";if(a.type){this.Gb=f("\x3cdiv\x3e\x3c/div\x3e");f(this.Gb).attr("id",this.PV());this.Ci.append(this.Gb);var b="oj-slider-range oj-slider-bar-value",c=this;this.Gb.on("mousedown"+c.eventNamespace,function(a){c.z_(a);c.sx(a);c.DB().focus()});this.Gb=this.Ci.find("#"+this.PV());var e="";"fromMin"===a.type?e=" oj-slider-range-min":"fromMax"===a.type&&(e=" oj-slider-range-max");this.Gb.addClass(b+e)}else this.Gb&&this.Gb.remove(),this.Gb=null},nla:function(a){this.qM=
b.Ce.D1(a)},Kla:function(a){b.Ce.Z4(a)},Cj:function(){this.Hv()&&this._hoverable(this.ri);this._focusable(this.ri);this.rg.toArray().forEach(function(a){a=f(a);this.Np(a);this._on(a,this.Pla);this.nla(a)},this)},Xd:function(){return this.ri},WU:function(){this.rg.toArray().forEach(function(a){a=f(a);this.Kla(a)},this);this.Gb&&this.Gb.remove();this.Ci&&this.Ci.remove()},hma:function(){b.v.unwrap(this.element,this.ri);this.element.css("display",this.eY);this.Cs(this.element)},_destroy:function(){this.WU();
this.hma();return this._super()},z_:function(a){var b,c,e,g=this,h=this.options;e=0;this.fU=this.wo;if(h.disabled||h.readOnly)return!1;b=this.aea({x:a.pageX,y:a.pageY});c=this.Ye()-this.$c()+1;this.Df&&this.rg.each(function(a){var l=Math.abs(b-g.lq(a));if(c>l||c===l&&(a===g.tha||g.lq(a)===h.min))c=l,this.fU=f(this),e=a});this.qg=e;if(this.fU)return this.rg.hasClass("ui-state-hover")||this.Rq(a,e,b),this.DB().addClass("oj-active").focus(),this.Gb.addClass("oj-active"),!0},tga:function(a,b){var c=this.options;
if(c.disabled||c.readOnly)return!1;b.addClass("oj-active").focus();this.Gb.addClass("oj-active");return!0},Yha:function(a,b){var c=this.EW(b);this.Rq(a,this.qg,c,!0);c=100*this.iW(b);this.Df?this.n0(c,this.qg):this.k0(c);return!1},sx:function(a,b){this.rg.removeClass("oj-active");this.Gb.removeClass("oj-active");var c=this.EW(b);this.Rq(a,this.qg,c);this.Dh(a,this.qg,!1);this.qg=null;return!1},kc:function(){return"vertical"===this.options.orientation},FW:function(a){1<a&&(a=1);0>a&&(a=0);this.kc()&&
(a=1-a);return a},aea:function(a){var b=this.Dda(a);a=this.Ye()-this.$c();this.ee()&&!this.kc()&&(b=1-b);return this.Mh(this.$c()+b*a)},Dda:function(a){var b;this.kc()?(b=this.Vc.height(),a=a.y-this.Vc.offset().top):(b=this.Vc.width(),a=a.x-this.Vc.offset().left);return 0==b?1:b=this.FW(a/b)},DB:function(){return this.Df?f(this.rg[this.qg]):this.wo},iW:function(a){var b;a||(a=this.DB());this.kc()?(b=a.outerHeight()/2,b=a.offset().top+b,a=this.Vc.height(),b-=this.Vc.offset().top):(b=a.outerWidth()/
2,b=a.offset().left+b,a=this.Vc.width(),b-=this.Vc.offset().left);return 0==a?1:a=this.FW(b/a)},EW:function(a){var b;a=this.iW(a);b=this.Ye()-this.$c();this.ee()&&!this.kc()&&(a=1-a);return this.Mh(this.$c()+a*b)},cea:function(a){return this.lq(a?0:1)},Xda:function(a,b,c){return 2===this.options.value.length&&(0===a&&b>c||1===a&&b<c)?c:b},Rq:function(a,b,c,e){var f;this.Df?(f=this.cea(b),c=this.Xda(b,c,f),c!==this.lq(b)&&this.Wka(a,b,c,e)):c!==this.VW()&&(this.cla(a,c,e),e||this.gY&&this.element.val(c))},
cla:function(a,b,c){this.LC=this.Mh(b);c||(this.hc(this.LC,a),this.oy());this.zn(this.LC,a)},Dh:function(a,b,c){this.Df?(this.NY=this.Yda(b,this.lZ[b]),this.zn(this.NY,a),c||this.hc(this.NY,a)):(this.zn(this.LC,a),c||this.hc(this.LC,a));this.tha=b},Yda:function(a,b){var c,e;c=this.options.value.slice();for(e=0;e<c.length;e+=1)c[e]=this.Mh(c[e]);a===this.qg&&(c[a]=b);return c},VW:function(){return this.jX()},lq:function(a){return this.Cea(a)},Wka:function(a,b,c,e){this.lZ[b]=this.Mh(c);this.Dh(a,b,
e);e||this.oy()},_setOption:function(a,b,c){"value"===a&&(Array.isArray(b)?isNaN(b[0])?(this.Df=!1,this.Fk(a,b[0])):this.Df=!0:(this.Df=!1,this.Fk(a,b)));b="max"===a||"min"===a?this.Fk(a,b):"step"===a?this.Ax(b):b;"disabled"!=a&&this._super(a,b,c);"readOnly"===a&&(this.options.VO=b);"disabled"===a&&(this.options.disabled=b);switch(a){case "value":this.oy();this.Nt();break;case "min":case "max":this.GT();this.oy();this.Nt();break;case "orientation":case "readonly":case "step":case "type":case "disabled":this.cja()}},
cja:function(){this.WU();this.iU();this.mf()},jX:function(){var a=this.options.value;return a=this.Mh(a)},Cea:function(a){return this.Mh(this.options.value[a])},Mh:function(a){if(a<=this.$c())return this.$c();if(a>=this.Ye())return this.Ye();var b=0<this.options.step?this.options.step:1,c=(a-this.$c())%b;a-=c;2*Math.abs(c)>=b&&(a+=0<c?b:-b);return parseFloat(a.toFixed(5))},GT:function(){var a=this.$c();this.max=0!==(this.options.max-a)/this.options.step%1?this.options.max-(this.options.max-a)%this.options.step:
this.options.max},$c:function(){return this.options.min},Ye:function(){return this.max},jW:function(){var a;a=0<this.options.step?(this.Ye()-this.$c())/this.options.step:100;a=(this.kc()?this.Vc.height():this.Vc.width())/a;1>a&&(a=1);return this.kc()?[1,a]:[a,1]},HJ:function(a){return(this.lq(a)-this.$c())/(this.Ye()-this.$c())},oy:function(){var a,b,c,e;this.Df?this.rg.toArray().forEach(function(b,c){var d=f(b);a=100*this.HJ(c);this.ee()&&!this.kc()&&(a=100-a);this.kc()?f(d).css({top:100-a+"%"}):
f(d).css({left:a+"%"});f(d).attr("aria-valuenow",this.lq(c));this.n0(a,c)},this):(b=this.jX(),c=this.$c(),e=this.Ye(),a=e!==c?(b-c)/(e-c)*100:0,this.ee()&&!this.kc()&&(a=100-a),this.kc()?this.wo.css({top:100-a+"%"}):this.wo.css({left:a+"%"}),f(this.wo).attr("aria-valuenow",b),this.k0(a))},k0:function(a){var b=this.options.type;this.kc()?("fromMin"===b&&this.Gb.css({height:a+"%"}),"fromMax"===b&&this.Gb.css({height:100-a+"%"})):this.ee()?("fromMin"===b&&this.Gb.css({width:100-a+"%"}),"fromMax"===b&&
this.Gb.css({width:a+"%"})):("fromMin"===b&&this.Gb.css({width:a+"%"}),"fromMax"===b&&this.Gb.css({width:100-a+"%"}))},n0:function(a,b){var c=this.Gb.attr("id");if(0==b)switch(c=100*this.HJ(1),this.options.type){case "fromMin":this.kc()?this.Gb.css({height:a+"%"}):this.Gb.css({width:a+"%"});break;case "range":this.kc()?(this.Gb.css({top:100-c+"%"}),this.Gb.css({height:c-a+"%"})):this.ee()?(this.Gb.css({left:100-c+"%"}),this.Gb.css({width:c-(100-a)+"%"})):(this.Gb.css({left:a+"%"}),this.Gb.css({width:c-
a+"%"}))}else{var e=100*this.HJ(0);switch(this.options.type){case "fromMax":this.kc()?this.Gb.css({height:100-a+"%"}):this.Gb.css({width:100-a+"%"});break;case "range":this.kc()?document.getElementById(c)&&(this.Gb.css({top:100-a+"%"}),this.Gb.css({height:a-e+"%"})):this.ee()?document.getElementById(c)&&(this.Gb.css({left:a+"%"}),this.Gb.css({width:-a+100-e+"%"})):document.getElementById(c)&&this.Gb.css({width:a-parseInt(document.getElementById(c).style.left,10)+"%"})}}},Pla:{keydown:function(a){var b,
c,e,g=f(a.target).data("oj-slider-thumb-index");this.qg=g;switch(a.keyCode){case f.ui.keyCode.HOME:case f.ui.keyCode.END:case f.ui.keyCode.PAGE_UP:case f.ui.keyCode.PAGE_DOWN:case f.ui.keyCode.UP:case f.ui.keyCode.RIGHT:case f.ui.keyCode.DOWN:case f.ui.keyCode.LEFT:a.preventDefault(),f(a.target).addClass("oj-active")}e=this.options.step;b=this.Df?c=this.lq(g):c=this.VW();switch(a.keyCode){case f.ui.keyCode.HOME:c=this.$c();break;case f.ui.keyCode.END:c=this.Ye();break;case f.ui.keyCode.PAGE_UP:c=
this.Mh(b+(this.Ye()-this.$c())/this.nZ);break;case f.ui.keyCode.PAGE_DOWN:c=this.Mh(b-(this.Ye()-this.$c())/this.nZ);break;case f.ui.keyCode.UP:if(b===this.Ye())return;c=this.Mh(b+e);break;case f.ui.keyCode.RIGHT:if(!this.ee()||this.kc()){if(b===this.Ye())return;b+=e}else{if(b===this.$c())return;b-=e}c=this.Mh(b);break;case f.ui.keyCode.DOWN:if(b===this.$c())return;c=this.Mh(b-e);break;case f.ui.keyCode.LEFT:if(!this.ee()||this.kc()){if(b===this.$c())return;b-=e}else{if(b===this.Ye())return;b+=e}c=
this.Mh(b)}this.Rq(a,g,c)},keyup:function(a){var b=f(a.target).data("oj-slider-thumb-index");this.qg=b;this.Dh(a,b,!1);f(a.target).removeClass("oj-active");this.qg=null}},Yd:function(a,d){var c=this.options,e=this;this._superApply(arguments);b.ve.al([{W:"disabled",yc:!0},{W:"value"},{W:"title"},{W:"min"},{W:"max"},{W:"step"}],d,this,function(a){for(var b=["value","step","min","max"],d=0;d<b.length;d++){var f=b[d],m=f in a?a[f]:c[f];null!=m&&("step"===f?a[f]=e.Ax(m):"min"===f||"max"===f?a[f]=e.Fk(f,
m):"value"===f&&(Array.isArray(m)?a[f]=m:a[f]=e.Fk(f,m)))}});if(void 0===c.value)throw Error(this.A("noValue"));if(null!=c.min&&null!=c.max){if(c.max<c.min)throw Error(this.A("maxMin"));if(c.value<c.min||c.value>c.max)throw Error(this.A("valueRange"));}},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-slider-thumb-0"===a?this.widget().find(".oj-slider-thumb")[0]:"oj-slider-thumb-1"===a?this.widget().find(".oj-slider-thumb")[1]:"oj-slider-bar"===a?
this.widget().find("."+a)[0]:"oj-slider-bar-value"===a?this.widget().find("."+a)[0]:null},getSubIdByNode:function(a){if(null!=a){if(a.id===this.GJ(0)&&f(a).hasClass("oj-slider-thumb"))return{subId:"oj-slider-thumb-0"};if(a.id===this.GJ(1)&&f(a).hasClass("oj-slider-thumb"))return{subId:"oj-slider-thumb-1"};if(f(a).hasClass("oj-slider-bar"))return{subId:"oj-slider-bar"};if(f(a).hasClass("oj-slider-bar-value"))return{subId:"oj-slider-bar-value"}}return null},_GetDefaultStyleClass:function(){return"oj-slider"},
Fk:function(a,b){var c;c=null!==b?+b:b;if(isNaN(c))throw Error(this.A("optionNum",{option:a}));return c},Ax:function(a){if(null===a)return 1;a=this.Fk("step",a);if(0>=a)throw Error(this.A("invalidStep"));if(null===a||0>=a)a=1;return a},kra:function(){return this.Vc.offset().left+this.Vc.width()},tra:function(){return this.Vc.offset().left},HT:function(a){var b=this.jW(),c=a[0].style,e=this;a.draggable({axis:this.kc()?"y":"x",grid:b,disabled:!1,start:function(b){a[0]==f(e.rg)[0]?e.qg=0:a[0]==f(e.rg)[1]&&
(e.qg=1);e.tga(b,a)},drag:function(b,d){var k=d.position;e.kc()?(c.left="",k.left=""):(c.top="",k.top="");e.Yha(b,a);e.kc()?(0>k.top&&(k.top=0),k.top>e.Vc.height()&&(k.top=e.Vc.height())):(0>k.left&&(k.left=0),k.left>e.Vc.width()&&(k.left=e.Vc.width()));if(e.Df){var l;l=0==e.qg?f(e.rg[1]):f(e.rg[0]);if(e.kc()){var m=a.outerHeight()/2,n=e.Vc.offsetParent().offset().top;a.offset();l=l.offset().top+m-n}else m=a.outerWidth()/2,n=e.Vc.offsetParent().offset().left,a.offset(),l=l.offset().left+m-n;0==e.qg?
e.kc()?k.top<l&&(k.top=l):e.ee()?k.left<l&&(k.left=l):k.left>l&&(k.left=l):e.kc()?k.top>l&&(k.top=l):e.ee()?k.left>l&&(k.left=l):k.left<l&&(k.left=l)}},stop:function(b){this.style.width="";this.style.height="";e.sx(b,a)}})},Nt:function(){this.options.disabled||(this.Df?this.rg.toArray().forEach(function(a){a=f(a);this.HT(a)},this):this.HT(this.wo))},gra:function(){this.Df?this.rg.toArray().forEach(function(a){a=f(a);a.is(".ui-draggable")&&a.draggable("disable")},this):this.wo.is(".ui-draggable")&&
this.wo.draggable("disable")}})})()});