/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise","ojdnd","ojs/ojdomscroller","ojs/ojeditablevalue","ojs/ojmenu","ojs/ojdatasource-common","ojs/ojpagingtabledatasource","ojs/ojflattenedtreetabledatasource"],function(b,f){(function(){b.ya("oj.ojTable",f.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3ctable\x3e",widgetEventPrefix:"oj",options:{accessibility:null,currentRow:null,data:null,display:"list",dnd:{drag:null,drop:null,reorder:{columns:"disabled"}},emptyText:null,horizontalGridVisible:"auto",
rowRenderer:null,scrollPolicy:"auto",scrollPolicyOptions:{fetchSize:25,maxCount:500},selection:[],selectionMode:null,verticalGridVisible:"auto",columns:[{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,id:null,sortable:"auto",sortProperty:null,style:null}],columnsDefault:{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,
headerRenderer:null,headerStyle:null,headerText:null,sortable:"auto",sortProperty:null,style:null},beforeCurrentRow:null,ready:null,sort:null,optionChange:null},xa:{C8:"msgFetchingData",G8:"msgNoData",r8:"labelSelectColumn",LR:"labelSelectRow"},gc:{nR:"Did not change current row due to error.",mR:"Error detail: {error}.",K7:"Did not change current row due to unavailable row index.",J7:"Unavailable row index: {rowIdx}.",S7:"Invalid row index value.",R7:"Row index: {rowIdx}.",lR:"Invalid data type.",
kR:"Please specify the appropriate data type.",O7:"Invalid element type.",N7:"Only a \x3ctable\x3e element can be specified for ojTable.",M7:"Exceeded maximum rows for table scrolling.",L7:"Please reload with smaller data set."},Tz:"id",bj:"data",Gv:"indexes",ln:"key",ks:"keys",Ae:"startIndex",Ue:"endIndex",WQ:"pageSize",Vd:"column",Wd:"row",Oqa:"_headerColumn",Pqa:"_headerColumnText",Lqa:"_headerColumnAsc",Nqa:"_headerColumnDsc",r7:"_hdrCol",ps:"_focusedCalled",fA:"auto",Vg:"enabled",vn:"disabled",
ZR:"none",ni:{Ds:"single",Ep:"multiple"},K8:{Sg:"auto",u8:"loadMoreOnScroll"},Bh:{xp:"ascending",ms:"descending"},H7:"oj-table-dnd-reorder-table-id",Ub:{IR:32,g8:13,cA:38,bA:40,FR:37,GR:39,ER:36,DR:35,i8:9,h8:27,pn:"shiftKey"},getContextByNode:function(a){return this.getSubIdByNode(a,!0)},getDataForVisibleRow:function(a){a=this.p().qe(a);return null!=a?a.data("rowData"):null},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var d=a.subId;if("oj-table-cell"===d)return d=
parseInt(a.rowIndex,10),a=parseInt(a.columnIndex,10),this.p().hoa(d)[a];if("oj-table-header"===d||"oj-table-sort-ascending"===d||"oj-table-sort-descending"===d){if(a=a.index,a=f(this.p().joa()[a]),null!=a){if("oj-table-header"===d)return a[0];d="oj-table-sort-ascending"===d?a.find("."+b.f.C.zp):a.find("."+b.f.C.js);if(0<d.length)return d[0]}}else if("oj-table-footer"===d&&(a=a.index,d=this.p().ioa()[a],null!=d))return d;return null},getSubIdByNode:function(a,d){var c=f(a).closest("."+b.f.C.Es);if(0<
c.length)return{subId:"oj-table-cell",rowIndex:this.p().No(c),columnIndex:this.p().me(c)};c=f(a).closest("."+b.f.C.zp);if(0<c.length)return{subId:d?"oj-table-header":"oj-table-sort-ascending",index:this.p().me(c)};c=f(a).closest("."+b.f.C.js);if(0<c.length)return{subId:d?"oj-table-header":"oj-table-sort-descending",index:this.p().me(c)};c=f(a).closest("."+b.f.C.kn);if(0<c.length)return{subId:"oj-table-header",index:this.p().me(c)};c=f(a).closest("."+b.f.C.Lp);return 0<c.length?{subId:"oj-table-footer",
index:this.p().me(c)}:null},refresh:function(){this._super();this.Pd()},refreshRow:function(a){var d=this.eb();if(!d)return!1;var c=this.p().Nf();if(isNaN(a)||0>a||null!=c&&a>=c.length)throw d=this.gc.S7,c=b.ha.Mb(this.gc.R7,{rowIdx:a.toString()}),new RangeError(d+"\n"+c);var c=this.pq(a),e=d.get(c);if(null==e)return!1;var g=this;return this.Ai(function(){return e.then(function(b){g.VC(a,b)}).then(function(){return!0})})},widget:function(){var a=this.p().nc();return null!=a?a:this.element},_ComponentCreate:function(){this._super();
this.Dw();this.rja();this._on(this.Ml);if(this.CK()){var a=this.p().nc();this._on(a,this.Bca)}this.sja();this.Lq();this.BT=f.extend(!0,{},this.options)},mf:function(){this._super();this.p().h2(this.rj.bind(this));this.sC()},qf:function(a,b,c){var e={};this.hj=b.originalEvent;if(!(this.BK(f(this.hj.target))||this.cha(f(this.hj.target))||"touch"==c&&this.dha(f(this.hj.target)))){var g=this.p().Oo(f(this.hj.target),"oj-table-column-header-cell"),g=null==g?this.p().Qc(this.US):g,h=this.p().Oo(f(this.hj.target),
"oj-table-data-cell");null!=h&&(g=this.p().me(h),g=this.p().Qc(g));"keydown"===this.hj.type&&(h=this.kM.Pc(),this.hj.target==h[0]?null!=g&&null!=g[0]?e.position={my:"start top",at:"start bottom",of:g[0]}:(h=this.nj(),0<=h?(h=this.p().qe(h),e.position={my:"start top",at:"start bottom",of:h[0]}):e.position={my:"start top",at:"start bottom",of:this.hj.target}):e.position={my:"start top",at:"start bottom",of:this.hj.target});g.attr("data-oj-sortable")==this.Vg?(f(a.element).find("[data-oj-command\x3doj-table-sortAsc]").removeClass("oj-disabled"),
f(a.element).find("[data-oj-command\x3doj-table-sortDsc]").removeClass("oj-disabled")):(f(a.element).find("[data-oj-command\x3doj-table-sortAsc]").addClass("oj-disabled"),f(a.element).find("[data-oj-command\x3doj-table-sortDsc]").addClass("oj-disabled"));this.sf(b,c,e)}},_destroy:function(){this.eb();this.Mk();this.Nk();this.p().nd().removeAttr(b.Components.tn);this.element.children().remove("."+b.f.C.QG);this.element.children().remove("."+b.f.C.HG);this.element.children().remove("."+b.f.C.PG);this.element.children().remove("."+
b.f.C.RG);this.element.children().remove("."+b.f.C.AS);b.v.unwrap(this.element,this.p().nc());this.element.removeClass(b.f.C.tS);this.uw=!0},Dw:function(){this.Hka(function(){this.p().PE();this.bu(this.options.selection);this.xi()&&!this.HU&&this.tI.checkViewport().then(this.iV,null)});if(!this.element.is("table"))throw new RangeError(this.gc.O7+"\n"+this.gc.N7);this.element.addClass(b.f.C.H9);this.p().kna(this.CC(),this.GY());this.p().fqa();this.$Z();this.Rx();this.ZZ();this.p().PE();this.xi()&&
this.f_();this.options.disabled&&this.disable();this.yj()},Ml:{blur:function(a){var b=this.p().Pc();0<b.has(a.relatedTarget).length||null!=a.originalEvent&&a.originalEvent.explicitOriginalTarget==b[0]||(this.Aaa(),this.WT(),this.XT(!1),this.iD(!1))},focus:function(a){this.NT(a)},"focus .oj-table-column-header-acc-asc-link":function(a){var b=this;setTimeout(function(){b.NT(a)},0)},"click .oj-table-checkbox-acc-select-column":function(a){var b=this.p().me(f(a.currentTarget)),c=f(a.currentTarget).is(":checked");
c&&this.Ik(b,!0,!0,null);this.Jk(b,c,a.currentTarget,a,!0);a.stopPropagation()},"click .oj-table-checkbox-acc-select-row":function(a){var b=this.p().No(f(a.currentTarget)),c=f(a.currentTarget).is(":checked"),e=!1;c&&(e=this.Jh(b,!0,!0,null,a,!0));e&&this.kh(b,c,a.currentTarget,a,!0);a.stopPropagation()},keydown:function(a){if(!(this.BK(f(a.target))||null!=this.p().Zk()&&0<this.p().Zk().has(a.target).length)&&(this.i$(a.keyCode),1==this.Pl().length||2==this.Pl().length&&a[this.Ub.pn])){if(this.Bf(this.Ub.cA)||
this.Bf(this.Ub.bA)||this.Bf(this.Ub.IR)||this.Bf(this.Ub.ER)||this.Bf(this.Ub.DR))a.preventDefault(),a.stopPropagation();this.Bf(this.Ub.cA)||this.Bf(this.Ub.bA)?this.ufa(a):this.Bf(this.Ub.FR)||this.Bf(this.Ub.GR)?this.sfa(a):this.Bf(this.Ub.i8)&&this.tfa(a)}},keyup:function(a){if(!(this.BK(f(a.target))||null!=this.p().Zk()&&0<this.p().Zk().has(a.target).length)){if(1==this.Pl().length){var b=this.Pl()[0];b==this.Ub.IR?this.zfa(a):b==this.Ub.g8?this.wfa(a):b==this.Ub.ER?this.yfa(a):b==this.Ub.DR?
this.vfa(a):b==this.Ub.h8&&this.xfa(a);this.vL(b)}this.vL(a.keyCode)}},"mousedown .oj-table-body":function(a){this.pg=this.p().No(f(a.target));if(null!=this.pg){var d=this.p().qe(this.pg);null!=d&&d.prop("draggable")?this.pg=null:null==this.pg||a[this.Ub.pn]||b.v.Am(a)||this.tt(this.pg)&&1==this.vt().length||this.Os()}},"mouseup .oj-table-body":function(){this.pg=null},"mouseenter .oj-table-body-row":function(a){f(a.currentTarget).addClass(b.f.la.dk);this.YJ(a.target)},"mouseleave .oj-table-body-row":function(a){f(a.currentTarget).removeClass(b.f.la.dk)},
"mousedown .oj-table-column-header-cell":function(a){var b=this.p().me(f(a.currentTarget));this.Ik(b,!0,!0,a);f(a.target).data(this.ps,!0)},"mouseenter .oj-table-column-header-cell":function(a){f(a.currentTarget).addClass(b.f.la.dk);a=this.p().me(f(a.currentTarget));this.C0(a)},"mouseleave .oj-table-column-header-cell":function(a){f(a.currentTarget).removeClass(b.f.la.dk);a=this.p().me(f(a.currentTarget));this.xq(a,!0);this.xq(a,!1)},"mousedown .oj-table-data-cell":function(a){var b=this.p().No(f(a.currentTarget));
this.Jh(b,!0,!0,a.currentTarget,a);f(a.target).data(this.ps,!0)},"mouseenter .oj-table-data-cell":function(a){f(a.currentTarget).addClass(b.f.la.dk)},"mouseleave .oj-table-data-cell":function(a){f(a.currentTarget).removeClass(b.f.la.dk)},"click .oj-table-column-header-asc-link":function(a){var b=this.p().me(f(a.target)),c=this.p().Qc(b);c&&(c.data("sorted")==this.Bh.xp?this.yk(b,!1,a):this.yk(b,!0,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-asc-link":function(a){var b=
this.p().me(f(a.target));this.yk(b,!0,a);a.preventDefault();a.stopPropagation()},"click .oj-table-column-header-dsc-link":function(a){var b=this.p().me(f(a.target)),c=this.p().Qc(b);c&&(c.data("sorted")==this.Bh.ms?this.yk(b,!0,a):this.yk(b,!1,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-dsc-link":function(a){var b=this.p().me(f(a.target));this.yk(b,!1,a);a.preventDefault();a.stopPropagation()},"click .oj-table-data-cell":function(a){var d=this.p().No(f(a.currentTarget));
if(!f(a.target).data(this.ps)){var c=this.Jh(d,!0,!0,a.currentTarget,a);f(a.target).data(this.ps,!1);if(!c)return}if(a[this.Ub.pn]){if(c=this.Pda(),null!=c)if(window.getSelection().removeAllRanges(),d<c){var e;for(e=d;e<=c;e++)this.kh(e,!0,a.currentTarget,a,!0)}else for(e=c;e<=d;e++)this.kh(e,!0,a.currentTarget,a,!0)}else b.v.Am(a)?this.kh(d,!this.tt(d),a.currentTarget,a,!0):0==this.Pl().length&&(c=this.tt(d),this.kh(d,!c,a.currentTarget,a,!0),this.CK()&&this.ut()==this.ni.Ep&&!c&&this.p().ona(d))},
"contextmenu .oj-table-data-cell":function(a){var b=this.p().No(f(a.currentTarget)),b=this.pq(b);this.gm({rowKey:b},a)},"click .oj-table-column-header-cell":function(a){var d=this.p().me(f(a.currentTarget));f(a.target).data(this.ps)||(this.Ik(d,!0,!0,a),f(a.target).data(this.ps,!1));if(a[this.Ub.pn]){var c=this.Oda();if(null!=c)if(d<c){var e;for(e=d;e<=c;e++)this.Jk(e,!0,a.currentTarget,a,!0)}else for(e=c;e<=d;e++)this.Jk(e,!0,a.currentTarget,a,!0)}else b.v.Am(a)?this.Jk(d,!this.Pw(d),a.currentTarget,
a,!0):0==this.Pl().length&&(this.rw(),this.Jk(d,!this.Pw(d),a.currentTarget,a,!0),this.dh().q5(d,!0))},"dragstart .oj-table-column-header-cell":function(a){return this.dh().soa(a)},"dragenter .oj-table-column-header-cell":function(a){return this.dh().poa(a)},"dragover .oj-table-column-header-cell":function(a){return this.dh().roa(a)},"dragleave .oj-table-column-header-cell":function(a){return this.dh().qoa(a)},"drop .oj-table-column-header-cell":function(a){return this.dh().toa(a)},"dragend .oj-table-column-header-cell":function(){return this.dh().ooa()},
"dragstart .oj-table-body-row":function(a){return this.dh().Joa(a)},"drag .oj-table-body-row":function(a){return this.dh().Eoa(a)},"dragend .oj-table-body-row":function(a){return this.dh().Foa(a)},"dragenter .oj-table-body":function(a){return this.dh().Goa(a)},"dragover .oj-table-body":function(a){return this.dh().Ioa(a)},"dragleave .oj-table-body":function(a){return this.dh().Hoa(a)},"drop .oj-table-body":function(a){return this.dh().Koa(a)}},Bca:{touchstart:function(a){if(1==a.originalEvent.touches.length&&
this.ut()==this.ni.Ep)if(f(a.target).hasClass(b.f.C.NG)||f(a.target).hasClass(b.f.C.wS))a.preventDefault(),this.pg=this.p().s3().data("rowIdx");else if(f(a.target).hasClass(b.f.C.MG)||f(a.target).hasClass(b.f.C.vS))a.preventDefault(),this.pg=this.p().t3().data("rowIdx")},touchmove:function(a){null!=this.pg&&(a.preventDefault(),a=this.gX(a),this.YJ(a))},touchend:function(a){null!=this.pg&&(a=this.gX(a),this.YJ(a));this.pg=null},touchcancel:function(){this.pg=null}},Pd:function(){var a=null,b=!1;this.i!=
this.options[this.bj]&&(this.OH(),null==this.i?b=!0:a=0,this.xi()&&(null!=this.tI&&this.tI.destroy(),this.f_()));this.mU!=this.p().P2()&&this.p().h2(this.rj.bind(this));this.p().ana();this.p().Cpa();this.nja();if(b)return this.sC();var c=this;this.Ai(function(){return c.uC(a)})},_setOption:function(a,b){this._superApply(arguments);this.iha(a,b)?this.Pd():"selection"==a?(this.Os(),this.rw(),this.bu(b)):"currentRow"==a&&this.gm(b,null,!0)},i$:function(a){var b=!1,c;for(c in this.Ub)this.Ub.hasOwnProperty(c)&&
this.Ub[c]==a&&(b=!0);if(b){b=this.Pl();c=!1;var e,g=b.length;for(e=0;e<g;e++)if(b[e]==a){c=!0;break}c||b.push(a)}},$S:function(a,b,c,e){var g=this.p().k2(a,b[this.ln]);this.p().lP(g,!0);this.p().R3(a,g,b,c);this.VC(a,b,g,c,e,!0)},NT:function(a){var b=this.nj(),c=this.Ol();null==b&&null==c&&(this.CC()?this.Jh(0,!0,!0,null,a):this.Ik(0,!0,!1,a))},yaa:function(){this.Jn=null;this.iD(!1)},OH:function(){null!=this.i&&this.Mk();this.i=null},ok:function(){this.cga();this.dga();this.HU=!1},Aaa:function(){this.GK=
[]},WT:function(){var a=this.Ol();null!=a&&this.Ik(a,!1,!1,null);this.US=-1},XT:function(a){null!=this.nj()&&this.Jh(-1,!0,a,null,null)},rw:function(){var a=this.SW(),b,c=a.length;for(b=0;b<c;b++)this.Jk(a[b],!1,null,null,!1)},Os:function(){var a=this.vt(),b,c=a.length;for(b=0;b<c;b++)this.kh(a[b],!1,null,null,!1);this.CK()&&this.ut()==this.ni.Ep&&this.p().Jpa()},$T:function(a){var d=this.wea();if(null!=d){var c=this.p().Qc(d),e=c.data("sorted");c.data("sorted",null);d!=a?e==this.Bh.xp?this.xq(d,
!0):this.xq(d,!1):(c.find("."+b.f.C.zp).removeClass(b.f.la.hd),c.find("."+b.f.C.js).removeClass(b.f.la.hd))}},Cca:function(a){var d=this;this.Ai(function(){var c=!1;if(1<a.length){var e,g=a.length,h=!0;for(e=0;e<g;e++)if(0!=e&&a[e-1].Th!=a[e].Th-1){h=!1;break}if(h){c=d.p().nd();h=f(document.createDocumentFragment());g=a.length;for(e=0;e<g;e++)d.$S(a[e].Th,a[e].row,h,a[0].Th);0==a[0].Th?c.prepend(h):(e=d.p().qe(a[0].Th),null!=e?c[0].insertBefore(h[0],e[0]):c[0].insertBefore(h[0],null));d.p().br();
b.Components.Sf(c[0]);c=!0}}if(!c)for(g=a.length,e=0;e<g;e++)d.$S(a[e].Th,a[e].row);d.p().br();d.Rx()})},Dca:function(a){var b=this;this.Ai(function(){var c,e=a.length;for(c=0;c<e;c++)b.VC(a[c].Th,a[c].row);b.Rx()})},Eca:function(a){var d=this,c=this.aW(),e=null!=c?c.rowKey:null;this.Ai(function(){var c,f,k=a.length;for(c=0;c<k;c++)d.p().Y4(a[c].Th),null!=e&&(f=a[c].row[d.Tz],b.b.mh(f,e)&&(d.gm(null,null),e=null));d.Rx();c=d.p().Nf();null!=c&&0!=c.length||this.y0()})},xb:function(){this.Jn||(this.Jn=
this.VV());return this.Jn},VV:function(){var a=this.options.columns,b=this.options.columnsDefault;if((0==a.length||1==a.length&&null==a[0].id&&null==a[0].headerText&&null==a[0].field)&&null==b.headerText&&null==b.field)return[];var c=[],e,g=a.length;for(e=0;e<g;e++)c[e]=f.extend({},b,a[e]);a=[];b=c.length;for(e=0;e<b;e++)a.push(c[e]);e=this.eb();c=!1;null!=e&&"full"==e.getCapability("sort")&&(c=!0);for(e=0;e<b;e++)null==a[e][this.Tz]&&(a[e][this.Tz]=this.r7+e),null!=a[e].sortable&&a[e].sortable!=
this.fA||!c||(a[e].sortable=this.Vg);return a},TV:function(a){var d=this.xb();if(null!=d){var c,e,g=d.length;for(c=0;c<g;c++)if(e=d[c],b.b.mh(e.id,a))return c}return null},UV:function(a){a=this.p().Pc().find(a);var b=[];if(a&&0<a.length){var c,e,g,h,k,l=a.length;for(c=0;c<l;c++){h=this.p().me(f(a.get(c)));g=!1;k=b.length;for(e=0;e<k;e++)b[e]==h&&(g=!0);g||b.push(h)}}return b},GB:function(a){var b=this.xb();return null!=b&&a<b.length?b[a][this.Tz]:null},Qn:function(a,b){var c=this.xb()[a];return"cell"==
b?c.renderer:"footer"==b?c.footerRenderer:"header"==b?c.headerRenderer:null},aW:function(){return this.eb()?this.bq:null},eb:function(){if(!this.i&&null!=this.options.data){var a=this.options.data;if(a instanceof b.T||a instanceof b.na)this.i=a;else throw Error(this.gc.lR+"\n"+this.gc.kR);this.Lq()}return this.i},Ol:function(){return this.UV("."+b.f.C.kn+"."+b.f.la.cj)[0]},nj:function(){return this.QW("."+b.f.C.Kp+"."+b.f.la.cj)[0]},lra:function(a){return this.dJ(a).Ij},Pw:function(a){return this.dJ(a).selected},
HB:function(){return null==this.options.selectionMode?null:this.options.selectionMode[this.Vd]},dJ:function(a){a=this.p().Qc(a);return{Ij:a.hasClass(b.f.la.cj),selected:a.hasClass(b.f.la.hd)}},Pl:function(){this.GK||(this.GK=[]);return this.GK.reverse()},Oda:function(){return null!=this.eo&&0<this.eo.length?this.eo[0]:null},Pda:function(){return null!=this.fo&&0<this.fo.length?this.fo[0]:null},sea:function(a,b){var c=[];if(null!=a){var e,g=a[this.Gv].length;for(e=0;e<g;e++)c.push({row:{data:a[this.bj][e],
key:a[this.ks][e],index:a[this.Gv][e]},Th:b+e})}return c},Tw:function(a){var d=this.p().Nf();if(null!=d&&0<d.length){var c,e=d.length;for(c=0;c<e;c++)if(b.b.mh(f(d[c]).data("rowKey"),a))return c}return null},hq:function(a){var d=this.p().Nf();if(null!=d&&0<d.length){var c,e=d.length;for(c=0;c<e;c++)if(b.b.mh(f(d[c]).data("rowKey"),a))return a=this.eb(),d=0,a instanceof b.na&&(d=a.getStartItemIndex()),c+d}return null},QW:function(a){a=this.p().Pc().find(a);var b=[];if(a&&0<a.length){var c,e,g,h,k,
l=a.length;for(c=0;c<l;c++){g=this.p().No(f(a.get(c)));k=!1;h=b.length;for(e=0;e<h;e++)b[e]==g&&(k=!0);k||b.push(g)}}return b},Uw:function(a){var d=this.p().Nf();if(null!=d&&0<d.length){var c=this.eb(),e=0;c instanceof b.na&&(e=c.getStartItemIndex());for(var g=d.length,c=0;c<g;c++)if(e+c==a)return f(d[c]).data("rowKey")}return null},pq:function(a){a=this.p().qe(a);return null!=a?a.data("rowKey"):null},RW:function(){return this.options.rowRenderer},tt:function(a){return this.p().qe(a).hasClass(b.f.la.hd)},
ut:function(){return null==this.options.selectionMode?null:this.options.selectionMode[this.Wd]},SW:function(){return this.UV("."+b.f.C.kn+"."+b.f.la.hd)},vt:function(){return this.QW("."+b.f.C.Kp+"."+b.f.la.hd)},TW:function(){var a=this.vt(),b=this.SW(),c=null,e=!0;if(null!=a&&0<a.length)c=a;else if(null!=b&&0<b.length)c=b,e=!1;else return null;var a=[],b=0,g=null,f,k,l,m,n,p=c.length;for(n=0;n<p;n++)l=c[n],0==n?(f={},f[this.Ae]={},f[this.Ue]={},f.startKey={},f.endKey={},e?(m=this.pq(l),k=this.hq(m),
f.startKey[this.Wd]=m,f.endKey[this.Wd]=m,f[this.Ae][this.Wd]=k,f[this.Ue][this.Wd]=k):(f[this.Ae][this.Vd]=l,f[this.Ue][this.Vd]=l,m=this.GB(l),f.startKey[this.Vd]=m,f.endKey[this.Vd]=m),a[0]=f):(f=a[b],e?(m=this.pq(l),k=this.hq(m),f.endKey[this.Wd]=m,f[this.Ue][this.Wd]=k):(f[this.Ue][this.Vd]=l,m=this.GB(l),f.endKey[this.Vd]=m),l!=g+1&&(e?(m=this.pq(g),k=this.hq(m),f.endKey[this.Wd]=m,f[this.Ue][this.Wd]=k,f={},f[this.Ae]={},f[this.Ue]={},f.startKey={},f.endKey={},m=this.pq(l),k=this.hq(m),f.startKey[this.Wd]=
m,f.endKey[this.Wd]=m,f[this.Ae][this.Wd]=k,f[this.Ue][this.Wd]=k):(f[this.Ue][this.Vd]=g,m=this.GB(g),f.endKey[this.Vd]=m,f={},f[this.Ae]={},f[this.Ue]={},f.startKey={},f.endKey={},f[this.Ae][this.Vd]=l,f[this.Ue][this.Vd]=l,m=this.GB(l),f.startKey[this.Vd]=m,f.endKey[this.Vd]=m),b++,a[b]=f)),g=l;return a},wea:function(){var a=this.p().Oy(),b,c,e=a.length;for(b=0;b<e;b++)if(c=f(a[b]).data("sorted"),null!=c)return b;return null},bC:function(a){a=a.find(":tabbable");return null!=a&&0<a.length?a:null},
dh:function(){this.V0||(this.V0=new b.cb(this));return this.V0},p:function(){this.kM||(this.kM=new b.f(this));return this.kM},gX:function(a){a=a.originalEvent.changedTouches[0];return f(document.elementFromPoint(a.clientX,a.clientY))},rj:function(a,b){var c=b.item.attr("data-oj-command"),e=this.p().Oo(f(this.hj.target),"oj-table-column-header-cell"),g=this.p().Oo(f(this.hj.target),"oj-table-data-cell"),h=null;null!=e&&(h=this.p().me(e));null!=g&&(h=this.p().me(g));"oj-table-sortAsc"==c?this.yk(h,
!0,a):"oj-table-sortDsc"==c&&this.yk(h,!1,a)},Wea:function(a){this.ok();b.r.error(a)},Xea:function(){this.b0()},RJ:function(a){try{var d=this;this.Ai(function(){var c=0,g=d.eb();g instanceof b.na&&(c=g.getStartItemIndex());var g=[],f,k=a[d.bj].length;for(f=0;f<k;f++)g[f]=f+c+a[d.Ae];d.QZ({data:a[d.bj],keys:a[d.ks],indexes:g},a[d.Ae])})}catch(c){b.r.error(c)}finally{this.ok()}},gC:function(){try{var a=this.uC(),d=this;this.Ai(function(){d.gm(null,null);return a})}catch(c){b.r.error(c)}finally{this.ok()}},
Xn:function(){try{this.sC();var a=this;this.Ai(function(){a.gm(null,null)})}catch(d){b.r.error(d)}finally{this.ok()}},SJ:function(a){try{var d=this.eb(),c=a[this.bj],e=a[this.Gv],g=a[this.ks];c instanceof Array||(c=[c]);a=0;d instanceof b.na&&(a=d.getStartItemIndex());var d=[],f,k=c.length;for(f=0;f<k;f++){var l=e[f]-a;void 0!==l&&d.push({row:{data:c[f],key:g[f],index:e[f]},Th:l})}0<d.length&&this.Cca(d)}catch(m){b.r.error(m)}finally{this.ok()}},Zea:function(a){try{var d=this.eb(),c=a[this.bj],e=
a[this.Gv],g=a[this.ks];c instanceof Array||(c=[c]);a=0;d instanceof b.na&&(a=d.getStartItemIndex());var d=[],f,k=c.length;for(f=0;f<k;f++){var l=e[f]-a;void 0!==l&&d.push({row:{data:c[f],key:g[f],index:e[f]},Th:l})}0<d.length&&this.Dca(d)}catch(m){b.r.error(m)}finally{this.ok()}},TJ:function(a){try{var d=this.eb(),c=a[this.bj],e=a[this.Gv],g=a[this.ks];c instanceof Array||(c=[c]);a=0;d instanceof b.na&&(a=d.getStartItemIndex());var d=[],f;for(f=c.length-1;0<=f;f--){var k=e[f]-a;void 0!==k&&d.push({row:{data:c[f],
key:g[f],index:e[f]},Th:k})}0<d.length&&this.Eca(d)}catch(l){b.r.error(l)}finally{this.ok()}},UJ:function(a){try{var d;if(null!=a){var c=this.xb(),e,g,f,k=c.length;for(e=0;e<k;e++)if(g=c[e],f=null==g.sortProperty?g.field:g.sortProperty,a.header==f){d=e;break}null!=d&&this.YZ(d,a.direction==this.Bh.xp)}var l=this.options.selection;if(null!=l){a=!1;if(1<l.length)a=!0;else if(null!=l[0]){var m=l[0][this.Ue];b.b.mh(l[0][this.Ae],m)||null==m||(a=!0)}a&&(this.bu(null),this.option("selection",null,{_context:{Ic:!0,
Va:!0}}))}this.gm(this.options.currentRow,null);var n=this;this.Ai(function(){return n.uC(null)}).then(function(){null!=d&&setTimeout(function(){n.L_(d)},0)})}catch(p){b.r.error(p)}finally{this.ok()}},sfa:function(a){var b=this.Ol(),c=this.xb();if(null!=b){var e=b;this.Bf(this.Ub.FR)?e=0<b?b-1:b:this.Bf(this.Ub.GR)&&(e=b<c.length-1?b+1:b);e!=b&&(this.Ik(e,!0,!1,null),a[this.Ub.pn]&&(c=this.Pw(e),this.Jk(e,!c,null,a,!0),c&&this.Pw(b)&&this.Jk(b,!1,null,a,!0)))}},tfa:function(a){var b=!1,c=this.nj();
if(null!=c&&this.X0){var e=document.activeElement,g=this.p().nd();if(f.contains(g[0],e))return;e=this.bC(g);null==e||a[this.Ub.pn]||(b=!0,c=this.p().qe(c),c=this.bC(c),null!=c?f(c[0]).focus():f(e[0]).focus(),a.preventDefault(),a.stopPropagation())}if(!b){e=this.p().Pc();b=this.bC(f(document));c=b.length;e=this.bC(e);e=null!=e?e.length:0;g=b.index(this.p().Pc());if(a[this.Ub.pn])if(0<=g){if(0==g)return;f(b[g-1]).focus()}else return;else{if(g==c-1)return;f(b[g+e+1]).focus()}a.preventDefault();a.stopPropagation()}this.vL(a.keyCode)},
ufa:function(a){var b=this.nj(),c=this.Ol();if(null!=b){var c=this.p().Nf(),e=null!=c?c.length:0,c=b;this.Bf(this.Ub.cA)?c=0<b?b-1:b:this.Bf(this.Ub.bA)&&(c=b<e-1?b+1:b);c!=b?this.Jh(c,!0,!0,null,a)&&a[this.Ub.pn]&&(e=this.tt(c),this.kh(c,!e,null,a,!0),e&&this.tt(b)&&this.kh(b,!1,null,a,!0)):c==b&&0==b&&this.Bf(this.Ub.cA)&&this.Ik(0,!0,!1,null)}else null!=c&&this.Bf(this.Ub.bA)&&this.Jh(0,!0,!0,null,a)},vfa:function(a){var b=this.Ol();if(null!=b&&b!=this.xb().length-1)this.Ik(this.xb().length-1,
!0,!1,null);else{var b=this.nj(),c=this.p().Nf(),c=null!=c?c.length:0;null!=b&&b!=c-1&&0<c&&this.Jh(c-1,!0,!0,null,a)}},wfa:function(a){var b=this.Ol();if(null!=b&&this.xb()[b].sortable==this.Vg){var c=this.p().Qc(b).data("sorted");null==c||c==this.Bh.ms?this.yk(b,!0,a):this.yk(b,!1,a)}},xfa:function(a){a.preventDefault();a.stopPropagation();this.p().Pc().focus();this.iD(!1)},yfa:function(a){var b=this.Ol();null!=b&&0!=b?this.Ik(0,!0,!1,null):(b=this.nj(),null!=b&&0!=b&&this.Jh(0,!0,!0,null,a))},
zfa:function(a){var b=this.nj();null!=b?this.kh(b,!this.tt(b),null,a,!0):(b=this.Ol(),null!=b&&(this.Os(),this.Jk(b,!this.Pw(b),null,a,!0)))},YJ:function(a){var b=this.p().No(f(a));if(null!=b&&null!=this.pg&&this.pg!=b){var c=this.pg,e=this.vt();if(b<c){var g;for(g=0;g<e.length;g++)(e[g]<b||e[g]>c)&&this.kh(e[g],!1,a,null,!0);for(g=c;g>=b;g--)this.kh(g,!0,a,null,!0),this.p().B4(g)}else{for(g=0;g<e.length;g++)(e[g]>b||e[g]<c)&&this.kh(e[g],!1,a,null,!0);for(g=c;g<=b;g++)this.kh(g,!0,a,null,!0),this.p().A4(g)}}},
bK:function(){this.tla(this.gc.M7,this.gc.L7,b.X.Tb.WARNING)},Sfa:function(a){var d=this.p().wm(),c=this.p().Zk();this.p().cl()?(d&&("rtl"===this.ec()?d.css(b.f.F.nA,"-"+a+b.f.ma.fc):d.css(b.f.F.gk,"-"+a+b.f.ma.fc)),c&&("rtl"===this.ec()?c.css(b.f.F.nA,"-"+a+b.f.ma.fc):c.css(b.f.F.gk,"-"+a+b.f.ma.fc))):((d=this.p().lr())&&("rtl"===this.ec()?d.css(b.f.F.nA,"-"+a+b.f.ma.fc):d.css(b.f.F.gk,"-"+a+b.f.ma.fc)),(d=this.p().Ju())&&("rtl"===this.ec()?d.css(b.f.F.nA,"-"+a+b.f.ma.fc):d.css(b.f.F.gk,"-"+a+b.f.ma.fc)))},
yk:function(a,b,c){this.$T(a);var e=this.xb()[a];this.Pga(null==e.sortProperty?e.field:e.sortProperty,b,c);this.H0=e;this.YZ(a,b)},IX:function(a){if(null!=this.RW())return!0;var b=null;if(null!=a)b=this.Qn(a,"cell");else{var c=this.xb().length;for(a=0;a<c&&(b=this.Qn(a,"cell"),null==b);a++);}return null!=b?!0:!1},cga:function(){var a=this.p().VN();if(a.css(b.f.F.wd)!=b.f.ma.rn){var d=a.outerHeight(),c=this.p().nc(),e=parseInt(c.css(b.f.F.OQ),10),g=parseInt(c.css(b.f.F.dA),10);c.css(b.f.F.dA,g-e-d+
b.f.ma.fc);c.removeClass(b.f.la.yA);a.removeClass(b.f.la.yA);a.css(b.f.F.WF,"");a.css(b.f.F.wd,b.f.ma.rn)}},lK:function(){var a=this.p().x3();null!=a&&a.remove()},dga:function(){this.p().Py().css(b.f.F.wd,b.f.ma.rn)},xq:function(a,d){if(this.xb()[a].sortable==this.Vg){var c=this.p().Qc(a),e=c.data("sorted");!d||null!=e&&e!=this.Bh.ms?d||null!=e&&e!=this.Bh.xp||(c=c.find("."+b.f.C.js),c.addClass(b.f.la.vb),c.removeClass(b.f.la.pf),c.removeClass(b.f.la.hd)):(c=c.find("."+b.f.C.zp),c.addClass(b.f.la.vb),
c.removeClass(b.f.la.pf),c.removeClass(b.f.la.hd))}},sC:function(){var a=this,d=this.eb();null!=d&&d instanceof b.T&&!(d instanceof b.na)?(this.p().Oc()[0].scrollTop=0,this.Ai(function(){return a.uC(0,{fetchType:"init"})})):null==d&&this.Ai(function(){return Promise.resolve()})},uC:function(a,d){d=d||{};d[this.Ae]=a;!d[this.WQ]&&this.xi()&&(d[this.WQ]=this.options.scrollPolicyOptions.fetchSize);d.silent=!0;var c="init"==d.fetchType?!0:!1,e=this.eb(),g=this;return new Promise(function(a,f){null!=e?
(g.b0(),e.fetch(d).then(function(d){if(null!=d&&null!=d[g.bj]){var f=0;e instanceof b.na&&(f=e.getStartItemIndex());var k=[],p,r=d[g.bj].length;for(p=0;p<r;p++)k[p]=p+f+d[g.Ae];g.QZ({data:d[g.bj],keys:d[g.ks],indexes:k},d[g.Ae],c,c)}g.ok();a(null)},function(a){g.ok();f(a)})):a(null)})},Pga:function(a,b,c){var e=this.eb();if(!e)return null;this.B0();var g={};g[this.ln]=a;g.direction=b?this.Bh.xp:this.Bh.ms;this._trigger("sort",c,{header:g[this.ln],direction:g.direction});e.sort(g)},Tga:function(){if(null!=
this.Jn){var a=this.VV();if(this.Jn.length!=a.length)return!0;var b,c,e=a.length;for(b=0;b<e;b++)for(c in a[b])if(a[b].hasOwnProperty(c)&&a[b][c]!=this.Jn[b][c])return!0;return!1}return!0},Bf:function(a){var b=this.Pl(),c,e=b.length;for(c=0;c<e;c++)if(b[c]==a)return!0;return!1},xi:function(){return this.options.scrollPolicy==this.K8.u8?!0:!1},BK:function(a){return this.uY(a,/^INPUT|TEXTAREA/)},cha:function(a){return this.uY(a,/SELECT|OPTION|BUTTON|^A\b/)},dha:function(a){return 0<a.closest("[draggable\x3d'true']").length},
uY:function(a,b){for(var c,e=this.p().Pc();null!=a&&a[0]!=e[0]&&"TD"!=(c=a.prop("nodeName"))&&"TH"!=c;)if(3==a[0].nodeType)a=a[0].parentNode;else{var g=a.attr("tabIndex");if(c.match(b)&&-1!=g)return!0;a=a.parentNode}return!1},GY:function(){var a,b,c=this.xb().length;for(a=0;a<c;a++)if(b=this.Qn(a,"footer"),null!=b)return!1;return!0},CC:function(){var a=this.xb(),b,c=a.length;for(b=0;b<c;b++)if(null!=a[b].headerText||null!=a[b].headerStyle||null!=a[b].sortable&&a[b].sortable!=this.ZR||null!=a[b].sortProperty||
null!=a[b].headerRenderer)return!1;return!0},hha:function(){return!0==this.Zja},Dra:function(){return this.X0},iha:function(a,d){var c=this.BT,e=!1;"contextMenu"==a&&d=="#"+this.p().$k()+"_contextmenu"?e=!1:"selection"==a||"currentRow"==a||b.b.mh(d,c[a])||(e=!0);this.BT=f.extend(!0,{},this.options);return e},jha:function(){var a=this.xb(),b,c=a.length;for(b=0;b<c;b++)if(null!=a[b].sortable&&a[b].sortable!=this.ZR)return!0;return!1},CK:function(){if(void 0==this.It){var a=navigator.userAgent.toLowerCase();
-1!=a.indexOf("mobile")||-1!=a.indexOf("android")?this.It=!0:this.It=!1}return this.It},QZ:function(a,d,c,e){if(this.Tga()||!this.hha()&&!this.CC())if(this.yaa(),this.$Z(),null!=this.H0){var g,f,k=!1,l=this.xb();if(null!=l){var m=l.length;for(g=0;g<m;g++)if(f=l[g],b.b.mh(f,this.H0)){k=!0;break}k||this.eb().sort(null)}}this.Rx();this.ZZ(a,d,c,e)},YZ:function(a,d){this.$T(a);var c=this.p().Qc(a),e=c.data("sorted");d&&e!=this.Bh.xp?(c.data("sorted",this.Bh.xp),e=c.find("."+b.f.C.zp),e.addClass(b.f.la.pf),
e.removeClass(b.f.la.vb),e=c.find("."+b.f.C.Mz),e.removeClass(b.f.la.vb),e=c.find("."+b.f.C.Qz),e.addClass(b.f.la.vb),this.xq(a,!d)):d||e==this.Bh.ms||(c.data("sorted",this.Bh.ms),e=c.find("."+b.f.C.js),e.addClass(b.f.la.pf),e.removeClass(b.f.la.vb),e=c.find("."+b.f.C.Qz),e.removeClass(b.f.la.vb),e=c.find("."+b.f.C.Mz),e.addClass(b.f.la.vb))},ZZ:function(a,d,c,e){var g=this.p().nd();if(null!=g){a=this.sea(a,d);var h;if(0==d)b.Components.Kg(g[0]),g.empty();else if(h=g.children(),null!=h&&0<h.length)for(h=
h.length-1;h>=d;h--)this.p().Y4(h);this.p().br();this.lK();h=g.children();if(0!=a.length||null!=h&&0!=h.length){var k=f(document.createDocumentFragment()),l,m,n,p=a.length;for(h=0;h<p;h++)l=a[h].row,m=a[h].Th,null!=l&&(n=this.p().k2(m,l[this.ln]),this.p().lP(n,!0),this.p().R3(m,n,l,k),this.VC(m,l,n,k,d,!0));g.append(k);this.IX()&&(this.p().PE(null,null,c,e),b.Components.Sf(g[0]))}else this.y0()}},VC:function(a,d,c,e,g,h){var k=this.RW();this.xb();var l=this.p().nd();(isNaN(a)||0>a)&&b.r.error("Error: Invalid rowIdx value: "+
a);var m=this.p().nr(d[this.ln]);if(null==c)if(c=this.p().qe(a))c.empty(),h=!0,this.p().nN(a,d[this.ln],m,c,h);else return;this.lK();c.data("rowData",d);h={rowContext:b.dg.oE(this,d,c[0]),row:f.extend({},d[this.bj])};if(k){k=k(h);null!=k?c.append(k):(null==e?c=f(l.children()[a]):(g=null==g?0:g,c=f(e.children()[a-g])),this.p().br(),this.p().fP(d,c),this.p().lP(c,!1));this.p().nN(a,d[this.ln],m,c,!1);g=c.children(b.f.mb.Bl);l=g.length;for(e=1;e<l;e++)k=f(g[e]),this.p().eP(a,d[this.ln],m,e-1,k),this.p().kP(e-
1,k,!1);if(null!=this.qk)for(e=0;e<this.qk.length-1;e++)this.qk[e]>e&&(a=f(g[this.qk[e]+1]),d=f(g[e+1]),a[0].parentNode.insertBefore(a[0],d[0]),g=c.children(b.f.mb.Bl))}else b.dg.mqa(a,d,h)},Rx:function(){var a=this.xb(),d=this.p().Zk();if(!d){if(this.GY())return;d=this.p().l2();this.p().B5(d)}d=this.p().Ju();d.empty();if(a&&0<a.length){this.p().m2(d);for(var c,e,g=a.length,a=0;a<g;a++)c=this.Qn(a,"footer"),e=this.p().rna(),this.p().C5(a,e),this.p().Toa(a,e),c&&(c=c({footerContext:b.dg.oE(this,null,
e[0]),columnIndex:a}),null!=c?(e.empty(),e.append(c)):(e=f(d.children(":not(."+b.f.C.ji+")")[a]),this.p().C5(a,e)))}},$Z:function(){var a=this.xb(),d=this.p().wm();if(!d){if(this.CC())return;d=this.p().n2();this.p().D5(d)}d=this.p().lr();this.JM(d);d.empty();if(a&&0<a.length){var c=this.p().sna();d.append(c);for(var e,g,h,k,l=a.length,c=0;c<l;c++)e=a[c],g=this.Qn(c,"header"),h=this.p().tna(c),g&&(k=b.dg.oE(this,null,h[0]),k={headerContext:k,columnIndex:c,data:e.headerText},e.sortable==b.f.Vg?k.columnHeaderSortableIconRenderer=
function(a,c){b.dg.Y1(this,c)}:k.columnHeaderDefaultRenderer=function(a,c){b.dg.W1(this,c)},e=g(k),null!=e?(h.empty(),h.append(e)):(h=f(d.children(":not(."+b.f.C.$F+")")[c]),this.p().p5(c,h),this.p().E5(c,h,!1))),this.p().una(c,this.HB());this.Zja=!0}},nja:function(){var a=this.p().Py();null!=a&&a.remove();this.p().o2()},rja:function(){var a=f.event.special;a.ojtablebeforecurrentrow={handle:function(a,b){return a.handleObj.handler.apply(this,[a,b])}};a.ojtablesort={handle:function(a,b){return a.handleObj.handler.apply(this,
[a,b])}}},Lq:function(){var a=this.eb();if(null!=a){this.Mk();this.Ua=[];this.Ua.push({eventType:b.T.D.REQUEST,eventHandler:this.Xea.bind(this)});this.Ua.push({eventType:b.T.D.SYNC,eventHandler:this.RJ.bind(this)});this.Ua.push({eventType:b.T.D.SORT,eventHandler:this.UJ.bind(this)});this.Ua.push({eventType:b.T.D.ADD,eventHandler:this.SJ.bind(this)});this.Ua.push({eventType:b.T.D.REMOVE,eventHandler:this.TJ.bind(this)});this.Ua.push({eventType:b.T.D.CHANGE,eventHandler:this.Zea.bind(this)});this.Ua.push({eventType:b.T.D.REFRESH,
eventHandler:this.gC.bind(this)});this.Ua.push({eventType:b.T.D.RESET,eventHandler:this.Xn.bind(this)});this.Ua.push({eventType:b.T.D.ERROR,eventHandler:this.Wea.bind(this)});var d,c,e=this.Ua.length;for(d=0;d<e;d++)(c=a.on(this.Ua[d].eventType,this.Ua[d].eventHandler))&&(this.Ua[d].eventHandler=c)}},sja:function(){null!=this.p().Oc()&&this.p().Oc().scroll(function(a){this.Sfa(this.p().l3(a.target))}.bind(this))},f_:function(){var a=this;this.iV=function(b){null!=b&&b.maxCountLimit&&a.bK()};this.tI=
new b.$f(this.p().Oc(),this.eb(),{fetchSize:this.options.scrollPolicyOptions.fetchSize,maxCount:this.options.scrollPolicyOptions.maxCount,success:this.iV})},yj:function(){var a=this.p().nc();if(!this.Bi){var d=this;this.Bi=function(){var a=d.p().nc().outerHeight(),b=d.p().nc().outerWidth();d.p().PE(b,a)}}this.zC||(b.v.Nh(a[0],this.Bi,50),this.zC=!0)},vL:function(a){var b=this.Pl(),c,e=b.length;for(c=0;c<e;c++)b[c]==a&&b.splice(c,1)},L_:function(a){var b="rtl"===this.ec(),c=this.p().nd(),e=this.p().Qc(a);
if(e){a=this.p().m3();var e=e.get(0).getBoundingClientRect(),g=c.get(0).getBoundingClientRect(),f=!1;b?(e.left<g.left+a&&(b=g.left-e.left+a,this.p().xC()||(b*=-1),c.scrollLeft(c.scrollLeft()+b),f=!0),e.right>g.right&&!f&&(b=e.right-g.right,this.p().xC()||(b*=-1),c.scrollLeft(c.scrollLeft()-b))):(e.left<g.left&&(b=g.left-e.left,c.scrollLeft(c.scrollLeft()-b),f=!0),e.right>g.right-a&&!f&&(b=e.right-g.right+a,c.scrollLeft(c.scrollLeft()+b)))}},vka:function(a){var b=this.p().qe(a);a=this.p().eoa();var b=
b.get(0).getBoundingClientRect(),c=this.p().Oc(),e=c.get(0).getBoundingClientRect(),g=!1;b.bottom>e.bottom-a&&(a=b.bottom-e.bottom+a,c.scrollTop(c.scrollTop()+a),g=!0);b.top<e.top&&!g&&(a=e.top-b.top,c.scrollTop(c.scrollTop()-a))},gm:function(a,d,c){var e=this.bq,g;g=!0;if(null==a){if(null!=e){try{g=this._trigger("beforecurrentrow",d,{currentRow:null,previousCurrentRow:this.bq})}catch(f){a=this.gc.nR;var k=b.ha.Mb(this.gc.mR,{error:f.toString()});b.r.info(a+"\n"+k);return!1}if(!g)return!1;this.bq=
null;this.option("currentRow",null,{_context:{Ic:!0,originalEvent:d,Va:!0}});null==d&&this.Jh(-1,!0,!1,null,d);e=e.rowIndex;e=this.Uw(e);e=this.Tw(e);g=this.p().qe(e);null!=g&&g.removeClass(b.f.C.JG)}return!0}var l=this.eb(),m=a.rowIndex,n=a.rowKey;null==n&&(n=this.Uw(m));null==m&&(m=this.hq(n));k=this.Tw(n);a={rowIndex:m,rowKey:n};if(-1!=k&&(!l||0==l.totalSize()||-1>k||null===k||null===n)){a=this.gc.K7;k=b.ha.Mb(this.gc.J7,{rowIdx:k});if(c)throw Error(a+"\n"+k);b.r.info(a+"\n"+k);return!1}c=this.nj();
if(l=!b.b.mh(this.bq,a)){try{g=this._trigger("beforecurrentrow",d,{currentRow:{rowIndex:m,rowKey:n},previousCurrentRow:this.bq})}catch(p){return a=this.gc.nR,k=b.ha.Mb(this.gc.mR,{error:p.toString()}),b.r.info(a+"\n"+k),!1}if(!g)return!1;this.bq={rowIndex:m,rowKey:n};this.option("currentRow",this.bq,{_context:{Ic:!0,originalEvent:d,Va:!0}});g=this.p().qe(k);null!=g&&g.addClass(b.f.C.JG);null!=e&&(e=e.rowIndex,e=this.Uw(e),e=this.Tw(e),g=this.p().qe(e),null!=g&&g.removeClass(b.f.C.JG))}(l||c!=a.rowIndex)&&
null==d&&this.Jh(k,!0,!1,null,d);return!0},b0:function(){this.B0();this.lK();this.HU=!0},Ik:function(a,b,c,e){var g=null;null!=e&&(g=e.currentTarget);if(b){var f=this.Ol();null!=f&&f!=a&&this.Ik(f,!1,!1,e);this.XT(!0);c&&this.Os();this.L_(a);this.US=a}this.c0(a,{Ij:b},g)},Jk:function(a,d,c,e,g){if(this.HB()==this.ni.Ds||this.HB()==this.ni.Ep)(isNaN(a)||0>a)&&b.r.error("Error: Invalid column selection value: "+a),this.HB()==this.ni.Ds&&d&&this.rw(),this.c0(a,{selected:d},c,e),this.Qka(a,d),a=this.p().w3(a),
f(a.children("."+b.f.C.QQ)[0]).prop("checked",d),g&&(d=this.TW(),this.option("selection",d,{_context:{Ic:!0,Va:!0}}))},c0:function(a,d){var c=this.p().Qc(a);if(c){var e=d.Ij,g=d.selected;null!=g&&c.hasClass(b.f.la.hd)!=g&&(g?c.addClass(b.f.la.hd):c.removeClass(b.f.la.hd));null!=e&&(e?(c.addClass(b.f.la.cj),this.C0(a)):(c.removeClass(b.f.la.cj),this.xq(a,!0),this.xq(a,!1)));this.oma(a)}},Qka:function(a,b){this.eo||(this.eo=[]);var c,e=this.eo.length;for(c=0;c<e;c++)if(this.eo[c]==a){this.eo.splice(c,
1);break}b&&this.eo.push(a)},Ska:function(a,b){this.fo||(this.fo=[]);var c,e=this.fo.length;for(c=0;c<e;c++)if(this.fo[c]==a){this.fo.splice(c,1);break}b&&this.fo.push(a)},Jh:function(a,d,c,e,g){if(-1==a){var f=this.nj();null!=f&&this.Jh(f,!1,c,null,null);return c&&(g=this.gm(null,g),!g)?!1:!0}var k=this.p().qe(a);if(!k)return!1;if(d){f=this.nj();null!=f&&f!=a&&this.Jh(f,!1,c,e,null);if(c&&(c=this.pq(a),g=this.gm({rowKey:c},g),!g))return!1;k.addClass(b.f.la.cj);this.vka(a);this.HD(a,{Ij:!0,hover:!1});
this.WT();this.rw();this.iD(!0)}else k.removeClass(b.f.la.cj);this.HD(a,{Ij:d});return!0},kh:function(a,d,c,e,g){if(this.ut()==this.ni.Ds||this.ut()==this.ni.Ep)if((isNaN(a)||0>a)&&b.r.error("Error: Invalid row selection value: "+a),this.ut()==this.ni.Ds&&d&&this.Os(),c=this.p().qe(a),null!=c){e=!1;if(c.hasClass(b.f.la.hd)!=d){d?c.addClass(b.f.la.hd):c.removeClass(b.f.la.hd);e=!0;var h=this.options.dnd.drag;h&&("rows"===h||h.rows)&&c.prop("draggable",d)}e&&(d?this.HD(a,{hover:!1,Ij:!1,selected:!0}):
this.HD(a,{selected:!1}));this.Ska(a,d);a=this.p().r3(c);f(a.children("."+b.f.C.RQ)[0]).prop("checked",d);g&&(d=this.TW(),this.option("selection",d,{_context:{Ic:!0,Va:!0}}))}},bu:function(a){if(null==a)this.Os(),this.rw();else{var d,c,e,g,f,k,l=a.length;for(d=0;d<l;d++){e=a[d];if(null==e.startKey&&null==e[this.Ae]||null==e.endKey&&null==e[this.Ue])return b.r.error("Error: Invalid range object in selection. Both start and end objects must be specified"),null;g=k=c=f=null;null!=e.startKey&&null!=e.startKey[this.Wd]&&
(f=this.hq(e.startKey[this.Wd]));null!=e.endKey&&null!=e.endKey[this.Wd]&&(c=this.hq(e.endKey[this.Wd]));null!=e.startKey&&null!=e.startKey[this.Vd]&&(k=this.TV(e.startKey[this.Vd]));null!=e.endKey&&null!=e.endKey[this.Vd]&&(g=this.TV(e.endKey[this.Vd]));null==f&&null!=e[this.Ae]&&(f=e[this.Ae][this.Wd]);null==c&&null!=e[this.Ue]&&(c=e[this.Ue][this.Wd]);null==k&&null!=e[this.Ae]&&(k=e[this.Ae][this.Vd]);null==g&&null!=e[this.Ue]&&(g=e[this.Ue][this.Vd]);if(null!=f&&null!=c&&null!=k&&null!=g)return b.r.error("Error: Invalid range object in selection - Can only support row or column selection. Not both"),
null;if(null!=f&&0<=f&&null!=c&&0<=c)for(g=this.Uw(f),c=this.Uw(c),g=this.Tw(g),e=this.Tw(c),c=g;c<=e;c++)try{this.kh(c,!0,null,null,!1)}catch(m){b.r.error("Error: "+m)}else if(null!=k&&null!=g)for(c=k;c<=g;c++)try{this.Jk(c,!0,null,null,!1)}catch(n){b.r.error("Error: "+n)}else return b.r.error("Error: Invalid range object in selection - \n start row: "+f+"\nend row: "+c+"\nstart column: "+k+"\nend column: "+g),null}}},iD:function(a){this.X0=a},tla:function(a,d,c){this.p().Ypa(a,d,c);a=this.p().VN();
if(a.css(b.f.F.wd)==b.f.ma.rn){a.css(b.f.F.wd,b.f.ma.gs);var e=parseInt(a.css(b.f.F.Gp),10),g=parseInt(a.css(b.f.F.Hp),10);d=this.p().nc();c==b.X.Tb.WARNING&&(d.addClass(b.f.la.yA),a.addClass(b.f.la.yA));c=d.width();a.css(b.f.F.xd,c-e-g+b.f.ma.fc);c=a.outerHeight();var e=parseInt(d.css(b.f.F.OQ),10),g=parseInt(d.css(b.f.F.l7),10),f=parseInt(d.css(b.f.F.dA),10),f=f+e+c;d.css(b.f.F.dA,f+b.f.ma.fc);a.css(b.f.F.WF,-1*(f+e)+b.f.ma.fc);a.css(b.f.F.gk,-1*g+b.f.ma.fc)}},y0:function(){null==this.p().x3()&&
this.p().zna(this.xb().length)},B0:function(){this.p().Py().css(b.f.F.wd,b.f.ma.xR);this.p().W4()},C0:function(a){if(this.xb()[a].sortable==this.Vg&&(a=this.p().Qc(a))&&null==a.data("sorted")){var d=a.find("."+b.f.C.zp);d.addClass(b.f.la.pf);d.removeClass(b.f.la.vb);a.find("."+b.f.C.Mz).removeClass(b.f.la.vb);a.find("."+b.f.C.Qz).addClass(b.f.la.vb)}},JM:function(a){var b=this;a.find("*").each(function(){b.Np(this)})},Mk:function(){var a=this.eb();if(null!=this.Ua&&null!=a){var b,c=this.Ua.length;
for(b=0;b<c;b++)a.off(this.Ua[b].eventType,this.Ua[b].eventHandler)}},Nk:function(){var a=this.p().nc();b.v.Oi(a[0],this.Bi);this.zC=!1},oma:function(a){var d=this.dJ(a).selected,c=this.vt(),e=this.p().Nf();if(null!=e&&0<e.length)for(var g,h,k,l,m=e.length,e=0;e<m;e++)if(h=this.p().kr(e,a),d)f(h).addClass(b.f.la.hd);else{k=!1;l=c.length;for(g=0;g<l;g++)if(e==c[g]){k=!0;break}k||f(h).removeClass(b.f.la.hd)}},HD:function(a,d){var c=this.p().TN(a),e=d.Ij,g=d.selected,h=d.hover;if(c){if(null!=h){var k,
l=c.length;for(k=0;k<l;k++)h?f(c[k]).addClass(b.f.la.dk):f(c[k]).removeClass(b.f.la.dk)}if(null!=e)for(l=c.length,k=0;k<l;k++)e?f(c[k]).addClass(b.f.la.cj):f(c[k]).removeClass(b.f.la.cj);if(null!=g)for(l=c.length,k=0;k<l;k++)g?f(c[k]).addClass(b.f.la.hd):f(c[k]).removeClass(b.f.la.hd)}},Hka:function(a){this.zV=a?a.bind(this):void 0},Ai:function(a){var d=this;this.Vt||(this.ey=0,this.Vt=Promise.resolve());this.ey++;return this.Vt=this.Vt.then(function(){if(!d.uw)return a.bind(d)()}).then(function(a){d.ey--;
0!=d.ey||d.uw||(d.Vt=void 0,d.zV&&d.zV(),d._trigger("ready"));return a},function(a){d.ey--;0==d.ey&&(d.Vt=void 0,b.r.error(a));return Promise.reject(a)})}})})();b.Components.Om({ojTable:{display:b.Components.nh(function(){return b.ze.Yk("table").display})}});b.f=function(a){this.Q=a;this.options=a.options;this.element=a.element;this.Init()};o_("TableDomUtils",b.f,b);b.b.ga(b.f,b.b,"oj.TableDomUtils");b.f.prototype.Init=function(){b.f.q.Init.call(this)};b.b.g("TableDomUtils.prototype.Init",{Init:b.f.prototype.Init});
b.f.prototype.ana=function(){this.br();this.Ei=null};b.f.prototype.br=function(){this.xH=null};b.f.prototype.h2=function(a){var d=null,c=this;if(null!=this.options.contextMenu||null!=this.Pc().attr("contextmenu")){var e=this.P2(),d=f(e);if(null!=d&&0<d.length){var g=d.find("[data-oj-command]");if(null!=g&&0<g.length){var h;g.each(function(){0===f(this).children(b.f.mb.RF).length&&(h=f(this).attr("data-oj-command").split("-"),f(this).replaceWith(c.i2(h[h.length-1])))});this.aZ=d;this.Q.mU=e;d.ojMenu("refresh");
d.on("ojselect",a)}}}else this.Q.jha()&&(d=f(document.createElement(b.f.mb.O9)),d.css(b.f.F.wd,b.f.ma.rn),d.attr(b.f.lb.ek,this.$k()+"_contextmenu"),this.nc().append(d),e=this.i2("sort"),d.append(e),d.ojMenu(),this.aZ=d,this.Q.mU="#"+d.attr(b.f.lb.ek),d.on("ojselect",a),this.Q._setOption("contextMenu","#"+d.attr(b.f.lb.ek)))};b.f.prototype.i2=function(a){return"sort"===a?f(this.lN(a)).append(f("\x3cul\x3e\x3c/ul\x3e").append(f(this.lN("sortAsc"))).append(f(this.lN("sortDsc")))):null};b.f.prototype.lN=
function(a){var b=f(document.createElement("li"));b.attr("data-oj-command","oj-table-"+a);b.append(this.jna(a));return b};b.f.prototype.jna=function(a){var d=f(document.createElement(b.f.mb.RF));d.attr(b.f.lb.Y7,"#");var c=null;"sort"==a?c=this.Q.A("labelSort"):"sortAsc"==a?c=this.Q.A("labelSortAsc"):"sortDsc"==a&&(c=this.Q.A("labelSortDsc"));d.text(c);return d};b.f.prototype.kna=function(a,b){this.Pc();this.pna();this.cl()&&this.qna();a||this.n2();b||this.l2();this.mna();this.o2();this.wna()};b.f.prototype.mna=
function(){var a=this.Pc(),d=f(document.createElement(b.f.mb.DS));a.append(d);this.wH=d};b.f.prototype.nna=function(){return f(document.createElement(b.f.mb.Bl))};b.f.prototype.nN=function(a,d,c,e,g){var h=null;g||(h=this.r3(e));null==h&&(h=null!=d?d.toString():a.toString(),a=null==c?this.nr(h):c,h=f(document.createElement(b.f.mb.Bl)),h.addClass(b.f.C.IG),h.css("padding","0"),h.css("border","0"),null!=this.wm()&&h.attr(b.f.lb.hG,this.$k()+":"+b.f.UQ),c=f(document.createElement(b.f.mb.Yz)),c.attr(b.f.lb.ek,
this.$k()+":acc_sel_row_"+a),c.attr(b.f.lb.vA,"checkbox"),c.attr(b.f.lb.Uv,"-1"),a=this.Q.A(this.Q.xa.LR),c.attr(b.f.lb.sA,a),c.addClass(b.f.C.RQ),c.addClass(b.f.C.ji),h.append(c),e.prepend(h))};b.f.prototype.k2=function(a,d){var c=f(document.createElement(b.f.mb.Mp));this.nN(a,d,null,c,!0);return c};b.f.prototype.ona=function(a){var d=f(document.createElement(b.f.mb.bk));d.addClass(b.f.C.NG);d.addClass(b.f.C.OG);d.data("rowIdx",a);var c=f(document.createElement(b.f.mb.bk));c.addClass(b.f.C.wS);c.attr("role",
"button");c.attr("aria-label",this.Q.A("labelAccSelectionAffordanceTop"));c.data("rowIdx",a);d.append(c);c=f(document.createElement(b.f.mb.bk));c.addClass(b.f.C.MG);c.addClass(b.f.C.OG);c.data("rowIdx",a);var e=f(document.createElement(b.f.mb.bk));e.addClass(b.f.C.vS);e.attr("role","button");e.attr("aria-label",this.Q.A("labelAccSelectionAffordanceBottom"));e.data("rowIdx",a);c.append(e);e=this.nc();e.append(d);e.append(c);this.B4(a);this.A4(a)};b.f.prototype.pna=function(){var a=f(document.createElement(b.f.mb.bk));
this.element.parent()[0].replaceChild(a[0],this.element[0]);a.prepend(this.element);this.RA=a};b.f.prototype.l2=function(){var a=this.Pc(),d=f(document.createElement(b.f.mb.ES)),c=f(document.createElement(b.f.mb.Mp));this.m2(c);d.append(c);c=this.wm();null!=c?c.after(d):(c=this.nd(),null!=c?c.before(d):a.append(d));return d};b.f.prototype.m2=function(a){var d=a.children("."+b.f.C.ji);null!=d&&0<d.length?f(d[0]):(d=f(document.createElement(b.f.mb.Bl)),d.addClass(b.f.C.ji),d.attr(b.f.lb.Uv,"-1"),a.prepend(d))};
b.f.prototype.rna=function(){return f(document.createElement(b.f.mb.Bl))};b.f.prototype.n2=function(){var a=this.Pc(),d=f(document.createElement(b.f.mb.GS)),c=f(document.createElement(b.f.mb.Mp));this.AH=c;d.append(c);c=this.Zk();null!=c?c.before(d):(c=this.nd(),null!=c?c.before(d):a.append(d));return this.zH=d};b.f.prototype.sna=function(){var a=f(document.createElement(b.f.mb.FS));a.addClass(b.f.C.$F);a.attr(b.f.lb.ek,this.$k()+":"+b.f.UQ);var d=this.Q.A(this.Q.xa.LR);a.attr(b.f.lb.sA,d);a.css("padding",
"0");a.css("border","0");var c=f(document.createElement(b.f.mb.A9));c.text(d);c.addClass(b.f.C.ji);a.append(c);return a};b.f.prototype.tna=function(a){var d=this.Q.xb()[a],c=f(document.createElement(b.f.mb.FS));this.E5(a,c,!0);c.attr("abbr",d.headerText);c.attr(b.f.lb.sA,d.headerText);this.Uoa(a,c);a={columnIndex:a,headerContext:{component:this.Q,parentElement:c}};d.sortable==b.f.Vg?(c.attr("data-oj-sortable",b.f.Vg),b.dg.Y1(a,null)):b.dg.W1(a,null);return c};b.f.prototype.vna=function(a){a=this.Qc(a).clone();
a.removeClass(b.f.la.ns);a.removeClass(b.f.la.cj);a.removeClass(b.f.la.dk);a.addClass(b.f.C.TQ);a.css(b.f.F.Al,b.f.ma.SF);a.css(b.f.F.Gs,"0");a.css(b.f.F.gk,"0");a.css(b.f.F.Q9,"-999");this.nc().append(a);return a};b.f.prototype.una=function(a,d){if(d==b.f.ni.Ds||d==b.f.ni.Ep){var c=this.Qc(a),e=this.w3(a);if(null==e){e=f(document.createElement(b.f.mb.bk));e.addClass(b.f.C.SQ);e.addClass(b.f.C.ji);var g=f(document.createElement(b.f.mb.Yz));g.attr(b.f.lb.ek,this.$k()+":acc_sel_col"+a);g.attr(b.f.lb.vA,
"checkbox");g.attr(b.f.lb.Uv,"-1");var h=this.Q.A(this.Q.xa.r8);g.attr(b.f.lb.sA,h);g.addClass(b.f.C.QQ);e.append(g);c.prepend(e)}}};b.f.prototype.qna=function(){var a=this.Pc(),d=this.nc(),c=f(document.createElement(b.f.mb.bk));c.addClass(b.f.C.CS);d[0].replaceChild(c[0],a[0]);c.append(a);this.yH=c};b.f.prototype.zna=function(a){var d=this.nd(),c=f(document.createElement(b.f.mb.Mp));c.addClass(b.f.C.BS);this.xna(c);this.yna(c,a);d.append(c)};b.f.prototype.xna=function(a){var d=f(document.createElement(b.f.mb.Bl));
d.addClass(b.f.C.ji);d.attr(b.f.lb.Uv,"-1");a.prepend(d)};b.f.prototype.yna=function(a,d){var c=f(document.createElement(b.f.mb.Bl));c.attr(b.f.lb.hs,d||1);c.addClass(b.f.C.AS);var e=null,e=null!=this.options.emptyText?this.options.emptyText:this.Q.A(this.Q.xa.G8);c.text(e);a.append(c)};b.f.prototype.wna=function(){var a=this.nc(),d=f(document.createElement(b.f.mb.bk));d.addClass(b.f.C.zS);d.css(b.f.F.wd,b.f.ma.rn);a.append(d);this.BH=d};b.f.prototype.o2=function(){var a=this.nc(),d=f(document.createElement(b.f.mb.bk));
d.addClass(b.f.C.RG);d.css(b.f.F.wd,b.f.ma.rn);var c=f(document.createElement(b.f.mb.bk));c.addClass(b.f.C.I9);c.text(this.Q.A(this.Q.xa.C8));d.append(c);a.append(d);this.CH=d};b.f.prototype.t2=function(a,d){this.RE();var c=this.lr(),e=this.Qc(a);if(null!=e)d?e.addClass(b.f.C.Pz):e.addClass(b.f.C.Oz);else if(e=this.Q.xb(),null==e||0==e.length)d?c.addClass(b.f.C.Pz):c.addClass(b.f.C.Oz)};b.f.prototype.Hna=function(a,d){this.XO();var c=f(document.createElement(b.f.mb.Mp));c.addClass(b.f.C.KG);d&&c.height(d.height());
var e=f(document.createElement(b.f.mb.Bl)),g=this.Q.xb();e.attr(b.f.lb.hs,g.length+1);c.append(e);e=this.qe(a);null!=e?e.before(c):this.nd().append(c)};b.f.prototype.P2=function(){return null==this.options.contextMenu?"#"+this.Pc().attr("contextmenu"):this.options.contextMenu};b.f.prototype.me=function(a){var d=this.Oo(a,b.f.C.Es);if(null!=d)return d.parent().children("."+b.f.C.Es).index(d);d=this.Oo(a,b.f.C.kn);if(null!=d)return d.parent().children("."+b.f.C.kn).index(d);a=this.Oo(a,b.f.C.Lp);return null!=
a?a.parent().children("."+b.f.C.Lp).index(a):null};b.f.prototype.No=function(a){a=this.Oo(a,b.f.C.Kp);return null!=a?a.index():null};b.f.prototype.Oo=function(a,b){var c;if(null==a)return null;a=f(a);if(a.hasClass(b))return a;c=a.parents("."+b);return 0!=c.length?c.eq(0):null};b.f.prototype.eoa=function(){var a=this.Oc();return 0<a.get(0).clientHeight?a.get(0).offsetHeight-a.get(0).clientHeight:0};b.f.prototype.m3=function(){var a=this.Oc();return 0<a.get(0).clientWidth?a.get(0).offsetWidth-a.get(0).clientWidth:
0};b.f.prototype.Oc=function(){return this.cl()?this.u3():this.nd()};b.f.prototype.l3=function(a){a=f(a);var b=a[0].scrollLeft;"rtl"===this.Q.ec()&&(b=Math.abs(b),this.IY()&&(b=a[0].scrollWidth-a[0].clientWidth-b));return b};b.f.prototype.Pc=function(){return f(this.element)};b.f.prototype.nd=function(){if(!this.wH){var a=this.Pc(),d=null;a&&(d=a.children("."+b.f.C.HG))&&0<d.length&&(this.wH=f(d.get(0)))}return this.wH};b.f.prototype.kr=function(a,b,c){return(a=this.TN(a,c))?a.length>b?f(a[b]):null:
null};b.f.prototype.r3=function(a){return null!=a&&(a=a.children("."+b.f.C.IG),null!=a&&0<a.length)?f(a[0]):null};b.f.prototype.hoa=function(a){return(a=this.TN(a,void 0))?this.VI(a):null};b.f.prototype.TN=function(a,d){d||(d=this.qe(a));if(!d)return null;var c=d.children("."+b.f.C.Es);return null!=c&&0<c.length?c:null};b.f.prototype.qe=function(a){var b=this.Nf();return b&&null!=a?b.length>a?f(b[a]):null:null};b.f.prototype.Nf=function(){if(!this.xH){var a=this.nd().children("."+b.f.C.Kp);null!=
a&&0<a.length&&(this.xH=a)}return this.xH};b.f.prototype.t3=function(){var a=this.nc().children("."+b.f.C.NG);return null!=a&&0<a.length?a=f(a[0]):null};b.f.prototype.s3=function(){var a=this.nc().children("."+b.f.C.MG);return null!=a&&0<a.length?a=f(a[0]):null};b.f.prototype.nc=function(){this.RA||(this.cl()?this.RA=f(this.element.get(0).parentNode.parentNode):this.RA=f(this.element.get(0).parentNode));return this.RA};b.f.prototype.Zk=function(){var a=this.Pc(),d=null;return a&&(d=a.children("."+
b.f.C.PG))&&0<d.length?f(d.get(0)):null};b.f.prototype.UN=function(a){var b=this.v3();return null!=b&&b.length>a?f(b[a]):null};b.f.prototype.v3=function(){var a=this.Ju(),a=f(a).children("."+b.f.C.Lp);return null!=a&&0<a.length?a:null};b.f.prototype.ioa=function(){var a=this.v3();return a?this.VI(a):null};b.f.prototype.Ju=function(){if(!this.AT){var a=this.Zk();if(!a)return null;this.AT=f(a.children("."+b.f.C.xS).get(0))}return this.AT};b.f.prototype.wm=function(){if(!this.zH){var a=this.Pc(),d=null;
a&&(d=a.children("."+b.f.C.QG))&&0<d.length&&(this.zH=f(d.get(0)))}return this.zH};b.f.prototype.Qc=function(a){var b=this.Oy();return b?b.length>a?f(b[a]):null:null};b.f.prototype.w3=function(a){a=this.Qc(a);return null!=a&&(a=a.children("."+b.f.C.SQ),null!=a&&0<a.length)?f(a[0]):null};b.f.prototype.Oy=function(){var a=this.lr();return null!=a&&(a=a.children("."+b.f.C.kn),null!=a&&0<a.length)?a:null};b.f.prototype.joa=function(){var a=this.Oy();return a?this.VI(a):null};b.f.prototype.lr=function(){if(!this.AH){var a=
this.wm();if(!a)return null;this.AH=f(a.children("."+b.f.C.yS).get(0))}return this.AH};b.f.prototype.u3=function(){if(!this.yH){var a=this.nc();a&&(a=a.children("."+b.f.C.CS))&&0<a.length&&(this.yH=f(a.get(0)))}return this.yH};b.f.prototype.$k=function(){this.W0||(this.W0=this.Pc().attr(b.f.lb.ek));return this.W0};b.f.prototype.VN=function(){if(!this.BH){var a=this.nc();a&&(a=a.children("."+b.f.C.zS))&&0<a.length&&(this.BH=f(a.get(0)))}return this.BH};b.f.prototype.x3=function(){var a=this.nd();return a&&
(a=a.children("."+b.f.C.BS))&&0<a.length?f(a.get(0)):null};b.f.prototype.Py=function(){if(!this.CH){var a=this.nc();a&&(a=a.children("."+b.f.C.RG))&&0<a.length&&(this.CH=f(a.get(0)))}return this.CH};b.f.prototype.koa=function(){if(!this.Y0){var a=this.$k();null==a&&(a=(1E32*Math.random()).toString(36));this.Y0=a}return this.Y0};b.f.prototype.nr=function(a){"string"!=f.type(a)&&(a=a.toString());var b=0;if(0==a.length)return b;var c,e,g=a.length;for(e=0;e<g;e++)c=a.charCodeAt(e),b=(b<<5)-b+c,b&=b;return b};
b.f.prototype.Soa=function(a,b,c,e,g,h){this.eP(a,b,c,e,g);f(h).append(g)};b.f.prototype.R3=function(a,d,c,e){this.fP(c,d);null==e?(c=this.nd(),e=c.children("."+b.f.C.Kp),0==a?c.prepend(d):e.length>=a?f(e.get(a-1)).after(d):c.append(d)):e.append(d);this.br()};b.f.prototype.Toa=function(a,d){var c=this.Ju(),e=f(c).children("."+b.f.C.Lp);0==a?(e=c.children("."+b.f.C.ji),null!=e&&0<e.length?f(e[0]).after(d):c.prepend(d)):c.length>=a?f(e.get(a-1)).after(d):c.append(d)};b.f.prototype.Uoa=function(a,d){var c=
this.lr(),e=this.Oy();this.p5(a,d);var g=this.Qc(a);g?g.replaceWith(d):0==a?(e=c.children("."+b.f.C.$F),null!=e&&0<e.length?f(e[0]).after(d):c.prepend(d)):e.length>=a?f(e.get(a-1)).after(d):c.append(d)};b.f.prototype.cl=function(){return this.xC()&&10>this.xC()?!0:!1};b.f.prototype.a4=function(){var a=this.nc(),d=this.Pc(),c=this.Py(),e=c.css(b.f.F.wd).toString();c.css(b.f.F.wd,b.f.ma.rn);var g=[];g[0]=0<a[0].clientHeight?d[0].clientHeight>a[0].clientHeight?1:1<a[0].clientHeight-d[0].clientHeight?
-1:0:0;g[1]=0<a[0].clientWidth?d[0].clientWidth>a[0].clientWidth?1:1<a[0].clientWidth-d[0].clientWidth?-1:0:0;c.css(b.f.F.wd,e);return g};b.f.prototype.B4=function(a){var d=this.t3();if(null!=d){d.data("rowIdx",a);f(d.children()[0]).data("rowIdx",a);var c=this.nd();a=this.qe(a)[0].getBoundingClientRect();var e=this.nc()[0].getBoundingClientRect();d.css(b.f.F.Gs,a.top-e.top-d.height()/2);d.css(b.f.F.gk,c.width()/2+"px")}};b.f.prototype.A4=function(a){var d=this.s3();if(null!=d){d.data("rowIdx",a);
f(d.children()[0]).data("rowIdx",a);var c=this.nd();a=this.qe(a)[0].getBoundingClientRect();var e=this.nc()[0].getBoundingClientRect();d.css(b.f.F.Gs,a.top-e.top+a.height-d.height()/2);d.css(b.f.F.gk,c.width()/2+"px")}};b.f.prototype.npa=function(a,d,c){var e=this.Q.xb(),g=this.Qc(a),f=this.UN(a),k=null,l=k=k=null,m=null,n=!1;d==e.length&&(d-=1,n=!0);null!=g&&(m=g.attr(b.f.lb.hs),k=this.Qc(d),null==k||null!=m&&1!=m||(n?k.after(g):k.before(g)));null!=f&&(m=f.attr(b.f.lb.hs),k=this.UN(d),null==k||null!=
m&&1!=m||(n?k.after(f):k.before(f)));g=this.Nf();if(null!=g)for(e=0;e<g.length;e++)k=this.kr(e,a,null),null!=k&&(l=this.kr(e,d,null),m=k.attr(b.f.lb.hs),null==l||null!=m&&1!=m||(n?l.after(k):l.before(k)));m=this.options.columns;d=a<d&&!n?d-1:d;n=m.splice(a,1);m.splice(d,0,n[0]);m=m.slice(0);this.Q.option("columns",m,{_context:{Ic:!0,originalEvent:c,Va:!0}});c=this.Q.Jn.splice(a,1);this.Q.Jn.splice(d,0,c[0]);if(!this.qk)for(this.qk=[],e=0;e<m.length;e++)this.qk[e]=e;a=this.qk.splice(a,1);this.qk.splice(d,
0,a[0]);this.Q.Ai(function(){});return this.qk};b.f.prototype.Cpa=function(){var a=this,d=this.aZ;d&&0<d.length&&d.find("[data-oj-command]").each(function(){var c=f(this).children(b.f.mb.RF);if(0<c.length){var d=f(this).attr("data-oj-command").split("-"),d=d[d.length-1],g;"sort"==d?g=a.Q.A("labelSort"):"sortAsc"==d?g=a.Q.A("labelSortAsc"):"sortDsc"==d&&(g=a.Q.A("labelSortDsc"));c.contents().filter(function(){return 3===this.nodeType})[0].nodeValue=g}})};b.f.prototype.PE=function(a,b,c,e){this.Q.Nk();
this.mja(a,b,c,e);this.Q.yj();this.Q.gm(this.options.currentRow,null)};b.f.prototype.RE=function(){var a=this.Pc().find("."+b.f.C.Pz+",."+b.f.C.Oz),d=0;if(a&&0<a.length)for(var c=a.length,d=0;d<c;d++)f(a[d]).removeClass(b.f.C.Pz),f(a[d]).removeClass(b.f.C.Oz)};b.f.prototype.XO=function(){var a=this.nd(),d=a.children("."+b.f.C.KG),a=a.children("."+b.f.C.G9),c=0;if(d&&0<d.length)for(var e=d.length,c=0;c<e;c++)f(d[c]).remove();if(a&&0<a.length)for(d=a.length,c=0;c<d;c++)f(a[c]).remove()};b.f.prototype.Y4=
function(a){a=this.qe(a);null!=a&&(b.Components.Kg(a[0]),a.remove(),this.br())};b.f.prototype.Jpa=function(){var a=this.nc().children("."+b.f.C.OG);if(null!=a&&0<a.length){var d;for(d=0;d<a.length;d++)a[d].remove()}};b.f.prototype.Kpa=function(){var a=this.nc().find("."+b.f.C.TQ);if(a&&0<a.length){var d,c=a.length;for(d=0;d<c;d++)f(a[d]).remove()}};b.f.prototype.n5=function(a,b){a=f(a);"rtl"===this.Q.ec()&&(b=Math.abs(b),this.IY()?b=a[0].scrollWidth-a[0].clientWidth-b:this.Yga()&&(b*=-1));a[0].scrollLeft!=
b&&(a[0].scrollLeft=b)};b.f.prototype.eP=function(a,d,c,e,g){var f=this.options.accessibility;e=this.Q.xb()[e];var k=null,l=null==this.wm()?!0:!1,k=null!=f&&null!=f.rowHeader?f.rowHeader:this.Q.xb()[0].id;a=null!=d?d.toString():a.toString();c=null==c?this.nr(a):c;c=this.$k()+":"+k+"_"+c;a=this.$k()+":"+e.id;k==e.id?(g.attr(b.f.lb.ek,c),l&&(a="")):a=l?c:a+" "+c;g.attr(b.f.lb.hG)||g.attr(b.f.lb.hG,a)};b.f.prototype.fP=function(a,b){b.data("rowKey",a.key)};b.f.prototype.p5=function(a,d){var c=this.Q.xb()[a];
d.attr(b.f.lb.ek)||d.attr(b.f.lb.ek,this.$k()+":"+c.id)};b.f.prototype.o5=function(a,b,c){var e=this.Nf();if(null!=e&&0<e.length)if(null===a){if(a=null,a=b?this.nd().find("[td]"):this.nd().find("."+c),null!=a&&0<a.length)for(var g=a.length,e=0;e<g;e++)b?f(a[e]).addClass(c):f(a[e]).removeClass(c)}else for(var h=e.length,e=0;e<h;e++)g=this.kr(e,a,null),b?f(g).addClass(c):f(g).removeClass(c)};b.f.prototype.Ypa=function(a,d,c){var e=this.VN();e.empty();e.append(b.Na.N1(document,a,d,c,null))};b.f.prototype.fqa=
function(){var a=this.Pc(),d=this.nc(),c=a.children(b.f.mb.GS),c=0<c.length?f(c[0]):null,e=a.children(b.f.mb.ES),e=0<e.length?f(e[0]):null,g=a.children(b.f.mb.DS),g=0<g.length?f(g[0]):null;a.attr(b.f.lb.Uv,"0");this.Q._focusable(a);this.Q._focusable(d);this.D5(c);this.B5(e);this.gqa(g)};b.f.prototype.gqa=function(a){a.addClass(b.f.C.HG);a.attr(b.Components.tn,this.Q.widgetName)};b.f.prototype.kP=function(a,d,c){a=this.Q.xb()[a];if(c||!d.hasClass(b.f.C.Es))d.addClass(b.f.C.Es),null==a.style||!c&&d.attr(b.f.lb.ik)==
a.style||d.attr(b.f.lb.ik,a.style),null==a.className||!c&&d.hasClass(a.className)||d.addClass(a.className);this.DK()&&(!c&&d.hasClass(b.f.C.Fs)||d.addClass(b.f.C.Fs))};b.f.prototype.lP=function(a,d){!d&&a.hasClass(b.f.C.Kp)||a.addClass(b.f.C.Kp);this.rY()&&(!d&&a.hasClass(b.f.C.Vv)||a.addClass(b.f.C.Vv))};b.f.prototype.hqa=function(a){a.addClass(b.f.C.tS);a.addClass(b.f.C.F9);a.addClass(b.f.la.VG);this.options.display==b.f.XR.pR?a.addClass(b.f.C.uS):a.removeClass(b.f.C.uS)};b.f.prototype.B5=function(a){a&&
(a.addClass(b.f.C.PG),f(a.children(b.f.mb.Mp)[0]).addClass(b.f.C.xS))};b.f.prototype.C5=function(a,d){this.Q.xb();var c=this.Q.xb()[a];d.attr(b.f.lb.ik,c.footerStyle);d.hasClass(b.f.C.Lp)||d.addClass(b.f.C.Lp);this.DK()&&!d.hasClass(b.f.C.Fs)&&d.addClass(b.f.C.Fs);c.footerClassName&&d.addClass(c.footerClassName)};b.f.prototype.D5=function(a){a&&(a.addClass(b.f.C.QG),a.css(b.f.F.wd,"table-header-group"),a=f(a.children(b.f.mb.Mp)[0]),a.addClass(b.f.C.yS),a.css(b.f.F.Al,b.f.ma.Bs))};b.f.prototype.E5=
function(a,d,c){a=this.Q.xb()[a];if(c||!d.hasClass(b.f.C.kn))d.addClass(b.f.C.kn),this.DK()&&(!c&&d.hasClass(b.f.C.Fs)||d.addClass(b.f.C.Fs)),null==a.headerStyle||!c&&d.attr(b.f.lb.ik)==a.headerStyle||d.attr(b.f.lb.ik,a.headerStyle),null==a.headerClassName||!c&&d.hasClass(a.headerClassName)||d.addClass(a.headerClassName)};b.f.prototype.VI=function(a){var d,c,e=0,g=[],h=a.length;for(d=0;d<h;d++){var k=f(a[d]).attr(b.f.lb.hs);if(null!=k){k=parseInt(k,10);for(c=0;c<k;c++)g[e+c]=a[d];e+=k}else g[e++]=
a[d]}return f(g)};b.f.prototype.rY=function(){return this.options.horizontalGridVisible==b.f.Vg||this.options.horizontalGridVisible==b.f.fA?!0:!1};b.f.prototype.DK=function(){return this.options.verticalGridVisible==b.f.Vg||this.options.verticalGridVisible==b.f.fA&&this.options.display==b.f.XR.pR?!0:!1};b.f.prototype.Yga=function(){return-1<navigator.userAgent.toLowerCase().indexOf("firefox")?!0:!1};b.f.prototype.xC=function(){if("undefined"==typeof this.OA){var a=navigator.userAgent;"Microsoft Internet Explorer"==
navigator.appName?(a=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(a),null!=a&&(this.OA=parseFloat(a[1]))):0<=a.indexOf("Trident")?this.OA=11:this.OA=null}return this.OA};b.f.prototype.IY=function(){if("undefined"==typeof this.xT){var a=navigator.userAgent.toLowerCase();this.xT=/webkit/.test(a)&&!/edge/.test(a)}return this.xT};b.f.prototype.mja=function(a,d,c,e){var g=this.Pc(),h=this.wm(),k=this.Zk(),l=this.Ju(),m=this.lr(),n=this.nc(),p=this.nd(),r=null,s=null;if(null!=this.Oc()){var q=this.Oc()[0].scrollHeight-
this.Oc()[0].clientHeight,t=this.Oc()[0].scrollWidth-this.Oc()[0].clientWidth;0<q&&(r=this.Oc()[0].scrollTop);0<t&&(s=this.l3(this.Oc()[0]))}this.Tja();this.hqa(n);q=this.a4();this.fu=1===q[0]?!0:!1;this.Uq=1===q[1]?!0:!1;if(null!=p){if(this.fu||this.Uq)this.Ei||(this.Ei={}),0<a||0<d?(0<a&&this.Uq&&(this.Ei[b.f.F.xd]=a),0<d&&this.fu&&(this.Ei[b.f.F.Cp]=d)):(this.Ei[b.f.F.Cp]=this.fu?n[0].offsetHeight:0,this.Ei[b.f.F.xd]=this.Uq?n[0].offsetWidth:0),this.rD||(this.rD=n.outerWidth()-n.innerWidth()),
this.U0||(this.U0=n.outerHeight()-n.innerHeight()),a=0,this.fu&&!this.Uq&&(n.css(b.f.F.gA,b.f.ma.Sg),a=n.get(0).offsetWidth-n.get(0).clientWidth,0<this.Ei[b.f.F.xd]?g.css(b.f.F.xd,n.get(0).clientWidth+b.f.ma.fc):(g.css(b.f.F.xd,n.get(0).scrollWidth+a+b.f.ma.fc),q=this.a4(),1===q[1]&&g.css(b.f.F.xd,n.get(0).clientWidth+b.f.ma.fc)),n.css(b.f.F.gA,"")),d=g.width(),this.yka(),t=0,g=g.children("caption"),null!=g&&0<g.length&&(t=f(g[0]).outerHeight(),g.css(b.f.F.wd,b.f.ma.xR),null!=h&&h.css(b.f.F.PQ,n.css(b.f.F.PQ).toString())),
g=0,null!=h&&(h.css(b.f.F.wd,b.f.ma.gs),this.cl()?(h.css(b.f.F.Al,b.f.ma.SF),h.css(b.f.F.Gs,"0px")):h.css(b.f.F.Al,b.f.ma.Bs),m.css(b.f.F.wd,b.f.ma.gs),m.css(b.f.F.Al,b.f.ma.Bs),g=h.outerHeight()),this.cl()&&n.css(b.f.F.L8,g+t+b.f.ma.fc),m=0,null!=k&&(this.cl()?(k.css(b.f.F.Al,b.f.ma.SF),h.css(b.f.F.WF,"0px")):k.css(b.f.F.Al,b.f.ma.Bs),k.css(b.f.F.wd,b.f.ma.gs),l.css(b.f.F.wd,b.f.ma.gs),l.css(b.f.F.Al,b.f.ma.Bs)),p.css(b.f.F.wd,b.f.ma.gs),l=0,this.cl()||(p.css(b.f.F.rG,b.f.ma.Sg),p.css(b.f.F.Al,b.f.ma.Bs),
this.Uq?p.css(b.f.F.xd,this.Ei[b.f.F.xd]-this.rD):0<a&&p.css(b.f.F.xd,d-this.rD+a),p.width(),null!=k&&(m=k.outerHeight(),p.css(b.f.F.Gs,-1*m+b.f.ma.fc)),this.fu?(l=this.Ei[b.f.F.Cp]-g-m-t-this.U0,0<l&&(p.css(b.f.F.Cp,l+b.f.ma.fc),p.css(b.f.F.NR,l+b.f.ma.fc))):l=p.outerHeight(),a=this.m3(),this.Uq?(d=this.Nf(),null!=d&&0<d.length?(p.css(b.f.F.Ov,b.f.ma.Sg),n.css(b.f.F.Ov,b.f.ma.ts),n.css(b.f.F.rG,b.f.ma.ts),null!=h&&(d=this.Ei[b.f.F.xd]-this.rD,0<d&&(0<a?h.css(b.f.F.xd,d-a+b.f.ma.fc):h.css(b.f.F.xd,
d+b.f.ma.fc)))):(p.css(b.f.F.Ov,b.f.ma.ts),n.css(b.f.F.Ov,b.f.ma.Sg),n.css(b.f.F.rG,b.f.ma.ts))):p.css(b.f.F.Ov,b.f.ma.ts)),this.cl()&&(h=this.u3(),h.css(b.f.F.gA,b.f.ma.Sg),this.Uq&&h.css(b.f.F.xd,this.Ei[b.f.F.xd]),this.fu&&h.css(b.f.F.Cp,this.Ei[b.f.F.Cp]-g-m),p.css(b.f.F.T7,b.f.ma.gk),n.css(b.f.F.gA,b.f.ma.ts)),null!=k&&(this.cl()||k.css(b.f.F.Gs,l+b.f.ma.fc));this.Lka();this.Sja(0>q[0]);this.W4();null==r||c?c&&(this.Oc()[0].scrollTop=0,this.Oc().scroll()):(q=this.Oc()[0].scrollHeight-this.Oc()[0].clientHeight,
r=r>q?q:r,this.Q.xi()&&q==r&&r--,this.Oc()[0].scrollTop=r,this.Oc().scroll());null==s||e?e&&(this.n5(this.Oc()[0],0),this.Oc().scroll()):(this.n5(this.Oc()[0],s),this.Oc().scroll())}};b.f.prototype.W4=function(){var a=this.nc(),d=this.nd(),c=this.Py(),e=a;0<d.height()&&(e=d);c&&c[0].offsetParent&&(c.css(b.f.F.Cp,d.height()+b.f.ma.fc),c.css(b.f.F.xd,d.width()+b.f.ma.fc),d=f(c[0].children[0]),a="rtl"===this.Q.ec(),e={my:"center",at:"center",collision:"none",of:e},e=b.qc.Gg(e,a),c.position(e),c={my:"center",
at:"center",collision:"none",of:c},c=b.qc.Gg(c,a),d.position(c))};b.f.prototype.Hja=function(){var a,d,c=this.Q.xb().length;for(a=0;a<c;a++)d=this.Qc(a),null!=d&&d.css(b.f.F.Mv,"");a=this.Nf();if(null!=a&&0<a.length)for(a=0;a<c;a++)d=this.kr(0,a,null),null!=d&&d.css(b.f.F.Mv,"")};b.f.prototype.Sja=function(a){if(this.rY()){var d=this.Nf();if(null!=d&&0<d.length){var c,e=d.length;for(c=0;c<e;c++)f(d[c]).hasClass(b.f.C.Vv)||f(d[c]).addClass(b.f.C.Vv);d=f(d[d.length-1]);a||d.removeClass(b.f.C.Vv)}}};
b.f.prototype.Tja=function(){var a=this.Pc(),d=this.wm(),c=this.lr(),e=this.Zk(),g=this.Ju(),h=this.nd();if(null!=d&&(d.attr(b.f.lb.ik,""),c.attr(b.f.lb.ik,""),(d=c.find("."+b.f.C.Fv))&&0<d.length))for(var k=d.length,c=0;c<k;c++)f(d[c]).css(b.f.F.xd,"");null!=e&&(e.attr(b.f.lb.ik,""),g.attr(b.f.lb.ik,""));a.css(b.f.F.wd,"");a.css(b.f.F.xd,"");null!=h&&h.attr(b.f.lb.ik,"");this.Hja()};b.f.prototype.yka=function(){var a=[],d=[],c=null,e,g,f,k,l,m=this.Q.xb().length;for(k=0;k<m;k++)c=this.Qc(k),null!=
c&&(l=window.getComputedStyle(c[0]),a[k]=parseInt(l[b.f.F.xd],10),f=this.Q.Qn(k,"header"),e||null!=f?d[k]=null!=f?parseInt(l[b.f.F.Hp],10)+parseInt(l[b.f.F.Gp],10):e:(e=parseInt(l[b.f.F.Hp],10)+parseInt(l[b.f.F.Gp],10),d[k]=e),f=null,(l=c.find("."+b.f.C.Fv))&&0<l.length&&(f=l.get(0).clientHeight),null!=f&&(c=c.find("."+b.f.C.Nz),c.css(b.f.F.NR,f+b.f.ma.fc)));e=[];k=this.Nf();if(null!=k&&0<k.length)for(k=0;k<m;k++)c=this.kr(0,k,null),null!=c&&(this.Q.Qn(k,"cell"),this.Q.IX(k)?(c=window.getComputedStyle(c[0]),
c=parseInt(c[b.f.F.Hp],10)+parseInt(c[b.f.F.Gp],10)):(g||(c=window.getComputedStyle(c[0]),g=parseInt(c[b.f.F.Hp],10)+parseInt(c[b.f.F.Gp],10)),c=g),c=c>d[k]?a[k]-c+d[k]:a[k]+d[k]-c,e[k]=c);for(k=0;k<m;k++)c=this.Qc(k),null!=c&&c.css(b.f.F.Mv,a[k]+b.f.ma.fc),c=this.kr(0,k,null),null!=c&&c.css(b.f.F.Mv,e[k]+b.f.ma.fc),g=this.UN(k),null!=g&&(c=parseInt(g.css(b.f.F.Hp),10)+parseInt(g.css(b.f.F.Gp),10),c=c>d[k]?a[k]-c+d[k]:a[k]+d[k]-c,g.css(b.f.F.Mv,c+b.f.ma.fc))};b.f.prototype.Lka=function(){var a=this.Q.xb(),
d,c,e,g,h,k,l=a.length;for(d=0;d<l;d++)c=a[d],e=this.Qc(d),null!=e&&(g=e.children("."+b.f.C.Nz),0<g.length&&(g=f(g[0]),(h=e.find("."+b.f.C.Fv))&&0<h.length&&(k=0,c.sortable==b.f.Vg&&(k=f(e.find("."+b.f.C.VQ).get(0)).width()),0<g[0].clientWidth&&h.width()+k>g[0].clientWidth&&(h.css(b.f.F.xd,""),c=h.width(),e=e.width()-k,c>e+1&&h.css(b.f.F.xd,e+b.f.ma.fc)))))};b.f.C={QQ:"oj-table-checkbox-acc-select-column",RQ:"oj-table-checkbox-acc-select-row",F9:"oj-table-container",CS:"oj-table-scroller",tS:"oj-table",
uS:"oj-table-grid-display",H9:"oj-table-element",PG:"oj-table-footer",xS:"oj-table-footer-row",QG:"oj-table-header",yS:"oj-table-header-row",kn:"oj-table-column-header-cell",Mqa:"oj-table-column-header-drop-empty-cell",SQ:"oj-table-column-header-acc-select-column",$F:"oj-table-column-header-acc-select-row",Kqa:"oj-table-column-header-acc-select-row-text",Nz:"oj-table-column-header",Fv:"oj-table-column-header-text",Mz:"oj-table-column-header-asc",Qz:"oj-table-column-header-dsc",VQ:"oj-table-column-header-sort-placeholder",
n7:"oj-table-column-header-acc-asc-link",o7:"oj-table-column-header-acc-dsc-link",zp:"oj-table-column-header-asc-link",js:"oj-table-column-header-dsc-link",p7:"oj-table-column-header-asc-icon",q7:"oj-table-column-header-dsc-icon",Pz:"oj-table-column-header-drag-indicator-before",Oz:"oj-table-column-header-drag-indicator-after",TQ:"oj-table-column-header-cell-drag-image",HG:"oj-table-body",Kp:"oj-table-body-row",KG:"oj-table-body-row-drag-indicator-before",G9:"oj-table-body-row-drag-indicator-after",
NG:"oj-table-body-row-touch-selection-affordance-top",MG:"oj-table-body-row-touch-selection-affordance-bottom",wS:"oj-table-body-row-touch-selection-affordance-top-icon",vS:"oj-table-body-row-touch-selection-affordance-bottom-icon",OG:"oj-table-body-row-touch-selection-affordance-touch-area",JG:"oj-table-body-current-row",Es:"oj-table-data-cell",IG:"oj-table-data-cell-acc-select",Fs:"oj-table-vgrid-lines",Vv:"oj-table-hgrid-lines",Lp:"oj-table-footer-cell",bra:"oj-table-footer-drop-empty-cell",zS:"oj-table-inline-message",
RG:"oj-table-status-message",I9:"oj-table-status-message-text",AS:"oj-table-no-data-message",BS:"oj-table-no-data-row",Op:"oj-component-icon",ji:"oj-helper-hidden-accessible"};b.f.F={wd:"display",Al:"position",Cp:"height",xd:"width",Gs:"top",WF:"bottom",gk:"left",nA:"right",L8:"padding-top",Gp:"padding-left",Hp:"padding-right",gA:"overflow",Ov:"overflow-x",rG:"overflow-y",Mv:"min-width",NR:"min-height",T7:"float",PQ:"border-top",OQ:"border-bottom-width",l7:"border-left-width",dA:"margin-bottom",P9:"vertical-align",
YQ:"cursor",Q9:"z-index"};b.f.ma={rn:"none",gs:"block",Bs:"relative",SF:"absolute",xR:"inline",Sg:"auto",ts:"hidden",gk:"left",fc:"px",A8:"middle",B8:"move"};b.f.lb={ik:"style",Uv:"tabindex",vA:"type",ek:"id",sA:"title",Y7:"href",hG:"headers",hs:"colspan"};b.f.mb={bk:"div",RF:"a",Mp:"tr",Bl:"td",FS:"th",ara:"table",DS:"tbody",GS:"thead",ES:"tfoot",Yz:"input",O9:"ul",A9:"span"};b.f.la={VG:"oj-component",lf:"oj-active",yp:"oj-clickable-icon-nocontext",vb:"oj-disabled",pf:"oj-enabled",cj:"oj-focus",
dk:"oj-hover",hd:"oj-selected",yA:"oj-warning",hR:"oj-draggable",ns:"oj-drag"};b.f.UQ="_hdrColRowSel";b.f.fA="auto";b.f.Vg="enabled";b.f.vn="disabled";b.f.ni={Ds:"single",Ep:"multiple"};b.f.XR={Wqa:"list",pR:"grid"};b.cb=function(a){this.Q=a;this.options=a.options;this.Init()};o_("TableDndContext",b.cb,b);b.b.ga(b.cb,b.b,"oj.TableDndContext");b.cb.prototype.Init=function(){b.cb.q.Init.call(this)};b.b.g("TableDndContext.prototype.Init",{Init:b.cb.prototype.Init});b.cb.prototype.Y9=function(a){this.p().Qc(a).addClass(b.f.la.ns);
this.p().o5(a,!0,b.f.la.ns)};b.cb.prototype.Dja=function(){var a=this.p().wm().find("."+b.f.la.ns);if(null!=a&&0<a.length){var d,c=a.length;for(d=0;d<c;d++)f(a[d]).removeClass(b.f.la.ns)}this.p().o5(null,!1,b.f.la.ns)};b.cb.prototype.Eaa=function(a){var b;a[0].getBoundingClientRect();var c=a.scrollLeft(),e=a.scrollTop();b=a.clone();b.css({overflow:"hidden","overflow-x":"hidden","overflow-y":"hidden","background-color":"transparent",width:a.css("width"),height:a.css("height"),position:"fixed",top:1E4});
f("body").append(b);b.scrollLeft(1*c);b.scrollTop(1*e);return b};b.cb.prototype.Vba=function(){this.vI&&(this.vI.remove(),this.vI=null)};b.cb.prototype.iq=function(a){return this.p().me(f(a.currentTarget))};b.cb.prototype.dea=function(a){var d;d=f(a.target).closest("tr");d=(a=this.Q.getContextByNode(a.target))&&"oj-table-cell"==a.subId?a.rowIndex:d&&d.hasClass(b.f.C.KG)?this.Pn:(d=this.p().Nf())?d.length:0;return d};b.cb.prototype.p=function(){return this.Q.p()};b.cb.prototype.soa=function(a){if(this.wK()){var b=
this.iq(a);this.mB=b;this.ala(a,b);this.Q.bu(null);this.Q.option("selection",null,{_context:{Ic:!0,Va:!0}});setTimeout(function(){window.getSelection().removeAllRanges()},0);this.Y9(b);return!0}};b.cb.prototype.ooa=function(){this.wK()&&(this.q5(null,!1),this.mB=null,this.p().RE(),this.p().Kpa(),this.Dja())};b.cb.prototype.poa=function(a){if(!this.vC()){var b=this.iq(a);return this.Ft("columns","dragEnter",a,{columnIndex:b})}};b.cb.prototype.uoa=function(a){var b=this.iq(a),c=this.mB;null!=c&&c!=
b&&((this.Ss=this.xK(a))&&c==b-1||!this.Ss&&c==b+1||this.p().t2(b,this.Ss),a.preventDefault())};b.cb.prototype.roa=function(a){if(this.vC())return this.uoa(a);var b=this.iq(a);this.Ss=this.xK(a);var c=this.Ft("columns","dragOver",a,{columnIndex:b});(!1===c||a.isDefaultPrevented())&&this.p().t2(b,this.xK(a));return c};b.cb.prototype.qoa=function(a){if(!this.vC()){this.p().RE();var b=this.iq(a);return this.Et("drop","columns","dragLeave",a,{columnIndex:b})}};b.cb.prototype.voa=function(a){var b=this.iq(a);
this.Ss||b++;this.Q.qk=this.p().npa(this.mB,b,a);a.preventDefault()};b.cb.prototype.toa=function(a){if(this.vC())return this.voa(a);this.p().RE();var b=this.iq(a);this.Ss||b++;return this.Ft("columns","drop",a,{columnIndex:b})};b.cb.prototype.Joa=function(a){var b=this.options.dnd.drag;if(b&&b.rows)return(b=this.Cka(a,b.rows.dataTypes,this.Q.vt()))?this.Et("drag","rows","dragStart",a,b):!1};b.cb.prototype.Eoa=function(a){return this.Et("drag","rows","drag",a)};b.cb.prototype.Foa=function(a){this.Vba();
return this.Et("drag","rows","dragEnd",a)};b.cb.prototype.Goa=function(a){var b=this.dea(a),c=this.Ft("rows","dragEnter",a,{rowIndex:b});(!1===c||a.isDefaultPrevented())&&this.mma(a,b);return c};b.cb.prototype.Ioa=function(a){return this.Ft("rows","dragOver",a,{rowIndex:this.Pn})};b.cb.prototype.Hoa=function(a){var b=this.Et("drop","rows","dragLeave",a,{rowIndex:this.Pn});this.Wga(a,a.currentTarget)||(this.p().XO(),this.Pn=null);return b};b.cb.prototype.Koa=function(a){var b=this.Pn;this.p().XO();
this.Pn=null;return this.Ft("rows","drop",a,{rowIndex:b})};b.cb.prototype.gga=function(a,b){var c;c=a.children("tr");for(var e=0;e<c.length;e++)-1==b.indexOf(e)&&f(c[e]).css("visibility","hidden")};b.cb.prototype.Et=function(a,d,c,e,g){a=this.options.dnd[a];var f;if(a&&a[d]&&(d=a[d][c])&&"function"==typeof d)try{e.dataTransfer=e.originalEvent.dataTransfer,f=d(e,g)}catch(k){b.r.error("Error: "+k)}return f};b.cb.prototype.Ft=function(a,b,c,e){b=this.Et("drop",a,b,c,e);void 0===b&&this.Kha(c,a)&&c.preventDefault();
return b};b.cb.prototype.wK=function(){var a=this.options.dnd;return a&&a.reorder&&a.reorder.columns==this.Q.Vg?!0:!1};b.cb.prototype.vC=function(){return null!=this.mB};b.cb.prototype.Wga=function(a,b){var c=b.getBoundingClientRect(),e=a.originalEvent;return e.clientX>=c.left&&e.clientX<c.right&&e.clientY>=c.top&&e.clientY<c.bottom};b.cb.prototype.xK=function(a){var d=a.currentTarget.getBoundingClientRect();return null!=a.originalEvent.clientX?(a=d.right-a.originalEvent.clientX<(d.right-d.left)/
2,"rtl"===b.v.um()?a:!a):!1};b.cb.prototype.Kha=function(a,b){var c=a.originalEvent.dataTransfer.types,e=this.options.dnd.drop;if(e&&e[b]&&e[b].dataTypes)for(var e=e[b].dataTypes,e="string"==typeof e?[e]:e,g=0;g<c.length;g++)if(0<=e.indexOf(c[g]))return!0;return!1};b.cb.prototype.Kka=function(a,d){if(a.draggable=d)f(a).css(b.f.F.YQ,b.f.ma.B8),f(a).addClass(b.f.la.hR)};b.cb.prototype.zaa=function(a){a.draggable="";f(a).css(b.f.F.YQ,b.f.ma.Sg);f(a).removeClass(b.f.la.hR)};b.cb.prototype.Bka=function(a,
b,c){a=a.dataTransfer;c=JSON.stringify(c);if("string"==typeof b)a.setData(b,c);else if(b)for(var e=0;e<b.length;e++)a.setData(b[e],c)};b.cb.prototype.Cka=function(a,b,c){for(var e=[],g=0;g<c.length;g++){var h=this.Q.getDataForVisibleRow(c[g]);h&&e.push(h)}return e.length?(this.Bka(a.originalEvent,b,e),this.vI=this.Dka(a.originalEvent,f(a.currentTarget).closest("tbody"),c),{rows:e}):null};b.cb.prototype.Dka=function(a,b,c){var e=this.Eaa(b);this.gga(e,c);c=b[0].getBoundingClientRect();var g=b.scrollLeft();
b=b.scrollTop();a.dataTransfer.setDragImage(e[0],a.clientX-c.left+g,a.clientY-c.top+b);return e};b.cb.prototype.ala=function(a,b){var c=a.originalEvent.dataTransfer,e=this.p().nr(this.p().koa());c.setData("Text",this.Q.H7+":"+e+":"+b);e=this.p().vna(b);try{c.setDragImage(e[0],0,0)}catch(g){}};b.cb.prototype.q5=function(a,b){if(this.wK()){var c=this.p().Oy();if(null!=c&&0<c.length){var e;for(e=0;e<c.length;e++){var g=c[e];null!=a&&e==a?this.Kka(g,b):this.zaa(g)}}}};b.cb.prototype.mma=function(a,b){if(this.Pn!=
b){var c=f(a.target).closest("tr");this.Pn=b;this.p().Hna(this.Pn,c)}};b.dg={};b.dg.W1=function(a,d){var c=f(a.headerContext.parentElement),e=f(document.createElement("div"));e.addClass(b.f.C.Nz);c.empty();c.append(e);c=f(document.createElement("div"));c.addClass(b.f.C.Fv);e.prepend(c);null!=d?d(c):this.X1(c,a)};b.dg.Y1=function(a,d){var c=a.headerContext.component,e=f(a.headerContext.parentElement),g=f(document.createElement("div"));g.addClass(b.f.C.Nz);e.empty();e.append(g);"rtl"===c.ec()?g.css(b.f.F.Gp,
"0px"):g.css(b.f.F.Hp,"0px");e=f(document.createElement("div"));e.addClass(b.f.C.Mz);g.append(e);var h=f(document.createElement("a"));h.addClass(b.f.C.zp);h.addClass(b.f.C.Op);h.addClass(b.f.C.p7);h.addClass(b.f.la.vb);h.addClass(b.f.la.yp);c._hoverable(h);e.append(h);var h=e.width(),k=e.height(),l=f(document.createElement("a"));l.attr("tabindex","0");l.attr("href","#");l.addClass(b.f.C.n7);l.addClass(b.f.C.ji);l.text(c.A("labelSortAsc"));e.append(l);e=f(document.createElement("div"));e.addClass(b.f.C.VQ);
e.css(b.f.F.wd,"inline-block");e.css(b.f.F.P9,b.f.ma.A8);e.css("width",h+"px");e.css("height",k+"px");g.append(e);e=f(document.createElement("div"));e.addClass(b.f.C.Qz);e.addClass(b.f.la.vb);g.append(e);h=f(document.createElement("a"));h.addClass(b.f.C.js);h.addClass(b.f.C.Op);h.addClass(b.f.C.q7);h.addClass(b.f.la.vb);h.addClass(b.f.la.yp);c._hoverable(h);e.append(h);h=f(document.createElement("a"));h.attr("tabindex","0");h.attr("href","#");h.addClass(b.f.C.o7);h.addClass(b.f.C.ji);h.text(c.A("labelSortDsc"));
e.append(h);c=f(document.createElement("div"));c.addClass(b.f.C.Fv);g.prepend(c);null!=d?d(c):this.X1(c,a)};b.dg.X1=function(a,b){var c=b.columnIndex,c=b.headerContext.component.xb()[c];a.text(c.headerText)};b.dg.mqa=function(a,b,c){var e=c.rowContext.component,g=f(c.rowContext.parentElement),h=e.p().nr(b.key),k=e.xb();e.p().fP(b,g);g=k.length;for(e=0;e<g;e++)this.lqa(a,e,b,h,c)};b.dg.lqa=function(a,d,c,e,g){var h=g.rowContext.component;g=f(g.rowContext.parentElement);var k=h.xb()[d],l=h.p().nna();
h.p().kP(d,l,!0);h.p().Soa(a,c.key,e,d,l,g);var m=null;null!=k.field&&(m=c.data[k.field]);if(k=h.Qn(d,"cell")){var n=this.oE(h,c,l[0]),m=k({cellContext:n,columnIndex:d,data:m,row:f.extend({},c.data)});null!=m?l.append(m):(l=f(g.children(":not(."+b.f.C.IG+")")[d]),h.p().eP(a,c.key,e,d,l),h.p().kP(d,l,!1))}else l.text(m)};b.dg.oE=function(a,d,c){var e={};e.component=a;var g=a.eb();g instanceof b.na&&(g=g.getWrappedDataSource());e.datasource=g;e.parentElement=c;if(null!=d&&(e.status=this.doa(a,d),g instanceof
b.nb)){a=g.oJ(d.index);for(var f in a)a.hasOwnProperty(f)&&(e[f]=a[f])}return e};b.dg.doa=function(a,b){return{rowIndex:b.index,rowKey:b.key,currentRow:f.extend({},a.aW())}}});