/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtThematicMap"],function(b,f,a,d,c){b.ya("oj.ojThematicMap",f.oj.dvtBaseComponent,{widgetEventPrefix:"oj",options:{load:null,optionChange:null},GU:"",FC:[],S0:{ar:"ar",cs:"cs",da:"da",de:"de",el:"el",es:"es",fi:"fi",fr:"fr","fr-ca":"fr_CA",he:"iw",hu:"hu",it:"it",ja:"ja",ko:"ko",nl:"nl",no:"no",pl:"pl",pt:"pt_BR","pt-pt":"pt",ro:"ro",ru:"ru",sk:"sk",sv:"sv",th:"th",tr:"tr","zh-hans":"zh_CN","zh-hant":"zh_TW"},
_ComponentCreate:function(){this._super();this.Tp=[];this.dY=!1;this.Ts=[]},nf:function(a,b,d){return c.DvtThematicMap.newInstance(a,b,d)},di:function(a){var b=a.subId;"oj-thematicmap-area"==b?b=a.dataLayer+":area["+a.index+"]":"oj-thematicmap-marker"==b?b=a.dataLayer+":marker["+a.index+"]":"oj-thematicmap-tooltip"==b&&(b="tooltip");return b},gg:function(a){var b={};0<a.indexOf(":area")?(b.subId="oj-thematicmap-area",b.dataLayer=a.substring(0,a.indexOf(":")),b.index=this.Ug(a)):0<a.indexOf(":marker")?
(b.subId="oj-thematicmap-marker",b.dataLayer=a.substring(0,a.indexOf(":")),b.index=this.Ug(a)):"tooltip"==a&&(b.subId="oj-thematicmap-tooltip");return b},Be:function(){var a=this._super();a.push("oj-thematicmap");return a},ei:function(){var a=this._super();a["oj-dvtbase oj-thematicmap"]={path:"animationDuration",property:"animation-duration"};a["oj-thematicmap-arealayer"]=[{path:"styleDefaults/areaStyle",property:"CSS_BACKGROUND_PROPERTIES"},{path:"styleDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"}];
a["oj-thematicmap-area"]={path:"styleDefaults/dataAreaDefaults/borderColor",property:"border-top-color"};a["oj-thematicmap-area oj-hover"]={path:"styleDefaults/dataAreaDefaults/hoverColor",property:"border-top-color"};a["oj-thematicmap-area oj-selected"]=[{path:"styleDefaults/dataAreaDefaults/selectedInnerColor",property:"border-top-color"},{path:"styleDefaults/dataAreaDefaults/selectedOuterColor",property:"border-bottom-color"}];a["oj-thematicmap-marker"]=[{path:"styleDefaults/dataMarkerDefaults/labelStyle",
property:"CSS_TEXT_PROPERTIES"},{path:"styleDefaults/dataMarkerDefaults/color",property:"background-color"},{path:"styleDefaults/dataMarkerDefaults/opacity",property:"opacity"},{path:"styleDefaults/dataMarkerDefaults/borderColor",property:"border-top-color"}];return a},hi:function(){return["load","optionChange"]},_setOptions:function(a,c){var d=Object.keys(a).length,f=a.areaLayers,l=this.options.areaLayers,m=a.pointDataLayers;if(1==d&&f&&l&&0<l.length)for(d=0;d<f.length;d++){var m=f[d],n=l[d],p=!0,
r;for(r in m)"areaDataLayer"!=r&&m[r]!=n[r]&&(p=p&&!1);p&&!b.b.mh(n.areaDataLayer,m.areaDataLayer)&&this.Ts.push({options:m.areaDataLayer,parentLayer:m.layer,isADL:!0})}else if(1==d&&m&&this.options.pointDataLayers&&0<this.options.pointDataLayers.length)for(d=0;d<m.length;d++)b.b.mh(this.options.pointDataLayers[d],m[d])||this.Ts.push({options:m[d],parentLayer:m[d].id,isADL:!1});this._super(a,c)},ig:function(){this.zha();for(var a=0;a<this.Tp.length;a++)if(!this.FC[this.Tp[a]])return;this.Tp=[];this.lma();
var b=this.options.areaLayers;if(b)for(a=0;a<b.length;a++){var c=b[a].areaDataLayer;if(c){var d=c._templateRenderer;d&&(c.renderer=this.cC(d,c.markers))}}if(b=this.options.pointDataLayers)for(a=0;a<b.length;a++)(c=b[a])&&(d=c._templateRenderer)&&(c.renderer=this.cC(d,c.markers));this.options._contextHandler=this.WI();if(this.dY&&0<this.Ts.length){if(this.lg.isReadyToRender()){for(a=0;a<this.Ts.length;a++)d=this.Ts[a],this.ka.updateLayer(d.options,d.parentLayer,d.isADL);this.Ts=[]}}else this._super(),
this.dY=!0;this._trigger("load",null,null)},cC:function(a){var b=this;return function(c){var d=document.createElement("div");d.style.display="none";d.zI=b.lg;b.element.append(d);a({parentElement:d,data:c.data});return(c=d.children[0])?"http://www.w3.org/2000/svg"===c.namespaceURI?(f(d).remove(),c):b.Kv(c):null}},WI:function(){var a=this;return function(c,d,f,l,m){return{component:b.Components.Of(a.element),parentElement:c,rootElement:d,data:f,state:l,previousState:m,id:f.id,label:f.label,color:f.color,
location:f.location,x:f.x,y:f.y}}},renderDefaultHover:function(a){a.previousState&&a.state.hovered==a.previousState.hovered||this.ka.processDefaultHoverEffect(a.id,a.state.hovered)},renderDefaultSelection:function(a){a.previousState&&a.state.selected==a.previousState.selected||this.ka.processDefaultSelectionEffect(a.id,a.state.selected)},renderDefaultFocus:function(a){a.previousState&&a.state.focused==a.previousState.focused||this.ka.processDefaultFocusEffect(a.id,a.state.focused)},zha:function(){var a=
this.options.basemap;if(a){var c=b.ba.Ag();c!==this.GU&&(this.GU=c,this.FC=[]);var a=a.charAt(0).toUpperCase()+a.slice(1),d=this.options.areaLayers;if(d)for(var f=0;f<d.length;f++){var l=d[f].layer;l&&(l=l.charAt(0).toUpperCase()+l.slice(1),this.SY(a,l,c))}(d=this.options.pointDataLayers)&&0<d.length&&this.SY(a,"Cities",c)}},VY:function(a){if(!this.FC[a]){var c=b.ba.kb(a),d=this,k=this.FC;f.getScript(c,function(){k[a]=!0;d.ig()})}},SY:function(a,b,c){var d="resources/internal-deps/dvt/thematicMap/basemaps/DvtBaseMap"+
a+b+".js";-1==this.Tp.indexOf(d)&&(this.Tp.push(d),this.VY(d));if(-1===c.indexOf("en"))for(d=c.toLowerCase().split("-"),c=[d[0]],1<d.length&&c.unshift(d[0]+"-"+d[1]),2<d.length&&c.unshift(d[0]+"-"+d[2],d[0]+"-"+d[1]+"-"+d[2]),a="resources/internal-deps/dvt/thematicMap/resourceBundles/"+a+b+"Bundle",b=0;b<c.length;b++)if(this.S0[c[b]]){a=a+"_"+this.S0[c[b]]+".js";-1==this.Tp.indexOf(a)&&(this.Tp.push(a),this.VY(a));break}},ki:function(a){var b,d;if((a&&a.getType?a.getType():null)===c.DvtSelectionEvent.TYPE){b=
{};d=a.getParamValue("clientId");b[d]=a.getSelection();if(this.options.selection)for(var f in this.options.selection)d!==f&&(b[f]=this.options.selection[f]);this.jc("selection",b)}else this._super(a)},ii:function(){var a=this.options.translations,b=this._super();b["DvtUtilBundle.THEMATIC_MAP"]=a.componentName;return b},lma:function(){var a=this.options.selection;if(a){var b=this.options.pointDataLayers;if(b)for(var c=0;c<b.length;c++)a[b[c].id]&&(b[c].selection=a[b[c].id]);if(b=this.options.areaLayers)for(c=
0;c<b.length;c++){var d=b[c].areaDataLayer;d&&a[d.id]&&(d.selection=a[d.id])}}},getArea:function(a,b){var c=this.ka.getAutomation().getData(a,"area",b);this.Tg(c);return c},getMarker:function(a,b){var c=this.ka.getAutomation().getData(a,"marker",b);this.Tg(c);return c},getContextByNode:function(a){return(a=this.getSubIdByNode(a))&&"oj-thematicmap-tooltip"!==a.subId?a:null},gi:function(){return{areaLayers:["areaDataLayer/areas","areaDataLayer/markers"],pointDataLayers:["markers"]}},rR:function(a){var b=
this.options.basemap;a=a.layer?a.layer:"cities";return{basemap:b,layer:a,ids:c.DvtBaseMapManager.getLayerIds(b,a)}}})});