/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(b,f){(function(){b.ya("oj.ojToolbar",f.oj.baseComponent,{widgetEventPrefix:"oj",options:{chroming:"half"},Yd:function(a,d){this._super(a,d);"disabled"in d&&b.r.warn("Caller attempted to set the 'disabled' option on Toolbar, but Toolbar does not support the 'disabled' option.  See API doc.")},_ComponentCreate:function(){this._super();this.element.attr(b.Components.tn,this.widgetName).addClass("oj-toolbar oj-component").attr("role","toolbar");
this.Aa(!0)},qf:function(a,b,c){a=this.element.find(":oj-button[tabindex\x3d0]");this.sf(b,c,{launcher:a,position:{of:"keyboard"===c?a.ojButton("widget"):b}})},_setOption:function(a,d){this._superApply(arguments);"disabled"===a?b.r.warn("Caller attempted to set the 'disabled' option on Toolbar, but Toolbar does not support the 'disabled' option.  See API doc.  Ignoring the call."):"chroming"===a&&(this.$E.ojButtonset("refresh"),this.AP.ojButton("refresh"))},refresh:function(){this._super();this.Aa(!1)},
Aa:function(a){var b=this;this.Qf="rtl"===this.ec();this.Fd=this.element.find(":oj-button").unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.tq(a,f(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){f(this).ojButton("option","disabled")||b.Pq(f(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Pq(f(this))});this.$E=this.element.find(":oj-buttonset").ojButtonset("refresh");this.AP=this.Fd.not(this.$E.find(":oj-button")).ojButton("refresh");
this.rl=this.Fd.filter(function(){return!f(this).ojButton("option","disabled")});this.sK(a)},sK:function(a){var b=f(this.Eq);this.Eq=void 0;this.Fd.attr("tabindex","-1");a=a||!b.is(this.rl)?this.rl.first():b;this.Pq(a)},NK:function(a){var b=this.rl;return a.map(function(a,e){if("radio"!=e.type||e.checked||""==e.name)return e;var f=e.name;f?(f=f.replace(/'/g,"\\'"),f=b.filter(":radio[name\x3d'"+f+"']:oj-button")):f=b.filter(e).filter(":oj-button");f=f.filter(":checked");return f.length?f[0]:e})},Pq:function(a){a=
this.NK(a);var b=a[0],c=this.Eq;b!==c&&(f(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.Eq=b)},tq:function(a,b){switch(a.which){case f.ui.keyCode.LEFT:case f.ui.keyCode.RIGHT:a.preventDefault();var c=this.rl,e=c.length;if(2>e)break;var g=c.index(b);c.eq((g+(a.which==f.ui.keyCode.RIGHT^this.Qf?1:-1)+e)%e).focus();break;case f.ui.keyCode.UP:case f.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-toolbar oj-component").removeAttr(b.Components.tn).removeAttr("role");
this.Fd.attr("tabindex","0");this.$E.ojButtonset("refresh");this.AP.ojButton("refresh")}})})();b.Components.Om({ojToolbar:{chroming:b.Components.nh(function(){return b.ze.Yk("toolbar").chroming})}})});