define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.KB=(0,D.w)();(0,D.qa)("DvtAxis",D.KB);D.D.l(D.KB,D.Rx,"DvtAxis");D.KB.newInstance=function(b,c,d){var e=new D.KB;e.Init(b,c,d);return e};D.JC=function(b){return(0,D.lG)(new D.Dx,b)};D.KB.getDefaults=D.JC;D.KB.prototype.Init=function(b,c,d){D.KB.q.Init.call(this,b,c,d);this.lf=new D.Dx;this.Aa=new D.Gx(this);this.Aa.rf(this);this.pS=D.n;this.Ja=D.q};D.KB.prototype.be=function(b){b?this.N=this.lf.Vg(b):this.N||(this.N=(0,D.DC)(this))};
D.KB.prototype.Nw=function(b,c,d){this.be(b);this.za().isLayout=D.n;this.L(D.q,c,d);b=this.C();this.za().isLayout=D.t;this.vi();var e=this.za().position;if("top"==e||"bottom"==e)return b.j<=d&&(this.pS=D.t),new D.Je(c,window.Math.min(b.j,d));e=0<b.g?window.Math.max(1,0.1*b.g):0;b.g+e<=c&&(this.pS=D.t);return new D.Je(window.Math.min(b.g+e,c),d)};D.KB.prototype.L=function(b,c,d,e,f){this.be(b);this.ub=c;this.Lb=d;this.vi();e||(e=0);f||(f=0);D.sx.L(this,new D.H(e,f,c,d))};D.KB.prototype.render=D.KB.prototype.L;
D.C=D.KB.prototype;D.C.ag=function(b,c){this===c&&this.Xa(b)};D.C.za=(0,D.B)("N");D.C.Ua=(0,D.B)("Aa");D.C.getWidth=(0,D.B)("ub");D.C.getHeight=(0,D.B)("Lb");D.C.U=function(){this.Aa&&(this.Aa.zs(this),this.Aa.U(),this.Aa=D.q);D.KB.q.U.call(this)};D.C.xZ=(0,D.ba)("Ja");D.C.Li=function(){return new D.vx(this)};D.KB.prototype.getAutomation=D.KB.prototype.Li;
D.ux={};(0,D.qa)("DvtAxisConstants",D.ux);D.D.l(D.ux,D.D,"DvtAxisConstants");D.ux.Jx="tickLabel";D.ux.TICK_LABEL=D.ux.Jx;D.ux.Kp="title";D.ux.TITLE=D.ux.Kp;
D.Hx=(0,D.ba)("Mg");D.D.l(D.Hx,D.D,"DvtAbstractAxisValueFormatter");D.Hx.prototype.Fq=(0,D.w)();
D.vx=function(b){this.bi=b;this.Ic=this.bi.za();this.mca=this.bi.Fb};(0,D.qa)("DvtAxisAutomation",D.vx);D.D.l(D.vx,D.Ol,"DvtAxisAutomation");D.vx.prototype.hr=function(b){if((b=this.bi.Ua().na(b))&&b instanceof D.Ll&&this.Ic.groups){b=b.Tl().id;for(var c=0;c<this.Ic.groups.length;c++)if(this.Ic.groups[c]==b)return"item["+c+"]"}return D.q};D.vx.prototype.bk=function(b){if(this.mca instanceof D.hx){var c=b.indexOf("["),d=b.indexOf("]");if(0<c&&0<d)return b=b.substring(c+1,d),this.mca.Jw(this.bi.e)[b].oa()}return D.q};
D.vx.prototype.getDomElementForSubId=D.vx.prototype.bk;
D.Dx=function(){this.Init({skyros:D.Bx,alta:D.Cx})};D.D.l(D.Dx,D.Dl,"DvtAxisDefaults");D.Cx={axisLine:{lineColor:"#9E9E9E"},majorTick:{lineColor:"rgba(196,206,215,0.4)",baselineColor:"auto"},minorTick:{lineColor:"rgba(196,206,215,0.2)"},tickLabel:{style:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},titleStyle:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")};
D.Bx={position:D.q,baselineScaling:"zero",axisLine:{lineColor:"#8A8DAC",lineWidth:1,rendered:"on"},majorTick:{lineColor:"rgba(138,141,172,0.4)",lineWidth:1,rendered:"auto",lineStyle:"solid"},minorTick:{lineColor:"rgba(138,141,172,0.20)",lineWidth:1,rendered:"off",lineStyle:"solid"},tickLabel:{scaling:"auto",style:new D.K("font-size: 11px; color: #333333;"),rotation:"auto",rendered:"on"},titleStyle:new D.K("font-size: 11px; color: #737373;"),startGroupOffset:0,endGroupOffset:0,layout:{gapRatio:1,titleGap:4},
_useBaselineColor:D.t,isLayout:D.t};
D.Gx=function(b){this.Init(b.e,b.ag,b);this.bi=b};D.D.l(D.Gx,D.tm,"DvtAxisEventManager");D.Gx.prototype.Ms=function(b,c){c instanceof D.Ll&&c.Tl()!=D.q&&this.gh(new D.Tm(b,c.Tl()),this.bi)};
D.sx={};D.D.l(D.sx,D.D,"DvtAxisRenderer");D.sx.psa=5;D.sx.L=function(b,c){var d=b.za(),e=(0,D.tx)(b.e,d,c);b.Fb=e;"off"==d.rendered||(0>=c.g||0>=c.j)||(b.xZ(c.clone()),D.sx.VL(b,e,c),D.sx.SL(b,e,c))};
D.sx.VL=function(b,c,d){var e=b.za();if(e.title&&(c=e.position,!("radial"==c||"tangential"==c))){e.isLayout&&"bottom"==c&&(c="top");var f;if(f="top"==c||"bottom"==c?D.sx.qda(b.Ua(),b,e.title,e.titleStyle,d.g,d.j):D.sx.qda(b.Ua(),b,e.title,e.titleStyle,d.j,d.g)){b=(0,D.Qe)(b.e);var g=f.Rb(),e=window.Math.ceil(e.layout.titleGap*e.layout.gapRatio);"top"==c?(f.da(d.x+d.g/2-g.g/2),f.ta(d.y),d.y+=g.j+e,d.j-=g.j+e):"bottom"==c?(f.da(d.x+d.g/2-g.g/2),f.ta(d.y+d.j-g.j),d.j-=g.j+e):"left"==c?(f.Re(),f.Ae(),
f.Zi(b?window.Math.PI/2:3*window.Math.PI/2),(0,D.jg)(f,d.x+g.j/2,d.y+d.j/2),d.x+=g.j+e,d.g-=g.j+e):"right"==c&&(f.Re(),f.Ae(),f.Zi(b?window.Math.PI/2:3*window.Math.PI/2),(0,D.jg)(f,d.x+d.g-g.j/2,d.y+d.j/2),d.g-=g.j+e)}}};D.sx.SL=function(b,c,d){var e=b.za();"on"==e.tickLabel.rendered&&(e=e.position,"top"==e||"bottom"==e?D.sx.aza(b,c,d):"tangential"==e?D.sx.bza(b,c,d):D.sx.cza(b,c,d))};
D.sx.aza=function(b,c,d){for(var e=c.Jw(b.e),f=b.za().isLayout,g=0,h=(0,D.Qe)(b.e),j=0;j<e.length;j++){var m=e[j];if(m!=D.q){if(c.uV()){!f&&b.pS&&(m=D.Kl.Ub(m,d.j,d.g,b)?m:D.q);if(!m)continue;h?m.Tk():m.ni();m.O(d.y)}else{if(D.Kl.Qi(m).j-1>d.j)continue;m.lp();m.ta(d.y)}b.Ua().ja(m,new D.Ll(m.Aq,D.q,D.q,{type:D.ux.Jx,id:m.We()}));b.k(m);g=window.Math.max(g,D.Kl.Qi(m).j)}}d.y+=g;d.j-=g;c=c.Jw(b.e,1);f=0;if(c!=D.q)for(j=0;j<c.length;j++)m=c[j],m!=D.q&&!(D.Kl.Qi(m).j-1>d.j)&&(b.Ua().ja(m,new D.Ll(D.q,
D.q,D.q,{type:D.ux.Jx,id:m.We()})),e[j]!=D.q&&(f=e[j].Rb().g/2),h?m.da(m.ea()+f):m.da(m.ea()-f),m.lp(),m.ta(d.y),b.k(m))};
D.sx.cza=function(b,c,d){var e=b.za(),f=e.isLayout,g=e._alwaysAlignRight,h=e.position,e=(0,D.Qe)(b.e),j="radial"==h&&e||f&&"left"==h||!g&&!f&&"right"==h,m;"radial"==h?(m=d.x+d.g/2,m+=D.sx.psa*(e?1:-1)):m=j?d.x:d.x+d.g;for(var g=function(e){!f&&b.pS&&(e=D.Kl.Ub(e,d.g,d.j,b)?e:D.q);if(e){b.Ua().ja(e,new D.Ll(e.Aq,D.q,D.q,{type:D.ux.Jx,id:e.We()}));e.da(m);j?e.Tk():e.ni();if("radial"==h){var g=e.ga();e.ta(d.y+d.j/2-g);var o=e.C(),p=0.15*o.j,g=g+o.j/2>c.Xka()&&"circle"==b.za().polarGridShape?1:0.3,o=
window.DvtPathUtils.eA(o.x-p,o.y,o.g+2*p,o.j,2,2,2,2),o=new D.ef(b.e,o);o.la("#FFFFFF",g);b.k(o)}b.k(e)}},o=c.Jw(b.e),e=0;e<o.length;e++){var p=o[e];p!=D.q&&g(p)}o=c.Jw(b.e,1);if(o!=D.q)for(e=0;e<o.length;e++)p=o[e],p!=D.q&&g(p)};
D.sx.bza=function(b,c,d){c=c.Jw(b.e);for(var e=0;e<c.length;e++){var f=c[e];if(f!=D.q){var g=f.We(),h=d.g/2-window.Math.abs(f.ea()),j=d.j/2-window.Math.abs(f.ga());D.Kl.Ub(f,h,j,b)&&(b.Ua().ja(f,new D.Ll(f.kg()?g:D.q,D.q,D.q,{type:D.ux.Jx,id:g})),f.F(d.x+d.g/2),f.O(d.y+d.j/2),b.k(f))}}};D.sx.qda=function(b,c,d,e,f,g){var h={type:D.ux.Kp,id:D.k};d=new D.ph(c.e,d,0,0);d.Ha(e);return D.Kl.Ub(d,f,g,c)?(b.ja(d,new D.Ll(d.Aq,D.q,D.q,h)),d):D.q};
D.ix=(0,D.w)();D.D.l(D.ix,D.D,"DvtAxisInfo");D.tx=function(b,c,d){return c.timeAxisType&&"disabled"!=c.timeAxisType?new D.wx(b,c,d):(0,window.isNaN)(c.dataMin)&&(0,window.isNaN)(c.dataMax)?new D.hx(b,c,d):new D.Ex(b,c,d)};D.C=D.ix.prototype;
D.C.Init=function(b,c,d){this.e=b;this.md=c.position;this.Wj=c._radius;"top"==this.md||"bottom"==this.md?(this.jh=d.x,this.Bh=d.x+d.g):"left"==this.md||"right"==this.md?(this.jh=d.y,this.Bh=d.y+d.j):"radial"==this.md?(this.jh=0,this.Bh=this.Wj):"tangential"==this.md&&((0,D.Qe)(b)?(this.jh=2*window.Math.PI,this.Bh=0):(this.jh=0,this.Bh=2*window.Math.PI));this.rHa=this.Ah=this.Yh=this.Kf=this.xf=this.Md=this.Gc=D.q;this.lo=this.Co=0;c.leftBuffer==D.q&&(c.leftBuffer=window.Infinity);c.rightBuffer==D.q&&
(c.rightBuffer=window.Infinity);this.N=c};D.C.J=(0,D.B)("N");D.C.Jw=(0,D.ca)(D.q);D.C.oH=(0,D.ca)(D.q);D.C.Hz=function(){return[]};D.C.YC=function(){return[]};D.C.ak=(0,D.ca)(D.q);D.C.OC=(0,D.ca)(D.q);D.C.NC=(0,D.ca)(D.q);D.C.Rn=(0,D.ca)(D.q);D.C.bd=(0,D.ca)(D.q);D.C.Cz=(0,D.ca)(D.q);D.C.uV=(0,D.ca)(D.t);
D.C.Cp=function(b,c,d){if("tangential"==this.md){var e=16/180*window.Math.PI,f=1/180*window.Math.PI,g=0.5*(0,window.parseInt)(this.N.tickLabel.style.v("font-size")),h=this.Wj+g;if(d<f||d>2*window.Math.PI-f)h+=g;b=new D.ph(b,c,window.Math.round(h*window.Math.sin(d)),window.Math.round(-h*window.Math.cos(d)));d<f||window.Math.abs(d-window.Math.PI)<f||d>2*window.Math.PI-f?b.Re():d<window.Math.PI?b.Tk():b.ni();window.Math.abs(d-window.Math.PI/2)<e||window.Math.abs(d-3*window.Math.PI/2)<e?b.Ae():d<window.Math.PI/
2||d>3*window.Math.PI/2?b.ww():b.lp()}else b=new D.ph(b,c,d,d),b.Ae(),b.Re();b.Ha(this.N.tickLabel.style);return b};D.rx=function(b,c,d,e){var f=!(0,D.wf)()||1<(0,D.jq)();"radial"==b.md?("polygon"==b.N.polarGridShape?(e=D.Fx.BH(0,0,b.N._numGroups,e),c=new D.Lv(c,e)):c=new D.Hv(c,0,0,e),(0,D.Yg)(c)):"tangential"==b.md?(c=new D.cn(c,0,0,b.Wj*window.Math.sin(e),-b.Wj*window.Math.cos(e)),0.01>e%window.Math.PI/2&&f&&(0,D.bn)(c)):(c=new D.cn(c,e,e,e,e),f&&(0,D.bn)(c));c.Z(d);c.ia(D.t);return c};
D.px=function(b,c,d){if(!c||0>=c.length)return D.t;var e=(0,window.parseInt)(b.N.tickLabel.style.v("font-size")),f=b instanceof D.hx?0.3*e:1*e,g=b instanceof D.hx?0.1*e:0.35*e,f=(e="left"==b.md||"right"==b.md||"radial"==b.md)||b.uV()?g:f;b=(0,D.Qe)(b.e);for(var h,j,m,o=0;o<c.length;o+=d+1)if(c[o]!=D.q)if(h==D.q||j==D.q)e?(h=c[o].y,j=c[o].y+c[o].j):(h=c[o].x,j=c[o].x+c[o].g);else{if(e){if(g=c[o].y,m=c[o].y+c[o].j,g>=h&&g-f<j||g<h&&m+f>h)return D.n}else if(g=c[o].x,m=c[o].x+c[o].g,!b&&g-f<j||b&&m+f>
h)return D.n;h=g;j=m}return D.t};D.mx=function(b,c,d){for(var e=0,f=(0,D.px)(b,d,e);f;)e++,f=(0,D.px)(b,d,e);if(0<e){b=[];for(d=0;d<c.length;d+=e+1)b.push(c[d]);return b}return c};D.qx=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f==D.q?d.push(D.q):(f=f.Rb(c),d.push(f))}return d};
D.lx=function(b,c,d,e){var f=[];"undefined"==typeof e&&(e=1);for(var g=0;g<c.length;g++){var h=c[g];if(h==D.q)f.push(D.q);else{d.k(h);var j=D.Kl.Qi(h),m=j.g*e,j=j.j;d.removeChild(h);h=b.uV()?new D.H(h.M()-j/2,h.K()-m/2,j,m):new D.H(h.ea()-m/2,h.ga()-j/2,m,j);f.push(h)}}return f};D.C=D.ix.prototype;D.C.VU=(0,D.ca)(D.q);D.C.qW=(0,D.w)();D.C.aV=(0,D.ca)(D.q);D.C.rW=(0,D.w)();D.C.eN=(0,D.ca)(D.q);D.C.$U=(0,D.ca)(D.q);D.C.Gw=(0,D.B)("xf");D.C.Fw=(0,D.B)("Kf");D.C.us=(0,D.B)("Gc");D.C.Qw=(0,D.B)("Md");
D.C.S5=(0,D.B)("Yh");D.C.R5=(0,D.B)("Ah");D.C.Kw=(0,D.ca)(0);D.C.Xka=(0,D.B)("Bh");D.C.iV=(0,D.B)("Co");D.C.LU=(0,D.B)("lo");
D.Ex=function(b,c,d){this.Init(b,c,d)};D.D.l(D.Ex,D.ix,"DvtDataAxisInfo");D.C=D.Ex.prototype;
D.C.Init=function(b,c,d){D.Ex.q.Init.call(this,b,c,d);"top"==this.md||"bottom"==this.md?("off"!=c.tickLabel.rendered&&"off"!=c.rendered&&(this.Co=window.Math.max(10-c.leftBuffer,0),this.lo=window.Math.max(10-c.rightBuffer,0)),(0,D.Qe)(b)?(this.Fi=this.Bh-this.lo,this.Nk=this.jh+this.Co):(this.Fi=this.jh+this.Co,this.Nk=this.Bh-this.lo)):"tangential"==this.md||"radial"==this.md?(this.Fi=this.jh,this.Nk=this.Bh):(this.Fi=this.Bh,this.Nk=this.jh);this.xf=c.min;this.Kf=c.max;this.Gc=c.viewportMin==D.q?
this.xf:c.viewportMin;this.Md=c.viewportMax==D.q?this.Kf:c.viewportMax;this.Cf=c.step;this.bC=c.minorStep;this.c2=c.minStep;this.Hh=D.q;c.tickLabel!=D.q&&(this.Hh=c.tickLabel.converter);this.Yh=c.dataMin;this.Ah=c.dataMax;b="zero"==this.N.baselineScaling;c="on"==this.N._continuousExtent;b&&(this.Yh=window.Math.min(0,this.Yh),this.Ah=window.Math.max(0,this.Ah));d=(0,D.Ix)(this,this.xf!=D.q?this.xf:this.Yh,this.Kf!=D.q?this.Kf:this.Ah);this.Yh==this.Ah&&(0==this.Yh?this.Ah+=5*d:(this.Yh-=3*d,this.Ah+=
2*d));if(this.xf==D.q)if(b&&0<=this.Yh)this.xf=0;else if(c)this.xf=this.Yh-0.1*(this.Ah-this.Yh),0<=this.Yh&&(this.xf=window.Math.max(this.xf,0));else if(!b&&this.Kf!=D.q)for(this.xf=this.Kf;this.xf>this.Yh;)this.xf-=d;else this.xf=window.Math.floor(this.Yh/d)*d;if(this.Kf==D.q)if(b&&0>=this.Ah)this.Kf=0;else if(c)this.Kf=this.Ah+0.1*(this.Ah-this.Yh),0>=this.Ah&&(this.Kf=window.Math.min(this.Kf,0));else if(b)this.Kf=(window.Math.floor(this.Ah/d)+1)*d;else for(this.Kf=this.xf;this.Kf<=this.Ah;)this.Kf+=
d;this.Kf==this.xf&&(this.Kf=100,this.xf=0,d=(this.Kf-this.xf)/10);this.Gc==D.q&&(this.Gc=this.xf);this.Md==D.q&&(this.Md=this.Kf);if(this.Gc!=this.xf||this.Md!=this.Kf)d=(0,D.Ix)(this,this.Gc,this.Md);this.Cf=this.Cf?this.Cf:d;"on"==this.N.alignTickMarks&&this.N._majorTickCount?(this.Uv=this.N._majorTickCount,this.Cf=(this.Md-this.Iz())/this.Uv,b=window.Math.pow(10,window.Math.ceil(window.Math.log(this.Cf)/window.Math.log(10)-1)),c=this.Cf/b,c=1<c&&1.5>=c?1.5:window.Math.ceil(c),this.Cf=c*b,this.Md=
this.Cf*this.Uv+this.Iz()):(this.c2!=D.q&&this.Cf<this.c2&&(this.Cf=this.c2),this.Uv=(this.Md-this.Iz())/this.Cf);this.oL=this.bC!=D.q&&2<=this.Cf/this.bC?this.N._minorTickCount?this.N._minorTickCount:this.Cf/this.bC:2;this.bC=this.Cf/this.oL};D.C.Iz=function(){return"zero"==this.N.baselineScaling||"on"==this.N._continuousExtent&&this.N.min==D.q?window.Math.ceil(this.Gc/this.Cf)*this.Cf:window.Math.ceil((this.Gc-this.xf)/this.Cf)*this.Cf+this.xf};
D.C.Jw=function(b,c){if(c&&0<c)return D.q;var d=[],e=[],e=b.Jc,f="tangential"==this.md;this.N.tickLabel&&this.N.tickLabel.scaling&&(this.YP=new D.Jx(this.Gc,this.Md,this.Cf,this.N.tickLabel.scaling,this.N.tickLabel.autoPrecision?this.N.tickLabel.autoPrecision:"on"));for(var g=0;g<=this.Uv;g++){var h=g*this.Cf+this.Iz();if(!(f&&h==this.Md)){var j=this.Mo(h),h=this.bd(h),j=this.Cp(b,j,h);d.push(j)}}f||(e=(0,D.qx)(d,e),d=(0,D.mx)(this,d,e));return d};
D.C.oH=function(b){var c=this.N.axisLine;return"on"==c.rendered?(c=new D.ff(c.lineColor,1,c.lineWidth),(0,D.rx)(this,b,c,this.Nk)):D.q};
D.C.Hz=function(b){var c=[],d,e,f=this.N.majorTick;if("off"==f.rendered)return c;e=f.lineColor;var g=new D.ff(e,1,f.lineWidth);f.lineStyle&&g.V((0,D.dn)(f.lineStyle));var h=g.clone();"inherit"!=f.baselineColor&&(e="auto"==f.baselineColor?D.N.Yk(e,0.4):f.baselineColor,h.Bs(e));h.ha(f.baselineWidth!=D.q?f.baselineWidth:f.lineWidth);h.V((0,D.dn)(f.baselineStyle?f.baselineStyle:f.lineStyle));for(f=0;f<=this.Uv;f++)d=f*this.Cf+this.Iz(),"tangential"==this.md&&d==this.Md||(e=0==d?h:g,d=this.bd(d),e=(0,D.rx)(this,
b,e,d),c.push(e));return c};D.C.YC=function(b){var c=[],d,e=this.N.minorTick;if("on"!=e.rendered)return c;var f=new D.ff(e.lineColor,1,e.lineWidth);e.lineStyle&&f.V((0,D.dn)(e.lineStyle));for(e=-1;e<=this.Uv;e++)for(var g=e*this.Cf+this.Iz(),h=1;h<this.oL;h++){d=g+h*this.bC;if(d>this.Md)break;d<this.Gc||(d=this.bd(d),d=(0,D.rx)(this,b,f,d),c.push(d))}return c};D.C.ak=function(b){return b<this.Gc||b>this.Md?D.q:this.bd(b)};
D.C.OC=function(b){var c=window.Math.min(this.Fi,this.Nk),d=window.Math.max(this.Fi,this.Nk);b<c?b=c:b>d&&(b=d);return this.Rn(b)};D.C.NC=function(b){b<this.Gc?b=this.Gc:b>this.Md&&(b=this.Md);return this.bd(b)};D.C.Rn=function(b){return this.Gc+(b-this.Fi)/(this.Nk-this.Fi)*(this.Md-this.Gc)};D.C.bd=function(b){return this.Fi+(b-this.Gc)/(this.Md-this.Gc)*(this.Nk-this.Fi)};D.C.Cz=function(){var b=0;0>this.Md?b=this.Md:0<this.Gc&&(b=this.Gc);return this.ak(b)};
D.C.Mo=function(b){if(this.Hh&&(this.Hh.getAsString||this.Hh.format)){if(this.YP)return this.YP.Fq(b,this.Hh);if(this.Hh.getAsString)return this.Hh.getAsString(b);if(this.Hh.format)return this.Hh.format(b)}else{if(this.YP)return this.YP.Fq(b);var c=window.Math.log(this.Cf)/window.Math.log(10),c=window.Math.max(window.Math.ceil(-c),0);return b.toFixed(c)}};
D.Ix=function(b,c,d){if(b.Cf)return b.Cf;b=d-c;if(0==b)return 0==c?10:window.Math.pow(10,window.Math.floor(window.Math.log(c)/window.Math.LN10)-1);c=window.Math.log(b)/window.Math.log(10);c=window.Math.pow(10,window.Math.ceil(c)-2);b=window.Math.round(b/c);return(10<=b&&14>=b?2:15<=b&&19>=b?3:20<=b&&24>=b?4:25<=b&&45>=b?5:46<=b&&80>=b?10:20)*c};D.C=D.Ex.prototype;D.C.VU=(0,D.B)("Uv");D.C.qW=function(b){this.Uv=b;this.Cf=(this.Md-this.Gc)/this.Uv};D.C.aV=(0,D.B)("oL");
D.C.rW=function(b){this.oL=b;this.bC=this.Cf/this.oL};D.C.eN=(0,D.B)("Cf");D.C.$U=(0,D.B)("bC");D.C.Kw=function(){return(this.Kf-this.xf)/64};D.C.iV=function(){return("top"==this.md||"bottom"==this.md)&&(0,D.Qe)(this.e)?this.lo:this.Co};D.C.LU=function(){return("top"==this.md||"bottom"==this.md)&&(0,D.Qe)(this.e)?this.Co:this.lo};
D.hx=function(b,c,d){this.Init(b,c,d)};D.D.l(D.hx,D.ix,"DvtGroupAxisInfo");
D.hx.prototype.Init=function(b,c,d){D.hx.q.Init.call(this,b,c,d);b=(0,D.Qe)(b);if(("top"==this.md||"bottom"==this.md)&&b)d=this.jh,this.jh=this.Bh,this.Bh=d;this.At=c.groups;d=0<c.endGroupOffset?(0,window.Number)(c.endGroupOffset):0;var e=0<c.startGroupOffset?(0,window.Number)(c.startGroupOffset):0;this.Yh=0;this.Ah=this.At.length-1;this.xf=c.min==D.q?this.Yh-e:c.min;this.Kf=c.max==D.q?this.Ah+d:c.max;this.Gc=c.viewportMin==D.q?this.xf:c.viewportMin;this.Md=c.viewportMax==D.q?this.Kf:c.viewportMax;
var f=(0,D.jx)(this,c.viewportStartGroup),g=(0,D.jx)(this,c.viewportEndGroup);-1!=f&&(this.Gc=f-e);-1!=g&&(this.Md=g+d);this.$ia=b?c.rightBuffer:c.leftBuffer;this.Yda=b?c.leftBuffer:c.rightBuffer;this.wfa=D.t;this.Wya=c._renderGridAtLabels;this.Sv=D.q};D.nx=function(b,c,d,e){var f,g=(0,D.Qe)(b.e);b.wfa=D.n;(0,D.kx)(b,e,e,c);for(var h=0;h<c.length;h++)e=c[h],e!=D.q&&(f=e.ea(),e.da(0),e.ta(0),g?e.Zi(window.Math.PI/2):e.Zi(3*window.Math.PI/2),e.F(f));d=(0,D.lx)(b,c,d);return(0,D.mx)(b,c,d)};
D.hx.prototype.uV=(0,D.B)("wfa");D.kx=function(b,c,d,e){c=window.Math.max(c-b.$ia,0);d=window.Math.max(d-b.Yda,0);var f=(0,D.Qe)(b.e);b.jh+=(c-b.Co)*(f?-1:1);b.Bh-=(d-b.lo)*(f?-1:1);for(f=0;f<e.length;f++){var g=e[f];g&&g.da(b.ak(f))}b.Co=c;b.lo=d};D.C=D.hx.prototype;D.C.Jw=function(b,c){if(c&&0<c)return D.q;this.Sv||(this.Sv=this.L0(b));return this.Sv};
D.C.L0=function(b){for(var c=[],d=b.Jc,e="top"==this.md||"bottom"==this.md,f=(0,D.Qe)(b),g=this.At.length,h,j,m=0;m<g;m++){var o=(0,D.ox)(this,m),p=this.ak(m);p!=D.q?(j=this.Cp(b,o,p),c.push(j),h||(h=j)):c.push(D.q)}if("tangential"==this.md)return c;b=h.Rb();e&&(this.N._startOverflow!=D.q&&this.N._endOverflow!=D.q?(g=this.N._startOverflow,f=this.N._endOverflow):(h=j.Rb(),g=f?b.g+b.x-this.jh:this.jh-b.x,f=f?this.Bh-h.x:h.g+h.x-this.Bh),(g>this.$ia||f>this.Yda)&&(0,D.kx)(this,g,f,c));f=[];f=(0,D.lx)(this,
c,d,0.3);g=(0,D.lx)(this,c,d);if(!(0,D.px)(this,g,0))return c;if(e){if("auto"==this.N.tickLabel.rotation){if((0,D.px)(this,f,0))return(0,D.nx)(this,c,d,b.j/2);f=(0,D.qx)(c,d);return(0,D.px)(this,f,0)?(0,D.nx)(this,c,d,b.j/2):c}f=(0,D.qx)(c,d);return(0,D.mx)(this,c,f)}return(0,D.mx)(this,c,g)};D.C.oH=function(b){var c=this.N.axisLine;return"on"==c.rendered?(c=new D.ff(c.lineColor,1,c.lineWidth),(0,D.rx)(this,b,c,0)):D.q};
D.C.Hz=function(b){var c=[],d,e=this.N.majorTick,f=new D.ff(e.lineColor,1,e.lineWidth);e.lineStyle&&f.V((0,D.dn)(e.lineStyle));e=e.rendered;if("on"==e||"auto"==e&&"tangential"==this.md)for(var e=this.At.length,g=0;g<e;g++){if(this.Wya)d=this.ak(g);else if(this.ak(g+0.5))d=this.ak(g+0.5);else continue;d!=D.q&&(d=(0,D.rx)(this,b,f,d),c.push(d))}return c};D.C.ak=function(b){return b<this.Gc||b>this.Md?D.q:this.bd(b)};
D.C.OC=function(b){var c=window.Math.min(this.jh,this.Bh),d=window.Math.max(this.jh,this.Bh);b<c?b=c:b>d&&(b=d);return this.Rn(b)};D.C.NC=function(b){b<this.Gc?b=this.Gc:b>=this.Md&&(b=this.Md);return this.bd(b)};D.C.Rn=function(b){return this.Gc+(b-this.jh)/((this.Bh-this.jh)/(this.Md-this.Gc))};D.C.bd=function(b){return this.jh+(b-this.Gc)*((this.Bh-this.jh)/(this.Md-this.Gc))};D.ox=function(b,c){c=window.Math.round(c);if(0>c||c>=b.At.length)return D.q;var d=b.At[c];d&&d.name&&(d=d.name);return d};
D.jx=function(b,c){if(c==D.q)return-1;for(var d=-1,e=0;e<b.At.length;e++)if(c==(0,D.ox)(b,e)){d=e;break}return d};D.hx.prototype.Kw=(0,D.ca)(1);
D.Jx=function(b,c,d,e,f){this.Mg=new D.Pn;this.Init(b,c,d,e,f)};D.D.l(D.Jx,D.Hx,"DvtLinearScaleAxisValueFormatter");
D.Jx.prototype.Init=function(b,c,d,e,f){this.Eia={};this.cs=[];this.$da={};var g=function(b,c,d){var e;this.Mg&&d&&(e=(0,D.wg)(this.Mg,d,D.q));d={As:c,EFa:e};this.Eia[b]=d;this.cs.push(d);this.$da[c]=d};g.call(this,"none",0);g.call(this,"thousand",3,"SCALING_SUFFIX_THOUSAND");g.call(this,"million",6,"SCALING_SUFFIX_MILLION");g.call(this,"billion",9,"SCALING_SUFFIX_BILLION");g.call(this,"trillion",12,"SCALING_SUFFIX_TRILLION");g.call(this,"quadrillion",15,"SCALING_SUFFIX_QUADRILLION");this.cs.sort(function(b,
c){return b.As<c.As?-1:b.As>c.As?1:0});var h=D.t,j,m,g=D.t;"off"!==f&&(g=D.n);e||(e="auto");if(e=this.Eia[e])m=e.As;"number"!==typeof m&&(h=D.n);if(h)if(h=window.Math.max(window.Math.abs(b),window.Math.abs(c)),h=(0,D.Kx)(h),m=0,h<=this.cs[0].As)m=this.cs[0].As;else if(h>=this.cs[this.cs.length-1].As)m=this.cs[this.cs.length-1].As;else for(e=this.cs.length-1;0<=e;e--)if(this.cs[e].As<=h){m=this.cs[e].As;break}g===D.n&&(0==d&&b==c?(b=m-(0,D.Kx)(c),j=0>=b?3+b:window.Math.max(b,4)):j=window.Math.max(m-
(0,D.Kx)(d),0));this.hAa=g;this.y3=m;this.g0=j};
D.Jx.prototype.Fq=function(b,c){var d=(0,window.parseFloat)(b);if((0,window.isNaN)(d))return b;var e;if(0<this.y3){for(e=0;e<this.y3;e++)d/=10;e=this.$da[this.y3].EFa}if(c&&c.getAsString)d=c.getAsString(d);else if(c&&c.format)d=c.format(d);else if(this.hAa&&!(0,window.isNaN)((0,window.parseFloat)(d))&&(d=(0,window.parseFloat)((new window.Number(d)).toFixed(this.g0)),d=""+d,0<this.g0)){-1==d.indexOf(".")&&(d+=".");for(var f=d.substring(d.indexOf(".")+1).length;f<this.g0;)d+="0",f++}"string"===typeof e&&
(d+=e);return d};D.Kx=function(b){b=0<=b?b:-b;var c=0;if(1E-15>b)return 0;if(window.Infinity==b)return window.Number.MAX_VALUE;if(10<=b)for(;10<=b;)c+=1,b/=10;else if(1>b)for(;1>b;)c-=1,b*=10;return c};
D.wx=function(b,c,d){this.Init(b,c,d)};D.D.l(D.wx,D.ix,"DvtTimeAxisInfo");
D.wx.prototype.Init=function(b,c,d){D.wx.q.Init.call(this,b,c,d);"top"==this.md||"bottom"==this.md?(!c._isOverview&&"on"==c.tickLabel.rendered&&(this.Co=window.Math.max(10-c.leftBuffer,0),this.lo=window.Math.max(10-c.rightBuffer,0)),(0,D.Qe)(b)?(this.Fi=this.Bh-this.lo,this.Nk=this.jh+this.Co):(this.Fi=this.jh+this.Co,this.Nk=this.Bh-this.lo)):(this.Fi=this.jh,this.Nk=this.Bh);this.Hh=c.tickLabel!=D.q?c.tickLabel.converter:D.q;this.Bfa=c._isoConverter;this.At=c.groups;this.Yh=c.dataMin;this.Ah=c.dataMax;
this.tr=0<this.At.length?(this.Ah-this.Yh)/(this.At.length-1):0;this.Zt=c.step;b=0<c.endGroupOffset?c.endGroupOffset*this.tr:0;d=0<c.startGroupOffset?c.startGroupOffset*this.tr:0;this.xf=c.min!=D.q?c.min:this.Yh-d;this.Kf=c.max!=D.q?c.max:this.Ah+b;this.Gc=c.viewportMin==D.q?this.xf:c.viewportMin;this.Md=c.viewportMax==D.q?this.Kf:c.viewportMax;c.viewportStartGroup!=D.q&&(this.Gc=c.viewportStartGroup-d);c.viewportEndGroup!=D.q&&(this.Md=c.viewportEndGroup+b);this.mja=0;this.q4=this.Md-this.Gc;this.wS=
this.WB=this.cga=this.Sv=D.q;this.p1=D.n;c=new D.Pn;this.Gm=[(0,D.wg)(c,"MONTH_SHORT_JANUARY",D.q),(0,D.wg)(c,"MONTH_SHORT_FEBRUARY",D.q),(0,D.wg)(c,"MONTH_SHORT_MARCH",D.q),(0,D.wg)(c,"MONTH_SHORT_APRIL",D.q),(0,D.wg)(c,"MONTH_SHORT_MAY",D.q),(0,D.wg)(c,"MONTH_SHORT_JUNE",D.q),(0,D.wg)(c,"MONTH_SHORT_JULY",D.q),(0,D.wg)(c,"MONTH_SHORT_AUGUST",D.q),(0,D.wg)(c,"MONTH_SHORT_SEPTEMBER",D.q),(0,D.wg)(c,"MONTH_SHORT_OCTOBER",D.q),(0,D.wg)(c,"MONTH_SHORT_NOVEMBER",D.q),(0,D.wg)(c,"MONTH_SHORT_DECEMBER",
D.q)]};
D.zx=function(b,c,d){var e=D.q,f=D.q,g="left"==b.md||"right"==b.md;if(b.Hh&&b.Hh.getAsString)e=b.Hh.getAsString(c);else if(b.Hh&&b.Hh.format)e=b.Hh.format(b.Bfa?b.Bfa(c):c);else if(31536E6<=b.Zt)e=(0,D.xx)(b,c,D.t,D.t,D.n);else if(31536E6<=b.q4||24192E5<=b.Zt){if(d==D.q||d.getMonth()!=c.getMonth())e=(0,D.xx)(b,c,D.t,D.n,D.t);if(d==D.q||d.getYear()!=c.getYear())f=(0,D.xx)(b,c,D.t,D.t,D.n)}else if(24192E5<=b.q4||864E5<=b.Zt){if(d==D.q||d.getDate()!=c.getDate())e=(0,D.xx)(b,c,D.n,D.t,D.t);d==D.q||d.getYear()!=
c.getYear()?f=(0,D.xx)(b,c,D.t,D.n,D.n):d.getMonth()!=c.getMonth()&&(f=(0,D.xx)(b,c,D.t,D.n,D.t))}else{if(36E5<=b.q4||6E4<=b.Zt){if(d==D.q||d.getHours()!=c.getHours()||d.getMinutes()!=c.getMinutes())e=(0,D.yx)(b,c,D.t)}else if(d==D.q||d.getSeconds()!=c.getSeconds())e=(0,D.yx)(b,c,D.n);if(g){if(d==D.q||d.getDate()!=c.getDate())f=(0,D.xx)(b,c,D.n,D.n,D.t)}else d==D.q||d.getYear()!=c.getYear()?f=(0,D.xx)(b,c,D.n,D.n,D.n):d.getMonth()!=c.getMonth()?f=(0,D.xx)(b,c,D.n,D.n,D.t):d.getDate()!=c.getDate()&&
(f=(0,D.xx)(b,c,D.n,D.t,D.t))}return[e,f]};D.xx=function(b,c,d,e,f){var g=c.getFullYear(),h;h=b.Gm&&12<=b.Gm.length?b.Gm[c.getMonth()]:c.toString().split(" ")[1];c=c.getDate();if(b.Gm&&17<b.Gm.length){var j=b.Gm[17],g=g+b.Gm[16];c+=j}j="DMY";b.Gm&&15<b.Gm.length&&(j=b.Gm[15]);b="";for(var m=0;m<j.length;m++)d&&"D"==j[m]?b+=c+" ":e&&"M"==j[m]?b+=h+" ":f&&"Y"==j[m]&&(b+=g+" ");return 0<b.length?b.slice(0,b.length-1):b};
D.yx=function(b,c,d){var e=c.getHours(),f=c.getMinutes();c=c.getSeconds();var g="",h="",j=D.t;b.Gm!=D.q&&14<b.Gm&&(g=b.Gm[window.DvtTimeAxis.aHa],h=b.Gm[window.DvtTimeAxis.vHa],j="t"==b.Gm[14]);b=""!=g&&""!=h;var m;b&&(m=h,12<e?(e-=12,m=h):0==e?(m=g,e=12):12>e&&(m=g));e=(10>e?"0"+e:""+e)+":"+(10>f?"0"+f:""+f);d&&(e+=":"+(10>c?"0"+c:""+c));return b?j?m+" "+e:e+" "+m:e};
D.Ax=function(b,c,d){var e=(new window.Date((new window.Date(b)).getFullYear(),0,1,0,0,0)).getTime();b=e+window.Math.ceil((b-e)/d)*d;for(e=[];b<=c;)e.push(b),b+=d;return e};D.C=D.wx.prototype;
D.C.L0=function(b){var c=[],d=[],e=[],f=[],g=D.q,h=0,j=0,j=b.Jc,m=(0,D.Qe)(b),o="left"==this.md||"right"==this.md,p="off"!=this.N.zoomAndScroll;if(p)var r=D.n;var u=0;o&&(0,D.kt)()&&(u=0.2*(0,window.parseInt)(this.N.tickLabel.style.v("font-size")));var v=[],h=0;this.Zt!=D.q?v=(0,D.Ax)(this.Gc,this.Md,this.Zt):"mixedFrequency"==this.N.timeAxisType?(this.Zt=316224E5<=this.tr?316224E5:26784E5<=this.tr?26784E5:864E5<=this.tr?864E5:36E5<=this.tr?36E5:6E4<=this.tr?6E4:1E3,v=(0,D.Ax)(this.Gc,this.Md,this.Zt),
h=window.Math.floor(this.tr/this.Zt)-1):(v=this.At,this.Zt=this.tr);for(var z=0;z<v.length;z++){window.time=v[z];var A=this.ak(window.time);if(A!=D.q){var F=new window.Date(window.time+this.mja),E=(0,D.zx)(this,F,g),g=E[0],E=E[1];g!=D.q?(E!=D.q?c.push(this.Cp(b,g,A+u)):c.push(this.Cp(b,g,A)),e.push(A)):(c.push(D.q),e.push(D.q));p&&r&&(A=this.Gc?this.ak(this.Gc):A,r=D.t);E!=D.q?(g=D.q,g=E!=D.q?this.Cp(b,E,A-u):this.Cp(b,E,A),f.push(A),o||(m?g.ni():g.Tk()),d.push(g),this.p1=D.t):(d.push(D.q),f.push(D.q));
g=F}}b=c;m=(0,D.qx)(c,j);u=h;h=[];for(r=0;r<m.length;r++)m[r]!=D.q&&h.push(m[r]);m=u;for(r=(0,D.px)(this,h,m);r;)m++,r=(0,D.px)(this,h,m);h=h.length;if(0<m)for(r=u=0;r<b.length;r++)b[r]!=D.q&&(0!=u%(m+1)&&(b[r]=D.q,h--),u++);b=d;j=(0,D.qx)(d,j);if(!j||0>=j.length)j=D.t;else{for(var r="left"==this.md||"right"==this.md,m=(0,window.parseInt)(this.N.tickLabel.style.v("font-size")),m=r?0.1*m:0.3*m,u=0,J,M,A=0;A<j.length;A++)j[A]!=D.q&&(r?(v=j[A].y,z=j[A].y+j[A].j):(v=j[A].x,z=j[A].x+j[A].g),J!=D.q&&(M!=
D.q&&(v>=J&&v-m<M||v<J&&z+m>J))&&(b[A]=D.q),b[A]!=D.q&&(J=v,M=z,u++));j=u}if(!p&&1<j&&h<=1.5*j){c=d;d=D.q;for(p=0;p<c.length;p++)c[p]!=D.q&&c[p].Re()}if(o&&d!=D.q){var o=c,p=d,L=0.1*(0,window.parseInt)(this.N.tickLabel.style.v("font-size"));J=function(b,c){return c.y>=b.y&&c.y-L<b.y+b.j||c.y<b.y&&c.y+c.j+L>b.y?D.n:D.t};j=D.q;b=D.t;for(M=0;M<o.length;M++)if(o[M]&&p[M])if(o[M].lp(),p[M].ww(),j&&J(j,o[M].Rb())){b=D.n;break}else if(o[M+1]&&J(o[M].Rb(),o[M+1].Rb())){b=D.n;break}else j=p[M].Rb();else if(o[M]||
p[M])if(r=o[M]?o[M]:p[M],j&&J(j,r.Rb())){b=D.n;break}else j=r.Rb();if(b){r=b=j=D.q;for(M=0;M<o.length;M++)p[M]?(o[M]=D.q,p[M].Ae(),h=p[M].Rb(),b&&J(b,h)&&(o[j]=D.q),r=h):o[M]&&(h=o[M].Rb(),r&&J(r,h)?o[M]=D.q:(b=h,j=M))}}this.Sv=c;this.cga=d;this.WB=e;this.wS=f};D.C.Jw=function(b,c){if(c&&1<c)return D.q;this.Sv||this.L0(b);return 1==c?this.cga:this.Sv};D.C.oH=function(b){var c=this.N.axisLine;return"on"==c.rendered?(c=new D.ff(c.lineColor,1,c.lineWidth),(0,D.rx)(this,b,c,10)):D.q};
D.C.Hz=function(b){var c=this.N.majorTick;if("on"!=c.rendered)return[];var d=[];if(this.p1)for(var e=0;e<this.WB.length;e++)this.WB[e]!=D.q&&this.Sv[e]!=D.q&&d.push(this.WB[e]);else for(e=0;e<this.wS.length;e++)this.wS[e]!=D.q&&d.push(this.wS[e]);var f=new D.ff(c.lineColor,1,c.lineWidth);c.lineStyle&&f.V((0,D.dn)(c.lineStyle));c=[];for(e=0;e<d.length;e++)d[e]>=this.Fi&&d[e]<=this.Nk&&c.push((0,D.rx)(this,b,f,d[e]));return c};
D.C.YC=function(b){var c=this.N.minorTick;if("on"!=c.rendered||this.p1)return[];for(var d=[],e=0;e<this.WB.length;e++)this.WB[e]!=D.q&&this.Sv[e]!=D.q&&d.push(this.WB[e]);var f=new D.ff(c.lineColor,1,c.lineWidth);c.lineStyle&&f.V((0,D.dn)(c.lineStyle));c=[];for(e=0;e<d.length;e++)d[e]>=this.Fi&&d[e]<=this.Nk&&c.push((0,D.rx)(this,b,f,d[e]));return c};D.C.ak=function(b){return b<this.Gc||b>this.Md?D.q:this.bd(b)};
D.C.OC=function(b){var c=window.Math.min(this.Fi,this.Nk),d=window.Math.max(this.Fi,this.Nk);b<c?b=c:b>d&&(b=d);return this.Rn(b)};D.C.NC=function(b){b<this.Gc?b=this.Gc:b>this.Md&&(b=this.Md);return this.bd(b)};D.C.Rn=function(b){return this.Gc+(b-this.Fi)/(this.Nk-this.Fi)*(this.Md-this.Gc)};D.C.bd=function(b){return this.Fi+(b-this.Gc)/(this.Md-this.Gc)*(this.Nk-this.Fi)};D.C.OU=function(){return window.Math.abs(this.bd(this.Gc+this.tr)-this.bd(this.Gc))};D.C.Kw=(0,D.B)("tr");
D.C.iV=function(){return("top"==this.md||"bottom"==this.md)&&(0,D.Qe)(this.e)?this.lo:this.Co};D.C.LU=function(){return("top"==this.md||"bottom"==this.md)&&(0,D.Qe)(this.e)?this.Co:this.lo};
});