define(['./DvtToolkit', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.aG=(0,D.w)();(0,D.qa)("DvtBaseTreeView",D.aG);D.D.l(D.aG,D.Rx,"DvtBaseTreeView");D.C=D.aG.prototype;D.C.Init=function(b,c,d){D.aG.q.Init.call(this,b,c,d);this.Aa=this.bE(this,b,this.Xa,this);this.Aa.rf(this);this.Hk=new D.Gq(b);this.u0=new D.rl(this);(0,D.cr)(this.Aa,this.Hk);this.WX=this.Ba=D.q;this.Vea=D.t;this.sL=D.q};
D.C.L=function(b,c,d){this.ub=c;this.Lb=d;this.Aa&&this.Aa.tc();this.bn&&!b&&(b=this.WX);b&&(this.WX=b);b&&(c=this.Uu(b),this.xI(c));d=new D.H(0,0,this.ub,this.Lb);this.uo(d);c=new D.Q(this.e);this.k(c);this.l4&&(this.EZ=new D.pr(this.e,this.Aa),this.EZ.vG=D.n);this.xi(c,d);this.bn&&(this.GW=D.n,this.bn.stop());var e=new D.H(0,0,this.ub,this.Lb);d=D.t;if(this.fa){if(this.vI&&b)if(D.ap.isSupported(this.vI))this.bn=D.ap.Dz(this.e,this.vI,this.fa,c,e,this.XD),d=D.n;else if(this.BL&&"auto"==this.vI){this.ej=
this.qX();this.k(this.ej);var e=new D.Tl(this.e,this.ej),f=this.BL,g=this.Pa,h=this.OS,j=this.Yx;e.GJ=D.t;e.BL=f;e.OS=h;(0,D.Vl)(j,f)||(0,D.Vl)(h,g)?(e.GJ=D.n,h=(0,D.cm)(f),j=(0,D.cm)(g),h.push(f),j.push(g),(0,D.hm)(e,h,j)):(0,D.hm)(e,[f],[g]);this.bn=e.Gq()}}else this.bn=this.sX(c,e);this.OS=this.BL=D.q;this.bn&&(this.Aa.zs(this),this.bn.xd(this.vo,this),this.bn.play());d?this.Pk=this.fa:this.fa&&this.removeChild(this.fa);this.fa=c;b?(this.nG(),(0,D.bG)(this,!this.bn)):this.HY()};D.C.Uu=(0,D.ca)(D.q);
D.C.uo=(0,D.w)();D.C.xi=(0,D.w)();D.cG=function(b,c){var d=new D.af(b.e,0,0,b.ub,b.Lb);(0,D.Yg)(d);c.k(d)};D.dG=function(b,c){if(b.Yx&&0<b.Yx.length){var d=b.Pa?b.Pa.Eg():D.q;b.xl&&(0,D.rs)(b.Aa,b.xl.Sc());b.xl=D.Fl.L(b,c,b.Yx,d);(0,D.ss)(b.Aa,b.xl.Sc())}else b.xl&&(0,D.rs)(b.Aa,b.xl.Sc()),b.xl=D.q};D.eG=function(b,c){var d=D.q;if(b.bga&&b.PZ)for(var e=0;e<b.PZ.length;e++){var f=b.PZ[e];if(f.id==b.bga){d=f.fu;break}}if(b.Uia||b.bda||d)b.Ba=D.Il.L(b,c,b.rh.legendSize,b.rh.legendColor,b.Uia,b.bda,d)};
D.fG=function(b,c){if(b.Up){var d=new D.ph(b.e,b.Up,b.ub/2,b.Lb/2);d.Re();d.Ae();D.Kl.Ub(d,b.ub-4,b.Lb-4,b);c.k(d)}};D.gG=function(b){return b.Pa&&0<b.Pa.sc()};D.C=D.aG.prototype;D.C.sX=function(b,c){return D.ap.isSupported(this.FW)?D.ap.vH(this.e,this.FW,b,c,this.XD):D.q};D.C.vo=function(){this.ej&&(this.removeChild(this.ej),this.ej=D.q);this.Pk&&(this.removeChild(this.Pk),this.Pk=D.q);this.GW=D.t;this.bn=D.q;this.Aa.rf(this);(0,D.bG)(this,D.n)};D.C.qX=function(){return new D.Q(this.e)};D.C.wx=function(b){return new D.Yl(b)};
D.C.bE=function(b,c,d,e){return new D.sm(b,c,d,e)};D.C.a$=(0,D.aa)();D.C.Ua=(0,D.B)("Aa");D.hG=function(b,c){var d=c,e=b.jb();if(e)for(var f=0;f<e.length;f++)var g=(0,D.hG)(e[f],c+1),d=window.Math.max(d,g);return d};
D.aG.prototype.xI=function(b){this.BL=this.Pa;this.OS=this.Yx;this.Gl=b.NFa;this.rh=b.wna?b.wna:{};this.Pa=b.root;this.Up=b.v5;this.Yx=b.EAa;this.zIa=new D.gf(b.CBa,b.DBa);this.AIa=new D.ff(b.BBa);this.FW=b.R4;this.vI=b.HAa;this.XD=b.FAa;this.tP=b.SGa;this.Jn=b.VGa;this.bha=b.bna;b.D8&&(this.l4=b.D8);this.bha?(this.Nb=new D.nr(b.bna),this.LB=b.yGa):this.Nb=D.q;this.Aa.kA(this.Nb);this.Aa.vx=b.a5;(0,D.yr)(this.Aa,this.wx(this.Aa));this.Pa&&(this.iq=(0,D.hG)(this.Pa,0));this.PZ=b.fu;this.bga=b.vFa;
this.Uia=b.QGa;this.bda=b.XAa};D.aG.prototype.HY=function(){for(var b=this.Nb?this.Nb.getSelection():[],c=0;c<b.length;c++)b[c].Ob(D.n)};D.aG.prototype.nG=function(){if(this.Nb&&this.LB){var b=[];(0,D.iG)(this,this.Pa,b);(0,D.vs)(this.Nb,this.LB,b);this.LB=D.q}};D.bG=function(b,c){var d=D.q,e=b.sL;e&&(d=(0,D.gm)(b.Pa,e),b.Aa.Cs(d));c&&(b.sL=D.q);d||(d=b.a$(b.Pa),b.Aa.Cs(d));c&&b.wp(b.tV())};D.aG.prototype.wp=function(b){this.Vea=b;this.Aa.wp(b)};D.aG.prototype.tV=(0,D.B)("Vea");
D.iG=function(b,c,d){if(c&&(d.push(c),c=c.jb()))for(var e=0;e<c.length;e++)(0,D.iG)(b,c[e],d)};D.aG.prototype.CE=function(b){return this.Nb?b[0]:D.q};D.aG.prototype.Wx=function(b){b.Na()||(this.Nb.Yi(b,D.t),this.Aa.Eq());b=[];for(var c=this.Nb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b};D.aG.prototype.Vx=function(){for(var b=[],c=this.Nb.getSelection(),d=0;d<c.length;d++)b.push(c[d].FP());return b};D.aG.prototype.$sa=function(b){b instanceof D.gt&&(0,D.um)(this,b.getId(),D.t)};
D.um=function(b,c,d){d&&b.Pa&&c==b.Pa.getId()&&b.Yx&&0<b.Yx.length?(b.sL=c,b.Xa(new D.jG(b.Yx[0].id))):d||b.Xa(new D.jG(c));b.e.Vd().tc()};D.aG.prototype.j6=function(b){return this.Aa.na(b)};D.aG.prototype.Kc=function(){this.Mg||(this.Mg=new D.Pn);return this.Mg};D.aG.prototype.Li=function(){return new D.Nl(this)};D.aG.prototype.getAutomation=D.aG.prototype.Li;
D.aG.prototype.Fj=function(b,c,d){return this.Hk.Fj(d)};D.aG.prototype.Zk=function(b,c){return this.Hk.Zk(b,c)};

D.Tl=function(b,c){this.Init(b,c)};D.D.l(D.Tl,D.Ul,"DvtBaseTreeAnimationHandler");D.Vl=function(b,c){if(!c||!b)return D.t;for(var d=0;d<b.length;d++)if(b[d].id==c.getId())return D.n;return D.t};
D.rl=(0,D.ba)("I");D.D.l(D.rl,D.sl,"DvtBaseTreeDropTarget");
D.sm=function(b,c,d,e){this.Init(c,d,e);this.I=b};D.D.l(D.sm,D.tm,"DvtBaseTreeEventManager");D.C=D.sm.prototype;D.C.wo=function(b){D.sm.q.wo.call(this,b);var c=this.na(b.target);c&&(b=b.shiftKey,c.Vq&&c.Vq()&&(0,D.um)(this.I,c.getId(),b))};D.C.hh=function(b){D.sm.q.hh.call(this,b);b=this.na(b.target);(0,D.vm)(this,b)};D.C.xo=function(b){D.sm.q.xo.call(this,b);(b=this.na(b.target))&&b.Rw&&b.Rw()};
D.C.pk=function(b){D.sm.q.pk.call(this,b);var c=this.na(b.target);c&&c.Sq&&(b=this.na(b.relatedTarget),(b&&b.getId?b.getId():D.q)!=c.getId()&&c.Sq())};D.C.hm=function(b){var c=D.t,c=this.Be();13==b.keyCode&&!b.ctrlKey?(c=this.Be(),c.Vq&&c.Vq()&&(b.shiftKey&&(c=this.I.Pa),(0,D.um)(this.I,c.getId(),b.shiftKey)),b.preventDefault(),c=D.n):c=D.sm.q.hm.call(this,b);return c};
D.C.Qu=function(b){b=this.na(b.target);(0,D.vm)(this,b);this.kK&&this.kK!=b&&(this.kK.Sq(),this.kK=D.q);b&&b instanceof D.Pl&&this.kK!=b&&(this.kK=b,b.Rw())};D.C.zA=function(b){(b=this.na(b.target))&&b.Vq&&b.Vq()&&(0,D.um)(this.I,b.getId(),D.t)};D.vm=function(b,c){c&&(c instanceof D.Ml&&c.ey)&&(0,D.um)(b.I,c.getId(),D.t)};
D.tl=(0,D.w)();D.D.l(D.tl,D.D,"DvtBaseTreeParser");D.C=D.tl.prototype;D.C.Init=function(b){this.I=b;this.Zo=new D.ul;this.b2=window.Infinity;this.V1=-window.Infinity};
D.C.parse=function(b){b=b.replace(/&Oslash;/gi,"\u00f8");var c=this.Zo.parse(b);b=this.gm(c);var c=c.jb(),d;d=(0,D.vl)(c,"f");var e=d.length;if(0<e){for(var f,g,h={},j=0;j<e;j++)f=d[j],g=f.o("name"),h[g]=D.I.fl(f);d=h}else d=D.q;b.D8=d;this.Gl=0;f=(0,D.vl)(c,"n");e=[];for(d=0;d<f.length;d++)(g=this.lG(f[d],b.D8))&&e.push(g);b.NFa=this.Gl;if(1==e.length)d=e[0];else{d=this.I;for(g=f=0;g<e.length;g++)f+=e[g].sc();d=this.dn(d,{size:f,MAa:D.n,kka:D.n});(0,D.wl)(d,e)}b.root=d;for(d=0;d<c.length;d++)if(e=
c[d],f=b,e)if(g=e.getName(),"spb"==g)e=this.Y2(e,f),f.Fna||(f.Fna=[]),f.Fna.push(e);else if("menus"==g)f.a5||(f.a5=new D.xl(this.I.e)),f.a5.add(e);else if("ag"==g){j=e;e=f;h=D.k;f=j.o("id");g=j.o("T");if("continuous"==j.o("t")){var h=j.o("minValue"),m=j.o("maxValue"),o=j.o("minLabel"),p=j.o("maxLabel"),j=j.o("ramp").split(";");h==D.q&&(h=this.b2);m==D.q&&(m=this.V1);h=new D.yl(h,m,o,p,j)}else{h=new D.zl;j=j.jb();for(m=0;m<j.length;m++){var r=j[m];r&&(o=r.o("g"),p=r.o("l"),r={color:r.o("c"),pattern:r.o("p")},
h.add(o,p,r))}}e.fu||(e.fu=[]);e.fu.push({fu:h,C8:g,id:f})}else if("styles"==g)f.VGa=this.Z2(e,f);else if("a"==g){g=[];e=e.jb();for(h=0;h<e.length;h++)j=e[h].o("id"),m=e[h].o("l"),g.push({id:j,text:m});f.EAa=g}else if("resources"==g){g={};e=e.getAttributes();for(h=0;h<e.length;h++)g[e[h].name]=e[h].value;f.wna=g}this.Fo(b.root,b);return b};D.C.dn=(0,D.ca)(D.q);
D.C.gm=function(b){var c={},d=b.o("sel");c.bna="none"==d?D.q:"single"==d?"s":"m";c.SGa=b.o("sort");if(d=b.o("selIds"))c.yGa=d.split(",");c.v5=b.o("emptyText");c.vFa=b.o("ls");c.QGa=b.o("sv");c.XAa=b.o("cv");if(d=b.o("adu"))c.FAa=d/1E3;c.HAa=b.o("adc");c.R4=b.o("adi");return c};
D.C.Vu=function(b){var c={};c.C8=b.o("T");c.LFa=b.o("M");c.iU=b.o("ag");c.id=b.o("id");c.size=(0,window.Number)(b.o("s"));c.color=b.o("c");c.pattern=b.o("p");c.label=b.o("l");c.YGa=b.o("tt");c.CV=b.o("ld");c.ABa=b.o("d");c.kka="t"==b.o("di")?D.n:D.t;c.xGa=b.o("nsel");var d=b.o("tn");d&&(c.Kna=d);if(b=b.o("ls"))c.xu=new D.K(b);c.iU!=D.q&&(this.V1=window.Math.max(this.V1,c.iU),this.b2=window.Math.min(this.b2,c.iU));return c};
D.C.lG=function(b,c){if(!b||"n"!=b.getName())return D.q;this.Gl++;var d=this.Vu(b),d=this.dn(this.I,d,c);(0,D.wl)(d,this.dT(b,d,c));return d};D.C.dT=function(b,c,d){var e=[];b=b.jb();for(var f=0;f<b.length;f++){var g=b[f];g&&("el"==g.getName()?d&&c.Maa&&c.Maa((0,D.Al)(g)):c.eb()&&e.push(this.lG(g,d)))}return e};D.C.Y2=function(b,c){var d=(0,D.Bl)(b),e=b.o("T");c.rI||(c.rI={});c.rI[e]||(c.rI[e]=[]);c.rI[e].push(d)};
D.C.Fo=function(b,c){if(b){var d=b.dp;if(c.rI){var e=c.rI[d];e&&b.x8(e)}if(c.fu)for(var f=0;f<c.fu.length;f++)if(e=c.fu[f],e.C8==d){if(e.fu instanceof D.yl&&(d=b,e=e.fu.get(d.qta)))d.Ng=e;break}if(d=b.jb())for(e=0;e<d.length;e++)this.Fo(d[e],c)}};D.vl=function(b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];f&&f.getName()==c&&d.push(f)}return d};
D.tl.prototype.Z2=function(b,c){var d={},e=new D.K(b.o("top"));d.BACKGROUND_STYLE=e;d.ANIMATION_UPDATE_COLOR_STYLE=e.v("-tr-animation-update-color");e=new D.K(b.o("node"));d.LABEL_TEXT_DEFAULT_STYLE=e;var f=e.clone().Cb(new D.K(b.o("node-hover"))),g=e.clone().Cb(new D.K(b.o("node-selected")));c.CBa=b.o("dsf");c.BBa=b.o("dsb");c.DBa=b.o("dso");this.kY(e,f,g,d);this.paa(b,d);e=new D.K(b.o("rootText"));d.TEXT_STYLE=e;e=new D.K(b.o("attrType"));d.ATTRIBUTE_TYPE_STYLE=e;e=new D.K(b.o("attrValue"));d.ATTRIBUTE_VALUE_STYLE=
e;e=new D.K(b.o("drillText"));d.DRILL_TEXT_STYLE=e;e=new D.K(b.o("currentText"));d.CURRENT_TEXT_STYLE=e;return d};D.tl.prototype.kY=(0,D.w)();D.tl.prototype.paa=(0,D.w)();
D.Pl=(0,D.w)();D.D.l(D.Pl,D.D,"DvtBaseTreeNode");D.am=new D.$l("#000000",2,5,5,45,0.5);
D.Pl.prototype.Init=function(b,c,d){this.I=b;this.dp=c.C8;this.a2=c.LFa;this.qta=c.iU;this.Oa=c.id;this.Yj=c.size;this.Ng=c.color?c.color:"#000000";this.$o=c.pattern;this.tz=c.label;this.zy=c.YGa;this.ym=c.xu;this.pR=c.ABa;this.sg=c.kka;this.OE=c.MAa;this.$s=1;this.tS=D.q;this.Wd=D.t;this.l4=d;c.Kna?(0,D.bm)(this,c.Kna):d&&d.content?(0,D.bm)(this,"content"):d&&d.rootContent&&(0,D.bm)(this,"rootContent");this.SI=D.t;this.jw=c.xGa;this.ed=b.Kc()};
D.wl=function(b,c){if(c!=D.q)for(var d=0;d<c.length;d++)c[d].pf=b;b.je=c};D.Pl.prototype.jb=(0,D.B)("je");D.cm=function(b){var c=[],d,e;if(!b.De())return c;for(var f=0;f<b.je.length;f++)e=b.je[f],d=(0,D.cm)(e),c.push(e),c=c.concat(d);return c};D.dm=function(b){var c=b.pf;c&&(c.tS=b)};D.Pl.prototype.lD=function(b){return!b||!this.pf?D.t:this.pf==b?D.n:this.pf.lD(b)};
D.em=function(b,c,d){var e=[];if(0>d)return e;if(0==d)return[b];if(c.De()){b=c.jb();for(var f=0;f<b.length;f++)c=b[f],e=e.concat((0,D.em)(c,c,d-1))}return e};D.fm=function(b){var c=[],d;if(!b.De())return[b];for(var e=0;e<b.je.length;e++)d=b.je[e],d=(0,D.fm)(d),c=c.concat(d);return c};D.gm=function(b,c){if(b.getId()==c)return b;for(var d=D.q,e=b.jb(),f=e.length,d=D.q,g=0;g<f;g++)if(d=e[g],d=(0,D.gm)(d,c))return d;return D.q};D.C=D.Pl.prototype;D.C.getId=(0,D.B)("Oa");D.C.sc=(0,D.B)("Yj");D.C.Hb=(0,D.B)("Ng");
D.C.gf=(0,D.B)("zy");D.C.zj=(0,D.B)("Ng");D.C.$=(0,D.B)("$s");D.C.B=function(b){this.$s=b;this.H&&this.H.B(this.$s)};D.C.eb=(0,D.B)("sg");D.C.Vq=function(){return"r"==this.pR||"ir"==this.pR};D.C.x8=(0,D.ba)("jd");D.C.Fd=(0,D.B)("jd");D.C.Cw=(0,D.B)("a2");D.C.L=(0,D.w)();D.C.Gu=function(b){var c=this.jb();if(c!=D.q)for(var d=0;d<c.length;d++)c[d].L(b)};D.C.Ef=function(){(0,D.dm)(this);return this};D.C.hf=function(){return new D.H(0,0,0,0)};D.C.Pm=(0,D.ca)(D.q);
D.C.bg=function(){this.Wd=D.n;this.Fc();this.Rw&&this.Rw()};D.C.Mc=function(){this.Wd&&(this.Wd=D.t,this.nc());this.Sq&&this.Sq()};D.C.Gg=(0,D.B)("Wd");D.C.Rw=function(){this.SI=D.n};D.C.Sq=function(){this.SI=D.t};D.C.dc=function(){return"off"!=this.jw&&this.I.bha!=D.q};D.C.Na=(0,D.B)("Rd");D.C.Ob=function(b){this.Rd=b;this.Oj()};D.C.Fc=(0,D.w)();D.C.nc=(0,D.w)();D.C.Fj=function(b){return this.I.CE(b)};D.C.Zk=function(){return this.I.Wx(this)};D.C.UC=function(){return this.I.Vx()};D.C.FP=(0,D.B)("H");
D.C.$C=(0,D.ca)(D.q);D.C.contains=(0,D.ca)(D.t);D.C.ml=function(){return[]};D.C.Ao=(0,D.w)();D.C.Wf=function(b,c){b.GJ||(0,D.hm)(b,c.jb(),this.jb());var d=c.ml(),e=this.ml(),f;if(!D.Kf.Xg(d,e)&&(f=new D.im(this.I.e,this,this.I.XD),(0,D.P)(f.R,"typeNumberArray",this,this.ml,this.Ao,e),b.add(f,1),e=this.Yj!=c.Yj,f=D.N.dV(this.Ng)!=D.N.dV(c.Ng),this.Ao(d),(d=(0,D.jm)(this,D.q,"ANIMATION_UPDATE_COLOR_STYLE"))&&(e||f)))this.Ng=d};
D.C.Ug=function(b){if(!b.GJ||!b.GJ||!(b.BL.getId()==this.getId()||(0,D.Vl)(b.OS,this))){this.B(0);var c=new D.km(this.I.e,this,this.I.XD);b.add(c,2);for(c=0;c<this.je.length;c++)this.je[c].Ug(b)}};D.C.oi=function(b,c){c.k(this.H);var d=new D.lm(this.I.e,this,this.I.XD);b.add(d,0);if(!b.GJ)for(d=0;d<this.je.length;d++)this.je[d].oi(b,c)};D.C.De=function(){return this.je!=D.q&&0<this.je.length};D.mm=function(b){var c=0;for(b=b.pf;b;)c++,b=b.pf;return c};
D.Pl.prototype.gE=function(){return this.$o?new D.nm(this.$o,this.Ng):new D.gf(this.Ng)};D.om=function(b){return b.$o?"#000000":D.N.Vk(b.Ng)};D.qm=function(b,c){var d=(0,D.om)(b);c.la(d);var e=[];e.push(b.I.Jn.LABEL_TEXT_DEFAULT_STYLE);b.ym&&e.push(b.ym);c.Ha((0,D.Gl)(e));D.pm===D.n&&c.la(d)};D.jm=function(b,c,d){(b=b.I.Jn[d])&&(c=b);return c};D.rm=function(b){var c=11;(b=b.I.Jn.LABEL_TEXT_DEFAULT_STYLE.uH())&&(c=(0,window.parseFloat)(b));return c};D.Pl.prototype.Da=(0,D.B)("H");
D.Pl.prototype.Eg=(0,D.B)("tz");D.Pl.prototype.Maa=function(b){b&&!this.nM&&(0,D.bm)(this,"content");this.gi=b};D.bm=function(b,c){c&&(b.nM=b.l4[c])};D.Pl.prototype.Fg=function(){return this.Vq()};D.Pl.prototype.Oj=(0,D.w)();
D.Ml=function(b,c,d,e,f){this.Init(d,e,f);this.wb=b;this.Oa=c;this.ey=D.t};D.D.l(D.Ml,D.Ll,"DvtBaseTreePeer");D.Ml.prototype.getId=(0,D.B)("Oa");D.Ml.prototype.oma=(0,D.B)("ey");D.Ml.prototype.q8=(0,D.ba)("ey");D.Ml.prototype.Sq=function(){this.wb&&this.wb.Sq&&this.wb.Sq()};
D.Fl=(0,D.w)();D.D.l(D.Fl,D.D,"DvtTreeBreadcrumbsRenderer");D.Fl.rra=6;D.Fl.Gra="color: #003286;";
D.Fl.L=function(b,c,d,e){var f=b.e,g=[];g.push(b.Jn.TEXT_STYLE);g.push(new D.K(D.Fl.Gra));g.push(b.Jn.DRILL_TEXT_STYLE);var g=(0,D.Gl)(g).toString(),h=g+"text-decoration: underline;",j=[];j.push(b.Jn.TEXT_STYLE);j.push(b.Jn.CURRENT_TEXT_STYLE);j=(0,D.Gl)(j).toString();f=new D.Hl(f,b.$sa,b,{xu:g,n7:h,m7:h,jka:j});b.k(f);d=d.slice(0).reverse();d.push({text:e});f.L({items:d},c.g);e=f.C();(0,D.jg)(f,c.x,c.y);e=e.j+D.Fl.rra;c.y+=e;c.j-=e;b.removeChild(f);return f};
D.Il=(0,D.w)();D.D.l(D.Il,D.D,"DvtTreeLegendRenderer");D.Il.Ora=4;D.Il.Xs=7;D.Il.CP=24;D.Il.Nra=11;D.Il.Aba="#636363";D.Il.KHa="color:"+D.Il.Aba+";";
D.Il.L=function(b,c,d,e,f,g,h){var j=b.e,m=b.Ua(),o=new D.Q(j);b.k(o);var p=D.Il.SL(j,b,o,c.g,d,e,f,g,h),r=b.rh.alta?D.q:"#000000",u=[];u.push(b.Jn.TEXT_STYLE);var u={borderColor:r,xu:(0,D.Gl)(u)},r=D.Jl.X7(j,m,o,c.g,c.j,h,u),v=p?p.C():D.q,z=r?r.C():D.q;if(p&&!r)p.F(c.y+(c.g-v.g)/2);else if(r&&!p)r.F(c.y+(c.g-z.g)/2);else if(r&&p){var A=c.g-D.Il.CP;v.g+z.g>A&&(v.g>A/2&&z.g>A/2?(o.removeChild(p),o.removeChild(r),p=D.Il.SL(j,b,o,A/2,d,e,f,g,h),r=D.Jl.X7(j,m,o,A/2,c.j,h,u)):v.g>z.g?(m=A-z.g,o.removeChild(p),
p=D.Il.SL(j,b,o,m,d,e,f,g,h)):(d=A-v.g,o.removeChild(r),r=D.Jl.X7(j,m,o,d,c.j,h,u)),v=p.C(),z=r.C());(0,D.Qe)(j)?(r.F(c.x),p.F(c.x+c.g-v.g)):(p.F(c.x),r.F(c.x+c.g-z.g))}h=o.C();o.O(c.y+c.j-h.j);c.j-=h.j+D.Il.Ora;b.removeChild(o);return o};
D.Il.SL=function(b,c,d,e,f,g,h,j){var m=(0,D.Qe)(b),o=c.Ua(),p=D.q;if(h||j){p=new D.Q(b);d.k(p);var r=[];r.push(c.Jn.TEXT_STYLE);r.push(c.Jn.ATTRIBUTE_TYPE_STYLE);d=(0,D.Gl)(r);r=[];r.push(c.Jn.TEXT_STYLE);r.push(c.Jn.ATTRIBUTE_VALUE_STYLE);var r=(0,D.Gl)(r),u,v,z,A;c=0;h&&(u=new D.ph(b,f,0,0),u.Ha(d),p.k(u),z=u.Rb().g,v=new D.ph(b,h,0,0),v.Ha(r),p.k(v),A=v.Rb().g,c=z+A+D.Il.Xs);var F,E,J,M;f=0;j&&(F=new D.ph(b,g,0,0),F.Ha(d),p.k(F),J=F.Rb().g,E=new D.ph(b,j,0,0),E.Ha(r),p.k(E),M=E.Rb().g,f=J+M+D.Il.Xs);
e-=D.Il.CP;c+f>e&&(b=e/2,c>b&&f>b?(D.Kl.Ub(v,b-z-D.Il.Xs,window.Infinity,p)?(A=v.Rb().g,o.ja(v,new D.Ll(h))):(p.removeChild(u),p.removeChild(v),v=D.q,A=0),D.Kl.Ub(E,b-J-D.Il.Xs,window.Infinity,p)?(M=E.Rb().g,o.ja(E,new D.Ll(j))):(p.removeChild(F),p.removeChild(E),E=D.q,M=0)):c>f?D.Kl.Ub(v,e-f-z-D.Il.Xs,window.Infinity,p)?(A=v.Rb().g,o.ja(v,new D.Ll(h))):(p.removeChild(u),p.removeChild(v),v=D.q,A=0):D.Kl.Ub(E,e-c-J-D.Il.Xs,window.Infinity,p)?(M=E.Rb().g,o.ja(E,new D.Ll(j))):(p.removeChild(F),p.removeChild(E),
E=D.q,M=0));e=0;m?(E&&(E.da(e),e+=M+D.Il.Xs,F.da(e),e+=J+D.Il.CP),v&&(v.da(e),e+=A+D.Il.Xs,u.da(e))):(v&&(u.da(e),e+=z+D.Il.Xs,v.da(e),e+=A+D.Il.CP),E&&(F.da(e),e+=J+D.Il.Xs,E.da(e)))}return p};
D.Yl=function(b){this.Init(b)};D.D.l(D.Yl,D.Zl,"DvtBaseTreeKeyboardHandler");D.Yl.prototype.RH=function(b){return this.Si(b)&&!b.ctrlKey};D.Yl.prototype.nD=function(b){return 32==b.keyCode&&b.ctrlKey};
D.Cl=(0,D.w)();D.D.l(D.Cl,D.Dl,"DvtBaseTreeDefaults");D.El={skin:"skyros",emptyText:"No data to display",nodeDefaults:{labelStyle:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},styleDefaults:{_attributeTypeTextStyle:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;")},_resources:{}};
D.Cl.prototype.Init=function(b){b={skyros:D.nl.Cb(b.skyros,D.El),alta:D.nl.Cb(b.alta,{})};D.Cl.q.Init.call(this,b)};
D.Wl=(0,D.w)();D.D.l(D.Wl,D.D,"DvtBaseTreeJsonUtils");
D.Wl.prototype.F8=function(b){var c;c="\x3c"+this.KO();c+=this.kJ(b);c+="\x3e\n";if(b&&b.nodes)for(var d=b.nodes,e=0;e<d.length;e++)c+=(0,D.Xl)(this,b,d[e]);d="\x3ca/\x3e\n"+this.eZ(b);d+=this.mJ(b);if(e=b.attributeGroups?b.attributeGroups[0]:D.q)if(b='\x3cag id\x3d"'+e.id+'"',"continuous"==e.attributeType)b+=this.Ea("t","continuous"),b+=this.Ea("ramp",e.colors.join(";")),b+=this.Ea("minValue",e.min),b+=this.Ea("maxValue",e.max),b+=this.Ea("minLabel",e.minLabel),b+=this.Ea("maxLabel",e.maxLabel),
b+="/\x3e";else{b+="\x3e\n";for(var e=e.groups,f=0;f<e.length;f++)b+="\x3ci",b+=this.Ea("g",e[f].id),b+=this.Ea("l",e[f].label),b+=this.Ea("c",e[f].color),b+=this.Ea("p",e[f].pattern),b+="/\x3e\n";b+="\x3c/ag\x3e\n"}else b="";d=d+b+("\x3c/"+this.KO()+"\x3e");return c+=d};D.Wl.prototype.Ea=function(b,c){return c!=D.q?" "+b+'\x3d"'+c+'"':""};D.Wl.prototype.KO=(0,D.ca)(D.q);
D.Wl.prototype.kJ=function(b){var c;c=""+this.Ea("sv",b.sizeLabel);c+=this.Ea("cv",b.colorLabel);var d=b.attributeGroups?b.attributeGroups[0]:D.q;d&&(c+=this.Ea("ls",d.id));for(var d=b.selection?b.selection:[],e="",f=0;f<d.length;f++)0<e.length&&(e+=","),e+=d[f];0<e.length&&(c+=this.Ea("selIds",e));c+=this.Ea("adu",b.animationDuration);c+=this.Ea("adc",b.animationOnDataChange);c+=this.Ea("emptyText",b.emptyText);c+=this.Ea("sel",b.selectionMode);return c+=this.Ea("sort",b.sorting)};
D.Xl=function(b,c,d){var e;e="\x3cn"+b.lJ(c,d);if(d&&d.nodes&&0<d.nodes.length){e+=b.Ea("di","t");e+="\x3e\n";d=d.nodes;for(var f=0;f<d.length;f++)e+=(0,D.Xl)(b,c,d[f]);e+="\x3c/n\x3e\n"}else e+="/\x3e\n";return e};
D.Wl.prototype.lJ=function(b,c){var d;d=""+this.Ea("id",c.id);d+=this.Ea("s",c.value);d+=this.Ea("c",c.color);d+=this.Ea("l",c.label);d+=this.Ea("p",c.pattern);d+=this.Ea("tt",c.shortDesc?c.shortDesc:c.tooltip);d+=this.Ea("ls",c.labelStyle?c.labelStyle:b.nodeDefaults.labelStyle);var e=c.drilling?c.drilling:b.nodeDefaults.drilling;"insert"==e?d+=this.Ea("d","i"):"replace"==e?d+=this.Ea("d","r"):"insertAndReplace"==e&&(d+=this.Ea("d","ir"));return d+=this.Ea("nsel",c.selectable?c.selectable:"auto")};
D.Wl.prototype.eZ=(0,D.w)();D.Wl.prototype.mJ=function(b){var c;c="\x3cstyles "+this.Ea("attrType",b.styleDefaults._attributeTypeTextStyle);return c+=this.Ea("attrValue",b.styleDefaults._attributeValueTextStyle)};
D.Nl=function(b){this.bAa=b;this.Pa=b.Pa};(0,D.qa)("DvtTreeAutomation",D.Nl);D.D.l(D.Nl,D.Ol,"DvtTreeAutomation");D.Nl.prototype.hr=function(b){var c=this.bAa.j6(b);if(!c)return D.q;if(c instanceof D.Pl){b="";if(!this.Pa.OE){if(c==this.Pa)return"node[0]";b+="[0]"}b=(c=this.CR(c,this.Pa.jb()))?b+c:b;if(0<b.length)return"node"+b}return D.q};D.Nl.prototype.CR=function(b,c){if(c&&0<c.length)for(var d=0;d<c.length;d++){if(c[d]==b)return"["+d+"]";var e=this.CR(b,c[d].jb());if(e)return"["+d+"]"+e}return D.q};
D.Nl.prototype.bk=function(b){return!this.Pa.OE&&(b=b.substring(0,b.indexOf("["))+b.substring(b.indexOf("]")+1),"node"==b)?this.Pa.FP().oa():(b=(0,D.Ql)(this,this.Pa,b))?b.Da().oa():D.q};D.Nl.prototype.getDomElementForSubId=D.Nl.prototype.bk;D.Ql=function(b,c,d){var e=d.indexOf("["),f=d.indexOf("]");if(0<=e&&0<=f)return e=d.substring(e+1,f),d=d.substring(f+1),f=d.indexOf("]"),0<=d.indexOf("[")&&0<=f?(0,D.Ql)(b,c.jb()[e],d):c.jb()[e]};
D.Rl=function(b,c,d){var e=d.shift();c=c.jb();return 0==d.length?c[e]:0<d.length?(0,D.Rl)(b,c[e],d):D.q};D.Nl.prototype.Ed=function(b){!this.Pa.OE&&0==b[0]&&b.shift();b=0==b.length?this.Pa:(0,D.Rl)(this,this.Pa,b);return{color:b.Hb(),label:b.Eg(),selected:b.Na()==D.k?D.t:b.Na(),size:b.sc(),tooltip:b.gf()}};D.Nl.prototype.getNode=D.Nl.prototype.Ed;
});