define(['./DvtToolkit', './DvtAxis'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.zH=(0,D.w)();(0,D.qa)("DvtGauge",D.zH);D.D.l(D.zH,D.Rx,"DvtGauge");D.zH.prototype.Init=function(b,c,d,e){D.zH.q.Init.call(this,b,c,d);this.ed=new D.jz;this.vca=e;this.vca||(this.sa=this.bE(),this.sa.rf(this),(0,D.wf)()||(0,D.yr)(this.sa,this.wx(this.sa)),this.setId("gauge1000"+window.Math.floor(1E9*window.Math.random())),this.lF=new D.af(b,0,0),(0,D.Yg)(this.lF),this.k(this.lF));this.VA=D.t;this.dG=D.q};
D.zH.prototype.be=function(b){this.N=b;(0,D.Gg)()||(this.N.animationOnDisplay="none",this.N.animationOnDataChange="none")};
D.zH.prototype.L=function(b,c,d){b?this.be(b):this.N||this.be(D.q);this.N.thresholds&&(this.N.thresholds=this.N.thresholds.sort(D.AH));!(0,window.isNaN)(c)&&!(0,window.isNaN)(d)&&(this.ub=c,this.Lb=d);d=this.Zu;this.Zu=[];c=new D.Q(this.e);this.Ia(c,0);this.xi(c,this.ub,this.Lb);var e=b!=D.q,f=this.ub,g=this.Lb;this.pb&&this.pb.stop();b=D.t;var h=this.VA?"none":this.za().animationOnDataChange,j=this.VA?"none":this.za().animationOnDisplay,m=this.za().animationDuration/1E3;if(j||h){f=new D.H(0,0,f,
g);g=this.e;if(!this.fa&&"none"!==j&&this.Zu[0]!=D.q)this.pb=D.ap.vH(g,j,c,f,m),this.pb||(this.pb=this.RW(this.Zu,j,m));else if(this.fa&&"none"!=h&&e&&this.Zu[0]!=D.q)if(this.pb=D.ap.Dz(g,h,this.fa,c,f,m))b=D.n;else{e=this.Zu;h=[];for(j=0;j<d.length;j++){var f=e[j],o=d[j].Zd(),g=f.Zd();f.oe(o);o=new D.im(this.e,f,m);(0,D.P)(o.R,"typeNumberArray",f,f.Zd,f.oe,g);h.push(o)}this.pb=new D.Zv(this.e,h)}b||this.removeChild(this.fa);this.pb&&(this.pb.play(),this.pb.xd(this.mC,this));b&&(this.Pk=this.fa);
this.fa=c}this.lF&&this.N.readOnly===D.t&&(this.lF.ha(this.ub),this.lF.ua(this.Lb));this.vca||(d=this.getParent()==this.e.Jc,b=D.Uy.mN(this),this.N.readOnly&&d?(this.e.If("img"),(0,D.BH)(this.e,b)):(c.If("img"),(0,D.gn)(c,"label",b),this.j3=this.j3!=D.q?this.j3+1:0,d=this.getId()+"_"+this.j3,c.setId(d),(0,D.vC)(this.e,c),(c=this.Ua())&&c.ja(this.lF,this.na(),D.n)))};D.zH.prototype.render=D.zH.prototype.L;D.C=D.zH.prototype;
D.C.na=function(){var b=D.Uy.mN(this),c=D.Vy.Hb(this);return new D.Ll(D.q,b,c)};D.C.xi=(0,D.w)();D.C.RW=(0,D.ca)(D.q);D.C.Pu=(0,D.ca)(D.q);D.C.mC=function(){this.Pk&&(this.removeChild(this.Pk),this.Pk=D.q);this.pb=D.q};D.C.sJ=(0,D.B)("ed");D.C.za=(0,D.B)("N");D.C.Ua=(0,D.B)("sa");D.C.JP=function(b,c){this.VA=D.n;this.dG=this.N.value;this.tJ(b,c)};D.C.tJ=function(b,c){this.N.value=D.Uy.hU(this.N,this.Pu(b,c));this.L();this.Xa(new D.dz(this.dG,this.N.value,D.t))};
D.C.IP=function(b,c){this.tJ(b,c);this.Xa(new D.dz(this.dG,this.N.value,D.n));this.VA=D.t;this.dG=D.q};D.C.bE=function(){return new D.mz(this)};D.AH=function(b,c){return b.max&&c.max?b.max-c.max:b.max?-window.Infinity:window.Infinity};D.zH.prototype.Li=function(){return new D.pz(this)};D.zH.prototype.getAutomation=D.zH.prototype.Li;D.zH.prototype.wx=function(b){return new D.cz(b,this)};
D.pz=(0,D.ba)("le");(0,D.qa)("DvtGaugeAutomation",D.pz);D.D.l(D.pz,D.Ol,"DvtGaugeAutomation");D.pz.prototype.getValue=function(){return this.le.za().value};D.pz.prototype.getValue=D.pz.prototype.getValue;D.pz.prototype.dDa=function(){return D.Uy.Lq(this.getValue(),this.le)};D.pz.prototype.getMetricLabel=D.pz.prototype.dDa;
D.jz=(0,D.w)();D.D.l(D.jz,D.kz,"DvtGaugeBundle");D.jz._defaults={EMPTY_TEXT:"No data to display"};D.jz.prototype.no=function(b){return D.jz._defaults[b]};D.jz.prototype.xx=(0,D.ca)("DvtGaugeBundle");
D.hz=(0,D.w)();D.D.l(D.hz,D.Dl,"DvtGaugeDefaults");D.vz={skin:"alta",color:"#393737",metricLabel:{style:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};D.wz={skin:"skyros",min:0,max:100,color:"#313842",borderColor:D.q,visualEffects:"auto",emptyText:D.q,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"off",scaling:"auto",style:new D.K,textType:"number"},__layout:{outerGap:1,labelGap:3}};
D.hz.prototype.Init=function(b){b={skyros:D.nl.Cb(b.skyros,D.wz),alta:D.nl.Cb(b.alta,D.vz)};D.hz.q.Init.call(this,b)};D.Xy=function(b){return"skyros"==b.za().skin};
D.Qy={};D.D.l(D.Qy,D.D,"DvtGaugeDataUtils");D.Qy.pu=function(b){b=b.za();return!b||(0,window.isNaN)(b.value)||b.value===D.q?D.t:D.n};D.Qy.fD=function(b,c){var d=b.za(),e=c?c:d.value,d=d.thresholds;if(!d)return-1;for(var f=0;f<d.length;f++)if(e<=d[f].max)return f;return d.length-1};D.Qy.EH=function(b,c){var d=b.za().thresholds;return d&&0<=c&&c<d.length?d[c]:D.q};D.Qy.WJa=function(b,c){var d=b.za().referenceLines;return d&&0<=c&&c<d.length?d[c]:D.q};
D.mz=function(b){this.Init(b.e,b.Xa,b);this.le=b;this.fk=D.t};D.D.l(D.mz,D.tm,"DvtGaugeEventManager");D.C=D.mz.prototype;D.C.ol=function(b){this.le.za().readOnly===D.t?(this.fk=D.n,this.tc(),b=(0,D.nz)(this,b.pageX,b.pageY),this.le.JP(b.x,b.y)):D.mz.q.ol.call(this,b)};D.C.hn=function(b){this.fk?(this.fk=D.t,b=(0,D.nz)(this,b.pageX,b.pageY),this.le.IP(b.x,b.y)):D.mz.q.hn.call(this,b)};
D.C.Ip=function(b){if(this.fk){var c=(0,D.nz)(this,b.pageX,b.pageY);this.le.tJ(c.x,c.y)}(this.R$()||!this.fk)&&D.mz.q.Ip.call(this,b)};D.C.R$=(0,D.ca)(D.t);
D.C.dJ=function(b){if(D.xz.we===b.type&&this.le.za().readOnly===D.t){this.fk=D.n;var c=(0,D.nz)(this,b.touches[0].pageX,b.touches[0].pageY);this.le.JP(c.x,c.y);b.preventDefault()}else D.xz.aj===b.type&&this.fk?(c=(0,D.nz)(this,b.touches[0].pageX,b.touches[0].pageY),this.le.tJ(c.x,c.y),b.preventDefault()):D.xz.Dh===b.type&&this.fk?(this.fk=D.t,c=(0,D.nz)(this,b.changedTouches[0].pageX,b.changedTouches[0].pageY),this.le.IP(c.x,c.y),b.preventDefault()):D.mz.q.dJ.call(this,b)};
D.nz=function(b,c,d){c=(0,D.Pg)(b.e,c,d);return b.le.Eb(c)};D.mz.prototype.Lx=(0,D.w)();
D.cz=function(b,c){this.Init(b,c)};D.D.l(D.cz,D.Zl,"DvtGaugeKeyboardHandler");D.cz.prototype.Init=function(b,c){D.cz.q.Init.call(this,b);this.le=c};
D.cz.prototype.$n=function(b){var c=b.keyCode,d=(0,D.Qe)(this.le.e);if(38==c||c==(d?37:39))c=this.le,c.N.readOnly||(d=c.N.value,c.N.value=c.N.step!=D.q?D.Uy.hU(c.N,c.N.value+c.N.step):window.Math.min(window.Math.max(c.N.value+(c.N.max-c.N.min)/100,c.N.min),c.N.max),c.L(),c.Xa(new D.dz(d,c.N.value,D.n))),b.preventDefault();else if(40==c||c==(d?39:37))c=this.le,c.N.readOnly||(d=c.N.value,c.N.value=c.N.step!=D.q?D.Uy.hU(c.N,c.N.value-c.N.step):window.Math.min(window.Math.max(c.N.value-(c.N.max-c.N.min)/
100,c.N.min),c.N.max),c.L(),c.Xa(new D.dz(d,c.N.value,D.n))),b.preventDefault()};
D.Vy={};D.D.l(D.Vy,D.D,"DvtGaugeStyleUtils");D.Vy.Mba=["#ed6647","#fad55c","#68c182"];D.Vy.Kba=["#D62800","#FFCF21","#84AE31"];D.Vy.Kba=["#D62800","#FFCF21","#84AE31"];D.Vy.ara={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:80,y:86,width:40,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};
D.Vy.bra={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};D.Vy.dra={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};
D.Vy.era={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:82,y:133,width:36,height:34},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:61,majorTickCount:6};D.Vy.fra={startAngle:195.5,angleExtent:210.8,anchorX:100,anchorY:100,metricLabelBounds:{x:84,y:135,width:32,height:35},indicatorLength:0.98,tickLabelHeight:20,tickLabelWidth:30,radius:63,majorTickCount:6};
D.Vy.hra={startAngle:207.6,angleExtent:235,anchorX:100,anchorY:95.8,metricLabelBounds:{x:83,y:125,width:34,height:40},indicatorLength:1.05,tickLabelHeight:20,tickLabelWidth:30,radius:64,majorTickCount:6};D.Vy.Qra={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:0.82,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};
D.Vy.Rra={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:70,width:41,height:39},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};D.Vy.Tra={startAngle:211,angleExtent:242,anchorX:100,anchorY:91.445,metricLabelBounds:{x:78,y:75,width:44,height:38},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};
D.Vy.sra={startAngle:220.5,angleExtent:261.5,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:0.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};D.Vy.tra={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:73,width:40,height:36},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};
D.Vy.vra={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:99.5,metricLabelBounds:{x:80,y:83,width:41,height:36},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};D.Vy.gra={anchorX:42,anchorY:510};D.Vy.cra={anchorX:187,anchorY:388};D.Vy.Sra={anchorX:227,anchorY:425};D.Vy.ura={anchorX:227,anchorY:425};
D.Vy.Hb=function(b){var c=b.za(),d=D.Qy.fD(b),e=D.Qy.EH(b,d);return e&&(!(b instanceof D.Wy)||b instanceof D.Wy&&"onIndicator"==c.thresholdDisplay)?D.Vy.kN(b,e,d):c.color};D.Vy.vh=function(b){var c=b.za(),d=D.Qy.EH(b,D.Qy.fD(b));return d&&d.borderColor&&(!(b instanceof D.Wy)||b instanceof D.Wy&&"onIndicator"==c.thresholdDisplay)?d.borderColor:c.borderColor};
D.Vy.zla=function(b){var c=b.za(),d=D.Qy.fD(b),e=D.Qy.EH(b,d);return e&&(!(b instanceof D.Wy)||b instanceof D.Wy&&"onIndicator"!=c.thresholdDisplay)?D.Vy.kN(b,e,d):c.plotArea.color};D.Vy.kN=function(b,c,d){if(c.color)return c.color;if(d<D.Vy.Mba.length)return(0,D.Xy)(b)?D.Vy.Kba[d]:D.Vy.Mba[d]};
D.Vy.yCa=function(b){return"rectangleAlta"===b?D.Vy.dra:"domeAlta"===b?D.Vy.bra:"circleAntique"===b?D.Vy.era:"rectangleAntique"===b?D.Vy.hra:"domeAntique"===b?D.Vy.fra:"circleLight"===b?D.Vy.Qra:"rectangleLight"===b?D.Vy.Tra:"domeLight"===b?D.Vy.Rra:"circleDark"===b?D.Vy.sra:"rectangleDark"===b?D.Vy.vra:"domeDark"===b?D.Vy.tra:D.Vy.ara};D.Vy.zCa=function(b){return"needleAntique"===b?D.Vy.gra:"needleLight"===b?D.Vy.Sra:"needleDark"===b?D.Vy.ura:D.Vy.cra};
D.Uy={};D.D.l(D.Uy,D.D,"DvtGaugeRenderer");D.Uy.kZ=2;D.Uy.uba=1;D.Uy.dA=function(b,c,d){var e=b.za(),f=e.emptyText;f||(f=(0,D.wg)(b.sJ(),"EMPTY_TEXT",D.q));var g=d.g-2*D.Uy.kZ,h=d.j-2*D.Uy.uba;d=new D.ph(b.e,f,d.x+d.g/2,d.y+d.j/2);e.metricLabel.style.v("font-size")||e.metricLabel.style.V("font-size","13px");d.Ha(e.metricLabel.style);d.Re();d.Ae();D.Kl.Ub(d,g,h,c)&&d.kg()&&b.Ua().ja(d,new D.Ll(f))};
D.Uy.Lq=function(b,c){var d=c.za(),e="percent"==d.metricLabel.textType;e&&(b=100*D.Uy.tH(d,d.min,b));var f=D.q;"on"==d.metricLabel.rendered&&d.metricLabel.converter&&(f=d.metricLabel.converter);var g=D.q;"on"==d.metricLabel.rendered&&d.metricLabel.scaling&&(g=d.metricLabel.scaling);return D.Uy.hea(b,c,f,g,d.metricLabel.autoPrecision?d.metricLabel.autoPrecision:"on",e)};
D.Uy.AU=function(b,c){var d=c.za(),e="percent"==d.tickLabel.textType;e&&(b=100*D.Uy.tH(d,d.min,b));var f=D.q;"on"==d.tickLabel.rendered&&d.tickLabel.converter&&(f=d.tickLabel.converter);var g=D.q;"on"==d.tickLabel.rendered&&d.tickLabel.scaling&&(g=d.tickLabel.scaling);return D.Uy.hea(b,c,f,g,d.tickLabel.autoPrecision?d.tickLabel.autoPrecision:"on",e)};
D.Uy.hea=function(b,c,d,e,f,g){var h=c.za();c=b;c=h.min;var h=h.max,j=h-c,m=D.q;(0,window.isNaN)(j)||(m=j/(1E3>j?100:1E3));e=new D.Jx(c,h,m,e,f);if(d&&d.getAsString)c=e.Fq(b,d);else{if(d&&d.format)return e.Fq(b,d);c=e.Fq(b)}return g?(0,window.String)(c)+"%":c};D.Uy.tH=function(b,c,d){b=(d-c)/(b.max-b.min);return b=window.Math.min(window.Math.max(0,b),1)};D.Uy.mN=function(b){var c=b.za(),d=D.Qy.EH(b,D.Qy.fD(b));return d&&d.shortDesc!=D.q?d.shortDesc:c.shortDesc!=D.q?c.shortDesc:D.Uy.Lq(c.value,b)};
D.Uy.Z7=function(b,c,d,e){var f=b.za();if("on"==f.metricLabel.rendered){var g=D.Uy.Lq(f.value,b),h=d.g,j=d.j;b=new D.ph(b.e,g,d.x+d.g/2,d.y+d.j/2);b.Ha(f.metricLabel.style);var m=f.metricLabel.style.v("font-size");if(!f.metricLabel.style.v("font-size")){var m=window.Math.max(f.max.toString().length,f.min.toString().length,g.length),o="";"percent"==f.metricLabel.textType&&(m=window.Math.max(3,g.length),o+="%");for(f=0;f<m;f++)o+="0";b.zd(o);m=b.Lw(d);b.zd(g);b.Jf(m)}b.Ae();b.Re();e!=D.q&&b.la(e);D.Kl.Ub(b,
h,j,c)&&b.ia(D.t)}};D.Uy.hU=function(b,c){var d=(0,window.Number)(b.step);if(d&&0<d){var e=(c-b.min)/d;return 0.5<e?window.Math.max(window.Math.min(b.max,window.Math.round(e)*d+b.min),b.min):b.min}return c};
D.yH=(0,D.w)();(0,D.qa)("DvtLedGauge",D.yH);D.D.l(D.yH,D.zH,"DvtLedGauge");D.Sy=function(b,c,d,e){var f=new D.yH;f.Init(b,c,d,e);return f};D.yH.newInstance=D.Sy;D.yH.prototype.Init=function(b,c,d,e){D.yH.q.Init.call(this,b,c,d,e);this.lf=new D.uz};D.yH.prototype.be=function(b){D.yH.q.be.call(this,this.lf.Vg(b));"auto"==this.N.animationOnDisplay&&(this.N.animationOnDisplay="zoom");"auto"==this.N.animationOnDataChange&&(this.N.animationOnDataChange="alphaFade");this.N.readOnly=D.n};
D.yH.prototype.xi=function(b,c,d){D.iz.L(this,b,c,d)};
D.uz=function(){this.Init({skyros:D.tz,alta:{}})};D.D.l(D.uz,D.hz,"DvtLedGaugeDefaults");D.tz={type:"circle"};
D.iz={};D.D.l(D.iz,D.D,"DvtLedGaugeRenderer");D.iz.THa=1/6;D.iz.Esa="M-42,36.6Q-50,36.6,-46.54,28.6L-4,-43.07Q0,-50,4,-43.07L46.54,28.6Q50,36.6,42,36.6Z";D.iz.zsa=[-50,36.6,0,-50,50,36.6];D.iz.Fsa=[-50,36.6,0,-50,50,36.6];D.iz.Jba=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,0.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-0.06,-47.59];D.iz.ysa=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.iz.Csa="M0,45L21,45Q24.414,44.414,25,41L25,10L42,10Q48.5,9.1,45,4L2,-38Q0,-39,-2,-38L-45,4Q-48.5,9.1,-42,10L-25,10L-25,41Q-24.414,44.414,-21,45Z";
D.iz.xsa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];D.iz.Dsa=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];
D.iz.L=function(b,c,d,e){if(D.Qy.pu(b)){var f=b.za(),g=f.__layout.outerGap,h=f&&(0<=f.size||1>f.size)?window.Math.sqrt(f.size):1;d=new D.H(g+(d-2*g)*(1-h)/2,g+(e-2*g)*(1-h)/2,(d-2*g)*h,(e-2*g)*h);D.iz.UL(b,c,d);D.iz.p3(b,c,d);"on"==f.metricLabel.rendered&&(D.pm!==D.n&&f.metricLabel.style.v("color")!=D.q?D.Uy.Z7(b,c,D.iz.zea(b,d),D.q):(e=D.N.Vk(D.Vy.Hb(b)),f.metricLabel.style.V("color",e),D.Uy.Z7(b,c,D.iz.zea(b,d),e)))}else D.Uy.dA(b,c,new D.H(0,0,d,e))};
D.iz.UL=function(b,c,d){var e=b.e,f=b.za(),g=f.type,h=D.Vy.Hb(b),j=D.Vy.vh(b),m=d.x+d.g/2,o=d.y+d.j/2,p=window.Math.min(d.g,d.j)/2,r=(0,D.Xy)(b),u,v=window.Math.min(d.g/100,d.j/100);"rectangle"==g?e=new D.af(e,d.x,d.y,d.g,d.j):"diamond"==g?e=new D.Lv(e,[m-p,o,m,o-p,m+p,o,m,o+p]):"star"==g||"triangle"==g||"arrow"==g?("star"==g?u=r?D.iz.Jba:D.iz.ysa:"triangle"==g?u=r?D.iz.Esa:D.iz.zsa:"arrow"==g&&(u=r?D.iz.Csa:D.iz.xsa),r&&"triangle"==g||r&&"arrow"==g?(u=window.DvtPathUtils.xW(u,d.x+d.g/2,d.y+d.j/2,
v,v),e=new D.ef(e,u)):(u=D.Fx.scale(u,v,v),u=D.Fx.translate(u,d.x+d.g/2,d.y+d.j/2),e=new D.Lv(e,u))):e=new D.Hv(e,m,o,p);r||"none"==f.visualEffects?e.la(h):(m=[D.N.Cg(h,-0.09,0.04),D.N.Cg(h,-0.04,-0.05)],o=f&&0==f.rotation%90?f.rotation:0,e.G(new D.cf("arrow"==g||"star"==g||"triangle"==g?o-90:270,m,[1,1],[0,1])));j&&e.La(j);j=b.Ua();(m=D.Uy.mN(b))&&j&&j.ja(e,new D.Ll(D.q,m,h));o=r?f.rotation+90:f.rotation;if(0!=o&&("arrow"==g||"triangle"==g))e=D.iz.v3(b,c,e,d);c.k(e)};
D.iz.v3=function(b,c,d,e){var f=b.za();b=new D.Q(b.e);c.k(b);b.k(d);c=f&&0==f.rotation%90?f.rotation:0;f=new D.rh;f.rotate(window.Math.PI*c/180);d.ra(f);c=b.C();d=e.x+e.g/2-(c.x+c.g/2);e=e.y+e.j/2-(c.y+c.j/2);c=new D.rh;c.translate(d,e);b.ra(c);return b};D.iz.p3=function(b,c,d){var e=b.za(),f=e.type;"none"!=e.visualEffects&&(0,D.Xy)(b)&&("rectangle"==f?D.iz.kza(b,c,d):"diamond"==f?D.iz.jza(b,c,d):"triangle"==f?D.iz.mza(b,c,d):"star"==f?D.iz.lza(b,c):"arrow"==f?D.iz.hza(b,c,d):D.iz.iza(b,c,d))};
D.iz.kza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.H(d.x+e,d.y+f,d.g-2*e,d.j-2*f);b=new D.af(b.e,d.x,d.y,d.g,d.j);b.ia(D.t);c.k(b);c=new D.cf(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.G(c)};
D.iz.jza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,f=new D.H(d.x+e,d.y+f,d.g-2*e,d.j-2*f);d=f.x+f.g/2;e=f.y+f.j/2;f=window.Math.min(f.g,f.j)/2;b=new D.Lv(b.e,[d-f,e,d,e-f,d+f,e,d,e+f]);b.ia(D.t);c.k(b);c=new D.cf(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[0.75,0.5,0.15,0,0.2,0.4,0.2],[0,0.05,0.4,0.6,0.8,0.9,1]);b.G(c)};
D.iz.mza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,g=(0,D.Xy)(b),e=new D.H(d.x+e,d.y+f,d.g-2*e,d.j-2*f),f=D.iz.Fsa,h=window.Math.min(e.g/100,e.j/100),f=D.Fx.scale(f,h,h),f=D.Fx.translate(f,d.x+d.g/2,d.y+d.j/2);d=new D.Lv(b.e,f);f=(f=b.za())&&0==f.rotation%90?f.rotation:0;g=new D.cf(g?f-90:360-f,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);d.G(g);d=D.iz.v3(b,c,d,e);d.ia(D.t);c.k(d)};
D.iz.hza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j,g=(0,D.Xy)(b),e=new D.H(d.x+e,d.y+f,d.g-2*e,d.j-2*f),f=D.iz.Dsa,h=window.Math.min(e.g/100,e.j/100),f=D.Fx.scale(f,h,h),f=D.Fx.translate(f,d.x+d.g/2,d.y+d.j/2);d=new D.Lv(b.e,f);f=(f=b.za())&&0==f.rotation%90?f.rotation:0;g=new D.cf(g?f-90:360-f,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[0.3,0.55,0,0.25,0.1],[0,0.05,0.4,0.9,1]);d.G(g);d=D.iz.v3(b,c,d,e);d.ia(D.t);c.k(d)};
D.iz.lza=function(b,c){var d=new D.ef(b.e,D.iz.Jba),e=b.za(),e=360-(e&&0==e.rotation%90?e.rotation:0),f=D.Vy.Hb(b),f=[D.N.Yk(f,0.9),f,D.N.Jka(f)],e=new D.cf(e,f,[1,1,1],[0.1,0.4,0.8]);d.G(e);d.ia(D.t);c.k(d)};
D.iz.iza=function(b,c,d){var e=0.05*d.g,f=0.05*d.j;d=new D.H(d.x+e,d.y+f,d.g-2*e,d.j-2*f);var e=d.x+d.g/2,f=d.y+d.j/2,g=window.Math.min(d.g,d.j)/2,h=new D.Hv(b.e,e,f,g);h.ia(D.t);c.k(h);var j=new D.Yx(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.25,0.5],[0.15,0.7,0.95],e,f-0.6*g,1.5*g,[d.x,d.y,d.g,d.j]);h.G(j);h=0.6*g;g*=0.4;f-=0.3*g;b=new D.bf(b.e,e,f-g,h,g);b.ia(D.t);c.k(b);c=new D.Yx(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,0.2,0.5],[0.6,0.8,1],e,f,h,[d.x,d.y,d.g,d.j]);b.G(c)};
D.iz.zea=function(b,c){var d=b.za(),e=d.type,d=0==d.rotation%90?d.rotation:0,f=window.Math.min(c.g,c.j),g=c.x+c.g/2-f/2,h=c.y+c.j/2-f/2,j=f,m=f;"triangle"==e?0==d?(g+=0.2*f,h+=0.25*f,j-=0.4*f,m-=0.3*f):90==d?(g+=0.05*f,h+=0.2*f,j-=0.3*f,m-=0.4*f):180==d?(g+=0.2*f,h+=0.05*f,j-=0.4*f,m-=0.3*f):270==d&&(g+=0.25*f,h+=0.2*f,j-=0.3*f,m-=0.4*f):"arrow"==e?0==d?(g+=0.2*f,h+=0.2*f,j-=0.4*f,m-=0.4*f):90==d?(g+=0.05*f,h+=0.2*f,j-=0.28*f,m-=0.4*f):180==d?(g+=0.2*f,h+=0.2*f,j-=0.4*f,m-=0.4*f):270==d&&(g+=0.23*
f,h+=0.2*f,j-=0.28*f,m-=0.4*f):"star"==e?(g+=0.25*f,h+=0.25*f,j-=0.5*f,m-=0.4*f):"diamond"==e?(g+=0.15*f,h+=0.15*f,j-=0.3*f,m-=0.3*f):"rectangle"==e?(g+=0.1*f,h+=0.1*f,j-=0.2*f,m-=0.2*f):"circle"==e&&(g+=0.15*f,h+=0.15*f,j-=0.3*f,m-=0.3*f);return new D.H(g,h,j,m)};
D.Wy=(0,D.w)();(0,D.qa)("DvtStatusMeterGauge",D.Wy);D.D.l(D.Wy,D.zH,"DvtStatusMeterGauge");D.mE=function(b,c,d){var e=new D.Wy;e.Init(b,c,d);return e};D.Wy.newInstance=D.mE;D.C=D.Wy.prototype;D.C.Init=function(b,c,d){D.Wy.q.Init.call(this,b,c,d);this.lf=new D.sz;this.wZ=D.q};D.C.be=function(b){D.Wy.q.be.call(this,this.lf.Vg(b))};D.C.xi=function(b,c,d){D.bz.L(this,b,c,d)};
D.C.RW=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Zd();"horizontal"==this.N.orientation?f.oe([g[0],g[0],g[2],g[3]]):"vertical"==this.N.orientation?f.oe([g[0],g[1],g[3],g[3]]):"circular"==this.N.orientation&&f.oe([g[0],g[1],0,g[3],g[4]]);var h=new D.im(this.e,f,d);(0,D.P)(h.R,"typeNumberArray",f,f.Zd,f.oe,g);h.R.Ij(function(b){return(0,D.jH)(b,0.7)});c.push(h)}return new D.Zv(this.e,c)};
D.C.Pu=function(b,c){if("horizontal"==this.N.orientation)return this.wZ.OC(b);if("vertical"==this.N.orientation)return this.wZ.OC(c);if("circular"==this.N.orientation){var d=D.Mz.W7(window.Math.atan2(c-this.Lb/2,b-this.ub/2))-270,d=(d+720)%360;0<=d&&360>=d||(d=360<d?360-d<d-360?0:360:0-d<d?0:360);if((0,D.Qe)(this.e))for(d=360-d;0>d;)d+=360;var e=this.N.min;return d/360*(this.N.max-e)+e}};
D.sz=function(){this.Init({skyros:D.qz,alta:D.rz})};D.D.l(D.sz,D.hz,"DvtStatusMeterGaugeDefaults");D.rz={color:"#393737",metricLabel:{style:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},plotArea:{color:"#f5f6f7",borderColor:"#D6DFE6"}};D.qz={color:"#313842",indicatorSize:1,metricLabel:{style:new D.K("color: #333333;")},orientation:"horizontal",plotArea:{color:"#AAAAAA",borderColor:"#C6C6C6",rendered:"auto"},thresholdDisplay:"onIndicator"};
D.bz={};D.D.l(D.bz,D.D,"DvtStatusMeterGaugeRenderer");D.bz.L=function(b,c,d,e){if(D.Qy.pu(b)){var f=b.za(),g=f.__layout.outerGap;d=new D.H(g,g,d-2*g,e-2*g);"horizontal"==f.orientation||"vertical"==f.orientation?(D.bz.as(b,c,d),D.bz.UL(b,c,d)):"circular"==f.orientation&&(f=window.Math.min(d.g,d.j),D.Uy.Z7(b,c,new D.H(d.x+d.g/2-0.325*f,d.y+d.j/2-0.25*f,0.65*f,0.5*f),D.q),D.bz.Rya(b,c,d))}else D.Uy.dA(b,c,new D.H(0,0,d,e))};
D.bz.Rya=function(b,c,d){var e=b.za(),f=0,g=e.value,h=e.thresholds,j=window.Math.min(d.g,d.j),m=0.3125*j,o=0.4625*j,p=1.5*window.Math.PI,f=2*f*window.Math.PI;if(h&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(var r=0;r<h.length;r++){var u=D.Vy.kN(b,h[r],r),f=h[r].max?h[r].max:e.max,v=0==r?e.min:h[r-1].max,p=1.5*window.Math.PI+2*window.Math.PI*D.Uy.tH(e,e.min,v),f=D.Uy.tH(e,v,f),f=2*f*window.Math.PI;D.bz.t0(b,c,d,p,f,m,o,u,D.n)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&
"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(u=D.Vy.zla(b),p=1.5*window.Math.PI,f=2*window.Math.PI,D.bz.t0(b,c,d,p,f,m,o,u,D.n));if((h=e.indicatorSize)&&1!=h)j*=0.075*(1-h),m+=j,o-=j;p=1.5*window.Math.PI;f=D.Uy.tH(e,e.min,g);f=2*f*window.Math.PI;D.bz.t0(b,c,d,p,f,m,o,D.Vy.Hb(b),D.t);if(m=e.referenceLines)for(o=0;o<m.length;o++)j=m[o].color?m[o].color:"black",h=m[o].lineWidth?m[o].lineWidth:2,p=m[o].lineStyle,g=m[o].value,window.angle=1.5*window.Math.PI+2*D.Uy.tH(e,e.min,g)*window.Math.PI,
D.bz.sva(b,c,d,j,h,p);d=new D.af(b.e,d.x,d.y,d.g,d.j);(0,D.Yg)(d);c.k(d);((c=D.Uy.mN(b))||b.za().readOnly===D.t)&&b.Ua().ja(d,new D.Ll(D.q,c,D.Vy.Hb(b)))};
D.bz.UL=function(b,c,d){var e=b.za(),f=(0,D.Qe)(b.e),g="vertical"==e.orientation,h={layout:{}};h.layout.gapRatio=0;h.timeAxisType="disabled";h.position=g?"left":"bottom";h.min=e.min;h.max=e.max;h.dataMin=e.min;h.dataMax=e.max;h.tickLabel={rendered:"off"};h=(0,D.tx)(b.e,h,d);b.wZ=h;var j=0;0>=e.max?j=e.max:0<=e.min&&(j=e.min);var m=h.ak(j);"off"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&(m=h.bd(e.min));var o=h.bd(e.value),o=g?window.Math.max(d.y,window.Math.min(d.y+
d.j,o)):window.Math.max(d.x,window.Math.min(d.x+d.g,o)),p=0,p=0>e.min&&0>e.value?h.bd(e.min):h.bd(e.max),r,u,v,z,A,F,E,j=0;g?(r=d.x,u=d.x+d.g,z=m,v=window.Math.min(d.y,window.Math.min(d.y+d.j,p)),A=d.x+(1-e.indicatorSize)/2*d.g+0.5,F=d.x+d.g*(1-(1-e.indicatorSize)/2)-0.5,j=m-0.5,E=o+0.5):(r=m,u=window.Math.max(d.x,window.Math.max(d.x+d.g,p)),v=d.y,z=d.y+d.j,A=f?m-0.5:m+0.5,F=f?o+0.5:o-0.5,E=d.y+(1-e.indicatorSize)/2*d.j+0.5,j=d.y+d.j*(1-(1-e.indicatorSize)/2)-0.5);p=D.n;o==m&&(p=D.t);var J=D.Vy.vh(b),
M=e.plotArea.borderColor,L=e.thresholds,m=g?0:270;if(L&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(o=L.length-1;0<=o;o--){var S=o,U=D.bz.tv(b,b.e,r,u,v,z,D.n),$=new D.bt("pacp"+b.getId());o==L.length-1?g?(0,D.ct)($,0,0,d.g+2,z-v+2,0,0):f?(0,D.ct)($,h.bd(e.max),0,d.g+2,z-v+2,0,0):(0,D.ct)($,0,0,d.g+2,z-v+2,0,0):g?(0,D.ct)($,0,h.bd(e.max),u-r+2,1*window.Math.abs(e.max-L[L.length-2-S].max)/window.Math.abs(e.min-e.max)*d.j,0,0):f?(0,D.ct)($,0,0,1*(e.max-(L[L.length-2-S].max==D.q?100:L[L.length-
2-S].max))/window.Math.abs(e.min-e.max)*d.g,z-v+2,0,0):(0,D.ct)($,0,0,1*window.Math.abs(L[S].max-e.min)/window.Math.abs(e.min-e.max)*d.g,z-v+2,0,0);(0,D.dt)(U,$);if(f||g)S=L.length-1-o;U.la(D.Vy.kN(b,L[S],S));U.La(M);D.bz.pia(b,c,U,D.Vy.kN(b,L[S],S),m)}else"off"!=e.plotArea.rendered&&(!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)&&"all"!=e.thresholdDisplay)&&(U=g?D.bz.tv(b,b.e,r,u,h.bd(e.max),h.bd(e.min),D.n):D.bz.tv(b,b.e,h.bd(e.min),h.bd(e.max),v,z,D.n),o=D.Vy.zla(b),U.la(o),
U.La(M),D.bz.pia(b,c,U,o,m));o=D.bz.tv(b,b.e,A,F,E,j,D.n);b.Zu.push(o);f=D.Vy.Hb(b);!(0,D.Xy)(b)&&"none"!=e.visualEffects?(r=[D.N.Cg(f,-0.09,0.04),D.N.Cg(f,-0.04,-0.05)],r=new D.cf(m,r,[1,1],[0,1]),o.G(r)):o.la(f);J&&o.La(J);p&&c.k(o);j=D.bz.tv(b,b.e,A,F,E,j,D.n);D.bz.p3(b,c,j,p,m);if(j=e.referenceLines)for(o=0;o<j.length;o++)f=j[o].color?j[o].color:"white",p=j[o].value,A=e.indicatorSize,g?(window.referenceLineSize=((1-A)/2+A)*d.g,window.xCoord=d.x+(1-A)/4*d.g,window.yCoord=h.bd(p),window.referenceLine=
new D.cn(b.e,window.xCoord,window.yCoord,window.xCoord+window.referenceLineSize,window.yCoord)):(window.referenceLineSize=((1-A)/2+A)*d.j,window.xCoord=h.bd(p),window.yCoord=d.y+(1-A)/4*d.j,window.referenceLine=new D.cn(b.e,window.xCoord,window.yCoord,window.xCoord,window.yCoord+window.referenceLineSize)),p=new D.ff(f,1,j[o].lineWidth?j[o].lineWidth:2),j[o].lineStyle&&p.V((0,D.dn)(j[o].lineStyle)),window.referenceLine.Z(p),p=new D.$l(D.N.Du(0,0,0,0.8),0.75,3,3,50,1,2,D.t,D.t,D.t),c.k(window.referenceLine),
(0,D.Xg)(window.referenceLine,p);d=new D.af(b.e,d.x,d.y,d.g,d.j);(0,D.Yg)(d);c.k(d);((c=D.Uy.mN(b))||e.readOnly===D.t)&&b.Ua().ja(d,new D.Ll(D.q,c,f))};D.bz.tv=function(b,c,d,e,f,g,h){return new window.DvtStatusMeterGaugeIndicator(b,c,d,e,f,g,h)};D.bz.p3=function(b,c,d,e,f){"none"!=b.za().visualEffects&&(0,D.Xy)(b)&&(f=new D.cf(f,["#FFFFFF","#FFFFFF","#FFFFFF"],[0.5,0.3125,0],[0,0.3,1]),d.G(f),b.Zu.push(d),d.ia(D.t),e&&c.k(d))};
D.bz.pia=function(b,c,d,e,f){var g=b.za();d.ia(D.t);c.k(d);"none"!=g.visualEffects&&((0,D.Xy)(b)?(b=[D.N.Yk(e,0.9),e,D.N.Jka(e)],f=new D.cf(f,b,[1,1,1],[0,0.04,0.73])):(b=[D.N.Cg(e,-0.04,-0.05),D.N.Cg(e,-0.09,0.04)],f=new D.cf(f,b,[1,1],[0,1])),d.G(f))};
D.bz.as=function(b,c,d){var e=b.za(),f=(0,D.Qe)(b.e),g="vertical"==e.orientation,h=new D.ph(b.e,""),j=D.Uy.Lq(e.value,b),m=e.__layout.labelGap;h.Ha(e.metricLabel.style);if(g&&"on"==e.metricLabel.rendered){var o=0<e.max?e.max:e.min,o=D.Uy.Lq(o,b),p=new D.ph(b.e,o);p.Ha(e.metricLabel.style);f=new D.H(d.x,d.y+0.8*d.j,d.g,0.2*d.j);g=(g=e.metricLabel.style.v("font-size"))?(0,window.parseInt)(g):p.Lw(f);p=p.Rb();d.j-=p.j;window.labelSpace=p.g;h.Jf(g);h.zd(j);h.da(d.x+d.g/2);h.ta(d.y+d.j);d.j-=m;h.Re();
D.Kl.Ub(h,d.g,d.j,c)}else if(!g&&"on"==e.metricLabel.rendered){var g=(g=e.metricLabel.style.v("font-size"))?(0,window.parseInt)(g):13,r=D.Uy.Lq(e.min,b),p=D.Uy.Lq(e.max,b),p=window.Math.max(p.toString().length,r.toString().length),r="";"percent"==e.metricLabel.textType&&(p=3,r+="%");for(var u=0;u<p;u++)r+="0";h.zd(r);18>d.j&&(g=h.Lw(d));h.Jf(g);if(0<e.max||"off"!=e.plotArea.rendered||!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay))o=0<e.max?e.max:e.min,o=D.Uy.Lq(o,b),p=new D.ph(b.e,
o),p.Ha(e.metricLabel.style),p.Jf(g),p=h.Rb(),o=f?d.x+p.g:d.x+d.g,window.labelSpace=p.g,f&&(d.x+=p.g+m),d.g-=p.g+m;if(0>e.min&&"on"!=e.plotArea.rendered&&!("auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay)){g=D.Uy.Lq(e.min,b);r=new D.ph(b.e,g);r.Ha(e.metricLabel.style);b=r.Rb();if(0>e.value||0>=e.max)o=f?d.x+d.g:d.x+b.g,window.labelSpace=b.g;f||(d.x+=b.g+m);d.g-=b.g+m}h.zd(j);h.da(o);h.ta(d.y+d.j/2);h.Ae();h.ni();D.Kl.Ub(h,window.labelSpace,d.j,c)}};
D.bz.jt=function(b,c,d){return{x:window.Math.cos(d)*c+b.g/2+b.x,y:window.Math.sin(d)*c+b.j/2+b.y}};D.bz.t0=function(b,c,d,e,f,g,h,j,m){var o=b.e;(0,D.Qe)(b.e)&&(e=window.Math.PI-e-f,e=0<e?e:e+2*window.Math.PI);m?d=new D.ef(o,D.bz.Tja(d,e,f,g,h)):(d=new D.$y(o,d,e,f,g,h),b.Zu.push(d));d.la(j);(b=D.Vy.vh(b))&&!m&&d.La(b);c.k(d)};
D.bz.sva=function(b,c,d,e,f,g){var h=window.angle,j=b.e,m=window.Math.min(d.g,d.j),o=0.275*m,m=0.5*m;(0,D.Qe)(b.e)&&(h=window.Math.PI-h,h=0<h?h:h+2*window.Math.PI);window.p1=D.bz.jt(d,o,h);window.p2=D.bz.jt(d,m,h);b=new D.cn(j,window.p1.x,window.p1.y,window.p2.x,window.p2.y);e=new D.ff(e,1,f);g&&e.V((0,D.dn)(g));b.Z(e);c.k(b)};
D.bz.Tja=function(b,c,d,e,f){var g,h,j;d<2*window.Math.PI?(g=D.bz.jt(b,f,c),h=D.bz.jt(b,f,c+d),j=D.bz.jt(b,e,c+d),b=D.bz.jt(b,e,c),f=window.DvtPathUtils.moveTo(g.x,g.y)+window.DvtPathUtils.arcTo(f,f,d,1,h.x,h.y)+window.DvtPathUtils.lineTo(j.x,j.y)+window.DvtPathUtils.arcTo(e,e,d,0,b.x,b.y)+window.DvtPathUtils.closePath()):(g=D.bz.jt(b,f,c),h=D.bz.jt(b,f,c+d/2),j=D.bz.jt(b,e,c),b=D.bz.jt(b,e,c+d/2),f=window.DvtPathUtils.moveTo(g.x,g.y)+window.DvtPathUtils.arcTo(f,f,d/2,1,h.x,h.y)+window.DvtPathUtils.arcTo(f,
f,d/2,1,g.x,g.y),0<e&&(f+=window.DvtPathUtils.moveTo(b.x,b.y)+window.DvtPathUtils.arcTo(e,e,d/2,0,j.x,j.y)+window.DvtPathUtils.arcTo(e,e,d/2,0,b.x,b.y)),f+=window.DvtPathUtils.closePath());return f};
window.DvtStatusMeterGaugeIndicator=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.D.l(window.DvtStatusMeterGaugeIndicator,D.af,"DvtStatusMeterGaugeIndicator");window.DvtStatusMeterGaugeIndicator.asa=2.5;window.DvtStatusMeterGaugeIndicator.prototype.Init=function(b,c,d,e,f,g,h){window.DvtStatusMeterGaugeIndicator.q.Init.call(this,c);this.le=b;this.xza=h;this.gxa="vertical"==b.za().orientation;this.gA(d,e,f,g)};
window.DvtStatusMeterGaugeIndicator.prototype.gA=function(b,c,d,e){this.hp=b;this.ip=c;this.uAa=d;this.vAa=e;var f=window.Math.min(b,c),g=window.Math.min(d,e);b=window.Math.abs(b-c);d=window.Math.abs(e-d);(0,D.Dn)(this,f,g,b,d);this.xza&&(f=(this.gxa?b:d)*((0,D.Xy)(this.le)?0.25:0.15),f>=window.DvtStatusMeterGaugeIndicator.asa&&(0,D.Nv)(this,f,f))};window.DvtStatusMeterGaugeIndicator.prototype.Zd=function(){return[this.hp,this.ip,this.uAa,this.vAa]};
window.DvtStatusMeterGaugeIndicator.prototype.oe=function(b){b&&4==b.length&&this.gA(b[0],b[1],b[2],b[3])};
D.$y=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.D.l(D.$y,D.ef,"DvtStatusMeterGaugeCircularIndicator");D.$y.prototype.Init=function(b,c,d,e,f,g){D.$y.q.Init.call(this,b);(0,D.az)(this,c,d,e,f,g)};D.az=function(b,c,d,e,f,g){c&&c instanceof D.H?b.Ja=c:c=b.Ja;b.Xc=d;b.fd=e;b.ji=f;b.Mh=g;b.kk(D.bz.Tja(c,d,e,f,g))};D.$y.prototype.Zd=function(){return[this.Ja,this.Xc,this.fd,this.ji,this.Mh]};D.$y.prototype.oe=function(b){b&&5==b.length&&(0,D.az)(this,b[0],b[1],b[2],b[3],b[4])};
D.DH=(0,D.w)();(0,D.qa)("DvtDialGauge",D.DH);D.D.l(D.DH,D.zH,"DvtDialGauge");D.nE=function(b,c,d){var e=new D.DH;e.Init(b,c,d);return e};D.DH.newInstance=D.nE;D.C=D.DH.prototype;D.C.Init=function(b,c,d){D.DH.q.Init.call(this,b,c,d);this.lf=new D.zz;this.vZ=D.q};
D.C.be=function(b){var c=b.background,d=b.indicator;"string"===typeof c&&(b.background=D.Vy.yCa(c),b.background.images=b._backgroundImages);"string"===typeof d&&(b.indicator=D.Vy.zCa(d),b.indicator.images=b._indicatorImages);D.DH.q.be.call(this,this.lf.Vg(b))};D.C.xi=function(b,c,d){D.Yy.L(this,b,c,d)};
D.C.RW=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var f=b[e],g=f.Zd(),h=D.Yy.Ysa(this);f.$g(h);h=new D.im(this.e,f,d);(0,D.P)(h.R,"typeNumberArray",f,f.Zd,f.oe,g);h.R.Ij(function(b){return(0,D.jH)(b,0.7)});c.push(h)}return new D.Zv(this.e,c)};
D.C.Pu=function(b,c){var d=D.Mz.W7(window.Math.atan2(c-this.vZ.y,b-this.vZ.x));0>=d&&(d+=360);var e=(0,D.Qe)(this.e),f=this.za().background,g=e?180+f.startAngle:360-f.startAngle,f=f.angleExtent,h=g+f;if(e){h=g;for(g-=f;0>g;)g+=360,h+=360}d+360>=g&&d+360<=h?d+=360:d>=g&&d<=h||(d=d>h?g+360-d<d-h?g:h:g-d<d+360-h?g:h);d=(d-g)/f;e&&(d=1-d);e=this.N.min;return d*(this.N.max-e)+e};
D.zz=function(){this.Init({skyros:D.yz,alta:{}})};D.D.l(D.zz,D.hz,"DvtDialGaugeDefaults");D.yz={background:{startAngle:180,angleExtent:180,indicatorLength:0.7},metricLabel:{style:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},tickLabel:{scaling:"auto",style:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")}};
D.Yy={};D.D.l(D.Yy,D.D,"DvtDialGaugeRenderer");D.Yy.L=function(b,c,d,e){D.Qy.pu(b)?(d=new D.H(0,0,d,e),D.Yy.UL(b,c,d),D.Yy.as(b,c,d)):D.Uy.dA(b,c,new D.H(0,0,d,e))};
D.Yy.UL=function(b,c,d){var e=b.za(),f=D.Yy.Qua(b,d);c.k(f);e.background.majorTickCount&&e.background.radius&&D.Yy.pza(b,c,d);var g=D.Yy.Tua(b,d),h=new D.Q(b.e),j=new D.Zy(b.e);c.k(h);h.k(j);j.k(g);var m=g.C(),o=D.Yy.Dea(b,e.value),f=D.Yy.pea(b,d),p=D.Yy.Zva(b,m);d=D.Yy.$va(b,d,m);m=new D.rh;m.translate(-p.x,-p.y);m.scale(d,d);g.ra(m);j.$g(o);m=new D.rh;m.translate(f.x,f.y);h.ra(m);b.Zu.push(j);((e=e.shortDesc)||b.za().readOnly===D.t)&&b.Ua().ja(c,new D.Ll(D.q,e));b.vZ=f};
D.Yy.Qua=function(b,c){var d=b.za().background,e=(0,D.Qe)(b.e),f=(0,D.wf)(),g=f?2*c.g:c.g,h=f?2*c.j:c.j,j=d.images;if(j&&0<j.length){var m,o,p,f=[];for(m=0;m<j.length;m++){var r="rtl"==j[m].dir;e&&r?f.push(j[m]):!e&&!r&&f.push(j[m])}j=0<f.length?f:j;for(m=0;m<j.length;m++){var u=j[m],r=u.src,f=u.width,u=u.height,v=r&&-1<r.search(".svg");0==m&&(o=f,p=u);if(v||f>=g&&u>=h||m==j.length-1){var g=new D.kf(b.e,r,0,0,f,u),z=new D.rh,h=window.Math.min(c.g/f,c.j/u),j=(c.g-h*f)/2;m=(c.j-h*u)/2;z.scale(h,h);
z.translate(j,m);g.ra(z);v&&(0,D.un)()&&(r=D.Ip.Gj(b.e,r,D.D.uj(g,g.yZ)))&&g.yZ(r);c.x+=j;c.y+=m;c.g=h*f;c.j=h*u;!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=e?c.x+c.g-c.g*d.anchorX/o:c.x+c.g*d.anchorX/o,d._anchorY=c.y+c.j*d.anchorY/p);d.metricLabelBounds&&(f={},f.width=c.g*d.metricLabelBounds.width/o,f.height=c.j*d.metricLabelBounds.height/p,f.y=c.y+c.j*d.metricLabelBounds.y/p,f.x=e?c.x+c.g-c.g*d.metricLabelBounds.x/o-f.width:c.x+c.g*d.metricLabelBounds.x/o,d._metricLabelBounds=
f);e=window.Math.min(c.g/o,c.j/p);d._radius=d.radius*e;d._tickLabelHeight=d.tickLabelHeight*c.j/p;d._tickLabelWidth=d.tickLabelWidth*c.g/o;return g}}}return D.q};
D.Yy.Tua=function(b,c){var d=b.za().indicator,e=D.Yy.wea(b,c),f=(0,D.wf)()?2*e:e,g,h,j=d.images;if(j&&0<j.length)for(var m=0;m<j.length;m++){var o=j[m],e=o.src,p=o.width,o=o.height,r=e&&-1<e.search(".svg");0==m&&(g=p,h=o);if(r||o>=f||m==j.length-1)return f=new D.kf(b.e,e,0,0,p,o),r&&(0,D.un)()&&D.Ip.Gj(b.e,e,D.D.uj(f,f.yZ))&&(f.ha(p),f.ua(o)),!(0,window.isNaN)(d.anchorX)&&!(0,window.isNaN)(d.anchorY)&&(d._anchorX=d.anchorX*p/g,d._anchorY=d.anchorY*o/h),f}return D.q};
D.Yy.Ysa=function(b){var c=b.za().background;b=(0,D.Qe)(b.e)?180-c.startAngle:c.startAngle;return window.Math.PI*(90-b)/180};D.Yy.Dea=function(b,c){var d=b.za(),e=d.background,f=d.min,d=d.max;c=window.Math.max(window.Math.min(c,d),f);f=(c-f)/(d-f);d=(0,D.Qe)(b.e);return window.Math.PI*(90-((d?180-e.startAngle:e.startAngle)-f*(d?-e.angleExtent:e.angleExtent)))/180};
D.Yy.pea=function(b,c){var d=b.za().background,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.G(e,d):new D.G(c.x+c.g/2,c.y+c.j/2)};D.Yy.wea=function(b,c){var d=window.Math.min(c.g,c.j)/2;return b.za().background.indicatorLength*d};D.Yy.Zva=function(b,c){var d=b.za().indicator,e=d._anchorX,d=d._anchorY;return!(0,window.isNaN)(e)&&!(0,window.isNaN)(d)?new D.G(e,d):new D.G(c.x+c.g/2,c.y+c.j)};D.Yy.$va=function(b,c,d){return D.Yy.wea(b,c)/d.j};
D.Yy.as=function(b,c,d){var e=b.za();if("on"==e.metricLabel.rendered){var f=D.Uy.Lq(e.value,b),g=d.x+d.g/2,h=d.y+d.j/2,j=d.g,m=d.j,o=e.background._metricLabelBounds;o&&(g=o.x+o.width/2,h=o.y+o.height/2,d.g=o.width,d.j=o.height);g=new D.ph(b.e,f,g,h);!e.metricLabel.style.v("color")&&e.background._isDark&&e.metricLabel.style.V("color","#CCCCCC");g.Ha(e.metricLabel.style);h=(0,window.parseInt)(e.metricLabel.style.uH());if(!h){h=window.Math.max(D.Uy.Lq(e.max,b).length,D.Uy.Lq(e.min,b).length,f.length);
o="";"percent"==e.metricLabel.textType&&(h=window.Math.max(3,f.length),o+="%");for(e=0;e<h;e++)o+="0";g.zd(o);h=g.Lw(d);g.zd(f);g.Jf(h)}g.Re();g.Ae();D.Kl.Ub(g,j,m,c)&&g.kg()&&b.Ua().ja(g,new D.Ll(f))}};
D.Yy.pza=function(b,c,d){var e=b.za(),f=(0,D.Qe)(b.e);if(e.background.radius&&e.background.majorTickCount){var g=e.background._radius,h=e.min,j=e.max,m=e.background.majorTickCount,o=12,p=new D.H(A,v,d.g,d.j),r=e.metricLabel.style.v("font-size");e.background._tickLabelHeight&&!r&&(p.j=e.background._tickLabelHeight);e.background._tickLabelWidth&&!r&&(p.g=e.background._tickLabelWidth);if(!r){var u=new D.ph(b.e,"",A,v),o=window.Math.max(D.Uy.AU(e.max,b).length,D.Uy.AU(e.min,b).length),r="";"percent"==
e.tickLabel.textType&&(o=window.Math.max(3,D.Uy.AU(100,b).length-1),r+="%");for(A=0;A<o;A++)r+="0";u.zd(r);o=u.Lw(p)}for(r=0;r<m;r++){A=h+window.Math.abs(j-h)*r/(m-1);f&&(A=h+window.Math.abs(j-h)*(m-1-r)/(m-1));var u=D.Uy.AU(A,b),v=D.Yy.Dea(b,A),z=D.Yy.pea(b,d),A=z.x+g*window.Math.cos(v-window.Math.PI/2),v=z.y+g*window.Math.sin(v-window.Math.PI/2),u=new D.ph(b.e,u,A,v);!e.tickLabel.style.v("color")&&e.background._isDark&&e.tickLabel.style.V("color","#CCCCCC");u.Ha(e.tickLabel.style);e.tickLabel.style.v("font-size")||
u.Jf(o);u.Re();u.Ae();D.Kl.Ub(u,p.g+0.5,p.j+0.5,c)&&u.kg()&&b.Ua().ja(u,new D.Ll(u.Aq))}}};
D.Zy=function(b){this.Init(b)};D.D.l(D.Zy,D.Q,"DvtDialGaugeIndicator");D.Zy.prototype.$g=function(b){var c=new D.rh;c.rotate(b);this.ra(c);this.wta=b};D.Zy.prototype.Zd=function(){return[this.wta]};D.Zy.prototype.oe=function(b){b&&1==b.length&&this.$g(b[0])};
D.CH=(0,D.w)();(0,D.qa)("DvtRatingGauge",D.CH);D.D.l(D.CH,D.zH,"DvtRatingGauge");D.oE=function(b,c,d){var e=new D.CH;e.Init(b,c,d);return e};D.CH.newInstance=D.oE;D.C=D.CH.prototype;D.C.Init=function(b,c,d){D.CH.q.Init.call(this,b,c,d);this.lf=new D.gz};D.C.be=function(b){D.CH.q.be.call(this,this.lf.Vg(b))};D.C.xi=function(b,c,d){var e=this.za().__layout.outerGap,f=this.N.max;this.Yj=window.Math.min(d-2*e,(c-2*e)/f);this.Ja=new D.H((this.ub-this.Yj*f)/2,e,this.Yj*f,this.Lb-2*e);D.Py.L(this,b,c,d)};
D.C.na=function(){return new D.Ty(this)};D.C.Pu=function(b){if(D.Qy.pu(this)){b=window.Math.max(window.Math.min(b,this.Ja.x+this.Ja.g),this.Ja.x);var c=0,c=(0,D.Qe)(this.e)?window.Math.max((this.Ja.x+this.Ja.g-b)/this.Yj,this.N.min):window.Math.max((b-this.Ja.x)/this.Yj,this.N.min);return D.Uy.hU(this.N,c)}return D.q};D.oz=function(b){(0,D.Ry)(b,b.N.value,"render")};D.CH.prototype.JP=function(b,c){(0,D.Ry)(this,this.Pu(b,c),"hover")};
D.CH.prototype.tJ=function(b,c){var d=this.Pu(b,c);(0,D.Ry)(this,d,"hover");this.Xa(new D.dz(this.N.value,d,D.t))};D.CH.prototype.IP=function(b,c){var d=this.N.value;this.N.value=this.Pu(b,c);this.N.changed=D.n;this.L();this.Xa(new D.dz(d,this.N.value,D.t));this.Xa(new D.dz(d,this.N.value,D.n))};
D.Ry=function(b,c,d,e){if(D.Qy.pu(b)){e||(e=b.fa);var f=(0,D.Qe)(b.e);c=window.Math.max(window.Math.min(c,b.N.max),0);var g=0,h=c*b.Yj,j=c*b.Yj;"render"==d&&(g=c*b.Yj,h=0);f?(c=e.ca(0),d=new D.bt("unsel"+b.getId()),(0,D.ct)(d,b.Ja.x,b.Ja.y,b.Ja.g-j,b.Ja.j),(0,D.dt)(c,d),c=e.ca(1),d=new D.bt("sel"+b.getId()),(0,D.ct)(d,b.Ja.x+b.Ja.g-j,b.Ja.y,g,b.Ja.j),(0,D.dt)(c,d),e=e.ca(2),g=new D.bt("hover"+b.getId()),(0,D.ct)(g,b.Ja.x+b.Ja.g-j,b.Ja.y,h,b.Ja.j)):(c=e.ca(0),d=new D.bt("unsel"+b.getId()),(0,D.ct)(d,
b.Ja.x+j,b.Ja.y,b.Ja.g-j,b.Ja.j),(0,D.dt)(c,d),c=e.ca(1),d=new D.bt("sel"+b.getId()),(0,D.ct)(d,b.Ja.x,b.Ja.y,g,b.Ja.j),(0,D.dt)(c,d),e=e.ca(2),g=new D.bt("hover"+b.getId()),(0,D.ct)(g,b.Ja.x,b.Ja.y,h,b.Ja.j));(0,D.dt)(e,g)}};D.CH.prototype.bE=function(){return new D.lz(this)};
D.gz=function(){this.Init({skyros:D.ez,alta:D.fz})};D.D.l(D.gz,D.hz,"DvtRatingGaugeDefaults");D.fz={unselectedState:{shape:"star",color:"#C4CED7",borderColor:D.q},selectedState:{shape:"star",color:"#F8C15A",borderColor:D.q},hoverState:{shape:"star",color:"#007CC8",borderColor:D.q},changedState:{shape:"star",color:"#ED2C02",borderColor:D.q}};
D.ez={min:0,max:5,unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",borderColor:"#959595"},step:1};
D.Ty=function(b){this.Init();this.le=b};D.D.l(D.Ty,D.Ll,"DvtRatingGaugePeer");D.Ty.prototype.gf=function(b,c,d){b=this.le.za();c=this.le.Ua().fk?D.Qy.fD(this.le,this.le.Pu(c,d)):D.Qy.fD(this.le);return(c=D.Qy.EH(this.le,c))&&c.shortDesc?c.shortDesc:b.shortDesc};
D.Py={};D.D.l(D.Py,D.D,"DvtRatingGaugeRenderer");D.Py.EP=["circle","diamond","rectangle","star","triangle"];
D.Py.L=function(b,c,d,e){if(D.Qy.pu(b)){var f=b.za(),g=f.__layout.outerGap,h=f.max,j=window.Math.min(e-2*g,(d-2*g)/h);e=new D.H((d-j*h)/2,g,j*h,e-2*g);d=D.Qy.EH(b,D.Qy.fD(b));var m=f.selectedState.color,o=f.changedState.color,p=f.selectedState.borderColor,r=f.changedState.borderColor;d&&d.color&&(o=m=d.color);d&&d.borderColor&&(r=p=d.borderColor);g={value:0,type:f.unselectedState.shape,color:f.unselectedState.color,borderColor:f.unselectedState.borderColor,visualEffects:f.visualEffects};m={value:0,
type:f.selectedState.shape,color:m,borderColor:p,visualEffects:f.visualEffects};o={value:0,type:f.changedState.shape,color:o,borderColor:r,visualEffects:f.visualEffects};r={value:0,type:f.hoverState.shape,color:f.hoverState.color,borderColor:f.hoverState.borderColor,visualEffects:f.visualEffects};"dot"==f.unselectedState.shape&&(g.type="circle",g.visualEffects="none",g.size=0.05);p=new D.Q(b.e);c.k(p);var u=new D.Q(b.e);c.k(u);var v=new D.Q(b.e);c.k(v);(0,D.Ry)(b,f.value,"render",c);for(var z=0;z<
h;z++){if("none"!=f.unselectedState.shape){var A=(0,D.Sy)(b.e,D.q,D.q,D.n);p.k(A);(0,D.jg)(A,e.x+z*j,e.y+e.j/2-j/2);-1==D.Kf.Fa(D.Py.EP,g.type)&&(g.type="star");A.L(g,j,j)}f.changed?(A=(0,D.Sy)(b.e,D.q,D.q,D.n),u.k(A),(0,D.jg)(A,e.x+z*j,e.y+e.j/2-j/2),-1==D.Kf.Fa(D.Py.EP,o.type)&&(o.type="star"),A.L(o,j,j)):(A=(0,D.Sy)(b.e,D.q,D.q,D.n),u.k(A),(0,D.jg)(A,e.x+z*j,e.y+e.j/2-j/2),-1==D.Kf.Fa(D.Py.EP,m.type)&&(m.type="star"),A.L(m,j,j));A=(0,D.Sy)(b.e,D.q,D.q,D.n);v.k(A);(0,D.jg)(A,e.x+z*j,e.y+e.j/2-j/
2);-1==D.Kf.Fa(D.Py.EP,r.type)&&(r.type="star");A.L(r,j,j)}h=new D.af(b.e,e.x,e.y,e.g,e.j);(0,D.Yg)(h);c.k(h);(d&&d.shortDesc?d.shortDesc:f.shortDesc)&&b.Ua().ja(h,new D.Ty(b))}else D.Uy.dA(b,c,new D.H(0,0,d,e))};
D.lz=function(b){this.Init(b.e,b.Xa,b);this.le=b;this.VJ=this.fk=D.t;this.vfa=(0,D.Vp)();this.d4=D.t};D.D.l(D.lz,D.mz,"DvtRatingGaugeEventManager");D.C=D.lz.prototype;D.C.xo=function(b){if(this.le.za().readOnly===D.t&&!this.VJ){var c=(0,D.nz)(this,b.pageX,b.pageY),d=this.le;(0,D.Ry)(d,d.Pu(c.x,c.y),"hover");this.fk=D.n}D.mz.q.xo.call(this,b)};
D.C.pk=function(b){if(this.le.za().readOnly===D.t){if(this.vfa&&this.VJ&&this.d4){this.d4=D.t;return}(0,D.nz)(this,b.pageX,b.pageY);(0,D.oz)(this.le);this.VJ=D.t}D.mz.q.pk.call(this,b)};D.C.ol=function(b){this.VJ||(this.le.za().readOnly===D.t?(this.fk=D.n,this.tc(),b=(0,D.nz)(this,b.pageX,b.pageY),this.le.JP(b.x,b.y)):D.mz.q.ol.call(this,b))};
D.C.hn=function(b){this.fk&&(this.le.za().readOnly===D.t?(this.fk=D.t,b=(0,D.nz)(this,b.pageX,b.pageY),this.le.IP(b.x,b.y),(0,D.oz)(this.le),this.VJ=D.n,this.vfa&&(this.d4=D.n)):D.mz.q.hn.call(this,b))};D.C.R$=(0,D.ca)(D.n);
});