define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.xw={dm:function(){return(0,D.wf)()}};D.D.l(D.xw,D.D,"DvtTimeUtils");D.xw.tf=function(b,c,d,e){d=(d-b)*e;b=c-b;return 0==d||0==b?0:d/b};D.xw.Te=function(b,c,d,e){c=d*(c-b);return 0==c||0==e?b:c/e+b};
D.$w=function(b,c,d){this.Init(b,c,d)};(0,D.qa)("DvtOverview",D.$w);D.D.l(D.$w,D.Q,"DvtOverview");
D.$w.prototype.Init=function(b,c,d){D.$w.q.Init.call(this,b);this.hb=c;this.ka=d;this.An=this.su()?7:6;if(this.hb!=D.q||this.ka!=D.q)D.xw.dm()?(this.W(D.xz.we,this.RX,D.t,this),this.W(D.xz.aj,this.QX,D.t,this),this.W(D.xz.Dh,this.MX,D.t,this),this.W(D.bi,this.OI,D.t,this)):(this.W(D.Mh,this.JX,D.t,this),this.W(D.Nh,this.IX,D.t,this),this.W(D.bi,this.OI,D.t,this),this.W(D.Ar,this.Ep,D.t,this),this.W(D.Gr,this.qo,D.t,this),this.W(D.Gk,this.wA,D.t,this),this.W(D.Hk,this.l$,D.t,this),this.W(D.Ik,this.m$,
D.t,this));this.k1=0};D.$w.prototype.lA=function(b,c){var d=this.tf(b),e=this.tf(c);if(!(d<this.fq||e>(0,D.wF)(this))){var f=window.Math.max(e-d,(0,D.xF)(this));0<f&&(0<=d&&e<=this.ub)&&(e=this.ca(1),this.Ti()?(0,D.yF)(this,e,this.ub-(d+f)):(0,D.yF)(this,e,d),(0,D.zF)(this,e,f),(0,D.AF)(this))}};D.BF=function(b){return b.wR==D.q?D.t:-1!=b.wR.indexOf("zoom")};
D.$w.prototype.L=function(b,c,d){if(b==D.q){var e=this.Tg,f=this.Jh,g=this.ca(1),h=(0,D.CF)(this,g);g!=D.q&&0!=h&&(this.qia=D.xw.Te(e,f,h,this.ub));this.vi()}c!=D.q&&d!=D.q&&(this.ub=c,this.Lb=d);b&&(b=this.Uu(b),this.Fo(b));b=this.hb!=D.q||this.ka!=D.q;this.kH(c,d);if(b){f=(e=this.pc())?new D.af(this.e,0,0,c,0,"window"):new D.af(this.e,0,0,0,d,"window");f.la(this.YT,this.lAa);(0,D.bn)(f);if(!(0,D.BF)(this)){var j=(0,D.DF)(),m=(0,D.EF)();if(e){var o=(c-36)/2,p=window.DvtPathUtils.moveTo(o,0)+window.DvtPathUtils.fc(o+
3,6,o+8,8)+window.DvtPathUtils.lineTo(o+28,8)+window.DvtPathUtils.fc(o+33,6,o+36,0);window.DvtPathUtils.closePath();h=window.DvtPathUtils.moveTo(o,0)+window.DvtPathUtils.fc(o+3,-6,o+8,-8)+window.DvtPathUtils.lineTo(o+28,-8)+window.DvtPathUtils.fc(o+33,-6,o+36,0);window.DvtPathUtils.closePath();var g=new D.af(this.e,0,0,c,j,"lhb"),j=new D.af(this.e,0,0,c,j,"rhb"),r="row-resize";if(this.W0)var u=(0,D.FF)(this,c,10),o=(0,D.FF)(this,c,10);else u=(0,D.GF)(this,o),o=(0,D.GF)(this,o)}else o=(d-36)/2,p=window.DvtPathUtils.moveTo(0,
o)+window.DvtPathUtils.fc(6,o+3,8,o+8)+window.DvtPathUtils.lineTo(8,o+28)+window.DvtPathUtils.fc(6,o+33,0,o+36),window.DvtPathUtils.closePath(),h=window.DvtPathUtils.moveTo(0,o)+window.DvtPathUtils.fc(-6,o+3,-8,o+8)+window.DvtPathUtils.lineTo(-8,o+28)+window.DvtPathUtils.fc(-6,o+33,0,o+36),window.DvtPathUtils.closePath(),g=new D.af(this.e,0-m,0,j,d,"lhb"),j=new D.af(this.e,m,0,j,d,"rhb"),r="col-resize",this.W0?(u=(0,D.FF)(this,10,d),o=(0,D.FF)(this,10,d)):(u=(0,D.GF)(this,o),o=(0,D.GF)(this,o));g.la(this.YT,
0);j.la(this.YT,0);(0,D.bn)(g);(0,D.bn)(j);p=new D.ef(this.e,p,"lh");h=new D.ef(this.e,h,"rh");p.la(this.LK);p.La(this.LK);h.la(this.LK);h.La(this.LK);this.YT==this.LK&&((0,D.bn)(p),(0,D.bn)(h));g.setCursor(r);j.setCursor(r);p.setCursor(r);h.setCursor(r);u.setCursor(r);o.setCursor(r);f.k(g);f.k(p);f.k(u);f.k(j);f.k(h);f.k(o)}f.setCursor("move");this.k(f);f=e?new D.cn(this.e,c-this.lN(),0,c-this.lN(),d,"tab"):"above"==this.YS?new D.cn(this.e,0,this.dk(),c,this.dk(),"tab"):new D.cn(this.e,0,d-this.dk(),
c,d-this.dk(),"tab");f.La(this.Vza,this.Wza);(0,D.bn)(f);this.k(f);this.Wq()&&(e?(f=new D.af(this.e,0,0,c,0,"lbg"),g=new D.af(this.e,0,0,c,0,"rbg")):(f=new D.af(this.e,0,0,0,d,"lbg"),g=new D.af(this.e,0,0,0,d,"rbg")),f.la(this.aga,this.wxa),this.k(f),g.la(this.xia,this.tza),this.k(g),D.xw.dm()&&m!=D.k&&((0,D.EF)(),e?(e=new D.af(this.e,0,0,c,m,"lbgrh"),m=new D.af(this.e,0,0,c,m,"rbgrh")):(e=new D.af(this.e,0,0,m,d,"lbgrh"),m=new D.af(this.e,0,0,m,d,"rbgrh")),e.la(this.aga,0),this.k(e),m.la(this.xia,
0),this.k(m)))}this.Sna(c,d);if(this.K0!=D.q)for(m=0;m<this.K0.length;m++)g=this.K0[m],e=c,f=d,r=(0,window.parseInt)(g.o("rs"),10),h=(0,window.parseInt)(g.o("re"),10),g=g.o("c"),r!=D.q&&h!=D.q&&(j=(0,D.HF)(this),r=this.tf(r),h=this.tf(h)-r,this.Ti()&&(r=j-r-h),e=this.pc()?new D.af(this.e,0,r,e-this.lN(),h,"ftr"):new D.af(this.e,r,"above"==this.YS?this.dk():0,h,f-this.dk(),"ftr"),g!=D.q&&e.la(g,0.4),e.setCursor("move"),(0,D.bn)(e),this.k(e));this.a0==D.q||(0,window.isNaN)(this.a0)||(m=this.tf(this.a0),
this.pc()?m=new D.cn(this.e,0,m,c,m,"ocd"):(this.Ti()&&(m=c-m),m=new D.cn(this.e,m,0,m,d,"ocd")),m.La(this.dva),(0,D.bn)(m),this.k(m));this.LN(c,d);b&&(f=this.ca(1),this.pc()?(b=f.ga(),m=f.ga()+f.getHeight()-1,this.su()||(0,D.un)()?(e=0,j=c-1):(e=1,j=c),f=new D.cn(this.e,0,b,c,b,"lh"),g=new D.cn(this.e,0,m,c,m,"rh"),h=new D.cn(this.e,e,0,e,b,"ltb"),c=new D.cn(this.e,e,m,e,d,"rtb"),d=new D.cn(this.e,j,b,j,m,"bb"),b=new D.cn(this.e,e,b,e,m,"tb")):(b=1,this.su()&&(b=0),m=d-1,e=f.ea(),j=f.ea()+f.getWidth()-
1,f=new D.cn(this.e,e,b,e,m,"lh"),g=new D.cn(this.e,j,b,j,m,"rh"),h=new D.cn(this.e,0,window.Math.max(0,b-1),e+1,window.Math.max(0,b-1),"ltb"),c=new D.cn(this.e,j-1,window.Math.max(0,b-1),c,window.Math.max(0,b-1),"rtb"),d=new D.cn(this.e,e,m,j,m,"bb"),b=new D.cn(this.e,e,b,j,b,"tb")),(0,D.bn)(f),(0,D.bn)(g),(0,D.bn)(h),(0,D.bn)(c),(0,D.bn)(d),(0,D.bn)(b),"none"!=this.pAa&&f.La(this.oAa),this.k(f),"none"!=this.rAa&&g.La(this.qAa),this.k(g),"none"!=this.pua&&this.l_&&(h.La(this.l_),c.La(this.l_)),this.k(h),
this.k(c),"none"!=this.nAa&&d.La(this.mAa),this.k(d),"none"!=this.tAa&&b.La(this.sAa),this.k(b),this.su()&&(c=this.pc()?window.DvtPathUtils.moveTo(6,0)+window.DvtPathUtils.lineTo(0,5)+window.DvtPathUtils.lineTo(5,5)+window.DvtPathUtils.lineTo(5,17)+window.DvtPathUtils.lineTo(0,17)+window.DvtPathUtils.lineTo(6,22)+window.DvtPathUtils.lineTo(12,17)+window.DvtPathUtils.lineTo(7,17)+window.DvtPathUtils.lineTo(7,5)+window.DvtPathUtils.lineTo(12,5)+window.DvtPathUtils.closePath():window.DvtPathUtils.moveTo(5,
0)+window.DvtPathUtils.lineTo(0,6)+window.DvtPathUtils.lineTo(5,12)+window.DvtPathUtils.lineTo(5,7)+window.DvtPathUtils.lineTo(17,7)+window.DvtPathUtils.lineTo(17,12)+window.DvtPathUtils.lineTo(22,6)+window.DvtPathUtils.lineTo(17,0)+window.DvtPathUtils.lineTo(17,4)+window.DvtPathUtils.lineTo(5,4)+window.DvtPathUtils.lineTo(5,0)+window.DvtPathUtils.closePath(),c=new D.ef(this.e,c,"arr"),c.la("#ffffff"),c.La("#000000"),c.bb(D.t),this.k(c),this.sG=c),b=this.pc(),d=this.ca(1),c=(0,D.HF)(this),m=b?this.Lb:
this.ub,f=this.S,g=this.Tg,h=this.Jh,b=this.qia,e=D.xw.Te(g,h,0,f),f=D.xw.Te(g,h,m,f),e=this.tf(e),m=window.Math.min(m,this.tf(f)),b=this.tf(b),m-=e,this.Ti()?(0,D.yF)(this,d,c-b-m):(0,D.yF)(this,d,b),(0,D.zF)(this,d,m),(0,D.AF)(this),d=this.S,b=this.Tg,m=this.Jh,e=D.xw.Te(b,m,1,c),c=D.xw.Te(b,m,2,c),e=D.xw.tf(b,m,e,d),this.i1=D.xw.tf(b,m,c,d)-e);this.ifa!=D.q&&(this.k1=window.Math.max(0,D.xw.tf(this.Tg,this.Jh,this.ifa,this.S)));0<this.k1&&(c=this.k1/this.i1,this.Ti()&&(c=0-c),(0,D.ex)(this,c))};
D.$w.prototype.render=D.$w.prototype.L;D.C=D.$w.prototype;D.C.xla=function(){return new D.IF(this)};D.C.Uu=function(b){return this.xla(b).parse(b)};
D.C.Fo=function(b){this.Tg=b.start;this.Jh=b.end;this.S=b.width;this.qia=b.c8;this.a0=b.currentTime;this.ifa=b.LEa;this.Gta=b.GAa;this.fq=window.Math.max(0,b.uFa);this.tG=window.Math.max(0,b.tGa);(0,window.isNaN)(this.fq)&&(this.fq=0);(0,window.isNaN)(this.tG)&&(this.tG=0);this.az=b.orientation;this.YS=b.hna;this.Afa=b.yV;b.rka!=D.q&&(this.wR=b.rka.split(" "));b.B7!=D.q&&0<b.B7&&(this.Fga=b.B7);this.oua=b.PAa;this.sM=b.Nna;b.Nna!=D.q&&(this.rM=this.sM.XGa);this.K0=b.UBa;this.pua=b.borderTopStyle;
this.l_=b.borderTopColor;this.YT=b.K8;this.lAa=b.Una;this.tAa=b.S8;this.rAa=b.Q8;this.nAa=b.M8;this.pAa=b.O8;this.sAa=b.R8;this.qAa=b.P8;this.mAa=b.L8;this.oAa=b.N8;this.Kwa=b.Y6;this.LK=b.U6;this.W0=b.Mla;this.Uea=b.ama;this.Rea=b.Xla;this.lya=b.E7;this.dva=b.m5;this.Xza=b.E8;this.Vza=b.Lna;this.Wza=b.Mna;this.aga=b.Ama;this.wxa=b.zma;this.xia=b.yna;this.tza=b.xna};D.C.tf=function(b){return window.Math.max(0,D.xw.tf(this.Tg,this.Jh,b,(0,D.HF)(this)))+this.fq};
D.C.Te=function(b){return D.xw.Te(this.Tg,this.Jh,window.Math.max(0,b-this.fq),(0,D.HF)(this))};D.C.Ti=function(){return!this.pc()&&"true"==this.Afa};D.C.pc=function(){return"vertical"==this.az};D.HF=function(b){return b.pc()?b.Lb-b.fq-b.tG:b.ub-b.fq-b.tG};D.wF=function(b){return b.pc()?b.Lb-b.tG:b.ub-b.tG};D.xF=function(b){return b.e2!=D.q?b.e2:b.Fga!=D.q?(b.e2=D.xw.tf(b.Tg,b.Jh,b.Tg+b.Fga,(0,D.HF)(b)),b.e2):10};D.EF=function(){return D.xw.dm()?(0,D.DF)()/2:0};
D.DF=function(){return D.xw.dm()?30:10};D.JF=function(b){var c=b.getId();return"lh"==c||"rh"==c||"lhb"==c||"rhb"==c||"grpy"==c||"lbgrh"==c||"rbgrh"==c||b.getParent()!=D.q&&"grpy"==b.getParent().getId()};D.$w.prototype.lN=function(){if(this.sM==D.q)return 0;if(this.tM==D.q){var b=(0,window.parseInt)(this.sM.width,10);this.tM=!(0,window.isNaN)(b)&&b<this.ub?b:40}return this.tM};
D.$w.prototype.dk=function(){if(this.sM==D.q)return 0;if(this.lja==D.q){var b=(0,window.parseInt)(this.sM.height,10);this.lja=!(0,window.isNaN)(b)&&b<this.Lb?b:20}return this.lja};D.KF=function(b){return D.xw.dm()&&b.targetTouches!=D.q?0<b.targetTouches.length?b.targetTouches[0].pageX:D.q:b.pageX};D.LF=function(b){return D.xw.dm()&&b.targetTouches!=D.q?0<b.targetTouches.length?b.targetTouches[0].pageY:D.q:b.pageY};D.$w.prototype.Wq=(0,D.ca)(D.t);D.MF=function(b){return b.Wq()?b.ca(3):D.q};
D.NF=function(b){return b.Wq()?b.ca(4):D.q};D.OF=function(b){return b.Wq()&&!(0,D.BF)(b)?b.ca(6):D.q};D.PF=function(b,c,d,e){b.pc()?(-1!=d&&c.Jj(d),-1!=e&&c.jl(e)):(-1!=d&&c.mk(d),-1!=e&&c.wi(e))};D.QF=function(b,c){return b.pc()?c.Qm():c.ek()};D.$w.prototype.rF=function(b){b=b.target;if(b!=D.q){var c=b.getId();if(c==D.q)return D.q;if("_border"==c.substr(c.length-7))return this.O5(b);if("tick"!=c.substr(0,4)&&"ltb"!=c&&"rtb"!=c&&"bb"!=c&&"tab"!=c)return b}return D.q};
D.cx=function(b){return"window"==b.getId()||"ftr"==b.getId()||"sta"==b.getId()||(0,D.JF)(b)?D.n:D.t};D.$w.prototype.su=function(){return window&&window.su};D.$w.prototype.kH=function(b,c){var d=new D.af(this.e,0,0,b,c,"bg");d.la(this.lya);(0,D.bn)(d);this.k(d);return d};D.FF=function(b,c,d){return new D.kf(b.e,b.W0,(c-b.Uea)/2,(d-b.Rea)/2,b.Uea,b.Rea,"grpy")};
D.GF=function(b,c){var d=new D.Q(b.e,"grpy"),e=b.Kwa;if(b.pc()){for(var f=8+c,g=3,h=0;9>h;h++){var j=new D.cn(b.e,f+2*h,g,f+2*h+1,g,"dot1"+h);j.La(e);d.k(j);g+=2;j=new D.cn(b.e,f+1+2*h,g,f+1+2*h+1,g,"dot2"+h);j.La(e);d.k(j);g+=2;j=new D.cn(b.e,f+2*h,g,f+2*h+1,g,"dot3"+h);j.La(e);d.k(j);g=3}j=new D.cn(b.e,f+18,g,f+18+1,g,"dot4");j.La(e);d.k(j);g+=4;j=new D.cn(b.e,f+18,g,f+18+1,g,"dot5")}else{f=3;g=8+c;for(h=0;9>h;h++)j=new D.cn(b.e,f,g+2*h,f,g+2*h+1,"dot1"+h),j.La(e),d.k(j),f+=2,j=new D.cn(b.e,f,g+
1+2*h,f,g+1+2*h+1,"dot2"+h),j.La(e),d.k(j),f+=2,j=new D.cn(b.e,f,g+2*h,f,g+2*h+1,"dot3"+h),j.La(e),d.k(j),f=3;j=new D.cn(b.e,f,g+18,f,g+18+1,"dot4");j.La(e);d.k(j);f+=4;j=new D.cn(b.e,f,g+18,f,g+18+1,"dot5")}j.La(e);d.k(j);(0,D.bn)(d);return d};D.RF=function(b,c){return b.pc()?c.getHeight():c.getWidth()};D.CF=function(b,c){return b.pc()?c.K():c.M()};
D.yF=function(b,c,d){d=window.Math.max(0,d);b.pc()?c.O(d):c.F(d);if(b.Wq()){(0,D.MF)(b).ha(d);c=d+(0,D.RF)(b,c);var e=(0,D.NF)(b);e.da(c);e.ha(window.Math.max(0,b.ub-c));D.xw.dm()&&!(0,D.BF)(b)&&(e=(0,D.EF)(),(b.Wq()&&!(0,D.BF)(b)?b.ca(5):D.q).da(d-e),(0,D.OF)(b).da(c))}};
D.zF=function(b,c,d){d=window.Math.max((0,D.xF)(b),d);var e=d=window.Math.min(b.pc()?b.Lb:b.ub,d);b.pc()?c.ua(e):c.ha(e);if(b.Wq()){var e=(0,D.CF)(b,c)+d,f=(0,D.NF)(b);f.da(e);f.ha(window.Math.max(0,b.ub-e));D.xw.dm()&&!(0,D.BF)(b)&&(0,D.OF)(b).da(e)}(0,D.BF)(b)||(e=c.ca(3),f=c.ca(4),c=c.ca(5),b.pc()?(f.O(d),e.O(d-(0,D.DF)()),c.O(d-10)):(f.F(d),e.F(d-(0,D.DF)()),c.F(d-10)))};
D.$w.prototype.Sna=function(b,c){if(this.rM!=D.q){this.pc();for(var d=(0,D.HF)(this),e=0;e<this.rM.length;e++){var f=this.rM[e],g=(0,window.parseInt)(f.o("time"),10),g=this.tf(g),f=f.o("label"),h=0;e+1<this.rM.length?(h=(0,window.parseInt)(this.rM[e+1].o("time"),10),h=this.tf(h)-g):h=d-g;this.Ti()&&(g=d-g);this.fU(g,b,c,"tick"+e);this.O4(g,f,b,c,h,"label"+e)}}};
D.$w.prototype.fU=function(b,c,d,e){b=this.pc()?new D.cn(this.e,0,b,c,b,e):new D.cn(this.e,b,0,b,d,e);c=new D.ff(this.Xza);c.V(1,3);b.Z(c);(0,D.bn)(b);this.k(b)};D.$w.prototype.O4=function(b,c,d,e,f,g){this.pc()?b=new D.ph(this.e,c,4,b,g):(d="above"==this.YS?2:e-this.dk()+2,b=new D.ph(this.e,c,b+5,d,g));b.Ha(new D.K("font-weight:bold"));D.Kl.Ub(b,f,window.Infinity,this);b.Hya=b.Aq};D.$w.prototype.LN=(0,D.w)();
D.ex=function(b,c){var d=b.ca(1);d.ca(3);d.ca(4);d.ca(5);if(c!=(0,D.CF)(b,d)){var e=b.ca(b.Ca()-b.An),f=b.ca(b.Ca()-(b.An-1)),g=b.ca(b.Ca()-(b.An-2)),h=b.ca(b.Ca()-(b.An-3)),j=b.ca(b.Ca()-(b.An-4)),m=b.ca(b.Ca()-(b.An-5));if(b.pc())var o=d.K,p=d.O,r=e.Qm,u=e.Jj,v=e.Rq,z=e.jl,A=f.Qm,F=f.Jj,E=f.Rq,J=f.jl,M=g.Rq,L=g.jl,S=h.Qm,U=h.Jj,$=j.Qm,ya=j.Jj,ra=j.Rq,ua=j.jl,Bb=m.Qm,lb=m.Jj,Ja=m.Rq,Kb=m.jl;else o=d.M,p=d.F,r=e.ek,u=e.mk,v=e.Tn,z=e.wi,A=f.ek,F=f.mk,E=f.Tn,J=f.wi,M=g.Tn,L=g.wi,S=h.ek,U=h.mk,$=j.ek,
ya=j.mk,ra=j.Tn,ua=j.wi,Bb=m.ek,lb=m.mk,Ja=m.Tn,Kb=m.wi;var Db=b.fq,Nd=(0,D.wF)(b),tc=(0,D.RF)(b,d);c=window.Math.max(Db,window.Math.min(Nd-tc,c));Db="off"!==b.Gta?new D.Ef(b.e,0.5,0,D.Jw):D.q;(0,D.SF)(Db,d,o,p,c);(0,D.SF)(Db,e,r,u,c);(0,D.SF)(Db,e,v,z,c);(0,D.SF)(Db,f,A,F,c+tc);(0,D.SF)(Db,f,E,J,c+tc);(0,D.SF)(Db,g,M,L,c+1);(0,D.SF)(Db,h,S,U,c+tc-1);(0,D.SF)(Db,j,$,ya,c);(0,D.SF)(Db,m,Bb,lb,c);(0,D.SF)(Db,j,ra,ua,c+tc);(0,D.SF)(Db,m,Ja,Kb,c+tc);b.Wq()&&(d=(0,D.MF)(b),(0,D.SF)(Db,d,d.getWidth,d.ha,
c),tc=c+tc,d=(0,D.NF)(b),e=d.getWidth,f=d.ha,g=d.ea,h=d.da,j=b.pc()?b.Lb:b.ub,(0,D.SF)(Db,d,e,f,j-tc),(0,D.SF)(Db,d,g,h,tc),D.xw.dm()&&!(0,D.BF)(b)&&(d=(0,D.EF)(),e=b.Wq()&&!(0,D.BF)(b)?b.ca(5):D.q,f=e.ea,g=e.da,h=(0,D.OF)(b),j=h.ea,m=h.da,(0,D.SF)(Db,e,f,g,c-d),(0,D.SF)(Db,h,j,m,tc)));Db!=D.q&&Db.play()}};D.SF=function(b,c,d,e,f){b!=D.q?(0,D.P)(b,"typeNumber",c,d,e,f):e.call(c,f)};
D.$w.prototype.JX=function(b){var c=this.rF(b);if(c&&!("bg"==c.getId()||"ocd"==c.getId()))if("label"==c.getId().substr(0,5)&&c instanceof D.ph)c.kg()&&this.e.Vd().qI(b.pageX,b.pageY,c.Hya,"#000000");else if(this.sG!=D.q&&(0,D.JF)(c)&&(b=(0,D.Pg)(this.e,b.pageX,b.pageY),b=this.Eb(b),this.pc()?(0,D.jg)(this.sG,b.x+6,b.y-10):(0,D.jg)(this.sG,b.x-6,b.y-20),this.sG.bb(D.n)),"window"==c.getId()||"ftr"==c.getId()||"arr"==c.getId()||(0,D.JF)(c))this.su()&&this.setCursor("move");else return c};
D.$w.prototype.IX=function(b){this.Am==D.q&&this.setCursor("default");b=this.rF(b);if(b!=D.q)return(0,D.JF)(b)&&this.sG!=D.q&&this.sG.bb(D.t),b};
D.$w.prototype.OI=function(b,c,d){b.stopPropagation();var e=this.rF(b);if(e&&!("window"==e.getId()||(0,D.JF)(e)))if("bg"==e.getId()||"label"==e.getId().substr(0,5)||"ocd"==e.getId()||"lbg"==e.getId()||"rbg"==e.getId()){c==D.k&&(c=b.pageX);d==D.k&&(d=b.pageY);b=(0,D.Pg)(this.e,c,d);b=this.Eb(b);this.pc()?(d=b.y,e=this.Lb):(d=b.x,e=this.ub);b=this.ca(1);c=d-(0,D.RF)(this,b)/2;(0,D.ex)(this,c);this.Ti()&&(d=this.ub-d);var f=this.Te(d);d=new D.ww("scrollTime");d.setTime(f);c=window.Math.max(0,window.Math.min(c,
e-(0,D.RF)(this,b)));this.Ti()?(e=this.Te(this.ub-(c+(0,D.RF)(this,b))),b=this.Te(this.ub-c)):(e=this.Te(c),b=this.Te(c+(0,D.RF)(this,b)));(0,D.TF)(d,e);(0,D.UF)(d,b);this.dispatchEvent(d)}else return e};D.$w.prototype.Ep=function(b){(0,D.VF)(this,b)};
D.VF=function(b,c){c.stopPropagation();var d=b.rF(c);if(d!=D.q&&(0,D.cx)(d)){if("ftr"==d.getId()||"sta"==d.getId())d=b.ca(1);b.UR=(0,D.KF)(c);b.hfa=(0,D.LF)(c);if((0,D.JF)(d)){var e=b.ca(1);b.Ti()?(b.m2=b.ub-e.ea(),b.v2=b.m2-e.getWidth()):(b.v2=e.ea(),b.m2=b.v2+e.getWidth());"grpy"==d.getParent().getId()&&(d=d.getParent());var f=d.getId();"grpy"==f&&(d=e.IU(d),f=d.getId());if("lh"==f||"rh"==f)d=e.IU(d),f=d.getId();"lbgrh"==f&&(d=e.ca(0));"rbgrh"==f&&(d=e.ca(e.Ca()-3));D.xw.dm()||(b.pc()?(d.ta(-20),
d.ua(2*(d.getHeight()+20))):(d.da(-20),d.ha(2*(d.getWidth()+20))));e=d.getCursor();f=b.ca(1);f!=D.q&&f.setCursor(e);if(b.Wq()){var f=(0,D.MF)(b),g=(0,D.NF)(b);f!=D.q&&g!=D.q&&(f.setCursor(e),g.setCursor(e))}}b.Am=d;d=new D.ww("dropCallback");b.dispatchEvent(d)}};D.$w.prototype.qo=function(b){(0,D.WF)(this,b)};
D.WF=function(b,c){c!=D.q&&c.stopPropagation();if(b.Am!=D.q){if("window"==b.Am.getId())b.vka(0,0,0);else if((0,D.JF)(b.Am)){b.B5();D.xw.dm()||(b.pc()?(b.Am.ta(0),b.Am.ua((0,D.DF)())):(b.Am.da(0),b.Am.ha((0,D.DF)())));var d=b.ca(1);d!=D.q&&d.setCursor("move");if(b.Wq()){var d=(0,D.MF)(b),e=(0,D.NF)(b);d!=D.q&&e!=D.q&&(d.setCursor("default"),e.setCursor("default"))}}b.Am=D.q;b.UR=-1}};D.$w.prototype.wA=function(b){(0,D.XF)(this,b)};
D.XF=function(b,c){c.stopPropagation();if(b.Am!=D.q&&-1!=b.UR){var d=(0,D.KF)(c),e=(0,D.LF)(c),f=d-b.UR,g=e-b.hfa;b.UR=d;b.hfa=e;"window"==b.Am.getId()?b.bma(0,f,g):"lh"==b.Am.getId()||"lhb"==b.Am.getId()?(0,D.YF)(b,c,f,g,D.n):("rh"==b.Am.getId()||"rhb"==b.Am.getId())&&b.X6(c,f,g)}};D.C=D.$w.prototype;
D.C.RX=function(b){var c=b.targetTouches[0];this.UG=c.pageX;this.GC=c.pageY;2==b.targetTouches.length?(b.preventDefault(),c=b.targetTouches[1],this.VG=c.pageX,this.AM=c.pageY,20>window.Math.abs(this.GC-this.AM)?this.hK=0:this.AM=this.VG=this.GC=this.UG=D.q):(0,D.VF)(this,b)};
D.C.QX=function(b){b.preventDefault();if(this.VG!=D.q&&this.AM!=D.q)if(50>this.hK)this.hK++;else{var c=b.targetTouches[1];this.X6(D.q,c.pageX-this.VG,0);this.VG=c.pageX;this.hK=0}else{c=b.targetTouches[0];if(this.UG!=c.pageX||this.GC!=c.pageY)this.GC=this.UG=D.q;(0,D.XF)(this,b)}};D.C.MX=function(b){this.VG!=D.q&&this.AM!=D.q?this.B5():((0,D.WF)(this,b),this.UG!=D.q&&this.GC!=D.q&&this.OI(b,this.UG,this.GC));this.AM=this.VG=this.GC=this.UG=D.q};
D.C.l$=function(b){var c=b.keyCode;if(37===c||39===c)c=37===c?-1:1,(b.shiftKey?this.X6:this.bma).call(this,b,c,c)};D.C.m$=function(b){var c=b.keyCode;if(37===c||39===c)c=37===c?-1:1,(b.shiftKey?this.B5:this.vka).call(this,b,c,c)};D.C.bma=function(b,c,d){(0,D.ZF)(this,"scrollPos",c,d)};D.C.vka=function(b,c,d){(0,D.ZF)(this,"scrollEnd",c,d)};
D.ZF=function(b,c,d,e){var f=b.ca(1),g=(0,D.CF)(b,f),h=(0,D.RF)(b,f),j=b.fq,m=(0,D.wF)(b);d=b.pc()?e:d;g+d<=j?((0,D.yF)(b,f,j),h=b.Ti()?-2:-1):g+h+d>=m?((0,D.yF)(b,f,m-h),h=b.Ti()?-1:-2):((0,D.yF)(b,f,g+d),h=b.Ti()?(m-h-g-b.fq)*b.i1:(g-b.fq)*b.i1);(0,D.AF)(b);c=new D.ww(c);c.bh(h);b.Ti()?(h=b.Te(b.ub-(g+(0,D.RF)(b,f))),f=b.Te(b.ub-g)):(h=b.Te(g),f=b.Te(g+(0,D.RF)(b,f)));(0,D.TF)(c,h);(0,D.UF)(c,f);b.dispatchEvent(c)};D.$w.prototype.X6=function(b,c,d){(0,D.YF)(this,b,c,d,D.t)};
D.YF=function(b,c,d,e,f){var g=(0,D.HF)(b);e=b.pc()?e:d;if(0!=e){d=b.ca(1);var h=(0,D.CF)(b,d),j=(0,D.RF)(b,d);if(f){if(j-e<=(0,D.xF)(b)||h+e<=b.fq)return;c=b.pc()?(0,D.Pg)(b.e,(0,D.KF)(c),(0,D.LF)(c)).y:(0,D.Pg)(b.e,(0,D.KF)(c),(0,D.LF)(c)).x;c=b.Eb(c);if(0<e&&c<=h||0>e&&c>=h)return;(0,D.yF)(b,d,h+e);(0,D.zF)(b,d,j-e)}else{if(j+e<=(0,D.xF)(b)||h+j+e>=(0,D.wF)(b))return;c=b.pc()?(0,D.Pg)(b.e,(0,D.KF)(c),(0,D.LF)(c)).y:(0,D.Pg)(b.e,(0,D.KF)(c),(0,D.LF)(c)).x;c=b.Eb(c);if(0<e&&c<=h+j||0>e&&c>=h+j)return;
(0,D.zF)(b,d,j+e)}(0,D.AF)(b);c=b.Te((0,D.RF)(b,d));c=g*(b.Jh-b.Tg)/(c-b.Tg);b.sma()&&(g=new D.ww("rangeChanging"),(0,D.Mf)(g,"newSize",c),c=b.Ti()?f:!f,(0,D.Mf)(g,"endHandle",c),f?(0,D.Mf)(g,"expand",0>e):(0,D.Mf)(g,"expand",0<e),b.Ti()?(f=b.Te(b.ub-((0,D.CF)(b,d)+(0,D.RF)(b,d))),d=b.Te(b.ub-(0,D.CF)(b,d))):(f=b.Te((0,D.CF)(b,d)),d=b.Te((0,D.CF)(b,d)+(0,D.RF)(b,d))),(0,D.TF)(g,f),(0,D.UF)(g,d),b.dispatchEvent(g))}};D.$w.prototype.sma=(0,D.ca)(D.n);
D.$w.prototype.B5=function(){var b=this.Tg,c=this.Jh,d=this.S,e=(0,D.HF)(this),f=this.ca(1),g=this.Te((0,D.RF)(this,f)),b=e*(c-b)/(g-b),c=this.Te(this.v2),e=this.Te(this.m2);this.Ti()?(g=this.Te(this.ub-((0,D.CF)(this,f)+(0,D.RF)(this,f))),f=this.Te(this.ub-(0,D.CF)(this,f))):(g=this.Te((0,D.CF)(this,f)),f=this.Te((0,D.CF)(this,f)+(0,D.RF)(this,f)));var h=new D.ww("rangeChange");(0,D.Mf)(h,"oldSize",d);(0,D.Mf)(h,"newSize",b);(0,D.Mf)(h,"oldStartTime",c);(0,D.Mf)(h,"oldEndTime",e);(0,D.TF)(h,g);(0,D.UF)(h,
f);this.dispatchEvent(h)};D.AF=function(b){var c=b.ca(1),d=b.ca(b.Ca()-b.An),e=b.ca(b.Ca()-(b.An-1)),f=b.ca(b.Ca()-(b.An-2)),g=b.ca(b.Ca()-(b.An-3)),h=b.ca(b.Ca()-(b.An-4)),j=b.ca(b.Ca()-(b.An-5));(0,D.PF)(b,d,(0,D.CF)(b,c),(0,D.CF)(b,c));(0,D.PF)(b,e,(0,D.CF)(b,c)+(0,D.RF)(b,c),(0,D.CF)(b,c)+(0,D.RF)(b,c));(0,D.PF)(b,f,-1,(0,D.CF)(b,c)+1);(0,D.PF)(b,g,(0,D.QF)(b,e)-1,-1);(0,D.PF)(b,h,(0,D.QF)(b,d),(0,D.QF)(b,e));(0,D.PF)(b,j,(0,D.QF)(b,d),(0,D.QF)(b,e))};
D.$w.prototype.dispatchEvent=function(b){D.Nw.dispatchEvent(this.hb,this.ka,this,b)};
D.IF=function(b){this.Init(b)};D.D.l(D.IF,D.D,"DvtOverviewParser");D.IF.prototype.Init=(0,D.ba)("I");D.IF.prototype.parse=function(b){return this.gm(b)};
D.IF.prototype.gm=function(b){var c={};c.GAa=b.animationOnClick;b.startTime!=D.q&&(c.start=b.startTime);b.endTime!=D.q&&(c.end=b.endTime);c.start==D.q&&(c.start=(new window.Date).getTime());if(c.end==D.q||c.end<=c.start)c.end=c.start+864E5;b.currentTime!=D.q&&(c.currentTime=b.currentTime);b.initialFocusTime!=D.q&&(c.LEa=b.initialFocusTime);c.orientation="horizontal";b.orientation!=D.q&&(c.orientation=b.orientation);c.rka=b.featuresOff;c.B7=b.minimumWindowSize;c.uFa=b.leftMargin;c.tGa=b.rightMargin;
if(b.viewportEndTime!=D.q){var d=b.viewportEndTime,e=c.start;b.viewportStartTime!=D.q&&b.viewportStartTime<d&&(e=b.viewportStartTime);c.width=b.viewportEndPos!=D.q?(0,D.$F)(c.start,c.end,e,d,b.viewportEndPos):(0,D.$F)(c.start,c.end,e,d,this.I.ub);c.c8=e}else c.c8=c.start;0==c.width&&(c.width=1E3);c.hna="below";c.TN="none";c.yV=(0,D.Qe)(this.I.e).toString();b.rtl!=D.q&&(c.yV=b.rtl.toString());c.U6="#FFFFFF";c.Y6="#B3C6DB";c.K8="#FFFFFF";c.Una=1;c.S8="solid";c.Q8="solid";c.M8="solid";c.O8="solid";c.R8=
"#4F4F4F";c.P8="#4F4F4F";c.L8="#4F4F4F";c.N8="#4F4F4F";c.E7="#E6ECF3";c.m5="#C000D1";c.E8="#BCC7D2";c.Lna="#e5e5e5";c.Mna=1;c.Ama="#FFFFFF";c.zma=0.7;c.yna="#FFFFFF";c.xna=0.7;b.style!=D.q&&(b.style.handleFillColor!=D.q&&(c.U6=b.style.handleFillColor),b.style.handleTextureColor!=D.q&&(c.Y6=b.style.handleTextureColor),b.style.handleBackgroundImage!=D.q&&(c.Mla=b.style.handleBackgroundImage),b.style.handleWidth!=D.q&&(c.ama=b.style.handleWidth),b.style.handleHeight!=D.q&&(c.Xla=b.style.handleHeight),
b.style.windowBackgroundColor!=D.q&&(c.K8=b.style.windowBackgroundColor),b.style.windowBackgroundAlpha!=D.q&&(c.Una=b.style.windowBackgroundAlpha),b.style.windowBorderTopStyle!=D.q&&(c.S8=b.style.windowBorderTopStyle),b.style.windowBorderRightStyle!=D.q&&(c.Q8=b.style.windowBorderRightStyle),b.style.windowBorderBottomStyle!=D.q&&(c.M8=b.style.windowBorderBottomStyle),b.style.windowBorderLeftStyle!=D.q&&(c.O8=b.style.windowBorderLeftStyle),b.style.windowBorderTopColor!=D.q&&(c.R8=b.style.windowBorderTopColor),
b.style.windowBorderRightColor!=D.q&&(c.P8=b.style.windowBorderRightColor),b.style.windowBorderBottomColor!=D.q&&(c.L8=b.style.windowBorderBottomColor),b.style.windowBorderLeftColor!=D.q&&(c.N8=b.style.windowBorderLeftColor),b.style.overviewBackgroundColor!=D.q&&(c.E7=b.style.overviewBackgroundColor),b.style.currentTimeIndicatorColor!=D.q&&(c.m5=b.style.currentTimeIndicatorColor),b.style.timeIndicatorColor!=D.q&&(c.E8=b.style.timeIndicatorColor),b.style.leftFilterPanelColor!=D.q&&(c.Ama=b.style.leftFilterPanelColor),
b.style.leftFilterPanelAlpha!=D.q&&(c.zma=b.style.leftFilterPanelAlpha),b.style.rightFilterPanelColor!=D.q&&(c.yna=b.style.rightFilterPanelColor),b.style.rightFilterPanelAlpha!=D.q&&(c.xna=b.style.rightFilterPanelAlpha));return c};D.$F=function(b,c,d,e,f){b=f*(c-b);d=e-d;return 0==b||0==d?0:b/d};
D.ww=function(b){this.Init("overview");this.Ml=b};D.D.l(D.ww,D.pf,"DvtOverviewEvent");D.ww.prototype.Pi=(0,D.B)("Ml");D.ww.prototype.setTime=function(b){(0,D.Mf)(this,"time",b)};D.ww.prototype.getTime=function(){return this.Dj("time")};D.TF=function(b,c){(0,D.Mf)(b,"newStartTime",c)};D.UF=function(b,c){(0,D.Mf)(b,"newEndTime",c)};D.ww.prototype.bh=function(b){(0,D.Mf)(this,"pos",b)};D.ww.prototype.Gf=function(){return this.Dj("pos")};
});