define(['./DvtToolkit'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.Bk=function(b,c,d){this.Init(b,c,d)};D.D.l(D.Bk,D.Q,"DvtComboBox");D.Bk.prototype.Init=function(b,c,d){D.Bk.q.Init.call(this,b,D.q,c);this.D=d;this.lS=[];this.tb=[];this.rja=[];this.In=0;this.a_=this.sQ=D.t;this.X1=new D.H(0,0,0,0);this.lc=new D.H(0,0,0,0);this.uM=b.Vd();this.q1=(0,D.wf)();this.rb=(0,D.VG)(this,c+"_cl");this.k(this.rb);this.eK=new D.Q(b);this.eK.ia(D.t);this.k(this.eK);this.a1=new D.Hg(b,100,this.rpa,this,1);this.yha=new D.Hg(b,100,this.xpa,this,1);this.v0=D.t};
D.Bk.prototype.iO=function(b){this.In=b;this.sQ||(0,D.WG)(this);b=new D.XG("cbItemChange",b,this.Og);this.Og=D.q;this.Sb(b)};
D.VG=function(b,c){var d=b.e,e=b.e,f=b.C(),f=new D.af(e,0,0,f.g,f.j,c+"_up");(0,D.Nv)(f,D.R.AY);(0,D.Yg)(f);f.k((0,D.YG)(e,f.getWidth(),f.getHeight()));var g=b.e,e=b.C(),e=new D.af(g,0,0,e.g,e.j,c+"_up");e.La(D.R.vO);e.G(new D.cf(0,[D.R.T9,D.R.S9]));(0,D.Nv)(e,D.R.AY);e.k((0,D.YG)(g,e.getWidth(),e.getHeight()));var g=b.e,h=b.C(),h=new D.af(g,0,0,h.g,h.j,c+"_up");(0,D.Nv)(h,D.R.AY);h.La(D.R.vO);h.G(new D.cf(0,[D.R.S9,D.R.T9]));h.k((0,D.YG)(g,h.getWidth(),h.getHeight()));d=new D.kh(d,f,e,h,D.q,c);(0,D.Lh)(d,
b.NI,b);d.setCursor("pointer");b.q1||d.W(D.Ar,b.g$,D.t,b);d.cB=D.n;return d};D.C=D.Bk.prototype;D.C.tj=function(b,c,d,e,f){b.ia(D.t);this.tb.push(b);this.rja.push(c);c=D.R.xm(this.e,d?d:b);var g=this.X1,h=this.C();c.g>g.g&&(g.g=c.g,h.g=c.g+16);c.j>g.j&&(g.j=c.j,h.j=c.j);this.X1=g;c=D.q;d&&(e&&f)&&(c=[],c[0]=d,c[1]=e,c[2]=f);this.lS.push(c);this.sQ||(this.removeChild(this.rb),this.rb=(0,D.VG)(this,b.getId()),this.Ia(this.rb,0),(0,D.WG)(this))};D.C.getItem=function(b){return this.tb[b]};
D.C.B6=function(){var b=this.In;return 0>b||b>this.tb.length-1?D.q:this.tb[b]};
D.C.NI=function(b){(0,D.Uh)(b);this.a_&&(this.a_=D.t,this.Tp&&(this.Tp.bb(D.t),this.Tp.getParent().removeChild(this.Tp),this.Tp=D.q));b=this.e;for(var c=this.D?this.D.comboBox:D.q,d=(0,D.zk)(c,"paddingLeft",0),e=(0,D.zk)(c,"paddingBottom",0),f=(0,D.zk)(c,"paddingRight",0),g=(0,D.zk)(c,"paddingInner",0),h=(0,D.zk)(c,"paddingTop",0),j=this.e,m,o,p,r=new D.Q(j,"__dd"),u=0;u<this.tb.length;u++)p=this.tb[u],m=D.R.xm(j,p),o=new D.Q(j,"__it"+u),(0,D.jg)(o,d,h),o.k(p),p.ia(D.n),p.setCursor("pointer"),h+=
m.j+g,this.sa&&(m=new D.Ek(this,this.ppa,this.g$,D.q,D.q,D.q,this.rja[u]),this.sa.ja(p,m)),r.k(o);c=D.R.yBa(j,this.X1.g+d+f,h+e-g,c);c.k(r);r=(0,D.zk)(this.D,"background-color",D.q);d=(0,D.zk)(this.D,"backgroundAlpha",1);c.La((0,D.zk)(this.D,"border-color",D.q),(0,D.zk)(this.D,"borderAlpha",1));r&&c.la(r,d);this.Tp=c;c=D.R.xm(b,this.Tp);this.k(this.Tp);r=this.rb.C();c=(0,D.Qe)(b)?-c.g+1*r.g/4:3*r.g/4;(0,D.jg)(this.Tp,c,3*r.j/4);this.rb.ia(D.t);(0,D.FA)(this.rb,D.n);this.Sb(new D.XG("cbShowDropdown"));
(b=b.Jc)&&(this.q1?b.W(D.xz.we,this.$O,D.n,this):b.W(D.Gr,this.$O,D.n,this))};D.C.rpa=function(){(0,D.Cp)(this);this.sQ||(0,D.WG)(this)};D.C.$O=function(){this.v0=D.t;this.yha.reset();this.yha.start()};D.C.xpa=function(){this.v0||(this.a1.reset(),this.a1.start())};D.C.g$=function(){(0,D.Uh)()};
D.C.ppa=function(b){this.v0=D.n;this.a1.stop();(0,D.Uh)(b);var c;c=b.target;for(var d,e;c;){if((e=c.getId())&&c instanceof D.Q&&"__it"==e.substr(0,4)){d=c;break}c=c.getParent()}c=d;var f;this.Tp&&c&&(d=this.Tp.ca(0))&&(f=d.Se(c));(0,D.Cp)(this);this.Og=b;this.iO(f)};D.Cp=function(b){b.Tp&&(b.Tp.bb(D.t),(0,D.FA)(b.rb,D.t),b.Sb(new D.XG("cbHideDropdown")),b.a_=D.n);var c=b.e.Jc;c&&(b.q1?c.Ra(D.xz.we,b.$O,D.n,b):c.Ra(D.Gr,b.$O,D.n,b));b.rb.ia(D.n)};D.Bk.prototype.C=(0,D.B)("lc");D.Bk.prototype.Mq=(0,D.B)("tb");
D.WG=function(b){var c=D.n,d=b.In;if(b.lS&&b.lS.length>d&&(d=b.lS[d])&&2<d.length)(0,D.Kh)(b.rb,d[0]),(0,D.Jh)(b.rb,d[1]),(0,D.Ih)(b.rb,d[2]),c=D.t;c&&(0<b.eK.Ca()&&b.eK.up(0),b.eK.k(b.B6()))};D.YG=function(b,c,d){var e=[];e.push(c-12,d/2-2);e.push(c-4,d/2-2);e.push(c-8,d/2+2);e.push(c-12,d/2-2);b=new D.Lv(b,e,D.q);b.La(D.R.vO);b.la(D.R.vO);b.ia(D.t);return b};D.Bk.prototype.lW=(0,D.ba)("sa");D.ZG=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.D.l(D.ZG,D.af,"DropdownItemSprite");
D.ZG.prototype.Init=function(b){D.af.q.Init.call(this,b)};
D.XG=function(b,c,d){this.Init(b,c,d)};D.D.l(D.XG,D.$G,"DvtComboBoxEvent");D.XG.prototype.Init=function(b,c,d){D.XG.q.Init.call(this,"comboBoxEvent");c===D.k&&(c=-1);this.sI=b;this.KB=c;this.nF=d};D.XG.prototype.Fa=(0,D.B)("KB");
D.WD=function(b,c,d){this.Init(b,c,d)};D.D.l(D.WD,D.Q,"DvtBaseControl");D.WD.prototype.Init=function(b,c,d){D.WD.q.Init.call(this,b);this.ba=c;this.e=b;this.uM=b.Vd();this.ed=d};D.WD.prototype.Vd=(0,D.B)("uM");
D.JG=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.JG,D.WD,"DvtZoomInButton");D.C=D.JG.prototype;D.C.Init=function(b,c,d,e,f){D.JG.q.Init.call(this,b,d,e);this.e_=D.t;this.bU=new D.Hg(b,100,this.Npa,this);this.JC=new D.Hg(b,250,this.SX,this,1);this.Jm=c;(0,D.Lh)(this.Jm,this.Lpa,this);this.sa=f;b=new D.Ek(this,D.q,this.Mpa,this.K$,this.K$,D.q,(0,D.wg)(this.ed,"CONTROL_PANEL_ZOOMIN"));this.sa.ja(this.Jm,b);this.k(this.Jm)};
D.C.Lpa=function(){if(!this.bU.Zg()){var b=this.ba.zc(),b=(0,D.my)(this.ba,b),c=new D.Ef(this.e,this.ba.Qa());(0,D.qs)(this.ba,b,D.k,D.k,c);c.play()}};D.C.Mpa=function(){this.e_=D.n;this.bU.stop();this.JC.stop();this.JC.start()};D.C.K$=function(){this.e_&&(this.e_=D.t,this.bU.stop(),this.JC.stop())};D.C.SX=function(){this.bU.start()};D.C.Npa=function(){var b=this.ba.zc();(0,D.qs)(this.ba,(0,D.my)(this.ba,b))};D.C.ah=function(b){this.Jm.setCursor(b?"pointer":D.q);this.Jm.ah(b);(0,D.XD)(this.Jm)};
D.KG=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.KG,D.WD,"DvtZoomOutButton");D.C=D.KG.prototype;D.C.Init=function(b,c,d,e,f){D.KG.q.Init.call(this,b,d,e);this.f_=D.t;this.cU=new D.Hg(b,100,this.Qpa,this);this.JC=new D.Hg(b,250,this.SX,this,1);this.Km=c;(0,D.Lh)(this.Km,this.Opa,this);this.sa=f;b=new D.Ek(this,D.q,this.Ppa,this.L$,this.L$,D.q,(0,D.wg)(this.ed,"CONTROL_PANEL_ZOOMOUT"));this.sa.ja(this.Km,b);this.k(this.Km)};
D.C.Opa=function(){if(!this.cU.Zg()){var b=this.ba.zc(),b=(0,D.ny)(this.ba,b),c=new D.Ef(this.e,this.ba.Qa());(0,D.qs)(this.ba,b,D.k,D.k,c);c.play()}};D.C.Ppa=function(){this.f_=D.n;this.cU.stop();this.JC.stop();this.JC.start()};D.C.L$=function(){this.f_&&(this.f_=D.t,this.cU.stop(),this.JC.stop())};D.C.SX=function(){this.cU.start()};D.C.Qpa=function(){var b=this.ba.zc();(0,D.qs)(this.ba,(0,D.ny)(this.ba,b))};D.C.ah=function(b){this.Km.setCursor(b?"pointer":D.q);this.Km.ah(b);(0,D.XD)(this.Km)};
D.LG=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.LG,D.WD,"DvtZoomToFitButton");D.LG.prototype.Init=function(b,c,d,e,f){D.LG.q.Init.call(this,b,d,e);this.cu=c;(0,D.Lh)(this.cu,this.Rpa,this);this.cu.setCursor("pointer");this.sa=f;b=new D.Ek(this,D.q,D.q,D.q,D.q,D.q,(0,D.wg)(this.ed,"CONTROL_PANEL_ZOOMTOFIT"));this.sa.ja(this.cu,b);this.k(this.cu)};D.LG.prototype.Rpa=function(){var b=new D.Ef(this.e,this.ba.Qa());this.ba.io(b);b.play()};
D.MG=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.D.l(D.MG,D.WD,"DvtPanControl");D.C=D.MG.prototype;
D.C.Init=function(b,c,d,e,f,g,h){D.MG.q.Init.call(this,b,e,f);this.Gha=new D.Hg(b,50,this.Hpa,this);this.PJ=D.t;this.aT=new D.G(20,20);this.Io=g?g:16777215;c.k(d);d&&(this.Qk=d,this.Qk.bb(D.t),this.Qk.W(D.xz.we,this.s$,D.t,this),(0,D.wf)()||(this.Qk.W(D.bi,this.s$,D.t,this),this.Qk.W(D.Ar,this.ypa,D.t,this),this.Qk.W(D.Gr,this.Cpa,D.t,this),this.Qk.W(D.Mh,this.Bpa,D.t,this),this.Qk.W(D.Nh,this.Apa,D.t,this)),this.Qk.W(D.Gk,this.zpa,D.t,this));this.En=c;this.En.W(D.xz.we,this.t$,D.t,this);(0,D.wf)()||
(this.En.W(D.bi,this.t$,D.t,this),this.En.W(D.Ar,this.Dpa,D.t,this),this.En.W(D.Gr,this.u$,D.t,this),this.En.W(D.Mh,this.Gpa,D.t,this),this.En.W(D.Nh,this.Fpa,D.t,this),this.En.W(D.Gk,this.Epa,D.t,this));this.Qt=D.R.fBa(b,h);this.Qt.k(this.En);this.k(this.Qt)};D.C.t$=function(b){(0,D.Uh)(b)};D.C.Dpa=function(b){(0,D.Uh)(b);this.PJ=D.n;this.Qk&&this.Qk.bb(D.t);b=(0,D.ky)(this.ba,b);b=this.En.Eb(b);(0,D.NG)(this,b.x,b.y,this.En.Wg);this.O2=new D.G(b.x,b.y);this.Gha.start();this.Hha=0};
D.C.u$=function(b){this.PJ&&((0,D.Uh)(b),this.PJ=D.t,this.Qk&&this.Qk.bb(D.n),this.Gha.stop());this.En.Wr(b);this.Vd().tc()};D.C.Gpa=function(b){this.Qk&&this.Qk.bb(D.n);var c=(0,D.wg)(this.ed,"CONTROL_PANEL_PAN");this.Vd().nO(b.pageX,b.pageY,c,b.target)};D.C.Fpa=function(b){this.u$(b);this.Qk&&this.Qk.bb(D.t)};D.C.Epa=function(b){(0,D.Uh)(b);b=(0,D.ky)(this.ba,b);b=this.En.Eb(b);this.PJ?((0,D.NG)(this,b.x,b.y,this.En.Wg),this.O2=new D.G(b.x,b.y)):(0,D.NG)(this,b.x,b.y,this.En.zh)};
D.C.Hpa=function(){if(this.PJ){var b=window.Math.atan2(this.aT.y-this.O2.y,this.aT.x-this.O2.x),c=window.Math.cos(b),b=window.Math.sin(b),d=15;this.Hha++;40<this.Hha&&(d*=3);this.ba.jk(d*c,d*b)}};D.C.s$=function(b){(0,D.Uh)(b);this.ba.yW()};D.C.ypa=function(b){(0,D.Uh)(b)};D.C.Cpa=function(b){(0,D.Uh)(b);this.Vd().tc()};D.C.Bpa=function(b){var c=(0,D.wg)(this.ed,"CONTROL_PANEL_ZOOMANDCENTER");this.Vd().nO(b.pageX,b.pageY,c,b.target);this.Qk.bb(D.n);(0,D.Uh)(b)};
D.C.Apa=function(b){this.Vd().tc();(0,D.Uh)(b)};D.C.zpa=function(b){(0,D.Uh)(b)};D.NG=function(b,c,d,e){e.Zi(window.Math.atan2(d-b.aT.y,c-b.aT.x)-window.Math.PI/4)};
D.SG=function(b){this.Init("dvtPZCPExpand");this.Ml=b};D.D.l(D.SG,D.pf,"DvtControlPanelEvent");D.SG.prototype.Pi=(0,D.B)("Ml");
D.Ap=function(b,c,d){this.Init(b,c,d)};D.D.l(D.Ap,D.Q,"DvtControlPanel");D.OG=[0,0.25,0.5,0.75,1];
D.Ap.prototype.Init=function(b,c,d){D.Ap.q.Init.call(this,b);this.ZZ=this.oQ=D.t;this.ba=c.ba;this.Io=c.Bl;this.ed=c.Kc();this.yl=(0,D.lh)(c);this.uM=b.Vd();this.D=D.q;if(this.I=c)this.D=this.I.ts(),this.D.centerButtonDisplayed||(this.Io&=-17,this.I.Bl=this.Io);this.zAa=D.OG;this.ln=D.t;this.Qj=this.D.backgroundAlpha;this.sa=new D.Zx(b,D.q,c);this.sa.bs.push(D.Ap);this.sa.rf(this);this.sa.ja(this,this);this.od=d;this.mLa=D.t;(0,D.bn)(this)};D.Ap.prototype.Vd=(0,D.B)("uM");
D.sy=function(b){b.oQ=D.n;b.Za.ia(D.t);b.Ad.ia(D.t);b.Za.B(b.D.backgroundDragAlpha);b.Ad.B(b.D.borderDragAlpha)};D.xy=function(b){b.oQ=D.t;b.Za.ia(D.n);b.Ad.ia(D.n);b.ZZ?b.em(D.q):b.nl(D.q)};D.Ap.prototype.SH=(0,D.ca)(D.n);D.Ap.prototype.Sn=function(){var b=0,b=this.SH()?D.tv.mV():D.tv.Sn();return window.Math.max((0,D.zk)(this.D,"tabSize",0),b)};
D.PG=function(b){var c=b.e,d=new D.Q(c),e=b.Sn(),f=(0,D.Qe)(c);b.Za=D.tv.Xja(c,e,b.D,f);b.Ad=D.tv.f5(c,e,b.D,f);b.Eua=D.R.xm(c,b.Ad);b.Ec=D.R.rU(b.e,b.yl,b.Sn(),b.D,f);(0,D.Lh)(b.Ec,b.NI,b);b.Ec.setCursor("pointer");c=new D.Ek(b,D.q,D.q,D.q,D.q,D.q,(0,D.wg)(b.ed,"CONTROL_PANEL"));b.sa.ja(b.Ec,c);b.Ad.k(b.Ec);d.k(b.Za);d.k(b.Ad);return d};
D.QG=function(b){var c=b.e,d=new D.Q(c);b.Za=new D.Q(c);b.Ad=new D.Q(c);d.k(b.Za);d.k(b.Ad);var e=(0,D.Qe)(c),f=0,g=new D.Q(c),h;h=0;var j=b.e,m=b.SH();0!=(b.Io&16)&&(b.Qt=D.R.gBa(j,b.ba,b.ed,b.Io,b.yl,b.D),m&&(b.bw=D.R.cka(j,b.D),b.HL=D.R.cka(j,b.D),g.k(b.HL),g.k(b.bw)),g.k(b.Qt),h++);b.Ci=D.R.pU(b.e,b.yl,b.Sn(),b.D,(0,D.Qe)(b.e));(0,D.Lh)(b.Ci,b.BX,b);b.Ci.setCursor("pointer");j=new D.Ek(b,D.q,D.q,D.q,D.q,D.q,(0,D.wg)(b.ed,"CONTROL_PANEL"));b.sa.ja(b.Ci,j);g.k(b.Ci);b.qr=new D.Q(b.e);b.cJ(b.qr);
0<b.qr.Ca()?(g.k(b.qr),h++):b.qr=D.q;var j=f,f=b.e,o=D.q,m=(0,D.zk)(b.D,"openCloseButtonWidth",0),p=(0,D.zk)(b.D,"buttonWidth",0),r=(0,D.zk)(b.D,"tabSize",0),u=b.Sn(),v=(0,D.zk)(b.D.hbar,"paddingLeft",0),z=(0,D.zk)(b.D.hbar,"paddingInner",0);e?(b.Ci.F(0),j+=m,b.qr&&(o=D.R.xm(f,b.qr),j+=z,(0,D.jg)(b.qr,j,(u-o.j)/2),j+=window.Math.max(o.g,p)),b.Qt&&(j+=z,o=3.5,(0,D.jg)(b.Qt,j,o),b.bw&&(0,D.jg)(b.bw,j,o),b.HL&&(0,D.jg)(b.HL,j,o),o=D.R.xm(f,b.Qt),j+=o.g),j+=v):(b.Qt&&(j+=v,o=3.5,(0,D.jg)(b.Qt,v,o),b.bw&&
(0,D.jg)(b.bw,v,o),b.HL&&(0,D.jg)(b.HL,v,o),o=D.R.xm(f,b.Qt),j+=z+o.g,j+=1),b.qr&&(o=D.R.xm(f,b.qr),0==j&&(j+=v),(0,D.jg)(b.qr,j,(u-o.j)/2),j+=o.g,j=window.Math.max(j+z,r)),b.Ci.F(j),j+=m);f=j;j=D.q;m=b.Io&16||b.D&&b.D.panelDrawerStyles&&0==h?(0,D.zk)(b.D.vbar,"paddingTop",0):0;b.SH()&&0!=(b.Io&16)&&(m+=D.tv.Sn()-b.Sn());if(0!=(b.Io&256)||0!=(b.Io&4097))j=new D.Q(c),j.O(g.K()+b.Sn()),r=j,0!=(b.Io&256)&&(u=(0,D.zk)(b.D.vbar,"paddingInner",0),v=(0,D.zk)(b.D.vbar,"paddingLeft",0),b.cu=D.R.sBa(b.e,b.ba,
b.ed,b.sa,b.yl,b.D),(0,D.jg)(b.cu,v,b.cu.K()+m),v=D.R.xm(b.e,b.cu),r.k(b.cu),m+=v.j,m+=u),r=j,u=D.q,v=(0,D.zk)(b.D.vbar,"paddingInner",0),z=(0,D.zk)(b.D.vbar,"paddingLeft",0),0!=(b.Io&4097)&&(b.Jm=D.R.qBa(b.e,b.ba,b.ed,b.sa,b.yl,b.D),(0,D.jg)(b.Jm,z,b.Jm.K()+m),u=D.R.xm(b.e,b.Jm),r.k(b.Jm),m+=u.j+v,b.Km=D.R.rBa(b.e,b.ba,b.ed,b.sa,b.yl,b.D),(0,D.jg)(b.Km,z,b.Km.K()+m),u=D.R.xm(b.e,b.Km),r.k(b.Km),m+=u.j,r=b.ba.zc(),u=(0,D.my)(b.ba,r),v=(0,D.ny)(b.ba,r),b.Jm&&b.Jm.ah(r!=u),b.Km&&b.Km.ah(r!=v)),b.Ad.k(j);
var v=j,z=h,r=b.e,A=(0,D.zk)(b.D,"openCloseButtonWidth",0),u=(0,D.zk)(b.D,"tabSize",0),f=(o=(0,D.zk)(b.D,"panelDrawerStyles",D.q))?f:f-A,p=b.Sn(),F=0,E=0;o?o&&0==z&&(E=e?-u:u):(F=e?A:0,E=e?A:0);if(0<z||o){var J=A=D.q,J=(0,window.parseInt)((0,D.zk)(b.D,"border-radius",0));o?(e=0<z&&v!=D.q?D.tv.aY:D.tv.bY,A=D.tv.Wma(r,J,f,p,e,u),J=D.tv.Wma(r,J,f,p,e,u)):(A=D.tv.Yja(r,f,b.Sn(),!e,b.D),J=D.tv.Yja(r,f,b.Sn(),!e,b.D));A.La((0,D.zk)(b.D,"border-color",D.q));A.G(D.q);(0,D.jg)(A,g.M()+F,g.K());g.Ia(A,0);J.la((0,D.zk)(b.D,
"background-color",D.q));(0,D.jg)(J,g.M()+E,g.K());b.Za.k(J)}b.Ad.k(g);e=j;f=b.e;r=(0,D.Qe)(f);u=(0,D.zk)(b.D,"openCloseButtonWidth",0);!b.qr&&0==(b.Io&16)?r?(g.F(0-g.M()),g.O(0),e&&(D.R.xm(f,e),g.F(g.M()-u),e.O(0))):e?(f=(0,D.zk)(b.D,"tabSize",0),(0,D.jg)(e,0,0),(0,D.jg)(g,g.M()+f,0)):(0,D.jg)(g,g.M(),0):r&&e&&(f=D.R.xm(f,g),r=(0,D.zk)(b.D,"tabSize",0),g.F(0),e.F(f.g+f.x-r));e=j;r=m;j=b.e;e&&(f=e.Ca(),f=1<f||b.cu==D.q||1<h||0<h&&1==f,m=D.q,b.D&&b.D.panelDrawerStyles&&(m=0<h?D.tv.dY:D.tv.cY),g=D.R.xm(j,
g),r+=4,h=f?r:window.Math.max(g.j,r),h+=(0,D.zk)(b.D.vbar,"paddingBottom",0),g=D.tv.jGa(j,h,b.D,m,b.Sn()),h=D.tv.iGa(j,h,f,b.D,m,b.Sn()),(0,D.jg)(g,e.M(),e.K()),b.Za.k(g),e.Ia(h,0));b.Eva=D.R.xm(c,d);return d};D.Ap.prototype.cJ=(0,D.w)();D.Ap.prototype.pO=function(){this.ln||(2===this.od?this.rB():1===this.od&&this.xK())};D.Ap.prototype.NI=function(b){(0,D.Uh)(b);this.ln||(this.xK(),this.Vd()&&this.Vd().tc())};
D.Ap.prototype.xK=function(){this.ln=D.n;this.ia(D.t);var b=(0,D.QG)(this);this.k(b);(0,D.RG)(this);var c=this.ca(0),d=c.C(),e=(0,D.zk)(this.D,"openCloseButtonWidth",0);if(d&&0!=d.g){var f=b.C(),g=new D.Ef(this.e,0.25);c.B(1);b.B(0);(0,D.P)(g,"typeNumber",c,c.$,c.B,0);(0,D.P)(g,"typeNumber",b,b.$,b.B,1);b.Ld(d.g/f.g);(0,D.P)(g,"typeNumber",b,b.Qb,b.Ld,1);if((0,D.Qe)(this.e)){b.F(c.M());var h=f.g+f.x;(0,D.P)(g,"typeNumber",b,b.M,b.F,c.M()+e-h)}b.yd(d.j/f.j);(0,D.P)(g,"typeNumber",b,b.Vb,b.yd,1);g.xd(function(){c.getParent().removeChild(c);
this.ln=D.t;this.ia(D.n)},this);g.play()}else c.getParent().removeChild(c),(0,D.Qe)(this.e)?(f=(0,D.rr)(this.e,b),h=window.Math.floor(f.g+f.x),d=e-h):d=0,(0,D.jg)(b,d,0);this.od=2;b=new D.SG("show");this.Sb(b)};D.RG=function(b){var c=D.t;b.e.Jc&&(c=D.n);c?(0,D.TG)(b):(0,D.UG)(b)};D.Ap.prototype.BX=function(b){(0,D.Uh)(b);this.ln||this.rB()};
D.Ap.prototype.rB=function(){this.ln=D.n;var b=(0,D.PG)(this);this.k(b);(0,D.RG)(this);var c=this.ca(0),d=new D.Ef(this.e,0.25);c.B(1);b.B(0);(0,D.P)(d,"typeNumber",c,c.$,c.B,0);(0,D.P)(d,"typeNumber",b,b.$,b.B,1);var e=this.Eua,f=this.Eva;(0,D.P)(d,"typeNumber",c,c.Qb,c.Ld,e.g/f.g);(0,D.Qe)(this.e)&&(0,D.P)(d,"typeNumber",c,c.M,c.F,b.M());(0,D.P)(d,"typeNumber",c,c.Vb,c.yd,e.j/f.j);d.xd(function(){c.getParent().removeChild(c);this.ln=D.t},this);d.play();this.od=1;b=new D.SG("hide");this.Sb(b)};
D.Ap.prototype.em=function(){this.ZZ=D.n;this.oQ||(0,D.TG)(this)};D.Ap.prototype.nl=function(){this.ZZ=D.t;this.oQ||(0,D.UG)(this)};D.TG=function(b){b.Za.B(b.D.backgroundHoverAlpha);b.Ad.B(b.D.borderHoverAlpha);b.bw&&b.bw.B(b.D.backgroundHoverAlpha)};D.UG=function(b){b.Za.B(b.Qj);b.Ad.B(b.D.borderAlpha);b.bw&&b.bw.B(b.Qj)};D.Ap.prototype.C=function(){this.lc||(this.lc=D.Ap.q.C.call(this));return this.lc};
D.Ap.prototype.Xm=function(){var b;b=1==this.od?(0,D.PG)(this):(0,D.QG)(this);this.Za.B(this.Qj);this.Ad.B(this.D.borderAlpha);this.k(b)};D.Ap.prototype.Iq=(0,D.B)("yl");D.gy=function(b,c){b.Jm&&b.Jm.ah(c)};D.hy=function(b,c){b.Km&&b.Km.ah(c)};
D.Vx={};D.D.l(D.Vx,D.D,"DvtControlPanelDefaults");
D.Vx.JY={"fill-type":"solid",backgroundAlpha:1,backgroundDragAlpha:1,borderDragAlpha:1,panelDrawerStyles:D.n,buttonWidth:42,buttonHeight:42,buttonRadius:0,openCloseButtonWidth:42,tabSize:42,paddingTop:15,paddingSide:-1,imageWidth:24,imageHeight:24,centerButtonDisplayed:D.t,scrollbarBackground:"linear-gradient(bottom, #dce2e7 0%, #f8f8f8 8%)",scrollbarBorderColor:"#dce2e7",scrollbarHandleColor:"#abb0b4",scrollbarHandleHoverColor:"#333333",scrollbarHandleActiveColor:"#333333",comboBox:{paddingTop:0,
paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0,itemHeight:30,imagePadding:0,itemPadding:10},vbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0},hbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0}};D.Vx.KY={"fill-type":"solid"};
D.Vx.qA={"fill-type":"gradient","border-color":"#ffffff","background-color":"#ffffff","border-radius":6,backgroundAlpha:0.5,backgroundHoverAlpha:1,backgroundDragAlpha:0.5,borderAlpha:1,borderHoverAlpha:1,borderDragAlpha:0.5,tabSize:26,buttonWidth:22,buttonHeight:22,buttonRadius:3,paddingTop:5,paddingSide:5,imageWidth:22,imageHeight:20,openCloseButtonWidth:10,centerButtonDisplayed:D.n,comboBox:{paddingTop:2,paddingBottom:6,paddingLeft:3,paddingRight:3,paddingInner:2,itemHeight:22,radius:4,imagePadding:2,
itemPadding:7},vbar:{paddingTop:2.5,paddingBottom:2.5,paddingLeft:2,paddingRight:2,paddingInner:2},hbar:{paddingTop:2,paddingBottom:2,paddingLeft:3,paddingRight:3,paddingInner:2}};D.Vx.Vg=function(b){var c=D.Vx.DB(b);return b?D.nl.Cb(b,c):c};D.Vx.DB=function(b){var c=D.q;return c=b&&"skyros"===b.skin?D.nl.Cb(D.Vx.KY,D.Vx.qA):b&&"alta"===b.skin?D.nl.Cb(D.Vx.JY,D.Vx.qA):D.nl.clone(D.Vx.qA)};
D.Zx=function(b,c,d){this.Init(b,c,d)};D.D.l(D.Zx,D.tm,"DvtControlPanelEventManager");D.C=D.Zx.prototype;D.C.ol=function(b){var c=this.na((0,D.vr)(b));D.Zx.q.ol.call(this,b);c&&(c.Ep&&c.Ep(b),b.stopPropagation())};D.C.hn=function(b){var c=this.na((0,D.vr)(b));D.Zx.q.hn.call(this,b);c&&(c.qo&&c.qo(b),b.stopPropagation())};D.C.pk=function(b){var c=this.na((0,D.vr)(b));D.Zx.q.pk.call(this,b);c&&(c.kE&&c.kE(b),b.stopPropagation())};
D.C.hh=function(b){var c=this.na((0,D.vr)(b));D.Zx.q.hh.call(this,b);c&&(c.Zc&&c.Zc(b),b.stopPropagation())};D.C.Tu=function(b){D.Zx.q.Tu.call(this,b);var c=this.na((0,D.vr)(b));c&&c.em&&c.em(b)};D.C.Su=function(b){D.Zx.q.Su.call(this,b);var c=this.na((0,D.vr)(b));c&&c.nl&&c.nl(b)};D.C.Vs=function(b){var c=this.na((0,D.vr)(b));c&&(c.Zc&&c.Zc(b),b.stopPropagation())};D.C.jE=function(b){b.Az();(0,D.Uh)(b)};
D.Ek=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.D.l(D.Ek,D.D,"DvtControlPanelEventHandlerProxy");D.C=D.Ek.prototype;D.C.Init=function(b,c,d,e,f,g,h){this.ka=b;this.Bt=c;this.Tea=e;this.JR=d;this.KR=f;this.LR=g;this.ef=h};D.C.Zc=function(b){this.Bt&&this.Bt.call(this.ka,b)};D.C.Ep=function(b){this.JR&&this.JR.call(this.ka,b)};D.C.qo=function(b){this.Tea&&this.Tea.call(this.ka,b)};D.C.kE=function(b){this.KR&&this.KR.call(this.ka,b)};D.C.WO=function(b){this.LR&&this.LR.call(this.ka,b)};
D.C.ne=(0,D.B)("ef");
D.tv={};D.D.l(D.tv,D.D,"DvtControlPanelLAFUtils");D.tv.dY="top";D.tv.cY="right";D.tv.bY="left";D.tv.aY="bottom";D.tv.$aa=47;D.tv.Zaa=26;D.tv.Nd=window.Math.sin(window.Math.PI/4);D.tv.Od=window.Math.tan(window.Math.PI/8);D.tv.Sn=function(){return D.tv.$aa};D.tv.mV=function(){return D.tv.Zaa};D.tv.Yja=function(b,c,d,e,f){c||(c=86);d||(d=47);e===D.k&&(e=D.n);f=(0,window.parseInt)((0,D.zk)(f,"border-radius",0));return D.tv.GFa(b,f,c-2*f,d-2*f,e)};
D.tv.GFa=function(b,c,d,e,f){var g=d+c,h=e+c,j=window.DvtPathUtils.moveTo(g+c,h+c),j=j+window.DvtPathUtils.lineTo(g-d,h+c),g=g-d,j=j+window.DvtPathUtils.lineTo(g-c,h+c),j=j+window.DvtPathUtils.lineTo(g-c,h-e),h=h-e;f?(j+=window.DvtPathUtils.fc(-c+g,-D.tv.Od*c+h,-D.tv.Nd*c+g,-D.tv.Nd*c+h)+window.DvtPathUtils.fc(-D.tv.Od*c+g,-c+h,g,-c+h)+window.DvtPathUtils.lineTo(g,-c+h),j+=window.DvtPathUtils.lineTo(g+d+c,-c+h),j+=window.DvtPathUtils.lineTo(g+d+c,h+e)):(j+=window.DvtPathUtils.lineTo(g-c,-c+h),j+=
window.DvtPathUtils.lineTo(g+d,-c+h),g+=d,j+=window.DvtPathUtils.fc(D.tv.Od*c+g,-c+h,D.tv.Nd*c+g,-D.tv.Nd*c+h)+window.DvtPathUtils.fc(c+g,-D.tv.Od*c+h,c+g,h)+window.DvtPathUtils.lineTo(g+c,h+e));j+=window.DvtPathUtils.closePath();return new D.ef(b,j)};
D.tv.Xja=function(b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.zk)(d,"border-radius",0)),g=(0,D.zk)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.zk)(d,"buttonHeight",c));e=D.R.oX(g,c,f,e);e=e.concat("Z");b=new D.ef(b,e,"cls_shape");(e=(0,D.zk)(d,"tab-color-inactive",D.q))||(e=(0,D.zk)(d,"background-color",D.q));b.la(e);return b};
D.tv.f5=function(b,c,d,e){c||(c=47);var f=(0,window.parseInt)((0,D.zk)(d,"border-radius",0)),g=(0,D.zk)(d,"openCloseButtonWidth",0);c=window.Math.max(c,(0,D.zk)(d,"buttonHeight",c));e=D.R.oX(g,c,f,e);e=e.concat("Z");b=new D.ef(b,e,"cls_shape");b.La((0,D.zk)(d,"border-color",D.q));b.G(D.q);return b};
D.tv.jGa=function(b,c,d,e,f){c||(c=137);var g=(0,window.parseInt)((0,D.zk)(d,"border-radius",0)),h=(0,D.zk)(d,"tabSize",0),j=h-2*g,m=c+7-2*g;b=e&&f?D.tv.Yma(b,g,h,c,e,f):D.tv.Xma(b,g,j,m);b.la((0,D.zk)(d,"background-color",D.q));return b};D.tv.iGa=function(b,c,d,e,f,g){c||(c=137);d||(d=D.n);var h=(0,window.parseInt)((0,D.zk)(e,"border-radius",0)),j=(0,D.zk)(e,"tabSize",0),m=j-2*h,o=c+7-2*h,p=D.q,p=f&&g?D.tv.Yma(b,h,j,c,f,g):D.tv.Xma(b,h,m,o,d);p.La((0,D.zk)(e,"border-color",D.q));p.G(D.q);return p};
D.tv.Xma=function(b,c,d,e,f){f||(f=D.n);var g=d+c,h=e,j=window.DvtPathUtils.moveTo(g+c,h),j=f?j+(window.DvtPathUtils.fc(c+g,D.tv.Od*c+h,D.tv.Nd*c+g,D.tv.Nd*c+h)+window.DvtPathUtils.fc(D.tv.Od*c+g,c+h,g,c+h)+window.DvtPathUtils.lineTo(g,c+h)):j+window.DvtPathUtils.lineTo(g+c,h+c),j=j+window.DvtPathUtils.lineTo(g-d,c+h),g=g-d,j=j+(window.DvtPathUtils.fc(-D.tv.Od*c+g,c+h,-D.tv.Nd*c+g,D.tv.Nd*c+h)+window.DvtPathUtils.fc(-c+g,D.tv.Od*c+h,-c+g,h)+window.DvtPathUtils.lineTo(-c+g,h)+window.DvtPathUtils.lineTo(-c+
g,h-e)),h=h-e,j=j+(window.DvtPathUtils.lineTo(g+d+c,h)+window.DvtPathUtils.lineTo(g+d+c,h+e)+window.DvtPathUtils.closePath());return new D.ef(b,j)};D.tv.Yma=function(b,c,d,e,f,g){c=D.tv.d$(d,e,c,f,g);return new D.ef(b,c)};D.tv.Wma=function(b,c,d,e,f,g){c=D.tv.d$(d,e,c,f,g);return new D.ef(b,c)};
D.tv.d$=function(b,c,d,e,f){var g,h=(0,D.Qe)();e==D.tv.dY&&!h&&(g=["M",b,0,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c,"L",0,0]);e==D.tv.dY&&h?g=["M",b,0,"L",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,0]:e==D.tv.cY&&!h?g=["M",b,f,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c,"L",0,0,"L",b,0]:e==D.tv.cY&&h?g=["M",0,0,"L",b,0,"L",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",0,f]:e==D.tv.bY&&!h?g=["M",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c]:e==D.tv.bY&&h?g=["M",b,c,"L",d,c,"A",d,d,0,0,1,0,c-d,"L",
0,d,"A",d,d,0,0,1,d,0,"L",b,0]:e==D.tv.aY&&!h?g=["M",0,c,"L",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",f,c]:e==D.tv.aY&&h&&(g=["M",b,c,"L",b,0,"L",d,0,"A",d,d,0,0,0,0,d,"L",0,c-d,"A",d,d,0,0,0,d,c,"L",b-f,c]);return g};
D.wr=function(b,c,d){this.Init(b,c,d)};(0,D.qa)("DvtPanZoomComponent",D.wr);D.D.l(D.wr,D.Rx,"DvtPanZoomComponent");D.wr.prototype.Init=function(b,c,d){D.wr.q.Init.call(this,b,c,d);this.gK="initCollapsed";this.Bl=16777215;this.Fe=!(0,D.Vp)()&&!((0,D.zn)()&&17>=(0,D.Sx)());this.f4=this.q3=D.q;this.Gb=""};D.wr.prototype.nDa=(0,D.B)("ba");D.wr.prototype.getPanZoomCanvas=D.wr.prototype.nDa;D.lh=function(b){b.q3||(b.q3=b.N?b.N.resources:{});return b.q3};
D.wr.prototype.Kc=function(){this.Mg||(this.Mg=new D.Tx);return this.Mg};D.wr.prototype.ts=(0,D.B)("f4");
D.Lp=function(b,c){var d=(new D.K(c.inlineStyle)).v("background-color");d&&(b.D0=d);var d={},e=c.skin;e&&(b.Gb=e,d.skin=e);(0,D.Ux)(d,"background-color",c.cpBackgroundColor);(0,D.Ux)(d,"border-color",c.cpBorderColor);(0,D.Ux)(d,"border-radius",c.cpBorderRadius);(0,D.Ux)(d,"box-shadow",c.cpBoxShadow);(0,D.Ux)(d,"tab-color-inactive",c.tabBgColorInactive);(0,D.Ux)(d,"tab-border-color-inactive",c.tabBorderColorInactive);(0,D.Ux)(d,"scrollbarBackground",c.scrollbarBg);(0,D.Ux)(d,"scrollbarBorderColor",
c.scrollbarBorderColor);(0,D.Ux)(d,"scrollbarHandleColor",c.scrollbarHandleColor);(0,D.Ux)(d,"scrollbarHandleActiveColor",c.scrollbarHandleActiveColor);(0,D.Ux)(d,"scrollbarHandleHoverColor",c.scrollbarHandleHoverColor);d=D.Vx.Vg(d);b.f4=d};
D.Mo=function(b,c){var d=(new D.K(c.o("inlineStyle"))).v("background-color");d&&(b.D0=d);var d={},e=c.o("skin");e&&(b.Gb=e,d.skin=e);(0,D.Ux)(d,"background-color",c.o("cpBackgroundColor"));(0,D.Ux)(d,"border-color",c.o("cpBorderColor"));(0,D.Ux)(d,"border-radius",c.o("cpBorderRadius"));(0,D.Ux)(d,"box-shadow",c.o("cpBoxShadow"));(0,D.Ux)(d,"tab-color-inactive",c.o("tabBgColorInactive"));(0,D.Ux)(d,"tab-border-color-inactive",c.o("tabBorderColorInactive"));(0,D.Ux)(d,"scrollbarBackground",c.o("scrollbarBg"));
(0,D.Ux)(d,"scrollbarBorderColor",c.o("scrollbarBorderColor"));(0,D.Ux)(d,"scrollbarHandleColor",c.o("scrollbarHandleColor"));(0,D.Ux)(d,"scrollbarHandleActiveColor",c.o("scrollbarHandleActiveColor"));(0,D.Ux)(d,"scrollbarHandleHoverColor",c.o("scrollbarHandleHoverColor"));d=D.Vx.Vg(d);b.f4=d};
D.wr.prototype.L=function(b,c,d){this.S=c;this.X=d;this.Ly=!b;this.eJ();if(!this.Ly)if("object"==typeof b)this.be(b);else if(!(b==D.q||0==b.length)){var e=new D.ul;if(e&&(e=e.parse(b)))"r"===e.getName()&&(e=e.getFirstChild()),e&&this.vA().q7(e)}this.xi(b,c,d)};D.wr.prototype.render=D.wr.prototype.L;D.C=D.wr.prototype;D.C.LO=function(){var b=this.yx();return"hidden"!=b?new D.Ap(this.e,this,"initCollapsed"==b?1:2):D.q};D.C.yx=(0,D.B)("gK");D.C.vA=(0,D.ca)(D.q);D.C.Ps=(0,D.w)();D.C.ng=(0,D.w)();
D.C.eJ=(0,D.w)();
D.C.xi=function(){if(this.D0||!this.Gb)this.ht||(this.ht=new D.af(this.e,0,0,0,0),this.k(this.ht)),this.ht.ha(this.S),this.ht.ua(this.X),this.ht.G((0,D.Wx)(this,this.D0));if(this.Ly)this.ba.Xh(this.S,this.X);else{this.ba&&(this.removeChild(this.ba),this.ba=D.q);this.ba=new D.Xx(this.e,this.S,this.X,this);this.ba.W("dvtPan",this.Ps,D.t,this);this.ba.W("dvtZoom",this.ng,D.t,this);this.k(this.ba);var b=this.LO();b&&(b.W("dvtPZCPExpand",this.Awa,D.t,this),this.ba.Cc=b);this.ba.Xm()}b=new D.bt("comp");
(0,D.ct)(b,this.M(),this.K(),this.S,this.X);(0,D.dt)(this,b)};D.C.be=function(b){this.N=this.lf?this.lf.Vg(b):b};
D.Wx=function(b,c){var d,e=1;if(c&&"#7396C8"!=c){e=D.N.$(c);d=(D.N.sd("#AECDEA")-D.N.sd("#7396C8"))/(255-D.N.sd("#7396C8"));var f=(D.N.rd("#AECDEA")-D.N.rd("#7396C8"))/(255-D.N.rd("#7396C8")),g=(D.N.qd("#AECDEA")-D.N.qd("#7396C8"))/(255-D.N.qd("#7396C8")),h=D.N.sd(c),j=D.N.rd(c),m=D.N.qd(c);d=D.N.hx(window.Math.round(h+d*(255-h)),window.Math.round(j+f*(255-j)),window.Math.round(m+g*(255-m)));f=D.N.Mi(c);d=["#FFFFFF","#FFFFFF",d,f]}else d=["#FFFFFF","#FFFFFF","#AECDEA","#7396C8"];var e=[e,e,e,e],f=
[0,45/255,190/255,1],j=b.S,g=1.7*1.7*j,h=1.7*b.X,j=0+(j-g)/2,m=j+g/2,o=-35+h/2,p=1.5*window.Math.min(g/2,h/2);return new D.Yx(d,e,f,m,o,p,[j,-35,g,h])};D.wr.prototype.Awa=function(b){var c=new D.Lf;(0,D.Mf)(c,"controlPanelBehavior","show"==b.Pi()?"initExpanded":"initCollapsed");this.Xa(c)};
D.Xx=function(b,c,d,e){this.Init(b,c,d,e)};D.D.l(D.Xx,D.Q,"DvtPanZoomCanvas");
D.Xx.prototype.Init=function(b,c,d,e){D.Xx.q.Init.call(this,b);this.I=e;this.Bg=c;this.Pg=d;this.Jt=this.It=this.nz=this.pG=0;this.kq=this.mq=this.jq=this.lq=D.q;this.Fl=0.1;this.zm=1;this.bT=15;this.IM=0.05;this.iIa=D.t;this.kp=20;this.Cc=D.q;this.yca=this.zr=this.ci=D.n;this.ht=new D.af(this.e,0,0,this.Bg,this.Pg);this.k(this.ht);(0,D.Yg)(this.ht);this.Y=new D.Q(this.e);this.k(this.Y);this.Y.ra(new D.rh);this.at=0.5;this.sa=new D.$x(b,this.Sb,this);this.sa.rf(this);this.uIa=1;(0,D.ay)(this,c,d);
this.WA=D.t;this.Lo=D.q};D.Xx.prototype.Xh=function(b,c,d){this.Bg=b;this.Pg=c;d||(this.ht.ha(b),this.ht.ua(c),this.Cc&&(0,D.by)(this),(0,D.ay)(this,b,c))};D.Xx.prototype.sc=function(){return new D.Je(this.Bg,this.Pg)};D.ay=function(b,c,d){var e=new D.bt("pzc");(0,D.ct)(e,b.M(),b.K(),c,d);(0,D.dt)(b,e)};D.wu=function(b){return b.Y};D.Rf=function(b,c){if(c){var d=(0,D.zg)(c,b.Y,b.Y.ma);if(d)return d}return b.Y.ma()};D.Xx.prototype.zc=function(b){return(0,D.Rf)(this,b).Qc};
(0,D.qa)("DvtPanZoomCanvas.prototype.getZoom",D.Xx.prototype.zc);
D.Xx.prototype.jk=function(b,c,d){if(this.ci){var e=(0,D.Rf)(this,d).Bb,f=(0,D.Rf)(this,d).yb,g=(0,D.cy)(this,e+b),h=(0,D.dy)(this,f+c);c=g-e;var j=h-f;b=D.q;d&&(b=(0,D.zg)(d,this.Y,this.Y.ma))&&(b=b.clone());b||(b=this.Y.ma().clone());b.translate(c,j);var m=this;c=function(){var b=new D.ey("panning",g,h,e,f,d);m.Sb(b)};j=function(){var b=new D.ey("panned",g,h,e,f,d);m.Sb(b)};d?((0,D.P)(d,"typeMatrix",this.Y,this.Y.ma,this.Y.ra,b),(0,D.fy)(d,c),(0,D.Gf)(d,j)):(c(),this.Y.ra(b),j())}};
D.Sf=function(b,c,d,e){b.ci&&(c-=(0,D.Rf)(b,e).Bb,d-=(0,D.Rf)(b,e).yb,b.jk(c,d,e))};
D.Xx.prototype.WD=function(b,c,d,e){if(this.zr){!c&&0!==c&&(c=this.Bg/2);!d&&0!==d&&(d=this.Pg/2);var f=this.zc(e),g=(0,D.Kv)(this,f*b);this.Cc&&(b=this.zc(),g==this.Fl&&g==this.zm?((0,D.gy)(this.Cc,D.t),(0,D.hy)(this.Cc,D.t)):b<=g&&g==this.zm?((0,D.gy)(this.Cc,D.t),(0,D.hy)(this.Cc,D.n)):b>=g&&g==this.Fl?((0,D.gy)(this.Cc,D.n),(0,D.hy)(this.Cc,D.t)):((0,D.gy)(this.Cc,D.n),(0,D.hy)(this.Cc,D.n)));if(window.Math.round(1E5*f)!=window.Math.round(1E5*g)){var h=g/f;b=D.q;e&&(b=(0,D.zg)(e,this.Y,this.Y.ma))&&
(b=b.clone());b||(b=this.Y.ma().clone());b.scale(h,h,c,d);var j=(0,D.cy)(this,b.Bb)-b.Bb,m=(0,D.dy)(this,b.yb)-b.yb;(0,D.Jv)(this,"adjustPanConstraints",g,f,e,D.q,c,d,j,m);j=(0,D.cy)(this,b.Bb)-b.Bb;m=(0,D.dy)(this,b.yb)-b.yb;b.translate(j,m);var o=this,h=function(){(0,D.Jv)(o,"zooming",g,f,e,D.q,c,d,j,m)},p=function(){(0,D.Jv)(o,"zoomed",o.zc(),f,e,D.q,c,d,j,m)};e?((0,D.P)(e,"typeMatrix",this.Y,this.Y.ma,this.Y.ra,b),(0,D.fy)(e,h),(0,D.Gf)(e,p)):(h(),this.Y.ra(b),p())}}};
D.qs=function(b,c,d,e,f){b.zr&&(c/=b.zc(f),b.WD(c,d,e,f))};D.Xx.prototype.Nja=function(b,c){var d=this.ci;this.ci=D.n;var e=c;e||(e=this.Y.C());var f=(e.x+e.g/2)*this.zc(),e=(e.y+e.j/2)*this.zc();(0,D.Sf)(this,this.Bg/2-f,this.Pg/2-e,b);this.ci=d};
D.Xx.prototype.io=function(b,c){if(this.yca){var d=this.ci,e=this.zr;this.zr=this.ci=D.n;try{var f=c?c:this.Y.C();if(f=(0,D.Jv)(this,"zoomToFitCalcBounds",D.q,D.q,b,f).bH){var g=window.Math.min((this.Bg-2*this.kp)/f.g,(this.Pg-2*this.kp)/f.j),g=(0,D.Kv)(this,g),h=this.Bg/2-(f.x+f.g/2)*g,j=this.Pg/2-(f.y+f.j/2)*g,m=this,o=function(){(0,D.Jv)(m,"zoomToFitBegin",D.q,D.q,b,f)},p=function(){(0,D.Jv)(m,"zoomToFitEnd",D.q,D.q,b,f)};b?(0,D.fy)(b,o):o();(0,D.qs)(this,g,0,0,b);(0,D.Sf)(this,h,j,b);b?(0,D.Gf)(b,
p):p()}}finally{this.ci=d,this.zr=e}}};D.Xx.prototype.Oz=function(){var b=(0,D.vg)(this,new D.G(0,0)),c=(0,D.vg)(this,new D.G(this.Bg,this.Pg)),b=this.Y.Eb(b),c=this.Y.Eb(c);return new D.H(b.x,b.y,c.x-b.x,c.y-b.y)};
D.jy=function(b,c){if(b.WA=c)b.Lo&&(b.Lo.Zg()&&b.Lo.stop(),b.Lo=D.q);else{var d=(0,D.Rf)(b,D.k).Bb,e=(0,D.Rf)(b,D.k).yb,f=b.zc();b.cQ=d!=(0,D.cy)(b,d)||e!=(0,D.dy)(b,e);b.dQ=f!=(0,D.Kv)(b,f);if(b.cQ||b.dQ)b.Lo=new D.Ef(b.e,0.4),b.Lo.Ij(D.iy),b.dQ&&b.WD(1,0.5*b.Bg,0.5*b.Pg,b.Lo),b.cQ&&b.jk(0,0,b.Lo),(0,D.Gf)(b.Lo,b.Bva,b),b.cQ&&(d=new D.ey("elasticAnimBegin",D.q,D.q,D.q,D.q,b.Lo),b.Sb(d)),b.dQ&&(0,D.Jv)(b,"elasticAnimBegin",D.q,D.q,D.q,D.q,b.Lo),b.Lo.play()}};
D.Xx.prototype.Bva=function(){this.Lo=D.q;if(this.cQ){var b=new D.ey("elasticAnimEnd",D.k,D.k,D.k,D.k,D.k);this.Sb(b)}this.dQ&&(0,D.Jv)(this,"elasticAnimEnd")};D.cy=function(b,c){var d=c;b.lq!=D.q&&d<b.lq&&(b.WA?(d=b.lq-d,d=b.lq-window.Math.sqrt(4*(0.01*b.Bg)*d)):d=b.lq);b.jq!=D.q&&d>b.jq&&(b.WA?(d-=b.jq,d=b.jq+window.Math.sqrt(4*(0.01*b.Bg)*d)):d=b.jq);return d};
D.dy=function(b,c){var d=c;b.mq!=D.q&&d<b.mq&&(b.WA?(d=b.mq-d,d=b.mq-window.Math.sqrt(4*(0.01*b.Pg)*d)):d=b.mq);b.kq!=D.q&&d>b.kq&&(b.WA?(d-=b.kq,d=b.kq+window.Math.sqrt(4*(0.01*b.Pg)*d)):d=b.kq);return d};D.Kv=function(b,c){var d=window.Math.max(0,c);b.Fl&&d<b.Fl&&(b.WA?(d=b.Fl-d,d=b.Fl-window.Math.sqrt(4*(0.002*(b.zm-b.Fl))*d)):d=b.Fl);b.zm&&d>b.zm&&(b.WA?(d-=b.zm,d=b.zm+window.Math.sqrt(4*(0.002*(b.zm-b.Fl))*d)):d=b.zm);return d};
D.Xx.prototype.Xm=function(){var b=this.Cc;b&&(this.k(b),(0,D.by)(this),b.Xm())};D.by=function(b){var c=b.I.ts(),d=(0,D.zk)(c,"paddingSide",0),e=(0,D.zk)(c,"paddingTop",0),c=(0,D.zk)(c,"openCloseButtonWidth",0),d=(0,D.Qe)(b.e)?b.Bg-c-d:d;(0,D.jg)(b.Cc,d,e)};D.ky=function(b,c){return(0,D.Pg)(b.e,c.pageX,c.pageY)};D.Jv=function(b,c,d,e,f,g,h,j,m,o){c=new D.ly(c,d,e,f,g,new D.G(h,j),m,o);b.Sb(c);return c};D.Xx.prototype.yW=function(){(0,D.Jv)(this,"zoomAndCenter")};
D.my=function(b,c){var d;d=c+b.IM;d>b.zm&&(d=b.zm);return d};D.ny=function(b,c){var d;d=c-b.IM;d<b.Fl&&(d=b.Fl);return d};D.Xx.prototype.Es=(0,D.ba)("Fl");D.Xx.prototype.Ju=function(b){0>b&&(b=1);this.zm=b};D.Xx.prototype.ao=(0,D.ba)("at");D.Xx.prototype.Qa=(0,D.B)("at");
D.$x=function(b,c,d){this.Init(b,c,d)};D.D.l(D.$x,D.tm,"DvtPanZoomCanvasEventManager");D.C=D.$x.prototype;D.C.Init=function(b,c,d){D.$x.q.Init.call(this,b,c,d);this.Mb=d;this.ms=D.q;this.yr=this.SE=D.t;this.mQ=D.n};D.C.rf=function(b){D.$x.q.rf.call(this,b);(0,D.zn)()?b.W("DOMMouseScroll",this.BA,D.t,this):b.W(D.hv,this.BA,D.t,this)};
D.C.ol=function(b){2!=b.button&&(b=(0,D.ky)(this.ka,b),this.It=b.x,this.Jt=b.y,this.pG=this.It,this.nz=this.Jt,this.TZ=D.n,this.US=(0,D.Rf)(this.ka,D.k).Bb,this.VS=(0,D.Rf)(this.ka,D.k).yb,this.WS=this.ka.zc(),this.mQ&&(this.aR=(new window.Date).getTime()));this.kj&&this.kj.Zg()&&(this.kj.stop(),this.kj.reset())};
D.C.Ip=function(b){if(this.TZ){var c=(0,D.ky)(this.ka,b),d=c.x,c=c.y;b.ctrlKey?(this.yr||(this.hb.call(this.ka,new D.ly("dragZoomBegin")),this.yr=D.n,this.Mb.Cc&&(0,D.sy)(this.Mb.Cc),(0,D.jy)(this.ka,D.n)),b=this.WS*window.Math.pow(1+0.01*(this.nz>=c?1:-1),window.Math.abs(this.nz-c)),this.ka.ci?(0,D.qs)(this.ka,b,this.pG,this.nz):(0,D.qs)(this.ka,b,D.q,D.q)):(0,D.ty)(this,d,c);this.It=d;this.Jt=c}};D.C.hn=function(){this.TZ=D.t;this.SE&&(0,D.uy)(this);this.yr&&(0,D.vy)(this)};
D.C.pk=function(b){if(this.TZ&&(this.SE||this.yr))(!b.relatedTarget||b.relatedTarget==D.q)&&this.hn(b);D.$x.q.pk.call(this,b)};
D.C.BA=function(b){if(b.wheelDelta&&0!==b.wheelDelta){var c=this.ka.zc();this.ms&&(c=this.ms,this.ms.stop(),c=this.ka.zc(c),this.ms=D.q);this.ms=D.q;var d=b.wheelDelta;(0,D.zn)()&&(d=-d);c*=1+this.ka.IM*d/window.Math.abs(d);d=(0,D.ky)(this.ka,b);this.e.Ez().UAa(b);this.ka.ci?(0,D.qs)(this.ka,c,d.x,d.y,this.ms):(0,D.qs)(this.ka,c,D.q,D.q,this.ms);this.ms&&((0,D.Gf)(this.ms,this.Bua,this),this.ms.play())}};D.C.Bua=function(){this.ms=D.q};D.C.Fwa=(0,D.w)();
D.C.Gwa=function(){var b=1-0.04*this.i2,b=b*b,c=this.kj.RU(),d=b*this.Pxa*c,b=b*this.Qxa*c;this.g2+=d;this.h2+=b;var c=this.US+this.It-this.pG+this.g2,e=this.VS+this.Jt-this.nz+this.h2;(0,D.Sf)(this.ka,c,e);var f=D.t;if(24<=this.i2)f=D.n;else{var g=(0,D.Rf)(this.ka,D.k).Bb,h=(0,D.Rf)(this.ka,D.k).yb;if(window.Math.abs(g-c)>window.Math.abs(d)||window.Math.abs(h-e)>window.Math.abs(b))f=D.n}f?(this.kj.stop(),this.kj.reset(),(0,D.jy)(this.ka,D.t)):this.i2++};
D.C.jE=function(b){this.ka.zr&&(0,D.St)(b,this.Xqa,this);this.ka.ci&&(0,D.St)(b,this.qqa,this)};D.C.TO=function(b){this.ka.zr&&(0,D.Tt)(this.Pb,b,"zoomTouch");this.ka.ci&&(0,D.Tt)(this.Pb,b,"panTouch");b&&b.preventDefault()};D.C.SO=function(b){this.ka.zr&&(0,D.Vt)(this.Pb,b,"zoomTouch");this.ka.ci&&(0,D.Vt)(this.Pb,b,"panTouch")};
D.C.Xqa=function(b,c){var d=(0,D.Wt)(this.Pb,"zoomTouch");1>=d.length&&((0,D.Xt)(this.Pb,c.identifier,"zoomTouch","zoomTouch","zoomTouch",this.Wqa,this.Vqa,this),this.It=c.pageX,this.Jt=c.pageY,this.pG=this.It,this.nz=this.Jt,this.US=(0,D.Rf)(this.ka,D.k).Bb,this.VS=(0,D.Rf)(this.ka,D.k).yb,this.WS=this.ka.zc(),this.TS=D.q,d=(0,D.Wt)(this.Pb,"zoomTouch"),d=(0,D.wy)(this.Pb,d),this.ka.Y_=d);this.kj&&this.kj.Zg()&&(this.kj.stop(),this.kj.reset())};
D.C.Wqa=function(){var b=(0,D.Wt)(this.Pb,"zoomTouch");if(2==b.length){var c;var d=this.Pb;if(2==b.length)if(c=d.uh[b[0]],d=d.uh[b[1]],c==D.q||d==D.q||0==c.nka&&0==d.oka)c=D.q;else{var e=c.pageX-d.pageX,f=c.pageY-d.pageY,e=window.Math.sqrt(e*e+f*f),f=c.M7-d.M7,g=c.N7-d.N7,h=(c.pageX+d.pageX)/2,j=(c.pageY+d.pageY)/2;c={MBa:e-window.Math.sqrt(f*f+g*g),tU:h,mH:j,uBa:h-(c.M7+d.M7)/2,vBa:j-(c.N7+d.N7)/2,lka:e}}else c=D.q;c&&(this.yr||(this.yr=D.n,this.Pb.Az(),this.hb.call(this.ka,new D.ly("dragZoomBegin")),
this.Mb.Cc&&(0,D.sy)(this.Mb.Cc)),(0,D.jy)(this.ka,D.n),this.TS==D.q&&(this.TS=c.lka-c.MBa),d=this.WS*(c.lka/this.TS),e=(0,D.Pg)(this.Mb.e,c.tU,c.mH),this.tc(),b=(0,D.wy)(this.Pb,b),this.ka.Y_=b,(0,D.qs)(this.ka,d,e.x,e.y),this.ka.jk(c.uBa,c.vBa))}};D.C.Vqa=function(){this.yr&&(this.TS=D.q,this.Pb.j_=D.t,(0,D.vy)(this));var b=(0,D.Wt)(this.Pb,"zoomTouch"),c=(0,D.wy)(this.Pb,b);this.ka.Y_=c;0==b.length&&this.hb.call(this.ka,new D.ly("zoomEnd"))};
D.C.qqa=function(b,c){!this.yr&&1>=(0,D.Wt)(this.Pb,"panTouch").length&&((0,D.Xt)(this.Pb,c.identifier,"panTouch","panTouch","panTouch",this.pqa,this.oqa,this),this.It=c.pageX,this.Jt=c.pageY,this.pG=this.It,this.nz=this.Jt,this.US=(0,D.Rf)(this.ka,D.k).Bb,this.VS=(0,D.Rf)(this.ka,D.k).yb,this.WS=this.ka.zc(),this.mQ&&(this.aR=(new window.Date).getTime()));this.kj&&this.kj.Zg()&&(this.kj.stop(),this.kj.reset())};
D.C.pqa=function(b,c){if(!this.yr&&1==(0,D.Wt)(this.Pb,"panTouch").length){var d=c.pageX,e=c.pageY;(0,D.ty)(this,d,e);this.It=d;this.Jt=e}};D.C.oqa=function(){!this.yr&&this.SE&&(0,D.uy)(this)};D.vy=function(b){b.hb.call(b.ka,new D.ly("dragZoomEnd"));b.yr=D.t;b.Mb.Cc&&(0,D.xy)(b.Mb.Cc);(0,D.jy)(b.ka,D.t)};
D.ty=function(b,c,d){b.SE||(b.hb.call(b.ka,new D.ey("dragPanBegin")),b.SE=D.n,b.Mb.Cc&&(0,D.sy)(b.Mb.Cc),(0,D.jy)(b.ka,D.n),b.mQ&&(b.SA=[]));(0,D.Sf)(b.ka,b.US+c-b.pG,b.VS+d-b.nz);b.mQ&&(b.qxa=b.aR,b.aR=(new window.Date).getTime(),b.Xv?(b.Xv.Zg()&&b.Xv.stop(),b.Xv.reset()):b.Xv=new D.Hg(b.e,50,b.Fwa,b,1),b.SA.push({EBa:b.aR-b.qxa,nka:c-b.It,oka:d-b.Jt}),5<b.SA.length&&b.SA.splice(0,1),b.Xv.start())};
D.uy=function(b){b.hb.call(b.ka,new D.ey("dragPanEnd"));b.SE=D.t;b.Mb.Cc&&(0,D.xy)(b.Mb.Cc);if(b.Xv&&b.Xv.Zg()){b.Xv.stop();b.Xv.reset();b.kj?b.kj.reset():b.kj=new D.Hg(b.e,50,b.Gwa,b);for(var c=0,d=0,e=0,f=b.SA.length;0<b.SA.length;)var g=b.SA.pop(),c=c+g.EBa,d=d+g.nka,e=e+g.oka;b.SA=D.q;b.Pxa=d/c;b.Qxa=e/c;b.kj.setInterval(window.Math.ceil(c/f));b.i2=1;b.g2=0;b.h2=0;b.Mb.ci&&b.kj.start()}else(0,D.jy)(b.ka,D.t)};
D.Qu=function(b,c){this.Init(b,c)};D.D.l(D.Qu,D.Zl,"DvtPanZoomCanvasKeyboardHandler");D.Qu.prototype.Init=function(b,c){D.Qu.q.Init(c);this.Jua=b};
D.Qu.prototype.$n=function(b){var c=b.keyCode,d=this.Jua.ba;if(33==c)b.ctrlKey||b.shiftKey?d.jk(d.bT,0):d.jk(0,d.bT);else if(34==c)b.ctrlKey||b.shiftKey?d.jk(-d.bT,0):d.jk(0,-d.bT);else if(191==c)(b=d.Cc)&&b.pO();else if((0,D.oy)(b)||(0,D.py)(b))(0,D.qs)(d,d.zc()+d.IM);else if((0,D.qy)(b)||(0,D.ry)(b))(0,D.qs)(d,d.zc()-d.IM);else if((48==c||96==c)&&!b.ctrlKey&&!b.shiftKey)d.io();else return D.Qu.q.$n.call(this,b)};
D.Jt=function(b,c,d,e,f,g,h,j){this.Init(b,c,d,e,f,g,h,j)};D.D.l(D.Jt,D.Q,"DvtCollapsiblePanel");
D.Jt.prototype.Init=function(b,c,d,e,f,g,h,j){D.Jt.q.Init.call(this,b);this.wg=c;this.xc=d;this.Di=e?e:"col_northeast";(0,D.Qe)(this.e)&&("col_northeast"==this.Di?this.Di="col_northwest":"col_northwest"==this.Di?this.Di="col_northeast":"col_southeast"==this.Di?this.Di="col_southwest":"col_southwest"==this.Di&&(this.Di="col_southeast"));this.yl=f;this.Pv=j?j:(0,D.wh)();this.pb=this.iB=this.wB=D.q;this.D=g;this.Pp=(0,D.zk)(this.D,"border-color",D.q);this.Gh=(0,window.parseInt)((0,D.zk)(this.D,"border-radius",
D.q));this.nv=(0,D.zk)(this.D,"background-color",D.q);this.Qj=(0,D.zk)(this.D,"backgroundAlpha",1);this.GQ=h!==D.k?!h:D.t;this.Wc=new D.Xu(b,0,0,c-10,d-10,3,"collapsiblePanel");this.k(this.Wc);this.Wc.PK=D.t;(0,D.jg)(this.Wc,5,5);this.W(D.Mh,this.WO,D.t,this);this.W(D.Nh,this.kE,D.t,this)};
D.Jt.prototype.HX=function(){this.Wc.refresh();var b=this.Wc.C(),c=b.g+10,b=b.j+10;this.Za.kk((0,D.bH)(this,c,b));var d="col_northwest"==this.Di||"col_southwest"==this.Di;this.pg&&d&&this.pg.F(c);this.Sb(new D.nv(c,b,0,0))};D.Jt.prototype.isCollapsed=(0,D.B)("GQ");D.Kt=function(b,c){b.GQ!=c&&(b.GQ=c,(0,D.cH)(b,D.n),b.Sb(new D.aH(c?"hide":"show")))};D.Jt.prototype.m6=function(){return this.wg-27};D.Jt.prototype.l6=function(){return this.xc-27};
D.dH=function(b,c,d){return!b.isCollapsed()?d?new D.G(1/c.x,1/c.y):new D.G(-c.x,-c.y):c};
D.cH=function(b,c){b.pb&&(b.uJ=D.n,b.pb.stop(D.n));var d="col_northwest"==b.Di||"col_northeast"==b.Di,e="col_northwest"==b.Di||"col_southwest"==b.Di,f=e?0:b.S,g=d?0:b.X,h=new D.G(1/b.S,1/b.X),f=new D.G(f,g),d=new D.G(e?-b.S:b.S,g-(d?0:25));c||(b.Za.B(0),b.pg&&b.pg.B(0));h=new D.RA(b.e,b.Za,(0,D.dH)(b,h,D.n),c?0.25:1E-5);d=new D.SA(b.e,b.pg,(0,D.dH)(b,d),c?0.25:1E-5);f=new D.SA(b.e,b.Za,(0,D.dH)(b,f),c?0.25:1E-5);b.pb=new D.Zv(b.e,h,d,f);b.pb&&(b.e.Vd().tc(),b.Ra(D.Mh,b.WO,D.t,b),b.Ra(D.Nh,b.kE,D.t,
b),b.Sj&&(b.Sj.Ra(D.xz.we,b.pE,D.t,b),b.Sj.Ra(D.bi,b.pE,D.t,b),b.Sj.Ra(D.Mh,b.gY,D.t,b),b.Sj.Ra(D.Nh,b.fY,D.t,b)),b.isCollapsed()&&b.Wc.B(0),b.pb.xd(b.vo,b),b.pb.play())};
D.bH=function(b,c,d){var e=b.Gh,f,g="col_northwest"==b.Di||"col_southwest"==b.Di;25>=d&&(d=25);f=b.Pv||g?window.DvtPathUtils.moveTo(e,0):window.DvtPathUtils.moveTo(0,0);f+=window.DvtPathUtils.lineTo(c-e,0);!b.Pv&&g?(f+=window.DvtPathUtils.lineTo(c,0),f+=window.DvtPathUtils.lineTo(c,e)):f+=window.DvtPathUtils.fc(c,0,c,e);!b.Pv&&25==d&&g?f+=window.DvtPathUtils.lineTo(c,d):(f+=window.DvtPathUtils.lineTo(c,d-e),f+=window.DvtPathUtils.fc(c,d,c-e,d));f+=window.DvtPathUtils.lineTo(e,d);f=!b.Pv&&25==d&&!g?
f+window.DvtPathUtils.lineTo(0,d):f+window.DvtPathUtils.fc(0,d,0,d-e);if(b.Pv||g)f+=window.DvtPathUtils.lineTo(0,e),f+=window.DvtPathUtils.fc(0,0,e,0);return f+=window.DvtPathUtils.closePath()};D.C=D.Jt.prototype;
D.C.vo=function(){this.uJ=D.t;this.pb=D.q;var b=this.Za.mc().clone();b.B(this.D.borderAlpha);this.Za.Z(b);var b=this.D[D.Ap.cHa],c=this.Za.Lc().clone();c.B(b);this.Za.G(c);this.pg&&this.pg.B(this.D.borderAlpha);this.isCollapsed()||this.Wc.B(1);this.W(D.Mh,this.WO,D.t,this);this.W(D.Nh,this.kE,D.t,this);this.Sj&&(this.Sj=this.isCollapsed()?D.R.rU(this.e,this.yl,25,this.D,D.t):D.R.pU(this.e,this.yl,25,this.D,D.t),this.pg.k(this.Sj),this.pg.up(0),(0,D.wf)()?this.Sj.W(D.xz.we,this.pE,D.t,this):(this.Sj.W(D.bi,
this.pE,D.t,this),this.Sj.W(D.Mh,this.gY,D.t,this),this.Sj.W(D.Nh,this.fY,D.t,this)))};D.C.pE=function(){this.e.Vd().tc();(0,D.Kt)(this,!this.isCollapsed())};D.C.gY=function(b){var c=this.isCollapsed()?this.wB:this.iB;c!=D.q&&this.e.Vd().nO(b.pageX,b.pageY,c,this.Sj,D.n)};D.C.fY=function(){this.e.Vd().tc()};D.C.WO=function(){var b=this.Za.mc().clone();b.B(this.D.borderHoverAlpha);this.Za.Z(b);var b=this.D.backgroundHoverAlpha,c=this.Za.Lc().clone();c.B(b);this.Za.G(c);this.pg&&this.pg.B(this.D.borderHoverAlpha)};
D.C.kE=function(){var b=this.Za.mc().clone();b.B(this.D.borderAlpha);this.Za.Z(b);b=this.Za.Lc().clone();b.B(this.Qj);this.Za.G(b);this.pg&&this.pg.B(this.D.borderAlpha)};
D.aH=function(b){this.Init("dvtCollapsiblePanelEvent");this.Ml=b};D.D.l(D.aH,D.pf,"DvtCollapsiblePanelEvent");D.aH.prototype.Pi=(0,D.B)("Ml");
D.eh={};D.D.l(D.eh,D.D,"DvtImageLAFUtils");D.eh.TH=function(b,c){var d=new D.kf(b,c);d.ia(D.t);D.Ip.Gj(b,c,function(b){b!=D.q&&(b.width&&b.height)&&(d.ha(b.width),d.ua(b.height))});return d};
D.R={};D.D.l(D.R,D.D,"DvtButtonLAFUtils");D.R.gHa=-6;D.R.i9=23;D.R.h9=21;D.R.FHa=20;D.R.tHa=22;D.R.sHa=20;D.R.$aa=47;D.R.Zaa=26;D.R.Nd=window.Math.sin(window.Math.PI/4);D.R.Od=window.Math.tan(window.Math.PI/8);D.R.vO="#7C8191";D.R.S9="#E0E1E1";D.R.T9="#F0F1F2";D.R.AY=8;D.R.Doa="solid";D.R.Aoa="#7BA0D9";D.R.bX="#3474D3";D.R.s9="#BFD8FB";D.R.Psa="zoominUp";D.R.Qsa="zoominOver";D.R.Osa="zoominDown";D.R.Nsa="zoominDisabled";D.R.Wsa="zoomtofitUp";D.R.Xsa="zoomtofitOver";D.R.Vsa="zoomtofitDown";
D.R.Tsa="zoomoutUp";D.R.Usa="zoomoutOver";D.R.Ssa="zoomoutDown";D.R.Rsa="zoomoutDisabled";D.R.jsa="pandialUp";D.R.ksa="pandialOver";D.R.isa="pandialDown";D.R.rsa="recenterUp";D.R.ssa="recenterOver";D.R.qsa="recenterDown";D.R.Fba="resetUp";D.R.usa="resetOver";D.R.tsa="resetDown";D.R.sba="drillupUp";D.R.Fra="drillupOver";D.R.Era="drillupDown";D.R.rba="drilldownUp";D.R.Dra="drilldownOver";D.R.Cra="drilldownDown";D.R.NHa="maxUp";D.R.OHa="maxOver";D.R.MHa="maxDown";D.R.QHa="restoreUp";D.R.RHa="restoreOver";
D.R.PHa="restoreDown";D.R.ora="collapseEna";D.R.pra="collapseOvr";D.R.nra="collapseDwn";D.R.Ira="expandEna";D.R.Jra="expandOvr";D.R.Hra="expandDwn";D.R.msa="quickQueryEna";D.R.nsa="quickQueryOvr";D.R.lsa="quickQueryDwn";D.R.lra="clearResultsEna";D.R.mra="clearResultsOvr";D.R.kra="clearResultsDwn";D.R.Lsa="Up";D.R.hsa="Over";D.R.Bra="Down";D.R.wsa="Sel";D.R.osa="_r";D.R.Gsa="synchronize";
D.R.gBa=function(b,c,d,e,f,g){var h=D.R.T_(b,f[D.R.jsa],g),j=new D.Q(b);(0,D.jg)(j,20,20);var m=D.R.T_(b,f[D.R.isa],g);(0,D.jg)(m,-20,-20);j.k(m);m=new D.Q(b);(0,D.jg)(m,20,20);var o=D.R.T_(b,f[D.R.ksa],g);(0,D.jg)(o,-20,-20);m.k(o);h=new D.kh(b,h,m,j);if(0<(e&16)){var p=new D.kh(b,D.R.V_(b,f[D.R.rsa],g),D.R.V_(b,f[D.R.ssa],g),D.R.V_(b,f[D.R.qsa],g));(0,D.jg)(p,9,9)}return new D.MG(b,h,p,c,d,e,g)};
D.R.bBa=function(b,c,d,e,f,g,h){var j=D.R.qg(b,0,f[D.R.sba],h),m=D.R.qg(b,1,f[D.R.Fra],h),o=D.R.qg(b,2,f[D.R.Era],h);f=D.R.qg(b,0,f[D.R.sba],h);return new D.VD(b,new D.kh(b,j,m,o,f),c,d,0,e,g)};D.R.aBa=function(b,c,d,e,f,g,h){var j=D.R.qg(b,0,f[D.R.rba],h),m=D.R.qg(b,1,f[D.R.Dra],h),o=D.R.qg(b,2,f[D.R.Cra],h);f=D.R.qg(b,0,f[D.R.rba],h);return new D.VD(b,new D.kh(b,j,m,o,f),c,d,1,e,g)};
D.R.mBa=function(b,c,d,e,f,g,h){var j=D.R.qg(b,0,f[D.R.Fba],h),m=D.R.qg(b,1,f[D.R.usa],h),o=D.R.qg(b,2,f[D.R.tsa],h);f=D.R.qg(b,0,f[D.R.Fba],h);return new D.VD(b,new D.kh(b,j,m,o,f),c,d,2,e,g)};D.R.sBa=function(b,c,d,e,f,g){var h=D.R.qg(b,0,f[D.R.Wsa],g),j=D.R.qg(b,1,f[D.R.Xsa],g);f=D.R.qg(b,2,f[D.R.Vsa],g);return new D.LG(b,new D.kh(b,h,j,f),c,d,e)};
D.R.qBa=function(b,c,d,e,f,g){var h=D.R.qg(b,0,f[D.R.Psa],g),j=D.R.qg(b,1,f[D.R.Qsa],g),m=D.R.qg(b,2,f[D.R.Osa],g);f=D.R.qg(b,3,f[D.R.Nsa],g);return new D.JG(b,new D.kh(b,h,j,m,f),c,d,e)};D.R.rBa=function(b,c,d,e,f,g){var h=D.R.qg(b,0,f[D.R.Tsa],g),j=D.R.qg(b,1,f[D.R.Usa],g),m=D.R.qg(b,2,f[D.R.Ssa],g);f=D.R.qg(b,3,f[D.R.Rsa],g);return new D.KG(b,new D.kh(b,h,j,m,f),c,d,e)};
D.R.cBa=function(b,c,d,e,f){var g=(0,D.zk)(f,"buttonRadius",0),h=(0,D.zk)(f,"buttonWidth",0),j=(0,D.zk)(f,"buttonWidth",0),m=D.R.Q_(b,g,h,j,f);D.R.N3(d,m,h,j+2*g,f,D.n);c=D.R.S0(b,d,c);(b=D.R.lga(b,e[c],h,j))&&m.k(b);return m};D.R.S0=function(b,c,d,e){var f="";0==c?c=D.R.Lsa:1==c?c=D.R.hsa:2==c&&(c=D.R.Bra);e&&(d+=D.R.wsa,(0,D.Qe)(b)&&(f=D.R.osa));return d+(c+f)};D.R.j5=function(b,c,d,e){var f=D.R.S0(b,c,D.R.Gsa,D.n);return D.R.qg(b,c,e[f],d)};
D.R.hBa=function(b,c,d,e,f){var g=(0,D.zk)(f,"buttonRadius",0);b=D.R.Q_(b,g,d,e,f);D.R.N3(c,b,d,e+2*g,f,D.n);return b};D.R.$Aa=function(b,c,d,e,f){c=D.R.S0(b,d,c);return D.R.qg(b,d,e[c],f)};D.R.rU=function(b,c,d,e,f){var g=D.R.$E(b,0,d,c[D.R.Ira],e,f),h=D.R.$E(b,1,d,c[D.R.Jra],e,f);c=D.R.$E(b,2,d,c[D.R.Hra],e,f);return new D.kh(b,g,h,c)};D.R.pU=function(b,c,d,e,f){var g=D.R.$E(b,0,d,c[D.R.ora],e,f),h=D.R.$E(b,1,d,c[D.R.pra],e,f);c=D.R.$E(b,2,d,c[D.R.nra],e,f);return new D.kh(b,g,h,c)};
D.R.kBa=function(b,c){var d=D.R.aF(b,c[D.R.msa]),e=D.R.aF(b,c[D.R.nsa]),f=D.R.aF(b,c[D.R.lsa]);return new D.kh(b,d,e,f)};D.R.ZAa=function(b,c){var d=D.R.aF(b,c[D.R.lra]),e=D.R.aF(b,c[D.R.mra]),f=D.R.aF(b,c[D.R.kra]);return new D.kh(b,d,e,f)};D.R.qg=function(b,c,d,e){var f,g,h=(0,D.zk)(e,"buttonRadius",0);if("undefined"===f||f==D.q)f=(0,D.zk)(e,"buttonWidth",0);if("undefined"===g||g==D.q)g=(0,D.zk)(e,"buttonWidth",0);c=D.R.rva(b,c,h,f,g,e);(b=D.R.lga(b,d,f,g))&&c.k(b);return c};
D.R.lga=function(b,c,d,e){var f=new D.kf(b,c);f.ia(D.t);D.Ip.Gj(b,c,function(b){b!=D.q&&(b.width&&b.height)&&(f.ha(b.width),f.ua(b.height),(0,D.jg)(f,d/2-b.width/2,e/2-b.height/2))});return f};D.R.T_=function(b,c,d){var e=new D.Q(b),f=new D.Hv(b,20,20,20);f.B(0);f.la((0,D.zk)(d,"background-color",D.q));e.k(f);(b=D.eh.TH(b,c))&&e.k(b);return e};D.R.V_=function(b,c,d){var e=new D.Q(b),f=new D.Hv(b,11,11,8);f.B(0);f.la((0,D.zk)(d,"background-color",D.q));e.k(f);(b=D.eh.TH(b,c))&&e.k(b);return e};
D.R.$E=function(b,c,d,e,f,g){d||(d=47);c=D.R.uva(b,c,d,f,g);if(b=D.eh.TH(b,e))e=(0,D.zk)(f,"imageWidth",0),g=(0,D.zk)(f,"imageHeight",0),c.k(b),(0,D.jg)(b,((0,D.zk)(f,"openCloseButtonWidth",0)-e)/2,(d-g)/2);return c};D.R.aF=function(b,c){var d=D.eh.TH(b,c);d.ia(D.n);return d};
D.R.fBa=function(b,c){var d=D.R.Nda(b),e=(0,D.zk)(c,"background-color",D.q),f=(0,D.zk)(c,"border-color",D.q);"solid"==(0,D.zk)(c,"fill-type",D.q)?(d.La(f),d.la(e)):(d.Z(new D.df(36,["#8D93A5","#E0EAEB",f],[1,1,1],[0,125/255,1],[0,0,40,40],1)),d.G(new D.cf(90,[e,e,"#5A83BE",e],[0.9,0.1,0,0.7],[0,105/255,150/255,1],[0,0,40,40])));return d};D.R.cka=function(b,c){var d=D.R.Nda(b),e=(0,D.zk)(c,"background-color",D.q);d.La(e);d.la(e);return d};
D.R.Nda=function(b){var c=window.DvtPathUtils.moveTo(40,20)+window.DvtPathUtils.fc(40,20*D.R.Od+20,20*D.R.Nd+20,20*D.R.Nd+20)+window.DvtPathUtils.fc(20*D.R.Od+20,40,20,40)+window.DvtPathUtils.fc(20*-D.R.Od+20,40,20*-D.R.Nd+20,20*D.R.Nd+20)+window.DvtPathUtils.fc(0,20*D.R.Od+20,0,20)+window.DvtPathUtils.fc(0,20*-D.R.Od+20,20*-D.R.Nd+20,20*-D.R.Nd+20)+window.DvtPathUtils.fc(20*-D.R.Od+20,0,20,0)+window.DvtPathUtils.fc(20*D.R.Od+20,0,20*D.R.Nd+20,20*-D.R.Nd+20)+window.DvtPathUtils.fc(40,20*-D.R.Od+20,
40,20)+window.DvtPathUtils.closePath();return new D.ef(b,c,"draw_pan_button")};D.R.ET=function(b,c,d,e,f){b.La("#FFFFFF");b.Z(new D.df(63,["#8D93A5","#E0EAEB","#FFFFFF"],[1,1,1],[0,155/255,1],[e,f,c,d],1))};
D.R.N3=function(b,c,d,e,f,g){if((0,D.zk)(f,"panelDrawerStyles",D.q))!g||g&&0==b?(0,D.Yg)(c):(1==b||2==b)&&c.G(new D.gf("#EBECED"));else if("skyros"==f.skin)switch(b){case 1:c.G(new D.gf("#FFFFFF",0.7));c.Z(new D.ff((0,D.zk)(f,"border-color",D.q)));break;case 2:c.G(new D.gf("#B3C6DB"));c.Z(new D.ff((0,D.zk)(f,"border-color",D.q)));break;default:(0,D.Yg)(c)}else{var h,j,m;switch(b){case 3:case 0:h=["#5B868A","#FFFFFF","#FFFFFF","#5B868A"];j=[0.01,0,0.05,0.01];m=[0,120/255,130/255,1];break;case 1:D.R.ET(c,
d,e,0,0);h=["#FFFFFF","#4671B0","#4671B0","#FFFFFF"];j=[0.5,0.2,0.1,0.7];m=[0,120/255,130/255,1];break;case 2:D.R.ET(c,d,e,0,0),h=["#E0EAEB","#5B868A","#4671B0"],j=[0.1,0.3,0.6],m=[0,130/255,1]}c.G(new D.cf(90,h,j,m,[0,0,d,e]))}};
D.R.Iza=function(b,c,d,e,f){if((0,D.zk)(f,"panelDrawerStyles",D.q))(0,D.Yg)(c);else{var g;g=(0,D.zk)(f,"border-color",D.q);if("solid"==(0,D.zk)(f,"fill-type",D.q)){d=(0,D.zk)(f,"background-color",D.q);switch(b){case 0:window.bgAlpha=(0,D.zk)(f,"backgroundAlpha",1);window.strokeAlpha=(0,D.zk)(f,"borderAlpha",1);break;case 2:case 1:window.bgAlpha=(0,D.zk)(f,"backgroundHoverAlpha",1),window.strokeAlpha=(0,D.zk)(f,"borderHoverAlpha",1)}b=new D.gf(d,window.bgAlpha);g=new D.ff(g,window.strokeAlpha)}else{var h,
j,m;switch(b){case 0:h=["#FFFFFF","#5B868A","#5B868A"];j=[0,0.2,0.3];m=[0,130/255,1];break;case 1:h=["#FFFFFF","#FFFFFF","#4671B0","#4671B0"];j=[0.1,0.2,0.1,0.6];m=[0,120/255,130/255,1];break;case 2:h=["#4671B0","#5B868A","#5B868A"],j=[0.5,0.2,0.4],m=[0,130/255,1]}b=new D.cf(0,h,j,m,[0,0,d,e]);g=new D.ff(g,1,0.8)}c.Z(g);c.G(b)}};
D.R.iJa=function(b,c,d,e,f,g){var h,j,m;switch(b){case 0:c.La("#FFFFFF",1,0.25);h=["#FFFFFF","#4671B0","#E0EAEB","#FFFFFF"];j=[0.6,0.3,0.3,0.8];m=[0,125/255,130/255,1];break;case 1:D.R.ET(c,d,e,f,g);h=["#4671B0","#FFFFFF","#FFFFFF","#FFFFFF"];j=[0.4,0.3,0.7,1];m=[0,70/255,200/255,1];break;case 2:D.R.ET(c,d,e,f,g),h=["#FFFFFF","#4671B0","#E0EAEB"],j=[0.6,0.5,0.8],m=[0,130/255,1]}c.G(new D.cf(90,h,j,m,[f,g,d,e]))};
D.R.oX=function(b,c,d,e){return e?["M",b,0,"L",d,0,"A",d,d,0,0,0,0,d,"L",0,c-d,"A",d,d,0,0,0,d,c,"L",b,c]:["M",0,0,"L",b-d,0,"A",d,d,0,0,1,b,d,"L",b,c-d,"A",d,d,0,0,1,b-d,c,"L",0,c]};D.R.uva=function(b,c,d,e,f){d||(d=47);var g=(0,window.parseInt)((0,D.zk)(e,"border-radius",0)),h=(0,D.zk)(e,"openCloseButtonWidth",0);d=window.Math.max(d,(0,D.zk)(e,"buttonHeight",d));b=new D.ef(b,D.R.oX(h,d,g,f));D.R.Iza(c,b,h,d,e);return b};D.R.rva=function(b,c,d,e,f,g){b=D.R.Q_(b,d,e,f,g);D.R.N3(c,b,e,f+2*d,g);return b};
D.R.Q_=function(b,c,d,e,f){if("skyros"==f.skin)return new D.af(b,0,0,d,e);d-=2*c;e-=2*c;f=d+c;var g=e+c,h=window.DvtPathUtils.moveTo(f+c,g)+window.DvtPathUtils.fc(c+f,D.R.Od*c+g,D.R.Nd*c+f,D.R.Nd*c+g)+window.DvtPathUtils.fc(D.R.Od*c+f,c+g,f,c+g)+window.DvtPathUtils.lineTo(f,g+c)+window.DvtPathUtils.lineTo(f-d,c+g);f-=d;h+=window.DvtPathUtils.fc(-D.R.Od*c+f,c+g,-D.R.Nd*c+f,D.R.Nd*c+g)+window.DvtPathUtils.fc(-c+f,D.R.Od*c+g,-c+f,g)+window.DvtPathUtils.lineTo(f-c,g)+window.DvtPathUtils.lineTo(f-c,g-
e);g-=e;h+=window.DvtPathUtils.fc(-c+f,-D.R.Od*c+g,-D.R.Nd*c+f,-D.R.Nd*c+g)+window.DvtPathUtils.fc(-D.R.Od*c+f,-c+g,f,-c+g)+window.DvtPathUtils.lineTo(f,-c+g)+window.DvtPathUtils.lineTo(f+d,-c+g);f+=d;h+=window.DvtPathUtils.fc(D.R.Od*c+f,-c+g,D.R.Nd*c+f,-D.R.Nd*c+g)+window.DvtPathUtils.fc(c+f,-D.R.Od*c+g,c+f,g)+window.DvtPathUtils.lineTo(f+c,g+e)+window.DvtPathUtils.closePath();return new D.ef(b,h)};
D.R.yBa=function(b,c,d,e){e=(0,D.zk)(e,"radius",0);c-=2*e;d-=e;var f=c+e,g=d,h=window.DvtPathUtils.moveTo(f+e,g)+window.DvtPathUtils.fc(e+f,D.R.Od*e+g,D.R.Nd*e+f,D.R.Nd*e+g)+window.DvtPathUtils.fc(D.R.Od*e+f,e+g,f,e+g)+window.DvtPathUtils.lineTo(f,e+g)+window.DvtPathUtils.lineTo(f-c,e+g),f=f-c,h=h+(window.DvtPathUtils.fc(-D.R.Od*e+f,e+g,-D.R.Nd*e+f,D.R.Nd*e+g)+window.DvtPathUtils.fc(-e+f,D.R.Od*e+g,-e+f,g)+window.DvtPathUtils.lineTo(-e+f,g)+window.DvtPathUtils.lineTo(-e+f,g-d)),g=g-d,h=h+(window.DvtPathUtils.lineTo(f+
c+e,g)+window.DvtPathUtils.lineTo(f+c+e,g+d)+window.DvtPathUtils.closePath());return new D.ef(b,h)};D.R.GJa=function(b,c){var d=new window.DvtDropShadowFilter(7,45,"#5A83BE",0.9,14,14,1,3,D.t,D.t,D.t),e=[];e.push(d);c.filters=e};D.R.xm=function(b,c){c instanceof D.kh&&(c=c.ca(0));return(0,D.rr)(b,c)};
D.R.I7=function(b,c){var d=D.R.Doa,e=D.R.Aoa,f=D.R.bX,g;c&&(c.v("fill-type")&&(d=c.v("fill-type")),c.v("border-color")&&(e=c.v("border-color")),c.v("background-color")&&(f=c.v("background-color")),c.v("background")&&(g=c.v("background")));var e=new D.ff(e),h;if("solid"==d)h=new D.gf(f);else{var j,m,o;if(g&&0<=g.indexOf("linear-gradient")){if(d=(0,D.hf)(g))o=d.$j(),h=d.sl,j=d.rl,m=d.fv}else h=f,j=D.R.s9,h!=D.R.bX&&(j=D.N.rp(D.R.bX,D.R.s9,h)),h=[h,j],j=[0.6,0.8],m=[0,1],o=-270;h=new D.cf(o,h,j,m)}b.G(h);
b.Z(e)};
D.uG={};D.D.l(D.uG,D.D,"DvtCommonLegendDefaults");D.uG.JY={rowColGap:6,separatorGap:7,indicatorSize:16,buttonSize:12,dwn:"#0572CE",ovr:"#5D5D5D",ena:"#7E7F80",separatorColor:"#D9DFE3"};D.uG.KY={dwn:"#202F48",ovr:"#184DD8",ena:"#003D5B"};D.uG.qA={rowColGap:4,separatorGap:4,indicatorSize:11,buttonSize:11,dwn:"#000000",ovr:"#245EDD",ena:"#495D7C",separatorColor:"#ADB6C7"};D.uG.Vg=function(b){var c=D.uG.DB(b);return b?D.nl.Cb(b,c):c};
D.uG.DB=function(b){var c=D.q;return c=b&&"skyros"===b.skin?D.nl.Cb(D.uG.KY,D.uG.qA):b&&"alta"===b.skin?D.nl.Cb(D.uG.JY,D.uG.qA):D.nl.clone(D.uG.qA)};
D.DvtCommonLegend=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.DvtCommonLegend,D.Q,"DvtCommonLegend");D.DvtCommonLegend.V$="isLegendDisclosed";D.DvtCommonLegend.Eqa="skin";D.C=D.DvtCommonLegend.prototype;D.C.Init=function(b,c,d,e,f){D.DvtCommonLegend.q.Init.call(this,b,D.q,c,d);this.Lh=(0,D.Qe)();this.S=this.lJa=c;this.X=d;this.VP={};this.$0={};this.BJ=[];this.FE=D.t;this.Wt=[];this.vza=this.hM=D.t;this.AF=[];this.ij=e;this.D=D.uG.Vg(f?{skin:f}:D.q);this.r1=D.t;this.Mg=new D.Pn};D.C.sJ=(0,D.B)("Mg");
D.C.Uz=(0,D.B)("r1");D.C.uW=(0,D.ba)("RF");D.C.r8=function(b){b&&(this.UB=b)};D.C.eb=(0,D.B)("JF");D.C.Je=(0,D.ba)("JF");
D.xG=function(b,c,d,e,f){var g=c.o("label"),g=new D.vG(b.e,b,g,b.I3,b.D);g.L(d,e,f);if(c=c.jb())for(var h=0;h<c.length;h++){var j=c[h],m;if("item"==j.getName()){m=b;var o={};o.itemId=j.o("itemId");o.attributeGroupId=j.o("attributeGroupId");o.hideAttrs=j.o("hideAttrs");m=new D.wG(m.e,m,o,m.$K,m.D);j=j.jb();for(o=0;o<j.length;o++)if("marker"==j[o].getName()){var p=m,r=j[o],u=r.o("url"),v=r.o("shapeType"),z=r.o("color"),A=r.o("pattern");(r=r.o("opacity"))&&(r=(0,window.parseFloat)(r));p.setMarker(u,
v,z,A,r)}else"text"==j[o].getName()&&m.dh(j[o].o("value"))}else"text"==j.getName()&&(m=new D.wG(b.e,b,D.q,b.$K,b.D),m.dh(j.o("value")));m&&(m.L(g,e,f),g.tj(m))}d.k(g);e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};
D.yG=function(b,c,d,e,f){var g=new D.vG(b.e,b,c.label,b.I3,b.D);g.L(d,e,f);var h=c.item,j;if(h)for(var m=0;m<h.length;m++){var o=b;j=h[m];var p={};p.itemId=j.itemId;p.attributeGroupId=j.attributeGroupId;p.hideAttrs=j.hideAttrs;var o=new D.wG(o.e,o,p,o.$K,o.D),r=j.marker,p=r.url,u=r.shapeType,v=r.color,z=r.pattern;(r=r.opacity)&&(r=(0,window.parseFloat)(r));o.setMarker(p,u,v,z,r);o.dh(j.text.value);if(j=o)j.L(g,e,f),g.tj(j)}if(c=c.text)for(m=0;m<c.length;m++)j=new D.wG(b.e,b,D.q,b.$K,b.D),j.dh(c[m].value),
j&&(j.L(g,e,f),g.tj(j));d.k(g);e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};D.AG=function(b,c,d,e,f){var g=c.o("label"),h="true"==c.o("disclosed"),j=c.o("expandTooltip"),m=c.o("collapseTooltip"),g=new D.zG(b.e,b,g,b.G3,m,j,h,b.D);g.L(d,e,f);d=f?-1:1;if(c=c.jb())for(h=0;h<c.length;h++)j=c[h],"section"==j.getName()&&(e.x+=(b.D.buttonSize+b.D.rowColGap)*d,j=(0,D.xG)(b,j,g,e,f),e.x-=(b.D.buttonSize+b.D.rowColGap)*d,g.tj(j));e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};
D.BG=function(b,c,d,e,f){var g=new D.zG(b.e,b,c.label,b.G3,c.collapseTooltip,c.expandTooltip,"true"==c.disclosed,b.D);g.L(d,e,f);d=f?-1:1;if(c=c.section)for(var h=0;h<c.length;h++){e.x+=(b.D.buttonSize+b.D.rowColGap)*d;var j=(0,D.yG)(b,c[h],g,e,f);e.x-=(b.D.buttonSize+b.D.rowColGap)*d;g.tj(j)}e.y=e.y-b.D.rowColGap+b.D.rowColGap;return g};
D.CG=function(b,c,d){d.y=d.y-b.D.rowColGap+b.D.separatorGap;var e=new D.cn(b.e,d.x,d.y,d.x,d.y);(0,D.bn)(e);e.La(b.D.separatorColor);b.Wt.push(e);var f;if("alta"==b.D.skin)f=e;else{d.y++;var g=new D.cn(b.e,d.x,d.y,d.x,d.y);g.La("#FFFFFF");(0,D.bn)(g);f=new D.Q(b.e);f.k(e);f.k(g);b.Wt.push(g)}c.k(f);d.y+=b.D.separatorGap;return f};
D.DvtCommonLegend.prototype.update=function(b,c){for(var d=this.je.indexOf(b),d=d+1;d<this.je.length;){var e=this.je[d].K();this.je[d].O(e+c);d++}this.lc.j+=c;this.Sb(new D.nv(this.lc.g,this.lc.j,0,0))};D.DvtCommonLegend.prototype.Sc=(0,D.B)("Aa");
D.DvtCommonLegend.prototype.L=function(){if(this.RF){this.Aa=new D.DG(this.e,this.zxa,this);this.Dd=this.RF.o("label");this.JF="true"==this.RF.o("disclosed");var b=this.RF.getElementsByTagName("style");if(b&&(b=b[0].jb()))for(var c=0;c<b.length;c++){var d=b[c];"legend-title"==d.getName()?this.aL=d.getTextContent():"sectionGroup-title"==d.getName()?this.G3=d.getTextContent():"section-title"==d.getName()?this.I3=d.getTextContent():"legend-item"==d.getName()&&(this.$K=d.getTextContent())}if(b=this.RF.o("noWrap"))this.r1=
"false"==b;b=this.Lh?new D.H(this.S,0,this.S,this.X):new D.H(0,0,this.S,this.X);this.Bn=new D.Q(this.e);this.k(this.Bn);if(this.Dd&&(c=this.Uz()?new D.FC(this.e):new D.ph(this.e),d=b.g-b.x,this.Lh&&(d=b.g-d),0<d&&(this.Lh&&c.ni(),this.aL&&c.Ha(new D.K(this.aL)),c.zd(this.Dd),c.da(b.x),c.ta(b.y),D.Kl.Ub(c,d,b.j,this.Bn),c.kg()&&this.Aa.ja(c,new D.Ll(this.Dd)),(c=c.C())&&0<c.j)))b.y=b.y+c.j+this.D.rowColGap;this.je=[];if(d=this.RF.jb()){for(c=0;c<d.length;c++){var e=d[c];if("separatorDef"==e.getName()&&
(e=e.jb(),0<e.length&&"separator"==e[0].getName())){this.FE=D.n;break}}for(c=0;c<d.length;c++)e=d[c],b.x=this.Lh?this.S:0,"sectionGroup"==e.getName()?(this.FE&&(this.Dd||1<c)&&this.je.push((0,D.CG)(this,this.Bn,b)),this.je.push((0,D.AG)(this,e,this.Bn,b,this.Lh))):"section"==e.getName()&&(this.FE&&(this.Dd||1<c)&&this.je.push((0,D.CG)(this,this.Bn,b)),this.je.push((0,D.xG)(this,e,this.Bn,b,this.Lh)))}this.lc=this.Aj();for(b=0;b<this.Wt.length;b++)this.Lh?this.Wt[b].wi(this.lc.x):this.Wt[b].wi(this.lc.g);
this.Aa.rf(this);for(c=0;c<this.BJ.length;c++)b=this.BJ[c],this.Aa.ja(b,b),this.AF&&-1<D.Kf.Fa(this.AF,b.xj()+":"+b.Hw())&&(0,D.EG)(b,D.n)}else{this.Aa=new D.DG(this.e,this.zxa,this);this.Dd=this.UB.label;this.JF="true"==this.UB.disclosed;if(b=this.UB.style)this.aL=b["legend-title"],this.G3=b["sectionGroup-title"],this.I3=b["section-title"],this.$K=b["legend-item"];if(b=this.UB.noWrap)this.r1="false"==b;b=this.Lh?new D.H(this.S,0,this.S,this.X):new D.H(0,0,this.S,this.X);this.Bn=new D.Q(this.e);this.k(this.Bn);
if(this.Dd&&(c=this.Uz()?new D.FC(this.e):new D.ph(this.e),d=b.g-b.x,this.Lh&&(d=b.g-d),0<d&&(this.Lh&&c.ni(),this.aL&&c.Ha(new D.K(this.aL)),c.zd(this.Dd),c.da(b.x),c.ta(b.y),D.Kl.Ub(c,d,b.j,this.Bn),c.kg()&&this.Aa.ja(c,new D.Ll(this.Dd)),(c=c.C())&&0<c.j)))b.y=b.y+c.j+this.D.rowColGap;this.je=[];if(d=this.UB.separatorDef)for(c=0;c<d.length;c++)if((e=d[c].separator)&&0<e.length){this.FE=D.n;break}d=this.UB.sectionGroup;b.x=this.Lh?this.S:0;if(d)for(c=0;c<d.length;c++)this.FE&&(this.Dd||1<c)&&this.je.push((0,D.CG)(this,
this.Bn,b)),this.je.push((0,D.BG)(this,d[c],this.Bn,b,this.Lh));if(d=this.UB.section)for(c=0;c<d.length;c++)this.FE&&(this.Dd||1<c)&&this.je.push((0,D.CG)(this,this.Bn,b)),this.je.push((0,D.yG)(this,d[c],this.Bn,b,this.Lh));this.lc=this.Aj();for(b=0;b<this.Wt.length;b++)this.Lh?(this.lc.x=this.Wt[b].ek()-this.lc.g,this.Wt[b].wi(this.lc.x)):this.Wt[b].wi(this.lc.g+this.Wt[b].ek());this.Aa.rf(this);for(c=0;c<this.BJ.length;c++)b=this.BJ[c],this.Aa.ja(b,b),this.AF&&-1<D.Kf.Fa(this.AF,b.xj()+":"+b.Hw())&&
(0,D.EG)(b)}this.AF&&(this.lc=this.Aj(),this.Sb(new D.nv(this.lc.g,this.lc.j,this.lc.x,this.lc.y)));this.Lh&&this.Bn.F(-this.lc.x)};D.zG=function(b,c,d,e,f,g,h,j){this.Init(b,c,d,e,f,g,h,j)};D.D.l(D.zG,D.Q,"DvtCommonLegendSection");D.zG.prototype.Init=function(b,c,d,e,f,g,h,j){D.vG.q.Init.call(this,b);this.Dd=d;this.uz=e;this.tb=[];this.Ba=c;this.iB=f;this.wB=g;this.XJ=h?0:1;this.D=j};
D.FG=function(b,c,d,e,f,g,h){if(!c)return new D.kh(b.e);switch(h){case 1:h=new D.kf(b.e,c.groupColEna,d,e,f,g);var j=new D.kf(b.e,c.groupColOvr,d,e,f,g);c=new D.kf(b.e,c.groupColDwn,d,e,f,g);return new D.kh(b.e,h,j,c);default:return h=new D.kf(b.e,c.groupExpDwn,d,e,f,g),j=new D.kf(b.e,c.groupExpOvr,d,e,f,g),c=new D.kf(b.e,c.groupExpDwn,d,e,f,g),new D.kh(b.e,h,j,c)}};D.C=D.zG.prototype;
D.C.Sea=function(){var b=(0,D.Qe)()?-1:1;this.H3||(this.H3=this.Aj().j-this.Kv);0==this.XJ?("alta"==this.D.skin?(b=this.rb.getParent(),b.removeChild(this.rb),this.rb=this.ly,b.k(this.rb)):this.rb.Pc([this.Dr+1.5*b,this.Er+1.5,this.Dr+9.5*b,this.Er+5.5,this.Dr+1.5*b,this.Er+9.5]),this.Gfa=D.t,this.XJ=1,b=-this.H3):("alta"==this.D.skin?(b=this.rb.getParent(),b.removeChild(this.rb),this.rb=this.Bv,b.k(this.rb)):this.rb.Pc([this.Dr+1.5*b,this.Er+1.5,this.Dr+9.5*b,this.Er+1.5,this.Dr+5.5*b,this.Er+9.5]),
this.Gfa=D.n,this.XJ=0,b=this.H3);if(this.Gfa)for(var c=0;c<this.tb.length;c++)this.k(this.tb[c]);else for(c=0;c<this.tb.length;c++)this.removeChild(this.tb[c]);this.Ba.update(this,b)};D.C.LR=function(){"alta"==!this.D.skin&&this.rb.la(this.D.ovr)};D.C.KR=function(){"alta"==!this.D.skin&&this.rb.la(this.D.ena)};D.C.JR=function(){"alta"==!this.D.skin&&this.rb.la(this.D.dwn)};D.C.tj=function(b){return this.tb.push(b)};
D.C.L=function(b,c,d){b.k(this);b=new D.Q(this.e);this.k(b);this.Dr=c.x;this.Er=c.y;var e=d?-1:1;if("alta"==this.D.skin){var f=this.Ba.ij;this.Bv=(0,D.FG)(this,f,this.Dr,this.Er,this.D.buttonSize,this.D.buttonSize,0);this.ly=(0,D.FG)(this,f,this.Dr,this.Er,this.D.buttonSize,this.D.buttonSize,1);this.rb=this.Bv}else this.rb=new D.Lv(this.e,[this.Dr+1.5*e,this.Er+1.5,this.Dr+9.5*e,this.Er+1.5,this.Dr+5.5*e,this.Er+9.5]),this.rb.la(this.D.ena);b.k(this.rb);if((0,D.wf)())b.W(D.xz.we,this.Sea,D.t,this);
else{var g=this;this.Ba.Sc().ja(b,{ne:function(){return 0==g.XJ?g.iB:g.wB}});b.W(D.bi,this.Sea,D.t,this);b.W(D.Mh,this.LR,D.t,this);b.W(D.Nh,this.KR,D.t,this);b.W(D.Ar,this.JR,D.t,this)}this.XJ=0;c.x+=(("alta"==this.D.skin&&d?0:this.D.buttonSize)+this.D.rowColGap)*e;this.Dd&&(e=this.Ba.Uz()?new D.FC(this.e):new D.ph(this.e),f=c.g-c.x,d&&(f=c.g-f),0<f&&(d&&e.ni(),this.uz&&e.Ha(new D.K(this.uz)),e.zd(this.Dd),e.da(c.x),e.ta(c.y),D.Kl.Ub(e,f,c.j,b),e.kg()&&this.Ba.Sc().ja(e,new D.Ll(this.Dd)),b=e.C(),
c.y=c.y+window.Math.max(b?b.j:0,this.D.buttonSize)+this.D.rowColGap));c.x+=(this.D.buttonSize+this.D.rowColGap)*(d?1:-1);this.Kv=this.Aj().j};D.vG=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.vG,D.Q,"DvtCommonLegendSection");D.vG.prototype.Init=function(b,c,d,e,f){D.vG.q.Init.call(this,b);this.Dd=d;this.uz=e;this.tb=[];this.Ba=c;this.D=f};D.vG.prototype.tj=function(b){return this.tb.push(b)};D.vG.prototype.Mq=(0,D.B)("tb");
D.vG.prototype.L=function(b,c,d){b.k(this);if(this.Dd){b=this.Ba.Uz()?new D.FC(this.e):new D.ph(this.e);var e=c.g-c.x;d&&(e=c.g-e);0<e&&(d&&b.ni(),this.uz&&b.Ha(new D.K(this.uz)),b.zd(this.Dd),b.da(c.x),b.ta(c.y),D.Kl.Ub(b,e,c.j,this),b.kg()&&this.Ba.Sc().ja(b,new D.Ll(this.Dd)),d=b.C(),c.y=c.y+(d?d.j:0)+this.D.rowColGap)}};D.wG=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.wG,D.Q,"DvtCommonLegendRow");D.C=D.wG.prototype;
D.C.Init=function(b,c,d,e,f){D.wG.q.Init.call(this,b);this.Ba=c;this.ap=d;this.Efa=e;this.gQ=D.t;this.D=f};D.C.xj=function(){return this.ap.attributeGroupId};D.C.Hw=function(){return this.ap.itemId};D.C.c6=function(){return this.ap.hideAttrs};D.C.dh=(0,D.ba)("Ya");D.C.setMarker=function(b,c,d,e,f){this.UT=b;this.H=c;this.Ng=d?d:"#000000";this.$o=e;this.C2=f};D.EG=function(b,c){b.gQ=!b.gQ;b.Cn.mI(b.Ng);b.Oj();c||(b.Ba.lc=b.Ba.Aj(),b.Ba.Sb(new D.nv(b.Ba.lc.g,b.Ba.lc.j,b.Ba.lc.x,b.Ba.lc.y)))};
D.wG.prototype.ee=function(){if(this.Ba.hM){var b=this.Ba.sJ(),c=[(0,D.wg)(b,this.gQ?"STATE_HIDDEN":"STATE_VISIBLE")];return(0,D.en)(this.Ya,c,b)}return D.q};D.wG.prototype.Oj=function(){(0,D.fn)()||(0,D.gn)(this,"label",this.ee())};
D.wG.prototype.L=function(b,c,d){if(this.ap){var e=this.Ba,f=this.ap.attributeGroupId,g=this.ap.itemId;e.VP[f]==D.q&&(e.VP[f]={});e.VP[f][g]=this;this.Ba.BJ.push(this);e=this.Ba;f=this.ap.hideAttrs;e.$0[f]||(e.$0[f]=this)}b.k(this);b=c.x;d&&(c.x-=this.D.indicatorSize);var h;if(this.UT||this.H!=D.q)h=new D.Vm(this.e,this.UT?[this.UT]:this.H,this.D[D.DvtCommonLegend.Eqa],c.x,c.y,this.D.indicatorSize,this.D.indicatorSize),e=D.Fo.Rka(this.e,this.H),!this.UT&&!e&&(this.$o?h.G(new D.nm(this.$o,this.Ng)):
h.la(this.Ng,this.C2)),this.k(h),c.x=d?c.x-this.D.rowColGap:c.x+this.D.indicatorSize+this.D.rowColGap;this.Cn=h;h=new D.H;this.Ya&&(this.Ba.hM&&(this.If("img"),this.Oj()),e=c.g-c.x,d&&(e=c.g-e),0>e?this.Ba.Sc().ja(this.Cn,new D.Ll(this.Ya)):(f=this.Ba.Uz()?new D.FC(this.e):new D.ph(this.e),d&&f.ni(),this.Efa&&f.Ha(new D.K(this.Efa)),f.zd(this.Ya),f.da(c.x),f.ta(c.y),D.Kl.Ub(f,e,c.j,this)?(h=f.C(),f.kg()&&this.Ba.Sc().ja(f,new D.Ll(this.Ya))):this.Ba.Sc().ja(this.Cn,new D.Ll(this.Ya))));c.y=c.y+window.Math.max(this.D.indicatorSize,
h.j)+this.D.rowColGap;c.x=b};D.DG=function(b,c,d){this.Init(b,c,d);this.Ba=d};D.D.l(D.DG,D.tm,"DvtCommonLegendEventManager");D.C=D.DG.prototype;D.C.hh=function(b){D.DG.q.hh.call(this,b);this.Bt(b)};D.C.xo=function(b){D.DG.q.xo.call(this,b);(0,D.GG)(this,b)};D.C.pk=function(b){D.DG.q.pk.call(this,b);(0,D.GG)(this,b)};D.C.Vs=function(b){D.DG.q.Vs.call(this,b);this.Bt(b)};
D.C.Bt=function(b){if(this.Ba.hM){var c=this.na(b.target);if(c instanceof D.wG){var d=c.Hw(),e=c.xj();(0,D.EG)(c);b=new D.HG(d,e,c.gQ?"hide":"show",b);this.Ba.Sb(b)}}};D.GG=function(b,c){var d=b.na(c.target);if(d instanceof D.wG){if(b.Ba.vza){var e=d.Hw(),f=d.xj(),e=new D.IG(e,f,d.c6(),c.type,c);b.Ba.Sb(e)}b.Ba.hM&&b.Lx(d)}};
});