define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.pG=function(b,c){this.Init(c===D.t?"sunburstRotationInput":"sunburstRotation");this.Xc=b%360};(0,D.qa)("DvtSunburstRotationEvent",D.pG);D.D.l(D.pG,D.pf,"DvtSunburstRotationEvent");D.pG.TYPE="sunburstRotation";D.pG.TYPE_INPUT="sunburstRotationInput";D.pG.prototype.Gla=(0,D.B)("Xc");D.pG.prototype.getStartAngle=D.pG.prototype.Gla;
D.RP=function(b,c,d){this.Init(b,c,d)};D.D.l(D.RP,D.aG,"DvtBaseSunburst");D.C=D.RP.prototype;D.C.Init=function(b,c,d){D.RP.q.Init.call(this,b,c,d);this.lf=new D.nF;this.fd=2*window.Math.PI};D.C.Uu=function(b){return(new D.qF(this)).parse(b)};D.C.xI=function(b){D.RP.q.xI.call(this,b);this.Aia=b.rotation;this.yia=(0,D.Vp)()?"url("+this.rh.cursorRotate+"), auto":"url("+this.rh.cursorRotate+") 8 8, auto";this.Xc=(360-b.wW)*D.ZE/360;this.Xc>window.Math.PI&&(this.Xc-=D.ZE)};
D.C.uo=function(b){var c=window.Math.max(window.Math.ceil(3*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;(0,D.dG)(this,b);(0,D.eG)(this,b);this.sja=window.Math.floor(window.Math.min(b.g,b.j)/2);this.Pa&&D.oF.Wn(this.sja,this.Pa,this.Xc,this.fd,this.tP)};
D.C.xi=function(b,c){(0,D.cG)(this,b);this.xl&&b.k(this.xl);this.Ba&&(b.k(this.Ba),this.Ba=D.q);this.WG=new D.G(c.x+c.g/2,c.y+c.j/2);if("on"==this.Aia&&(0,D.gG)(this)){var d=(0,D.wf)()?60:15,d=new D.Hv(this.e,c.x+c.g/2,c.y+c.j/2,this.sja+d);(0,D.Yg)(d);d.setCursor(this.yia);b.k(d);this.Ua().ja(d,new D.Ml(D.q,"_rotationShape"))}d=new D.Q(this.e);(0,D.jg)(d,this.WG.x,this.WG.y);b.k(d);if((0,D.gG)(this)){var e=new D.Q(this.e);d.k(e);this.Pa.L(e);this.Ut=new D.Q(this.e);d.k(this.Ut);this.bfa=new D.Q(this.e);
d.k(this.bfa)}else(0,D.fG)(this,b)};D.C.bE=function(b,c,d,e){return new D.rF(b,c,d,e)};D.C.sX=function(b,c){if("fan"===this.FW&&(0,D.gG)(this)){this.JZ(0);var d=new D.im(this.e,this,this.XD);(0,D.P)(d.R,"typeNumber",this,this.Mva,this.JZ,2*window.Math.PI);return d}return D.RP.q.sX.call(this,b,c)};D.C.qX=function(){var b=D.RP.q.qX.call(this);b&&(0,D.jg)(b,this.WG.x,this.WG.y);return b};
D.C.vo=function(){if(!this.GW){this.fa.vi();var b=new D.H(0,0,this.ub,this.Lb);this.uo(b);this.xi(this.fa,b);for(var b=this.Nb?this.Nb.getSelection():[],c=0;c<b.length;c++)b[c].Ob(D.n)}this.fd<2*window.Math.PI&&this.JZ(2*window.Math.PI);D.RP.q.vo.call(this)};D.C.HP=function(b){this.Ut.k(b);!(0,D.yn)()&&!(0,D.zn)()&&((0,D.An)(this.Ut),(0,D.Xg)(this.Ut,D.am))};D.C.Mva=(0,D.B)("fd");D.C.JZ=function(b){this.fd=b;this.uo(new D.H(0,0,this.ub,this.Lb));this.Pa&&(0,D.eF)(this.Pa,D.n)};
D.sF=function(b,c){b.Z_=c;b.xG=new D.af(b.e,0,0,b.ub,b.Lb);(0,D.Yg)(b.xG);b.xG.setCursor(b.yia);b.k(b.xG);b.Ua().ja(b.xG,new D.Ml(D.q,"_rotationShape"))};D.uF=function(b,c){var d=c-b.Z_;b.Z_=c;b.Xc+=d;b.Xc<-window.Math.PI?b.Xc+=2*window.Math.PI:b.Xc>window.Math.PI&&(b.Xc-=2*window.Math.PI);b.uo(new D.H(0,0,b.ub,b.Lb));b.Pa&&(0,D.eF)(b.Pa,D.n);b.Xa(new D.pG(360-window.Math.round(180*b.Xc/window.Math.PI),D.t))};
D.vF=function(b){b.Z_=D.q;b.removeChild(b.xG);b.xG=D.q;var c=360-window.Math.round(180*b.Xc/window.Math.PI);b.Xa(new D.pG(c,D.t));b.Xa(new D.pG(c,D.n))};D.tF=function(b,c,d){return window.Math.atan2(d-b.WG.y,c-b.WG.x)};
D.QP=(0,D.w)();(0,D.qa)("DvtSunburst",D.QP);D.D.l(D.QP,D.RP,"DvtSunburst");D.QP.newInstance=function(b,c,d){var e=new D.QP;e.Init(b,c,d);return e};D.QP.getDefaults=function(b){return(0,D.lG)(new D.nF,b)};D.QP.prototype.L=function(b,c,d){b?(this.N=this.lf.Vg(b),(0,D.Gg)()||(this.N.animationOnDisplay="none",this.N.animationOnDataChange="none")):this.N||(this.N=(0,D.DC)(this));b=(new D.pF).F8(this.N);D.QP.q.L.call(this,b,c,d)};D.QP.prototype.render=D.QP.prototype.L;
D.QP.prototype.Kc=function(){this.Mg||(this.Mg=new D.lF);return this.Mg};
D.qF=function(b){this.Init(b)};D.D.l(D.qF,D.tl,"DvtSunburstParser");D.qF.prototype.dn=function(b,c,d){return new D.YE(b,c,d)};D.qF.prototype.gm=function(b){var c=D.qF.q.gm.call(this,b);c.rotation=b.o("r");c.wW=b.o("sa");if(c.wW===D.q||(0,window.isNaN)(c.wW))c.wW=90;return c};D.qF.prototype.Vu=function(b){var c=D.qF.q.Vu.call(this,b);c.DV=b.o("ha");c.fGa=b.o("r");return c};
D.qF.prototype.kY=function(b,c,d,e){e.NODE_DEFAULT_COLOR_STYLE=b.v("border-color");e.NODE_HOVER_COLOR_STYLE=c.v("border-color");e.NODE_SELECTED_INNER_COLOR_STYLE=d.v("-tr-inner-color");e.NODE_SELECTED_OUTER_COLOR_STYLE=d.v("-tr-outer-color")};
D.YE=function(b,c,d){this.Init(b,c,d);this.Po=c.CV?c.CV:"auto";this.NF=c.DV;this.Wj=c.fGa};D.D.l(D.YE,D.Pl,"DvtSunburstNode");D.ZE=2*window.Math.PI;
D.YE.prototype.L=function(b){if(this.Jv){this.MS=b;this.H=this.W_();b.k(this.H);var c=this.nM;if(!this.pf&&(0==this.ji&&this.fd==D.ZE)&&c){var d=window.Math.sqrt(2),e=this.Mh*d-4;this.Ta=-this.Mh/d+2;this.mb=-this.Mh/d+2;d=this.I.EZ;d.Ko=this.gi;0<e&&0<e&&((0,D.sn)(d,e),(0,D.tn)(d,e),d.Jf((0,D.rm)(this)),this.N_=c=D.I.ED(d,c,this.H),d=c.C(),(0,D.jg)(c,this.Ta+(e-d.g)/2,this.mb+(e-d.j)/2))}else this.Ya=this.jK(this.H),this.Ya!=D.q&&(this.H.k(this.Ya),this.$o&&(d=this.Ya.Rb(),this.ep=new D.af(this.I.e,
d.x,d.y,d.g,d.j),this.ep.la("#FFFFFF"),this.ep.ia(D.t),this.H.k(this.ep),e=this.Ya.ma(),(0,D.$E)(e)||this.ep.ra(e),this.H.k(this.Ya)));this.H.If("img");this.Oj();this.Gu(b)}};D.YE.prototype.Ob=function(b){D.YE.q.Ob.call(this,b);this.Na()?(this.H.Ob(D.n),this.I.HP(this.H)):(this.H.Ob(D.t),this.MS&&this.MS.k(this.H))};D.YE.prototype.Fc=function(){this.H&&this.Jv&&(this.H.Fc(),this.Na()?this.I.HP(this.H):this.I.bfa.k(this.H))};
D.YE.prototype.nc=function(){this.H&&(this.Jv&&!this.Gg())&&(this.H.nc(),!this.Na()&&this.MS&&this.MS.k(this.H))};D.aF=function(b){return"i"==b.pR||"ir"==b.pR};
D.YE.prototype.Ef=function(b){var c,d,e,f;if(b.type==D.bi)return D.YE.q.Ef.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;for(f=this;f.pf;)f=f.pf;d=(0,D.em)(this,f,(0,D.mm)(this));a:{for(e=0;e<d.length;e++)if(this===d[e])break a;e=-1}var g=this.Xc+this.fd/2,g=(0,D.bF)(g);switch(c){case 38:if(this===f||180<g){if(c=this.tS)if(d=c.Xc+c.fd/2,d=(0,D.bF)(d),180<d)return c;b=(0,D.xq)(this,b,(0,D.cm)(this))}else b=(0,D.cF)(this);break;case 40:if(this===f||0<=g&&180>=g){if(c=this.tS)if(d=c.Xc+c.fd/
2,d=(0,D.bF)(d),0<=d&&180>=d)return c;b=(0,D.xq)(this,b,(0,D.cm)(this))}else b=(0,D.cF)(this);break;case 37:b=1==d.length?this:0==e?d[d.length-1]:d[e-1];break;case 39:b=1==d.length?this:e==d.length-1?d[0]:d[e+1];break;default:b=this}(0,D.dm)(b);return b};D.cF=function(b){var c=b.pf;c&&(b=c,(0,D.dm)(c));(0,D.dm)(b);return b};D.bF=function(b){b=D.Mz.W7(b);0>b?b+=360:360<b&&(b-=360);return b};D.C=D.YE.prototype;
D.C.hf=function(){if(this.H){var b=this.H.C(),c=new D.G(b.x,b.y),c=(0,D.vg)(this.H,c);b.x=c.x;b.y=c.y;return b}return new D.H(0,0,0,0)};D.C.Pm=function(){return this.H?this.H.oa():D.q};D.C.KU=function(){return(0,D.vg)(this.H,(0,D.dF)(0.5*(this.Mh+this.ji),this.Xc+this.fd/2))};D.C.cO=function(b,c,d,e){this.ji=b;this.Mh=c;this.Xc=d;this.fd=e;this.Jv=D.n};D.C.gE=function(){return this.OE?(0,D.ax)():D.YE.q.gE.call(this)};
D.C.ml=function(){var b=D.N.sd(this.Ng),c=D.N.rd(this.Ng),d=D.N.qd(this.Ng);return[this.ji,this.Mh,this.Xc,this.fd,b,c,d]};D.C.Ao=function(b){this.cO(b[0],b[1],b[2],b[3]);this.Ng=D.N.hx(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));(0,D.eF)(this,D.t)};D.C.Wf=function(b,c){c.Jv&&0<c.fd?D.YE.q.Wf.call(this,b,c):this.Ug(b)};D.C.contains=function(b,c){var d=(0,D.fF)(b,c);return window.Math.sqrt(b*b+c*c)>=this.ji&&window.Math.sqrt(b*b+c*c)<=this.Mh&&(0,D.gF)(this,d)};
D.gF=function(b,c){for(;c<b.Xc;)c+=D.ZE;for(;c-b.Xc>D.ZE;)c-=D.ZE;return c>=b.Xc&&c<=b.Xc+b.fd};D.dF=function(b,c){return{x:window.Math.cos(c)*b,y:window.Math.sin(c)*b}};D.fF=function(b,c){var d=window.Math.atan2(c,b);0>d?d+=D.ZE:d>D.ZE&&(d-=D.ZE);return d};
D.YE.prototype.W_=function(){if(!this.fd||0>=this.fd)return D.q;var b=(0,D.hF)(this),b=new D.ef(this.I.e,b);this.I.Ua().ja(b,this);b.B(this.$());b.G(this.gE());var c=(0,D.jm)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR_STYLE"),d=(0,D.jm)(this,"#000000","NODE_SELECTED_OUTER_COLOR_STYLE"),e=(0,D.jm)(this,"#FFFFFF","NODE_HOVER_COLOR_STYLE");b.Z(new D.ff((0,D.jm)(this,"#FFFFFF","NODE_DEFAULT_COLOR_STYLE"),0.3));b.$q(new D.ff(e,1,3));b.br(new D.ff(c,1,1.5),new D.ff(d,1,3.5));b.Ku(new D.ff(e,1,3));b.Jg(this.dc());
this.OE&&(b.B(0.001),b.ia(D.t));return b};
D.hF=function(b){var c,d,e,f;b.fd<D.ZE?(c=(0,D.dF)(b.Mh,b.Xc),d=(0,D.dF)(b.Mh,b.Xc+b.fd),e=(0,D.dF)(b.ji,b.Xc+b.fd),f=(0,D.dF)(b.ji,b.Xc),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Mh,b.Mh,b.fd,1,d.x,d.y)+window.DvtPathUtils.lineTo(e.x,e.y)+window.DvtPathUtils.arcTo(b.ji,b.ji,b.fd,0,f.x,f.y)+window.DvtPathUtils.closePath()):(c=(0,D.dF)(b.Mh,b.Xc),d=(0,D.dF)(b.Mh,b.Xc+b.fd/2),e=(0,D.dF)(b.ji,b.Xc),f=(0,D.dF)(b.ji,b.Xc+b.fd/2),c=window.DvtPathUtils.moveTo(c.x,c.y)+window.DvtPathUtils.arcTo(b.Mh,
b.Mh,b.fd/2,1,d.x,d.y)+window.DvtPathUtils.arcTo(b.Mh,b.Mh,b.fd/2,1,c.x,c.y),0<b.ji&&(c+=window.DvtPathUtils.moveTo(f.x,f.y)+window.DvtPathUtils.arcTo(b.ji,b.ji,b.fd/2,0,e.x,e.y)+window.DvtPathUtils.arcTo(b.ji,b.ji,b.fd/2,0,f.x,f.y)),c+=window.DvtPathUtils.closePath());return c};
D.YE.prototype.jK=function(b){if(!this.tz||!b||!this.Po||"off"==this.Po)return D.q;var c=D.t;if("auto"==this.Po){if(c=!(0,D.Vp)())(0,D.iF)(),c="Windows"==D.jF;c=c?D.t:D.n}else"rotated"==this.Po&&(c=D.n);if(c&&this.fd<2*window.Math.PI){var d=window.Math.max(this.ji,10),e=this.Mh-d-6,f=1.1*this.fd*(d+6);if(6>=f)b=D.q;else if(c=new D.ph(this.I.e,this.tz,0,0),c.Jf((0,D.rm)(this)),(0,D.qm)(this,c),D.Kl.Ub(c,e,f,b)){f=(d+this.Mh)/2;if("s"==this.NF||"e"==this.NF)b.k(c),b=c.C().g,"s"==this.NF?f=d+4.5+b/2:
"e"==this.NF&&(f=d+e-4.5-b/2);b=(0,D.dF)(f,this.Xc+this.fd/2);c.Re();c.Ae();d=this.Xc+this.fd/2;d=d>=D.ZE?d-D.ZE:d;d=0>d?d+D.ZE:d;d>0.5*window.Math.PI&&d<1.5*window.Math.PI&&(d+=window.Math.PI);c.Zi(d);(0,D.jg)(c,b.x,b.y);c.ia(D.t);b=c}else b=D.q}else{if(0==this.ji)c={x:0,y:0};else if(c=(0,D.dF)((this.ji+this.Mh)/2,this.Xc+this.fd/2),d=3*(0,D.rm)(this)/2,e=(0,D.fF)(c.x+d/2,c.y),!(0,D.gF)(this,(0,D.fF)(c.x-d/2,c.y))||!(0,D.gF)(this,e))c=D.q;if(c){d=new D.ph(this.I.e,this.tz,c.x,c.y,D.q);d.Jf((0,D.rm)(this));
(0,D.qm)(this,d);d.Re();d.Ae();d.ia(D.t);for(var e=D.Kl.Qi(d),g=f=c.x,h=c.y-e.j/2,j=c.y+e.j/2;this.contains(f,h)&&this.contains(f,j);)f--;for(;this.contains(g,h)&&this.contains(g,j);)g++;f+=3;g-=3;c=2*window.Math.min(c.x-f,g-c.x);c<e.g&&(d.da((f+g)/2),c=g-f);b=D.Kl.Ub(d,c,e.j,b)?d:D.q}else b=D.k}return b};
D.YE.prototype.Rw=function(){if(!this.Ec){var b;b=this.H;if(!b||!(0,D.aF)(this))b=D.q;else{var c;if(this.sg){c=this.I.e;var d=this.I.rh,e=new D.kf(c,d.collapseUp,0,0,16,16),f=new D.kf(c,d.collapseOver,0,0,16,16),d=new D.kf(c,d.collapseDown,0,0,16,16)}else c=this.I.e,d=this.I.rh,e=new D.kf(c,d.expandUp,0,0,16,16),f=new D.kf(c,d.expandOver,0,0,16,16),d=new D.kf(c,d.expandDown,0,0,16,16);(0,D.Yg)(e);(0,D.Yg)(f);(0,D.Yg)(d);c=new D.kh(c,e,f,d);c.W(D.bi,this.y5,D.t,this);e=(0,D.dF)(this.Mh,this.Xc+this.fd/
2);(0,D.jg)(c,e.x-8,e.y-8);b.k(c);b=this.sg?this.I.rh.collapse:this.I.rh.expand;this.I.Ua().ja(c,new D.Ml(this,this.getId(),b));b=c}this.Ec=b}D.YE.q.Rw.call(this)};D.YE.prototype.Sq=function(){this.Ec&&this.H&&(this.H.removeChild(this.Ec),this.Ec=D.q);D.YE.q.Sq.call(this)};
D.eF=function(b,c){if(b.H){var d=(0,D.hF)(b);b.H.kk(d);if(b.pf||!(0==b.ji&&b.fd==D.ZE))b.Ya&&b.H.removeChild(b.Ya),b.Ya=b.jK(b.H),b.ep&&(b.H.removeChild(b.ep),b.ep=D.q);b.H.G(b.gE());if(c)for(var d=b.jb(),e=0;e<d.length;e++)(0,D.eF)(d[e],D.n)}};
D.YE.prototype.y5=function(){this.sg=!this.sg;var b=this.I,c=this.sg,d=this.getId();b.sL=d;if(c)b.Xa(new D.XE("sunburstExpand",this.getId()));else{var c=b.WX,d=this.getId(),d=c.indexOf('\x3cn id\x3d"'+d),e=c.indexOf("\x3e",d),f=c.substring(d,e),f=-1<f.indexOf("di\x3d")?f.replace('di\x3d"t"','di\x3d"f"'):f+'di\x3d"f"';b.L(c.substring(0,d)+f+c.substring(e),b.ub,b.Lb);b.Xa(new D.XE("sunburstCollapse",this.getId()))}this.Oj()};D.YE.prototype.eb=(0,D.B)("sg");
D.kF=function(b){return b.Wj!=D.q?(0,window.Number)(b.Wj):b.pf?1:b.OE?0.25:b.nM?1:0.5};D.YE.prototype.ee=function(){var b=[];this.dc()&&b.push((0,D.wg)(this.ed,this.Na()?"STATE_SELECTED":"STATE_UNSELECTED"));(0,D.aF)(this)&&b.push((0,D.wg)(this.ed,this.eb()?"STATE_EXPANDED":"STATE_COLLAPSED"));return(0,D.en)(this.zy,b,this.ed)};D.YE.prototype.Oj=function(){!(0,D.fn)()&&this.H&&(0,D.gn)(this.H,"label",this.ee())};
D.oF={};D.D.l(D.oF,D.D,"DvtSunburstLayout");D.oF.Wn=function(b,c,d,e,f){var g=D.oF.Nca(c);D.oF.Qf(b/g,c,d,e,f,0)};D.oF.Qf=function(b,c,d,e,f,g){var h=g+(0,D.kF)(c)*b;c.cO(g,h,d,e);g=c.jb();if(g!=D.q&&c.eb()){"on"==f&&(g=g.slice(0),g.sort(function(b,c){return c.sc()-b.sc()}));(0,D.Qe)(c.I.e)&&(g=g.slice(0).reverse());var j=0;for(c=0;c<g.length;c++)j+=0<g[c].sc()?g[c].sc():0;for(c=0;c<g.length;c++){var m=g[c];if(!(0>=m.sc())){var o=m.sc()/j*e;D.oF.Qf(b,m,d,o,f,h);d+=o}}}};
D.oF.Nca=function(b){var c=0,d=b.jb();if(d&&0<d.length){for(var e=0;e<d.length;e++)var f=D.oF.Nca(d[e]),c=window.Math.max(c,f);return c+(0,D.kF)(b)}return(0,D.kF)(b)};
D.XE=function(b,c){this.Init(b);this.Oa=c?c:D.q};D.D.l(D.XE,D.pf,"DvtSunburstExpandCollapseEvent");D.XE.prototype.getId=(0,D.B)("Oa");
D.rF=function(b,c,d,e){D.sm.call(this,b,c,d,e)};D.D.l(D.rF,D.sm,"DvtSunburstEventManager");D.C=D.rF.prototype;D.C.ol=function(b){var c=this.na(b.target);c&&c.getId&&"_rotationShape"==c.getId()&&!this.pQ?(this.pQ=D.n,b=(0,D.Pg)(this.e,b.pageX,b.pageY),c=this.I,(0,D.sF)(c,(0,D.tF)(c,b.x,b.y))):D.rF.q.ol.call(this,b)};D.C.Ip=function(b){if(this.pQ){b=(0,D.Pg)(this.e,b.pageX,b.pageY);var c=this.I;(0,D.uF)(c,(0,D.tF)(c,b.x,b.y))}else D.rF.q.Ip.call(this,b)};
D.C.hn=function(b){this.pQ?(this.pQ=D.t,(0,D.vF)(this.I)):D.rF.q.hn.call(this,b)};D.C.hm=function(b){var c=D.n,d=b.keyCode,e=this.Be(),f=this.I;(0,D.aF)(e)&&((0,D.py)(b)&&!e.eb()||(0,D.qy)(b)&&e.eb()||b.ctrlKey&&13==d)?(e.y5(),b.preventDefault()):f&&"on"==f.Aia&&(37==d||39==d)&&!b.ctrlKey&&b.altKey&&b.shiftKey?(d=37==d?-5*(window.Math.PI/180):5*(window.Math.PI/180),(0,D.sF)(f,0),(0,D.uF)(f,d),(0,D.vF)(f),b.preventDefault()):c=D.rF.q.hm.call(this,b);return c};
D.C.jE=function(b){var c=this.na(b.target);c&&(c.getId&&"_rotationShape"==c.getId())&&(0,D.St)(b,this.yqa,this)};D.C.TO=function(b){(0,D.Tt)(this.Pb,b,"rotateKey")};D.C.SO=function(b){(0,D.Vt)(this.Pb,b,"rotateKey")};D.C.yqa=function(b,c){if(1>=(0,D.Wt)(this.Pb,"rotateKey").length){(0,D.Xt)(this.Pb,c.identifier,"rotateKey","rotateKey","rotateKey",this.xqa,this.wqa,this);(0,D.Yt)(this.Pb,c.identifier,D.t);var d=(0,D.Pg)(this.e,c.pageX,c.pageY),e=this.I;(0,D.sF)(e,(0,D.tF)(e,d.x,d.y));b.Az()}};
D.C.xqa=function(b,c){var d=(0,D.Pg)(this.e,c.pageX,c.pageY),e=this.I;(0,D.uF)(e,(0,D.tF)(e,d.x,d.y));b.preventDefault()};D.C.wqa=function(){(0,D.vF)(this.I)};
D.lF=(0,D.w)();D.D.l(D.lF,D.Pn,"DvtSunburstBundle");D.lF._defaults={COLOR:"Color",SIZE:"Size"};D.lF.prototype.no=function(b){var c=D.lF.q.no.call(this,b);return c?c:D.lF._defaults[b]};D.lF.prototype.xx=(0,D.ca)("DvtSunburstBundle");
D.nF=function(){this.Init({skyros:D.mF,alta:{}})};D.D.l(D.nF,D.Cl,"DvtSunburstDefaults");D.mF={rotation:"on"};
D.pF=(0,D.w)();D.D.l(D.pF,D.Wl,"DvtSunburstJsonUtils");D.C=D.pF.prototype;D.C.KO=(0,D.ca)("sunburst");D.C.kJ=function(b){var c=D.pF.q.kJ.call(this,b),c=c+this.Ea("r",b.rotation),c=c+this.Ea("sa",(b.startAngle+360)%360);b=b.animationOnDisplay;return c="auto"==b?c+this.Ea("adi","fan"):c+this.Ea("adi",b)};
D.C.lJ=function(b,c){var d=D.pF.q.lJ.call(this,b,c),d=d+this.Ea("ld",c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay),e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"inner"==e?d+=this.Ea("ha","s"):"outer"==e&&(d+=this.Ea("ha","e"));e=c.radius;e!=D.q&&!(0,window.isNaN)(e)&&(d+=this.Ea("r",e));return d};
D.C.eZ=function(b){var c,d=new D.lF;c="\x3cresources"+this.Ea("legendSize",(0,D.wg)(d,"SIZE"));c+=this.Ea("legendColor",(0,D.wg)(d,"COLOR"));c+=this.Ea("cursorRotate",b._resources.rotateCursor);c+=this.Ea("alta","true");return c+"/\x3e\n"};
D.C.mJ=function(b){var c=D.pF.q.mJ.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ea("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.borderColor)&&(c+=this.Ea("node","border-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ea("node-hover","border-color: "+d));(b=b.nodeDefaults.selectedColor)&&(c+=this.Ea("node-selected","border-color: "+b));return c+"/\x3e\n"};
});