define(['./DvtToolkit', './DvtBaseTreeView'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.nG=function(b,c,d){this.Init(b,c,d)};D.D.l(D.nG,D.aG,"DvtBaseTreemap");D.C=D.nG.prototype;D.C.Init=function(b,c,d){D.nG.q.Init.call(this,b,c,d);this.lf=new D.qn};D.C.Uu=function(b){return(new D.Sn(this)).parse(b)};D.C.xI=function(b){D.nG.q.xI.call(this,b);this.Qf=b.Wn;this.wwa=b.S6;this.Qf&&(this.Qf.tP=this.tP);this.ad=[];if((b=b.vma)&&this.Pa){var c=(0,D.cm)(this.Pa);c.push(this.Pa);for(var d=0;d<c.length;d++)if(c[d].getId()==b){this.ad.push(c[d]);break}}};
D.C.uo=function(b){var c=window.Math.max(window.Math.ceil(7*window.Math.min(b.g,b.j)/400),2);b.x+=c;b.y+=c;b.g-=2*c;b.j-=2*c;c=this.Qf.X5(this,1);b.x+=c;b.g-=2*c;(0,D.dG)(this,b);(0,D.eG)(this,b);b.x-=c;b.g+=2*c;c=this.ad.length;if(0<c&&this.kS)this.Qf.Wn(this,this.ad[c-1],b.x,b.y,b.g,b.j,D.n);else{this.Pa&&this.Qf.Wn(this,this.Pa,b.x,b.y,b.g,b.j,D.t);for(var d=0;d<c;d++)this.Qf.Wn(this,this.ad[d],b.x,b.y,b.g,b.j,D.n)}};
D.C.xi=function(b){(0,D.cG)(this,b);this.xl&&b.k(this.xl);this.Ba&&(b.k(this.Ba),this.Ba=D.q);if((0,D.gG)(this)){this.V0=new D.Q(this.e);b.k(this.V0);this.lxa?this.lxa.L(b):this.Pa.De()?this.Pa.Gu(b):this.Pa.L(b);this.t1=new D.Q(this.e);b.k(this.t1);this.Ut=new D.Q(this.e);b.k(this.Ut);b.k(this.V0);this.Hy=new D.Mv(this.e,[]);this.Hy.bb(D.t);this.Hy.ia(D.t);(0,D.bn)(this.Hy);b.k(this.Hy);for(b=0;b<this.ad.length;b++){var c=this.ad[b].Da();this.t1.k(c)}}else(0,D.fG)(this,b)};
D.C.vo=function(){this.GW||(this.fa.vi(),this.uo(new D.H(0,0,this.ub,this.Lb)),this.xi(this.fa),this.HY());D.nG.q.vo.call(this)};D.C.HY=function(){for(var b=this.Nb?this.Nb.getSelection():[],c=0;c<b.length;c++)if(0<this.ad.length){var d=this.ad[this.ad.length-1];(b[c]==d||b[c].lD(d))&&b[c].Ob(D.n)}else b[c].Ob(D.n)};D.C.wx=function(b){return new D.Un(b)};D.C.bE=function(b,c,d,e){return new D.Qn(b,c,d,e)};
D.C.a$=function(b){var c=(0,D.Bn)(this);return c?(0,D.Cn)(this,(0,D.fm)(c)):b?(0,D.Cn)(this,(0,D.fm)(b)):D.q};D.C.HP=function(b){for(var c=0,d=this.Ut.Ca(),e=0;e<d;e++){var f=this.Ut.ca(e);b.zIndex>f.zIndex&&(c=e+1)}c<d?this.Ut.Ia(b,c):this.Ut.k(b)};D.Bn=function(b){return b.ad&&0<b.ad.length?b.ad[b.ad.length-1]:D.q};
D.In=function(b,c){if(b.vI){for(var d=b.Nb?b.Nb.getSelection():[],e=0;e<d.length;e++)d[e].Ob(D.t);for(var d=[(0,D.Fn)(c)],e=(0,D.cm)(c),f=0;f<e.length;f++)d.push((0,D.Fn)(e[f]));b.bn=new D.Zv(b.e,d);b.bn.xd(b.vo,b);b.Aa.zs(b);b.bn.play()}else b.L(D.q,b.ub,b.Lb,D.n)};D.Cn=function(b,c){var d=b.Aa.Nj;return d?d.ZM(c):c&&0<c.length?c[0]:D.q};
D.mG=(0,D.w)();(0,D.qa)("DvtTreemap",D.mG);D.D.l(D.mG,D.nG,"DvtTreemap");D.mG.newInstance=function(b,c,d){var e=new D.mG;e.Init(b,c,d);return e};D.mG.getDefaults=function(b){return(0,D.lG)(new D.qn,b)};D.mG.prototype.L=function(b,c,d,e){b?(this.N=this.lf.Vg(b),(0,D.Gg)()||(this.N.animationOnDisplay="none",this.N.animationOnDataChange="none")):this.N||(this.N=(0,D.DC)(this));b=e?D.q:(new D.Rn(this.e)).F8(this.N);D.mG.q.L.call(this,b,c,d)};D.mG.prototype.render=D.mG.prototype.L;
D.mG.prototype.Kc=function(){this.Mg||(this.Mg=new D.On);return this.Mg};
D.Sn=function(b){this.Init(b)};D.D.l(D.Sn,D.tl,"DvtTreemapParser");D.C=D.Sn.prototype;D.C.dn=function(b,c,d){return new D.rn(b,c,d)};D.C.gm=function(b){var c=D.Sn.q.gm.call(this,b),d=b.o("layout");c.Wn="h"==d?new D.Tn(D.n):"v"==d?new D.Tn(D.t):new D.Jn;c.S6=b.o("gg");c.S6||(c.S6="o");c.vma=b.o("irk");this.jxa=c.vma;return c};
D.C.Vu=function(b){var c=D.Sn.q.Vu.call(this,b);c.Lla=b.o("gld");c.DV=b.o("ha");c.yma=b.o("va");c.uma=b.o("hi");c.HEa=b.o("unc");c.fma=b.o("hha");if(b=b.o("hls"))c.GEa=new D.K(b);this.jxa==c.id&&(c.Xl=D.n);return c};D.C.kY=function(b,c,d,e){e.NODE_HOVER_COLOR=c.v("border-color");e.NODE_SELECTED_OUTER_COLOR=d.v("-tr-outer-color");e.NODE_SELECTED_INNER_COLOR=d.v("-tr-inner-color")};
D.C.paa=function(b,c){var d=new D.K(b.o("nodeHeader"));c.HEADER_TEXT_DEFAULT_STYLE=d;c.HEADER_BACKGROUND_STYLE=d;var e=d.clone().Cb(new D.K(b.o("nodeHeader-hover")));c.HEADER_TEXT_HOVER_DEFAULT_STYLE=e;c.HEADER_BACKGROUND_HOVER_STYLE=e;var f=d.clone().Cb(new D.K(b.o("nodeHeader-selected")));c.HEADER_TEXT_SELECTED_DEFAULT_STYLE=f;c.HEADER_BACKGROUND_SELECTED_STYLE=f;d=d.clone().Cb(new D.K(b.o("nodeHeaderDrill")));c.HEADER_DRILL_TEXT_DEFAULT_STYLE=d;c.HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE=d.clone().Cb(new D.K(b.o("nodeHeaderDrill-hover")));
c.HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE=d.clone().Cb(new D.K(b.o("nodeHeaderDrill-selected")));c.HEADER_HOVER_OUTER_COLOR_STYLE=e.v("-tr-outer-color");c.HEADER_HOVER_INNER_COLOR_STYLE=e.v("-tr-inner-color");c.HEADER_SELECTED_OUTER_COLOR_STYLE=f.v("-tr-outer-color");c.HEADER_SELECTED_INNER_COLOR_STYLE=f.v("-tr-inner-color")};
D.rn=function(b,c,d){this.Init(b,c,d);this.Po=c.CV?c.CV:"n";this.xwa=c.Lla?c.Lla:"h";this.NF=c.DV?c.DV:"c";this.A1=c.yma?c.yma:"c";this.Pwa=c.fma?c.fma:"s";this.Wea=c.GEa;this.Z0="on"==c.HEa;this.ixa=c.uma?c.uma:"on";this.Qv=c.Xl};D.D.l(D.rn,D.Pl,"DvtTreemapNode");D.C=D.rn.prototype;
D.C.L=function(b){if(this.Jv){this.H=this.W_();b.k(this.H);var c;this.De()?(this.EQ=new D.Q(this.I.e),this.H.k(this.EQ),this.Gu(this.EQ)):c=this.nM;if(c){var d=this.I.EZ;d.Ko=this.gi;var e=this.S-8-2,f=this.X-4-2;0<e&&0<f&&((0,D.sn)(d,e),(0,D.tn)(d,f),d.Jf((0,D.rm)(this)),this.N_=c=D.I.ED(d,c,this.H),(0,D.Qe)(b.e)?(b=c.C(),b=this.Ta+this.S-4-1-b.g):b=this.Ta+4+1,(0,D.jg)(c,b,this.mb+2+1))}else this.Ya=this.jK(this.H),this.Ya!=D.q&&(this.$o&&"h"!=this.rj)&&(b=this.Ya.Rb(),this.ep=new D.af(this.I.e,
b.x,b.y,b.g,b.j),this.ep.la("#FFFFFF"),this.ep.ia(D.t),this.H.k(this.ep),b=this.Ya,"n"==this.rj&&this.De()?this.I.V0.k(b):this.H.k(b));this.H.If("img");this.Oj()}};
D.C.Ob=function(b){D.rn.q.Ob.call(this,b);if(this.H)if(this.Na()){b=this.Ta;var c=this.mb+1,d=this.S-1,e=this.X-1;(0,D.un)()&&(c-=1);(0,D.vn)(this,this.Tf);(0,D.vn)(this,this.Vt);this.Vt=this.Tf=D.q;this.Tf=new D.af(this.I.e,b,c,d,e);this.Tf.ia(D.t);this.Tf.G(D.q);(0,D.bn)(this.Tf);this.H.k(this.Tf);this.Vt=new D.af(this.I.e,b+1,c+1,d-2,e-2);this.Vt.ia(D.t);this.Vt.G(D.q);(0,D.bn)(this.Vt);this.H.k(this.Vt);"h"==this.rj?(this.SI||this.Gg()?(0,D.wn)(this,this.H,this.cq,"background-color:#C4DCFF;",
"HEADER_BACKGROUND_HOVER_STYLE"):((0,D.wn)(this,this.H,this.cq,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Ya&&(0,D.xn)(this,this.Ya,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B")),this.Tf.La((0,D.jm)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),1),this.Vt.La((0,D.jm)(this,"#FFFFFF","HEADER_SELECTED_INNER_COLOR_STYLE"),1)):(this.Tf.La((0,D.jm)(this,"#000000","NODE_SELECTED_OUTER_COLOR"),1),this.Vt.La((0,D.jm)(this,"#FFFFFF","NODE_SELECTED_INNER_COLOR"),1),!(0,D.yn)()&&
!(0,D.zn)()&&(0,D.Xg)(this.H,D.am),this.I.HP(this.H))}else(0,D.vn)(this,this.Vt),this.Vt=D.q,"h"==this.rj?(this.SI||this.Gg()?(0,D.wn)(this,this.H,this.cq,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"):((0,D.wn)(this,this.H,this.cq,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.Ya&&(this.Vq()?(0,D.xn)(this,this.Ya,"HEADER_TEXT_DEFAULT_STYLE","#003286"):(0,D.xn)(this,this.Ya,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"))),this.Tf&&(this.SI||this.Gg()?this.Tf.La((0,D.jm)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"):((0,D.vn)(this,this.Tf),this.Tf=D.q))):((0,D.An)(this.H),this.Tf&&((0,D.vn)(this,this.Tf),this.Tf=D.q),(b=this.pf)&&b.EQ&&b.EQ.k(this.H))};
D.C.Fc=function(){if(this.H&&this.Jv){var b=(0,D.Bn)(this.I);if(!(b!=D.q&&b!=this&&!this.lD(b))){var b=[],c,d,e,f;"h"==this.rj?((0,D.wn)(this,this.H,this.cq,"background-color:#C4DCFF;","HEADER_BACKGROUND_HOVER_STYLE"),this.Tf||(d=this.Ta,c=this.mb+1,e=this.S-1,f=this.X-1,(0,D.un)()&&(c-=1),this.Tf=new D.af(this.I.e,d,c,e,f),this.Tf.ia(D.t),this.Tf.G(D.q),(0,D.bn)(this.Tf),this.H.k(this.Tf)),this.Na()?this.Tf.La((0,D.jm)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.rn.hpa):this.Tf.La((0,D.jm)(this,
"#00AEFF","HEADER_HOVER_OUTER_COLOR_STYLE"),"1"),d=this.Ta+1.5+1,e=this.Ta+this.S-1.5-1,c=this.mb+this.Ol,f=this.mb+this.X-1.5-1,b.push(e,c,e,f,d,f,d,c),c=new D.ff((0,D.jm)(this,"#C4DCFF","HEADER_HOVER_INNER_COLOR_STYLE"),0.8,3),this.Ya&&(this.Vq()?(0,D.xn)(this,this.Ya,"HEADER_DRILL_TEXT_HOVER_DEFAULT_STYLE","#000000"):(0,D.xn)(this,this.Ya,"HEADER_TEXT_HOVER_DEFAULT_STYLE","#000000"))):(d=this.Ta+1,e=this.Ta+this.S-1,c=this.mb+1,f=this.mb+this.X-1,b.push(this.Ta,c,e,c,e,f,d,f,d,c),c=new D.ff((0,D.jm)(this,
"#FFFFFF","NODE_HOVER_COLOR"),1,2));d=this.I;d.Hy.Pc(b);d.Hy.Z(c);d.Hy.bb(D.n)}}};
D.C.nc=function(){this.H&&this.Jv&&("h"==this.rj&&(this.Na()?((0,D.wn)(this,this.H,this.cq,"background-color:#9CACC9;","HEADER_BACKGROUND_SELECTED_STYLE"),this.Tf.La((0,D.jm)(this,"#000000","HEADER_SELECTED_OUTER_COLOR_STYLE"),D.rn.hpa),this.Ya&&(this.Vq()?(0,D.xn)(this,this.Ya,"HEADER_DRILL_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"):(0,D.xn)(this,this.Ya,"HEADER_TEXT_SELECTED_DEFAULT_STYLE","#003D5B"))):((0,D.wn)(this,this.H,this.cq,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),
this.Tf&&(this.H.removeChild(this.Tf),this.Tf=D.q),this.Ya&&(this.Vq()?(0,D.xn)(this,this.Ya,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"):(0,D.xn)(this,this.Ya,"HEADER_TEXT_DEFAULT_STYLE","#003D5B")))),this.I.Hy.bb(D.t))};D.C.mD=function(){return"on"==this.ixa&&"h"==this.rj};D.C.$C=function(b){return!b||!b.MC()?D.rn.q.$C.call(this,b):new D.H(this.Ta,this.mb,this.S,this.X)};
D.C.Ef=function(b){var c;if(b.type==D.bi)return D.rn.q.Ef.call(this,b);c=b.keyCode;if(32==c&&b.ctrlKey)return this;if(38==c&&b.altKey||221==c)(c=this.pf)&&c.getId()!=this.I.Pa.getId()?(b=c,(0,D.dm)(c)):b=this;else if(40==c&&b.altKey||219==c)b=(b=this.tS)?b:this.De()?(0,D.Cn)(this.I,this.jb()):this;else{var d=(0,D.Bn)(this.I),e=0;if(d)if(this==d)e=0;else{c=this.pf;for(e=1;d!=c;)e++,c=c.pf}else{for(d=this;d.pf;)d=d.pf;e=(0,D.mm)(this)}c=(0,D.em)(this,d,e);b=(0,D.hn)(this,b,c)}(0,D.dm)(b);return b};
D.C.hf=function(){return new D.H(this.Ta,this.mb,this.S,this.X)};D.C.Pm=function(){return this.H?this.H.oa():D.q};
D.C.cO=function(b,c,d,e){if(!(0>=d||0>=e)){this.Jv=D.n;this.rha=this.ml();this.Ta=b;this.mb=c;this.S=d?d:0;this.X=e?e:0;this.rj=this.De()?this.xwa:this.Po;this.tz||(this.rj="o");if("h"==this.rj){this.Ol=15;b=new D.ph(this.I.e,this.tz);b.Jf((0,D.rm)(this));(0,D.xn)(this,b,"HEADER_TEXT_DEFAULT_STYLE","#003D5B");b=D.Kl.Qi(b).j;this.Ol=window.Math.max(this.Ol,b);this.mD()&&(this.Ol=window.Math.max(this.Ol,15));b=this.Ta;c=this.mb+this.Ol;d=this.S;e=this.X-this.Ol;if(0<=d&&0<=e)return new D.H(b,c,d,e);
this.rj=D.q}return new D.H(this.Ta,this.mb,this.S,this.X)}};D.C.contains=function(b,c){return b>=this.Ta&&b<=this.Ta+this.S&&c>=this.mb&&c<=this.mb+this.X};D.C.ml=function(){var b=D.N.sd(this.Ng),c=D.N.rd(this.Ng),d=D.N.qd(this.Ng);return[this.Ta,this.mb,this.S,this.X,b,c,d,this.De()?0:window.Math.random()]};
D.C.Ao=function(b){this.cO(b[0],b[1],b[2],b[3]);this.Ng=D.N.hx(window.Math.round(b[4]),window.Math.round(b[5]),window.Math.round(b[6]));this.H&&((0,D.Dn)(this.H,this.Ta,this.mb,this.S,this.X),this.cq&&(0,D.Dn)(this.cq,this.Ta+1,this.mb+1,this.S-2,this.X-2),("h"!=this.rj||this.Z0)&&this.H.G(this.gE()),this.Na()&&this.Ob(D.t),(0,D.vn)(this,this.Cv),(0,D.vn)(this,this.xM),this.xM=this.Cv=D.q,(0,D.En)(this),this.nM?((0,D.vn)(this,this.N_),this.N_=D.q):((0,D.vn)(this,this.ep),this.ep=D.q,this.Ya&&this.Ya.getParent().removeChild(this.Ya),
this.Ya=this.jK(this.H)))};D.Fn=function(b){if(b.rha){var c=new D.im(b.I.e,b,0.3);(0,D.P)(c.R,"typeNumberArray",b,b.ml,b.Ao,b.ml());b.Ao(b.rha);return c}return D.q};D.rn.prototype.Wf=function(b,c){return 0==(0,D.mm)(this)||c.Jv&&0<c.S&&0<c.X?D.rn.q.Wf.call(this,b,c):this.Ug(b)};
D.rn.prototype.W_=function(){var b=this.I.e,c;if("h"==this.rj)c=new D.af(b,this.Ta,this.mb,this.S,this.X),this.cq=new D.af(b,this.Ta+1,this.mb+1,this.S-2,this.X-2),(0,D.wn)(this,c,this.cq,"background-color:#FFFFFF;border-color:#E1E6EE;","HEADER_BACKGROUND_STYLE"),this.cq.ia(D.t),c.k(this.cq),this.Qv&&(this.me=(0,D.Gn)(this,c));else{var d=this.gE();c=new D.af(b,this.Ta,this.mb,this.S,this.X);if((1E3>this.I.Gl||!(0,D.wf)())&&2<=this.S&&2<=this.X){new D.ff((0,D.jm)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),
0.3);new D.ff((0,D.jm)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),0.3);this.$o&&new D.ff(this.Ng,0.15);var e=this.Hb(),f=(0,D.jm)(this,"#FFFFFF","LEAF_NODE_TOP_BORDER_COLOR_STYLE"),f=D.N.KH(f,e,0.7),g=(0,D.jm)(this,"#000000","LEAF_NODE_BOTTOM_BORDER_COLOR_STYLE"),g=D.N.KH(g,e,0.7),e=window.Math.min(this.S,this.X);4<=e?(c.la(g),this.xM=new D.af(b,this.Ta,this.mb,this.S-1,this.X-1),this.xM.la(f),this.xM.ia(D.t),c.k(this.xM),this.Cv=new D.af(b,this.Ta+1,this.mb+1,this.S-2,this.X-2),this.Cv.G(d),
this.Cv.ia(D.t),c.k(this.Cv)):2<=e?(c.la(g),this.Cv=new D.af(b,this.Ta,this.mb,this.S-1,this.X-1),this.Cv.G(d),this.Cv.ia(D.t),c.k(this.Cv)):c.G(d)}else c.G(d)}this.I.Ua().ja(c,this);this.dc()?c.Jg(D.n):c.setCursor("default");c.zIndex=this.$T;return c};
D.Gn=function(b,c){if("h"!=b.rj||!b.mD())return D.q;var d=D.q,e=b.Ta,f=b.Ta+b.S-1,g=b.mb+1,h=b.mb+b.Ol;if(12<f-e-2){if(b.Qv){var d=b.I.e,j=b.I.rh,m=new D.kf(d,j.restoreUp,0,0,12,12),o=new D.kf(d,j.restoreOver,0,0,12,12),j=new D.kf(d,j.restoreDown,0,0,12,12);(0,D.Yg)(m);(0,D.Yg)(o);(0,D.Yg)(j);d=new D.kh(d,m,o,j);d.W(D.bi,b.Wba,D.t,b)}else d=b.I.e,j=b.I.rh,m=new D.kf(d,j.maximizeUp,0,0,12,12),o=new D.kf(d,j.maximizeOver,0,0,12,12),j=new D.kf(d,j.maximizeDown,0,0,12,12),(0,D.Yg)(m),(0,D.Yg)(o),(0,D.Yg)(j),
d=new D.kh(d,m,o,j),d.W(D.bi,b.Vba,D.t,b);e=(0,D.Qe)(c.e)?e+1:f-12-1;(0,D.jg)(d,e,(h+g-12)/2);c.k(d);(0,D.wf)()&&(g=new D.af(c.e,-2,-2,16,16),(0,D.Yg)(g),d.k(g));"true"==b.I.rh.alta?b.I.Ua().ja(d,b):(g=b.Qv?b.I.rh.restore:b.I.rh.isolate,b.I.Ua().ja(d,new D.Ml(b,b.getId(),g)))}return d};D.En=function(b){b.me&&((0,D.vn)(b,b.me),b.me=D.q)};
D.rn.prototype.jK=function(b){var c=(0,D.Qe)(b.e);if(!this.tz||!b||!this.rj||"o"==this.rj)return D.q;var d=this.X;if((0,D.rm)(this)>d)return D.q;var e="n"==this.rj?this.NF:this.Pwa;c&&("s"==e?e="e":"e"==e&&(e="s"));var f=this.S-6,g=0;this.mD()&&(g=13,f="c"==e?f-2*g:f-g);if(0>=f)return D.q;var h=new D.ph(this.I.e,this.tz);h.Jf((0,D.rm)(this));"s"==e?(c?h.da(this.Ta+4+g):h.da(this.Ta+4),h.Tk()):"c"==e?(h.da(this.Ta+this.S/2),h.Re()):"e"==e&&(c?h.da(this.Ta+this.S-4):h.da(this.Ta+this.S-4-g),h.ni());
"n"==this.rj?(d=this.X-4,"t"==this.A1?(h.ta(this.mb+2),h.lp()):"c"==this.A1?(h.ta(this.mb+this.X/2),h.Ae()):"b"==this.A1&&(h.ta(this.mb+this.X-2),h.ww()),(0,D.qm)(this,h)):"h"==this.rj&&(c=(0,D.un)()?1:0,h.ta(this.mb+1+this.Ol/2+c),h.Ae(),(0,D.xn)(this,h,"HEADER_TEXT_DEFAULT_STYLE","#003D5B"));if(h!=D.q)return"h"==this.rj&&this.Vq()?((0,D.xn)(this,h,"HEADER_DRILL_TEXT_DEFAULT_STYLE","#003286"),h.setCursor("pointer"),c=new D.Ml(this,this.getId(),D.q,this.gf(),this.zj()),c.q8(D.n),this.I.Ua().ja(h,
c)):h.ia(D.t),D.Kl.Ub(h,f,d,b)?h:D.q};D.wn=function(b,c,d,e,f){var g=new D.K(e);g.Cb(b.I.Jn[f]);e=g.v("background-color");g=g.v("border-color");b.Z0&&"HEADER_BACKGROUND_STYLE"==f?(b=b.Hb(),d.la(b),g=D.N.KH(g,b,0.5),c.la(g)):(c.la(g),d.la(e))};D.xn=function(b,c,d,e){var f=b.Z0&&"HEADER_TEXT_DEFAULT_STYLE"==d;f?c.la((0,D.om)(b)):c.la(e);e=[];1>=(0,D.mm)(b)&&b.De()&&e.push(new D.K("font-weight:bold;"));e.push(b.I.Jn[d]);b.Wea&&e.push(b.Wea);c.Ha((0,D.Gl)(e));D.pm===D.n&&f&&c.la((0,D.om)(b))};
D.rn.prototype.Rw=function(){this.me||(this.me=(0,D.Gn)(this,this.H));D.rn.q.Rw.call(this)};D.rn.prototype.Sq=function(){this.Qv!==D.n&&(0,D.En)(this);D.rn.q.Sq.call(this)};D.vn=function(b,c){c&&b.H.removeChild(c)};D.C=D.rn.prototype;D.C.Vba=function(){this.Qv=D.n;this.nc();var b=this.I,c=b.Ua().Be();c&&c.Mc();b.ad.push(this);b.Xa(new D.Hn(this.getId()));b.kS=D.n;b.uo(new D.H(0,0,b.ub,b.Lb));b.kS=D.t;c=this.Da();b.t1.k(c);(0,D.In)(b,this);(0,D.En)(this);this.Oj()};
D.C.Wba=function(){this.Qv=D.t;this.nc();var b=this.I,c=b.ad.pop(),d=b.Ua().Be();d&&d.Mc();d=c.getId();b.sL=d;b.Xa(new D.Hn);b.kS=D.n;b.uo(new D.H(0,0,b.ub,b.Lb));b.kS=D.t;(0,D.In)(b,c);(0,D.En)(this);this.Oj()};D.C.gf=function(b,c,d){return b&&b instanceof D.kh?D.q:D.rn.q.gf.call(this,b,c,d)};D.C.zj=function(b){return b&&b instanceof D.kh?D.q:D.rn.q.zj.call(this,b)};D.C.ne=function(b){return b&&b instanceof D.kh?this.Qv?this.I.rh.restore:this.I.rh.isolate:D.q};
D.C.ee=function(){var b=[];this.dc()&&b.push((0,D.wg)(this.ed,this.Na()?"STATE_SELECTED":"STATE_UNSELECTED"));this.Qv&&b.push((0,D.wg)(this.ed,"STATE_ISOLATED"));return(0,D.en)(this.zy,b,this.ed)};D.C.Oj=function(){!(0,D.fn)()&&this.H&&(0,D.gn)(this.H,"label",this.ee())};
D.Kn=function(){this.Init()};D.D.l(D.Kn,D.D,"DvtBaseTreemapLayout");D.Kn.prototype.Init=function(){this.$T=0};D.Kn.prototype.Wn=(0,D.w)();D.Ln=function(b,c,d,e,f,g,h){c.$T=b.$T;b.$T++;if(!h||!c.De()){b=b.X5(c.I,(0,D.mm)(c));h=window.Math.round(d+b);var j=window.Math.round(e+b);if(c=c.cO(h,j,window.Math.round(d+f-b)-h,window.Math.round(e+g-b)-j))return c}return new D.H(d,e,f,g)};D.Kn.prototype.X5=function(b,c){var d=b.wwa;return"o"==d?1==c&&2<=b.iq?3:0:"a"==d?c<b.iq?3:0:0};
D.Jn=function(){this.Init()};D.D.l(D.Jn,D.Kn,"DvtSquarifyingLayout");D.Jn.prototype.Wn=function(b,c,d,e,f,g,h){this.Qf(c,d,e,f,g,h?D.t:D.n)};D.Jn.prototype.Qf=function(b,c,d,e,f,g){c=(0,D.Ln)(this,b,c,d,e,f,g);b=b.jb();if(b!=D.q&&0<b.length){d=b;f=c.g*c.j;for(e=e=g=0;e<d.length;e++)g+=0<d[e].sc()?d[e].sc():0;f=0==f?0:f/g;for(e=0;e<d.length;e++)g=d[e],g.LA=g.sc()*f;b=b.slice(0).sort(function(b,c){return b.sc()-c.sc()});d=window.Math.min(c.g,c.j);(0,D.Mn)(this,b,d,new D.H(c.x,c.y,c.g,c.j))}};
D.Mn=function(b,c,d,e){var f=[],g=window.Infinity;if(c==D.q||0==c.length)(0,D.Nn)(b,f,d,e);else for(;0<c.length;){var h=c.pop();if(0>h.LA){(0,D.Nn)(b,f,d,e);break}f.push(h);var j,m=f,o=d,p=0;j=window.Infinity;for(var r=-window.Infinity,u=0;u<m.length;u++)p+=m[u].LA,j=window.Math.min(j,m[u].LA),r=window.Math.max(r,m[u].LA);m=p*p;o*=o;j=window.Math.max(o*r/m,m/(o*j));if(j>g){c.push(h);f.pop();e=(0,D.Nn)(b,f,d,e);(0,D.Mn)(b,c,window.Math.min(e.g,e.j),e);break}else if(0==c.length){(0,D.Nn)(b,f,d,e);break}else g=
j}};D.Nn=function(b,c,d,e){var f=0,g;for(g=0;g<c.length;g++)f+=c[g].LA;var h=e.x,j=e.y;if(d==e.g){f=0==d?0:f/d;for(g=0;g<c.length;g++)d=c[g].LA/f,b.Qf(c[g],h,j,d,f,D.t),h+=d;return new D.H(e.x,e.y+f,e.g,e.j-f)}d=0==d?0:f/d;for(g=0;g<c.length;g++)f=c[g].LA/d,b.Qf(c[g],h,j,d,f,D.t),j+=f;return new D.H(e.x+d,e.y,e.g-d,e.j)};
D.Tn=function(b){this.Init();this.Dt=b};D.D.l(D.Tn,D.Kn,"DvtSliceAndDiceLayout");D.Tn.prototype.Wn=function(b,c,d,e,f,g,h){this.Qf(this.Dt,b,c,d,e,f,g,h?D.t:D.n)};
D.Tn.prototype.Qf=function(b,c,d,e,f,g,h,j){e=(0,D.Ln)(this,d,e,f,g,h,j);d=d.jb();if(d!=D.q){f=e.x;g=e.y;h=e.g;j=e.j;var m=0,o;for(o=0;o<d.length;o++)m+=0<d[o].sc()?d[o].sc():0;"on"==this.tP&&(d=d.slice(0),d.sort(function(b,c){return c.sc()-b.sc()}));b&&(0,D.Qe)(c.e)&&(d=d.slice(0).reverse());for(o=0;o<d.length;o++){var p=d[o];if(!(0>=p.sc())){var r=p.sc()/m;b?h=e.g*r:j=e.j*r;this.Qf(!b,c,p,f,g,h,j,D.t);b?f+=h:g+=j}}}};
D.Hn=function(b){this.Init("treemapIsolate");this.Oa=b?b:D.q};(0,D.qa)("DvtTreemapIsolateEvent",D.Hn);D.D.l(D.Hn,D.pf,"DvtTreemapIsolateEvent");D.Hn.TYPE="treemapIsolate";D.Hn.prototype.getId=(0,D.B)("Oa");D.Hn.prototype.getId=D.Hn.prototype.getId;
D.Un=function(b){this.Init(b)};D.D.l(D.Un,D.Yl,"DvtTreemapKeyboardHandler");D.Un.prototype.Si=function(b){var c=D.Un.q.Si.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.n;return c};
D.Qn=function(b,c,d,e){D.sm.call(this,b,c,d,e)};D.D.l(D.Qn,D.sm,"DvtTreemapEventManager");D.Qn.prototype.hm=function(b){var c=D.n;if(13==b.keyCode&&b.ctrlKey){var d=this.Be();d.mD()&&(d.Qv?d.Wba():d.Vba());b.preventDefault()}else c=D.Qn.q.hm.call(this,b);return c};D.Qn.prototype.d7=(0,D.ca)(D.t);
D.On=(0,D.w)();D.D.l(D.On,D.Pn,"DvtTreemapBundle");D.On._defaults={COLOR:"Color",SIZE:"Size"};D.On.prototype.no=function(b){var c=D.On.q.no.call(this,b);return c?c:D.On._defaults[b]};D.On.prototype.xx=(0,D.ca)("DvtTreemapBundle");
D.qn=function(){this.Init({skyros:D.pn,alta:{}})};D.D.l(D.qn,D.Cl,"DvtTreemapDefaults");D.pn={nodeDefaults:{header:{labelStyle:new D.K("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;")}}};
D.Rn=(0,D.ba)("e");D.D.l(D.Rn,D.Wl,"DvtTreemapJsonUtils");D.C=D.Rn.prototype;D.C.KO=(0,D.ca)("treemap");D.C.kJ=function(b){var c=D.Rn.q.kJ.call(this,b),c=c+this.Ea("irk",b.isolatedNode),d=b.groupGaps;"all"==d?c+=this.Ea("gg","a"):"none"==d&&(c+=this.Ea("gg","n"));d=b.layout;"sliceAndDiceHorizontal"==d?c+=this.Ea("layout","h"):"sliceAndDiceVertical"==d&&(c+=this.Ea("layout","v"));b=b.animationOnDisplay;return c="auto"==b?c+this.Ea("adi","alphaFade"):c+this.Ea("adi",b)};
D.C.lJ=function(b,c){var d=D.Rn.q.lJ.call(this,b,c);if("off"==(c.labelDisplay?c.labelDisplay:b.nodeDefaults.labelDisplay))d+=this.Ea("ld","o");var e=c.groupLabelDisplay?c.groupLabelDisplay:b.nodeDefaults.groupLabelDisplay;"node"==e?d+=this.Ea("gld","n"):"off"==e&&(d+=this.Ea("gld","o"));e=c.labelHalign?c.labelHalign:b.nodeDefaults.labelHalign;"start"==e?d+=this.Ea("ha","s"):"end"==e&&(d+=this.Ea("ha","e"));e=c.labelValign?c.labelValign:b.nodeDefaults.labelValign;"top"==e?d+=this.Ea("va","t"):"bottom"==
e&&(d+=this.Ea("va","b"));var e=c.header,d=d+this.Ea("hls",e&&e.labelStyle?e.labelStyle:b.nodeDefaults.header.labelStyle),f=e&&e.labelHalign?e.labelHalign:b.nodeDefaults.header.labelHalign;"center"==f?d+=this.Ea("hha","c"):"end"==f&&(d+=this.Ea("hha","e"));if("off"==(e&&e.isolate?e.isolate:b.nodeDefaults.header.isolate))d+=this.Ea("hi","off");if("on"==(e&&e.useNodeColor?e.useNodeColor:b.nodeDefaults.header.useNodeColor))d+=this.Ea("unc","on");return d};
D.C.eZ=function(b){var c,d=new D.On;c="\x3cresources"+this.Ea("legendSize",(0,D.wg)(d,"SIZE"));c+=this.Ea("legendColor",(0,D.wg)(d,"COLOR"));b=b._resources;d=(0,D.Qe)(this.e);c+=this.Ea("maximizeUp",d&&b.isolateRtl?b.isolateRtl:b.isolate);c+=this.Ea("maximizeDown",d&&b.isolateDownRtl?b.isolateDownRtl:b.isolateDown);c+=this.Ea("maximizeOver",d&&b.isolateOverRtl?b.isolateOverRtl:b.isolateOver);c+=this.Ea("restoreUp",d&&b.restoreRtl?b.restoreRtl:b.restore);c+=this.Ea("restoreDown",d&&b.restoreDownRtl?
b.restoreDownRtl:b.restoreDown);c+=this.Ea("restoreOver",d&&b.restoreOverRtl?b.restoreOverRtl:b.restoreOver);c+=this.Ea("alta","true");return c+"/\x3e\n"};
D.C.mJ=function(b){var c=D.Rn.q.mJ.call(this,b),d=b.animationUpdateColor;d&&(c+=this.Ea("top","-tr-animation-update-color: "+d));(d=b.nodeDefaults.hoverColor)&&(c+=this.Ea("node-hover","border-color: "+d));var d=b.nodeDefaults.selectedInnerColor,e=b.nodeDefaults.selectedOuterColor;(d=(d?"-tr-inner-color:"+d+";":"")+(e?"-tr-outer-color:"+e:""))&&(c+=this.Ea("node-selected",d));d=b.nodeDefaults.header.backgroundColor;e=b.nodeDefaults.header.borderColor;(d=(d?"background-color:"+d+";":"")+(e?"border-color:"+
e:""))&&(c+=this.Ea("nodeHeader",d));var e=b.nodeDefaults.header.hoverBackgroundColor,f=b.nodeDefaults.header.hoverInnerColor,d=b.nodeDefaults.header.hoverOuterColor,e=(e?"background-color:"+e+";":"")+(f?"-tr-inner-color:"+f+";":"");(e+=d?"-tr-outer-color:"+d:"")&&(c+=this.Ea("nodeHeader-hover",e));d=b.nodeDefaults.header.selectedBackgroundColor;e=b.nodeDefaults.header.selectedInnerColor;b=b.nodeDefaults.header.selectedOuterColor;d=(d?"background-color:"+d+";":"")+(e?"-tr-inner-color:"+e+";":"");
(d+=b?"-tr-outer-color:"+b:"")&&(c+=this.Ea("nodeHeader-selected",d));return c+"/\x3e\n"};
});