define(['./DvtToolkit', './DvtPanZoomCanvas', './DvtSubcomponent'], function() {
  // Internal use only.  All APIs and functionality are subject to change at any time.
    // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  D.PP=function(b,c,d){this.Init(b,c,d)};(0,D.qa)("DvtAmxThematicMap",D.PP);D.D.l(D.PP,D.Q,"DvtAmxThematicMap");D.PP.Qx=10;D.PP.prototype.Init=function(b,c,d){D.PP.q.Init.call(this,b);this.P=new D.sD(b,c,d);this.QT=new D.Q(b);this.QT.k(this.P);this.k(this.QT);this.lf=new D.UD};D.PP.newInstance=function(b,c,d){return new D.PP(b,c,d)};D.PP.newInstance=D.PP.newInstance;D.PP.prototype.L=function(b,c,d){this.N=this.lf.Vg(b);this.S=c;this.X=d;c=new D.H(0,0,c,d);this.TL(this,c);this.P.L(b,c.g,c.j)};
D.PP.prototype.render=D.PP.prototype.L;
D.PP.prototype.TL=function(b,c){this.Ba&&(b.removeChild(this.Ba),this.Ba=D.q);var d=new D.H(D.PP.Qx,D.PP.Qx,c.g-2*D.PP.Qx,c.j-2*D.PP.Qx),e=this.N,f=e.legend.rendered,g=e.legend.scrolling,h=D.nl.clone(e.legend);this.CZ(this.N,h);if(f&&!(h.wGa&&0==h.wGa.length)){f=e.legend.position;delete h.position;h.layout.gapRatio=this.Fz();h.hideAndShowBehavior="none";h.rolloverBehavior="none";h.scrolling=e.legend.scrolling;var j=(0,D.yy)(this.P.e,D.q,D.q);this.P.getId()!=D.q&&j.setId(this.P.getId()+"legend");b.k(j);
"auto"==f&&"asNeeded"!==g?f="bottom":"auto"==f&&"asNeeded"==g&&(f="end");g=(0,D.Qe)(b.e);"start"==f?f=g?"right":"left":"end"==f&&(f=g?"left":"right");h.orientation="left"==f||"right"==f?"vertical":"horizontal";g="top"==f||"bottom"==f;g=j.Nw(h,g?d.g:e.layout.legendMaxSize*d.g,g?e.layout.legendMaxSize*d.j:d.j);if(0<g.g&&0<g.j)switch(j.L(h,g.g,g.j),this.Ba=j,e=window.Math.ceil(e.layout.legendGap*this.Fz()),(0,D.$B)(d,f,j,g.g,g.j,e),f){case "top":this.QT.O(g.j+D.PP.Qx);case "bottom":c.j-=g.j+D.PP.Qx;
break;case "left":this.QT.F(g.g+D.PP.Qx);case "right":c.g-=g.g+D.PP.Qx}}};D.PP.prototype.Fz=function(){if(this.N.layout.gapRatio!==D.q&&!(0,window.isNaN)(this.N.layout.gapRatio))return this.N.layout.gapRatio;var b=window.Math.min(this.S/400,1),c=window.Math.min(this.X/300,1);return window.Math.min(b,c)};
D.PP.prototype.CZ=function(b,c){c.title=b.legend?b.legend.title:D.q;c.sections=[];if(b&&b.legend&&b.legend.sections)for(var d=0;d<b.legend.sections.length;d++){var e=b.legend.sections[d];e&&c.sections.push({title:e.title,items:e.items,sections:e.sections})}return c};
D.sD=function(b,c,d){this.Init(b,c,d)};(0,D.qa)("DvtThematicMap",D.sD);D.D.l(D.sD,D.wr,"DvtThematicMap");
D.sD.prototype.Init=function(b,c,d){D.sD.q.Init.call(this,b,c,d);(0,D.EP)(this);this.Le=[];this.zv=[];this.xxa=this.Ro=this.jc=this.Ba=D.q;this.$P=D.t;this.hF=[];this.GF={};this.hT=D.t;this.oR={};this.E_={};this.vm=[];this.MZ=new D.Q(this.e);this.lK=new D.Q(this.e);this.vv=new D.Q(this.e);this.Ft=new D.Q(this.e);this.WR=D.t;this.rC=this.yz=D.n;this.Z1=6;this.Tr=D.n;this.AG={};this.Bl=16777215;this.lf=new D.UD;this.Mf=D.t};D.sD.newInstance=function(b,c,d){return new D.sD(b,c,d)};
D.sD.prototype.be=function(b){D.sD.q.be.call(this,b);(0,D.Gg)()||(this.N.animationOnDisplay="none",this.N.animationOnMapChange="none",this.N.animationOnDrill="none");this.N.skin||(this.N.skin="alta");(new D.tD(this)).parse(this.N)};D.kE=function(b,c){for(var d=0;d<b.Le.length;d++)if(b.Le[d].Lf==c)return b.Le[d]};D.C=D.sD.prototype;D.C.ao=function(b){this.at=(0,window.parseFloat)(b)};D.C.Qa=(0,D.B)("at");
D.C.mW=function(b){b=(0,window.parseInt)(b);var c=this.Bl;if(1==b||3==b||5==b||7==b)c&=-17,this.rC=D.t;if(2==b||3==b||6==b||7==b)c&=-4098,this.yz=D.t;if(4==b||5==b||6==b||7==b)c&=-257;this.Bl=c};D.C.jW=function(b){this.Ik=b;this.Aa.jW(b)};
D.C.eJ=function(){D.sD.q.eJ.call(this);!this.Ly&&this.Fya&&(this.Le=[],this.hF=[],this.GF={},this.oR={},this.E_={},this.vm=[],this.removeChild(this.jc),this.xxa=this.Ro=this.Ba=this.jc=D.q,this.Bl=16777215,this.rC=this.yz=D.n,this.cG=this.Mb,this.MZ=new D.Q(this.e),this.lK=new D.Q(this.e),this.vv=new D.Q(this.e),this.Ft=new D.Q(this.e),(0,D.EP)(this),this.Aa.tc())};D.EP=function(b){b.Aa=new D.dE(b.e,b.Xa,b);b.Aa.rf(b);(0,D.wf)()?b.v1=D.q:(b.v1=new D.nD(b,b.Aa),(0,D.yr)(b.Aa,b.v1))};
D.sD.prototype.vpa=function(b){(0,D.Qe)(this.e)||(b=this.S-5-b.getWidth(),this.jc.F(b))};
D.sD.prototype.TL=function(){if(this.Ro){this.jc&&(this.jc.U(),this.removeChild(this.jc));var b="true"==this.Ro.o("disclosed"),c="fixed"==this.Ro.o("display")||(0,D.wh)();if(!c||b){var d=this.Ro.o("maxWidth"),e=d.indexOf("%"),d=-1!=e?(0,window.parseFloat)(d.substring(0,e))/100*this.S:(0,window.parseFloat)(d),e=this.X-10;if("alta"==this.Gb)this.jc=new D.Yr(this.e,D.q,this,"pd"),this.jc.W("dvtPanelDrawerEvent",this.n$,D.t,this),this.jc.cm(d),this.jc.ND(e),this.jc.Pv=c,(0,D.Qe)(this.e)?(this.jc.Kr="right",
this.jc.F(0)):this.jc.F(this.S);else{this.jc=new D.Jt(this.e,d,e,f,(0,D.lh)(this),this.ts(),b,c);this.jc.W("dvtCollapsiblePanelEvent",this.n$,D.t,this);this.jc.W("dvtResizeEvent",this.vpa,D.t,this);var d=this.Ro.o("expandTooltip"),e=this.Ro.o("collapseTooltip"),f=(0,D.Qe)(this.e)?"col_northwest":"col_northeast",f=this.jc;f.wB=d;f.iB=e}this.Ba=new D.DvtCommonLegend(this.e,this.jc.m6(),this.jc.l6(),(0,D.lh)(this),this.Gb);this.Ba.uW(this.Ro);this.k(this.jc);this.k(this.Ba);this.Ba.L();var g;if("alta"==
this.Gb){f=this.Ba.C();(0,D.$r)(this.jc,f.j);this.removeChild(this.Ba);var f=new D.kf(this.e,(0,D.lh)(this).legendEna,0,0,24,24),d=new D.kf(this.e,(0,D.lh)(this).legendOvr,0,0,24,24),e=new D.kf(this.e,(0,D.lh)(this).legendDwn,0,0,24,24),h=(0,D.wg)(this.Kc(),"LEGEND");(0,D.as)(this.jc,this.Ba,f,d,e,h,"legend");this.jc.Xm();b&&this.jc.Je(D.n,D.n)}else g=this.jc,b=this.Ba,g.Wc.k(b),b.W("dvtResizeEvent",g.HX,D.t,g),f=g.Wc.C(),b=f.g+10,f=f.j+10,g.X=f,g.S=b,g.Za?(g.Za.kk((0,D.bH)(g,b,f)),b="col_northwest"==
g.Di||"col_southwest"==g.Di,g.pg&&b&&g.pg.F(g.S)):(b=new D.ef(g.e,(0,D.bH)(g,b,f)),f=g.D.borderAlpha,b.la(g.nv,g.Qj),b.La(g.Pp,f),g.Za=b,g.Ia(g.Za,0),g.Pv||(g.pg=D.tv.f5(g.e,25,g.D,D.t),g.pg.B(g.D.borderAlpha),g.k(g.pg),g.Sj=g.isCollapsed()?D.R.rU(g.e,g.yl,25,g.D,D.t):D.R.pU(g.e,g.yl,25,g.D,D.t),g.pg.k(g.Sj),"col_northwest"==g.Di||"col_southwest"==g.Di||(g.pg.O(25),g.pg.Zi(-window.Math.PI)),(0,D.Qe)(g.e)&&g.pg.F(g.S),(0,D.wf)()?g.Sj.W(D.xz.we,g.pE,D.t,g):(g.Sj.W(D.bi,g.pE,D.t,g),g.Sj.W(D.Mh,g.gY,
D.t,g),g.Sj.W(D.Nh,g.fY,D.t,g)))),g.GQ&&(0,D.cH)(g,D.t),g=this.jc.C(),b=(0,D.Qe)(this.e)?5:this.S-5-g.g-g.x,(0,D.jg)(this.jc,b,5),g.g+=5;if(this.dS=c)g||(g=this.jc.C()),this.bL=g.g}}};
D.sD.prototype.xi=function(){D.sD.q.xi.call(this);var b=new D.Q(this.e),c=new D.Q(this.e);this.Mb=this.ba;this.Mb.k(b);this.Mb.Y.k(c);this.Nh(b,c);if(this.sj){(this.Cc=this.Mb.Cc)&&this.Mb.k(this.Cc);(0,D.FP)(this);var d=new D.H(0,0,this.S,this.X);if(!this.Mf&&!this.cG)D.ap.isSupported(this.KZ)&&(this.pb=D.ap.vH(this.e,this.KZ,this.Mb,d,this.at));else{var e=D.q;if(this.$P&&!this.Ly)e=this.eca;else if(this.sj&&this.sj.Lf!=this.cya&&(e=this.sj.Gq(),!e)){var f=this.sj.fh,g;for(g in f)if(f[g].Gq()){e=
f[g].Gq();break}}e&&D.ap.isSupported(e)?(this.pb=D.ap.Dz(this.e,e,this.cG,this.Mb,d,this.at))&&this.k(this.cG):(this.Mb.Y.removeChild(this.ZE),this.vo())}this.pb&&(this.Cc&&this.k(this.Cc),this.Aa.tc(),this.Aa.zs(this),this.pb.xd(this.vo,this),this.pb.play(D.n));this.Fya=b;this.ZE=c;this.sj&&(this.cya=this.sj.Lf);this.Mf=D.n}};
D.sD.prototype.Nh=function(b,c){this.TL();c.k(this.MZ);c.k(this.lK);this.Tr?b.k(this.vv):c.k(this.vv);b.k(this.Ft);var d=this.Mb.Y.ma();this.x4=D.t;for(var e=0;e<this.Le.length;e++){var f=this.Le[e];if(!this.x4&&f instanceof D.UC||!(f instanceof D.UC))f.L(d),!this.x4&&f instanceof D.UC&&(this.x4=D.n,this.sj=f)}this.sj&&(d=(0,D.qD)(this),0==d.length&&(d=(0,D.oD)(this)),this.v1&&(d=d[0])&&D.dE.q.Cs.call(this.Aa,d),this.Mb.Es(D.q),this.Mb.Ju(D.q),this.Mb.zr=D.n,this.Mb.ci=D.n,!this.$P&&!this.Ly&&this.kfa!=
D.q?((0,D.qs)(this.Mb,this.kfa),(0,D.Sf)(this.Mb,this.$wa,this.axa)):this.Mb.io(D.q,this.sj.WC()),(0,D.GP)(this),d=this.Mb.kp,e=this.sj.WC(),f=this.Mb.sc(),f.g=this.dS?f.g-this.bL:f.g,d=window.Math.min((f.g-2*d)/e.g,(f.j-2*d)/e.j),this.Mb.Es(d),this.Mb.Ju(d*(this.yz?this.Z1:1)),this.Mb.zr=this.yz,this.Mb.ci=this.rC)};D.cE=function(b){b.sj.LF&&b.Mb.io(D.q,b.sj.WC());(0,D.GP)(b);b.WR&&(0,D.HP)(b)};D.sD.prototype.v8=(0,D.ba)("wG");D.sD.prototype.vA=function(){return new D.gE(this)};
D.IP=function(b,c){var d=new D.rh;d.translate(c.Bb,c.yb);b.Tr&&b.vv.ra(d);b.Ft.ra(d)};D.sD.prototype.n$=function(b){var c=new D.Lf;(0,D.Mf)(c,D.DvtCommonLegend.V$,"show"==b.Pi());this.Xa(c)};D.JP=function(b,c,d){if(c=c.R){var e=b.Mb.Y,f=(0,D.zg)(c,e,e.ma);d&&(b.wda=e.ma(),(0,D.P)(c,"typeMatrix",b,b.Qva,b.Hza,f));d=new D.rh(1,0,0,1,f.Bb,f.yb);b.Tr&&(0,D.P)(c,"typeMatrix",b.vv,b.vv.ma,b.vv.ra,d);(0,D.P)(c,"typeMatrix",b.Ft,b.Ft.ma,b.Ft.ra,d)}};
D.sD.prototype.ng=function(b){switch(b.Pi()){case "adjustPanConstraints":if(this.rC){var c=b.Xy;b=this.Mb.kp;var d=this.Mb.sc();b=new D.H(b,b,d.g-2*b,d.j-2*b);var e=this.sj.WC(),f=e.x*c,d=e.y*c,g=e.g*c,c=e.j*c;g>b.g?(this.Mb.lq=b.x+b.g-(f+g),this.Mb.jq=b.x-f):(e=0,this.dS&&((0,D.Qe)(this.e)?e=this.s1?2*-this.bL:-this.bL:this.s1||(e=this.bL)),f=(b.x+b.g-e)/2-(f+g/2),this.Mb.lq=f,this.Mb.jq=f);c>b.j?(this.Mb.mq=b.y+b.j-(d+c),this.Mb.kq=b.y-d):(b=(b.y+b.j)/2-(d+c/2),this.Mb.mq=b,this.Mb.kq=b)}break;
case "zooming":case "elasticAnimBegin":(0,D.JP)(this,b,D.n);break;case "zoomed":if(b.Xy!=D.q){d=this.Mb.Y.ma();(0,D.Mf)(b,"panX",d.Bb);(0,D.Mf)(b,"panY",d.yb);b.R=D.q;this.Xa(b);(0,D.IP)(this,d);for(c=0;c<this.Le.length;c++)this.Le[c].ng(b,d)}break;case "zoomAndCenter":(0,D.fE)(this);break;case "zoomToFitBegin":this.s1=D.n;this.dS&&this.Mb.Xh(this.S-this.bL,this.X,D.n);break;case "zoomToFitEnd":this.s1=D.t,this.dS&&this.Mb.Xh(this.S,this.X,D.n),this.Xa(new D.ly)}};
D.sD.prototype.Ps=function(b){var c=b.Pi();if("elasticAnimBegin"==c)(0,D.JP)(this,b,D.t);else if("panned"==c&&b.Pga!=D.q){var d=this.Mb.Y.ma();(0,D.Mf)(b,"zoom",this.Mb.zc());(0,D.Mf)(b,"panX",d.Bb);(0,D.Mf)(b,"panY",d.yb);b.R=D.q;this.Xa(b);(0,D.IP)(this,d);for(b=0;b<this.Le.length;b++)this.Le[b].Ps(d)}this.jc&&("alta"==this.Gb?"dragPanBegin"===c?this.jc.ia(D.t):"dragPanEnd"===c&&this.jc.ia(D.n):(d=this.ts(),b=this.jc.Za.mc().clone(),"dragPanBegin"===c?(this.Ba.B(d.backgroundDragAlpha),b.B(d.borderDragAlpha),
this.jc.Za.Z(b),this.jc.pg&&this.jc.pg.B(d.borderDragAlpha),this.jc.ia(D.t)):"dragPanEnd"===c&&(this.Ba.B(1),b.B(d.borderAlpha),this.jc.Za.Z(b),this.jc.pg&&this.jc.pg.B(d.borderAlpha),this.jc.ia(D.n))))};D.sD.prototype.yx=function(){return"none"==this.Ik&&!this.yz&&(!this.rC||"alta"==this.Gb)?"hidden":D.sD.q.yx.call(this)};D.sD.prototype.LO=function(){var b=this.yx();return"hidden"!=b?new D.YD(this.e,this,"initCollapsed"==b?1:2):D.q};
D.GP=function(b){b.hT=D.n;for(var c=0;c<b.Le.length;c++){var d=b.Le[c].Lf;d in b.GF&&(b.AG[d]=b.GF[d][1],b.Rj=d,b.rv=b.GF[d][0],b.wU())}b.hT=D.t};
D.sD.prototype.d8=function(){(0,D.FP)(this);for(var b=[],c=[],d=this.Le.length-1;-1<d;d--)this.Le[d].Lf==this.sj.Lf?this.Le[d].reset(c):this.Le[d].reset(b);for(d=0;d<b.length;d++)if(b[d]){var e=b[d].getParent();e&&e.removeChild(b[d])}for(d=0;d<c.length;d++)c[d]&&c[d].B(1);this.hF=[];b=new D.Ef(this.e,0.3);this.Mb.io(b);b.play();this.vm=[];this.Cc&&"none"!=this.Ik&&((0,D.ZD)(this.Cc,D.t),(0,D.$D)(this.Cc,D.t))};
D.HP=function(b){var c=b.lK.C(),d=b.vv.C();if(b.Tr){var e=b.Mb.Y.ma();d.g/=e.Qc;d.j/=e.Ke;d.x/=e.Qc;d.y/=e.Ke}c=(0,D.$h)(c,d);(0,D.FP)(b);(0,D.Gg)()&&(b.pb=new D.Ef(b.e,0.3));0<c.g&&0<c.j?b.Mb.io(b.pb,c):b.Mb.io(b.pb,b.sj.WC());b.pb&&b.pb.play()};D.sD.prototype.bH=function(b){var c=new D.Ef(this.e,0.3);this.Mb.io(c,b);c.play()};
D.fE=function(b){if(b.rv){var c=(0,D.kE)(b,b.Rj).yj(b.rv);if(c&&(c=c.Nb)){for(var c=c.getSelection(),d=0;d<c.length;d++)c[d]=c[d].Da();if(0<c.length){for(var e=c[0].C(),d=1;d<c.length;d++)e=(0,D.$h)(e,c[d].C());b.bH(e)}}}};D.KP=function(b,c){var d=D.iD.oDa(b.Me,c);return(0,D.kE)(b,d)};D.mD=function(b,c){var d=D.iD.Lka(b.Me,c);return(0,D.kE)(b,d)};D.qD=function(b){var c=[];if(b.sj)for(var d=0;d<b.Le.length;d++){var e=b.Le[d].fh,f;for(f in e)c=b.sj.Lf==b.Le[d].Lf?c.concat((0,D.ID)(e[f])):c.concat((0,D.JD)(e[f]))}return c};
D.oD=function(b){var c=[];if(b.sj)for(var d=0;d<b.Le.length;d++){var e=b.Le[d].fh;if(b.sj.Lf==b.Le[d].Lf||!(b.Le[d]instanceof D.UC))for(var f in e)c=c.concat(e[f].Ih)}return c};D.sD.prototype.Hza=function(b){this.wda=b;if(this.Tr){for(var c=(0,D.oD)(this),d=0;d<c.length;d++)c[d].ng(b);c=this.Ft.Ca();for(d=0;d<c;d++)for(var e=this.Ft.ca(d),f=e.Ca(),g=0;g<f;g++){var h=e.ca(g);h instanceof D.YC&&h.update(b)}}};D.sD.prototype.Qva=(0,D.B)("wda");
D.sD.prototype.wU=function(){(0,D.FP)(this);var b=(0,D.mD)(this,this.Rj),c=(0,D.kE)(this,this.Rj),d=[];if(b){this.oR[this.Rj]=this.rv;var e=this.AG[this.Rj];!this.hT&&"single"==this.Ik&&(this.vm.pop(),c.reset(d,e),b.reset(this.zv));for(var f=[],g=0;g<e.length;g++){var h=e[g],j=(0,D.gD)(c,h);f.push(j[0]);for(var m=0;m<j.length;m++)this.E_[j[m]]=e[g];b.r5(j,d);if(j=c.yj(this.rv)){for(var m=h,o=this.zv,p=0;p<j.ic.length;p++)if(j.ic[p].kl==m){j.ic[p].kI(D.n);j.vm.push(m);o.push(j.ic[p].Da());if(p=j.ic[p].Eg())o.push(p),
(p=p.Uj)&&o.push(p);break}for(p=0;p<j.Ih.length;p++)if(j.Ih[p].kl==m){o.push(j.Ih[p].Da());break}}this.vm.push(h)}(0,D.LP)(this,this.zv,d,D.t);(0,D.MP)(this,b.Lf);this.Rj=b.Lf;this.AG[this.Rj]=f}};
D.sD.prototype.t5=function(){(0,D.FP)(this);for(var b=(0,D.kE)(this,this.Rj),c=(0,D.KP)(this,this.Rj),d=[],e=[],f=this.AG[this.Rj],g=0;g<f.length;g++){var h=this.E_[f[g]];e.push(h);if(-1!=D.Kf.Fa(this.vm,h)){b.qO((0,D.gD)(c,h),this.zv);for(var j=c.yj(this.oR[c.Lf]),m=h,o=d,p=0;p<j.ic.length;p++)if(j.ic[p].kl==m){j.vm.splice(D.Kf.Fa(j.vm,m),1);j.ic[p].kI(D.t);var r=j.ic[p].Da();j.Ek.k(r);o.push(r);if(p=j.ic[p].Eg())p.update(j.qG),o.push(p),o.push(p.Uj);break}for(p=0;p<j.Ih.length;p++)if(j.Ih[p].kl==
m){r=j.Ih[p].Da();j.Jr.k(r);o.push(r);break}h=D.Kf.Fa(this.vm,h);-1!=h&&this.vm.splice(h,1)}}(0,D.LP)(this,this.zv,d,D.n);this.Rj=c.Lf;this.rv=this.oR[this.Rj];this.AG[this.Rj]=e;(0,D.MP)(this,this.Rj)};D.FP=function(b){b.pb&&(b.pb.stop(D.n),b.pb=D.q)};
D.LP=function(b,c,d,e){b.Mb.Y.ma();if(b.yva&&!b.hT){var f=new D.Ef(b.e,0.3);(0,D.Gg)()||(f=D.q);e?b.Mb.io(f):(0,D.fE)(b);f&&f.play()}(0,D.FP)(b);b.pb=D.ap.Dz(b.e,b.Hta,c,d,D.q,0.5);(0,D.Gg)()||(b.pb=D.q);b.pb?(b.Aa.tc(),b.Aa.zs(b),b.pb.xd(b.mqa,b),b.pb.play()):(0,D.OP)(b)};
D.sD.prototype.Xa=function(b){var c=b.Ga();if("selection"==c)if(this.rv){this.K3=b.getSelection();for(var c=this.AG,d=this.Rj,e=this.K3,f=[],g=(0,D.kE)(this,this.Rj).yj(this.rv).ic,h=0;h<e.length;h++)for(var j=0;j<g.length;j++)if(g[j].getId()==e[h]){f.push(g[j].kl);break}c[d]=f;(0,D.MP)(this,this.Rj);(0,D.Mf)(b,"clientId",this.rv);this.FQ&&!(this.FQ instanceof D.Vm)&&(this.Fja=this.FQ)}else(0,D.MP)(this,D.q),this.Fja=D.q;else c==D.ND.Uaa?((0,D.Mf)(b,"clientId",this.rR),this.hF="multiple"==this.Ik?
this.hF.concat(this.K3):this.K3,c=b.wva,c==D.ND.Noa&&this.t5(),c==D.ND.cX?this.wU():c==D.ND.tqa&&this.d8(),b.Je(this.hF)):("showPopup"==c||"hidePopup"==c)&&(0,D.Mf)(b,"clientId",this.rR);D.sD.q.Xa.call(this,b)};D.MP=function(b,c){if(b.Cc&&b.Ik&&"none"!=b.Ik){var d=(0,D.mD)(b,c),e=(0,D.KP)(b,c);d?(0,D.ZD)(b.Cc,D.n):(0,D.ZD)(b.Cc,D.t);e?(0,D.$D)(b.Cc,D.n):(0,D.$D)(b.Cc,D.t)}};D.sD.prototype.U=function(){D.sD.q.U.call(this);this.Aa&&(this.Aa.U(),this.Aa=D.q)};D.sD.prototype.destroy=D.sD.prototype.U;
D.sD.prototype.vo=function(){this.Cc&&this.Mb.k(this.Cc);this.cG&&(this.removeChild(this.cG),this.cG=D.q);this.pb=D.q;this.WR&&(0,D.HP)(this);this.Aa.rf(this)};D.sD.prototype.mqa=function(){(0,D.OP)(this);this.pb=D.q;this.Aa.rf(this)};D.OP=function(b){if(0<b.zv.length){for(var c=0;c<b.zv.length;c++){var d=b.zv[c];if(d)if(d instanceof D.YC)d.reset();else if(d.ru&&d.ru())d.B(0);else{var e=d.getParent();e&&e.removeChild(d)}}b.zv=[]}};
D.sD.prototype.tT=function(b){this.xR("mouseover"==b.Kga?"categoryRollOver":"categoryRollOut",b.c6())};D.sD.prototype.xR=function(b,c){var d=new D.Ym(b,c),e=[],f;for(f in this.mh)for(var g in this.mh[f])e.push(this.mh[f][g]);for(f in this.Vv)for(g in this.Vv[f])e.push(this.Vv[f][g]);f=this.Ba.$0;for(var h in f)g=new D.QD(f[h].fe(),h),e.push(g);(0,D.Br)(d,e,0.1)};D.sD.prototype.Li=function(){this.tx||(this.tx=new D.$C(this));return this.tx};D.sD.prototype.getAutomation=D.sD.prototype.Li;
D.UD=function(){this.Init({fusion:D.RD,skyros:D.SD,alta:D.TD})};D.D.l(D.UD,D.Dl,"DvtThematicMapDefaults");
D.RD={skin:D.q,animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"off",initialZooming:"none",maintainDrill:"off",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",zooming:"none",styleDefaults:{areaStyle:"background-color:#B8CDEC;border-color:#FFFFFF;",dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",
selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",borderWidth:"0.5px",color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:0.4,scaleX:1,scaleY:1,shape:"circle",width:8},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:D.n,layout:{gapRatio:1}},layout:{gapRatio:D.q,legendMaxSize:0.3,legendGap:10},resources:{images:{},translations:{}}};D.SD={styleDefaults:{backgroundColor:"#FFFFFF"}};
D.TD={skin:"alta",styleDefaults:{areaStyle:"background-color:#DDDDDD;border-color:#FFFFFF;",backgroundColor:"#FFFFFF",dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;color:#333333',opacity:1},labelStyle:'font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;font-size:12px;'}};D.uD={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};
D.vD={animationOnDataChange:"none",selection:"none"};
D.rD=function(b){for(var c=0;c<b.Le.length;c++){var d=b.Le[c].fh,e;for(e in d){var f=d[e].Hk;if(f&&f.tB)return f}}return D.q};D.sD.prototype.Fj=function(b,c,d){this.ova=D.t;return(b=(0,D.rD)(this))?b.Fj(d):D.t};D.sD.prototype.Zk=function(b,c){var d=(0,D.rD)(this);return d?d.Zk(b,c):D.q};

D.fD=function(b,c){this.XHa=b;this.kIa=c};D.D.l(D.fD,D.sl,"DvtThematicMapDropTarget");
D.$C=(0,D.ba)("P");(0,D.qa)("DvtThematicMapAutomation",D.$C);D.D.l(D.$C,D.Ol,"DvtThematicMapAutomation");
D.$C.prototype.hr=function(b){b=this.P.Aa.na(b);var c;if(b&&(b instanceof D.aD||b instanceof D.bD))a:{for(var d=this.P.Le,e=0;e<d.length;e++){var f=d[e].fh;for(c in f)if(b instanceof D.aD)for(var g=f[c].ic,h=0;h<g.length;h++){if(g[h]===b){c=(0,D.cD)(c)+":area["+b.getId()+"]";break a}}else if(b instanceof D.bD){g=f[c].Ih;for(h=0;h<g.length;h++)if(g[h]===b){c=(0,D.cD)(c)+":marker["+b.getId()+"]";break a}}}c=D.q}else c=D.q;return c};
D.$C.prototype.bk=function(b){var c=b.indexOf(":"),d=b.indexOf("[");b=0<c&&0<d?(b=(0,D.dD)(this,b.substring(0,c),b.substring(c+1,d),b.substring(d+1,b.length-1)))?b.Da().oa():D.q:D.q;return b};D.$C.prototype.getDomElementForSubId=D.$C.prototype.bk;D.$C.prototype.getData=function(b,c,d){return(b=(0,D.dD)(this,b,c,d))?(c={},c.color=b.zj(),c.tooltip=b.gf(),d=b.Eg(),c.label=d?d.We():D.q,c.isSelected=b.Na(),c):D.q};D.$C.prototype.getData=D.$C.prototype.getData;
D.dD=function(b,c,d,e){b=b.P.Le;for(var f=0;f<b.length;f++){var g=b[f].fh,h;for(h in g)if((0,D.cD)(h)==c)if("area"==d)for(var j=g[h].ic,m=0;m<j.length;m++){if(j[m].getId()===e)return j[m]}else if("marker"==d){j=g[h].Ih;for(m=0;m<j.length;m++)if(j[m].getId()===e)return j[m]}}return D.q};D.cD=function(b){var c=b.lastIndexOf(":");return 0<c?b.substring(c+1):b};
D.CD=function(b,c){this.Init(b,c)};D.D.l(D.CD,D.ef,"DvtDrillablePath");D.C=D.CD.prototype;D.C.Init=function(b,c){D.CD.q.Init.call(this,b);this.By=this.Ay=this.hR=this.gR=D.q;this.cS=D.t;this.Zoom=1;this.Fe=c};D.C.ru=(0,D.B)("cS");
D.C.kI=function(b){this.cS!=b&&(this.cS=b,this.ru()?(this.Ay=this.Ji(),this.Ay.G(D.q),this.Ay.ia(D.t),this.By=this.Ji(),this.By.G(D.q),this.By.ia(D.t),b=this.getParent(),b.k(this.By),b.k(this.Ay),this.Ay.Z((0,D.OD)(this,this.gR,2)),this.By.Z((0,D.OD)(this,this.hR,4)),this.ia(D.t),this.Ss=D.t):(this.Uh()&&(this.Ai(),this.Kg.Z((0,D.OD)(this,this.jr,1),2)),this.By.getParent().removeChild(this.By),this.Ay.getParent().removeChild(this.Ay),this.ia(D.n),this.B(1)))};
D.C.Ob=function(b){this.Fp!=b&&(b&&(this.Uh()?(this.EI(),this.pl=(0,D.OD)(this,this.pl,2),this.tk=(0,D.OD)(this,this.tk,6)):(this.mr=(0,D.OD)(this,this.mr,1),this.zo=(0,D.OD)(this,this.zo,4))),D.CD.q.Ob.call(this,b))};D.C.Fc=function(){this.Na()?(this.EI(),this.pl=(0,D.OD)(this,this.pl,2),this.tk=(0,D.OD)(this,this.tk,6)):this.jr=(0,D.OD)(this,this.jr,2);D.CD.q.Fc.call(this)};
D.C.EI=function(){this.pl||(this.pl=this.jr.clone(),this.pl.ha(2),this.Fe&&(this.pl.gd=D.n));this.tk||(this.tk=this.zo.clone(),this.tk.ha(6),this.Fe&&(this.tk.gd=D.n))};D.C.nc=function(){this.Na()&&(this.mr=(0,D.OD)(this,this.mr,1),this.zo=(0,D.OD)(this,this.zo,4));D.CD.q.nc.call(this)};D.C.$q=function(b,c){D.CD.q.$q.call(this,b,c);this.Fe&&(this.jr&&(this.jr.gd=D.n),this.bP&&(this.bP.gd=D.n));return this};
D.C.br=function(b,c){D.CD.q.br.call(this,b,c);this.Fe&&(this.mr&&(this.mr.gd=D.n),this.zo&&(this.zo.gd=D.n));return this};D.C.Ku=function(b,c){D.CD.q.Ku.call(this,b,c);this.Fe&&(this.pl&&(this.pl.gd=D.n),this.tk&&(this.tk.gd=D.n));return this};D.DD=function(b,c,d){b.gR=c;b.gR&&b.Fe&&(b.gR.gd=D.n);b.hR=d;b.hR&&b.Fe&&(b.hR.gd=D.n)};D.PD=function(b,c,d){if(!b.Fe){var e=c.mc();e&&(e=e.clone(),e.ha(d/b.Zoom),c.Z(e))}};D.OD=function(b,c,d){b.Fe||(c=c.clone(),c.ha(d/b.Zoom));return c};
D.MD=function(b,c){b.Zoom=c.Qc;b.ru()?((0,D.PD)(b,b.Ay,2),(0,D.PD)(b,b.By,4)):b.Na()?b.Uh()?((0,D.PD)(b,b.Kg,2),(0,D.PD)(b,b,6)):((0,D.PD)(b,b.Kg,1),(0,D.PD)(b,b,4)):b.Uh()?(0,D.PD)(b,b.Kg,2):(0,D.PD)(b,b,1)};
D.iD=this.DvtBaseMapManager;D.iD?(D.iD.pr=D.iD._UNPROCESSED_MAPS,D.iD.AE=D.iD._UNPROCESSED_PARENT_UPDATES):D.iD={pr:[[],[],[]],AE:[[],[],[]]};"undefined"!=typeof D.DVT_ADVANCED_CLOSURE&&((0,D.qa)("DvtBaseMapManager",D.iD),D.iD._UNPROCESSED_MAPS=D.iD.pr,D.iD._UNPROCESSED_PARENT_UPDATES=D.iD.AE);D.D.l(D.iD,D.D,"DvtBaseMapManager");D.iD.wE=0;D.iD.iJ=1;D.iD.WY=2;D.iD.VY=3;D.iD.vP=4;D.iD.Ws="__index";D.iD.kh={};
D.iD.Ika=function(b,c){D.iD.Gn();var d=D.iD.kh[b][c];return d&&(d=d[D.iD.vP])?new D.H(d[0],d[1],d[2],d[3]):D.q};D.iD.Cka=function(b,c){D.iD.Gn();var d=D.iD.kh[b][c];return d?d[D.iD.VY]:D.q};D.iD.Dka=function(b,c){D.iD.Gn();var d=D.iD.kh[b][c];return d?d[D.iD.wE]:D.q};D.iD.kla=function(b,c,d){D.iD.Gn();b=D.iD.kh[b][c];var e;b&&(e=b[D.iD.wE]);return e&&e[d]?e[d][1]:D.q};D.iD.Oka=function(b,c){D.iD.Gn();var d=D.iD.kh[b];if(d&&(d=d.cities))if(d=d[D.iD.iJ][c])return new D.G(d[0],d[1]);return D.q};
D.iD.Pka=function(b,c){D.iD.Gn();var d=D.iD.kh[b];if(d&&(d=d.cities))if(d=d[D.iD.wE][c])return d[1];return D.q};D.iD.Bka=function(b,c,d){D.iD.Gn();var e=D.iD.kh[b];if(e&&(e=e[c])){if((e=e[D.iD.VY])&&e[d])return(0,D.ZC)(e[d][0]).Td();b=D.iD.kh[b][c][D.iD.iJ][d];if(!b)return D.q;b=window.DvtPathUtils.sU(b);return window.DvtPathUtils.C(b).Td()}return D.q};D.iD.Lka=function(b,c){D.iD.Gn();var d=D.iD.kh[b][c];return d?D.iD.kh[b][D.iD.Ws][d.__index+1]:D.q};
D.iD.oDa=function(b,c){D.iD.Gn();return D.iD.kh[b][c]?D.iD.kh[b][D.iD.Ws][D.iD.kh[b][c].__index-1]:D.q};D.iD.Eka=function(b,c){D.iD.Gn();return D.iD.kh[b][c][D.iD.iJ]};D.iD.pDa=function(b,c,d){D.iD.Gn();return D.iD.kh[b][c][D.iD.iJ][d]};D.iD.Mka=function(b,c){D.iD.Gn();var d=D.iD.Lka(b,c);return d&&(d=D.iD.kh[b][d][D.iD.WY])?d:[]};D.iD.QJa=function(b,c){D.iD.Gn();return D.iD.kh[b][D.iD.Ws][c]};
D.iD.aW=function(b,c,d,e,f,g,h,j){var m=D.iD.kh[b];m||(m={},m[D.iD.Ws]=[],D.iD.kh[b]=m);b=m[c];b||(b={},m[c]=b,h!=D.q&&(m[D.iD.Ws][h]=c));b[D.iD.wE]=d;b[D.iD.iJ]=e;b[D.iD.WY]=f;b[D.iD.VY]=g;b[D.iD.vP]=j;b[D.iD.Ws]=h};(0,D.qa)("DvtBaseMapManager.registerBaseMapLayer",D.iD.aW);D.iD.rna=function(b,c,d){var e=D.iD.kh[b];e||(e={},D.iD.kh[b]=e);b=e[c];b||(b={},e[c]=b);(b=e[c])&&(b[D.iD.wE]=d)};(0,D.qa)("DvtBaseMapManager.registerResourceBundle",D.iD.rna);
D.iD.Rna=function(b,c,d){if(b=D.iD.kh[b])if(c=b[c])for(var e in d)c[D.iD.wE][e]=d[e]};(0,D.qa)("DvtBaseMapManager.updateResourceBundle",D.iD.Rna);D.iD.CFa=function(b,c){D.iD.pr=b;D.iD.AE=c;D.iD.Gn()};(0,D.qa)("DvtBaseMapManager.loadUnprocessedMaps",D.iD.CFa);
D.iD.Gn=function(){var b,c;if(D.iD.pr){for(b=0;b<D.iD.pr[0].length;b++)c=D.iD.pr[0][b],D.iD.aW(c[0],c[1],c[2],c[3],c[4],c[5],c[6],c[7]);for(b=0;b<D.iD.pr[1].length;b++)c=D.iD.pr[1][b],D.iD.rna(c[0],c[1],c[2]);for(b=0;b<D.iD.pr[2].length;b++)c=D.iD.pr[2][b],D.iD.Rna(c[0],c[1],c[2]);D.iD.pr=D.q}if(D.iD.AE)for(b=0;b<D.iD.AE[0].length;b++){c=D.iD.AE[0][b];var d=c[1],e=c[2],f=D.iD.kh[c[0]],g;if(f){if(d=f[d]){d[D.iD.WY]=c[3];g=d[D.iD.vP];b=d[D.iD.Ws];d=f[D.iD.Ws];d.splice(b,0,e);f[e][D.iD.Ws]=b;for(b+=
1;b<d.length;b++)(e=f[d[b]])&&e[D.iD.Ws]++}(d=f[c[2]])&&(d[D.iD.vP]=g)}}};D.iD.OGa=function(b,c,d,e,f,g){if(0<g){c=1/(window.Math.min(e/c,f/d)*g);if(1>=c)return b;d=[];if(b)for(var h in b)e=b[h],(0,window.isNaN)(e)&&(e=window.DvtPathUtils.sU(b[h])),d[h]=window.DvtPathUtils.PGa(e,c);return d}return b};
D.QD=function(b,c){this.Init(b,c)};D.D.l(D.QD,D.D,"DvtThematicMapCategoryWrapper");D.QD.prototype.Init=function(b,c){this.qB=b;this.qn=c};D.QD.prototype.Oh=(0,D.B)("qn");D.QD.prototype.ve=function(){return[this.qB]};
D.ND=function(b){this.Init(D.ND.Uaa);this.wva=b};D.D.l(D.ND,D.pf,"DvtMapDrillEvent");D.ND.Uaa="drill";D.ND.Noa=0;D.ND.cX=1;D.ND.tqa=2;D.ND.prototype.Je=(0,D.ba)("sg");
D.Px=function(b,c,d){this.Init("action");this.mt=b;this.aM=c;this.vk=d};(0,D.qa)("DvtMapActionEvent",D.Px);D.D.l(D.Px,D.pf,"DvtMapActionEvent");D.Px.TYPE="action";D.Px.prototype.wh=(0,D.B)("mt");D.Px.prototype.getClientId=D.Px.prototype.wh;D.Px.prototype.y6=(0,D.B)("aM");D.Px.prototype.getRowKey=D.Px.prototype.y6;D.Px.prototype.vj=(0,D.B)("vk");D.Px.prototype.getAction=D.Px.prototype.vj;
D.YC=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.D.l(D.YC,D.ph,"DvtMapLabel");D.C=D.YC.prototype;D.C.Init=function(b,c,d,e,f,g){D.YC.q.Init.call(this,b,c,0,0);this.Fe=g;this.it=[];this.ia(D.t);this.Re();this.Ae();this.kt=D.q;this.Po=e;this.uC=f;if(d&&(this.it.push((0,D.ZC)(d[0])),1<d.length)){this.G1=[];for(c=1;c<d.length;c++)e=d[c],this.it.push((0,D.ZC)(e[0])),e=new D.Mv(b,e[1]),(0,D.bn)(e),f=new D.ff("#000000"),this.Fe&&(f.gd=D.n),e.Z(f),this.G1.push(e)}};
D.C.update=function(b){b=b.Qc;for(var c=-1,d=D.Kl.Qi(this),e=D.t,f=0;f<this.it.length;f++){var g=this.it[f].g*b;if(d.j<=this.it[f].j*b)if(d.g<=g){c=f;break}else if(this.getParent()||(e=D.n,this.uC.k(this)),this.C().g<=g){c=f;break}}-1==c&&"on"==this.Po&&(c=this.it.length-1);this.$_!=c?(-1==c?this.reset():(this.getParent()||this.uC.k(this),d=this.it[c].Td(),this.bo(d),this.G1&&(this.uC.removeChild(this.Uj),this.Uj=D.q,0<c?(this.Uj=this.G1[c-1],this.uC.k(this.Uj),e=this.Rc(),e.V("color","#000000"),
this.Ha(e),e=this.it[c],f=this.Uj.Ib(),g=f.length,e.x>f[g-2]?(this.Tk(),this.Ae(),this.bo(new D.G(e.x,d.y))):e.y>f[g-1]?(this.lp(),this.Re(),this.bo(new D.G(d.x,e.y))):e.x+e.g<f[g-2]?(this.ni(),this.Ae(),this.bo(new D.G(e.x+e.g,d.y))):e.y+e.j<f[g-1]&&(this.ww(),this.Re(),this.bo(new D.G(d.x,e.y+e.j)))):(this.Re(),this.Ae(),e=this.Rc(),e.V("color",this.Ifa),this.Ha(e)))),this.$_=c):-1==c&&e&&this.uC.removeChild(this);-1!=this.$_&&(c=new D.rh,c.translate(b*this.kt.x-this.kt.x,b*this.kt.y-this.kt.y),
this.ra(c),this.Uj&&(this.Uj.ra(new D.rh(b,0,0,b)),this.Fe||(c=this.Uj.mc().clone(),c.ha(1/b),this.Uj.Z(c))))};D.C.bo=function(b){this.kt=b;this.da(b.x);this.ta(b.y)};D.C.Td=(0,D.B)("kt");D.C.Ha=function(b){D.YC.q.Ha.call(this,b);this.Ifa||(this.Ifa=b.v("color"))};D.C.reset=function(){this.uC.removeChild(this);this.$_=-1;this.Uj&&(this.uC.removeChild(this.Uj),this.Uj=D.q)};
D.RC=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.RC,D.Q,"DvtMapDataObject");D.C=D.RC.prototype;D.C.Init=function(b,c,d,e,f){D.RC.q.Init.call(this,b,D.q,e);this.pn=[];this.Jb=D.q;this.Oa=d;this.mt=e;this.kl=f;this.hJa=D.q;this.mK="#000000";this.Zoom=1;this.MR=D.t;this.cR=c;this.ed=c.P.Kc()};D.C.getId=(0,D.B)("Oa");D.C.wh=(0,D.B)("mt");D.C.Kd=function(b){(this.Jb=b)&&this.Jb.If("img")};D.C.bo=(0,D.ba)("nk");D.C.Td=(0,D.B)("nk");D.C.Da=(0,D.B)("Jb");D.C.eo=(0,D.ba)("so");D.C.Eg=(0,D.B)("so");
D.C.Oc=(0,D.ba)("Z$");D.C.vj=(0,D.B)("vk");D.C.bb=function(b){D.RC.q.bb.call(this,b);this.so&&this.so.bb(b)};D.C.ve=function(){return[this.Jb]};D.C.Oh=(0,D.B)("pn");D.C.gf=(0,D.B)("zy");D.C.zj=(0,D.B)("mK");D.C.n8=function(b){this.mK=b;this.Jb&&this.Jb.vp&&this.Jb.vp(b)};D.C.m8=function(b){this.zy=b;this.Oj()};D.C.ee=function(){var b=[];this.dc()&&b.push((0,D.wg)(this.ed,this.Na()?"STATE_SELECTED":"STATE_UNSELECTED"));return(0,D.en)(this.gf(),b,this.ed)};
D.C.Oj=function(){!(0,D.fn)()&&this.Jb&&(0,D.gn)(this.Jb,"label",this.ee())};D.C.dc=function(){return this.Jb.dc()};D.C.Na=function(){return this.Jb.Na()};D.C.Fc=(0,D.w)();D.C.nc=function(){this.Wd||this.UX()};D.C.UX=(0,D.w)();D.C.x8=(0,D.ba)("jd");D.C.Fd=(0,D.B)("jd");D.C.Fj=function(b){for(var c=this.cR.wh(),d=0;d<b.length&&b[d]!=c;d++);return c};D.C.yj=(0,D.B)("cR");D.C.Zk=function(){return this.cR.Wx(this)};D.C.UC=function(){return this.cR.Vx()};
D.C.Ef=function(b){return b.type==D.bi?this:32==b.keyCode&&b.ctrlKey?this:(0,D.xq)(this,b,this.wX())};D.C.wX=(0,D.ca)(D.q);D.C.hf=function(b){return this.Jb&&this.Jb.getParent()?this.Jb.C(b):new D.H(0,0,0,0)};D.C.Pm=function(){return this.Jb?this.Jb.oa():D.q};D.C.bg=function(){this.Wd=D.n;this.Fc()};D.C.Mc=function(){this.Wd&&(this.Wd=D.t,this.nc())};D.C.Gg=(0,D.B)("Wd");D.C.ng=function(b){this.Jb.getParent()&&(this.Zoom=b.Qc,this.QN())};D.C.Jp=(0,D.w)();D.C.QN=(0,D.w)();D.C.sc=(0,D.ca)(0);
D.aD=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.aD,D.RC,"DvtMapDataArea");D.C=D.aD.prototype;D.C.Init=function(b,c,d,e,f){D.aD.q.Init.call(this,b,c,d,e,f);this.n1=D.t};D.C.Kd=function(b){D.aD.q.Kd.call(this,b)};D.C.Ob=function(b){b&&!this.n1&&this.Ek.k(this.Jb);this.Jb.Ob(b);this.Oj()};D.C.Fc=function(){this.Ek.k(this.Jb);this.Jb.Fc();this.n1=D.n};D.C.UX=function(){this.Na()?this.Ek.k(this.Jb):this.Ek.Ia(this.Jb,0);this.Jb.nc();this.n1=D.t};D.C.ru=function(){return this.Jb.ru()};
D.C.kI=function(b){(this.cS=b)?this.Ek.k(this.Jb):this.Ek.Ia(this.Jb,0);this.Jb.kI(b)};D.C.ng=function(b){this.Jb.getParent()&&(D.aD.q.ng.call(this,b),(0,D.MD)(this.Jb,b),this.ru()||this.Jp(b))};D.C.Jp=function(b){this.so&&this.so.update(b)};D.C.wX=function(){return(0,D.qD)(this.yj().P)};
D.bD=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.bD,D.RC,"DvtMapDataMarker");D.C=D.bD.prototype;D.C.Init=function(b,c,d,e,f){D.bD.q.Init.call(this,b,c,d,e,f);this.lHa=1;this.Yj=0};D.C.Ob=function(b){this.Jb.Ob(b);this.Oj()};D.C.Fc=function(){this.Jb.Fc()};D.C.UX=function(){this.Jb.nc()};
D.C.Jp=function(){if(this.so){this.so.Re();var b=(this.Jb.ea()+(0,D.aE)(this.Jb)/2)*this.Zoom,c=this.Jb.ga()*this.Zoom,d=(0,D.bE)(this.Jb),e=this.Jb.Ga();"top"==this.Z$?(c-=4,this.so.ww()):"bottom"==this.Z$?(c+=d,this.so.lp()):(c="triangleUp"==e?c+2*d/3:"triangleDown"==e?c+d/3:c+d/2,this.so.Ae());this.so.da(b);this.so.ta(c)}};
D.C.QN=function(){var b=this.Jb.getParent(),c=(0,D.bE)(this.Jb);(0,D.aE)(this.Jb)!=D.q&&(c!=D.q&&b)&&(c=this.Jb.aD(),this.so&&this.Jb.aD()?((0,D.jg)(b,this.nk.x*this.Zoom-this.nk.x,this.nk.y*this.Zoom-this.nk.y),(0,D.nw)(b)):((0,D.jg)(this.Jb,this.nk.x*this.Zoom-(this.nk.x*window.Math.cos(c)-this.nk.y*window.Math.sin(c)),this.nk.y*this.Zoom-(this.nk.x*window.Math.sin(c)+this.nk.y*window.Math.cos(c))),(0,D.nw)(this.Jb)))};D.C.wX=function(){return(0,D.oD)(this.yj().P)};D.C.Xh=(0,D.ba)("Yj");
D.C.sc=(0,D.B)("Yj");
D.QC=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.QC,D.RC,"DvtMapDataImage");D.C=D.QC.prototype;D.C.Init=function(b,c,d,e,f){D.QC.q.Init.call(this,b,c,d,e,f)};D.C.UV=function(b){b&&(b.width&&b.height)&&(this.Jb.getWidth()||this.Jb.ha(b.width),this.Jb.getHeight()||this.Jb.ua(b.height),this.Xh(b.width*b.height),this.Jb.da(this.nk.x-b.width/2),this.Jb.ta(this.nk.y-b.height/2),this.QN())};D.C.Na=(0,D.ca)(D.t);
D.C.QN=function(){var b=this.Jb.getWidth(),c=this.Jb.getHeight();b!=D.q&&(c!=D.q&&this.Jb.getParent())&&(b=this.Jb.ea()+b/2,c=this.Jb.ga()+c/2,(0,D.jg)(this.Jb,b*this.Zoom-this.nk.x,c*this.Zoom-this.nk.y))};D.C.Xh=(0,D.ba)("Yj");D.C.sc=(0,D.B)("Yj");
D.LD=function(b,c,d,e,f){this.Init(b,c,d,e,f)};D.D.l(D.LD,D.RC,"DvtMapDataComponent");D.C=D.LD.prototype;D.C.Init=function(b,c,d,e,f){D.LD.q.Init.call(this,b,c,d,e,f)};D.C.ha=(0,D.ba)("S");D.C.getWidth=(0,D.B)("S");D.C.ua=(0,D.ba)("X");D.C.getHeight=(0,D.B)("X");D.C.da=(0,D.ba)("Ta");D.C.ta=(0,D.ba)("mb");D.C.QN=function(){if(this.Jb.getParent()){var b=this.mb+this.X/2;this.Jb.F(this.Ta+(this.Ta+this.S/2)*this.Zoom-this.nk.x);this.Jb.O(this.mb+b*this.Zoom-this.nk.y)}};
D.QC.prototype.sc=function(){return this.S*this.X};
D.SC=function(b,c,d,e){this.Init(b,c,d,e)};D.D.l(D.SC,D.Q,"DvtMapArea");D.C=D.SC.prototype;D.C.Init=function(b,c,d,e){D.SC.q.Init.call(this,b);this.iS=this.rQ=D.t;this.YHa=d;this.H=c;this.k(this.H);this.Fe=e;if(b=c.mc())this.ica=b.getWidth();this.H&&this.H.If("img")};D.C.ne=(0,D.B)("ef");D.C.nx=(0,D.ba)("ef");D.C.mc=function(){return this.H instanceof D.du?this.H.mc():D.q};D.C.Z=function(b){this.H instanceof D.du&&this.H.Z(b)};D.C.G=function(b){this.H instanceof D.du&&this.H.G(b)};
D.C.Lc=function(){return this.H instanceof D.du?this.H.Lc():D.q};D.C.PC=function(){return this.H instanceof D.ef?this.H.PC():D.q};D.C.kk=function(b){this.H instanceof D.ef&&this.H.kk(b)};D.C.RD=function(b){this.H instanceof D.kf&&this.H.RD(b)};D.C.contains=function(b,c){var d=this.C();return b>=d.x&&b<=d.x+d.g&&c>=d.y&&c<=d.y+d.j};D.C.ng=function(b){if(!this.Fe&&this.H&&this.ica){var c=this.H.mc().clone();c.ha(this.ica/b.Qc);this.H.Z(c)}};
D.eD=function(b,c){this.Init(b,c)};D.D.l(D.eD,D.D,"DvtMapLayer");D.C=D.eD.prototype;D.C.Init=function(b,c){this.P=b;this.Lf="cities";this.k9=D.q;this.LI=c;this.fh={};this.jn=new D.rh};D.C.raa=(0,D.w)();D.C.kP=(0,D.w)();
D.C.H8=function(b,c){this.pb&&(this.uJ=D.n,this.pb.stop(D.n));this.jn=c;this.Kt=this.yj(b.wh());this.fh[b.wh()]=b;b.L(this.jn);b.ng(new D.ly("zoomed"),this.jn);if(this.Kt){var d=b.Gq(),e=b.Qa();if(D.ap.isSupported(d)){for(var f=new D.H(0,0,this.P.S,this.P.X),g=(0,D.HD)(this.Kt),h=0;h<g.length;h++){var j=new D.af(this.P.e,0,0,this.P.S,this.P.X);j.G(D.q);g[h].k(j)}for(var m=(0,D.HD)(b),h=0;h<m.length;h++)j=new D.af(this.P.e,0,0,this.P.S,this.P.X),j.G(D.q),m[h].k(j);f=D.ap.Dz(this.P.e,d,g,m,f,e);g=new D.H(0,
0,this.P.S/this.jn.Qc,this.P.X/this.jn.Qc);m=[this.Kt.Ek];for(h=0;h<m.length;h++)j=new D.af(this.P.e,0,0,this.P.S/this.jn.Qc,this.P.X/this.jn.Qc),j.G(D.q),m[h].k(j);for(var o=[b.Ek],h=0;h<o.length;h++)j=new D.af(this.P.e,0,0,this.P.S/this.jn.Qc,this.P.X/this.jn.Qc),j.G(D.q),o[h].k(j);h=D.ap.Dz(this.P.e,d,m,o,g,e);this.pb=new D.Zv(this.P.e,[f,h])}else{d=[this.Kt.Ek,this.Kt.Jr,this.Kt.nB];for(h=0;h<d.length;h++)d[h].getParent().removeChild(d[h]);this.kP()}this.raa();if(this.pb){this.LI.zs(this.ka);
var p=this;this.pb.xd(function(){p.vo(b)},this);this.pb.play(D.n)}}else this.kP(),(0,D.cE)(this.P)};D.C.yj=function(b){return this.fh?this.fh[b]:D.q};D.C.wh=(0,D.B)("k9");D.C.L=function(b){this.jn=b;for(var c in this.fh)this.fh[c].L(b)};D.C.reset=function(b,c){for(var d in this.fh)this.fh[d].reset(b,c)};D.C.ng=function(b,c){this.jn=c;for(var d in this.fh)this.fh[d].ng(b,c)};D.C.Ps=function(b){this.jn=b;for(var c in this.fh)this.fh[c].Ps(b)};
D.C.vo=function(b){if(this.Kt)for(var c=[this.Kt.Ek,this.Kt.Jr,this.Kt.nB],d=0;d<c.length;d++){var e=c[d].getParent();e&&e.removeChild(c[d])}c=(0,D.HD)(b);for(d=0;d<c.length;d++)c[d].up(c[d].Ca()-1);b=[b.Ek];for(d=0;d<b.length;d++)b[d].up(b[d].Ca()-1);this.kP();(0,D.cE)(this.P);this.uJ=D.t;this.pb=D.q;this.LI.rf(this.ka)};
D.UC=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.D.l(D.UC,D.eD,"DvtMapAreaLayer");D.C=D.UC.prototype;D.C.Init=function(b,c,d,e,f,g){D.UC.q.Init.call(this,b,g);this.Po=e;this.Lf=c;this.k9=d;this.z1=f;this.AJ={};this.Ap={};this.cn={};this.QB=this.jo=D.q;this.sg=[];this.nq={};this.as={};this.pT={};this.tO=new D.Q(this.P.e);this.TI=new D.Q(this.P.e);this.P.MZ.Ia(this.tO,0);this.P.Ft.Ia(this.TI,0);this.u0=new D.fD(this,this.P.Me)};D.C.fI=(0,D.ba)("IZ");D.C.Gq=(0,D.B)("IZ");D.C.ao=(0,D.ba)("HZ");
D.C.Qa=(0,D.B)("HZ");D.WC=function(b,c){b.jo=c;for(var d in b.jo)b.nq[d]=D.n,b.as[d]=D.n};D.UC.prototype.SU=function(b){return!this.QB?D.q:this.QB[b]};D.gD=function(b,c){return b.je[c]?b.je[c].split(","):[]};D.UC.prototype.wH=(0,D.B)("Po");D.hD=function(b,c){b.LF=c;b.PF=D.q;for(var d in b.cn)d!=c&&(b.nq[d]=D.t)};
D.UC.prototype.WC=function(){if(!this.PF)if(this.LF)this.PF=window.DvtPathUtils.C(window.DvtPathUtils.sU(D.iD.pDa(this.P.Me,this.Lf,this.LF)));else if("world"!=this.P.Me&&"worldRegions"!=this.P.Me&&(this.PF=D.iD.Ika(this.P.Me,this.Lf)),!this.PF){var b=(0,D.$h)(this.tO.C(),this.P.lK.C());0<b.g&&0<b.j&&(this.PF=b)}return this.PF};
D.jD=function(b,c,d){var e=b.cn[c];if(e&&((d||!b.Ap[c])&&b.Qna(c),b.Ap[c]||(d=new D.SC(b.P.e,e,c,b.P.Fe),b.Ap[c]=d,b.LI.ja(e,d),d.nx(b.jo&&b.jo[c]?b.jo[c][1]:D.q)),b.as[c]&&(d=b.AJ[c],!d&&("off"!=b.Po&&b.jo)&&(d="short"==b.z1?b.jo[c][0]:b.jo[c][1]))))b.QB&&b.QB[c]?d=new D.YC(b.P.e,d,b.QB[c],b.Po,b.TI,b.P.Fe):(e=(0,D.Gp)(b.P.e,e),d=new D.YC(b.P.e,d,[[e.x,e.y,e.g,e.j]],b.Po,b.TI,b.P.Fe)),b.AJ[c]=d,b.uS&&d.Ha(b.uS)};
D.kD=function(b,c,d){if(b.cn[c]){b.tO.k(b.Ap[c]);var e=b.AJ[c];e&&(b.as[c]?e.update(b.jn):e.reset(),b.pT[c]=b.as[c]);d&&(d.push(b.Ap[c]),e&&(d.push(e),d.push(e.Uj)))}};D.UC.prototype.Qna=function(b){if(!this.Nha||this.wca){this.wca=D.t;var c;this.Nha=(c="world"==this.P.Me||"worldRegions"==this.P.Me?D.iD.Ika(this.P.Me,this.Lf):this.WC())?D.iD.OGa(D.iD.Eka(this.P.Me,this.Lf),c.g,c.j,this.P.S,this.P.X,this.P.yz?this.P.Z1:1):D.iD.Eka(this.P.Me,this.Lf)}c=this.Nha[b];this.cn[b]&&c?this.cn[b].kk(c):delete this.cn[b]};
D.lD=function(b){for(var c in b.jo)b.nq[c]=D.n,b.as[c]=D.n};D.C=D.UC.prototype;D.C.H8=function(b,c,d){D.UC.q.H8.call(this,b,c,d);if(d==this.Lf)for(var e in this.cn)(0,D.jD)(this,e,D.n),this.nq[e]&&(0,D.kD)(this,e)};D.C.L=function(b){this.wca=D.n;for(var c in this.cn)(0,D.jD)(this,c,D.n),this.nq[c]&&(0,D.kD)(this,c);D.UC.q.L.call(this,b)};D.C.raa=function(){for(var b in this.nq)this.nq[b]||((0,D.jD)(this,b,D.t),(0,D.kD)(this,b))};
D.C.kP=function(){for(var b in this.nq)if(!this.nq[b]){this.tO.removeChild(this.Ap[b]);var c=this.AJ[b];c&&(this.pT[b]=D.t,this.TI.removeChild(c),(c=c.Uj)&&this.TI.removeChild(c))}};D.C.r5=function(b,c){for(var d=0;d<b.length;d++)(0,D.jD)(this,b[d],D.t),this.nq[b[d]]&&(0,D.kD)(this,b[d],c);for(var e in this.fh)this.fh[e].r5(b,c,this.jn);this.sg=this.sg.concat(b)};
D.C.qO=function(b,c){for(var d in this.fh)this.fh[d].qO(b,c);d=(0,D.mD)(this.P,this.Lf);for(var e=0;e<b.length;e++){var f=b[e];if(this.Ap[f]){var g=D.Kf.Fa(this.sg,f);-1!==g&&(this.sg.splice(g,1),c.push(this.Ap[f]))}d&&d.qO((0,D.gD)(this,f),c)}};D.C.reset=function(b,c){D.UC.q.reset.call(this,b,c);"none"!=this.P.Ik&&(this.qO(this.sg,b),this.sg=[])};D.C.ng=function(b,c){D.UC.q.ng.call(this,b,c);if(!this.P.Fe)for(var d in this.Ap)this.Ap[d].ng(c);for(d in this.pT)if(this.pT[d]){var e=this.AJ[d];e&&e.update(c)}};
D.TC=function(b,c,d,e,f,g){this.Init(b,c,d,e,f,g)};D.D.l(D.TC,D.UC,"DvtMapCustomAreaLayer");D.TC.prototype.Init=function(b,c,d,e,f,g){D.TC.q.Init.call(this,b,c,d,e,f,g)};D.TC.prototype.Qna=(0,D.w)();D.TC.prototype.WC=function(){return new D.H(0,0,this.sxa,this.rxa)};D.VC=function(b){var c=b.P.S,d=b.P.X;b=b.Nta;for(var e=0;e<b.length;e++){var f=b[e],g=f.source,h=f.width,f=f.height;if(g&&-1<g.search(".svg")||h>=c&&f>=d||e==b.length-1)return g}};
D.XC=function(b,c){var d=D.q,e=(0,D.Qe)(b.P.e);if(c&&0<c.length){var d=c[0].width,f=c[0].height;b.sxa=d;b.rxa=f;for(var g=[],h=0;h<c.length;h++)e&&"rtl"==c[h].dir?g.push(c[h]):!e&&"ltr"==c[h].dir&&g.push(c[h]);b.Nta=0<g.length?g:c;b.SR=(0,D.VC)(b);d=new D.kf(b.P.e,b.SR,0,0,d,f)}d&&((0,D.WC)(b,{image:[D.q,D.q]}),b.cn={image:d})};D.TC.prototype.ng=function(b,c){D.TC.q.ng.call(this,b,c);if(this.Ap.image){var d=(0,D.VC)(this);d!=this.SR&&(this.SR=d,this.Ap[window.areaName].RD(this.SR))}};
D.wD=function(b,c,d,e){this.Init(b,c,d,e)};D.D.l(D.wD,D.D,"DvtMapDataLayer");D.wD.prototype.Init=function(b,c,d,e){this.P=b;this.mt=d;this.ic=[];this.Ih=[];this.Aa=e;this.Hk=new D.Gq(b.e);(0,D.cr)(this.Aa,this.Hk);this.Ek=new D.Q(this.P.e);this.Jr=new D.Q(this.P.e);this.nB=new D.Q(this.P.e);this.P.lK.Ia(this.Ek,0);this.P.vv.Ia(this.Jr,0);this.P.Ft.Ia(this.nB,0);this.Kha=c;this.sg=[];this.vm=[]};D.HD=function(b){var c=[b.nB];b.P.Tr&&c.push(b.Jr);return c};
D.ID=function(b){for(var c=[],d=0;d<b.ic.length;d++)b.ic[d].ru()||c.push(b.ic[d]);return c};D.JD=function(b){for(var c=[],d=0;d<b.ic.length;d++)for(var e=0;e<b.sg.length;e++)b.ic[d].kl==b.sg[e]&&(b.ic[d].ru()||c.push(b.ic[d]));return c};D.xD=function(b,c){b.ic.push(c);b.Aa.ja(c.Da(),c);c.Ek=b.Ek};D.C=D.wD.prototype;D.C.wh=(0,D.B)("mt");D.C.fI=(0,D.ba)("IZ");D.C.Gq=(0,D.B)("IZ");D.C.ao=(0,D.ba)("HZ");D.C.Qa=(0,D.B)("HZ");
D.C.Hs=function(b){if(this.fs=b)this.Nb=new D.nr(this.fs),this.Aa.kA(this.mt,this.Nb)};D.C.dc=function(){return this.fs!=D.q};D.KD=function(b,c){var d;d=b.ic[c];var e=d.Da(),f=b.Kha.cn[d.kl];f?(e.kk(f.PC()),d=D.n):(d=b.ic.indexOf(d),-1!==d&&b.ic.splice(d,1),d=D.t);if(d){e=b.ic[c].Da();b.Ek.k(e);if(d=b.ic[c].Eg())0<d.it.length||(e=e.C(),d.it.push(e)),d.update(b.qG);return D.n}return D.t};D.C=D.wD.prototype;
D.C.L=function(b){this.qca=D.n;this.qG=b;var c={};this.Ih.sort(function(b,c){return b.sc()<c.sc()?1:b.sc()>c.sc()?-1:0});for(var d=0;d<this.Ih.length;d++){var e=this.Ih[d],f=e.Da(),g=e.Eg();if(g){if(f.aD()){var h=new D.Q(f.e);this.Jr.k(h);h.k(f);h.k(g)}else this.Jr.k(f),f.k(g);e.Jp(b)}else this.Jr.k(f);if(e instanceof D.LD)if(g=e.pxa)f.L(window.JSON.parse(g),e.getWidth(),e.getHeight());else continue;(e=e.kl)&&(c[e]=D.n)}for(d=0;d<this.ic.length;d++)c[this.ic[d].kl]&&this.ic[d].eo(D.q),(0,D.KD)(this,
d)||d--;this.TR&&this.nG()};D.C.r5=function(b,c,d){this.qG=d;for(var e=[],f=0;f<b.length;f++)for(var g=0;g<this.ic.length;g++)if(this.ic[g].kl==b[f]){e.push(this.ic[g].kl);(0,D.KD)(this,g);var h=this.ic[g].Da();c.push(h);(0,D.MD)(h,d);if(g=this.ic[g].Eg())c.push(g),(g=g.Uj)&&c.push(g);break}for(g=0;g<this.Ih.length;g++)for(f=0;f<b.length;f++)d=this.Ih[g].kl,h=this.Ih[g].Da(),d!=D.q?d==b[f]&&(this.Jr.k(h),c.push(h)):(this.Jr.k(h),c.push(h));this.sg=this.sg.concat(e)};
D.C.qO=function(b,c){for(var d=0;d<b.length;d++)for(var e=0;e<this.ic.length;e++)if(this.ic[e].kl==b[d]){this.ic[e].ru()&&this.ic[e].kI(D.t);this.ic[e].Na()&&this.Nb.SN(this.ic[e]);var f=D.Kf.Fa(this.sg,b[d]);if(-1<f&&(this.sg.splice(f,1),c.push(this.ic[e].Da()),e=this.ic[e].Eg()))c.push(e),c.push(e.Uj);break}};
D.C.reset=function(b,c){if(this.Nb)for(var d=this.Nb.getSelection(),e=0;e<d.length;e++)(!c||c&&-1==D.Kf.Fa(c,d[e].kl))&&this.Nb.SN(d[e]);if("none"!=this.P.Ik)for(d=0;d<this.vm.length;d++){for(e=0;e<this.ic.length;e++)if(this.ic[e].kl==this.vm[d]){this.ic[e].kI(D.t);var f=this.ic[e].Da();this.Ek.k(f);b.push(f);if(e=this.ic[e].Eg())e.update(this.qG),b.push(e),b.push(e.Uj);break}for(e=0;e<this.Ih.length;e++)if(this.Ih[e].kl==this.vm[d]){f=this.Ih[e].Da();this.Jr.k(f);b.push(f);break}}this.vm=[]};
D.C.ng=function(b,c){this.qG=c;var d=c.Qc,e=b.Pi();if(this.qca&&"zoomed"==e){this.qca=D.t;for(e=0;e<this.ic.length;e++){var f=this.ic[e].Da(),g=f.aia;if(g){var h=new D.nm;g.Jd(h);h.ra(new D.rh(1/d,D.q,D.q,1/d));f.G(h)}}}e=this.ic;for(d=0;d<e.length;d++)e[d].ng(c);if(this.P.Tr){e=this.Ih;for(d=0;d<e.length;d++)e[d].ng(c)}};D.C.Ps=(0,D.ba)("qG");D.C.nG=function(){this.Nb&&((0,D.vs)(this.Nb,this.TR,this.Ih.concat(this.ic)),this.TR=D.q)};
D.C.Wx=function(b){if(this.Nb){b.Na()||(this.Nb.Yi(b,D.t),this.Aa.Eq(b));b=[];for(var c=this.Nb.getSelection(),d=0;d<c.length;d++)b.push(c[d].getId());return b}return D.q};D.C.Vx=function(){for(var b=[],c=this.Nb.getSelection(),d=0;d<c.length;d++)b.push(c[d].Da());return b};
D.nD=function(b,c){this.Init(b,c)};D.D.l(D.nD,D.Qu,"DvtThematicMapKeyboardHandler");D.C=D.nD.prototype;D.C.Init=function(b,c){D.nD.q.Init(b,c);this.P=b};D.C.RH=function(b){return this.Si(b)&&!b.ctrlKey};
D.C.$n=function(b){var c=b.keyCode;if(221==c){var c=this.sa.Be(),d=(0,D.oD)(this.P);c instanceof D.aD&&0<d.length&&(c=(0,D.xq)(c,b,d));(0,D.pD)(this.sa,c)}else 219==c?(c=this.sa.Be(),d=(0,D.qD)(this.P),!(c instanceof D.aD)&&0<d.length&&(c=(0,D.xq)(c,b,d)),(0,D.pD)(this.sa,c)):(c=D.nD.q.$n.call(this,b),this.Si(b)&&!b.ctrlKey&&(0,D.pD)(this.sa,c));return c};D.C.nD=function(b){return 32==b.keyCode&&b.ctrlKey};D.C.Si=function(b){var c=D.nD.q.Si.call(this,b);if(!c&&(b=b.keyCode,219==b||221==b))c=D.n;return c};
D.dE=function(b,c,d){this.Init(b,c,d)};D.D.l(D.dE,D.tm,"DvtThematicMapEventManager");D.C=D.dE.prototype;D.C.Init=function(b,c,d){D.dE.q.Init.call(this,b,c,d);this.lw={};this.P=d;this.ft=D.t};D.C.uf=function(b){if(b&&b.yj)return this.lw[b.yj().wh()]};D.C.kA=function(b,c){this.lw[b]=c};D.C.jW=(0,D.ba)("Ik");D.C.SN=function(b,c){var d=this.lw[b];d&&d.SN(c)};D.C.jH=function(b){(b=this.lw[b])&&b.jH()};
D.C.xo=function(b){var c=this.na(b.target);c&&(c.Fd&&c.yj)&&(this.P.rR=c.yj().wh());D.dE.q.xo.call(this,b)};D.C.ol=function(b){this.ft=D.t;D.dE.q.ol.call(this,b)};D.C.Ip=function(b){this.ft=D.n;D.dE.q.Ip.call(this,b)};D.C.hh=function(b){if(!this.ft){var c=this.na(b.target);(0,D.pD)(this,c);if(!c||!c.dc||!c.dc())for(var d in this.lw)if(this.lw[d].Yi(D.q,b.ctrlKey)){var e=new D.Ww([]);(0,D.Mf)(e,"clientId",d);this.hb.call(this.ka,e)}D.dE.q.hh.call(this,b);this.Bt(c,b.pageX,b.pageY)}};
D.C.Bt=function(b,c,d){b instanceof D.RC&&(b.MR?(0,D.eE)(this,b,c,d):b.Fd()&&(this.P.rR=b.yj().wh()))};D.eE=function(b,c,d,e){var f=new D.Px(c.wh(),c.getId(),c.vj());(0,D.Mf)(f,"clientId",c.yj().wh());d!=D.q&&e!=D.q&&(c=(0,D.Pg)(b.P.e,d,e),(0,D.Mf)(f,"pointXY",{x:c.x,y:c.y}));b.tc();b.hb.call(b.ka,f)};D.pD=function(b,c){var d=D.q,e=D.q,f=D.q;c&&(c instanceof D.RC?f=c.Da():c instanceof D.SC&&(f=c),c.yj&&(e=c.yj(),d=e.wh(),e=e.Kha.Lf));var g=b.P;g.Rj=e;g.rv=d;g.FQ=f};D.C=D.dE.prototype;
D.C.wo=function(b){D.dE.q.wo.call(this,b);b=this.na(b.target);this.uf(b)&&(this.Ik&&"none"!=this.Ik)&&(b=new D.ND(D.ND.cX),this.hb.call(this.ka,b))};
D.C.hm=function(b){var c=D.n,d=b.keyCode;if((48==d||96==d)&&b.ctrlKey&&b.shiftKey)this.P.d8(),b.preventDefault();else if(220==d)(d=this.P.jc)&&(d instanceof D.Jt?(0,D.Kt)(d,!d.isCollapsed()):d instanceof D.Yr&&d.Je(!d.eb())),b.preventDefault();else if(13==d)d=this.Be(),d instanceof D.RC&&d.MR?(0,D.eE)(this,d):(b.shiftKey?this.P.t5():this.P.wU(),b.preventDefault());else if(32==d&&b.ctrlKey)d=this.Be(),(0,D.pD)(this,d),(0,D.er)(this,d,D.n),b.preventDefault();else if((48==d||96==d)&&b.ctrlKey){var e=
this.Be();b.altKey?(d=this.P,e=e.Da(),e||(e=d.Fja),e||(e=d.FQ),d.bH(e.C())):(0,D.fE)(this.P);b.preventDefault()}else c=D.dE.q.hm.call(this,b);return c};D.C.Vs=function(b){var c=this.na(b.target);(0,D.pD)(this,c);if(!c||c.fKa)for(var d in this.lw)if(this.lw[d].Yi(D.q,b.ctrlKey)){for(var e=this.lw[d].getSelection(),f=[],g=0;g<e.length;g++)f.push(e[g].getId());e=new D.Ww(f);this.hb.call(this.ka,e)}D.dE.q.Vs.call(this,b);this.Bt(c,b.cr.pageX,b.cr.pageY)};
D.C.aP=function(b){if((b=this.na(b.target))&&b.Fd&&b.yj)this.P.rR=b.yj().wh()};D.C.zA=function(b){var c=this.na(b.target);c&&(this.uf(c)&&this.Ik&&"none"!=this.Ik)&&((0,D.er)(this,c,b.ctrlKey),b=new D.ND(D.ND.cX),this.hb.call(this.ka,b))};
D.gE=function(b){this.Init(b)};D.D.l(D.gE,D.D,"DvtThematicMapParser");D.yD="layer";D.zD="points";D.AD="point";D.hE="inlineStyle";D.iE="animationOnMapChange";D.iE="animationOnMapChange";D.hE="inlineStyle";D.C=D.gE.prototype;D.C.Init=function(b){this.P=b;this.Ada={};this.OP=this.QP=this.PP=this.dt=D.q;this.xfa=(0,D.wf)()};
D.C.q7=function(b){b=b.jb();for(var c,d,e=0;e<b.length;e++)if(c=b[e],d=c.getName(),"mapProperties"==d)this.uY(c);else if("customLayer"==d)this.wHa(c);else if("layers"==d)this.ZI(c);else if("legend"==d)this.jP(c);else if("childResources"==d){c=c.jb();for(d=0;d<c.length;d++){var f=c[d].getTextContent();f&&(0,D.jE)(window.JSON.parse(f))}}};
D.C.uY=function(b){var c;if(c=b.o("source"))this.Ov=D.n;if(c=b.o("baseMapName")){var d=this.P;c=this.Ov?"$"+c:c;d.$P=d.Me&&d.Me!=c;d.Me=c}if(c=b.o("animationOnDisplay"))this.P.KZ=c;if(c=b.o(D.iE))this.P.eca=c;(c=b.o("animationDuration"))&&this.P.ao(c);if(c=b.o("displayTooltips"))this.P.o0=c;if(c=b.o("dropTargetStyle"))this.Mta=new D.K(c);if(c=b.o("controlPanelBehavior"))this.P.gK=c;(c=b.o("featuresOff"))&&this.P.mW(c);if(c=b.o("centerX"))this.P.$wa=(0,window.parseFloat)(c);if(c=b.o("centerY"))this.P.axa=
(0,window.parseFloat)(c);if(c=b.o("curZoom"))this.P.kfa=(0,window.parseFloat)(c);if((c=b.o("animationOnDrill"))&&"alphaFade"==c)this.P.Hta=c;(c=b.o("drillMode"))&&this.P.jW(c);if(c=b.o("drillZoomToFit"))this.P.yva="true"==c;c=b.o("initialZooming");"auto"==c&&(this.P.WR=D.n);c=b.o("zooming");"none"==c&&(this.P.yz=D.t);c=b.o("panning");"none"==c&&(this.P.rC=D.t);c=(0,window.parseFloat)(b.o("maxZoom"));(0,window.isNaN)(c)||(this.P.Z1=c);if(c=b.o("markerZoomBehavior"))this.P.Tr="fixed"==c;(0,D.Mo)(this.P,
b);b=b.jb();for(var e,d=0;d<b.length;d++)if(c=b[d],e=c.getName(),"mapHierarchy"==e){c=c.jb();e=this.P.Me;for(var f=D.k,g=D.k,h=D.k,j=D.k,g=D.k,m=0;m<c.length;m++){var o=c[m];if("pointLayer"!=o.getName()){var f=o.o("layerName"),g=o.o("labelDisplay"),h=o.o("clientId"),j=o.o("labelType"),p=o.o("areaStyle");p&&this.dt.Cb(new D.K(p));(p=o.o("labelStyle"))&&this.dt.Cb(new D.K(p));this.Ov?g=new D.TC(this.P,f,h,g,j,this.P.Aa):(g=new D.UC(this.P,f,h,g,j,this.P.Aa),p=D.iD.Dka(e,f),h=this.U_(p),g.cn=h,(0,D.WC)(g,
p),p=D.iD.Cka(e,f),g.QB=p,f=D.iD.Mka(this.P.Me,f),g.je=f,g.PP=this.PP,g.QP=this.QP,g.OP=this.OP);g.uS=this.dt;g.yIa=this.Mta;if(p=o.o("animationOnLayerChange")){(o=o.o("animationDuration"))&&(o=(0,window.parseFloat)(o));if(!o||(0,window.isNaN)(o))o=1;g.fI(p);g.ao(o)}g&&this.P.Le.push(g)}}}else if("regionLayer"==e){if(e=c.o(D.hE))this.dt=new D.K(e);if(e=c.o("hoverStyle"))this.PP=new D.K(e);if(e=c.o("selectStyle"))this.QP=new D.K(e);if(e=c.o("disclosedStyle"))this.OP=new D.K(e)}else"markerStyle"==e?
(c=new D.K(c.o(D.hE)),this.P.yga=c):"basemap"==e&&this.P.Me=="$"+c.o("id")&&this.lY(c)};
D.C.ZI=function(b,c,d){var e=b.getElementsByTagName(D.yD);b=b.getElementsByTagName("legend");c&&(b&&b[0])&&this.jP(b[0]);for(b=0;b<e.length;b++){var f=e[b].o("clientId"),g=e[b].o("id"),h=(0,D.kE)(this.P,g);h?h instanceof D.UC&&(0,D.lD)(h):(h=e[b].o("showWith"))?h=(0,D.kE)(this.P,h):(h=new D.eD(this.P,this.P.Aa),this.P.Le.push(h));var f=new D.wD(this.P,h,f,this.P.Aa),j=e[b].o("selectionMode");"single"==j?f.Hs("s"):"multiple"==j&&f.Hs("m");if(j=e[b].o("animationDataChange")){var m=e[b].o("animationDuration");
m&&(m=(0,window.parseFloat)(m));if(!m||(0,window.isNaN)(m))m=1;f.fI(j);f.ao(m)}j=D.q;h instanceof D.UC&&(j=e[b].o("isolatedRowKey"));for(var m=[],o=[],p=this.Z2(e[b].getElementsByTagName("styles")),r=e[b].getElementsByTagName("row"),u=this.Y2(e[b],p),v=0;v<r.length;v++){var z=r[v].o("styleId"),A;a:{var F=h,E=f;A=g;var J=r[v],M=p[z],L=m,S=o,U=j,$=this.P.e,ya=J.o("rowKey"),ra=J.o("clientId"),z=J.o("id"),ua=D.k,Bb=M.getName();if("colorStyles"==Bb){if(U){if(U!=ya){A=D.q;break a}this.LF=z}F.nq[z]=D.t;
ua=new D.aD($,E,ya,ra,z);this.U2($,z,F,J,ua)}else if("graduatedSymbol"==Bb)ua=new D.bD($,E,ya,ra,z),this.V2($,M,A,J,ua);else if("image"==Bb){var ua=new D.QC($,E,ya,ra,z),M=$,lb=A,Ja=J,U=ua,ra=Ja.o("url"),Kb=D.q;if(lb=(0,D.lE)(this,lb,Ja,"cities"!=lb)){Kb=new D.kf(M,ra);U.bo(lb);U.Kd(Kb);var Db=D.k,Nd=D.k;if(Ja=Ja.o(D.hE))Ja=new D.K(Ja),(Db=Ja.v("width").substring(0,Ja.v("width").indexOf("px")))&&Kb.ha(Db),(Nd=Ja.v("height").substring(0,Ja.v("height").indexOf("px")))&&Kb.ua(Nd),Db!=D.q&&Nd!=D.q&&(Kb.da(lb.x-
Db/2),Kb.ta(lb.y-Nd/2),U.Xh(Db*Nd));(!Db||!Nd)&&D.Ip.Gj(M,ra,D.D.uj(U,U.UV))}}else if(ua=new D.LD($,E,ya,ra,z),Kb=$,U=J,M=ua,lb=Bb,ra=(0,D.lE)(this,A,U,"cities"!=A)){"statusMeterGauge"==lb?window.gauge=(0,D.mE)(Kb,D.q,D.q):"ledGauge"==lb?window.gauge=(0,D.Sy)(Kb,D.q,D.q):"dialGauge"==lb?window.gauge=(0,D.nE)(Kb,D.q,D.q):"ratingGauge"==lb&&(window.gauge=(0,D.oE)(Kb,D.q,D.q));M.bo(ra);M.Kd(window.gauge);lb=Kb=D.k;if(Kb=U.o(D.hE))lb=new D.K(Kb),Kb=lb.width?(0,window.parseInt)(lb.width.substring(0,lb.width.indexOf("px"))):
50,M.ha(Kb),lb=lb.height?(0,window.parseInt)(lb.height.substring(0,lb.height.indexOf("px"))):50,M.ua(lb),M.da(ra.x-Kb/2),M.ta(ra.y-lb/2);if(U=U.o("json"))M.pxa=U}if(M=ua.Da()){if(U=(0,window.parseInt)(J.o("rotation")))U=U*window.Math.PI/180,M.Zi(U),ra=ua.Td(),(0,D.jg)(M,ra.x-(ra.x*window.Math.cos(U)-ra.y*window.Math.sin(U)),ra.y-(ra.x*window.Math.sin(U)+ra.y*window.Math.cos(U)));z&&F instanceof D.UC&&(F.as[z]=D.t);U="true"==J.o("hasAction");if(ua.MR=U)U=J.o("action"),ua.vk=U;if(U=J.o("destination"))ra=
[],ra.destination=U,ra.targetFrame="_blank",ra.focusable=D.n,(0,D.ql)(M,ra);"true"==J.o("selected")&&L.push(ya);"true"==J.o("drilled")&&(S.push(J.o("id")),this.P.hF.push(ya));L=J.o("label");S="off";L?S="on":"colorStyles"==Bb&&(S=F.wH());!L&&(z&&"off"!=S)&&(L="long"==F.z1?F.jo[z][1]:F.jo[z][0]);if(L){ya=D.k;F.SU&&(ya=F.SU(z));var tc=D.k,tc=ya?new D.YC($,L,ya,S,E.nB,this.P.Fe):"colorStyles"!=Bb?new D.ph($,L,0,0):new D.YC($,L,D.q,S,E.nB,this.P.Fe);(E=J.o("labelPosition"))&&ua.Oc(E);E=new D.K;"colorStyles"==
Bb?E.Cb(F.uS):"graduatedSymbol"==Bb&&E.Cb(this.P.yga);(F=J.o("labelStyle"))&&E.Cb(new D.K(F));tc instanceof D.YC&&(E.v("color")||E.V("color",D.N.Vk(ua.zj())));tc.Ha(E)}ua.eo(tc);F=this.P.o0;"none"!=F&&(J=J.o("shortDesc"),"auto"==F&&(F=D.k,z&&(F="cities"==A||this.Ov?D.iD.Pka(this.P.Me,z):D.iD.kla(this.P.Me,A,z)),F&&(J=J?F+": "+J:F)),J&&ua.m8(J));A=ua}else A=D.q}A&&(z=A.Da(),z.Jg&&z.Jg(f.dc()&&!(A instanceof D.QC)),0<u.length&&A.x8(u),A instanceof D.aD?(0,D.xD)(f,A):(z=f,z.Ih.push(A),z.Aa.ja(A.Da(),
A)))}j&&this.LF&&(f.kxa=j,(0,D.hD)(h,this.LF));f.dc()&&0<m.length&&(f.TR=m);0<o.length&&(this.P.GF[h.Lf]=[f.wh(),o]);c||h.yj(f.wh())?h.H8(f,c,d):h.fh[f.wh()]=f}};D.C.jP=function(b){this.P.Ro=b};D.C.lY=function(b){b=b.jb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),d==D.yD?this.S2(c):d==D.zD&&this.T2(c)};
D.C.S2=function(b){var c=b.jb();b=b.o("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.o("source");e.width=d.o("width");e.height=d.o("height");var h=d.o("bidi");d=d.o("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}(0,D.XC)((0,D.kE)(this.P,b),f)};
D.C.T2=function(b){b=b.jb();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),d==D.AD&&(e[c.o("name")]=[c.o("x"),c.o("y")],f[c.o("name")]=[D.q,c.o("longLabel")]);D.iD.aW(this.P.Me,"cities",f,e,D.q,D.q,1)};D.C.U_=function(b){var c={},d=this.P.e,e;for(e in b)c[e]=new D.ef(d),(0,D.pE)(this,"colorStyles",this.dt,c[e]);return c};D.C.Z2=function(b){var c={};if(b&&0<b.length){b=b[0].jb();for(var d=0;d<b.length;d++){var e=b[d].o("id");c[e]=b[d]}}return c};
D.C.Y2=function(b,c){for(var d=b.getElementsByTagName("spb"),e=[],f=0;f<d.length;f++){var g=d[f].o("alignId"),h=(0,D.Bl)(d[f]),j;for(j in c)if(g==j){h=new D.sC(h.Kz(),h.Sh(),D.q,h.MC());break}e.push(h)}return e};D.lE=function(b,c,d,e){b=b.P.Me;var f=d.o("id");if(f)return e?D.iD.Bka(b,c,f):D.iD.Oka(b,f);c=(0,window.parseFloat)(d.o("x"));d=(0,window.parseFloat)(d.o("y"));return new D.G(c,d)};
D.gE.prototype.U2=function(b,c,d,e,f){if(d.cn[c]){c=new D.K(e.o(D.hE));b=new D.CD(b,this.P.Fe);var g=d.QP;e=d.OP;d=new D.ff(d.PP.v("border-color"),1,2);var h=new D.ff(g.v("-tr-inner-color"),1,1),g=new D.ff(g.v("-tr-outer-color"),1,4);b.$q(d,D.q).br(h,g);e&&(d=new D.ff(e.v("-tr-inner-color"),1,2),e=new D.ff(e.v("-tr-outer-color"),1,4),(0,D.DD)(b,d,e));f.Kd(b);(0,D.pE)(this,"colorStyles",c,b,f)}};
D.gE.prototype.V2=function(b,c,d,e,f){var g=D.q;if(d=(0,D.lE)(this,d,e,"cities"!=d)){if(g=e.o("source"))g=[g,e.o("sourceSelected"),e.o("sourceHover"),e.o("sourceHoverSelected")];else if((g=e.o("shapeType"))||(g="c"),!(0,D.FD)(g)){c=c.getElementsByTagName("markerDef");for(var h=0;h<c.length;h++)!this.Ada[g]&&c[h].o("id")==g&&(this.Ada[g]=D.Fo.aka(b,c[h]))}c=e.o("scaleX");c=(0,window.isNaN)(c)?1:(0,window.parseFloat)(c);var h=e.o("scaleY"),h=(0,window.isNaN)(h)?1:(0,window.parseFloat)(h),j=e.o("width"),
m=e.o("height"),j=!j||(0,window.isNaN)(j)?8:(0,window.parseInt)(j),m=!m||(0,window.isNaN)(m)?8:(0,window.parseInt)(m),g=new D.Vm(b,g,this.P.Gb,d.x-j*c/2,d.y-m*h/2,j,m,D.q,c,h);f.bo(d);f.Kd(g);f.Xh(j*c*m*h);if(b=e.o(D.hE))b=new D.K(b),(0,D.pE)(this,"graduatedSymbol",b,g,f)}};
D.pE=function(b,c,d,e,f){d||(d={});var g=d.v("pattern"),h=d.v("pattern-color"),j=d.v("background-color"),m=b.xfa||"alta"==b.P.Gb?D.t:d.v("gradient");j&&f?f.pn.push(j):h&&f&&f.pn.push(h);var o;o=d.v("opacity")?(0,window.parseFloat)(d.v("opacity")):1;f&&f.n8(j?j:h);if("graduatedSymbol"==c&&(0,D.FD)(e.Ga())){c=b.P.yga;f=d.v("border-style")?d.v("border-style"):c.v("border-style");if("none"!=f){var p=d.v("border-color")?d.v("border-color"):c.v("border-color");(d=d.v("border-width")?d.v("border-width"):
c.v("border-width"))&&(d=(0,window.parseFloat)(d.substring(0,d.indexOf("px"))));d=new D.ff(p,1,d);d.$i((0,D.dn)(f));b.P.Tr||(d.gd=D.n);e.Z(d)}"true"==m&&j?e.G(new D.GD.i5(j,e,o)):g?e.G(new D.nm(g,h,j)):j?e.la(j,o):e.la(c.v("background-color"),o)}else if("colorStyles"==c){if((m=d.v("border-color"))&&"transparent"!=m)d=new D.ff(m),b.P.Fe&&(d.gd=D.n),e.Z(d);g?(b=new D.nm(g,h,j),e.aia=b):j&&"transparent"!=j?e.la(j,o):e.G(D.q)}};
D.tD=function(b){this.Init(b)};D.D.l(D.tD,D.D,"DvtThematicMapJsonParser");D.C=D.tD.prototype;D.C.Init=function(b){this.P=b;this.Ov=D.t;this.dt=D.q;this.xfa=(0,D.wf)();this.yda={}};
D.C.parse=function(b){b.skin="alta";this.uY(b);var c=b.styleDefaults;this.dt=new D.K(c.areaStyle+c.labelStyle);this.P.ks=c;this.Ov&&(c=(new D.ul).parse(b.sourceXml))&&this.lY(c);for(var c=b.areaLayers,d=this.P.Me,e=0;e<c.length;e++){var f=D.nl.Cb(c[e],D.uD),g=f.layer;if(g){var h;f.areaStyle&&(0,D.mk)(this.dt,f.areaStyle);if(this.Ov)h=new D.TC(this.P,g,D.q,f.labelDisplay,f.labelType,this.P.Aa),(0,D.XC)(h,this.yda[g]);else{h=new D.UC(this.P,g,D.q,f.labelDisplay,f.labelType,this.P.Aa);var j=D.iD.Dka(d,
g),m=this.U_(j);h.cn=m;(0,D.WC)(h,j);j=D.iD.Cka(d,g);h.QB=j;g=D.iD.Mka(this.P.Me,g);h.je=g}h.uS=this.dt;h.fI("auto"==f.animationOnLayerChange?"alphaFade":f.animationOnLayerChange);h.ao(this.P.Qa());this.P.Le.push(h);f.areaDataLayer&&this.ZI([f.areaDataLayer],h,D.n);f.pointDataLayers&&this.ZI(f.pointDataLayers,h,D.t)}}this.ZI(b.pointDataLayers,D.q,D.t)};
D.C.uY=function(b){(0,D.Lp)(this.P,b);this.P.ao(b.animationDuration/1E3);this.P.KZ="auto"==b.animationOnDisplay?"alphaFade":b.animationOnDisplay;this.P.eca="auto"==b.animationOnMapChange?"alphaFade":b.animationOnMapChange;this.Ov=b.source!=D.q;var c=this.P,d=this.Ov?"$"+b.basemap:b.basemap;c.$P=c.Me&&c.Me!=d;c.Me=d;this.P.gK=b.controlPanelBehavior;this.P.jW("none");this.P.WR="auto"==b.initialZooming;this.P.Tr="fixed"==b.markerZoomBehavior;this.P.rC="auto"==b.panning;c=b.tooltipDisplay;"shortDesc"==
c?c="shortDescOnly":"labelAndShortDesc"==c&&(c="auto");this.P.o0=c;this.P.yz="auto"==b.zooming};
D.C.ZI=function(b,c,d){if(b)for(var e=0;e<b.length;e++){var f=D.nl.Cb(b[e],D.vD);c?c instanceof D.UC&&(0,D.lD)(c):(c=new D.eD(this.P,this.P.Aa),this.P.Le.push(c));var g=new D.wD(this.P,c,f.id,this.P.Aa),h=f.selectionMode;"single"==h?g.Hs("s"):"multiple"==h&&g.Hs("m");g.fI("auto"==f.animationOnDataChange?"alphaFade":f.animationOnDataChange);g.ao(this.P.Qa());var j=D.q;c instanceof D.UC&&(j=f.isolatedItem);var m=f.disclosedItems,h=[],o,p=f.areas;if(p)for(var r=0;r<p.length;r++){var u=p[r].location;
if(j)if(j!=p[r].id)continue;else o=u;m&&-1!=m.indexOf(p[r].id)&&h.push(u);if(u=this.U2(c,g,p[r])){if(g.dc()){var v=u.Da();v.Jg(D.n)}(0,D.xD)(g,u)}}if(m=f.markers)for(r=0;r<m.length;r++){u=m[r].location;if(d&&j)if(j!=m[r].id)continue;else o=u;if(u=this.V2(c,g,m[r],d))g.dc()&&(v=u.Da(),v.Jg(D.n)),p=g,p.Ih.push(u),p.Aa.ja(u.Da(),u)}o&&(g.kxa=j,(0,D.hD)(c,o));if((f=f.selection)&&0<f.length)g.TR=f;h&&0<h.length&&(this.P.GF[c.Lf]=[g.wh(),h]);c.fh[g.wh()]=g}};
D.C.lY=function(b){b=b.jb();for(var c,d,e=0;e<b.length;e++)c=b[e],d=c.getName(),d==D.yD?this.S2(c):d==D.zD&&this.T2(c)};D.C.S2=function(b){var c=b.jb();b=b.o("id");for(var d,e,f=[],g=0;g<c.length;g++)if(d=c[g],e=d.getName(),"image"==e){e={};e.source=d.o("source");e.width=d.o("width");e.height=d.o("height");var h=d.o("bidi");d=d.o("dir");e.dir="true"==h||"rtl"==d?"rtl":"ltr";f.push(e)}this.yda[b]=f};
D.C.T2=function(b){b=b.jb();for(var c,d,e={},f={},g=0;g<b.length;g++)c=b[g],d=c.getName(),d==D.AD&&(e[c.o("name")]=[c.o("x"),c.o("y")],f[c.o("name")]=[D.q,c.o("longLabel")]);D.iD.aW(this.P.Me,"cities",f,e,D.q,D.q,1)};D.C.U_=function(b){var c={},d=this.P.e,e;for(e in b)c[e]=new D.ef(d),(0,D.BD)(this,this.dt,c[e]);return c};
D.C.U2=function(b,c,d){var e=d.location;if(b.cn[e]&&d.color){b.nq[e]=D.t;var f=this.P.e,g=new D.CD(f,this.P.Fe);d=D.nl.Cb(d,this.P.ks.dataAreaDefaults);d.labelStyle||(d.labelStyle=this.P.ks.labelStyle);var h=new D.ff(d.hoverColor,1,2),j=new D.ff(d.selectedInnerColor,1,1),m=new D.ff(d.selectedOuterColor,1,4);g.$q(h,D.q).br(j,m);h=new D.ff(d.drilledInnerColor,1,2);j=new D.ff(d.drilledOuterColor,1,4);(0,D.DD)(g,h,j);e=new D.aD(f,c,d.id,d.clientId,e);e.Kd(g);(0,D.ED)(this,b,c,d,g,e,D.n);return e}return D.q};
D.C.V2=function(b,c,d,e){var f;f=d;var g=this.P.Me,h=f.location;f=h?e?D.iD.Bka(g,b.Lf,h):D.iD.Oka(g,h):D.Y.eGa(f.x,f.y,this.P.Me);if(!f)return D.q;g=this.P.e;window.dataObj=new D.bD(g,c,d.id,d.clientId,d.location);window.dataObj.bo(f);d=D.nl.Cb(d,this.P.ks.dataMarkerDefaults);(h=d.source)?h=[h,d.sourceSelected,d.sourceHover,d.sourceHoverSelected]:(h=d.shape)||(h="c");var j=d.scaleX;(0,window.isNaN)(j)&&(j=1);var m=d.scaleY;(0,window.isNaN)(m)&&(m=1);var o=d.width,p=d.height;if(!o||(0,window.isNaN)(o))o=
8;if(!p||(0,window.isNaN)(p))p=8;window.marker=new D.Vm(g,h,"alta",f.x-o*j/2,f.y-p*m/2,o,p,D.q,j,m);window.dataObj.Kd(window.marker);window.dataObj.Xh(o*j*p*m);window.dataObj.Oc(d.labelPosition);if(f=d.rotation)g=f*window.Math.PI/180,window.marker.Zi(g),f=window.dataObj.Td(),(0,D.jg)(window.marker,f.x-(f.x*window.Math.cos(g)-f.y*window.Math.sin(g)),f.y-(f.x*window.Math.sin(g)+f.y*window.Math.cos(g)));(0,D.ED)(this,b,c,d,window.marker,window.dataObj,e);return window.dataObj};
D.ED=function(b,c,d,e,f,g,h){var j=e.location;h&&"auto"==c.wH()&&(c.as[j]=D.t);e.action&&(g.MR=D.n,g.vk=e.action);if(j=e.destination){var m=[];m.destination=j;m.targetFrame="_blank";m.focusable=D.n;(0,D.ql)(f,m)}m=b.P.o0;if("none"!=m){j=e.shortDesc;if("auto"==m){var o;(m=e.location)&&(o=!h||b.Ov?D.iD.Pka(b.P.Me,m):D.iD.kla(b.P.Me,c.Lf,m));o&&(j=j?o+": "+j:o)}j&&g.m8(j)}o=new D.K;o.V("background-color",e.color);o.V("pattern",e.pattern);o.V("border-color",e.borderColor);o.V("border-style",e.borderStyle);
e.borderWidth&&o.V("border-width",e.borderWidth);o.V("opacity",e.opacity);(0,D.BD)(b,o,f,g);f=e.location;j=(o=e.label)?"on":"off";h&&(j=c.wH());if(!o&&h&&(g instanceof D.aD&&"off"!=j||!(g instanceof D.aD)&&"on"==j))o="long"==c.z1?c.jo[f][1]:c.jo[f][0];if(o){var p=b.P.e,p=g instanceof D.bD?new D.ph(p,o,0,0):new D.YC(p,o,c.SU?c.SU(f):D.q,j,d.nB,b.P.Fe);b=new D.K(e.labelStyle);p instanceof D.YC&&(b.v("color")||b.V("color",D.N.Vk(g.zj())));p.Ha(b)}g.eo(p)};
D.BD=function(b,c,d,e){c||(c={});var f=c.v("pattern"),g=c.v("background-color");e&&e.n8(g);if(d instanceof D.Vm&&(0,D.FD)(d.Ga())){"none"!=c.v("border-style")&&(e=new D.ff(c.v("border-color"),1,c.v("border-width")),b.P.Tr||(e.gd=D.n),e.$i((0,D.dn)(c.v("border-style"))),d.Z(e));var h=c.v("opacity");"true"==D.t&&g?d.G(new D.GD.i5(g,d,h)):f?d.G(new D.nm(f,g,"#FFFFFF")):g?d.la(g,h):d.la(c.v("background-color"),h)}else if(d instanceof D.ef){if((c=c.v("border-color"))&&"transparent"!=c)e=new D.ff(c),b.P.Fe&&
(e.gd=D.n),d.Z(e);f?(b=new D.nm(f,g,"#FFFFFF"),d.aia=b):"transparent"!=g?d.la(g,h):d.G(D.q)}};
D.Y={};D.D.l(D.Y,D.D,"DvtThematicMapProjections");D.Y.Yu=new D.H(0,0,800,500);D.Y.DP=6378206.4;D.Y.oZ=new D.H(500,200,200,200);D.Y.nZ=new D.H(163,-49,17,17);D.Y.gba=new D.H(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);D.Y.jba=new D.H(-0.8436866097568272,-0.7626456732012923,1.8336308036296942,1.5748427214611724);D.Y.kba=new D.H(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);
D.Y.vba=new D.H(-0.47944476148667076,-0.0014669405958800579,0.7364925893845453,0.6293972741802124);D.Y.Eba=new D.H(-0.6154469465354344,-0.24589767758847714,1.2448236795108683,1.2631535127174947);D.Y.Lba=new D.H(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);D.Y.iba=new D.H(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);D.Y.tba=new D.H(-24.543831069368586,-37.202500659225905,204.54283106936856,164.9634493690208);
D.Y.Dba=new D.H(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);D.Y.Pba=new D.H(-0.6154656300926513,0.0507209798775865,1.0153104799231851,0.966537441082997);D.Y.Qba=new D.H(-171.9,-62.6,349.8,150.8);D.Y.Yqa=new D.H(172,51,8,3);D.Y.Zqa=new D.H(-180,51,51,21);D.Y.Lra=new D.H(-178.5,18.9,35,11);D.Y.Msa=new D.H(-124.8,24.4,58,25.5);D.Y.hba=new D.H(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);
D.Y.zba=new D.H(-160.23606872558594,18.91549301147461,5.4374847412109375,3.3189010620117188);D.Y.Oba=new D.H(-2386803.25,-1183550.5,4514111,2908402);D.Y.lZ=new D.H(165,400,100,100);D.Y.hZ=new D.H(-75,350,240,150);D.Y.ql=[[1,0],[0.9986,0.0314],[0.9954,0.0629],[0.99,0.0943],[0.9822,0.1258],[0.973,0.1572],[0.96,0.1887],[0.9427,0.2201],[0.9216,0.2515],[0.8962,0.2826],[0.8679,0.3132],[0.835,0.3433],[0.7986,0.3726],[0.7597,0.4008],[0.6732,0.4532],[0.6213,0.4765],[0.5722,0.4951],[0.5322,0.5072]];
D.Y.eGa=function(b,c,d){var e;switch(d){case "africa":e=D.Y.Fv(D.Y.gba,D.Y.JK(b,c));break;case "asia":e=D.Y.Fv(D.Y.jba,D.Y.AR(40,95,20,60,b,c),D.Y.eh(5));break;case "australia":e=D.Y.Ova(b,c);break;case "europe":e=D.Y.Fv(D.Y.vba,D.Y.AR(35,25,40,65,b,c),D.Y.eh(10));break;case "northAmerica":e=D.Y.Fv(D.Y.Eba,D.Y.AR(23,-96,20,60,b,c));break;case "southAmerica":e=D.Y.Fv(D.Y.Lba,new D.G(b,c),D.Y.eh(5));break;case "apac":e=D.Y.Fv(D.Y.iba,D.Y.JK(b,c));break;case "emea":e=D.Y.Fv(D.Y.tba,D.Y.JK(b,c));break;
case "latinAmerica":e=D.Y.Fv(D.Y.Dba,new D.G(b,c));break;case "usaAndCanada":e=D.Y.Fv(D.Y.Pba,D.Y.AR(23,-96,20,60,b,c));break;case "worldRegions":e=D.Y.Mea(b,c);break;case "usa":e=D.Y.uwa(b,c);break;case "world":e=D.Y.Mea(b,c)}return e?new D.G(10*e.x,10*e.y):new D.G(b,c)};
D.Y.uwa=function(b,c){var d;return(0,D.yA)(D.Y.Yqa,b,c)||(0,D.yA)(D.Y.Zqa,b,c)?(d=D.Y.xn(D.Y.hba,D.Y.hZ),D.Y.vJ(d,D.Y.JK(b,c))):(0,D.yA)(D.Y.Lra,b,c)?(d=D.Y.xn(D.Y.zba,D.Y.lZ),D.Y.vJ(d,new D.G(b,c))):(0,D.yA)(D.Y.Msa,b,c)?(d=D.Y.xn(D.Y.Oba,D.Y.Yu),D.Y.vJ(d,D.Y.lwa(new D.G(-95,36),b,c))):new D.G(b,c)};D.Y.Mea=function(b,c){var d=D.Y.xn(D.Y.Qba,D.Y.Yu);return D.Y.vJ(d,D.Y.owa(b,c))};
D.Y.Ova=function(b,c){var d;d=(0,D.yA)(D.Y.nZ,b,c)?D.Y.xn(D.Y.nZ,D.Y.oZ):D.Y.xn(D.Y.kba,D.Y.Yu);return D.Y.vJ(d,D.Y.JK(b,c))};D.Y.Fv=function(b,c,d){b=D.Y.xn(b,D.Y.Yu);if(d){var e=new D.rh;e.rotate(d);b=D.Y.dda(b,e)}return(0,D.rq)(b,c)};
D.Y.AR=function(b,c,d,e,f,g){c=D.Y.eh(c);b=D.Y.eh(b);d=D.Y.eh(d);e=D.Y.eh(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;f=e*(D.Y.eh(f)-c);g=d-2*e*window.Math.sin(D.Y.eh(g));g=window.Math.sqrt(g)/e;return new D.G(g*window.Math.sin(f),b-g*window.Math.cos(f))};D.Y.JK=function(b,c){var d=window.Math.log(window.Math.tan(0.25*window.Math.PI+0.5*D.Y.eh(c)));return new D.G(b,D.Y.tI(d))};
D.Y.lwa=function(b,c,d){c=D.Y.eh(c);d=D.Y.eh(d);var e=D.Y.eh(b.x);b=D.Y.eh(b.y);return new D.G(window.Math.cos(d)*window.Math.sin(c-e)*D.Y.DP,(window.Math.cos(b)*window.Math.sin(d)-window.Math.sin(b)*window.Math.cos(d)*window.Math.cos(c-e))*D.Y.DP)};
D.Y.owa=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.Y.ql.length-1&&(d=D.Y.ql.length-2);var e=(window.Math.abs(c)-5*d)/5,f=b*(D.Y.ql[d][0]+e*(D.Y.ql[d+1][0]-D.Y.ql[d][0])),d=D.Y.ql[d][1]+e*(D.Y.ql[d+1][1]-D.Y.ql[d][1]);0>c&&(d*=-1);return new D.G(f,180*d)};D.Y.vJ=function(b,c){return new D.G(c.x*b.Qc+b.Bb,c.y*b.Ke+b.yb)};D.Y.dda=function(b,c){var d=b.Qc,e=b.Ke;return new D.rh(c.Qc*d,c.cg*d,c.Af*e,c.Ke*e,b.Bb+c.Bb*d,b.yb+c.yb*e)};
D.Y.xn=function(b,c){var d=c.x,e=c.y,f=b.g,g=b.j,h=0,h=c.g/f,j=c.j/g,h=h<=j?h:j,d=d-b.x*h,e=e+b.y*h,d=d+(c.g-f*h)/2,e=e+(c.j-(c.j-g*h)/2);return new D.rh(h,0,0,-h,d,e)};D.Y.eh=function(b){return b*(window.Math.PI/180)};D.Y.tI=function(b){return b*(180/window.Math.PI)};
D.Y.eKa=function(b,c,d){var e;b/=10;c/=10;switch(d){case "africa":e=D.Y.Gv(D.Y.gba,new D.G(b,c));e=D.Y.IK(e.x,e.y);break;case "asia":e=D.Y.Gv(D.Y.jba,new D.G(b,c),D.Y.eh(5));e=D.Y.DR(40,95,20,60,e.x,e.y);break;case "australia":e=D.Y.awa(b,c);break;case "europe":e=D.Y.Gv(D.Y.vba,new D.G(b,c),D.Y.eh(10));e=D.Y.DR(35,25,40,65,e.x,e.y);break;case "northAmerica":e=D.Y.Gv(D.Y.Eba,new D.G(b,c));e=D.Y.DR(23,-96,20,60,e.x,e.y);break;case "southAmerica":e=D.Y.Gv(D.Y.Lba,new D.G(b,c),D.Y.eh(5));break;case "apac":e=
D.Y.Gv(D.Y.iba,new D.G(b,c));e=D.Y.IK(e.x,e.y);break;case "emea":e=D.Y.Gv(D.Y.tba,new D.G(b,c));e=D.Y.IK(e.x,e.y);break;case "latinAmerica":e=D.Y.Gv(D.Y.Dba,new D.G(b,c));break;case "usaAndCanada":e=D.Y.Gv(D.Y.Pba,new D.G(b,c));e=D.Y.DR(23,-96,20,60,e.x,e.y);break;case "worldRegions":e=D.Y.xea(b,c);break;case "usa":e=D.Y.dwa(b,c);break;case "world":e=D.Y.xea(b,c)}return e?e:new D.G(b,c)};
D.Y.dwa=function(b,c){var d;return(0,D.yA)(D.Y.hZ,b,c)?(d=D.Y.xn(D.Y.hba,D.Y.hZ),d.qu(),d=(0,D.rq)(d,new D.G(b,c)),D.Y.IK(d.x,d.y)):(0,D.yA)(D.Y.lZ,b,c)?(d=D.Y.xn(D.Y.zba,D.Y.lZ),d.qu(),(0,D.rq)(d,new D.G(b,c))):(0,D.yA)(D.Y.Yu,b,c)?(d=D.Y.xn(D.Y.Oba,D.Y.Yu),d.qu(),d=(0,D.rq)(d,new D.G(b,c)),D.Y.bwa(new D.G(-95,36),d.x,d.y)):new D.G(b,c)};D.Y.xea=function(b,c){var d=D.Y.xn(D.Y.Qba,D.Y.Yu);d.qu();d=(0,D.rq)(d,new D.G(b,c));return D.Y.cwa(d.x,d.y)};
D.Y.awa=function(b,c){var d;d=(0,D.yA)(D.Y.oZ,b,c)?D.Y.xn(D.Y.nZ,D.Y.oZ):D.Y.xn(D.Y.kba,D.Y.Yu);d.qu();d=(0,D.rq)(d,new D.G(b,c));return D.Y.IK(d.x,d.y)};D.Y.Gv=function(b,c,d){b=D.Y.xn(b,D.Y.Yu);if(d){var e=new D.rh;e.rotate(d);b=D.Y.dda(b,e)}b.qu();return(0,D.rq)(b,c)};
D.Y.DR=function(b,c,d,e,f,g){c=D.Y.eh(c);b=D.Y.eh(b);d=D.Y.eh(d);e=D.Y.eh(e);e=0.5*(window.Math.sin(d)+window.Math.sin(e));d=window.Math.pow(window.Math.cos(d),2)+2*e*window.Math.sin(d);b=d-2*e*window.Math.sin(b);b=window.Math.sqrt(b)/e;var h=window.Math.sqrt(f*f+(b-g)*(b-g));return new D.G(D.Y.tI(c+window.Math.atan(f/(b-g))/e),D.Y.tI(window.Math.asin((d-h*h*e*e)/(2*e))))};D.Y.IK=function(b,c){return new D.G(b,D.Y.tI(2*window.Math.atan(window.Math.exp(D.Y.eh(c)))-0.5*window.Math.PI))};
D.Y.bwa=function(b,c,d){c/=D.Y.DP;d/=D.Y.DP;var e=D.Y.eh(b.y),f=window.Math.sqrt(c*c+d*d),g=window.Math.asin(f);return new D.G(D.Y.tI(D.Y.eh(b.x)+window.Math.atan(c*window.Math.sin(g)/(f*window.Math.cos(e)*window.Math.cos(g)-d*window.Math.sin(e)*window.Math.sin(g)))),D.Y.tI(window.Math.asin(window.Math.cos(g)*window.Math.sin(e)+d*window.Math.sin(g)*window.Math.cos(e)/f)))};
D.Y.cwa=function(b,c){var d=window.Math.floor(window.Math.abs(c)/5);d>=D.Y.ql.length-1&&(d=D.Y.ql.length-2);var e=(window.Math.abs(c/180)-D.Y.ql[d][1])/(D.Y.ql[d+1][1]-D.Y.ql[d][1]),f=5*e+5*d,d=b/(D.Y.ql[d][0]+e*(D.Y.ql[d+1][0]-D.Y.ql[d][0]));0>c&&(f*=-1);return new D.G(d,f)};
D.VD=function(b,c,d,e,f,g,h){this.Init(b,c,d,e,f,g,h)};D.D.l(D.VD,D.WD,"DvtMapControlButton");
D.VD.prototype.Init=function(b,c,d,e,f,g,h){D.VD.q.Init.call(this,b,e,g);this.q_=f;this.rb=c;this.sa=h;(0,D.Lh)(this.rb,this.wpa,this);this.rb.setCursor("pointer");b=new D.Ek(this,D.q,D.q,D.q,D.q,D.q,0==this.q_?(0,D.wg)(this.ed,"CONTROL_PANEL_DRILLUP"):1==this.q_?(0,D.wg)(this.ed,"CONTROL_PANEL_DRILLDOWN"):2==this.q_?(0,D.wg)(this.ed,"CONTROL_PANEL_RESET"):D.q);this.sa.ja(this.rb,b);this.k(this.rb);this.sga=d;this.qfa=D.n};
D.VD.prototype.ah=function(b){this.B(b?1:0.4);this.rb.setCursor(b?"pointer":D.q);this.qfa=b;this.rb.ah(b);(0,D.XD)(this.rb)};D.VD.prototype.wpa=function(b){(0,D.Uh)(b);this.qfa&&this.sga&&this.sga()};
D.YD=function(b,c,d){this.Init(b,c,d)};D.D.l(D.YD,D.Ap,"DvtThematicMapControlPanel");D.YD.prototype.Init=function(b,c,d){D.YD.q.Init.call(this,b,c,d);this.Ik=c.Ik;this.yl=(0,D.lh)(c);this.xva=D.D.uj(c,c.t5);this.vva=D.D.uj(c,c.wU);this.rza=D.D.uj(c,c.d8);this.fF=this.gF=this.via=D.q;this.Pda=this.Oda=D.t;this.D=c.ts()};D.ZD=function(b,c){b.Oda=c;b.fF&&b.fF.ah(c)};D.$D=function(b,c){b.Pda=c;b.gF&&b.gF.ah(c)};
D.YD.prototype.cJ=function(b){if(this.Ik&&"none"!=this.Ik){var c=(0,D.zk)(this.D,"buttonWidth",0);this.via=D.R.mBa(this.e,this.rza,this.ba,this.ed,this.yl,this.sa,this.D);b.k(this.via);this.fF=D.R.aBa(this.e,this.vva,this.ba,this.ed,this.yl,this.sa,this.D);this.fF.F(c);this.fF.ah(this.Oda);b.k(this.fF);this.gF=D.R.bBa(this.e,this.xva,this.ba,this.ed,this.yl,this.sa,this.D);this.gF.F(2*c);this.gF.ah(this.Pda);b.k(this.gF)}};
});